### ISSUE TITLE
Lara Croft and the Guardian of Light: Strange rectangle on the screen

### ISSUE THREAD

**Issue by jcapsule** [RPCS3/rpcs3#5513] opened 2019-01-06 10:43 UTC
Lara Croft and the Guardian of Light [NPUB30225]

This game shows a rectangle at top left of the screen only for **Vulkan**.

It start to happen on the commit "rsx: Improve ARGB8->D24S8 casting".

![capture](https://user-images.githubusercontent.com/15172818/50735006-a5c2f380-119f-11e9-86cd-2124cf5603b8.PNG)

[RPCS3.log.gz](https://github.com/RPCS3/rpcs3/files/2730362/RPCS3.log.gz)

**Comment by kd-11** [comment] 2019-01-06 14:50
Need a renderdoc capture of this vs ogl if possible.

**Comment by kd-11** [comment] 2019-01-25 12:16
Retest

**Comment by jcapsule** [comment] 2019-01-25 21:21
The issue still appears with the latest version, only with Vulkan.

![capture](https://user-images.githubusercontent.com/15172818/51773512-f6ff3c80-20e6-11e9-85a1-05d35e49c10a.PNG)

**Comment by kd-11** [comment] 2019-02-05 09:34
Provide renderdocs for this (Renderdoc 1.2, before and after)

**Comment by kd-11** [comment] 2019-02-05 09:40
Tracking as a duplicate of https://github.com/RPCS3/rpcs3/issues/5514

**Closed by kd-11** 2019-02-05 09:40 UTC

**Comment by jcapsule** [comment] 2019-02-07 00:47
Sorry, I hope the generated renderdocs are ok:

The issue starts to appear between the following versions:

VK - Before - **Work**: rpcs3-v0.0.5-e6475e05_win64
https://mega.nz/#!SXhniYKI!PM7Sk5UGsKyJjYcP_8WVh6fjyeLJ7FOjkOwvrbqI6SY

VK - After - **Not Work**: rpcs3-v0.0.5-156179f4_win64
https://mega.nz/#!3bglXSKC!mgglVVWBKMSHI3QckXEE1O4Hj8KnlN--6fKREClKPAE

PR: "vk: Fix usage of VK_IMAGE_LAYOUT_GENERAL": rpcs3-v0.0.6-027d9e7e_win64

VK - **Not Work**
https://mega.nz/#!yHgRxaTQ!ssERCktIV8ohLco4YjcZqfGgoHKOwQW60WvkJAay8IU

**Comment by kd-11** [comment] 2019-02-07 06:46
I tested this game personally and it works with the PR build.
