### ISSUE TITLE
[Bug] "Resolution Scale" setting affecting "Default Resolution" setting at 1080p

### ISSUE THREAD

**Issue by Rex000** [RPCS3/rpcs3#13376] opened 2023-02-08 20:21 UTC
### Quick summary

"Default Resolution" description states that it's setting will be ignored if the "Resolution Scale" is set to anything other than 100%. 

"Resolution Scale" description states that its base resolution will always be 1280x720.

This doesn't seem to be the case in practical, however.

### Details

If you keep Default Resolution to the recommended 1280x720, then put Resolution Scale to 200%, the game will be rendered at 2560x1440, which is an expected behavior.

However, if you set Default Resolution to 1920x1080 and keep Resolution Scale to 200%, now the game will be rendered at 3840x2160, which basically means that Resolution Scale is now doing a multiple of 1920x1080 instead of 1280x720.

### Attach a log file

Not needed(?)

**Comment by kd-11** [comment] 2023-02-08 21:36
> However, if you set Default Resolution to 1920x1080 and keep Resolution Scale to 200%, now the game will be rendered at 3840x2160, which basically means that Resolution Scale is now doing a multiple of 1920x1080 instead of 1280x720.

This is incorrect. 1080p is the "TV resolution" here, not game resolution. The game will render 720p and upscale to 1080p bilinearly. The resolution setting refers to the virtual TV, not render resolution, but it is difficult to communicate this fact with end users as that's not how PC games work. Now there are a handful of titles that will use a different base resolution when the TV supports 1080p, but these are a handful and the games almost never actually run at 1080p. Its going to be something in between usually sub-900p with some features removed (e.g worse shadows, etc) to achieve the higher resolution.

**Comment by Rex000** [comment] 2023-02-09 00:01
I understand what you're saying but I'm not sure if this is related to that. Following is an example of a game:

Default Resolution=1280x720; Resolution Scale=200%
Result=2560x1440 at fullscreen
![NPUB30226_screenshot_2023_02_09_04_44_22](https://user-images.githubusercontent.com/28770012/217678809-30217d85-d939-4285-9f1c-17df37d27f56.png)


Default Resolution=1920x1080; Resolution Scale=200%
Result=3840x2160 at fullscreen
![NPUB30226_screenshot_2023_02_09_04_50_12](https://user-images.githubusercontent.com/28770012/217678831-f00fd98d-bdce-493d-8180-2d0813ef1796.png)

What I'm trying to say here is that the result should not be different if I understood the descriptions correctly.

**Comment by kd-11** [comment] 2023-02-09 00:11
That's one of the simple games that I mentioned. Try with AAA. The internal resolution will not match the TV resolution.
So we should just use the game's real resolution as a base then. However such a concept does not exist on PS3 and all modern features like dynamic resolution are in play. The game will use the resolution it wants ingame and that is dynamic. The only common factor we found is that the vast majority of games run at around 720p which is why we use it as the base of approximation. This means we're sometimes incorrect, but using the TV resolution would be even worse.

**Comment by Rex000** [comment] 2023-02-09 00:30
Here is God of War. Same thing.

Default Resolution=1280x720; Resolution Scale=200%
Result=2560x1440 at fullscreen
![BCUS98229_screenshot_2023_02_09_05_21_54](https://user-images.githubusercontent.com/28770012/217683269-2b668332-5ada-42c3-8bea-78dd3f66c60c.png)

Default Resolution=1920x1080; Resolution Scale=200%
Result=3840x2160 at fullscreen
![BCUS98229_screenshot_2023_02_09_05_26_48](https://user-images.githubusercontent.com/28770012/217683296-272552d9-8ec4-406a-8741-b78265dffbbd.png)

**Comment by Asinin3** [comment] 2023-02-09 08:44
God of War 1 is a PS2 game, its not a AAA PS3 title. The way we have it now is accurate for most titles aside from anything basic or ps2 ports.

**Comment by kd-11** [comment] 2023-02-09 09:48
> Here is God of War. Same thing.
> 
> Default Resolution=1280x720; Resolution Scale=200% Result=2560x1440 at fullscreen ![BCUS98229_screenshot_2023_02_09_05_21_54](https://user-images.githubusercontent.com/28770012/217683269-2b668332-5ada-42c3-8bea-78dd3f66c60c.png)
> 
> Default Resolution=1920x1080; Resolution Scale=200% Result=3840x2160 at fullscreen ![BCUS98229_screenshot_2023_02_09_05_26_48](https://user-images.githubusercontent.com/28770012/217683296-272552d9-8ec4-406a-8741-b78265dffbbd.png)

Anecdotal. As I said, it happens with very light games. Try this with tlou and uncharted gow3 demons souls, RDR etc. Many heavy games don't even reach 720p.

**Comment by Rex000** [comment] 2023-02-09 18:28
How can one tell which game is light or heavy? There is only like a handful of these PS3 exclusives. Are these the only AAA games a PS3 has?

**Comment by RainbowCookie32** [comment] 2023-02-09 18:49
Using 3D games developed *for* the PS3 (not ports/remasters) is probably a good start.

**Comment by Rex000** [comment] 2023-02-09 18:54
Like I said, that's only a handful of games, and only one of them has a playable status.

**Comment by RainbowCookie32** [comment] 2023-02-09 18:55
There are a lot of games like that on the ps3 library, and whether or not they are playable doesn't affect what they do with resolution anyways

**Comment by Megamouse** [comment] 2023-02-09 18:57
duplicate of #12831

**Comment by Rex000** [comment] 2023-02-09 18:57
Is there a list somewhere for games that qualify to be tested here? Because I don't see a point building a strategy around a handful of games that are not even playable.

**Closed by Megamouse** 2023-02-09 18:57 UTC
