### ISSUE TITLE
Super Robot Wars OG The Moon Dwellers BLJS10335 HDD Coruption error 

### ISSUE THREAD

**Issue by Wizzy2018** [RPCS3/rpcs3#6588] opened 2019-09-19 13:03 UTC
I just found a issue with this game.On first start up of a game everything goes well game boots playable all fine.Problem starts on second startup of game
On first startup game creates a HDD data and after it finishes all fine
On second startup we have that data on HDD already but when a game boot up it says HDD data corupted please reinstall.
A solution for this is to go dev-hdd0-game folder and delete a folder called BLJS10335 that force a game to do again a HDD data install and a game works again fine.
Only i need do it every 2nd startup cuz data gets corrupted.
If someone of Dev can do some little fix it will be very helpfull.
And i forget to say i have a Disk version of this game idk is my way works for PKG version of game

**Comment by AniLeo** [comment] 2020-04-10 09:39
Closing as duplicate of #2532
Please discuss there

**Closed by AniLeo** 2020-04-10 09:39 UTC
