### ISSUE TITLE
hle: Not enough space, negative space needed

### ISSUE THREAD

**Issue by uaqlover** [RPCS3/rpcs3#7084] opened 2019-12-12 22:06 UTC
![FPS_ 3032 85 _ Vulkan _ 0 0 7-9219 _ Fuel Overdose  NPEB00876  12_12_2019 2_05_01 PM](https://user-images.githubusercontent.com/45731484/70752953-8f46e580-1ce8-11ea-9944-d9f58de638c8.png)

[RPCS3.log.gz](https://github.com/RPCS3/rpcs3/files/3958004/RPCS3.log.gz)

**Comment by elad335** [comment] 2019-12-13 02:15
Test and upload log with #7087

**Comment by uaqlover** [comment] 2019-12-13 14:51
still the same

here the log file 

[RPCS3.log.gz](https://github.com/RPCS3/rpcs3/files/3961309/RPCS3.log.gz)

**Comment by uaqlover** [comment] 2020-02-03 02:08
now game close it self RPCS3 v0.0.8-9492-7f4e546f Alpha

[RPCS3 over.log.gz](https://github.com/RPCS3/rpcs3/files/4145962/RPCS3.over.log.gz)

**Comment by digitaldude555** [comment] 2020-02-22 12:42
[RPCS3.log](https://github.com/RPCS3/rpcs3/files/4239359/RPCS3.log)
Now it freezes at 100% loading, that error doesnt show up anymore.

**Comment by Artins90** [comment] 2020-02-27 06:01
I am not sure if it's the same issue but Lollipop chainsaw shows a "not enough available space" message with a positive value. The emulator becomes unresponsive after pressing X. 

<img width="1337" alt="Capture" src="https://user-images.githubusercontent.com/28777957/75416567-da0eeb80-592e-11ea-99c7-6e18549a74de.PNG">
[RPCS3.log.gz](https://github.com/RPCS3/rpcs3/files/4259707/RPCS3.log.gz)

**Comment by Artins90** [comment] 2020-09-20 15:18
This was fixed by #8799  
https://github.com/RPCS3/rpcs3/issues/3506#issuecomment-695099840

**Comment by AniLeo** [comment] 2020-09-20 15:31
Closing as reported fixed, ping if you can still reproduce with master

**Closed by AniLeo** 2020-09-20 15:31 UTC
Labels: Bug, Firmware: HLE

**Comment by RempelOliveira** [comment] 2021-01-14 01:01
When converting the NPUA80637 psn game to disk using the PSN LIBERATOR, I get this message:
![image](https://user-images.githubusercontent.com/6107887/104530387-9c6c8d00-55ea-11eb-9b18-452f85b09def.png)

Partial log:
```
U {PPU[0x1000000] Thread (main_thread) [0x0120061c]} sys_prx TODO: _sys_prx_register_module()
U {PPU[0x1000000] Thread (main_thread) [0x011fff0c]} sys_prx TODO: _sys_prx_get_module_id_by_name(name=“cellLibprof”, flags=0, pOpt=*0x0)
E {PPU[0x1000000] Thread (main_thread) [0x011fff0c]} SYS: '_sys_prx_get_module_id_by_name' failed with 0x8001112e : CELL_PRX_ERROR_UNKNOWN_MODULE [1]
E {PPU[0x1000000] Thread (main_thread) [0x012c2090]} SYS: 'sys_fs_open' failed with 0x80010006 : CELL_ENOENT, “/app_home//dev_bdvd/PS3_GAME/USRDIR/data/coo/config/SurroundReverb.ini” [1]
S {PPU[0x1000000] Thread (main_thread) [0x012009ac]} ppu_loader: PRX library hash: PRX-ce1292a0c69a33f3073f15e7a86b240baac90136 (<- 0)
S {SPUW.1} SPU: New block compiled successfully
S {PPU[0x1000000] Thread (main_thread) [0x012009ac]} PPU: LLVM: Loaded module v3-kusa-XPMH8ztYKnZCkeMcGCePPX-00000G-skylake.obj
S {PPU[0x1000000] Thread (main_thread) [0x012009ac]} sys_prx: Loaded module: “/dev_flash/sys/external/libpamf.sprx” (id=0x23007100)
E {PPU[0x1000010] Thread (movie-audio-dispatch) [0x011f54ec]} SYS: '_sys_lwmutex_lock' failed with 0x80010005 : CELL_ESRCH [1]
E {PPU[0x1000010] Thread (movie-audio-dispatch) [0x011f54ec]} SYS: '_sys_lwmutex_lock' failed with 0x80010005 : CELL_ESRCH [2]
E {PPU[0x1000010] Thread (movie-audio-dispatch) [0x011f54ec]} SYS: '_sys_lwmutex_lock' failed with 0x80010005 : CELL_ESRCH [3]
S {PPU[0x1000000] Thread (main_thread) [0x012009ac]} ppu_loader: PRX library hash: PRX-631eaf1054d114d76722b2c2b12a494e79d05fdc (<- 0)
S {PPU[0x1000000] Thread (main_thread) [0x012009ac]} PPU: LLVM: Loaded module v3-kusa-Ugpy776JMwx9TjiTsYUVuT-00000G-skylake.obj
S {PPU[0x1000000] Thread (main_thread) [0x012009ac]} PPU: LLVM: Loaded module v3-kusa-bfwtN13iYk934dxr4yUoyj-00000G-skylake.obj
S {PPU[0x1000000] Thread (main_thread) [0x012009ac]} sys_prx: Loaded module: “/dev_flash/sys/external/libsail.sprx” (id=0x23007200)
U {PPU[0x1000000] Thread (main_thread) [0x013241c4]} sys_ss TODO: sys_ss_access_control_engine(pkg_id=0x1, a2=0x1, a3=0xd01000e8)
E {PPU[0x1000000] Thread (main_thread) [0x013241c4]} SYS: 'sys_ss_access_control_engine' failed with 0x80010003 : CELL_ENOSYS [2]
E {PPU[0x1000000] Thread (main_thread) [HLE:0x00fd0f14, LR:0x0024c078]} SYS: 'cellGameBootCheck' failed with 0x8002cb23 : CELL_GAME_ERROR_BUSY [1]
```

RPCS3 Version: 0.0.14-11569-6cf73fad Alpha

Can someone help me?

**Comment by AniLeo** [comment] 2021-01-14 01:03
You're not supposed to convert PSN games to disc.

**Comment by RempelOliveira** [comment] 2021-01-14 01:10
@AniLeo Why not? I already converted several and this is the first one that I had this problem.

**Comment by AniLeo** [comment] 2021-01-14 01:16
Because things work differently between PSN and Disc games internally, you can't just change a few things and expect it to work correctly as a Disc game.

This is unsupported, and just a terrible idea, both in a preservation perspective as well as a compatibility perspective.

**Comment by AniLeo** [comment] 2021-01-14 01:24
Both points I mentioned are objective, not subjective.

**Comment by RempelOliveira** [comment] 2021-01-14 01:35
The conversion output is identical to the installation in dev_hdd0 / game, except for the creation of the PS3_DISC.SFB file, if I just move these files to the installation directory, the game works, the application is not able to interpret this for this case specific, other games worked correctly. If the intention is not to support this, it may just be a lack of interest, as it does not appear to be a technical impediment.

**Comment by AniLeo** [comment] 2021-01-14 01:41
No. Games that have both versions usually share an identical executable, so they can decide whether they are PSN and Disc games by properties like the ones in PARAM.SFO. This is not guaranteed to work, as there are many games that don't share an executable.

If you want to preserve digital games, the correct way to do so is by preserving the PKG files together with their RAP licenses (see No-Intro for digital game preseration and Redump for disc game preservation). 

By "preserving" games the wrong way you're not only not helping but also actively harming the preservation community by introducing broken copies / broken methods of archival and tainting previous work.

**Comment by RempelOliveira** [comment] 2021-01-14 11:30
@AniLeo

1. Is the reverse process also considered bad (disk to pkg)?

2. What would be the recommended method for my games to behave like roms from other emulators?

For example, I would like to have only one source of files, both for backup and to be read by the emulator, saving them in individual directories, such as:

roms / ps3 / game-one / ...
roms / ps3 / game-two / ...

PS: In terms of emulation, personally I think it is bad to have to store the game for bakcup separately from the installed game, these are two fonts with large sizes.

**Comment by AniLeo** [comment] 2021-01-14 11:47
1. Yes because
- It will install a disc game as if it was a digital game. Disc games are supposed to be mounted and read-only. This can also cause problems such as a game trying to use the same path to install game data and overwrite itself since it doesn't expect itself to be there.
- As far as preservation goes also yes, because it's an irreversible process (an example of a reversible process is converting from encrypted ISO to decrypted ISO and vice-versa), meaning you can't convert back and get an ISO with the same checksum because some information is lost that PKG headers don't have the ability to store.

2. Modern consoles are different from older consoles in terms of game media. While on older consoles everything is physical and mostly read-only, now you have digital titles as well. And digital titles come in installers, so you preserve them instead.

You can't get digital games and disc games to behave the same because that's how PS3 was made, and from the nature that one is a read only media and the other is a read/write media. You can perhaps choose whether you want to have your library be disc only or digital only.

**Comment by RempelOliveira** [comment] 2021-01-14 13:48
Okay, thanks for the replies, especially for the ones that were answered with a technical approach.

One more question: How can I contribute to the status of the games? If a game is not listed on the compatibility list, how can I include it?
