### ISSUE TITLE
rpcs3-v0.0.6-8180-f90f68d1_linux64.AppImage core generated aborted

### ISSUE THREAD

**Issue by crack-keys** [RPCS3/rpcs3#6049] opened 2019-06-02 15:31 UTC
aries@aries:~$ '/home/aries/Escritorio/rpcs3-v0.0.6-8180-f90f68d1_linux64.AppImage' 
terminate called after throwing an instance of 'std::runtime_error'
  what():  Unknown system error: 20.
Abortado (`core' generado)

ubuntu 18.04
memory RAM 8Gb
processor Q6600
nvidia geforce gt-710 2Gb RAM

**Comment by AniLeo** [comment] 2019-06-02 15:40
Can not reproduce, ran cube properly.

**Comment by crack-keys** [comment] 2019-06-02 17:22
![Captura de pantalla_2019-06-02_19-18-14](https://user-images.githubusercontent.com/42444573/58764737-3f35dc00-856b-11e9-83b0-0276f3c3e4a3.png)


same mistake
v. rpcs3-v0.0.6-8180-f90f68d1_linux64.AppImage
v. rpcs3-v0.0.6-8179-cafa4521_linux64.AppImage



same mistake
aries @ aries: ~ $ '/home/aries/Escritorio/rpcs3-v0.0.6-8180-f90f68d1_linux64.AppImage' 
termina después de lanzar una instancia de 'std :: runtime_error' 
what (): Error de sistema desconocido: 20. 
Abortado (`core 'generado)

aries @ aries: ~ $ '/home/aries/Escritorio/rpcs3-v0.0.6-8179-cafa4521_linux64.AppImage' 
termina después de lanzar una instancia de 'std :: runtime_error' 
what (): Error de sistema desconocido: 20. 
Abortado (`core 'generado)

**Comment by AniLeo** [comment] 2019-06-02 17:33
Looks like an issue on your setup, not something to do with RPCS3 itself

Upload the RPCS3.log file and/or a backtrace

**Comment by crack-keys** [comment] 2019-06-02 17:40
[RPCS3.log](https://github.com/RPCS3/rpcs3/files/3245021/RPCS3.log)
RPCS3.log

**Comment by AniLeo** [comment] 2019-06-02 18:54
Log shows pirated game, removed log and closing issue

**Closed by AniLeo** 2019-06-02 18:54 UTC
