### ISSUE TITLE
Linux In the same session closing a game does not free memory

### ISSUE THREAD

**Issue by Augusto7743** [RPCS3/rpcs3#9811] opened 2021-02-20 18:10 UTC
Linux Lubuntu 20.04 64 bits.
Only OS memory usage is 480 MB RAM.
When RPCS3 is started goes to 650 MB RAM.

If starting an game for first time is created PPUs and thus allocate memory.
The problems is the memory used for create PPUs continue being allocated and thus the game will use an huge memory allocation.
Have games that creating the PPUs the memory allocation goest to 2,5 GB and starting the game goes to above 3,5 GB being an problem for systems using 4 GB RAM.
Thus need after PPUs are created close and restart RPCS3 and the gameplay will use 2,5 GB or less RAM.
That also happen when starting an game and close and not closing RPCS3 continuing in same session and start another game.
RPCS3 gameplay allocate 2,5 Gb or 3 GB RAM for an game after closing goes to 1,2 or 1,5 GB instead 650 or 750 MB RAM.
Thus need start RPCS3 and closing game also close RPCS3 and after restart RPCS3 to avoid huge memory allocation that some times use totally the RAM with high swap usage that in some times need to reset the machine.

I not has information if is an problem or feature in Linux file cache or RPCS3 issue.
Possibly in windows not happen that issue.
Thanks for read my report and have an nice day.

**Comment by RainbowCookie32** [comment] 2021-02-20 18:12
Duplicate of #7430

**Closed** 2021-02-20 18:14 UTC

**Comment by Augusto7743** [comment] 2021-02-20 18:20
Thanks :-)
