### ISSUE TITLE
Ultimate Marvel Vs Capcom 3 [BLUS30787]: silver line with Vulkan on Mesa

### ISSUE THREAD

**Issue by toccata10** [RPCS3/rpcs3#5164] opened 2018-09-23 10:55 UTC
Used version: rpcs3-v0.0.5-7377-b7e010bb_linux64
R9 fury, Archlinux, mesa 18.2
On Ogl, graphics seem perfect. On Vulkan, it's also very good (thanks to recent improvements), excepted there's a thin silver line which appears on the tile screen (after the intro movie) and never goes away.
The screenshots and the renderdoc trace with vulkan
![selection_016](https://user-images.githubusercontent.com/7478580/45927206-c7b9a280-bf2f-11e8-84f0-76334822d5f6.jpg)
![selection_017](https://user-images.githubusercontent.com/7478580/45927207-c7b9a280-bf2f-11e8-8d06-f0e588a9d14c.jpg)
[rpcs3-v0_2018.09.23_10.46.47_frame1718.zip](https://github.com/RPCS3/rpcs3/files/2408634/rpcs3-v0_2018.09.23_10.46.47_frame1718.zip)

**Comment by sunshan1990** [comment] 2018-09-30 02:01
this game freeze on the intro with a black screen , my system is ubuntu18.04 with nvidia card.

**Comment by toccata10** [comment] 2018-09-30 06:37
Please attach a log file

**Comment by hakzsam** [comment] 2019-05-06 19:32
Hi all,

I think this issue can be closed because:
1) the lines problem is solved if you enable the "Strict Rendering Mode", this is because RPCS3 violates the Vulkan spec (probably some missing barriers)
2) the game no longer freezes with latest mesa/llvm git on both Polaris10/Vega10 (tested GL/VK)

FWIW, the lines problem can also be reproduced with AMDVLK and I think it would be nice to fix the root cause instead of using a workaround (not saying it's easy of course). Also the wiki should be updated because it's not driver related.

If you experiment issues that you think are RADV specific, feel free to report them directly here https://bugs.freedesktop.org (under the Drivers/Vulkan/radeon component), I would be glad to help!

Thanks,
Samuel (a RADV developer)

**Comment by kd-11** [comment] 2019-05-07 05:26
Indeed, there is a violation without strict mode, it's a framebuffer feedback loop. I do have a pipeline barrier in this case from attachment_write to shader_read but it is seemingly not enough on some GPUs. Strict rendering mode bypasses all that by just making a copy of the texture in question but incurs some memory overhead. On PS3 fbo feedback loop access somehow always resolve correctly (as if the target was copied before the invocation) which makes matching its behavior rather difficult on desktop.

**Comment by kd-11** [comment] 2019-05-17 13:41
Fixed by https://github.com/RPCS3/rpcs3/pull/5977

**Closed by kd-11** 2019-05-17 13:41 UTC
Labels: Driver: AMD, Render: Vulkan
