### ISSUE TITLE
Gundam Reborn issue : In-game , can ply specific mission with no crash(char's counterattack)(edited)

### ISSUE THREAD

**Issue by song12347** [RPCS3/rpcs3#4547] opened 2018-05-12 10:39 UTC
![dasdsad](https://user-images.githubusercontent.com/39214838/39956489-f9cd9324-5613-11e8-8836-4057a349b48f.png)

Version RPCS3: 0.0.5-6718-737db9005 Alpha
Game : Gundam Reborn 
Spec: 
i7-4790
GTX 980 with 4gb memory
16gb ddr3 ram
750W of power supply
3tb 7200rpm hdd

 Log:
F {PPU[0x100003f] Thread (CStageSceneBuilder) [0x0021dfc4]} MEM: Access violation reading location 0x10010010

details: The game (gundam reborn) can be ply with no crash and high fps(30-60fps) in specific mission( Char's Counter Attack) , it also have enough of fps to ply but most of the mission will appear error above(the Log) and causes hang in gameplay  , really just a small step to be complete this game , hope u guys can solve this issues ...

**Comment by AniLeo** [comment] 2018-05-20 19:11
Removed console output, missing log files

**Comment by AniLeo** [comment] 2018-11-15 22:57
It's good, this kind of issue has been found in other games too
This is a duplicate of #4522 so will be closing this one so it can be tracked there

**Closed by AniLeo** 2018-11-15 22:57 UTC
Labels: Need Information
