### ISSUE TITLE
F SIG: Thread terminated due to fatal error: Verification failed (in file D:\a\1\s\rpcs3\Emu\RSX\VK\VKTexture.cpp:798[:3], in function gpu_deswizzle_sections_impl) (e=0x000001e7[487])

### ISSUE THREAD

**Issue by seanawesome** [RPCS3/rpcs3#10612] opened 2021-07-25 23:09 UTC
Please briefly describe what is not working correctly.
I just installed RPCS3 today, and Ratchet and Clank Tools of Destruction launched after a couple hours of troubleshooting. However, after going past a certain point in the level, the game crashes. I'm not sure if it's a graphical issue yet.
[RPCS3Log.txt](https://github.com/RPCS3/rpcs3/files/6874687/RPCS3Log.txt)

Windows 10 Pro, RTX 3090, I9-9900k, 4x8GB Trident Royal, 1TB Samsung Pro m.2
If necessary, I could go back into the game with any overlay, debugging, etc for someone in support.

**Comment by AniLeo** [comment] 2021-07-25 23:14
Attached file is not a log file
You must follow the regression template
It's probably from #10604

**Comment by seanawesome** [comment] 2021-07-25 23:33
Okay, so the game only crashes on a higher resolution scale, but is there any way to fix that?

**Comment by kd-11** [comment] 2021-07-26 07:59
I know what causes this, I'll provide a fix.

**Comment by kd-11** [comment] 2021-07-26 21:43
Should be fixed by https://github.com/RPCS3/rpcs3/pull/10611. Please try with a build from the PR and see if the problem goes away.

**Comment by jokoputera** [comment] 2021-07-27 00:46
im just wondering, is the the workaround some buggy AMD driver or is it because the complexity of PS3 hardware?

**Comment by AniLeo** [comment] 2021-07-27 01:18
It's not a workaround, it's a fix, the driver isn't at fault

**Closed** 2021-08-13 19:46 UTC
Labels: Bug, Render: Vulkan, Regression
