### ISSUE TITLE
Infamous 2 [BCES01144] segfault on launch

### ISSUE THREAD

**Issue by Spencer-0003** [RPCS3/rpcs3#14481] opened 2023-08-13 16:08 UTC
### Quick summary

The game crashes during  the "Sony Computer Entertainment Presents" screen.

### Details

RPCS3 freezes with "F {RSX [0x0014808]} SIG: Thread terminated due to fatal error: Segfault writing location 0000002973002973 at 00007f660eefbac8."

### Attach a log file

[RPCS3.log](https://github.com/RPCS3/rpcs3/files/12329880/RPCS3.log)

### System configuration

OS: Arch Linux
GPU: RX 6950XT
CPU: Ryzen 9 5900X

### Other details

Build: rpcs3-git (0.0.29.r15479.39bbf17caf-1) from the AUR

**Comment by FlexBy420** [comment] 2023-08-13 17:47
Unable to reproduce.
[RPCS3.log.gz](https://github.com/RPCS3/rpcs3/files/12330053/RPCS3.log.gz)

**Comment by Spencer-0003** [comment] 2023-08-13 18:57
Fixed the issue by deleting my custom configuration and recreating it with the same settings (settings copied from the wiki). Migrating from bin to git then deleting obsolete settings may have caused this?

**Comment by Wontell** [comment] 2023-08-15 22:35
> Fixed the issue by deleting my custom configuration and recreating it with the same settings (settings copied from the wiki). Migrating from bin to git then deleting obsolete settings may have caused this?

OP, please Close the issue, too many open issues hard to find the ones that need attention

**Closed** 2023-08-17 08:46 UTC
