### ISSUE TITLE
Huge performance lost in Persona 5 since build 8204

### ISSUE THREAD

**Issue by Ghostotakoi** [RPCS3/rpcs3#6134] opened 2019-06-26 04:13 UTC
Since [6112](https://github.com/RPCS3/rpcs3/pull/6112) i have been experiencing a major performance lost in P5 in older builds i almost all the time was locked to 30fps, except in some crowded areas of Shibuya around 22fps to 24fps, now is like locked to 20fps and even if i activate TSX multi-thread or put to sleep some SPURS threads, witch use to increase a little the performance, now still locked 20fps.
My pc specs.
i7-6700 non k
gtx-1060 6gb driver ver. 430.86
16gb ram

![ScreenShot_20190625235330](https://user-images.githubusercontent.com/20958581/60150515-11793700-97a7-11e9-8cdc-106735631cbc.png)
![ScreenShot_20190625235446](https://user-images.githubusercontent.com/20958581/60150517-11793700-97a7-11e9-9dce-82553f265657.png)
![ScreenShot_20190625235508](https://user-images.githubusercontent.com/20958581/60150518-11793700-97a7-11e9-9260-08e56806ee7a.png)
![ScreenShot_20190625235529](https://user-images.githubusercontent.com/20958581/60150519-1211cd80-97a7-11e9-8161-da533ea2d113.png)

**Comment by Asinin3** [comment] 2019-06-26 04:44
Did you try turning the new Multithreaded RSX option off then?
Also try anti-aliasing off if it's still slow.

**Comment by Emulator-Team-2** [comment] 2019-06-26 06:59
@Ghostotakoi 
[Implement TSX fallback]
After this pr #6056 `Preferred SPU Threads` should be set to Auto.

See this comment:
https://github.com/RPCS3/rpcs3/pull/6056#issuecomment-502766550

**Comment by mjuzikfrik** [comment] 2019-06-26 07:06
With the latest versions I have multiple problems with P5 and TSX enabled like exploding verticles or audio cutting out. 
Disable TSX and set SPU block size to safe and the rest leave as is. I've got the same CPU as you and with these settings I have no problems.

**Comment by kd-11** [comment] 2019-06-26 07:16
A quad core cannot handle RSX multithreading as of now. Its meant for wider Ryzens or the newer hexacore and octacore intel chips which have enough resources to spare.

**Comment by digitaldude555** [comment] 2019-06-26 09:45
Turn on accurate getllar thats what brings the fps for me, it's only for persona. @Ghostotakoi

**Comment by vsub** [comment] 2019-06-26 14:21
No change here.
The difference from your settings are
1.Enable Threaded Scheduler is not enabled
2.Preferred SPU Threads is set to Auto
3. FPS Limit is set to 59.54
4.AF - Automatic
5.Resolution Scaling - 100%
6.MT RTX is off
7.From Debug nothing is enabled and SPURS is set to 5

I have i7-6700HQ limited to 2.5Ghz(which makes my cpu even weaker than yours)to reduce heat and my gpu(GTX1060)is set to Prefer Maximum Performance

I also don't have any cpu firmware updates installed,I only use what MS is giving me from the windows updates

![8300](https://user-images.githubusercontent.com/5032540/60187610-c81bfc80-9825-11e9-9a15-e73819e06d5f.jpg)
![8274](https://user-images.githubusercontent.com/5032540/60187611-c81bfc80-9825-11e9-9aa4-f3260951c648.jpg)

**Comment by Ghostotakoi** [comment] 2019-06-26 21:04
I have tried all you advice and still locked 20 fps.
![ScreenShot_20190626170041](https://user-images.githubusercontent.com/20958581/60214885-7464df80-9834-11e9-8573-6a0789bc21b1.png)
![ScreenShot_20190626170111](https://user-images.githubusercontent.com/20958581/60214887-74fd7600-9834-11e9-8862-23a820ca44bf.png)
![ScreenShot_20190626170141](https://user-images.githubusercontent.com/20958581/60214888-75960c80-9834-11e9-8799-b4cc24357936.png)
![ScreenShot_20190626170149](https://user-images.githubusercontent.com/20958581/60214889-75960c80-9834-11e9-997a-2ee77f2fd66d.png)

**Comment by Ghostotakoi** [comment] 2019-06-26 21:16
Older build 8205 performance.
![ScreenShot_20190626171017](https://user-images.githubusercontent.com/20958581/60215490-b8a4af80-9835-11e9-8f03-80a101f1b8d3.png)
![ScreenShot_20190626171043](https://user-images.githubusercontent.com/20958581/60215492-b93d4600-9835-11e9-8cbd-5e48ceb5f65a.png)
![ScreenShot_20190626171050](https://user-images.githubusercontent.com/20958581/60215493-b93d4600-9835-11e9-8cfa-d976ac5068c7.png)
![ScreenShot_20190626171058](https://user-images.githubusercontent.com/20958581/60215494-b9d5dc80-9835-11e9-88ab-68f99515e5a0.png)

Ok i try older builds and i realize that the real performance lost for me was at [#6055](https://github.com/RPCS3/rpcs3/pull/6055)

**Comment by Asinin3** [comment] 2019-06-27 01:44
Don't use gpu texture scaling, it was moved to debug tab and hidden for a reason. Disable Zcull should really not be used either of cases. Stay away from debug settings for the most part. Framelimiter should also be left off since the game has an inbuilt fps cap anyway and using a framelimiter will only hurt performance a bit with 0 benefit. And why did you switch to using mega? Post logs after you run each test of each build.

This is really turning into a support thread which isn't what GitHub is for though.

**Comment by kd-11** [comment] 2019-06-27 14:34
@Ghostotakoi Close this issue and reach out on discord. Whenever a 'bug' affects only a handful of people it usually means something system-specific is to blame rather than the emulator code itself. Writing anything here pings everyone with emails which can be aggrevating. That being said, I would like to suggest the following:
1. Create a new directory for rpcs3 and extract the archive there (clean slate). This tends to resolve problems like these if appveyor changed something silently.
2. Rename the executable to a different name after doing step 1. You can name it abcdef.exe for example just in case you accidentally have some global flags active. Again, you'd be surprised how often this can solve issues like these.

I'd start with option 1 with a clean slate, new config and everything and only install the affected game. I'm also curious what kind of performance you're getting with other examples especially with samples like gs_basic_triangle.elf

**Comment by Ghostotakoi** [comment] 2019-07-04 00:44
@kd-11 i am reopening this issue because i did a fresh install of my rpcs3 but still the performance lost is evident losing 10+ fps.

**build 8196**
![ScreenShot_20190703195841](https://user-images.githubusercontent.com/20958581/60632304-ead48500-9dd2-11e9-9208-3963762ac947.png)
![ScreenShot_20190703195917](https://user-images.githubusercontent.com/20958581/60632305-eb6d1b80-9dd2-11e9-95e7-bf489ac33355.png)
![ScreenShot_20190703195953](https://user-images.githubusercontent.com/20958581/60632307-eb6d1b80-9dd2-11e9-875c-2bf7bbbe5634.png)
![ScreenShot_20190703200018](https://user-images.githubusercontent.com/20958581/60632308-ec05b200-9dd2-11e9-9d4e-c73d68ad41e7.png)

**build 8329**
![ScreenShot_20190703200434](https://user-images.githubusercontent.com/20958581/60632353-20796e00-9dd3-11e9-874c-caf71f3971b1.png)
![ScreenShot_20190703200512](https://user-images.githubusercontent.com/20958581/60632354-21120480-9dd3-11e9-9bdd-a452ec61c820.png)
![ScreenShot_20190703200531](https://user-images.githubusercontent.com/20958581/60632355-21120480-9dd3-11e9-9010-4f3825fb0e57.png)
![ScreenShot_20190703200549](https://user-images.githubusercontent.com/20958581/60632356-21120480-9dd3-11e9-857c-d7ab2d72a6b6.png)

**Comment by kd-11** [comment] 2019-07-04 08:38
What happened to all the builds in between? The build before my PR was merged is 8280 and my PR is 8298. There isn't much I can do with this unless other people are affected so we can figure out how to reproduce the problem.

**Comment by spyropt** [comment] 2019-07-04 09:12
play in window mode and see if fps rizes while window is not on top (click with the mouse in the desktop for instance)
if its just this game that has lower fps probably it's this bug

**Comment by AmineI** [comment] 2019-07-04 13:12
> @kd-11 i am reopening this issue because i did a fresh install of my rpcs3 but still the performance lost is evident losing 10+ fps with exact same options and same place.

You kept the debug settings enabled though.

**Comment by vsub** [comment] 2019-07-04 14:02
Don't use SPURS less than 5
I clear the whole game(more that 90 hours without a single crash)by manually disabling threads and I can tell you that disabling more than one core\thread will always gives you random results
I am also not sure how rpcs3 decides which thread to disable,but I always get best results by disabling the seconds one(3rd when you count 0)

Try setting the SPURS to 5 or Auto and try both revs
I also don't know how better "Mega" is because I clear the game by using only Safe

**Comment by Ghostotakoi** [comment] 2019-07-04 19:53
@kd-11 i will try the build just before yours, then a few builds after, and should i post a log or an rsx capture? i will disable debug tab and try the other things people said.
@AmineI i will disable debug tab and try
@vsub i will try your advices
@spyropt i always play in winindow mode

**Comment by Ghostotakoi** [comment] 2019-07-05 02:09
@kd-11
ok i have tried a a lot of builds and the performance lost for me was at build 8204. apparently is related to vulkan render. 

**setting i used for all my tests**
![ScreenShot_20190704205239](https://user-images.githubusercontent.com/20958581/60693283-bf6f9a00-9ea7-11e9-94f6-3d2a2ca3f89d.png)
![ScreenShot_20190704205245](https://user-images.githubusercontent.com/20958581/60693285-c0083080-9ea7-11e9-879e-8157a605f373.png)

**build 8202**
![ScreenShot_20190704215114](https://user-images.githubusercontent.com/20958581/60693310-d44c2d80-9ea7-11e9-9f58-f042a4c7f549.png)

**build 8204**
![ScreenShot_20190704211028](https://user-images.githubusercontent.com/20958581/60693359-fd6cbe00-9ea7-11e9-9240-d5fed4bca07b.png)

**Comment by Asinin3** [comment] 2019-07-05 03:38
Disabling debug tab just hides the settings from the ui it doeant turn them off..

**Comment by kd-11** [comment] 2019-07-05 10:30
@Ghostotakoi What framerate do you get with the triangle sample?

**Comment by Ghostotakoi** [comment] 2019-07-05 20:41
@Asinin3 those all are fresh install so i haven´t tweak debug.
@kd-11 sorry for my ignorance what do you mean for triangle sample?

**Comment by RainbowCookie32** [comment] 2019-07-05 20:43
The triangle sample is an included test in RPCS3, it's (I think) gs_gcm_basic_triangle.elf under dev_hdd0/game/TEST12345/USRDIR.
You can boot it from RPCS3 if you go to File->Boot SELF/ELF

**Comment by Ghostotakoi** [comment] 2019-07-05 21:47
ok @RainbowCookie32 @kd-11 triangle test on fresh install

**settings used**
![ScreenShot_20190705174132](https://user-images.githubusercontent.com/20958581/60746451-cf8d8500-9f4c-11e9-9572-fe059697a76e.png)
![ScreenShot_20190705174137](https://user-images.githubusercontent.com/20958581/60746452-d0261b80-9f4c-11e9-98a8-1f58863ee690.png)

**build 8202**
![ScreenShot_20190705174334](https://user-images.githubusercontent.com/20958581/60746475-ea5ff980-9f4c-11e9-8785-15ecb18f9486.png)

**build 8204**
![ScreenShot_20190705174245](https://user-images.githubusercontent.com/20958581/60746495-f946ac00-9f4c-11e9-86ec-afb03c94c226.png)

**Comment by Whatcookie** [comment] 2019-07-06 00:43
Isn't 18 fps a bit low for a 6700 in the before screenshot?

This is a bit of a stretch, but is the cable that's hooked up to your monitor plugged into your motherboard or into your Nvidia GPU? Another user in discord mentioned earlier that the same build you've singled out made his games "less smooth" and the conclusion I came to was that it may be due to having your dedicated GPU not hooked up directly to the monitor. This user was on a laptop, so we couldn't verify that, but it's the only other time I've seen someone complain about that build.

**Comment by Ghostotakoi** [comment] 2019-07-06 01:21
@Whatcookie yes my cable is directlty plugged into my Nvidia GPU

**Comment by kd-11** [comment] 2019-07-06 10:21
As expected. Just nuke the drivers and reinstall.

**Comment by AmineI** [comment] 2019-07-06 16:51
Reading this thoroughly should be enough to get you started @Ghostotakoi, as a simple uninstall of the drivers often isn't enough https://www.wagnardsoft.com/content/ddu-guide-tutorial .
If you need help about it, feel free to ask on discord, and report back here once it's done :)

**Comment by Ghostotakoi** [comment] 2019-07-08 03:55
@kd-11 @AmineI
I used the DDU to wipe out my gpu driver, now using a fresh clean driver install 430.86, and result the same, major performance lost since 8202... at least for me.
![ScreenShot_20190707233751](https://user-images.githubusercontent.com/20958581/60781962-99016700-a112-11e9-84a7-3716fbd28c32.png)
![ScreenShot_20190707233915](https://user-images.githubusercontent.com/20958581/60781963-99016700-a112-11e9-8b76-ee346a1697f2.png)

i use the same settings as last time
**latest build 8352**
![ScreenShot_20190707234520](https://user-images.githubusercontent.com/20958581/60781928-6eafa980-a112-11e9-8a3e-7a24d454eb97.png)

**build 8204**
![ScreenShot_20190707234253](https://user-images.githubusercontent.com/20958581/60781935-77a07b00-a112-11e9-92a9-24a0b141fefb.png)

**build 8202**
![ScreenShot_20190707234206](https://user-images.githubusercontent.com/20958581/60781951-85ee9700-a112-11e9-9261-c32b69e2998f.png)

**Comment by kd-11** [comment] 2019-07-08 14:19
Unfortunately there is nothing we can do about this until we find more affected users and compare hardware and software configuration. Its nearly impossible to figure out what's wrong with one individual system, unless its a developer's rig where we can rip everything apart safely and use profiling to narrow down the cause. I'll leave this as need information until we see if other users are experiencing the same issue.

**Comment by AmineI** [comment] 2019-07-08 14:59
Thanks for all your details @Ghostotakoi - I was unable to reproduce the issue on my end either, could you drop your config.yml file here please, in case I didn't properly replicate your config ? Also, which Windows 10 version are you on ? (Typing winver on the start menu will give you that info. It's also specified in dxdiag I believe)

**Comment by Ghostotakoi** [comment] 2019-07-09 00:27
@AmineI here
[config.zip](https://github.com/RPCS3/rpcs3/files/3370663/config.zip)
@kd-11 any other test i can do to know if is a bug that affect only me??

**Comment by Asinin3** [comment] 2019-07-09 01:33
Only thing you can do is test on different systems and wait for other people to test as well.

**Comment by Ghostotakoi** [comment] 2019-07-14 22:32
@AmineI winver
![ScreenShot_20190714183038](https://user-images.githubusercontent.com/20958581/61190153-ba5bd900-a665-11e9-9c49-8154a28a933d.png)

**Comment by Gonbatfire** [comment] 2019-08-04 23:52
Perfomance has been decreased significantly for my system too
Latest build 8440
![latest 8440 persona 5](https://user-images.githubusercontent.com/46731233/62430886-ca148d80-b6f8-11e9-8be0-43a8728e86a8.png)
8204 build
![8204 p5](https://user-images.githubusercontent.com/46731233/62430897-e31d3e80-b6f8-11e9-888e-995834d4d653.png)
log:
[RPCS3.log.gz](https://github.com/RPCS3/rpcs3/files/3465452/RPCS3.log.gz)

8202 build (best performance)
log: 
[RPCS3.log.gz](https://github.com/RPCS3/rpcs3/files/3465453/RPCS3.log.gz)

![8202 p5](https://user-images.githubusercontent.com/46731233/62430908-fa5c2c00-b6f8-11e9-8a9b-90a519a9b553.png)

Also, other games have seen a perfomance lost it seems:
8440 build
![latest 8440](https://user-images.githubusercontent.com/46731233/62430956-81a99f80-b6f9-11e9-8448-58fa71f77479.png)
8202 build (the framerate is much more stable here)
![8202](https://user-images.githubusercontent.com/46731233/62430962-8d956180-b6f9-11e9-90f6-b2b3f4dc7c15.png)

**Comment by Ghostotakoi** [comment] 2019-08-05 05:25
@Gonbatfire could you try also the triangle test???

**Comment by Gonbatfire** [comment] 2019-08-06 01:48
An user on RPCS3 Discord [khalil78] posted the same issue:
![khalil78](https://user-images.githubusercontent.com/46731233/62505366-c2291c00-b7d2-11e9-835b-62084e640411.png)
https://media.discordapp.net/attachments/272875751773306881/607842451675414569/drop.JPG?width=1202&height=677
https://media.discordapp.net/attachments/272875751773306881/607842958938734592/Capture_drop.JPG?width=1202&height=677

Clearly, this isn't an P5 issue, and it's affecting other games too.

Also, i'll do the triangle test tomorrow probably, sorry.

**Comment by Ghostotakoi** [comment] 2019-08-06 04:57
Interesting @Gonbatfire, @kd-11 i haven´t able to play anything on rpcs3 since build 8202 because the fps are too low, what could this be, window version, driver related, vulkan related???

**Comment by Gonbatfire** [comment] 2019-08-06 23:19
build 8440 (fps actually improved)
![triangle 8440](https://user-images.githubusercontent.com/46731233/62583194-92871c00-b885-11e9-929a-aab35f5fda68.png)
[RPCS3.log.gz](https://github.com/RPCS3/rpcs3/files/3474494/RPCS3.log.gz)

build 8204 
![triangle 8204](https://user-images.githubusercontent.com/46731233/62583212-a468bf00-b885-11e9-801c-7429a72facab.png)
[RPCS3.log.gz](https://github.com/RPCS3/rpcs3/files/3474500/RPCS3.log.gz)

build 8202 seems like no difference from 8204, weird...
![triangle 8202](https://user-images.githubusercontent.com/46731233/62583236-bd717000-b885-11e9-91c6-1a87395bb000.png)
[RPCS3.log.gz](https://github.com/RPCS3/rpcs3/files/3474502/RPCS3.log.gz)

HOWEVER, on 8204 both me and Ghostokoi have around 1600 fps, i'm running an i7 2600 with 1x8gb ddr3 ram and rx 570 while he is on an i7 6700 with ddr4 memory and an 1060, we shouldn't get about the same fps right??

**Comment by Ghostotakoi** [comment] 2019-08-09 01:16
@Gonbatfire OMG is true i am actually getting better performance in triangle test in latest build but not in the games... so wierd...

build 8202
![ScreenShot_20190808211216](https://user-images.githubusercontent.com/20958581/62747284-c139f980-ba21-11e9-937c-791cecf7e9fa.png)

build 8445
![ScreenShot_20190808210735](https://user-images.githubusercontent.com/20958581/62747304-d31b9c80-ba21-11e9-8b93-75242e65316f.png)

**Comment by AniLeo** [comment] 2020-01-08 21:15
Test on the latest builds, this should be irrelevant now

**Comment by Gonbatfire** [comment] 2020-01-19 17:55
can confirm Persona 5 performs better than ever on latest build, 30 FPS most of the time with an i7 2600 stock, very impressed

**Closed** 2020-01-19 18:23 UTC
Labels: Driver: NVIDIA, Need Information
