### ISSUE TITLE
Demon's Souls Crash after Tutorial

### ISSUE THREAD

**Issue by Mindbomb77** [RPCS3/rpcs3#3178] opened 2017-08-08 04:33 UTC
CPU: Intel Core i7-4700MQ 2.4GHz
GPU: NVIDIA GeForce GTX 770M
RAM: 16GB
OS: 15063.483

![screenshot 1](https://user-images.githubusercontent.com/30820514/29056406-71140ec6-7bc8-11e7-8295-d7a9d9000838.png)
![screenshot 2](https://user-images.githubusercontent.com/30820514/29056411-751c4524-7bc8-11e7-8edc-4a877d58b658.png)
![screenshot 3](https://user-images.githubusercontent.com/30820514/29056412-770d37c6-7bc8-11e7-9212-4117d6849686.png)

Log: 
[RPCS3.zip](https://github.com/RPCS3/rpcs3/files/1209464/RPCS3.zip)

**Comment by Asinin3** [comment] 2017-08-08 18:57
Not a fix but I managed to ask someone for a save file that should be after this point (I didn't check) place in \dev_hdd0\home\00000001 if it doesn't work message me on discord. Also you need to zip the error log file and upload it rather than paste that wall of text here.
[savedata.zip](https://github.com/RPCS3/rpcs3/files/1209245/savedata.zip)

**Comment by Mindbomb77** [comment] 2017-08-08 20:25
Hey thanks a million Asinin. I really appreciate how much time and effort you've put in to getting this to work for me. The save file is working so far.

**Comment by Asinin3** [comment] 2017-08-10 08:05
I'll delete/edit this comment when Mindbomb77 posts an update (if he does):

He has told me that the issue was solved by making a fresh re-install of RPCS3, however he did try many different builds before posting here with pretty much every setting imaginable. I can't say what exactly causes this or if it still exists in the new masters but perhaps someone else may know and be confident enough to close this?

I can also confirm that other people have been experiencing this bug and a fresh rpcs3 folder/install fixed it for them.

**Comment by kd-11** [comment] 2017-08-26 10:58
Well, this is the second time I've seen game breaking bugs in DeS fixed by a clean install. DeS does actually write data to /dev_hdd1/cache so that might be the cause of these issues. I'm closing this one as the OPs problem is fixed.

**Closed by kd-11** 2017-08-26 10:58 UTC
