### ISSUE TITLE
Builds after 0.0.33-17061 do not load

### ISSUE THREAD

**Issue by yeahme49** [RPCS3/rpcs3#16263] opened 2024-10-29 12:46 UTC
### Quick summary

I was trying to launch the latest version (17066) and after trying to load RPCS3, it would create games.yml and RPCS3.buf and that was it. No GUI loaded, no errors, no log file. Task manager shows rpcs3.exe running, using around 450kb of memory. If I try to load it again I get an error that another instance is running. I started testing older builds and 0.0.33-17055 and older loads just fine. Not sure what other details I can provide since no log file is created but if there is anything let me know.

### Attach a log file

No log created

**Comment by Monsterman07** [comment] 2024-10-29 13:06
Duplicate of #16260

**Closed** 2024-10-29 13:09 UTC
