### ISSUE TITLE
Verification Failed error 

### ISSUE THREAD

**Issue by Red1860** [RPCS3/rpcs3#11411] opened 2022-01-20 06:42 UTC
## Quick summary
I am getting this error when loading a game:

Verification failed
(in file /private/var/folders/tn/f_9sf1xx5t14qm_6f83q3b840000gn/T/cirrus-ci-build/rpcs3/util/simd.hpp:120[:4], in function vec_alloc) (errno=2)
Thread id = 0x10788ee00.

#### 1. Please provide _exact_ build (or commit) information that introduced the regression you're reporting.
https://github.com/RPCS3/rpcs3/commit/d572d90bb751acc76576ebfa783c27aa0186d95c

#### 4. Please attach screenshots of your problem.
<img width="532" alt="ss" src="https://user-images.githubusercontent.com/58611972/150287065-e4446ed6-299b-440a-8239-b6e107666f1a.PNG">

* Enable performance overlay with at least medium level of detail.
You can find it in _Emulator_ tab in _Settings_.

#### 6. Please provide your system configuration:
macOS Big Sur 11.6
Apple M1 MacBook Air

#### Please include.
* Anything else you deem to be important

**Comment by MSuih** [comment] 2022-01-20 06:47
Duplicate of #11409

**Closed by MSuih** 2022-01-20 06:47 UTC
