### ISSUE TITLE
Exploding vertices in Persona 5 on Kamoshida´s hair

### ISSUE THREAD

**Issue by Ekaseo** [RPCS3/rpcs3#5745] opened 2019-03-19 13:10 UTC
Im currently at work, so I cant post any logs, but this issue exists on master right now. I was using Vulkan with the latest Nvidia drivers. Can anyone else confirm this issue, or is it just a problem on my end.

**Comment by vsub** [comment] 2019-03-19 13:22
It does exist but that's the only problem and only in that cut scene(if I remember correctly).
I already clear the game(few months ago)and there is no other similar problems anywhere else in the game

**Comment by RipleyTom** [comment] 2019-03-19 13:34
Iirc, the issue is actually present on a real ps3 too.

**Comment by kd-11** [comment] 2019-03-19 20:58
I think it was caused by unlocking fps to 60? Maybe I'm remembering wrong.

**Comment by Vas0sky** [comment] 2019-03-21 23:05
It is not related to patching the game to run at 60 fps. I'm playing the game vanilla (version 1.00 without dlc) and the issue is there, it's only present on the right (left? I can't remember well) of his face, but it happens on all cutscenes.

**Comment by HerrHulaHoop** [comment] 2019-03-31 20:59
Apparently enabling Accurate xfloat fixes the issue (thanks to Lipsum on discord for pointing it out).

Would need somebody to test this out and confirm that SPU LLVM with just approximate xfloat causes the vertex explosions during this scene.

**Comment by Ghostotakoi** [comment] 2019-04-01 01:15
yes it happened to me too

**Comment by kd-11** [comment] 2019-04-19 09:17
If its fixed with accurate xfloat, why is this issue still open?

**Closed by kd-11** 2019-04-19 09:17 UTC
