### ISSUE TITLE
Devil May Cry™ HD Collection [NPEB01188] missing graphics Vulkan only (opengl plays fine)

### ISSUE THREAD

**Issue by benderscruffy** [RPCS3/rpcs3#6962] opened 2019-11-08 06:50 UTC
missing all  the graphics in vulkan (doesnt happen with opengl)
music  and sound fx plays in the background
happens on all 3 DMC
![dmc](https://user-images.githubusercontent.com/2696404/68455662-e0ba0b80-0236-11ea-8811-5003171d4055.PNG)
[RPCS3.log.gz](https://github.com/RPCS3/rpcs3/files/3823274/RPCS3.log.gz)
[captures.zip](https://github.com/RPCS3/rpcs3/files/3823277/captures.zip)

**Comment by Asinin3** [comment] 2019-11-23 09:23
I got ingame just fine with proper graphics on DMC 2 and 3 with vulkan.
![image](https://user-images.githubusercontent.com/15137035/69476445-ea906100-0e29-11ea-88e1-5eefb8e962ab.png)
![image](https://user-images.githubusercontent.com/15137035/69476474-44912680-0e2a-11ea-8a52-0e4fae5c32d6.png)

DMC 1 kept giving me this though:
``F {RSX [0x0168ad0]} RSX: class std::runtime_error thrown: Verification failed: 
(in file C:\projects\rpcs3\rpcs3\Emu\RSX\Common\texture_cache.h:2310)``

But regardless, if this is an actual regression for you and not just due to some bad settings then you need to find where it broke.

**Comment by Asinin3** [comment] 2019-11-23 12:48
DMC 1 is fixed by newest KD pr (that crash was a recent regression) but regardless its not the same issue as OP reported. I think this can be closed unless we can confirm its an amd only issue or something :/

![image](https://user-images.githubusercontent.com/15137035/69478881-5d5c0500-0e47-11ea-846e-e1e8e122d5ee.png)

**Comment by kd-11** [comment] 2019-11-23 18:27
Need more testers to confirm this.

**Comment by kd-11** [comment] 2019-11-23 18:28
@benderscruffy Try getting a renderdoc trace and we can see if it replays correctly/incorrectly depending on the user's hardware.

**Comment by benderscruffy** [comment] 2019-11-28 07:15
here is a renderdoc
https://mega.nz/#!83BSwK5K!8a56xUMcn0LT9eFzLvjmqdwZz3SgSm8DqzDgzzP9W9A

**Comment by VelocityRa** [comment] 2019-11-28 09:10
I assume the below issue is irrelevant but I can't replay on GTX 970.

![image](https://user-images.githubusercontent.com/6632271/69792576-8fff5800-11cf-11ea-9ee5-06c3684bab28.png)

**Comment by kd-11** [comment] 2019-11-28 09:11
Yes, you must have the same hardware and drivers for renderdoc to work properly.

**Comment by kd-11** [comment] 2019-11-28 09:21
Ok, I think I see whats wrong, we'll see if a patch fixes it. The game is missing the image in the caches and has to fall back to a CPU upload path.

**Comment by kd-11** [comment] 2019-11-28 09:40
On second thought, this will have to be shelved at the moment. There are too many issues present and I'm currently working on something else.

**Comment by benderscruffy** [comment] 2019-11-30 01:56
ok if you set aspect ratio to auto graphics are messed up
if you set to 16:9 graphics are fine

**Comment by kd-11** [comment] 2020-01-06 21:25
Closing as it is resolved by using correct settings.

**Closed by kd-11** 2020-01-06 21:25 UTC
Labels: Render: Vulkan
