### ISSUE TITLE
Ketsui Kizuna Jigokutachi Extra (BLJM61060) - Crash on Startup

### ISSUE THREAD

**Issue by Dos-Boss** [RPCS3/rpcs3#14052] opened 2023-06-19 16:25 UTC
### Quick summary

Ketsui crashes on startup with **“An error has occurred. (80610702)”**.
Game used to work when I tried it a couple years back.

### Details

After intro splashes/movies have played, emulator will crash with 

"Opening error message dialog with message: “An error has occurred. (80610702)”

### Attach a log file

[RPCS3.log](https://github.com/RPCS3/rpcs3/files/11790280/RPCS3.log)

### System configuration

██████████████████  ████████   w0lf@aperture 
██████████████████  ████████   ------------- 
██████████████████  ████████   OS: Manjaro Linux x86_64 
██████████████████  ████████   Host: X670 AORUS ELITE AX -CF 
████████                             ████████   Kernel: 6.3.5-2-MANJARO 
████████  ████████     ████████   Uptime: 1 hour, 22 mins 
████████  ████████     ████████   Packages: 1712 (pacman) 
████████  ████████     ████████   Shell: zsh 5.9 
████████  ████████     ████████   Resolution: 3840x2160 
████████  ████████     ████████   DE: Plasma 5.27.5 
████████  ████████     ████████   WM: KWin 
████████  ████████     ████████   Theme: [Plasma], Breeze [GTK2/3] 
████████  ████████     ████████   Icons: [Plasma], breeze [GTK2/3] 
████████  ████████     ████████   Terminal: konsole 
                               CPU: AMD Ryzen 9 7950X (32) @ 4.500GHz 
                               GPU: AMD ATI 15:00.0 Raphael 
                               GPU: NVIDIA GeForce RTX 3080 
                               Memory: 12819MiB / 31231MiB

**Comment by Asinin3** [comment] 2023-07-23 00:53
>Game used to work when I tried it a couple years back.

Then you should test old builds from https://rpcs3.net/compatibility?b until you find where it broke. Go back 2-3 months at a time until you find where it works again then narrow down the exact build which caused the issue. It's on users to provide helpful issue reports so we can easily find and fix issues.

**Comment by fluttergust** [comment] 2023-07-29 19:14
I tried this a while ago and recently and had the same issue. Commented in #13518 where I found rpcs3-v0.0.22-13626 getting the error, while rpcs3-v0.0.22-13604 works fine. Hopefully that is enough information.

**Comment by leshokunin** [comment] 2023-12-31 08:21
Error is still occurring on latest as of today.

**Comment by AniLeo** [comment] 2024-01-01 15:50
Thanks for the information, closing as duplicate of #13518, will continue tracking the issue there

**Closed** 2024-01-01 17:47 UTC
Labels: Meta: Duplicate, Regression
