### ISSUE TITLE
Fullscreen Stretching seems to be bugged

### ISSUE THREAD

**Issue by rdeleonp** [RPCS3/rpcs3#4835] opened 2018-06-30 03:53 UTC
_Configuration > Emulator > Start games in Fullscreen mode_

When set, I tested the following:

**GPU Renderer - OpenGL**
- Boot any game.
- On first boot, Fullscreen Stretching looks correct.
- On subsequent boot, Fullscreen Stretching looks correct.

**GPU Renderer - Vulkan**
- Boot any game.
- On first boot, Fullscreen Stretching looks correct.
- On subsequent boot, Fullscreen Stretching makes the output look pixelated. Initially thought to be a bug with Resolution Scale, but that was discarded when seeing that Double Click or Alt+ENTER fixes the issue on transition to windowed mode. Double Click or Alt+ENTER once again for fullscreen, and Fullscreen Stretching looks correct. This is reproducible every single time.

Background information: #4815

**Comment by vsub** [comment] 2018-06-30 10:37
Correct me if I am doing this the wrong way
I am using RPCS3 0.0.5-7005 with vulkan 
1280x720 default res
150% scaling(which is 1920x1080)
Aspect Res is set to 16:9(some games gives me black sreen if I leave it to Auto)
Use GPU texture scaling disabled(with enabled is the same)
Stretch to display area enabled(my screen res is 1920x1080)
Start the game in full screen is enabled

and then run Ar noSurge=>load my save=>press Esc=>close the window=>run the same game

I am on Win10 with i7-6700HQ,GTX1060 but when I use my intel card and run the game,the window maximizes to full screen but the actual game part remains at the size of 1280x720 at the top right but exiting and entering full screen again fixes that

It could be AMD GPU thing(trying to resize the game to match the screen size witch will result in pixelation)

**Comment by kd-11** [comment] 2018-06-30 12:34
Its a thing with how drivers interact with qt windows and how those interact with the OS message pump. There are corner cases remaining and this happens usually when loading shaders. It will be fixed.

**Comment by joaodriessen** [comment] 2018-07-08 09:49
Same behaviour here

AMD Graphics (RX480 Software version 18.6.1)
When setting RPCS3 to use Vulkan at higher resolution scaling, if "start games in Fullscreen mode" is set. RPCS3 will not display the game at the set higher resolution scale.
Switching the "start games in Fullscreen mode" setting off and manually going to fullscreen avoids the issue.

**Comment by AniLeo** [comment] 2019-09-18 14:11
Is this still an issue? I can't reproduce

**Comment by rdeleonp** [comment] 2019-09-21 12:48
Hi, @AniLeo 

Sorry, had forgotten about this.

The issue has not happened since quite a long time ago already, don't even remember when it stopped being an issue; long story short, I can no longer reproduce the issue in latest RPCS3.

I'll close the issue.

Thank you and all the RPCS3 team.

Cheers.

**Closed** 2019-09-21 12:49 UTC
Labels: Need Information
