### ISSUE TITLE
Dragon Ball Xenoverse white background in vulkan game

### ISSUE THREAD

**Issue by mkultimate** [RPCS3/rpcs3#5051] opened 2018-08-29 12:33 UTC
![image](https://user-images.githubusercontent.com/16367065/44787710-79e29200-ab5d-11e8-9d8c-8a45882fc15c.png)

![image](https://user-images.githubusercontent.com/16367065/44787742-91ba1600-ab5d-11e8-825d-4b04c9e85310.png)

log
[RPCS3.log.gz](https://github.com/RPCS3/rpcs3/files/2332088/RPCS3.log.gz)

**Comment by elad335** [comment] 2018-08-29 13:54
The default graphics state has been changed. if there are regressions that means something else is broken that wasnt been used/enabled before.

**Comment by kd-11** [comment] 2018-08-31 08:29
Duplicate of https://github.com/RPCS3/rpcs3/issues/5066

**Closed by kd-11** 2018-08-31 08:29 UTC
