### ISSUE TITLE
Madden 17 won't start......

### ISSUE THREAD

**Issue by MakiSalonga** [RPCS3/rpcs3#7444] opened 2020-02-09 02:54 UTC
Ok somehow I got this error on version 9537:
F {PPU[0x1000019] Thread (LoopSimulation)} SYS: class std::runtime_error thrown: Verification failed: 
(in file C:\projects\rpcs3\rpcs3\Loader\PSF.cpp:118)

Also the save file for the game corrupted.
What does that mean? : 

Specs:
RPCS3 v0.0.8-9537-9d1bb60a Alpha | HEAD | Firmware version: 4.85
Intel(R) Core(TM) i5-7200U CPU @ 2.50GHz | 4 Threads | 3.90 GiB RAM | TSC: Bad | AVX+

**Comment by RainbowCookie32** [comment] 2020-02-09 03:00
Seems like a corrupted save. Support is provided in [our Discord server](https://discord.me/RPCS3), not here

**Comment by MakiSalonga** [comment] 2020-02-09 03:08
OK. I got a new save file. If that same error happens again, I'll let you know

**Comment by RainbowCookie32** [comment] 2020-02-09 03:11
Just close the issue and use Discord next time.

Support is provided on our help channel there, the GitHub issues are intended for tracking regressions and issues with games (a corrupted save isn't, it can happen).

If it's actually a consistent issue (the game always ends up with a corrupted save, or it didn't happen before), them open a proper issue with a log, and the last good build if applicable.

**Closed** 2020-02-09 04:24 UTC
