### ISSUE TITLE
South Park The Stick of Truth: sceNp TODO: sceNpBasicSetPresenceDetails2(pres=*0xd01006c0, options=0x2) after winning first fight

### ISSUE THREAD

**Issue by goedzo** [RPCS3/rpcs3#7662] opened 2020-03-01 17:06 UTC
After winning the first battle in the Stick of Truth, a black screen appears with error:
U {PPU[0x1000000] Thread (main_thread) [0x02715878]} sceNp TODO: sceNpBasicSetPresenceDetails2(pres=*0xd01006c0, options=0x2)

Screen goes black and you cannot continue playing.

Attached is the full log.

**Comment by goedzo** [comment] 2020-03-01 17:07
[RPCS3.log](https://github.com/RPCS3/rpcs3/files/4272131/RPCS3.log)

**Comment by digitaldude555** [comment] 2021-01-28 15:35
Now fixed.

**Comment by mieser** [comment] 2021-01-28 20:42
Hi, its still unfixed for me. The black screen appears after the 3 first tutorial fights. 

It occurred in both vanilla and with game update 1.02. 

[RPCS3.log](https://github.com/RPCS3/rpcs3/files/5889707/RPCS3.log)

**Comment by kd-11** [comment] 2021-01-29 10:34
@digitaldude555 Can you get a log of it running so we can compare if options are the cause of this?

**Comment by digitaldude555** [comment] 2021-01-29 12:08
I froze after tutorial, its same if you load a game while ingame. 
[RPCS3.log.gz](https://github.com/RPCS3/rpcs3/files/5893707/RPCS3.log.gz)

**Comment by digitaldude555** [comment] 2021-07-28 17:09
Still issue? @mieser ?

**Comment by Darkhost1999** [comment] 2021-07-28 17:19
I just played through to the tent and battles. The issues of no audio are present but I definitely am not having any black screen or texture issues anymore

**Comment by mieser** [comment] 2021-07-28 17:25
Just played it again and it went to blackscreen again. Audio seems to be fine for me. 
[RPCS3.log](https://github.com/RPCS3/rpcs3/files/6895316/RPCS3.log)

**Comment by Megamouse** [comment] 2021-07-28 17:30
@Darkhost1999 It would be nice if you could play "past" that blackscreen and then also post a log for comparison.

**Comment by Darkhost1999** [comment] 2021-07-28 17:53
My wife and I literally just played this 2 nights ago is when we got past these 3 tutorial batlles. Upon retesting. LLVM has no audio as soon as you're kicked out of the house to go play. ASMJIT has audio the entire time. Both of them now have black screens as soon as the 3 battles are done. So my original comment is invalid as of latest master.
[llvm.log.gz](https://github.com/RPCS3/rpcs3/files/6895474/llvm.log.gz)
[asmjit.log.gz](https://github.com/RPCS3/rpcs3/files/6895475/asmjit.log.gz)

**Comment by Darkhost1999** [comment] 2022-04-11 15:55
[RPCS3.log](https://github.com/RPCS3/rpcs3/files/8465711/RPCS3.log)
Still an issue. ASMJIT still fixes some audio problems. Lots of graphics look fixed. I Really don't like this game. But my wife does.

**Comment by mieser** [comment] 2022-05-30 18:44
Just tested again and everything went good. There is no black screen after the 3rd tutorial battle. So far i just had one ~15 second black screen in a scene to scene transition.

[RPCS3-2.log](https://github.com/RPCS3/rpcs3/files/8800222/RPCS3-2.log)
[RPCS3-1.log](https://github.com/RPCS3/rpcs3/files/8800223/RPCS3-1.log)

**Comment by Darkhost1999** [comment] 2022-05-30 19:28
Fixed

**Closed** 2022-05-30 19:32 UTC
