### ISSUE TITLE
Game speed is ~halved when launching games with `--no-gui` flag

### ISSUE THREAD

**Issue by SuperOkazaki** [RPCS3/rpcs3#8744] opened 2020-08-17 17:47 UTC
## Quick summary
Games that run at full-speed normally have their speed and framerate halved when launched with the `--no-gui` flag.

## Details

Games launched from RPCS3's normal GUI run at full-speed.
Games launched from RPCS3 through a batch file or through the commandline that *do not* include the `--no-gui` flag run at full-speed.
Games launched from RPCS3 through a batch file or through the commandline that *do* include the `--no-gui` flag run at significantly worse speed.

[Fullspeed RPCS3.log.gz](https://github.com/RPCS3/rpcs3/files/5085907/Fullspeed.RPCS3.log.gz)
[--no-gui RPCS3.log.gz](https://github.com/RPCS3/rpcs3/files/5085908/--no-gui.RPCS3.log.gz)

#### Please attach screenshots of your problem.
Fullspeed:
![fulspeed](https://user-images.githubusercontent.com/12318905/90427571-b6805e80-e090-11ea-8148-8845f70ac9ca.png)

No GUI:
![slow](https://user-images.githubusercontent.com/12318905/90426997-eda24000-e08f-11ea-8de6-006a5736b0d4.png)

#### 4. Please provide comparison with real PS3.
N/A

#### 5. Please provide your system configuration:
* Windows 10 2004
* AMD Ryzen 9 3900X
* NVIDIA RTX 2070

#### Notes
Tested on the two games that I've dumped from my PS3 -- Project Diva F and Project Diva F2nd.

**Comment by Megamouse** [comment] 2020-08-17 18:30
Duplicate of #8248

**Closed by Megamouse** 2020-08-17 18:30 UTC
