### ISSUE TITLE
Formula one championship edtion

### ISSUE THREAD

**Issue by redscorp99** [RPCS3/rpcs3#2712] opened 2017-04-18 18:51 UTC
So i am pretty new at this and i cant seem to figure out what the issue is or how to resolve the issue. 
I constantly get the error of "
F {rsx::thread} struct gsl::fail_fast thrown: GSL: Precondition failure at c:\rpcs3\3rdparty\gsl\include\span.h: 1432"
Hopefully someone can help and explain to me how to resolve this issue.
Ive been dying to play this game again and i no longer have a hard copy of this game for my ps3 so this is  my best option.
Thank you in advance for the help.

**Comment by Zangetsu38** [comment] 2017-04-18 18:54
Issue already exist

**Comment by redscorp99** [comment] 2017-04-18 18:55
i am aware of that but i was not able to figure out if its been resolved or not.

**Comment by AniLeo** [comment] 2017-04-18 18:59
Duplicate of #2340

**Closed by AniLeo** 2017-04-18 18:59 UTC
