### ISSUE TITLE
DX12: 1942 Joint Strike wrong water effect (Nvidia Specific)

### ISSUE THREAD

**Issue by raven02** [RPCS3/rpcs3#1878] opened 2016-07-09 14:32 UTC
![untitled](https://cloud.githubusercontent.com/assets/3000282/16708402/fbff4148-4624-11e6-8218-ba3be2b9fb66.jpg)

**Comment by raven02** [comment] 2016-07-09 14:46
This is from one of the old 0.0.0.6 build

![1](https://cloud.githubusercontent.com/assets/3000282/16708451/ed8c0590-4626-11e6-86c9-8876715663a3.jpg)

**Comment by kd-11** [comment] 2016-07-09 17:03
@raven02 You could test for the regression. Are the other backends affected as well or only dx12?

**Comment by raven02** [comment] 2016-07-09 20:41
i'll try to find out which commit breaks it. Vulkan no more black screen but it keep crashing for me . (it is quite unstable on nvidia system and always crash)

**Comment by raven02** [comment] 2016-07-10 01:27
Alright .This is GL one .In-game but most of area are black .

![untitled](https://cloud.githubusercontent.com/assets/3000282/16711190/759a0bcc-4680-11e6-8cd8-6b64001dfedd.jpg)

**Comment by raven02** [comment] 2016-07-10 02:38
Alright . It regressed at https://github.com/RPCS3/rpcs3/pull/1455

**Comment by raven02** [comment] 2016-07-10 04:28
If anyone own this title , feel free to try it out using Vulkan to see how it looks like in-game if you are using NV system

**Comment by sirdanielk** [comment] 2016-07-10 12:35
I use Opengl and AMD card. In new version of rpcs i see HUD only, rest of the screen is black noise, and there are some effects like explodes. Like on the screen above. Previously this title was working in ogl. The commit that affected game was probably new vertex recompiler by dhrpcs3 - PR1840 
The other remaining issue is invisible bullets. When it gonna be adressed, game would be turned into playable.

**Comment by raven02** [comment] 2016-07-10 13:30
@vlj , from your previous pull https://github.com/RPCS3/rpcs3/pull/1455 , which part you think that may be related to this water effect ?

**Comment by raven02** [comment] 2016-07-10 15:32
@sirdanielk , GL is undergo WIP now so more fixes will come to GL shortly .

**Comment by raven02** [comment] 2016-07-12 07:05
@kd-11 , which part you think in this PR https://github.com/RPCS3/rpcs3/pull/1455 likely affect the water effect ?

**Comment by SakataGintokiYT** [comment] 2016-07-12 08:54
@raven02 
[06c6c821]
I have the same problem

**Comment by raven02** [comment] 2016-07-12 09:06
Thanks @SakataGintokiYT .

**Comment by kd-11** [comment] 2016-07-12 11:09
@raven02 Probably the shift to streaming vertex attributes, although I don't see why that would cause the issue here. Porting this changeset to openGL was one of my first contributions to rpcs3 and the same method is used for vulkan and opengl. The bug looks like a vertex attribute issue. There may be an issue with emulated primitives somewhere. Can you capture a frame and attach the command_dump.log?

**Comment by kd-11** [comment] 2016-07-12 11:11
Also, OpenGL is probably due to broken cull face and primitive emulation. I have fixes for most GL bugs, but I'm waiting for DH to merge his WIP branch which has some improvements.

**Comment by raven02** [comment] 2016-07-12 11:56
Thanks @kd-11 .Will try to isolate the bug and retest .

**Comment by DHrpcs3** [comment] 2016-07-12 17:22
@kd-11, I'm not sure that current WIP branch will be merged to that repository. Last commits from me to that repository will be rsx_decompiler fixes, than I will commit my changes to the my fork only. I disagree with current development roadmap (from architectural point) and I think emulator need for much more fundamental changes, wich I do in the my fork.

**Comment by kd-11** [comment] 2016-07-12 18:38
@DHrpcs3 Its unfortunate that you have to branch out on your own, but I understand. I'll try to clean up the GL backend and update the list of rsx_decompiler issues if I find any bugs there.

**Comment by AniLeo** [comment] 2016-07-12 21:04
@DHrpcs3 why not opening a PR for all of those once you're finished?

**Comment by raven02** [comment] 2016-07-13 06:35
@kd-11 . here is the command_dump.log capture from the water effect frame

[command_dump.txt](https://github.com/RPCS3/rpcs3/files/360842/command_dump.txt)

**Comment by kd-11** [comment] 2016-07-13 09:06
@raven02 How does GL behave with https://github.com/RPCS3/rpcs3/pull/1902?

**Comment by raven02** [comment] 2016-07-13 11:00
@kd-11 . It keep flashing in-game

![untitled](https://cloud.githubusercontent.com/assets/3000282/16801237/0ff0c424-492c-11e6-8871-7029868d2bbe.jpg)

**Comment by vlj** [comment] 2016-07-13 16:01
It looks like a vertex has wrong uv attributes in dx12 case, maybe it uses a register vertex attributes that went missing in the commit that breaks.

**Comment by raven02** [comment] 2016-07-13 16:11
@vlj  , i did try to isolate out the register vertex attribute but seems the game is not using it but instead the active vertex attributes.

**Comment by raven02** [comment] 2016-07-13 16:12
@kd-11 , let me check out any gcm samples that flickering .

**Comment by vlj** [comment] 2016-07-13 16:16
Maybe there is an issue with the CMP format then, looking at the command dump it looks like it's used in some place.

**Comment by raven02** [comment] 2016-07-13 16:19
@vlj .If you suspect any code that may fix it , you can let me know and i can test it out here.

**Comment by kd-11** [comment] 2016-07-14 18:22
https://github.com/RPCS3/rpcs3/issues/1907 fixes this game for ogl

**Comment by raven02** [comment] 2016-07-14 18:36
Thanks @kd-11 .This thread still valid for DX12 issue.

**Comment by sirdanielk** [comment] 2016-07-14 21:13
Game went back to previous state with ogl amd, which means visual bugs are fixed. Some small remaing glitches are still present though. Theese may be out of scope of this PR.

**Comment by kd-11** [comment] 2016-07-17 17:06
DX12 on AMD is perfect by the way. I was finally able to test and it looks good. Vulkan is however missing the lighting effect on the water as well as invisible bullets.

**Comment by raven02** [comment] 2016-07-17 17:33
Do you mean the water effect look good in DX12 on your AMD system ? if yes , then it is nvidia specific issue again

**Comment by raven02** [comment] 2016-07-20 14:52
@kd-11 , Do you mean the water effect look good in DX12 on your AMD system ?

**Comment by raven02** [comment] 2016-07-22 18:19
1942 Joint Strike seems to be freeze in bootup using DX12 in latest build  .Anybody hits this ?

**Comment by vlj** [comment] 2016-08-20 16:37
I could replicate on dx12 with nvidia, I will try to find what's happening by extending rsx debugger.

**Comment by vlj** [comment] 2016-09-10 23:52
If I disable vertex component remapping the issue is fixed with nvidia as well, which is strange.

**Comment by vlj** [comment] 2016-09-11 00:00
Ok I found the issue, will submit a patch tomorrow

**Comment by raven02** [comment] 2016-09-11 00:52
thanks @vlj

**Closed** 2016-09-12 18:38 UTC
Labels: bug, dx12, regression
