### ISSUE TITLE
Disappearing environment in Mortal Kombat vs. DC Universe [NPUB30594]

### ISSUE THREAD

**Issue by Psycho-A** [RPCS3/rpcs3#4833] opened 2018-06-30 02:27 UTC
Game works fast, but there are black screens on some main menu background screens, and in game process, including invisible fighters. "Write color buffers" partially helps, but still there are lots of locations and fighting effects that gives black screens with HUD on it, or partial environment disappearing when just some light or effect stays, and no more.

NVidia GTX 750 Ti with latest drivers, Vulkan, Windows 7 x64.

**Comment by Rpcs3tester** [comment] 2018-07-03 14:54
@Psycho-A 

you need to check to GPU additional setting:

-use GPU texture scaling

-strict rendering mode

-Vsync

-stretch to display area

**Comment by AniLeo** [comment] 2018-07-06 18:10
Is this an issue with Strict Rendering Mode? The other options are not important for accuracy.

**Comment by DenisHeiden** [comment] 2018-07-07 01:49
@AniLeo 

all mentioned options are required  before the recent build 0.0.5-7069

I can confirm that issue fixed only with Strict Rendering Mode.

**Comment by digitaldude555** [comment] 2020-02-07 15:47
Its been nearly two years time for update. @Psycho-A

**Comment by benderscruffy** [comment] 2020-02-11 11:34
please close due to no activity for over a year

**Comment by AniLeo** [comment] 2020-02-22 11:39
Needs retesting, can't close just yet. If no retesting is provided, then yes
Make sure to use SRM if it doesn't work without it

**Comment by Psycho-A** [comment] 2020-02-22 21:34
Tested on last month builds. Generic disappearing is gone, but still characters may disappear during making some special moves and effects.

**Comment by AniLeo** [comment] 2020-03-03 10:04
There's a similar issue with GH5. Not sure if it's related, or whether it's an RSX or CPU side bug.

**Comment by digitaldude555** [comment] 2021-01-28 15:43
@Psycho-A retest

**Comment by Xcedf** [comment] 2021-09-18 21:30
Game works fine, and i guess for a long time, same issue MK9 once had.
Anti-Aliasing enabled required, no WCb or SRM or any other needed, scaling works.
Issue should be closed.

**Closed** 2021-09-19 03:54 UTC
Labels: Need Information
