### ISSUE TITLE
Constant Freezing and Errors on games

### ISSUE THREAD

**Issue by whatcorey** [RPCS3/rpcs3#10274] opened 2021-05-13 07:04 UTC
## Quick summary
Most playable games on Rcps3

## Details

I have the latest version for Rcps3, i used DDU and did a fresh install of my graphics card drivers, but am still freezing then crashing on some games i play, specifically dbz ultimate tenkaichi, no idea what to do at this point but just stick to playing it on my console since it isn't working for me on here? I will post the log on here,

I don't use discord, sorry.

#### 1. Please attach RPCS3's log.
[RPCS3.log](https://github.com/RPCS3/rpcs3/files/6470819/RPCS3.log)

#### 3. Please attach screenshots of your problem.
![errorr](https://user-images.githubusercontent.com/35015068/118090531-898e7d00-b37e-11eb-99b9-1168d126d1db.png)
![error2](https://user-images.githubusercontent.com/35015068/118090543-8c896d80-b37e-11eb-81bf-71221992c928.png)

#### 4. Please provide comparison with real PS3.
No issues on PS3

#### 5. Please provide your system configuration:
* OS: Windows 10 Pro
* CPU: i7 10875h 2.30 ghz
* GPU: RTX 2070 Super 8gb
* Driver version: 27.21.14.6627 Nvidia
* etc. 32 gig of ram

**Comment by YuriNator557** [comment] 2021-05-15 18:58
Please run the following tool: https://github.com/13xforever/vkdiag/releases/latest
This issue is most likely caused by a faulty FPS monitoring software.

**Comment by whatcorey** [comment] 2021-05-15 22:29
![asdg](https://user-images.githubusercontent.com/35015068/118379823-61776780-b592-11eb-96f6-82185d1fb766.png)

**Comment by AniLeo** [comment] 2021-05-21 21:27
Duplicate of #10273

If you don't use Discord, there are other listed platforms on [How to ask for Support](https://github.com/RPCS3/rpcs3/wiki/How-to-ask-for-Support) such as Forums

---

**Please read [**the guidelines**](https://github.com/RPCS3/rpcs3/blob/master/.github/CONTRIBUTING.md) before opening an issue.**

Remember that the GitHub Issue Tracker is not the place to [**ask for support**](https://github.com/RPCS3/rpcs3/wiki/How-to-ask-for-Support) or to [**submit Game Compatibility reports**](https://github.com/RPCS3/rpcs3/wiki/Game-Compatibility).

The issue has been marked as **Invalid** and closed.

**Closed by AniLeo** 2021-05-21 21:27 UTC
