### ISSUE TITLE
[Feature request] Please let the user bind the PS Move buttons

### ISSUE THREAD

**Issue by Johnramirezwilson** [RPCS3/rpcs3#15461] opened 2024-04-15 14:08 UTC
### Quick summary

Currently, the PS Move trigger button is bound to the middle mouse click.

### Details

I'd like to play Time Crisis 4 using a Wiimote to emulate the mouse movement with Touchmote. However, Touchmote can't bind the middle mouse button, only left and right buttons. This makes it impossible to use Wiimote for playing Guncon 3 games.

EDIT: The middle mouse click actually is the X button. However, it would be nice if the user could set the keys.

**Comment by AniLeo** [comment] 2024-04-28 19:04
Closing as duplicate of #13093

**Closed by AniLeo** 2024-04-28 19:04 UTC
Labels: PSMove
