### ISSUE TITLE
All games crashing after v0.0.12-10945

### ISSUE THREAD

**Issue by githuborer** [RPCS3/rpcs3#9421] opened 2020-12-12 17:34 UTC
Hello.
Latest version I can use is v0.0.12-10945. Since then all games crashing (window is closing) after running for a half sec.
When I copy files back from v0.0.12-10945 zip its working again. Tried different games and different rpcs3 versions after v0.0.12-10945. No luck.

Already posted here:
https://www.reddit.com/r/rpcs3/comments/jhvl4s/no_games_loading_after_v001210945/

#### Please provide your system configuration:
AMD Ryzen 7 3700X 8-Core Processor | 16 Threads | 15.92 GiB RAM | TSC: 3.600GHz | AVX+ | FMA3
Operating system: Windows, Major: 10, Minor: 0, Build: 18362, Service Pack: none, Compatibility mode: 0
'AMD Radeon RX 5700 XT' running on driver 2.0.168

Anything else you deem to be important:
- Running my games from smb nas

[RPCS3.log](https://github.com/RPCS3/rpcs3/files/5683499/RPCS3.log)

**Comment by leonardo2707** [comment] 2020-12-13 00:23
I can confirm that issue too. I was playing final fantasy xii and after update the game stop working.

I use a flatpak version of the RPCS3, there are two updates at the same day 2020-12-10 on flathub, and all of them make the game stop working, after I rollback the RPCS3 with the version launched on flathub at 2020-11-09 with commit 1745f313bb500bf9864efeee3211bf410ecd5e3a96af6df0c7e702769ae647c9 the game back to run. (are two updates back)

if someone are using the flatpak version, the command below will rollback to the version that was working

<code>sudo flatpak update --commit=1745f313bb500bf9864efeee3211bf410ecd5e3a96af6df0c7e702769ae647c9 net.rpcs3.RPCS3</code>

honestly, i don't see any difference at the log of the version that works and on that not works, I don't know what have changed in the last update;

but i am willing to test if necessary, just send me the .flatpak file that i install next to the current version to test. it doesn't hurt at all since flatpak is all containers. :b

**Please provide your system configuration:**

Distro: Arch Linux
Kernel: 5.9.13-arch1-1
GPU: RX 580 (Mesa 20.3.0)
CPU: Ryzen 5 2600X
Memory: 16GB

**Comment by AniLeo** [comment] 2020-12-13 14:12
Duplicate of #9291

**Closed by AniLeo** 2020-12-13 14:12 UTC
