### ISSUE TITLE
Unreadable text in Black Ops 2

### ISSUE THREAD

**Issue by guy224444** [RPCS3/rpcs3#12506] opened 2022-08-13 03:18 UTC
### Quick summary

The text in Black Ops 2 isn't readable and shows looking like lines

### Details

When starting up black ops 2 on the emulator the first thing you're shown is whether you want to play the campaign, multiplayer, or zombies, and the text that shows these options is unreadable, as far as I know the rest of the text in the game also shows up like this and is unreadable except for the black ops 2 logo on the loading screen and some other text before you're taken to the main menu.

### Attach a log file

https://mega.nz/file/aBBwQYqY#ff3MM5v36_8ZQ3J07VSiiPYlaW--EEnzgIpMAsnENG8

**Comment by RainbowCookie32** [comment] 2022-08-13 03:21
Duplicate of #8718

**Comment by MSuih** [comment] 2022-08-13 03:21
Duplicate of #8718

**Closed** 2022-08-13 03:21 UTC
