### ISSUE TITLE
function get_renderpass_key not working properly (unsupported image layout)

### ISSUE THREAD

**Issue by jokoputera** [RPCS3/rpcs3#10286] opened 2021-05-16 03:41 UTC
## Quick summary
Uncharted : Drake Fortune randomly freeze (usually around 25 sec) with log : F SIG: Thread terminated due to fatal error: Unsupported image layout 0x5
(in file **D:\a\1\s\rpcs3\Emu\RSX\VK\VKRenderPass.cpp:83[:25]**, in function get_renderpass_key) 

## Details
OpenGL works fine, and Vulkan used to work well

#### 0. Make sure you're running with settings as close to default as possible
no matter what combination i used (except using OpenGL) and without patches, game will not work. 

#### 1. Please provide _exact_ build (or commit) information that introduced the regression you're reporting.
latest build

##### How to obtain RPCS3's log:
[log.txt](https://github.com/RPCS3/rpcs3/files/6489340/log.txt)

F SIG: Thread terminated due to fatal error: Unsupported image layout 0x5
(in file **D:\a\1\s\rpcs3\Emu\RSX\VK\VKRenderPass.cpp:83[:25], in function get_renderpass_key)**
S RSX: Program compiled successfully

#### 4. Please attach screenshots of your problem.
![Screenshot (5)](https://user-images.githubusercontent.com/59791277/118384705-87ecdf80-b632-11eb-8aae-2774c9fa3519.png)

#### 6. Please provide your system configuration:
* OS Windows 10 64bit
* CPU Ryzen 5 3600
* GPU GTX 1660 Super
* Driver version Latest
* etc.

#### Please include.
* Anything else you deem to be important
* ive read KD-11 able to fix these functions in similar cases like in this https://github.com/RPCS3/rpcs3/issues/9995 and this https://github.com/RPCS3/rpcs3/issues/10263
* so maybe @kd-11 able to fix this one too

thanks

**Comment by sampletext32** [comment] 2021-05-16 11:36
Please upload a `RPCS3.log` file or it's `.gz` version here. This wall of log is nuts.

**Comment by jokoputera** [comment] 2021-05-16 14:04
edited : move log into txt

**Comment by YuriNator557** [comment] 2021-05-16 15:45
What you have uploaded is not the log file,. it is just the contents of the log shown in the GUI, which is missing most of the useful information. Please upload the one generated by RPCS3, it will be directly under the .exe on Windows.

**Comment by AniLeo** [comment] 2021-05-16 15:52
> 1. Please provide exact build (or commit) information that introduced the regression you're reporting.
> latest build

This is not valid. You need to indicate the exact build that introduced the regression.

**Comment by AniLeo** [comment] 2021-05-16 15:53
Closing as duplicate of #9887

**Closed by AniLeo** 2021-05-16 15:53 UTC
Labels: Need Information
