### ISSUE TITLE
Almost Every Graphic's Problems On Project Diva F 2nd [BLUS31431]

### ISSUE THREAD

**Issue by Sangabc** [RPCS3/rpcs3#3194] opened 2017-08-11 03:12 UTC
There are a lots of Graphical Problem in PDF 2nd but here is the sum up of them and there actually only four problem
First the little problem: Wrong Shader on Stage
The Stage display weirdly like the are little sparkling thing on them and almost every song have it, pretty sure it is just like Dreamy Theater Extend and 2nd
Most noticeable is Romeo to Cinderella and This is the happiness commitee and peace of mind (I forgot the name of the song)
Second Problem: Movies Cut
-Meteor
-Melt
-Erase or Zero
-Kowase Kowase
-Decorator (For some reasons sometime the movie play normaly on this song) 
Every movies play in game except the opening is cut on the right just look at the pictures
Third Problem: Transparency Error
Every Character transparent show their inside instead of their outside (I think it maybe the OpenGL glitch?)
-Akatuski Arrival
-Glory 3usi9
-Meteor
-Soundless Voice
-Erase or Zero
Four the Major Problem: The Red Stage and distortion
-Melt
-Luka Luka Night Fever
-Knife (only have red distortion in character model)
-magnet (Very Serious)
-Rosary Pale
-When First Love Ends
-Blackjack (Very Serious)
-2d Dream Fever (Extremly Serious)
-Package
-Wintry Winds (Very Serious)
Extra Tiny Problem: Water
The water in game look kinda weird but i think it ok
-Promise
-MeltDown (Roshin Rukai) 
![2d dream fever red](https://user-images.githubusercontent.com/29393657/29199964-9004ef70-7e7b-11e7-8f13-d8c5ca2b308d.png)
![blackjack and the whole stage is way too bad](https://user-images.githubusercontent.com/29393657/29199969-900f948e-7e7b-11e7-8869-08df3c33a767.png)
![glory 3usi9 transparent](https://user-images.githubusercontent.com/29393657/29199965-9008f5ac-7e7b-11e7-9c4b-6f6427d92511.png)
![i ll miku miku you](https://user-images.githubusercontent.com/29393657/29199967-9009a4ac-7e7b-11e7-9024-c4686fa9d455.png)
![magnet red](https://user-images.githubusercontent.com/29393657/29199968-9009d3be-7e7b-11e7-93cb-c1cf985c5891.png)
![melt movie cut](https://user-images.githubusercontent.com/29393657/29199966-9009377e-7e7b-11e7-8168-d9c2308794df.png)
![melt red color](https://user-images.githubusercontent.com/29393657/29199970-903ae85a-7e7b-11e7-969b-c10848e7ef27.png)
![meteor movie cut](https://user-images.githubusercontent.com/29393657/29199973-904137a0-7e7b-11e7-9d81-b86ab8ce91d9.png)
![package corrupted stage](https://user-images.githubusercontent.com/29393657/29199972-90406762-7e7b-11e7-9133-2cfe35b3ba3a.png)
![romeo to cinderella wrong shader](https://user-images.githubusercontent.com/29393657/29199971-903d9906-7e7b-11e7-9e57-f8641c19aa2e.png)

**Comment by hcorion** [comment] 2017-08-11 04:30
Post RPCS3.log (just one will be good), Also, are you on Linux or Windows?
What build are you using? (make sure your using the latest one from https://rpcs3.net/download)
What CPU and GPU does this computer have? What GPU drivers?

**Comment by Sangabc** [comment] 2017-08-11 04:34
Already The Latest Build
Windows
Vulkan got the same glitch!
My Specs:
i5 4690
ram 8gb
Nvidia 1060 3gb

**Comment by MaikelChan** [comment] 2017-12-10 20:01
Hi everyone!

I originally created a new issue about this problem, but since it was a duplicate, I closed it and I'm going to post here. Just wanted to add a little bit of extra info.

It appears that those weird red, green and blue color splotches show because of some weird clamping values used when applying the bloom post-process. As you can see in the fragment shader, there are a lot of clamps with min and max values of -65504 and 65504. I don't know if that is how it's supposed to be? I found it a bit weird. Anyway, changing them to 0 and 1 fixes the issue.

Some screenshots from Renderdoc with and without the issue:

![1](https://user-images.githubusercontent.com/7031754/33808378-8f5c12f0-dde5-11e7-9e08-6bacaa7f5f6e.png)
![2](https://user-images.githubusercontent.com/7031754/33808379-8f7868e2-dde5-11e7-8df8-8f0c35f29f15.png)


The selected lines are the ones I changed in order to fix the weird colors. But it darkens the image a little bit, so it's not the correct fix, but I don't know exactly how it should be. This happens with all graphic backends.

Specifications:
RPCS3 0.0.4-6216-60f5929f.
Windows 10 Pro x64.
Intel(R) Core(TM) i7-2600K CPU @ 3.40GHz
8 Threads
9.98 GiB RAM
AVX+
GeForce GTX 980

[RPCS3.log.gz](https://github.com/RPCS3/rpcs3/files/1546006/RPCS3.log.gz)

**Comment by kd-11** [comment] 2017-12-10 21:23
16-bit floats have a range of -65504 to +65504. Removing the clamping will break other games like naruto. The range is also confirmed by nvidia on their site, there is a link to it in the decompiler code somewhere. Clamping to [0, 1] is controlled by the saturate flag bit which is not set for those particular instructions, so the range is clamped to the 16-bit range. It is likely that the games hit a corner case in nvidia's exp2 implementation. Similar strangeness has been observed in other instructions where the hardware does not comply to IEEE standards.

**Comment by MaikelChan** [comment] 2017-12-10 21:40
Thanks for the answer. Even if I'm not too much of an expert, I wanted to take a look mainly for learning purposes. So it is good to know that.

I've been investigating a little bit more, and I found out that those log2 are generating NaNs because of receiving negative values. And that's all what I'm able too see because I don't know what the previous lines are supposed to be doing.

**Comment by kd-11** [comment] 2017-12-10 22:04
Old nvidia chips are not IEEE compliant and will happily accept negative values and even sqrt(0) and 1/0 generate valid numbers, we already have several instructions marked as special because of this. Check if https://github.com/kd-11/rpcs3/commit/06876a285bfffb41bfaa3ff9ac03e77d6880109f helps with the Nan issue.

**Comment by MaikelChan** [comment] 2017-12-10 22:31
Amazing, now it works great!

![3](https://user-images.githubusercontent.com/7031754/33810192-372f91ac-de02-11e7-80a9-a7edc8fc2448.jpg)

**Comment by kd-11** [comment] 2017-12-10 22:40
Well, that means LG2 also qualifies on the list of wierd/broken instructions on ps3. Looks like log2(0) is some large number and log2(negative) just uses absolute value instead. I don't know if the other games listed here are the same bug since I don't have the rdc. Thank you @MaikelChan for looking into the bug.

**Comment by MaikelChan** [comment] 2017-12-10 22:53
There are several bugs posted here. One of them, the one about the movies being cut, is actually a regression I think. They worked ok some months ago, but I don't know exactly when they broke.

**Comment by kd-11** [comment] 2017-12-10 23:00
The cuts are clipping errors in blit engine. I usually avoid tinkering with it too much since it requires significant time investment to fix issues and touching one small issue can end up in a rewrite. They can probably be fixed by just using the software mode in debug settings. I dont have any games with the clipping errors though since only PDF 2 and silent hill downpour are reported to exhibit the issue.

**Comment by MaikelChan** [comment] 2017-12-11 17:07
Another small graphical problem the game has is related to masking UI elements in Vulkan. It works fine with OpenGL.

In some song titles, menu elements, etc. there are black areas around them. They are from masks used for transitions and stuff like that. It is a very simple shader, it just multiplies the alpha of the mask with the alpha of the UI texture. But for some reason in Vulkan it doesn't work correctly, even though the shader does the same (or at least I think it does) and the mask texture is the same. The only difference I see is that in Vulkan the Play texture is blue instead of red even though it appears red in-game in both backends.

OpenGL and Vulkan screenshots:

![gl](https://user-images.githubusercontent.com/7031754/33843414-9be3acd2-de9d-11e7-83d3-c232763db6bc.png)
![vk](https://user-images.githubusercontent.com/7031754/33843415-9bff6e40-de9d-11e7-92f7-db9394bc97f8.png)

I have zero experience with Vulkan. Renderdoc doesn't seem to support editing Vulkan shaders. Any recommendation for that?

**Comment by MaikelChan** [comment] 2017-12-12 03:18
Well, I managed to edit vulkan shaders by pasting in Renderdoc the one generated by the rpcs3 shader log. This is what I found out:

Modified the shader to show the alpha of the mask. There are discrepancies between GL and Vulkan:
![gl1](https://user-images.githubusercontent.com/7031754/33865422-f97da092-def1-11e7-8602-7918d79459e5.png)
![vk1](https://user-images.githubusercontent.com/7031754/33865426-f9df28c6-def1-11e7-87e4-d48ac10e3360.png)

The mask has a different format and different clamping modes in each backend:
![gl2](https://user-images.githubusercontent.com/7031754/33865423-f9954904-def1-11e7-8fbb-af198f511200.png)
![vk2](https://user-images.githubusercontent.com/7031754/33865428-f9fa12b2-def1-11e7-994b-34d1f39e0e56.png)

However, the main problem is actually in the alpha of the Play texture (notice how this also affects to some background effects too):
![gl3](https://user-images.githubusercontent.com/7031754/33865424-f9adb66a-def1-11e7-980a-6335952ec0cb.png)
![vk3](https://user-images.githubusercontent.com/7031754/33865429-fa19558c-def1-11e7-9199-4efd6a37e6b9.png)

As with the mask texture, the Play texture has different formats and clamping modes:
![gl4](https://user-images.githubusercontent.com/7031754/33865425-f9c68ab4-def1-11e7-9430-76719fc40508.png)
![vk4](https://user-images.githubusercontent.com/7031754/33865430-fa341606-def1-11e7-9e1e-438900abab35.png)

Maybe the format is not actually the problem, I don't know how Vulkan works and if it's normal or not that difference. But the clamping seems suspicious.

**Comment by kd-11** [comment] 2017-12-12 06:20
Clamping modes are the same with exception of boder color.which you cannot freely change using vulkan, you have to choose between 4 presets and thats it. The algorithm can be tweaked a bit to choose a better match but it's something that will always be a problem unless we write our own sampling routines. Also, number of formats on vulkan is usually shockingly low as it is the true number supported by the gpu. Most opengl and directx formats are emulated. In this case, we handle emulation ourselves.

**Comment by Sangabc** [comment] 2017-12-12 13:25
What about the Third Problem: Transparency Error

**Comment by kd-11** [comment] 2017-12-12 14:53
I have not seen any captured traces of that bug

**Comment by MaikelChan** [comment] 2017-12-13 05:16
If you mean a Renderdoc trace, here it is: [http://www.mediafire.com/file/21ahfc5e7dhhefi/transparency.7z](url)

**Comment by MaikelChan** [comment] 2018-01-01 02:56
Nice. I don't know what build fixed it, but those UI mask problems have disappeared.
![diva](https://user-images.githubusercontent.com/7031754/34465322-b44e27f6-eea7-11e7-86b9-94ffedb952e6.jpg)

**Comment by kd-11** [comment] 2018-01-01 12:43
Interesting. I hadn't started looking into this one yet, probably fixed when fixing some other bug. Likely the last merged PR which fixed some framebuffer configuration bugs.

**Comment by kd-11** [comment] 2018-01-22 12:10
Some format fixes were recently merged. Please retest if any issues are left.

**Comment by MaikelChan** [comment] 2018-01-22 15:38
From what I've tested, this game works exactly the same. It still has the transparency problems on characters and cropped videos (In Diva F videos appear correctly). I don't know if I'm forgetting something.

**Comment by Lemiru** [comment] 2018-01-22 15:58
There is one more issue that (I think) is exclusive to "love-hate" song. In this song some object doesn't render correctly, like for example those babies:
![screen shot 01-22-18 at 01 50 pm 001](https://user-images.githubusercontent.com/25465452/35230015-38314c80-ff95-11e7-8e79-c705e3cae259.PNG)

**Comment by EliEron** [comment] 2018-01-24 20:35
There is one other bug that I've noticed. Which is that flash-to-white transitions doesn't seem to render quite right. This occurs in multiple songs but is easiest to notice in songs like "Erase or Zero" due to it having a very large amount of them.

Here is a video of the song on RPCS3:
https://youtu.be/Ba_OLCJDmn0?t=20

And here is a video of the game on real hardware:
https://youtu.be/bv5BjQ0eYp4?t=24

If you look at the white transitions at the beginning there is a pretty clear difference, on RPCS3 the white does not actually get bright enough to hide the screen, and it seems to linger for quite a bit longer than it's supposed to.

Also while playing around with graphics settings trying to solve the above issue, I discovered that if you disable "GPU Texture Scaling" then that appears to fix the cropped video issue. At least it fixes it for me on "Erase or "Zero". Though the video is pretty laggy so it's not quite the same as on real hardware.

**Comment by MaikelChan** [comment] 2018-01-24 21:10
Those flashes shouldn't happen in that PV. I can also see some desynced videos in your youtube video. I think all that is just because of the 60fps patch. The game is intended to run at 30fps, and the patch, although it is playable, it breaks videos and desyncs other stuff.

**Comment by EliEron** [comment] 2018-01-24 21:42
Ah you are entirely right, with the 60fps patch disabled all of the light flash bugs go away. I have had that patch enabled for so long that I literally forgot about it. If I had then I would have tested with it disabled before reporting anything here.

So sorry about that, and thank you for clarifying that issue for me. That flashing issue occurred in quite a few songs and was quite distracting, enough so that I will probably just keep the 60fps patch disabled from now on.

Also as a side note with the 60fps patch disabled and "Use GPU Texture Scaling" disabled the videos now play without any cropping issues and at their proper speed.

**Comment by MaikelChan** [comment] 2018-01-24 22:25
No need to be sorry. And it's good to know that the cropping issues can be fixed with GPU Texture Scaling. Maybe it will make things easier for the developers to fix. It's interesting how in the first Diva F they work perfectly.

**Comment by hbzlmx** [comment] 2018-01-26 16:10
Hi, I'm also complain from saturated hue color with playing prince of Persia epilogue as seen
<a href="https://ibb.co/mBirbw"><img src="https://preview.ibb.co/bX1cGw/Untitled.png" alt="Untitled" border="0"></a>
<a href="https://ibb.co/fd8opG"><img src="https://preview.ibb.co/hx18pG/Untitled2.png" alt="Untitled2" border="0"></a>

**Comment by Lemiru** [comment] 2018-01-26 16:12
@hbzlmx Wrong Issue.

**Comment by zack4488** [comment] 2018-02-04 04:48
![image](https://user-images.githubusercontent.com/34994511/35774421-a1d7d6d6-09a9-11e8-9a6d-af645a38075c.png)

Still have problem...

**Comment by slashiee** [comment] 2018-07-12 08:11
Here's RSX captures (and logs) of the two reminding issues that I have seen: outline only appearing on some models and broken transparency
![2018-07-12_01-04-36](https://user-images.githubusercontent.com/15317421/42620396-b31782f6-856f-11e8-8aea-518cb3b90861.png)
[IevanPolkka.zip](https://github.com/RPCS3/rpcs3/files/2187662/IevanPolkka.zip)
[RPCS3.log.gz](https://github.com/RPCS3/rpcs3/files/2187674/RPCS3.log.gz)

![2018-07-12_01-04-29](https://user-images.githubusercontent.com/15317421/42620428-c9d8eb74-856f-11e8-8e37-1005bf5d7c82.png)
[DoubleGanger.zip](https://github.com/RPCS3/rpcs3/files/2187664/DoubleGanger.zip)
[RPCS3.log.gz](https://github.com/RPCS3/rpcs3/files/2187707/RPCS3.log.gz)

**Comment by kd-11** [comment] 2018-09-15 10:38
which issue is left? Someone needs to make a checklist so we can know when its fully fixed.

**Comment by EliEron** [comment] 2018-09-15 12:39
Here is a checklist based on the bugs that have been reported in this issue (checked items have been fixed):

- [x] Many stages suffer from color corruption
- [x] Background movies do not play or render properly
- [x] Models look broken when transparency is applied
- [x] Black boxes around some UI elements on Vulkan 
- [x] Some models are only rendered as silhouettes

As you can see the problems reported in this issue have all been dealt with, at least as far as I can tell. 

I have not tested every song in the game, but of the ones I have played none have exhibited any noticeable issues. And I made sure to test some of the stages that were reported to have issues with color corruption, movie playback, silhouettes, transparency, etc.

**Comment by Pikota3124** [comment] 2018-09-15 12:47
I can say there is nothing left to fix, I play Hatsune Miku a lot and I dont see anything wrong.

**Comment by AniLeo** [comment] 2018-09-15 13:08
Closing as fixed, if anything remains it can be reopened

**Closed by AniLeo** 2018-09-15 13:08 UTC

**Comment by MaikelChan** [comment] 2018-09-18 16:18
The only thing left, I think, are the videos being cropped at the bottom.

**Comment by Cristallix** [comment] 2018-09-18 16:29
@MaikelChan I've had this too, but not anymore. I don't know which is triggering this.

**Comment by vietnam13231** [comment] 2018-09-18 16:35
Turn off "Use GPU Texture Scaling".

**Comment by Pikota3124** [comment] 2018-09-18 16:42
@MaikelChan If with cropped you mean this.

http://i67.tinypic.com/dbpr9s.png

You must have this settings to fix it.

http://i63.tinypic.com/afacmh.png

**Comment by Cristallix** [comment] 2018-09-18 16:44
@vietnam13231 It was that indeed. Thanks!

**Comment by MaikelChan** [comment] 2018-09-18 16:51
@vietnam13231 @Pikota3124 Thanks, I didn't know about that!

**Comment by vietnam13231** [comment] 2018-09-24 08:13
OpenGL fixed with KD's last update. Works about perfect.
