### ISSUE TITLE
Resogun - Crash on OpenGL

### ISSUE THREAD

**Issue by mjd180** [RPCS3/rpcs3#11941] opened 2022-05-05 16:24 UTC
Unlike on Vulkan, 'Resogun' crashed every time on OpenGL with default settings. It boots normally before crashing the emulator upon "press x to continue". Tested on both EUR & US PSN versions, with or without update.

System Configuration:
Windows 11
Ryzen 5 2600
Nvidia GTX 1660 (512.59
[RPCS3.zip](https://github.com/RPCS3/rpcs3/files/8633007/RPCS3.zip)
)

**Comment by mjd180** [comment] 2022-05-05 17:19
This should be reclassed under "regression". Confirmed working on build 0.0.6-8464 (Aug 2019).

**Comment by kd-11** [comment] 2022-05-11 19:18
This games works just fine with default settings. Try resetting your settings to default by opening the configuration dialog and clicking on the default settings button in the bottom left corner.
![image](https://user-images.githubusercontent.com/15904127/167928595-f8da8bcf-a53f-452a-b805-2163b264abac.png)

**Comment by mjd180** [comment] 2022-05-11 22:55
Unfortunately, doesn't work for me. My interest piqued, I decided to dig down into the old builds to really narrow down my problem. 0.0.20-13282 (https://github.com/RPCS3/rpcs3/pull/11525 breaks it for me. All prior builds are fine. And the changes in that particular build appear mundane to my untrained eye ("rsx: Minor cleanup of format routines"). Nevertheless, that's the one that does it for me...

**Comment by Illynir** [comment] 2022-05-17 16:51
Confirmed.

**Comment by kd-11** [comment] 2022-05-18 16:34
Try with https://github.com/RPCS3/rpcs3/pull/12029

**Comment by kd-11** [comment] 2022-05-21 11:42
It seems this bug only affects NVIDIA turing and newer.

**Comment by kd-11** [comment] 2022-05-28 20:33
Try with https://github.com/RPCS3/rpcs3/pull/12114

**Comment by mjd180** [comment] 2022-05-29 13:52
> Try with #12114

Excellent/Problem resolved!

**Comment by kunit1** [comment] 2022-06-01 02:26
Should this issue be closed since the PR has been merged and issue is resolved? Just a reminder.

**Closed** 2022-06-01 06:08 UTC
Labels: Render: OpenGL, Regression, Driver: NVIDIA, In Progress
