### ISSUE TITLE
Demon Souls regression after 8664

### ISSUE THREAD

**Issue by VeroxinFox** [RPCS3/rpcs3#8692] opened 2020-08-05 08:37 UTC
## Quick summary
Demons Souls, warping, entering fog gates, object and NPC glitches

## Details
Occasionaly warping between areas and entering fog gates in Demons Souls would cause a "Access violation writing location 0xff000004 (unmapped memory)" error and crash along with some objects/NPCs having vertex glitches.

####  Please provide _exact_ build (or commit) information that introduced the regression you're reporting.
https://github.com/RPCS3/rpcs3/pull/8664

[Build with Regression.gz](https://github.com/RPCS3/rpcs3/files/5027117/Build.with.Regression.gz)
Build that works as expected: https://drive.google.com/file/d/1R1KLfufz1z5Ys5YVwkD3x-aSSAERu1Cn/view?usp=sharing 

####  Please attach screenshots of your problem.
(https://user-images.githubusercontent.com/69237999/89390594-903fe380-d6cc-11ea-9040-024afe1d3669.png)
(https://user-images.githubusercontent.com/69237999/89390643-a2ba1d00-d6cc-11ea-9890-e4ca6e3cbcec.png)

####  Please provide your system configuration:
* Windows 10 (Build 19041.338
* Ryzen 5 6500
* GTX 1080 Ti
* Driver version 451.67

**Comment by Asinin3** [comment] 2020-08-05 09:04
Pretty sure this is unrelated. Vericies explosions were caused by: https://github.com/RPCS3/rpcs3/pull/8664

**Comment by illusion0001** [comment] 2020-08-05 09:12
As of updated_sec branch on https://github.com/RipleyTom/rpcs3/commit/97cc137 does not have #8664 merged.

**Comment by kd-11** [comment] 2020-08-05 09:42
Explosions are apparently caused by some Cell PR and not https://github.com/RPCS3/rpcs3/pull/8664.

**Comment by flashmasta** [comment] 2020-08-05 18:07
I can reproduce this every time when entering the fog to get to Vanguard, about 2 minutes into the tutorial.

**Comment by illusion0001** [comment] 2020-08-05 18:25
Please test #8694 with no ppu cache

**Comment by kd-11** [comment] 2020-08-05 19:58
Probably fixed by https://github.com/RPCS3/rpcs3/pull/8696. At least crash at vanguard is confirmed fixed. Not sure if it affects vertex explosions, hopefully it solves both issues.

**Closed** 2020-08-05 20:23 UTC
Labels: RSX, Regression
