### ISSUE TITLE
Gran Turismo 6 RSXIO memory not mapped error

### ISSUE THREAD

**Issue by Wizzy2018** [RPCS3/rpcs3#6275] opened 2019-07-28 10:16 UTC
RPCS3 v0.0.6-8424
CPU Ryzen 7 1700
RAM DDR4-2400Mhz
GPU RX 470 4Gb
Windows 10 x64

I getting this error everytime i tried change settings and all but still on my system a game crashes when i want to purchase a Honda at begining of the game.

[RPCS3.log.gz](https://github.com/RPCS3/rpcs3/files/3439045/RPCS3.log.gz)

**Comment by Wizzy2018** [comment] 2019-07-28 10:20
Here are a video of flashing black screen can someone tell me why i have this errors?? Is my cpu slow and that's why??
[FPS_ 12.02 _ Vulkan _ 0.0.6-8424 _ Gran Turismo®6 [BCES01893] 2019-07-28 12-17-31.zip](https://github.com/RPCS3/rpcs3/files/3439054/FPS_.12.02._.Vulkan._.0.0.6-8424._.Gran.Turismo.6.BCES01893.2019-07-28.12-17-31.zip)

**Comment by elad335** [comment] 2019-07-28 10:23
Duplicate of #5802 , close issue.

**Comment by Wizzy2018** [comment] 2019-07-28 10:42
I update a game to 1.03 version now i got this kind of error 
 RSX: class std::runtime_error thrown: Assertion Failed! Vulkan API call failed with unrecoverable error: Out of video memory (VRAM) (VK_ERROR_OUT_OF_DEVICE_MEMORY)
Is there a solution for this?? or my settings are bad?

**Comment by AniLeo** [comment] 2019-07-28 16:05
Closing as duplicate

**Closed** 2019-07-28 16:05 UTC
