### ISSUE TITLE
NI NO KUNI [BLES01555] random freeze

### ISSUE THREAD

**Issue by psennermann** [RPCS3/rpcs3#4334] opened 2018-03-24 18:51 UTC
The game NI NO KUNI [BLES01555] keeps on random freezing (game image stuck, music still playing and fps showing normal but game no more running with no more input available), sometimes with violet error message:

F {rsx::thread} class std::runtime_error thrown: Unknown magnify filter 0x0
(in file Emu\RSX\gcm_enums.cpp:631)

but most of the time with the following red error message:

E {rsx::thread} RSX: Invalid register index (load=268104, index=0)
E {rsx::thread} RSX: Invalid register index (load=268104, index=1)
E {rsx::thread} RSX: Invalid register index (load=268104, index=2)
E {rsx::thread} RSX: Invalid register index (load=268104, index=3)
E {rsx::thread} RSX: Invalid register index (load=268104, index=4)
E {rsx::thread} RSX: Invalid register index (load=268104, index=5)
E {rsx::thread} RSX: Invalid register index (load=268104, index=6)
E {rsx::thread} RSX: Invalid register index (load=268104, index=7)
E {rsx::thread} RSX: Invalid register index (load=268104, index=8)
E {rsx::thread} RSX: Invalid register index (load=268104, index=9)
E {rsx::thread} RSX: Invalid register index (load=268104, index=10)
E {rsx::thread} RSX: Invalid register index (load=268104, index=11)
E {rsx::thread} RSX: Invalid register index (load=268104, index=12)
E {rsx::thread} RSX: Invalid register index (load=268104, index=13)
E {rsx::thread} RSX: Invalid register index (load=268104, index=14)
E {rsx::thread} RSX: Invalid register index (load=268104, index=15)
E {rsx::thread} RSX: FIFO: RET found without corresponding CALL. Discarding queue

followed by this one when you close game window:

E {PPU[0x100001a] Thread (fios mediathread 12) [0x01db4ae0]} Stat: 'sys_fs_stat' failed with 0x80010006 : CELL_ENOENT, “/dev_bdvd/PS3_GAME/USRDIR/HDD_GAMEDATA/hd05.adat” [x6]
E {PPU[0x100001a] Thread (fios mediathread 12) [0x01db4ae0]} Stat: 'sys_fs_stat' failed with 0x80010006 : CELL_ENOENT, “/dev_bdvd/PS3_GAME/USRDIR/HDD_GAMEDATA/hs06.adat.sdat” [x6]
E {PPU[0x100001a] Thread (fios mediathread 12) [0x01db4ae0]} Stat: 'sys_fs_stat' failed with 0x80010006 : CELL_ENOENT, “/dev_hdd0/game/BLES01555/USRDIR/HDD_GAMEDATA/hs06.adat.sdat” [x6]
E {PPU[0x100001a] Thread (fios mediathread 12) [0x01db4ae0]} Stat: 'sys_fs_stat' failed with 0x80010006 : CELL_ENOENT, “/dev_hdd0/game/BLES01555/USRDIR/HDD_GAMEDATA/hd05.adat” [x6]
E {PPU[0x100001a] Thread (fios mediathread 12) [0x01db4ae0]} Stat: 'sys_fs_stat' failed with 0x80010006 : CELL_ENOENT, “/dev_bdvd/PS3_GAME/USRDIR/HDD_GAMEDATA/hs02.adat.sdat” [x6]
E {PPU[0x100001a] Thread (fios mediathread 12) [0x01db4ae0]} Stat: 'sys_fs_stat' failed with 0x80010006 : CELL_ENOENT, “/dev_hdd0/game/BLES01555/USRDIR/HDD_GAMEDATA/hs02.adat.sdat” [x6]
E {PPU[0x100001a] Thread (fios mediathread 12) [0x01db4ae0]} Stat: 'sys_fs_stat' failed with 0x80010006 : CELL_ENOENT, “/dev_bdvd/PS3_GAME/USRDIR/HDD_GAMEDATA/hd01.adat” [x6]
E {PPU[0x100001a] Thread (fios mediathread 12) [0x01db4ae0]} Stat: 'sys_fs_stat' failed with 0x80010006 : CELL_ENOENT, “/dev_hdd0/game/BLES01555/USRDIR/HDD_GAMEDATA/hd01.adat” [x6]
E {PPU[0x100001a] Thread (fios mediathread 12) [0x01db4ae0]} Stat: 'sys_fs_stat' failed with 0x80010006 : CELL_ENOENT, “/dev_bdvd/PS3_GAME/USRDIR/data/system/game_system_setting.0.10f.cfg.bin.zarc” [x4]
E {PPU[0x100001a] Thread (fios mediathread 12) [0x01db4ae0]} Stat: 'sys_fs_stat' failed with 0x80010006 : CELL_ENOENT, “/dev_hdd0/game/BLES01555/USRDIR/data/system/game_system_setting.0.10f.cfg.bin.zarc” [x4]

tested on 0.0.5-6578 (I've tried every single option/plugin but the game keeps on freezing; btw so I discovered that setting "preferred spu thred" to 2 gives in this game on my system a 20% speed boost) 

my system:
Win10
Gtx1060 3gb
i5 7400
MSI b250 integrated Realtek high definition audio

**Comment by AniLeo** [comment] 2018-03-24 18:53
First one is duplicate of #3973

**Comment by psennermann** [comment] 2018-03-24 21:10
Ok, I found out that maybe this issue should be another regression caused by #4162 since at the moment using 0.0.4-7952 I haven't been able to reproduce the freezing, while instead 0.04-7975 (#4162) do random freezes

**Comment by kd-11** [comment] 2018-03-25 13:05
Duplicate of https://github.com/RPCS3/rpcs3/issues/2359. Desynchronizaion issue

**Closed by kd-11** 2018-03-25 13:05 UTC

**Comment by psennermann** [comment] 2018-03-26 18:29
Since it is a more than year old issue, I guess that unfortunately at the moment no one knows how to fix it :-(

**Comment by hockland** [comment] 2018-04-08 15:34
Just noting that this issue occurs, even after the cutscene fixes of #4401, which shouldn't have an effect on this issue anyway.

**Comment by Asinin3** [comment] 2018-04-24 05:57
The magnify filter crash still exists with the KD Pull Request I played for 4 hours with Vulkan then had it crash with that error. It's more stable but still crashes.

**Comment by psennermann** [comment] 2018-04-28 12:42
Yes, for now it's playable only on OpenGL
