### ISSUE TITLE
Broken Visuals

### ISSUE THREAD

**Issue by Zulthar** [RPCS3/rpcs3#12943] opened 2022-11-11 21:49 UTC
### Quick summary

Star wars force unleashed the colours are all wrong

### Details

The visuals look incredibly over-saturated would upload .zip file to show, but even compressed as a .zip file it was too big (og file was 90 MB for a couple of seconds of footage). What you'll see instead is a screenshot (sorry). The fil was originally a .7z that I turned into a .zip, should still work, but if it doesn't just change the file extension

### Attach a log file

[RPCS3.log](https://github.com/RPCS3/rpcs3/files/9993366/RPCS3.log)

### Attach capture files for visual issues

[Uploading Capture.zip…]()

### Other details

The game also chugs at ~10-15 fps, however the capture itself ran at ~2-3 fps, which may have been what ballooned the file size. Maybe add an overlay if rsx capture is on? One that allows you to compress the resolution, or pause it without ending the game? Because it's fairly opaque to me as to how to control/edit them, if it can even be done

**Comment by Darkhost1999** [comment] 2022-11-11 21:51
Force unleashed 1
https://github.com/RPCS3/rpcs3/issues/12756
and 2
https://github.com/RPCS3/rpcs3/issues/8244
Already have issues open

**Comment by Darkhost1999** [comment] 2022-11-11 21:53
The fix (not public) runs too slow atm and is getting some work done.

**Comment by Zulthar** [comment] 2022-11-11 21:54
Ah, I wasn't aware as the wiki has a "no known issues" on it

**Comment by Darkhost1999** [comment] 2022-11-11 21:55
Yea it's a pain to add every GitHub issue to each wiki page

**Comment by kd-11** [comment] 2022-11-12 20:28
Duplicate of https://github.com/RPCS3/rpcs3/issues/12756

**Closed by kd-11** 2022-11-12 20:28 UTC
