### ISSUE TITLE
Performance regressions after #5115

### ISSUE THREAD

**Issue by weter11** [RPCS3/rpcs3#5182] opened 2018-09-26 14:58 UTC
From my small list of games only NieR Replicant [BLJM60223] is regressed in terms of performance.
7377 & 7380 (34fps)
https://user-images.githubusercontent.com/14630689/46079667-706e3900-c1a0-11e8-9803-a0838607355c.png
7385 (21fps)
https://user-images.githubusercontent.com/14630689/46079694-87ad2680-c1a0-11e8-87b8-9d25e6109265.png

PS: 7380 broken graphics like in 7385, but performance is ok.
https://github.com/RPCS3/rpcs3/files/2420229/RPCS3_7380.log.gz
https://github.com/RPCS3/rpcs3/files/2420231/RPCS3_7385.log.gz

**Comment by weter11** [comment] 2018-09-27 01:50
Ok. Yes on master it looks like it was before #5115.
But as I said it never looks like on PS3. There are strange change in the picture with a slight deviation of the angle of the view the picture becomes either too bright or on the contrary dim. I don't know how to investigate that problem. It is on master builds too for at least 9 months.
PS: IMHO this game should work without WCB, some time ago it worked without this option, not counting some locations and the sound was not distorted.

**Comment by kd-11** [comment] 2018-09-27 08:37
Don't mislead people; nier has always required WCB to work properly. Your GPU does not match the PS3 GPU instruction for instruction and the slight drift in values on rpcs3 vs ps3 causes the strange lighting fluctuation when the game attempts to perform eye adaptation calculations. That will not go away any time soon.

**Comment by ruipin** [comment] 2018-09-29 17:09
I now know what the issue is. https://github.com/ruipin/rpcs3/commit/e4cf125b40e4df9ae27951615a0af2b913b79bd6 has a workaround/hack for this issue that should make Nier perform well again.

However, this is just a hack, a proper fix that can be merged will require significant changes to the texture cache flush prediction mechanism, which I'll work on at some point.

**Comment by ruipin** [comment] 2018-10-21 14:52
Please test #5276

**Comment by weter11** [comment] 2018-12-18 11:52
It's sad, but performance not restored even after latest changes to master.
7377 35fps, GPU load 60%, RSX load 90%;
7588 23fps, GPU load 65%, RSX load 99%.
[RPCS3_7588.log.gz](https://github.com/RPCS3/rpcs3/files/2690334/RPCS3_7588.log.gz)

**Comment by weter11** [comment] 2019-05-06 09:49
So, overall after latest optimizations, stats after #5922 
8066 30fps, GPU load 90%, RSX load 99%.
From now I'm limited on my weak GPU, except small overclock. #5922 is a huge boost in fps.
And now  emulator only 15-20% slower than before.

**Comment by AniLeo** [comment] 2019-09-18 14:25
Test on latest and close if there's no relevant difference, performance regressions with NieR are mostly fixed

**Comment by AniLeo** [comment] 2019-10-18 10:50
Closing as solved, performance regressions regarding this game were fixed, I tested it myself as well and see no performance hit when compared to previous builds.

**Closed by AniLeo** 2019-10-18 10:50 UTC
Labels: Need Information

**Comment by weter11** [comment] 2019-11-02 18:53
I didn’t have a laptop with me for few months, so I could not test.
And now
9050 23fps GPU load 9o%.
May I know the model of your video card for tests, if I understood correctly, the backend and accuracy was improved for the last 5 months, and with it the load on the video card. So I will not be able to enjoy the gameplay on the new builds of the emulator on my hardware (MX150 (GT1030)). 2 years ago I thought my video card would be enough for RPCS3. Looks like I was wrong and need more powerful hardware.
