### ISSUE TITLE
Demon's souls

### ISSUE THREAD

**Issue by joseluisggpp** [RPCS3/rpcs3#15194] opened 2024-02-11 19:55 UTC
### Quick summary

Before updating, the game was running at 60fps with a perfect performance. After updating  RPCS3 to 16085 version, it's really freezing.

### Attach a log file

![image](https://github.com/RPCS3/rpcs3/assets/56825258/f84bea85-c97c-4799-9c64-b9e77995b824)

**Comment by AniLeo** [comment] 2024-02-11 19:56
Duplicate of #15193

**Closed by AniLeo** 2024-02-11 19:56 UTC
