### ISSUE TITLE
Feature request: save to and resume from disk rpcs3 emulation state

### ISSUE THREAD

**Issue by jobs-git** [RPCS3/rpcs3#4694] opened 2018-06-02 14:42 UTC
Feature that allows rpcs3 to save the emulate state to disk and allow resumption of current save state even after pc restart.

This feature is also similar to pcsx2 save and resume state.

**Comment by scribam** [comment] 2018-06-02 14:45
Duplicate of #4218?

**Closed** 2018-06-02 14:46 UTC
