### ISSUE TITLE
Doesn't starts in Linux

### ISSUE THREAD

**Issue by logos88** [RPCS3/rpcs3#2616] opened 2017-03-31 12:36 UTC
Terminal says: Segment violation (`core' generated)

Today I have updated since few weeks without and now doesn't starts the program.

**Comment by 7oxicshadow** [comment] 2017-03-31 17:18
@logos88 I have just built RPCS3 on Fedora 25 and everything loads with no errors? The only problem I have is that the program hangs shortly after starting a game.

Is it possible that one of the libraries that RPCS3 uses has been removed accidentally from your machine?

**Comment by hcorion** [comment] 2017-03-31 17:42
@logos88 Computer specs? Linux version?

**Comment by logos88** [comment] 2017-03-31 20:33
Processor: i5-4570 CPU @ 3.20GHz
Memor: 8060MB (3219MB used)
Operating System: Arch Linux

**Comment by hcorion** [comment] 2017-03-31 20:41
Did you use the PKGBUILD from the aur or build it yourself?

**Comment by logos88** [comment] 2017-03-31 20:44
Its the PKGBUILD from the aur

**Comment by logos88** [comment] 2017-03-31 20:52
````
(gdb) r
Starting program: /usr/bin/rpcs3 
[Thread debugging using libthread_db enabled]
Using host libthread_db library "/usr/lib/libthread_db.so.1".

Program received signal SIGSEGV, Segmentation fault.
0x000000000068671a in ?? ()
(gdb) bt full
#0  0x000000000068671a in  ()
#1  0x0000000000b99f7d in __libc_csu_init ()
#2  0x00007ffff200b4a0 in __libc_start_main () at /usr/lib/libc.so.6
#3  0x000000000069113a in _start ()
```
`

**Comment by hcorion** [comment] 2017-03-31 20:52
Confirmed issue. Just tried to build it on Arch Linux 64-bit, segmentation fault as well.

**Comment by hcorion** [comment] 2017-03-31 20:56
Debug build GDB backtrace: 
```gdb
 Program received signal SIGSEGV, Segmentation fault.
0x00000000014cc53c in rsx::<lambda()>::operator()(void) const (__closure=0x7fffffffdb8f) at /home/zion/Documents/source/rpcs3/rpcs3/Emu/RSX/rsx_methods.cpp:1278
1278                    methods[GCM_SET_DRIVER_OBJECT]                    = nullptr;
(gdb) bt
#0  0x00000000014cc53c in rsx::<lambda()>::operator()(void) const (__closure=0x7fffffffdb8f)
    at /home/zion/Documents/source/rpcs3/rpcs3/Emu/RSX/rsx_methods.cpp:1278
#1  0x00000000014cf452 in __static_initialization_and_destruction_0(int, int) (__initialize_p=1, __priority=65535)
    at /home/zion/Documents/source/rpcs3/rpcs3/Emu/RSX/rsx_methods.cpp:1378
#2  0x00000000014cffaf in _GLOBAL__sub_I_g_cfg_rsx_frame_limit() () at /home/zion/Documents/source/rpcs3/rpcs3/Emu/RSX/rsx_methods.cpp:1379
#3  0x000000000170728d in __libc_csu_init ()
#4  0x00007ffff200b4a0 in __libc_start_main () at /usr/lib/libc.so.6
#5  0x0000000000d917aa in _start ()
**(gdb)**
```

**Comment by hcorion** [comment] 2017-03-31 21:05
@kd-11 your commit 909f3e9b3e3736b71f1b6b5f09b0967a80c7ba03 broke the Linux version of rpcs3

**Comment by hcorion** [comment] 2017-03-31 21:11
@7oxicshadow Are you sure it was the latest version of rpcs3? If so, it may have to do with the custom ArchLinux flags.
These are the cmake flags I use with my custom build: 
```shell
cmake ../../source/rpcs3 -G "Unix Makefiles" -DUSE_SYSTEM_LIBPNG=ON -DUSE_SYSTEM_FFMPEG=ON -DCMAKE_BUILD_TYPE=Release -DCMAKE_EXE_LINKER_FLAGS='-ldl -lyaml-cpp' -DCMAKE_SKIP_RPATH='ON' -DLLVM_DIR=/usr/
```
And the ArchLinux PKGBUILD uses: 
```shell
cmake .. \
    -DCMAKE_BUILD_TYPE='Release' \
    -DCMAKE_INSTALL_PREFIX='/usr' \
    -DCMAKE_EXE_LINKER_FLAGS='-ldl -lyaml-cpp' \
    -DCMAKE_SKIP_RPATH='ON' \
    -DUSE_SYSTEM_FFMPEG='ON' \
    -DUSE_SYSTEM_LIBPNG='ON'
```

**Comment by 7oxicshadow** [comment] 2017-03-31 21:13
i dont specify any build flags so assume is has some defaults. I dont have LLVM support as it complains during compilation.

**Comment by 7oxicshadow** [comment] 2017-03-31 21:18
The version string is : RPCS3 v0.0.2-5077-0fba38f Alpha

**Comment by hcorion** [comment] 2017-03-31 21:23
Perhaps it's an issue with the latest version of GCC, @7oxicshadow what version of gcc are you running?

**Comment by 7oxicshadow** [comment] 2017-03-31 21:25
gcc (GCC) 6.3.1 20161221 (Red Hat 6.3.1-1)

**Comment by 7oxicshadow** [comment] 2017-03-31 21:39
Something else to consider. I am using the NVIDIA proprietary driver 378.13

**Comment by hcorion** [comment] 2017-03-31 21:39
@7oxicshadow SAME NIVIDA DRIVERS! SAME GCC! WTH is going one!

**Comment by 7oxicshadow** [comment] 2017-03-31 21:42
i am building against wx widgets 3.0 even though I believe its supposed to be build using 3.1?

**Comment by hcorion** [comment] 2017-03-31 21:45
Nope. Arch Linux provides wxGTK 3.0 not 3.1

**Comment by 7oxicshadow** [comment] 2017-03-31 21:52
im building using clang.....

I just checked my build script

**Comment by hcorion** [comment] 2017-03-31 21:56
Could you try with GCC?

**Comment by 7oxicshadow** [comment] 2017-03-31 22:08
gcc rpcs3 binary =  30.7MB
glang rpcs3 binary = 31.3MB

Both work fine. I am using PS3DOOM as the test game.

**Comment by logos88** [comment] 2017-03-31 22:11
I have mesa drivers for Intel graphic card in my case and gcc 6.3.1

**Comment by hcorion** [comment] 2017-03-31 22:22
Ah, I found the issue. It was with the cmake flags used by Arch Linux. It was with FFMPEG. If I use the bundled ffmpeg all is good, If I use the system installed ffmpeg (which is what the Arch Linux build does) it screws up.

**Comment by 7oxicshadow** [comment] 2017-03-31 22:29
Good catch. It looks like CMakeLists.txt defaults to off for libpng but has no mention of FFMPEG. Guess that is set to use the bundled version by defualt.

**Comment by logos88** [comment] 2017-04-01 12:16
So which should be the cmake flags then? I have tried  -DUSE_SYSTEM_FFMPEG='OFF' \ but it doesn't compile

**Comment by hcorion** [comment] 2017-04-01 19:11
Hi, yeah @logos88 you can just remove the -DUSE_SYSTEM_FFMPEG flag all together, however you'd also need to add https://github.com/hrydgard/ppsspp-ffmpeg as a source and set the submodule to update. Anyway, I added a message for a maintainer on the PKGBUILD website, I think he's pretty quick at applying fixes.

**Comment by hcorion** [comment] 2017-04-03 18:45
@logos88 The issue was actually fixed PR https://github.com/RPCS3/rpcs3/pull/2629 can you retest with the default PKGBUILD just to make sure it works for you?

**Comment by logos88** [comment] 2017-04-03 20:18
@hcorion I have tested the default PKGBUILD and works fine now. Thanks!! : )

**Comment by hcorion** [comment] 2017-04-04 02:01
Great, then if you could close the issue, that would be great.

**Closed** 2017-04-04 06:26 UTC
