### ISSUE TITLE
Legend of the Guardians: The Owls of Ga'Hoole Graphical Issue

### ISSUE THREAD

**Issue by Triticum0** [RPCS3/rpcs3#13741] opened 2023-04-23 13:11 UTC
### Quick summary

Seems to have a graphical issue when your character hits the fire catapult

### Details

when testing this game I ran into an issue where if I run into the fire catapult every seems to stop rendering other than the UI elements and post effects. you can restart the mission and it seems to fix the issue but can be very annoying.

Rpcs3
![NPEB90248_screenshot_2023_04_23_13_59_16](https://user-images.githubusercontent.com/71127352/233841324-209b0e21-7716-4a12-ad94-336658a09c65.png)

Note: this could possibly affect the real ps3 but I am unable to test to find out but did find a video online of someone having a similar  issue https://www.youtube.com/watch?v=ywf_8EfAxUA

### Attach a log file

[RPCS3.log.gz](https://github.com/RPCS3/rpcs3/files/11303796/RPCS3.log.gz)

### Attach capture files for visual issues

https://drive.google.com/file/d/1GMniYnLI4qV3gk1ERFG8ZobyyCb3CV0Z/view?usp=sharing

### System configuration

RPCS3 v0.0.27-14921-a6e4b772 Alpha | master | FW 4.88 | 5.15.106-1-MANJARO
AMD Ryzen 5 2600 | 12 Threads | 15.95 GiB RAM | AVX+ | FMA3
GPU: NVIDIA GeForce RTX 3060 Ti (530.41)

**Comment by AniLeo** [comment] 2023-04-23 13:42
Did you try with Read/Write Color/Depth buffer options, as well as Debug > CPU Blit Emulation to test if anything changes?

**Comment by Triticum0** [comment] 2023-04-23 15:35
Didn't fix the issue testing permutations:
WCB=Cause graphical issue ·E 0:01:06.337811 {RSX [0x00329f0]} RSX: Excluded region overlaps with flushed surface! crashes when going in-game (VM: Access violation writing location 0x121826 (read-only memory)
[RPCS3.log.gz](https://github.com/RPCS3/rpcs3/files/11304066/RPCS3.log.gz)
RDB=Nothing
WDB= Black screen/Graphical issues
RCB= Nothing
RDB+WDB=Crashes F {RSX [0x110eea4]} SIG: Thread terminated due to fatal error: Verification failed
(in file ../rpcs3/Emu/RSX/VK/VKTexture.cpp:921, in function calculate_upload_pitch) (errno=110=Connection timed out)
[RPCS3.log](https://github.com/RPCS3/rpcs3/files/11304106/RPCS3.log)
RCB+WDB=Crashes F {RSX [0x10eaea4]} SIG: Thread terminated due to fatal error: Verification failed
(in file ../rpcs3/Emu/RSX/VK/VKTexture.cpp:921, in function calculate_upload_pitch) (errno=110=Connection timed out)
RCB+RDB= Crashes F {RSX [0x22fefa4]} SIG: Thread terminated due to fatal error: Verification failed
(in file ../rpcs3/Emu/RSX/VK/VKTexture.cpp:921, in function calculate_upload_pitch) (errno=110=Connection timed out)
RCB+WDB+RDB= Crashes F {RSX [0x22fefa4]} SIG: Thread terminated due to fatal error: Verification failed
(in file ../rpcs3/Emu/RSX/VK/VKTexture.cpp:921, in function calculate_upload_pitch) (errno=110=Connection timed out)

**Comment by kd-11** [comment] 2023-04-24 06:38
At least the crashes should be investigated first.

**Comment by kd-11** [comment] 2023-04-24 19:45
Btw the blackscreen isn't a graphics glitch. The game itself is glitched. Only the UI is being sent to the GPU. And you can also see the logic isn't advancing. You get failure messages continuously in a loop and even audio dies.

**Comment by kd-11** [comment] 2023-04-24 19:50
The logic glitch is caused by SPU LLVM. Changing the SPU recompiler to ASMJIT fixes the problem.

**Comment by kd-11** [comment] 2023-04-24 19:57
The remaining crashes are fixed by https://github.com/RPCS3/rpcs3/pull/13753

**Comment by Triticum0** [comment] 2023-04-24 19:58
Thank I test once the pr finished being built

**Comment by Triticum0** [comment] 2023-04-24 20:19
#13753  It seems to fix all the issues with crashing and using Accurate Xfloat fixes the issue with the broken physics and logic issue causing the black screen. Thanks Will add it to the wiki and will move it to playable.

Also, did you get any crashing, when testing the game I had to turn on RSX Fifo accuracy to atomic when testing without SPU xfloat accuracy set to accurate xfloat. not sure if that is just a side effect of the logic issue or is effected with xfloat accurate as haven't test enought to know.

**Comment by Triticum0** [comment] 2023-04-24 20:20
also does E RSX: Unknown/illegal instruction: 0x7f (forced unit 0) x2 mean anything? do you get it while testing

**Comment by Megamouse** [comment] 2023-04-24 20:22
issues are closed when they are fixed in master

**Closed** 2023-04-25 10:07 UTC
Labels: Need Information
