### ISSUE TITLE
[Feature Request] BetterJoy for Gyroscope

### ISSUE THREAD

**Issue by metalslayer** [RPCS3/rpcs3#9683] opened 2021-01-30 12:03 UTC
BetterJoy support gyroscope feature for Cemu and Yuzu emulators:
List of gamepads that support it:
Joycons
Switch Pro Controller
8Bitdo SN30 Pro/Pro+

**Comment by Megamouse** [comment] 2021-08-07 21:56
closing as this seems to be a duplicate of #8600

**Closed by Megamouse** 2021-08-07 21:56 UTC
Labels: Input, OS: Windows
