### ISSUE TITLE
Nier Replicant Save Crash

### ISSUE THREAD

**Issue by SalamanderSandwich** [RPCS3/rpcs3#4135] opened 2018-02-01 06:53 UTC
When I try to make a fourth save the game will freeze and give these errors.
```
F {PPU[0x1000027] Thread (CSaveDataLib) [0x0073e1a4]} MEM: Access violation reading location 0x4
E {rsx::thread} RSX: nv406e::semaphore_acquire has timed out. semaphore_address=0x40300430
```
The save is not visible in the save manager and there's no folder for it. On reboot the game says "Cannot use the selected storage device. Select another storage device? Yes/No" and won't work until you restart rpcs3.
Using Ubuntu 17.10, RPCS3-0.0.4-6368-70fe0cc22. I did move saves I made in windows over, but they loaded fine and was able to make a third save multiple times. Saving over other saves works fine.

**Comment by theoldsport** [comment] 2018-06-07 10:18
Been playing Nier Replicant for many hours on RPCS3. The constant semaphore locking was fixed recently, though I've noticed that often when saving and prompting the ingame save overlay,  it'll snag a "semaphore_acquire has timed out". May or may not be related to this?

**Comment by AniLeo** [comment] 2018-07-23 17:49
Cannot reproduce, retest

**Comment by AniLeo** [comment] 2018-09-28 22:11
Closing due to no one being able to reproduce. If anyone is able to reproduce this somehow, open a new issue with clear steps on how to do so with current master.

**Closed by AniLeo** 2018-09-28 22:11 UTC
Labels: Bug, Need Information, Savedata
