### ISSUE TITLE
0.0.4-6320 and later has missing trees in ni no kuni on world map

### ISSUE THREAD

**Issue by Kadaban** [RPCS3/rpcs3#4062] opened 2018-01-15 14:06 UTC
All versions more recent than (and including) 0.0.4-6320 are missing the trees from the world map when outside of cities. 
I just downloaded all versions up to the latest and replaced the exe files by hand, then loaded a savegame right outside of castaway cove to test whether trees were showing or not. No configuration changes were made in between version swapping and just replacing the newer exe files with the exe files from build 6315 (the last working version) fixes the trees.
Deleting the shader caches didn't work as well.

EDIT: Just tried with versions up to 6328; they're broken as well.

I attached two screenshots which show the issue, but I did NOT attach any log files as they are not showing anything out of the ordinary when switching the rpcs3 versions. If anyone really wants a log file I'll gladly upload one.

Short system summary:
Intel i7-8700K
16GB RAM
Nvidia GTX 1070
Windows 7

![no trees](https://user-images.githubusercontent.com/5698994/34945930-385f5516-fa05-11e7-8751-9632bb3f5b66.jpg)
![trees](https://user-images.githubusercontent.com/5698994/34945939-3be79a5e-fa05-11e7-8e8a-7b33bbee7d7e.jpg)

**Comment by TheCake21** [comment] 2018-01-17 14:17
Can confirm that this indeed a regression caused by #4043

**Comment by Kadaban** [comment] 2018-01-17 15:02
Is there anything else I can do to help with this?

**Comment by kd-11** [comment] 2018-01-17 15:05
Its an old known issue, patches should land for it in the next few days.

**Comment by Kadaban** [comment] 2018-01-17 17:51
I'll keep checking newer versions and report back once something changes.

**Comment by kd-11** [comment] 2018-01-19 09:07
Should be fixed by https://github.com/RPCS3/rpcs3/pull/4079. If not, reopen.

**Closed by kd-11** 2018-01-19 09:07 UTC
