### ISSUE TITLE
rsx: White Album 2 - Graphical corruption on character texture / portrait

### ISSUE THREAD

**Issue by RainKikyou** [RPCS3/rpcs3#8625] opened 2020-07-25 06:32 UTC
VK
![QQ截图20200725134007](https://user-images.githubusercontent.com/20301499/88450490-e8cbe100-ce81-11ea-8a5b-9f44289a44a9.png)

OGL
![QQ截图20200725134819](https://user-images.githubusercontent.com/20301499/88450496-fb461a80-ce81-11ea-94ef-c34cd3a111fb.png)

PS3
![QQ截图20200725142354](https://user-images.githubusercontent.com/20301499/88450544-5ed04800-ce82-11ea-87e8-9ed7265edd61.png)

i cant caputure rdc data，using vk to fatal error，using ogl to very slow framerate(get infinite black sreen in after ingame）
![QQ图片20200725140600](https://user-images.githubusercontent.com/20301499/88450612-c9818380-ce82-11ea-906a-308da19f8401.png)

rsx caputure 
https://drive.google.com/file/d/1zn_SrmAatgDFJI1OZU6ZmuFq7e0-Y2R0/view?usp=sharing

* OS win10 18362.959
* CPU i9 9900kf oc 4.8ghz
* GPU gtx1060 6gb
* Driver version 446.14

ps:this problem sometimes disappears,  character is normal, it can be said to be random.but there is a high probability that it is wrong character.

**Comment by AniLeo** [comment] 2020-07-25 07:46
Your screenshot shows the game is not running, otherwise the Stop button would not be disabled

**Comment by kd-11** [comment] 2020-07-25 10:56
Is this a duplicate of https://github.com/RPCS3/rpcs3/issues/8150? I recognize the first image as the swizzled data problem that I am working on.

**Closed** 2020-07-25 11:53 UTC
Labels: Need Information
