### ISSUE TITLE
Gran turismo 6 access_violation

### ISSUE THREAD

**Issue by Exmach** [RPCS3/rpcs3#2066] opened 2016-08-12 15:46 UTC
GL window opens for a second then 
U {PPU[0x80000000] Thread (main_thread) [0x00a477dc]} sys_mmapper TODO: sys_mmapper_enable_page_fault_notification(addr=0x60000000, eq=0x206)
F {PPU[0x80000000] Thread (main_thread) [0x00a4fe38]} struct vm::access_violation thrown: Access violation writing address 0x6ffd0000

**Comment by raven02** [comment] 2016-08-12 16:34
Merged into already existing issue.

**Closed by raven02** 2016-08-12 16:34 UTC

**Comment by paulsapps** [comment] 2016-08-12 21:43
Isn't this another issue caused by sys_mmapper_enable_page_fault_notification not being implemented?
