### ISSUE TITLE
Persona 4 Arena completely broken in recent builds

### ISSUE THREAD

**Issue by esppc** [RPCS3/rpcs3#7983] opened 2020-04-07 18:43 UTC
## Quick summary
Persona 4 Arena shows only totally glitched graphics in recent builds, while older builds works fine

Bugged game:
![glitch](https://user-images.githubusercontent.com/34080739/78706367-52c97600-78e5-11ea-8dbd-7abba9d80186.png)

Working game:
![image](https://user-images.githubusercontent.com/34080739/78706950-514c7d80-78e6-11ea-923a-82649e2ef0d3.png)

## Details
The issue starts to appear at 8253, prior builds works just fine.
My specs are: RX 5700XT and a Ryzen 7 2700X

[RPCS3-v0.0.6-8231.log](https://github.com/RPCS3/rpcs3/files/4446434/RPCS3-v0.0.6-8231.log)
[RPCS3-v0.0.6-8253.log](https://github.com/RPCS3/rpcs3/files/4446447/RPCS3-v0.0.6-8253.log)
[BLUS30985_20200407153911_capture.zip](https://github.com/RPCS3/rpcs3/files/4446458/BLUS30985_20200407153911_capture.zip)

**Comment by esppc** [comment] 2020-04-07 18:50
Whoops! Forgot about the recent build log... my bad!

![image](https://user-images.githubusercontent.com/34080739/78707682-52ca7580-78e7-11ea-9fd0-f2fc534d8d1f.png)

[BLUS30985_20200407154741_capture.zip](https://github.com/RPCS3/rpcs3/files/4446490/BLUS30985_20200407154741_capture.zip)
[RPCS3.log](https://github.com/RPCS3/rpcs3/files/4446493/RPCS3.log)

**Comment by illusion0001** [comment] 2020-04-07 18:53
Disable AA. It's a bug with driver.

**Comment by AniLeo** [comment] 2020-04-08 01:27
Closing as duplicate of #6999

**Closed by AniLeo** 2020-04-08 01:27 UTC
