### ISSUE TITLE
RESIDENT EVIL 6[BLUS30855]RSX: class std::runtime_error thrown: Assertion Failed!

### ISSUE THREAD

**Issue by Myoko** [RPCS3/rpcs3#6639] opened 2019-09-25 12:43 UTC
I can only load into the brightness option
![2](https://user-images.githubusercontent.com/3013386/65611732-cfe66b00-dfe5-11e9-877c-0303543ba088.jpg)

E {RSX [0x026365c]} RSX: [vulkan] vk::wait_for_event has timed out!
U {PPU[0x1000000] Thread (main_thread) [0x019d5d28]} sceNp TODO: sceNpManagerGetStatus(status=*0xd0015e60)
S {RSX Decompiler Thread} RSX: New program compiled successfully x2
E {RSX [0x015cf40]} RSX: [vulkan] vk::wait_for_event has timed out!
F {RSX [0x0168e14]} RSX: class std::runtime_error thrown: Assertion Failed! Vulkan API call failed with unrecoverable error: Device lost (Driver crashed with unspecified error or stopped responding and recovered) (VK_ERROR_DEVICE_LOST)
(in file F:\Project\rpcs32\rpcs3\rpcs3\Emu\RSX\VK\VKHelpers.h:1052)
S {RSX Decompiler Thread} RSX: New program compiled successfully

log
[RPCS3.log.gz](https://github.com/RPCS3/rpcs3/files/3653056/RPCS3.log.gz)

**Comment by kd-11** [comment] 2019-09-25 14:43
Known glitch with turing GPUs. Just enable "High precision Z" in the debug options. If that fixes the issue, close this ticket.

**Comment by kd-11** [comment] 2019-09-26 12:00
Retry with https://github.com/RPCS3/rpcs3/pull/6644

**Comment by Myoko** [comment] 2019-09-26 13:55
using "High precision Z" The same result

![33](https://user-images.githubusercontent.com/3013386/65694375-5794ae00-e0a8-11e9-9e65-775a18eadd35.jpg)

log
[RPCS3.log.gz](https://github.com/RPCS3/rpcs3/files/3658100/RPCS3.log.gz)

**Comment by kd-11** [comment] 2019-09-28 18:25
Retest with https://github.com/RPCS3/rpcs3/pull/6667

**Comment by Myoko** [comment] 2019-09-29 01:07
nothing changed!
![12](https://user-images.githubusercontent.com/3013386/65824247-62ae3080-e298-11e9-89ca-20341b052b13.jpg)

[RPCS3.log.gz](https://github.com/RPCS3/rpcs3/files/3666196/RPCS3.log.gz)

**Comment by kd-11** [comment] 2019-09-29 08:41
I can't make this happen on my pascal card, so we'll just wait for more reports to narrow down what is triggering it. In the meantime you should install the vulkan SDK and run with "debug output" option enabled (its in the config file). Hopefully there'll be diagnostic information before the crash happens.

**Comment by Myoko** [comment] 2019-09-29 09:41
you did good, thanks
i dont know why it always happen! VK SDK i'll try it

**Comment by kd-11** [comment] 2019-09-29 09:49
You can find the latest SDK here https://vulkan.lunarg.com/sdk/home#windows

**Comment by Myoko** [comment] 2019-09-29 09:57
thanks

**Comment by Myoko** [comment] 2019-10-02 14:29
OGL its normal and no High precision Z
![1](https://user-images.githubusercontent.com/3013386/66049236-9d94ba80-e55d-11e9-9ea2-aa68b3dbe1fa.jpg)

log
https://drive.google.com/file/d/1C-kE_82rDh2Yy-r2qjwJPvGHqGh8OTbp/view?usp=sharing

**Comment by Emulator-Team-2** [comment] 2019-11-16 19:20
@kd-11 
Tested with the latest master build (0.0.7-9142):
GPU: GTX 1660

This game still crashes only in Vulkan on the loading screen with a fatal error:
```
RSX: class std::runtime_error thrown: Assertion Failed! Vulkan API call failed with unrecoverable error: Device lost (Driver crashed with unspecified error or stopped responding and recovered) (VK_ERROR_DEVICE_LOST)
(in file C:\projects\rpcs3\rpcs3\Emu\RSX\VK\VKHelpers.h:1178)
```
Log with installed (**Vulkan SDK**) and Debug Output enabled:
[RPCS3.log.gz](https://github.com/RPCS3/rpcs3/files/3854591/RPCS3.log.gz)

**Comment by digitaldude555** [comment] 2020-02-22 11:30
Add vulkan tag.

**Comment by kd-11** [comment] 2020-02-23 06:54
This is likely already fixed actually

**Comment by Emulator-Team-2** [comment] 2020-03-07 21:15
Tested with the latest master Build: 0.0.9-9849.
GPU: GTX 1660.

This game still crashes on the loading screen.
```
F {RSX [0x019ac90]} RSX: class std::runtime_error thrown: Assertion Failed! Vulkan API call failed with unrecoverable error: Device lost (Driver crashed with unspecified error or stopped responding and recovered) (VK_ERROR_DEVICE_LOST)
(in file C:\projects\rpcs3\rpcs3\Emu\RSX\VK\VKHelpers.cpp:917)

```
Log with installed Vulkan SDK:
[RPCS3.log.gz](https://github.com/RPCS3/rpcs3/files/4302493/RPCS3.log.gz)

**Comment by stizzo1** [comment] 2020-03-21 23:33
I can confirm that the issue is persistent even in the latest build.

![Screenshot (3)](https://user-images.githubusercontent.com/43874809/77238872-b27d0d00-6bd4-11ea-8a10-b245b6805c14.png)

[RPCS3.log.gz](https://github.com/RPCS3/rpcs3/files/4364440/RPCS3.log.gz)

**Comment by kd-11** [comment] 2020-03-22 11:27
I was able to reproduce this issue. A fix will be available in the next fixups cycle.

**Comment by zombie167** [comment] 2020-03-23 15:03
> I was able to reproduce this issue. A fix will be available in the next fixups cycle.

Thank you very much!

**Comment by kd-11** [comment] 2020-06-29 17:20
I forgot to self-assign this, fortunately I was doing prework on another RE6 ticket and remembered this one.

**Comment by kd-11** [comment] 2020-07-02 17:48
Fixed by https://github.com/RPCS3/rpcs3/pull/8545, please confirm.

**Comment by Emulator-Team-2** [comment] 2020-07-02 19:48
Fixed by https://github.com/RPCS3/rpcs3/pull/8545.

**Closed** 2020-07-03 11:29 UTC
Labels: Bug, RSX
