### ISSUE TITLE
Regression: SIG: Thread terminated due to fatal error: Verification failed (0000000000000000) in Far Cry 4

### ISSUE THREAD

**Issue by xddxd** [RPCS3/rpcs3#8901] opened 2020-09-13 17:49 UTC
~~After PR #8434 (RPCS3 v0.0.10-10502-3663a8ab)~~ After PR #8299 (rpcs3-v0.0.10-10439-c9a978a0), when WCB is enabled Far Cry 4 will fatal with the following error in the menu: `SIG: Thread terminated due to fatal error: Verification failed (0000000000000000): 
(in file D:\a\1\s\rpcs3\Emu\RSX\VK\VKRenderTargets.h:602)`

Log from last working version (RPCS3 v0.0.10-10435-3df83e03):
[RPCS3.log.gz](https://github.com/RPCS3/rpcs3/files/5359882/RPCS3.log.gz)

Log from latest master (RPCS3 v0.0.12-10987-ffea52dc):
[RPCS3.zip](https://github.com/RPCS3/rpcs3/files/5356813/RPCS3.zip)

VS Call stack from 10876:
![Screenshot_11](https://user-images.githubusercontent.com/1712979/93024969-d9a41c80-f602-11ea-895e-84042847ee1f.png)

R7 2700
RX 580 20.8.3
Windows 2004

**Comment by xddxd** [comment] 2020-10-10 19:45
Updated the issue with more accurate information. I can reproduce this on 10439, while I can't repro it on 10435 even after about 20 tries. *sigh*

**Comment by kd-11** [comment] 2020-10-25 17:48
Blocked by https://github.com/RPCS3/rpcs3/issues/9133. Underlying root cause is known, but some redesign of the surface configuration is required to fix this issue for good. Basically WCB & WDB have to be combined to eliminate the possibility of a surface getting dirtied and erased from the surface cache while a reference to it still remains active in the texture cache. This is only possible when locking is applied to some surfaces but not others and is a nightmare to manage effectively.

**Comment by kd-11** [comment] 2022-01-17 18:06
This shouldn't be an issue anymore.

**Comment by xddxd** [comment] 2022-01-18 03:20
Who knows, game freezes before showing the Ubi logo.
`F {RSX [0x0a0caac]} SIG: Thread terminated due to fatal error: Verification failed
(in file D:\a\1\s\rpcs3\Emu\RSX\VK\VKTexture.cpp:252[:4], in function copy_buffer_to_image)`
It has been like it since at least August 2021
[RPCS3.zip](https://github.com/RPCS3/rpcs3/files/7885950/RPCS3.zip)

**Comment by Darkhost1999** [comment] 2022-08-07 22:34
Are you sure this is still an issue?
[RPCS3.log.gz](https://github.com/RPCS3/rpcs3/files/9277688/RPCS3.log.gz)
I get long past the ubi logo with WCB enabled.

**Comment by kd-11** [comment] 2023-06-07 22:59
Closing as fixed. Reopen if still present.

**Closed by kd-11** 2023-06-07 22:59 UTC
Labels: RSX, Blocked
