### ISSUE TITLE
erro  OpenGL 0x0502 e 0x506

### ISSUE THREAD

**Issue by andre4688** [RPCS3/rpcs3#919] opened 2014-12-24 09:42 UTC
And now new error is affecting several game nvidia graphics car

 I apologize all 
 It does not verify all my  games  OpenGL error  Continues to OpenGL error 0x0502 and 0x506
new erro   E {RSXThread} glDrawArrays: opengl error 0x0501  game  winters end 

E {RSXThread} glUseProgram: opengl error 0x0502
E {RSXThread} glGetUniformLocation(0x5, tex0): opengl error 0x0502   until  0-15
E {RSXThread} glGetUniformLocation(0x5, vc[0]): opengl error 0x0502
E {RSXThread} glGetUniformLocation(0x5, vc[1]): opengl error 0x0502
E {RSXThread} glGetUniformLocation(0x5, vc[2]): opengl error 0x0502
E {RSXThread} glGetUniformLocation(0x5, vc[3]): opengl error 0x0502
E {RSXThread} glGetUniformLocation(0x5, vc[4]): opengl error 0x0502
E {RSXThread} glGetUniformLocation(0x5, vc[5]): opengl error 0x0502
E {RSXThread} glGetUniformLocation(0x5, vc[6]): opengl error 0x0502
E {RSXThread} glGetUniformLocation(0x5, vc[7]): opengl error 0x0502
E {RSXThread} glGetUniformLocation(0x5, vc[467]): opengl error 0x0502
RSXThread} glGetUniformLocation(0x5, vc[467]): opengl error 0x0502
E {RSXThread} glGetUniformLocation(0x5, scaleOffsetMat): opengl error 0x0502
E {RSXThread} glDrawArrays: opengl error 0x0506
E {RSXThread} Unknown/illegal instruction: 0x5c (forced unit 0)

**Comment by tambry** [comment] 2015-03-25 19:24
@andre4688 Does this still occur? If yes, then in which games?

**Comment by andre4688** [comment] 2015-03-27 17:28
should create the correct this error would be good for this very aperse emulator games
  NV0039 OFFSET
NV4097 SET CONTROL0 (0x100000)
NV3089

**Comment by MoochMcGee** [comment] 2015-03-27 17:29
@andre4688 Sorry, but I really can't understand you. Your English seems to be lacking.

**Comment by paulsapps** [comment] 2015-03-27 19:16
Hes saying that error 0x0506 is fixed but now has error 0x0502

**Comment by tambry** [comment] 2015-03-27 19:25
@andre4688 Andre, could you please specify the games as I asked? That logs segment gives us no information on why the OpenGL error 0x0502 occured. It only says that it occured, but we are unable to identify the cause. If you would be kind enough to provide the game's name, developers might be able to debug the game and find out what's causing the error. If you have no further information to provide, we might as well close this issue as we don't have the required details that would help us resolve this "issue", which might not even be a real issue - it might just be a misconfiguration of VFS (Game doesn't find shader files, but still tries to compile/use code from these missing files/shaders/whatever).

**Comment by andre4688** [comment] 2015-03-28 14:11
Dear  tambry
specify the games that this error Game list error 

froge returms 
E {RSXThread} Unimplemented sca_opcode BRB
E {RSXThread} Unknown vp sca_opcode 0x9
E {RSXThread} Could not link program: Fragment info
-------------
0(99) : error C5052: gl_Position is not accessible in this profile
E {RSXThread} glUseProgram: opengl error 0x0502
E {RSXThread} glGetUniformLocation(0x5, tex0): opengl error 0x0502    numbers until 0-15
E {RSXThread} glGetUniformLocation(0x5, vc[0]): opengl error 0x0502    numbers until 0-7
E {RSXThread} glGetUniformLocation(0x5, vc[467]): opengl error 0x0502
E {RSXThread} glGetUniformLocation(0x5, scaleOffsetMat): opengl error 0x0502

all the same games   without write color buffer
tank battles              
the simpsons arcade 
AlteredBeast
comix zone

{RSXThread} Unimplemented TEX_SRB instruction: UPB
E {RSXThread} Unimplemented SCB instruction: PKG
E {RSXThread} Unknown/illegal instruction: 0x30 (forced unit 0)
E
E {RSXThread} Unknown/illegal instruction: 0x30 (forced unit 0)
E {RSXThread} Unknown/illegal instruction: 0x48 (forced unit 0)
E {RSXThread} Unknown/illegal instruction: 0x4c (forced unit 0)
E {RSXThread} Unknown/illegal instruction: 0x50 (forced unit 0)
E {RSXThread} Unknown/illegal instruction: 0x54 (forced unit 0)
E {RSXThread} Unknown/illegal instruction: 0x58 (forced unit 0)
E {RSXThread} Unknown/illegal instruction: 0x5c (forced unit 0)
E {RSXThread} Unknown/illegal instruction: 0x60 (forced unit 0)
E {RSXThread} Unknown/illegal instruction: 0x64 (forced unit 0)
E {RSXThread} Unknown/illegal instruction: 0x68 (forced unit 0)
E {RSXThread} Unknown/illegal instruction: 0x6c (forced unit 0)
E {RSXThread} Unknown/illegal instruction: 0x70 (forced unit 0)
E {RSXThread} Unknown/illegal instruction: 0x74 (forced unit 0)
E {RSXThread} Unknown/illegal instruction: 0x78 (forced unit 0)
E {RSXThread} Unknown/illegal instruction: 0x7c (forced unit 0)
E {RSXThread} Unknown/illegal instruction: 0x48 (forced unit 0)
E {RSXThread} Unknown/illegal instruction: 0x4c (forced unit 0)
E {RSXThread} Unknown/illegal instruction: 0x50 (forced unit 0)
E {RSXThread} Unknown/illegal instruction: 0x54 (forced unit 0)
E {RSXThread} Unknown/illegal instruction: 0x58 (forced unit 0)
E {RSXThread} Unknown/illegal instruction: 0x5c (forced unit 0)
E {RSXThread} Unknown/illegal instruction: 0x60 (forced unit 0)
E {RSXThread} Unknown/illegal instruction: 0x64 (forced unit 0)
E {RSXThread} Unknown/illegal instruction: 0x68 (forced unit 0)
E {RSXThread} Unknown/illegal instruction: 0x6c (forced unit 0)
E {RSXThread} Unknown/illegal instruction: 0x70 (forced unit 0)
E {RSXThread} Unknown/illegal instruction: 0x74 (forced unit 0)
E {RSXThread} Unknown/illegal instruction: 0x78 (forced unit 0)
E {RSXThread} Unknown/illegal instruction: 0x7c (forced unit 0)
E {RSXThread} glDrawArrays: opengl error 0x0506
E {RSXThread} WriteColorBufferA(): glReadPixels: opengl error 0x0506

**Comment by Syphurith** [comment] 2015-03-29 06:17
@andre4688 It seems that the name was spelt wrongly.
Would you please tell us the ID of the game?
The game ID is alike `BCAS20310`, `BLES01921` and so on.
BTW I can not determine which game is with the name given by you.

If that is not so easy for you to do, please just follow this guide:
* First, run the game again. After it crashes, you can close rpcs3 and get the `rpcs3.log`. The log file should be along with your rpcs3 executable, after running.
* Then find somewhere to upload the log file. Mind please not just post the full log here, It could be very hugh to be included in the issue report.
* You can use gist.github.com to create a gist with its content, or use pastebin and similiar websites.

Hope this not a obfuscated one.

**Comment by tambry** [comment] 2015-03-29 06:34
After some discussion with on IRC, it would seem that the problem is that we don't properly extract the value from the instruction.

For reference of the (small) discussion on the problem:
<tambre> Does anybody know why some games try to execute like 20 different unknown (or illegal) VP/FP methods?
<tambre> It's common for certain games.
<AlexAltea> tambre: which ones?
<AlexAltea> (not which games, but which illegal vertex/fragment shader instructions)
<tambre> AlexAltea: All of them
<AlexAltea> tambre: what does the error say then?
<tambre> https://github.com/DHrpcs3/rpcs3/issues/919
<tambre> Andre's latest post
<AlexAltea> the opcode field is 6 bit long (i.e. < 0x40), so it seems the value is wrongly extracted from the instruction
<AlexAltea> I'm not 100% sure about this: but when DH fixed the LOOP/IF/REP stuff, he just OR'ed the opcode with some 0x40 flag
<AlexAltea> which is wrong
<AlexAltea> (not sure if it has been changed since then)
<AlexAltea> anyway, whatever it's causing this, find out why are these instructions >= 0x40
<AlexAltea> the only one that baffles me is 0x30
<AlexAltea> maybe it's not OR'ing but just left shifting

**Comment by Syphurith** [comment] 2015-05-09 13:26
@tambry After some search.. That seems to be related with unused ones. [OpenGL things](https://www.opengl.org/wiki/GLSL_:_common_mistakes)
From [This](http://comments.gmane.org/gmane.comp.compilers.emscripten/2889) Email list:
`It's a common optimization for GL and GLES drivers to eliminate unused uniforms from the linked shader programs. This is correct and valid behavior by the spec, and should be accounted for by the renderer code.`
`All browsers, except IE & possibly Opera, use the ANGLE shader validator. The shader validator is not where getUniformLocation is handled. Ultimately the location is provided by the GPU's GLSL compiler which may, indeed, optimized away unused uniforms. The WebGL layer converts the GPU provided location into the WebGLUniformLocation object that the app sees. `
From [OpenGL Wiki](https://www.opengl.org/wiki/OpenGL_Error) 0x0502 is **GL_INVALID_OPERATION**
And for `GLint glGetUniformLocation(GLuint program,  const GLchar *name);`
GL_INVALID_OPERATION is generated if program is not a program object.

**Comment by mainadmin** [comment] 2015-06-28 07:27
I have AMD Radeon card and also have sometimes this error 502. For example in Comet Crash NPEB90210.
Error 506 was less frequent, i think didnt see it some time.

**Comment by tambry** [comment] 2015-12-23 16:10
@andre4688 Is this still a problem?
Doesn't seem very relevant anymore, as OpenGL backend is currently basically abandoned, and Vulkan will arrive soon.

**Closed** 2016-01-07 17:35 UTC
Labels: bug, shaders
