### ISSUE TITLE
Regression of Shadow of the Damned

### ISSUE THREAD

**Issue by StalkerDolg** [RPCS3/rpcs3#5952] opened 2019-05-12 04:07 UTC
After the last revisions, the game start to freeze on cut scenes.
[RPCS3.zip](https://github.com/RPCS3/rpcs3/files/3169712/RPCS3.zip)

**Comment by AniLeo** [comment] 2019-05-20 00:39
Regressed in what build?

**Comment by StalkerDolg** [comment] 2019-05-20 01:06
I dont remember. Mabye 5923, or 5949, or 5951, one of this build, about 8 days ago

**Comment by RainbowCookie32** [comment] 2019-05-20 01:07
You should test them out then and mention it on the issue. Just saying that it regressed isn't helpful for developers that may want to take a look at the issue

**Comment by StalkerDolg** [comment] 2019-05-20 01:56
I'll test, after I get home from work. Mabye this problem still exist on last revision

**Comment by AniLeo** [comment] 2019-06-29 12:42
Closing due to lack of information, if it's still an issue on latest build open a regression report issue mentioning what build broke it

**Closed by AniLeo** 2019-06-29 12:42 UTC
Labels: Need Information
