### ISSUE TITLE
 inconsistent framerate from pr 4505 build RPCS3 v0.0.5-6733-4836a03a7

### ISSUE THREAD

**Issue by Nerboruto** [RPCS3/rpcs3#4653] opened 2018-05-23 21:53 UTC
my system spec
RPCS3 v0.0.5-6733-4836a03a7 Alpha | HEAD
Intel(R) Core(TM)2 CPU 4300 @ 2.64GHz | 2 Threads | 3.37 GiB RAM
gtx 530 nvidia 2gb ddr3
windows 10 

all my rpcs3 games becomes unplayable. big slowdown.
very stuttering and audio sobs.
latest version included.

rpcs3-v0.0.5-6724-75b40931 is ok for me.

**Comment by JohnHolmesII** [comment] 2018-05-23 21:57
You have got to be kidding me

**Comment by JohnHolmesII** [comment] 2018-05-23 22:32
Both of those builds are ancient, and your hardware is terrible. Not sure what you expect. Does the frame rate issue still happen in master?

**Comment by Nerboruto** [comment] 2018-05-23 23:07
yes, from that version to latest builds.
I'm practically cut out.
I do not know if it's structural or it's a bug for my configuration.

**Comment by CrabLugo** [comment] 2018-05-23 23:20
From the rpcs3 page: 
The system requirements for running the emulator vary depending on your hardware configuration. We have listed the minimum and recommend system requirements below. For the best experience, users should be running within the recommended system requirements. We **cannot guarantee the performance of system specifications below the minimum requirements** but you're always welcome to experiment.

Upgrade CPU to at least 4 cores haswell

**Comment by Zangetsu38** [comment] 2018-05-23 23:28
Change your conputer hmhm ps3 have 8 thread

**Comment by Nerboruto** [comment] 2018-05-23 23:30
I have another pc amd fm2 quad core 4,4ghz.
I'll do some tests on that PC to see if the slowdown is noticeable on that configuration.

**Comment by bigol83** [comment] 2018-05-24 08:59
I have the same issue. I could play Beyond Good and Evil Hd with 15-20 fps until two weeks ago, now it's all a big stutter with fps floating from 5 fps to 20 in the same location for no apparent reason and the stutter is huge. 

CPU G4560
hd 6450 

opengl

**Comment by Asinin3** [comment] 2018-05-24 11:18
Beyond Good & Evil framerate is same as normal for me on master with Vulkan and OpenGL
![image](https://user-images.githubusercontent.com/15137035/40477243-7d200336-5f35-11e8-8259-9d53b92386e9.png)
![image](https://user-images.githubusercontent.com/15137035/40482262-c000c1f0-5f43-11e8-8bc6-9049c8ccd084.png)

I tried old builds and got roughtly the same results.

**Comment by spyropt** [comment] 2018-05-24 13:01
try disabling spu loop detection and thread scheduler
and use the latest master

**Comment by Nerboruto** [comment] 2018-05-24 13:41
bigol83 try rpcs3-v0.0.5-6724-75b40931 and RPCS3 v0.0.5-6733-4836a03a7...

spyropt loop and scheduler disabled... the problem is pr 4505...

**Comment by bigol83** [comment] 2018-05-24 17:12
@Nerboruto Tried both 6733 and 6724. As you said 6733 has this issue, while 6724 doesn't.

**Comment by HenningJW** [comment] 2018-05-24 21:15
I don't experience the regression. Win10 1803 Core2 Quad with HD7850, with latest drivers and OpenGL. The performance is better with master (6845) than with 6724. All settings standard (fresh configs), but gpu texture scaling disabled (otherwise the lower 20% of the screen are cut off/black).

Do you have the latest drivers?

**Comment by Psycho-A** [comment] 2018-05-24 23:59
Maybe I'm wrong, but it similar to my issue #4643, although I have much more higher system specs and tested later builds, and it's strange for me. Maybe they have the same roots though?

**Comment by bigol83** [comment] 2018-05-25 08:18
@HenningJW Not all games i tested have regressed. Some have better performance in master compared to earlier builds. 

RDR and Beyond Good and Evil are much worse than before for me with these huge slowdowns and stutterings while Gran Turismo Hd and Ridge Racer have better performance.

**Comment by Nerboruto** [comment] 2018-05-25 11:11
I have tested all my 4 games ...
they all got worse. I'm forced to put the old build back because otherwise I'm cut off.

**Comment by HenningJW** [comment] 2018-05-25 14:51
@bigol83 sorry, I somehow missed mentioning that this was tested with Beyond Good & Evil, a game which has regressed for others.

**Comment by hcorion** [comment] 2018-05-29 18:51
Is this still an issue with the latest build?

**Comment by Psycho-A** [comment] 2018-05-29 23:02
> Is this still an issue with the latest build?

For me it doesn't happen on Windows 10, but I can't check it on Win 7 because of #4625.
It's needed to say for sure since I found that there are some differences in CPU managing between these OS versions.

**Comment by Nerboruto** [comment] 2018-05-30 11:34
rpcs3-v0.0.5-6860-4576a31f build tested 
with 2 games BLUS30767 Dragons Crown and NPEB00026 1942: Joint Strike
low framerate and bad stuttering.
completely unplayable for me.
revert to rpcs3-v0.0.5-6724-75b40931.

**Comment by bigol83** [comment] 2018-05-31 08:22
Tested with latest build 6869, it killed performance even more in Beyond Good and Evil HD. 

It passed from being floating 5-20 fps to being around 5 fps in every situation, menu or ingame. 

Can you confirm you have a worse performance with last build too @Nerboruto ?

**Comment by Nerboruto** [comment] 2018-05-31 10:40
rpcs3-v0.0.5-6880 tested with 1942 joint strike
completely broken and not playable.
emulation stop for 4-5 seconds continuously.

**Comment by SakataGintokiYT** [comment] 2018-06-01 12:44
@kd-11 
I think regression only affect dual core cpu.
[Tested with amd fx 6300]

Before:
![bez tytulu1](https://user-images.githubusercontent.com/13681488/40841140-b24190d2-65a9-11e8-94d0-416a82c12e57.png)

--------------------------------------------------------------------------------------------------------------
After #4505 [rsx: Stuff ]:
![bez tytulu2](https://user-images.githubusercontent.com/13681488/40841173-c934ae5a-65a9-11e8-885d-c9f415c2d1a1.png)

**Comment by Emulator-Team-2** [comment] 2018-06-01 12:58
@kd-11 
I think regression only affect dual core cpu.
[Tested with amd fx 6300]

Before:
![bez tytulu1](https://user-images.githubusercontent.com/38318848/40841788-fdc6798a-65ab-11e8-98d4-dcba3f248584.png)

-----------------------------------------------------------------------------------------------------------
After #4505 [rsx: Stuff] :
![bez tytulu2](https://user-images.githubusercontent.com/38318848/40841835-2616e8d4-65ac-11e8-8ee2-d0832770c628.png)

**Comment by Psycho-A** [comment] 2018-06-02 03:00
@bigol83 for me it started from merging #4631. There were some changes in CPU managing for SPU, and it definitely had negative impact to some processors. It's sad if developers won't pay their attention to it if they not able to reproduce our issues.

**Comment by bigol83** [comment] 2018-06-02 08:17
This is a regression that mainly affects dual core and quad core cpus, developers probably have much newer cpus and they can't even test this.

**Comment by Psycho-A** [comment] 2018-06-02 18:13
Then I think they need more beta-testers with quad-core processors. I don't think someone sane will be used the PS3 emulator on dual-core processors, but quad-core are still too popular for now and have enough performance to run some games.

**Comment by JohnHolmesII** [comment] 2018-06-02 18:28
There are quad core testers, but the fact if the matter is rpcs3 is demanding. I think updating the sys reqs to reflect the need for 8 threads.

**Comment by Psycho-A** [comment] 2018-06-03 02:14
I understand it, but problem is only what was working good before, works really bad for now, and it's not a reason to talk about gaining system requirements. The currently described problems are **not** performance degradation - it's more like bugs with all these random stutterings!

**Comment by CrabLugo** [comment] 2018-06-03 02:40
RPCS3 requirements may raise along with increasing emulating accuracy, and it's happening.
6 thread is a reasonable minimum for playing bigger games.
It's also propably possible to prepare less accurate builds for 4 thread CPUs. Correct me if i am wrong

**Comment by Psycho-A** [comment] 2018-06-03 04:45
@CrabLugo I repeat, the performance is not suffer with new builds - I'm just getting random stutterings with peak CPU load, but between of them the performance is the same as before. And it's only on Windows 7 for me, that directly says that something went wrong after that unhappy PR. Let's Nekotekina (PR's author) say what can it be...

**Comment by logan83** [comment] 2018-10-01 23:04
i think best build is rpcs3-v0.0.5-6724-75b40931.. the latest now is slow ..very very slow.. im playing silent hill downpour with this build 12-30fps. on dual core 3.16ghz .. win 10.. i know my cpu is old but please dev rpcs3, give a small chances to old cpu.. not only core i3/5/7 cpu.. thumbs up to dev

**Comment by AniLeo** [comment] 2019-09-18 14:42
Closing since it's an old thread, RPCS3 has changed a lot since then, and discussion was based on 2 thread CPUs on the first place which are way below recommended requirements

**Closed by AniLeo** 2019-09-18 14:42 UTC
