### ISSUE TITLE
Kingdom Hearts 1.5 Remix [BLES01897] Freeze during the game

### ISSUE THREAD

**Issue by bolverk93** [RPCS3/rpcs3#5608] opened 2019-01-28 16:33 UTC
Hello everybody, as indicated in title, my game freeze ever, wrapped after 5 minutes, in other cases after 2 hours, but the music and FPS continue to work, please help me guys, i don't know what to do. 

My spec : 
CPU : I7-4790K
GPU : ASUS ROG Strix GeForce GTX 1070
RAM : Kingston HyperX Fury 8GBX2
SSD : SAMSUNG 850EVO 500GB (games and emulator is here)

My RPCS3 Confuguration : 
CPU
PPU : LLVM Recompiler (fastest)
SPU : ASMJIT Recompiler (faster)
SPU Threads : Auto
Firmware : liblv2.sprx only
Additional Settings : Enable SPU loop detection and SPU cache
SPU Block Size : Safe
GPU
Renderer : Vulkan
Device : GTX 1070
Aspect : Auto
FPS : 60
Anisotropic Filter : 16x
Default Resolution : 1280x720
Resolution Scale : 3840x2160
Resolution Scale Threshold : 16x16
Additional Settings : Write Color Buffers

**Comment by AniLeo** [comment] 2019-01-28 16:35
Missing RPCS3.LOG file, don't copy paste stuff from the emulator's log window

**Comment by MSuih** [comment] 2019-01-28 16:36
Probably a duplicate of #5351. Are you playing in fullscreen, and have you tried using opengl?

**Comment by bolverk93** [comment] 2019-01-28 16:38
> 
> 
> Missing RPCS3.LOG file, don't copy paste stuff from the emulator's log window

Sorry, how should I copy it?

**Comment by bolverk93** [comment] 2019-01-28 16:41
> 
> 
> Probably a duplicate of #5351. Are you playing in fullscreen, and have you tried using opengl?

No i don't play in fullscreen, i test OpenGL but i have much missing grafics and glitch

**Comment by bolverk93** [comment] 2019-01-28 16:44
[RPCS3.log](https://github.com/RPCS3/rpcs3/files/2803969/RPCS3.log)

This? Sorry for my inexperience and bad english, I'm just looking for a solution

**Comment by RainbowCookie32** [comment] 2019-01-28 16:46
> [RPCS3.log](https://github.com/RPCS3/rpcs3/files/2803969/RPCS3.log)
> 
> This? Sorry for my inexperience and bad english, I'm just looking for a solution

You got the correct file, but we need the log from the freeze. Run the game, reproduce the freeze and upload that log

**Comment by bolverk93** [comment] 2019-01-28 16:46
[LOG.txt](https://github.com/RPCS3/rpcs3/files/2803983/LOG.txt)
This? Sorry for my inexperience and bad english, I'm just looking for a solution

**Comment by RainbowCookie32** [comment] 2019-01-28 16:47
> [LOG.txt](https://github.com/RPCS3/rpcs3/files/2803983/LOG.txt)
> This? Sorry for my inexperience and bad english, I'm just looking for a solution

No, that's a copy paste from the emulator

**Comment by AniLeo** [comment] 2019-01-28 17:07
If you're looking to get support and not submit an issue report, this is not the place

Ask for support on the appropriate channels, once you verified it's not an issue with your dump, drivers or settings, know how to properly submit an issue with a log file and steps to reproduce, submit a correct issue

---

**Please read [**the guidelines**](https://github.com/RPCS3/rpcs3/blob/master/.github/CONTRIBUTING.md) before opening an issue.**

Remember that the GitHub Issue Tracker is not the place to ask for support or to submit Game Compatibility reports. You must use [**our forums**](https://forums.rpcs3.net/forum-18.html) for that.

The issue has been marked as **Invalid** and closed.

**Closed by AniLeo** 2019-01-28 17:07 UTC
Labels: Need Information

**Comment by bolverk93** [comment] 2019-01-28 17:36
> 
> 
> If you're looking to get support and not submit an issue report, this is not the place
> 
> Ask for support on the appropriate channels, once you verified it's not an issue with your dump, drivers or settings, know how to properly submit an issue with a log file and steps to reproduce, submit a correct issue
> 
> **Please read [**the guidelines**](https://github.com/RPCS3/rpcs3/blob/master/.github/CONTRIBUTING.md) before opening an issue.**
> 
> Remember that the GitHub Issue Tracker is not the place to [ask for support](https://github.com/RPCS3/rpcs3/wiki/How-to-ask-for-Support) or to submit Game Compatibility reports, you must use [**our forums**](https://forums.rpcs3.net/forum-18.html) for that.
> 
> The issue has been marked as **Invalid** and closed.

I can't register at the rpsc3 forum because of the captcha that doesnt let me complete the registration

**Comment by RainbowCookie32** [comment] 2019-01-28 17:37
The forums isn't the only option. https://github.com/RPCS3/rpcs3/wiki/How-to-ask-for-Support

**Comment by bolverk93** [comment] 2019-01-28 17:38
however, the log file is 100mb, I can not share it

**Comment by RainbowCookie32** [comment] 2019-01-28 17:39
> however, the log file are 100mb, I can not share it

Go to Discord, we can help you there

**Comment by AniLeo** [comment] 2019-01-28 17:40
Forums are a must for game compatibility reports, if you click the support link there are other options
