### ISSUE TITLE
Regression: Demon's Souls graphical corruption

### ISSUE THREAD

**Issue by isshininu** [RPCS3/rpcs3#3754] opened 2017-11-19 00:48 UTC
It seems that latest PR's (one of them) adds an regression, resulting in plume of corrupted plastic textures, making game almost unbeatable in some points.

[RPCS3.log.gz](https://github.com/RPCS3/rpcs3/files/1485177/RPCS3.log.gz)

![02](https://user-images.githubusercontent.com/6324523/32986155-df7bc7ce-cce4-11e7-9807-d333727a0cc7.png)
![3](https://user-images.githubusercontent.com/6324523/32986161-0218d420-cce5-11e7-9795-c0ec74da440a.png)

**Comment by kd-11** [comment] 2017-11-19 08:28
Steps to reproduce? I haven't encountered this bug. Also, with DeS, its best to clear out /dev_hdd1 if you experience any issues as the game writes alot of stuff in there.

**Comment by isshininu** [comment] 2017-11-19 11:55
Okay, i'll clear this folder today and see.

**Comment by kd-11** [comment] 2017-11-19 16:01
I have encountered this in boletaria. Reloading the area makes it go away making it near impossible to debug without regression tests. So we need to identify when it started. Loading in the first time was fine, then got corrupted after first death and minor corruption remained one more time then it was cleared. No amount of dying or warping in and out made it appear again.

**Comment by isshininu** [comment] 2017-11-25 17:19
wow

https://youtu.be/L_yAZPZFZek

**Comment by theoldsport** [comment] 2017-12-03 04:09
After testing old builds, I've narrowed PR #3699 as the first time this corruption arose in both renderers. It also appears to cause the flickering of this title in GL. Due to time, I am unable to narrow a commit further.

**Comment by Asinin3** [comment] 2017-12-03 04:18
![image](https://user-images.githubusercontent.com/15137035/33522289-100a6fd0-d839-11e7-99a5-7651c2a4df06.png)

**Comment by Asinin3** [comment] 2017-12-03 04:19
![image](https://user-images.githubusercontent.com/15137035/33522300-3ade0532-d839-11e7-8bf6-13c08a712c13.png)

**Comment by theoldsport** [comment] 2017-12-03 04:20
Oh that's me :D

**Comment by kd-11** [comment] 2017-12-03 04:30
Thats disappointing. I'm guessing editing the default return for undefined vertex inputs to 0 fixes the issue. I'll think of a better workaround.

**Comment by kd-11** [comment] 2017-12-03 05:42
A proper fix is included here https://github.com/RPCS3/rpcs3/pull/3827. I dont have a save near corrupt areas at the moment so I dont know if the vertex glitches are fixed for sure Opengl flickering is a separate issue that will be resolved soon.

**Comment by theoldsport** [comment] 2017-12-03 05:46
Will test soon as it compiles

**Comment by kd-11** [comment] 2017-12-05 11:18
https://github.com/RPCS3/rpcs3/pull/3858 Should hide this fairly well. To clarify, the issue has always been there under the right conditions, but recent builds made it easier to manifest. The rearrangement of code makes it harder to encounter in the time being as a better global solution is being designed.

**Comment by kd-11** [comment] 2017-12-06 09:57
Please reopen if you are able to reproduce with significant occurrence anywhere except northern limits.

**Closed by kd-11** 2017-12-06 09:57 UTC
Labels: Regression
