### ISSUE TITLE
ModNation™ Racers [NPUA80535] Weird texture bug occurence

### ISSUE THREAD

**Issue by koochiigo** [RPCS3/rpcs3#13579] opened 2023-03-26 11:15 UTC
### Quick summary

On later versions of Modnation Racers(1.09-1.11), a weird in-game texture corruption will occur. This occurence will happen only in the Races and the Hub area while in Creation Station textures seem to appear normally.

### Details

The mods and karts would have weird texture corruptions after being used for a period of time. It would appear after changing into the other mod and then back to the one used before. Usually, those occurences would happen on user-published creations and rarely on the default ones. Statues in the Hub Area(Modspot) also seem to have this kind of occurence. Version 1.00 of the game doesn't have this bug however, which would assume there is some changes in game that would make the bug appear on emulator.

### Attach a log file

[RPCS3.log.gz](https://github.com/RPCS3/rpcs3/files/11071394/RPCS3.log.gz)

### Attach capture files for visual issues

https://drive.google.com/file/d/14Po6t7FQ3GzYEYqZAoGV5cTNvAEPMvaf/view?usp=sharing

### System configuration

GPU - NVIDIA Quadro P1000
CPU - AMD Ryzen 7 2700X Eight-Core

**Comment by Asinin3** [comment] 2023-03-26 11:28
Closing as duplicate of #7365

**Closed by Asinin3** 2023-03-26 11:28 UTC
