### ISSUE TITLE
GT6 PPU LLVM Softlock

### ISSUE THREAD

**Issue by xddxd** [RPCS3/rpcs3#6499] opened 2019-09-08 13:24 UTC
Hello,

Gran Turismo 6 BCES01893, when using PPU LLVM, softlocks (audio cuts out, input dies, the race freezes, but you can still see the crowd moving around) when entering a track; either in the beginning of the race, or in the screen where you can start the race, change driving options, etc.  
This does not happen with any of the PPU Interpreters. One thing to note, is that on a fresh save, in the tutorial it does not happen and you can finish the race.
[RPCS3.log.gz](https://github.com/RPCS3/rpcs3/files/3587630/RPCS3.log.gz)

System specifications:
CPU: Ryzen 7 2700
GPU: RX 580 4GB
RAM: 8GB DDR4-3000
OS: Windows 10 1903
GPU Driver: 19.8.1

Settings:
PPU LLVM/PPU Interpreter and SPU Mega LLVM, Vulkan
Force CPU Blit
Game Version 1.02 (happens on 1.05 too)
RPCS3 v0.0.7-8664-0c69b7da

**Comment by arabek** [comment] 2019-09-16 10:14
Same happens to me with PPU LLVM, switching to PPU Interpreter (fast) on Threadripper 1950X makes the game playable. Seems to be AMD specific.

**Comment by elad335** [comment] 2019-09-16 10:15
Maybe it is a regression?

**Comment by xddxd** [comment] 2019-09-16 10:22
I could not find the build where this began, so I don't know where it regressed.

**Comment by elad335** [comment] 2019-09-16 10:25
You need to clear PPU cache entirely everytime you test (clears both firmeare's and game's)
this means clearing rpcs3/cache.
Thisid the only way to test for the build where it regressed.

**Comment by xddxd** [comment] 2019-09-16 10:28
Okay, will do.

**Comment by xddxd** [comment] 2019-09-16 14:44
Urgh I give up, it still happens even as far back as 0.0.6-8341. Maybe this is something AMD specific and no one noticed?

**Comment by ju2ef1986** [comment] 2019-09-16 14:52
Nah, this also happened on Nvidia intel duo.

**Comment by kd-11** [comment] 2019-09-16 15:04
There seem to be several triggers of this, the obvious one I'm seeing is that somebody is supposed to wake RSX thread when entering a race but doesn't, so you get a semaphore timed out. However unlike most games, this freeze is real and trying to escape the deadlock by just printing an error and continuing leads to a proper crash later on, either invalid location or gcm_intr_thread crash. I tested the game with infinite timeout (0) and it is truly frozen/deadlocked. I'll try and see if I can somehow get ingame with 'mastered' inputs and try to load ingame without graphics output.

**Comment by kd-11** [comment] 2019-09-16 15:25
Disabling the renderers is much worse, crashes almost instantly on boot.

**Comment by elad335** [comment] 2020-02-07 15:53
Was this tasted with rsx wake up delay?

**Comment by xddxd** [comment] 2020-03-07 00:34
Yes, it does not help.

**Comment by elad335** [comment] 2020-10-26 07:10
Duplicate of #6427

**Closed by elad335** 2020-10-26 07:10 UTC
