### ISSUE TITLE
Gran Turismo 5 crash on start

### ISSUE THREAD

**Issue by NiewidomyWWW** [RPCS3/rpcs3#13946] opened 2023-06-03 21:57 UTC
### Quick summary

Gran Turismo 5 [BCES00569] crashes together with emulator at start.

### Details

With default settings + wiki recommendations (also checked with default settings) the game will start and then immediately closes together with whole emulator after game logo (2.0) or at ACCESSING DATA screen (first button press) (1.0)
tried to remove all caches, removed save data.
[RPCS3.log](https://github.com/RPCS3/rpcs3/files/11644329/RPCS3.log)

### Attach a log file

[RPCS3.log](https://github.com/RPCS3/rpcs3/files/11644330/RPCS3.log)

### System configuration

CPU: Intel 12400F
GPU: MSI RTX 2060 Gaming Z (535.98  WHQL driver ver.)
MOBO: ASUS Prime H670 Prime D4

**Comment by AniLeo** [comment] 2023-06-11 15:53
Validate your game dump, as other people can't reproduce this
https://wiki.rpcs3.net/index.php?title=Help:Validating_PlayStation_3_game_dumps

Also, make sure to delete the cache in **dev_hdd1** before retesting again on latest build

**Comment by Asinin3** [comment] 2023-07-23 01:12
Closing, unable to reproduce this issue. Likely bad game dump.

**Closed by Asinin3** 2023-07-23 01:12 UTC
Labels: Need Information
