### ISSUE TITLE
Dishonored [BLUS41038] Cannot enter the game

### ISSUE THREAD

**Issue by lastavenger2004** [RPCS3/rpcs3#16304] opened 2024-11-09 17:45 UTC
### Quick summary

After going through logos, it doesn't even go to the main menu.

### Attach a log file

[RPCS3.log.gz](https://github.com/user-attachments/files/17688839/RPCS3.log.gz)

**Comment by FlexBy420** [comment] 2024-11-09 17:55
You need to use settings that will slow RSX down, rsx fifo atomic n ordered, driver wake up delay maxed etc

**Comment by FlexBy420** [comment] 2024-11-09 17:55
Also duplicate of #13929

**Comment by lastavenger2004** [comment] 2024-11-09 18:05
> Also duplicate of #13929

The BLUS41038 wasn't in the compatibility database. I just thought I installed a version that is not supported by RPCS3 crew yet, so I didn't notice it's a duplicate.

Also, I've tested with your settings. I turned FSX FIFO to ordered and atomic.
I also set driver wake up delay to 800μs (the max amount).

The game was OK in main menu, until I tried a new game, and the game crashed.

Here's the new log.
[RPCS3.log.gz](https://github.com/user-attachments/files/17688899/RPCS3.log.gz)

**Comment by lastavenger2004** [comment] 2024-11-09 18:09
High upscale fixed it, for now

**Comment by lastavenger2004** [comment] 2024-11-09 18:11
The game crashed after I tried to move my character, after the first cutscene on the boat.

[RPCS3.log.gz](https://github.com/user-attachments/files/17688913/RPCS3.log.gz)

**Comment by lastavenger2004** [comment] 2024-11-09 18:15
Please it's not completed yet. the issue still exists after the first cutscene

**Closed** 2024-11-09 18:14 UTC

**Comment by lastavenger2004** [comment] 2024-11-09 18:36
I used Accurate RSR and Multithread RSX. Not sure what exactly fixed the issue, but it fixed the issue.
