### ISSUE TITLE
Hard crash on createdevice.elf from Test Suite of Short Wave PS3 Emulator (when VSYNC turned OFF)

### ISSUE THREAD

**Issue by bevanweiss** [RPCS3/rpcs3#8636] opened 2020-07-26 07:12 UTC
## Quick summary
When run with VSYNC on, it appears to run locked to 60FPS (and doesn't crash)
However, when VSYNC is turned off, the FPS goes up to ~600FPS, and then the entire RPCS3 application freezes up (after about 2 minutes on my laptop).
It appears to happen in both Vulken and OpenGL, and happens with both Multithread RSX and not.
If VSYNC is turned on, then it appears to run fine.

## Details
When run on my laptop (with VSYNC disabled), it starts off pretty 'easy', but very quickly ramps up the CPU utilisation, and the fan speed to 'jet engine' level.  Then about half a minute after fans are at maximum thrust, it locks up.

It appears to be a home brew test suite as part of the Short Waves PS3 emulator.
But might give us some good test information for RPCS3.

Short Waves PS3 emulator: http://wololo.net/downloads/index.php/download/8128

createdevice.elf here:
https://drive.google.com/file/d/1hRJVFZeuHklrhPzsBmQ_lXL-qWjOaT7l/view?usp=sharing

I'm not sure whether we do have an internal bug here that this is triggering.
It's probably a bit too advanced for my current skill level to analyse much more for now.  But wanted to put the issue out there for potential investigation.

#### 1. Please attach RPCS3's log.
Log can be found here (7zip format):
https://drive.google.com/file/d/178Ylb4Xf9sZHCaCaVXQzBNmjcwujqhxp/view?usp=sharing

#### 2. If you describe graphical issue, please provide an RSX capture and a RenderDoc capture that demonstrate it.
NOT APPLICABLE

#### 3. Please attach screenshots of your problem.
NOT APPLICABLE

#### 4. Please provide comparison with real PS3.
NOT APPLICABLE

#### 5. Please provide your system configuration:
* OS - Windows 10 2004
* CPU - Intel i7-9750H
* GPU - Nvidia RTX2060M

**Comment by nitroos-ai** [comment] 2022-05-12 04:34
Still an issue?

**Comment by Megamouse** [comment] 2023-02-15 21:38
The test actually closes itself after x frames. so the higher the framerate, the faster it closes.
There seems to have been an issue with closing the game 2-3 years ago. But I can't reproduce it anymore.

**Closed by Megamouse** 2023-02-15 21:38 UTC
