### ISSUE TITLE
METAL GEAR SOLID 2 & 3 HD EDITION [NPUB30609] [NPUB30610] stopped working from version rpcs3-v0.0.20-13172-ef0bee92 onwards

### ISSUE THREAD

**Issue by Ominousonion666** [RPCS3/rpcs3#11369] opened 2022-01-13 03:38 UTC
They either outright crash RPCS3 or get stuck in this loading screen. Both worked fine before this update.
![FPS_ 15 01 _ Vulkan _ 0 0 20-13175 _ METAL GEAR SOLID 3 HD EDITION  NPUB30610  13_01_2022 8_59_16 AM](https://user-images.githubusercontent.com/45669443/149260973-e029f0d7-3278-4d4b-9cbf-2c47aceaba46.png)

Logs

MGS2: [RPCS3.log](https://github.com/RPCS3/rpcs3/files/7859640/RPCS3.log)
MGS3: [RPCS3.log](https://github.com/RPCS3/rpcs3/files/7859621/RPCS3.log)

**Comment by RainbowCookie32** [comment] 2022-01-13 03:43
Probably a duplicate of #11368, which itself is probably a duplicate of #11360

**Closed** 2022-01-13 07:02 UTC

**Comment by kd-11** [comment] 2022-01-13 07:03
Should have been fixed by https://github.com/RPCS3/rpcs3/pull/11370
