### ISSUE TITLE
Demon Souls: after a long play renderer(vulkan) starts freezing. Stably.

### ISSUE THREAD

**Issue by truthfinder** [RPCS3/rpcs3#7035] opened 2019-11-28 18:05 UTC
Hi,

After EACH long play (around an hour) video start freezing. Image doesn't change, mouse cursor shows windows UI rotating circle showing wait for some process. Due to sounds plays and game reacts to joystick controls the game keep working. I thought the game is totally broken, but today after around a minute or two image were unfreezed for a short period of time. And freezed again. It repeated around three times. (I tried to kill dragon and didn't want to do it again. So I just tried to kill targeted dragon by sound.) I think my log can be useful. I packed it myself because I had to make forced shutdown. Check around the last 10 minutes of the log.

BLES00932 Demon Souls
rpcs3 0.0.7-9185 (Nothing really matters, guess any 0.0.7, tested 8674, 9058, 9096 too)
After some minutes it can unfreeze.

[rpcs3-9185.zip](https://github.com/RPCS3/rpcs3/files/3902740/rpcs3-9185.zip)

Best regards, Vyacheslav

**Comment by kd-11** [comment] 2020-01-15 18:40
Retest, this game has undergone significant testing in recent days and everything seems to be fine.

**Comment by truthfinder** [comment] 2020-01-16 17:15
I played last week old version for a long periods of time and didn't see this issue. That pretty strange. The only update that I can blame in this change is windows. So the game already plays well.
Anyway I'll update to the last rpcs and test this issue again.

**Comment by kd-11** [comment] 2020-01-18 19:33
I'll pre-emptively close this issue. If the problem is still present, ask to reopen.

**Closed by kd-11** 2020-01-18 19:33 UTC

**Comment by truthfinder** [comment] 2020-01-19 13:35
Played for a long time. Everything is OK now.
