### ISSUE TITLE
ISSUE: Unregistered PPU function: Revenant Saga

### ISSUE THREAD

**Issue by markcagatandavis** [RPCS3/rpcs3#4683] opened 2018-06-01 16:12 UTC
Game Fails to load: 

Game: Revenant Saga
Serial: NPUB31863

```
U {PPU[0x1000000] Thread (main_thread) [0x01577c8c]} sys_spu TODO: Unsupported SPU Thread Group type (0x18)
U {PPU[0x1000000] Thread (main_thread) [0x01577d80]} sys_spu TODO: Unimplemented SPU Thread options (0x2) x5
U {PPU[0x1000000] Thread (main_thread) [0x0157de58]} sys_prx TODO: _sys_prx_get_module_id_by_name(name=“cellLibprof”, flags=0, pOpt=*0x0)
E {PPU[0x1000000] Thread (main_thread) [0x0157de58]} 'sys_prx_get_module_id_by_name' failed with 0x8001112e : CELL_PRX_ERROR_UNKNOWN_MODULE [1]
S {PPU[0x1000005] Thread (UnityMain) [0x010b3a90]} PPU: LLVM: Loaded module v2-PRXManager.sprx-21E8E7E8DF05D3D1-haswell.obj
S {PPU[0x1000005] Thread (UnityMain) [0x010b3a90]} sys_prx: Loaded module: /dev_hdd0/game/NPUB31863/USRDIR/Media/PRXManager.sprx
E {PPU[0x1000005] Thread (UnityMain) [0x00aac9d0]} 'sys_fs_open' failed with 0x80010006 : CELL_ENOENT, “/app_home/mono/etc/mono/config” [1]
E {PPU[0x1000005] Thread (UnityMain) [0x00aac9d0]} 'sys_fs_open' failed with 0x8001003a : CELL_ENOTMOUNTED, “//.mono/config” [1]
E {PPU[0x1000005] Thread (UnityMain) [0x00aac9d0]} 'sys_fs_open' failed with 0x80010006 : CELL_ENOENT, “/dev_hdd0/game/NPUB31863/USRDIR/Media/Managed/mono/config” [1]
E {PPU[0x1000005] Thread (UnityMain) [0x00aac9d0]} 'sys_fs_open' failed with 0x8001003a : CELL_ENOTMOUNTED, “//.mono/config” [2]
E {PPU[0x1000005] Thread (UnityMain) [0x00a7f6ac]} 'sys_mutex_unlock' failed with 0x80010009 : CELL_EPERM [1]
E {PPU[0x1000005] Thread (UnityMain) [0x00a7f6ac]} 'sys_mutex_unlock' failed with 0x80010009 : CELL_EPERM [2]
E {PPU[0x1000005] Thread (UnityMain) [0x00a7f6ac]} 'sys_mutex_unlock' failed with 0x80010009 : CELL_EPERM [3]
S {PPU[0x1000005] Thread (UnityMain) [0x010b3a90]} sys_prx: Loaded module: /dev_hdd0/game/NPUB31863/USRDIR/Media/Managed/mscorlib.dll.sprx
S {PPU[0x1000005] Thread (UnityMain) [0x010b3a90]} PPU: LLVM: Loaded module v2-mscorlib.dll.sprx.b.sprx-A2E77ED78909C445-haswell.obj
S {PPU[0x1000005] Thread (UnityMain) [0x010b3a90]} sys_prx: Loaded module: /dev_hdd0/game/NPUB31863/USRDIR/Media/Managed/mscorlib.dll.sprx.b.sprx
U {PPU[0x1000005] Thread (UnityMain) [0x010b5f88]} sys_prx TODO: _sys_prx_unload_module(id=0x2300c100, flags=0x0, pOpt=*0x0)
E {PPU[0x1000005] Thread (UnityMain) [0x015b2090]} 'sys_fs_open' failed with 0x80010006 : CELL_ENOENT, “/dev_hdd0/game/NPUB31863/USRDIR/Media/Managed/mono/gac/policy.2.0.mscorlib/0.0.0.0__b77a5c561934e089/policy.2.0.mscorlib.dll.sdat” [1]
E {PPU[0x1000005] Thread (UnityMain) [0x015b2090]} 'sys_fs_open' failed with 0x80010006 : CELL_ENOENT, “/dev_hdd0/game/NPUB31863/USRDIR/Media/Managed/mono/gac/policy.2.0.mscorlib/0.0.0.0__b77a5c561934e089/policy.2.0.mscorlib.dll” [1]
E {PPU[0x1000005] Thread (UnityMain) [0x00aac9d0]} 'sys_fs_open' failed with 0x80010006 : CELL_ENOENT, “/dev_hdd0/game/NPUB31863/USRDIR/Media/Managed/mscorlib.dll.config” [1]
E {PPU[0x1000005] Thread (UnityMain) [0x00aac9d0]} 'sys_fs_open' failed with 0x80010006 : CELL_ENOENT, “/dev_hdd0/game/NPUB31863/USRDIR/Media/Managed/mono/assemblies/mscorlib/mscorlib.config” [1]
F {PPU[0x1000005] Thread (UnityMain) [0x010b5c08]} class std::runtime_error thrown: Unregistered PPU function
E {PPU[0x1000005] Thread (UnityMain) [0x010b5c08]} Stat: 'sys_mutex_unlock' failed with 0x80010009 : CELL_EPERM [x45]
```

**Comment by AniLeo** [comment] 2018-06-01 16:22
Duplicate of #2909
Game added to the list

**Closed by AniLeo** 2018-06-01 16:22 UTC
