### ISSUE TITLE
LLVM Silent Hill  class std::runtime_error thrown: Null function Error

### ISSUE THREAD

**Issue by aakh1361** [RPCS3/rpcs3#2546] opened 2017-03-17 15:12 UTC
Silent Hill: Homecoming [BLES00460]
PPU Decoder: Recompiler (LLVM)
SPU Decoder: Recompiler (ASMJIT)

when create .obj File

[RPCS3.zip](https://github.com/RPCS3/rpcs3/files/850954/RPCS3.zip)

> F {PPU[0x1000000] Thread (main_thread) [0x00010230]} class std::runtime_error thrown: Null function
(in file C:\rpcs3\Utilities\JIT.cpp:86)

**Comment by AniLeo** [comment] 2017-03-17 15:37
SPU JIT initialization...

Title: HEAVY RAIN™ Demo
Title ID: NPEA90053

Wrong log

**Comment by darkredflame** [comment] 2017-03-17 18:32
Here is my RPCS3 and SPUJIT log for this game, I get the same error message as above when trying to run the game using the LLVM recompiler.
[RPCS3.zip](https://github.com/RPCS3/rpcs3/files/851449/RPCS3.zip)
[SPUJIT.zip](https://github.com/RPCS3/rpcs3/files/851450/SPUJIT.zip)

**Comment by aakh1361** [comment] 2017-03-17 21:23
Retest and don't create SPU 
only RPCS3.txt
@AniLeo

**Comment by aakh1361** [comment] 2017-03-17 21:46
i retest and don't create SPU JIT whit this build "RPCS3 v0.0.2-9-d38c4e6 Alpha"
but darkredflame  attach spu jit

**Comment by aakh1361** [comment] 2017-03-18 14:30
#1870

**Comment by raven02** [comment] 2017-03-24 14:46
Duplicate of #1870

**Closed by raven02** 2017-03-24 14:46 UTC
Labels: bug, cpu
