### ISSUE TITLE
OGL: Saint Seiya Brave Soldiers unimplemented opcode

### ISSUE THREAD

**Issue by rcaridade145** [RPCS3/rpcs3#1749] opened 2016-06-05 13:17 UTC
While trying to run Saint Seiya Brave Soldiers i get RSX: Unimplemented sca_opcode BRB on the console. This is on the OpenGL backend.

**Comment by raven02** [comment] 2016-06-05 14:17
I think it happen on other backends? and does it boot in-game

**Comment by rcaridade145** [comment] 2016-06-05 14:25
It does go in game but crashes after this screen
![captura de ecra de 2016-06-05 15-23-16](https://cloud.githubusercontent.com/assets/11843298/15806010/797ead84-2b31-11e6-9495-2c3979ebd2a0.png)

How do i enable the Vulkan backend to test? I'm running Ubuntu with Nvidia drivers 367.18 which should support Vulkan but on the combobox i only get Null and OpenGL

**Comment by raven02** [comment] 2016-06-05 14:45
What GPU you are using ?

**Comment by rcaridade145** [comment] 2016-06-05 14:59
Nvidia 650.

LLE : libspurs_jq and libsre.

**Comment by mob41** [comment] 2016-06-05 15:03
Seems like we mixed the check of Windows to Vulkan

```
#ifdef _MSC_VER
	{ "DX12", PURE_EXPR(std::make_shared<D3D12GSRender>()) },
	{ "Vulkan", PURE_EXPR(std::make_shared<VKGSRender>()) },
#endif
```

**Comment by mob41** [comment] 2016-06-05 15:06
Therefore, Vulkan is only shown in Windows that the preprocessor bypassed the selection...

https://github.com/RPCS3/rpcs3/blob/master/rpcs3/rpcs3.cpp#L98

**Comment by raven02** [comment] 2016-06-05 15:13
Looks like only OGL works upto title . DX12 hits the following error in the 'Now loading'

> {rsx::thread} RSX: FS build failed:D:\rpcs3\FragmentProgram.hlsl(135,12-55): warning X3570: gradient instruction used in a loop with varying iteration, attempting to unroll the loop
> D:\rpcs3\FragmentProgram.hlsl(126,3-36): error X3511: unable to unroll loop, loop does not appear to terminate in a timely manner (248 iterations) or unrolled loop is too large, use the [unroll(n)] attribute to force an exact higher number

**Comment by mob41** [comment] 2016-06-05 15:21
@raven02 But the problem is that Vulkan cannot even used in Linux cause the code blocked it.

**Comment by raven02** [comment] 2016-06-05 15:24
@mob41 yep agreed .Probably he can try to compile one to fix that cod to re-run again.

**Comment by raven02** [comment] 2016-06-05 15:44
Not too sure if it is the gradient instruction TXD , checking it.

**Comment by mob41** [comment] 2016-06-05 16:13
@raven02 I am surely that Linux can run Vulkan with the NVIDIA driver 367.18 ([Official Page](https://developer.nvidia.com/vulkan-driver)). And once the driver is installed to ubuntu. It should run. Whatever, Vulkan has no support for Mac.

Maybe the preprocessor modify to this. ```wx/platform.h```
```cpp
cfg::map_entry<std::function<std::shared_ptr<GSRender>()>> g_cfg_gs_render(cfg::root.video, "Renderer", "OpenGL",
{
	{ "Null", PURE_EXPR(std::make_shared<NullGSRender>()) },
	{ "OpenGL", PURE_EXPR(std::make_shared<GLGSRender>()) },
#ifdef _MSC_VER
	{ "DX12", PURE_EXPR(std::make_shared<D3D12GSRender>()) },
#endif
#ifndef __WXOSX__
	{ "Vulkan", PURE_EXPR(std::make_shared<VKGSRender>()) },
#endif
});
```

https://github.com/RPCS3/rpcs3/commit/d287ba44ce489c745c0fd5b90f2c3cbd78827594#diff-811302300b2bbbbbdf830254005554c3R147

**Comment by mob41** [comment] 2016-06-05 16:19
>Not too sure if it is the gradient instruction TXD , checking it.
@raven02 Can you explan more about what is ```gradient instruction TXD```... I have no idea about this...

**Comment by kd-11** [comment] 2016-06-05 17:25
@mob41 texture gradient is the glsl function texturegrad. I thought it was enabled for openGL, but I guess not. As for vulkan on linux, that is intentionally disabled. Its not as easy as enabling the option since each operating system will have it'w own windowing API and vulkan does not abstract that stuff for you. You'll have to implement an Xcb surface management system in there.

**Comment by mob41** [comment] 2016-06-05 17:34
@kd-11 But seems Vulkan have its Cross-platform API that ports to linux and wndows directly.

**Comment by kd-11** [comment] 2016-06-05 17:45
@mob41 afaik Vulkan WSI extensions have operating system independent window management code. Its the only part that is different on different platforms. If you look at the vulkan initialization code, you can see I need to grab a swapchain target surface from the HWND of the window. Of course this bit is windows-specific hence it is commented out using #ifdefs. The same is true of vulkan example code from lunarG where android, win32 and X11 have different blocks separated using #defs.

**Comment by rcaridade145** [comment] 2016-06-06 14:11
@mob41 This is how for instance glfw initializes vulkan https://github.com/glfw/glfw/blob/master/src/vulkan.c .

**Comment by mob41** [comment] 2016-06-06 14:46
@rcaridade145 I currently not good at writing to apis in C++, but with Java I works well. Besides, my graphics card does not support Vulkan, sadly, it also does not support DirectX 12. So I can't test with those features. May be some developers will pick this up to develop for linux.

**Comment by rcaridade145** [comment] 2016-06-06 14:49
I'll try to implement and test this on Linux by this week's end.

**Comment by mob41** [comment] 2016-06-06 14:50
@rcaridade145 That will be great.

**Comment by mob41** [comment] 2016-06-07 15:55
@kd-11 It is bit away from the topic. Should this (including HWND grabbing and implement unimplemented opcode) to be assigned to somebody or put it in the SML tasks? So that some developers that are finding things to do to develop it.

**Comment by kd-11** [comment] 2016-06-07 16:03
@mob41 Leave the opcode stuff here as it is relevant and I'll take a look at this issue soon. As for the vulkan window management on linux stuff, we can just leave it for now until @rcaridade145 has a pull request and move the discussion there since someone is already working on it. The X11 windowing stuff is trivial (as far as rsx stuff goes) so it shouldn't be diffucult for someone in a linux environment to get it working.

**Comment by raven02** [comment] 2016-08-09 08:34
Close this and open a new one for more specific and precise using latest build

**Closed by raven02** 2016-08-09 08:34 UTC
Labels: opengl, rsx
