### ISSUE TITLE
Blazing Angels 2 [BLUS30052] issues

### ISSUE THREAD

**Issue by Megamouse** [RPCS3/rpcs3#8130] opened 2020-05-01 10:57 UTC
## Quick summary
Vulkan: 
Blazing Angels 2 crashes in mere seconds after going ingame (splitscreen multiplayer) due to running out of VRAM (8GB RTX 2070). This does not happen with OpenGl.

OpenGl: miraculously fixed
~~The game's intro and menu background videos are black with cleared shader cache.
They only appear once you have gone ingame once. The videos keep being black if you only stay in the menus and reboot.~~

Also of Note:
Sometimes the game crashes when you close it.

## Details
Log with both renderers:
[RPCS3.log](https://github.com/RPCS3/rpcs3/files/4563724/RPCS3.log)

Crash-on-close Log:
[RPCS3.log](https://github.com/RPCS3/rpcs3/files/4563771/RPCS3.log)

**Comment by kd-11** [comment] 2020-07-21 19:11
![image](https://user-images.githubusercontent.com/15904127/88096242-03127000-cb9f-11ea-9278-3f299b3220ff.png)
Cannot reproduce OpenGL issue. This is running with a permanently disabled shader cache and everything in menus and intro renders ok.

**Comment by Megamouse** [comment] 2020-07-21 21:46
Yes, you are right. The OpenGl issue seems to have been fixed somehow in the meantime

**Comment by kd-11** [comment] 2020-07-22 19:19
This game has... issues. I went through the whole process of designing a memory balancing routine but it only delays the inevitable - at some point it still allocates all the VRAM as textures and somehow fails to trigger normal triggers that would automatically remove older data. It seems to be dynamically allocating blit destination targets and never reading from them or at least that is the current theory.

**Comment by kd-11** [comment] 2020-07-23 20:16
Should be resolved by https://github.com/RPCS3/rpcs3/pull/8618

**Closed** 2020-07-25 11:48 UTC
Labels: Render: Vulkan
