### ISSUE TITLE
Regression in NCAA Football 10 [BLUS3055] with PR #5977

### ISSUE THREAD

**Issue by connorwalks** [RPCS3/rpcs3#5990] opened 2019-05-18 05:54 UTC
i9 9900K
16GB 3000 MHz C15 DDR4
Nvidia RTX 2080 (driver 430.64)

Prior to #5977 NCAA Football 10 was perfectly playable and one of the better running, stable games I have played with RPCS3. However, as of v0.0.6-8135-4037225e (PR #5977), the game fails to get ingame with the following error:  `F {RSX [0x008befc]} RSX: class std::runtime_error thrown: Verification failed: 
(in file c:\projects\rpcs3\rpcs3\emu\rsx\vk\vktexture.cpp:146)` 

Here is what the game looked like prior to #5977 with the corresponding log:

![8134_WORKING](https://user-images.githubusercontent.com/48158481/57965089-517a0e00-790d-11e9-8eb7-12437a682d67.jpg)

[8134_Working.log.gz](https://github.com/RPCS3/rpcs3/files/3193684/8134_Working.log.gz)

Here is the game crashing as of PR #5977 with log:

![8135_BROKEN](https://user-images.githubusercontent.com/48158481/57965145-30fe8380-790e-11e9-8767-41a022d2151d.jpg)

[8135_BROKEN.log.gz](https://github.com/RPCS3/rpcs3/files/3193688/8135_BROKEN.log.gz)

EDIT: I should also add that this only affects Vulkan. The game still manages to get ingame with OpenGL, but it is far from playable even on a 9900K with OpenGL

**Comment by kd-11** [comment] 2019-05-18 07:25
Lower your resolution scale. I have pushed a commit to double the allocation but you will still run out if you use too high of a resolution scale.

**Comment by kd-11** [comment] 2019-05-18 07:26
Closing as duplicate of https://github.com/RPCS3/rpcs3/issues/5983

**Closed by kd-11** 2019-05-18 07:26 UTC
