### ISSUE TITLE
[Nvidia Only] Persona 5 red "static"

### ISSUE THREAD

**Issue by Gamesfan34260** [RPCS3/rpcs3#5589] opened 2019-01-22 01:40 UTC
[BLUS31604_20190122005744_capture.zip](https://github.com/RPCS3/rpcs3/files/2780950/BLUS31604_20190122005744_capture.zip)

0.0.5-7732-5ed71811 Alpha
Unsure exactly what causes the issue, seems to occur during any screen transition, examples including loading new menus or moving maps. I had 1 instance when walking through a door, another when I went to load a save. (Of which I could not do before it occurred)
Specs: i5 4460 @ 3.20GHz, 750 Ti (2GB), 4GBx2 DDR3 1600MHz

The issue itself is graphical, after spending considerable time playing, the whole screen is covered in a red flickering "static"; it's difficult to see anything as a result, making it unplayable.
It almost resembles a failing graphics card but the issue only persists until RPCS3 is closed, it does not occur on other programs and will reside when the game window is moved over to a monitor ran on integrated graphics (Intel HD 4600)

![persona 5 rpcs3 glitch](https://user-images.githubusercontent.com/46910384/51506609-03348280-1de5-11e9-9403-17eb993e620c.png)

![persona 5 rpcs3 glitch 2](https://user-images.githubusercontent.com/46910384/51506716-92419a80-1de5-11e9-8963-54a11a852aaa.png)

I don't have any pictures of the game running on a PS3 but RPCS3 seems to work fine for a few hours before it occurs: (PS4 version I think)
![image](https://user-images.githubusercontent.com/46910384/51506881-64108a80-1de6-11e9-9609-f909400544f7.png)

**Comment by vsub** [comment] 2019-01-22 04:55
I see sometimes something similar on Ar Tonelico 3 but only while using spu llvm
I recently clear P5 with no problems at all(200+ hours) and I was using spu asmjit

**Comment by kd-11** [comment] 2019-01-22 07:31
What you are seeing there is the hard raster pattern of an nvidia gpu. Those squares are the warp groups themselves and they are not completing. This is not something userspace has control over unless we use shader timeouts which we do not,  which means either your hw or the driver are going crazy. Check with gpu-z what is happening when you have this, it could be that the gpu ran out of vram or something.

**Comment by Gamesfan34260** [comment] 2019-01-22 14:36
> I see sometimes something similar on Ar Tonelico 3 but only while using spu llvm
> I recently clear P5 with no problems at all(200+ hours) and I was using spu asmjit

I'll try ASMJIT and see if I can recreate the issue in that, it's not that I doubt kd-11 but I've played things that are far more taxing on my GPU and it seems odd that RPCS3 would be the only instance of me getting this issue especially since task manager only shows a 30% GPU utilisation.

**Comment by GitArUs** [comment] 2019-01-23 08:32
Because it happens after a few hours, maybe related to issue #5130 ?

**Comment by Gamesfan34260** [comment] 2019-01-23 23:19
So I should also test with OpenGL and any settings mentioned in the post?
Well, can't hurt to try, time to go paint my screen red. (Or maybe not, hopefully not XD)
I'll report back in a few day's time on my testing.

**Comment by GitArUs** [comment] 2019-01-24 16:56
So You use OpenGL ? In this case it may be caused by the size of shader cache. I mean driver shader cache. On Linux it is in directory ~/.nv/GLCache, on Windows probably C:\ProgramData\NVIDIA Corporation\NV_Cache. I have seen similar things ~ year ago, when I was still using OpenGL. When size of cache file was 250-300 MB, I could see similar glitches, although not so bad as on Your screenshot.
I don't know why, but shader cache is several (5-6) times bigger for OpenGL than for Vulkan (like 300MB OpenGL vs 60MB Vulkan).

**Comment by Gamesfan34260** [comment] 2019-01-24 18:05
I've yet to try it yet, sorry.
I've always used Vulkan since I get better FPS with that, I also have Windows 10 as an OS, not Linux.
If the issue persists, I'll look at the driver cache you mentioned.

**Comment by kd-11** [comment] 2019-01-25 11:47
Retest on current master, some vulkan compliance stuff has been improved.

**Comment by Gamesfan34260** [comment] 2019-01-25 14:59
I couldn't seem to trigger it on OpenGL, the Vram was DEFINITELY going up way more than it should but stopped at 1.8GB's.
I'll try the latest build though, thank you kd

**Comment by vsub** [comment] 2019-01-25 15:51
Yes because you  have 2gb vram
I have 3gb and it goes to ~3GB and then rpcs3 freezes but at least here,that high vram usage freeze happens after more than 6 hours or gameplay(it goes up little by little)

**Comment by Gamesfan34260** [comment] 2019-01-25 19:56
It doesn't freeze for me, it's just really difficult to play when I can't see the screen properly.
Anyway, I've noted that it always stops at 1.8GB's on Vulkan and OpenGL but the issue ONLY occur with Vulkan...for reasons beyond me.
Is it that Nvidia GPU's just don't agree with Vulkan for some reason?

**Comment by AniLeo** [comment] 2019-03-12 22:49
Needs retesting

**Comment by kd-11** [comment] 2019-03-19 21:08
Retest or close this.

**Comment by Gamesfan34260** [comment] 2019-03-19 21:13
Understood, I'll get back to updating about this shortly...although I have since had incidents where the game DOES freeze if I hit a loading screen whilst the graphical corruption has occurred.

**Comment by Gamesfan34260** [comment] 2019-03-21 02:00
It appears to be fixed, I spent 8 hours today trying to cause it. 
It may have been because of a lack of stuff that was compiled in the playthrough but I couldn't trigger it, I believe that's not enough to explain being unable to trigger it though as opening the menu has caused it before.

**Closed** 2019-04-05 13:27 UTC
