### ISSUE TITLE
OpenGl/Vulkan : Dragon Ball: Raging blast game hangs

### ISSUE THREAD

**Issue by Quadronomic** [RPCS3/rpcs3#3175] opened 2017-08-07 17:20 UTC
Game hangs going into most stages but is playable in some stages, however mid-match it tends to hang as well
![db raging blast crash](https://user-images.githubusercontent.com/30027863/29037786-0debbc7a-7b9d-11e7-8005-bcf87a5335b2.PNG)

RX 480
i5-4670k stock
Windows 10 64-bit

**Comment by Quadronomic** [comment] 2017-08-07 17:24
[RPCS3.zip](https://github.com/RPCS3/rpcs3/files/1205590/RPCS3.zip)

**Comment by kd-11** [comment] 2017-08-22 12:30
Duplicate of https://github.com/RPCS3/rpcs3/issues/2359

**Closed by kd-11** 2017-08-22 12:30 UTC
