### ISSUE TITLE
Regression: The Legend of Heroes: Trails of Cold Steel II (#3931)

### ISSUE THREAD

**Issue by xplosion666** [RPCS3/rpcs3#4038] opened 2018-01-09 23:06 UTC
Since #3927 all versions most likely have this visual bug in all cutscenes. while performance is better in #4034  (also #4034 sometimes freezes while loading game)

this is #4034
![not working](https://user-images.githubusercontent.com/35277880/34747718-cf5b50a2-f599-11e7-8a79-0b1af1967a1e.jpg)

and #3927
![working](https://user-images.githubusercontent.com/35277880/34747774-fe348eca-f599-11e7-82ee-0a4079bb4be1.jpg)

**Comment by AniLeo** [comment] 2018-01-09 23:08
#3927 Only touches Linux files and you're using Windows.

Need information to what was the PR that actually regressed it as it's nearly impossible that one did.

**Comment by xplosion666** [comment] 2018-01-09 23:20
it was  #3931

**Comment by alex88510** [comment] 2018-01-10 12:53
I have already mentioned about this regression 2 days ago at here https://github.com/RPCS3/rpcs3/issues/3947.

**Comment by kd-11** [comment] 2018-01-10 16:40
Closing as duplicate of https://github.com/RPCS3/rpcs3/issues/3947

**Closed by kd-11** 2018-01-10 16:40 UTC
Labels: RSX, Regression
