### ISSUE TITLE
Massive performance drop in various games (Shadow of the Colossus, Call of Duty 3) after PR #8175

### ISSUE THREAD

**Issue by Emogop** [RPCS3/rpcs3#8222] opened 2020-05-14 16:55 UTC
Massive performance drop in various games (Shadow of the Colossus, Call of Duty 3) after PR #8175

Win 10 1909
i3 6100 @ 4,5 Ghz
16 Gb RAM
GTX 1063
Also the sound became from being perfect to a stuttery mess. But it's because the performance drop.
10358 (before):
![Screenshot_471](https://user-images.githubusercontent.com/42875723/81960793-28708400-961a-11ea-9c2f-171b59523067.png)
10361 (after):
![Screenshot_470](https://user-images.githubusercontent.com/42875723/81960847-3aeabd80-961a-11ea-9b7b-d29492edae89.png)
Even more severe case:
10358 (before):
![Screenshot_483](https://user-images.githubusercontent.com/42875723/82161897-296b1500-98a9-11ea-940d-7582bbfca113.png)
Performance were fine, although with graphical artifacts.
And now after. It's not that it won't go ingame. But with that speed it would take forever:
![Screenshot_484](https://user-images.githubusercontent.com/42875723/82161960-a5fdf380-98a9-11ea-8f66-6ef207961d9f.png)

**Comment by AniLeo** [comment] 2020-05-14 16:56
Did you check with 10377?

**Comment by elad335** [comment] 2020-05-14 16:56
Have you tested latest master?

**Comment by elad335** [comment] 2020-05-14 16:57
And upload full log.

**Comment by Emogop** [comment] 2020-05-14 17:12
> Did you check with 10377?

10377: no changes. Also loading time now is HUGE.
![Screenshot_472](https://user-images.githubusercontent.com/42875723/81964391-2d840200-961f-11ea-8946-9cae28881c65.png)

[RPCS3.log.gz](https://github.com/RPCS3/rpcs3/files/4629908/RPCS3.log.gz)

**Comment by elad335** [comment] 2020-05-14 17:14
Can someone with more threads test this as well?

**Comment by RainbowCookie32** [comment] 2020-05-14 17:20
I'll check on my 1700 in a bit

**Comment by RainbowCookie32** [comment] 2020-05-14 17:35
Before optimizations PR:
![Screenshot_20200514_142839](https://user-images.githubusercontent.com/16805474/81966146-7328d680-95ef-11ea-84c5-71ceff1b723f.png)

Current master:
![After](https://user-images.githubusercontent.com/16805474/81966479-fc400d80-95ef-11ea-9815-00c5414a159a.png)

That's the only camera angle that gives me sub-60fps, and it's the same before and after the PR

**Comment by elad335** [comment] 2020-05-14 17:38
Unfortunately I suspect this issue will remain open for a while, the mentioned pr makes better use of more threads and potentially worse on less threads.
I don't currently plan to change this.

**Comment by Emogop** [comment] 2020-05-17 22:52
I've added CoD3.
I actually wanted to make an issue about flickering textures at first. But I couldn't get there :D

**Comment by galahadhiryu** [comment] 2020-05-27 22:54
Hi, sorry if i'm posting in the wrong place, but i have the same to report as the OP. 
Cpu:ryzen 3500x 
Gpu: 5500xt
16 Gb RAM
Since #8175 i've a massive drop in performance on motorstorm 2, and my cpu usage changed a lot increasing up to 5 to 15 degres the temperature of the cpu.
10358 (before)
![2020 05 27-19 23_06](https://user-images.githubusercontent.com/51791923/83079829-13044c80-a053-11ea-8561-772c8c0dff1c.png)
Now
![2020 05 27-19 20](https://user-images.githubusercontent.com/51791923/83079806-03850380-a053-11ea-926c-68e1a52ab4c9.png)

10358 (before)
![2020 05 27-19 25_02](https://user-images.githubusercontent.com/51791923/83079972-5ced3280-a053-11ea-8de6-52d3a57d53f8.png)
Now
![2020 05 27-19 21_01](https://user-images.githubusercontent.com/51791923/83079988-66769a80-a053-11ea-8225-00fe30be570e.png)

**Comment by gamrXerus** [comment] 2020-06-01 19:25
I can confirm this issue. Running Street Fighter X Tekken I get constant 60fps in rpcs3 0.0.10-10358. But from build 0.0.10-10361 I get fps fluctuating between 26 to 50 fps.
Before
![screen](https://user-images.githubusercontent.com/19245344/83445861-c2f30480-a41b-11ea-83fb-7598779ab723.jpg)
After
![screen2](https://user-images.githubusercontent.com/19245344/83445905-d3a37a80-a41b-11ea-8507-5d87b194ae23.jpg)
Specs:
CPU: Intel Core i5 8600k @ 4.3Ghz
RAM: 8GB
GPU: NVIDIA GTX 1060 6gb
OS: Ubuntu 20.04

**Comment by Yahfz** [comment] 2020-06-02 15:15
This is still an issue and it happens on every CPU, including my 9900KS.

**Comment by elad335** [comment] 2020-06-02 15:23
try tweaking SPURS max threads.

**Comment by Yahfz** [comment] 2020-06-02 15:24
for some reason performance is awful with block size mega, but good with safe and preferred spu threads on 6

**Comment by elad335** [comment] 2020-06-06 10:53
Test with #8358 and report your results, remember to report results with the new setting as well.

**Comment by Emogop** [comment] 2020-06-06 11:26
> Test with #8358 and report your results, remember to report results with the new setting as well.
I added the line 'SPU GETLLAR polling detection: true' in the game's custom config and launched the game:
![Screenshot_532](https://user-images.githubusercontent.com/42875723/83942813-a3831f80-a7ff-11ea-8d39-f5a66c382e8c.png)
In SotC it seams things came back the way they were before.
COD 3 is also improved a lot. Now I'm getting the former performance with SPURS unlimited.

**Comment by elad335** [comment] 2020-06-06 11:28
Thanks for testing, but please teport in the pull request next time until it is merged.

**Comment by galahadhiryu** [comment] 2020-06-06 13:42
rpcs3-v0.0.10-2e58a00b
Using "SPU GETLLAR polling detection: true" worked for me.
![2020 06 06-10 34](https://user-images.githubusercontent.com/51791923/83945621-4dec4a00-a7e2-11ea-8b7d-cfe5c1760860.png)

**Closed** 2020-07-09 02:17 UTC
