### ISSUE TITLE
[Regression] GOW3 Demo - persistent rendering error. 

### ISSUE THREAD

**Issue by JohnLoveJoy** [RPCS3/rpcs3#14106] opened 2023-06-27 21:45 UTC
### Quick summary

After the last modifications in the vk*, GOW3(Demo) started to show rendering errors, overlapping objects and smoke as if there was incorrect transparency. The error continues after corrections: https://github.com/RPCS3/rpcs3/pull/14101

* > https://github.com/RPCS3/rpcs3/pull/14065

### Details

When standing still without moving the rendering issues go up for an instant, the issue appear mostly in motion.

### Build with regression

v.0.0.28-15255-Alpha

### Attach two log files

[RPCS3.log.gz](https://github.com/RPCS3/rpcs3/files/11887564/RPCS3.log.gz)

### Attach capture files for visual issues

![GPU_GW3_Static](https://github.com/RPCS3/rpcs3/assets/31490343/53bc1b82-d628-416e-a207-66e0588ba4b5)
![IssueGPUGW3](https://github.com/RPCS3/rpcs3/assets/31490343/91db2590-3f79-4b2f-8996-96b57455e3e5)

### System configuration

Specs 5500U @ Vega 7 + 12GB ram
Latest drivers.
Windows 10.

**Comment by kd-11** [comment] 2023-06-28 01:39
Luckily AMD's drivers are open source (mostly) so we can see why the split barriers don't work:
![image](https://github.com/RPCS3/rpcs3/assets/15904127/7e2aa927-4629-4b98-ad97-b16defad6f55)

Without split barriers it just aggregates the incoming stages and emits a regular event which we already know doesn't work. This means the extension is functionally useless for anything older than RDNA1 and might as well be disabled to use a slower fallback.

**Comment by JohnLoveJoy** [comment] 2023-06-28 15:07
> Try #14107

Thank you. I can test it if someone please send me a build with this pull. I'm having trouble compiling this, Sorry.

**Comment by MSuih** [comment] 2023-06-28 15:19
[Follow these instructions](https://wiki.rpcs3.net/index.php?title=Help:Using_different_versions_of_RPCS3#How_to_download_builds_from_a_pull_request_on_GitHub?)

**Comment by JohnLoveJoy** [comment] 2023-06-28 16:22
> [Follow these instructions](https://wiki.rpcs3.net/index.php?title=Help:Using_different_versions_of_RPCS3#How_to_download_builds_from_a_pull_request_on_GitHub?)

Thank you. I tested, the issue is still there:

![TELA000](https://github.com/RPCS3/rpcs3/assets/31490343/6ae66b51-3237-4301-b7fc-1f55af928136)

[RPCS3.log.gz](https://github.com/RPCS3/rpcs3/files/11897732/RPCS3.log.gz)

**Comment by JohnLoveJoy** [comment] 2023-06-28 20:18
> Thanks. I guess we can just give up on everything pre-rdna as I initially feared.

This game ran a bit faster before VK sync was implemented anyway. Just out of curiosity, would the semaphores and fences synchronization introduced in Vulkan 1.2 not fit in this case?

_"Now that we’ve gone through some mechanisms for setting up dependencies within a single device queue, let’s check out how we can orchestrate synchronization across different queues.

The Vulkan API provides two options, each with different purposes: semaphores and fences.

Note that Vulkan 1.2 introduced timeline semaphores, which is the new and preferred approach to semaphores going forward."_

https://www.khronos.org/blog/understanding-vulkan-synchronization

**Comment by kd-11** [comment] 2023-06-28 20:28
> The Vulkan API provides two options, each with different purposes: semaphores and fences.
> 
> Note that Vulkan 1.2 introduced timeline semaphores, which is the new and preferred approach to semaphores going forward."_
> 
> https://www.khronos.org/blog/understanding-vulkan-synchronization

In this case we need asynchronous host-signaling without fences. That's a bit of a rare use case and the spec is very vague about it. What we actually need is labels which work more like opengl fences. No submit, but host can poll to get signaled/unsignaled state. Events are supposed to do this but drivers are not implementing it the way we need so we just have to roll our own stuff for a bit longer.

**Comment by kd-11** [comment] 2023-06-28 22:28
I've restored the custom labels. You can test the next build available on the PR.

**Comment by JohnLoveJoy** [comment] 2023-06-28 23:14
> I've restored the custom labels. You can test the next build available on the PR.

It's back to working almost completely correctly as before, the only issue is on the character's head where the texture has become darkened with small blue fragments. 

![TextureGPUissue](https://github.com/RPCS3/rpcs3/assets/31490343/9905aec6-c020-43d4-b203-bddd1b328151)


How Kratos' head looks when rendered correctly(Master Build):

![GPUissue2](https://github.com/RPCS3/rpcs3/assets/31490343/3c317ab7-9c29-4574-b31a-96a1c4157044)


[RPCS3.log.gz](https://github.com/RPCS3/rpcs3/files/11900558/RPCS3.log.gz)

**Comment by kd-11** [comment] 2023-06-29 00:38
How repeatable is it? I've simply returned the sync to the way it was before the first PR. I also cannot see any bugs when spoofing a vega igpu.

**Comment by kd-11** [comment] 2023-06-29 00:41
If you can, try to reproduce this one https://github.com/RPCS3/rpcs3/issues/12021. That game triggers the bug immediately in the loading screens.

**Comment by kd-11** [comment] 2023-06-29 15:51
@JohnLoveJoy How frequently can you reproduce this problem? Like if you boot the game 5 times is it broken 5/5 times?

**Comment by JohnLoveJoy** [comment] 2023-06-29 18:16
When I switch to the console's native resolution, blue lights start popping all over the scene. The strangest point is that when I try to record with Msi Afterburner, the bug appears much less, so I recorded with my cell phone: https://uploadnow.io/f/pvFggQF
With afterburner too:
https://streamable.com/jxmkd9

**Comment by kd-11** [comment] 2023-06-29 23:06
I think those glitches are caused by enabling asynchronous texture streaming.

**Comment by kd-11** [comment] 2023-06-29 23:26
Ok, I think I see a problem on the fallback path that is only present in the PR. This explains why async streaming is broken now but was ok in master.

**Comment by kd-11** [comment] 2023-06-29 23:54
Should be fixed now, once the builds are ready.

**Comment by JohnLoveJoy** [comment] 2023-06-30 15:32
> Should be fixed now, once the builds are ready.

The problem shown in the video was corrected, but the small blue edges on Kratos were still there... however, on Master there is the same defect, after investigating a little, this ends up being corrected when switching to **ASMJIT**

**Closed** 2023-06-30 15:38 UTC
Labels: Driver: AMD Vulkan, Workaround
