### ISSUE TITLE
Ninja Gaiden 3 black screen in game

### ISSUE THREAD

**Issue by vanderleivieirainacio** [RPCS3/rpcs3#9405] opened 2020-12-10 15:53 UTC
The ninja game Gaiden 3 Razors edge is presenting a black screen inside the game as if it had not loaded the textures but you can access the options menu within the game and hear the sounds and small textures but the screen is black in game both in the OpenGL API as Vulkan and in any resolution.
![Captura de tela 2020-12-10 124500](https://user-images.githubusercontent.com/46516229/101795001-3457f200-3ae6-11eb-88a5-400d149c8e2d.png)
![Captura de tela 2020-12-10 124642](https://user-images.githubusercontent.com/46516229/101795041-3cb02d00-3ae6-11eb-975d-0903affb6be4.png)
![Captura de tela 2020-12-10 124725](https://user-images.githubusercontent.com/46516229/101795065-446fd180-3ae6-11eb-9551-cb866c63903a.png)
![Captura de tela 2020-12-10 124752](https://user-images.githubusercontent.com/46516229/101795121-53ef1a80-3ae6-11eb-871a-efc34d9a82de.png)
[RPCS3.log](https://github.com/RPCS3/rpcs3/files/5673924/RPCS3.log)

**Comment by kd-11** [comment] 2020-12-10 20:24
Duplicate of https://github.com/RPCS3/rpcs3/issues/9410

**Closed by kd-11** 2020-12-10 20:24 UTC
