### ISSUE TITLE
RPCS3 silently terminated after a DS3 pad is disconnected (e.g. due to inactivity)

### ISSUE THREAD

**Issue by digant73** [RPCS3/rpcs3#16445] opened 2024-12-22 14:46 UTC
### Quick summary

This is a possible issue I always saw from June 2024 (when I started to use the emulator).
If the DS3 pad is disconnected during a gameplay (e.g. after 5 minutes of inactivity) the game window and also RPCS3 are silently terminated after some minutes the DS3 was disconnected.
Attached a log file on Uncharted 1, but the issue is present on all games I own.

Steps to easily reproduce the issue:
1) start a game and start a gameplay
2) press `start` button on the DS3 pad to move the game on pause menu
3) do not use the pad for 5 minutes so it will disconnect (by default, LED on the pad is also switched off)
4) wait some minutes. On average, after 12 minutes both the game window and also RPCS3 are silently terminated

### Attach a log file

[RPCS3.log](https://github.com/user-attachments/files/18222245/RPCS3.log)

**Comment by Megamouse** [comment] 2024-12-22 14:48
Duplicate of #14063

**Closed** 2024-12-22 14:47 UTC

**Comment by Megamouse** [comment] 2024-12-22 15:38
Sadly I can not reproduce this at all anyway.
So it would need someone to compile rpcs3 and post a callstack of the crash here.

**Comment by digant73** [comment] 2024-12-22 16:10
I usually compile my project. Do you mean to run from VS and wait for the crash?

**Comment by Megamouse** [comment] 2024-12-22 16:13
exactly

**Comment by digant73** [comment] 2024-12-22 16:23
ok, I will do that

**Comment by digant73** [comment] 2024-12-22 20:49
I got only this issue

![crash_on_DS3_dsconnect](https://github.com/user-attachments/assets/1dd8cd91-95e5-41e4-aa93-791bbaa5eb4c)

**Comment by digant73** [comment] 2025-01-02 19:06
thanks, I already read your bug report but unfortunately old rpcs3 versions seem to crash on startup due to VC++ redist. I tried to use VC++ 2015-2019 redist but the crash is still there so I cannot test those old rpcs3 versions
