### ISSUE TITLE
ERROR I get for every game either pkg or disc

### ISSUE THREAD

**Issue by DanGotTalent** [RPCS3/rpcs3#8325] opened 2020-06-02 15:14 UTC
E {RSX Decompiler Thread} RSX: Failed to compile shader: ERROR: 0:117: 'tex00' : undeclared identifier 
ERROR: 0:117: 'texture' : no matching overloaded function found (using implicit conversion) 
ERROR: 0:117: 'process_texel' : no matching overloaded function found (using implicit conversion) 
ERROR: 0:117: 'assign' :  cannot convert from 'const highp float' to 'inout 4-component vector of highp float'

**Comment by MSuih** [comment] 2020-06-02 15:16
Duplicate of https://github.com/RPCS3/rpcs3/issues/6199

**Comment by vsub** [comment] 2020-06-02 16:54
You say every game but I just tried two by using my intel gpu instead of my nvidia card and they both work fine(vulkan)

Maybe I am not using the latest drivers but the control panel says that I am but the intel site says that I am not
I am using 26.20.100.7158 and on the intel site it says 27.20.100.8280

**Comment by kd-11** [comment] 2020-06-02 16:56
It's intel's opengl driver that is extremely broken, vulkan mostly works fine.

**Comment by RainbowCookie32** [comment] 2020-06-02 16:57
It's the usual error you get on Intel iGPUs before Skylake.

**Closed** 2020-06-02 19:16 UTC
