### ISSUE TITLE
TSX is broken for Red Dead Redemption

### ISSUE THREAD

**Issue by Bokujutsu** [RPCS3/rpcs3#7922] opened 2020-04-02 19:32 UTC
Red Dead Redemption will not go in game with TSX enabled, the game gets stuck at a black screen or loading screen. Same settings with TSX disabled loads main menu and goes in game consistently.

[RPCS3.log](https://github.com/RPCS3/rpcs3/files/4423215/RPCS3.log)

**Comment by lainiwaku** [comment] 2020-04-02 20:01
i have many game broken on tsx, but actually,  RDR  work  with TSX on my side

**Comment by DaRkL3AD3R** [comment] 2020-04-06 20:05
Can confirm this as well with an i7 7700k. Game would fail to load properly with TSX on Enabled. Infinite loading black screen or failed to get past the main menu at all.

**Comment by lainiwaku** [comment] 2020-04-08 07:15
ok it  crash, it's a regression since it worked some days ago

**Comment by Yahfz** [comment] 2020-04-08 15:35
> ok it crash, it's a regression since it worked some days ago
If it really is a regression then please find the offending PR and update the thread.

**Comment by jedinjapan** [comment] 2020-04-29 18:09
This is not limited to RDR, but the TSX causing infinite loads is present in the Metal Gear Solid HD Collection titles as well, and likely a few others. Currently disabling TSX is the only way to move forward without periodic issues.

**Comment by DaRkL3AD3R** [comment] 2020-05-30 19:50
I'm getting into game (RDR) with TSX now on latest builds as of 2020/5/30 but the game is crashing extremely fast. Turning TSX off allows it to run much longer. Has nothing to do with system stability as even at stock settings it still occurs.

**Comment by Xcedf** [comment] 2020-06-06 18:32
Confirm this issue, sometimes not getting into menu(black screen) sometimes it boots but freezes soon after it

**Comment by Asinin3** [comment] 2020-10-29 13:37
Can you guys retest? There's been a ton of TSX changes recently and i've seen a lot of people get ingame with TSX.

**Comment by jedinjapan** [comment] 2020-10-29 18:14
There was never an issue with getting in game, aside from one post here most do boot and go in game. The issue is overall TSX stability. RDR and MGS Collection both boot, and run fine for a period of time. The issue comes after running it for a bit when something changed by enabling TSX produces an instruction that either hangs or loops. In the MGS Collection, this seemed to be most easily triggered by changing zones, but in RDR the direct trigger seems unknown.

**Comment by lainiwaku** [comment] 2020-10-31 06:41
the author clearly said "Red Dead Redemption will not go in game with TSX enabled, "
So it  is fixed and can  be closed now

**Comment by Asinin3** [comment] 2020-10-31 06:48
I agree. But sometimes theirs weird issues that only appear on some people's set-up so its good to get confirmation from author. He hasn't updated the post though and the game has known to have random crashes even without tsx so I'll just close this since there's no point keeping it open if author can't be bothered updating it.

**Closed by Asinin3** 2020-10-31 06:48 UTC
