### ISSUE TITLE
Missions of the Lunar Expedition in GT 6 don't start

### ISSUE THREAD

**Issue by PY3AN** [RPCS3/rpcs3#9538] opened 2021-01-03 20:24 UTC
When launching Lunar Expedition missions, the emulator crashes with the following error:

F {RSX [0x12bf650]} SIG: Thread terminated due to fatal error: rsx::get_address(offset=0x40326b10, location=0x1): RSXIO memory not mapped!
(in file D:\a\1\s\rpcs3\Emu\RSX\RSXThread.cpp:890[:41], in function get_raw_index_array)
(in file D:\a\1\s\rpcs3\Emu\RSX\RSXThread.cpp:140[:23], in function get_address)

![Lunar Expedition](https://user-images.githubusercontent.com/76910089/103488048-c79cf280-4e1a-11eb-836f-36632a021a9c.png)

[Lunar Expedition.log](https://github.com/RPCS3/rpcs3/files/5762227/Lunar.Expedition.log)

System configuration:

    RPCS3 v0.0.14-11509
    OS Windows 10 20H2, 19042.685
    CPU AMD Ryzen 5 3600
    GPU AMD Radeon RX 580 8G
    Memory Crucial Ballistix Sport 16G
    Driver version 2.0.168

**Comment by Satan86** [comment] 2021-01-03 20:25
Duplicate of #5802

**Closed** 2021-01-03 20:29 UTC
