### ISSUE TITLE
[Feature Request] Use std::filesystem when possible

### ISSUE THREAD

**Issue by elad335** [RPCS3/rpcs3#9787] opened 2021-02-16 08:30 UTC
From what I'm reading, some functions match perfectly with rpcs3 such as std::filesystem::space (replacing fs::statfs) and std::filesystem::path constructor as a replacement for the buggy fs::escape_path implentation. There is little sense to continue support platform specific implementations if there's STL implementation.

**Comment by Nekotekina** [comment] 2021-02-16 08:49
I disagree. It's not only NOT a silver bullet, it's also a blackbox you'll have to deal with. It'll only get in the way in the long term.

Use std::filesystem if you have no other choice - that's what I can agree with, but only as a short-term workaround.

**Comment by Nekotekina** [comment] 2021-02-16 09:24
I also suspect fs::escape_path is just unneeded: moving between different mountpoints may be not possible. Could have saved escaped VFS path instead of real path for moving purpose.

**Comment by kd-11** [comment] 2021-02-16 09:55
I think the move to std::filesystem makes sense if and only if it provides everything required by rpcs3. Then at that point it would indeed be pointless to keep using custom code that does the exact same thing supplied by spec. But as long as its only some functions provided and not others, let's not mix as it can end up being a mess.
Looking at all the previous fs regressions and problems, does STL implementation really solve all of them without needing additional code? If it does, and at some point we no longer need to invoke win32/posix ourselves then we should indeed move to STL.
One of the problems I have with STL is (as neko mentioned) it is a black box. Since STL implementations tend to cater to the platforms concerned, what happens when we need some BSD-specific behaviour? We already had this issue with open file handles getting deleted or renamed (I can't remember exactly) and we had to resort to custom code to handle it on windows for example.

**Comment by Augusto7743** [comment] 2021-02-17 06:32
I not has information if that thread is relative with loading ISO using disc mount.
Thus being if not is please excuse me.
RPCS3 allow to start games loading ISO using disc mount drivers (PowerISO, Daemon Tools and others).
In Windows works, but in Linux not work.
In Linux using GCDEMU loading an ISO is created an media device being possible read all files in mounted ISO drive, but RPCS3 when selecting that mounted drive read only the EBOOT.BIN compile PPUs and stop after loading all PPUs how if not read others files or directories.
RPCS3 is started being user and GCDEMU drive are also user not being mounted being sudo.
Disc dumps being ISO DAA are compressed 25 %. That help extremely with disc space and CPU usage is low even using high compression.
100 GB dumped disc ISOs is less of 70 GB if using ISO compression. That's better than having the game uncompressed in RPCS3 disc folder.

**Comment by Nekotekina** [comment] 2021-02-17 09:19
Someone added ISO support via current fs capabilities IIRC, but it wasn't merged for some reason.

**Comment by Augusto7743** [comment] 2021-02-17 10:02
RPCS3 windows version load ISO mounted in virtual disc driver (PowerISO, Daemon Tools and others) perfectly since 2018 versions.
I not has tested current version on windows. Perhaps is working.
Linux not is working :-(
Thanks very much for your reply.

**Closed** 2021-02-24 17:47 UTC
Labels: Discussion, Filesystem
