### ISSUE TITLE
Nesting the RPCS3 directory in a restricted directory causes RPCS3 to fail to launch.

### ISSUE THREAD

**Issue by EdgeOfControl** [RPCS3/rpcs3#14111] opened 2023-06-29 02:24 UTC
### Quick summary

If the RPCS3 install directory is located in a restricted directory (i.e Program Files or Program Files (x86)) RPCS3 will refuse to open thinking there is a conflicting process open. Taking ownership of the RPCS3 folder and all contents with full control permissions granted to the local user fixes this issue.

Windows 11

### Attach a log file

Not applicable

### Other details

This issue affects Windows systems, I don't know if similar folders exist on Unix systems that would require a similar operation to chmod 777

**Comment by Darkhost1999** [comment] 2023-06-29 05:20
Can you explain a little more about what the issue is and what you expect to see as a solution? Right now it looks like you're pointing out how RPCS3 is supposed to function and saying that there's a problem but it's unclear as to what. Is it the message you received telling you about a "conflicting process" when in reality you put RPCS3 in your program files directory? It's of course not recommended to practice bad file management practices and to exercise good file management habits.

**Comment by MSuih** [comment] 2023-06-29 05:20
RPCS3 is provided as portable directory for Windows users. The upside is that no installation is required and the folder can easily be moved around, but the downside is that if the location  that you drop the folder in has restricted permissions it'll prevent emulator from functioning properly. In this case you have RPCS3.buf file present but emulator is not allowed to access it.

As we don't currently have any plans to switch to f.ex. `%appdata%` or `%userprofile%` based data directories I'm closing this issue. Just place RPCS3 in some other location.

**Closed by MSuih** 2023-06-29 05:20 UTC
