### ISSUE TITLE
LLVM: Using unsupported instruction on G4560

### ISSUE THREAD

**Issue by adelin07** [RPCS3/rpcs3#2950] opened 2017-07-04 07:21 UTC
---------------------------
Fatal error
---------------------------
Unhandled Win32 exception 0xC000001D.
Exception address: 0000000010ed1bad.
Instruction address: 0000000010ed1bad.
RPCS3 image base: 0000000000010000.

Illegal instruction exception occured.
Note that your CPU must support SSSE3 extension.

---------------------------
OK   
---------------------------
I'm sorry for posting this issue that has been raised in the past, but every time I found it, people had CPU's which didn't support SSSE3 extension. That's not true in my cause. 
This happens only when I try to run a game(I only tried Dragon Ball Z burst limit) using the LLVM recompiler, it boots and runs using Interpreter(fast).
My CPU: Pentium G4560.
Instructions according to CPU-Z: MMX, SSE, SSE2, SSE3, SSSE3, SSE4.1, SSE4.2, EM64T, VT-x, AES. Does rpcs3 require some other instruction that triggers this error?
I'm using v0.0.2-7-6074218

**Comment by Megamouse** [comment] 2017-07-04 07:24
I have seen @Zangetsu38 with a similar problem...

**Comment by AniLeo** [comment] 2017-07-04 12:44
Please upload a RPCS3.log file

**Comment by adelin07** [comment] 2017-07-04 12:48
[RPCS3.zip](https://github.com/RPCS3/rpcs3/files/1122075/RPCS3.zip)

**Comment by hcorion** [comment] 2017-07-04 19:37
I can't seem to find 6074218 in any of the recent builds. Please download this one: https://ci.appveyor.com/project/rpcs3/rpcs3/build/0.0.2-5093/artifacts and try again.

**Comment by hcorion** [comment] 2017-07-04 19:37
Also, don't use D3D12 renderer, use Vulkan or OpenGL

**Comment by adelin07** [comment] 2017-07-04 19:48
[RPCS3.zip](https://github.com/RPCS3/rpcs3/files/1122943/RPCS3.zip)
This is the log file I get after using the version you suggested.

**Comment by AniLeo** [comment] 2017-07-04 19:51
G4560 is kaby lake but LLVM is assuming skylake there

**Comment by hcorion** [comment] 2017-07-04 19:51
Hmm, the only thing that I see that is awry is LLVM is building skylake binaries, but your CPU is kabylake. They are functionally similar, so I don't see why this would be the issue.

**Comment by hcorion** [comment] 2017-07-04 19:53
Ah, looking at LLVM's code, it groups kaby lake and skylake into the same group, ie skylake.

**Comment by raveskirza** [comment] 2017-07-04 19:54
LLVM identifies kaby lake chips as skylake which is normal. 
Works fine for my i5 7300HQ

**Comment by hcorion** [comment] 2017-07-04 19:56
Are you on Windows 10?

**Comment by adelin07** [comment] 2017-07-04 19:58
Yes, I'm on Windows 10

**Comment by hcorion** [comment] 2017-07-04 20:23
I wonder if it has something do with this: https://arstechnica.com/information-technology/2017/06/skylake-kaby-lake-chips-have-a-crash-bug-with-hyperthreading-enabled/?comments=1

**Comment by paulsapps** [comment] 2017-07-05 06:51
Its very unlikely, if this is easy to reproduce then its also easy to prove. Disable hyperthreading and see if the bug is gone. Of course if the bug is gone it might just be because changing the timing has hidden some other race.

**Comment by adelin07** [comment] 2017-07-05 06:54
I tried running the program by disabling cores 1 and 3(the hyperthreaded ones) of rpcs3.exe from task manager and then booting the game. The result is the same crash.

**Comment by Zangetsu38** [comment] 2017-07-05 12:19
no i don't have this problem by defaut znver1, i have this error after try emulate bdver1, but it is strange yes

**Comment by egiofanas420** [comment] 2017-07-06 23:11
Tested minecraft trial on G620 which supports SSSE3 according to CPU-Z & speccy getting the same issue

---------------------------
Fatal error
---------------------------
Unhandled Win32 exception 0xC000001D.
Exception address: 00000000117efb06.
Instruction address: 00000000117efb06.
RPCS3 image base: 0000000000010000.

Illegal instruction exception occured.
Note that your CPU must support SSSE3 extension.

HOW TO REPORT ERRORS: Check the FAQ, README, other sources.
Please, don't send incorrect reports. Thanks for understanding.
Press (Ctrl+C) to copy this message.
---------------------------
OK   
---------------------------

LOG:

[RPCS3.zip](https://github.com/RPCS3/rpcs3/files/1129505/RPCS3.zip)

**Comment by kajmen33** [comment] 2017-07-09 06:02
I have the same issue with the Intel G4560 too. It just crashes every time with the SSSE3 error code :/

**Comment by kajmen33** [comment] 2017-07-10 05:50
I found a solution change this line in the config file LLVM CPU: "" to LLVM CPU: "nehalem" 
Remove your game from RPCS3 and install it again then try LLVM option it will be fixed.

**Comment by adelin07** [comment] 2017-07-10 07:00
Thanks! That does indeed solve the problem. I'm now getting an avg of 30 fps and before I was getting about 1-2 fps using interpreter(fast). Huge improvement. RPCS3 also seems to be different from other emulators, this 30 fps feels like full speed with skipped frames instead of half the speed with full frames that all emulators I know use.

**Comment by SakataGintokiYT** [comment] 2017-07-18 17:27
@Nekotekina 
![gg](https://user-images.githubusercontent.com/13681488/28330786-177316d4-6bef-11e7-9fda-a741250824c4.png)

**Closed** 2017-07-27 21:31 UTC
Labels: bug, cpu
