### ISSUE TITLE
God of War Collection (Vulkan API) crash

### ISSUE THREAD

**Issue by Vakamisu** [RPCS3/rpcs3#4437] opened 2018-04-13 11:37 UTC
Shortly after launching "playable" game - God of War Collection, using Vulkan API, game crashes with Exception:

```
E {rsx::thread} RSX: dst index out of range: 17
E {rsx::thread} RSX: Unknown vp opcode 0x1a
E {rsx::thread} RSX: Unknown vp sca_opcode 0x17
E {rsx::thread} RSX: ERROR: 0:214: 'dst_reg17' : undeclared identifier 
ERROR: 0:214: 'xzw' : vector swizzle selection out of range 
ERROR: 0:214: '' : compilation terminated 
ERROR: 3 compilation errors.  No code generated.

E {rsx::thread} RSX: 
F {rsx::thread} class std::runtime_error thrown: Failed to compile vertex shader
(in file Emu\RSX\VK\VKVertexProgram.cpp:350)
```

**Comment by kd-11** [comment] 2018-04-13 11:47
Duplicate of https://github.com/RPCS3/rpcs3/issues/2359
Renderer ran too fast compared to the rest of the virtual ps3 and desynchronized. In this case ends up trying to draw with a shader that is still being copied by cell. Should go away once spu performance catches up, or use opengl to slow down the renderer intentionally.

**Closed by kd-11** 2018-04-13 11:47 UTC
