### ISSUE TITLE
Metal Gear Solid 4 - VirtualProtect failed

### ISSUE THREAD

**Issue by Auresalia** [RPCS3/rpcs3#16443] opened 2024-12-21 23:38 UTC
### Quick summary

Upon exiting the pause menu, the game will almost always freeze, requiring RPCS3 to be forcefully terminated via the Task Manager. The log shows the following error:

`F 0:01:20.328470 {RSX [0x0025884]} SIG: Thread terminated due to fatal error: VirtualProtect failed (0000000368107000, 0x1000, addr=0x368107000, error=Attempt to access invalid address. (0x1e7))`
`(in file D:\a\1\s\rpcs3\util\vm_native.cpp:418[:25], in function void __cdecl utils::memory_protect(void *,unsigned __int64,enum utils::protection)) (error=0x1e7)`

### Details

Once the pause menu animation finishes, the game will freeze, occasionally still playing audio. The framerate counter still updates as well.

I've tried various combinations of settings, but nothing that I've seen online has worked-- at most, some things like changing max VRAM limits or increasing Driver Wake-Up Delay allow the pause menu exit to function normally for a few times, before the same error begins happening all over again. I've also tried using both the latest PS3 firmware, as well as the one that shipped with the game (4.11). I've attached a log file of the error happening.

### Attach a log file

[RPCS3_MGS4.log](https://github.com/user-attachments/files/18220240/RPCS3_MGS4.log)

### System configuration

CPU: AMD Ryzen 9 7950X
RAM: 64.0 GB
GPU: NVIDIA RTX 3090
GPU Driver Version: 566.36
RPCS3 Version: 0.0.34-17228-beb35650

**Comment by Zonrotan** [comment] 2024-12-21 23:40
Can confirm I'm having the exact same issue. 
Issue appeared after updating RPCS3, nothing else changed.
Last time i can confirm it worked was about 30 days ago.

**Comment by FlexBy420** [comment] 2024-12-22 00:08
If it is a regression you need to post both logs from a last working build and the one that broke it

**Comment by Auresalia** [comment] 2024-12-22 00:30
For me, this is not something that was working in a previous build. I originally encountered this issue on a build that was almost two years old, and it persisted after updating to the last two releases. If someone can provide a log of a working build, or at least the release number so I can test on my own machine, that would be appreciated.

**Comment by Zonrotan** [comment] 2024-12-22 13:13
> If it is a regression you need to post both logs from a last working build and the one that broke it

Just tested with a ~2 week build, worked great.
See attached logs.
[v0.0.34-17173_RPCS3.log](https://github.com/user-attachments/files/18221932/v0.0.34-17173_RPCS3.log)
[v0.0.34-17229_RPCS3.log](https://github.com/user-attachments/files/18221934/v0.0.34-17229_RPCS3.log)


> For me, this is not something that was working in a previous build. I originally encountered this issue on a build that was almost two years old, and it persisted after updating to the last two releases. If someone can provide a log of a working build, or at least the release number so I can test on my own machine, that would be appreciated.

Try 17173.

**Comment by kd-11** [comment] 2024-12-22 14:14
@Zonrotan 
The only addition to core behavior has been an RSX optimization patch. There is an option in advanced tab to disable the speedup, try disabling "asynchronous host memory manager". Check if that fixes the crash for you with current rpcs3 master.

**Comment by Zonrotan** [comment] 2024-12-22 14:37
> @Zonrotan The only addition to core behavior has been an RSX optimization patch. There is an option in advanced tab to disable the speedup, try disabling "asynchronous host memory manager". Check if that fixes the crash for you with current rpcs3 master.

Quick tests point to this being the issue! Checking "Disable Asynchronous Memory Manager" seems to have fixed the issue when playing on the latest build. Thank you kd!
![image](https://github.com/user-attachments/assets/56010b16-a4cc-4826-9cff-7dcb2a17f56d)

**Comment by kd-11** [comment] 2024-12-22 14:39
Thanks for checking. I'll check why it's sensitive to that optimization.

**Comment by Satan86** [comment] 2024-12-22 17:07
Hello. I would like to inform that Gran Turismo 5 is also affected by this crash. I am unable to test right now, but I got this log from a user on the RPCS3 Discord, others have already reported it as well.
[RPCS3-1.log](https://github.com/user-attachments/files/18222638/RPCS3-1.log)

**Comment by kd-11** [comment] 2024-12-22 17:43
@Satan86 And the crash goes away when checking the option, right? Let's get confirmation of that as well.

**Comment by JellySnek** [comment] 2024-12-22 19:46
> @Satan86 And the crash goes away when checking the option, right? Let's get confirmation of that as well.

I've tried the new memory manager recently and tried Gran Turismo 5. 

The game crashes with: 
`·F 0:06:24.009095 {RSX [0x0010080]} SIG: Thread terminated due to fatal error: VirtualProtect failed (000000034273a000, 0x1000, addr=0x34273a000, error=Próbowano uzyskać dostęp do nieprawidłowego adresu. (0x1e7))
(in file D:\a\1\s\rpcs3\util\vm_native.cpp:418[:25], in function void __cdecl utils::memory_protect(void *,unsigned __int64,enum utils::protection)) (error=0x1e7)`

After entering a race in arcade mode, not even completing the race, watching replay for a little bit, then trying to return to the menu, the game crashes. 

[RPCS3.log](https://github.com/user-attachments/files/18223037/RPCS3.log)

I want to stress that Disabling Async Memory Manager fixes the issue. 

Apologies if the log file didn't upload well. I hope this one works, it contains the error with enabled Async Memory Manager.

**Comment by BronyUraj** [comment] 2024-12-22 20:53
After the RPCS3 update, MGS4 stopped working. The emulator crashes on launch. Enabling the Disable Async Memory Manager option didn't help. The Canary patch was also applied, but it doesn't appear in the log.

[RPCS3.log](https://github.com/user-attachments/files/18223193/RPCS3.log)

CPU: AMD Ryzen 7 7700X
GPU: NVIDIA GeForce RTX 4080 (566.36)

**Comment by BronyUraj** [comment] 2024-12-22 21:35
Downgrading build to 17229 helps! Game's working now.

**Comment by Auresalia** [comment] 2024-12-23 03:33
Confirmed that disabling Asynchronous Memory Manager resolved the issue for me-- I guess that I didn't think to try that setting while I was experimenting.

**Comment by Lumanator** [comment] 2024-12-25 12:05
Ridge Racer 7 also suffered a similar regression. For me, the Bandai Namco logo appeared before it crashed to desktop.

**Comment by kd-11** [comment] 2024-12-30 19:16
Ok, this one is pretty easy, we just need to do mm flush when sys_mmapper is deleting stuff.

**Comment by kd-11** [comment] 2024-12-30 21:02
This should be fixed by https://github.com/RPCS3/rpcs3/pull/16482
Please verify when the build is ready.

**Closed** 2024-12-30 22:52 UTC
Labels: Bug
