### ISSUE TITLE
Alice: Madness Returns™ [BLUS30607] random freeze

### ISSUE THREAD

**Issue by Evil0Dead** [RPCS3/rpcs3#8499] opened 2020-06-25 17:11 UTC
this game has improved a lot with leatest builds of RPCS3

now it's has random freezes with RSX error

`RSX: nv406e::semaphore_acquire has timed out. semaphore_address=0x60300F80`

this is random freeze can be happen any time in game 

I tried all settings still not fixed 

[RPCS3.log.gz](https://github.com/RPCS3/rpcs3/files/4832799/RPCS3.log.gz)

**Comment by TonyAMG** [comment] 2020-06-29 08:31
Confirm. Despite it has status Playable
I have the same error.
i5 8400, Radeon RX580 8G

**Comment by minisauruslepro** [comment] 2020-07-09 20:36
Yes, I have the same problem I tried changing every single setting in the software, nothing worked

**Comment by Asinin3** [comment] 2020-09-18 04:08
Retest, if it's still bad then retest by making a custom game config (right-click the game and hit configure) and in there go to advanced tab and set driver wake-up delay to 100us. If it's still bad We can move it back to ingame.

**Comment by Evil0Dead** [comment] 2020-09-20 19:39
> Retest, if it's still bad then retest by making a custom game config (right-click the game and hit configure) and in there go to advanced tab and set driver wake-up delay to 100us. If it's still bad We can move it back to ingame.

Still .. same problem .. BTW I've tried driver wake-up delay on my log build before , and I tried it now with no luck .. now the game froze in main menu ( faster than before ) and there isn't 100us .. it's 200us minimum .

**Comment by seniortwinkie** [comment] 2020-11-06 03:56
I am also getting the same issue here. (kinda the whole point for me trying this whole thing was to replay this game).

I have tried the above with 200us, changing different rendering engines, rendering settings. PPU / SPU settings nothing appears to make it work better.

I did notice that if you were fast enough through the menus to start the game, you could view the intro animation / movie. The farthest I made it was ~10-15 seconds into the in-engine cut scene. (was getting 30 FPS the whole time)

System:
v0.0.13-11166 and 0.0.13-11172
AMD Ryzen 3800x
32GB RAM
RTX 2080ti

Error Code:
```
RSX: nv406e::semaphore_acquire has timed out. semaphore_address=0x60300F80
```

Some further testing (as I write this up) shows using Interperter (precise) for the PPU / SPU allows for the game to get past that error, or at least allow the game to not throw that error right away, granted, it is chugging along at 1-4 FPS.

**Comment by SilverBeamx** [comment] 2020-11-19 23:10
A similar issue also happens in DUST 514 [NPUB30643]. All the builds i could test had this issue.

The game runs fine, then, after 5-15 minutes, randomly, the FPS plummets to 0.5 FPS and renders it unplayable. The issue doesn't occur in a specific area, it may happen in the loading screens, or during gameplay. At this point, the log is spammed with semaphore timeouts.

Here's a log of the issue: 
[RPCS3.log.gz](https://github.com/RPCS3/rpcs3/files/5570221/RPCS3.log.gz)

Already tried whatever combination of settings could come to mind. Also, as an additional note, this game is also based on Unreal Engine 3. I don't know if this is related, but i wanted to point it out. 

If someone's interested on testing this, there's a small setup needed to hook it up to our custom server. Just let me know and i'll PM the link in Discord.

**Comment by Megamouse** [comment] 2022-05-06 05:36
Is this still an issue?

**Comment by Jonathan44062** [comment] 2022-05-06 07:16
![image](https://user-images.githubusercontent.com/78843189/167078050-daf40e6e-ba56-45e3-a8a4-74607272c0b2.png)
It seems so, the issue is still there

Log:
[RPCS3.log.gz](https://github.com/RPCS3/rpcs3/files/8637961/RPCS3.log.gz)

But, it seems only happen if `Accurate RSX reservation access` is not enable, with that setting enable, I can go Ingame, I play a little to confirm
![image](https://user-images.githubusercontent.com/78843189/167078390-37d64745-b735-4b2e-b250-9778f65b02cd.png)

Log with Accurate RSX: 
[RPCS3AliceAccurateRSX.log.gz](https://github.com/RPCS3/rpcs3/files/8638256/RPCS3AliceAccurateRSX.log.gz)

**Comment by kd-11** [comment] 2022-05-06 07:53
Closing as fixed.

**Closed by kd-11** 2022-05-06 07:53 UTC
Labels: Bug, RSX
