### ISSUE TITLE
Unseen buttons (Dark theme) in Windows 10

### ISSUE THREAD

**Issue by gandalfthewhite19890404** [RPCS3/rpcs3#3385] opened 2017-09-03 18:47 UTC
Stop and Pause emulation buttons cannot be recognised in Windows 10(stock, without any mods).
![rpcs3_datktheme](https://user-images.githubusercontent.com/24764335/30005722-5d999bd4-90f1-11e7-854b-8e5541dd0195.JPG)

**Comment by Megamouse** [comment] 2017-09-03 19:11
please uncheck this and tell me if it works:
![image](https://user-images.githubusercontent.com/23019877/30005884-645c1974-90ec-11e7-80a3-b627c9b28af7.png)

**Comment by Megamouse** [comment] 2017-09-03 19:13
as an alternative you can make the toolbar icons darker

**Comment by AniLeo** [comment] 2017-09-03 19:42
Yeah, you're overriding custom UI colors for that to happen

**Comment by gandalfthewhite19890404** [comment] 2017-09-04 04:02
Better but not good enough.
![rpcs3_datktheme_with_custom](https://user-images.githubusercontent.com/24764335/30011310-ea2e64c4-913e-11e7-843b-a11341d45c00.JPG)

**Comment by AniLeo** [comment] 2017-09-04 04:15
It's working as intended, I checked on clean installation.

Closing.

**Comment by AniLeo** [comment] 2017-09-04 04:18
I think your color is slightly off though, did you try costum colors?

I will check again to make sure

**Comment by Megamouse** [comment] 2017-09-04 06:01
I don't see the "not good enough".
I can clearly distiguish all the buttons

**Comment by AniLeo** [comment] 2017-09-04 17:04
Ok, I checked again, that's the proper color. Closing

**Closed by AniLeo** 2017-09-04 17:04 UTC

**Comment by gandalfthewhite19890404** [comment] 2017-09-04 17:37
I oriented on this
[https://rpcs3.net/blog/wp-content/uploads/2017/08/progress2/kuroi.jpg](url)

**Comment by Megamouse** [comment] 2017-09-04 17:39
What you refer to as "Wrong color" is the color of disabled buttons. you need to boot a game first to have those buttons enabled.

**Comment by AniLeo** [comment] 2017-09-04 17:46
That screenshot is outdated, I hadn't coded in disabled buttons by then
