### ISSUE TITLE
DX12/GL/Vulkan: Turbo: Super Stunt Squad black textures

### ISSUE THREAD

**Issue by SakataGintokiYT** [RPCS3/rpcs3#1867] opened 2016-07-06 06:28 UTC
##### Turbo Super Stunt Squad :

<img src="http://www.fotoszok.pl/upload/ba9056a6.jpg" alt="Fotoszok.pl" />

{PPU[0x9] Thread (main_thread) [0x008ab518]} sys_io TODO: cellPadPeriphGetInfo(info=*0xd00bf8bc)

{PPU[0x9] Thread (main_thread) [0x008ab518]} sys_io TODO: cellPadPeriphGetInfo(info=*0xd00b324c)

{PPU[0x9] Thread (main_thread) [0x008ab518]} sys_io TODO: cellPadPeriphGetInfo(info=*0xd00b31ac)

{PPU[0x9] Thread (main_thread) [0x008ab518]} sys_io TODO: cellPadPeriphGetInfo(info=*0xd00befcc)

{PPU[0x9] Thread (main_thread) [0x008ab518]} sys_io TODO: cellPadPeriphGetInfo(info=*0xd00c61fc)
##### With lib_io

{PPU[0xa] Thread (main_thread) [0x00ba263c]} HLE TODO: Unimplemented syscall syscall_510 -> CELL_OK
{PPU[0xa] Thread (main_thread) [0x00ba2680]} HLE TODO: Unimplemented syscall syscall_512 -> CELL_OK
{PPU[0xa] Thread (main_thread) [0x00ba27f4]} HLE TODO: Unimplemented syscall syscall_514 -> CELL_OK
##### Shaderlog : https://mega.nz/#!JRwnXIxb!IGrNiC5Sn2JsOmMSlwZ57kIr98wfegT-C4AJchb_TjQ

---
##### Pac-Man and the Ghostly Adventures

<img src="http://www.fotoszok.pl/upload/98893e38.png" alt="Fotoszok.pl" />

{PPU[0x9] Thread (main_thread) [0x008bff10]} sys_io TODO: cellPadPeriphGetInfo(info=*0xd00bf8ac)

{PPU[0xb] Thread (main_thread) [0x008ab518]} sys_io TODO: cellPadPeriphGetInfo(info=*0xd00bf8bc)

{PPU[0xb] Thread (main_thread) [0x008bff10]} sys_io TODO: cellPadPeriphGetInfo(info=*0xd00c61fc)

{PPU[0x9] Thread (main_thread) [0x008bff10]} sys_io TODO: cellPadPeriphGetInfo(info=*0xd00befbc)

{PPU[0xb] Thread (main_thread) [0x008bff10]} sys_io TODO: cellPadPeriphGetInfo(info=*0xd00befbc)
##### With lib_io

{PPU[0xa] Thread (main_thread) [0x00bb263c]} HLE TODO: Unimplemented syscall syscall_510 -> CELL_OK
{PPU[0xa] Thread (main_thread) [0x00bb2680]} HLE TODO: Unimplemented syscall syscall_512 -> CELL_OK
{PPU[0xa] Thread (main_thread) [0x00bb967c]} HLE TODO: Unimplemented syscall syscall_514 -> CELL_OK

**Comment by raven02** [comment] 2016-07-06 15:02
How about Vulkan?

**Comment by SakataGintokiYT** [comment] 2016-07-06 15:29
@raven02 
The same issue  on Ogl/ vulkan  ;}

**Comment by raven02** [comment] 2016-07-06 15:37
i see. thanks @SakataGintokiYT

**Comment by SakataGintokiYT** [comment] 2016-09-21 15:52
**Vulkan**
Pac-Man and the Ghostly Adventures  [RenderDoc]
<img src="http://www.fotoszok.pl/upload/d765c3b0.jpg" alt="Fotoszok.pl" />
[Title.Screen.rdc](https://mega.nz/#!YAAGXbDJ!Kb9E4y1FldNCHdzo0keeUaIPXs9-OemxQkr8fi36I-Q)
[In.Game.rdc](https://mega.nz/#!VU5RnJQT!a6Bpuu7V3I3S4Ax4CObY4dGW815g8ABagSGfz99ZiOM)

**Comment by SakataGintokiYT** [comment] 2016-09-29 10:19
@kd-11 
Do you know how to fix black textures in these games ?

**Comment by kd-11** [comment] 2016-09-29 10:26
I'll investigate when I have some time

**Comment by kd-11** [comment] 2016-09-29 10:27
@SakataGintokiYT could you upload the ogl trace? Its much easier to debug

**Comment by SakataGintokiYT** [comment] 2016-09-29 10:32
@kd-11 
Yes, i upload this later

**Comment by SakataGintokiYT** [comment] 2016-09-29 12:11
@kd-11 
**[OpenGL]**
**[In Game](https://mega.nz/#!pEwzURib!5hxKT7VbkyYYO-Ybk7O5qPo85SRbfQjSY6_l3XuTAKU)**

**Comment by SakataGintokiYT** [comment] 2016-10-15 13:05
`E {rsx::thread} RSX: Unknown/illegal instruction: 0x18 (forced unit 2)`

**Comment by SakataGintokiYT** [comment] 2017-02-03 21:43
@kd-11 
**[debug] Read data from cell when initializing RTVs]**
[5a46560d]
**[Log:](https://gist.github.com/SakataGintokiYT/ee39d1f414b75f4933c12fb348d440be)**

**[OpenGL-RenderDoc:](https://mega.nz/#!hZQ30AjS!fBz5FkXKyQcAaceNXapmAYhuhuscXrp67Hf_Ka26gho)**

**Comment by kd-11** [comment] 2017-02-04 06:03
@SakataGintokiYT Does enabling read/write color buffers make a difference with opengl? The misses I'm seeing would be affected by that I think.

**Comment by SakataGintokiYT** [comment] 2017-02-04 06:20
@kd-11 
with: read/write color buffers
<img src="http://www.fotoszok.pl/upload/24fcaf52.jpg" alt="Fotoszok.pl" />

**[OpenGL-RenderDoc: ](https://mega.nz/#!tQozjYBQ!zq9-gFNyXgqH1lGy43etAPxN2e0HIpGftmCVlnY9XL4)**

**Comment by SakataGintokiYT** [comment] 2017-02-05 10:02
@kd-11 

Cache views of fbo data in pinned PBOs
[4ccb9799]

```
Fatal error
Unhandled Win32 exception 0xC0000005.
Segfault reading location 0000000000000000 at 00007ffd91cfca20.
Instruction address: 00007ffd91cfca20.
Function address: 00007ffd91cfc830 (base+0xc830).
Module name: 'VCRUNTIME140.dll'.
Module base: 00007ffd91cf0000.
RPCS3 image base: 0000000000010000.
```

**[Log:](https://gist.github.com/SakataGintokiYT/dfb24f790065bfb44235451b88e8dc19)**

**Comment by kd-11** [comment] 2017-02-05 10:10
Yea, that's what I feared. However, it does confirm that this game is trying to read data from a locked section view. Will add more info to the log and try to figure this one out.

**Comment by kd-11** [comment] 2017-02-05 10:21
https://ci.appveyor.com/project/kd-11/rpcs3/build/0.0.1-398
I forgot that vm::protect actually does modify page properties. Also, remember to disable r/w buffers since I dont want anything to interfere with this test.

**Comment by SakataGintokiYT** [comment] 2017-02-05 10:35
@kd-11 

[debug] Fix rtt surface dimensions
[47334cfc]

```

Fatal error
Unhandled Win32 exception 0xC0000005.
Segfault reading location 0000000000000000 at 00007ff82a04ca20.
Instruction address: 00007ff82a04ca20.
Function address: 00007ff82a04c830 (base+0xc830).
Module name: 'VCRUNTIME140.dll'.
Module base: 00007ff82a040000.
RPCS3 image base: 0000000000010000.
```

**[Log:](https://gist.github.com/SakataGintokiYT/d3288ea8856e81962c5b393fbfe5892c)**

**Comment by kd-11** [comment] 2017-02-05 10:38
Looks like a failed map operation.

**Comment by kd-11** [comment] 2017-02-05 10:48
https://ci.appveyor.com/project/kd-11/rpcs3/build/0.0.1-400
If it fails to run, enable debug output and attach log.

**Comment by SakataGintokiYT** [comment] 2017-02-05 11:04
@kd-11 
[Initialize pbo target 5c1fee42]

```
Unhandled Win32 exception 0xC0000005.
Segfault reading location 0000000007231000 at 00007ff83179cb7c.
Instruction address: 00007ff83179cb7c.
Function address: 00007ff83179c830 (base+0xc830).
Module name: 'VCRUNTIME140.dll'.
Module base: 00007ff831790000.
RPCS3 image base: 0000000000010000.
```
with enable debug output
**[Log:](https://gist.github.com/SakataGintokiYT/024bda92d6e12d53f8de890eef026ba5)**

**Comment by kd-11** [comment] 2017-02-05 11:23
Looks like map succeeded, but something else failed.
https://ci.appveyor.com/project/kd-11/rpcs3/build/0.0.1-401 dumps info to log file. I still expect the crash, but hopefully this will give me enough information.

**Comment by SakataGintokiYT** [comment] 2017-02-05 11:43
@kd-11 
[debug] Dump more info from texture cache [ a886e058 ]

```

Fatal error
Unhandled Win32 exception 0xC0000005.
Segfault reading location 000000000ae01000 at 00007ffbc414cb7c.
Instruction address: 00007ffbc414cb7c.
Function address: 00007ffbc414c830 (base+0xc830).
Module name: 'VCRUNTIME140.dll'.
Module base: 00007ffbc4140000.
RPCS3 image base: 0000000000010000.
```
**[Log:](https://gist.github.com/SakataGintokiYT/832cbc8bb37368f633b0f3a0e41df9f4)**

**Comment by kd-11** [comment] 2017-02-05 11:51
Looks like it needs more work. Will update soon.

**Comment by kd-11** [comment] 2017-02-05 16:39
https://ci.appveyor.com/project/kd-11/rpcs3/build/0.0.1-402
Expect very poor performance with this one until I get around to cleaning and optimizing the code.

**Comment by kd-11** [comment] 2017-02-05 16:41
I know there may be some missing drawings, this is due to odd pitch handling.
I'll have to run more tests to determine correct behavior for these double-pitch textures (MSAA?). I believe the same issue affects catherine half-width sampling.

**Comment by SakataGintokiYT** [comment] 2017-02-05 17:10
@kd-11 
<img src="http://www.fotoszok.pl/upload/083de718.jpg" alt="Fotoszok.pl" />

**[OpenGL-RenderDoc:](https://mega.nz/#!JMpVATYY!9g22jmhMWOR2MNujlq8K2u_LnDA05y4JX6VNlw94Q1c)**

**[shaderlog:](https://mega.nz/#!lVZlQSJK!RJjgygn_Kp7kMXBV1HZr3b0XJPyKTq5pT3LzG0zPQpM)**

**Comment by SakataGintokiYT** [comment] 2017-02-05 17:22
@kd-11 
Very nice progress in   Bakugan: Battle Brawlers  ^_^
<img src="http://www.fotoszok.pl/upload/91a2bc64.jpg" alt="Fotoszok.pl" />

**Comment by kd-11** [comment] 2017-02-05 20:12
Looks like super stunt squad menu is trying to perform some kind of blend operation. Blending is set to off, but once can clearly see the shader is attempting to overwrite the render with the background image and sets the alpha component to a computed variable. That might actually be unrelated to this bug.
As for bakugan, its the wierd pitch issue again it seems.

**Comment by al0xf** [comment] 2017-02-08 14:13
If you by crashing in Persona 4 mean black screen but otherwise running in Persona 4 Arena then it makes no (visible) difference.

**Comment by kd-11** [comment] 2017-02-08 14:15
For persona 4, yes, the crash is what I'm interested in right now.

**Comment by SakataGintokiYT** [comment] 2017-02-08 15:07
@kd-11 

<img src="http://www.fotoszok.pl/upload/8cbf5789.png" alt="Fotoszok.pl" />

**[Log:](https://gist.github.com/SakataGintokiYT/f87c4fdd35c9dc8eec4b65db425686cd)**
**[ShaderLog:](https://mega.nz/#!RcYWEYIY!xz0bScl9Ui5LSOH17wbuhiSLmbKwdFzBvHMFZTrMHe0)**
**[OpenGL-Render-Doc:](https://mega.nz/#!0dAR1RJJ!kHfkpvnCzJE1Al7B83hYZ1QJmClImcxGAP9QbtzFurg)**

**Comment by AniLeo** [comment] 2017-02-08 19:36
@kd-11 Persona 5 is slightly improved too

Master build
![https://rpcs3.net/blog/wp-content/uploads/2017/02/p5jpg.jpg](https://rpcs3.net/blog/wp-content/uploads/2017/02/p5jpg.jpg)

Your build
![screenshot_308](https://cloud.githubusercontent.com/assets/10283761/22753978/dc4f6fda-ee35-11e6-8518-2cf94709f26b.jpg)

**Comment by kd-11** [comment] 2017-02-10 09:11
The broken graphics in bakugan are a regression I inadvertently introduced while rewriting the texture cache. I'm hunting down which part of the changes causes the misalignment with the fragment constants buffer. Some other titles are also affected.

**Comment by kd-11** [comment] 2017-02-13 14:38
https://ci.appveyor.com/project/kd-11/rpcs3/build/0.0.1-421 fixes the regression. Please retest.

**Comment by Nekotekina** [comment] 2017-02-13 14:40
@kd-11 Can you fix framebuffer copying in Vulkan? It's blackscreen in some homebrews when the frame is "rendered" on the Cell side.

**Comment by kd-11** [comment] 2017-02-13 14:43
@Nekotekina Will do so as soon as I've confirmed that GL works properly. Same goes for DX12, although DX12 has the basics done.

**Comment by SakataGintokiYT** [comment] 2017-02-13 14:51
@kd-11 
<img src="http://www.fotoszok.pl/upload/c42aa401.png" alt="Fotoszok.pl" />

**Comment by Zangetsu38** [comment] 2017-02-13 17:24
SplatterHouse have exactly same issue render, look my issue for see detail ^^
![capture d ecran 2017-02-13 18 15 02](https://cloud.githubusercontent.com/assets/5261759/22894517/8823d288-f219-11e6-95a2-c0dd75049ff3.png)

**Comment by kd-11** [comment] 2017-02-13 18:11
Ok. I'll have to do software "scaling" to get around this. Will push an update using nearest scaling and we can see what happens.

**Comment by kd-11** [comment] 2017-02-13 18:58
https://ci.appveyor.com/project/kd-11/rpcs3/build/0.0.1-422 adds software scaling for upto 2 and 4 samples per pixel. It implements the inverse of the fix we committed for catherine, but this time for programs that copy the data and re-use it.

**Comment by SakataGintokiYT** [comment] 2017-02-13 19:09
@kd-11 

<img src="http://www.fotoszok.pl/upload/bf5e22e1.jpg" alt="Fotoszok.pl" />

**Comment by kd-11** [comment] 2017-02-13 19:12
Lol. That seems worse somehow. Not sure what is going on there; looks like I've made a wrong assumption about byte order somehow.

**Comment by Zangetsu38** [comment] 2017-02-13 20:59
@kd-11  Very good, just very pixelize lol and oh i just see with picture, but in OGL, have polyghon line, same Catherine.
![capture d ecran 2017-02-13 21 57 51](https://cloud.githubusercontent.com/assets/5261759/22903034/890760c0-f237-11e6-916e-3f3995575cba.png)

**Comment by kd-11** [comment] 2017-02-14 07:56
I'm using nearest mode scaling for this test. I'll have to figure out why it didn't work for bakugan. Will update to use the GPU to perform the scaling which might be faster and at least better quality. Vulkan and DX12 are still unimplemented because I'm using GL as a test platform right now. Its just easier that way.

**Comment by Zangetsu38** [comment] 2017-02-14 09:59
Ah ok I understand, it is like for catherine so, once it is good for ogl you apply it on the other two ^^

**Comment by kd-11** [comment] 2017-02-14 12:12
https://ci.appveyor.com/project/kd-11/rpcs3/build/0.0.1-424 Should fix CPU scaling for Bakugan. I can work on GPU accelerated scaling from there.

**Comment by SakataGintokiYT** [comment] 2017-02-14 12:31
@kd-11 
<img src="http://www.fotoszok.pl/upload/5a1431c1.jpg" alt="Fotoszok.pl" />
**[shaderlog:](https://mega.nz/#!RZ5ixDiR!j91yAjIs3C4DAi6UDcjOoD8FeQtWrBm1EkEPg0pfKrU)**
[Log:](https://gist.github.com/SakataGintokiYT/6eb4ee2a18ec55ca137ff25484726c0b)

**Comment by kd-11** [comment] 2017-02-14 13:29
Looks like the framebuffer does not divide evenly by the pitch. This will be fixed using GPU scaling as it will be too slow to do on the CPU.

**Comment by Zangetsu38** [comment] 2017-02-14 13:54
I think No change for Splatterhouse
[RenderDoc+Log](https://mega.nz/#!pA4zGJxZ!hWS9wJIlAKbBkeEyzKOlV29JH2HGZAYgqYlTNYJE86M)
![capture d ecran 2017-02-14 14 45 10](https://cloud.githubusercontent.com/assets/5261759/22931600/87c4ced0-f2c5-11e6-80db-21dc06b692fe.png)

**Comment by kd-11** [comment] 2017-02-15 10:59
https://github.com/RPCS3/rpcs3/pull/2391
GPU scaling is not yet implemented, but hopefully bakugan is not misaligned.

**Comment by SakataGintokiYT** [comment] 2017-02-15 11:34
@kd-11 
[Bakugan: Battle Brawlers]
F {rsx::thread} class std::system_error thrown: device or resource busy: device or resource busy

**Comment by kd-11** [comment] 2017-02-15 16:11
I've pushed a fix for overflow when padding rows. Should hopefully fix the bakugan crash

**Comment by SakataGintokiYT** [comment] 2017-02-15 16:35
@kd-11 
[a2e1688e]
<img src="http://www.fotoszok.pl/upload/c6745753.jpg" alt="Fotoszok.pl" />

**Comment by Zangetsu38** [comment] 2017-02-15 20:11
@SakataGintokiYT you use wat setting ? for me not works, i don't understand :/
I use build appeveyor for sure, but i don't iknow with impossible acces ingame

**Comment by SakataGintokiYT** [comment] 2017-02-15 20:31
@kd-11 
@Zangetsu38 
<img src="http://www.fotoszok.pl/upload/14c9e4e9.jpg" alt="Fotoszok.pl" />
I use Nvidia Vulkan Beta Driver 376.71
**[Log:](https://gist.github.com/SakataGintokiYT/ce860248ef0f9afaf74b3b8a90b0f709)**

**Comment by Zangetsu38** [comment] 2017-02-15 20:41
@SakataGintokiYT I don't knwo why, i have set exactly same setting, with same build, and don't works, aftyer chow loading, rpcs3 show nothing more and log don't change

**Comment by SakataGintokiYT** [comment] 2017-02-15 21:18
@Zangetsu38 
Retested on latest driver [378.66]
<img src="http://www.fotoszok.pl/upload/058ad38d.jpg" alt="Fotoszok.pl" />

**Comment by Zangetsu38** [comment] 2017-02-15 21:21
very strange :/ hmm I have GTX 1080 and insider build 15.031, and after instaled this new drivers my pc have a very bugged, crash explorer random, rpcs3 crash

**Comment by SakataGintokiYT** [comment] 2017-02-15 21:31
@Zangetsu38 
I use old build 10.00.10586.0000 and RedStone 2 is sucks  ^_^

**Comment by Zangetsu38** [comment] 2017-02-15 21:32
@SakataGintokiYT  xD i see :D

**Comment by Zangetsu38** [comment] 2017-02-16 00:39
@SakataGintokiYT  ok fixed lol, problem caused by libgem xD, just disable and after working, but no ingame in avanture mod afrer cinematic i have this @kd-11
>E {PPU[0x1000000] Thread (main_thread) [0x0007c68c]} RSX: gl::fence sync returned unknown error 0x0
F {PPU[0x1000000] Thread (main_thread) [0x0007c68c]} class std::runtime_error thrown: Verification failed (e=0x2): 
(in file g:\git\rpcs3-dante\rpcs3\emu\rsx\gl\GLTextureCache.h:490)

Same error il mt issue, Persona, Lone etc

**Comment by kd-11** [comment] 2017-02-20 05:41
I have discovered a corner case that was not handled within the shared surface store.
This issue I consider to be fixed with latest update to the PR; please retest other games. You do not need to enable "Write Color Buffers" for this to work. Please test if this affects other games (You should see alot of errors about overlapping surfaces if that is the case).


![image](https://cloud.githubusercontent.com/assets/15904127/23113303/4ba13380-f748-11e6-8f34-bd2ed47bf2a8.png)

**Comment by SakataGintokiYT** [comment] 2017-02-20 06:49
@kd-11 

I have a memory overflow in Turbo: Super Stunt Squad
<img src="http://www.fotoszok.pl/upload/507b6247.jpg" alt="Fotoszok.pl" />

------------------------------------------------------------------------------------------------------------
Pac-Man and the Ghostly Adventures
```
F {rsx::thread} class std::runtime_error thrown: Verification failed: 
(in file c:\rpcs3\rpcs3\emu\rsx\gl\GLTextureCache.h:571)
```
------------------------------------------------------------------------------------------------------------

Bakugan: Battle Brawlers /  Jet Set Radio  have a black screen with / without Write Color Buffers

**Comment by kd-11** [comment] 2017-02-20 07:43
Overflow should be fixed now. Will look into the other issues.

**Comment by SakataGintokiYT** [comment] 2017-02-20 08:00
**Ben 10: Omniverse 2**  without Write Color Buffers
<img src="http://www.fotoszok.pl/upload/d28e59b0.png" alt="Fotoszok.pl" />

**Comment by SakataGintokiYT** [comment] 2017-02-22 11:05
[aab9759b]

**Pac-Man and the Ghostly Adventures**
<img src="http://www.fotoszok.pl/upload/14486776.jpg" alt="Fotoszok.pl" />

**Comment by SakataGintokiYT** [comment] 2017-02-22 14:01
@kd-11 
**Bayonetta: First Climax -Demo**
[Write color buffer is required]
<img src="http://www.fotoszok.pl/upload/69806893.jpg" alt="Fotoszok.pl" />

**Comment by kd-11** [comment] 2017-03-11 11:52
Closing this issue since most games listed here are fixed on current master.

**Closed by kd-11** 2017-03-11 11:52 UTC
Labels: d3d12, opengl, vulkan
