### ISSUE TITLE
[Feature Request] make a wiki best settings for rpcs3 that download into emulator 

### ISSUE THREAD

**Issue by Mew89** [RPCS3/rpcs3#8986] opened 2020-09-26 23:03 UTC
## Quick summary
Allow people go to wiki find best settings or rpcs3 have in game settings download best settings 

## Details

Please describe the feature as accurately as possible.

#### 1. Please describe, what part of RPCS3 would be affected by your feature: Gameplay UI
* Gameplay
* Debugging
* UI
* Patches
* Installation
* Github
* CI
* etc.

#### 2. Please tell us, why your feature is important to RPCS3.
Let download best game settings do change it so much your self

#### 4. Please provide your system configuration:
* windows 10 2004 
* ryzen 9 4900hs 
* rtx 2060 max q
* 450.6
* etc.

#### Please include.
* Anything else you deem to be important

**Comment by AniLeo** [comment] 2020-09-26 23:09
Duplicate of #4434

**Closed by AniLeo** 2020-09-26 23:09 UTC

**Comment by Mew89** [comment] 2020-09-26 23:10
L

**Comment by Mew89** [comment] 2020-09-28 03:18
![download](https://user-images.githubusercontent.com/71794185/94387279-b2c40b00-0117-11eb-8645-780448f5c838.jpeg)
It is just a joke and issues closed  please ban me

**Comment by Mew89** [comment] 2020-09-28 03:22
L
