### ISSUE TITLE
Demon's Souls reliably hangs after build 6718

### ISSUE THREAD

**Issue by ashemedai** [RPCS3/rpcs3#4568] opened 2018-05-13 21:38 UTC
System: Windows 10 (April's update; build 1803), GTX 980, Intel i7-4770, 16 GB
Settings: Vulkan, Write Color Buffers, English (US), Pads: DualShock 4, rest default
Firmware: 4.82
Kept the title to Demon's Souls as it's the only ISO I have dumped at the moment, so could not personally verify with other titles.

After PR #4553 (tested with build 6734) Demon's Souls hangs after fighting the first enemy in the tutorial. Audio keeps playing, FPS counter still fluctuates at times, but game is otherwise hung up.

After forcibly quitting the emulator render window, you cannot load the game again due to encountering `{PPU[0x1000000] Thread (main_thread)} class std::runtime_error thrown: Verification failed (e=0xb7) (0): 
(in file Emu\Cell\SPUASMJITRecompiler.cpp:2753)`. It does not matter if you delete the save game and clear the LLVM cache, problem persists.

I could not reproduce the above mentioned loading problem with PR #4565 and build 63e4a0d8. That build, however, still has the hang problem described earlier.

Build 6718 works, as in: I can continue past the first enemy, kill some others and walk around for a while.

I've attached the log file of the 63e4a0d8 build run until the hang:
[RPCS3.gz](https://github.com/RPCS3/rpcs3/files/1998953/RPCS3.gz)
I might have missed something subtle, but it does not seem that there's anything in the log that's out of the ordinary. If there's anything I can do to help narrow it down, let me know.

**Comment by Lotiuss** [comment] 2018-05-14 13:28
I can confirm the same issue. System: elementary OS 0.4.1 Loki, R9380X, AMD FX-8350, 16GB RAM. I was unable to find settings that work, always drops to ~10 FPS in the counter and hangs after the first or second enemy.

**Comment by Dreadmoth** [comment] 2018-05-14 22:01
I have encountered the same issue (BLES00932) - the game hangs whilst loading a savegame with some progress, or shortly after the first enemy in the tutorial. I am also unable to boot the game after stopping emulation, but I found it's possible to get it to start again (until the next hang) by deleting the following file:

`rpcs3\data\BLES00932\ppu-Jn6VNnpwAE4RVNGTAov70kUVgwKA-EBOOT.BIN\spu-§safe-v1.dat`

**Comment by thinkdude** [comment] 2018-05-16 15:16
I confirm it freezes within first minute or so and will not start again.

**Comment by money123451** [comment] 2018-05-16 16:44
can we get someone with a TSX enabled cpu to test to see if neko added a TSX optimization to the non TSX cpu branch since all these logs are with older cpus (like my i7-4770k) also if your testing with [this build](https://ci.appveyor.com/project/rpcs3/rpcs3/build/0.0.5-6718/artifacts) go to the games config folder after each run and delete the PPU-something-something folders to fix the error
`{PPU[0x1000000] Thread (main_thread)} class std::runtime_error thrown: Verification failed (e=0xb7) (0): (in file Emu\Cell\SPUASMJITRecompiler.cpp:2753)`

**Comment by Moonsera** [comment] 2018-05-17 15:46
At work now so can't attach log, but I figured out what causes the hang. When you kill the first enemy in tutorial, his body becomes a ragdoll, and at this moment game freezes. Same thing happens if you get past him and try to break crates, freezes the instant your rolling body touches the crate.
So it's something physics-related.
P.S. i7-3770K here.

**Comment by Nekotekina** [comment] 2018-05-17 16:12
Try #4603 please

**Comment by isshininu** [comment] 2018-05-17 16:36
Well, DeS still hangs on loading screen for me:
spu asmjit
[RPCS3.log.gz](https://github.com/RPCS3/rpcs3/files/2014036/RPCS3.log.gz)

spu llvm
[RPCS3.log.gz](https://github.com/RPCS3/rpcs3/files/2014037/RPCS3.log.gz)

**Comment by Nekotekina** [comment] 2018-05-17 19:56
Another bug was fixed in that PR

**Comment by thinkdude** [comment] 2018-05-17 23:11
Hey I'm getting the hangs and I have an i5-7600k

**Comment by flatflatflat** [comment] 2018-05-17 23:46
Same issue here. Demon Souls hangs. Tried 6718 (pull 4503) and that still works, but anything after that resuslts in DeS hanging when loading a save and showing the npc's during loading.
tried all diferent cpu/gpu settings, no difference. Only thing that has worked has been to revert to 6718 or earlier builds.

**Comment by Parthorisian** [comment] 2018-05-18 23:53
Can confirm - game loads but hang https://i.imgur.com/jKdNNbs.jpg
Log [DemonSoulz_hangRPCS3.zip](https://github.com/RPCS3/rpcs3/files/2018931/DemonSoulz_hangRPCS3.zip)

**Comment by TigiHof** [comment] 2018-05-20 13:42
Still no fix for this with the latest build 0.0.5-c1f84fff. The game freezes after a couple of minutes every time I try it. I have an i7-6700k.

**Comment by Parthorisian** [comment] 2018-05-21 00:40
For now **Demon soulz[blus30443]** still able load menu, but unfortunately throws this exception for now
F {PPU[0x100002f] Thread (ChrInsManThread::Thread) [0x009e1e70]} class std::runtime_error thrown: Verification failed (e=0x57): 
(in file Emu\Cell\lv2\sys_cond.cpp:279)
Log [DemonSouls_throwRPCS3.zip](https://github.com/RPCS3/rpcs3/files/2020868/DemonSouls_throwRPCS3.zip)

**Comment by Parthorisian** [comment] 2018-05-22 08:27
**NTZ1989**
kd11 expbuild https://ci.appveyor.com/api/buildjobs/370t489e4itv7ysx/artifacts/rpcs3-v0.0.5-9cdc6f80_win64.7z still able work even for my i7-4770 in best way (still some glitches and random hangs+crashes as usual)

**Comment by NTZ1989** [comment] 2018-05-22 22:46
@Parthorisian Thanks! 
I tested it and the error kept happening, I used the recommended settings and I've loaded my save on Nexus when I try to travel for the first time to the unique dungeon available, Boletarian Palace. I got this infinite loading screen:

![infinite loading screen demon s souls](https://user-images.githubusercontent.com/39391129/40393469-f395fb10-5df5-11e8-9cb4-57ea8515c964.png)

The fps' counter keep varying but it doesn't pass through that screen no matter how many time I wait, it doesn't freeze the emulator but I feel like some kind of Looping or something similar...
 
Then I opened the config.yml and changed the PPU Threads from 2 to 1 and SPU Penalty from 3 to 0 I got this error code when I try to open the "Configure" option, it keep repeating the error, preventing me to open that windows and change the emulator settings.

![error rpcs3](https://user-images.githubusercontent.com/39391129/40393635-a71e1028-5df6-11e8-8a03-e8284cd5cad2.png)

it hangs the emulator, makes me force to close its task.

I gave a brief check, the i7 4970 supports TSX but unfornatully my ryzen 1700 just AVX+ and AVX2+ I can't affirm for sure this is the reason that is the causing the issues but any build seems pass through that screen on my pc...

**Comment by psennermann** [comment] 2018-05-23 16:35
If this cannot be fixed, why not just reverting or partially reverting #4553 ? I mean breaking Demon's Soul, NiNoKuni, GTI Club and maybe other games for fixing The House of Dead 4 doesn't seem to me a great deal...

**Comment by Asinin3** [comment] 2018-05-23 16:45
No one said it can't be fixed, just use old builds for now. We're still in alpha regressions are to be expected more testing on Pull Requests from users would help reduce the amount of regressions in master builds.

**Comment by Parthorisian** [comment] 2018-05-24 03:26
**@NTZ1989**
Ive never seen this issue, "infinite loading screen". For all tested builds. But i dont have Windows 10 build 1803. Only old Haswell 4770, Win7SP1Ultx64bit(updates before December 2016y) and Win10LTSB(updates before March 2017y). May be another patch for Win10b1803 (like#4579) can help.

**Comment by NTZ1989** [comment] 2018-05-24 04:27
@Parthorisian 
Every build that I tested gets stuck on an infinity loading screen I'm starting the game from the zero. I've already tested many build more than 10 ones, if you want I can record a short video. The oldest build that I tried was the 6487 until the last one released today the 6841... No Success, they all do the same to me. I'll put my log file, I hope that it can help you.

[RPCS3.log.gz](https://github.com/RPCS3/rpcs3/files/2033811/RPCS3.log.gz)

**Comment by NTZ1989** [comment] 2018-05-24 04:42
I copied the code generated by the emulator, not the Gz file, that code the emulator generates when the game is running in live. 

I don't know nothing about codes or programming but it keep repeating itself

U {PPU[0x1000017] Thread (NexusRevolution Main) [0x01d55654]} sceNp TODO: sceNpManagerGetNpId(npId=*0xd0378864)
U {PPU[0x1000017] Thread (NexusRevolution Main) [0x00e123ec]} sceNp TODO: sceNpManagerGetOnlineName(onlineName=*0xd0378888)
U {PPU[0x1000017] Thread (NexusRevolution Main) [0x00e123fc]} sceNp TODO: sceNpManagerGetAvatarUrl(avatarUrl=*0xd03788bc)

[Copy of the emulator Log.zip](https://github.com/RPCS3/rpcs3/files/2033829/Copy.of.the.emulator.Log.zip)

![code repeating demon souls](https://user-images.githubusercontent.com/39391129/40464761-7ed0a056-5ef3-11e8-9ebb-a51b43481dc0.png)

It says something about online stuff, no sure. But as standard the emulator is set to "Disconnected" status.

**Comment by NTZ1989** [comment] 2018-05-24 04:54
Maybe there is nothing but looking at the code just before it starts to repeat these three lines it gives these erros: 

dirName=“BLUS30443”, errDialog=0x0, funcStat=*0x1970c00, container=4294967295)
E {PPU[0x1000000] Thread (main_thread) [0x00c3a9d4]} 'sys_ppu_thread_detach' failed with 0x80010005 : CELL_ESRCH [1]
E {PPU[0x1000013] Thread (_cellsurMixerMain) [0x01d554ec]} '_sys_lwmutex_lock' failed with 0x80010005 : CELL_ESRCH [1]
E {PPU[0x1000013] Thread (_cellsurMixerMain) [0x01d554ec]} '_sys_lwmutex_lock' failed with 0x80010005 : CELL_ESRCH [2]
E {PPU[0x1000013] Thread (_cellsurMixerMain) [0x01d554ec]} '_sys_lwmutex_lock' failed with 0x80010005 : CELL_ESRCH [3]
E {PPU[0x1000011] Thread (_sys_MixerChStripMain) [0x01d554ec]} '_sys_lwmutex_lock' failed with 0x80010005 : CELL_ESRCH [1]
E {PPU[0x1000011] Thread (_sys_MixerChStripMain) [0x01d554ec]} '_sys_lwmutex_lock' failed with 0x80010005 : CELL_ESRCH [2]
E {PPU[0x1000011] Thread (_sys_MixerChStripMain) [0x01d554ec]} '_sys_lwmutex_lock' failed with 0x80010005 : CELL_ESRCH [3]
E {PPU[0x1000013] Thread (_cellsurMixerMain) [0x01547fb0]} 'sys_mutex_lock' failed with 0x80010008 : CELL_EDEADLK [1]
E {PPU[0x1000013] Thread (_cellsurMixerMain) [0x01547fb0]} 'sys_mutex_lock' failed with 0x80010008 : CELL_EDEADLK [2]
U {PPU[0x1000017] Thread (NexusRevolution Main) [0x01d55654]} sceNp TODO: sceNpManagerGetNpId(npId=*0xd0378864)
U {PPU[0x1000017] Thread (NexusRevolution Main) [0x00e123ec]} sceNp TODO: sceNpManagerGetOnlineName(onlineName=*0xd0378888)
U {PPU[0x1000017] Thread (NexusRevolution Main) [0x00e123fc]} sceNp TODO: sceNpManagerGetAvatarUrl(avatarUrl=*0xd03788bc)
E {PPU[0x1000013] Thread (_cellsurMixerMain) [0x01547fb0]} 'sys_mutex_lock' failed with 0x80010008 : CELL_EDEADLK [3]

and then after that, it keep repeating this endlessly: 

U {PPU[0x1000017] Thread (NexusRevolution Main) [0x01d55654]} sceNp TODO: sceNpManagerGetNpId(npId=*0xd0378864)
U {PPU[0x1000017] Thread (NexusRevolution Main) [0x00e123ec]} sceNp TODO: sceNpManagerGetOnlineName(onlineName=*0xd0378888)
U {PPU[0x1000017] Thread (NexusRevolution Main) [0x00e123fc]} sceNp TODO: sceNpManagerGetAvatarUrl(avatarUrl=*0xd03788bc)

as I said, i'm not programmer and don't know nothing about it, maybe this is related or not.

**Comment by kd-11** [comment] 2018-05-24 09:52
sceNp* spam is harmless.
Easiest way to isolate this is to just start the tutorial and kill the first enemy (the one who does not attack). When his death animation completes and ragdoll physics should start, the system will lock up almost instantly.

**Comment by NTZ1989** [comment] 2018-05-24 19:01
@kd-11 Hello!  
Yes, these hangs happened with my too, mainly after killing the first enemy during the tutorial, but using custom settings I can't avoid this... I did a record, where I prove that changing somes settings it is completely avoidable and you can play it without to hang, just some infinite loading screen, I used the lastest version available 6844 though I couldn't go further on it, I tested with older builds where I could go until Nexus and there I algo get stuck on an infinite loading screen. 

Here is the video's link, I credited it putting your official midias (Twitter, Patreon, Official Site, Youtube and said about what the project is...) My intention isn't to promote myself just to provide more info about the issue:

https://youtu.be/3nwAgsyzJVU

**00:00 - 02:45**  1st attempting - Using the standard settings, I could go a little bit further from the mentioned spot but it hanged. 

**02:46 - 04:47**  2nd attempting - Using the same settings as the 1st test, just to see if it hangs again, it did exactly on the same spot. 

**04:48 - 05:04**  I applied somes custom settings.

**05:05 - 08:32**  I play it without to hang, I went further from the mentioned spot...

**08:33 - 10:18**  The inifinite loading screen that I'm saying, I just waited almost 2 minutes to don't make the video too long but I could've waited 10, 20 minutes and still get stuck on this screen. On older builds I could pass through it, finish the tutorial and reaching on Nexus, where I can't travel to Boletarian, I got stuck on it again.

**Comment by IbanPetrov** [comment] 2018-05-25 02:49
"Loading precompiled shaders from disk" **build**6718 (**638** loading pipeline object) => **build**6750 (**392** lpo, ~61%) [video](https://streamable.com/t29cq)
PS: build6733 (pr4505) **F {PPU[0x1000000] Thread (main_thread)} class std::runtime_error thrown: Verification failed (e=0xb7) (0):
(in file Emu\Cell\SPUASMJITRecompiler.cpp:2753)**

**Comment by money123451** [comment] 2018-05-25 16:11
Ctrl + F "SPUASMJITRecompiler" match 2 of now 4 is my other comment about how to fix that also you can go back another build if you want.

**Comment by captainstarpaw** [comment] 2018-05-30 17:48
Thanks for posting a video example @NTZ1989 The lockup at 2:46 is exactly what I am experiencing too, using the latest build.

**Comment by tommis15** [comment] 2018-06-12 03:09
Still facing the freezing issue after killing first few NPCs in tutorial, is this fixed for anyone?

**Comment by AniLeo** [comment] 2018-06-12 03:56
It's still an issue yes

**Comment by tommis15** [comment] 2018-06-12 03:57
Ok, thanks for the heads up.

I don't know if this would help, but I'm seeing the following in the log:

E {PPU[0x1000013] Thread (_cellsurMixerMain) [0x0154844c]} Stat: '_sys_lwmutex_lock' failed with 0x80010005 : CELL_ESRCH [x390044]
E {PPU[0x1000013] Thread (_cellsurMixerMain) [0x0154844c]} Stat: 'sys_mutex_lock' failed with 0x80010008 : CELL_EDEADLK [x97504]
E {PPU[0x1000011] Thread (_sys_MixerChStripMain) [0x0154cb2c]} Stat: '_sys_lwmutex_lock' failed with 0x80010005 : CELL_ESRCH [x780088]

**Comment by Sekanato** [comment] 2018-06-14 13:09
Me too. Hangs on any character contact with the ragdoll'ed enemy body.
Build v0.0.5-6936-09c816223
XPS15 9560
Win10 Pro 1803
i7-7700HQ
8GB RAM
GTX 1050 4gb

Does not hang on RPCS3 v0.0.5-6675-bd1d4de42 But the soldier shield does not render there :smile:

**Comment by munderwoods** [comment] 2018-06-15 22:20
Same issue on i7-3770

**Comment by M0rt41** [comment] 2018-06-16 23:46
Exactly the same issue here, sucha shame since this game runs really well on this build FPS wise.
Anyone has any ideas for a workaround ?

**Comment by munderwoods** [comment] 2018-06-17 00:35
Sure, just use the last build that worked.
https://obk.ee/rpcs3/archive/rpcs3-v0.0.5-6697-753d8170_win64.7z

**Comment by psennermann** [comment] 2018-06-18 15:24
Last working is 6718, not 6697...

P.S. having absolutely no knowledge at all, anyone knows if it would be possible to build (locally) the new code (latest revisions) without PR #4553 ?

**Comment by tommis15** [comment] 2018-06-18 17:59
@Sekanato You just made me realize that it was freezing when it came into contact with ragdoll. Was curious so I tested it.

![ragdoll_freeze](https://user-images.githubusercontent.com/40190153/41553416-c2f83d96-72ff-11e8-8def-5b26157a4717.PNG)

**Comment by munderwoods** [comment] 2018-06-18 19:41
@psennermann I know that would seem to make sense, but I tried 6718 and it still crashed in the same way.

**Comment by M0rt41** [comment] 2018-06-18 19:44
I have tried 6697 it works but the game runs much better on the current version (well except for the crashing obviously :P)

**Comment by isshininu** [comment] 2018-06-18 20:01
Big ragdoll problem.
I just tried to reproduce this problem on new savefile.
Log attached . Game stops after killing and `ragdollising`.
[RPCS3.log.gz](https://github.com/RPCS3/rpcs3/files/2112801/RPCS3.log.gz)

**Comment by Sekanato** [comment] 2018-06-19 13:14
@tommis15 You're welcome :wink: 
At first I also thought, that it freezes on any kill after souls counter goes up, but after I've killed the first enemy and it didn't freeze but did after killing the second one, I got that the game freezes only on character-ragdoll interaction for me.
Sounds like a "fun souls challenge" to play through the whole game without touching the corpses of your enemies :laughing:

**Comment by money123451** [comment] 2018-06-19 15:52
well ... its any havoc object I bet (rolling into things that break also locks it up) so just avoiding the corpses would not really make this issue go away.

**Comment by munderwoods** [comment] 2018-06-19 20:12
Pretty sure it also hangs at the load screens. It definitely was for me, so I think that will make your challenge unwinable @Sekanato

**Comment by Sekanato** [comment] 2018-06-20 09:15
@money123451 @munderwoods Well, yeah. That's a shame.

**Comment by luka1498** [comment] 2018-06-21 03:47
![image](https://user-images.githubusercontent.com/25275368/41696845-8a33cb62-74ec-11e8-8424-505f45123311.png)
Got the exactly same freeze, as @Sekanato said, freeze when in contact with ragdolls

**Comment by JackWesleyNelson** [comment] 2018-06-21 04:42
![demon s souls freeze enemy roll v0 0 5-6976 alpha](https://user-images.githubusercontent.com/8739573/41698305-d1ec1f98-74da-11e8-885a-e25f0044a977.PNG)
The freeze also occurs when enemies roll, as can be seen in this screenshot. Not sure if it has the same cause as the ragdoll freeze.

**Comment by Yessos** [comment] 2018-06-23 16:32
I can confirm that switching from LLVM Recompiler to Interpreter does nothing - it still freezes on ragdoll interaction.

**Comment by tommis15** [comment] 2018-07-06 18:21
On the latest master I am no longer having the issue with freezing on ragdoll interaction.

**Comment by psennermann** [comment] 2018-07-06 18:38
Am I the only one who gets constant crashes/stuck screen when loading Demon's Soul with rpcs3 0.0.5-7069 (I can't even get in-game - no TSX CPU)?

**Comment by tommis15** [comment] 2018-07-06 18:41
@psennermann You tried a clean install of RPCS3?

**Comment by isshininu** [comment] 2018-07-06 18:58
For everyone experiencing stuck on RPCS3 7069: go to dev_hdd1/cache and clear content of this folder completely. After this run game again, it should no more freeze.

**Comment by psennermann** [comment] 2018-07-06 19:08
Yes, I tried a clean install...

**Comment by psennermann** [comment] 2018-07-06 19:11
But I don't think the issue lies in last PR 7069, because with the older PR "[No Merge] praise miyazaki" I had the same problem...

**Comment by kd-11** [comment] 2018-07-07 13:39
You need to clear your SPU cache as well

**Comment by Parthorisian** [comment] 2018-07-07 14:36
Wow, it really works [ragdoll interaction](https://i.imgur.com/XJzPJSG.png)+allows load any savegames unavailable before! Praise Nekotekina!

**Comment by kd-11** [comment] 2018-07-07 15:20
Closing as fixed

**Closed by kd-11** 2018-07-07 15:20 UTC
Labels: Regression

**Comment by YaPeL** [comment] 2018-07-07 19:46
I still have the issue, clean install and all, non TSX cpu, I attached the log to the other issue

**Comment by GoaLitiuM** [comment] 2018-07-19 12:18
The game still freezes with LLVM Recompiler as SPU Decoder, but sometimes it recovers after waiting a while after the freezing occurs. With ASMJIT the issue seems to be gone. For the reference, I also have a non-TSX capable CPU (i7-2600k).

**Comment by Asinin3** [comment] 2018-07-20 06:03
SPU LLVM is experimental, it says it right there next to the name.. No need to report issues like "it freezes" or "graphics missing" only spu logs etc will be useful at this stage.

**Comment by Fashish** [comment] 2018-07-21 10:40
Same issue as @psennermann, the game freezes before even getting to the main menu. I've tried everything suggested in this thread to no avail. Using the latest 7111 build.

**Comment by Sladern** [comment] 2018-07-30 03:36
how do i download old builds? can someone get me a link please?

**Comment by psennermann** [comment] 2018-09-03 15:33
on my system Demon's Soul still hangs no matter what options you choose (LLVM included)

**Comment by al0xf** [comment] 2018-09-24 20:17
Delete the dev_hdd1 (one) and data folders to clear all caches and try again first with SPU ASMJIT and then with SPU LLVM with safe block size.

**Comment by isshininu** [comment] 2018-09-24 20:32
> Delete the dev_hdd1 (one) and data folders to clear all caches and try again first with SPU ASMJIT and then with SPU LLVM with safe block size.

will not help.

He is talking about another DeS bug on 4 core/4 threads CPUs. as described here: https://github.com/RPCS3/rpcs3/issues/4861

**Comment by captainstarpaw** [comment] 2018-09-24 21:38
RPCS3 0.0.5-7377-b7e010bb Alpha

i7-8700K CPU
GeForce 980 Ti GPU
16 GB DDR4

PPU: LLVM, SPU: LLVM, 1 SPU thread, safe SPU block size, TSX Enabled.

All fine here, cleared out cache and I've played through the first three boss fights no issues.
