### ISSUE TITLE
Windows Taskbar Restart

### ISSUE THREAD

**Issue by Darkhost1999** [RPCS3/rpcs3#13709] opened 2023-04-19 19:49 UTC
### Quick summary

Pressing restart on windows Taskbar fails to load a custom config or at least all the settings

### Details

I tested with Netflix while I am editing custom icons and loading screens.
I clicked restart and network fails to say connected despite custom config says it is.
I've observed this behavior before I just didn't want to report it.

### Attach a log file

[RPCS3.log.gz](https://github.com/RPCS3/rpcs3/files/11276963/RPCS3.log.gz)

### Attach capture files for visual issues

NA

### System configuration

Ryzen 5 3600
gtx 1660 Super
Win11 pro

### Other details

Testing games and stuff I don't believe that all settings fail to load idk how many succeeded or fail.
But network fails when it shouldn't.

**Comment by Megamouse** [comment] 2023-04-23 17:55
cannot reproduce

**Comment by Megamouse** [comment] 2023-04-23 17:58
Also, does it not happen with the other buttons?

**Comment by Darkhost1999** [comment] 2023-04-23 18:12
It doesn't happen with other buttons.
Because the toolbar requires to press stop before restart. The taskbar button just allows restart without stopping.
The configs are fine if you actually stop before restarting even from Taskbar.
And not all settings are effected by the same behavior.

**Comment by Darkhost1999** [comment] 2023-05-06 20:20
I see what's happening;
I boot eboot.bin. The eboot boots rigel_loader_dll.self using my config from continuous mode. But after using Windows Taskbar restart it boots rigel_loader_dll.self but not in continuous mode so a custom config isn't found.
[RPCS3.log](https://github.com/RPCS3/rpcs3/files/11413313/RPCS3.log)
When I press stop on the windows taskbar and use windows taskbar to restart I get an E SYS: Restart failed:  Failed to decrypt SELF: C:/Games/RPCS3/dev_hdd0/game/NPUP00030/USRDIR/rigel_loader_dll.self.
[RPCS3.log](https://github.com/RPCS3/rpcs3/files/11413317/RPCS3.log)
Meanwhile, the restart button on the toolbar requires stop to be pressed before restart even shows up and restart from the toolbar uses continuous mode correctly booting rigel_loader_dll.self without an issue.
[RPCS3.log](https://github.com/RPCS3/rpcs3/files/11413319/RPCS3.log)

So it can be seen there are 2 issues here
1. Windows Taskbar restart doesn't use continuous mode correctly
2. Windows Taskbar restart doesn't have boot parity to Toolbar restart (also probably caused by lack of continuous mode}

**Comment by Megamouse** [comment] 2023-05-06 20:25
There is no toolbar "restart". All it does is boot the game you booted last.

You will probably have the same issue in the menu item topleft though

**Comment by Darkhost1999** [comment] 2023-05-06 20:28
K, Well it's rebooting update files and not just games. But yea the more I look at this it's working as it was designed. Cause of the boot order and everything.

**Comment by elad335** [comment] 2023-07-08 16:04
Still an issue?

**Comment by Darkhost1999** [comment] 2023-07-08 16:45
> Still an issue?

![image](https://github.com/RPCS3/rpcs3/assets/60384196/6e191181-6845-432d-a76a-b02104539032)
[RPCS3.log.gz](https://github.com/RPCS3/rpcs3/files/11991303/RPCS3.log.gz)
Yes it is. Because custom configs in continuous mode only applies to eboot.bin files and not .self files. Or the windows taskbar restart button is rebooting the .self file and not the eboot.bin when it needs to restart the eboot.bin. The toolbar doesn't present this problem by simply Not displaying the restart button until stop is made then when clicking restart rebooting the eboot.bin.
Meanwhile pressing stop on the taskbar and restart on the taskbar boots the last .self file.
The config should be checked for changes during the restart and before reboot. But because it's booting the .self file being restarted it isn't pointing to the custom config created for the eboot

**Comment by Megamouse** [comment] 2023-07-08 16:45
it's a "Emu.Restart()" bug.

**Comment by elad335** [comment] 2023-07-25 09:14
Retest with latest master.

**Comment by Darkhost1999** [comment] 2023-07-25 10:38
[RPCS3.log](https://github.com/RPCS3/rpcs3/files/12159892/RPCS3.log)
E SELF: Failed to decrypt SELF metadata info!
E SELF: Failed to load SELF file metadata!
E SYS: Failed to decrypt SELF: C:/Games/RPCS3/dev_hdd0/game/NPUP00030/USRDIR/rigel_loader_dll.self
E SYS: Restart failed: Failed to decrypt content 
Now it just restarts to these messages.
However, looking at the log. The reported issue is resolved and my config is loaded.
·! 0:01:02.718251 VFS: Mounted path "/app_home" to "C:/Games/RPCS3/dev_hdd0/game/NPUP00030/USRDIR/"
![image](https://github.com/RPCS3/rpcs3/assets/60384196/16a9c658-c3a4-4ffe-9d3d-376eb9c9b538)
Would be nice to restart to the eboot.bin then let the .self load naturally.

**Comment by Megamouse** [comment] 2023-08-12 14:53
Since the original bug seems fixed, I'll close this issue

**Closed by Megamouse** 2023-08-12 14:53 UTC
Labels: GUI, OS: Windows
