### ISSUE TITLE
Dragon Quest Builders [BLJM61311] Unplayable Due To Texture Buffer Overload

### ISSUE THREAD

**Issue by bronsonabc** [RPCS3/rpcs3#6756] opened 2019-10-12 16:22 UTC
Version - RPCS3 v0.0.7-8855-9242f165 Alpha | HEAD | Firmware version: 4.84
Game - Dragon Quest Builders [BLJM61311]

Error Message - F {RSX [0x009a744]} RSX: class std::runtime_error thrown: [texture upload buffer] Working buffer not big enough, buffer_length=268435456 allocated=251657728 requested=16777224 guard=33554432 largest_pool=16777728
(in file C:\projects\rpcs3\rpcs3\Emu\RSX\Common\ring_buffer_helper.h:80)

The issue seems to be hard to replicate for people, it happens to me on every boot I can barely get the game to play for more than 2 minutes now. The issue has slowely gotten worse and I think it has something to do with a file wanting to be loaded but the file has gotten too big for the emulator and it causes an error. When I get this issue the game will hard lock and no longer be playable. Issue started by happening randomly and slowly over time the issue gets worse, I am at the point now where I load in and the game locks up upon entering the world with the same error everytime. 

(Older versions run the game fine, found a post of someone saying they could play it in version 6.6 or something like that)

Thanks, first time posting here I hope I did it properly.

**Comment by 13xforever** [comment] 2019-10-12 16:38
duplicate of #6417

**Comment by kd-11** [comment] 2019-10-12 18:09
Closing as duplicate

**Closed by kd-11** 2019-10-12 18:09 UTC
