### ISSUE TITLE
RPCS3 performance regression since PR#6507

### ISSUE THREAD

**Issue by Lenox548** [RPCS3/rpcs3#7007] opened 2019-11-18 01:10 UTC
Since the the build 0.0.7-8709 or the PR #6507  there has been happening a issue in which if you're in the rpcs3 window the game lags horribly, but if go to another window and look over the rpcs3 window with the mouse, the performance goes back to normal, later, on PR #6543 the issue was kinda fixed, but it kept happening to a lesser extent, then, in PR #6602 that issue started happening again, and since then, even in the latest build 0.0.7-9145, that issue is still present. The last build that worked fine for me was the build 0.0.7-8677 or the PR #6522  (due to I've been disconnected from the rpcs3 scene for a while, I don't know if this issue was solved on another more recently build and regressed again), back then when i opened #6536 I thought that it only was a Persona 5 thing, but now that i've been testing, I realized that this issue affects all the games that I have (Persona 5, JJBA: All Star Battle and Demon's Souls)

My pc specs:
i3-8100 3.60GHz
RX-570 8gb driver ver. 19.11.2
16gb ram

JJBA All Star Battle:
![screenshot1](https://user-images.githubusercontent.com/54904556/69017191-29cf3580-0984-11ea-998f-c8634dccc141.jpg)
![screenshot2](https://user-images.githubusercontent.com/54904556/69017193-2cca2600-0984-11ea-88e0-4c246729dd3a.jpg)

Persona 5:
![screenshot3](https://user-images.githubusercontent.com/54904556/69017209-453a4080-0984-11ea-943d-d74b9b515d1a.jpg)
![screenshot4](https://user-images.githubusercontent.com/54904556/69017213-48353100-0984-11ea-935b-848231451400.jpg)

Demon's Souls:
![screenshot5](https://user-images.githubusercontent.com/54904556/69017249-79adfc80-0984-11ea-9ba4-43be4736964d.jpg)
![screenshot6](https://user-images.githubusercontent.com/54904556/69017252-7ca8ed00-0984-11ea-8ec5-cfdfb7985e97.jpg)

[JJBA All Star Battle log build 0.0.7-9145.gz](https://github.com/RPCS3/rpcs3/files/3856469/JJBA.All.Star.Battle.log.build.0.0.7-9145.gz)
[JJBA All Star Battle log build 0.0.7-8677.gz](https://github.com/RPCS3/rpcs3/files/3856473/JJBA.All.Star.Battle.log.build.0.0.7-8677.gz)
[Persona 5 log  build 0.0.7-9145.gz](https://github.com/RPCS3/rpcs3/files/3856475/Persona.5.log.build.0.0.7-9145.gz)
[Persona 5 log  build 0.0.7-8677.gz](https://github.com/RPCS3/rpcs3/files/3856482/Persona.5.log.build.0.0.7-8677.gz)
[Demon's Souls log  build 0.0.7-9145.gz](https://github.com/RPCS3/rpcs3/files/3856484/Demon.s.Souls.log.build.0.0.7-9145.gz)
[Demon's Souls log  build 0.0.7-8677.gz](https://github.com/RPCS3/rpcs3/files/3856490/Demon.s.Souls.log.build.0.0.7-8677.gz)

**Comment by Lenox548** [comment] 2019-11-28 20:12
Welp, i recently upgraded my cpu to an i5 9400f and the issue got "fixed", probably because the i5 has 6 threads and 6 cores, unlike the i3 8100, which only has 4 threads and 4 cores

**Comment by Lenox548** [comment] 2019-12-14 23:59
I retested in the latest build 0.0.7-9226 and the issue is back, I don't know which version in between the one i tested 16 days ago has make the issue happen again

**Comment by Yahfz** [comment] 2020-01-09 01:30
@Lenox548 Can you narrow it down? Because at this point this sounds like user error.

**Comment by Lenox548** [comment] 2020-01-12 17:46
What do you mean? some months ago plenty of people were reporting the same issue, i don't think it is an user error

**Comment by Yahfz** [comment] 2020-01-12 17:48
> @Yahfz What do you mean? some months ago plenty of people were reporting the same issue, i don't think it is an user error

what i mean is, can you test and find which build made the performance worse? You said the issue is back and reopened it but didn’t really give any info on how to reproduce.

**Comment by Lenox548** [comment] 2020-01-12 17:49
Right now the issue is kinda fixed, now the perfomance is perfect while in windowed mode, but when i go to full screen it gets kinda laggy

**Comment by Lenox548** [comment] 2020-01-12 17:52
> what i mean is, can you test and find which build made the performance worse? You said the issue is back and reopened it but didn’t really give any info on how to reproduce.

I've given all the info to reproduce the issue in the first comment of the thread

**Comment by Yahfz** [comment] 2020-01-12 17:54
by how to reproduce i mean which build exactly broke it again.

**Comment by Lenox548** [comment] 2020-01-12 19:28
@Yahfz Well, i've tested nearly 30 builds and it seems that the issue got fixed again in the build 0.0.7-9276 or the PR #7150 and it kept like that until the build 0.0.8-9311 or PR #7183 where it started to happen another weird issue

> Right now the issue is kinda fixed, now the perfomance is perfect while in windowed mode, but when i go to full screen it gets kinda laggy

This one more specifically, and in addition to that the fps started to behave weird, like it says that the game is running at 90-120 fps, when the game is locked to 30 fps by default and it's clearly laggy

**Comment by BuIlDaLiBlE** [comment] 2020-01-24 21:11
Can confirm happens for all games in all 0.0.8 builds. Old 0.0.5 or 0.0.6 builds didn't do this for sure. My CPU is i5-7400.

**Comment by OlderedJohnStalvern** [comment] 2020-02-05 23:47
Can confirm this on 0.0.8-9508-049e392a, also could reproduce your fps issue(https://github.com/RPCS3/rpcs3/issues/7007#issuecomment-573448607 ):

1. Start Demon's Souls.
2. Go fullscreen > ALT+TAB to return to the rpcs3 screen > "Change Custom Configuration" > (change any setting) > "Save Custom Configuration", return to game, ALT+F4
3. Restart the game without restarting rpcs3, now it unlocks the FPS(not internally, only repeats frames) and Demon's Souls runs with way less stutter and loads shaders way faster

Video reproducing both issues, you can see on 3:40 the difference between rpcs3 running on front(massive lag) and running on background(full speed even when destroying furniture/moving ragdoll):

https://streamable.com/8ua78

The fps unlock issue disappears when you restart rpcs3. 
The foreground issue is partially fixed by setting rpcs3 on low cpu priority, but the performance boost by running on background is still noticeable.

Default settings except for: 300% resolution, INTRO LOGO SKIP patch, disabled "Enable SPU loop detection", enabled "Lower SPU thread priority".

**Comment by elad335** [comment] 2020-10-26 06:49
Waitable atomics perf improved quite a bit recently.. I doubt that this is still an issue.
Will reopen if someone encounters this problem.

**Closed by elad335** 2020-10-26 06:49 UTC
