### ISSUE TITLE
Demon Souls (BLES00932) Visual Bugs

### ISSUE THREAD

**Issue by LightHazel** [RPCS3/rpcs3#5059] opened 2018-08-30 16:32 UTC
My Computer 
~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
OS : Microsoft Windows 10
CPU : Intel(R) Core(TM) i78550U CPU @ 1.80GHz (8 CPUs), ~2,0GHz
GPU : Intel(R) UHD Graphics Family 
~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
My Settings 
~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
CPU=
 PPU Decoder : LLVM Recompiler 
SPU Decoder : ASMJIT Recompiler 
Firmwere Settings : Load liblv2.sprx only
Additional Settings : Enable thread scheduler , Lower SPU thread priority , Enable SPU loop Detection , SPU Cache 
Preferred SPU thread : Auto
 SPU Block size : Mega


GPU=
Renderer : OpenGL
Anisotropic : Force Disable
Additional Settings : Write Colour Buffers , Use GPU Texture Scaling 
~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
![screenshot 4](https://user-images.githubusercontent.com/42841287/44860689-8232ee00-ac7f-11e8-9164-9ccedfd9d3b9.png)

![screenshot 3](https://user-images.githubusercontent.com/42841287/44860701-8a8b2900-ac7f-11e8-802e-a2e21535162e.png)

 Every Time I Open The Game The Launcher Marks These Text In Orange And Red,These Are the Texts
~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
Orange~
 U {PPU[0x1000000] Thread (main_thread) [0x01df7d80]} sys_spu TODO: Unimplemented SPU Thread options (0x2) x5

U {PPU[0x1000000] Thread (main_thread) [0x01dfde58]} sys_prx TODO: _sys_prx_get_module_id_by_name(name=“cellLibprof”, flags=0, pOpt=*0x0)

U {PPU[0x1000000] Thread (main_thread) [0x01d5029c]} cellUserInfo TODO: cellUserInfoGetList(listNum=*0xd0100854, listBuf=*0xd01008a8, currentUserId=*0x1b94b58)

U {PPU[0x1000000] Thread (main_thread) [0x01d503a0]} sys_prx TODO: _sys_prx_unload_module(id=0x2304bb00, flags=0x0, pOpt=*0x0)

U {PPU[0x1000005] Thread (HighGraphics) [0x00acb924]} cellSysutil TODO: cellVideoOutConfigure(videoOut=0, config=*0xd0170a00, option=*0x0, waitForEvent=0)

U {PPU[0x1000000] Thread (main_thread) [0x01d53d8c]} HLE TODO: Unimplemented syscall sys_ss_access_control_engine -> CELL_OK  

U {PPU[0x1000000] Thread (main_thread) [0x00e6bbfc]} sceNp2 TODO: sceNpMatching2Init(poolsize=0x0, priority=0)

Red ~
 
E {PPU[0x1000000] Thread (main_thread) [0x01dfde58]} 'sys_prx_get_module_id_by_name' failed with 0x8001112e : CELL_PRX_ERROR_UNKNOWN_MODULE [1]

E {rsx::thread} RSX: OpenGL: initialization of glDepthBoundsEXT failed.

E {rsx::thread} RSX: OpenGL: initialization of glTextureBarrierNV failed.

E {rsx::thread} RSX: NV3089_IMAGE_IN_SIZE: Invalid blit dimensions passed

E {PPU[0x1000000] Thread (main_thread) [0x01543ce8]} 'sys_mutex_lock' failed with 0x80010008 : CELL_EDEADLK [1]

**Comment by AniLeo** [comment] 2018-08-30 16:33
Retest with default settings, not with random ones you pick

**Comment by Asinin3** [comment] 2018-08-30 16:39
As ani said, however remember to use Write Color Buffers. You have anisotropic filtering forced to disable which you should never do. It means rpcs3 wont let the game use its own texture filtering, use automatic. Mega/Giga block size is another setting that can cause compatibility issues too.

**Comment by LightHazel** [comment] 2018-08-30 16:49
i tried the default settings ,but the problem is still present

**Comment by AniLeo** [comment] 2018-08-30 16:51
Upload a log file. This looks like an Intel Driver issue.

**Comment by LightHazel** [comment] 2018-08-30 17:29
Problem Fixed , i just switched to vulkan... thank you all for your help

**Comment by AniLeo** [comment] 2018-08-30 17:29
That's not fixing a problem, the problem is with OpenGL..

**Comment by AniLeo** [comment] 2018-09-05 14:06
Since it's an Intel Driver issue and user seems to have used tracker for pure leeching and is not interested in providing further information to the issue, I'm closing the issue.

**Closed by AniLeo** 2018-09-05 14:06 UTC
Labels: Driver: Intel, Need Information
