### ISSUE TITLE
Gran Turismo 6 desync/freeze NPUA81049

### ISSUE THREAD

**Issue by mashakos** [RPCS3/rpcs3#13279] opened 2023-01-23 05:38 UTC
### Quick summary

Gam desyncs frequently on latest release vs. releases from 0.0.25 or earlier

### Details

During a race, game freezes with particles/smoke looping in place. The log has a series of repeating `RSX: FP not found in buffer!` and `RSX: BRK opcode found outside of a loop` entries

### Attach a log file

[RPCS3.log.gz](https://github.com/RPCS3/rpcs3/files/10476998/RPCS3.log.gz)

### System configuration

- SYS: RPCS3 v0.0.26-14600-53cc067c Alpha | master
- SYS: Intel(R) Core(TM) i9-9900K CPU @ 3.60GHz | 16 Threads | 31.86 GiB RAM | TSC: 3.600GHz | AVX+ | FMA3 | TSX
- SYS: Operating system: Windows, Major: 10, Minor: 0, Build: 19044, Service Pack: none, Compatibility mode: 0
- RSX: Found vulkan-compatible GPU: 'NVIDIA GeForce GTX TITAN X' running on driver 528.2.0.0
- SYS: Firmware version: 4.87

**Comment by RainbowCookie32** [comment] 2023-01-23 05:42
Duplicate of #10882

**Closed** 2023-01-23 06:03 UTC

**Comment by Kwangnofx** [comment] 2023-04-11 20:29
![image](https://user-images.githubusercontent.com/119879648/231280474-b486223e-a23f-47a8-b557-7c5b8e445cc6.png)![image](https://user-images.githubusercontent.com/119879648/231280504-94a66459-3ded-4533-98b8-95b3ebfdf169.png)![image](https://user-images.githubusercontent.com/119879648/231280535-37775a97-b6e5-4fe5-9a47-d327dc621517.png)![image](https://user-images.githubusercontent.com/119879648/231280559-898f554f-d3d6-4ee8-9883-ce51ce4a344a.png)

Try these setting with update 1.05 max on current master build , its freeze only one time sometime at first lanch but never freeze again 
Work with these setting 36 hours with no crash on 10900k and rtx 3090

**Comment by steven88ita** [comment] 2023-04-15 12:55
on my pc (ryzen 4) gt5 is playing fine without hangs or crash but I had to disable smt (hyperthreading) and set just on 4 cores in the bios. Audio still stutter and stop after a while though. Have yet to test gt6

**Comment by steven88ita** [comment] 2023-04-15 13:19
on my pc (ryzen 4) gt5 is playing without hangs or crash but I had to disable smt (hyperthreading) and to set 2 cores in the bios, so emulation is very slow, audio still stutters. Have yet to test gt6

**Comment by steven88ita** [comment] 2023-04-15 16:12
>
> Try these setting with update 1.05 max on current master build , its freeze only one time sometime at first lanch but never freeze again Work with these setting 36 hours with no crash on 10900k and rtx 3090

These settings are not the best as the game is hell slow and stuttering. I tried reducing the active cores to 4 and the game desycn/freeze a bit less, ever lesser on 2 cores, please some developer can have a try?

**Comment by Kwangnofx** [comment] 2023-04-15 19:12
> >
> 
> > Try these setting with update 1.05 max on current master build , its freeze only one time sometime at first lanch but never freeze again Work with these setting 36 hours with no crash on 10900k and rtx 3090
> 
> 
> 
> These settings are not the best as the game is hell slow and stuttering. I tried reducing the active cores to 4 and the game desycn/freeze a bit less, ever lesser on 2 cores, please some developer can have a try?
> 
> 
> 
> 
Try hoholee12 build on slow performance pc 

https://github.com/hoholee12/rpcs3-custom/releases/tag/v7
