### ISSUE TITLE
Regression after 6763 and later (0.0.7-8888) - Games from Windows share directories cant be no more loaded.

### ISSUE THREAD

**Issue by ruthan** [RPCS3/rpcs3#6854] opened 2019-10-23 19:14 UTC
Hello,
it worked for years, but stopped 10 days ago, i tested one version by other and it seems that it stopped working with 6763 PR.. 

  In log is just this, i tested lots of games:
E Boot failed: //10.0.0.15/!nas/GamesDumps/!ConsolesISOs/Playstation3/Fallout 3/BLUS30185/PS3_GAME/USRDIR/EBOOT.BIN

 Game even fail to add to RPCS games list at the emulator start, digital version of games installed on emulator HDD are working.

 I long is only this:
RPCS3 v0.0.7-8888-076a80d7 Alpha | HEAD | Firmware version: 4.81
Intel(R) Core(TM) i7-4770S CPU @ 3.10GHz | 8 Threads | 31.95 GiB RAM | TSC: Bad | AVX+
Operating system: Windows, Major: 10, Minor: 0, Build: 18362, Service Pack: none, Compatibility mode: 0
·! 0:00:00.000000 RSX: Found vulkan-compatible GPU: 'GeForce GTX 970' running on driver 436.2.0.0
·! 0:00:00.526483 Compatibility notice: { Finished reading database from file: D:/Games/!Emulators/PS3 - Rpcs3/GuiConfigs/compat_database.dat }
·W 0:00:00.731469 Could not load image from path D:/Games/!Emulators/PS3 - Rpcs3/dev_hdd0/game/_GDATA_1920210986100/ICON0.PNG
·! 0:03:00.391697 LDR: Booting from BootElf...
·E 0:03:00.391843 Boot failed: //10.0.0.15/!nas/GamesDumps/!ConsolesISOs/Playstation3/Fallout 3/BLUS30185/PS3_GAME/USRDIR/EBOOT.BIN
·W 0:03:00.478917 Could not load image from path D:/Games/!Emulators/PS3 - Rpcs3/dev_hdd0/game/_GDATA_1920210986100/ICON0.PNG

I dunno what first _GDATA_1920210986100/ICON0.PNG means, games list i now empty..

 0.0.7-8886 - is last fine version.

**Comment by RainbowCookie32** [comment] 2019-10-23 19:16
Probably related to, or the same issue as #6841

**Comment by Nekotekina** [comment] 2019-10-27 15:54
Try https://github.com/RPCS3/rpcs3/pull/6903

**Comment by RainbowCookie32** [comment] 2019-11-14 01:12
Is this still an issue? You mentioned on #6903 that the games are now loading again. If that's the case, please close the issue, since the regression was fixed

**Comment by AniLeo** [comment] 2020-01-08 21:31
Closing as fixed

**Closed by AniLeo** 2020-01-08 21:31 UTC

**Comment by ruthan** [comment] 2020-12-30 11:38
Bug is back.. i cant yet point it to exact version, but month back its working and in last week it does not.
