### ISSUE TITLE
Macross 30 - Regression detected: All textures blue tinted except HUD

### ISSUE THREAD

**Issue by santasemilla** [RPCS3/rpcs3#8075] opened 2020-04-21 15:21 UTC
## Quick summary
By December ‘19 the game was pretty full playable! (RPCS3 0.0.8-9456). Then, as revisions followed, the game kept loading and getting into game BUT! it’s like all textures on 3D objects are now blue. After trial and error, I found the version where this issue started to happen. That is: **v0.0.8-9487-7d2ed920 (or better #7353)**. I'm running the emulator under Linux (KUbuntu 18.04) couldn't test under Windows to see if the problem is also there. Up today the problem is still present.

## Details
Please provide as much detail as you can here, including
- Expected behavior vs Emulator (current version): Please see images below
![image](https://user-images.githubusercontent.com/64089021/79879982-c9767100-83c5-11ea-9152-f80a4ae92778.png)

![image](https://user-images.githubusercontent.com/64089021/79880055-e14df500-83c5-11ea-951c-5341b0e304e7.png)
  
It is worth mentioning that the intro, loading, and in game seems to work with no problem. This bug seems a graphics problem only.

- full logs (not from UI)
Log from UI: https://pastebin.com/RdWP8M59
RPCS3.log file attached but seems outdated, I cannot tell if it has relevant info. That's why I'm also adding the UI log from a quick run of the game. 
Additionally, I'm attaching my config.yml file here: https://pastebin.com/uPRz8bU1

Please let me know what else should I add.

- System Configuration:
Kubuntu 18.04
intel core i7 @2.4GHz (notebook)
16GB RAM
Nvidia GTX 1060 (current driver 440.82, tested also with 435.xx versions)

Thank you very much!! Hope this info would help to solve issues in this great game!

[RPCS3.zip](https://github.com/RPCS3/rpcs3/files/4510889/RPCS3.zip)

**Comment by kd-11** [comment] 2020-04-21 17:12
Unfortunately this issue seems to be non-trivial. I'll take a look during next maintenance cycle.

**Comment by santasemilla** [comment] 2020-04-21 17:41
> Unfortunately this issue seems to be non-trivial. I'll take a look during next maintenance cycle.

No problem and thanks for you time! If anything is needed, just let me know.

**Comment by kd-11** [comment] 2020-07-15 15:44
I am unable to reproduce this, for some reason on RADV the image is just black. I reverted the PR mentioned in the report but nothing changed. Unfortunately this game does not run on windows so debugging is taking much longer than desired due to "just linux things" getting in the way.
@santasemilla Are you still able to get an image ingame?

**Comment by kd-11** [comment] 2020-07-15 16:13
Nvm, I figured it out. I had to disable async compiler to make sure shaders are all present when debugging. Regression confirmed.

**Comment by kd-11** [comment] 2020-07-15 18:47
Fixed by https://github.com/RPCS3/rpcs3/pull/8590. I'll wait for more user testing, the current solution is inelegant imo, but without major rewrites nothing can be done at the moment.

**Closed** 2020-07-16 16:11 UTC
Labels: In Progress, Regression

**Comment by kd-11** [comment] 2020-07-23 20:31
Looks like I messed up the commit and the important file VKGSRender.cpp had the changes lost during rebase. Fixup included in https://github.com/RPCS3/rpcs3/pull/8618
