### ISSUE TITLE
MGS 4 25th Anniversary ( problem install 11% 16 min long)  

### ISSUE THREAD

**Issue by stan0danny** [RPCS3/rpcs3#6478] opened 2019-09-03 11:32 UTC
![mgs4](https://user-images.githubusercontent.com/41484098/64169784-31883f00-ce57-11e9-93dc-cded46fe6492.PNG)

i saw play rpcs3 v0.0.7-8641 Alpha  MGS 4  install 11% ( 16 min ) long again  , i'm feel bored hours 6 ago , this not work 
my hp omen 17 gaming laptop spec : ram 32gb , nvidia gtx 1060 6gb , i7 8750h 
here--->
[RPCS3.log.gz](https://github.com/RPCS3/rpcs3/files/3569236/RPCS3.log.gz)

**Comment by AniLeo** [comment] 2019-09-03 12:12
Duplicate of #6457

**Closed by AniLeo** 2019-09-03 12:12 UTC

**Comment by stan0danny** [comment] 2019-09-03 13:17
oh sorry, I'm not know thank you :)
