### ISSUE TITLE
[Feature request] Analog limiter

### ISSUE THREAD

**Issue by Slickbait** [RPCS3/rpcs3#14690] opened 2023-09-29 16:24 UTC
### Quick summary

two binds to dictate the speed of either analog stick

### Details

a feature from PPSSPP and Dolphin which have us map a key to activate it, with the ability to control the value of how hard the stick is pushed (which can be adjusted) and would be quite good for games that rely on lightly pushing the stick to move slowly such as the MGS games (with MGS2 being an exception seeing as mapping the D-pad to WASD and using the pressure sensitivity toggle works) and TLOU (despite having a PC release)

**Comment by Slickbait** [comment] 2023-11-17 14:28
any updates? it's kind of a feature that I'm desperate for, though I can understand if there are more important things to work on as of right now

**Comment by Megamouse** [comment] 2023-11-22 18:54
Duplicate of #12453

**Closed by Megamouse** 2023-11-22 18:54 UTC
Labels: Input

**Comment by Alexbeav** [comment] 2024-08-09 19:38
Sorry to reopen this @Megamouse and thank you so much for your contributions, but this is not a duplicate of #12453 

While analog stick multipliers implemented in #8553 work for changing them once and then playing with them in-game, what the OP is asking (as well as me) is the ability to have a new shortcut added that toggles the stick multipliers between 2 positions i.e. 100% and 50% (selected by the user). Currently, if we want to change the values we have to do it every time in the pad settings.

This would allow i.e. in Assassin's Creed to toggle between run (100%) and walk (50%), same thing in MGS.

Thank you for considering this.

**Comment by Megamouse** [comment] 2024-08-09 19:43
Well then it's a duplicate, because it's exactly what the other issue is asking for.

**Comment by Slickbait** [comment] 2024-08-09 20:26
wonder if this is ever gonna be worked on, I understand if it's not very needed at the moment but it'd be pretty awesome, as I've been mind blown with how playable MGS4 is for example on KBM

**Comment by Slickbait** [comment] 2024-08-10 15:29
it's here but it's missing an actual percentage slider, am I doing something wrong?

**Comment by Megamouse** [comment] 2024-08-10 17:37
The analog limiter toggle affects the stick multipliers.
There wasn't much to gain by adding yet another parameter.

**Comment by Salk619** [comment] 2024-08-17 04:43
> it's here but it's missing an actual percentage slider, am I doing something wrong?
> 
> EDIT: quickly figured it out, my bad

plz let me know how you've done this. I have emulated MGS4 on my pc and want KB controls but can't figure out how to do the sneaking control.

**Comment by Megamouse** [comment] 2024-08-17 06:47
I've literally commented the solution directly below.

**Comment by Salk619** [comment] 2024-08-17 14:37
> I've literally commented the solution directly below.

my bad, I finally figured it out, I had to assign left stick multiplier to 0.5 and assigned a button Left Shift to analog limiter and it worked! Thanks again for your amazing contributions!
