### ISSUE TITLE
Buttons do not fit on the screen

### ISSUE THREAD

**Issue by Hallkezz** [RPCS3/rpcs3#9982] opened 2021-03-17 13:12 UTC
Bottom buttons in the Gamepad Settings window do not fit on the screen.

Screen Resolution: 1360x768

![image](https://user-images.githubusercontent.com/32846474/111472917-83dc3880-873b-11eb-8297-087740b3e797.png)

**Comment by Megamouse** [comment] 2021-03-17 16:23
Duplicate of #7420

You can resize the dialog anyway

**Closed by Megamouse** 2021-03-17 16:23 UTC
Labels: GUI
