### ISSUE TITLE
Wall-E [BLUS30151] Everything Rendered In Blue

### ISSUE THREAD

**Issue by SuperMitsaYouTube** [RPCS3/rpcs3#14102] opened 2023-06-26 22:10 UTC
### Quick summary

Almost Everything Except Hud Elements, Cutscenes, Menus And Small Textures Are Rendered In A Strong Blue Tint

### Details

(Tested On Both Vulkan And OpenGL) Used A Bunch Of Different Settings To Attempt To Fix
What It Should Look Like
![walleps3](https://github.com/RPCS3/rpcs3/assets/98070193/7b0bc3ee-fb55-4a47-be39-e71a17f0138a)

What It Looks Like In The Emulator
![Walleissueps3](https://github.com/RPCS3/rpcs3/assets/98070193/3addf048-a990-43d3-9baa-7d9d657eb25e)

### Attach a log file

[RPCS3.log](https://github.com/RPCS3/rpcs3/files/11875048/RPCS3.log)

### System configuration

CPU: Intel Core i7 9700
GPU: RTX 2080 Super

**Comment by YuriNator557** [comment] 2023-06-27 00:07
duplicate of #10530

**Closed** 2023-06-27 00:22 UTC
