### ISSUE TITLE
Tomb Raider Trilogy [BLES01195] Lighting effects missing on Vulkan

### ISSUE THREAD

**Issue by NovaPrima** [RPCS3/rpcs3#6265] opened 2019-07-26 05:27 UTC
The lighting isn't right on Vulkan. No bloom on her collarbone, for example.

![vulkan](https://user-images.githubusercontent.com/42202690/61930026-f5440200-afbf-11e9-80ee-8b5a7e5616b7.jpg)
![opengl](https://user-images.githubusercontent.com/42202690/61930027-f5440200-afbf-11e9-9f6d-b6ba99fe3ab2.jpg)

It flickers between the two on OpenGL, so hopefully my RSX and RenderDoc captures aren't useless. It flickers less over time though. I don't know whether it's compiling shaders since the message doesn't pop up.

https://www107.zippyshare.com/v/4io5MuAq/file.html

**Comment by Asinin3** [comment] 2019-07-26 05:33
Did you try disabling anti-aliasing? And when doing a regression report you need to find what pull request broke it.

**Comment by RainbowCookie32** [comment] 2019-07-26 05:41
If disabling anti-aliasing fixes it, then it's related/a duplicate of #6103

**Comment by NovaPrima** [comment] 2019-07-26 06:11
Yep, AA off fixes it. Thanks.

New issue, though I don't know if it's of note: the lighting isn't right on Vulkan. No bloom on her collarbone, for example.

![vulkan](https://user-images.githubusercontent.com/42202690/61930026-f5440200-afbf-11e9-80ee-8b5a7e5616b7.jpg)
![opengl](https://user-images.githubusercontent.com/42202690/61930027-f5440200-afbf-11e9-9f6d-b6ba99fe3ab2.jpg)

**Comment by Asinin3** [comment] 2019-07-26 13:09
Is that not a time of day thing? The lighting is completely different. But you can try using Write Color Buffers. I think you should edit the OP to the lighting issue if it persists, and post the color/anti-aliasing issue into #6103

**Comment by NovaPrima** [comment] 2019-07-27 00:38
Do I need to get these captures in OGL and Vulkan or just Vulkan?

**Comment by Asinin3** [comment] 2019-07-27 04:41
Do both so kd-11 can compare them.

**Comment by digitaldude555** [comment] 2020-02-25 14:09
![Screenshot (1180)](https://user-images.githubusercontent.com/26138653/75254479-159f9d80-57e9-11ea-9f55-6eccda689bee.png)
![Screenshot (1182)](https://user-images.githubusercontent.com/26138653/75254482-17696100-57e9-11ea-9574-0f5ce9d17619.png)
there is bloom on her collarbone now.

**Comment by AniLeo** [comment] 2020-02-26 10:37
Closing as fixed, ping if other lighting issues remain

**Closed by AniLeo** 2020-02-26 10:37 UTC
