### ISSUE TITLE
TLoU Performance regression PR6376

### ISSUE THREAD

**Issue by Xcedf** [RPCS3/rpcs3#6419] opened 2019-08-27 06:57 UTC
The Last of Us became slower after https://github.com/RPCS3/rpcs3/pull/6376, found out that two commits responsible: 9cd53259 and 5d1b7eb94
Normally it was like this:
![2](https://user-images.githubusercontent.com/7060586/63747587-26aa3900-c8b0-11e9-969b-fe082c185ff3.jpg)
after 9cd53259 became slightly slower
![3](https://user-images.githubusercontent.com/7060586/63747609-36298200-c8b0-11e9-9991-d937f01d2a46.jpg)
and after 5d1b7eb94 it came to it's current state
![4](https://user-images.githubusercontent.com/7060586/63747948-0333be00-c8b1-11e9-93b0-7c1ebc3c7e15.jpg)
reverting both brings fps back but i'm sure reverting isn't the way

**Comment by kd-11** [comment] 2019-08-27 07:47
Marked as discussion since there isn't much that can be done about it. The first one can be mitigated somewhat with a rewrite, but the second one is not so simple. There is overhead due to the fact that write color buffer and write depth buffer are separate options for performance reasons but logically they should not be. It makes it possible to have crazy situations due to memory aliasing such as references to deleted textures existing in the texture cache. Probably can be somewhat mitigated with yet another rewrite, but that's future work at the moment.

**Comment by kd-11** [comment] 2019-08-28 18:03
It may still be. The main problem is that the page granularity of 4KB is too large for emulation. So while merging the options may improve performance of one part, it may bring down performance in another unrelated area.

**Comment by Xcedf** [comment] 2019-08-28 19:27
Did more testing: it seems only CPU Blit performance is affected GPU Blit remains intact

**Comment by kd-11** [comment] 2019-08-28 20:11
That is expected in this case. There should be an increased rate of section flushing in this situation due to removal of sections left in an undefined state. Section A is protected as color buffer under WCB rules but the game then reuses the memory for a depth buffer which should be unprotected since WDB is disabled. What do we do with section A? Unprotect it? Ignore it? The only reasonable solution is to avoid the data loss and flush the section to CPU then unprotect it. Afterall, memory contents persist between configuration changes and you can have a setup that never introduces new data. Its not a simple situation.
The first regression is caused due to invalidation rules at the moment, but this could in theory be improved to allow invalidated sections to auto-clear barrier memory owners on release. Can be done by overloading ref_counted::release() but I really do not want that base type to be inheritable. Makes more sense to have some kind of balancer to monitor memory usage since the amount of temporary VRAM that can be held at one time can be massive if you don't force collapse and release as soon as it is possible to do so.

**Comment by Xcedf** [comment] 2019-11-24 17:57
An update to this issue:
With all new recent fixes to TLOU, i can tell for sure this issue is only about WCB, CPU blit is doing fine, previously WCB was needed for CPU Blit to render stuff, but with new MLAA patch it's no longer needed and here's a major difference:
Cpu Blit by itself:
![2](https://user-images.githubusercontent.com/7060586/69498803-fbf66d80-0efc-11ea-9c44-1222a8123cf7.jpg)
Cpu blit + WCB
![1](https://user-images.githubusercontent.com/7060586/69498812-0ca6e380-0efd-11ea-90f9-d3bc09e6ef44.jpg)

**Closed** 2020-01-29 14:23 UTC
Labels: Discussion
