### ISSUE TITLE
Unable to find asmjit.lib on Windows 8 [Debug - LLVM]

### ISSUE THREAD

**Issue by ss23** [RPCS3/rpcs3#1234] opened 2015-09-27 10:01 UTC
Similar/same issue as #397. I fixed it by changing the libraries directory to include `..\libs\Debug\` for my local copy, but I'm unsure how to best make this change nicely (Windows isn't my strong suit).

**Comment by Bigpet** [comment] 2015-10-12 10:56
should be fixed, leave a comment if the issue is still present

**Closed by Bigpet** 2015-10-12 10:56 UTC
