### ISSUE TITLE
MGS4 [BLES00246] hangs on act 4 briefing end

### ISSUE THREAD

**Issue by zorn-v** [RPCS3/rpcs3#13678] opened 2023-04-16 05:30 UTC
### Quick summary

RPCS3 Version: 0.0.27-14876-44b3709d Alpha | master

On loading screen it just close game window and open black new one with something like this in log
```
·E 0:01:17.952747 {PPU[0x1000000] Thread (main_thread) [liblv2: 0x017d29bc]} SIG: Invalid or unsupported instruction (op=0, reg=24, d_size=0, a_size=0x0, i_size=0)
·E 0:01:17.952751 {PPU[0x1000000] Thread (main_thread) [liblv2: 0x017d29bc]} SIG: decode_x64_reg_op(00007f42d9bfa3d2): unsupported opcode: 0xc46270f734034585f64c897518c6853c

·F 0:01:17.952898 {PPU[0x1000000] Thread (main_thread) [liblv2: 0x017d29bc]} SIG: Thread terminated due to fatal error: Segfault reading location 00000003e004322c at 00007f42d9bfa3d2.
```

### Attach a log file

[RPCS3.log.gz](https://github.com/RPCS3/rpcs3/files/11241307/RPCS3.log.gz)

**Comment by GamingPlutia** [comment] 2023-04-25 22:53
I had that same issue today, I got around it by using a older build

**Comment by zorn-v** [comment] 2023-04-28 11:22
What concrete build you are used for pass this issue ?

**Comment by GamingPlutia** [comment] 2023-04-28 16:00
I used build 0.0.25-14499. Simply get the save from (dev_hdd0 > home > 0000001 > savedata) of the current build, and put the folder in the older build's savedata folder. Once that's done, simply use the older build to finish the MGS 1 flashback segment and save. Now that the flashback segment is over, you grab the new save file and put in the current build's savedata folder.

And by doing all of this, you're able to finally to play Act 4 of MGS4. It's a lot but pretty simple. Just compiling the PPU modules in the older 0.0.25-14499 build takes a long time.

**Comment by zorn-v** [comment] 2023-04-29 03:32
> I used build 0.0.25-14499

Thanks, it worked. But you need to completely remove `.cache/cache` dir to recompile PPU modules (including system).
After compilling you can use latest version of rpcs3.

> Just compiling the PPU modules in the older 0.0.25-14499 build takes a long time.

You can disable "PPU LLVM Precompilation" in "Advanced" tab to not precompile all PPU at start game.

**Comment by AniLeo** [comment] 2023-05-21 20:31
The error pointed in the OP has been fixed on #13807, it was a bug with Ryzen CPUs, so I'm closing this issue.

Please provide a log with latest build if you see the same error (`Invalid or unsupported instruction`) with the same repro steps so it can be reopened.

**Comment by AniLeo** [comment] 2023-05-21 20:39
Reopening since it seems it's affected by a different bug, please provide an updated log with latest RPCS3 build for this crash

**Comment by zorn-v** [comment] 2023-05-22 00:54
RPCS3 Version: 0.0.27-15030-8db31809 Alpha | master
All works fine with rebuilding cache.

**Comment by lithiumfox** [comment] 2023-06-05 16:20
Can confirm that 0.0.27-15030 worked after downgrading from v0.0.28-15124-c8577592 master

**Comment by Nekotekina** [comment] 2023-06-05 16:29
Can someone post error message from the recent master?

**Comment by lithiumfox** [comment] 2023-06-05 16:55
> Can someone post error message from the recent master?

Gonna test 2 custom settings really fast, I think I found the source of the issue...

**Comment by AniLeo** [comment] 2023-06-05 17:19
Giga is not supposed to be used to begin with. If the issue cannot be reproduced anymore on Safe or Mega, this issue can be closed.

**Comment by lithiumfox** [comment] 2023-06-05 17:21
Hence why I was double checking to make sure it was consistent: It is not.

It still happens on both Safe and Mega.

Here's the Safe logs:
[RPCS3.log](https://github.com/RPCS3/rpcs3/files/11655089/RPCS3.log)
[RPCS3.log.gz](https://github.com/RPCS3/rpcs3/files/11655090/RPCS3.log.gz)

**Comment by lithiumfox** [comment] 2023-06-05 17:37
If needed, here's the working log as a comparison example from 0.0.27-15030

[RPCS3.log.gz](https://github.com/RPCS3/rpcs3/files/11655190/RPCS3.log.gz)

**Comment by lithiumfox** [comment] 2023-06-05 21:43
This was resolved for me by using the imported patch file provided by !explain bot on the discord and not the canary patch on the wiki

Removing the flickering texture patch seems to resolve this for me. May need testing from others before confirming resolved.

**Comment by ItsALH** [comment] 2023-06-07 16:06
Can reproduce, but what I'll post is subjective since other people have had this issue for a while on builds older than the one I'm reporting.

Latest working (for me): [15120.log](https://github.com/RPCS3/rpcs3/files/11679492/15120.log)
Broken: [15124-broken.log](https://github.com/RPCS3/rpcs3/files/11679502/15124-broken.log) [PR #13840 ]

In 0.0.28-15120, after the briefing, you normally get a loading screen and the game window will close and open again to load the MGS1 flashback, and after you're done with the section, same thing will happen and you'll go back to MGS4.

In 0.0.28-15124, you'll get a blackscreen when the flashback is supposed to happen.

**Comment by solarmystic** [comment] 2023-06-07 20:27
> Can reproduce, but what I'll post is subjective ig since other people have had this issue for a while on builds older than the one I'm reporting. Not using any patches.

I can confirm this new finding. It straight up freezes with a blackscreen now (after the game window closes and opens again to load the flashback) instead of a long pause before the MGS1 flashback starts up.

Extra logs and screenshots from my end -

Working in 15120 [RPCS3.log.gz](https://github.com/RPCS3/rpcs3/files/11681670/RPCS3.log.gz)
![image](https://github.com/RPCS3/rpcs3/assets/4345150/ca1715a7-f82f-4a96-a0d8-e8bfb7fd6462)

Not working in 15124 [RPCS3.log.gz](https://github.com/RPCS3/rpcs3/files/11681684/RPCS3.log.gz)
![image](https://github.com/RPCS3/rpcs3/assets/4345150/87704700-208e-410b-958a-1c83a07c2619)

**Comment by jceverritt** [comment] 2023-06-08 01:35
I'm seeing the exact same issue with NPU831633 on 15143

Error: E SYS: 'cellPadSetActDirect' failed with 0x80121107 : CELL_PAD_ERROR_NO_DEVICE [1]

**Comment by AniLeo** [comment] 2023-06-09 21:05
@brian218 can you check? Above report flags your PR as the broken one

**Comment by solarmystic** [comment] 2023-06-10 00:22
Attached savedata to easily reproduce this issue for devs working on it.
[BLUS30109G64680987.zip](https://github.com/RPCS3/rpcs3/files/11710778/BLUS30109G64680987.zip)

**Comment by brian218** [comment] 2023-06-10 02:48
> @brian218 can you check? Above report flags your PR as the broken one

I'll look into the issue later.
As for the mentioned error, IMO it seems to have something to do with cellPad, which wasn't touched in #13840.

**Comment by brian218** [comment] 2023-06-10 11:56
> > Can reproduce, but what I'll post is subjective ig since other people have had this issue for a while on builds older than the one I'm reporting. Not using any patches.
> 
> I can confirm this new finding. It straight up freezes with a blackscreen now (after the game window closes and opens again to load the flashback) instead of a long pause before the MGS1 flashback starts up.
> 
> Extra logs and screenshots from my end -
> 
> Working in 15120 [RPCS3.log.gz](https://github.com/RPCS3/rpcs3/files/11681670/RPCS3.log.gz) ![image](https://user-images.githubusercontent.com/4345150/244188788-ca1715a7-f82f-4a96-a0d8-e8bfb7fd6462.png)
> 
> Not working in 15124 [RPCS3.log.gz](https://github.com/RPCS3/rpcs3/files/11681684/RPCS3.log.gz) ![image](https://user-images.githubusercontent.com/4345150/244189256-87704700-208e-410b-958a-1c83a07c2619.png)
> 
> EDIT:- Final error message before the black screen freeze is `E {PPU[0x1000000] Thread (main_thread) [HLE:0x015d1184, LR:0x0001c808]} SYS: 'cellPadSetActDirect' failed with 0x80121107 : CELL_PAD_ERROR_NO_DEVICE [1]`
> 
> ![image](https://user-images.githubusercontent.com/4345150/244190990-5fd47152-8d1f-4ffa-88fd-79af49e47052.png)

Please retest with `master`.

**Comment by ItsALH** [comment] 2023-06-10 13:39
Working in latest (15169).

**Comment by brian218** [comment] 2023-06-10 14:08
> Working in latest (15169).
> 
> EDIT: Nevermind, upon booting it again the same section, it freezes. Clearing caches allowed me to play through it again.
> 
> Also out of curiosity, I tried with master 15145 (the one with the hotfix) and it still hanged in that one, even with cleared caches. [15145.log](https://github.com/RPCS3/rpcs3/files/11712573/15145.log)

Please confirm if `sspu_spu.elf` actually exists in your game dump.
I saw it in your log but I don't have that game so I cannot confirm.

**Comment by ItsALH** [comment] 2023-06-10 14:17
> > Working in latest (15169).
> > EDIT: Nevermind, upon booting it again the same section, it freezes. Clearing caches allowed me to play through it again.
> > Also out of curiosity, I tried with master 15145 (the one with the hotfix) and it still hanged in that one, even with cleared caches. [15145.log](https://github.com/RPCS3/rpcs3/files/11712573/15145.log)
> 
> Please confirm if `sspu_spu.elf` actually exists in your game dump. I saw it in your log but I don't have that game so I cannot confirm.

No, it doesn't exist.

Also, I could get into the flashback again without clearing caches in latest, but what seems to happen is that it'll hang if you reload the section after you go through it and compile the next part of the game.

**Comment by brian218** [comment] 2023-06-10 14:19
> > > Working in latest (15169).
> > > EDIT: Nevermind, upon booting it again the same section, it freezes. Clearing caches allowed me to play through it again.
> > > Also out of curiosity, I tried with master 15145 (the one with the hotfix) and it still hanged in that one, even with cleared caches. [15145.log](https://github.com/RPCS3/rpcs3/files/11712573/15145.log)
> > 
> > 
> > Please confirm if `sspu_spu.elf` actually exists in your game dump. I saw it in your log but I don't have that game so I cannot confirm.
> 
> No, it doesn't exist.
> 
> Also, I could get into the flashback again without clearing caches in latest, but what seems to happen is that it'll hang if you reload the section after you go through it and compile the next part of the game.

Or try looking for it in caches.

**Comment by ItsALH** [comment] 2023-06-10 14:27
> > > > Working in latest (15169).
> > > > EDIT: Nevermind, upon booting it again the same section, it freezes. Clearing caches allowed me to play through it again.
> > > > Also out of curiosity, I tried with master 15145 (the one with the hotfix) and it still hanged in that one, even with cleared caches. [15145.log](https://github.com/RPCS3/rpcs3/files/11712573/15145.log)
> > > 
> > > 
> > > Please confirm if `sspu_spu.elf` actually exists in your game dump. I saw it in your log but I don't have that game so I cannot confirm.
> > 
> > 
> > No, it doesn't exist.
> > Also, I could get into the flashback again without clearing caches in latest, but what seems to happen is that it'll hang if you reload the section after you go through it and compile the next part of the game.
> 
> Or try looking for it in caches.

Nothing, made a search in both the emulator folder and game folder.
I'll try clearing caches and compiling again, then leaving the game when I boot in the section and see if that file pops somehow.

**Comment by brian218** [comment] 2023-06-10 14:56
Please test #13995.

**Comment by ItsALH** [comment] 2023-06-10 15:01
> Please test #13995.

It's working, ran it a second time just to make sure and didn't face any hanging.

**Comment by brian218** [comment] 2023-06-10 15:03
> > Please test #13995.
> 
> It's working, ran it a second time just to make sure and didn't face any hanging.

Nice! Glad to help.😄

**Comment by solarmystic** [comment] 2023-06-10 15:55
> > Please test #13995.
> 
> It's working, ran it a second time just to make sure and didn't face any hanging.

Confirmed @ItsALH's findings, the MGS1 flashback now works perfectly with PR #13995. Thanks for the fix @brian218 

![image](https://github.com/RPCS3/rpcs3/assets/4345150/765cc060-cdf9-4e3e-9c89-89384cbc7cf1)

**Closed** 2023-06-10 15:59 UTC
Labels: Regression
