### ISSUE TITLE
video record inversion and minor lighting glitches.

### ISSUE THREAD

**Issue by TristisOris** [RPCS3/rpcs3#4811] opened 2018-06-24 12:39 UTC
i tried to report lightning glitches, but got a little another result)
NieR Replicant [BLJM60223]

captured by bandicam 4.1.4
OpenGL, Write color buffers enabled.
[RPCS3.log](https://github.com/RPCS3/rpcs3/files/2130755/RPCS3.log)

https://www.youtube.com/watch?v=pZE6hQHuizI
https://www.youtube.com/watch?v=6HonPU5Pjrc

**Comment by Asinin3** [comment] 2018-06-24 12:42
"video record inversion" what does this even mean? you had the wrong settings so the videos are upside down? I never seen this issue in RPCS3. The minor lighting issue is mainly bad if your camera is low, just raise it up a bit.

**Comment by TristisOris** [comment] 2018-06-24 12:47
you see that issue now.
all other apps recorded normally.

**Comment by kd-11** [comment] 2019-04-05 13:17
Video record inversion = bandicam issue, not ours.
Lighting glitches are a duplicate of an existing issue (already reported)

**Closed by kd-11** 2019-04-05 13:17 UTC
