### ISSUE TITLE
Persona 5 White dots/flickering 

### ISSUE THREAD

**Issue by yerDunn** [RPCS3/rpcs3#8017] opened 2020-04-12 02:44 UTC
## Quick summary
I'm getting lots of flickering white dots all over certain textures in Persona 5, tried disabling all mods/patches and running it clean but no luck.

## Details
The flickering is a lot worse when playing compared to screenshots. Seems to especially happen to grass/trees/signs.

![Screenshot (48)](https://user-images.githubusercontent.com/63524738/79059257-bcc77f80-7c45-11ea-9021-5b813cb0249a.png)
![Capture](https://user-images.githubusercontent.com/63524738/79059280-eed8e180-7c45-11ea-922d-ea2f280b3744.PNG)
![Logs](https://user-images.githubusercontent.com/63524738/79059282-f13b3b80-7c45-11ea-8b0a-4f3a6f4dcd11.PNG)

**Comment by Asinin3** [comment] 2020-04-12 02:47
Try without the disable blur patch.

**Comment by yerDunn** [comment] 2020-04-12 03:03
> Try without the disable blur patch.

Still showing up unfortunately, no dice trying to run it clean either.

**Comment by Asinin3** [comment] 2020-04-12 03:04
Try SPU asmjit? It could be Frest issue coming back

**Comment by yerDunn** [comment] 2020-04-12 03:15
rly appreciate the help so far! I checked the Frest issue page, SPU asmjit doesn't seem to fix anything.

**Comment by AniLeo** [comment] 2020-04-12 07:36
Upload the actual log file too

**Comment by kd-11** [comment] 2020-04-13 08:41
This would likely be a regression if its happening on vanilla game (no patches, upscaling, etc). In that case some regression testing would be required to identify when it started happening.

**Comment by vsub** [comment] 2020-04-13 17:25
I am using the 60fps patch and either I don't have that problem or it appears only in specific locations which I did not try

**Comment by Yamazukii** [comment] 2020-05-24 16:22
I am also having this problem. It seems worse on LLVM. I tried running it on asmjit and the dots don't seem nearly as prevalent, but still there. The game is running really great otherwise though. I have it patched.

**Comment by EPixowl** [comment] 2020-09-19 04:46
Happens to me as well with LLVM (xFloat on and off) and ASMJIT with little to no difference.
The only real change is visible while playing around with the Resolution scale, leaving it to 100% seems to greatly reduce the white dots, using strict mode removes them almost completely.

Specs :
I7-9700k 
RX 5700XT

**Comment by FanderWasTaken** [comment] 2020-10-15 14:05
Try setting resolution scale to even number, a.k.a 100%, 200%, 300% etc. I had similar issue that was showing up at 1080p, but not at 720p, 1440p or 2160p.

![20201015172009_1](https://user-images.githubusercontent.com/48799496/96140372-eae98d00-0f10-11eb-90f8-67853f9e43a8.jpg)

**Comment by kd-11** [comment] 2020-10-16 07:41
Non-integer scaling is always going to break things because you cannot divide pixels and get coherent data all the time. This is why especially 200% and 400% are usually a lot more compatible than other scaling values.

**Comment by mrxthealpha19** [comment] 2021-07-20 17:55
I had this problem too. Been messing around with the config and nothing work but the above solution. Changing the Resolution Scale to 200% and 400% fix the white, green, blue dots immediately. Tks guys.

**Comment by Asinin3** [comment] 2022-04-07 23:10
As this is caused by res scaling at non integer values I'm closing this off. I'll add a note to our wiki about it.

**Closed by Asinin3** 2022-04-07 23:10 UTC
Labels: Bug, CPU
