### ISSUE TITLE
GT5 has broken text rendering on RADV

### ISSUE THREAD

**Issue by xddxd** [RPCS3/rpcs3#8642] opened 2020-07-27 10:20 UTC
Gran Turismo 5 BCES00569 has broken text rendering in the menu on the RADV driver, when testing on Windows 10 with the AMD 20.7.2 driver it renders correctly.

RADV:
![unknown](https://user-images.githubusercontent.com/1712979/88531494-9b7b7b00-d00b-11ea-92ff-97c6aa0d8a16.png)
[RPCS3.log.gz](https://github.com/RPCS3/rpcs3/files/4981391/RPCS3.log.gz)
RSX capture: https://www.dropbox.com/s/75q41jnrc6y0kq8/BCES00569_20200727125243_capture.7z?dl=0
Windows:
![Screenshot_10](https://user-images.githubusercontent.com/1712979/88531590-bd74fd80-d00b-11ea-8342-b0d2f1b591db.png)
[RPCS3.log.gz](https://github.com/RPCS3/rpcs3/files/4981395/RPCS3.log.gz)
RSX capture: https://www.dropbox.com/s/t4zuj3qaoikh9df/BCES00569_20200727130153_capture.7z?dl=0

EDIT: tested with AMDVLK too, it renders correctly.

**Comment by AniLeo** [comment] 2020-07-29 08:55
> Mesa 20.1.3

Can you try with mesa-git? Maybe it has been fixed in the meantime

If this is a driver bug, may need to be reported on Mesa directly

Can you also test with `RADV_PERFTEST=aco` vs `RADV_PERFTEST=llvm` (Note that Mesa 20.1 has LLVM as default and Mesa 20.2 has ACO as default)

**Comment by xddxd** [comment] 2020-07-29 13:48
Mesa 20.1 ACO
![mesaaco](https://user-images.githubusercontent.com/1712979/88808243-48e0c100-d1bb-11ea-8126-25dc2c7f8ead.png)
I'm still working on getting mesa-git.

**Comment by xddxd** [comment] 2020-07-29 17:15
mesa-git 20.2 ACO:
![gitaco](https://user-images.githubusercontent.com/1712979/88831506-1db89a80-d1d8-11ea-8248-63bf7b42a7da.png)
mesa-git 20.2 LLVM:
![gitllvm](https://user-images.githubusercontent.com/1712979/88831591-3628b500-d1d8-11ea-99a8-bd61fbd1173e.png)
the glitch is present

**Comment by AniLeo** [comment] 2020-07-29 17:29
Tagging @kd-11 for triaging

**Comment by pendingchaos** [comment] 2020-12-18 15:05
`RADV_PERFTEST=llvm` doesn't do anything on Mesa 20.2 and newer btw. The env to disable it is `RADV_DEBUG=llvm`

**Comment by AniLeo** [comment] 2020-12-18 15:09
Just to confirm, can you retest this with Strict Rendering Mode enabled and see if validation layers catch anything?

**Comment by AniLeo** [comment] 2020-12-18 15:32
Ok, I've retested this

Mesa: `mesa-git 21.0.0_devel.132192.04c7fce799a-1`
GPU: `AMD RADV SIENNA_CICHLID (LLVM 11.0.0)` (RX 6800 XT)

**ACO**

SRM On
![image](https://user-images.githubusercontent.com/10283761/102630668-bda1a100-4144-11eb-88e1-1424c6bb1420.png)

SRM Off
![image](https://user-images.githubusercontent.com/10283761/102630698-c72b0900-4144-11eb-8d9d-165557510d98.png)

**LLVM**

SRM Off
![image](https://user-images.githubusercontent.com/10283761/102631041-3a347f80-4145-11eb-9e92-57c6d9dfa7c1.png)

There are a few validation errors regardless of SRM being enabled or disabled:

- `E {RSX Worker 10} RSX: ERROR: [Validation] Code 0 : Validation Error: [ UNASSIGNED-CoreValidation-Shader-InconsistentSpirv ] Object 0: handle = 0x10213c80, type = VK_OBJECT_TYPE_DEVICE; | MessageID = 0x6bbb14 | SPIR-V module not valid: Result type component width must be 32 bits
%484 = OpDPdy %v4half %483`
- https://www.khronos.org/registry/vulkan/specs/1.2-extensions/html/vkspec.html#VUID-vkCmdDraw-magFilter-04553
- https://www.khronos.org/registry/vulkan/specs/1.2-extensions/html/vkspec.html#VUID-vkCmdDraw-None-02698

**Comment by kd-11** [comment] 2020-12-18 15:41
This is very likely triggered by fbo loops which go away with SRM enabled. There is no actual fix other than to make SRM always enabled and eat a huge perf loss (input attachments). On PS3 this setup just works and on windows they have workarounds because a lot of software uses this technically incorrect access pattern.

**Comment by AniLeo** [comment] 2020-12-24 23:42
Reopening and moving the unrelated spec violations to another ticket

**Comment by kd-11** [comment] 2022-09-26 22:49
We finally got the framebuffer loops extension in mesa-git. This needs an update.

**Comment by xddxd** [comment] 2022-09-27 20:24
Same behavior on latest mesa-git RADV

**Comment by kd-11** [comment] 2022-12-27 00:22
This is caused by a missing barrier between subsequent virtual subpasses. The game has a very weird font rendering mechanism where we basically have stencil_draw->stencil_draw...->color_draw + stencil_read->stencil_draw. All the while we have a single RP with the same RTV+DSV bound with the DSV being cyclic. No barrier is injected between the cyclic stencil draw and the color draw with stencil read which causes this data hazard.
There is an existing cyclic ref tracking system that is supposed to inject the barriers but this is not working as intended and needs an overhaul.

**Closed** 2022-12-28 14:37 UTC
Labels: OS: Linux, Driver: RADV (Mesa)
