### ISSUE TITLE
[Feature Request] sysaxis input using keyboard

### ISSUE THREAD

**Issue by Augusto7743** [RPCS3/rpcs3#10203] opened 2021-04-28 09:03 UTC
If using keyboard not has any configuration to sixaxis.
Have games that need sixaxis in some moments.
KZ2 has an area that need to use an machine that only is controlled if using sixaxis input and if using keyboard not is possible continue gameplay.
Thanks very much for read my topic.

**Comment by Megamouse** [comment] 2021-04-28 09:05
duplicate of #8600

**Closed by Megamouse** 2021-04-28 09:05 UTC
