### ISSUE TITLE
Uncharted: Drake's Fortune crashing

### ISSUE THREAD

**Issue by CodyMechanix** [RPCS3/rpcs3#9510] opened 2020-12-27 22:58 UTC
Hello everybody. For some reason, Uncharted: Drake's Fortune isn't working on this emulator for me. The game starts and loads fine, (most of the time) but crashes in the very beginning of the game. As soon as you spawn on the boat to start shooting the pirates, the game will crash if I look to the right side. This happens every single time, no matter what renderer/accuracy settings/sound settings I use. I have tried using different versions of the emulator but nothing seems to work. Every time it crashes I get this log: "F {RSX [0x0892af4]} SIG: Thread terminated due to fatal error: Unreachable
(in file D:\a\1\s\rpcs3\Emu\RSX\Common\surface_store.h:764[:24], in function get_surface_at) (e=0x0000007e[126])".

Here's a video of the crash: https://user-images.githubusercontent.com/76666793/103181151-b9673900-4852-11eb-8922-0ee3f6c5cfff.mov

Yes, the framerate is low. However, my hardware is not maxing out so that's not the issue.

Here are my specs:
Windows 10
Intel Core i7-7700k
GTX 1060 6GB (Driver version 26.21.14.4120)
16GB DDR4 2400Mhz

Somebody please help or do something about this. I would greatly appreciate it.

**Comment by AniLeo** [comment] 2020-12-27 23:00
Missing log file

**Comment by Satan86** [comment] 2020-12-27 23:01
duplicate of #9474

**Comment by CodyMechanix** [comment] 2020-12-27 23:01
> Missing log file

Sorry, I'm new here. What's a log file?

**Comment by AniLeo** [comment] 2020-12-27 23:03
Closing as duplicate of #9474
Read the guidelines before opening an issue next time to see how to submit an issue correctly

**Closed by AniLeo** 2020-12-27 23:03 UTC
Labels: Need Information
