### ISSUE TITLE
Jak and Daxter Collection™ [BCUS98281] Character borders are broken in Title Menu [Above 100% Resolution Scale]

### ISSUE THREAD

**Issue by Zorklis** [RPCS3/rpcs3#10843] opened 2021-09-08 21:07 UTC
## Quick summary
When launched, in the menu to pick a title to play, Jak and Daxter are moving (GIF or something) there's a visible border around them, just a small bug.

## Details
I noticed it happens when using Resolution Scaling above 100% (not below) which is 1280x720. So resolutions scaling options [1318x741 - 10240x5760] have a broken border visible and moving with the characters

Video showing it off - https://youtu.be/M7pDVdtVsr0

**Comment by JimScript** [comment] 2021-09-08 23:34
How do you get into the menu? Every time I try I get "F VM: Access violation reading location 0x52d5980 (unmapped memory) [type=u32]" after the Mass Media screen.

My Specs:
- SYS: AMD Ryzen 5 3600 6-Core Processor | 12 Threads | 15.95 GiB RAM | TSC: 3.600GHz | AVX+ | FMA3
- SYS: Operating system: Windows, Major: 10, Minor: 0, Build: 19043, Service Pack: none, Compatibility mode: 0
- RSX: Found vulkan-compatible GPU: 'NVIDIA GeForce RTX 2070 SUPER' running on driver 471.68.0.0
- SYS: Firmware version: 4.85

**Comment by Asinin3** [comment] 2021-09-08 23:40
Bugs with resolution scaling aren't to be tracked as its technically a hack.
You can try changing resolution scale threshold e.g to 128x128 or 256x256 or 512x512 and it might fix it but yeah closing

**Closed by Asinin3** 2021-09-08 23:40 UTC

**Comment by Darkhost1999** [comment] 2021-09-09 13:22
Since when are resolution scaling issues not tracked?
#10316

**Comment by Asinin3** [comment] 2021-09-10 00:52
Since forever actually. Typically only regression issues for when scaling regressed would be tracked. Go through closed tickets more.
https://github.com/RPCS3/rpcs3/issues/4341#issuecomment-376091369

**Comment by Asinin3** [comment] 2021-09-10 01:16
@zorklis Test with changing scale threshold like i said before and it will probably fix it anyway

**Comment by RinMaru** [comment] 2021-09-10 01:33
> @Zorklis Test with changing scale threshold like i said before and it will probably fix it anyway

doesnt work. the issue has probably always been there even on real hw just too low res to notice
