### ISSUE TITLE
Current master (08c12f4c) fails to build under Gentoo with gcc

### ISSUE THREAD

**Issue by arabek** [RPCS3/rpcs3#6477] opened 2019-09-03 06:43 UTC
```
[1215/1549] Building CXX object rpcs3/Emu/CMakeFiles/rpcs3_emu.dir/System.cpp.o
FAILED: rpcs3/Emu/CMakeFiles/rpcs3_emu.dir/System.cpp.o 
/usr/bin/g++  -DGLX_GLXEXT_PROTOTYPES -DGL_GLEXT_PROTOTYPES -DHAVE_ALSA -DHAVE_LIBEVDEV -DHAVE_PULSE -DHAVE_VULKAN -DLLVM_AVAILABLE -DNDEBUG -DVK_USE_PLATFORM_WAYLAND_KHR -I../rpcs3 -I../ -I../3rdparty/yaml-cpp/include -I../3rdparty/pugixml/src -I../3rdparty/GSL/include -I/usr/include/AL -I../3rdparty/stblib -I3rdparty/libpng -I../3rdparty/libpng -I../llvm/include -I3rdparty/llvm_build/include -I../asmjit/src -I../3rdparty/ffmpeg/linux/x86_64/include -I../3rdparty/cereal/include -I../3rdparty/GL -I../Vulkan/glslang/SPIRV/.. -I../Vulkan/glslang/glslang/.. -I../3rdparty/xxHash -isystem /usr/include/libevdev-1.0 -Wl,--exclude-libs,ALL -O3 -DNDEBUG   -pthread -Wall -fexceptions -ftemplate-depth=1024 -msse -msse2 -mcx16 -fno-strict-aliasing -Wno-unused-variable -Wno-reorder -Wno-unknown-pragmas -Wno-invalid-offsetof -Wno-unused-function -Wno-attributes -Wno-enum-compare -Wno-comment -Wno-overloaded-virtual -Wno-missing-braces -Wno-sign-compare -Wno-maybe-uninitialized -Wno-strict-aliasing -Wno-unused-but-set-variable -Wno-class-memaccess -march=native -std=gnu++17  -Winvalid-pch -include "/home/user/src/rpcs3/build/rpcs3/Emu/cotire/rpcs3_emu_CXX_prefix.hxx" -MD -MT rpcs3/Emu/CMakeFiles/rpcs3_emu.dir/System.cpp.o -MF rpcs3/Emu/CMakeFiles/rpcs3_emu.dir/System.cpp.o.d -o rpcs3/Emu/CMakeFiles/rpcs3_emu.dir/System.cpp.o -c ../rpcs3/Emu/System.cpp
In file included from ../rpcs3/Emu/RSX/rsx_cache.h:4,
                 from ../rpcs3/Emu/RSX/RSXThread.h:6,
                 from ../rpcs3/Emu/RSX/GSRender.h:3,
                 from ../rpcs3/Emu/System.cpp:19:
../Utilities/File.h:20:13: error: multiple definition of ‘enum class fs::open_mode’
  enum class open_mode : u32
             ^~~~~~~~~
In file included from /home/user/src/rpcs3/rpcs3/stdafx.h:31,
                 from /home/user/src/rpcs3/build/rpcs3/Emu/cotire/rpcs3_emu_CXX_prefix.cxx:4,
                 from /home/user/src/rpcs3/build/rpcs3/Emu/cotire/rpcs3_emu_CXX_prefix.hxx:4:
/home/user/src/rpcs3/Utilities/File.h:20:13: note: previous definition here
  enum class open_mode : u32
             ^~~~~~~~~
```

```
$ gcc -v
Using built-in specs.
COLLECT_GCC=gcc
COLLECT_LTO_WRAPPER=/usr/libexec/gcc/x86_64-pc-linux-gnu/8.3.0/lto-wrapper
Target: x86_64-pc-linux-gnu
Configured with: /var/tmp/portage/portage/sys-devel/gcc-8.3.0-r1/work/gcc-8.3.0/configure --host=x86_64-pc-linux-gnu --build=x86_64-pc-linux-gnu --prefix=/usr --bindir=/usr/x86_64-pc-linux-gnu/gcc-bin/8.3.0 --includedir=/usr/lib/gcc/x86_64-pc-linux-gnu/8.3.0/include --datadir=/usr/share/gcc-data/x86_64-pc-linux-gnu/8.3.0 --mandir=/usr/share/gcc-data/x86_64-pc-linux-gnu/8.3.0/man --infodir=/usr/share/gcc-data/x86_64-pc-linux-gnu/8.3.0/info --with-gxx-include-dir=/usr/lib/gcc/x86_64-pc-linux-gnu/8.3.0/include/g++-v8 --with-python-dir=/share/gcc-data/x86_64-pc-linux-gnu/8.3.0/python --enable-languages=c,c++ --enable-obsolete --enable-secureplt --disable-werror --with-system-zlib --enable-nls --without-included-gettext --enable-checking=release --with-bugurl=https://bugs.gentoo.org/ --with-pkgversion='Gentoo 8.3.0-r1 p1.1' --disable-esp --enable-libstdcxx-time --enable-shared --enable-threads=posix --enable-__cxa_atexit --enable-clocale=gnu --enable-multilib --with-multilib-list=m32,m64 --disable-altivec --disable-fixed-point --enable-targets=all --enable-libgomp --disable-libmudflap --disable-libssp --disable-libmpx --disable-systemtap --disable-vtable-verify --disable-libvtv --disable-libquadmath --enable-lto --without-isl --enable-default-pie --enable-default-ssp
Thread model: posix
gcc version 8.3.0 (Gentoo 8.3.0-r1 p1.1) 
```

**Comment by MSuih** [comment] 2019-09-03 06:43
Duplicate of #6474

**Closed** 2019-09-03 06:44 UTC
