### ISSUE TITLE
Trophy Manager window ignores selected and unselected categories, showing the default every time

### ISSUE THREAD

**Issue by Masamune3210** [RPCS3/rpcs3#16198] opened 2024-10-11 13:54 UTC
### Quick summary

In the Trophy Manager window, you can right click the category bar at the top of the trophies section to select and unselect what you want to be shown. Unfortunately, it only sticks for as long as you have that specific instance of the window open. As soon as you close it and open a new instance, it goes back to showing the default layout.

### Details

Be on 0.0.33-17022-fa707047
Open the Trophy Manager window with at least one game registered with the emulator
Attempt to change shown categories by right clicking the bar and selecting or deselecting categories. 
Close window and open a new one. 
Notice the default categories and layout being shown, despite the fact that the window still shows your selection if you right click the bar.  

### Attach a log file

Unrelated to emulation, log shows nothing pertaining to issue

### Attach capture files for visual issues

![image](https://github.com/user-attachments/assets/e9eaf0ab-c5c9-4b0a-a6a9-29e6e00f61d2)

### System configuration

Windows 11 22631.4169

**Comment by Megamouse** [comment] 2024-10-14 17:55
Closing since invalid report without log file.
The columns can be hidden anyway. This has been working since the dialog was first added.

**Closed by Megamouse** 2024-10-14 17:55 UTC
Labels: GUI, Trophies

**Comment by Masamune3210** [comment] 2024-10-14 23:06
The whole point of this issue was the fact that the columns don't stay hidden and the window will be back in its default layout, column selection and order the moment a new window is opened.....

I fail to see why a log would be needed considering the log doesn't say anything about the UI and has for the most part nothing to do with it.

**Comment by Megamouse** [comment] 2024-10-14 23:13
I know exactly what you meant. And it also works as intended, provided your GuiSettings aren't corrupt.
But since you don't provide any log, we can neither prove nor disprove if you're using rpcs3 correctly.

**Comment by Masamune3210** [comment] 2024-10-14 23:27
....and of course it works just fine now.

**Comment by Megamouse** [comment] 2024-10-15 00:03
I assume the gui settings file was corrupt (or somehow the header state diverged from the visibility setting of the menu entry).
So I added a workaround that tries to sync the column visibility with the menu options after restoring the last table header state.

**Comment by Masamune3210** [comment] 2024-10-15 03:27
Sweet, that should definitely help things. Sorry for being kind of an arse about the whole log thing, I had just gotten off of work and was apparently slightly cranky
