### ISSUE TITLE
Vulkan always crash

### ISSUE THREAD

**Issue by Wheel-Of-Fate** [RPCS3/rpcs3#4756] opened 2018-06-14 11:17 UTC
In Persona 5 The Game open normally but after skipping the intro movie the emulator crash
OS: Windows 7 x64 SP1
CPU: Ryzen 1600x @3.8GHZ
Rams: 16GB @3200mhz
GPU: Radeon HD 7730 1GB i know its sort of old but it supports Vulkan.
all drivers and bios are updated
i know this isn't for support but i believe its an issue since other games on my PC such as doom run normally with Vulkan
Thanks for your Great Efforts
![untitled2](https://user-images.githubusercontent.com/40186693/41409024-fac7eace-6fd4-11e8-9832-e07aa4b24569.png)
[RPCS3.log](https://github.com/RPCS3/rpcs3/files/2102050/RPCS3.log)

**Comment by AniLeo** [comment] 2018-06-14 13:16
There is nothing in the log related to the crash. You need Thread Scheduler On for better performance, not that it should matter for that crash.

Issue needs more information though, with what error does it die?

**Comment by amateur-tester** [comment] 2018-06-14 20:43
it just stay on the black screen then it freeze

**Comment by Buzing** [comment] 2018-06-15 13:52
Could it be related to my amdvlk64.dll crash issue. I cant really pinpoint it either for now but im willing to do testing.

System:
Ryzen 1700
GPU RX 580
RPCS3 Build: 6940

Error Replication: 
Enter Persona Skill menu. Crash 100% of the time.

![vulkan error](https://user-images.githubusercontent.com/12416643/41471354-fbc86cfc-70e5-11e8-88fa-2fff25247cd5.PNG)

Fixed by using Farseer(unoffical build).

other noted errors. a certain area in the game also crashes farseer and current builds.

**Comment by Buzing** [comment] 2018-06-15 15:31
@kd-11 ah no not really. Ogl works nicely for me so I've been using it for now

As for my testing i've reset the config before reswitching back to vulkan. I might have forgotten to reset the actual emulator config and only the game. I shall try to clean all configs tomorrow.

**Comment by Buzing** [comment] 2018-06-15 16:27
@MSuih interesting hmmm are you using an Intel cpu and what version is your game. Us or eu ?

**Comment by MSuih** [comment] 2018-06-15 16:28
Ryzen 5 1600 and NPEB02436

**Comment by Buzing** [comment] 2018-06-15 16:30
Same. I'll try recinding my bios to default. Other than that I'm using the latest windows insider hmm.. maybe that's why . I'll go download the non insider asap.

**Comment by amateur-tester** [comment] 2018-06-15 17:12
@kd-11 yea exactly it just stay black and when i try to close it .it freezes and i have to end it by task manager i don't use DLC OR Any types of mods

**Comment by Buzing** [comment] 2018-06-15 20:58
@amateur-tester can you answer the rest of the questions though like does other modes work

**Comment by amateur-tester** [comment] 2018-06-16 03:11
@Buzing um... which question?  everything works fine except Vulkan that's the only problem i face i want Vulkan for a good reason opengl fps drops real badly in some scenes which contain many details

**Comment by Buzing** [comment] 2018-06-16 04:17
@amateur-tester  trythe farseer build just in case. and or clearing the shader cache if you havent. it might just be a conflict.

farseer unoffical build: (backup your save file if you have one)
https://ci.appveyor.com/project/rpcs3/rpcs3/build/0.0.4-7799/artifacts

**Comment by MSuih** [comment] 2018-06-16 04:20
There is a sligtly newer version of Farseer's build on the RPCS3 Discord, in a pinned message on #help channel.

**Comment by amateur-tester** [comment] 2018-06-16 07:28
@Buzing farseer seem to be working but i have question when the fix is going to be implemented in the official build of RPCS3?

**Comment by kd-11** [comment] 2018-06-16 07:53
Tried with 7870/R9 270 card with the build from my latest work (https://github.com/RPCS3/rpcs3/pull/4752) and everything works just fine with these settings:
![image](https://user-images.githubusercontent.com/15904127/41496912-2a1925d4-7153-11e8-8260-95a5194ff891.png)
Due to technical reasons I was forced to make rpcs3 use some very unsafe methods recently. Its probably why there are crashes on some cards/drivers and not others. I'll add correct path for it if it crashes things, only trade-off will be loss of performance.

**Comment by Buzing** [comment] 2018-06-16 11:53
Ah. Thanks for the update! Take your time :)

**Comment by amateur-tester** [comment] 2018-06-16 14:43
@kd-11 i tried your latest build (0.0.0.6-6958) still the game doesn't go past the intro movie it seem
while the old farseer build worked fine

**Comment by KMGuertena** [comment] 2018-06-16 22:37
I'm having the same issue in both the latest master and the farseer build with an R9 390. It only happens when using Vulkan as the renderer. I've tried the settings above and it still crashes, with the same error as both screenshots above. I've tried reinstalling the drivers twice. I'm using driver version 18.6.1
[RPCS3.log](https://github.com/RPCS3/rpcs3/files/2108555/RPCS3.log)


CPU: i5 4690K
RAM: 16 GB
GPU: R9 390

**Comment by Buzing** [comment] 2018-06-17 05:39
@KMGuertena did you clear the shade cache Everytime you switched builds ? And yeah agreed it crashes on those parts

**Comment by KMGuertena** [comment] 2018-06-17 06:27
@Buzing Yup, it would usually just delay the crashing for a bit.

**Comment by Yukonz** [comment] 2018-06-17 10:00
Can confirm Persona 5 100% crash with Vulkan on latest master build (6956) right after loading the first save. Shader cache is cleared.
 GPU: RX Vega 64, driver 18.6.1
<a href="http://piccy.info/view3/12419800/f82290b44d1036bcbde38185d62865cc/1200/" target="_blank"><img src="http://i.piccy.info/i9/5da7cf16928b0777e8ab530c89206b21/1529229048/30265/1245362/persona5_800.jpg" alt="Piccy.info - Free Image Hosting" border="0" /></a><a href="http://i.piccy.info/a3c/2018-06-17-09-50/i9-12419800/800x442-r" target="_blank"><img src="http://i.piccy.info/a3/2018-06-17-09-50/i9-12419800/800x442-r/i.gif" alt="" border="0" /></a>
[RPCS3.log](https://github.com/RPCS3/rpcs3/files/2108844/RPCS3.log)

**Comment by TristisOris** [comment] 2018-06-17 13:06
v6956, Nier Replicant, win10 1803, ryzen 2600, rx 580.

on error emulator is hangs up.

![default](https://user-images.githubusercontent.com/1270117/41508120-3a4370e0-7248-11e8-9933-9a40e059c21f.png)

**Comment by MSuih** [comment] 2018-06-18 14:27
So I took another look into this. Updated my drivers from 2018.3.1 to 2018.6.1 and didn't change anything else. Persona 5 started to crash as it was loading shaders, apparently one of the shaders I had compiled previously wasn't valid anymore. After clearing my shader cache I could get the menu to appear but the game would crash either when loading my save or when opening the persona menu on that tutorial fight.

I'm not sure what your policy is on game saves so hopefully I don't break any rules by dropping this save here: [NPEB02436-00--001--.zip](https://github.com/RPCS3/rpcs3/files/2111623/NPEB02436-00--001--.zip). I can't load this save anymore, game crashes as it tries to generate shaders for this area.

So the oblivous takeaway here is that something changed with AMD drivers recently and now RPCS3 is triggering crashes for code that was fine previosly.

**Comment by Buzing** [comment] 2018-06-18 15:41
After sifting through 20 builds I have concluded that Build 0.0.5 6590 [https://github.com/RPCS3/rpcs3/pull/4312](Project Link) 

is possibly related to the crash. as build 6579 works ok (further testing needed)

@MSuih  can you test it with build 6579

**Comment by kd-11** [comment] 2018-06-18 16:08
I have 18.5.1, maybe thats why it doesn't crash for me?

**Comment by MSuih** [comment] 2018-06-18 16:51
@Buzing Tested, 6590 works fine on 6.1

@kd-11 You're correct, I downgraded to that version and crashes are gone.

**Comment by Buzing** [comment] 2018-06-18 16:52
I have a feeling 18.5.2 is also affected since that was the driver I first tested with

**Comment by KMGuertena** [comment] 2018-06-18 18:31
I can confirm it's gone for me as well (at least so far) with 18.5.1.
I did figure it had something to do with the driver version. ~~I guess I was just kinda lazy and decided not to downgrade.~~

**Comment by kd-11** [comment] 2018-06-18 20:31
Thank you for confirming. I'll try to isolate the bug and devise a workaround since AMD doesn't seem to care about bug reports.

**Comment by kd-11** [comment] 2018-06-19 14:52
Turns out its worse than I thought. On my card even the official cube sample crashes immediately on launch with a nullptr dereference. There exists an alternative swapchain implementation that will work around this issue if enabled (usually only kicks in if you run rpcs3 without an active display) but its very slow and not a real solution, so I will not add a config option to forcefully enable it. AMD will have to fix this one.

**Comment by kd-11** [comment] 2018-06-19 15:02
https://community.amd.com/message/2866277

**Comment by kd-11** [comment] 2018-06-19 15:06
@amateur-tester Install lunarG SDK from https://vulkan.lunarg.com/ and run the cube sample from C:\VulkanSDK\1.1.73.0\Bin\Cube.exe and see if it crashes immediately for you as well.

For a bit of extra info, there is nothing that precedes the crash, just swapchain creation and image clearing followed by an attempted present with no drawing in between. I'm surprised this driver shipped in this state.

**Comment by TheRibbit** [comment] 2018-06-20 07:22
18.5.2 driver - Unnamed 5 crashes during save loading (or exactly after? - when it starts compiling shaders) https://i.imgur.com/kUKIxY9.png - crash error; https://i.imgur.com/LUfYxwa.png - AMD Settings panel shot. OpenGL renderer is working fine **AND Cube.exe** is working fine (or at least without crashing) (both 32bit and 64bit). [RPCS3-crashvulkan.log.gz](https://github.com/RPCS3/rpcs3/files/2118236/RPCS3-crashvulkan.log.gz)
18.5.1 driver works as expected; Cube.exe too of course. - https://i.imgur.com/ZQCaWBi.png - AMD settings panel shot; 
i5-4670K 4.5GHz, 16GB 2133MHz RAM, R7 260X 2GB GPU, Windows 10 1607 x64.

**Comment by kd-11** [comment] 2018-06-20 11:09
How can we all have different issues? For me all vulkan applications crash instantly upon starting if they try to use the AMD card. I do have an nvidia card also installed, but then again 18.5.1 works flawlessly and only 18.6.1 crashes.

**Comment by kd-11** [comment] 2018-06-20 11:49
I have identified another bug in the driver and updated the issue report which fixes my problem (AMD card is not usable unless display is attached to it directly). There is indeed another crash in vkCreateGraphicsPipelines, hopefully its not something we cannot work around.

**Comment by kd-11** [comment] 2018-06-20 12:20
Looks like someone else already reported something similar https://community.amd.com/thread/229446

**Comment by kd-11** [comment] 2018-06-20 13:34
Reported here https://community.amd.com/message/2866456
It is not something fixable on our end without AMD intervening. Therefore use driver 18.5.1 until we get feedback on what about the spirv is making their driver unhappy.

**Comment by amateur-tester** [comment] 2018-06-20 13:53
@Buzing as i mentioned before any Vulkan app/game works just fine except RPCS3 emulator exactly skipping the intro movie there is just blackscreen no error messages that's all

**Comment by Buzing** [comment] 2018-06-20 14:16
@amateur-tester if you have read it has been mainly determined that the issue lies with drivers 18.5.2 and above. 

I'm not trying to invalidate your responses but rather you told us that 18.5.1 crashes on the latest build which is a separate/another issue by it's self. 

I know farseer works since it's the exact version I used to use. But I rolled back my driver to 18.5.1 and the game works on the latest builds.

**Comment by Seroneiei** [comment] 2018-06-20 18:14
Downgrading to 18.5.1 fixed random crashes I had in tales of vesperia, so the newer drivers causes issues elsewhere too. And I'm on a r9 nano, so not gcn1.

**Comment by amateur-tester** [comment] 2018-06-22 03:39
@kd-11 Update: after alot of digging i figured that the problem is related to the official source code.
this is the update which broke Vulkan render for Persona 5:
https://github.com/RPCS3/rpcs3/pull/4265
![untitled1](https://user-images.githubusercontent.com/40186693/41756742-715836e4-75de-11e8-829e-76341e94868e.png)

The last Working version:
https://github.com/RPCS3/rpcs3/pull/4026
![untitled2](https://user-images.githubusercontent.com/40186693/41756753-7c72d250-75de-11e8-98e1-19f8dc20b831.png)

i hope this is helps in fixing the issue.

**Comment by kd-11** [comment] 2018-06-22 08:01
Your issue is unique which is unfortunate, its not possible to debug if we cannot recreate it. This happens even on 18.5.1? Maybe the amd compiler issues go back further for the 7730, but my 270 which is a rebranded 7870 should be the same in theory but it works fine. Usually driver issues will manifest like that, after some new feature is added, but I'm yet to encounter someone else with this specific issue. You said the renderer freezes ans doesnt actually segfault, which could point to a timing problem, but to debug any further you would need to set up a development environment and build rpcs3 from source on your machine.

**Comment by amateur-tester** [comment] 2018-06-22 14:32
yea my driver is 18.5.1 and for the other issue yea there is no segfault or any error messages
so there is no hope for sending reports or logs right?

**Comment by SgtSteel** [comment] 2018-06-22 21:19
I'm having issues as well.
Looks like some shaders make rpcs3 crash with a segfault in amdvlk64.dll
The emulator crashes immediately after boot when using OpenGL with a segfault in atio6axx.dll

This happens when using the latest AMD driver (Adrenalin 18.6.1; Vulkan Driver version 2.0.33; Vulkan API 1.1.73)

I'm using:
Windows 10 Pro	Build 17134 
Intel i5 3570k		Ivy Bridge
AMD HD 7870		Pitcairn


LunarG _cube.exe_ test works fine for me.
I'm also experiencing a crash outside rpcs3, in the PC game "_A Way Out_" when loading a different map. Really looks like this driver version doesn't like loading some kind of shaders.

PS: Downgrading to _AMD Adrenalin 18.5.1_ fixes the shader compiling problem. Both _Unnamed 5_ on rpcs3 and _A Way Out_ on Origin are playable again. atio6axx.dll still segfaults when booting _Unnamed 5_ using OpenGL:

![screenshot 2018-06-22 23 14 35](https://user-images.githubusercontent.com/31051418/41799656-8914fda0-7672-11e8-93b3-2fd74b1f242f.png)

**Comment by kd-11** [comment] 2018-06-23 09:00
@amateur-tester You mentioned the emulator was responsive, something I failed to spot before. Does this mean the emulator can be closed normally? If thats the case, then it has nothing to do with graphics settings. If the renderer crashes, you get a crashbox or the emulator truly freezes (cannot be closed unless you use task manager). Try removing all the cpu options (no loop detection for example, you dont need it on ryzen, auto spu threads to start with and then set to 2) and also remember to try using Null renderer. Vulkan runs faster than OpenGL internally, and this can mess up timings somewhat.

**Comment by amateur-tester** [comment] 2018-06-23 11:38
@kd-11 for Vulkan Render still the same result in the newer builds gives a black screen and the older builds which i mentioned above it freeze my whole PC as soon as the mission starts so i had to press on the reset button the null render gives a white screen but it's totally responsive. such info looks like no use right?

**Comment by Andreyogld3d** [comment] 2018-06-28 08:30
The same problem:
https://community.amd.com/thread/229559
https://community.amd.com/thread/229579

**Comment by amateur-tester** [comment] 2018-06-28 15:47
@Andreyogld3d i still believe it's not the driver because i got v18.5.1 and still can't get it to work with Persona 5 and RPCS3 besides all other Vulkan Apps are working on my PC here is a proof this is PPSSPP with Vulkan enabled
![untitled](https://user-images.githubusercontent.com/40186693/42045207-3b5777c2-7afb-11e8-86d6-d6314e85d888.png)

**Comment by Noir5536** [comment] 2018-06-30 10:03
Given the time I have spent on the game the crash is relatively rare, but there is this weird crash i encounter quite a few times at random points of the game.
P5 actually froze and blackscreen during gameplay, and then it will stop working, then windows terminate the entire thing due to some error(?)
(sorry no screenshot, rpcs3 crashes before i could do that)

the log file is massive (163MB) so I had to zip it
[RPCS3.zip](https://github.com/RPCS3/rpcs3/files/2151598/RPCS3.zip)

specs:
Intel i7-7700HQ 2.8GHz
16GB RAM
NVIDIA GeForce GTX 1060 

Game settings:
![image](https://user-images.githubusercontent.com/40714342/42124112-746e2d20-7ca0-11e8-8dc8-eb626fb51db2.png)
![image](https://user-images.githubusercontent.com/40714342/42124114-7c870d56-7ca0-11e8-9579-6c78ed44e465.png)

**Comment by jobs-git** [comment] 2018-06-30 19:15
try without framelimit, I notice crash are more frequent when its active

**Comment by AniLeo** [comment] 2018-07-01 16:09
Makes no sense to use frame limit on games that already cap themselves

**Comment by kd-11** [comment] 2018-07-02 17:09
Just an update. A few days ago we found the issue here, the driver was hanging when asked for query results with the WAIT flag set. Looks to be a driver thing since the validation layer did not complain and it is restricted to only one model of GPU. Issue was worked around by disabling occlusion tests in debug tab.

**Comment by amateur-tester** [comment] 2018-07-03 14:44
Yea as kd-11 said there is a temporary fix you can use and this is how
1 - Go to X:\rpcs3-v0.0.5-xxxx-xxxxxxxxx_win64\GuiConfigs"
2 - Open currentsettings.ini and find this line "showDebugTab=false"
3 - Change false to true.
4 - Open RPCS3 Options a new tab will appear called "Debug"
5 - Press on Debug you will find an option there called "Disable ZCull Occlusion Queries" check the box and you are done no more crashes or blackscreens with Vulkan that fixed my problem

**Comment by Web1017** [comment] 2018-07-03 18:58
I just tried the method by Disabling "ZCull Occlusion Queries" on Dantes Inferno Game with latest RPCS3 Version. It still crashes with "Fatal Error" Message once you begin fighting the First Boss, but no longer Freezes

**Comment by amateur-tester** [comment] 2018-07-04 12:14
@Web1017 if you think that that previous solution fixed a part of the issue then you better make a open a new issue and upload log file

**Comment by kd-11** [comment] 2018-07-05 17:02
Occlusion query bug seems limited to some GCN1 cards, not all of them.

As for the 18.6.1 driver crashing bug, AMD team has replied and promised a driver update to resolve the issue soon. You can see the discussion thread here https://community.amd.com/thread/229579

**Comment by KMGuertena** [comment] 2018-07-22 20:14
Tested in driver version 18.7.1, still happens.
[RPCS3.log](https://github.com/RPCS3/rpcs3/files/2217346/RPCS3.log)

**Comment by AniLeo** [comment] 2018-07-22 20:40
It's known, drivers are still bugged

**Comment by kd-11** [comment] 2018-07-23 05:04
They said August, so maybe 18.8.1 or even later.

**Comment by MSuih** [comment] 2018-08-06 17:16
I wasn't able to trigger this crash with 18.8.1 and RX 480, so it seems to be fixed now. KD can give his seal of approval if he wants to but otherwise this issue can probably be closed.

**Comment by kd-11** [comment] 2018-08-07 11:26
Confirming both issues are resolved with driver version 18.8.1. Closing.

**Closed by kd-11** 2018-08-07 11:26 UTC
Labels: Bug, Driver: AMD

**Comment by Wheel-Of-Fate** [comment] 2018-08-18 15:05
Disable ZCull Occlusion Queries Issue Fixed in https://github.com/RPCS3/rpcs3/pull/4973
