### ISSUE TITLE
Diablo 3 RoS

### ISSUE THREAD

**Issue by TheWolfOW** [RPCS3/rpcs3#8079] opened 2020-04-22 13:56 UTC
Crash: "SIG: Thread terminated due to fatal error: Unknown STOP code: 0x20e (Out_MBox is empty)"
[RPCS3.zip](https://github.com/RPCS3/rpcs3/files/4516505/RPCS3.zip)

**Comment by dio-gh** [comment] 2020-04-27 00:42
Any extra information? The game hangs every now and then, that's a known issue, that's why it's kept in Ingame.

**Comment by AniLeo** [comment] 2020-05-05 18:51
Duplicate of #5593

**Closed by AniLeo** 2020-05-05 18:51 UTC
