### ISSUE TITLE
BCES00225 Crash on cutscene (RSX)

### ISSUE THREAD

**Issue by clienthax** [RPCS3/rpcs3#3339] opened 2017-08-28 18:52 UTC
![unknown](https://user-images.githubusercontent.com/1056270/29788045-1620bcaa-8c29-11e7-82e3-7bf3dc83695e.png)

Log: https://drive.google.com/open?id=0B3htWWNJdaBpcGxVbDB6U1VjbE0

```
·E 0:05:39.919851 {rsx::thread} RSX: Invalid RSX method 0x4 (arg=0x8181c)
(in file C:\rpcs3\rpcs3\Emu\RSX\rsx_methods.cpp:45)
```
and shortly after
```
·F 0:05:40.149531 {rsx::thread} class std::runtime_error thrown: Unknown index array type 176
(in file C:\rpcs3\rpcs3\Emu\RSX\gcm_enums.cpp:26)
```

**Comment by kd-11** [comment] 2017-10-25 21:49
Closing as duplicate of https://github.com/RPCS3/rpcs3/issues/2359

**Closed by kd-11** 2017-10-25 21:49 UTC
