### ISSUE TITLE
Batman Arkham City - strange issues

### ISSUE THREAD

**Issue by GarettJaxx** [RPCS3/rpcs3#8558] opened 2020-07-06 10:54 UTC
## Quick summary

Batman Arkham City GOTY (BLUS30978) has several issues:

1. Graphics (shading?) is not rendering correctly above 100% scale
2. Audio is horribly distorted using LLVM, fine with ASMJIT

## Details

1. If I adjust the Resolution Scale higher than 100%, various aspects of the rendered graphics have a purple hue to them (e.g. shadows) which is not correct. This is immediately seen on the 'frozen' rain on the title screen - the rain is shown as purple lines rather than transparent, and further into the game e.g. the light shadows on Bruce's suit jacket are also purple. 
At 100% scaling, all graphics render correctly. 
Also, enemies seem to have a strange red box with white outline appearing over certain parts of their body, which I assume indicate 'hitboxes' - these should not appear at all (no adjustments to the settings that I can find remove them - including setting RS to 100%)

The Shader mode setting makes no difference - it does not rectify any of the above issues whichever mode is selected.

2. Using LLVM, during the introduction sequence when Bruce Wayne is tied to the chair and needs to rock it left/right to escape, the audio suddenly becomes extremely distorted if you move the camera around whilst Hugo Strange is addressing everybody over the PA system, and it then permanently remains that way - even after restarting RPCS3 and reloading etc. This behaviour does not happen when using ASMJIT - if you start the game using LLVM until the issue begins, stop the game, switch to ASMJIT then restart / reload your game the issue does go away, so this seems to be related to the LLVM SPU decoder

Switching from XAudio2 to to OpenAL does not resolve the issue either, nor does switching off SPU Loop detection

#### 1. Please attach RPCS3's log.

This log runs up to the Bruce Wayne escape sequence and is using LLVM for the audio issue, and 150% scale for the graphics issue:

[RPCS3.log.gz](https://github.com/RPCS3/rpcs3/files/4878187/RPCS3.log.gz)

#### 2. If you describe graphical issue, please provide an RSX capture and a RenderDoc capture that demonstrate it.

[BLUS30978_Title screen issue_capture.zip](https://github.com/RPCS3/rpcs3/files/4878469/BLUS30978_Title.screen.issue_capture.zip)

I can't seem to upload my RSX capture of the shading issue as it is too big - even after 7zing it

Images of the gfx issues:

![BAC-1](https://user-images.githubusercontent.com/46201027/86585522-7f416c80-bf7e-11ea-9f6c-c9e60e7b36ba.png)
![BAC-2](https://user-images.githubusercontent.com/46201027/86585528-810b3000-bf7e-11ea-8bbe-64c2caf54bf2.png)
![BAC-3](https://user-images.githubusercontent.com/46201027/86585530-823c5d00-bf7e-11ea-8d0b-0880a49e6d96.png)
![BAC-4](https://user-images.githubusercontent.com/46201027/86585534-836d8a00-bf7e-11ea-82a3-105f6c14de2d.png)

### 5. Please provide your system configuration:
* Win 10 Pro, v1909
* i7 7700 @ 4.2ghz
* Nvidia GeForce GTX 1070
* 445.87

#### Please include.

OpenGL does not render the game correctly at all and is horrendously slow, so cannot be used as a comparison

**Comment by Asinin3** [comment] 2020-09-18 04:54
@GarettJaxx  Resolution scaling is a hack, so we don't support issues created around it.
That being said.. The issue is likely resolved by changing resolution threshold. Try 512x512. If it's still bad try 1024x1024.

For 2nd issue, you were also using the Mega block size. Please try Safe and retest.

**Comment by Asinin3** [comment] 2020-10-31 04:18
I tested and can confirm changing res scale threshold doesn't fix the graphical artifacts, but resolution scaling is still a hack so it won't be tracked by the issue tracker.

For the 2nd issue I have been unable to reproduce it with SPU Loop off and SPU Safe with SPU LLVM re-compiler. Closing ticket, please ask to re-open if you can confirm audio issue still only happening with SPU LLVM.

**Closed by Asinin3** 2020-10-31 04:18 UTC
