### ISSUE TITLE
Metal gear solid 3 HD cut scene issues

### ISSUE THREAD

**Issue by puffledude** [RPCS3/rpcs3#7942] opened 2020-04-04 12:17 UTC
## Quick summary
There are graphics issues with cut scenes in mgs3.

## Details
In all cut scenes in mgs3, all moving characters and objects have a black box surrounding them. This is a flat texture on the floor of the scene that moves along with the characters.

In a couple of cut scenes, most notably in the first cut scene in the plane along with the cut scenes in the final segment at the lake, there are more serious issues. For instance, on the plane, you can see the screen of one of the computers through a characters head.

Due to the files being too large, I have created a google drive where I have put RSX captures during these errors.  Here is the link:    https://drive.google.com/open?id=1hQsa4_CVHpNl2foZk8ZAbsIppZVkUs0i

[MGS3 bug report screenshots and log.zip](https://github.com/RPCS3/rpcs3/files/4431289/MGS3.bug.report.screenshots.and.log.zip)

**Comment by kd-11** [comment] 2020-04-04 16:14
Duplicate of https://github.com/RPCS3/rpcs3/issues/6766

**Closed by kd-11** 2020-04-04 16:14 UTC

**Comment by Razatop** [comment] 2021-07-17 05:14
@kd-11 So how do you fix this? I've looked at this and #6766 and can't find a solid answer. Or maybe I just don't understand.

**Comment by kd-11** [comment] 2021-07-17 08:19
Enable read color buffers.
