### ISSUE TITLE
Regressions after #5937

### ISSUE THREAD

**Issue by Kravickas** [RPCS3/rpcs3#5983] opened 2019-05-17 14:06 UTC
Regressions after #5937

~~**NHL® Legacy [BLUS31540]**~~

~~Later commits~~

~~> F {RSX [0x00c312c]} RSX: class std::runtime_error thrown: Verification failed:~~ 
~~> (in file c:\projects\rpcs3\rpcs3\emu\rsx\vk\vktexture.cpp:146)~~
[RPCS3.log.gz](https://github.com/RPCS3/rpcs3/files/3191781/RPCS3.log.gz)

~~Commit 7749d6e1 (build 0.0.6-7211087b ) that broke it and few after~~ 

~~> F {RSX [0x004edcc]} RSX: class std::runtime_error thrown: Verification failed (e=0x7f):~~ 
~~> (in file c:\projects\rpcs3\rpcs3\emu\rsx\vk\vktexture.cpp:84)~~
[RPCS3.log.gz](https://github.com/RPCS3/rpcs3/files/3191779/RPCS3.log.gz)

Works with 200% scale (not with 300/400%)

**Comment by kd-11** [comment] 2019-05-17 14:54
Use a lower resolution scale.

**Comment by AniLeo** [comment] 2019-05-17 14:59
Yeah, log above shows

> Resolution Scale: 400

**Comment by vietnam13231** [comment] 2019-05-17 15:43
![Infamous 8133](https://user-images.githubusercontent.com/16107604/57938497-94fe5900-78c8-11e9-9eaa-4e91bfe86245.jpg)
RSX Capture: (40MB) https://drive.google.com/open?id=1efBxMS5SP3MoZZ_MnowhuP5G3U1DiY_W

Intel I9-9900k
GTX 1080
Ask if you need anything more.

**Comment by Valmar33** [comment] 2019-05-17 15:45
Will so if the prior commit, a016728a9e0bc9933ee987e5a2685bac4019da52, still works.

FFX HD Remaster and Ratchet and Clank 3 have been almost instantly dying on me, with this same error.

LLVM master, Mesa master, RPCS3 master.

**Comment by Xcedf** [comment] 2019-05-17 15:47
Confirm Infamous regression

**Comment by kd-11** [comment] 2019-05-17 16:07
@Valmar33 
> ...dying on me, with this same error

Which error? The VkTexture one? Just lower res scaling until VRAM usage is better managed. Its not really a regression, it was always there  since we only have 64MB of spare video memory allocated.

**Comment by kd-11** [comment] 2019-05-17 17:09
@vietnam13231 Which game is that?

**Comment by vietnam13231** [comment] 2019-05-17 17:29
@kd-11 First Infamous (BCUS98119).

**Comment by kd-11** [comment] 2019-05-17 17:33
Unfortunately its not there on the demo version which is strange. I'll see if messing with settings can make it appear.

**Comment by vietnam13231** [comment] 2019-05-17 17:41
Well, it happens no matter the settings for me, and seems like Xcedf has it too.

**Comment by RainbowCookie32** [comment] 2019-05-17 17:42
I can check inFamous, does it happen everywhere or at a specific spot in the game? (aka do I need a save?)

**Comment by vietnam13231** [comment] 2019-05-17 17:45
Well, I saw it right at the beginning, in "Press to start" intro part. Though it's way more visible from safehouse (so a savefile).

**Comment by RainbowCookie32** [comment] 2019-05-17 17:58
I can't notice anything here. Might show up in a different moment in the game
![inf02](https://user-images.githubusercontent.com/16805474/57946833-b6a11580-78b3-11e9-924a-fb72cf8bd15e.jpg)

![inf01](https://user-images.githubusercontent.com/16805474/57946861-c587c800-78b3-11e9-9204-3c1005f9b132.jpg)

Running on a Ryzen 3 1200 and RX 570, using OpenGL, 200% scaling and SPU LLVM.
[RPCS3.log.gz](https://github.com/RPCS3/rpcs3/files/3192547/RPCS3.log.gz)

**Comment by vietnam13231** [comment] 2019-05-17 19:49
Ok, I have to correct myself, I don't use OpenGL at all, and didn't check it here. Sorry. OpenGL doesn't have this problem, only Vulcan seems to have it. With SPU it doesn't matter though, both ASMJIT and LLVM have this.

**Comment by kd-11** [comment] 2019-05-17 20:25
@vietnam13231 Is it flickering or just broken in a fixed way?

**Comment by vietnam13231** [comment] 2019-05-17 20:31
In you don't move both character and camera, it's fixed, but if you do, it flickers.

**Comment by kd-11** [comment] 2019-05-17 20:33
Sounds like a botched image transfer then; I'll take a look tomorrow.

**Comment by kd-11** [comment] 2019-05-19 08:41
![image](https://user-images.githubusercontent.com/15904127/57979754-d73fab80-7a2a-11e9-9a74-14b4b3b0d22d.png)
No issues on my setup; Mesa RADV +  RX470. Requires a few hacks to bypass the "working buffer not big enough" issue which I'll fix shortly. How are you guys getting ingame without triggering this issue?

**Comment by vietnam13231** [comment] 2019-05-19 09:23
I have a safe from older build (pre #5579). It's a problem that's put on in issues (issues/5600).

I already tested #5988, but it doesn't fix it for me.

**Comment by kd-11** [comment] 2019-05-19 09:52
I've pushed the fix for the vertex bug, confirm if the issue happens from the start or if I need to to load a specific save.

**Comment by vietnam13231** [comment] 2019-05-19 11:27
Vertex bug (issue #5600) seems to be fixed, all the places I know that triggered it doesn't do that anymore. From my understanding it happened every time there was an explosion on the screen. First instance was in the intro.
About half a year ago I made a safe right after the intro, that's why I have the safehouse screens.

And the error I reported here originally is visible right away from the very start:
![infamous pr](https://user-images.githubusercontent.com/16107604/57981608-d06c6500-7a39-11e9-8e34-db7505d74a49.jpg)

**Comment by kd-11** [comment] 2019-05-19 11:47
I have tried both on windows and linux, using an NV and AMD card and I cannot get the results you have there. Something else is triggering this problem.

**Comment by kd-11** [comment] 2019-05-19 11:49
@Xcedf @vietnam13231 Which drivers are you guys on? Are you both on pre-400 series? Because I'm on 425 series I think and have no issues. AMD seems unaffected as well.

**Comment by vietnam13231** [comment] 2019-05-19 11:55
I have 399.24, as seen in my first post in this topic. Gonna update and check again.

**Comment by Xcedf** [comment] 2019-05-19 18:06
Guess i'm on 399, will try 400+ and see if smth changed

**Comment by AniLeo** [comment] 2019-05-20 00:34
Is that TLOU regression from 5937 too?

**Comment by Xcedf** [comment] 2019-05-20 00:49
Yes

**Comment by Emulator-Team-2** [comment] 2019-05-20 11:17
Regressions after #5937:

GPU: AMD RX 570 / Driver: 19.4.1

One Piece: Unlimited World Red-(Broken Depth)
Before:
![1](https://user-images.githubusercontent.com/38318848/58017114-aed5b100-7aff-11e9-8777-30ebef559200.png)
After:
![2](https://user-images.githubusercontent.com/38318848/58017149-bf862700-7aff-11e9-889f-197df96eac96.png)

[ RSX Capture ]:
[RSX Capture-Before](https://drive.google.com/file/d/1RIIynl2JfV_GK2qMlz-LLhNbxIH3VMRc/view?usp=sharing)
[RSX Capture-After](https://drive.google.com/file/d/16apvgiHsVF_o-m88uGlE1CrCj3h4527Y/view?usp=sharing)

**Comment by lostromb** [comment] 2019-05-25 02:49
Similar depth regressions are also seen in Valkyria Chronicles BLUS30196. Nvidia Titan X
Before:
![FPS_ 29 41 _ Vulkan _ 0 0 6-8096 _ Valkyria Chronicles  BLUS30196  5_24_2019 7_36_41 PM](https://user-images.githubusercontent.com/918053/58363673-f42a1380-7e5c-11e9-96c0-99df422635c8.png)
After:
![FPS_ 30 00 _ Vulkan _ 0 0 6-8133 _ Valkyria Chronicles  BLUS30196  5_24_2019 7_43_32 PM](https://user-images.githubusercontent.com/918053/58363677-ff7d3f00-7e5c-11e9-82a5-747c0ce32d4c.png)

**Comment by Xcedf** [comment] 2019-05-25 12:46
Finally had my time to do some tests, and The las of Us issue started with 45a13d03

**Comment by Xcedf** [comment] 2019-05-26 00:10
Another performance regression in this PR, GoW Ascension, unfortunately can't tell exactly what commit is after this because of driver fail errours during the PR but i think it's the first one, hehe's the comparisson
Normal build
![37](https://user-images.githubusercontent.com/7060586/58375779-b5cb4c00-7f63-11e9-97c1-af00dacf739e.jpg)
Same build + PR reverted
![38](https://user-images.githubusercontent.com/7060586/58375783-c8de1c00-7f63-11e9-932f-99174dc21cf5.jpg)
Normal build
![39](https://user-images.githubusercontent.com/7060586/58375784-d09dc080-7f63-11e9-9be2-e287976ad7f9.jpg)
PR reverted
![40](https://user-images.githubusercontent.com/7060586/58375785-d8f5fb80-7f63-11e9-84a6-1996db359b4e.jpg)

**Comment by QaleQ** [comment] 2019-06-26 22:54
Regression confirmed in Wrecked: Revenge Revisited aswell: https://imgur.com/a/lNQ5vis

**Comment by kd-11** [comment] 2019-07-12 11:02
I'm working on this. Need to finish some code that was left as WIP in the PR.

**Comment by Artins90** [comment] 2019-07-12 17:49
I am not sure if it's related but Katamari Forever is throwing some verification errors:
F {RSX [0x4badc48]} RSX: class std::runtime_error thrown: Verification failed (e=0x7f): 
[RPCS3.log.gz](https://github.com/RPCS3/rpcs3/files/3387453/RPCS3.log.gz)
(in file c:\projects\rpcs3\rpcs3\emu\rsx\vk\vktexture.cpp:84) x3

**Comment by kd-11** [comment] 2019-07-13 10:32
For actual regressions check https://github.com/RPCS3/rpcs3/pull/6205

**Comment by Xcedf** [comment] 2019-07-13 11:48
GoW Ascension slowdown not fixed

**Comment by kd-11** [comment] 2019-07-13 11:52
The fix is for graphical issues. For performance considerations there may actually be no sensible way around that. You may provide a profiling breakdown though if your system shows a big enough delta. Just use visual studio profiler and post the diagnostics file or even just screenshots.

**Comment by Xcedf** [comment] 2019-07-13 12:06
Well if this is about graphics issues, tested Uncharted 3 and TLoU on updated build and not fixed

**Comment by kd-11** [comment] 2019-07-13 12:11
I think uncharted 3 may be easier to diagnose between the 2 - can I get RSX capture for it?

**Comment by Xcedf** [comment] 2019-07-13 12:32
Uncharted 3 menu
https://mega.nz/#!SAgVVKDZ!YsTpEQvztnfa5l5dN-EZ0jRfGs-dSPJst3Wsq1WplDA

**Comment by Emulator-Team-2** [comment] 2019-07-15 21:40
Regression in One Piece: Unlimited World Red is fixed by https://github.com/RPCS3/rpcs3/pull/6213.
![1](https://user-images.githubusercontent.com/38318848/61251116-d5a81080-a759-11e9-9522-473879b9f79d.png)

**Comment by kd-11** [comment] 2019-07-20 12:46
I'm working on the naughty dog engine regression then we can start looking at performance problems.

**Comment by kd-11** [comment] 2019-08-19 22:36
Looks like misc fixes restores performance in GOW: Ascension. This would fix the remaining problems in this ticket.
Naughty dog problems turned out to be mostly false regressions whereby improving correctness in one area exposes problems in other parts of the emulator, but I have solutions for most of these.

**Comment by Realmantik** [comment] 2019-08-20 21:06
I found another regression with OpenGL. 

**How to reproduce**:
It happens with Tales of Vesperia (games with long intro video? Tales of series?...). Using OpenGL wait until intro video begins and then press stop button. Run the game again and before video starts you get fatal error like this:
![tales of vesperia opengl bug 8536](https://user-images.githubusercontent.com/22906342/63384346-4ff63100-c3a7-11e9-9deb-7e0a782ce5e8.png)

**Comment by Xcedf** [comment] 2019-09-14 12:00
Completed the Last of Us not so long ago, and noticed many different things ingame
on my old screen here in this issue
![30](https://user-images.githubusercontent.com/7060586/57986330-3a0d6300-7a7c-11e9-9af8-4f67231e8f01.jpg)
the broken thing on screen it's not a regression as i always thought, it's quite opposite actually, in TLoU and U3 it's some overlay effect that used by game to render different effects like fire, blizzard, smoke, in case of main menu some sun rays, yes it's broken but rendered, wes never rendered before.

**Comment by d4rkne55** [comment] 2019-09-14 16:14
@Xcedf Do you actually still get the sunrays on build 8709? I don't get them anymore.
If yes, what settings do you have?

**Comment by Xcedf** [comment] 2019-09-14 23:06
Don't have 8709, i use my own builds, but have all recent graphics commits and no hacks
so here ho it looks right now, settings WCB and Force CPU Blit are off, Read Color Buffer and Read Depth Buffer are On
main menu
![34](https://user-images.githubusercontent.com/7060586/64914540-d6125700-d75c-11e9-9115-90b3a4cd640a.jpg)
some distant smoke
![33](https://user-images.githubusercontent.com/7060586/64914542-f2ae8f00-d75c-11e9-98de-7ffaa72fad6e.jpg)
Smoke bomb inside and outside
![38](https://user-images.githubusercontent.com/7060586/64914559-36a19400-d75d-11e9-9d9a-85dd1fa45e5b.jpg)
![37](https://user-images.githubusercontent.com/7060586/64914560-399c8480-d75d-11e9-84e7-afe61da3695e.jpg)
And blizzard, the game renders a blizzard wall in this level to hide the fact that level is cutted off behind that wall
![36](https://user-images.githubusercontent.com/7060586/64914566-7b2d2f80-d75d-11e9-9825-2abf2386c9ed.jpg)

**Comment by kd-11** [comment] 2019-09-15 07:32
I guess we can close this now.

**Closed by kd-11** 2019-09-15 07:32 UTC
Labels: Regression

**Comment by Lan4545** [comment] 2019-11-30 18:24
F {RSX [0x00b1a28]} RSX: class std::runtime_error thrown: Verification failed: 
(in file C:\projects\rpcs3\rpcs3\Emu\RSX\GL\GLTextureCache.h:279)

Kindom hearts 2 final mix, only when i enter santa s house
