### ISSUE TITLE
Regression in Silent Hill: Downpour [BLUS30565]

### ISSUE THREAD

**Issue by Psycho-A** [RPCS3/rpcs3#4782] opened 2018-06-19 00:36 UTC
After merging #4769 game is unplayable - the emulator process just hangs when first frame must appear with 100% CPU load. I was waiting about 5 minutes, and nothing happens. My system config is GTX 750 Ti, I5-2500, 8 Gb RAM and Win7x64.

**Comment by isshininu** [comment] 2018-06-19 07:56
Cannot confirm.
Did you try to reset emulator settings or / and cache?

**Comment by Psycho-A** [comment] 2018-06-19 18:11
I deleted PPU, SPU and Shader Caches, and now I'm getting this after launch:
```
F {rsx::thread} class std::runtime_error thrown: Assertion Failed! Vulkan API call failed with unrecoverable error: Device lost (Driver crashed with unspecified error or stopped responding and recovered) (VK_ERROR_DEVICE_LOST)
(in file c:\projects\rpcs3\rpcs3\emu\rsx\vk\VKHelpers.h:1080)
```

My video card is okay, and game works on previous builds.

**Comment by Psycho-A** [comment] 2018-06-19 18:52
For some reasons, enabling "Force CPU blit" helps on Vulkan now, but disabling this checkbox makes emulator hang or stop as I shown above.

**Comment by Psycho-A** [comment] 2018-06-19 20:54
Enabling Force CPU Blit also helps Resident Evil HD, that also hangs the emulator on start after #4769...

**Comment by isshininu** [comment] 2018-06-20 10:43
Did you use any resolution scaling?

**Comment by Psycho-A** [comment] 2018-06-20 12:35
No difference between using scaling or not.

**Comment by Parthorisian** [comment] 2018-07-11 23:37
Silent Hill Downpour has sound since build 7084 (**pr4820**) [screen](https://imgur.com/YVAmnDk) Log [soundmutefixedSilentHillDownpour_RPCS3.zip](https://github.com/RPCS3/rpcs3/files/2186541/soundmutefixedSilentHillDownpour_RPCS3.zip)

**Comment by AniLeo** [comment] 2018-11-15 22:57
Assuming this is no longer an issue since you opened a most recent issue stating the game goes further than the problem reported here: #5160 
Closing as fixed, if this specific issue is still an issue comment here with updated information so it can be reopened, otherwise the other regression will keep being tracked on #5160

**Closed by AniLeo** 2018-11-15 22:57 UTC
