### ISSUE TITLE
NieR Replicant [BLJM60223] hangs during final cutscenes on Vulkan

### ISSUE THREAD

**Issue by steinuil** [RPCS3/rpcs3#6468] opened 2019-09-01 23:18 UTC
NieR Replicant hangs during one of the final cutscenes; I tried three times and it hung twice during the bridge cutscene and once in the cutscene right after that. The game freezes, I can restart it with ctrl+e but only the audio plays. The log spits this out:

```
{RSX [0x0029ee0]} RSX: class std::runtime_error thrown: Verification failed (e=0x7f): 
(in file C:\projects\rpcs3\rpcs3\Emu\RSX\VK\VKCompute.h:175)
```

[RPCS3.log.gz](https://github.com/RPCS3/rpcs3/files/3564010/RPCS3.log.gz)

**Comment by elemileTLDR** [comment] 2019-09-02 02:18
I'm also experiencing this. Video dies after the cutscene of beating Devola and Popola; emulation autopauses and when restarting it only music plays.  

[RPCS3.log.gz](https://github.com/RPCS3/rpcs3/files/3564244/RPCS3.log.gz)

**Comment by dio-gh** [comment] 2019-09-03 01:02
As a bit of an aside until kd investigates this ticket, both of you have bad settings. Doesn't affect the issue, but you may want to fix them either way.

@steinuil 
* You shouldn't use `16x` AF with Nier, as it messes up the visuals. Should be pretty noticable, at least it was / is for me. Leave it on `Auto`.
* I'd recommend *against* using non-integer scaling (150%). Might cause artifacts. Feel free to use 200%, as that should still be fine performance wise, even in Nier.
* If you're planning to use VSync, I'd advise you to force it from driver instead. It's really hit-or-miss when it works on RPCS3, and in my experience, it doesn't really ever.

@elemileTLDR 
* You don't need to (and thus, shouldn't) use `Accurate xfloat` with Nier. It doesn't even need `Approximate xfloat` either, but that's another story you don't need to worry about right now. (Switching that off is unlikely to increase your performance, but disabling Accurate xfloat might.)
* You have `Resolution Scale` at 107% for some reason. If this was you trying to reset it to 100%, then a, there's a `Reset` button, and b, you can use the arrow keys on your keyboard to adjust the slider one percent at a time. I'd leave it at 100% on your machine, though you can always try and experiment with 200%, if you feel a bit adventurous :p

Again, none of these settings mishaps are the cause of your issues, so **do** wait for a proper investigation. In the meanwhile, you might want to correct these mistakes though.

**Comment by elemileTLDR** [comment] 2019-09-03 01:45
@dio-gh
Thanks. As mentioned, most of those weird settings and others was me fiddling around to try and get the issue solved (I even played on Interpreter once). None of it worked, indeed.

**Comment by 0dd-B96** [comment] 2019-09-04 19:36
Hello there ! 
I've just created an account on GitHub to signal that I'm experiencing the same issue. The game freezes after the fight against Devola & Popola, with this message in RPCS3:

> F {RSX [0x01c17a8]} RSX: class std::runtime_error thrown: Verification failed (e=0x7f): 
> (in file C:\projects\rpcs3\rpcs3\Emu\RSX\VK\VKCompute.h:175)

I'm currently testing different graphic settings ! Thank you in advance for the help/futur fix and thanks for RPCS3 !

**Comment by steinuil** [comment] 2019-09-05 23:10
Thanks for the settings review @dio-gh. VSync seems to work well for me on Nier tho, and for the non-integer scaling it might be nice to have some easy way to do that from the UI without having to fiddle with the slider (I could send a PR in a week or two if you don't mind)

**Comment by kd-11** [comment] 2019-09-06 21:38
Retry with https://github.com/RPCS3/rpcs3/pull/6488

**Comment by elemileTLDR** [comment] 2019-09-07 06:59
@kd-11 Thanks. I tried with the new build and still hangs in the same place. However, with the previous build I got past it just by closing MSI afterburning and Rivatuner (which I use for screenshots).

**Comment by Chibameta** [comment] 2019-09-27 16:24
Same here, did anyone managed to get through it? \:
F {RSX [0x01c6120]} RSX: class std::runtime_error thrown: Verification failed (e=0x7f): 
(in file C:\projects\rpcs3\rpcs3\Emu\RSX\VK\VKCompute.h:175)

**Comment by Alphyn-gunner** [comment] 2019-10-01 17:08
Would you be so kind as to remove the major unnecessary spoilers from the comments? This post is now linked from the wiki and people who haven't beaten the game yet will come here.

**Comment by kd-11** [comment] 2019-10-01 19:07
After having some testers check this issue out it seems this issue does not happen in the original Nier (Gestalt). Anyone having this issue with any version other than this BLJM60223 version?

**Comment by Chibameta** [comment] 2019-10-01 19:10
> After having some testers check this issue out it seems this issue does not happen in the original Nier (Gestalt). Anyone having this issue with any version other than this BLJM60223 version?

I did have the Issue with BLUS30481 as well. didn't have the chance to try BLES00826

**Comment by kd-11** [comment] 2019-10-01 21:01
Try [this build.](https://www.dropbox.com/s/als2ha0o5z3jant/rpcs3_debug_cs_crash.7z?dl=1) It will still crash but hopefully there will be more debugging information in the log file.
Also, attach saves for other people assisting in testing.

**Comment by Chibameta** [comment] 2019-10-01 21:18
> Try [this build.](https://www.dropbox.com/s/als2ha0o5z3jant/rpcs3_debug_cs_crash.7z?dl=1) It will still crash but hopefully there will be more debugging information in the log file.
> Also, attach saves for other people assisting in testing.

Here are my save data for BLJM60223, and save data for BLUS30481 (provided by someone from another thread which I can't find right now) 
https://mega.nz/#!u3BAhYZJ!NbjQLWnnGbxy4ilBteAeIz7Fvpg5Wzrh3xk3JNRTeDI

as for the log and the build, I hope I'll be able to get to it this week.

**Comment by Illynir** [comment] 2019-10-01 22:20
Your saves are very far from the end, so I can't test and provide useful information for KD. Does anyone have a save of Nier Replicant just before the final, please?

**Comment by Chibameta** [comment] 2019-10-01 22:23
> Your saves are very far from the end, so I can't test and provide useful information for KD. Does anyone have a save of Nier Replicant just before the final, please?

umm... no they're not... for each version of the game, at least one of the save slots (I can't check right now which one) is right before entering the last dungeon, and it's the last save-spot available in the game... there is no way to save after it.

**Comment by Illynir** [comment] 2019-10-01 22:25
I tested all three slots and all three were several hours away from the end. The closest was the 24-hour one on the roof, but that's Kaine's fight.

**Comment by elemileTLDR** [comment] 2019-10-01 22:30
Here's a save right before ending A.
[home.zip](https://github.com/RPCS3/rpcs3/files/3678723/home.zip)

**Comment by Illynir** [comment] 2019-10-01 22:32
Thanks.

**Comment by Chibameta** [comment] 2019-10-01 22:34
> I tested all three slots and all three were several hours away from the end. The closest was the 22 hours one on the roof, but that's Kaine's fight.
> 
> On Nier replicant, I don't need it on Nier US, i have already my proper save for it.

Oh, damn... I might've overwritten the save with ending B NG+. sorry. \:

**Comment by Illynir** [comment] 2019-10-01 23:18
I finished Nier (BLUS30481) and Nier Replicant (BLJM60223) without any problem...

Tested with your provided saves. So I don't really know what your problem is. Maybe a bad RIP or a race condition.

**Comment by EverGreen1253** [comment] 2019-12-22 12:28
I managed to finish Nier Replicant (BLJM60223) and get Ending A without any issues using the Vulkan Renderer. RPCS3 Version: 0.0.7-9224-364ba95d Alpha.

**Comment by MrUndeadCat** [comment] 2019-12-26 20:50
I got ending A in Nier Replicant (BLJM60223). No issues occured during final cutscenes and boss fight.
RPCS3 v0.0.7-9250-e54438d3 Alpha

**Comment by z0z0z** [comment] 2019-12-30 19:33
I also recently beat the entirety of ending A with vulkan and 60fps patch and did not have this issue.

However on the second playthrough for ending B, the flying robot boss in part 2 keeps flying into the wall, getting stuck and becoming unkillable, disabling the 60fps patch and using ASMJIT don't solve this problem, I basically can't continue.

**Comment by kd-11** [comment] 2019-12-30 20:08
Closing as vulkan crash is fixed.

**Closed by kd-11** 2019-12-30 20:08 UTC
Labels: Discussion, Need Information
