### ISSUE TITLE
VK_ERROR_OUT_OF_DEVICE_MEMORY when minimizing while ingame

### ISSUE THREAD

**Issue by Ariq139** [RPCS3/rpcs3#3695] opened 2017-11-03 03:14 UTC
This happens everytime I minimize while I am ingame.
For the first 5 seconds the console spams "Swapchain creation failed because dimensions cannot fit. Max = 0, 0, Requested = 1366, 705 (or 1280, 720)" before not responding.
Using latest master and i5-6400 + GTX 1060 6GB.

Please note that this error came if I minimize it, not alt tabbing

[RPCS3.zip](https://github.com/RPCS3/rpcs3/files/1440044/RPCS3.zip)

**Comment by Alchemy-Meister** [comment] 2017-11-04 14:20
This also happened to me after minimizing emulator while in-game, but it wasn't instant crash. After leaving it for some time, I realized that the game music suddenly stopped and the whole emulator died. 

[RPCS3.zip](https://github.com/RPCS3/rpcs3/files/1443246/RPCS3.zip)

**Comment by annadess** [comment] 2017-11-09 14:46
Same thing here, I tried to get a backtrace with gdb and run Persona 5, but right after the Atlus logo showing it just gave me this segfault message, this doesn't happen when I run rpcs3 without gdb:
```
Thread 18 "PPU[0x1000000] Thread (main_thread)" received signal SIGSEGV, Segmentation fault.
[Switching to Thread 10272.0x2994]
0x000000001351f969 in ?? ()
```
Build&CPU:
RPCS3 v0.0.3-3-6782b22 Alpha | HEAD
Intel(R) Core(TM) i3-6100 CPU @ 3.70GHz | 4 Threads | 7.95 GiB RAM | AVX
GPU:
nVidia GTX 1060 3 GB

I hope this helps.

[RPCS3_normal.zip](https://github.com/RPCS3/rpcs3/files/1457955/RPCS3_normal.zip)
[RPCS3_withGDB.zip](https://github.com/RPCS3/rpcs3/files/1457956/RPCS3_withGDB.zip)

**Comment by takhlaq** [comment] 2017-11-10 15:15
potential fix in https://github.com/RPCS3/rpcs3/issues/3701 (should probably close this since the one linked is more active)

**Comment by annadess** [comment] 2017-11-10 18:24
Look into #3701 like takhlaq said, the fix kd-11 provided worked for me.
https://ci.appveyor.com/project/kd-11/rpcs3/build/0.0.3-1129
I hope it works for everyone else too.

**Comment by Alchemy-Meister** [comment] 2017-11-10 18:57
I can confirm that the build provided in #3701 solves the problem for me too.

**Comment by annadess** [comment] 2017-11-10 19:02
We should probably close both topics then.

**Closed** 2017-11-12 03:52 UTC
