### ISSUE TITLE
[Feature Request] Create Input for Motion Control

### ISSUE THREAD

**Issue by xiriby** [RPCS3/rpcs3#11903] opened 2022-04-30 07:16 UTC
## Quick summary
Create Input for Motion Control, So ps3 games that required motion control can be played on controller that doesn't support motion control

## Details
An option to decide that when a certain button was pressed the system acknowledge that as a motion input. 

#### 1. Please describe, what part of RPCS3 would be affected by your feature:
PADS

#### 2. Please tell us, why your feature is important to RPCS3.
It's hard to get a Controller for rpcs3 that support motion control 

Duallshock 3 - There are a lot of fake controllers on the internet that doesn't support motion control 
Duallshock 4 - Can easily be broken, I bought 2 Duallshock 4 controller for rpcs3 and they both got broken from accidently falling to the ground or overuse (Unlike my xbox 360 controller)
Duallshock 5 - They are pretty rare due to the high demand for a ps5 (at the time writing)

not to mention some people like to play with mouse and keyboard

#### 3. Please attach screenshots of the feature implemented in other projects.
Dolphin has this feature
![image](https://user-images.githubusercontent.com/101547056/166095644-96a5bda1-5132-4326-8832-a6c59546cf2e.png)

#### 4. Please provide your system configuration:
* OS : Windows 10
* CPU : I7-8700
* GPU : GTX 1060 6GB
* Driver version
* etc.

Thank You

**Comment by YuriNator557** [comment] 2022-04-30 07:17
looks like duplicate of #8600

**Comment by MSuih** [comment] 2022-04-30 07:18
Yes, let's keep this within that issue.

**Closed by MSuih** 2022-04-30 07:18 UTC
