### ISSUE TITLE
Crash w/o errors during SPU LLVM compiling

### ISSUE THREAD

**Issue by Andryshik345** [RPCS3/rpcs3#5776] opened 2019-04-01 15:35 UTC
During compiling SPU shaders through LLVM, on ~80% RPCS3 crashes without any errors.
Last strings before crash:
```
·W 0:00:48.584080 {Worker 2} SPU: [0x1fe5c] MFC_WrTagUpdate: $44 is not a good constant
·W 0:00:48.585826 {Worker 2} SPU: [0x1fe7c] MFC_WrTagUpdate: $42 is not a good constant
·W 0:00:48.626893 {Worker 2} SPU: [0x20764] MFC_WrTagUpdate: $44 is not a good constant
·W 0:00:48.629619 {Worker 2} SPU: [0x20784] MFC_WrTagUpdate: $42 is not a good constant
```
Game: ```Gran Turismo®6 [BCES01893] 01.00```
Emulator version: ```RPCS3 v0.0.6-7931-3bfe921a Alpha | HEAD```
[RPCS3.log](https://github.com/RPCS3/rpcs3/files/3030214/RPCS3.log)

**Comment by RainbowCookie32** [comment] 2019-04-01 15:42
Did you try removing the SPU cache? It may be corrupted, which may cause this crash

**Comment by Andryshik345** [comment] 2019-04-01 15:45
Oh it helped, thanks then

**Comment by RainbowCookie32** [comment] 2019-04-01 15:46
If the problem is gone, please close this issue. Keep in mind that [our Discord server](https://discord.me/RPCS3) is the place where you should go for support

**Comment by Andryshik345** [comment] 2019-04-01 15:47
[RPCS3.log](https://github.com/RPCS3/rpcs3/files/3030264/RPCS3.log)
new log

**Comment by RainbowCookie32** [comment] 2019-04-01 15:49
The issue is still happening then?

**Comment by Andryshik345** [comment] 2019-04-01 15:49
Yes, it is

**Comment by RainbowCookie32** [comment] 2019-04-01 15:54
Yeah, I can confirm that the game seems to be crashing when building the cache with SPU LLVM
[RPCS3.zip](https://github.com/RPCS3/rpcs3/files/3030299/RPCS3.zip)

**Comment by Nekotekina** [comment] 2019-04-01 17:04
Upload cache file please.

**Comment by RainbowCookie32** [comment] 2019-04-01 17:06
This one?
[spu-safe-v1-tane.zip](https://github.com/RPCS3/rpcs3/files/3030554/spu-safe-v1-tane.zip)

**Comment by AniLeo** [comment] 2019-04-01 18:17
I also got this on Gran Turismo 5, so it's not game specific

**Comment by legend800** [comment] 2019-04-02 16:51
It happens on Backbreaker games too. Worked fine before but broken around Oct. Exact same symptoms. There's a open defect on this, I'll have to dig it up later.

**Comment by RainbowCookie32** [comment] 2019-04-02 16:55
And also happens with The Last of Us [BCES01584] 
[spu-safe-v1-tane.zip](https://github.com/RPCS3/rpcs3/files/3035074/spu-safe-v1-tane.zip)

**Comment by legend800** [comment] 2019-04-04 02:15
Same issue?

https://github.com/RPCS3/rpcs3/issues/5257

**Comment by RainbowCookie32** [comment] 2019-04-04 02:20
I don't think so. I think that issue is the regression in block sizes that happened a while ago, using safe the games boot. Here they don't boot, doesn't matter the block size

**Comment by legend800** [comment] 2019-04-04 02:31
I confirmed in there the same build broke Backbreaker which is NOT fixed by using Safe. I would try the build before the regression build noted there to see if the games noted here launch fine with LLVM.

**Comment by RainbowCookie32** [comment] 2019-04-04 02:53
Games here regressed recently, they worked with SPU LLVM. I remember playing gt5 with LLVM a few weeks ago. So I don't think it's the same issue. It might be related to the LLVM update done recently?

**Comment by lcsondes** [comment] 2019-04-11 21:45
Also happens on Persona 5 (BLUS31604) c34821de

**Comment by RainbowCookie32** [comment] 2019-04-12 19:42
> Also happens on Persona 5 (BLUS31604) [c34821d](https://github.com/RPCS3/rpcs3/commit/c34821ded24666869e538e6a028d461c6255c6fd), Giga block size doesn't even start, Mega gets past the intro video and crashes before the main menu.

Persona 5 doesn't boot in anything else than Safe. It's been like that for months, and I'm pretty sure it's a different issue

**Comment by AniLeo** [comment] 2019-04-14 15:50
Retest with #5832

**Comment by legend800** [comment] 2019-04-14 16:09
Backbreaker series is fixed on latest build.

**Closed** 2019-04-14 16:10 UTC
Labels: CPU, Regression
