### ISSUE TITLE
white background after burner climax vulkan and opengl

### ISSUE THREAD

**Issue by mkultimate** [RPCS3/rpcs3#5065] opened 2018-08-31 02:31 UTC
![image](https://user-images.githubusercontent.com/16367065/44889463-a3093c80-ac9b-11e8-89e5-3c5f19a3f404.png)

![image](https://user-images.githubusercontent.com/16367065/44889491-bddbb100-ac9b-11e8-83e5-752253c485cf.png)

log
[RPCS3.log.gz](https://github.com/RPCS3/rpcs3/files/2338560/RPCS3.log.gz)

**Comment by AniLeo** [comment] 2018-08-31 02:49
Likely regressed on #5038, can you confirm?

**Comment by mkultimate** [comment] 2018-08-31 03:14
@AniLeo recently I just tried it and have that problem

**Comment by Emulator-Team-2** [comment] 2018-08-31 03:49
@AniLeo 
I can confirm this is a regression after #5038

**Comment by kd-11** [comment] 2018-08-31 08:29
Duplicate of https://github.com/RPCS3/rpcs3/issues/5066

**Closed by kd-11** 2018-08-31 08:29 UTC
