### ISSUE TITLE
God of War loads but does not start the game

### ISSUE THREAD

**Issue by luziiano1** [RPCS3/rpcs3#12928] opened 2022-11-07 01:07 UTC
### Quick summary

When clicking on boot, the game opens a loading screen, but closes soon after, even before the monica studio logo appears

### Details

After configuring the emulator, I start the god of war with the configuration I created. However, after loading a few things, the game closes even before the company logo appears. The curious thing is, when I used a less powerful computer, the game opened, but now with a Ryzen 7 5700X and RTX 3060 Ti it doesn't run

### Attach a log file

[RPCS3.log.gz](https://github.com/RPCS3/rpcs3/files/9947351/RPCS3.log.gz)

### Attach capture files for visual issues

![image](https://user-images.githubusercontent.com/97492579/200206619-c865e317-ff8d-4f1a-8700-adb3ba8172d3.png)
![image](https://user-images.githubusercontent.com/97492579/200206627-0d700a45-7319-4c57-a99b-0f1c07e5ede6.png)

### System configuration

Windows 10 21H2
AMD Ryzen 7 5700X | 16 Threads | 15.91 GiB RAM | AVX+ | FMA3
GPU: NVIDIA GeForce RTX 3060 Ti (526.47) 8GB
RAM: 16GB 3000

**Comment by luziiano1** [comment] 2022-11-07 01:08
I already used ddu to reinstall driver video card

**Comment by whoschery** [comment] 2022-11-16 07:27
You need to update God Of War from version 1.00 to 1.03

**Comment by Darkhost1999** [comment] 2022-11-16 13:36
As you can see in their screenshot they are updated.
Your comment was invalid before you hit send.
Anyways, we're just waiting for a retest of this issue.

**Comment by YuriNator557** [comment] 2022-11-19 14:13
This issue is normally caused by broken game files

**Comment by AniLeo** [comment] 2022-12-04 01:22
Closing as invalid as mentioned above, not an issue with RPCS3 but a local issue, no one can reproduce

**Closed by AniLeo** 2022-12-04 01:22 UTC
Labels: Need Information

**Comment by shieldanticheat** [comment] 2025-05-23 11:40
bug do proprio rpc
