### ISSUE TITLE
Heavy Rain BCUS98164

### ISSUE THREAD

**Issue by kaeldin1990** [RPCS3/rpcs3#3601] opened 2017-10-14 17:17 UTC
Iam facing an error with the lastest version of RPCS3 ver rpcs3-v0.0.3-2017-10-14-304a4a1b_win64

E {rsx::thread} HLE: Getting the real address failed. (addr=0x1e489f6c)
E {rsx::thread} RSX: Invalid FIFO queue get/put registers found, get=0x1E489F6C, put=0x89344
E {rsx::thread} HLE: Getting the real address failed. (addr=0x1e489f6c)
E {rsx::thread} RSX: Invalid FIFO queue get/put registers found, get=0x1E489F6C, put=0x89344
E {rsx::thread} HLE: Getting the real address failed. (addr=0x1e489f6c)
E {rsx::thread} RSX: Invalid FIFO queue get/put registers found, get=0x1E489F6C, put=0x89344
E {rsx::thread} HLE: Getting the real address failed. (addr=0x1e489f6c)
E {rsx::thread} RSX: Invalid FIFO queue get/put registers found, get=0x1E489F6C, put=0x89344
E {rsx::thread} RSX: Application has failed to recover, discarding FIFO queue

[RPCS3.log.gz](https://github.com/RPCS3/rpcs3/files/1384824/RPCS3.log.gz)

**Comment by kd-11** [comment] 2017-10-25 21:47
Generic synchronization bug. Search for `Invalid RSX method` in issues and you'll find it happens alot and is not unique to Heavy Rain. As such, until the issue is properly identified and fixed, one tracker is more than enough. Closing as duplicate of https://github.com/RPCS3/rpcs3/issues/2359

**Closed by kd-11** 2017-10-25 21:47 UTC
