### ISSUE TITLE
OpenGL error

### ISSUE THREAD

**Issue by Quochieu0211** [RPCS3/rpcs3#15942] opened 2024-08-14 12:29 UTC
### Quick summary

GPU

### Details

So when I tried the latest version of RPCS3, it gives me blurry graphics when I set to Vulkan. But when I set the graphics to OpenGL, the game crashed upon starting. Is there anything that I can fix this problem?

### Attach a log file

[RPCS3.log.gz](https://github.com/user-attachments/files/16612901/RPCS3.log.gz)

### Attach capture files for visual issues

![image](https://github.com/user-attachments/assets/c4005472-b54b-4e2d-8135-99d2c0db0561)
![image](https://github.com/user-attachments/assets/54feb8e7-47fb-411c-ba63-e373374d6fb4)

**Comment by FlexBy420** [comment] 2024-08-14 12:31
Intel igpu memery hits rpcs3 github issues once again

**Comment by AniLeo** [comment] 2024-08-14 12:53
Duplicate of #6199 (OpenGL) and #12021 (Vulkan)

**Closed by AniLeo** 2024-08-14 12:53 UTC
