### ISSUE TITLE
Music skipping in KATAMARI FOREVER

### ISSUE THREAD

**Issue by Flannels** [RPCS3/rpcs3#13416] opened 2023-02-18 23:22 UTC
### Quick summary

The background music in Katamari Forever (BLUS30336) on RPCS3 isn't playing correctly.

### Details

Katamari Forever runs very well on RPCS3 for the most part, however something is VERY wrong with the music outside of the FMV cutscenes (This issue is present on the title screen, main menu book, the end-level results screen, the game over screen, and of course during the standard gameplay).

On rare occasions, the music in these instances will play the way it's supposed to, but most of the time, the music will play normally for about 7 seconds before restarting, like a CD that skips.

REPORTEDLY, fixes have been found for this problem, but I've tried every single fix I've found and none of them seem to work.

For reference, I am emulating the game on the Valve Steam Deck (SteamOS Linux) with RPCS3 having been installed via EmuDeck. The bug being reported occurs with the default settings as well as with the altered settings I've seen be recommended.

### Attach a log file

file:///home/deck/.var/app/net.rpcs3.RPCS3/cache/rpcs3/RPCS3.log

**Comment by YuriNator557** [comment] 2023-02-18 23:29
The log didn't attach
Also the flatpak version is not an official release, try on the official Appimage

**Comment by Flannels** [comment] 2023-02-19 00:23
I’m not sure I’ll be able to get the controls working or add Katamari Forever to my steam library using the appimage version of RPCS3, unless there’s another method of doing so that I'm not aware of.

**Comment by Flannels** [comment] 2023-02-19 01:24
Update: Got the controls working on the appimage version, but the audio still skips.

**Comment by lovelylaika** [comment] 2023-02-19 03:18
I've had the same problem with newer builds. If you're willing to try an older version (just for now hopefully), I've used v0.0.20-13288 and the music restart issue is not present there.

**Comment by Flannels** [comment] 2023-02-19 03:29
I’ve already made a good few stars on the latest version and the music - when it has the skipping bug - does seem to eventually correct itself most of the time. I think I’ll just wait until a newer version of RPCS3 fixes this bug, but thank you very much for helping out and pointing me in the right direction! I can finally play the game without feeling like I’m going nuts

**Comment by Asinin3** [comment] 2023-07-23 03:08
The issue here is likely just due to using a Steam Deck. Audio issues happen all the time if performance is bad. You also dont have a log file still after we asked months ago. It's possible some settings to improve perf e.g using spu loop, trying 1, 2 and 3 spu preferred threads on cpu settings could have helped for instance.

Without proper info I'm closing this.

**Closed by Asinin3** 2023-07-23 03:08 UTC
Labels: Need Information

**Comment by Triticum0** [comment] 2023-07-23 17:03
@Asinin3 I did some testing and its a regression, builds before v20-13288 don't have the issue. Will find what pr the issue and update below

**Comment by Triticum0** [comment] 2023-07-23 17:42
Did some more testing and on my pc seems to just be random where audio looping triggered happens most of the time but does work sometimes.
