### ISSUE TITLE
VS 2015 static analysis is unavailable.

### ISSUE THREAD

**Issue by vlj** [RPCS3/rpcs3#1386] opened 2015-12-30 15:41 UTC
When trying to run a static analysis on D3D12GSRender I have the following errors :

3>Emu\RSX\D3D12\D3D12Buffer.cpp(1): fatal error C1083: Cannot open precompiled header file: 'x64\Release - LLVM.pch.codeanalysis': No such file or directory
3>Emu\RSX\D3D12\D3D12CommonDecompiler.cpp(1): fatal error C1083: Cannot open precompiled header file: 'x64\Release - LLVM.pch.codeanalysis': No such file or directory
...

**Comment by Nekotekina** [comment] 2016-01-10 19:11
It's caused by incorrect Rebuild behaviour. Rebuild does clean + build for each project independently, and each clean of the project other than emucore destroys the precompiled header. It's said that we can override Rebuild behaviour for each project independently, so it could be possibly fixed.

**Comment by Nekotekina** [comment] 2016-04-26 14:15
Should be fixed for now.

**Closed by Nekotekina** 2016-04-26 14:15 UTC
Labels: misc
