### ISSUE TITLE
Blocky looking shaders and particles Ratchet & Clank Future: A Crack in Time (NPUA80966)

### ISSUE THREAD

**Issue by TriageONE** [RPCS3/rpcs3#13180] opened 2023-01-07 18:39 UTC
### Quick summary

Upon entering the game, all shaders and particles appear to be "blocky". I cant identify any connected errors in console. 

### Details

Here are some examples: 

![image](https://user-images.githubusercontent.com/28678092/211164924-b8c65760-5ea4-44ee-ad92-e7f376342702.png)

![image](https://user-images.githubusercontent.com/28678092/211164935-ff256d21-facb-4ede-9d21-58bb06c8789c.png)

![image](https://user-images.githubusercontent.com/28678092/211164943-ce76ad48-11c4-4ef2-870a-edf8803b1d20.png)

![image](https://user-images.githubusercontent.com/28678092/211165036-70dd14cb-b5b6-459f-b6fa-09058a7c3ccd.png)

![image](https://user-images.githubusercontent.com/28678092/211165177-d5a49449-5419-42a8-b556-c9f2d225fcf5.png)

The artifacts almost look like scanlines. 

### Attach a log file

[RPCS3.log](https://github.com/RPCS3/rpcs3/files/10366957/RPCS3.log)

### Attach capture files for visual issues

[NPUA80966_20230107123616_capture.zip](https://github.com/RPCS3/rpcs3/files/10366976/NPUA80966_20230107123616_capture.zip)

[RPCS3.log.gz](https://github.com/RPCS3/rpcs3/files/10366982/RPCS3.log.gz)

### System configuration

CPU AMD Ryzen 5600X
GPU AMD Radeon 6900XT

**Comment by Jonathan44062** [comment] 2023-01-07 19:59
It's a known issue with AMD GPU's, also, it's duplicate of https://github.com/RPCS3/rpcs3/issues/12838

**Comment by kd-11** [comment] 2023-01-07 20:19
There's a missing pipeline barrier somewhere. Unfortunately I'm unable to reproduce on a 6700XT which makes it hard to fix from my end. If you have a scene in the game where the lines show up 100% of the time, please let me know and I can look into it.

**Comment by TriageONE** [comment] 2023-01-07 21:04
> There's a missing pipeline barrier somewhere. Unfortunately I'm unable to reproduce on a 6700XT which makes it hard to fix from my end. If you have a scene in the game where the lines show up 100% of the time, please let me know and I can look into it.

Every scene, including the very first clank section when you start the game produces this. The screenshots above are from Lord Votrigons ship.

**Closed** 2023-07-24 14:45 UTC
