### ISSUE TITLE
Ratchet & Clank: Tools of Destruction: Voron Asteroid Belt black screens upon loading the level

### ISSUE THREAD

**Issue by UltimateKamaro** [RPCS3/rpcs3#8655] opened 2020-07-30 01:19 UTC
So when I load up the Voron Asteroid Belt level on challenge mode, the game will black screen and it can't be played anymore. I've tried every option available and nothing works.

RCPS3 0.0.11-10707-ebf83221 Alpha

[RPCS3.log.gz](https://github.com/RPCS3/rpcs3/files/4998210/RPCS3.log.gz)
[RPCS3.log](https://github.com/RPCS3/rpcs3/files/4998211/RPCS3.log)

![Screenshot 7_29_2020 9_15_07 PM](https://user-images.githubusercontent.com/64123339/88869448-d1258d00-d1e0-11ea-98a0-1609dff494fa.png)
![Screenshot 7_29_2020 9_15_08 PM](https://user-images.githubusercontent.com/64123339/88869467-daaef500-d1e0-11ea-9421-561d0931fe0a.png)

PC Specs:
Windows 10 OS
Intel i7 8750H CPU
Nvidia GeForcce RTX 2080 with Max Q Design

**Comment by isJuhn** [comment] 2020-07-30 10:54
this is a duplicate of your own issue #8108

**Closed** 2020-07-30 10:55 UTC
Labels: Meta: Duplicate
