### ISSUE TITLE
Segfault writing location error whenever trying to open config

### ISSUE THREAD

**Issue by Hanly-Wijaya** [RPCS3/rpcs3#15090] opened 2024-01-24 21:33 UTC
### Quick summary

Whenever I attempt to open the config menu, I receive a 'Segfault writing location' error and RPCS3 crashes. I'm not sure if any other menu has the error but config always has it.

### Attach a log file

[RPCS3.log](https://github.com/RPCS3/rpcs3/files/14043824/RPCS3.log)

### Attach capture files for visual issues

https://drive.google.com/file/d/1gUrumUXib-rOM1JK-zT89wAE9OJCbinC/view?usp=sharing

### System configuration

CPU: Apple M2
GPU: Apple M2
RAM: 16 GB
OS: macOS Sonoma 14.3

**Comment by AniLeo** [comment] 2024-01-24 21:36
Duplicate of #14997

**Closed by AniLeo** 2024-01-24 21:36 UTC
