### ISSUE TITLE
JIT: Null Function on Don Bradman Cricket 14

### ISSUE THREAD

**Issue by uaqlover** [RPCS3/rpcs3#5972] opened 2019-05-15 17:52 UTC
![FPS_ 14 51 _ Vulkan _ 0 0 6-8105 _ Don Bradman Cricket 14  BLES01859  15_05_2019 10_49_47 AM](https://user-images.githubusercontent.com/45731484/57797499-6ed98d00-76ff-11e9-9a57-739e04fa4655.png)

[RPCS3 Don Bradman Cricket 14 .log.gz](https://github.com/RPCS3/rpcs3/files/3183836/RPCS3.Don.Bradman.Cricket.14.log.gz)

**Comment by AniLeo** [comment] 2019-05-16 02:19
```
·F 0:00:18.252554 {PPU[0x100000a] Thread (InitThread) [0x000a8c38]} class std::runtime_error thrown: Null function
(in file c:\projects\rpcs3\utilities\jit.cpp:324)
```

Retest on latest master.

**Comment by uaqlover** [comment] 2019-05-16 02:24
still same with RPCS3 v0.0.6-8116-91897fa6 Alpha | HEAD 

`
F {PPU[0x100000a] Thread (InitThread) [0x000a8c38]} class std::runtime_error thrown: Null function
(in file c:\projects\rpcs3\utilities\jit.cpp:324)
`

**Comment by AniLeo** [comment] 2019-05-16 02:27
I mean with the one that is still building

**Comment by uaqlover** [comment] 2019-05-16 02:33
@AniLeo still same RPCS3 v0.0.6-8119-a016728a Alpha https://github.com/RPCS3/rpcs3/commit/a016728a9e0bc9933ee987e5a2685bac4019da52



`
F {PPU[0x100000a] Thread (InitThread) [0x000a8c38]} class std::runtime_error thrown: Null function
(in file c:\projects\rpcs3\utilities\jit.cpp:324)
`

**Comment by AniLeo** [comment] 2019-05-20 00:48
Closing as duplicate of #5831 , continue discussion there

**Closed by AniLeo** 2019-05-20 00:48 UTC
Labels: Bug, CPU
