### ISSUE TITLE
SPUInterpreter: Unimplemented STOPD

### ISSUE THREAD

**Issue by TotalCaesar659** [RPCS3/rpcs3#4614] opened 2018-05-19 16:10 UTC
**Hitman™: Sniper Challenge [NPEB00867]**

> ·F 0:00:49.673954 {SPU[0x2000003] Thread (G2CellSpursKernel3) [0x08520]} class std::runtime_error thrown: Unimplemented instruction
> (in file Emu\Cell\SPUInterpreter.cpp:401)

[RPCS3.zip](https://github.com/RPCS3/rpcs3/files/2019622/RPCS3.zip)

**Comment by hcorion** [comment] 2018-05-21 03:07
Isn't this a duplicate of #2420

**Comment by AniLeo** [comment] 2018-05-21 03:08
Yeah but the other games don't hit it anymore as reported

**Comment by hcorion** [comment] 2018-05-21 03:15
Alright, but the issue isn't really related to unimplemented STOPD though.

**Comment by elad335** [comment] 2018-05-21 03:17
yes, the unimplemented label should be removed.

**Closed** 2018-06-17 19:20 UTC
Labels: CPU
