### ISSUE TITLE
F {rsx::thread} class std: ERROR  AFTER BATTLE INITIATION 

### ISSUE THREAD

**Issue by Linkbuzz** [RPCS3/rpcs3#2974] opened 2017-07-09 14:26 UTC
![screenshot_2](https://user-images.githubusercontent.com/30023060/27994721-8ff623fe-64f5-11e7-82a5-53406d0a90e7.png)
![screenshot_1](https://user-images.githubusercontent.com/30023060/27994722-913970d6-64f5-11e7-8a8e-d484ae323c32.png)

Help i go this message after a battle  initiation in the castle : F {rsx::thread} class std::runtime_error thrown: Invalid location (offset=0x0, location=0xffffffff)
(in file Emu\RSX\RSXThread.cpp:100)

Thanks

**Comment by AniLeo** [comment] 2017-07-09 14:28
You're using a WIP build, this is not on master
This is a duplicate of #2936 anyways

**Closed by AniLeo** 2017-07-09 14:28 UTC

**Comment by Linkbuzz** [comment] 2017-07-09 14:31
how can i use master ? is it downloadable

**Comment by SaltyCucumber** [comment] 2017-07-09 14:31
@Linkbuzz yes, here https://rpcs3.net/compatibility?b

**Comment by Linkbuzz** [comment] 2017-07-09 14:33
Thanks im gonna try this out

**Comment by AniLeo** [comment] 2017-07-09 14:34
Use the opened issue for discussion though.
This issue is known and should happen on master as well, but please refrain from reporting stuff when using non-master builds

**Comment by Linkbuzz** [comment] 2017-07-09 14:34
ok got it

**Comment by Trasen** [comment] 2018-07-25 18:11
Getting "F {rsx::thread} class std::runtime_error thrown: Verification failed: 
(in file c:\projects\rpcs3\rpcs3\emu\rsx\vk\../Common/texture_cache.h:299)" on random occations in Demon Souls, completly crashes the game.

Fresh Nvidia drivers, GTX1060,, 7700K, 16gb of ram - Windows 10.

Anyone who knows if there's a fix for ti?

Best regards.

**Comment by elad335** [comment] 2018-07-25 18:17
don't revive dead issues, not that this error is related or we provide such support on issues.

**Comment by Trasen** [comment] 2018-07-25 18:22
Aight, sorry about that.
