### ISSUE TITLE
Ratchet and Clank Future: ToD Flickering in Clanks first level

### ISSUE THREAD

**Issue by Cervoxx** [RPCS3/rpcs3#7577] opened 2020-02-24 03:46 UTC
## Quick summary
When playing Clank's first level you will encounter some flickering that seems to last a frame or two. I can't reliably find a place where it does occur, it just happens in that level. In the video it starts to happen about 17 seconds in. It doesn't seem to occur for the rest of the video and I lack editing software to edit out the irrelevant footage.

## Details
Video (Recorded at 720p@82fps but that extra framerate is not shown in the web video player): http://pc.cd/r3JrtalK

Renderdoc: http://pc.cd/40hotalK

Save file: https://files.catbox.moe/23t4tz.7z

Serial: BCUS98127

Video driver: Proprietary nvidia Linux driver ver 440.44

**Comment by Cervoxx** [comment] 2020-02-25 19:30
As a note, the reason the video is at 82fps is an attempt to make sure the flickering is caught in video, as the frame that flickers might not be caught in a 30 or 60fps video. And the game itself seems to have a 80-81 fps cap.

**Comment by Cervoxx** [comment] 2020-02-29 23:19
@kd-11 At around 42 seconds into the video you'll see some weird flickering on the cave wall, this flickering does [not occur](https://youtu.be/DPu3ZDEvfl8?t=4105) on native hardware, and still occurs as of 0.0.9-9790 . Should I make a separate issue for this with renderdocs and rsx captures pointed at that weird wall or nah?

**Comment by kd-11** [comment] 2020-03-01 06:00
There is already a megatracker with all the glitches.

**Comment by Cervoxx** [comment] 2020-03-01 07:12
I'm aware of #4258, however it does not cover the fullscreen flickering nor the weird wall flickering I mentioned in the previous comment. 

I've also realized I should probably clarify my previous comment a bit more, 42 seconds in the video that I myself linked thats hosted under pcloud, not the youtube playthrough.

**Comment by kd-11** [comment] 2020-06-27 07:54
Does "disable fifo reordering" fix this one? I know it can fix such flickering in rare cases

**Comment by kd-11** [comment] 2020-06-28 20:11
I cannot reproduce this issue when "Write color buffers" option is enabled. With the option disabled I can trigger the single frame flickers about once every minute or so in the spot shown in the video but I could not get it to happen after I enabled WCB. I did however lose fps from 82 to 78, maybe that has something to do with it, but then again PS3 cannot flip more than 60fps in the first place.

**Comment by kd-11** [comment] 2020-06-28 20:12
@Cervoxx Retest with WCB+WDB enabled. WDB (write depth buffer) is in the advanced tab.

**Comment by Cervoxx** [comment] 2020-06-28 20:31
Oh my god I'm so sorry, I meant to get to this as soon as you responded but totally forgot.

**Comment by Cervoxx** [comment] 2020-06-28 20:34
I will test with both in a bit. And as an unrelated side note it does seem that the game itself caps itself at 82fps or so.

**Comment by kd-11** [comment] 2020-06-28 20:43
Framerate capping is present in some form in almost every game made since you need to error check your time deltas. Unlocking framerate is done via game patches, I don't think one exists for this game though.

**Comment by Cervoxx** [comment] 2020-06-29 03:28
At the moment something upstream is causing compiler errors so I can't test with the very latest build, the current build i have is this (I use the AUR for rpcs3): 
![image](https://user-images.githubusercontent.com/12489208/85969849-75bc7100-b98e-11ea-89fe-74fcaaf96484.png)

Should I test with that version or wait till whatever issues that are preventing compiling gets fixed?

**Comment by RainbowCookie32** [comment] 2020-06-29 03:32
Could also get the latest AppImage from rpcs3.net/download

**Comment by Cervoxx** [comment] 2020-06-29 06:39
I completely forgot about that, I'll do it tomorrow

**Comment by Yahfz** [comment] 2020-07-16 13:55
@Cervoxx can you retest?

**Comment by Asinin3** [comment] 2020-10-29 12:00
@Cervoxx Please retest or the issue will get closed

**Comment by elad335** [comment] 2020-10-29 12:23
Closing until more relevant infornation is added, will reopen once it does.

**Closed by elad335** 2020-10-29 12:23 UTC
Labels: Need Information
