### ISSUE TITLE
St13runtime_error thrown: Verification failed (0): 

### ISSUE THREAD

**Issue by luntik2012** [RPCS3/rpcs3#2256] opened 2017-01-02 14:58 UTC
I get this error after pressing "Boot" ("Tank Battles" and "Scott Pilgrim vs The World")

U {PPU[0x70000000] Thread (main_thread) [0x0093d808]} sysPrxForUser TODO: _sys_process_atexitspawn()
U {PPU[0x70000000] Thread (main_thread) [0x0093d928]} sysPrxForUser TODO: _sys_process_at_Exitspawn
S {RawSPU[0x0] Thread ()} SPU: SPU Database initialized...
S {RawSPU[0x0] Thread ()} SPU: Function detected [0x000e0-0x00138] (size=0x58)
S {RawSPU[0x0] Thread ()} SPU: SPU Recompiler (ASMJIT) created...
S {RawSPU[0x0] Thread ()} SPU: Function detected [0x00090-0x000c0] (size=0x30)
S {RawSPU[0x0] Thread ()} SPU: Function detected [0x00138-0x00634] (size=0x4fc)
U {PPU[0x70000000] Thread (main_thread) [0x0093bb48]} cellGcmSys TODO: cellGcmSetGraphicsHandler
**F {rsx::thread} St13runtime_error thrown: Verification failed (0): 
(in file /tmp/rpcs3/rpcs3/Emu/RSX/GL/GLHelpers.h:641)**

**Comment by kd-11** [comment] 2017-01-09 10:39
This means a buffer failed to initialize likely due to insuffecient graphics memory. OGL only uses about 300MB VRAM at start though, so I dont know what modern video card would cause this kind of error.
You should try using legacy opengl buffers and see if it helps.

**Comment by mrcmunir** [comment] 2017-01-10 13:33
This issue I only reproduced with Intel GPUS and helped with Legacy opengl buffer.

**Comment by kd-11** [comment] 2017-01-10 13:48
In that case, I'm closing this issue since it is caused by a GPU driver that either doesn't have support for ARB_buffer_storage or is unable to commit enough VRAM to satisfy the emulator's needs. GL_ARB_buffer_storage or OpenGL 4.3 is required to use persistent mapped buffers.

**Closed by kd-11** 2017-01-10 13:48 UTC
