### ISSUE TITLE
DX12: J-Stars Victory VS+ DXTC texture exception 

### ISSUE THREAD

**Issue by SakataGintokiYT** [RPCS3/rpcs3#2073] opened 2016-08-18 07:38 UTC
RPCS3 [ 066e3006 ] /cellGameCreateGameData fixed

**Video** : https://www.youtube.com/watch?v=gY92F8ggDAM

Module:
-libfiber
-libl10n
-libresc
-librtc
-libspurs_jq
-libsre

__________________________________________________________________________________________________________
**Vulkan:**
Shader/Log : https://mega.nz/#!sBwQhAzb!2WvnZWmRW6kAUvGsKuNkTNLsmTYU9Xclz9IWhP0DQ9U

Stuck at title screen below after loaded savegame data.

<img src="http://www.fotoszok.pl/upload/5c611249.jpg" alt="Fotoszok.pl" />

**Comment by raven02** [comment] 2016-08-20 13:28
Just tested . Vulkan stuck at title screen after loading savegame data . GL and DX12 has their respective texture errors .

**Comment by SakataGintokiYT** [comment] 2016-08-20 14:47
@raven02 
Nope :P
Game starts up after the merge this fix 'cellGameCreateGameData'

**Comment by raven02** [comment] 2016-08-20 15:09
Alright so this game start working since "cellGameCreateGameData fixed" commit.

**Comment by raven02** [comment] 2016-08-20 16:09
I see someone get it working in DX12 here 

https://www.youtube.com/watch?v=JhfHM-RgZcw

**Comment by raven02** [comment] 2016-08-21 02:55
Humm Texture parameter in DX12 seems to be normal

E {rsx::thread} RSX: texture.width() = 200, texture.height() = 4e, texture.get_exact_mipmap_count() = 1
F {rsx::thread} class std::runtime_error thrown: HRESULT = The parameter is incorrect.
(in file Emu\RSX\D3D12\D3D12Texture.cpp:138)

**Comment by raven02** [comment] 2016-08-21 03:21
@vlj, any other thing i can check ?

	ComPtr<ID3D12Resource> result;
	CHECK_HRESULT(device->CreateCommittedResource(
		&CD3DX12_HEAP_PROPERTIES(D3D12_HEAP_TYPE_DEFAULT),
		D3D12_HEAP_FLAG_NONE,
		&get_texture_description(texture),
		D3D12_RESOURCE_STATE_COPY_DEST,
		nullptr,
		IID_PPV_ARGS(result.GetAddressOf())
		));

**Comment by raven02** [comment] 2016-08-21 15:45
BTW , there are two files missing during data installation so it cannot be loaded. Probably we need someone to help to get the real BLES02136-INSTALL to see 

```
E {PPU[0x7000000f] Thread (CRI FS File Access 1) [0x00733e0c]} sys_fs: sys_fs_stat(“/dev_hdd0/game/BLES02136-INSTALL/USRDIR/data/PS3/partition_op_patch_ps3.cpk”) failed: not found
E {PPU[0x7000000f] Thread (CRI FS File Access 1) [0x00733e0c]} 'cellFsStat' failed with 0x80010006 : CELL_ENOENT
E {PPU[0x7000000f] Thread (CRI FS File Access 1) [0x00733e0c]} sys_fs: sys_fs_stat(“/dev_hdd0/game/BLES02136-INSTALL/USRDIR/data/PS3/partition_op_game_ps3.cpk”) failed: not found
E {PPU[0x7000000f] Thread (CRI FS File Access 1) [0x00733e0c]} 'cellFsStat' failed with 0x80010006 : CELL_ENOENT
```

**Comment by SakataGintokiYT** [comment] 2016-08-27 11:07
@raven02 
I close this thread for while

**Comment by SakataGintokiYT** [comment] 2016-08-30 18:21
*Vulkan
PPU : Interpreter (precise)
SPU : Interpreter (precise)

Data/cach : https://mega.nz/#!5NwnEY4Y!VEMF-BySmNJlBY_KKiw3C3KiVcxXBzeUkiDumSDNCQ4
ShaderLog : https://mega.nz/#!Fco2BaLI!8IwRE8PoYfwnJGmVPvuJWfJmr9b_Egs4x9iJXWWLO6o
Log : https://gist.github.com/SakataGintokiYT/f10f73c633c8af6a254bed814db4b63d

**Comment by Nekotekina** [comment] 2016-08-30 18:25
@raven02 @SakataGintokiYT Don't edit messages, please. Use Preview feature if you can't type it right from the first attempt.

**Comment by vlj** [comment] 2016-08-30 23:40
@raven02 what do you mean ? Debug layer is enabled at texture creation. If there is no message when CreateCommittedResource is executed then it means that the call parameters are correct (assuming the debug layer is doing enough parameters check of course).

**Comment by raven02** [comment] 2016-09-01 13:53
@vlj , the only message i can see is "F {rsx::thread} class std::runtime_error thrown: HRESULT = The parameter is incorrect."

Or it also means something else other than CreateCommittedResource?

**Comment by vlj** [comment] 2016-09-02 15:53
What is the size of the texture ? I remember having a parameter error and no debug layer message when createCommittedResource is given a texture description with a 0 height/width or depth.

**Comment by raven02** [comment] 2016-09-02 23:59
It is a DXT45 compressed texture with dimesion 200x78

**Comment by vlj** [comment] 2016-09-03 15:14
I think the issue is the x78. DXTC uses 4x4 block texture and 78 is not a multiple of 4.
If you transform texture dimension to the next multiple of 4 in compressed texture case, does it crash ?

If it works it might introduce a subtle bug since the texture would be considered as a 200x80 by samplers on dx12 while it's accessed as a 200x78 on a real hardware ; it will introduce mismatch for texel closes to the border. We might fix this by scaling uv input in shaders though.

**Comment by raven02** [comment] 2016-09-04 04:36
It works okay if i align it to 4 .

		if (is_compressed_format(format))
		{
			width = align(width, 4);
			height = align(height, 4);
		}

**Comment by raven02** [comment] 2016-09-05 00:34
DXTC texture exception fixed by https://github.com/RPCS3/rpcs3/pull/2125

**Closed by raven02** 2016-09-05 00:34 UTC
Labels: bug, dx12
