### ISSUE TITLE
[Regression] Several games not loading now with shader compilation errors (#14149)

### ISSUE THREAD

**Issue by knifecat35** [RPCS3/rpcs3#14166] opened 2023-07-09 17:53 UTC
### Quick summary

Whenever I boot up inFAMOUS 2 now it get stuck on the "Preloading cached shaders from disk. 

![image](https://github.com/RPCS3/rpcs3/assets/85130682/4eb3146c-0ee4-4743-905c-96b5000a2abb)

Before it would load up without any errors and run.

### Details

I recieve this erorr in the Log when loading it:
E RSX: 
F {RSX Worker 11} SIG: Thread terminated due to fatal error: Failed to compile fragment shader
(in file C:\Users\ContainerAdministrator\AppData\Local\Temp\cirrus-ci-build\rpcs3\Emu\RSX\VK\VKProgramPipeline.cpp:29[:25], in function compile)

### Build with regression

0.0.28-15334-a98b4ade

### Attach two log files

[RPCS3.log](https://github.com/RPCS3/rpcs3/files/11995792/RPCS3.log)
[RPCS3.log.gz](https://github.com/RPCS3/rpcs3/files/11995793/RPCS3.log.gz)

**Comment by YuriNator557** [comment] 2023-07-09 18:03
This log is empty

**Comment by kd-11** [comment] 2023-07-09 18:31
Also, more importantly, system configuration. Different GPUs generate different shaders.

**Comment by MSuih** [comment] 2023-07-09 18:38
Unable to reproduce on my system, but then I'm on rtx 4090. The user seems to be either on integrated graphics of Ryzen 5600G or RX 5500.

**Comment by knifecat35** [comment] 2023-07-09 20:20
> Unable to reproduce on my system, but then I'm on rtx 4090. The user seems to be either on integrated graphics of Ryzen 5600G or RX 5500.

I am on a RX 5500

**Comment by knifecat35** [comment] 2023-07-09 20:26
> Also, more importantly, system configuration. Different GPUs generate different shaders.
Processor	AMD Ryzen 5 5600G with Radeon Graphics            3.90 GHz
Installed RAM	32.0 GB (31.3 GB usable)
System type	64-bit operating system, x64-based processor

**Comment by R4to0** [comment] 2023-07-10 02:49
This seems to happen with specific games. I only have this issue with Silent Hill Downpour. Attached a log, hope it helps to identify the issue.

AMD Ryzen 5 3600X running at 3.8GHz / 4.6GHz turbo
4x 8GB DDR4 at 3200MHz
AMD Radeon RX 6600 with driver version [23.7.1](https://www.amd.com/en/support/kb/release-notes/rn-rad-win-23-7-1)


[RPCS3-BLUS30565.log](https://github.com/RPCS3/rpcs3/files/11997343/RPCS3-BLUS30565.log)

**Comment by Asinin3** [comment] 2023-07-10 07:14
> I do suspect #14149 caused it. This is a different game but same issue and error message. If not, let me know and I'll open a new issue if needed.

Did you test the build on https://rpcs3.net/compatibility?b from before and after that PR merged? We need confirmation if its the cause or not.

**Comment by geymin** [comment] 2023-07-10 15:54
As said in that thread, getting the same error with inFamous 1, R&C ToD and R&C1.

**Comment by kd-11** [comment] 2023-07-10 19:22
Confirmed, affects AMD shader generation. I'll push a hotfix.

**Comment by kd-11** [comment] 2023-07-10 19:26
Should be fixed by https://github.com/RPCS3/rpcs3/pull/14179

**Closed** 2023-07-10 19:44 UTC
Labels: Bug

**Comment by R4to0** [comment] 2023-07-10 22:15
Can confirm, it fixed for me for Silent Hill Downpour game.
