### ISSUE TITLE
[issue 4091 again] [BLJS10188] Tales of Xillia 2 crashes if too many DLC is installed

### ISSUE THREAD

**Issue by qpgqiand303** [RPCS3/rpcs3#12343] opened 2022-07-13 13:54 UTC
issue 4091 
https://github.com/RPCS3/rpcs3/issues/4091

The problem reappears in the latest version

## Quick summary
 [BLJS10120] Tales of Xillia And [BLJS10188] Tales of Xillia 2 loads DLCs from the prequel and itself, which seems to work fine.
However, if there's too many DLCs active, the game just crashes when checking for DLC.

**Comment by CookiePLMonster** [comment] 2022-07-13 13:57
Can you bisect and pinpoint the exact revision where it broke?

**Comment by Darkhost1999** [comment] 2022-07-13 14:12
The best way if not the only way to make progress with this issue is to know the exact build. You can download old builds from here https://rpcs3.net/compatibility?b

2nd a log from the build that does work and a log from the build that doesn't work will provide comparitive information that may assist in finding the issue and then resolving it.

Without either of these things we can only shoot in the dark at the issue. In which case it'd be better off not even aiming to fix this problem until the information is provided.

**Comment by solarmystic** [comment] 2022-07-13 19:02
Interestingly enough I cannot reproduce this on the US version of the game [BLUS31397], It loads fine, and doesn't crash when Checking for DLC with 50+ DLC installed in the USRDIR folder, even on latest master build (0.0.23-13907)

![image](https://user-images.githubusercontent.com/4345150/178811284-57c71240-12ad-4699-b5c4-d81cfe89ed92.png)

**Comment by qpgqiand303** [comment] 2022-07-15 00:12
I think now I know how this problem is triggered. The game will display the Bandai Namco logo before loading DLC. Here, i can press X (or o) to skip this screen, and then enter the scene of loading DLC.

There is no problem for me to do this in the old version. Starting from the (0.0.23-13857) version, if I choose to skip the logo, DLC load crash will occur.

but, if the logo is not skipped in the new version. When you successfully enter the game, the log will still report error information about DLC files.

This is the log of successfully entering the game without skipping the logo, Version (0.0.23-13857)
[RPCS3.log](https://github.com/RPCS3/rpcs3/files/9116681/RPCS3.log)

**Closed** 2022-09-23 12:36 UTC
