### ISSUE TITLE
Compat DB update/Autoupdate issue

### ISSUE THREAD

**Issue by GarettJaxx** [RPCS3/rpcs3#6850] opened 2019-10-23 16:41 UTC
Whenever I fire up RPCS3, I get the following message:

RPCS3 v0.0.7-8987-ed0c25f7 Alpha | HEAD | Firmware version: 4.85
Intel(R) Core(TM) i7-7700K CPU @ 4.20GHz | 8 Threads | 15.93 GiB RAM | TSC: 4.20GHz | AVX+ | TSX
E Can't update! Please make sure your system supports SSL.
E Can not retrieve the online database! Please make sure your system supports SSL.

I've made exceptions in my firewall and turned off my antivirus but to no avail. the 2nd message results from my trying to manually download the Compatibility DB

It seems I have no connectivity but I don't think it's my system - suspect it's the way the software is trying to update

(FWIW I'm using Win 7 Ultimate x64)

**Comment by RainbowCookie32** [comment] 2019-10-23 16:43
Duplicate of #6837

**Closed** 2019-10-23 16:48 UTC
