### ISSUE TITLE
Cathernie [BLUS30428] black screen after intro logo

### ISSUE THREAD

**Issue by raulpetru** [RPCS3/rpcs3#4482] opened 2018-04-23 12:07 UTC
Hello, 
I don't really know since when this issue appeared, but Catherine is not playable anymore. I played it entirely last year with RPCS3, but with current build is not even going in menu. After showing the logos in the intro, there's just a black screen.
Here's the log:
[RPCS3.log.gz](https://github.com/RPCS3/rpcs3/files/1938045/RPCS3.log.gz)

**Comment by AniLeo** [comment] 2018-04-23 15:54
Can confirm it no longer goes Ingame

**Comment by AniLeo** [comment] 2018-04-23 17:41
Duplicate of #4473

**Closed by AniLeo** 2018-04-23 17:41 UTC
