### ISSUE TITLE
[BLES01459] Catherine Random - "MEM: Access violation reading location 0x0"

### ISSUE THREAD

**Issue by lexer98** [RPCS3/rpcs3#4338] opened 2018-03-25 16:38 UTC
This crash happens only in 3D and is completely random not in specific area. I could not find this same issue on google. Sorry if is already reported

This is my setup 
-i7 4790K@4.5Ghz (Not related to O.C it happens with stock settings too )
-16GB RAM 
-SSD
-GTX 1070 @ 391.01
-Windows 10

EMULATOR 

-Version: RPCS3 v0.0.5-6592-a36acf49d Alpha | HEAD
-Recopiler LLVM
-SPU ASMJIT
-Enable Thread scheduler
-Enable Loop detection
-SPU Threads : 2
-OpenGL (also happens with Vulkan)
-Resolution scale 200%
-Stretch to Display Area (i have a 21:9 monitor)
-Rest of the settings @ default 

ERROR

`E {rsx::thread} RSX: Dangling reports found, discarding... x22
S {rsx::thread} RSX: New program compiled successfully x69
E {PPU[0x100002d] Thread (Unlock Thread) [0x000ea8c8]} sceNpTrophy: sceNpTrophyUnlockTrophy(context=0x1, handle=0x1, trophyId=5, platinumId=*0xd00a4df0)
S {rsx::thread} RSX: New program compiled successfully x134
F {SPU[0x2000003] Thread (CellSpursKernel3)} MEM: Access violation reading location 0x0`

Full Log 
[FULL LOG.txt](https://github.com/RPCS3/rpcs3/files/1845532/FULL.LOG.txt)

**Comment by Mortimerium** [comment] 2018-03-25 16:48
Remember this freeze. Had it many times playing on versions 0.0.3, 0.0.4. Happens usually while loading new location. Just save often to not lose progress.

**Comment by AniLeo** [comment] 2018-11-15 22:57
This is a duplicate of #4408
Closing as it will be tracked there

**Closed by AniLeo** 2018-11-15 22:57 UTC
