### ISSUE TITLE
Rotate option via xinput gamepads

### ISSUE THREAD

**Issue by Krishster** [RPCS3/rpcs3#9045] opened 2020-10-07 21:48 UTC
I am using xinput controller for playing games, but it does not mapped any key for rotating. In killzone 2, rotate option must be enabled to progress. A  screen shot from gameplay is attached.
Kindly make some gamepad mapper to enable rotate options.
![Screenshot_20201008_033528](https://user-images.githubusercontent.com/64323517/95391536-d9065980-0914-11eb-97cf-68090630c0c6.jpg)

**Comment by RainbowCookie32** [comment] 2020-10-07 22:41
Duplicate of #8600

**Closed** 2020-10-07 23:48 UTC
