### ISSUE TITLE
Any build after 0.0.13-11265 won't open since today

### ISSUE THREAD

**Issue by Canhardy** [RPCS3/rpcs3#9340] opened 2020-11-26 02:13 UTC
Any build after 0.0.13-11265 won't open, I tried reinstalling newer builds, recent build, reinstalling c++ 2019, new folders, rebooted, changed monitors, I really tried everything. When i open it, it shows up in my task manager at 2061MB RAM usage. I cant provide a log due to me not being able to open the program with newer builds, only way older ones.

I have a windows 10 PC
2080ti
i9 10900f
all new drivers

Edit 1: Hey again everybody! so after sleeping again and downloading the newest update it worked again! :D

**Comment by RainbowCookie32** [comment] 2020-11-26 02:15
To clarify:
0.0.13-11265 works, but 0.0.13-11272 and further don't?

**Comment by Canhardy** [comment] 2020-11-26 02:16
> To clarify:
> 0.0.13-11265 works, but 0.0.13-11272 and further don't?

yes

**Comment by RainbowCookie32** [comment] 2020-11-26 02:16
Then #9298 would be the culprit in theory

**Comment by Canhardy** [comment] 2020-11-26 02:17
> Then #9298 would be the culprit in theory

in theory yes, but i updated the program multiple times yesterday and it worked. When i went to sleep and turned on my pc today nothing worked

**Comment by AniLeo** [comment] 2020-11-26 02:21
Can't reproduce, but I'm not using NVIDIA, though that doesn't seem relevant to the issue at hand

**Comment by Satan86** [comment] 2020-11-26 02:40
it's not related yeah, I can't reproduce on nvidia either

**Comment by stzokev** [comment] 2020-11-26 08:28
@Canhardy If the rpcs.exe process loads up as you say (it shows up in my task manager at 2061MB RAM usage), then in theory the rpcs.log should be generated. Have you checked it?

**Comment by Canhardy** [comment] 2020-11-26 09:52
> @Canhardy If the rpcs.exe process loads up as you say (it shows up in my task manager at 2061MB RAM usage), then in theory the rpcs.log should be generated. Have you checked it?

<img width="1920" alt="Desktop Screenshot 2020 11 26 - 10 51 33 16" src="https://user-images.githubusercontent.com/75048724/100335604-7573e080-2fd5-11eb-9341-a403b1416a44.png">
 It won't create a log file

**Comment by brmonaghan** [comment] 2020-11-26 19:29
Same here, I cannot open RPCS3 on my 8470p using AMD Radeon.

**Comment by Nekotekina** [comment] 2020-11-27 13:29
Try latest build, maybe it'll show some meaningful error.

**Comment by haolink** [comment] 2020-12-04 12:10
I can confirm this issue. Beginning builds after 11265 it doesn't open at all on my end. rpcs3.exe appears in task manage (with 368 K use) but it doesn't show its window or anything. A log file is not being created neither on 11272 nor one 11337. I extracted it into a blank folder to make sure existing configurations cannot cause errors.  
  
My configuration (my home office computer):  
-Intel Xeon E3 1231v3 (equals a Core i7 4xxx - so Haswell)  
-Nvidia Geforce 1070  
-16 GB DDR3-1333  
-Windows 10 Enterprise  
  
I have 2 more systems which both were not affected - so yes these two work fine, it's only the configuration above which is affected:  
VR System:  
-AMD Ryzen 2700X  
-Nvidia Geforce 1070  
-16 GB DDR4-3200  
-Windows 10 Pro  
  
Laptop:  
-AMD Ryzen 4800H (with integrated AMD Radeon)  
-Nvidia Geforce 1660 TI  
-16 GB DDR4-3200  
-Windows 10 Pro

**Comment by brmonaghan** [comment] 2020-12-04 17:51
Found the problem. Apparently I did not have vulkan installed.

**Comment by eyankee01** [comment] 2020-12-04 23:50
I'm also having this same issue. 11265 will work fine, but anything newer just is a process in task manager. 
I also tried in new folder, and also tried extracting 11265  over a copy of the original folder, and got it working. 
AMD Ryzen 5 3600X 
GeForce GTX 1660 SUPER
32 GB DDR4-3200
Windows 10
Can try other thigs or provide additional info if wanted/needed.

**Comment by AniLeo** [comment] 2020-12-08 16:36
@eyankee01 @haolink You can still reproduce this on the latest build?
Post the output of https://github.com/13xforever/vkdiag

**Comment by haolink** [comment] 2020-12-08 17:40
Hello AniLeo. I can unfortunately still reproduce the issue. I have attached the output of vkdiag for you:  
  
[vulkandriver.txt](https://github.com/RPCS3/rpcs3/files/5660813/vulkandriver.txt)
  
I then updated my drivers just for verification.  
[vulkan2.txt](https://github.com/RPCS3/rpcs3/files/5660815/vulkan2.txt)  
Updates drivers did not fix the issue.

**Comment by eyankee01** [comment] 2020-12-08 18:13
> @eyankee01 @haolink You can still reproduce this on the latest build?
> Post the output of https://github.com/13xforever/vkdiag

AniLeo,  Sorry, I'm a little clueless here. More then willing to help, but I'm really one for compiling code. 
I am still having the problem with the latest update. If you could point me to a compiled version of the vkdiag, or at least instruct how to compile it, I could give you the output as well.

**Comment by haolink** [comment] 2020-12-08 18:15
@eyankee01 You can download a compiled version of vkdiag at https://github.com/13xforever/vkdiag/releases . I used the newest one to get the results above.

**Comment by LiLENZO1101** [comment] 2020-12-12 11:36
do you have a Patch.yml file in the same folder?

**Comment by haolink** [comment] 2020-12-12 12:46
I don't.  
  
I also tried to create a debug build of RPCS3 - while I was able to compile it as a debug build and managed to run it - with the same issue. Unfortunately the Windows debugger doesn't seem to get far before it breaks on unhandled exceptions (it seems to die on xtree related functions where a parent value is a null pointer which is unhandled). If the Windows Debugger should be capable to handle RPCS3 - then I guess I could try to get you guys a stack trace.

**Comment by kd-11** [comment] 2020-12-13 10:53
@haolink Compile in Release-LLVM and run in visual studio. The Debug build had some issues last time I checked it, even if that was a long time ago. We build release with pdb information, so debugging should still be ok.

**Comment by Tru3Man** [comment] 2020-12-13 11:43
Hello, I have the same thing, after 0.0.13-11265 it does not open in any way after updates, replacements, reinstallations, the log does not create. Vulkan properly work. Windows 20H2 19042.685.

**Comment by haolink** [comment] 2020-12-22 08:40
Aaand it's me again!  
  
After having successfully compiled the emulator a few times - I decided to revert to 11265 - and the compiled versions ran. So I slowly merged the 7 commits which Nekotekina merged into the emulator. Aaand well: commit number 11270 (SHA d4d5dc99f307de3aaf9836c80edd0ec17220e8f9) broke it.  
  
Digging deeper into it I am confused but I found the line which breaks it:  
  
File: rpcs3/Emu/perf_meter.cpp
Lines - the offending line marked with a comment:  
```cpp
void perf_stat_base::add(u64 ns[66], const char* name) noexcept
{
	std::lock_guard lock(s_perf_mutex); //the attempt to lock the mutex apparently hangs the emulator. Commenting this line - even on the current HEAD will make it run fine

	s_perf_sources.emplace(name, ns);
```  
  
So yeah, on some systems lucking that mutex makes it hang - I have no real clue on how to debug this myself as it works fine on two other systems I have but yeah - without that line the emulator is in a working state, I would imagine performance metering isn't as accurate as it should be though.  
  
@Tru3Man @eyankee01 @Canhardy As you are also affected - would you mind testing the following: Download build 11456 which is the most recent one as of this writing - confirm that it still doesn't open. If so: please replace the EXE file with the one from https://pikachu.moe/rpcs3_exe.7z - this is the current HEAD branch executable compiled with the line above removed.

**Comment by Nekotekina** [comment] 2020-12-22 09:31
Thank you for debugging the issue. But perhaps it would be more helpful with the backtrace of the hanging thread.

**Comment by haolink** [comment] 2020-12-22 10:19
I think I am onto something. I should have checked which library is doing the call. Apparently if you have GeDoSaTo installed, it breaks this line (and I do have GeDoSaTo to force some applications into higher resolutions).  
  
GeDoSaTo injects shim64.dll into processes. The first breakpoint hit on that line is caused by a shim64.dll thread. Even deactivating GeDoSaTo using its tool didn't help. GeDoSaTo is essentially discontinued by its author - so I guess the best option. Get rid of it. I was able to recreate the issue on my laptop now. I installed GeDoSaTo (I copied it over and launched GeDoSaToTool.exe with Secure Boot disabled) and poof - RPCS3 did not open anymore.  
  
Due to the external code Visual Studio isn't able to properly stack trace into the issue either as it only lists the shim64.dll code as "External code"
![grafik](https://user-images.githubusercontent.com/5476865/102876569-ae249f80-4445-11eb-8a33-771bb903c408.png)  
  
Solutions:  
1. Uninstall GeDoSaTo
2. Renaming shim64.dll in the GeDoSaTo folder to shim64_.dll - this will mean the DLL injection will fail.  
  
For completion of this issue analysis: perf_stat_base:add is being called with an empty name (memory it points to is a bunch of zeros).  
  
An alternate option if name is usually always defined which compiled and worked fine for me would be to check the name variable for validity, I'd assume:  
  
```c++
void perf_stat_base::add(u64 ns[66], const char* name) noexcept
{
	if (name[0] == 0)
	{
		return;
	}

	std::lock_guard lock(s_perf_mutex);
        //...
}

void perf_stat_base::remove(u64 ns[66], const char* name) noexcept
{
	if (name[0] == 0)
	{
		return;
	}

	std::lock_guard lock(s_perf_mutex);
        //...
}```  
  
I would imagine that s_perf_mutix isn't valid inside the shim64.dll thread which causes the thread to halt.

**Comment by Nekotekina** [comment] 2020-12-22 10:31
Name shouldn't be empty - it's unreliable.
I'll add different check here, thanks for debugging.

**Comment by Tru3Man** [comment] 2020-12-22 11:51
> 
> 
> Aaand it's me again!
> 
> After having successfully compiled the emulator a few times - I decided to revert to 11265 - and the compiled versions ran. So I slowly merged the 7 commits which Nekotekina merged into the emulator. Aaand well: commit number 11270 (SHA [d4d5dc9](https://github.com/RPCS3/rpcs3/commit/d4d5dc99f307de3aaf9836c80edd0ec17220e8f9)) broke it.
> 
> Digging deeper into it I am confused but I found the line which breaks it:
> 
> File: rpcs3/Emu/perf_meter.cpp
> Lines - the offending line marked with a comment:
> 
> ```c++
> void perf_stat_base::add(u64 ns[66], const char* name) noexcept
> {
> 	std::lock_guard lock(s_perf_mutex); //the attempt to lock the mutex apparently hangs the emulator. Commenting this line - even on the current HEAD will make it run fine
> 
> 	s_perf_sources.emplace(name, ns);
> ```
> 
> So yeah, on some systems locking that mutex makes it hang - I have no real clue on how to debug this myself as it works fine on two other systems I have but yeah - without that line the emulator is in a working state, I would imagine performance metering isn't as accurate as it should be though.
> 
> @Tru3Man @eyankee01 @Canhardy As you are also affected - would you mind testing the following: Download build 11456 which is the most recent one as of this writing - confirm that it still doesn't open. If so: please replace the EXE file with the one from https://pikachu.moe/rpcs3_exe.7z - this is the current HEAD branch executable compiled with the line above removed.

This work for me!

**Comment by Nekotekina** [comment] 2020-12-22 12:39
I pushed possible fix to master.

**Comment by Tru3Man** [comment] 2020-12-22 14:22
> 
> 
> I pushed possible fix to master.

New build from update 11461 work for me. Many thanks to developers and fix creators!

**Comment by haolink** [comment] 2020-12-22 15:00
I can confirm, it's working again. Thank you for your work on this awesome emulator!

**Comment by Megamouse** [comment] 2020-12-22 16:36
Closing as assumed fixed

**Closed by Megamouse** 2020-12-22 16:36 UTC
Labels: Regression
