### ISSUE TITLE
White Album [BLJM60229] ATRAC3 Verfication failed in sys_cond.cpp:279

### ISSUE THREAD

**Issue by Mirlo** [RPCS3/rpcs3#4485] opened 2018-04-25 15:26 UTC
Using current master build as of 04/25 PR https://github.com/RPCS3/rpcs3/pull/4477
It crashes as soon as I get the press start button prompt.

{PPU[0x100003b] Thread (ATRAC3 Decode Thread) [0x002ef848]} class std::runtime_error thrown: Verification failed: 
(in file Emu\Cell\lv2\sys_cond.cpp:279)

This happens consistently.

[RPCS3.log.gz](https://github.com/RPCS3/rpcs3/files/1947642/RPCS3.log.gz)

**Comment by HorrorTroll** [comment] 2018-04-26 01:37
- F {PPU[0x1000004] Thread (Thread Change Thread) [0x002187a0]} class std::runtime_error thrown: Locking failed (lwmutex=*0x200001a8, owner=0x1000009)
(in file Emu\Cell\Modules\sys_lwmutex_.cpp:181)
- F {PPU[0x100000a] Thread (Sound Fade Thread) [0x002187a0]} class std::runtime_error thrown: Locking failed (lwmutex=*0x200001a8, owner=0x1000007)
(in file Emu\Cell\Modules\sys_lwmutex_.cpp:181)
- F {PPU[0x1000008] Thread (Flip Thread) [0x002187a0]} class std::runtime_error thrown: Locking failed (lwmutex=*0x200001a8, owner=0x1000000)
(in file Emu\Cell\Modules\sys_lwmutex_.cpp:181)
- F {PPU[0x1000007] Thread (VSynch Thread) [0x002187a0]} class std::runtime_error thrown: Locking failed (lwmutex=*0x200001a8, owner=0x1000008)
(in file Emu\Cell\Modules\sys_lwmutex_.cpp:181)
- F {PPU[0x1000000] Thread (main_thread) [0x002187a0]} MEM: Access violation writing location 0x68
- F {PPU[0x1000003] Thread (Thread Manager Thread) [0x002187a0]} class std::runtime_error thrown: Locking failed (lwmutex=*0x200001a8, owner=0x1000009)
(in file Emu\Cell\Modules\sys_lwmutex_.cpp:181)
- F {PPU[0x1000010] Thread (PNG Decode Thread) [0x0021ffe0]} MEM: Access violation writing location 0xd0053f90
- F {PPU[0x1000007] Thread (VSynch Thread) [0x00087f74]} MEM: Access violation reading location 0x2c
- F {PPU[0x1000013] Thread (NowLoading Draw Thread) [0x000a029c]} MEM: Access violation writing location 0x1b
- F {PPU[0x1000009] Thread (Pad Thread) [0x000cbcb8]} MEM: Access violation writing location 0x0
- F {PPU[0x1000009] Thread (Pad Thread) [0x002187a0]} MEM: Access violation writing location 0x68
- F {PPU[0x100000d] Thread (_cellsurMixerMain) [0x002187a0]} class std::runtime_error thrown: Locking failed (lwmutex=*0x200001a8, owner=0x1000007)
(in file Emu\Cell\Modules\sys_lwmutex_.cpp:181)
- F {PPU[0x1000000] Thread (main_thread) [0x000873c0]} MEM: Access violation reading location 0x8
- F {PPU[0x1000013] Thread (NowLoading Draw Thread) [0x002187a0]} class std::runtime_error thrown: Locking failed (lwmutex=*0x200001a8, owner=0x1000004)
(in file Emu\Cell\Modules\sys_lwmutex_.cpp:181)
- F {PPU[0x1000009] Thread (Pad Thread) [0x000cbd38]} MEM: Access violation writing location 0x3

More code like this!

**Comment by JohnHolmesII** [comment] 2018-04-26 08:47
The PR you referenced is not in master, yet you say you are using master. Which is it? If you are in fact using that pr, please post regression info on the pr, and not as a separate issue. This keeps everything trackable and tidy.

**Comment by Mirlo** [comment] 2018-04-26 09:33
Sorry, this isn't a regression.
I thought I was using the master.
It also persists with the actual master.
[RPCS3.log.gz](https://github.com/RPCS3/rpcs3/files/1950556/RPCS3.log.gz)

**Comment by jobs-git** [comment] 2018-04-26 11:05
close and file another?

**Comment by elad335** [comment] 2018-09-07 17:54
duplicate of #3634

**Comment by AniLeo** [comment] 2018-09-07 17:55
Closing as duplicate of #3634

**Closed by AniLeo** 2018-09-07 17:55 UTC
