### ISSUE TITLE
[Feature request] Please make F11 the fullscreen hotkey

### ISSUE THREAD

**Issue by Silent-Remux** [RPCS3/rpcs3#13740] opened 2023-04-23 08:59 UTC
### Quick summary

This is the standard key used for fullscreen in many windows applications.

### Details

F11 currently starts a recording but I think this should be rebound in favour of standard practices. Thank you for considering.

**Comment by Silent-Remux** [comment] 2023-04-23 11:38
Sure that would work too however it seems like a good default considering it's been standard for decades at this point. I don't really mind as long as the end result is that I can use F11 for fullscreen.
________________________________

**Comment by 13xforever** [comment] 2023-04-23 13:07
alt-enter is arguably more standard, as it was introduced way before IE got popular (that's where F11 hot key comes from, I'm pretty sure)

**Comment by AniLeo** [comment] 2023-04-23 13:39
Closing as duplicate of #5681

**Closed by AniLeo** 2023-04-23 13:39 UTC
