### ISSUE TITLE
Persona 5 Battle initiation runtime_error thrown: Invalid location (offset=0x0, location=0xffffffff)

### ISSUE THREAD

**Issue by Monkopeace** [RPCS3/rpcs3#2936] opened 2017-07-02 00:22 UTC
No major issues with cut scenes, animation, or movement. maintain consistent 30-60 fps.

Only issues is with player initiated battle. rsx thread failure.

![image](https://user-images.githubusercontent.com/29826219/27766332-b3d19940-5e9a-11e7-85b8-f0b942100468.png)

CPU: i7-6700k GPU: GTX 1080 OS: Win 10 pro

**Comment by AniLeo** [comment] 2017-07-02 10:52
Are you using a non-master branch / thread pausing?

**Comment by Monkopeace** [comment] 2017-07-03 01:53
I am not using thread pausing, Using the 07/01 Master branch.

**Comment by al0xf** [comment] 2017-07-03 15:35
Let's see what happens with this one as LLE gcm is improved upon. Several similar crashes in the master branch were already fixed with LLE gcm. 

Either way, a stack trace would be useful if anyone can provide it.

**Comment by AniLeo** [comment] 2017-07-13 10:12
Issue was reproduced upstream and we're aware

**Comment by Kratoszx** [comment] 2017-07-13 10:28
I just tried to overcome this error and it can be overcomed with cheat engine speedhack and lowering fps to 5 before starting the battle.  (T-T) is this only way i hope in near future this will be fixed

**Comment by Kratoszx** [comment] 2017-07-14 07:32
found the solution for P5 no crashing no fps drop. all animations, cutscenes and ingame fps 30

https://rpcs3.net/blog/2017/07/13/persona-5-is-now-playable-in-rpcs3/

**Comment by SaltyCucumber** [comment] 2017-08-06 09:18
No longer an issue, since updates are on master.

**Comment by rodjun** [comment] 2017-08-17 00:25
@AniLeo this is fixed

**Closed** 2017-08-17 00:52 UTC
