### ISSUE TITLE
rsx/common: Verification failed in function invalidate_range_impl_base (texture_cache.h:981)

### ISSUE THREAD

**Issue by voidv1** [RPCS3/rpcs3#11074] opened 2021-10-28 21:19 UTC
## Quick summary
After compiling/linking cache PPU/SPU i log to the game and it stops/freezes - black screen/thread stops as log said. Error is
·F 0:05:02.509742 {RSX [0x6a860d0]} SIG: Thread terminated due to fatal error: Verification failed
(in file /plc/fld2/.git/rpcs3/rpcs3/Emu/RSX/VK/../Common/texture_cache.h:981, in function invalidate_range_impl_base<>) (errno=110)

## Details

- RPCS3: latest from git - compiled / binary
- Game: The Last of Us [BCES01585]
- vulkan-headers / vulkan-loader and vulkan-layes - latest from git. build 10/26/2021 ~8pm.
- gcc-11.2.0.
- vulkan or opengl - error the same.
- tested on both gpu's - error the same.
- intel and nvidia drivers are latest.
- don't related to patches, tested with/without them.
- tried different versions of game/different versions of firmware.
Don't find anything about this error. I think i am only one who have this problem?

#### 1. Please attach RPCS3's log.
[RPCS3.log](https://github.com/RPCS3/rpcs3/files/7437330/RPCS3.log)

#### 5. Please provide your system configuration:
* OS                   :   Gentoo with kernel version 5.15.0-rc2
* CPU                 :   i5-9400
* GPU                 :   intel uhd 630 / gtx 1650 Mobile
* Driver version :   xf86-video-intel - latest from gitlab ( 09/20/2021 ) / nvidia-drivers 495.29.05-r1

**Comment by kd-11** [comment] 2021-11-09 18:12
Cannot reproduce this one unfortunately. We'll wait for more reports to come in until we can observe some kind of pattern.

**Comment by kd-11** [comment] 2023-08-01 23:49
This shouldn't happen anymore. Closing pre-emptively. Request to reopen if it can still be reproduced.

**Closed by kd-11** 2023-08-01 23:49 UTC
Labels: RSX
