### ISSUE TITLE
GOD OF WAR 3 BCUS98111 write color buffers bug

### ISSUE THREAD

**Issue by FirefoxinHell** [RPCS3/rpcs3#5714] opened 2019-03-12 19:16 UTC
the last 3 builds have very strange graphical problem when write color buffers its on, the menu intro shake image side to side, and the game have graphical errors likes multicolor dots on same place.

**Comment by kd-11** [comment] 2019-03-13 12:17
Duplicate of https://github.com/RPCS3/rpcs3/issues/5708

**Closed by kd-11** 2019-03-13 12:17 UTC
Labels: Need Information
