### ISSUE TITLE
Yakuza series random freezing in game without any error log

### ISSUE THREAD

**Issue by arcadee1977** [RPCS3/rpcs3#7203] opened 2020-01-06 13:12 UTC
version: 0.0.8 9303

OS: WIN10 1803
8700k 1070ti

Setting:
PPU LLVM+SPU LLVM+vulkan

This issue has existed for a long time and has not been fixed.

**Comment by AniLeo** [comment] 2020-01-06 13:20
Issue doesn't specify a game, there are already several open issues for yakuza games

**Comment by arcadee1977** [comment] 2020-01-06 13:23
Yakuza3 & 4 & Ishin

**Comment by AniLeo** [comment] 2020-01-07 17:45
#4489 is a more complete issue for this discussion , and the report already exists there

Closing as duplicate of #4489

**Closed by AniLeo** 2020-01-07 17:45 UTC
