### ISSUE TITLE
Linux -  recent rpcs3 builds freeze at any game boot

### ISSUE THREAD

**Issue by GitArUs** [RPCS3/rpcs3#9283] opened 2020-11-16 19:38 UTC
RPCS3 freezes immediately after booting any game after commit 0c7f9458. Main window becomes unresponsive. The only way to close it is to press ctrl+c in console window (or kill rpcs3 process). There is nothing interesting in log file, the one I'm attaching is produced by FFXIII-2 at boot.

[RPCS3.log](https://github.com/RPCS3/rpcs3/files/5549210/RPCS3.log)

#### 6. Please provide your system configuration:
* Fedora 32
* i9 9900K
* RTX2700
* 450.80.02
* gcc 10.2.1

Notifying @Shoegzer by request.

**Comment by birdcat87** [comment] 2020-11-20 07:10
So let us take a look at that log:

! 0:00:03.975004 SYS: Disc: /ps3/ffxiii-2/
·! 0:00:03.975005 SYS: Game: /ps3/ffxiii-2/PS3_GAME/
·S 0:00:04.021769 SYS: Updates found at /dev_hdd0/game/BLES01269/!
·! 0:00:04.021780 SYS: [ord:3] Object '11vfs_manager' is destroying
·! 0:00:04.021782 SYS: [ord:2] Object '12patch_engine' is destroying
·! 0:00:04.021807 SYS: [ord:1] Object '12named_threadIN12_GLOBAL__N_122progress_dialog_serverEE' is destroying

So here is what seems to be happening in my non-expert opinion.  RPCS3 is detecting updates for your game, but when it goes to find the updates in the RPCS3 local game folder, it accidentally detects them at a file or folder named !.  ! likely doesn't exist, and because of it nor existing, the virtual file system manager cannot open, the patch engine cannot open, and the progress dialog is locked.  Thus I would recommend turning on the show hidden files option on your file manager, and going to /dev_hdd0/game/BLES01269/ to find a file or folder named !.  If it is there, look in it to see if anything's important.  If nothing is important, delete it.  Then manually download and move your updates to the correct updating folder within BLES01269.  

That might fix your issue, @GitArUs.

**Comment by Megamouse** [comment] 2020-11-20 08:23
@birdcat87 the ! is simply part of the message, not part of the path

**Comment by Shoegzer** [comment] 2020-11-20 15:53
Agreed, that shouldnt have anything to do with this.  

Also thanks for creating this issue @GitArUs.  As you know I was getting the same results in testing more recent commits until RPCS3 stopped compiling altogether in linux, as documented in https://github.com/RPCS3/rpcs3/issues/9271.  That issue is more serious however, and precludes my ability to do any testing at all, but I'll test this one with more precision once that's fixed.

**Test specs:**

- OS: Linux Mint 20, kernel 5.4
- CPU: Intel i7-7700HK
- GPU: Nvidia 1070M, driver 450.80
- Compiler: gcc 9.3.0.

**Comment by GitArUs** [comment] 2020-11-20 16:50
I made a simple comparision of working and non-working builds under gdb. Because commit 0c7f945 was about thread management, I looked what is happening to threads. It seems that after that commit, when I try to start a game, one of threads immediately exits. It is always "Progress Dialog" thread, for example:

Thread 7 has target name 'Progress Dialog'
Thread 7 has target id 'Thread 0x7fff5e5b8700 (LWP 9720)'

after starting game this happens immediately:
[Thread 0x7fff5e5b8700 (LWP 9720) exited]

It happens every time with current build, but never with working builds up to mentioned commit.

**Comment by Nekotekina** [comment] 2020-11-21 02:27
Does AppImage work?

**Comment by GitArUs** [comment] 2020-11-21 08:43
Yes, it does. Crashes in some situations, but that's rather something else.

**Comment by GitArUs** [comment] 2020-11-21 18:32
Seems to be fixed by commit 71f1021.

**Comment by Shoegzer** [comment] 2020-11-21 20:58
I can confirm, this issue seems to be resolved so you can probably close this.  Thanks so much @Nekotekina.

**Closed** 2020-11-21 21:02 UTC
Labels: OS: Linux
