### ISSUE TITLE
NIER [BLUS30481] graphical glitches after PR #5166 (build 7380)

### ISSUE THREAD

**Issue by DanteBC** [RPCS3/rpcs3#5168] opened 2018-09-24 19:29 UTC
RPCS3 v0.0.5-7380-06572c60 Win10
Intel(R) Core(TM) i7-7700 OpenGL, SPU LLVM 
on that build and after there are white triangles on the screen. Issue is present on openGL and Vulkan as well.
![](https://cdn.discordapp.com/attachments/272035812277878785/493853059731030016/unknown.png)
RSX capture:
https://www.dropbox.com/s/xkqhm6jdq5o4obr/BLUS30481_20180924222200_capture.zip?dl=0
Not sure about it's validity, had _E {rsx::thread} RSX: Cannot invalidate a currently bound render target! x2_ error during getting a capture.

**Comment by AniLeo** [comment] 2018-09-24 19:41
Need log file as well or at least indicate the GPU and used drivers

**Comment by ruipin** [comment] 2018-09-24 19:46
I need a log file to debug this. What is necessary to reproduce it? Is creating a new game enough?

**Comment by DanteBC** [comment] 2018-09-24 19:49
> Need log file as well or at least indicate the GPU and used drivers

Sure thing. Log:
[RPCS3.log.gz](https://github.com/RPCS3/rpcs3/files/2412624/RPCS3.log.gz)
RSX capture of that sesstion:
https://www.dropbox.com/s/vu0uncsotah7n4v/BLUS30481_20180924224440_capture.zip?dl=0
Yes, it's reproducable by starting a new game. It's present everywhere.

**Comment by DanteBC** [comment] 2018-09-24 19:54
> This seems to have been caused by my PR, but I need a log file to debug it. What is necessary to reproduce it? Is creating a new game enough?

No, this was before your PR was merged

**Comment by ruipin** [comment] 2018-09-24 19:57
oh, when you said "after build 7380" I thought you meant 7380 still worked. Nevermind then 👍

**Comment by kd-11** [comment] 2018-09-25 04:47
Its a minor glitch; a fix will be made available soon. Also, isnt this a duplicate?

**Comment by kd-11** [comment] 2018-09-25 16:13
Reopening as this is caused by a different reason than https://github.com/RPCS3/rpcs3/issues/5170. This is actually fixed by https://github.com/RPCS3/rpcs3/pull/5175

**Closed** 2018-09-25 19:03 UTC

**Comment by Tutankhamun8080** [comment] 2018-09-30 00:00
Thanks

**Comment by elad335** [comment] 2018-10-12 17:30
Retest if pr #5248 causes the issue to appear again. this should be a proper fix.

**Comment by Asinin3** [comment] 2018-10-12 17:36
This was fixed before already if you mean the triangles. The only issue with NieR i know of was the performance regression. But I'm still getting 30fps in master 
![image](https://user-images.githubusercontent.com/15137035/46884698-49249680-ce45-11e8-991c-893e6adb0741.png)

**Comment by Asinin3** [comment] 2018-10-12 17:45
Confirmed the issue doesn't reappear with your new PR. 
![image](https://user-images.githubusercontent.com/15137035/46885019-3e1e3600-ce46-11e8-87ca-7d4891312038.png)

**Comment by AfterRebelion** [comment] 2019-01-06 16:06
I know necroing this issue will not be well received, but even though the the horrible mess that is seen in OP is not there anymore, some parts of this problem are still present.
In master 0.0.5-7389, when #5175 was implemented, it is visible that there is a purple distorsion on the diagonal axis. It only happens on certain camera angles and directions, so it was really hard to spot it at first glance (I needed more that 10 minutes to make a screenshot of the issue). To anyone that doesn't spot it inmediatelly, its on the upper left side corner, on the sky above the mountains.
![imagen](https://user-images.githubusercontent.com/559819/50738290-83969900-11d2-11e9-99b5-cd1e8d1f7eb1.png)
This was a little annoying, but not gamebreaking, since it happened really rarely. But since PRs got approved, this problem became more and more common. Now take a look at master 0.0.5-7678, the most recent at the time of writing this. The error is still there.
![imagen](https://user-images.githubusercontent.com/559819/50738438-33203b00-11d4-11e9-9a5f-bb65f9d024ac.png)
It's not made clear in the screenshots since it flashes constantly, but it happens all across the diagonal line, like shown in this edited image. That, and the fact that this didn't happen before build 7380, I'm certain that it is caused by the same underlying bug. If you think it is not related, I will open a new issue.
![imagen](https://user-images.githubusercontent.com/559819/50738469-9742ff00-11d4-11e9-9950-1615ad55a675.png)

[RPCS3.log](https://github.com/RPCS3/rpcs3/files/2730608/RPCS3.log)

**Comment by AniLeo** [comment] 2019-01-06 16:43
This looks like the diagonal line AMD/Intel hardware bug. Turn on Strict Rendering Mode and try to reproduce.

**Comment by AfterRebelion** [comment] 2019-01-06 17:33
Yeah, seems like that is the case, since Strict Rendering Mode doesn't have this issue, and it's practically identical to #2976
Any reason why that issue is closed, since it still happens on recent hardware and drivers?

**Comment by MSuih** [comment] 2019-01-06 17:42
1. The issue you mentioned is not related to Nier and thus not relevant to the topic. Diagonal line or rainbow-colored effects when using AMD card plague dozens of games on this emulator.
2. As kd said in that other issue, any graphical issues that disappear when SRM is turned off aren't considered bugs. Disabling SRM decreases accuracy for extra performance, and that will cause issues in some cases.

**Comment by AniLeo** [comment] 2019-01-06 18:18
The issue is closed because it's not our bug. SRM avoids the bug by rendering in a different way essentially, you can find this bug in other software too, just look up "amd driver diagonal line".
