### ISSUE TITLE
[RPCS3] Kingdom Hearts 1.5 Fatal Error

### ISSUE THREAD

**Issue by Jolliapplegirl** [RPCS3/rpcs3#8743] opened 2020-08-17 14:55 UTC
## Quick summary
The game crashes when starting the Wonderland boss fight. The cutscene goes as normal but ends with a black screen as soon as it ends. Closing the window results in the Fatal Error pop-up.

Have tried using Open GL and Vulkan as well as fiddling with the settings. RPCS3 is up to date as well as my drivers.

## Details

When attempting to fight a boss, the game freezes, leaving me with a black screen. When I try to close it, the Fatal error window pops up. 
![1](https://user-images.githubusercontent.com/69805421/90408770-2aa10f00-e05d-11ea-80bb-404d3a6c19db.png)
![2](https://user-images.githubusercontent.com/69805421/90408804-368cd100-e05d-11ea-88ff-57a4078d5c5f.png)

After that, the entire program shuts down.

[logs.zip](https://github.com/RPCS3/rpcs3/files/5084863/logs.zip)

#### 5. Please provide your system configuration:
* Windows 10
* CPU: Intel(R) Core i5 1035G1
* GPU: Intel(R) UHD
* Driver version: 3.11.1.0

**Comment by AniLeo** [comment] 2020-08-18 22:17
This is on an Intel iGPU, someone with a dedicated GPU should try to reproduce this to be sure it's not a driver issue

Alternatively, you can try an Unix distro with Mesa drivers with iris OpenGL driver and anv Vulkan driver

**Comment by Kidarek** [comment] 2020-08-23 18:39
For everyone here that's getting that bug I got an older version of rpcs3 0.0.11-10641 about 45 day old build and got past the black screen. @lamparazul @Jolliapplegirl

**Comment by FarLegend** [comment] 2020-08-28 13:23
So I'm having a regression issue when entering Wonderland, Queen's castle area specifically, on the 10790 version. 
[RPCS3.10790.log](https://github.com/RPCS3/rpcs3/files/5142183/RPCS3.10790.log)

Then I went back to find the exact build which caused regression, turns out it was the 0.0.11-10717 build 
( https://rpcs3.net/compatibility?b&p=3 ) 
[RPCS3.10717.log](https://github.com/RPCS3/rpcs3/files/5142197/RPCS3.10717.log)

This other log is for the build that did not cause regression. 0.0.11-10715
[RPCS3.10715.log](https://github.com/RPCS3/rpcs3/files/5142213/RPCS3.10715.log)

Here's an in-game screenshot for the crash if that's any help
![reg](https://user-images.githubusercontent.com/22748201/91564032-a26a1600-e948-11ea-8f7e-9a2beec528ae.png)

System Configuration:
Microsoft Windows 10 Home Single Language | Version 10.0.18362 Build 18362
Intel(R) Core(TM) i7-6700HQ CPU @ 2.60GHz, 2601 Mhz, 4 Cores
NVIDIA GeForce GTX 960M
16 GB RAM

**Comment by FarLegend** [comment] 2020-08-28 13:41
@Kidarek Could you please check if you also get rendering issues on the older version you're on? I sure do hope it's not only me
![1080](https://user-images.githubusercontent.com/22748201/91566646-a5ff9c00-e94c-11ea-8b4d-4b23edd13838.png) 
It's something similar to this. However, when loading in the area it rarely gets rendered properly, but that usually is not the case. I continued to play a little and reached a certain Hades cut-scene where he's completely invisible, so I'm afraid I'll find something game breaking later on.

**Comment by Kidarek** [comment] 2020-08-28 14:35
@FarLegend I'm definitely not getting any rendering issues on the version that I'm on. I've played about 20 hours the past week and everything looks fine. I've made it to Hollow Bastion so far without any crashes. However, I'm using vulkan so it could be an opengl issue.

**Comment by FarLegend** [comment] 2020-08-28 15:09
@Kidarek I'm definitely on vulkan, and I did test opengl for the sake of it. I've been going through past builds and I'm on 0.0.9 10219, it still has the same rendering issue. But to my surprise this specific issue happens after re-entering the room around 4-5 times on most of the older versions. I guess I'll play on your current version for the time being. Thanks.

**Comment by kd-11** [comment] 2020-08-28 15:47
The regression introduced in PR #8664 was fixed in PR #8696 (Build number 0.0.11-10729). It affected many games not just kingdom hearts. Maybe some corner case remains and is breaking this specific game, I'll need saves of the affected area and precise instructions how to trigger it.

**Comment by Kidarek** [comment] 2020-08-28 15:55
@kd-11 
[BLUS31212-BISLPM66676LAUNCHER.zip](https://github.com/RPCS3/rpcs3/files/5143006/BLUS31212-BISLPM66676LAUNCHER.zip)
Talk to one of the guards in front of the queen. Pick a random evidence box. It doesn't matter the outcome both should have the same error. At the end of the cut scene, the screen should go black and the error should occur.

**Comment by FarLegend** [comment] 2020-08-28 17:08
@kd-11 
[BLUS31212-BISLPS25198.zip](https://github.com/RPCS3/rpcs3/files/5143285/BLUS31212-BISLPS25198.zip)

It's the first save on Queen's Castle. Although my case is somewhat different from Kidarek, I already finished the evidence box scene, and now as soon as I enter the save I crash within 5 seconds, and very rarely I have to play around enter the next room then go back to the previous room which is the Queen's Castle area then I immediately crash.

**Comment by bunni-im** [comment] 2020-09-17 16:57
Same problem here. And right before, the game also crashed when entering the Queen’s castle from bizarre room the first time. Somehow the problem solved itself after visiting the other worlds before returning to wonderland, then changing from vulkan to OpenGL then back to vulkan again (no clue if the fix was the former or the latter action) -of course this didn’t work a 2nd time.

I saw a couple solutions on reddit for this same problem also. I’ve tried enabling strict rendering mode and changing to OpenGL and this doesn’t work for me. Another is to “enable strict texture flushing in the debug menu” but I’m not sure where the debug menu is (I’m sorry I’m a real idiot when it comes to this tech stuff!), and another has something to do with old builds -I suppose like mentioned above -that I also don’t understand..

**Comment by kd-11** [comment] 2020-09-17 18:11
I'm looking into it (see the 'in progress' label) and I should have an answer in a few hours.

**Comment by kd-11** [comment] 2020-09-18 12:34
Retest with https://github.com/RPCS3/rpcs3/pull/8927

**Comment by FarLegend** [comment] 2020-09-18 13:34
There are no crashes around Queen's Castle. I played around that area for a good 20 minutes and it runs smooth. At one point during my playthrough I returned to the build that caused regression out of curiosity and stumbled across the same regression upon entering Atlantica, now that I tested it again with #8927 it seems to be fixed.

**Comment by Asinin3** [comment] 2020-09-18 13:37
So you mean atlantica is fixed with #8927 ? I have had the atlantica crash for months now, just wasn't posted on GitHub.

**Comment by FarLegend** [comment] 2020-09-18 13:45
Yes, there are some things to be noted though. I crashed on entering it for the first time, where a cutscene happens. Now I've returned to it after finishing the whole world, where a cutscene isn't there and it did not crash. You can test it.

**Closed** 2020-09-18 22:56 UTC
Labels: Regression

**Comment by bunni-im** [comment] 2020-09-19 14:38
Really sorry if this is a stupid question, but would anyone be kind enough to spell the solution out for someone who’s clueless abt tech like me? I’ve checked out #8972 and I’m not sure what I’m supposed to do.. Sorry again for the silly request, but I’d love to continue playing. I’d really appreciate it!

**Comment by Asinin3** [comment] 2020-09-19 14:41
@bunni-im Basically, kd-11 opened a changeset which fixed the issue. And now that it's merged it means that the fix is now in the latest builds of RPCS3 from our website. https://rpcs3.net/download

**Comment by bunni-im** [comment] 2020-09-19 15:27
I see! I updated it and it works now, thanks so much you guys are amazing!! And thanks a lot Asinin3 for responding truly appreciated!!
