### ISSUE TITLE
NPEA00275 Tokyo Jungle - Broken lighting

### ISSUE THREAD

**Issue by CarlHalstead** [RPCS3/rpcs3#9428] opened 2020-12-13 15:32 UTC
The lighting appears to be broken as seen in the image below:

https://i.imgur.com/n4w6org.jpeg

Hardware config:

AMD Ryzen 7 2700
AMD Vega 56
16GB DDR4 RAM

Software config:

Radeon driver: 20.9.2

https://i.imgur.com/ad5jfWE.png
https://i.imgur.com/3EADJrc.png

I can add more information as needed. Thanks!

**Comment by digitaldude555** [comment] 2021-02-07 16:30
![Screenshot (326)](https://user-images.githubusercontent.com/26138653/107152786-85fbec00-6972-11eb-9837-cc507ba63f02.png)
Or is it.

**Comment by CarlHalstead** [comment] 2021-02-07 16:49
> ![Screenshot (326)](https://user-images.githubusercontent.com/26138653/107152786-85fbec00-6972-11eb-9837-cc507ba63f02.png)
> Or is it.

Just tested it again with a newly updated RPCS3, same software and hardware configuration as previously tested, same issue.

**Comment by digitaldude555** [comment] 2021-02-07 16:52
I have Nvidia gpu, most likely amd gpu or driver issue..

**Comment by CarlHalstead** [comment] 2021-02-07 16:54
> I have Nvidia gpu, most likely amd gpu or driver issue..

That is what I suspected also. I guess I will have to wait and see.

**Comment by kd-11** [comment] 2021-02-07 16:54
@CarlHalstead Does enabling write color buffers help?

**Comment by CarlHalstead** [comment] 2021-02-07 16:57
> @CarlHalstead Does enabling write color buffers help?

Exactly the same issue: 

Game: https://i.imgur.com/FA3icta.png
Settings: https://i.imgur.com/7y0feEA.png

Thanks for looking at this @kd-11 love the work you do!

**Comment by kd-11** [comment] 2021-02-07 17:10
Unfortunately I don't have a vega card (I'm still sitting on polaris) so I cannot check directly. You can also try and disable native fp16 in the config file. We need more people able to reproduce the issue.
In the meantime generate RSX capture file for debugging purposes and attach it here.

**Comment by CarlHalstead** [comment] 2021-02-07 17:41
> Unfortunately I don't have a vega card (I'm still sitting on polaris) so I cannot check directly. You can also try and disable native fp16 in the config file. We need more people able to reproduce the issue.
> In the meantime generate RSX capture file for debugging purposes and attach it here.

Disabling fp16 has no visible effect, same issue still occurs.

Here is an RSX capture. I have never done it before. I opened the game up to the point where the lighting error occurs (Simply starting a new game) and clicked "Create RSX Capture", is that correct?

[NPEA00275_20210207173829_capture.zip](https://github.com/RPCS3/rpcs3/files/5939582/NPEA00275_20210207173829_capture.zip)

**Comment by kd-11** [comment] 2021-02-07 17:44
@CarlHalstead Thanks, that should be enough.

**Comment by dante3732** [comment] 2021-02-16 14:12
I have this on vulkan 
![image](https://user-images.githubusercontent.com/66036249/108074264-11176900-707a-11eb-923b-00f2a9c9ef53.png)
and this on opengl 
![image](https://user-images.githubusercontent.com/66036249/108074373-2c827400-707a-11eb-98a9-66cbce9010d9.png)

**Comment by CarlHalstead** [comment] 2021-05-23 19:38
Just tested this on my friends setup and he experienced exactly the same issue.

He has:
Ryzen 3 3100
AMD RX 470
16GB 3000MHz

Driver: 20.7.2

**Comment by kd-11** [comment] 2021-05-28 18:45
This is an embarrassing driver bug from AMD side where blending is operating at double rate (0.5 x 1.0 = 1.0 according to their driver)
I'll have to isolate and report to them but for vulkan this is usually a painfully slow affair.

**Comment by Russeus** [comment] 2021-08-19 02:32
Tried to play this amazing game, but still this same issue. Tested on:
Ryzen 5 2400G
RX 5600XT
16GB DDR4
Driver 21.6.1

![tokyo](https://user-images.githubusercontent.com/89173918/129998067-2f656218-f555-423a-9632-a2a895d23b00.png)

**Comment by XeroPanda42** [comment] 2021-11-08 14:20
Made an account to comment that @dante3732 showed that OpenGL does work better for AMD cards that typically run in Vulkan. The only issue I've had since switching to OpenGL is the above-described diagonal graphical gash. Honestly, I'd take that over the super bright literal eyesore that is Vulkan anyday.

**Comment by rudamaia** [comment] 2022-08-07 21:42
Awwww I wanted to play this game so bad.
Vulkan has this bright/gamma issue and openGL is a no go, low fps and this slash thing in the middle of the screen.
Radeon Vega 64 driver 22.6.1 on latest RCPS3

**Comment by lattenjupp** [comment] 2022-08-10 13:46
having the same problems with vulkan, bright af, openGL seems to fix it but low fps and the slash part on screen

**Comment by otterbatch** [comment] 2022-09-16 04:47
Same problem here on driver 22.8.1.

**Comment by rudamaia** [comment] 2022-09-19 21:16
it also happens in OSX, no luck.
<img width="1077" alt="Screen Shot 2022-09-19 at 18 15 21" src="https://user-images.githubusercontent.com/9695456/191118015-79bded4f-1e0e-4ca3-bb20-d043cc041c6f.png">

**Comment by trumad** [comment] 2022-10-15 20:41
I'm currently seeing this issue when playing on Steam Deck

**Comment by kd-11** [comment] 2022-10-16 00:14
I verified this to be a hardware bug. I haven't had enough time to isolate it further for an official report.
We'll also need to know the exact failing inputs to craft a workaround.

**Comment by rudamaia** [comment] 2022-10-16 13:46
Anything you need, I can test it!
When you have the time, of course 👍🏻

**Comment by NicDerHund** [comment] 2022-10-18 23:28
Same issues here
Specs:
Ryzen 5 2600
Windows 10 (current)
16 GB ram
XFX RX5500XT
Driver 22.10.1
RSX:
[NPUA80523_20221018192359_capture.zip](https://github.com/RPCS3/rpcs3/files/9815648/NPUA80523_20221018192359_capture.zip)

![Screenshot 2022-10-18 192420](https://user-images.githubusercontent.com/116126096/196563591-e6d77d1f-176f-4522-ba15-a27d41161b42.png)

Open GL Just shows garbage, should I start a separate issue for that? Really wanna play this with the GF 😄

**Comment by kd-11** [comment] 2022-10-19 02:02
No need. I'll get a workaround out for this soon.

**Comment by NicDerHund** [comment] 2022-10-19 11:59
Sweet, I'll also throw my hat in here on providing any additional captures and info I can get

**Comment by Will-The-Lion** [comment] 2022-10-29 14:25
> No need. I'll get a workaround out for this soon.

Thanks for working on this. I can confirm that on Steam Deck with Vulkan it has the same bright white another user mentioned about steam deck.

**Comment by OliMcGee** [comment] 2022-11-03 10:58
Hi! I'n also on steam Deck and, of course, having the same issue. I'm new to rpcs3. 

Do you guys also have some crackling sound issue?

**Comment by WOOB4T** [comment] 2022-11-22 12:42
> Hi! I'n also on steam Deck and, of course, having the same issue. I'm new to rpcs3.
> 
> Do you guys also have some crackling sound issue?

Same for me on Steam Deck, openGL looks better. But I am also getting a mild crackling with the audio, nothing completely awful just like i'm sat next to a fire 👍

**Comment by AnonBoyage** [comment] 2022-12-26 14:11
Hi all, literally just signed up to say thanks for all the good work investigating this issue. I also have a Steam Deck and am currently exhibiting the lighting issue. I tried OpenGL and while I never experienced the diagonal graphic problem, the FPS is not ad stable as the vulkan branch. Is this something that is still being looked into? I know time and effort goes into these things and truly appreciate anything that comes out of this, whenever that may be!

**Comment by kd-11** [comment] 2022-12-26 22:38
Well, I finally figured out why the visuals are borked here and why they are also broken on MacOS. LogicOP. This is the only game out of thousands that seems to use this feature. If I disable all support for it, the bug appears on NVIDIA as well.
Now that I know its just a missing feature, I can emulate it and close this.

**Comment by kd-11** [comment] 2022-12-26 22:55
Fixed by https://github.com/RPCS3/rpcs3/pull/13132
Some MacOS hardware is incapable of logicOp. However, that shouldn't matter here as the game is using LOGIC_OP_COPY which is the same as simply turning off blending.

**Closed** 2022-12-26 23:56 UTC
Labels: Driver: AMD Vulkan

**Comment by rudamaia** [comment] 2022-12-27 01:41
Thank you Santa 😂❤️

**Comment by AnonBoyage** [comment] 2022-12-27 09:51
This is amazing news. I just updated and can confirm that the lighting issue has been resolved on my end! I cannot thank you enough for taking the time needed to fix this, TJ is actually one of my most played PS3 titles and the ability to play it on my Deck like this means it will be preserved forever in my gaming library.
