### ISSUE TITLE
Regression: Rendering doesn't work on Vulkan on any program (#9782)

### ISSUE THREAD

**Issue by AniLeo** [RPCS3/rpcs3#9784] opened 2021-02-15 13:22 UTC
PR: #9782 

After
![image](https://user-images.githubusercontent.com/10283761/107951700-a3434280-6f90-11eb-93cd-7eae330cc203.png)

Before
![image](https://user-images.githubusercontent.com/10283761/107951741-b35b2200-6f90-11eb-87d3-016f00e9f752.png)

Shows compiling shaders hint permanently too

**Comment by MSuih** [comment] 2021-02-15 13:35
![image](https://user-images.githubusercontent.com/19759300/107953119-52891500-6fa3-11eb-944d-e6f2d995eb43.png)
Cannot reproduce on Windows + AMD

**Comment by Nekotekina** [comment] 2021-02-15 13:35
Narrowed issue, let me try to fix it.

**Comment by Nekotekina** [comment] 2021-02-15 13:52
Fixed in #9783

**Comment by MSuih** [comment] 2021-02-15 14:28
Managed to replicate the bug, it only appears if you don't have existing shader cache.

**Comment by MSuih** [comment] 2021-02-15 15:43
Confirming that this is now fixed, at least in my end.

**Closed by MSuih** 2021-02-15 15:43 UTC
Labels: Regression, Render: Vulkan
