### ISSUE TITLE
Crash when GPU Texture Scaling is enabled

### ISSUE THREAD

**Issue by uaqlover** [RPCS3/rpcs3#5943] opened 2019-05-09 13:52 UTC
![RPCS3_ Fatal Error 09_05_2019 6_42_41 AM](https://user-images.githubusercontent.com/45731484/57458700-a5f2fe80-7226-11e9-8add-daf1c1f88001.png)

if i enable GPU Texture Scaling

it works fine but with graphical issue 

![FPS_ 117 39 _ Vulkan _ 0 0 6-8085 _ Call of Duty Classic  NPEB00101  09_05_2019 6_48_03 AM](https://user-images.githubusercontent.com/45731484/57458861-f79b8900-7226-11e9-8917-e258ba2f2ec6.png)

**Comment by AniLeo** [comment] 2019-05-10 00:27
Isn't this the same issue as #5743 ?

**Comment by AniLeo** [comment] 2019-05-20 00:48
Closing as duplicate of #5743

**Closed by AniLeo** 2019-05-20 00:48 UTC
Labels: Need Information
