### ISSUE TITLE
Regressions after #5436

### ISSUE THREAD

**Issue by MarioSonic2987** [RPCS3/rpcs3#5460] opened 2018-12-26 16:26 UTC
With #5436, there's no skybox and water rendered in Grand Theft Auto IV with OpenGL. In Vulkan, it's improved a bit. Now renders a portion of the skybox textures.

Prior to #5436:
![image](https://user-images.githubusercontent.com/20027681/50450991-92a75c80-0931-11e9-9f45-da0eacdbf528.png)

#5436:
![image](https://user-images.githubusercontent.com/20027681/50450994-9935d400-0931-11e9-8a45-ba57b5e9efad.png)

Vulkan is unaffected:
![image](https://user-images.githubusercontent.com/20027681/50451002-a05ce200-0931-11e9-9aba-dbf2f77b0e0e.png)

[RenderDoc OpenGL](https://drive.google.com/open?id=1nnrzTMHvke_NY1TZixlsb0NFqOkFj7x7)

Note: You have to enable Write Color Buffers to show the reflections.

**Comment by Xcedf** [comment] 2019-04-19 17:56
Found some more regressions in this PR
commit 4b79ef1a
R&C Quest for Booty and Tools of Destruction nanobots rendering issue
before:
![45](https://user-images.githubusercontent.com/7060586/56436198-b1b46a80-62e3-11e9-8308-d64de953eae4.jpg)
After:
![44](https://user-images.githubusercontent.com/7060586/56436222-bf69f000-62e3-11e9-8ea6-6663f536bff4.jpg)

Same commit broke Killzone 3 BCES01007, previous commit worked fine
F {RSX [0x0000000]} RSX: class std::runtime_error thrown: Verification failed: Too many sampler descriptors!
(in file g:\source\rpcs3\rpcs3\emu\rsx\vk\vkfragmentprogram.cpp:171)
To see this issue in menu choose
Campaign->Select Chapter->Evacuation Orders->Rooftop Showdown
![28](https://user-images.githubusercontent.com/7060586/56436445-9007b300-62e4-11e9-9ed2-9d7f5e5493a1.jpg)
Save here:
https://mega.nz/#!2YQB1CQb!MZuYEQMgU2-KbhFDkT15CsOI5kr8C5Fyk9-J9SdugwU

Commit 7555be23
Far Cry 2 BLES00325 Shader compilation issue
E {RSX [0x0000000]} RSX: ERROR: 0:327: '' :  syntax error, unexpected EQUAL
ERROR: 1 compilation errors.  No code generated.

E {RSX [0x0000000]} RSX: 
F {RSX [0x0000000]} RSX: class std::runtime_error thrown: Failed to compile vertex shader
(in file c:\users\zero\desktop\rpcs3\rpcs3\emu\rsx\vk\vkhelpers.h:2803)

**Comment by kd-11** [comment] 2019-04-20 07:20
When shader compilation fails its best to provide a clean shaderlog for analysis. Wipe the shaderlog folder then run the game until it crashes and attach log+shaderlog

**Comment by Xcedf** [comment] 2019-04-20 09:17
Here it is
https://mega.nz/#!WAgkzQCB!01NHEU3Kvzs-fl-KGHnMx1KwfSGHz4sVw2NU2qQMbgU

**Comment by Kravickas** [comment] 2019-04-24 16:10
@Xcedf try #5860 far cry 2 had similar or same error thats fixed now

**Comment by kd-11** [comment] 2019-04-24 17:07
The vertex program error should be gone, but the fragment program assert is intentional, 16 descriptors won't work on MoltenVK and there is no workaround that will ever make this work properly outside of forcing bitcasts which is too expensive. I can lift the restriction since macOS support is not as important, but it is very strange to have that many samplers active at once. Must be one hell of a shader to fill 16 texturing slots even with double-consumption caused by stencil views.

**Comment by Xcedf** [comment] 2019-04-24 17:28
Confirm Far Cry 2 fixed
![22](https://user-images.githubusercontent.com/7060586/56680233-8b217580-66cf-11e9-8fa3-b1734df6c938.jpg)

**Comment by AniLeo** [comment] 2019-07-12 18:12
@MarioSonic2987 can you update GTA V regression?

**Comment by kd-11** [comment] 2019-08-19 22:56
Closing due to inactivity.

**Closed by kd-11** 2019-08-19 22:56 UTC
Labels: Regression

**Comment by MarioSonic2987** [comment] 2019-08-20 08:10
In GTA IV it's worse now.
![image](https://user-images.githubusercontent.com/20027681/63329162-b5a7d600-c331-11e9-84db-2f77588f184a.png)
 
[RenderDoc OpenGL](https://drive.google.com/open?id=1tTr2y8eh8MCaKF04iXVjsDHiiJVhErYY)
