### ISSUE TITLE
Regression: Performance loss in pretty much every game (#8713)

### ISSUE THREAD

**Issue by Yahfz** [RPCS3/rpcs3#8976] opened 2020-09-25 17:52 UTC
It seems to be two different regressions so far. 

the first regression was in #8713, that made the fps go from 36 to 33-34. (seems to be nvidia only)

Then the other i still have to bisect and i'll be updating this issue later with more information.

I'd appreciate more testers just in case, preferable those who aren't that spu limited.

**Comment by mika123565** [comment] 2020-09-26 05:22
I am not sure if that is relevant or not...
https://github.com/RPCS3/rpcs3/issues/8587

**Comment by Yahfz** [comment] 2020-09-27 09:30
Apparently all the games were affected and not only nvidia

https://cdn.discordapp.com/attachments/442667232489897997/759707612706766858/unknown.png

**Comment by lextra2** [comment] 2020-09-28 07:56
nvidia driver tag should be changed since OP shows performance regression with an all amd desktop.

**Comment by kd-11** [comment] 2020-09-28 12:34
Need bisecting to identify which changes reduced performance as it was not caused by one change. Some of the changes identified are not going to be reverted as they add missing functionality, but it has been said there are several stages where the issue slowly built up.

**Comment by xddxd** [comment] 2020-09-28 12:41
From my testing on nfs carbon, first regression was caused by #8713, then by #8778, then performance was slightly improved by #8769, as of build 10800 performance is the same as on master

**Comment by kd-11** [comment] 2020-09-28 13:44
I have a feeling the performance problem was not caused by the code change. The ABGR layout that had support added in https://github.com/RPCS3/rpcs3/pull/8713 is very rarely used, and all the PR did was map that to RGBA layout. Initially I thought it may be a driver optimization problem but if it is observed in every game that is certainly not the cause then.
There really isn't much we can do about msvc derping out, maybe windows clang builds can be used for releases. I'll see about compiling a build with #8713 reverted using the same compiler before and after and see if it still has an observable difference. Unfortunately its unlikely that we end up reusing the clusterfuck that is BGRA8->ARGB8 mapping as that is also going to be slow as compute shaders are required to bridge the two when doing CPU readback.

**Comment by Xcedf** [comment] 2020-10-19 14:23
Reverted only VKGSRender and VKFormats from 2305d6ed of https://github.com/RPCS3/rpcs3/pull/8713 to get my 2 fps of RDR back, hope it'll help

**Comment by Yahfz** [comment] 2020-10-19 14:32
Performance went from 36-37 (back when I made this issue) to around 30 flat in the latest master. Honestly if anyone wants to look into the other regression be my guest, kinda lost motivation to do so, but one of them is caused by AGBR and its a driver/hardware issue.  

https://www.dropbox.com/s/u4xfiv3u6kpa2l6/rpcs3-rgba-vs-bgra.7z?dl=1

You can test these builds and you'll notice that your fps with BGRA will be higher. This is confirmed to be an issue with pascal, no idea if it happens on other architectures.

**Comment by kd-11** [comment] 2020-10-19 18:54
Just to add to this: another performance drop happened when visual studio compiler was changed in azure. For this reason locally compiled builds are slightly faster than azure builds.

**Comment by kd-11** [comment] 2020-12-06 18:30
Nvidia driver performance issue is fixed. See https://github.com/RPCS3/rpcs3/issues/9173

**Comment by RipleyTom** [comment] 2020-12-10 00:26
https://github.com/RPCS3/rpcs3/pull/9295 was merged so the regression from #8778 should be gone.

**Comment by dio-gh** [comment] 2021-07-21 01:34
Gonna be a bit cheeky, but still an issue?

**Closed** 2021-09-10 09:25 UTC
Labels: Need Information, Regression
