### ISSUE TITLE
Dragon Ball Z: Budokai HD Collection crashes when a game in the collection is selected

### ISSUE THREAD

**Issue by blkarcher77** [RPCS3/rpcs3#9278] opened 2020-11-16 03:07 UTC
## Quick summary

When I try to select a game inside of the Dragon Ball Z: Budokai HD Collection, the window stops responding, and I get an error window saying "Stopping emulator took too long. Some thread has probably deadlocked," after which the entire emulator closes.

## Details

I'm having issues launching Dragon Ball Z: Budokai 3. It's in the DBZ Budokai HD Collection. When you launch the game, it asks you which game you want to launch, Budokai 1 or Budokai 3. Up to here, it works perfectly fine. It's when I select either of the games that an error window pops up, saying "Stopping emulator took too long. Some thread has probably deadlocked." I then press ok, which then closes the entire emulator.

#### The Log

[RPCS3.log](https://github.com/RPCS3/rpcs3/files/5543845/RPCS3.log)

#### System configuration:

Windows 10 1903
Intel Core i7-6700K | 8 Threads 
15.95 GiB RAM  
TSC: 4.008GHz 
AVX+ 
FMA3 
TSX
GeForce GTX 980 Ti (456.71)

**Comment by CrustTF2** [comment] 2020-11-19 14:01
I would like to add my log file to this as well, since I'm having the same issue.

[RPCS3.log](https://github.com/RPCS3/rpcs3/files/5567163/RPCS3.log)

**System configuration:**
Windows 10 19042
AMD Ryzen 5 3600 | 12 Threads
32 GB DDR4 3600MHz RAM
TSC: 3.600 GHz
AVX+
FMA3
GeForce GTX 1070 Ti (456.71)

**Comment by ThirdofOne** [comment] 2020-11-22 06:15
I am also experiencing this issue.

**System configuration:**

Windows 10 20H2
AMD Ryzen 9 5950X | 32 Threads
31.93 GiB RAM DDR4 3600MHz RAM
TSC: 3.400GHz
AVX+
FMA3
GeForce RTX 2080 Ti (457.30)

[RPCS3.log](https://github.com/RPCS3/rpcs3/files/5579053/RPCS3.log)

**Comment by Satan86** [comment] 2020-12-01 04:47
since this is a regression, we need to know the exact emulator version that broke the game.

**Comment by blkarcher77** [comment] 2020-12-01 23:44
I have tested a bunch of versions, and I found that version 0.0.13-11248 is where it stops working. 0.0.13-11244 can launch the game no problem

**Comment by Gael2433** [comment] 2020-12-10 10:32
It would seem that the binaries for the individual games in the collection are just named DBZ1.BIN and DBZ3.BIN instead of .self like almost all other collections with a launcher, perhaps this is confusing the emulator?

**Comment by ThirdofOne** [comment] 2020-12-10 11:47
It would seem so. It happens to crash after a user selects Budokai 1 (DBZ1.BIN) or Budokai 3 (DBZ3.BIN).

**Comment by nabeelA-34** [comment] 2020-12-24 22:11
I've got the same problem as well, I tried running it on 0.0.13-11470 and it still crashes

**Comment by quackerjack25** [comment] 2020-12-24 22:14
I've got the same problem as well I tried running on 0.0.13-11470 and it still crashes after you choose which game you would like to play

**Comment by AphelionWasTaken** [comment] 2021-02-18 19:06
Fixed as of #9208 
![image](https://user-images.githubusercontent.com/61633628/108407837-e3e9c880-71e9-11eb-8147-aaaa7c4d8194.png)

**Closed** 2021-02-18 19:11 UTC

**Comment by GPery** [comment] 2023-02-26 14:28
Getting this happening now on Steam Deck with RPCS3 version 0.0.26-1-3388c8ed Alpha installed over flatpak. 
However, instead of the window freezing it just crashes, and RPCS3 itself stops responding.
Anyone have a clue on how to fix it?

[RPCS3.log](https://github.com/RPCS3/rpcs3/files/10833902/RPCS3.log)


System configuration:
SteamOS 3.4.4 (linux 5.13.0-valve36-1-neptune)
Processors: 8 × AMD Custom APU 0405
Memory: 14.5 GiB RAM
Graphics Processor: AMD Custom GPU 0405
