### ISSUE TITLE
[Linux only] Persona 5 [NPEB02436] freeze only when using Vulkan Mesa driver in a specific section of the game

### ISSUE THREAD

**Issue by Lukypie** [RPCS3/rpcs3#6358] opened 2019-08-16 17:06 UTC
**Bug description:**

The emulator locks up only on Linux and only when using the Vulkan renderer, it works fine with OpenGL and with Vulkan on Windows.

No errors are shown

95% of the times it locks up in the same section I have tested so far, in the Madarame's fight section of the game, the final dialogue before getting to the boss scene then it locks up. Sometimes it reachs the boss scene, other times it locks up even before or after.

Only the game music sound can be heard, no interactivity can be made,

![Schermata da 2019-08-16 18-11-23](https://user-images.githubusercontent.com/7904559/63182918-fc58b000-c053-11e9-965f-753848807123.png)

**What I have tried so far:**

- Changing the Vulkan Mesa driver, drivers tested: LLVM 9.0 padoka ppa, Valve Mesa ACO
- Changing basically most of the emulation options you can think, enabled xfloat, changed size of the PSU size, change LLVM recompiler to the older one, etc...
- Tried to pause and unpause the game and the specific threads through the debugger

**Workaround**
 
The only workaround I found is using windows or switching to the OpenGL renderer or use AMDVLK as Vulkan driver

**Comment by kd-11** [comment] 2019-08-16 17:11
Does it work with AMDVLK or AMGPU-pro?

**Comment by Lukypie** [comment] 2019-08-16 18:10
> ~Does it work with AMDVLK or AMGPU-pro?~ Nvm I saw it works. Ok, I'll try and isolate for the mesa team.

Forgot to say I'm on ubuntu 18.04.3 and since drivers are compiled with LLVM 8.0.0 the RPCS3 vulkan renderer is broken, those are the specific PPA's I've tried

https://launchpad.net/~paulo-miguel-dias/+archive/ubuntu/mesa
https://launchpad.net/~valve-experimental/+archive/ubuntu/mesa-bionic

**Comment by kd-11** [comment] 2019-08-16 18:14
You should provide a save to help in reproducing the issue. Just zip the files in /dev_hdd0/home/000001/savedata which are related to the game and attach.

**Comment by Lukypie** [comment] 2019-08-16 18:43
> You should provide a save to help in reproducing the issue. Just zip the files in /dev_hdd0/home/000001/savedata which are related to the game and attach.

No problem, take the first at the top which should be right in the madarame steal the tresure section
[saves.zip](https://github.com/RPCS3/rpcs3/files/3510760/saves.zip)

**Comment by GitArUs** [comment] 2019-08-19 13:26
Have You Multithreaded RSX option turned on or off ? It was happening for me (exactly in this moment) when i had it turned on.

**Comment by kd-11** [comment] 2019-08-19 13:33
It was caused by MTRSX. I'll close this issue soon (as soon as I push the patch for it, but I'm trying to group together a few fixups first)

**Comment by Lukypie** [comment] 2019-08-19 14:07
Interesting... I completely forgot about it, sorry

**Closed** 2019-08-25 19:09 UTC
Labels: OS: Linux
