### ISSUE TITLE
Lollipop Chainsaw [BLUS30917] cutscene and boss fights pink/green gfx bugs

### ISSUE THREAD

**Issue by k10kan** [RPCS3/rpcs3#5904] opened 2019-05-01 18:59 UTC
Issue #4859 was partially fixed by PR #5785, and now the whole game is playable, all cutscenes and boss fights are visable, except that some cutscenes and boss fightsnow have gfx bugs (pink/green):

  * (a) have no gfx corruption, but later on become pink/green
  * (b) alternate between good rendering and pink/green
  * (c) always ping/green gfx corruption

Manifestation  of gfx bugs depend on in game stage/level number (1-6) and on boss type. This issue happens only during some ingame in-engine cutscenes and with some boss fights.

Worth noting is that gfx bugs are present in both OpenGL and Vulkan renderers, but with Resolution Scale set to >100% (I tested 150%).

With Resolution Scale 100% there are no rendering issues in cutscenes and boss fights.

All other parts of this game are rendered properly (with addition of Resolution Scale Threshold set to 512x512).

Tested on latest build 0.0.6-8051-6b7cd458.

It is time consuming to reach the bosses, but every stage has intro cutscene where problem could be debugged (at least, I hope so) and that can be loaded from stage menu.

I am providing save game with unlocked all stages. Suggested intros in stages:
  * Fulci Fun Center - (c) type
  * O'Bannon Farm - (b) type
  * Stadium - (a) type

Savegame file:
[BLUS30917-AUTOSAVE.zip](https://github.com/RPCS3/rpcs3/files/3135632/BLUS30917-AUTOSAVE.zip)

(_Start game and if asked, select NOT to start from last checkpoint in order to reach stage selection map._)

Here are RDC captures (RenderDoc 1.4):
Build: **rpcs3-v0.0.6-8051-6b7cd458_win64**
Setting: **Default + Vulkan + RS: 150% + RST: 512x512**

**RDC_1 in Stage: Fulci Fun Center**
![Lollipop Chainsaw - Stage Fulci Fun Center #1](https://user-images.githubusercontent.com/37659629/57035516-8bcb8600-6c52-11e9-95d1-b86416520611.jpg)
File is 302MB, so use provided link (link valid for 30 days, download speed ~350KBps)
https://ufile.io/0dgtf3ep

**RDC_2 in Stage: Fulci Fun Center**
![Lollipop Chainsaw - Stage Fulci Fun Center #2](https://user-images.githubusercontent.com/37659629/57035519-90903a00-6c52-11e9-9078-4000de9ff2a7.jpg)
File is ~613MB, so use provided link (link valid for 30 days, download speed ~350KBps)
https://ufile.io/iotzdgxu

For comparison, this is Stage: Fulci Fun Center on old build **0.0.5-6461-d78b0467** and this screenshot is frozen during whole intro.
![rpcs3-v0 0 5-6461-d78b0467_win64](https://user-images.githubusercontent.com/37659629/57036058-8ae72400-6c53-11e9-80ad-10167921c36d.jpg)

In latest build whole intro is visable, but in pink/green colors and it feels like fixing this would bring Lollipop Chainsaw to 100% working title. Fingers crossed...

**Comment by k10kan** [comment] 2019-05-14 20:30
Before a true solution is implemented, one can resolve aforementioned problem by using:

- **Write Color Buffers**
- **Force CPU blit emulation (DEBUG)**

For best experience one can enable preferred **Resolution Scale** with **Resolution Scale Threshold 512x512**.

**Comment by nitroos-ai** [comment] 2022-02-02 02:41
Can this be closed? Looks playable. https://www.youtube.com/watch?v=7upYm3D_oTE

**Comment by jokoputera** [comment] 2022-04-10 04:23
@k10kan please retry and close it if its fixed

**Comment by ruanformigoni** [comment] 2022-06-12 22:51
Hello, issue not fixed, latest version on arch linux. Using the workaround of @k10kan fixes the issue.

**Comment by Asinin3** [comment] 2023-01-14 00:50
"With Resolution Scale 100% there are no rendering issues in cutscenes and boss fights."
Then the issue is to be closed as issues with resolution scaling are not tracked unless they are a regression. While its rare that games don't work with it, Res scaling is a hack and it will always have problems with specific games that do things in strange ways.

**Closed by Asinin3** 2023-01-14 00:50 UTC
