### ISSUE TITLE
Emulation slowing down after a few game restarts (increasing RSX guest utilization)

### ISSUE THREAD

**Issue by spiraluc** [RPCS3/rpcs3#11023] opened 2021-10-17 11:56 UTC
With the fresh start of RPCS3, games run much faster (less usage of RSX/more FPS) than after a few more stop/starts without closing RPCS3.

I tried it for example on the game Project DIVA F & F 2nd. 

First I started the game, then got to choose from the music menu, started it and let the game lose and returned to the menu. Then I clicked stop and started the game again.

**Here are some photos where you can see the growth of RSX usage and FPS drop**(I have slow HW, so it's more visible there):

**Project DIVA F1 fresh start**
![PD F1 fresh start](https://user-images.githubusercontent.com/54077874/137625708-dd7c832c-3572-451c-9d4b-0ef44f266ac9.png)
**Project DIVA F after 3 restarts**
![PD F after 3 restarts](https://user-images.githubusercontent.com/54077874/137625721-1c7ba099-0f9c-4f8b-8b24-19c12059874c.png)
**Project DIVA F after 6 restarts**
![PD F after 6 restarts](https://user-images.githubusercontent.com/54077874/137625732-a19c3647-a151-4a8d-9e0e-dc259ebc4df5.png)
**Project DIVA F2 fresh start**
![PD F2 fresh start](https://user-images.githubusercontent.com/54077874/137625796-fa90ee5d-b9cc-4df5-bb09-3c34a0ea915f.png)
**Project DIVA F2 after a few game starts**
![PD F2 after a few game starts](https://user-images.githubusercontent.com/54077874/137625799-7c015c11-d390-43c5-ac93-5e2c82ea3ed5.png)

[RPCS3 several game starts.log](https://github.com/RPCS3/rpcs3/files/7359791/RPCS3.several.game.starts.log)
[RPCS3 Project DIVA F2 fresh start.log](https://github.com/RPCS3/rpcs3/files/7359793/RPCS.3.Project.DIVA.F2.fresh.start.log)

CPU: Intel core i5 2430M
GPU: NVIDIA GT525M (openGL 4.6 only) (driver v391.35) 
RAM: 8GB
WIN 10 (v21H1)

**Comment by Darkhost1999** [comment] 2021-10-19 20:08
From what I gather it shouldn't matter what game I ran. So since I don't have Diva F & F 2nd or whatever. I tried a simple Lego Harry Potter.

Vulkan had a range from 30%-90% guest usage on first launch while compiling shaders.
2nd launch was about 85%
3rd was 55%
4th 50%
5th was about a 40% at the same point.
Without closing rpcs3 and continuing to OpenGL directly.
OpenGL is 60%.
2nd 50-55%
3rd 45-53%
And progressively decreasing the more I launch.
All of the percentages were taken from when the dementors fly around the castle if during the splash screen cutscene I never had guest above 15%.

GTX 1660S. 
So as well I can not reproduce an increase in guest utilization rather it is quite the opposite with a decrease the more consecutive boots of the same game.

**Comment by Darkhost1999** [comment] 2021-10-19 20:34
No fps remained the same full speed 60 fps that the game performs every time. Regardless of what the guest utilization was.

**Comment by Megamouse** [comment] 2021-11-16 00:53
Needs retest. Some fixes were made that might or might not affect how games behave between consecutive runs.

**Comment by Megamouse** [comment] 2022-02-11 23:30
Closing due to inactivity

**Closed by Megamouse** 2022-02-11 23:30 UTC
Labels: Need Information, Render: OpenGL, Discussion
