### ISSUE TITLE
[BCUS98111] God Of War 3 hangs

### ISSUE THREAD

**Issue by Wagnard** [RPCS3/rpcs3#6988] opened 2019-11-13 17:37 UTC
RPCS3 0.0.7-9128-8e39c778

Playing God Of war 3 is giving more than usual  RSX: nv406e::semaphore_acquire has timed out. semaphore_address=0x60300510 errors than a few revision back.
Of course this message is freezing the game.
TSX is disabled on my end and i'm using Write Color buffers.
Vulkan renderer, 
PPU: LLVM
SPU LLVM

I have played with the config.yml "  Driver Recovery Timeout" value but it only push back the inevitable. I must set huge value to have some resonable playtime before a freeze with the semaphore error.

This is not a request or anything, just reporting in.
Nice work so far.

[RPCS3.log.gz](https://github.com/RPCS3/rpcs3/files/3842601/RPCS3.log.gz)

**Comment by 13xforever** [comment] 2019-11-13 20:11
duplicate of #3986

**Comment by Wagnard** [comment] 2019-11-13 21:11
> duplicate of #3986

Not quite sure, it depends if in #3986 this was avoiding the issue or just delaying it.
And this is more frequent since the RSX updates(or around theses) from a couple of days ago.

**Comment by elad335** [comment] 2020-01-25 06:39
It can be workarounded with rsx wake-up delay iirc.

**Comment by Xcedf** [comment] 2020-02-22 01:50
This one should be fixed by now with Accurate RSX reservation access.

**Comment by Wagnard** [comment] 2020-02-22 12:14
Will try. I already know that rsx wake-up delay seems to work around it.

**Comment by Wagnard** [comment] 2020-03-02 15:03
Seem to work, but problem is that it give a big hit on FPS (+-15 fps less).
It is preferable to use the rsx wake-up delay

**Comment by Xcedf** [comment] 2020-03-02 19:05
It's just the way it works for now on non-TSX Cpus, perhaps will be better someday.

**Comment by AniLeo** [comment] 2020-03-20 19:21
Fixed by accurate RSX reservation access, therefore closing

**Closed by AniLeo** 2020-03-20 19:21 UTC
Labels: Need Information

**Comment by Wagnard** [comment] 2020-03-23 20:15
@Xcedf True , I have a 9900k CPU but GOW will hang randomly with TSX enabled.
Anyway thanks for the hard work you guys are doing.
