### ISSUE TITLE
Crash emulator error

### ISSUE THREAD

**Issue by BlackRocksShooter** [RPCS3/rpcs3#1738] opened 2016-06-01 13:02 UTC
And three days that while playing a game after 3-5 min I goes crashing giving me this error in the "Log"
{PPU[0x8] Thread (main_thread) [0x009c96ac]} sys_fs: sys_fs_stat('/dev_bdvd/PS3_GAME/USRDIR/rom/objset/itmpv/itmpv612.farc') failed: not found
{PPU[0x109] Thread (200baad0) [0x009c964c]} PPU: Function 'cellFsRead' aborted
{PPU[0x109] Thread (200baad0) [0x009c964c]} class fmt::exception thrown: Win32 error: 998.
(in file C:\rpcs3\Utilities\File.cpp:744)
There is a way to try to not get this error during the game?

**Comment by Nezarn** [comment] 2016-06-01 13:50
duplicate of #1466

**Comment by raven02** [comment] 2016-06-11 11:36
please close this one.

**Closed** 2016-06-11 13:58 UTC
