### ISSUE TITLE
PlayStation Eye Camera not work

### ISSUE THREAD

**Issue by adastmin1** [RPCS3/rpcs3#16384] opened 2024-12-08 17:30 UTC
### Quick summary

I connected the original PS3EYE camera from the PS3 and it doesn't work, and I also connected a third-party camera and it doesn't work either. The game asks to connect the PS3EYE camera.

### Details

I connected the original PS3EYE camera from the PS3 and it doesn't work, and I also connected a third-party camera and it doesn't work either. The game asks to connect the PS3EYE camera.

### Attach a log file

[Uploading RPCS3.log…]()

**Comment by FlexBy420** [comment] 2024-12-08 18:04
Duplicate of #14455

**Closed** 2024-12-08 21:18 UTC
