### ISSUE TITLE
Resolution Scale doesn't work on multiple titles. 

### ISSUE THREAD

**Issue by Nikorasu95** [RPCS3/rpcs3#5753] opened 2019-03-21 20:44 UTC
I'm using the latest RPCS3 which is 0.0.6-7888. No matter what percentage I set the Resolution Scale to, the results are always the same. The threshold setting also doesn't help. In full screen the results are always the same, the graphics are pixelated both with OpenGL and Vulkan and with Async Shader Compiler enabled/disabled..  The games I tested so far with these issues are:

Prince of Persia Trilogy HD  "all 3 games"  [BLUS30754]
ICO and Shadow of the Colossus "both games" [BCUS98259]
Flower [NPUA80083]
Journey [NPUA80275]
Resident Evil 0 [NPEB02226]
SoulCalibur V [BLUS30736] "Pixelated in menu always. Depending on the Fighting RING chosen, pixelation can vary. 
Wakeboarding HD [NPUB30098]
Eternal Sonata [BLUS30161]  Looks great at the beginning of the game! It's only when you get to the first village "Tenuto"  that the graphics are pixelated. From here on out the game is pixelated even becoming more pixelated at "Ritardando" where you first take control of Allegretto and Beat. 

Here are links to images showing the issue. All images were captured at a screen resolution of 4K/UHD 3840x2160:

Prince of Persia Trilogy HD:  https://i.postimg.cc/8pKb2MJx/Base-Profile-Screenshot-2019-03-21-15-46-28-28.png

Shadow of the Colossus: https://i.postimg.cc/4sCcmWgB/Base-Profile-Screenshot-2019-03-21-15-51-09-64.png

Eternal Sonata: https://i.postimg.cc/ZZNBt6d3/Base-Profile-Screenshot-2019-03-21-16-38-36-89.jpg

My specs:
i9 9900K
GTX 1080 Ti
16 GB DDR4
Windows 10 Pro x64 (Version 1809)

**Comment by Emulator-Team-2** [comment] 2019-03-21 20:58
I leave here a link to the old issue:
https://github.com/RPCS3/rpcs3/issues/4341

**Comment by Nikorasu95** [comment] 2019-03-21 21:12
> I leave here a link to the old issue:
> #4341

Dang, I forgot all about that. Thanks for reviving that old issue.. Are you really able to just go in my profile and see my older posts?? How embarrassing. I wish there was a way to delete them.

**Comment by Nikorasu95** [comment] 2019-03-22 02:36
@Emulator-Team-2, why do 2 people find your comment funny? I feel like I'm being attacked/made fun of here.

**Comment by RainbowCookie32** [comment] 2019-03-22 04:32
I posted the confused emoji just because of that. I'm confused. I don't see how people finding this situation kind of funny is being rude or qualifies as attacking someone. I really think you are overreacting here

**Comment by Nikorasu95** [comment] 2019-03-22 04:45
Because I don't see why his comment was so funny that 3 people had to react to it. I feel like I'm being thought of as a dumb person and being laughed at because of the old issue that I forgot I had created.

**Comment by RainbowCookie32** [comment] 2019-03-22 04:50
I never thought of that comment of you being dumb. I laughed because I
could see myself on that as I have very fragile memory, that was why it was
kind of funny to me. I won't continue this conversation as I don't want to
keep spamming notifications around, but I will make the final note that I
think this is being blown out of proportion

**Comment by Emulator-Team-2** [comment] 2019-03-22 05:22
@Nikorasu95 
KD-11 has already explained this in your old issue, so that's why I added a link to the old issue.

**Comment by Asinin3** [comment] 2019-03-22 07:21
Can you please just close this issue since it's a duplicate of an already closed issue and doesn't classify as a proper bug (see reasons why in the other issue). No need to overreact because some people clicked an emoji. I don't see why you would open a new issue when your old one was closed for a good reason and explained why. You're just spamming the issue tracker at this point, which is probably why people found it funny. But this is just going to annoy developers if people keep re-opening a new issue when their old one was closed for a good reason.

**Closed** 2019-03-22 16:13 UTC

**Comment by Nikorasu95** [comment] 2019-03-22 21:51
> You're just spamming the issue tracker at this point
Jeez, how could you possibly think such as thing??? I didn't make this post with the intention to spam. As I already said before "forgot about the issue I created previously". Why are people on Githhub always making assumptions???

**Comment by Nikorasu95** [comment] 2019-03-22 21:52
> You're just spamming the issue tracker at this point


Jeez, how could you possibly think such as thing??? I didn't make this post with the intention to spam. As I already said before "forgot about the issue I created previously". Why are people on Githhub always making assumptions???

**Comment by Nikorasu95** [comment] 2019-03-22 21:54
I just don't see how you people can not consider this a bug considering how some games work and some doesn't. Seems like RPCS3 will never be consistent like Dolphin, PCSX2, Citra, and PPSSPP with the resolution.

**Comment by Nikorasu95** [comment] 2019-03-22 21:56
@RainbowCookie32, you are a very unethical individual! I see what you did there! Adding a confused emoji for no logical reason!

**Comment by Nikorasu95** [comment] 2019-03-22 21:58
Like I said before, people on Github are unethical, and inconsiderate of others. Basically trolls I say. I know, I researched it and there are complaints about the unmoral behavior.

**Comment by HerrHulaHoop** [comment] 2019-03-22 22:05
You realise every message you send here gives a notification to our discord server with 40K members. Please stop replying to a closed issue.
