### ISSUE TITLE
Demon Souls save crash

### ISSUE THREAD

**Issue by GarettJaxx** [RPCS3/rpcs3#5481] opened 2018-12-31 14:56 UTC
I'm experiencing an odd issue - when DeS autosaves, it appears to create '.backup' and '.working' temporary directories of the save folder under 'Home\00000001\', however for some reason I have started to randomly see the following error message which results in an insta-crash when the emu tries to do this:

F {PPU[0x1000019] Thread (SLSession) [0x00b0c060]} class std::runtime_error thrown: Failed to move directory D:/Emulation related/PS3/home/00000001/savedata/../.working_BLES00932DEMONSS005/

I keep the game discs on a seperate drive for space reasons and have done for a long time - so dev_hdd0 points to this drive instead of the default in the VFS menu and has never caused an issue before, so I don't think it's that (I've also completed DeS using older RPCS3 versions and this setup). There is 606gb free on that drive too, so space isn't an issue....

the only way I can get the game to run again is to rename the '.working' folder back to the BLES...005 name and move it back into the Savedata folder. This seems to be random and doesn't always happen - any ideas? Log attached - thanks in advance

[RPCS3.log.gz](https://github.com/RPCS3/rpcs3/files/2718472/RPCS3.log.gz)

Using: RPCS3 v0.0.5-7642-632b0f48 Alpha | HEAD
Spec: Intel(R) Core(TM) i7-7700K CPU @ 4.20GHz | 8 Threads | 15.93 GiB RAM | AVX+ | TSX
OS: Win 7 Ultimate

**Comment by GarettJaxx** [comment] 2019-01-02 18:55
No worries - hope so!

and thank you for the info, hadn't seen it beforehand :)

**Comment by nitrohigito** [comment] 2019-01-02 19:01
@GarettJaxx Please test that PR and post your results there (whether it fixed this or not).

**Comment by GarettJaxx** [comment] 2019-01-02 19:52
Will do - just downloaded '0.0.5-55c66b27' entitled "cellSaveData: workaround possible issues with symlinks" which seems to be the issue I'm having (#5453 references multiple fixes and this is only one of them)

will report back progress ASAP.....

**Comment by cvasquez311** [comment] 2019-01-13 17:37
Can confrim this is still an issue for me and Katamari Forever with the latest HEAD build/compile.

I rolled back to 0.0.5-7388-dab30c00 and the problem does not occur.

So there was regression between 0.0.5-7388-dab30c00 and HEAD.

**Comment by GarettJaxx** [comment] 2019-01-14 20:09
just tested the new PR (7727) for over and hour with no issues, so am closing this as it appears to be resolved.

Thanks guys!! :+1:

**Comment by Megamouse** [comment] 2019-01-14 20:10
will have to be closed after the merge

**Comment by GarettJaxx** [comment] 2019-01-14 20:17
Apologies MM - I thought that when the PR was available to download from the "Builds" page it effectively had been merged (so, my bad!)

How do I know when this PR has been merged? (apologies for the ignorance - still picking up the jargon etc.)

**Comment by RainbowCookie32** [comment] 2019-01-14 20:19
The PR status will change from Open to Merged

**Comment by Megamouse** [comment] 2019-01-14 20:21
hmm i think that actually was the new build.
You simply called it PR build which confused me.

This one?
![image](https://user-images.githubusercontent.com/23019877/51138802-5edd9980-1842-11e9-8b4a-a63a545dafc0.png)

**Comment by GarettJaxx** [comment] 2019-01-14 20:23
Ok... well looking on the "Cache changes #5453" page - which this fix is part of - it does say "Merged" at the top of the page??

**Comment by GarettJaxx** [comment] 2019-01-14 22:10
Looks like I spoke too soon - save issue reared it's ugly head again I'm afraid :(
(Played for a good while before it did though)

[RPCS3.log.gz](https://github.com/RPCS3/rpcs3/files/2757253/RPCS3.log.gz)

**Comment by cvasquez311** [comment] 2019-01-14 22:37
dang, want me to test katamari for an hour and upload crash log too on the latest PR?

Would be nice to get this fixed.  Tell me how i can help! I really want to use the latest rather than a rolled back version.

I had a crash recently on the rolled back version but not for the same error listed in here, for something else.  I'm guessing this particular crash has been fixed in HEAD.

**Comment by GarettJaxx** [comment] 2019-01-15 21:02
Would be worth it yes - any help the devs can get in trying to identify/understand the issue can't be bad....

Megamouse - Please can this be re-opened?

**Comment by GarettJaxx** [comment] 2019-01-19 22:33
Just an update - I was trying to play Dark Souls II - Scholar of the 1st Sin (NPUB31666) and had this exact same crash.

The odd thing with this though is that the save directory is named "NPUB31358-GAME_000" and not 31666 - is this because of the SotFS addon?

**Comment by mrkurosawa** [comment] 2019-01-23 17:09
Same issue here demon's souls 7736 build. Game and emulator on SSD. May be is there temporary solution? May be dump save files only when i close game or so?

**Comment by fullerfury** [comment] 2019-01-30 21:42
Same issue with Persona 5.  It happens 1/3 times I save. There is no autosave function, but instead when I try and save normally it throws up that error sometimes "{PPU[0x1000085] Thread (xrd664_auto_save) [0x001ab1bc]} class std::runtime_error thrown: Failed to move directory".  It is quite frustrating, as I have to keep repeating my game play over and over. Anyone have any ideas how to fix this?

**Comment by mrkurosawa** [comment] 2019-02-01 18:09
Looks like it's antivirus problem lol. Tryed to play without antivirus, everything was ok, but not 100% sure.

**Comment by GarettJaxx** [comment] 2019-02-01 18:36
I don't believe that this issue is related to antivirus - I use Kaspersky and it doesn't interfere with RPCS3 at all....

In terms of latest build, so far so good. I've seen the directories appear and vanish wthout incident so I assume this is a positive! I've only played around 3 hours so far and need to try DS2 but so far it's looking good.

Will report back with an update after a couple more hours of testing.....

**Comment by mrkurosawa** [comment] 2019-02-01 23:56
> Try with antivírus on the latest build
I will, thanks.

> I use Kaspersky
Lol, me too. Coincidence? Dont think so, but may be.

**Comment by GarettJaxx** [comment] 2019-02-02 14:38
well it seems to be working fine for me so I cant see how it can be Kaspersky, but either way good  luck bro.

**Comment by AniLeo** [comment] 2019-02-02 20:00
This is very likely fixed by #5614 , I will be closing this soon if there are no reports of this issue happening on current builds

**Comment by mrkurosawa** [comment] 2019-02-04 20:40
Same here. No more error. But somehow about after 1-1.5 hours of playing, emulator starts to freeze and it needs to be rebooted to fix that, but may be it's my system problem.

**Comment by GarettJaxx** [comment] 2019-02-05 00:06
I've managed to playu a combination of DeS and DS2 tonight for circa 5 hours with no crash, so it looks like this is now fixed.

@mrkurosawa - hope you resolve your freezing issue bro (if it helps for specs comparing I'm on Nvidia drv ver 417.71 on a gtx 1070, i7-7700k, 16gb ram)

**Comment by kd-11** [comment] 2019-02-05 09:42
Closing as fixed by https://github.com/RPCS3/rpcs3/issues/5481

**Closed by kd-11** 2019-02-05 09:42 UTC
Labels: Regression, Savedata
