### ISSUE TITLE
Regression: White boxes on some particles (since #10637 - 0.0.17-12569)

### ISSUE THREAD

**Issue by xevious89** [RPCS3/rpcs3#10673] opened 2021-08-07 09:34 UTC
## Quick summary
White boxes

## Details
NeverDead [BLUS30654]
White boxes on some particles since:
#10637 - 0.0.17-12569   4 days ago (2021-08-02) to
#10668 - 0.0.17-12611   11 hours ago (2021-08-06) 
It run normally:
#10640 - 0.0.17-12565 5 days ago (2021-08-01)

#10668 - 0.0.17-12611 - PROBLEM
![ndw](https://user-images.githubusercontent.com/88389377/128595661-19fcbbbf-19ee-4b57-a42f-964080286323.gif)
#10640 - 0.0.17-12565 - FINE
![ndf](https://user-images.githubusercontent.com/88389377/128595679-19fa04cf-9eb1-49e2-80db-1ae9936e4d30.gif)

#### 2. Please attach TWO logs:
* One for the build with regression.
[RPCS3-#10668.log.gz](https://github.com/RPCS3/rpcs3/files/6948880/RPCS3-.10668.log.gz)
* One for the build that works as expected.
[RPCS3-#10640.log.gz](https://github.com/RPCS3/rpcs3/files/6948881/RPCS3-.10640.log.gz)

Details:
OS: Windows 10 64-bit
CPU: Ryzen 5600X
GPU: RTX 2060 - ( Driver version: 471.41.0.0 )
RAM: 16GB DDR4 3200

-RPCS3 rpcs3-v0.0.17-12611
-Game: NeverDead [BLUS30654]
-Issue: White boxes on some particles

**Comment by kd-11** [comment] 2021-08-07 10:15
Please provide the RSX capture file. Get the glitch on screen and then go to utilities->create rsx capture

**Comment by xevious89** [comment] 2021-08-07 11:12
Of course.
RSX Capture: https://www.mediafire.com/file/7vaea7ehrllate3/BLUS30654_20210807060046_capture.rrc/file
PD: (The graphic error only occurs when i move the camera)

**Comment by kd-11** [comment] 2021-08-07 11:45
The capture unfortunately does not show how the broken light is generated. Is the problem visible using openGL?

**Comment by xevious89** [comment] 2021-08-07 13:56
Yes, same using openGL (and worse performance), i try tu capture with opengl but it only appears a black screen. Here are another 2 captures probably it works.

RSX Capture:
1) https://www.mediafire.com/file/ktdyiylwd70zh74/BLUS30654_20210807073034_capture.rrc/file
2) https://www.mediafire.com/file/73f5xfe5mj7jzbj/BLUS30654_20210807084600_capture.rrc/file

**Comment by Darkhost1999** [comment] 2021-08-07 14:02
Since capturing issues like this require the camera to be in motion as soon as clicking the utilities button the issue is gone. Is there a sort of keyboard hotkey to be aware of that can capture the RSX while the camera is in motion to accurately report issues of this nature? This isn't the only game with this issue and I can try to add more information that may help if it's possible to capture the issue.

**Comment by kd-11** [comment] 2021-08-07 14:25
> Since capturing issues like this require the camera to be in motion as soon as clicking the utilities button the issue is gone. Is there a sort of keyboard hotkey to be aware of that can capture the RSX while the camera is in motion to accurately report issues of this nature? This isn't the only game with this issue and I can try to add more information that may help if it's possible to capture the issue.

At the moment, this is unimplemented as far as I know. However, you can capture renderdoc traces in this manner using vulkan (the performance won't be as bad as OpenGL) Note that renderdoc is an external tool and can be found here https://renderdoc.org/
I think since we need to capture something in motion we have to go with renderdoc for now. Just capture using vulkan backend and attach the compressed rdc file.

**Comment by MSuih** [comment] 2021-08-07 14:26
There is a keyboard shortcut for taking RSX captures, alt + c

https://wiki.rpcs3.net/index.php?title=Help:Keyboard_Shortcuts

**Comment by xevious89** [comment] 2021-08-07 14:45
Here's the render doc
RenderDoc:
Vulkan: https://www.mediafire.com/file/p0fplhfypdp4ma1/Renderdoc_NV.7z/file

**Comment by kd-11** [comment] 2021-08-09 16:29
One of the divisors is irrational (0.0015873015873015873015873015873...)
I'll have to rethink how we handle unnormalized texture access. Simply passing in reciprocals is not good for such delicate measurements.

**Comment by kd-11** [comment] 2021-08-09 16:56
This should be fixed by https://github.com/RPCS3/rpcs3/pull/10689

**Comment by Emulator-Team-2** [comment] 2021-08-10 08:02
Fixed by https://github.com/RPCS3/rpcs3/pull/10689.

<details> 
<summary>(rpcs3-v0.0.17-12621)</summary>

![1](https://user-images.githubusercontent.com/38318848/128830328-ce1e8a5d-fdbb-4e12-a48d-fcae393cac65.png)

</details>

<details> 
<summary>(PR: #10689)</summary>

![2](https://user-images.githubusercontent.com/38318848/128830595-3eca91e9-8f26-4bb6-a4a5-2033e2608075.png)

</details>

**Closed** 2021-08-10 09:02 UTC
Labels: RSX, Regression

**Comment by xevious89** [comment] 2021-08-10 18:08
Awesome thanks :)
