### ISSUE TITLE
MacOS：DS4 was disconnected from bluetooth when clicking Pads button

### ISSUE THREAD

**Issue by shangjun2x** [RPCS3/rpcs3#13919] opened 2023-05-25 05:42 UTC
### Quick summary

E DS4: GetCalibrationData: hid_get_feature_report 0x05 for bluetooth controller failed! result=-1, error=IOHIDDeviceGetReport failed: (0xE00002D7) (iokit/common) device offline
E DS4: check_add_device: GetCalibrationData failed!

### Details

See the attached log

### Attach a log file

[RPCS3.log](https://github.com/RPCS3/rpcs3/files/11561458/RPCS3.log)

**Comment by Megamouse** [comment] 2023-05-25 19:37
Does this always happen?
When did it start if it is a regression?

**Comment by shangjun2x** [comment] 2023-05-26 02:12
> Does this always happen? When did it start if it is a regression?

Hi Megamouse, I don't know. It's my first time to run rpcs3 on macos, I can only use the controller with USB now.

**Comment by Megamouse** [comment] 2024-06-26 20:31
Closing as duplicate of #11343

**Closed by Megamouse** 2024-06-26 20:31 UTC
Labels: Input, OS: Mac
