### ISSUE TITLE
[Features request] Add iso support and a shortcut key to hide/show overlay performance

### ISSUE THREAD

**Issue by marsselluo** [RPCS3/rpcs3#7941] opened 2020-04-04 11:26 UTC
It wil be great RPCS3 had iso support. I have about 100 games iso format and everytime I want to test some game, I need
to emulate the iso.
Add a shortcut key to show/hide the overlays performance it will be a great help.

I don't know if this right place to post this so you can close this if it's not in the right place.

Sorry for my english and thanks fir the great work.

**Comment by AniLeo** [comment] 2020-04-04 17:43
Duplicate of #4500 and #4021

**Closed by AniLeo** 2020-04-04 17:43 UTC
