### ISSUE TITLE
Missing VCRUNTIME140.DLL in inFamous: Festival of Blood

### ISSUE THREAD

**Issue by emulationchannel** [RPCS3/rpcs3#7185] opened 2020-01-03 15:42 UTC
![SharedScreenshot9](https://user-images.githubusercontent.com/54820827/71732592-6bc61500-2e26-11ea-8388-db51b165ce84.jpg)
[RPCS3.log](https://github.com/RPCS3/rpcs3/files/4019712/RPCS3.log)

**Comment by emulationchannel** [comment] 2020-01-03 19:11
![SharedScreenshot03](https://user-images.githubusercontent.com/54820827/71743584-adb18400-2e43-11ea-8dba-3c753e44866c.jpg)
[RPCS3.log](https://github.com/RPCS3/rpcs3/files/4020546/RPCS3.log)

**Comment by RainbowCookie32** [comment] 2020-01-03 19:13
You are not using master on the infamous 2 screenshot. Always use master when reporting issues.

Also, when did the issues started happening? This issue barely has any info

**Comment by emulationchannel** [comment] 2020-01-03 19:15
I did several test on all games branch master rpcs3 all games broke with this same problem.

**Comment by RainbowCookie32** [comment] 2020-01-03 19:17
But when did they break? Knowing when the games stopped working is key, helps a lot when someone wants to fix the issue

**Comment by emulationchannel** [comment] 2020-01-03 19:22
games break compile cache giving this Win32 error @RainbowCookie32 
![71732592-6bc61500-2e26-11ea-8388-db51b165ce84](https://user-images.githubusercontent.com/54820827/71744186-41378480-2e45-11ea-84ee-73219850bf72.jpg)

**Comment by RainbowCookie32** [comment] 2020-01-03 19:23
What I mean is that you should find the last RPCS3 build that works and add that to the issue. Otherwise we are blind here, we don't know what change broke it.

**Comment by emulationchannel** [comment] 2020-01-03 19:25
test latets master rpcs3 power by kd-11

**Comment by RainbowCookie32** [comment] 2020-01-03 21:11
Can't reproduce the issue with Festival of Blood in latest master (0.0.8-9313). Make sure the Visual C++ 2019 Redistributable is installed, since that DLL is from it. Here's the link to it https://aka.ms/vs/16/release/VC_redist.x64.exe

![Untitled](https://user-images.githubusercontent.com/16805474/71749545-81eaca00-2e54-11ea-9c8c-63920055dc09.jpg)

**Comment by emulationchannel** [comment] 2020-01-08 17:42
VCRUNTIME140.DLL 2017 and 2019 installed but bug occurred only once after test opening game works normal @RainbowCookie32

**Comment by RainbowCookie32** [comment] 2020-01-08 17:46
I never had the issue to begin with. Close the issue if it doesn't happen anymore

**Closed** 2020-01-08 18:56 UTC
