### ISSUE TITLE
Regression: Resistance 2 (#8769)

### ISSUE THREAD

**Issue by nitroos-ai** [RPCS3/rpcs3#8846] opened 2020-09-06 20:03 UTC
## Quick summary
When zooming with a gun the emulator crashes. The regression started with #8769  rpcs3-v0.0.11-10790

#### 2. Please attach TWO logs:
* Regression log [RPCS3.log.gz](https://github.com/RPCS3/rpcs3/files/5180164/RPCS3.log.gz)

* Works as expected log [RPCS3.log.gz](https://github.com/RPCS3/rpcs3/files/5180165/RPCS3.log.gz) rpcs3-v0.0.11-10781

#### 3. If you describe graphical regression, please provide an RSX capture and a RenderDoc capture that demonstrate it.

The game crashes when I try to create an RSX Capture.

#### 4. Please attach screenshots of your problem.

Normal stance
![normal stance](https://user-images.githubusercontent.com/68450737/92334111-f4055580-f058-11ea-8c98-285c60411bcf.jpg)
Zoom stance
![zoom stance](https://user-images.githubusercontent.com/68450737/92334115-f9fb3680-f058-11ea-9921-37cdaf827fa4.jpg)

#### 6. Please provide your system configuration:
* OS: Lubuntu 20.04.1
* CPU: i5-4590
* GPU: GeForce GTX 1070 TI
* GPU Driver: nvidia-driver-440
* RAM: 12gb

**Comment by kd-11** [comment] 2020-09-06 21:34
Attached "regression log" is corrupted (downloaded twice).
In the meantime, make sure to try https://github.com/RPCS3/rpcs3/pull/8842 first, it has some cleanup for vulkan code as well.

**Comment by nitroos-ai** [comment] 2020-09-06 22:12
[RPCS3.log](https://github.com/RPCS3/rpcs3/files/5180373/RPCS3.log)

**Comment by Asinin3** [comment] 2020-09-12 19:46
Retest please, it works for me, aphelion and digitaldude on latest.

**Comment by nitroos-ai** [comment] 2020-09-12 20:06
It happens sometimes ingame but reproducible in level "Battleship: Hangar Bay" when using guns zoom. Tested in version 0.0.12-10876-fe9c61fe Alpha.
Th emulator crashes with error code `{RSX [0x15258d8]} SIG: Thread terminated due to fatal error: Verification failed (e=11): Incompatible source and destination format!
(in file ../rpcs3/Emu/RSX/VK/VKTexture.cpp:1129)`.

**Comment by kd-11** [comment] 2020-09-13 17:04
Cannot reproduce either. Provide save file for the affected area to help with reproducing. I still cannot open those provided files, both winrar and 7zip say the log file archive is corrupted.

**Comment by nitroos-ai** [comment] 2020-09-13 17:44
Log + save 

[Resistance_2.tar.gz](https://github.com/RPCS3/rpcs3/files/5214794/Resistance_2.tar.gz)
[Resistance_2.zip](https://github.com/RPCS3/rpcs3/files/5214796/Resistance_2.zip)

**Comment by jeremybris** [comment] 2020-09-17 15:15
I get this on the BCES version but not the NPEA

**Comment by kd-11** [comment] 2020-09-21 21:21
Retest with https://github.com/RPCS3/rpcs3/pull/8949

**Comment by jeremybris** [comment] 2020-09-21 23:11
Fixed (mine), great job and thank you :)

**Comment by nitroos-ai** [comment] 2020-09-22 00:38
I can confirm that it fixes my game as well. Thank you.

**Comment by RainbowCookie32** [comment] 2020-09-22 00:39
Please keep the issue opened until the PR is merged

**Closed** 2020-09-22 09:19 UTC
Labels: RSX, Regression
