### ISSUE TITLE
GT6 [BCES01893] - Unknown Stop Code Out_MBox is empty

### ISSUE THREAD

**Issue by fearcraftor** [RPCS3/rpcs3#7765] opened 2020-03-12 17:52 UTC
## Quick summary
Can't go ingame on Gran Turismo 6 because of Fatal error

```
·F 0:01:53.088636 {SPU[0x2000100] Thread (PDICellSpursKernel2) [0x10360]} sig_log: Thread terminated due to fatal error: Unknown STOP code: 0x358 (Out_MBox is empty)
(in file C:\projects\rpcs3\rpcs3\Emu\Cell\SPUThread.cpp:3181)
```

## Details
- full logs and back traces provided
 
your system configuration (OS, CPU, GPU, driver versions, etc)
OS: Windows 10 1909
CPU: Intel Core i5-4440 CPU @ 3.10GHz
GPU: GTX 660 (v 432.00)
RAM: 8Go

[rpcs3-v0.0.8-9665-171e6c6e_win64.zip](https://github.com/RPCS3/rpcs3/files/4325701/rpcs3-v0.0.8-9665-171e6c6e_win64.zip)

**Comment by EmuRace** [comment] 2020-04-02 17:46
I have the same Problem regarding the fatal error with MBox is empty.
Any hint for a possible fix?

Game version: V1.04
Emulator Firmware: V4.85
Logfile: 
[RPCS3.zip](https://github.com/RPCS3/rpcs3/files/4422657/RPCS3.zip)


Error code:
F {SPU[0x4000100] Thread (PDICellSpursKernel4) [0x10360]} SIG: Thread terminated due to fatal error: Unknown STOP code: 0x358 (Out_MBox is empty)
(in file d:\a\1\s\rpcs3\Emu\Cell\SPUThread.cpp:3205)

System configuration:
OS: Windows 10 1903
CPU: Intel Core i7-6770k CPU @ 4,2GHz
GPU: GTX 1070Ti (v 445.75)
RAM: 16 GB
RPCS3 Version: 0.0.9-10084

**Comment by Satan86** [comment] 2020-11-06 19:59
try SPU Decoder ASMJIT

**Comment by Sly12346** [comment] 2021-05-05 14:23
Any solution yet?
ASMJIT recompiler causes so extreme sound lag. The same as 'Accurate xfloat'.
Sound ist totally chopped. The game is unplayable like that. So it's not a solution.

**Comment by Satan86** [comment] 2021-05-05 14:28
It's the best we got for now, unfortunately.

**Comment by DaishinSilviaGT** [comment] 2021-09-30 20:17
Is the problem still there?

**Comment by YuriNator557** [comment] 2021-09-30 20:27
SPU ASMJIT is still needed to fix it

**Comment by hoholee12** [comment] 2022-03-23 05:35
I was able to fix this issue by having all firmware modules HLE'd, except decoders, encoders, and libfiber, libgcm_sys, libhttp, libsmvd2, libsmvd4, libsre, libsysmodule.
It could be a placebo, but it helped completely remove those SPU crash issues for me.
Having libdmux and libdmuxpamf HLE'd will cause crash on video playback, so make sure to disable intro from ingame options before doing it.

**Comment by DaishinSilviaGT** [comment] 2022-08-19 23:38
> I was able to fix this issue by having all firmware modules HLE'd, except libfiber, libgcm_sys, libhttp, libsmvd2, libsmvd4, libsre, libsysmodule. It could be a placebo, but it helped completely remove those SPU crash issues for me. Having libdmux and libdmuxpamf HLE'd will cause crash on video playback, so make sure to disable intro from ingame options before doing it.

this config doesn't work in my case, so it's surely a "placebo"

**Comment by Aholicknight** [comment] 2023-01-15 04:22
> try SPU Decoder ASMJIT

@Satan86 I can confirm this works. The only problem that I am still having is a **ton** of framerate drops from 60 FPS to 12 FPS. Is there a fix for this as well?

**Comment by mikelitt28** [comment] 2023-05-16 20:53
Boys I got the answer update your firmware to the newest version instantly made it work for me lets go

**Comment by Hadrianneue** [comment] 2023-06-05 00:48
Having a similar issue, the only difference is the error code:

```
F {SPU[0x0000100] Thread (PDICellSpursKernel0) [0x1033c]} SIG: Thread terminated due to fatal error: Unknown STOP code: 0x0 (op=0x0, Out_MBox=empty)
(in file ../rpcs3/Emu/Cell/SPUThread.cpp:5896, in function stop_and_signal) (errno=110=Connection timed out)
```

Everything seems to work fine at first, starting a race on all modes in arcade mode works most of the time with good performance (even better than GT5) with SPU Recompiler (LLVM), however playing other modes besides arcade mode would crash 90% of the time, either just before loading a track or when listing the starting grid.

Using SPU Recompiler ASMJIT fixes this issue at a hefty performance cost, still playable though, no other setting seems to have helped avoid this crash, sometimes it just works at random...

tested on linux with radv/amdvlk/opengl

**Comment by Talal26** [comment] 2023-06-11 20:49
> **EDIT:** Accurate XFloat seems to fix crashes, it does affect performance quite a bit, but not as much as using SPU Recompiler ASMJIT

Can confirm this eliminates the crashing but causes a big performance drop, audio stuttering, and music was slowed even though the game was still running at full speed.

But those issues are even worse when using SPU ASMJIT Recompiler so it's a small improvement.

**Comment by m33ts4k0z** [comment] 2023-10-28 22:14
This is still an issue and every solution mentioned drops the framerate to the half and heavily lags the sound. When the race loads with LLVM, the game runs perfectly fine are around 40 fps with no sound issues.

**Comment by m33ts4k0z** [comment] 2023-11-02 11:35
An update on this. I used the 15688 build and the game runs fine without zero audio stuttering using the ASMJIT compiler and the reason is that the audio buffering option works on linux up to this version. Every version after this has a non-working audio buffer on linux so disabling it does bring the audio back but with great cut outs.  I'm on Ubuntu Mantic

**Comment by Talal26** [comment] 2024-04-01 22:18
Little update on this. In recent builds of RPCS3, the game no longer seems to crash when using SPU Recompiler LLVM with **Approximate XFloat** and this setting produces way better performance than using Accurate XFloat so now I can recommend using **Approximate Xfloat** to fix the performance issues.

**Closed** 2024-04-02 18:21 UTC
