### ISSUE TITLE
Sonic Unleashed crashes after title cards are done playing.

### ISSUE THREAD

**Issue by Buster915** [RPCS3/rpcs3#9334] opened 2020-11-24 21:16 UTC
Hello. I have not been able to play Sonic Unleashed in the past few builds of RPCS3. This bug was introduced after i updated from version v0.0.12-11091-15e8cba3. Every time there's an update, I update RPCS3 hoping the bug is fixed, but it has not been fixed. I've literally had to stick to version v0.0.12-11091-15e8cba3 in order to play Sonic Unleashed without worrying about the game crashing after the "Havok" title card is done. This bug happens majority of the time in the latest version. Very rarely, the game will actually play without it crashing. I will provide a video, the RPCS3 log, and my PC's CPU and GPU to see if it has anything to do with it.
[RPCS3.log](https://github.com/RPCS3/rpcs3/files/5592755/RPCS3.log)

I had to record this on my phone since my Radeon software was bugging out on trying to record it.
Video: https://streamable.com/cz7lpp

CPU: AMD Ryzen 7 3700X 8-Core 3.59Hz
GPU: Radeon RX 5700 TX 8GB
Windows 10

**Comment by MSuih** [comment] 2020-11-25 11:05
I'm closing this because of two issues:

* You didn't mention which exact version broke the game, which is required for regression reports
* Your settings are a mess, this needs to be retested with settings closer to our default options

**Closed by MSuih** 2020-11-25 11:05 UTC
Labels: Meta: Invalid
