### ISSUE TITLE
[Feature Request] sixaxis support for gyro controllers like switch pro and/or mouse

### ISSUE THREAD

**Issue by drago338** [RPCS3/rpcs3#10015] opened 2021-03-24 00:42 UTC
Many games require sixaxis so without a DS3/4 its impossible to play them so support through other methods to emulate sixaxis would make these games playable for people without a DS3/4.

**Comment by Megamouse** [comment] 2021-03-24 00:47
duplicate of #8600

**Closed by Megamouse** 2021-03-24 00:47 UTC
Labels: Input, Meta: Duplicate
