### ISSUE TITLE
Bug: SPU Mega doesn't work on Skyrim

### ISSUE THREAD

**Issue by xddxd** [RPCS3/rpcs3#9183] opened 2020-10-31 09:07 UTC
When SPU Mega is enabled on Skyrim, the emulator crashes to desktop when you load into the game.
VS Debugger shows this:
![Screenshot_12](https://user-images.githubusercontent.com/1712979/97775414-169f8080-1b69-11eb-9829-27df360cde11.png)
Log: 
[RPCS3.log](https://github.com/RPCS3/rpcs3/files/5468806/RPCS3.log)

RPCS3 v0.0.12-11134-5d55e509 Alpha
Ryzen 7 2700
RX 580
Windows 10 20H2

**Comment by Darkhost1999** [comment] 2022-02-21 02:58
Still present although idk why it matters when default settings work fine.
[RPCS3.log](https://github.com/RPCS3/rpcs3/files/8105860/RPCS3.log)

**Comment by Darkhost1999** [comment] 2022-05-10 23:33
For what it's worth 2 runs
[RPCS3.log.gz](https://github.com/RPCS3/rpcs3/files/8665544/RPCS3.log.gz)
I got to roam Breezehome but couldn't world gate on the 2nd run.
1st run I get in game for an instant freeze.

I fail to see value in this issue can someone explain?

**Comment by AhayriSG** [comment] 2022-07-17 22:44
"SPU Block Size: Safe" -> https://www.youtube.com/watch?v=gT4B99fcUu4

**Comment by Darkhost1999** [comment] 2022-08-27 15:00
This comment you quoted doesn't appear to contain any relevant information to any issue. Just thoughts on someone's experience

**Comment by AhayriSG** [comment] 2022-08-27 15:10
> This comment you quoted doesn't appear to contain any relevant information to any issue. Just thoughts on someone's experience

yup, sharing my testing/experience.

**Comment by Nekotekina** [comment] 2022-09-01 17:00
I'll try to reproduce locally

**Comment by Nekotekina** [comment] 2022-09-19 14:17
Please try to reproduce with #12684 and show the error message.

**Comment by Darkhost1999** [comment] 2022-09-19 15:24
![image](https://user-images.githubusercontent.com/60384196/191053782-eeae2e31-8f7b-456b-8626-88e31876d072.png)
E RSX: [attrib buffer] Pool limit was reached. Will attempt to swap out the current heap.
F {RSX [0x009493c]} VM: Access violation reading location 0xff3bc738 (unmapped memory)
[RPCS3.log](https://github.com/RPCS3/rpcs3/files/9600328/RPCS3.log)

**Comment by Nekotekina** [comment] 2022-09-19 15:35
It looks like a different issue.

**Comment by Darkhost1999** [comment] 2022-09-19 16:11
In that case spu block size Mega is working fine

**Comment by Darkhost1999** [comment] 2022-09-19 16:22
Original issue is unobserved in current master
[RPCS3.log](https://github.com/RPCS3/rpcs3/files/9600705/RPCS3.log)

**Comment by AniLeo** [comment] 2022-09-19 16:45
@xddxd do you confirm on your side? If anyone else knows games that don't work properly with SPU Mega but work properly with SPU Safe please open a separate ticket

**Comment by Nekotekina** [comment] 2022-09-20 10:18
@xddxd I updated the PR, another test please.

**Comment by xddxd** [comment] 2022-09-20 12:11
`Verification failed
(in file C:\Users\ContainerAdministrator\AppData\Local\Temp\cirrus-ci-build\rpcs3\Emu\Cell\SPURecompiler.cpp:3087[:3], in function analyse)`
[RPCS3.log.gz](https://github.com/RPCS3/rpcs3/files/9607443/RPCS3.log.gz)

**Comment by elad335** [comment] 2024-05-29 09:29
Probably outdated & fixed, closing. Open a new issue if persists.

**Closed by elad335** 2024-05-29 09:29 UTC
