### ISSUE TITLE
Gran Turismo 6 Vulkan API call failed with unrecoverable error

### ISSUE THREAD

**Issue by Wizzy2018** [RPCS3/rpcs3#6310] opened 2019-08-06 11:20 UTC
Sudenly new build give me this error  Out of video memory (VRAM) (VK_ERROR_OUT_OF_DEVICE_MEMORY)
Here is a log
[RPCS3.log.gz](https://github.com/RPCS3/rpcs3/files/3471873/RPCS3.log.gz)

**Comment by AniLeo** [comment] 2019-08-06 11:22
Duplicate of #6282

**Closed by AniLeo** 2019-08-06 11:22 UTC
