### ISSUE TITLE
Tales of Graces F Graphic Issue

### ISSUE THREAD

**Issue by ghastl** [RPCS3/rpcs3#3965] opened 2017-12-21 20:33 UTC
**Game**: Tales of Graces F [BLUS30903]
**RPCS3 Version**: v0.0.4-6243-de5dab35 Alpha

**CPU Settings**
PPU: Recompiler (LLVM)
SPU: Recompiler (ASMJIT)

**Spec**
CPU: I5 3470
GPU: Radeon RX 480
Ram: 8GB
OpenGL Version: 4.4
Windows: Win 7 64bit

**Issue**
-Broken Graphics with Vulkan + Strict Rendering Mode
![vulkan-game](https://user-images.githubusercontent.com/34751393/34272767-2b863764-e6c4-11e7-8405-898c372b01bd.jpg)
![vulkan-title](https://user-images.githubusercontent.com/34751393/34272782-3f02e81e-e6c4-11e7-9473-3e10a90c71d2.jpg)

-OpenGL
![opengl-game1](https://user-images.githubusercontent.com/34751393/34272791-4d6bbbb0-e6c4-11e7-96e5-fb40570de45f.jpg)
![vulkan-opengl](https://user-images.githubusercontent.com/34751393/34272797-50956930-e6c4-11e7-9b9c-1ea4448304c7.jpg)

However the problem with OpenGL is there's black and flickering textures in some places
![opengl-game](https://user-images.githubusercontent.com/34751393/34272809-5f02cd5a-e6c4-11e7-9955-b78d7d4fdbdc.jpg)

Vulkan with Strict Rendering Mode disabled, works fine in title, however once the game is started, the characters become transparent and other background problem
![vulkan-title-c](https://user-images.githubusercontent.com/34751393/34273858-b16b0bc6-e6c8-11e7-8225-76796dadbc48.jpg)
![vulkan-game-c](https://user-images.githubusercontent.com/34751393/34272854-86493f3e-e6c4-11e7-8241-d6198c83c421.jpg)

Vulkan Log:
[RPCS3.log.gz](https://github.com/RPCS3/rpcs3/files/1580504/RPCS3.log.gz)

OpenGL Log:
[RPCS3.log.gz](https://github.com/RPCS3/rpcs3/files/1580511/RPCS3.log.gz)

Older version (0.0.3) runs fine with Vulkan without Graphic issues (OpenGL graphic issue still exist) however the skits are blurred

**Comment by Illynir** [comment] 2017-12-21 20:49
I don't have this problem with Vulkan and on Nvidia.

**Comment by GeniusMage** [comment] 2017-12-21 21:16
This looks like an old build, website is already on 0.0.4-7271.

**Comment by Relsig** [comment] 2017-12-22 23:07
de5dab35 is actually build 7251(5 days ago, rsx: raise semaphore timeout). For some reason when you overwrite the files the build number isn't updated in logs but the commit number is...

Once my copy of tales arrives in the next few weeks I'll test as well, though I am team Nvidia so I suspect it will turn out as it did for Illynir.

@ghastl if you have time it might still be worth updating to the most recent build and confirming that it's still a problem.

**Comment by GeniusMage** [comment] 2017-12-22 23:48
Alright, tested it on my R9 Nano, and it works fine.
Although, I'm using the BLES version, not BLUS. But it would be weird for such an issue to appear on one but not the other.

**Comment by AniLeo** [comment] 2018-03-31 18:49
Confirmed not an issue on latest master, closing.

**Closed by AniLeo** 2018-03-31 18:49 UTC
