### ISSUE TITLE
Assassin's Creed 3 crashes

### ISSUE THREAD

**Issue by Zulthar** [RPCS3/rpcs3#12926] opened 2022-11-06 17:32 UTC
### Quick summary

game crashes seconds after starting gameplay

### Details

Nothing else to add beyond what's in the quick summary

### Attach a log file

[RPCS3.log](https://github.com/RPCS3/rpcs3/files/9946415/RPCS3.log)

**Comment by Darkhost1999** [comment] 2022-11-06 17:36
In order to play this game you currently need
PPU Interpreter
Enable Accurate ppu non-java mode 
Disable non java mode fixup
SPU Xfloat accuracy set to precise
Ordered and atomic FIFO accuracy.
All of these are accuracy settings required for it not to freeze. You'll have audio issues every time you run around or do eagle jumps.

**Comment by Zulthar** [comment] 2022-11-06 18:39
Hi there, I'm fairly certain I did all of this, except for SPU Xfloat was set to accurate, as there is no precise option, the framerate is still pretty low, are there any options that'll increase it without more crashes?

**Comment by Darkhost1999** [comment] 2022-11-06 20:29
SPU Xfloat accuracy is in the cpu tab.
There is nothing to improve the performance. You're trading that for the accuracy required to play these games.

**Comment by Darkhost1999** [comment] 2022-11-06 20:32
Maybe the performance can be improved by a developer understanding more of what specifically is the issue and improving the code. I can aid in providing information. I just don't know what is wanted or needed to aid this situation.

The biggest change to performance possibly is enabling accurate ppu non-java mode to LLVM. That is currently unimplemented.

**Comment by kd-11** [comment] 2022-11-22 09:28
CLosing as duplicate of https://github.com/RPCS3/rpcs3/issues/12807

**Closed by kd-11** 2022-11-22 09:28 UTC

**Comment by mityasokolay** [comment] 2023-02-17 10:44
hey! For some reason i cant enable Accurate ppu non-java mode in rpcs3 settings. i click on it, and nothing happens

**Comment by Darkhost1999** [comment] 2023-02-17 10:46
The setting is only enabled when ppu Interpreter is selected in the cpu tab at this time

**Comment by mityasokolay** [comment] 2023-02-17 11:11
thank you very much, i actually figured it out! very surprised, because im really bad at all this

**Comment by mityasokolay** [comment] 2023-02-17 20:35
hm, i did all that, but now it freezes everytime when the inspired by historycal events..... im playing on mac btw, can anyoe help me?

**Comment by brGren** [comment] 2023-04-10 14:46
Hello, could someone help me with a problem I have with the game "F1 Championship edition"?
The problem is that when you start the game it stays on a black screen and the game never loads, the fps also crash.
