### ISSUE TITLE
Star wars the force unleashed rendering issues (DMA detiling)

### ISSUE THREAD

**Issue by hmv2211** [RPCS3/rpcs3#12756] opened 2022-10-04 11:48 UTC
### Quick summary

When booting into the game, the title screen loads correctly and Fps is at 30 but when booting into game the Fps drops to 24 which is fine but the screen has inverted colours. (problem 1)

![Github problem 1](https://user-images.githubusercontent.com/114997703/193809696-74e1f17a-1865-48dc-bf60-8d73e9fe4b70.png)

![Github problem 1 settings](https://user-images.githubusercontent.com/114997703/193809726-550b1230-d04a-4886-b4b5-2850b8802798.png)

I then changed some of the GPU settings and the inverted colours disappear but now im confronted with some rendering issues and can hardly see what im doing. (problem 2)
![Github problem 2](https://user-images.githubusercontent.com/114997703/193809762-3e7209c9-8c07-428d-9a69-dd8f991a2881.png)

![Github problem 2 settings](https://user-images.githubusercontent.com/114997703/193809788-2b5482e2-3236-498b-94c0-b87dca119819.png)

Any help would be greatly appreiceted.

### Attach a log file

[RPCS3.log](https://github.com/RPCS3/rpcs3/files/9706337/RPCS3.log) log for problem 1

[RPCS3.log.gz](https://github.com/RPCS3/rpcs3/files/9706340/RPCS3.log.gz) log for problem 1 zipped

[RPCS3.log](https://github.com/RPCS3/rpcs3/files/9706393/RPCS3.log) log for problem 2

[RPCS3.log.gz](https://github.com/RPCS3/rpcs3/files/9706397/RPCS3.log.gz)  log for problem 2 zipped

### System configuration

AMD Ryzen 7 3700X 8-Core Processor                3.60 GHz
16.0 GB RAM
NVIDIA GeForce RTX 3060
Windows 11 home

**Comment by YuriNator557** [comment] 2022-10-04 12:43
Duplicate of #8244

**Comment by YuriNator557** [comment] 2022-10-04 12:48
No wait that one is for TFU2, sorry
Missing RSX capture, also I can see Asynchronous Texture Streaming enabled in at least one of those logs

**Comment by DiverseBloom780** [comment] 2022-10-26 06:24
In the new build 0.0.24-14337 it is still stuck on boot loop, idk what settings I should use,  been playing around with alot of settings recently and still can't get to the main Menu

**Closed** 2023-09-27 11:53 UTC
Labels: RSX

**Comment by slifer88** [comment] 2025-01-12 19:02
so whats the fix for the vertical lines?
