### ISSUE TITLE
[REGRESSION] #9102 Games will no longer launch, or will launch to a blank white screen.

### ISSUE THREAD

**Issue by jjw410** [RPCS3/rpcs3#9108] opened 2020-10-20 23:32 UTC
## Quick summary
With the newest build, V0.0.12-11055, games no longer launch properly. 11051 works as expected (logs attached). No settings were changed in between tests.

Version 11051 - [RPCS3_good.log.gz](https://github.com/RPCS3/rpcs3/files/5412195/RPCS3_good.log.gz)
Version 11055 - [RPCS3_bad.log.gz](https://github.com/RPCS3/rpcs3/files/5412196/RPCS3_bad.log.gz)

#### Screenshots
![11051 good](https://user-images.githubusercontent.com/44265824/96655022-6e9de200-1334-11eb-8e12-07f943c592f8.jpg)
![11055 bad](https://user-images.githubusercontent.com/44265824/96655031-7067a580-1334-11eb-83e2-eaa26599761b.jpg)

#### System Config
* OS - Microsoft Windows 10 Pro
* MOBO - ASRock B450 Steel Legend
* CPU - AMD Ryzen 5 3600 6-Core Processor
* GPU - Geforce GTX 970
* Driver version - 456.38

**Comment by AniLeo** [comment] 2020-10-21 00:01
Cannot reproduce on R7 2700X, seems to be Windows-only

**Comment by retrobio** [comment] 2020-10-21 00:18
Same here, all fine till update, and now persona 5 getting white screen... tried reinstall everything and mess with the settings and nothing seems to fix it.

My specs are:
Ryzen 5 3600
Xfx 5600xt
16gb ddr4

**Comment by Crafty-The-Fox** [comment] 2020-10-21 00:26
run the auto updater again, this is a known issue

**Comment by elad335** [comment] 2020-10-27 14:55
Fixed in latest build I think.

**Closed by elad335** 2020-10-27 14:55 UTC
Labels: OS: Windows, Regression
