### ISSUE TITLE
Freezing when save the system data at all game.

### ISSUE THREAD

**Issue by kyohigashi** [RPCS3/rpcs3#7603] opened 2020-02-26 15:58 UTC
I just updated latest version but have a big problem. When it have been loaded the game and always freezing on the save system data or "You must signed in the Playstation@Network in order to use this game on line service".

![rpcs3-freezing](https://user-images.githubusercontent.com/5468742/75362123-40761880-58f3-11ea-96b9-6f42c8205974.JPG)

[rpcs3-freezing.log](https://github.com/RPCS3/rpcs3/files/4256755/rpcs3-freezing.log)

[rpcs3-freezing2.log](https://github.com/RPCS3/rpcs3/files/4256961/rpcs3-freezing2.log)

**Comment by digitaldude555** [comment] 2020-02-26 17:09
#7588 already an issue.

**Comment by solarmystic** [comment] 2020-02-26 19:17
Can confirm this issue.

Strangely enough the fix for the msg dialog breakage introduced with #7594 caused this issue for me since 0.0.8-9723.
[broken RPCS3.log](https://github.com/RPCS3/rpcs3/files/4257708/RPCS3.log)

0.0.8-9720 is the last build not to exhibit this issue at all in my go to game for overlays, Soul Calibur IV.
[working RPCS3.log](https://github.com/RPCS3/rpcs3/files/4257701/RPCS3.log)

**Comment by AniLeo** [comment] 2020-02-26 19:50
Closing as duplicate of #7588 , report on the main issue

**Closed by AniLeo** 2020-02-26 19:50 UTC
