### ISSUE TITLE
Shadow of the Colossus HD [BCES01097] - Softlock

### ISSUE THREAD

**Issue by Resident007** [RPCS3/rpcs3#6495] opened 2019-09-07 18:30 UTC
Right in the first cutscene, The game runs at stable 30FPS, but after a few seconds FPS drops to 0.50 and it starts spamming `{RSX [0x007c3ec]} RSX: nv406e::semaphore_acquire has timed out. semaphore_address=0x40300460` error.
![image](https://user-images.githubusercontent.com/25570319/64478765-cb345100-d1b5-11e9-9fcc-5f4fdbf05b16.png)
Tested in RPCS3 v0.0.7-8653. Just in case, my specs:
i7-3770 (4c, 8T, 3.4 GhZ base clock, 3,9 GhZ Turbo Clock)
8GB DDR3-1333 RAM
GTX 1060 3GB
Windows 10 Pro 1903 x64

Logs:
[RPCS3.log](https://github.com/RPCS3/rpcs3/files/3586911/RPCS3.log)
[RPCS3.log.gz](https://github.com/RPCS3/rpcs3/files/3586912/RPCS3.log.gz)

**Comment by Resident007** [comment] 2019-09-08 15:48
In RPCS3 v0.0.7-8664 it randomly throws `RSX: class std::runtime_error thrown: Invalid location` fatal error.

**Comment by kd-11** [comment] 2019-09-14 10:32
This is expected; that message is not an error its a warning that means RSX has noticed the emulator is frozen and is attempting to run by itself. Of course this will likely lead to a crash but it allows one to close the emulator without everything crashing.
As for the cause, just look at your log - the emulator is frozen compiling SPU LLVM code. Try ASMJIT or interpreters instead.

**Comment by elad335** [comment] 2020-01-25 07:03
Retest with rsx wake-up delay

**Comment by elad335** [comment] 2020-01-28 15:01
Confirmed fixed with it.

**Closed** 2020-01-28 15:06 UTC
Labels: Need Information
