### ISSUE TITLE
GL/Vulkan: Skate 2

### ISSUE THREAD

**Issue by MarioSonic2987** [RPCS3/rpcs3#2383] opened 2017-02-14 15:09 UTC
@kd-11 @raven02 
Reaches to ingame in Vulkan. OpenGL is too slow.

**DX12**:
```
F {rsx::thread} class std::runtime_error thrown: Unsupported DXGI format 0x57
(in file C:\rpcs3\rpcs3\Emu\RSX\D3D12\D3D12Formats.cpp:201)
```
**GL**:
![](http://i.imgur.com/908KPud.png)
**Vulkan**:
![](http://i.imgur.com/Tg39gbY.jpg)
[Shaderlog DX12](https://drive.google.com/open?id=0B9LymxJkpT48dktNUjFfbEhfUG8)
[Shaderlog GL](https://drive.google.com/open?id=0B9LymxJkpT48bE9acVR4UUVDZkk)
[Shaderlog Vulkan](https://drive.google.com/open?id=0B9LymxJkpT48VzJQd2dNdkZaVWM)
[RenderDoc Vulkan (Character Creation)](https://drive.google.com/open?id=0B9LymxJkpT48TFlQVjU5SHNFb2M)

**Comment by MarioSonic2987** [comment] 2017-02-14 16:01
Still happens. https://gist.github.com/MarioSonic2987/d787f6fe972df0ddab7a7435e77eea57

**Comment by Zangetsu38** [comment] 2017-02-14 16:08
Fixed https://github.com/RPCS3/rpcs3/pull/2385#issuecomment-279751225

**Comment by raven02** [comment] 2017-02-14 16:16
thx i must be asleep .

**Comment by MarioSonic2987** [comment] 2017-02-14 16:21
With #2385, gives Win32 error. https://gist.github.com/MarioSonic2987/b03461756e121e356c66a84823bc8085#file-log-dx12-skate-2-2-log

**Comment by Zangetsu38** [comment] 2017-02-14 16:23
Yes, exactly  same crash with other several game, DX12 need just more work, But nothing to do with it, the problem is also.But nothing to do with it, the problem is also.

**Comment by MarioSonic2987** [comment] 2017-02-15 18:57
Remains labels for this issue.

**Comment by mchtt** [comment] 2017-02-16 13:22
Awesome progress ! Finally one of the skate game goes ingame, this made my day, you guys are amazing,
may i ask the list of modules you activated in rpcs3 ?

**Comment by MarioSonic2987** [comment] 2017-03-08 06:36
With #2482, it's improved a bit.
![](http://i.imgur.com/5VCVodu.jpg)

**Comment by MarioSonic2987** [comment] 2017-03-08 14:12
![](http://i.imgur.com/S2BewJ9.png)
With RenderDoc, it seems correctly rendered (with remove some layers).
[RenderDoc Vulkan](https://drive.google.com/open?id=0B9LymxJkpT48RE9xYV9LTzBjQ2s)

**Comment by MarioSonic2987** [comment] 2017-03-18 14:13
![](http://i.imgur.com/js1xKsh.png)
In https://github.com/RPCS3/rpcs3/commit/2b79a3691f064362b4ee9fac9c316668fffe1d16, it's improved a bit (I think).

**Comment by MarioSonic2987** [comment] 2017-03-30 07:25
[Video](https://www.youtube.com/watch?v=Li6csfacE5w)

**Comment by MarioSonic2987** [comment] 2017-04-09 21:17
With SPU precise, map doesn't disappear.

**Comment by MarioSonic2987** [comment] 2017-04-10 07:36
![image](https://cloud.githubusercontent.com/assets/20027681/24850629/18301f34-1dd1-11e7-9e6d-2b40964965e9.png)
With SPU precise, map doesn't disappear.

**Comment by mchtt** [comment] 2017-04-10 17:30
are you able to move on ground without falling ?

**Comment by MarioSonic2987** [comment] 2017-04-10 17:38
I haven't testes further, nut I think yes.

**Comment by MarioSonic2987** [comment] 2017-04-10 17:49
I tested now, and I'm not able to move.

**Comment by mchtt** [comment] 2017-04-11 19:21
same here, the demo timer is going on but no response from inputs !
at least the character is not falling through the ground anymore :-D

**Comment by mchtt** [comment] 2017-04-14 14:25
with today latest build i went at the same point with the full game (not demo), i can open the menu but the character does not respond to inputs ! weird, at least it's now ingame

**Comment by mchtt** [comment] 2017-04-19 18:08
also do you know that skate games register joysticks inputs @ 120 hz ? will it be a problem ?

**Comment by MarioSonic2987** [comment] 2017-05-25 04:24
@mchtt Can you test this game with Vulkan if your graphics card supports it? My GeForce 820M doesn't support it.

**Comment by mchtt** [comment] 2017-06-25 18:47
sorry for the late reply, i will !

**Comment by mchtt** [comment] 2017-06-25 18:59
just tried it (demo version) 👍 24/06/2017 build.
a lot of improvements regarding framerate !
30 fps in every menus, new freezes while loading, 40-60 fps in-game, falling to the ground again.
while falling the skater responds to my gamepad inputs :-D
still that ORANGE graphics (vulkan/open GL)

**Comment by mchtt** [comment] 2017-07-11 17:17
for today i was able to play the full game like in this [video](https://www.youtube.com/watch?v=fqNYj4BY3IM)

**Comment by MarioSonic2987** [comment] 2017-08-21 06:35
Tested in https://github.com/RPCS3/rpcs3/commit/c85806c422bc79265023866edee00f07aa051352:

![image](https://user-images.githubusercontent.com/20027681/29506349-873b84bc-864b-11e7-9653-a4ffbf105a8b.png)

There's zfighting in pillars.

**Comment by MarioSonic2987** [comment] 2017-12-20 10:21
Tested in https://github.com/RPCS3/rpcs3/commit/f24491de84fd5c0edb73ad876d9b1c3cef5da1f6:

![image](https://user-images.githubusercontent.com/20027681/34202254-7b54f954-e577-11e7-8775-db89b126440b.png)
[Log OpenGL](https://github.com/RPCS3/rpcs3/files/1575116/Log.Skate.2.20-12-17.GL.gz)
[Shaderlog OpenGL](https://drive.google.com/open?id=1vEFzTpaoTAmRqx29aPDv8q3xEPWPbpqK)
[RenderDoc OpenGL](https://drive.google.com/open?id=1WdC4PI5szvbC9UuChWfcwVYzHrMdgACH)

**Comment by mchtt** [comment] 2018-01-01 11:46
looks way better :-)

**Comment by MarioSonic2987** [comment] 2018-01-01 11:47
@mchtt In emulator, it's the same (orange issue).

**Comment by MarioSonic2987** [comment] 2018-03-14 06:53
With #4265, has the same improvements as Skate 3. Objects are no longer flickering and shadows are rendered properly, but not perfectly. Orange filter is still there,
![image](https://user-images.githubusercontent.com/20027681/37387418-90e3de8a-275c-11e8-837f-51eb88a694a2.png)

**Comment by MarioSonic2987** [comment] 2018-03-22 10:59
With #4311, orange filter is improved:
![image](https://user-images.githubusercontent.com/20027681/37713381-0f1d20da-2d17-11e8-9d08-2bd19dd21b5c.png)

**Comment by MarioSonic2987** [comment] 2018-03-25 11:30
With #4312, there's no orange filter, but a multicolor filter. Actually it fixes gamma, like Skate 3.
![image](https://user-images.githubusercontent.com/20027681/37874495-7c91800e-3030-11e8-8258-c72c65178bd3.png)

RenderDoc:
![](https://cdn.discordapp.com/attachments/361063300487970818/426829905309990915/skd-11.png)

**Comment by MarioSonic2987** [comment] 2018-03-29 09:00
With https://github.com/RPCS3/rpcs3/commit/a17025c465d71c67a0c6efd0d78d46fbd1e33b1d:

![image](https://user-images.githubusercontent.com/20027681/38079731-eab9c052-333f-11e8-94b6-93ceff1084eb.png)
[Log OpenGL](https://github.com/RPCS3/rpcs3/files/1859312/Log.Skate.2.29-3-18.GL.gz)
[Shaderlog OpenGL](https://drive.google.com/open?id=1BbqsPy_sEkI4-ggPNWqCyu6u_XqZEH5N)
[RenderDoc OpenGL](https://drive.google.com/open?id=1ehr1Hnb7yZEeAoeLEh7Z2Coh3RVniQ9P)

**Comment by kd-11** [comment] 2018-03-29 10:03
Like every other game with grading filter issues, this game is using a 3d palette for color grading. Either the contents of the 3d lookup palette are wrong or the computed vector is inacurrate. I'm leaning more towards the latter. Hard to tell without further digging.

**Comment by kd-11** [comment] 2018-03-29 11:04
The palette is definately wrong, no doubt about it. It does not have the usual left-right, top-bottom gradient expected which makes me think 3d texture uploads are still broken. Will take a proper look probably in the next few days.

**Comment by Asinin3** [comment] 2018-04-03 09:05
Fixed with #4382 
![kd_2018-04-01_117](https://user-images.githubusercontent.com/15137035/38240091-18e16840-371e-11e8-909c-bd36aae4e9e3.jpg)

**Comment by AniLeo** [comment] 2018-04-05 10:11
Closing as solved

**Comment by MarioSonic2987** [comment] 2018-04-05 10:12
Only remains broken shadows (same glitch as Skate 3).

**Closed by AniLeo** 2018-04-05 10:11 UTC
Labels: Render: Direct3D 12, Render: OpenGL, Render: Vulkan

**Comment by sheddup** [comment] 2018-04-05 22:19
Whats the performance like compared to Skate 3?

**Comment by Asinin3** [comment] 2018-04-05 22:26
@sheddup Github isn't the place for discussion, you can ask on discord: https://discord.me/RPCS3 or our forums.
