### ISSUE TITLE
BLUS30023 - The Godfather: The Don's Edition

### ISSUE THREAD

**Issue by chiefali06** [RPCS3/rpcs3#5067] opened 2018-08-31 08:26 UTC
Game has graphic loading errors [PPU fastest, SPU fastest]
[BLUS30023 Capture.zip](https://github.com/RPCS3/rpcs3/files/2357872/BLUS30023.Capture.zip)

![game error1](https://user-images.githubusercontent.com/42862070/44901634-9b37af80-ad10-11e8-84d5-77aedaa311e0.PNG)
![game error 3](https://user-images.githubusercontent.com/42862070/44901639-a12d9080-ad10-11e8-9bd4-f98c520a9fd8.PNG)

**Comment by chiefali06** [comment] 2018-09-04 15:01
Im still waiting...

**Comment by AniLeo** [comment] 2018-09-04 15:15
Waiting for?

Also, what you uploaded wasn't a log, and the issue is missing a RRC capture.

**Comment by chiefali06** [comment] 2018-09-06 16:18
[BLUS30023 Capture.zip](https://github.com/RPCS3/rpcs3/files/2357852/BLUS30023.Capture.zip)

Here it is.

**Comment by chiefali06** [comment] 2018-09-10 14:29
Im still waiting...

**Comment by AniLeo** [comment] 2018-09-10 15:23
Waiting for what? The capture is now attached, so the issue is good.

**Comment by chiefali06** [comment] 2018-09-10 15:26
Come on brother, I attached 4 days ago and you add new labels now

**Comment by Asinin3** [comment] 2018-09-10 15:30
Labels don't do anything other than allow people to search by filters on the issue page.

**Comment by chiefali06** [comment] 2018-09-10 15:34
I knew it, I mean he told me The capture is now attached I told him , I attached 4 days ago

**Comment by AniLeo** [comment] 2018-09-10 15:50
It doesn't mean anything, I can remove labels and it will be the same thing

**Comment by chiefali06** [comment] 2018-09-10 15:59
Allright thank you.

**Comment by kd-11** [comment] 2018-09-14 08:31
Retest with https://github.com/RPCS3/rpcs3/pull/5125

**Comment by Asinin3** [comment] 2018-09-14 11:18
Confirmed fixed with #5125 
![kd_2018-09-14_2493](https://user-images.githubusercontent.com/15137035/45547285-cdb4d280-b80f-11e8-8b25-edb69ef08e9c.jpg)
![kd_2018-09-14_2491](https://user-images.githubusercontent.com/15137035/45547286-cdb4d280-b80f-11e8-9b3f-e8720f7bf3d6.jpg)

**Comment by chiefali06** [comment] 2018-09-14 11:26
This is Godfather II but I suggested The Godfather Don's Edition - [Blus30023]

**Comment by Asinin3** [comment] 2018-09-14 11:27
Oh, oops. Then you can test it yourself because I don't have that one.

**Comment by chiefali06** [comment] 2018-09-14 11:37
> Oh, oops. Then you can test it yourself because I don't have that one. Link to PR build: https://ci.appveyor.com/api/buildjobs/1yr6uqr42veawn6u/artifacts/rpcs3-v0.0.5-02761273_win64.7z

Its not same but fire effects same
![err](https://user-images.githubusercontent.com/42862070/45548067-a0761d80-b82b-11e8-933a-8a4cf823c2a3.PNG)
![still](https://user-images.githubusercontent.com/42862070/45548069-a23fe100-b82b-11e8-9835-35a889d087c0.PNG)

**Comment by chiefali06** [comment] 2018-09-14 11:50
And mini map don't show ways 
![minimap](https://user-images.githubusercontent.com/42862070/45548585-8b9a8980-b82d-11e8-934f-e9c44cf400d3.PNG)

**Comment by Emulator-Team-2** [comment] 2018-09-14 11:55
@chiefali06 
Can you delete your messages from https://github.com/RPCS3/rpcs3/pull/5125

**Comment by chiefali06** [comment] 2018-09-14 12:09
> @chiefali06
> Can you delete your messages from #5125

Sure

**Comment by chiefali06** [comment] 2018-09-14 12:41
If police open sirens game going to be like that 
![error 2](https://user-images.githubusercontent.com/42862070/45550812-b4724d00-b834-11e8-915f-74e5f23e16e9.PNG)

**Comment by chiefali06** [comment] 2018-09-15 19:30
Anyone ?

**Comment by AniLeo** [comment] 2018-09-15 19:36
Don't spam, if that PR didn't fix the issue you have to keep testing newer ones until it's eventually fixed

**Comment by chiefali06** [comment] 2018-09-15 19:43
Allright, sorry

**Comment by chiefali06** [comment] 2018-10-22 18:43
You told me don't spam but any of you did nothing about that

**Comment by AniLeo** [comment] 2018-10-22 18:45
About what? You already stopped spamming

**Comment by chiefali06** [comment] 2018-10-22 18:51
I mean about Issue

**Comment by AniLeo** [comment] 2018-10-22 18:55
The issue is open and on the tracker, it will be solved either when someone wants to look at it or when it's solved by chance when looking into other issues.

You only opened this issue two months ago, there are 400 other issues in the tracker, and contributors choose whichever issues they want to work on.

**Comment by kd-11** [comment] 2020-01-19 10:59
Most of the issues reported here are already fixed. The remaining issue with reflections is being tracked separately (https://github.com/RPCS3/rpcs3/issues/7286)

**Closed by kd-11** 2020-01-19 10:59 UTC
Labels: Bug, RSX
