### ISSUE TITLE
[Regression] Okami HD - Missing Text/Health Bar

### ISSUE THREAD

**Issue by captainfanboy** [RPCS3/rpcs3#3511] opened 2017-09-28 15:15 UTC
I recently downloaded the most recent updates for RPCS3 after using one I downloaded on July 16, 2017 (so I assume v0.0.2 #4939 or #4941). Only game I played was Okami HD, and it was working perfectly fine, except for the usual slow down areas and FPS drops.

After upgrading to the most recent one, certain graphics are missing. 'New Game' is missing from the menu, as well as a bunch of other text, health bar is missing, etc. These were working fine before, and I haven't changed any of my rendering settings between v0.0.2 and v0.0.3. Apologies if I've missed uploading anything as I'm new to using GitHub/ reporting emulator issues.

![capture](https://user-images.githubusercontent.com/32366040/30974576-f8b2a0fc-a43d-11e7-8d3f-1946e0684d5a.PNG)
![capture1](https://user-images.githubusercontent.com/32366040/30974577-f8b45410-a43d-11e7-8f3c-0a0551286ea6.PNG)
![capture2](https://user-images.githubusercontent.com/32366040/30974578-f8c1140c-a43d-11e7-87b5-12dc892fb3eb.PNG)

**Comment by AniLeo** [comment] 2017-09-28 15:17
Has this been tested with Strict Rendering Mode?

**Comment by captainfanboy** [comment] 2017-09-28 15:20
Yes - my normal settings are the one in the Compatibility List on the main website, and I've tried Strict Rendering Mode both on and off.

**Comment by tazzkiller** [comment] 2017-10-07 15:15
Same for me on build 0.0.3-6353 but work correctly on build 0.0.3-3-01ffaab

AMD FX(tm)-8350 Eight-Core Processor  | 8 Threads | 7.95 GiB RAM | AVX

**Comment by elemileTLDR** [comment] 2017-10-10 04:58
Issue still present on v0.0.3-3-6d6b281 Alpha.

Lenovo Y510p. i7-4940MX @3.6 GHz. 2x SLI NVIDIA GeForce GT755M 2GB. 16GB DDR3.

**Comment by Xcedf** [comment] 2017-10-15 18:23
revision r061824a7 caused the regression, previous revision works fine, can't tell for sure which part since few commits were squashed but changing supports_multidraw = true line to false fixes the issue menu elements look perfect yet causes severe artifacts on Vulkan and less horrible on OGL, so smth in multidraw code is wrong
kd11, please take a look

**Comment by kd-11** [comment] 2017-10-24 12:37
Artefacting with `multidraw=false` has been fixed for some time now. It looks like there are still corner cases where it should behave differently, but you may retest @Xcedf

**Comment by Xcedf** [comment] 2017-10-25 08:46
Yes, confirm, game now works fine with multidraw= false

**Comment by marcussacana** [comment] 2017-10-25 16:11
multidraw=false is a launch paramter?

**Comment by kd-11** [comment] 2017-10-25 22:56
Just use strict mode with current master and should be fixed

**Comment by elemileTLDR** [comment] 2017-10-26 00:30
@kd-11- It does work on v0.0.3-3-9c94956. Thanks a lot.

**Comment by kd-11** [comment] 2017-10-26 11:25
I'll close this for the moment. Investigation into why draw call collapsing isn't working with this title will need more information and testing.

**Closed** 2017-10-26 12:00 UTC
