### ISSUE TITLE
Heavy Rain [BCUS98164] Mem: Access Violation

### ISSUE THREAD

**Issue by Nikorasu95** [RPCS3/rpcs3#4956] opened 2018-08-05 04:16 UTC
[RPCS3.log.gz](https://github.com/RPCS3/rpcs3/files/2260038/RPCS3.log.gz)
The game used to work on a build way back. I don't remember what build it was. I don't have time bisecting it either.  I tired all configurations and the game still won't boot.  The error is F {PPU[0x100000c] Thread (Read Chunk Thread HDD) [0x0056fd98]} MEM: Access violation writing location 0xd01108f0
I'm using build 0.0.5-7161-69af60749 Alpha.
My specs:
Intel i7 8700K
GTX 1080 Ti
16 GB DDR4
Windows 10 Version 1803

**Comment by elad335** [comment] 2018-08-05 05:01
duplicate of #4566

**Closed** 2018-08-05 12:05 UTC
