### ISSUE TITLE
Teenage Mutant Ninja Turtles™: Mutants in Manhattan [NPEB02246] 0.0.18-12718 sound pop and decrease sound volume

### ISSUE THREAD

**Issue by Augusto7743** [RPCS3/rpcs3#10853] opened 2021-09-11 03:28 UTC
If using SPU LLVM always in randomly happen :
- music and sound fx are played with a sequential high volume pop noise that stop few times if changing ingame sound options volume.
- music and sound fx volume are decreased to 20 %.

Not happen if using SPU ASMJIT.

log1 LLVM and log2 ASMJIT

[RPCS3.zip](https://github.com/RPCS3/rpcs3/files/7147141/RPCS3.zip)

**Comment by Megamouse** [comment] 2021-09-11 07:56
Duplicate of your own issue.
Duplicate of #9609

**Closed by Megamouse** 2021-09-11 07:56 UTC
Labels: Meta: Duplicate

**Comment by Augusto7743** [comment] 2021-09-11 13:17
Not close. see again.
TMNT Mutant in Manhattan ... the link "duplicate" is TMNT Turtles in Time being another game.
