### ISSUE TITLE
Golden Axe: Beast rider[BLUS30209], black screen+game sounds after first cutscene, RSX: Depth<->RGBA blit on a framebuffer requested but not supported

### ISSUE THREAD

**Issue by ruthan** [RPCS3/rpcs3#5158] opened 2018-09-21 15:08 UTC
Tested Core i7 4770S, Vulkan, Nvidia G970,Win10 64bit.

 After first cutscene only black screen + ingame sounds.
[RPCS3.zip](https://github.com/RPCS3/rpcs3/files/2405888/RPCS3.zip)

Its the same with Opengl:
[RPCS3.zip](https://github.com/RPCS3/rpcs3/files/2405927/RPCS3.zip)

There is interesnting message:
E {rsx::thread} RSX: Depth<->RGBA blit on a framebuffer requested but not supported x2

**Comment by ruipin** [comment] 2018-09-22 19:53
Try #5115

`E {rsx::thread} RSX: Depth<->RGBA blit on a framebuffer requested but not supported` is not serious, and would not cause crashes. Just means the game wants to do a blit operation that your GPU does not support. You might want to try WCB+CPUblit.

**Comment by ruthan** [comment] 2018-09-23 01:26
I have few questions:
How is exactly the Strict rendering mode - its some emulator temporary work around or valid mode, should be its need be autodetected?
  How to try that 5115 where is binary to download?

**Comment by scribam** [comment] 2018-09-24 09:50
@ruthan Here is the link to the binary to try #5115: https://ci.appveyor.com/api/buildjobs/71epwyta5x2m2dik/artifacts/rpcs3-v0.0.5-fa431b8c_win64.7z

Duplicate of #3361

**Closed** 2018-09-24 10:20 UTC
Labels: Meta: Duplicate

**Comment by ruthan** [comment] 2018-09-24 12:19
Ok i have tested 5115 without Strict rendering its still broken.

**Comment by HenningJW** [comment] 2018-09-24 12:29
@ruthan sroll to the bottom of the pr and click on "Show all checks", then on "Details" (AppVeyor for Windows, TravisCI for Linux). On AppVeyor you can download the build by clicking on artifacts.
