### ISSUE TITLE
HLE : cellvdec and CellOskDialog error

### ISSUE THREAD

**Issue by Kristiqn5** [RPCS3/rpcs3#1999] opened 2016-07-30 13:37 UTC
![loading](https://cloud.githubusercontent.com/assets/13494982/17270825/840add40-5674-11e6-8636-d60c2c952f2a.png)
Game opens and shows loading screen but freezes when intro is about to play 
F {PPU[0x22e] Thread (VideoDecoder[0x22d] Thread)} class fmt::exception thrown: vdecOpen::<lambda_b56ea98387005714a52e6dab677188ae>::operator ()(): Unsupported time_base.num (33333)
(in file Emu\Cell\Modules\cellVdec.cpp:306)

If LibVdec is enabled it skips the intro and gives this
E {PPU[0x28] Thread (main_thread) [0x006d60a0]} PPU: 'cellOskDialogAddSupportLanguage' aborted
F {PPU[0x28] Thread (main_thread) [0x006d60a0]} class fmt::exception thrown: cellOskDialogAddSupportLanguage(): 
(in file Emu\Cell\Modules\cellOskDialog.cpp:58)

log:
http://www.mediafire.com/download/ah3l13z477dls10

**Comment by raven02** [comment] 2016-07-30 15:28
Try to add dmux+dmuxpamf to see if it helps the vdec error.

**Comment by raven02** [comment] 2016-08-01 14:25
Duplicate of #1936

**Closed by raven02** 2016-08-01 14:25 UTC
Labels: hle
