### ISSUE TITLE
SSX - Custom music feature works and plays music, but is horribly broken

### ISSUE THREAD

**Issue by SlyCooperReloadCoded** [RPCS3/rpcs3#15024] opened 2024-01-08 14:08 UTC
### Quick summary

The game's custom music feature, which reads soundtracks stored as MP3 in dev_hdd0/music/ works, but has too many bugs to warrant using.

### Details

SSX has a custom playlist feature which looks on the console for playlists, and if they have proper metadata, the game will play them and use its special gameplay-based distortion effects on them.  This feature works on latest master, it scans the playlists and starts playing them, however it's horribly broken as there's way too many bugs to warrant using it:

1. The music is played way too softly.  Even if you amplify the crap out of it in Audacity, it's practically silent compared to everything else going on.  Compare that to other videos that use the feature, where the music overpowers everything else:

(Video is using the Xbox 360 release but PS3 works the exact same)
https://youtu.be/29vFty9FIro?t=144

2. At the end of the first song in the playlist, a loud audio corruption will happen, like a loud pop.

3. Also, instead of moving to the next song, it starts playing the first one again, likely looping it infinitely.

4. If you exit the current event and go into another one, all music completely stops, probably because it's trying to read the next song, which it's proven to be unable to do.

For this test I've used a custom playlist containing 4 songs.

I apologize if the attached log shows any missing file errors. On a code level, the game automatically looks for game files inside and outside of the data archives, so the modding community just extracts them and yoinks the archives. None of the extracted files have been modified, and the issue is present on a clean rip of the disc.

### Attach a log file

[RPCS3.log.gz](https://github.com/RPCS3/rpcs3/files/13861437/RPCS3.log.gz)

**Comment by Megamouse** [comment] 2024-01-08 15:31
Duplicate of #11596

**Closed by Megamouse** 2024-01-08 15:31 UTC
Labels: Bug, Firmware: HLE
