### ISSUE TITLE
Criterion Need For Speed Most Wanted does not render most car and npc car reflections.

### ISSUE THREAD

**Issue by Playstation-3** [RPCS3/rpcs3#14919] opened 2023-12-21 04:27 UTC
### Quick summary

Rpcs3, with any settings i try does not render most car reflections at all.

### Details

Rpcs3 does not seem to be rendering (almost) any car reflections, reflections are ether black or white. Tires and rims also glow white. This Graphical glitch applies to all cars and trucks, but not to anything else in the environment at all (that i noticed) I booted the game with default configuration.

### log

in the log, i am not attaching the whole files, but giving you every line that is red or orange, with the exception of 1 blue, because you probably do not need hundreds of "New block compiled successfully" or "Program compiled successfully." This is from me just casually playing the game fore a bit, then closing it.

```
E sys_net: get_sign_msgs: port 3658 not present
- RSX: Found Vulkan-compatible GPU: 'AMD Radeon(TM) Graphics' running on driver 2.0.279
E RSX: Your GPU does not support alpha-to-one for multisampling. Graphics may be inaccurate when MSAA is enabled.

U sys_prx TODO: _sys_prx_register_module(name=“cellProcessElf”, opt=*0xd0040c90)

U sys_ss TODO: sys_ss_access_control_engine(pkg_id=0x1, a2=0x1, a3=0xd0040a00)
E SYS: 'sys_ss_access_control_engine' failed with 0x80010003 : CELL_ENOSYS [1]
U sys_ss TODO: sys_ss_access_control_engine(pkg_id=0x2, a2=0xd0040a00, a3=0x0)

U sys_prx TODO: _sys_prx_register_module(name=“_sysProcessElf”, opt=*0xd0040da0)

U PPU TODO: Unimplemented syscall sys_ss_media_id -> CELL_OK (r3=0x10001, r4=0xd0040650, r5=0x200, r6=0x3b4d7a60, r7=0x3b4d7a58, r8=0x3b4d7e94, r9=0x0, r10=0x1000000)

U sys_prx TODO: _sys_prx_get_module_id_by_name(name=“cellLibprof”, flags=0, pOpt=*0x0)

U cellMusic TODO: cellMusicInitialize2(mode=0, spuPriority=16, func=*0xbd3c60, userData=*0x3bbe4818)

U cellSearch TODO: cellSearchStartListSearch(type=0x9, sortOrder=0x1, outSearchId=*0xd00402e0)
E SYS: 'cellSearchGetContentInfoByOffset' failed with 0x8002c80c : CELL_SEARCH_ERROR_OUT_OF_RANGE [1]
U cellSearch TODO: cellSearchEnd(searchId=0x1)

E SYS: 'sys_fs_opendir' failed with 0x8001003a : CELL_ENOTMOUNTED, “/UNLOCKS” [1]

E SYS: 'cellNetCtlInit' failed with 0x80130102 : CELL_NET_CTL_ERROR_NOT_TERMINATED [1]
U cellNetCtl TODO: cellNetCtlAddHandler(handler=*0xbed0f8, arg=*0x3a0682e8, hid=*0x3a068358)
E SYS: 'sceNpInit' failed with 0x8002aa02 : SCE_NP_ERROR_ALREADY_INITIALIZED [1]
U cellSearch TODO: cellSearchStartListSearch(type=0x9, sortOrder=0x1, outSearchId=*0xd00402e0)
E SYS: 'cellSearchGetContentInfoByOffset' failed with 0x8002c80c : CELL_SEARCH_ERROR_OUT_OF_RANGE [1]
U cellSearch TODO: cellSearchEnd(searchId=0x2)

E SYS: 'sys_fs_opendir' failed with 0x8001003a : CELL_ENOTMOUNTED, “/UNLOCKS” [1]


E RSX: Format incompatibility detected, reporting failure to force data copy (VK_FORMAT=0x2C, GCM_FORMAT=0x9F)

E SPU: [0x05d80] SPU Analyser failed, 10 vs 47

U cellNetCtl TODO: cellNetCtlDelHandler(hid=0x0)
E SYS: 'sys_timer_stop' failed with 0x80010005 : CELL_ESRCH [1]

U PPU TODO: Unimplemented syscall syscall_988 -> CELL_OK (r3=0x1, r4=0x0, r5=0x0, r6=0x0, r7=0xd0040598, r8=0xf814f0, r9=0x0, r10=0x10)


E sys_net: get_sign_msgs: port 3658 not present
- RSX: Found Vulkan-compatible GPU: 'AMD Radeon(TM) Graphics' running on driver 2.0.279
E RSX: Your GPU does not support alpha-to-one for multisampling. Graphics may be inaccurate when MSAA is enabled.

E SPU: [0x058c0] SPU Analyser failed, 92 vs 161

U sys_prx TODO: _sys_prx_register_module(name=“cellProcessElf”, opt=*0xd0040c90)

U sys_ss TODO: sys_ss_access_control_engine(pkg_id=0x1, a2=0x1, a3=0xd0040a00)
E SYS: 'sys_ss_access_control_engine' failed with 0x80010003 : CELL_ENOSYS [1]
U sys_ss TODO: sys_ss_access_control_engine(pkg_id=0x2, a2=0xd0040a00, a3=0x0)

U sys_prx TODO: _sys_prx_register_module(name=“_sysProcessElf”, opt=*0xd0040da0)

U PPU TODO: Unimplemented syscall sys_ss_media_id -> CELL_OK (r3=0x10001, r4=0xd0040650, r5=0x200, r6=0x3b4d7a60, r7=0x3b4d7a58, r8=0x3b4d7e94, r9=0x0, r10=0x1000000)

U sys_prx TODO: _sys_prx_get_module_id_by_name(name=“cellLibprof”, flags=0, pOpt=*0x0)
U cellMusic TODO: cellMusicInitialize2(mode=0, spuPriority=16, func=*0xbd3c60, userData=*0x3bbe4818)
U cellSearch TODO: cellSearchStartListSearch(type=0x9, sortOrder=0x1, outSearchId=*0xd00402e0)
E SYS: 'cellSearchGetContentInfoByOffset' failed with 0x8002c80c : CELL_SEARCH_ERROR_OUT_OF_RANGE [1]
U cellSearch TODO: cellSearchEnd(searchId=0x1)

E SYS: 'sys_fs_opendir' failed with 0x8001003a : CELL_ENOTMOUNTED, “/UNLOCKS” [1]
E SYS: 'cellNetCtlInit' failed with 0x80130102 : CELL_NET_CTL_ERROR_NOT_TERMINATED [1]
U cellNetCtl TODO: cellNetCtlAddHandler(handler=*0xbed0f8, arg=*0x3a0682e8, hid=*0x3a068358)
E SYS: 'sceNpInit' failed with 0x8002aa02 : SCE_NP_ERROR_ALREADY_INITIALIZED [1]
U cellSearch TODO: cellSearchStartListSearch(type=0x9, sortOrder=0x1, outSearchId=*0xd00402e0)
E SYS: 'cellSearchGetContentInfoByOffset' failed with 0x8002c80c : CELL_SEARCH_ERROR_OUT_OF_RANGE [1]
U cellSearch TODO: cellSearchEnd(searchId=0x2)
E SYS: 'sys_fs_opendir' failed with 0x8001003a : CELL_ENOTMOUNTED, “/UNLOCKS” [1]
E RSX: Format incompatibility detected, reporting failure to force data copy (VK_FORMAT=0x2C, GCM_FORMAT=0x9F)

U cellSearch TODO: cellSearchStartListSearch(type=0x9, sortOrder=0x1, outSearchId=*0xd00402e0)
E SYS: 'cellSearchGetContentInfoByOffset' failed with 0x8002c80c : CELL_SEARCH_ERROR_OUT_OF_RANGE [1]
U cellSearch TODO: cellSearchEnd(searchId=0x3)


U cellRtc TODO: cellRtcGetCurrentTick(pTick=*0xd0109e68)

U cellRtc TODO: cellRtcGetCurrentTick(pTick=*0xd0109e68)

U cellNetCtl TODO: cellNetCtlDelHandler(hid=0x0)
E SYS: 'sys_timer_stop' failed with 0x80010005 : CELL_ESRCH [1]
U PPU TODO: Unimplemented syscall syscall_988 -> CELL_OK (r3=0x1, r4=0x0, r5=0x0, r6=0x0, r7=0xd0040598, r8=0xf814f0, r9=0x0, r10=0x10)
```

### Screenshots
Car is gone
![Screenshot 2023-12-20 222943](https://github.com/RPCS3/rpcs3/assets/141864821/ce28e81f-d553-44dc-a577-c6561d9beaf4)
Black windows go through smoke trail
![Screenshot 2023-12-20 222101](https://github.com/RPCS3/rpcs3/assets/141864821/7298a6ac-f29b-4ea5-a593-a07e08483641)
Lack of glossy light reflection from tunnel lights
![Screenshot 2023-12-20 221954](https://github.com/RPCS3/rpcs3/assets/141864821/3cd87e36-4243-4b5f-9edc-3e9e536860da)
Sun seems to be the only glossy reflection that acts on the car
![Screenshot 2023-12-20 221856](https://github.com/RPCS3/rpcs3/assets/141864821/4624ef23-a6c9-4b24-bc28-69c3ee57e038)
Glow in the dark
![Screenshot 2023-12-20 221702](https://github.com/RPCS3/rpcs3/assets/141864821/5153c3b1-e565-439d-8b90-991bb5fd6cb3)
More glow in the dark, with road reflections showing perfectly
![Screenshot 2023-12-20 221639](https://github.com/RPCS3/rpcs3/assets/141864821/8f1a7036-f4fc-434f-990e-9de66f8152b5)
More glowing and headlight blackness, the rims on cars also glow
![Screenshot 2023-12-20 221614](https://github.com/RPCS3/rpcs3/assets/141864821/01fce15f-d917-42df-b9fd-ceb9ac40de36)
More road reflection examples
![Screenshot 2023-12-20 221532](https://github.com/RPCS3/rpcs3/assets/141864821/99cf9560-1a49-4776-801e-053d2f88f760)
Total general screenshot
![Screenshot 2023-12-20 221114](https://github.com/RPCS3/rpcs3/assets/141864821/30e38536-4ea9-44f1-8bb8-acdbd13e5738)

### Specs
![Screenshot 2023-12-20 230118](https://github.com/RPCS3/rpcs3/assets/141864821/1ff91208-49d9-4b77-b3b0-34e4a56bdd9a)
![Screenshot 2023-12-20 230126](https://github.com/RPCS3/rpcs3/assets/141864821/e8a2cdda-b33e-441f-a6fa-447b1e03d026)
![Screenshot 2023-12-20 230133](https://github.com/RPCS3/rpcs3/assets/141864821/398e3682-8c1e-41e9-9e99-be9dd76cd61a)
![Screenshot 2023-12-20 230149](https://github.com/RPCS3/rpcs3/assets/141864821/bcba5f90-192c-4c53-afea-81d38241c781)

### Other details
Ask for more info if needed.
![Screenshot 2023-12-20 231549](https://github.com/RPCS3/rpcs3/assets/141864821/1d2c4918-9eee-48c4-a4bf-dabd753b8e2a)
![image_2023-12-20_231815274](https://github.com/RPCS3/rpcs3/assets/141864821/e4a92bca-4521-4a5f-ae83-4d7c9b89982a)

**Comment by AniLeo** [comment] 2023-12-21 08:13
Missing log file and RSX captures.

**Comment by Ordinary205** [comment] 2023-12-21 08:23
You have to enable WCB with RSX Tiled memory in order to fix broken car lighting and reflections, enabling this option would result a huge performance impact, so please dont complain on why the performance are acting worse, its just the way on how the PS3 works when emulating it more accurately for this game.

**Comment by AniLeo** [comment] 2023-12-21 08:29
Closing then since the issue is bad settings

**Closed by AniLeo** 2023-12-21 08:29 UTC
Labels: Need Information
