### ISSUE TITLE
Vulkan w/ Gundam Extreme Vs Full Boost graphical trailing

### ISSUE THREAD

**Issue by lm231** [RPCS3/rpcs3#7267] opened 2020-01-17 08:37 UTC
This video shows the issue: https://youtu.be/mzPUvShJIZ8
Log: https://pastebin.com/FduqNt9P

Ryzen 5 3600
16gb ddr4 3733mhz RAM
RX 5700 XT
Windows 10
Latest version of RPCS3 (v0.0.8-9395 Alpha [2020-01-17] )
AMD Driver Version 19.12.2

This did not happen when I had my RX 580 8gb, but it may be because I was on an older AMD driver version at the time. It's either an issue with Navi or the newly released AMD drivers. OpenGL shows no screen at all, but that has been reported already.

**Comment by Emulator-Team-2** [comment] 2020-01-17 09:02
@lm231 
Probably duplicate of #6999.
Try disabling Anti-aliasing in the GPU tab settings.
Close this issue.

**Comment by kd-11** [comment] 2020-01-17 10:45
Navi has issues with rpcs3 when msaa is enabled.

**Closed by kd-11** 2020-01-17 10:45 UTC
