### ISSUE TITLE
Links in dark mode are hard to see

### ISSUE THREAD

**Issue by rakleed** [RPCS3/rpcs3#12681] opened 2022-09-19 00:44 UTC
### Quick summary

Links are hard to see when using the dark theme, as they are too dark, although they should be lighter.

### Details

The issue reproduces on the Welcome and About screens.

### Attach a log file

[RPCS3.log](https://github.com/RPCS3/rpcs3/files/9595495/RPCS3.log)

### System configuration

macOS 12.6

### Other details

![Screenshot 2022-09-19 at 03 34 09](https://user-images.githubusercontent.com/19418601/190935061-2dc55c8f-a251-4513-b540-8189203bbf0a.png)

![Screenshot 2022-09-19 at 03 41 17](https://user-images.githubusercontent.com/19418601/190935064-e887eba0-9fdc-42ca-b67d-446033e39fcd.png)

**Comment by Darkhost1999** [comment] 2022-09-19 00:47
Duplicate of https://github.com/RPCS3/rpcs3/issues/12445

**Closed** 2022-09-19 06:55 UTC
