### ISSUE TITLE
Star Ocean 5 - Integrity And Faithlessness BLJM61325

### ISSUE THREAD

**Issue by DenisNinja** [RPCS3/rpcs3#14369] opened 2023-07-25 22:03 UTC
### Quick summary

the game Star Ocean 5 - Integrity And Faithlessness BLJM61325 does not work, it does not load, it stays on a buggy black screen, I have already passed the emulator log below, I hope that the responsible developers fix this error problem, after the qualified ones who saw my post about this problem delete this post of mine, I do not like to be showing my hardware configurations etc

### Attach a log file

- SYS: RPCS3 v0.0.28-15397-94bb75fb Alpha | master
- SYS: AMD Ryzen 9 5950X 16-Core Processor | 32 Threads | 31.89 GiB RAM | TSC: 3.400GHz | AVX+ | FMA3
- SYS: Operating system: Windows, Major: 10, Minor: 0, Build: 22621, Service Pack: none, Compatibility mode: 0
- SYS: Current Time: 2023-07-25T18:56:06
- RSX: Found vulkan-compatible GPU: 'NVIDIA GeForce RTX 2070 SUPER' running on driver 536.67.0.0
- SYS: Firmware version: 4.90
S UPDATER: RPCS3 is up to date!
S SYS: Updates found at /dev_hdd0/game/BLJM61325/
E SIG: Thread [Performance Sensor] is too sleepy. Waiting for it 16705.106µs already!
E SIG: Thread [Performance Sensor] is too sleepy. Waiting for it 32717.256µs already!
E SIG: Thread [Performance Sensor] is too sleepy. Waiting for it 64746.226µs already!
E SIG: Thread [Performance Sensor] is too sleepy. Waiting for it 131310.126µs already!
S PPU: Enabled: Non-Java Mode Fixup
- RSX: Found vulkan-compatible GPU: 'NVIDIA GeForce RTX 2070 SUPER' running on driver 536.67.0.0
S Input: The pad mode was changed to Multi-threaded
S Input: XInput device 0 connected
S GUI: Boot successful.
S PPU: LLVM: Loaded module v6-kusa-tGToprrXr0A3Hg7XwjS2r2-00001G-znver3.obj
S PPU: LLVM: Loaded module v6-kusa-F6TtnL1AAzmSjAtHEpHwK2-00001G-znver3.obj
S PPU: LLVM: Loaded module v6-kusa-qrSZxParXkhefPi2myJ9eL-00001G-znver3.obj
S PPU: LLVM: Loaded module v6-kusa-9rnUg6v1jkw1Hc8t1eJL9z-00001G-znver3.obj
S PPU: LLVM: Loaded module v6-kusa-6ezCiPuJFZFXaMzdVPgpFS-00001G-znver3.obj
S PPU: LLVM: Loaded module v6-kusa-VffEyeQQGjeFKL3QwnjUNV-00001G-znver3.obj
S PPU: LLVM: Loaded module v6-kusa-kT1MNxvP613XXELkY9e4pV-00001G-znver3.obj
S PPU: LLVM: Loaded module v6-kusa-WzEStc4qMhGQmZUGJnPkUX-00001G-znver3.obj
S PPU: LLVM: Loaded module v6-kusa-HQqKH5u7AoZAUgYAxyaokW-00001G-znver3.obj
S PPU: LLVM: Loaded module v6-kusa-nSKVHNmU5vGALpFru3cRN6-00001G-znver3.obj
S PPU: LLVM: Loaded module v6-kusa-K7AjaJ38tojsW7vkfsJNdk-00001G-znver3.obj
S PPU: LLVM: Loaded module v6-kusa-5fnSkoT4L7MphiMf5UpyxS-00001G-znver3.obj
S PPU: LLVM: Loaded module v6-kusa-8LpxY0fpzQETv9Z1esj8UR-00001G-znver3.obj
S PPU: LLVM: Loaded module v6-kusa-Ym6RwWjv3if8gzgHfJbv5T-00001G-znver3.obj
S PPU: LLVM: Loaded module v6-kusa-jX8x5P7G7xVSKaV2ekViYT-00001G-znver3.obj
S PPU: LLVM: Loaded module v6-kusa-pu5KovGkianFpz5vCE6eA9-00001G-znver3.obj
S PPU: LLVM: Loaded module v6-kusa-KuEr4Zc3uxXXQZjtcmzNJz-00001G-znver3.obj
S PPU: LLVM: Loaded module v6-kusa-MWgfrynxAyv1ky4LhiPq8T-00001G-znver3.obj
S PPU: LLVM: Loaded module v6-kusa-Pphrj6QGYKwWGNgGxEaPkz-00001G-znver3.obj
S PPU: LLVM: Loaded module v6-kusa-NgQJbocWa7296cRttcK1og-00001G-znver3.obj
S PPU: LLVM: Loaded module v6-kusa-CTHcTJukYxsVZ3E1bSQvWZ-00001G-znver3.obj
S PPU: LLVM: Loaded module v6-kusa-fe460PjEnhpQZ6syRFZSZ7-00001G-znver3.obj
S PPU: LLVM: Loaded module v6-kusa-ot5YAQtYzKJLXEuAzEjLja-00001G-znver3.obj
S PPU: LLVM: Loaded module v6-kusa-K6i9jVQV7VC8v9iR1cZoQv-00001G-znver3.obj
S PPU: LLVM: Loaded module v6-kusa-F8AUfz4tNYsQAWM4cfg8gj-00001G-znver3.obj
S PPU: LLVM: Loaded module v6-kusa-ehenMZR4janH1TPsHpX1ye-00001G-znver3.obj
S PPU: LLVM: Loaded module v6-kusa-XagaFwHxa9Cai7SFUfhKeu-00001G-znver3.obj
S PPU: LLVM: Loaded module v6-kusa-G8q7wxqgKgniF9kkXvaMic-00001G-znver3.obj
S PPU: LLVM: Loaded module v6-kusa-iQfhHqYGrCwC6YgdN6n61r-00001G-znver3.obj
S PPU: LLVM: Loaded module v6-kusa-0WmS6qEZiPLgwfccpWqrjx-00001G-znver3.obj
S PPU: LLVM: Loaded module v6-kusa-p4EEZE8Nc90MyEeCcti5Mx-00001G-znver3.obj
S PPU: LLVM: Loaded module v6-kusa-kjNAixMaRdyXxJKYSvKjpp-00001G-znver3.obj
S PPU: LLVM: Loaded module v6-kusa-JyE4UkUEGb1XqUxmL9ikr0-00001G-znver3.obj
S PPU: LLVM: Loaded module v6-kusa-4F9dzxyqP5x79HG3pGt8w6-00001G-znver3.obj
S PPU: LLVM: Loaded module v6-kusa-cC95KwS8zFaFeJ1FE8prco-00001G-znver3.obj
S PPU: LLVM: Loaded module v6-kusa-r4fkhaj46rAp01CmkjLihP-00001G-znver3.obj
S PPU: LLVM: Loaded module v6-kusa-6o5hUPKbvU2f9mwwexgZMd-00001G-znver3.obj
S PPU: LLVM: Loaded module v6-kusa-GMdqkAj9NRZUu9iZC1yNQU-00001G-znver3.obj
S PPU: LLVM: Loaded module v6-kusa-2vyZenKTuPRR7mkcHmpAKv-00001G-znver3.obj
S PPU: LLVM: Loaded module v6-kusa-EyLmqpPr0c8pay0aPgb3eF-00001G-znver3.obj
S PPU: LLVM: Loaded module v6-kusa-eSkgqbwTxVRFfCj9vcC6oH-00001G-znver3.obj
S PPU: LLVM: Loaded module v6-kusa-Agqsm79vvKcGJM747bpyai-00001G-znver3.obj
S PPU: LLVM: Loaded module v6-kusa-tfr327A95QAUKC28jSGwQe-00001G-znver3.obj
S PPU: LLVM: Loaded module v6-kusa-hozRb1xg7W5Cc1XQ9tMYG8-00001G-znver3.obj
S PPU: LLVM: Loaded module v6-kusa-tYbagLtHVCxQutt4R4URU2-00001G-znver3.obj
S PPU: LLVM: Loaded module v6-kusa-HNTTNPQgNoFMTEfbSjmqjY-00001G-znver3.obj
S PPU: LLVM: Loaded module v6-kusa-gNynu5h0UMKm8ytT5Ypa6y-00001G-znver3.obj
S PPU: LLVM: Loaded module v6-kusa-78hfrejU1gL35S1aX54dJf-00001G-znver3.obj
S PPU: LLVM: Loaded module v6-kusa-13L7AtQNLoyJrg2rZaHJaJ-00001G-znver3.obj
S PPU: LLVM: Loaded module v6-kusa-dCR3tLhmKW7tTcpCYZVijN-00001G-znver3.obj
S PPU: LLVM: Loaded module v6-kusa-a4Une4uL3J0XE6oPXrnxqY-00001G-znver3.obj
S PPU: LLVM: Loaded module v6-kusa-6Ko3XWXPCKmHoESxVk23tw-00001G-znver3.obj
S PPU: LLVM: Loaded module v6-kusa-frpwabza7Eo8Ki11u08dg8-00001G-znver3.obj
S PPU: LLVM: Loaded module v6-kusa-5MmjPh55m4YXzVZF8ifJWc-00001G-znver3.obj
S PPU: LLVM: Loaded module v6-kusa-b01wXZFgQRr0SPhEdyKRUS-00001G-znver3.obj
S PPU: LLVM: Loaded module v6-kusa-RxrAQC8AURvq50n62rEMUK-00001G-znver3.obj
S PPU: LLVM: Loaded module v6-kusa-FchUHG3092gJmqhCySZFmA-00001G-znver3.obj
S PPU: LLVM: Loaded module v6-kusa-qLee0uqd8tFhw6ohZwgeiQ-00001G-znver3.obj
S PPU: LLVM: Loaded module v6-kusa-fAbMYEKoA3XeKZjf8xTqYG-00001G-znver3.obj
S PPU: LLVM: Loaded module v6-kusa-Y4GgNE7yowfmKHR7qjktaA-00001G-znver3.obj
S PPU: LLVM: Loaded module v6-kusa-m3F7coRw3VN3zdS0LCZEYJ-00001G-znver3.obj
S PPU: LLVM: Loaded module v6-kusa-ohXPfnZwg4peCKK1PcA7L0-00001G-znver3.obj
S PPU: LLVM: Loaded module v6-kusa-etZieUcjxLg7F7pShH6bCL-00001G-znver3.obj
S PPU: LLVM: Loaded module v6-kusa-CJzkJoxVS3RHRUxL22Eu5x-00001G-znver3.obj
S PPU: LLVM: Loaded module v6-kusa-byakiwbSaubZwVFT3pbEsU-00001G-znver3.obj
S PPU: LLVM: Loaded module v6-kusa-mm5nAicyqKh22jdw6TS0sp-00001G-znver3.obj
S PPU: LLVM: Loaded module v6-kusa-K4WVLaoU6Mynnb0umpb4Nc-00001G-znver3.obj
S PPU: LLVM: Loaded module v6-kusa-F9QVp690NSZXToFLCELK1i-00001G-znver3.obj
S PPU: LLVM: Loaded module v6-kusa-3W28xYcuQJEVFvNQ1QJQ5u-00001G-znver3.obj
S PPU: LLVM: Loaded module v6-kusa-dgbGctoQwqUMpSmRJe3iQA-00001G-znver3.obj
S PPU: LLVM: Loaded module v6-kusa-imJMmCpxumsVJXq1CH3rXh-00001G-znver3.obj
S PPU: LLVM: Loaded module v6-kusa-W6JhYSse3i77cgqdueM8wq-00001G-znver3.obj
S PPU: LLVM: Loaded module v6-kusa-3eQ1ujSMP25PhPa13ssryk-00001G-znver3.obj
S PPU: LLVM: Loaded module v6-kusa-PYLTp55MTeUHgxjN2QMaj0-00001G-znver3.obj
S PPU: LLVM: Loaded module v6-kusa-R7Ymmg2EbLMNWJA6PA8pbg-00001G-znver3.obj
S PPU: LLVM: Loaded module v6-kusa-R1NMu92sZr7o94ASwFY1U3-00001G-znver3.obj
S PPU: LLVM: Loaded module v6-kusa-HfmXFbdNfb2WnL7CiGiKqE-00001G-znver3.obj
S PPU: LLVM: Loaded module v6-kusa-EtJHAtHWqJj1zxwZjni8dt-00001G-znver3.obj
S PPU: LLVM: Loaded module v6-kusa-Ka7wpsivcM2grmeiN8Jpfh-00001G-znver3.obj
S PPU: LLVM: Loaded module v6-kusa-LvfgUoW3m2TCJbq8128aX0-00001G-znver3.obj
S PPU: LLVM: Loaded module v6-kusa-Mcen3RJimGssmHxfXYG59o-00001G-znver3.obj
S PPU: LLVM: Loaded module v6-kusa-fNcyAhTg9un7wmNseV6vxv-00001G-znver3.obj
S PPU: LLVM: Loaded module v6-kusa-3VaSi19itLfCVneCmH8t2R-00001G-znver3.obj
S PPU: LLVM: Loaded module v6-kusa-M3hpTiWb2M6ECG64xfaYJH-00001G-znver3.obj
S PPU: LLVM: Loaded module v6-kusa-3JjRWtti5NKKsM8poqTEf7-00001G-znver3.obj
S PPU: LLVM: Loaded module v6-kusa-3P8dzY6Pz7a0g3pT4vZnCx-00001G-znver3.obj
S PPU: LLVM: Loaded module v6-kusa-tV7aujgiGMn2wLrFPApp9v-00001G-znver3.obj
S PPU: LLVM: Loaded module v6-kusa-gcgxFuJbm05eUs4PhTWfUq-00001G-znver3.obj
S PPU: LLVM: Loaded module v6-kusa-SfEepykwy0dMjjFKkqk707-00001G-znver3.obj
S PPU: LLVM: Loaded module v6-kusa-2SN1eJygPM4eS4jcxGYqVe-00001G-znver3.obj
S PPU: LLVM: Loaded module v6-kusa-P3SMvc5Z8d2Wattrmk69Ze-00001G-znver3.obj
S PPU: LLVM: Loaded module v6-kusa-Xu3YALk8Z3MhN9ie5V4WY9-00001G-znver3.obj
S PPU: LLVM: Loaded module v6-kusa-LoPiGAn1nHhS4bZ3fGzhA5-00001G-znver3.obj
S PPU: LLVM: Loaded module v6-kusa-hWfot7obEPMVTWoJtEQaht-00001G-znver3.obj
S PPU: LLVM: Loaded module v6-kusa-qrFnt7L4UF6Kj30gkh1T8n-00001G-znver3.obj
S PPU: LLVM: Loaded module v6-kusa-3iojKqvLUf4Vaabscd5Wtm-00001G-znver3.obj
S PPU: LLVM: Loaded module v6-kusa-m5cMY9fmzZvXTZFQdnVL0R-00001G-znver3.obj
S PPU: LLVM: Loaded module v6-kusa-3kHLzsNJgLLktA6kQsgNES-00001G-znver3.obj
S PPU: LLVM: Loaded module v6-kusa-5U4U4et1JQ9bfEUJu79ALg-00001G-znver3.obj
S PPU: LLVM: Loaded module v6-kusa-eK3Xm6ZGfbZmpP0aWfb3pH-00001G-znver3.obj
S PPU: LLVM: Loaded module v6-kusa-EKVuXJneyQnq6hYhtabYvm-00001G-znver3.obj
S PPU: LLVM: Loaded module v6-kusa-0za8FmyJrwmgNJGdXj6cXZ-00001G-znver3.obj
S PPU: LLVM: Loaded module v6-kusa-Q6bY8i27CK29az9ZLRr2x1-00001G-znver3.obj
S PPU: LLVM: Loaded module v6-kusa-V79w7vyGPydG96CdiqQbMa-00001G-znver3.obj
S PPU: LLVM: Loaded module v6-kusa-SZEwXAY2PbYm3zFTC2f1hz-00001G-znver3.obj
S PPU: LLVM: Loaded module v6-kusa-YNQ6XH07VwapTqsvZ55Aq2-00001G-znver3.obj
S PPU: LLVM: Loaded module v6-kusa-Rm8zw1raCLaE07NGKv3RYN-00001G-znver3.obj
S PPU: LLVM: Loaded module v6-kusa-oaNVvZAGhWmiX13a1LFir8-00001G-znver3.obj
S PPU: LLVM: Loaded module v6-kusa-b24iN2ti98SH3JdrzPWXmo-00001G-znver3.obj
S PPU: LLVM: Loaded module v6-kusa-4i8yXM9jFGUgRiZ3xFoJug-00001G-znver3.obj
S PPU: LLVM: Loaded module v6-kusa-YauXg5MwKFG3vvWEGXx4Nq-00001G-znver3.obj
S PPU: LLVM: Loaded module v6-kusa-iv5nAqEGtdH2zYeSULeTqM-00001G-znver3.obj
S PPU: LLVM: Loaded module v6-kusa-1b27ktirqgwQc80E98hiYP-00001G-znver3.obj
S PPU: LLVM: Loaded module v6-kusa-VMcz0RCqZVkkW8ncxHCvNh-00001G-znver3.obj
S PPU: LLVM: Loaded module v6-kusa-JzeWEng62G75JsXVYp00mG-00001G-znver3.obj
S SPU: SPU Runtime: Built the interpreter.
S SPU: SPU Runtime: Built 1011 functions.
U sys_prx TODO: _sys_prx_register_module(name=“cellProcessElf”, opt=*0xd0020ce0)
S PPU: LLVM: Loaded module v6-kusa-1z3Pyu8YVnnorJiQ2hfu1e-00001G-znver3.obj
S sys_prx: Loaded module: “/dev_flash/sys/external/libsysmodule.sprx” (id=0x23000b00)
U sys_ss TODO: sys_ss_access_control_engine(pkg_id=0x1, a2=0x1, a3=0xd0020a50)
E SYS: 'sys_ss_access_control_engine' failed with 0x80010003 : CELL_ENOSYS [1]
U sys_ss TODO: sys_ss_access_control_engine(pkg_id=0x2, a2=0xd0020a50, a3=0x0)
S PPU: LLVM: Loaded module v6-kusa-XCgQWMc1s99n1WTwrpWvw4-00001G-znver3.obj
S sys_prx: Loaded module: “/dev_flash/sys/external/libgcm_sys.sprx” (id=0x23000e00)
S PPU: LLVM: Loaded module v6-kusa-1Au1tg93M0j9aPxhbpVJAC-00001G-znver3.obj
S PPU: LLVM: Loaded module v6-kusa-5MR5UPWcNoRKHsUNJqHbKV-00001G-znver3.obj
S sys_prx: Loaded module: “/dev_flash/sys/external/libsre.sprx” (id=0x23001100)
S PPU: LLVM: Loaded module v6-kusa-fLV79QqHgPi90UziTsWrHo-00001G-znver3.obj
S sys_prx: Loaded module: “/dev_flash/sys/external/libfs.sprx” (id=0x23001200)
U sys_prx TODO: _sys_prx_register_module(name=“_sysProcessElf”, opt=*0xd0020df0)
S PPU: LLVM: Loaded module v6-kusa-0YGzaLrMF50X8yE9c59dd2-00001G-znver3.obj
S sys_prx: Loaded module: “/dev_flash/sys/external/libfiber.sprx” (id=0x23005b00)
S PPU: LLVM: Loaded module v6-kusa-ZAhea3FFhakpfMa36ZvaNx-00001G-znver3.obj
S sys_prx: Loaded module: “/dev_flash/sys/external/librtc.sprx” (id=0x23005d00)
S PPU: LLVM: Loaded module v6-kusa-fNAFCrZ8xY5ftqnyUQLfTd-00001G-znver3.obj
S sys_prx: Loaded module: “/dev_flash/sys/external/libspurs_jq.sprx” (id=0x23005e00)
S PPU: LLVM: Loaded module v6-kusa-UnNP3fZh95wiCGy3Q0csRy-00001G-znver3.obj
S sys_prx: Loaded module: “/dev_flash/sys/external/libresc.sprx” (id=0x23006600)
U sys_prx TODO: _sys_prx_get_module_id_by_name(name=“cellLibprof”, flags=0, pOpt=*0x0)
S PPU: LLVM: Loaded module v6-kusa-awyXAjiP42JiuKipkxEuiy-00001G-znver3.obj
S sys_prx: Loaded module: “/dev_bdvd/PS3_GAME/USRDIR/sprx/Izumo.sprx” (id=0x23009200)
S PPU: LLVM: Loaded module v6-kusa-dGnoKU2EaRSbtxn1sWyMZi-00001G-znver3.obj
S sys_prx: Loaded module: “/dev_bdvd/PS3_GAME/USRDIR/sprx/AnimationJobs.sprx” (id=0x23009300)
S PPU: LLVM: Loaded module v6-kusa-toPHdiXXCc5rVG7augTLF9-00001G-znver3.obj
S sys_prx: Loaded module: “/dev_bdvd/PS3_GAME/USRDIR/sprx/ArticulatedDynamicsJobs.sprx” (id=0x23009400)
S PPU: LLVM: Loaded module v6-kusa-SHz7mCWh7mpXaxEH2mZ9U6-00001G-znver3.obj
S sys_prx: Loaded module: “/dev_bdvd/PS3_GAME/USRDIR/sprx/CollisionJobs.sprx” (id=0x23009500)
S PPU: LLVM: Loaded module v6-kusa-cT8WFfv3KZZprWNptorP9R-00001G-znver3.obj
S sys_prx: Loaded module: “/dev_bdvd/PS3_GAME/USRDIR/sprx/HeightObjectJobs.sprx” (id=0x23009600)
S PPU: LLVM: Loaded module v6-kusa-dzbZSem9mMwogfrmS3QSir-00001G-znver3.obj
S sys_prx: Loaded module: “/dev_bdvd/PS3_GAME/USRDIR/sprx/Yakumo.sprx” (id=0x23009700)
S PPU: LLVM: Loaded module v6-kusa-XrL6uToK0me18wg88ncUnG-00001G-znver3.obj
S sys_prx: Loaded module: “/dev_bdvd/PS3_GAME/USRDIR/sprx/YakumoTaskGroup.sprx” (id=0x23009800)
E SYS: 'sys_ppu_thread_join' failed with 0x80010005 : CELL_ESRCH [1]
E sys_fs: 'sys_fs_stat' failed with 0x80010006 : CELL_ENOENT, “/dev_bdvd/PS3_GAME/USRDIR/HostMachine.txt” [1]
E SYS: 'cellSysutilDisableBgmPlaybackEx' failed with 0x8002d301 : CELL_SYSUTIL_BGMPLAYBACK_EX_ERROR_PARAM [1]
S SPU: New block compiled successfully
F {PPU[0x1000000] Thread (main_thread) [0x0051409c]} VM: Access violation reading location 0xdadfe97 (unmapped memory)

### Other details

this game in the moment work for intel cpus

https://www.youtube.com/watch?v=gImFJ_BHzG0

**Comment by YuriNator557** [comment] 2023-07-25 22:06
The log shown here is just some irrelevant stuff copied from the GUI, we need the file that is generated by RPCS3 upon closure
Try following this, upload to here instead of Discord of course
![image](https://github.com/RPCS3/rpcs3/assets/76178650/b0252d01-999b-4dc4-b3a3-19cf73a357ef)

**Comment by DenisNinja** [comment] 2023-07-25 22:16
ok

**Comment by DenisNinja** [comment] 2023-07-25 22:26
please delete this post i have did what you ask on the discord

**Comment by DenisNinja** [comment] 2023-07-25 22:26
delete the entire post

**Comment by AniLeo** [comment] 2023-11-11 23:37
No log file so it's an invalid issue as is but regardless it's a duplicate of #6825

**Closed by AniLeo** 2023-11-11 23:37 UTC
