### ISSUE TITLE
Virtua Fighter 5 Final Showdown [NPUB30625] - Afterimages

### ISSUE THREAD

**Issue by scju** [RPCS3/rpcs3#13508] opened 2023-03-06 14:27 UTC
### Quick summary

Characters in this game have "afterimages" like this:

![2023-03-06_220416](https://user-images.githubusercontent.com/31085634/223133222-bb3e428c-fad6-479a-86e7-a67cfdb5e7c5.jpg)

I can feel that they don't move very "smoothly" because of this issue. 
I'm not sure if the game was originally like this on PS3.
However, Virtua Fighter 5 (BLES00029) doesn't seem to have this issue.

### Attach a log file

[RPCS3.log](https://github.com/RPCS3/rpcs3/files/10899091/RPCS3.log)
[NPUB30625_capture.zip](https://github.com/RPCS3/rpcs3/files/10899156/NPUB30625_capture.zip)

**Comment by Megamouse** [comment] 2023-03-06 17:40
That just looks like regular motion blur...

**Comment by RipleyTom** [comment] 2023-03-18 16:35
Quick google suggest that indeed they added motion blur for the Final Showdown version.
https://www.eurogamer.net/digitalfoundry-vf5-final-showdown-face-off mentions it.
Quick google of videos of the game on ps3 shows the same thing clearly visible when pausing.
Closing as not a bug.

**Closed by RipleyTom** 2023-03-18 16:35 UTC
Labels: Meta: Invalid
