### ISSUE TITLE
Motorstorm and Motorstorm: Pacific Rift performance regression on RTX after v0.0.7.8143

### ISSUE THREAD

**Issue by l0wd0ct0r** [RPCS3/rpcs3#7078] opened 2019-12-08 11:02 UTC
Recently upgraded from GTX1070 to RTX 2080Ti and have noticed that performance on Motorstorm and Motorstorm: Pacific Rift is greatly reduced, especially when the game is rendering other vehicles, dropping to 2FPS (4K) at the starting grid for example. This did not seem to affect the GTX1070 in the latest builds, but the switch to RTX definitely caused a big drop in performance. I previously used v0.0.7.8143 with Pacific Rift prior to the latest builds due to the loading freeze issue that was recently fixed. On running this version with the RTX performance is once again a mainly solid 30FPS (4K). I'm not sure what version the regression happened at as I've only very recently upgraded to the RTX card.

i7 9700K
32GB LPX3600
MSI Ventus GP 11GB RTX 2080Ti 
Aorus Master Z390

First screenshot is from the latest build v0.0.7.9212, second from the older v0.0.7.8143. It seems that the CPU cores aren't being used as much in the latest build? Definitely only seen this issue since the GPU upgrade however.

<img width="960" alt="v0 0 7 9212_MSPR" src="https://user-images.githubusercontent.com/26875307/70388630-51765400-19ac-11ea-88a1-9e1991149d5e.png">
<img width="960" alt="v0 0 7 8143_MSPR" src="https://user-images.githubusercontent.com/26875307/70388633-56d39e80-19ac-11ea-8fbe-47b5302041f8.png">

[RPCS3.log](https://github.com/RPCS3/rpcs3/files/3936152/RPCS3.log)

**Comment by kd-11** [comment] 2020-01-15 18:39
Retest with a clean driver and emulator installation.

**Comment by jeremybris** [comment] 2020-03-07 17:03
@kd-11 

I think I found the regression. It’s build 0.0.6-8253, PR #6055. Still happens.

The performance regression and the regression preventing the Motorstorm games from going in game appear to be the same, giant regression. When someone fixed the regression, they only half fixed it. No one noticed the performance regression because they could not go in game for that entire time.

I believe they are the same and not different regressions for the following, two reasons:

1. **All three Motorstorm games are effected equally** in the same way, **_a performance regression and a crash regression_**, and only these games. No other game reported a performance loss in this way. I found three other games, #7133, #7007, #4700, that have reported a performance regression, but they did not experience a crash regression at the same time.
2. I reliably reproduced the performance regression **_and_** the crash regression at the same time. On **build 0.0.6-8253**, in Motorstorm 1, when going straight and colliding into another car, **the game crashes** . **On build 0.0.7-8790 and after**", in Motorstorm 1, when going straight and colliding into another car", **you experience the performance regression**. See the steps below to reproduce.

**Build 0.0.6-8253, PR #6055** - The crash regression
**Build 0.0.7-8770 - 0.0.7-8790, Probably PR #6644** - The half fix is somewhere in between. It's probably #6644, since it mentions Turing cards.

To reproduce:

1. Have settings on Vulkan, 4K
2. Open Motorstorm [BCES00006]
3. Choose English>Play>2nd Ticket (Plain Dirty)>2nd Event (The Squall)>First Car (Springbok)
4. In-game, full gas (full R2), go straight (don't touch anything else), crash into another AI car

**Comment by kd-11** [comment] 2020-03-07 18:20
I'm pretty sure this is the MSAA nvidia problem where nvidia refuses to support extensions we need. Not sure why you didn't get this on 1070ti though.
I'm guessing changing MSAA from Auto to Disabled in GPU settings fixes it?

**Comment by jeremybris** [comment] 2020-03-07 18:32
> I'm pretty sure this is the MSAA nvidia problem where nvidia refuses to support extensions we need. Not sure why you didn't get this on 1070ti though.
> I'm guessing changing MSAA from Auto to Disabled in GPU settings fixes it?

Changing MSAA from Auto to Disabled in GPU _does not_ fix the issue :(. 

I also can not confirm if this is a Turing card issue only, because I only own a Turing card to test (RTX 2080). Is anyone with a Nvidia GTX or AMD Radeon GPU able to reproduce this issue? @web1018?

**Comment by kd-11** [comment] 2020-03-07 19:24
So its not an issue at lower resolution?

**Comment by jeremybris** [comment] 2020-03-07 20:03
Actually, after testing, changing Anti-Aliasing from **_off_** to **_auto_** fixes the issue for me. So, you are probably right.

> So its not an issue at lower resolution?

I think so.

**Comment by Asinin3** [comment] 2020-09-18 04:42
Retest, is it still an issue on turing with msaa?

**Comment by jeremybris** [comment] 2020-09-18 18:20
> Retest, is it still an issue on turing with msaa?

Yes, and there is still a [workaround](https://github.com/RPCS3/rpcs3/issues/7078#issuecomment-596132572).

**Comment by kd-11** [comment] 2022-03-17 00:00
I think this issue should be closed. I cannot reproduce the issue mentioned by the OP.
Note that:
1. RPCS3 is heavy at 4K, that's normal. What's not normal is running at 2fps on a 2080Ti
2. A lot has changed since this was reported.
3. In the worst case, with emulated MSAA, nvidia performs worse due to technical limitations with their hardware.

I cannot reproduce the issue on my 6700XT. Here's a 4K internal res render
![image](https://user-images.githubusercontent.com/15904127/158710725-cf4e5f7e-28f9-4c9f-8e2c-d4007507dcd7.png)

I don't have a modern NVIDIA gpu to compare to unfortunately, but this is a far cry from the sub 5fps reported in 2019.

**Comment by JimScript** [comment] 2022-03-17 00:34
I can reproduce this problem at 4k on my RTX 2070 super, but only when unpaused.
Paused, at 50% gpu usage:
![FPS_ 30 21 _ Vulkan _ 0 0 21-local_bu-local_build _ MotorStorm™  BCUS98137  3_16_2022 5_28_20 PM](https://user-images.githubusercontent.com/66685584/158713274-128c8770-63bc-45a4-9b69-bf79b7650a19.png)
Unpaused, at 95% gpu usage:
![FPS_ 16 23 _ Vulkan _ 0 0 21-local_bu-local_build _ MotorStorm™  BCUS98137  3_16_2022 5_28_53 PM](https://user-images.githubusercontent.com/66685584/158713367-9ea4161a-e695-4d1d-8eea-f36e4e627f26.png)

Something is happening during gameplay that is causing RTX gpus to slowdown immensely.

**Comment by l0wd0ct0r** [comment] 2022-03-17 20:42
I'm pretty sure this issue is now completely resolved, for Motorstorm Pacific Rift at least. I've not been able to recreate the issue of extreme performance drop in the latest releases.

**Comment by JimScript** [comment] 2022-03-17 23:11
Is there anyway to disable motion blur to check if it is that? Because on my RTX 2070 super running driver 511.23.0.0, whenever motion blur happens the performance just tanks, and exponentially with the resolution. After a while it will slow to a crawl and crash saying: "SIG: Thread terminated due to fatal error: Assertion Failed! Vulkan API call failed with unrecoverable error: Out of video memory (VRAM) (VK_ERROR_OUT_OF_DEVICE_MEMORY)" So to me it seems like motion blur is just eating video memory, but I don't know why other gpus aren't affected.

Log:
[RPCS3.log](https://github.com/RPCS3/rpcs3/files/8294285/RPCS3.log)

**Comment by jeremybris** [comment] 2022-03-18 00:17
There's a patch to disable Motion Blur. If not for Motorstorm, the other Motorstorm games.

**Comment by Xcedf** [comment] 2022-04-24 19:41
Is this still an issue?, after new msaa optimizations, motorstorm runs fine with msaa enabled, don't have pacific rift to confirm.

**Comment by JimScript** [comment] 2022-04-24 20:08
To me, motorstorm still explodes with gpu usage when I unpause, and it gets exponentially worse the higher the resolution scale goes. The thing is setting the threshold to 1024 doesn't seem to stop the bloating. At 200% resolution with the 60fps patch, I get sub 30fps on my RTX 2070 Super, but when I pause the game It shoots back up to 60fps with half the gpu usage. Which is weird because it doesn't pause the rendering as you can rotate the camera, but the slowdown happens at the starting countdown so it's not the mud tracks. Disabling motion blur doesn't change anything either, so I have no idea what changes from paused to unpaused, and why it only affects RTX gpus. By the way I use MSI afterburner to measure gpu usage.

**Comment by JimScript** [comment] 2022-04-25 12:46
Here are two videos of the same 4k 60fps session on different tracks. See how much the mud shader changes performance.

On a dry track:

https://user-images.githubusercontent.com/66685584/165090438-51cc0d73-2ad5-4eb7-99e8-68fd43a22fc0.mp4

On a muddy track:

https://user-images.githubusercontent.com/66685584/165090591-26ca98ea-4157-4da4-9edd-d9147a7a0d2b.mp4

**Comment by Asinin3** [comment] 2022-04-25 13:10
Please keep the comments here solely about the performance regression from the build you mentioned. Losing performance on one track vs another or losing performance from resolution scaling is unrelated.

**Comment by JimScript** [comment] 2022-04-25 22:46
I am sorry for getting off track, but I guess my first video shows that RTX gpus aren't a problem for this game anymore.

**Comment by Asinin3** [comment] 2023-01-14 00:54
@JimScript Please record the RPCS3 gamewindow so we can see build numbers. And test this on latest master with pausing and unpausing when on the mud track with the issue. Show latest master, the build that the issue first started happening in, and the build directly before it started happening.

The other videos and posts aren't serving as a good example of this issue.

**Comment by JimScript** [comment] 2023-01-14 01:50
> @JimScript Please record the RPCS3 gamewindow so we can see build numbers. And test this on latest master with pausing and unpausing when on the mud track with the issue. Show latest master, the build that the issue first started happening in, and the build directly before it started happening.
> 
> The other videos and posts aren't serving as a good example of this issue.

I actually made another issue for that with more research put in right here #11898.

**Comment by Darkhost1999** [comment] 2023-06-14 00:11
> I actually made another issue for that with more research put in right here #11898.

Since this issue was migrated, this issue can be closed right in favor of the newer/cleaner one?

**Comment by Megamouse** [comment] 2023-09-05 23:55
I'll close this issue since there are multiple reports that claim it is not an issue and another issue exists for the track specific slowdowns.

**Closed by Megamouse** 2023-09-05 23:55 UTC
Labels: Need Information
