### ISSUE TITLE
Poor SPU performance after MFC thread removal

### ISSUE THREAD

**Issue by bothlefthands** [RPCS3/rpcs3#4376] opened 2018-04-02 10:24 UTC
ver.6607 is working fine with 27-30 PFS, on 6611-6630 fps drops down to 4-7
 after intro, when "press any button screen is displayed.
Part of intro, when Morgana is running is not dispaying/miising
Win10_64x
AMD Ryzen 5 1600X Six-Core Processor  | 12 Threads | 15.95 GiB RAM | AVX+
Nvidia 1060 6GB
[RPCS3.log.gz](https://github.com/RPCS3/rpcs3/files/1867855/RPCS3.log.gz)

**Comment by Asinin3** [comment] 2018-04-02 14:57
Your log is completely empty, need to run the game first then close RPCS3, or it might be int he old_logs folder with a correct run of the game.

**Comment by AniLeo** [comment] 2018-04-02 15:14
![](https://cdn.discordapp.com/attachments/345204501831221249/430382611396034580/unknown.png)

Not an issue for me

**Comment by hcorion** [comment] 2018-04-02 18:26
Seems to be an issue with ryzen, then?
Has anybody tried on linux.

**Comment by greentop** [comment] 2018-04-03 00:04
i7 3770
Nvidia 730
Ubuntu 16.04
-24 FPS at the press any button screen. (Expected frame rate)
-All of the "press any button" intro screen rendering is present.

**Comment by al0xf** [comment] 2018-04-03 07:10
I had this game running at 3 fps once. I think I had forgot write color buffers on, or was it some other setting? Either way, try clearing everything, all settings, cache, etc. 

For me, on an i7-7820HQ, it runs as good as ever.

**Comment by SpinningSlash** [comment] 2018-04-03 17:03
Here, now its readable.
It seems that issue is showing on Ryzen only
[RPCS3.log.gz](https://github.com/RPCS3/rpcs3/files/1872513/RPCS3.log.gz)

**Comment by Asinin3** [comment] 2018-04-05 04:03
Badly affects skate 3 as well, some users with slower CPU's used to report that the game ran in "slow motion" even at 60fps but I never experienced it until this PR was merged.

**Comment by xfutaba** [comment] 2018-04-05 14:30
Having this issue too on intel, Persona 5 starts out at 60fps (w/ patch) but then as it gets to the title screen drops to 7-10 fps. Running an i7 5930k and GTX 1080ti w/ Vulkan renderer.
<img width="1920" alt="p5 latest master" src="https://user-images.githubusercontent.com/38107305/38372195-db761982-38b3-11e8-923c-da979e6822fe.PNG">

**Comment by Asinin3** [comment] 2018-04-05 16:15
Seems like Persona 5 just hates SPU Preferred threads = 2 now, with it set to 1 my performance is back to normal
![image](https://user-images.githubusercontent.com/15137035/38378232-8b2ea834-38ec-11e8-9cdf-cf5791acb378.png)

**Comment by Hirato** [comment] 2018-04-05 16:58
I'm on Linux with Ryzen, can't say I've noticed any performance issues.
Well, there is the bizarre fact that I seem to get about 50% higher FPS and much faster shader compile times with OpenGL than Vulkan, when I'd expect the exact opposite to be the case, but I digress.

I get a fairly consistent 40+ FPS  in the main menu, and it's still quite respectable in game (I'm also using the 60 FPS patch).

![image](https://user-images.githubusercontent.com/881518/38379161-75d34d8c-3932-11e8-8678-e58cf1e9d880.png)
![image](https://user-images.githubusercontent.com/881518/38379254-b7893458-3932-11e8-971b-04bc4b9f8456.png)

As for the Preferred SPU threads thing @Asinin3 mentioned, I've kept it at 6; at 2 I see a small hit of about 3 FPS on most scenes (ie 43 -> 41; 29 -> 26, etc.)

**Comment by al0xf** [comment] 2018-04-05 17:03
@Hirato Don't post _massive_ spoilers like that, edit/remove those images.

**Comment by AniLeo** [comment] 2018-04-05 17:05
I've removed the images.

**Comment by kd-11** [comment] 2018-04-05 17:52
Confirmed, ryzen on linux is actually faster after MFC thread removal. This would mean the new spu code needs the scheduler to be reworked and makes it a windows only issue.
Before MFC removal menu = ~33fps, after ~41fps
Before (in an unspecified saveroom) = ~35fps, after ~38-48fps depending on camera angle
Before (unspecified location) = ~20-27fps, after ~24-36fps
There is a significant boost on linux after MFC thread removal from testing, pointing to a windows issue.
The ryzen thread scheduler requires reworking after the changes it seems

**Comment by kd-11** [comment] 2018-04-07 11:57
This issue is fixed for ryzen. Current master has a clean 10+ fps bump over older builds with 2 (or even 3 on R7) SPU threads. 1 thread is now slower than using 2 or 3, but using 4-6 adds alot of stutter making 2 or 3 the sweet spot.

**Comment by Zangetsu38** [comment] 2018-04-07 11:58
yes, i have forget signled here sorry, on last master, regression for perfomence is totaly feezed, and have also get little more speed

**Comment by AniLeo** [comment] 2018-04-07 12:07
FX8350 has huge performance difference from 1 Thread to 2 or even auto

**Comment by kd-11** [comment] 2018-04-07 12:28
Renamed in case another cpu class is still affected. @AniLeo Whats the FX performance like?

**Comment by AniLeo** [comment] 2018-04-07 12:33
Persona 5 at Title Screen
Auto: 7 FPS
SPU 1: 18-19FPS

**Comment by Illynir** [comment] 2018-04-07 12:56
on i5 4670K, i lost 3 to 5 FPS on all games after MFC Thread removal.

**Comment by Asinin3** [comment] 2018-04-09 04:46
Skate 3 slow motion issue is gone for me (note: may still happen on a slow CPU, but that isn't a regression).
Persona performance is back to normal as well i think this issue can be closed.

**Comment by SpinningSlash** [comment] 2018-04-09 05:29
Everything is fine for me as well

**Comment by Asinin3** [comment] 2018-04-09 05:31
Then hit the close issue button at the bottom?

**Comment by SpinningSlash** [comment] 2018-04-09 05:37
Wow, it does have such function

**Closed as completed** 2018-04-09 05:38 UTC
Labels: Regression, OS: Windows
