### ISSUE TITLE
Unknown STOP code: 0x3fff (Out_MBox is empty)

### ISSUE THREAD

**Issue by d-jahren** [RPCS3/rpcs3#4527] opened 2018-05-07 03:15 UTC
```
{SPU[0x2000000] Thread (Job Manager - Job Thread) [0x032d4]} MEM: Access violation writing location 0x2a300000
{SPU[0x2000003] Thread (Job Manager - Job Thread) [0x032d4]} MEM: Access violation writing location 0x2a300300
{SPU[0x2000002] Thread (Job Manager - Job Thread) [0x014e0]} MEM: Access violation writing location 0x2a302700
{SPU[0x2000001] Thread (Job Manager - Job Thread) [0x032d4]} MEM: Access violation writing location 0x2a3062b0
{SPU[0x2000004] Thread (Job Manager - Job Thread) [0x026f8]} class std::runtime_error thrown: Unknown STOP code: 0x3fff (Out_MBox is empty)
(in file Emu\Cell\SPUThread.cpp:2317)
```

System info: i7 4790, RX 480 8GB. Game error occurred in: Need For Speed: ProStreet

[RPCS3.log](https://github.com/RPCS3/rpcs3/files/1978418/RPCS3.log)

**Comment by elad335** [comment] 2018-05-07 05:28
duplicate of #2452
in practice this error is very generic and can occur from any reason.
also, since both STOPD and STOP 0x3fff are essentially the same, might wanna comment it in issue #2420

**Comment by elad335** [comment] 2018-12-08 08:35
Not an issue on latest master, this game used to crash in loading screen with this error.
![unknown](https://user-images.githubusercontent.com/18193363/49683919-e104d080-fad4-11e8-867f-a0067a180ebf.png)

**Closed** 2018-12-09 23:00 UTC
