### ISSUE TITLE
[Regression] F1 Championship Edition (Missing audio)

### ISSUE THREAD

**Issue by KazBodnar** [RPCS3/rpcs3#15576] opened 2024-05-10 01:28 UTC
### Quick summary

No audio except for cutscenes. I disabled audio buffering and I set audio format to auto, but this hasn't worked.

### Build with regression

v0.0.32-16433-c02aae41

### Attach two log files

[RPCS3.log](https://github.com/RPCS3/rpcs3/files/15269278/RPCS3.log)
[RPCS3.log.gz](https://github.com/RPCS3/rpcs3/files/15269280/RPCS3.log.gz)

### System configuration

Windows 10, Intel i5-10600k, Nvidia RTX 3060

**Comment by RipleyTom** [comment] 2024-05-10 02:10
Duplicate of https://github.com/RPCS3/rpcs3/issues/12607

**Closed by RipleyTom** 2024-05-10 02:10 UTC

**Comment by KazBodnar** [comment] 2024-05-10 03:12
> Duplicate of #12607

not duplicate, tried the fix which didn't work

**Comment by RipleyTom** [comment] 2024-05-10 03:14
I tested just now, disabling buffering does fix it.
The logs you provided are empty so I can't confirm your settings.

**Comment by KazBodnar** [comment] 2024-05-10 03:25
> I tested just now, disabling buffering does fix it. The logs you provided are empty so I can't confirm your settings.

![image](https://github.com/RPCS3/rpcs3/assets/57724248/806c0010-b556-46fa-b406-223f67339ab5)

here are my audio settings. I know nothing about computer science so idk why the logs dont fill?

**Comment by KazBodnar** [comment] 2024-05-10 03:44
@RipleyTom 
Hopefully this should work
[RPCS3.log](https://github.com/RPCS3/rpcs3/files/15270098/RPCS3.log)

**Comment by RipleyTom** [comment] 2024-05-10 10:59
In your log:
```
Audio:
  Enable Buffering: true
```

You probably have a custom config for that game, you need to change the setting in the custom config.
If you require further help use our discord/forum.
