### ISSUE TITLE
《Dynasty Warriors 8 XL [BLAS50672]》the game still crashed

### ISSUE THREAD

**Issue by QJYEAH** [RPCS3/rpcs3#14541] opened 2023-08-23 13:47 UTC
### Quick summary

sometimes,this game still crashed.
![QQ图片20230823214301](https://github.com/RPCS3/rpcs3/assets/15781690/65cdc7eb-a86e-4b60-a675-8e8d8bb36f75)

### Attach a log file

[RPCS3.log](https://github.com/RPCS3/rpcs3/files/12419854/RPCS3.log)

### System configuration

CPU：R7 5800X
GPU：RTX 2080 8G
OS：Win10

**Comment by AniLeo** [comment] 2023-08-23 13:50
Duplicate of #9055

**Closed** 2023-08-23 13:50 UTC
