### ISSUE TITLE
Illegal instruction at 00007ff80f10162e (0x0f0b9090488d05153619004889052896). Thread: Main Thread. on MacOS Sonoma 14.1

### ISSUE THREAD

**Issue by hiakki** [RPCS3/rpcs3#14785] opened 2023-10-29 12:54 UTC
### Quick summary

Whenever I am exiting Game, RPCS3 crashes down with following error -
```
Illegal instruction at 00007ff80f10162e (0x0f0b9090488d05153619004889052896).
Thread: Main Thread.
```

### Details

RPCS3 Version - v0.0.29-15710-b7fe35a2 Alpha

### Attach a log file

[RPCS3.log](https://github.com/RPCS3/rpcs3/files/13198094/RPCS3.log)

### Attach capture files for visual issues

<img width="676" alt="image" src="https://github.com/RPCS3/rpcs3/assets/24492384/df4081cd-173f-4faf-8c33-77f63cca73ec">

### System configuration

MacOS - Sonoma 14.1
Chip - M1 Pro
Memory - 16 GB

**Comment by shinra-electric** [comment] 2023-11-05 09:12
Maybe related to your specific game, which is Tekken 5 Dark Resurrection NPEA00019 according to the log.

I can't reproduce with other games, I'm also on an M1 Pro.

**Comment by hiakki** [comment] 2023-11-05 09:19
@shinra-electric This issue also started right after Sonoma upgrade. Attaching logs with multiple other games, maybe that can help debugging this issue.
[RPCS3.log](https://github.com/RPCS3/rpcs3/files/13259107/RPCS3.log)

**Comment by ducthien1490** [comment] 2023-11-07 06:11
I have same problem after upgrading to Sonoma

**Comment by w-e-g** [comment] 2023-11-09 17:49
Nope. I tested this on many games. Same issues. And I seen this bug on Monterey too.

List of my games if you want:
Braid
Earthworm Jim HD
Raiden IV: Overkill
Söldner-X2: Final Prototype
Caladrius Blaze

**Comment by hiakki** [comment] 2023-11-10 07:24
@shinra-electric On further testing, got to know that this only occurs when we have RAM unavailability. Tested this app without multitasking/background processes, worked like a charm but after performing multitasking or pausing a game for too long is generating this issue.

**Comment by AniLeo** [comment] 2024-01-01 16:59
macOS 14 is currently unsupported due to a Rosetta 2 bug that leads to catastrophic failures, see #14794

Closing as assumed Duplicate, if the issue persists on a supported macOS version you can ask to reopen

**Closed by AniLeo** 2024-01-01 16:59 UTC

**Comment by hiakki** [comment] 2024-01-02 08:24
@AniLeo even after 14.3 beta upgrade, this issue seems to be resolved - https://github.com/RPCS3/rpcs3/issues/14794
but RPCS3 still crashes, whenever we exit the game. I don't think if it is a duplicate to Rosetta 2 bug.

**Comment by AniLeo** [comment] 2024-01-02 12:05
Thanks for the retest, then it's a duplicate of #14760 but it seemingly affects all macOS versions
