### ISSUE TITLE
Graphic glitches in some games on Nvidia GTX1060, Windows 7 and Async shader mode

### ISSUE THREAD

**Issue by Romano44** [RPCS3/rpcs3#12556] opened 2022-08-23 22:26 UTC
### Quick summary

Some games, like Uncharted 3 experience graphical glitches when using shader mode other than interpreter, like async. This happen on Windows 7, 5800X and GTX 1060 with latest Nvidia driver for it(472.12+, but also older like 466.xx).
No settings or game patches combination helped except shader interpreter, which is too slow.
I know this OS may soon became unsupported completely and I also know there are videos showing game working fine without glitches, either on Linux or maybe newer Windows. But still, I would love if this can be resolved especially since shader interpreter work and this may be opportunity to fix async. mode to more robust.
BTW I also tried older rpcs3 version all the way to some 0015.xxxx to no avail.

### Attach a log file

[RPCS3.log.gz](https://github.com/RPCS3/rpcs3/files/9410921/RPCS3.log.gz)

### Attach capture files for visual issues

![unch3](https://user-images.githubusercontent.com/17813740/186276776-61edfef8-ed59-4647-8a8d-df85a6eb81da.png)
![unch3_1](https://user-images.githubusercontent.com/17813740/186276796-d5dc8721-a10c-4db4-a252-3a782a19656b.png)

### System configuration

Windows 7 64bit
Ryzen 5800X
Nvidia GTX1060 : driver 472.12+/466.xx
16gb RAM

**Comment by RainbowCookie32** [comment] 2022-08-23 22:40
You can workaround the issues (and increase performance) by disabling some post-processing effects using game patches, the videos you mention probably use them. The issue itself looks like a duplicate of #11559 to me

**Comment by Romano44** [comment] 2022-08-24 09:09
@RainbowCookie32: I already did, I get only ~8fps on my CPU with that. But yes, issue look a lot like #11559, I have also seen those white sports and flickering squares as they show in the comments there. It is possible its same bug but I am not sure. In that bar I only had white spot issues but his second pic distortion look similar to mine which also happen mainly during movement.

However, unlike recommendation there I do have already updated game to v1.19 and I also enabled almost all patches(MLAA, SSAO, Bloom, DoF, motion blur etc.. I also enabled GPU lightning etc..). Nothing help.
Also, while shader interpreter works more stable, I should correct myself that its far from perfect as well: 
![unch3](https://user-images.githubusercontent.com/17813740/186376093-4836adbe-7b21-404a-a683-d48f05d98ae9.png)
Btw "force CPU blit" for white spots dos not work here. Also colors are off as you can see. With "async", colors are fine and random squares appear less with certain settings, but while spots and artifacts like shown in beginning of this post exist. 
They are most prevalent during movement, often can partially or fully disappear when standing still. Read and Write Depth Buffers does not help and can make for example starting screen look even worse.
I suspect people without issues are playing on RADV driver and Linux, since that guy in #11559 use Win 10.

**Comment by kd-11** [comment] 2022-08-24 09:47
Use the patch if you can. The cause of the blocks is known but the fix saps too much performance to be viable in production. Changes are being made to address this, but it will take some time (we're talking months)

**Comment by Romano44** [comment] 2022-08-24 10:52
@kd-11 By patch do you mean game update or a game patch? Because I tried using game patches(both on\off) and I did used latest game update.

**However, I have a new report! I was able to find solution! I simply removed game update and used original version**(which for my BCES01670 is v1.10 - not 1.0 or something - update was 1.19). 
After briefly testing without game update, I see 0 glitches! No white boxes, no squares, no artifacting like above of this post:
![unch3](https://user-images.githubusercontent.com/17813740/186400128-158b9a76-7032-43c4-bc0c-5455ecd6d602.png)
I used game patches and did not tried various settings yet. Later I will test more and probably restart game, but this looks like it.

**Comment by Romano44** [comment] 2022-08-24 19:33
Ok so I played from start about an hour, I can confirm that with a base game(v1.10) without update, there are no major glitches anymore - at least on settings with certain patches enabled. I am pretty sure there is no setting that would remedy updated game on my system as of now.

Patch to use GPU lightning fix the graphic glitch shown at the beginning of this post.
Then, if you use "write color buffer" option, you have to additionally use "performance WCB" patch, not just for the speed but it fix another graphic glitch that happen if WCB is enabled - ghosting:
![unch31](https://user-images.githubusercontent.com/17813740/186504520-3e4f9904-a066-4b44-b612-02473736f16b.png)
I could also play without WCB but some scenes would have wrong brightness. So that patch is more than just for performance. With WCB+ its patch, rare flashing of some background object still can occur but this is minor. 
Without WCB enabled there were no glitches at all, not even occasional, but brightness is wrong in some scenes so I use it(and RCB just in case). 

This issue can be considered fixed if using base game is enough as a solution. Otherwise for a fully updated game to v1.19, this issue remain unsolved - regardless of options or patches. I leave it up to you to decide whether or when to close it.

**Comment by solarmystic** [comment] 2022-08-25 00:10
Just to add another W10 user's perspective, i'm not seeing any of those white splotches or visual issues on my end with a 12400F/2080 ti rig using 516.94 drivers. Every patch is enabled except for Debug Menu and Dev Menu plus. 

![image](https://user-images.githubusercontent.com/4345150/186545551-0a6b10e8-aa37-4710-a6bf-c18023e0b6c5.png)

**Comment by RainbowCookie32** [comment] 2022-08-25 00:15
The log on the original post doesn't show any patches being applied, second log does. You probably used the patches for the wrong serial/update before downgrading the game.

**Comment by Romano44** [comment] 2022-08-25 08:19
@RainbowCookie32: I only uploaded one log, but I tested all combinations including patches on 1.19. I also checked that only patches for "games available" are shown.

**Comment by kd-11** [comment] 2022-08-28 11:45
I'll close this one. It seems the patches are not working for the fully updated version, but we don't track community patches here.
The cause of the other problems is well known and I'm slowly reworking the surface cache to handle it.

**Closed by kd-11** 2022-08-28 11:45 UTC
