### ISSUE TITLE
Graphical glitchs in Diablo III using Vulkan

### ISSUE THREAD

**Issue by FlyingCircus-** [RPCS3/rpcs3#8141] opened 2020-05-02 09:18 UTC
## Quick summary
Glitches shown on attached pictures

![RPCS3 Vulkan Diablo III 1](https://user-images.githubusercontent.com/9294088/80860115-efbdcb80-8c65-11ea-9f7b-9f5027fad997.JPG)
![RPCS3 Vulkan Diablo III 2](https://user-images.githubusercontent.com/9294088/80860119-f8ae9d00-8c65-11ea-8b74-95b2a180a88e.JPG)

## Details
Help me with the details you need to solve this problem.
System:
i7-2700K
AMD RX 5700

**Comment by kd-11** [comment] 2020-05-02 10:22
Duplicate of https://github.com/RPCS3/rpcs3/issues/6999
This is a known issue with RDNA 1 GPUs, disable MSAA in GUI options to fix it.

**Closed by kd-11** 2020-05-02 10:22 UTC
