### ISSUE TITLE
NieR RepliCant [BLJM60223] Pink effect

### ISSUE THREAD

**Issue by Sandvichero** [RPCS3/rpcs3#5077] opened 2018-09-03 18:31 UTC
RPCS3 0.0.5-7288
In some areas there is a pink effect on the textures.
Settings are default except:
WCB and the frame limiter is set to 30

![pink](https://user-images.githubusercontent.com/26612410/44998746-faeac080-af85-11e8-834d-032512dc9c57.PNG)

[RPCS3.log.gz](https://github.com/RPCS3/rpcs3/files/2346353/RPCS3.log.gz)
Intel i7-3770K

**Comment by AniLeo** [comment] 2018-09-05 14:09
In what areas can you get this effect? I have a save early in the game

Upload a RRC capture or indicate where to get this effect and I'll upload one

**Comment by Sandvichero** [comment] 2018-09-06 00:06
It occurs when you are tring to find yonah in the area before the first dungeon.

**Comment by AniLeo** [comment] 2018-09-09 19:02
Does it have to be on the mission? I went to the same area, but can't reproduce

**Comment by Sandvichero** [comment] 2018-09-09 21:34
I am on the mission when I took the picture also, when I try to take an RRC capture rpcs3 crashes.

**Comment by AniLeo** [comment] 2018-09-09 21:35
Crashes or stops? It's normal to stop and you having to press Play to continue.

Check if even with the crash there is an rrc capture in the captures folder.

**Comment by Sandvichero** [comment] 2018-09-09 21:48
The bug isn't appearing anymore IDK why.

**Comment by kd-11** [comment] 2018-09-13 07:48
Closing since bug is not reproducible.

**Closed by kd-11** 2018-09-13 07:48 UTC
Labels: Need Information
