### ISSUE TITLE
Plants Vs Zombies [NPEA00271] and [NPUA30059], full version crashes

### ISSUE THREAD

**Issue by JonesCroatia** [RPCS3/rpcs3#4774] opened 2018-06-18 14:22 UTC
Plants Vs Zombies, both [NPEA00271] and [NPUA30059] are playable as Trial versions. As soon as proper .rap file is copied to exdata folder, game crashes with white screen. Exact bug is noticed in another PopCap game, Peggle [NPUA30005]; (issue #4411)

RPCS3 v0.0.5-6957-af62c92b7 Alpha
Windows 7 x64 Sp1
Q9550@ 3.6GHz, 8GB RAM
GTX 1060 6GB, 397.94 

[RPCS3.PvZ.log.gz](https://github.com/RPCS3/rpcs3/files/2111618/RPCS3.PvZ.log.gz)

**Comment by AniLeo** [comment] 2018-06-18 14:41
Duplicate of #4411

**Closed by AniLeo** 2018-06-18 14:41 UTC
