### ISSUE TITLE
Bandicam vulkan hook crashing RPCS3

### ISSUE THREAD

**Issue by TristisOris** [RPCS3/rpcs3#5408] opened 2018-12-09 11:38 UTC
persona 5, rx 580, win10 1809.
it similar to old Vulkan issue, that was "fixed" at august.

![default](https://user-images.githubusercontent.com/1270117/49696651-3b2d9080-fbbe-11e8-881d-cc3582796203.png)
after that RPC hangs and must be close forced from task manager.

[RPCS3.log](https://github.com/RPCS3/rpcs3/files/2660466/RPCS3.log)
[DxDiag.txt](https://github.com/RPCS3/rpcs3/files/2660467/DxDiag.txt)

in OpenGL mode game works with huge freezes and perfomance drop on SSD.

**Comment by vsub** [comment] 2018-12-09 13:39
It seems to be coming from the program bandicam.
Did you tried without that program running

PS.I am already at 150+ hours on Persona 5 and I have yet to encounter a fatal error crash(rpcs3 freeze only 3 times this whole times but I know why,it was not unexpected)
I am on nvidia card tho and I don't have bandicam installed

**Comment by TristisOris** [comment] 2018-12-09 13:44
bandicam is not running. only RPC.

**Comment by vsub** [comment] 2018-12-09 13:50
Well according to the error,at least part of it,it is and it is injecting his dll into rpcs3
bdcamvk64.dll is part of bandicam

**Comment by TristisOris** [comment] 2018-12-09 14:46
i removed bandicam and game starts in vulkan mode.
thank you.

cleared all cashes, it looks work fine. Except of very long texture loading (white screen) on first location load without caches.
and all graphical glitches same as in openGL.
![default](https://user-images.githubusercontent.com/1270117/49698821-24953280-fbda-11e8-80eb-7d757838e845.png)

and error on exit. 
![default](https://user-images.githubusercontent.com/1270117/49698786-91f49380-fbd9-11e8-9a16-a73809d616b7.png)

**Comment by vsub** [comment] 2018-12-09 15:21
1.The weird face is caused by using Resolution Scaling(it's fine at 100% and I barely see an improvement above 100% in this game...or maybe because I am using 17inch screen)

2.Using ASMJIT rather than SPU LLVM makes shaders creation in this game MUCH faster and the game works faster.
If you have an option in your amd gpu control panel to force the gpu to always work at max power,it will also help speed up the shaders creation too

Personally I play with no shaders cache
Disable On-Disk Shader Cache: true
because at least here,the shaders are created instantly and I don't have to wait 2 minutes to load them at the game start

Also vulkan work better than OGL(you are on amd gpu using OGL is not very good choice)
And also,go to the personas screen and select and view any of them,the go to(rpcs3 menus)View=>Show Debugger=>from the drop down select SPU[0x2000002] Thread (gfdSpursCellSpursKernel2) and pause=>play it until the game start running while this is paused...I get +5-10 fps almost everywhere

**Comment by TristisOris** [comment] 2018-12-09 16:58
1. yep, i tested different resolution scaling, and didn't see any usefull difference above 100%. Only fonts curruption.
and it's stange, because i see videos with 4k scaling without any glitches.

2. you mean SPU cache? Disabled it now and loading became more fasters. 
ASMJIT is a ON by default, so i didn't change anything here.

after some time playing, i consider a less stuttering in public places with Vulkan. FPS drop became not so dramatic as before.

Thank you much.

**Comment by AniLeo** [comment] 2018-12-09 19:37
Closing as this isn't a RPCS3 issue, external software is interfering.

If you need support with the game, use our Discord server or our Forums.

**Closed by AniLeo** 2018-12-09 19:37 UTC

**Comment by Anths2016** [comment] 2020-05-31 20:19
I have the same problem... But Bandicam was closed ... why?

**Comment by Anamon** [comment] 2020-07-14 22:26
@Anths2016 Bandicam doesn't need to be running, it will be hooked by the Vulkan runtime. Check your registry key `HKLM\SOFTWARE\Khronos\Vulkan\ImplicitLayers`, you will likely find it listed there. Some versions of Bandicam don't remove this entry when you disable the Vulkan hook in settings. It doesn't help that the library seems to be buggy, I also can't start the Android emulator when it's active.

Quite some stuff can accumulate there, you can also see my low-tech way of temporarily disabling the Bandicam hook:
![grafik](https://user-images.githubusercontent.com/517549/87482535-e079d780-c631-11ea-9882-bfa447e63954.png)

**Comment by viplike** [comment] 2021-07-24 15:05
@Anamon, thanks, your decision is working for starting Android Studio Emulator

**Comment by griever-gf** [comment] 2023-04-04 08:25
Still presents in 2023
