### ISSUE TITLE
Drakenguard 3 [BLUS31197] Crashes when attempting to Save State

### ISSUE THREAD

**Issue by DGEDU** [RPCS3/rpcs3#14016] opened 2023-06-13 05:39 UTC
### Quick summary

Using CTRL+S causes emulator to stop responding without ever exiting cleanly (Tested >5 min), no Save State is created. 

### Details

Drakenguard 3 has not worked with Save States the last 4 builds, currently I'm on 0.0.28-15179-cedv95f. I thought at first it was just a issue with the game itself, and it might still be for all i know. But since more issues with this have cropped up, i figured more data might help. Game was dumped from Disc on a Manjaro Linux PC (RPCS3 sees it as "Disc Game"), then transferred to my windows machine since it had a far better GPU. No other issues have appeared in game besides the known ones (Which were easily resolved by changing settings). Game was also updated to 1.01 using official patch, 

### Attach a log file

[RPCS3.log](https://github.com/RPCS3/rpcs3/files/11730840/RPCS3.log)

### System configuration

OS: Windows 10 Pro - Build 19045.2965 
CPU: AMD Ryzen 3950X
GPU: Radeon RX 7900
RAM: 32GB DDR4 3200mhz
Storage: 256GB SSD, 2TB HDD, 3TB HDD (Game runs on SSD)

### Other details

Enable SPU Loop Detection is tripped enabled, along with Multithreaded RSX and Async Texture Streaming, Resolution Scale Threshold is 512x512 to prevent known issues on UE3, Scale is 300% and base resolution is default. PPU LLVM Precompilation is also enabled.

**Comment by Asinin3** [comment] 2023-06-13 12:48
Duplicate of #14007

**Closed by Asinin3** 2023-06-13 12:48 UTC
Labels: Savestates
