### ISSUE TITLE
Kingdom Hearts 2.5 ReMIX Missing game content 

### ISSUE THREAD

**Issue by Sharp8** [RPCS3/rpcs3#8061] opened 2020-04-17 22:23 UTC
## Quick summary
One content of the game doesn't appear.

## Details
Please provide as much detail as you can here, including
- expected (real hw) and observed (emulator) behavior
- full logs (not from UI)
- back traces (for hard crashes)
- screenshots, Renderdoc, and RSX captures (for visual issues)
- your system configuration (OS, CPU, GPU, driver versions, etc)
- anything else you deem to be important

I am playing on RPCS3 0.0.8-9680-fa3de7a Alpha 
The game: KINGDOM HEARTS HD 2.5 ReMIX
Serial BLES02070
Version: 01.00
Category: Disc Game
Compatibility: Playable (2017-11-21)

Concrete error: 
In Garden of Assemblage, you can defeat the Replica Data Organization and one of them is missing and I don't know if I can do anything. I killed all of them but Vexen doesn't appear in the game.

RPCS3 v0.0.8-9680-fa3fde7a Alpha | HEAD | Firmware version: 4.85
Intel(R) Core(TM) i7-7700 CPU @ 3.60GHz | 8 Threads | 15.94 GiB RAM | TSC: Bad | AVX+ | TSX
Operating system: Windows, Major: 10, Minor: 0, Build: 18362, Service Pack: none, Compatibility mode: 0
·! 0:00:00.000000 RSX: Found vulkan-compatible GPU: 'GeForce GTX 1050' running on driver 445.75.0.0

Screenshot:
![PROOF VEXEN BUG KH 2 5 REMIX](https://user-images.githubusercontent.com/63881741/79618588-ba17cf00-810a-11ea-87f0-037da96274ab.png)

**Comment by AniLeo** [comment] 2020-04-18 13:54
Using old build, invalid report. Needs retesting on latest master in order to proceed.

**Comment by darkash** [comment] 2020-04-18 16:24
If it doesn't appear, that means you haven't killed vexen

Vexen should be in peddler's room (aggrabah)
I don't think it's related to emulation since all the other replica data appeared as you've mentioned

**Comment by Asinin3** [comment] 2020-10-31 05:11
Closing ticket as haven't received an update and it's a potential non-issue. If the issue is still occurring please advise and we can re-open. But provide a new log file of the latest version of RPCS3 and include a save file so we can try to reproduce this crash if necessary.

**Closed by Asinin3** 2020-10-31 05:11 UTC
Labels: Need Information
