### ISSUE TITLE
Demon's souls broke after newest update

### ISSUE THREAD

**Issue by jamesbrandx97** [RPCS3/rpcs3#9408] opened 2020-12-10 19:50 UTC
## Quick summary
Updated to the latest rpcs3 and the game black screens after demon's souls loading screen when booted up

#### 1. RPCS3 build 0.0.13-11367

![2020 12 10-14 47](https://user-images.githubusercontent.com/75809030/101822089-d384e580-3af6-11eb-8ac4-6b61a8e492b5.png)
![2020 12 10-14 47_01](https://user-images.githubusercontent.com/75809030/101822111-d97ac680-3af6-11eb-9758-3ebf90630641.png)

#### 6. Please provide your system configuration:
* OS Windows 10
* CPU AMD ryzen 7 3700x 8 core 16 logical processor
* GPU Radeon RX 480
* Driver version 20.12.1
* etc.

worked fine yesterday 
[RPCS3.log.gz](https://github.com/RPCS3/rpcs3/files/5675249/RPCS3.log.gz)

**Comment by kotn3l** [comment] 2020-12-10 19:58
Can also confirm this. I mentioned it in the reddit questions thread as well, someone also commented they had the same issue.
1600X, GTX 1070 here.

**Comment by jamesbrandx97** [comment] 2020-12-10 19:59
i guess i am at their mercy lol

**Comment by kd-11** [comment] 2020-12-10 20:25
Duplicate of https://github.com/RPCS3/rpcs3/issues/9410

**Closed by kd-11** 2020-12-10 20:25 UTC
