### ISSUE TITLE
VSync option doesn't work for NVidia cards

### ISSUE THREAD

**Issue by Psycho-A** [RPCS3/rpcs3#4689] opened 2018-06-02 03:06 UTC
If I set VSync to On in the emulator, it does nothing if I play fullscreen. Video driver setting is "Use application setting", so the emulator **must** enable VSync. The only forced-enabling VSync inside videoderiver helps, but - hey, what the native emulator option for? It affects completely nothing in fullscreen. It seems to be workable in windowed mode only.

**Comment by JohnHolmesII** [comment] 2018-06-02 03:13
Windows?
OpenGL & Vulkan or just one?
Are you setting the global config to vsync or per game settings?

**Comment by Psycho-A** [comment] 2018-06-02 03:16
Windows 7, both OGL and Vulkan behaves the same. I don't use per-game settings, so it's global config.

**Comment by JohnHolmesII** [comment] 2018-06-02 03:17
What build, and is it every game?

**Comment by Psycho-A** [comment] 2018-06-02 03:18
See abouve about the build. Checked on Read Dead Redemption, WWE 2009 and Silent Hill Downpour.

**Comment by MSuih** [comment] 2018-06-02 05:40
There have been complaints about this on #help for months. so it doesn't seem like a recent regression.

**Comment by ruipin** [comment] 2018-06-02 11:58
I see this too. Have to force VSync on the driver control panel for tearing to disappear. Also, I've noticed that if I set my display to a refresh rate that is not 60Hz (e.g. 30Hz), I get tearing even if I force VSync on in the driver.

**Comment by kd-11** [comment] 2018-06-02 12:29
The nvidia driver tears even when present mode is fifo and its derivatives like mailbox. I chose to never truly force double buffered vsync as it is terrible, but a config option exists in the yml. As for why nvidia ignores mailbox and fifo relaxed modes - only they can tell us.

**Comment by Psycho-A** [comment] 2018-06-02 17:58
@kd-11 But why Fast Sync mode doesn't work too? It doesn't use double buffering as far I know - it just does existing frame aligning and dropping, and there's no tearing in other games even if framerate is lower than monitor's one.

**Comment by kd-11** [comment] 2018-06-02 20:33
Developers do not actually program vsync - you kindly ask the driver for it and hope it complies. There are a few provided modes by vulkan, FIFO (double buffered), FIFO_RELAXED (adaptive), MAILBOX(fast) and IMMEDIATE (no sync). What happens when you set fast mode is that the driver reports FIFO, MAILBOX and IMMEDIATE as being available. In this case, we pick MAILBOX. However, the driver does not like something about the rpcs3 context and ignores this setting. None of the options work correctly for me especially on linux, so I'm not really sure whats up. Try forcing FIFO in the config file and see if the driver respects it at least. The way the spec defines these modes, there should be no tearing, you just set the mode you want and the driver should automatically sync present with vblank.

**Comment by greentop** [comment] 2018-06-03 01:56
Under Linux _(Ubuntu 16.04)_, it could be observed that some applications (RPCS3 included) would have screen tearing present while running in fullscreen if using the Vulkan renderer. To correct this one must go into a "Advanced" setting within the Nvidia X Server Setting's "X Server Display Configuration" to enable the **Force Full Composition Pipeline**. 

![screenshot from 2018-06-02 21-30-03](https://user-images.githubusercontent.com/2325766/40882422-6b837f6e-66af-11e8-85c5-94f71b0aa8b2.png)

**Comment by Relsig** [comment] 2018-06-05 06:18
Windows 10 gtx 760 vsync option in rpcs3 works for me even while fullscreen with drivers set to 'let the 3d application decide'

Sorry you guys are having issues, hope it gets worked out!

**Comment by kd-11** [comment] 2018-09-10 10:57
This is a known nvidia bug, I'll close it since there is nothing we can do from our end.

**Closed by kd-11** 2018-09-10 10:57 UTC

**Comment by hrydgard** [comment] 2019-06-18 08:00
https://devtalk.nvidia.com/default/topic/1055177/vulkan/vk_present_mode_mailbox_khr-behaving-incorrectly/ looks like a fix is on the way.

**Comment by kd-11** [comment] 2019-06-18 08:34
Finally!

**Comment by drinkmystery** [comment] 2020-02-26 12:56
> 
> 
> Finally!

Now if vsync option is turned on, rpcs3 uses fifo mode.
https://github.com/RPCS3/rpcs3/blob/master/rpcs3/Emu/RSX/VK/VKHelpers.h#L2479
As nvidia has fixed the driver problem, is it possible to switch back to mailbox mode? Or maybe provide an option?

**Comment by kd-11** [comment] 2020-02-26 14:07
Is this confirmed fixed? It can be re-added when tri-state checkboxes come in. OpenGL also needs 3 options for no sync, vsync and adaptive/fast sync and I think vulkan could benefit from the same.

**Comment by drinkmystery** [comment] 2020-03-04 15:01
> 
> 
> Is this confirmed fixed? It can be re-added when tri-state checkboxes come in. OpenGL also needs 3 options for no sync, vsync and adaptive/fast sync and I think vulkan could benefit from the same.

I personally think this has nothing to do with nvidia bug.
RPCS3 uses vulkan, then it provides options to choose the presentation mode provided by vulkan is reasonable.
Not using the vulkan Specification due to a bug by nvidia is not fair to other vulkan users.
Amd card users may also use vulkan,I have not heard of amd having a similar bug.

**Comment by BreakPoints** [comment] 2023-12-12 00:57
Late to the party but I can confirm that vsync still doesn't work for me on driver 546.29, at least only in RPCS3.
