### ISSUE TITLE
System running out of memory compiling shader cache using Vulkan

### ISSUE THREAD

**Issue by afcaballero-1994** [RPCS3/rpcs3#8602] opened 2020-07-20 02:57 UTC
Running on linux, playing MLB 2k13.
CPU: Ryzen 3600
GPU: RX 5700 XT
16 GB of RAM
Endevour OS (ARCH based)
While compiling the shaders the process consumes all ram available, only using vulkan with OpenGL works fine
[RPCS3.log](https://github.com/RPCS3/rpcs3/files/4945253/RPCS3.log)

**Comment by AniLeo** [comment] 2020-07-20 03:56
That log is from Windows.

**Comment by afcaballero-1994** [comment] 2020-07-20 04:15
> That log is from Windows.

Sorry, I got confused, the file size is 200+MB so i uploaded to ZS [https://www21.zippyshare.com/v/2XDtiMAJ/file.html
](url). I was having issue with windows also, from what i see in that log file, i forgot it xd

**Comment by AniLeo** [comment] 2020-07-20 04:39
Compress it before uploading, 244MB of uncompressed text is unreasonable, after compressing you can upload it here directly, rename file if you need to if GitHub refuses the filename due to used extension

**Comment by afcaballero-1994** [comment] 2020-07-20 05:38
Well, Im having issues on windows with this game too, so the first log is still usefull, i think, upload again just in case
[RPCS3.zip](https://github.com/RPCS3/rpcs3/files/4945689/RPCS3.zip)

**Comment by AniLeo** [comment] 2020-07-20 06:00
Windows log shows a driver crash, Linux one doesn't show anything, could be a badly generated shader in RPCS3
@kd-11 for triaging

**Comment by kd-11** [comment] 2020-07-20 16:30
Known issue with AMD spirv compiler especially when shader optimizations are enabled. Unfortunately it is completely random.
I have a plan to work around this with SEH for AMD proprietary driver. Linux crash should be unrelated, RADV seems to be mostly unaffected.
Alternatively we can just remove all the shader optimization stuff for AMD hardware which seems incompatible. The optimization tools are third party, nothing we can really do from our side.

**Comment by afcaballero-1994** [comment] 2020-07-20 19:45
[RPCS3.log](https://github.com/RPCS3/rpcs3/files/4949740/RPCS3.log)
Here a more recent one on linux,at least on this one the system wasnt freeze.

**Comment by afcaballero-1994** [comment] 2020-09-06 03:45
The issue is solved, but there are some audio issues and graphical glitches.

**Comment by kd-11** [comment] 2020-10-18 15:33
I disabled automated spirv optimizations and instead handled codegen optimizations by hand. If the problem is fixed now, close the issue and open a new one for the graphics problems.

**Closed** 2020-10-18 16:30 UTC
Labels: Need Information
