### ISSUE TITLE
[MRTC00003] Final Fantasy XIII softlock (possible Ryzen-only issue)

### ISSUE THREAD

**Issue by Metasynic** [RPCS3/rpcs3#6623] opened 2019-09-23 11:35 UTC
I made an issue for this before (now closed), but making a new one because the old one was not very well written and I hadn't investigated the problem properly.

When finishing the tutorial battle for Final Fantasy XIII, the game softlocks. It's possible to move the camera but the game doesn't actually progress. There are some deadlock messages in the log which may or may not relate to it (they appear at the start of the battle and later on). Importantly, this issue doesn't seem to occur for anyone playing the game using an Intel processor, as there are reports on the [RPCS3 forums](https://forums.rpcs3.net/thread-181431-post-305819.html#pid305819) and [here on GitHub](https://github.com/RPCS3/rpcs3/issues/6610) that can get past the tutorial battle.

My hardware is AMD Ryzen 5 1500X and GTX 970 so I suspect this is a problem affecting the AMD Ryzen processors only, but this is just conjecture. [Here's a log](https://drive.google.com/file/d/1PdTg-g1OG83aZ3dPF1hDvdZ9jfKhFKS3/view?usp=sharing), let me know if there's any more information I can provide. Version is 0.0.7-8759 (hash 40fcd457).

![image](https://user-images.githubusercontent.com/24281766/65422269-db773d80-ddfd-11e9-8d70-f8c25d79ccdb.png)

**Comment by Myoko** [comment] 2019-09-23 11:51
you try locked 30 fps! and look what will happen

**Comment by Silanda** [comment] 2019-09-23 12:04
Possibly unrelated but I'll mention it just in case: I've experienced a number of issues with my Ryzen 3700x when the LLVM cpu type is set to default (it defaults to znver1) or manually to znver2, lockups being one issue. Manually setting the LLVM CPU type to skylake resolved the issue.

I posted about the it here: https://forums.rpcs3.net/thread-200726.html

Soul Calibur IV is another game affected and it locks up in the menus.

**Comment by Metasynic** [comment] 2019-09-23 12:23
Unfortunately I can't get a locked 30FPS because my CPU is too weak (unless there's a way to force it?), that could be the problem. On the other hand the forum report I linked above averages below 30FPS during battles, but that's on an Intel processor.

Thank you for the suggestion Silanda, I tried but unfortunately this didn't solve the problem. You should probably make an issue for that here so the devs can take a look at it, if you haven't already.

**Comment by kd-11** [comment] 2019-09-23 12:26
CPU incompatibility issues with LLVM should go away once rpcs3's llvm dependency is updated. This used to be a problem when zenver1 came out too; llvm was generating broken code for it.

**Comment by lextra2** [comment] 2019-10-06 18:07
works for me. ryzen 3600 with build 0.0.7-8829. had a "trap error" crash from what I'd assume is too many objects being cached at once but after simply restarting the game I could progress without any more crashes. game never softlocked for me.

**Comment by RainbowCookie32** [comment] 2020-06-09 01:19
@Metasynic can you retest on latest master?

**Comment by elad335** [comment] 2020-10-29 12:28
Closing until relavant information on how to reproduce is added, and it must be valid situation. (using correct settings etc)

**Closed by elad335** 2020-10-29 12:28 UTC
