### ISSUE TITLE
[NPEB01899] Minecraft major graphical issues

### ISSUE THREAD

**Issue by ZProLegend007** [RPCS3/rpcs3#15062] opened 2024-01-19 02:54 UTC
### Quick summary

Minecraft doesn't boot properly, loads on a black screen with some red artifacts and then when on minecraft home screen shows more graphical glitches.

### Details

Shows some artifacts and major graphical issues, basically no useable display output. Audio, controls and the rest of the game works fine as far as I can tell from audio and mashing buttons. 

### Attach a log file

[RPCS3.log](https://github.com/RPCS3/rpcs3/files/13983655/RPCS3.log)

### Attach capture files for visual issues

[NPEB01899_20240119104831_capture.rrc.gz](https://github.com/RPCS3/rpcs3/files/13983657/NPEB01899_20240119104831_capture.rrc.gz)

### System configuration

Intel 7th Gen i7-7700HQ
32GB DDR4 @2133MHz
NVIDIA GeForce GTX 1050 (probs mobile - its in a laptop)
256GB Samsung SSD
1080p 60z Display

**Comment by ZProLegend007** [comment] 2024-01-19 02:59
**UPDATE: This only happens when changing resolution to 1080p... any fix?**

**Comment by Jonathan44062** [comment] 2024-01-19 03:12
Never change resolution windows size, it breaks the game, change back to 1280x720p, keep using resolution upscaling instead, it won't be fixed the windows resolution.

**Comment by MSuih** [comment] 2024-01-19 05:01
Forcing games to output in resolutions they do not support can cause issues like these. It is not a bug but rather expected behaviour. Use resolution scaling instead as Jonathan mentioned.

Also ask for help and support over on our Discord, not in github issues.

**Closed by MSuih** 2024-01-19 05:01 UTC

**Comment by ZProLegend007** [comment] 2024-01-19 13:49
I see, understood. Is odd is all as the games that struggle to output 1080p work perfectly fine at that resolution on an actual ps3.

Also is there any reason some games would be blurry even at a higher res?

**Comment by Jonathan44062** [comment] 2024-01-19 17:13
This is what kd-11 said about it in another post (https://github.com/RPCS3/rpcs3/issues/13376#issuecomment-1423270457):
1080p is the "TV resolution" here, not game resolution. The game will render 720p and upscale to 1080p bilinearly. The resolution setting refers to the virtual TV, not render resolution, but it is difficult to communicate this fact with end users as that's not how PC games work. Now there are a handful of titles that will use a different base resolution when the TV supports 1080p, but these are a handful and the games almost never actually run at 1080p. Its going to be something in between usually sub-900p with some features removed (e.g worse shadows, etc) to achieve the higher resolution.
