### ISSUE TITLE
RPCS3 is hang

### ISSUE THREAD

**Issue by trantien1997** [RPCS3/rpcs3#15404] opened 2024-04-05 07:02 UTC
### Quick summary

After update new version (download new version and install), rpcs3 is still hang

### Details

After update new version (download new version and install), rpcs3 is still hang

### Attach a log file

[RPCS3.log](https://github.com/RPCS3/rpcs3/files/14881187/RPCS3.log)

**Comment by Megamouse** [comment] 2024-04-05 07:09
Duplicate of #15393

**Closed by Megamouse** 2024-04-05 07:09 UTC
