### ISSUE TITLE
ULTIMATE MARVEL VS. CAPCOM 3 [BLUS30787] random crashing, graphics and sound issues

### ISSUE THREAD

**Issue by Augusto7743** [RPCS3/rpcs3#4905] opened 2018-07-19 08:07 UTC
RPCS3 recent versions has graphics issues in both OpenGL and Vulkan.

![ultimate marvel vs capcom 3 blus30787 1](https://user-images.githubusercontent.com/21184987/42929660-1a3e5b5c-8b11-11e8-95a3-46154b365925.png)

![ultimate marvel vs capcom 3 blus30787 2](https://user-images.githubusercontent.com/21184987/42929718-40cb6f12-8b11-11e8-8b71-167f898896e6.png)

RPCS3 recent versions has random crashes when in "loading" screen, select player screen or in gameplay being that first the sound is cut off and in few seconds crash.
The game run OpenGL more fast than Vulkan.
CPU AMD FX-6300
RAM 4 GB
GPU GeForce GT 640 latest drivers
Windows 10 Pro 64 RS3

below the log and rpcs3.log
--
RPCS3 v0.0.5-7104-a19113025 Alpha | HEAD
AMD FX(tm)-6300 Six-Core Processor  | 6 Threads | 3.98 GiB RAM | AVXx
E CFG: cfg::try_to_enum_value('false'): invalid enum value: invalid stoull argument x2
S LDR: Updates found at /dev_hdd0/game/BLUS30787/!
E CFG: cfg::try_to_enum_value('false'): invalid enum value: invalid stoull argument
S LDR: Boot successful.
E PPU: LLVM: [0x006fc8f8] Error: MTFSF
E PPU: LLVM: [0x006fcb38] Error: MFFS
S {PPU[0x1000000] Thread (main_thread)} PPU: LLVM: Loaded module v2-liblv2.sprx-6E56691FE33B8E4B-bdver2.obj
S {PPU[0x1000000] Thread (main_thread)} SPU: SPU Recompiler Runtime (ASMJIT) initialized...
U {PPU[0x1000000] Thread (main_thread)} SPU TODO: [0x30a4] Unexpected instruction on $SP: SELB
U {PPU[0x1000000] Thread (main_thread)} SPU TODO: [0x30cc] Unexpected instruction on $SP: SELB
U {PPU[0x1000000] Thread (main_thread)} SPU TODO: [0x3088] Unexpected instruction on $SP: SELB
U {PPU[0x1000000] Thread (main_thread)} SPU TODO: [0x30b4] Unexpected instruction on $SP: SELB
U {PPU[0x1000000] Thread (main_thread)} SPU TODO: [0x30a4] Unexpected instruction on $SP: SELB
U {PPU[0x1000000] Thread (main_thread)} SPU TODO: [0x30cc] Unexpected instruction on $SP: SELB
U {PPU[0x1000000] Thread (main_thread)} SPU TODO: [0x5fb4] Unexpected instruction on $SP: SELB
U {PPU[0x1000000] Thread (main_thread)} SPU TODO: [0x3088] Unexpected instruction on $SP: SELB
U {PPU[0x1000000] Thread (main_thread)} SPU TODO: [0x30b4] Unexpected instruction on $SP: SELB
U {PPU[0x1000000] Thread (main_thread)} SPU TODO: [0x3088] Unexpected instruction on $SP: SELB
U {PPU[0x1000000] Thread (main_thread)} SPU TODO: [0x30b4] Unexpected instruction on $SP: SELB
S {PPU[0x1000000] Thread (main_thread)} SPU: SPU Runtime: Built 2330 functions.
U {PPU[0x1000000] Thread (main_thread) [0x0116fe64]} sys_prx TODO: _sys_prx_register_module()
U {PPU[0x1000000] Thread (main_thread) [0x011700bc]} sys_prx TODO: _sys_prx_register_library(library=*0x11726a0)
S {PPU[0x1000000] Thread (main_thread) [0x011709ac]} PPU: LLVM: Loaded module v2-libsysmodule.sprx-E926430A8C1D5DCB-bdver2.obj
S {PPU[0x1000000] Thread (main_thread) [0x011709ac]} sys_prx: Loaded module: /dev_flash/sys/external/libsysmodule.sprx
U {PPU[0x1000000] Thread (main_thread) [0x011b3d8c]} HLE TODO: Unimplemented syscall sys_ss_access_control_engine -> CELL_OK
S {PPU[0x1000000] Thread (main_thread) [0x011714d0]} PPU: LLVM: Loaded module v2-libgcm_sys.sprx-92BB3C6B43076AD9-bdver2.obj
S {PPU[0x1000000] Thread (main_thread) [0x011714d0]} sys_prx: Loaded module: /dev_flash/sys/external/libgcm_sys.sprx
S {PPU[0x1000000] Thread (main_thread) [0x011714d0]} PPU: LLVM: Loaded module v2-libsre.sprx-7BD57B68D8CA8EBC-bdver2.obj
S {PPU[0x1000000] Thread (main_thread) [0x011714d0]} sys_prx: Loaded module: /dev_flash/sys/external/libsre.sprx
S {PPU[0x1000000] Thread (main_thread) [0x011714d0]} PPU: LLVM: Loaded module v2-libfs.sprx-BB8655E4C5C49381-bdver2.obj
S {PPU[0x1000000] Thread (main_thread) [0x011714d0]} sys_prx: Loaded module: /dev_flash/sys/external/libfs.sprx
U {PPU[0x1000000] Thread (main_thread) [0x0117061c]} sys_prx TODO: _sys_prx_register_module()
E {PPU[0x1000000] Thread (main_thread) [0x011654ec]} '_sys_lwmutex_lock' failed with 0x80010005 : CELL_ESRCH [1]
E {PPU[0x1000000] Thread (main_thread) [0x011654ec]} '_sys_lwmutex_lock' failed with 0x80010005 : CELL_ESRCH [2]
S {PPU[0x1000000] Thread (main_thread) [0x011709ac]} PPU: LLVM: Loaded module v2-libadec.sprx-C1FA8E97F96CF507-bdver2.obj
S {PPU[0x1000000] Thread (main_thread) [0x011709ac]} sys_prx: Loaded module: /dev_flash/sys/external/libadec.sprx
S {PPU[0x1000000] Thread (main_thread) [0x011709ac]} PPU: LLVM: Loaded module v2-libat3dec.sprx-CF7CA4764ADFE9E1-bdver2.obj
S {PPU[0x1000000] Thread (main_thread) [0x011709ac]} sys_prx: Loaded module: /dev_flash/sys/external/libat3dec.sprx
S {PPU[0x1000000] Thread (main_thread) [0x011709ac]} PPU: LLVM: Loaded module v2-libatxdec.sprx-6D48FF4B62CB07E2-bdver2.obj
S {PPU[0x1000000] Thread (main_thread) [0x011709ac]} sys_prx: Loaded module: /dev_flash/sys/external/libatxdec.sprx
S {PPU[0x1000000] Thread (main_thread) [0x011709ac]} PPU: LLVM: Loaded module v2-libatrac3plus.sprx-579A6F0C799EE900-bdver2.obj
S {PPU[0x1000000] Thread (main_thread) [0x011709ac]} sys_prx: Loaded module: /dev_flash/sys/external/libatrac3plus.sprx
S {PPU[0x1000000] Thread (main_thread) [0x011709ac]} PPU: LLVM: Loaded module v2-libac3dec.sprx-59DFFFC9625469CF-bdver2.obj
S {PPU[0x1000000] Thread (main_thread) [0x011709ac]} sys_prx: Loaded module: /dev_flash/sys/external/libac3dec.sprx
S {PPU[0x1000000] Thread (main_thread) [0x011709ac]} PPU: LLVM: Loaded module v2-libpamf.sprx-9395500A1659F740-bdver2.obj
S {PPU[0x1000000] Thread (main_thread) [0x011709ac]} sys_prx: Loaded module: /dev_flash/sys/external/libpamf.sprx
S {PPU[0x1000000] Thread (main_thread) [0x011709ac]} PPU: LLVM: Loaded module v2-libdmux.sprx-163476C36B290E2B-bdver2.obj
S {PPU[0x1000000] Thread (main_thread) [0x011709ac]} sys_prx: Loaded module: /dev_flash/sys/external/libdmux.sprx
S {PPU[0x1000000] Thread (main_thread) [0x011709ac]} PPU: LLVM: Loaded module v2-libdmuxpamf.sprx-8A70960BBED2AB60-bdver2.obj
S {PPU[0x1000000] Thread (main_thread) [0x011709ac]} sys_prx: Loaded module: /dev_flash/sys/external/libdmuxpamf.sprx
S {PPU[0x1000000] Thread (main_thread) [0x011709ac]} PPU: LLVM: Loaded module v2-libsmvd2.sprx-FFB2AC5120590192-bdver2.obj
S {PPU[0x1000000] Thread (main_thread) [0x011709ac]} sys_prx: Loaded module: /dev_flash/sys/external/libsmvd2.sprx
S {PPU[0x1000000] Thread (main_thread) [0x011709ac]} PPU: LLVM: Loaded module v2-libavcdec.sprx-4EEBFE03EA0B9741-bdver2.obj
S {PPU[0x1000000] Thread (main_thread) [0x011709ac]} sys_prx: Loaded module: /dev_flash/sys/external/libavcdec.sprx
S {PPU[0x1000000] Thread (main_thread) [0x011709ac]} PPU: LLVM: Loaded module v2-libresc.sprx-868A23FA3425D270-bdver2.obj
S {PPU[0x1000000] Thread (main_thread) [0x011709ac]} sys_prx: Loaded module: /dev_flash/sys/external/libresc.sprx
S {PPU[0x1000000] Thread (main_thread) [0x011709ac]} PPU: LLVM: Loaded module v2-libfiber.sprx-90B538A6D4A84178-bdver2.obj
S {PPU[0x1000000] Thread (main_thread) [0x011709ac]} sys_prx: Loaded module: /dev_flash/sys/external/libfiber.sprx
S {PPU[0x1000000] Thread (main_thread) [0x011709ac]} PPU: LLVM: Loaded module v2-libl10n.sprx-CF794CD12F0202AD-bdver2.obj
S {PPU[0x1000000] Thread (main_thread) [0x011709ac]} sys_prx: Loaded module: /dev_flash/sys/external/libl10n.sprx
U {PPU[0x1000000] Thread (main_thread) [0x011f7d80]} sys_spu TODO: Unimplemented SPU Thread options (0x2)
U {PPU[0x1000000] Thread (main_thread) [0x0116ff0c]} sys_prx TODO: _sys_prx_get_module_id_by_name(name=“cellLibprof”, flags=0, pOpt=*0x0)
E {PPU[0x1000000] Thread (main_thread) [0x0116ff0c]} '_sys_prx_get_module_id_by_name' failed with 0x8001112e : CELL_PRX_ERROR_UNKNOWN_MODULE [1]
U {PPU[0x1000000] Thread (main_thread) [0x011f7d80]} sys_spu TODO: Unimplemented SPU Thread options (0x2)
U {PPU[0x1000000] Thread (main_thread) [0x0116ff0c]} sys_prx TODO: _sys_prx_get_module_id_by_name(name=“cellLibprof”, flags=0, pOpt=*0x0)
E {PPU[0x1000000] Thread (main_thread) [0x0116ff0c]} '_sys_prx_get_module_id_by_name' failed with 0x8001112e : CELL_PRX_ERROR_UNKNOWN_MODULE [2]
U {PPU[0x1000000] Thread (main_thread) [0x011f7d80]} sys_spu TODO: Unimplemented SPU Thread options (0x2)
U {PPU[0x1000000] Thread (main_thread) [0x0116ff0c]} sys_prx TODO: _sys_prx_get_module_id_by_name(name=“cellLibprof”, flags=0, pOpt=*0x0)
E {PPU[0x1000000] Thread (main_thread) [0x0116ff0c]} '_sys_prx_get_module_id_by_name' failed with 0x8001112e : CELL_PRX_ERROR_UNKNOWN_MODULE [3]
U {PPU[0x1000000] Thread (main_thread) [0x011f7d80]} sys_spu TODO: Unimplemented SPU Thread options (0x2) x5
U {PPU[0x1000000] Thread (main_thread) [0x0116ff0c]} sys_prx TODO: _sys_prx_get_module_id_by_name(name=“cellLibprof”, flags=0, pOpt=*0x0)
U {PPU[0x1000000] Thread (main_thread) [0x011f7d80]} sys_spu TODO: Unimplemented SPU Thread options (0x2)
U {PPU[0x1000000] Thread (main_thread) [0x0116ff0c]} sys_prx TODO: _sys_prx_get_module_id_by_name(name=“cellLibprof”, flags=0, pOpt=*0x0)
U {PPU[0x1000000] Thread (main_thread) [0x00cd5720]} cellSysutil TODO: cellVideoOutConfigure(videoOut=0, config=*0xd001df20, option=*0x0, waitForEvent=0)
E {rsx::thread} RSX: NV3089_IMAGE_IN_SIZE: Invalid blit dimensions passed
E {PPU[0x1000000] Thread (main_thread) [0x011654ec]} '_sys_lwmutex_lock' failed with 0x80010005 : CELL_ESRCH [3]
S {PPU[0x1000000] Thread (main_thread) [0x011709ac]} PPU: LLVM: Loaded module v2-libnet.sprx-FFB9AC229DA8A825-bdver2.obj
S {PPU[0x1000000] Thread (main_thread) [0x011709ac]} sys_prx: Loaded module: /dev_flash/sys/external/libnet.sprx
U {PPU[0x1000000] Thread (main_thread) [0x00cd70b8]} cellNetCtl TODO: cellNetCtlAddHandler(handler=*0xf84d28, arg=*0x2794ab50, hid=*0x2794aca4)
U {PPU[0x1000000] Thread (main_thread) [0x00cd7d68]} sceNp TODO: sceNpBasicRegisterContextSensitiveHandler
U {PPU[0x1000000] Thread (main_thread) [0x011651a4]} sceNp TODO: sceNpManagerGetNetworkTime(pTick=*0xd001e1d0)
U {PPU[0x1000000] Thread (main_thread) [0x011651a4]} cellVoice TODO: cellVoiceInit
U {PPU[0x1000000] Thread (main_thread) [0x00cd8d98]} cellVoice TODO: cellVoiceCreateNotifyEventQueue
U {PPU[0x1000000] Thread (main_thread) [0x00cd8bd8]} cellVoice TODO: cellVoiceSetNotifyEventQueue
U {PPU[0x1000000] Thread (main_thread) [0x00cd8c48]} cellVoice TODO: cellVoiceCreatePort
U {PPU[0x1000000] Thread (main_thread) [0x00cd8c10]} cellVoice TODO: cellVoiceCreatePort x2
U {PPU[0x1000000] Thread (main_thread) [0x00cd8c10]} cellVoice TODO: cellVoiceConnectIPortToOPort
U {PPU[0x1000000] Thread (main_thread) [0x011651a4]} sceNp TODO: sceNpCustomMenuRegisterActions
U {PPU[0x1000000] Thread (main_thread) [0x00cd7710]} sceNp TODO: sceNpCustomMenuActionSetActivation
S HLE: XInput device 0 reconnected
E {PPU[0x1000000] Thread (main_thread) [0x00719028]} 'sys_event_queue_receive' failed with 0x80010005 : CELL_ESRCH [1]
S {Audio Thread} XAudio 2.9 initialized
U {SPU[0x2000002] Thread (xf_sound_CellSpursKernel0) [0x05f80]} SPU TODO: [0x5fb4] Unexpected instruction on $SP: SELB
E {PPU[0x1000000] Thread (main_thread) [0x00719028]} 'sys_event_queue_receive' failed with 0x80010005 : CELL_ESRCH [2]
E {PPU[0x1000000] Thread (main_thread) [0x00719028]} 'sys_event_queue_receive' failed with 0x80010005 : CELL_ESRCH [3]
S {rsx::thread} RSX: New program compiled successfully x7
E {rsx::thread} RSX: nv406e::semaphore_acquire has timed out. semaphore_address=0x40300480
E {PPU[0x100001e] Thread (checkGdata) [0x01231ee4]} 'sys_fs_stat' failed with 0x80010006 : CELL_ENOENT, “/dev_hdd0/game/BLUS30787/USRDIR/PS3ContentFile/contentsico.bin” [1]
E {PPU[0x100001e] Thread (checkGdata) [0x01231ee4]} 'sys_fs_stat' failed with 0x80010006 : CELL_ENOENT, “/dev_hdd0/game/BLUS30787/USRDIR/PS3ContentFile/contents00.bin” [1]
E {PPU[0x100001e] Thread (checkGdata) [0x01231ee4]} 'sys_fs_stat' failed with 0x80010006 : CELL_ENOENT, “/dev_hdd0/game/BLUS30787/USRDIR/PS3ContentFile/contents01.bin” [1]
E {PPU[0x100001e] Thread (checkGdata) [0x01231ee4]} 'sys_fs_stat' failed with 0x80010006 : CELL_ENOENT, “/dev_hdd0/game/BLUS30787/USRDIR/PS3ContentFile/contents02.bin” [1]
E {PPU[0x100001e] Thread (checkGdata) [0x01231ee4]} 'sys_fs_stat' failed with 0x80010006 : CELL_ENOENT, “/dev_hdd0/game/BLUS30787/USRDIR/PS3ContentFile/contents03.bin” [1]
E {PPU[0x100001e] Thread (checkGdata) [0x01231ee4]} 'sys_fs_stat' failed with 0x80010006 : CELL_ENOENT, “/dev_hdd0/game/BLUS30787/USRDIR/PS3ContentFile/contents04.bin” [1]
E {PPU[0x100001e] Thread (checkGdata) [0x01231ee4]} 'sys_fs_stat' failed with 0x80010006 : CELL_ENOENT, “/dev_hdd0/game/BLUS30787/USRDIR/PS3ContentFile/contents05.bin” [1]
E {PPU[0x100001e] Thread (checkGdata) [0x01231ee4]} 'sys_fs_stat' failed with 0x80010006 : CELL_ENOENT, “/dev_hdd0/game/BLUS30787/USRDIR/PS3ContentFile/contents06.bin” [1]
E {PPU[0x100001e] Thread (checkGdata) [0x01231ee4]} 'sys_fs_stat' failed with 0x80010006 : CELL_ENOENT, “/dev_hdd0/game/BLUS30787/USRDIR/PS3ContentFile/contents07.bin” [1]
E {PPU[0x100001e] Thread (checkGdata) [0x01231ee4]} 'sys_fs_stat' failed with 0x80010006 : CELL_ENOENT, “/dev_hdd0/game/BLUS30787/USRDIR/PS3ContentFile/contents08.bin” [1]
E {PPU[0x100001e] Thread (checkGdata) [0x01231ee4]} 'sys_fs_stat' failed with 0x80010006 : CELL_ENOENT, “/dev_hdd0/game/BLUS30787/USRDIR/PS3ContentFile/contents09.bin” [1]
E {PPU[0x100001e] Thread (checkGdata) [0x01231ee4]} 'sys_fs_stat' failed with 0x80010006 : CELL_ENOENT, “/dev_hdd0/game/BLUS30787/USRDIR/PS3ContentFile/contents10.bin” [1]
E {PPU[0x100001e] Thread (checkGdata) [0x01231ee4]} 'sys_fs_stat' failed with 0x80010006 : CELL_ENOENT, “/dev_hdd0/game/BLUS30787/USRDIR/PS3ContentFile/contents11.bin” [1]
E {PPU[0x100001e] Thread (checkGdata) [0x01231ee4]} 'sys_fs_stat' failed with 0x80010006 : CELL_ENOENT, “/dev_hdd0/game/BLUS30787/USRDIR/PS3ContentFile/contents12.bin” [1]
E {PPU[0x100001e] Thread (checkGdata) [0x01231ee4]} 'sys_fs_stat' failed with 0x80010006 : CELL_ENOENT, “/dev_hdd0/game/BLUS30787/USRDIR/PS3ContentFile/contents13.bin” [1]
E {PPU[0x1000020] Thread (sddlib::npTrophyInst_thread) [0x0071a478]} sceNpTrophy: sceNpTrophyRegisterContext(context=0x1, handle=0x1, statusCb=*0xf84c18, arg=*0x2d16a470, options=0x0)
E {PPU[0x100000e] Thread (Resource Loader) [0x01231ee4]} 'sys_fs_stat' failed with 0x80010006 : CELL_ENOENT, “/dev_hdd0/game/BLUS30787/USRDIR/nativePS3/boot/0000.arc” [1]
E {PPU[0x100000e] Thread (Resource Loader) [0x01231ee4]} 'sys_fs_stat' failed with 0x80010006 : CELL_ENOENT, “/dev_hdd0/game/BLUS30787/USRDIR/nativePS3/ui/cmn_ps3.arc” [1]
E {PPU[0x100000e] Thread (Resource Loader) [0x01231ee4]} 'sys_fs_stat' failed with 0x80010006 : CELL_ENOENT, “/dev_hdd0/game/BLUS30787/USRDIR/nativePS3/ui/cmn_msg.arc” [1]
S {rsx::thread} RSX: New program compiled successfully
E {PPU[0x100000e] Thread (Resource Loader) [0x01231ee4]} 'sys_fs_stat' failed with 0x80010006 : CELL_ENOENT, “/dev_hdd0/game/BLUS30787/USRDIR/nativePS3/eft/cmn/0000.arc” [1]
S {rsx::thread} RSX: New program compiled successfully
E {PPU[0x1000102] Thread (sddlib::npTrophyRead_thread) [0x0071a340]} sceNpTrophy: sceNpTrophyGetTrophyUnlockState(context=0x1, handle=0x1, flags=*0x2d16ab2c, count=*0x2d16ab3c)
E {PPU[0x1000000] Thread (main_thread) [0x01231ee4]} 'sys_fs_stat' failed with 0x80010006 : CELL_ENOENT, “/dev_bdvd/PS3_GAME/USRDIR/nativePS3/sa/PS3/Movie.arc” [1]
E {PPU[0x1000000] Thread (main_thread) [0x01231ee4]} 'sys_fs_stat' failed with 0x80010006 : CELL_ENOENT, “/dev_bdvd/PS3_GAME/USRDIR/nativePS3/sa/PS3/Movie.arc” [2]
E {PPU[0x100000e] Thread (Resource Loader) [0x01231ee4]} 'sys_fs_stat' failed with 0x80010006 : CELL_ENOENT, “/dev_hdd0/game/BLUS30787/USRDIR/nativePS3/movie/0000.pam” [1]
E {PPU[0x1000000] Thread (main_thread) [0x01231ee4]} 'sys_fs_stat' failed with 0x80010006 : CELL_ENOENT, “/dev_bdvd/PS3_GAME/USRDIR/nativePS3/sa/PS3/Movie.arc” [3]
S {rsx::thread} RSX: New program compiled successfully x13
E {PPU[0x1000012] Thread (snddrv_stream_preparing_thread) [0x01231ee4]} 'sys_fs_stat' failed with 0x80010006 : CELL_ENOENT, “/dev_hdd0/game/BLUS30787/USRDIR/nativePS3/sound/bgm/source/bgm_gm_035.at3” [1]
S {rsx::thread} RSX: New program compiled successfully x2
E {PPU[0x1000012] Thread (snddrv_stream_preparing_thread) [0x01231ee4]} 'sys_fs_stat' failed with 0x80010006 : CELL_ENOENT, “/dev_hdd0/game/BLUS30787/USRDIR/nativePS3/sound/bgm/source/bgm_gm_036.at3” [1]
S {rsx::thread} RSX: New program compiled successfully
E {PPU[0x100014e] Thread (sddlib::npTrophyRead_thread) [0x00cd90f0]} sceNpTrophy: sceNpTrophyGetTrophyUnlockState(context=0x1, handle=0x1, flags=*0x2d16ab2c, count=*0x2d16ab3c)
S {rsx::thread} RSX: New program compiled successfully x3
E {PPU[0x1000000] Thread (main_thread) [0x01231ee4]} 'sys_fs_stat' failed with 0x80010006 : CELL_ENOENT, “/dev_hdd0/game/BLUS30787/USRDIR/00030000.edat” [1]
E {PPU[0x1000000] Thread (main_thread) [0x01231ee4]} 'sys_fs_stat' failed with 0x80010006 : CELL_ENOENT, “/dev_hdd0/game/BLUS30787/USRDIR/00030001.edat” [1]
E {PPU[0x1000000] Thread (main_thread) [0x01231ee4]} 'sys_fs_stat' failed with 0x80010006 : CELL_ENOENT, “/dev_hdd0/game/BLUS30787/USRDIR/00030002.edat” [1]
E {PPU[0x1000000] Thread (main_thread) [0x01231ee4]} 'sys_fs_stat' failed with 0x80010006 : CELL_ENOENT, “/dev_hdd0/game/BLUS30787/USRDIR/00030003.edat” [1]
E {PPU[0x1000000] Thread (main_thread) [0x01231ee4]} 'sys_fs_stat' failed with 0x80010006 : CELL_ENOENT, “/dev_hdd0/game/BLUS30787/USRDIR/00030004.edat” [1]
E {PPU[0x1000000] Thread (main_thread) [0x01231ee4]} 'sys_fs_stat' failed with 0x80010006 : CELL_ENOENT, “/dev_hdd0/game/BLUS30787/USRDIR/00030011.edat” [1]
E {PPU[0x1000000] Thread (main_thread) [0x01231ee4]} 'sys_fs_stat' failed with 0x80010006 : CELL_ENOENT, “/dev_hdd0/game/BLUS30787/USRDIR/00030006.edat” [1]
E {PPU[0x1000000] Thread (main_thread) [0x01231ee4]} 'sys_fs_stat' failed with 0x80010006 : CELL_ENOENT, “/dev_hdd0/game/BLUS30787/USRDIR/00030007.edat” [1]
E {PPU[0x1000000] Thread (main_thread) [0x01231ee4]} 'sys_fs_stat' failed with 0x80010006 : CELL_ENOENT, “/dev_hdd0/game/BLUS30787/USRDIR/00030008.edat” [1]
E {PPU[0x1000000] Thread (main_thread) [0x01231ee4]} 'sys_fs_stat' failed with 0x80010006 : CELL_ENOENT, “/dev_hdd0/game/BLUS30787/USRDIR/00030009.edat” [1]
E {PPU[0x1000000] Thread (main_thread) [0x01231ee4]} 'sys_fs_stat' failed with 0x80010006 : CELL_ENOENT, “/dev_hdd0/game/BLUS30787/USRDIR/00030012.edat” [1]
E {PPU[0x1000000] Thread (main_thread) [0x01231ee4]} 'sys_fs_stat' failed with 0x80010006 : CELL_ENOENT, “/dev_hdd0/game/BLUS30787/USRDIR/00000000.edat” [1]
E {PPU[0x1000000] Thread (main_thread) [0x01231ee4]} 'sys_fs_stat' failed with 0x80010006 : CELL_ENOENT, “/dev_hdd0/game/BLUS30787/USRDIR/00000000.edat” [2]
S {rsx::thread} RSX: New program compiled successfully x2
E {PPU[0x1000175] Thread (Savedata AutoSave) [0x01231ee4]} 'sys_fs_stat' failed with 0x80010006 : CELL_ENOENT, “/dev_hdd0/game/BLUS30787/USRDIR/PS3ContentFile/SaveIcon/ICON0.PNG” [1]
E {PPU[0x1000175] Thread (Savedata AutoSave) [0x01231ee4]} 'sys_fs_stat' failed with 0x80010006 : CELL_ENOENT, “/dev_hdd1/cache/BLUS30787/PS3ContentFile/SaveIcon/ICON0.PNG” [1]
E {PPU[0x1000175] Thread (Savedata AutoSave) [0x01231ee4]} 'sys_fs_stat' failed with 0x80010006 : CELL_ENOENT, “/dev_hdd0/game/BLUS30787/USRDIR/PS3ContentFile/SaveIcon/PIC1.PNG” [1]
E {PPU[0x1000175] Thread (Savedata AutoSave) [0x01231ee4]} 'sys_fs_stat' failed with 0x80010006 : CELL_ENOENT, “/dev_hdd1/cache/BLUS30787/PS3ContentFile/SaveIcon/PIC1.PNG” [1]
S {rsx::thread} RSX: New program compiled successfully x4
E {PPU[0x1000012] Thread (snddrv_stream_preparing_thread) [0x01231ee4]} 'sys_fs_stat' failed with 0x80010006 : CELL_ENOENT, “/dev_hdd0/game/BLUS30787/USRDIR/nativePS3/sound/bgm/source/bgm_gm_030.at3” [1]
S {rsx::thread} RSX: New program compiled successfully x22
E {PPU[0x1000012] Thread (snddrv_stream_preparing_thread) [0x01231ee4]} 'sys_fs_stat' failed with 0x80010006 : CELL_ENOENT, “/dev_hdd0/game/BLUS30787/USRDIR/nativePS3/sound/bgm/source/bgm_gm_032.at3” [1]
E {PPU[0x1000012] Thread (snddrv_stream_preparing_thread) [0x01231ee4]} 'sys_fs_stat' failed with 0x80010006 : CELL_ENOENT, “/dev_hdd0/game/BLUS30787/USRDIR/nativePS3/sound/live/nar_live/source/na1_176e.at3” [1]
S {rsx::thread} RSX: New program compiled successfully x4
E {PPU[0x1000012] Thread (snddrv_stream_preparing_thread) [0x01231ee4]} 'sys_fs_stat' failed with 0x80010006 : CELL_ENOENT, “/dev_hdd0/game/BLUS30787/USRDIR/nativePS3/sound/bgm/source/bgm_cr_037.at3” [1]
E {PPU[0x1000012] Thread (snddrv_stream_preparing_thread) [0x01231ee4]} 'sys_fs_stat' failed with 0x80010006 : CELL_ENOENT, “/dev_hdd0/game/BLUS30787/USRDIR/nativePS3/sound/event/art/source/art_038e.at3” [1]
S {rsx::thread} RSX: New program compiled successfully
E {PPU[0x1000012] Thread (snddrv_stream_preparing_thread) [0x01231ee4]} 'sys_fs_stat' failed with 0x80010006 : CELL_ENOENT, “/dev_hdd0/game/BLUS30787/USRDIR/nativePS3/sound/event/sto/source/sto_038e_pu.at3” [1]
S {rsx::thread} RSX: New program compiled successfully x154
E {rsx::thread} RSX: Invalid FIFO queue get/put registers found, get=0xC34CA4DC, put=0x8FC14 x4
E {rsx::thread} RSX: Application has failed to recover, resetting FIFO queue
S {rsx::thread} RSX: New program compiled successfully x43
E {rsx::thread} RSX: Invalid RSX method 0xfffc (arg=0xffff3200)
(in file Emu\RSX\rsx_methods.cpp:46)
E {rsx::thread} RSX: FIFO contents may be corrupted. Resetting...
S {rsx::thread} RSX: New program compiled successfully x21
E {rsx::thread} RSX: Invalid RSX method 0xb300 (arg=0xe8ba2900)
(in file Emu\RSX\rsx_methods.cpp:46)
E {rsx::thread} RSX: Invalid RSX method 0xfc (arg=0x93939300)
(in file Emu\RSX\rsx_methods.cpp:46)
E {rsx::thread} RSX: FIFO contents may be corrupted. Resetting...
S {rsx::thread} RSX: New program compiled successfully x5
E {rsx::thread} RSX: Invalid FIFO queue get/put registers found, get=0x442B9334, put=0xBA834 x4
E {rsx::thread} RSX: Application has failed to recover, resetting FIFO queue
S {rsx::thread} RSX: New program compiled successfully x5
E {PPU[0x1000012] Thread (snddrv_stream_preparing_thread) [0x01231ee4]} 'sys_fs_stat' failed with 0x80010006 : CELL_ENOENT, “/dev_hdd0/game/BLUS30787/USRDIR/nativePS3/sound/bgm/source/bgm_cr_043.at3” [1]
S {rsx::thread} RSX: New program compiled successfully x32
E {rsx::thread} RSX: Invalid RSX method 0x665c (arg=0xbd880000)
(in file Emu\RSX\rsx_methods.cpp:46)
E {rsx::thread} RSX: Invalid RSX method 0xd40 (arg=0x3db01a95)
(in file Emu\RSX\rsx_methods.cpp:46)
E {rsx::thread} RSX: FIFO contents may be corrupted. Resetting...
E {PPU[0x1000012] Thread (snddrv_stream_preparing_thread) [0x01231ee4]} 'sys_fs_stat' failed with 0x80010006 : CELL_ENOENT, “/dev_hdd0/game/BLUS30787/USRDIR/nativePS3/sound/event/drd/source/doo_049e_pu.at3” [1]
E {PPU[0x1000012] Thread (snddrv_stream_preparing_thread) [0x01231ee4]} 'sys_fs_stat' failed with 0x80010006 : CELL_ENOENT, “/dev_hdd0/game/BLUS30787/USRDIR/nativePS3/sound/bgm/source/bgm_gm_033.at3” [1]
S {rsx::thread} RSX: New program compiled successfully x10
E {rsx::thread} RSX: nv406e::semaphore_acquire has timed out. semaphore_address=0x40300480
E {PPU[0x1000000] Thread (main_thread) [0x011654ec]} Stat: '_sys_lwmutex_lock' failed with 0x80010005 : CELL_ESRCH [x27]
E {PPU[0x1000000] Thread (main_thread) [0x011654ec]} Stat: '_sys_prx_get_module_id_by_name' failed with 0x8001112e : CELL_PRX_ERROR_UNKNOWN_MODULE [x5]
E {PPU[0x1000000] Thread (main_thread) [0x011654ec]} Stat: 'sys_event_queue_receive' failed with 0x80010005 : CELL_ESRCH [x12285]
E {PPU[0x1000000] Thread (main_thread) [0x011654ec]} Stat: 'sys_fs_stat' failed with 0x80010006 : CELL_ENOENT, “/dev_bdvd/PS3_GAME/USRDIR/nativePS3/sa/PS3/Movie.arc” [x4]
E CFG: cfg::try_to_enum_value('false'): invalid enum value: invalid stoull argument

[RPCS3.zip](https://github.com/RPCS3/rpcs3/files/2208961/RPCS3.zip)

**Comment by elad335** [comment] 2018-07-19 08:08
duplicate of #2359

**Comment by Augusto7743** [comment] 2018-07-19 08:15
Thanks for share the link https://github.com/RPCS3/rpcs3/issues/2359
The issues in my post are recent and few times not crashes being possible finish the game.

**Comment by toccata10** [comment] 2018-09-23 10:58
Those issues are fixed in recent builds (ex: rpcs3-v0.0.5-7377-b7e010bb_linux64)
Excepted from a thin silver line on vulkan #5164, it seems playable now (i7 8700k, r9 fury, archlinux)

**Comment by AniLeo** [comment] 2019-01-09 01:41
Closing as superseded by #5164

**Closed by AniLeo** 2019-01-09 01:41 UTC
