### ISSUE TITLE
RPCS3 0.0.5-7275-85fa0942 Alpha Broke all the games with trophy setting

### ISSUE THREAD

**Issue by XemnasBlood** [RPCS3/rpcs3#5062] opened 2018-08-30 19:42 UTC
so before updating to the latest version of RPCS3 i was able to play KH2.5HD Flawlessly
after updating the game started freezing on the startup screen 

i have also attached the log 
[RPCS3.log](https://github.com/RPCS3/rpcs3/files/2337679/RPCS3.log)

i found out that the error is from the PPU, i tried using LLVM, both interpreter, none worked around, searched around the web for similar issues and they were all for odin sphere, and was solved using a code to bypass the whole thing, also read in one of the forum posts that using the emulator is so quick for the game, and the suggestion was to use cheat engine and use the speed hack, still no luck!

EDIT ---
Im using the default configuration for the whole RPCS3, tried using Vulkan and OpenGL 
Spec:
Core I7-7800
16GB Ram
GTX 1080

**Comment by AniLeo** [comment] 2018-08-30 19:55
> all the games with trophy setting
> KH2.5HD

Which one is it?

Also, did you make sure it was #5041 regressing it as in did you test the previous build?

**Comment by LuismaSP89** [comment] 2018-08-30 20:28
Can confirm the issue (Happens too with Guilty Gear XRD rev2) but the problem is not with #5041... is with #4871

**Comment by spyropt** [comment] 2018-08-30 20:30
Tekken 6 and Tekken tag suffer from the same #4871

**Comment by AniLeo** [comment] 2018-08-30 20:46
Closing as false report then, there is already one regression issue opened for #4871

**Closed by AniLeo** 2018-08-30 20:46 UTC
