### ISSUE TITLE
Metal Gear Solid Peace Walker HD [NPEB00686] stuck on first loading screen when using LLVM.

### ISSUE THREAD

**Issue by ConnorDY** [RPCS3/rpcs3#3268] opened 2017-08-19 03:32 UTC
The game runs fairly well under Interpreter (Fast) but under LLVM the first loading screen for the game loops forever. Below is my log file. Prior to the merging of KD-11's vertex rewrite, all that was displayed was a 60FPS black screen. The loading screen renders fine now. I believe this game will run exceptionally well if LLVM can be fixed for it.

[RPCS3.log.txt](https://github.com/RPCS3/rpcs3/files/1236034/RPCS3.log.txt)

**Comment by al0xf** [comment] 2017-08-21 00:31
For the record the relevant error is:

`·E 0:02:52.714941 {PPU[0x1000000] Thread (main_thread) [0x00c83160]} PPU: Unregistered function called (LR=0xc4b644)`

**Comment by ConnorDY** [comment] 2017-08-22 06:05
That error occurs once under Interpreter (Fast) as well. This part however loops endlessly under LLVM:

`sys_rsx_context_attribute(context_id=0x55555555, package_id=0x10a, a3=0x1, a4=0x7fffffff, a5=0x0, a6=0x0)`
`·W 0:00:44.356611 {rsx::thread} RSX: NV4097_GET_REPORT: Unimplemented type 1`
`·W 0:00:44.356708 {rsx::thread} RSX: NV4097_GET_REPORT: Unimplemented type 1`
`·W 0:00:44.357011 {PPU[0x1000009] Thread (InitialDrawThread) [0x01c26bb4]} sys_rsx:`

**Comment by AniLeo** [comment] 2017-09-04 14:24
Please use #2909 for LLVM specific issues.

Game throws exception when there's an unregistered function on LLVM, but logs an error and progresses with Interpreter. 

Is this still an issue? I recently pushed a commit that fixed several games with the Unregistered Function issue.

**Comment by ConnorDY** [comment] 2017-09-04 17:13
That commit hasn't fixed the issue.

**Comment by Zangetsu38** [comment] 2017-09-04 17:20
i have this in llvm
>E {PPU[0x1000000] Thread (main_thread) [0x01bdef78]} PPU: Unregistered function called (LR=0xc4b644)
F {PPU[0x1000000] Thread (main_thread) [0x01bdef78]} MEM: Access violation reading location 0x57c

litttle same error AMY and more

**Comment by ConnorDY** [comment] 2017-09-04 17:24
Here's my full log file if it helps.

[RPCS3.log.gz](https://github.com/RPCS3/rpcs3/files/1275266/RPCS3.log.gz)

**Comment by AniLeo** [comment] 2017-09-04 17:26
·W 0:00:00.000000 Experimental Build Warning! Build origin: RPCS3/rpcs3/master/=3329

Always test in master. In this case it doesn't matter as it doesn't touch PPU stuff, otherwise it would be invalidated

**Comment by AniLeo** [comment] 2018-03-09 15:20
This is being tracked on #2909, it's an issue that affects several games.
Closing as duplicate of #2909.

**Closed by AniLeo** 2018-03-09 15:20 UTC
