### ISSUE TITLE
CPU Crash Error Before Game Startup

### ISSUE THREAD

**Issue by WizardlyWords** [RPCS3/rpcs3#10428] opened 2021-06-08 21:48 UTC
## Quick summary
While playing a variety of Collection Games, just after the Company Logos, my game always crashes.

## Details
This started with the God of War Collection, but now happens with Metal Gear Solid Collection, Kingdom Hearts 1.5 and 2.5, and God of War Origins. What happens is I load the game, it sets the PPUs, it gets through the initial logos for the team, then it produces a fatal error and immediately crashes out of the game, reference a drive folder my External is used for. I have attached an image of the error below, as well as a link to my log. The latest problem occurs right at the end.

I made sure to alter nothing when I did this, as I wanted to ensure the games worked first. This, if it is not obvious, is my first time using RPCS3. I was able to get all else working except for actually running the game.

This also sounds like its a CPU problem, but I'm not sure how it even is. If I am just setting it up wrong, I apologize, but I've tried reinstalling it and rerunning it and this continues to persist.

[RPCS3's log](https://file.io/JcVldKx4l0EG)

My failure here
![image](https://i.ibb.co/7nNVYwW/Load-Failure.png)

system configuration:
* OS = Windows 10
* CPU = 11th gen Intel i7-7700KF 3.6GHz
* GPU = NVIDIA Geforce RTX 2060
* RAM = 16GB

**Comment by Megamouse** [comment] 2021-06-08 21:49
duplicate of #10424

**Closed by Megamouse** 2021-06-08 21:49 UTC
