### ISSUE TITLE
Settings window changes its size after switching to CPU tab

### ISSUE THREAD

**Issue by TotalCaesar659** [RPCS3/rpcs3#4725] opened 2018-06-08 21:36 UTC
![1](https://user-images.githubusercontent.com/14265316/41182124-089b6754-6b7d-11e8-82de-069ec9cb1fa9.png)
![2](https://user-images.githubusercontent.com/14265316/41182126-0c138966-6b7d-11e8-8703-a9dab87be590.png)

**Comment by AniLeo** [comment] 2018-06-08 21:41
Yes, because it has content that requires it to do so..

**Comment by Megamouse** [comment] 2018-06-09 08:36
I didnt have it on hidpi last time i checked. But the issue is known and i technically worked around this already. (Always show the biggest tab once before going to the correct one)

I dont know what changed. I will look at it

**Comment by Megamouse** [comment] 2018-06-16 13:18
For now I tracked it down to the initial tab index.
I'll simply have it set the currentIndex to 0 manually.

The reason why this seems to be an issue at times and then sometimes not is that as soon as someone changes anything in the settings_dialog.ui file, they often commit the change of said index too, leading to this behaviour.

I'm not sure how we can work around this problem properly

**Comment by AniLeo** [comment] 2018-06-22 18:41
Fixed via #4760 

If you can reproduce on latest builds, you can ping for the issue to be reopened

**Closed by AniLeo** 2018-06-22 18:41 UTC
