### ISSUE TITLE
RPCS3 Windows Are Massive

### ISSUE THREAD

**Issue by Enverex** [RPCS3/rpcs3#5820] opened 2019-04-11 14:00 UTC
This has been going on for some time now (months, at a guess) and I gave up trying to figure out what the problem was, but I thought I should revisit it now and at least report it.

The RPCS3 window, and any child windows, open as incredibly massive windows and don't display properly at all. Here's a screenshot of the 1080p display:
![image](https://user-images.githubusercontent.com/958670/55963035-f304a480-5c69-11e9-810d-73b0e73215ab.png)

An xprop analysis on the window shows the following:
```
WM_STATE(WM_STATE):
		window state: Normal
		icon window: 0x0
_NET_WM_DESKTOP(CARDINAL) = 0
_NET_WM_ALLOWED_ACTIONS(ATOM) = _NET_WM_ACTION_CHANGE_DESKTOP, _NET_WM_ACTION_SHADE, _NET_WM_ACTION_CLOSE, _NET_WM_ACTION_MOVE, _NET_WM_ACTION_MINIMIZE, _NET_WM_ACTION_FULLSCREEN, _NET_WM_ACTION_ABOVE, _NET_WM_ACTION_BELOW, _OB_WM_ACTION_UNDECORATE
_KDE_NET_WM_FRAME_STRUT(CARDINAL) = 1, 1, 26, 1
_NET_FRAME_EXTENTS(CARDINAL) = 1, 1, 26, 1
_OB_APP_TYPE(UTF8_STRING) = "normal"
_OB_APP_TITLE(UTF8_STRING) = "Welcome to RPCS3"
_OB_APP_GROUP_CLASS(UTF8_STRING) = 
_OB_APP_GROUP_NAME(UTF8_STRING) = 
_OB_APP_CLASS(UTF8_STRING) = "RPCS3"
_OB_APP_NAME(UTF8_STRING) = "rpcs3"
_OB_APP_ROLE(UTF8_STRING) = 
_NET_WM_VISIBLE_ICON_NAME(UTF8_STRING) = "Welcome to RPCS3"
_NET_WM_VISIBLE_NAME(UTF8_STRING) = "Welcome to RPCS3"
_NET_WM_USER_TIME(CARDINAL) = 108202401
_NET_WM_STATE(ATOM) = _NET_WM_STATE_MODAL
_NET_WM_ICON_NAME(UTF8_STRING) = 
_NET_WM_ICON(CARDINAL) = 
XdndAware(ATOM) = BITMAP
WM_NAME(STRING) = "Welcome to RPCS3"
_NET_WM_NAME(UTF8_STRING) = "Welcome to RPCS3"
_MOTIF_WM_HINTS(_MOTIF_WM_HINTS) = 0x7, 0x4, 0x1a, 0x3, 0x0
_NET_WM_WINDOW_TYPE(ATOM) = _NET_WM_WINDOW_TYPE_NORMAL
_XEMBED_INFO(_XEMBED_INFO) = 0x0, 0x1
WM_CLIENT_LEADER(WINDOW): window id # 0x1400007
WM_HINTS(WM_HINTS):
		Client accepts input or input focus: True
		Initial state is Normal State.
_NET_WM_PID(CARDINAL) = 4512
_NET_WM_SYNC_REQUEST_COUNTER(CARDINAL) = 20971534
WM_CLASS(STRING) = "rpcs3", "RPCS3"
WM_PROTOCOLS(ATOM): protocols  WM_DELETE_WINDOW, WM_TAKE_FOCUS, _NET_WM_PING, _NET_WM_SYNC_REQUEST
WM_NORMAL_HINTS(WM_SIZE_HINTS):
		user specified size: 67332 by 25916
		program specified minimum size: 16383 by 16383
		program specified maximum size: 16383 by 16383
		program specified resize increment: 124 by 124
		program specified base size: 0 by 0
		window gravity: Static
```

The key part here being **program specified minimum size: 16383 by 16383**. Essentially it's opening as a window, AT LEAST 16k x 16k which is insanely large.

No other programs appear to do this (QT or otherwise). I've tried both my compiled RPCS3 install and the AppImage with the same result.

_System:_
Arch Linux.
Openbox window manager.
Xorg 1.20.4.

It's almost as though QT is scaling it up to some insane value for some reason. To try and counter this, I've specified the following:
```
QT_AUTO_SCREEN_SCALE_FACTOR=0
QT_SCALE_FACTOR=0
QT_SCREEN_SCALE_FACTOR=0
QT_LOGGING_RULES=*=false
```

... but it doesn't seem to have helped.

**Comment by MSuih** [comment] 2019-04-11 14:02
Duplicate of #5455 I guess. Qt HiDPI scaling is a mess and the commit which enabled it might be reverted in future.

**Comment by Enverex** [comment] 2019-04-11 14:07
Should that still trigger on a "normal" DPI display though? (DPI is the default which I believe is 90).

**Comment by ruipin** [comment] 2019-04-11 14:12
Try setting the factors to `1` instead of `0`, since `0` is illegal.
Otherwise, try updating Qt.

**Comment by Enverex** [comment] 2019-04-11 14:22
Qt is already version 5.12 which AFAIK is up to date and the source version was rebuilt/linked a few days ago at most. Linking shouldn't batter because it happens with the AppImage too. I've tried both 1 and 0 with no change in behaviour. If I try a silly value like 0.1 I actually get something resembling the interface...

![image](https://user-images.githubusercontent.com/958670/55964945-825f8700-5c6d-11e9-9e9a-b4080d2cf0ed.png)

But going any lower (e.g. 0.05) results in a "Floating point exception (core dumped)".

**Comment by kd-11** [comment] 2019-04-11 16:09
`user specified size: 67332 by 25916` is also quite interesting. There is nothing special about how rpcs3 creates its windows though, so I suspect its something to do with Qt and the specific system in question (otherwise we'd have tons of reports like these). There is likely nothing any of us can do about this unfortunately, unless more users with the same problem come forward so we can compare what they all have in common. Did you try building rpcs3 from source to see if its an issue with the prepackaged appimage?

**Comment by Enverex** [comment] 2019-04-11 17:39
Yes (I thought I put that in the original report but maybe not). I normally build from source so that's what I checked first. I then tried the AppImage. Both do exactly the same thing.

**Comment by Hirato** [comment] 2019-04-14 06:13
What is the output of running `export | grep '^QT'`? - it kind of sounds like you've got some crazy scale factor set up - like 10x or so.

**Comment by Johndeep** [comment] 2019-04-28 09:55
Oh, here, I also have this issue since long ago, like how even the controller configuration window does not even fit into a FullHD screen, because of doubled sized (I think) elements (while font size stays small in comparison).
![Bildschirmfoto_2019-04-28_11-48-56](https://user-images.githubusercontent.com/306953/56862477-aaf4ba00-69ab-11e9-93f9-81f6834f29ce.png)
The window is original sized here (bottom is being cut off a little bit, because the window didn't fit entirely for screenshot).
And because of this scaling issue, I highly presume that the failing
`E {RSX [0x0001a20]} RSX: Swapchain: Swapchain creation failed because dimensions cannot fit. Max = 1920, 1023, Requested = 1920, 1024`
is caused by this very scaling problem during (every) gameplay (regardless if OpenGL or Vulkan).

**Comment by Enverex** [comment] 2019-05-14 14:44
@Hirato Sorry, didn't see your reply. No variables for QT set. I have in the past tried with them all set to "1" to imply no scaling, but that didn't help either (no change in behaviour).

**Comment by Hirato** [comment] 2019-05-14 23:56
You should probably find out why your environment isn't setting any.
My output for reference is:

```
QT_AUTO_SCREEN_SCALE_FACTOR=0
QT_SCREEN_SCALE_FACTORS='DisplayPort-0=1;DisplayPort-1=1;DVI-D-0=1;'
```

**Comment by Enverex** [comment] 2019-05-15 00:06
It doesn't matter because RPCS3 overrides them (or at least the one that matters). Setting QT_AUTO_SCREEN_SCALE_FACTOR and the others doesn't really do anything (or at least can't fix it). RPCS3 for sets "QT_AUTO_SCREEN_SCALE_FACTOR" to 1 regardless what it's currently set to, and that's the issue.

**Comment by Johndeep** [comment] 2019-05-15 12:01
Thanks to #5963 pr (thanks to z0z0z), at least I or maybe even we can finally (at least) use
`env QT_AUTO_SCREEN_SCALE_FACTOR=0`
to have properly scaled window again.

Still, the qt5.10 problem remains. Since this is more of a workaround for some of us (seems that in my case xfce is not quite happy with activated auto_scale option of qt5.10), the long term solution would be to upgrade qt to 5.11+ or even above (the version without the bug).

**Comment by Enverex** [comment] 2019-05-15 14:29
Cheers @Johndeep and @z0z0z - that should fix it for me (or at least work around it in a more official manner).

**Comment by Megamouse** [comment] 2019-10-22 19:48
Appimages should now run on qt 5.12.3.
Please retest.

**Comment by Johndeep** [comment] 2019-10-23 09:49
I can confirm that a cold start (in this case, start without any parameter, (pre-)configurations, caches or whatever) with version 0.0.7-8981, qt used is version 5.12.3 and scaling has no issues (at least on Debian testing). No need for environment parameter anymore. Nice!

**Comment by Megamouse** [comment] 2019-10-23 11:41
I'll close this in favor of the last comment

**Closed by Megamouse** 2019-10-23 11:41 UTC
Labels: GUI

**Comment by dragonDScript** [comment] 2022-04-22 17:58
No practical issues but it looks worse than the rest of apps that use Win32, or other GUI technologies. On latest commit as of now

**Comment by z0z0z** [comment] 2022-04-22 18:39
> No practical issues but it looks worse than the rest of apps that use Win32, or other GUI technologies. On latest commit as of now

So the actual complaint here is against Qt? RPCS3 has built-in Qt themes if you'd like to check them out.
