### ISSUE TITLE
Performance regression (?) in [NPEB02436]; Vulkan AMD driver crash

### ISSUE THREAD

**Issue by TheRibbit** [RPCS3/rpcs3#4313] opened 2018-03-21 19:05 UTC
Seems like this problem is pretty much limited to my configuration, because I haven't seen any issues or reports from others (well there's actually one lonely message at #4079 pull (which is 6343, see below) and it's somewhat similar to the issue #4301), but still.
All tests with Recompiler (SPU and PPU). Always cleared shaders cache and for some tests (not in the logs) also LLVM.

rpcs3-v0.0.4-2018-01-17-34c49c77_win64 - 6333 - latest working-as-intended build (both vulkan and openGL), no crashes, good fps.
rpcs3-v0.0.4-2018-01-17-71f69d1d_win64 - 6334 - first problems with Vulkan (still okay fps, but driver crashes very early - on intro or a few seconds in-game, so it's unplayable); openGL is alright.
rpcs3-v0.0.4-2018-01-18-54fbde0d_win64 - 6338 - latest build with good fps on both renderers; vulkan (amd driver) still crashes
rpcs3-v0.0.4-2018-01-19-6828fbf6_win64 - 6343 - first build with bad fps on both renderers (!); vulkan (amd driver) crashes; thread scheduler on/off doesn't matter, gpu texture scaling doesn't matter; preferred SPU threads doesn't matter, framelimit off, native user interface on/off doesn't matter.
rpcs3-v0.0.5-6550-252ddf80_win64 - 6550 - latest logged build (also caught in logs proper API Vulkan error); still bad fps on both renderers and AMD GPU driver crash on vulkan, all things mentioned above still don't matter.
6553 - latest build - the same situation, not logged though, tested just now.

https://mega.nz/#F!EZlEgY4I!Vntdj5yY939bahSgqdnBPg - logs (with renderer and version names)
https://www.youtube.com/playlist?list=PLTaSzGdtfYGFGtv4ekrFsLicMGZAqHN8i - videos (with renderer and version names)

P5 [NPEB02436]

My PC configuration:
Windows 7 x64 SP1; i5-4670k overclocked 4300MHz; 16GB DDR3 RAM; GPU AMD Radeon R7-260X 2GB; GPU drivers 18.3.3.

I couldn't post this on forums because of [P5], but I still see some mentions about it on Github, so I figured I'd like to give it a try. Sorry for any inconvenience caused. Once again, sorry if it's inappropriate place.

**Comment by useresuser** [comment] 2018-03-25 20:09
I'm having crashes on Demon's Souls and God Of War Collection only on vulkan after one minute or two, this did not happen in older builds.

270X 2GB drivers 18.2.1 WHQL

**Comment by kd-11** [comment] 2018-03-26 08:49
Retest with https://ci.appveyor.com/project/kd-11/rpcs3/build/artifacts. There seems to be a rather serious driver bug on older GCNs. For some reason, my 270X does not crash but other users with 280X can reproduce.

**Comment by kd-11** [comment] 2018-03-26 08:54
As for performance issues, that is unique to your setup @TheRibbit. Performance has not changed at all for me, all radeon settings left at stock, no rpcs3 profile.

**Comment by TheRibbit** [comment] 2018-03-26 09:57
Yep, on v0.0.0.6-6593-a5e6fc4e there is no crash. Still bad performance for me, sadly.
I also tested Demon's Souls - it crashed on 6590, but on 6593-a5e6fc4e it's also alright.

Just in case, here are logs.
[RPCS3-6593-kd11-P5.zip](https://github.com/RPCS3/rpcs3/files/1847247/RPCS3-6593-kd11-P5.zip)
[RPCS3-6590-DS.zip](https://github.com/RPCS3/rpcs3/files/1847248/RPCS3-6590-DS.zip)

I actually noticed this issue (#4166) just now. Seems like I made a duplicate (except for my specific performance issue), oops..

**Comment by kd-11** [comment] 2018-03-26 11:55
https://github.com/RPCS3/rpcs3/pull/4344

**Comment by kd-11** [comment] 2018-03-28 09:17
Closing as the crashing is fixed via https://github.com/RPCS3/rpcs3/pull/4344. For the performance issues, its better to get assistance on discord as it is limited to your specific setup. https://discord.me/RPCS3

**Closed by kd-11** 2018-03-28 09:17 UTC

**Comment by kd-11** [comment] 2018-03-28 09:20
Actually I just had a quick look at the new log and noticed this
```
  Preferred SPU Threads: 1
  SPU delay penalty: 0
```
Do not touch the delay penalty. Leave it at 3 if you intend to limit SPU thread performance. A value of 0 will not help much if the emulator are starved for cores. This behavior was slightly changed in the version you identified.

**Comment by TheRibbit** [comment] 2018-04-09 16:44
@kd-11 
Just wanted to say that I feel a bit ashamed and stupid. Exactly that was the root of my problem. Setting it to default fixed everything. I thought that I already have tried resetting the configuration, but, well, I actually did reset only the game configuration and not global.
Thanks for that.
