### ISSUE TITLE
Ni no Kuni Cutscenes

### ISSUE THREAD

**Issue by Redfry** [RPCS3/rpcs3#3196] opened 2017-08-11 08:22 UTC
Ni no Kuni works perfect but have one big problem,
If i watch a cutscenes until the end, the screen goes black and i cant play anymore, and i must to restart the game
I hope you will fix that, but I still have the patience

**Comment by Megamouse** [comment] 2017-08-11 08:28
duplicate of #2930

**Closed** 2017-08-11 12:21 UTC
