### ISSUE TITLE
Rainbow Moon [NPUB30434] Graphic issues

### ISSUE THREAD

**Issue by relaxfm** [RPCS3/rpcs3#4151] opened 2018-02-06 18:43 UTC
AMD A10, RAM 12G, GTX 1050Ti Win 8.1
0.0.4 6396
Graphic issues
View my character, without head, and weapons.
![rainb opengl](https://user-images.githubusercontent.com/31609899/35877539-a1fd6a52-0b86-11e8-8012-9b8e484ee1c5.jpg)
Graphic issues
![rainb vulkan](https://user-images.githubusercontent.com/31609899/35877530-99c60bbe-0b86-11e8-90db-4c4faa4d0d93.jpg)
[RPCS3.log](https://github.com/RPCS3/rpcs3/files/1700383/RPCS3.log)

**Comment by relaxfm** [comment] 2018-02-06 18:47
AMD A10, RAM 12G, GTX 1050Ti.

**Comment by AniLeo** [comment] 2018-03-16 15:51
Duplicate of #2338

**Closed by AniLeo** 2018-03-16 15:51 UTC
