### ISSUE TITLE
Some troubles with alpha textures on models

### ISSUE THREAD

**Issue by korenkonder** [RPCS3/rpcs3#4172] opened 2018-02-13 17:41 UTC
RPCS3 0.0.4-6422-95c6ac699
CPU: Intel Core i5-4570
GPU: GIGABYTE GTX 960 4 Gb
RAM: 16 Gb

In HMPDDTex (NPJB00201) rpcs3 partially ignores alpha textures which are on models.
RPCS3 screenshots:
(Sorry for gamepad on RPCS3 screenshots)
https://imgur.com/a/rwvwK
https://imgur.com/a/dfhnv
https://imgur.com/a/oWqgb

**Comment by shadowbrony33** [comment] 2018-02-13 18:06
Why are you sending FTP links?

Just re-upload to imgur or directly to github.

**Comment by KujiKita** [comment] 2018-02-13 18:17
@shadowbrony33 Reuploaded

**Comment by shadowbrony33** [comment] 2018-02-13 18:28
It could either be that or a bug the causes the engine to handle some 3D materials incorrectly. Just my guess

**Comment by KujiKita** [comment] 2018-02-28 08:57
Hmmm.... When you don't load PV textures are showing correctly in other menus.

**Comment by Pikota3124** [comment] 2018-09-16 18:28
They have already fixed the Project Diva F and how this thread takes time inactive I will relive it to see if there is luck for the Dreamy Theater.

This troubles are also present on HMPDDT2nd (NPJB00134), I attach some captures.

[https://imgur.com/a/RPyPNbY](url)

**Comment by KujiKita** [comment] 2019-02-11 05:44
1 year pass, but error is still here.

**Comment by digitaldude555** [comment] 2020-02-06 21:24
How about now? @korenkonder

**Comment by korenkonder** [comment] 2020-02-07 11:45
PS3: https://www.youtube.com/watch?v=uGzDKsRyuzo
RPCS3 0.0.8-9525-17df6c88: https://www.youtube.com/watch?v=DMGcvRLojGk

**Comment by Izofeu** [comment] 2020-03-19 17:53
Still a problem on 0.0.9-9954-27367dc4 Alpha

**Comment by kd-11** [comment] 2020-05-05 20:02
I'll need some RSX capture for this problem.

**Comment by Izofeu** [comment] 2020-05-05 20:07
> I'll need some RSX capture for this problem.

I dmed you on DIscord

**Comment by kd-11** [comment] 2020-05-06 20:18
Confirm if fixed by https://github.com/RPCS3/rpcs3/pull/8166

**Comment by Izofeu** [comment] 2020-05-06 22:55
> Confirm if fixed by #8166

While the skirt and other parts are no longer fully yellow, now they have almost no color at all. Her tattoo on left arm isn't visible either.
Screenshots for comparison https://drive.google.com/drive/folders/1hzg9ESn1jgokFPI2uwsMg8UIF_Y1c1JL?usp=sharing

**Comment by kd-11** [comment] 2020-05-07 09:45
Ok, I must have butchered the decode. I'll work on a proper fix.

**Closed** 2020-05-07 21:02 UTC
Labels: Bug, RSX

**Comment by kd-11** [comment] 2020-05-07 21:15
The issue is resolved and fix merged into main builds. I checked it this time, the decals work correctly. I had broken the value decode indeed with the previous build.

**Comment by Izofeu** [comment] 2020-05-07 23:39
> The issue is resolved and fix merged into main builds. I checked it this time, the decals work correctly. I had broken the value decode indeed with the previous build.

Yay! Thank you so much <3

**Comment by AniLeo** [comment] 2020-05-07 23:49
Can you post a screenshot of the fixed render?

**Comment by Izofeu** [comment] 2020-05-07 23:54
![image](https://user-images.githubusercontent.com/60717460/81355416-bbfffd00-90ce-11ea-8cf0-1ded519cd008.png)
