### ISSUE TITLE
[Windows 10] SixAxis's Motion controls not working properly with DsHidMini

### ISSUE THREAD

**Issue by RevyMary** [RPCS3/rpcs3#15414] opened 2024-04-07 13:12 UTC
### Quick summary

I've been trying to get the Camo Shake thingy in MGS4 working for some time and because with DsHidMini the G motion does not move more than 1 number i could never get it working, so when i switched to Official Sony Drivers as a last resort and it worked perfectly

### Attach a log file

[RPCS3.log.gz](https://github.com/RPCS3/rpcs3/files/14897264/RPCS3.log.gz)

### System configuration

Windows 10
i7-6700 @ 3.40GHz  
Radeon RX 570 31.0.21912.14
16GB RAM

**Comment by AniLeo** [comment] 2024-04-07 13:19
Duplicate of #15129.

**Closed by AniLeo** 2024-04-07 13:19 UTC
