### ISSUE TITLE
RPCS3 Unmapped memory issue

### ISSUE THREAD

**Issue by jakeestock** [RPCS3/rpcs3#12410] opened 2022-07-28 14:56 UTC
### Quick summary

I have been trying to play NCAA 14 on the RPCS3 emulator for a year now, up until recently I had never had this problem. Whenever I install RPCS3 and play for 2-3 days it randomly will freeze whenever I try to start the game. It gets all the way to the "press start" screen and freezes whenever a button is pressed. When I uninstall and reinstall it works again for a few days then goes back to freezing. Whenever this happens this error message pops up in the log: F {PPU[0x100001b] Thread (realmemcard_ps3) [0x003acf08]} VM: Access violation reading location 0x1 (unmapped memory)

### Attach a log file

[RPCS3.log.gz](https://github.com/RPCS3/rpcs3/files/9211674/RPCS3.log.gz)

**Comment by MSuih** [comment] 2022-07-28 18:02
The unmapped memory issue seems to be related to corrupted param.sfo in save data. Have you checked if you have corrupted saves and/or tried the game without saves?

If it's a regression then you'll have to find the version which caused this regression

**Comment by Asinin3** [comment] 2023-07-24 16:19
Closing, OP didn't give any further info

**Closed by Asinin3** 2023-07-24 16:19 UTC
