### ISSUE TITLE
J-Stars Victory Freeze after Luffy's strong attack

### ISSUE THREAD

**Issue by LittlePippy** [RPCS3/rpcs3#8273] opened 2020-05-22 15:02 UTC
So I just started J stars and whenever I used luffy's strong attack by pressing X (it doesnt happen when in the first battles with ace, koro-sensei or Seiya, so after that)  the game would hang.

**Comment by AniLeo** [comment] 2020-05-22 17:36
Duplicate of #7858

**Closed by AniLeo** 2020-05-22 17:36 UTC
