### ISSUE TITLE
LLVM SSSE3 CPU Compiling Error

### ISSUE THREAD

**Issue by kajmen33** [RPCS3/rpcs3#2971] opened 2017-07-08 19:33 UTC
![ssse3 error](https://user-images.githubusercontent.com/30007933/27988555-c91b9502-642c-11e7-8162-daafe6cb7946.png)
![cpuz](https://user-images.githubusercontent.com/30007933/27988564-16518002-642d-11e7-801d-572f0630fe99.png)

I dont know why but for some reason it gives this error every time. I reinstalled the emulator and the games and it didnt solve it. I have a Intel G4560 cpu and it does have SSSE3 support. Please help.

**Comment by AniLeo** [comment] 2017-07-08 19:52
Duplicate of #2950

**Closed** 2017-07-08 19:52 UTC
