### ISSUE TITLE
Blood texture issue

### ISSUE THREAD

**Issue by FaraondalekiegoEgiptu** [RPCS3/rpcs3#14548] opened 2023-08-25 12:03 UTC
### Quick summary

When I play UFC Undisputed 3 on RPCS3 i see only cuts and swelling places on face but I don't see blood. 
Blood is only on ground texture and in replays, not while playing. Please, help with that because is that important feature.

### Attach a log file

[RPCS3.log](https://github.com/RPCS3/rpcs3/files/12438879/RPCS3.log)

### System configuration

RTX 3070
i910900F 2,8 Ghz
32 GB RAM

**Comment by cas-1092** [comment] 2023-08-25 12:07
Duplicate of #14163

**Closed** 2023-08-25 12:07 UTC
