### ISSUE TITLE
Tales of Graces F JPN BLJS10093 atrac3 / black screen after certain time (only recompiler)

### ISSUE THREAD

**Issue by amakuramio** [RPCS3/rpcs3#3637] opened 2017-10-22 17:24 UTC
Game plays fine at full speed (openGL, openAL) it does have graphical artifacts.
However, suddenly
Thread (atrac3plusCellSpursKernel0)} MEM: Access violation reading location 0x0
music stops playing and screen goes black.

**Comment by marcussacana** [comment] 2017-10-22 19:35
regression?

**Comment by AniLeo** [comment] 2017-10-22 20:29
Closing anyways since the issue is Invalid.

On top of that, access violations reports by themselves are of no use without further investigation as that's the most generic error there is.

**Closed** 2017-10-22 20:30 UTC
Labels: Meta: Invalid
