### ISSUE TITLE
Gran Turismo 6 BCES01893 crash - Working buffer not big enough

### ISSUE THREAD

**Issue by EmuRace** [RPCS3/rpcs3#7923] opened 2020-04-02 20:09 UTC
Related to #7292, Gran Turismo 6 BCES01893 crash with the follow fault code:

F {RSX [0x19aae90]} SIG: Thread terminated due to fatal error: [index buffer] Working buffer not big enough, buffer_length=16777216 allocated=1083136 requested=4294967290 guard=65536 largest_pool=81048
(in file d:\a\1\s\rpcs3\Emu\RSX\Common\ring_buffer_helper.h:91)

It is in every case reproduceable and I try different settings, but they didn't make any difference.

Reproduce procedure:
1. Enter story mode
2. Switch to Career mode
3. National B
4. Start the first race from FR-Challange
5. Drive the race until end
6. The issue appear when the summary view appears (after the money picture)

Game version: V1.04
Emulator Firmware: V4.85
Logfile:
[RPCS3.zip](https://github.com/RPCS3/rpcs3/files/4423345/RPCS3.zip)

System configuration:
OS: Windows 10 1903
CPU: Intel Core i7-6770k CPU @ 4,2GHz
GPU: GTX 1070Ti (v 445.75)
RAM: 16 GB
RPCS3 Version: 0.0.9-10084

Thanks for support!

**Comment by illusion0001** [comment] 2020-04-03 03:33
Duplicate of #7913

**Comment by AniLeo** [comment] 2020-04-03 03:37
Duplicate of #7913

**Closed by AniLeo** 2020-04-03 03:37 UTC
Labels: RSX
