### ISSUE TITLE
Feat. req. - implement option to turn off logging to disk (*.log, *.gz)

### ISSUE THREAD

**Issue by necros2k7** [RPCS3/rpcs3#5486] opened 2019-01-02 08:26 UTC
subj

**Comment by MSuih** [comment] 2019-01-02 08:31
Pull request #5333 implements this.

**Comment by AniLeo** [comment] 2019-01-02 09:21
Duplicate of #5113

**Closed by AniLeo** 2019-01-02 09:21 UTC

**Comment by eadmaster** [comment] 2023-06-03 21:18
> Pull request #5333 implements this.

https://github.com/RPCS3/rpcs3/pull/5333 only allows to change the verbosity, not disabling the logs on disk, correct?

**Comment by elad335** [comment] 2023-06-04 03:51
It's implemented I do not remember which pull request made it. It's in advanced tab  I think.

**Comment by MSuih** [comment] 2023-06-04 03:57
There are two options:
* Silence logging after game starts
* Raise logging level to fatal so that barely anything gets logged.

There's no way to completely disable logging though so that even the file wouldn't get created.

**Comment by elad335** [comment] 2023-06-04 04:00
I do not think there should be a way to completely disable it on purpose.

**Comment by elad335** [comment] 2023-06-04 04:08
Like if you are really want it for some reason you can mark them as read only files  and rpcs3 won't bother.
