### ISSUE TITLE
Ni No Kuni - Cutscenes can't be watched until the end

### ISSUE THREAD

**Issue by Mogiks** [RPCS3/rpcs3#2930] opened 2017-06-30 16:06 UTC
Hi,

First thank to the team for the work provided on making RPCS3 working it's really appreaciated.
For Ni No Kuni, I saw that the game is finally playable but there is still a major bug : cutscenes.
If we watch a cutscenes until the end, the screen goes black and we cant play anymore.. the start button is still working but has no effect... have to restart the game.

Any Idea on how to fix that ??

Thank you !

**Comment by hcorion** [comment] 2017-06-30 17:38
Yes, this is a known issue, I guess a bug report won't hurt though.
The start button works for me, using the keyboard. What controller backend are you using?

**Comment by Mogiks** [comment] 2017-06-30 21:42
Hi, I'm using a logitech F310, never had problem with that before. When I get home I will provide a bug report . Thank you for your answer

**Comment by Mogiks** [comment] 2017-07-01 04:27
My controler is configured with the Xinput option and here is what I get at the end of a cutscene:

"E {PPU[0x100008b] Thread (_libsail-control) [0x0211a1cc]} 'sys_mutex_lock' failed with 0x80010008 : CELL_EDEADLK
E {PPU[0x1000017] Thread (fios mediathread 8) [0x01ec2ee4]} sys_fs: sys_fs_stat(“/dev_hdd0/game/NPEB01158/USRDIR/data/sound/sr/ja/sr0000.sgh.zarc”) failed: not found
E {PPU[0x1000017] Thread (fios mediathread 8) [0x01ec2ee4]} 'sys_fs_stat' failed with 0x80010006 : CELL_ENOENT
E {PPU[0x1000017] Thread (fios mediathread 8) [0x01ec2ee4]} sys_fs: sys_fs_stat(“/dev_hdd0/game/NPEB01158/USRDIR/data/sound/sr/ja/sr0000.sgh.zarc”) failed: not found
E {PPU[0x1000017] Thread (fios mediathread 8) [0x01ec2ee4]} 'sys_fs_stat' failed with 0x80010006 : CELL_ENOENT
E {PPU[0x1000017] Thread (fios mediathread 8) [0x01ec3090]} sys_fs: sys_fs_open(“/dev_hdd0/game/NPEB01158/USRDIR/data/sound/sr/ja/sr0000.sgh.zarc”): failed to open file (flags=0, mode=0)
E {PPU[0x1000017] Thread (fios mediathread 8) [0x01ec3090]} 'sys_fs_open' failed with 0x80010006 : CELL_ENOENT
E {PPU[0x1000000] Thread (main_thread) [0x0003554c]} 'sys_ppu_thread_join' failed with 0x80010005 : CELL_ESRCH
E {PPU[0x1000000] Thread (main_thread) [0x0003554c]} 'sys_ppu_thread_join' failed with 0x80010005 : CELL_ESRCH"

**Comment by al0xf** [comment] 2017-07-02 09:56
For the record LLE libvdec fixes this, but of course video playback will be too slow.

**Comment by Mogiks** [comment] 2017-07-05 02:37
Yeah I already tried this option... I'm really hoping that this will be fixed soon...

**Comment by Mogiks** [comment] 2017-07-07 18:38
So any news or update on this one ? please guys help me ...

**Comment by SaltyCucumber** [comment] 2017-07-07 18:41
1. Wait for a new build.
2. Download build and replace exe
3. Test Ni No Kuni to see if anything changed
4. If not - repeat 1-3 until it does

**Comment by Mogiks** [comment] 2017-07-31 03:47
Still no improvements on this side ?

**Comment by MattyXarope** [comment] 2017-08-01 14:18
@Mogiks No, no change in full cutscene functionality as of today's build. Also, I find I am _not_ able to skip these scenes as they fade to black despite the menu working and displaying the option to skip.

**Comment by Mogiks** [comment] 2017-08-07 14:18
@MattyXarope it's the same for me ....

**Comment by Asinin3** [comment] 2017-08-07 16:23
Just be patient, no need to spam the comments the devs know about this and and are aware it's still happening they don't need more than that.

**Comment by Mogiks** [comment] 2017-08-08 23:21
I'm not spaming, I was just letting him knows that I have the same issue. I'm perfectly aware that the devs are doing what they can on this, and thankful for their job. I was just hoping for some news on it, anyway I will be waiting for this politely.

**Comment by pwilkin** [comment] 2017-08-31 21:23
Any updates on this? Hints on how to debug, what to send over?

**Comment by hcorion** [comment] 2017-08-31 21:24
The issue is the transfer of data from LLE cellSail and HLE libVdec, something gets lost in translation.

**Comment by pwilkin** [comment] 2017-09-04 23:01
Will a trace dump with LLE libVdec help at all?

**Comment by AniLeo** [comment] 2018-04-07 23:52
Fixed by #4401, closing

**Closed by AniLeo** 2018-04-07 23:52 UTC
