### ISSUE TITLE
Ar Tonelico Qoga access violation (unmapped memory)

### ISSUE THREAD

**Issue by vsub** [RPCS3/rpcs3#8132] opened 2020-05-01 11:39 UTC
It's been a while since I tried this game and I don't think the know "access violation" fatal error was showing "unmapped memory" before

I am using RPCS3 0.0.10-10312 and I just do the usual test(in and out of area...area<=>world map)
[RPCS3.log.gz](https://github.com/RPCS3/rpcs3/files/4563957/RPCS3.log.gz)

**Comment by atomic83GitHub** [comment] 2020-05-10 22:00
This error also happen in the 1.6 client of the Playstation Home when using the "report" function in the help menu when ingame.

**Comment by dummygamer** [comment] 2021-04-10 07:14
I have been testing the game for days
trying every combination still got no good result

still crash when make item, world map, and even walking in field got crash
sometimes the rpcs3 window just close without any warning

anyone have any news?

**Comment by DixieFlat-line** [comment] 2021-10-03 03:30
It's at least similar, but the other one was *technically* closed quite awhile ago. 

Not that the problem still isn't occurring... I've not been having the issue between screen transitions, but Synthesis is kicking me in the backside.

**Comment by darkash** [comment] 2021-10-03 09:35
the issue is never closed, it's just the issue didn't pique dev's interest due to the error shown is a generic error, so more thorough research need to be done for it

Also I don't think it's a disc dump issue, the error happens randomly albeit on same place, sometimes you can pass and synthesis without any error (my longest gameplay is 2 hr without issue even when synthesizing).

**Comment by Megamouse** [comment] 2023-02-01 21:08
duplicate of #5418

**Closed by Megamouse** 2023-02-01 21:08 UTC
