### ISSUE TITLE
[BCES00569] Gran Turismo 5 Error

### ISSUE THREAD

**Issue by Jorzef** [RPCS3/rpcs3#13994] opened 2023-06-10 14:22 UTC
### Quick summary

Sometimes after getting out into a menu the game crashes with the message on log:

F {RSX [0x132edf8]} SIG: Thread terminated due to fatal error: Verification failed
(in file C:\Users\ContainerAdministrator\AppData\Local\Temp\cirrus-ci-build\rpcs3\Emu\RSX\VK\VKTexture.cpp:60[:3], in function copy_image_to_buffer) (error=0x57)

The config file is posted on other details, I suspect that the problem arises from using upscaling however I would like to know if there's any other thing i'm doing wrong. Thanks for all the help and constant development of this amazing tool!

### Attach a log file

[log.txt](https://github.com/RPCS3/rpcs3/files/11712599/log.txt)

### System configuration

CPU: AMD Ryzen 5700G
GPU: AMD RX580 8G
RAM: 64GB DDR4

### Other details

[config_BCES00569.txt](https://github.com/RPCS3/rpcs3/files/11712604/config_BCES00569.txt)

**Comment by AniLeo** [comment] 2023-06-11 15:35
Missing log file, attached file is not a log file

**Comment by readywer** [comment] 2023-06-11 17:13
It only happens for me during licens races. From discussions on discord only happens on BCES00569 version. (I haven't tried if updateing from 1.00 fixes it or any other setting, that why i haven't posed it...)
![Képernyőfelvétel (261)](https://github.com/RPCS3/rpcs3/assets/90259918/929bd4e3-9765-42ab-8131-65f2e09b21a3)

log:
[RPCS3.zip](https://github.com/RPCS3/rpcs3/files/11715274/RPCS3.zip)

**Comment by Jorzef** [comment] 2023-06-12 09:08
I was not aware on how to post a logfile my apologies. However what happens to readywer is exactly what happens to me and ever since I disabled the upscaling at 150 (1080p) using 720p as the resolution I haven't got the error again, which makes me think it might be something due to the UI after the licence test. I didn't say but I'm running the latest update 2.17 of the game.

**Comment by MauricioFiorini** [comment] 2023-06-14 23:48
I have the same issue, with GT5 ver 2.11 (BCUS98114)

**Comment by MauricioFiorini** [comment] 2023-06-14 23:49
> It only happens for me during licens races. From discussions on discord only happens on BCES00569 version. (I haven't tried if updateing from 1.00 fixes it or any other setting, that's why i haven't posed it...) ![Képernyőfelvétel (261)](https://user-images.githubusercontent.com/90259918/244954342-929bd4e3-9765-42ab-8131-65f2e09b21a3.png) I will updated my post when i finished my additional testing. log: [RPCS3.zip](https://github.com/RPCS3/rpcs3/files/11715274/RPCS3.zip)


I have the same issue, with GT5 ver 2.11 (BCUS98114)

**Comment by kd-11** [comment] 2023-06-15 11:01
The most important thing here is to find a series of steps that is likely to trigger this error so that we can debug.

**Comment by Jorzef** [comment] 2023-06-15 19:42
What steps could I do to help? only one I did that solved the issue was resetting Resolution Scale from 150% to 100%

**Comment by readywer** [comment] 2023-06-15 19:51
First this issue had happened to me on Res scal 100% too. The only thing that using res scal increase the likelyness of it like (10h play i had only 1 on 100%). The other thing using accurate XFloat increases the chane of it too, but on my version it is needed to fix the sound dropout.

**Comment by kd-11** [comment] 2023-07-17 19:27
I'm seeing another reported crash on the same check (https://github.com/RPCS3/rpcs3/issues/14199), but I cannot reproduce that one either. What exactly was being done when the error occurs? Does it happen in arcade mode?

**Comment by Satan86** [comment] 2023-08-12 13:42
Should be fixed by #14446

**Closed** 2023-08-12 14:18 UTC
Labels: Need Information
