### ISSUE TITLE
[macOS] [Arm Native] LLVM: Segfault before launching any game 

### ISSUE THREAD

**Issue by shinra-electric** [RPCS3/rpcs3#12882] opened 2022-10-25 14:08 UTC
### Quick summary

RPCS3 will segfault when trying to launch any game. 

Edit: Segfault doesn't happen if: 

- PPU Decoder is set to Static Interpreter
- SPU Decoder is set to Dynamic Interpreter

Edit: After the LLVM 16 update, it's no longer Ventura-only. LLVM fails on Ventura and Monterey. 

### Details

RPCS3 will segfault with the following error on launching any game. You can see that the segfault location is the same, though the thread may be different:

For Demon's Souls: 
```
F {PPU[0x1000005] Thread (HighGraphics) [libgcm_sys: 0x01fc0c78]} SIG: Thread terminated due to fatal error: Segfault writing location 0000000000000018 at 000000712003a4ec.
Emu Thread Name: 'PPU[0x1000005] HighGraphics'.
``` 

For Dragon's Crown: 
```
F {PPU[0x1000000] Thread (main_thread) [libgcm_sys: 0x00f90c78]} SIG: Thread terminated due to fatal error: Segfault writing location 0000000000000018 at 000000710002a4ec.
Emu Thread Name: 'PPU[0x1000000] main_thread'.
```

### Build with regression

Unknown

~~Edit: This is likely to do with Ventura, and not an RPCS3 regression~~
Edit: After the LLVM 16 update, it's no longer Ventura-only. LLVM fails on Ventura and Monterey. 

### Attach two log files

~~[RPCS3.log](https://github.com/RPCS3/rpcs3/files/9860972/RPCS3.log)~~

Edit: New log from after the LLVM 16 update: 
[RPCS3.log](https://github.com/RPCS3/rpcs3/files/11242157/RPCS3.log)

### System configuration

M1 Pro, macOS 13 Ventura

### Other details

I cannot identify the commit that introduced the regression since there are currently no Arm builds in CI.

~~It likely happened between #12620 and now. That PR broke Arm compilation and it has only been fixed yesterday.~~

~~Edit: This is likely to do with Ventura, and not an RPCS3 regression~~
Edit: After the LLVM 16 update, it's no longer Ventura-only. LLVM fails on Ventura and Monterey.

**Comment by Soneoylys** [comment] 2023-01-01 12:36
Can be reproduced in latest commit, build on M1 Apple Silicon with cmake arg 
"-DPNG_ARM_NEON=on -DUSE_ALSA=OFF -DUSE_PULSE=OFF -DUSE_AUDIOUNIT=ON -DUSE_NATIVE_INSTRUCTIONS=OFF -DUSE_SYSTEM_FFMPEG=on -DCMAKE_OSX_ARCHITECTURES="arm64" -DLLVM_TARGETS_TO_BUILD="X86;AArch64;ARM" -GNinja -DCMAKE_BUILD_TYPE=RelWithDebInfo -DUSE_SYSTEM_MVK=on"

Tried to run with static PPU/SPU decoder, which able to boot into game, but missing all 3D graphics.

Also, please consider to add native aarch64 release in CI if possible, Rosetta significant reduce the CPU performance which is usually a bottleneck in PS3 emulation.

**Comment by shinra-electric** [comment] 2023-01-17 13:42
I think this may be related to Ventura. 

I just made a build on Ventura no and it failed as described above. 

(I'll post a screenshot in a minute)

But I also made a build at the same time on Monterey in a VM, and it went in-game.

<img width="1512" alt="Screenshot 2023-01-17 at 13 04 38" src="https://user-images.githubusercontent.com/50119606/212914092-c809e6d8-ceef-4364-ab6a-d58d2a51c1ea.png">

It actually crashed shortly after that, but that crash was unrelated. 

Can anyone else with an M1 and Monterey confirm this?

**Comment by nsklaus** [comment] 2023-02-08 21:04
for what it's worth, i was able to start playing "the last of us" on macbookpro M2 (14" 2023 model)

```
- SYS: RPCS3 v0.0.26-14691-27cad422 Alpha | master
- SYS: VirtualApple @ 2.50GHz | 10 Threads | 16.00 GiB RAM | TSC: 1.000GHz
- SYS: Operating system: macOS, Version: 13.2.0
- SYS: Current Time: 2023-02- 8T21:59:35
- RSX: Found vulkan-compatible GPU: 'Apple M2 Pro' running on driver 0.2.986
- SYS: Firmware version: 4.89
```

the game did start, and i played for a minute or so, i thought i'd try to tweak a bit more settings so i did  quit game, and after that it could never be started again. no matter what i did with settings.. reverting back to previously working ones, default, or even tweak more, nothing worked.

let me know if you need more logs, or running some tests.

**Comment by nsklaus** [comment] 2023-02-08 21:22
hmm.. ok, if i delete the configuration directory in `~/Library/Application\ Support/rpcs3/` game is starting again. each time i want to play i have to delete that directory. maybe i could manage to make a backup copy of gamesaves before deleting that dir and import them in the freshly created one ?
i'll have to test. also, in the patch i disabled motion blur, but the game still have them. so i'm not sure patches are correctly applied either.

**Comment by shinra-electric** [comment] 2023-02-09 08:25
> - SYS: RPCS3 v0.0.26-14691-27cad422 Alpha | master

It looks to me like you are testing the CI builds, which are x86 and run through Rosetta. 
This issue is regarding Arm builds that have to be built yourself locally. There are no Arm CI build at this time. 

If you want to test an Arm build, here are the build instructions: 

[RPCS3 Build instructions.txt](https://github.com/RPCS3/rpcs3/files/10694905/RPCS3.Build.instructions.txt)

**Comment by nsklaus** [comment] 2023-02-09 08:45
ah, my bad :)
yes i was running x86, provided CI builds.
i had assumed you were all using provided (x86) builds too and just happened to use them on arm (m1/m2) machines. thank you for pointing me to the build instructions.

**Comment by shinra-electric** [comment] 2023-02-09 08:55
I renamed the issue to make it a bit clearer

**Comment by nsklaus** [comment] 2023-02-09 09:03
yes sorry about the confusion and my posts completely off target.
can i ask, how much of a boost native builds used to show compared to x86 ones ?
+5fps or so in a test game ?
it was very interesting to see rpcs3 could run games like 'last of us' on mac.
the fps though were around 10 to 20, but the machine barely got warm, i suppose there's room for optimisations later on ? there were quite a few gfx errors, texture 'popping' and flashing around. the game was overall looking normal, but with glitches here and there appearing and disappearing constantly. i'll try to see if i can make my own native build.

**Comment by shinra-electric** [comment] 2023-02-09 09:24
If you can make your own build, please post how it goes. But I suspect it will not launch any games for you due to this issue. 

The Arm build (when it works) can only play a handful of 2D games at this time. I usually test with Dragon's Crown, and the Arkedo series also work. Maybe some other 2D games I haven't tested work as well. It will not play any 3D games without further development.

**Comment by nsklaus** [comment] 2023-02-09 20:56
i see, thank you for those details. i bet both x86 and arm builds make use of same libs. most probably moltenvk, i wonder what differs that much as to break 3d completely for arm builds.
maybe it have to do with memory pages that are 16k on the M series ? but if that would be something like that, then probably nothing would run, not even 2d. so i guess it must be something else..  it's not that i have the knowledge to fix it anyway, but it got me curious. has anyone pinpointed the root cause of this yet ? shouldn't be that big of an issue. is there a specific thread for that particular problem ?
having native arm builds, with 3d and all the bells and whistle would surely be nice to have.

**Comment by zintus** [comment] 2023-02-11 11:35
I was able to build `465ca9753` locally on m2 using instructions from #12115

Game halt immediately with [rpcs3.log](https://github.com/RPCS3/rpcs3/files/10713493/rpcs3.log)

I hope this helps :)

**Comment by shinra-electric** [comment] 2023-02-11 12:10
Thanks for testing, though I expected it to fail on Ventura. 

If anyone can test with Monterey, that would be great. If we can confirm the issue is with a change in macOS, that would help identify the issue.

**Comment by shinra-electric** [comment] 2023-02-26 18:08
I came across something OpenMW that might have some relevance to this issue. 

Last year they made [this PR](https://gitlab.com/OpenMW/openmw/-/merge_requests/1399) that allowed OpenMW to work on the M1. One of the issues they had was with page sizes when using LuaJit, so they worked around it. 

However recently it was broken again, and they realised that Apple had fixed the problem in recent versions of macOS and that the workaround was now breaking things. So a [new PR](https://gitlab.com/OpenMW/openmw/-/merge_requests/2767) reverted part of the patch and it's working again now. 

I'm wondering if there are any similar page size workarounds in @sguo35's  [PR that fixed AsmJit](https://github.com/RPCS3/rpcs3/pull/12608/commits/ab993110fdb052f9c9fc001c2caad91de52f50e8) that might be responsible for this issue.

**Comment by shinra-electric** [comment] 2023-04-04 17:05
I tried using different options for the PPU and SPU decoders, and found that RPCS3 will not display this segfault issue if: 
PPU Decoder is set to Static Interpreter
SPU Decoder is set to Dynamic Interpreter

<img width="1392" alt="Screenshot 2023-04-04 at 18 00 03" src="https://user-images.githubusercontent.com/50119606/229865532-472ddcfa-d610-48d6-8280-60730f0b453e.png">

**Comment by kd-11** [comment] 2024-08-25 19:09
Fixed by https://github.com/RPCS3/rpcs3/pull/15992 and https://github.com/RPCS3/rpcs3/pull/15987

**Closed by kd-11** 2024-08-25 19:09 UTC
Labels: Regression, OS: Mac
