### ISSUE TITLE
SPU : class std::runtime_error thrown: Unknown STOP code: 0x0 (Out_MBox is empty)

### ISSUE THREAD

**Issue by MattKackles** [RPCS3/rpcs3#2315] opened 2017-01-31 19:32 UTC
(in file C:\rpcs3\rpcs3\Emu\Cell\SPUThread.cpp:1360)

Affects Mafia 2 and Mafia 2 Demo

LOG:
[RPCS3.txt](https://github.com/RPCS3/rpcs3/files/742961/RPCS3.txt)

**Comment by AniLeo** [comment] 2017-01-31 19:35
Duplicate of #1485

**Closed by AniLeo** 2017-01-31 19:35 UTC
