### ISSUE TITLE
Bug: Broken graphics in Deadpool - [BLUS31146]

### ISSUE THREAD

**Issue by Emulator-Team-2** [RPCS3/rpcs3#10869] opened 2021-09-13 03:33 UTC
## Quick summary
Please briefly describe what is not working correctly.
* Flickering and disappearing models, object etc.

#### 0. Make sure you're running with settings as close to default as possible.
* RPCS3 settings: (Default).

#### 1. Please attach RPCS3's log.
[RPCS3.log.gz](https://github.com/RPCS3/rpcs3/files/7151197/RPCS3.log.gz)

#### 2. If you describe graphical issue, please provide an RSX capture and a RenderDoc capture that demonstrate it.
[rsx capture](https://drive.google.com/file/d/1r1CVr3ckv9v-3Dzo0y0uwJkweSW0TMzH/view?usp=sharing)
[rdc capture-vk](https://drive.google.com/file/d/1_Dch5ErwVqOS-BJzS4729-aECh0ymK-g/view?usp=sharing)

#### 3. Please attach screenshots of your problem.
* Enable performance overlay with at least medium level of detail.

![1](https://user-images.githubusercontent.com/38318848/145715011-f02861ab-59ae-4784-9311-61676bc589e0.png)

#### 4. Please provide comparison with real PS3.
![2](https://user-images.githubusercontent.com/38318848/133019596-c30896d5-5cca-4f3a-ab97-da51b0afced1.png)

#### 5. Please provide your system configuration:
* OS: Windows 10 64-bit
* CPU: Intel i7-10700
* Memory: 16GB RAM
* GPU: GTX 1660
* Driver version: 471.68.0.0.

#### Please include.
Anything else you deem to be important:
* Game Engine: (Unreal Engine 3)
* No changes with enabled (WCB+WDB+RCB+RDB) settings.

#### List of known games with the same problem:
* Transformers: Fall of Cybertron.
* Shaun White Skateboarding.

**Comment by RainbowCookie32** [comment] 2021-09-13 03:34
Just edit the issue instead of closing it and opening another one 😕

**Comment by kd-11** [comment] 2021-09-14 21:25
Yet another zcull problem. This is an ancient regression, I'll have to figure out which corner-case I broke.
![image](https://user-images.githubusercontent.com/15904127/133335866-6afb499c-cd9f-4245-82eb-d3b17b9afa60.png)

**Comment by kd-11** [comment] 2022-01-08 10:55
This broke because GPU occlusion was implemented. It seems there is a ZCULL corner case that is yet to be examined, specifically, the game is reading reports without zpass statistics enabled but somehow getting valid results. It could be a game bug where it just reads uninitialized crap and it just works, I'll need to reverse the algorithm used in this case.

**Comment by Emulator-Team-2** [comment] 2022-07-25 18:31
Update:
-Tested with the latest master build: (rpcs3-v0.0.23-13964).

**1. Deadpool:**

<details> 
<summary>(Screenshots - Master / ZCull - Hack)</summary>

![1](https://user-images.githubusercontent.com/38318848/180835604-37ac855a-ed07-46f2-9407-dad28d0001a0.png)
![2](https://user-images.githubusercontent.com/38318848/180836392-a376d85f-08e8-439b-a5fe-fec4840917f7.png)

</details>

**2. Transformers: Fall of Cybertron:**

<details> 
<summary>(Screenshots - Master / ZCull - Hack)</summary>

![3](https://user-images.githubusercontent.com/38318848/180836929-b7fea23e-309a-4231-b5c3-88e00413571f.png)
![4](https://user-images.githubusercontent.com/38318848/180837050-46a63c4e-97f5-4ce6-8ce8-ac511380e475.png)

</details>

**3. Shaun White Skateboarding:**

<details> 
<summary>(Screenshots - Master / ZCull - Hack)</summary>

![5](https://user-images.githubusercontent.com/38318848/180837499-44a9724d-52a4-4474-a905-0663fa21befe.png)
![6](https://user-images.githubusercontent.com/38318848/180837557-2818589a-3201-4621-94da-7edfa74f9bb3.png)

</details>

--------------------------------------------------------------------------------------------------------------------------------------------

(RenderDoc/RSX Capture)
**Link:** 

**1.** [rdc capture-vk](https://drive.google.com/file/d/1ANoNsjzxquAY2Dze1p8a_qGbDtcaDYjd/view?usp=sharing)
- [rsx capture](https://drive.google.com/file/d/11fTmazBqx3jL0P0gEk6kjABLVCRS4uND/view?usp=sharing)

**2.** [rdc capture-vk](https://drive.google.com/file/d/1DlqAq8WD8GW0A4-RXt1Q40snvFQBCVmY/view?usp=sharing)
- [rsx capture](https://drive.google.com/file/d/1OR-AlQyYwtQlKHRnodCuL3Pi7LFUEMer/view?usp=sharing)

**3.** [rdc capture-gl](https://drive.google.com/file/d/1QDufJPqLS8L1hRYkUsR3LWB92OgUTf0l/view?usp=sharing)
- [rsx capture](https://drive.google.com/file/d/1VjiFKCVQGm8uDt1QYlYjd6SQ3fltK8FB/view?usp=sharing)

**Closed** 2022-07-31 21:23 UTC
Labels: Bug, RSX
