### ISSUE TITLE
GTA IV Doesn't Boot 

### ISSUE THREAD

**Issue by CodingJhames** [RPCS3/rpcs3#14888] opened 2023-12-11 23:21 UTC
### Quick summary

GTA IV Doesn't Boot afer being started, Game have the 1.00 update

### Details

this is the output from emulator's console appeared:

`E RSX: FIFO error: possible desync event (last cmd = 0xffffffff) x21
F {RSX [0x0001000]} SIG: Thread terminated due to fatal error: Dead FIFO commands queue state has been detected!
Try increasing "Driver Wake-Up Delay" setting or setting "RSX FIFO Accuracy" to "Atomic", both in Advanced settings. Called from 
(in file /run/build/rpcs3/rpcs3/Emu/RSX/RSXFIFO.cpp:647[:5], in function run_FIFO) (errno=110=Connection timed out)
(in file /run/build/rpcs3/rpcs3/Emu/RSX/RSXThread.cpp:3227[:4], in function recover_fifo) (errno=110=Connection timed out)`

### Attach a log file

E RSX: FIFO error: possible desync event (last cmd = 0xffffffff) x21
F {RSX [0x0001000]} SIG: Thread terminated due to fatal error: Dead FIFO commands queue state has been detected!
Try increasing "Driver Wake-Up Delay" setting or setting "RSX FIFO Accuracy" to "Atomic", both in Advanced settings. Called from 
(in file /run/build/rpcs3/rpcs3/Emu/RSX/RSXFIFO.cpp:647[:5], in function run_FIFO) (errno=110=Connection timed out)
(in file /run/build/rpcs3/rpcs3/Emu/RSX/RSXThread.cpp:3227[:4], in function recover_fifo) (errno=110=Connection timed out)

### System configuration

Ryzen 5 5600G APU
16 GB RAM DDR4

**Comment by FlexBy420** [comment] 2023-12-11 23:24
Duplicate of #14194

**Closed** 2023-12-11 23:25 UTC
