### ISSUE TITLE
Resogun Black Screen

### ISSUE THREAD

**Issue by DannyGlover** [RPCS3/rpcs3#3055] opened 2017-07-21 17:13 UTC
Attempting to run Resogun on the latest alpha results in a black screen with no audio.
The problem exists on both interpreter modes, and JIT.

Here is the log:

[RPCS3.zip](https://github.com/RPCS3/rpcs3/files/1166240/RPCS3.zip)

**Comment by AniLeo** [comment] 2017-07-21 17:13
Please upload a log file

**Comment by DannyGlover** [comment] 2017-07-21 17:15
Sorry, first time reporting a bug for RPCS3.




[RPCS3.zip](https://github.com/RPCS3/rpcs3/files/1166236/RPCS3.zip)

**Comment by AniLeo** [comment] 2017-07-21 17:19
Set Write Color Buffers to false. 
You'll also want to set frame limiter to off if RESOGUN has internal FPS cap, PPU and SPU to Recompilers for speed.

**Comment by Zangetsu38** [comment] 2017-07-21 17:19
strange, perfectly works for me
![image](https://user-images.githubusercontent.com/5261759/28474565-7560cafa-6e49-11e7-8f0a-861ead46f0a9.png)

**Comment by DannyGlover** [comment] 2017-07-21 17:23
@AniLeo 

Same issues reported in the debug output with those settings. New log below:

[RPCS3-log2.zip](https://github.com/RPCS3/rpcs3/files/1166246/RPCS3-log2.zip)

**Comment by kd-11** [comment] 2017-07-21 19:12
I'm pretty sure this is an issue for the forums. Resogun works very well with rpcs3. Wait a short while after booting as it takes some time to start up.

**Comment by AniLeo** [comment] 2017-07-21 19:14
Will be closing the issue since it's a support matter and not an actual bug since the game has been confirmed to be working. Please use the forums or Discord for support.

**Closed by AniLeo** 2017-07-21 19:14 UTC

**Comment by DannyGlover** [comment] 2017-07-22 01:01
Turns out the issue was due to my RPCS3 installation.

I have been upgrading since v0.0.1 and messing around with firmware files manually etc. Wiping clean and starting over, using the built in firmware installer fixed the issue.

Thanks for weighing in everyone, and apologies for wasting your time.
