### ISSUE TITLE
[Regression] Metal Gear Solid 4 performance regression

### ISSUE THREAD

**Issue by Mine93** [RPCS3/rpcs3#12542] opened 2022-08-21 14:08 UTC
### Quick summary

Performance in Metal Gear Solid 4: Guns of the Patriots seems to have regressed or in some way locked whenever the game is not paused, in prevoius versions performance was stable enough hovering around 50 to 60fps, with the latest one it seems to reach a maximum of 26fps with the game unpaused, while being paused it seems to be able to reach 60fps.

### Details

Performance seems to have heavily regressed with game reaching a maximum of 26 fps during gameplay, while versions as late as v0.0.23-14068-a74d3005, seem to work just fine.
![immagine](https://user-images.githubusercontent.com/46654962/185794081-7a1f0db9-5100-4568-a675-f72d5563662f.png)
this is what performance looks like on version v0.0.23-14068-a74d3005.
![immagine](https://user-images.githubusercontent.com/46654962/185794728-7928174e-d9ce-403b-88ec-549ea9fc9eeb.png)
while this is what it looks like on the latest update v0.0.23-14079-bf63a18c.
gameplay seems to cap out at a maximum of 26 fps but whenever the game is paused performce is unlocked again:
![immagine](https://user-images.githubusercontent.com/46654962/185794910-99f7563a-f4c1-449d-9d8d-31d158af3d25.png)

### Build with regression

v0.0.23-14079-bf63a18c

### Attach two log files

v0.0.23-14068-a74d3005:
[RPCS3.log.gz](https://github.com/RPCS3/rpcs3/files/9389221/RPCS3.log.gz)
v0.0.23-14079-bf63a18c:
[RPCS3.log.gz](https://github.com/RPCS3/rpcs3/files/9389255/RPCS3.log.gz)

### System configuration

Windows 11 21H2
Intel Core I7 11700k (no overclock)
Nvidia Geforce GTX 1080 (driver ver. 512.77.0.0) (no overclock)

**Comment by AniLeo** [comment] 2022-08-21 14:08
Duplicate of #12541

**Closed by AniLeo** 2022-08-21 14:08 UTC
