### ISSUE TITLE
Why this Custom old version is faster than new ones ? I got more fps running on that:

### ISSUE THREAD

**Issue by andregm3** [RPCS3/rpcs3#6094] opened 2019-06-15 13:41 UTC
Why this Custom old version is faster than new ones ?

Games got significantly more fps running on that:

https://drive.google.com/drive/folders/1ISv_os409P3CoRrV2eACk7plIam7k_Be

I heard from the developer that this custom version release full Mega instead of Safe mode, how can I activate it on newer versions of RPCS3 ?

**Comment by vsub** [comment] 2019-06-15 14:29
Because the emulator gets more and more accurate,it make more things work properly which results in higher hardware requirements

You may also get less fps because of a regression but that's not how you post a bug report 
https://github.com/RPCS3/rpcs3/wiki/How-to-ask-for-Support

**Comment by andregm3** [comment] 2019-06-15 14:36
> Because the emulator gets more and more accurate,it make more things work properly which results in higher hardware requirements
> 
> You may also get less fps because of a regression but that's not how you post a bug report
> https://github.com/RPCS3/rpcs3/wiki/How-to-ask-for-Support

This is a custom build over an old version, 0.0.6-8084, I already tested the official 8084 and the performance is the same as the 06/14/2019, the performance gain is something else, that I would like to know what is and to apply to new versions would be nice !

**Comment by win98and95** [comment] 2019-06-15 14:58
😹

**Comment by HerrHulaHoop** [comment] 2019-06-15 15:26
Not sure what custom build that is but custom builds sometimes have hacks that benefit certain games but are detrimental to others, so we don't incorporate such changes into master. Some might just be a gigantic mix of open PRs that are yet to be merged. So there could be many reason. 

This isn't a support request though. Please take such questions to our discord server.

**Comment by andregm3** [comment] 2019-06-15 23:29
> Not sure what custom build that is but custom builds sometimes have hacks that benefit certain games but are detrimental to others, so we don't incorporate such changes into master. Some might just be a gigantic mix of open PRs that are yet to be merged. So there could be many reason.
> 
> This isn't a support request though. Please take such questions to our discord server.

I don't think it is a specific game optimization, because it says was made for God of War, but worked great on MotorStorm here !

**Comment by RainbowCookie32** [comment] 2019-06-15 23:30
Hacks like this usually improve some games, break others. Without having the code, we can't know what exactly is what improves performance, and since it's probably a hack it won't be added into RPCS3. I'm not sure why this issue is a thing.

**Comment by andregm3** [comment] 2019-06-15 23:35
maybe Reverse engineering the build and get the changes, dunno, that's why i'm posting it here, to the specialists check out. I'm also asking the developer: DAN for ir
Here is the source:
https://www.youtube.com/watch?v=njujL_lCrTw&t

**Comment by RainbowCookie32** [comment] 2019-06-15 23:39
A link full of pirated games, please remove the link and close the issue. It's stuff to discuss in Discord at best

**Comment by legend800** [comment] 2019-06-16 00:51
So many great lines from Andre here. I think if I had to pick one, I'd have to go with:  
"maybe Reverse engineering the build and get the changes". 

I just pictured Neko stopping the rcps3 development for months to work on this reverse engineering project specifically so Andre can finally get a few fps back, ironically sacrificing all the other accuracy and performance improvements that could have been done during that time. 😸

**Comment by andregm3** [comment] 2019-06-16 00:55
> So many great lines from Andre here. I think if I had to pick one, I'd have to go with:
> "maybe Reverse engineering the build and get the changes".
> 
> I just pictured Neko stopping the rcps3 development for months to work on this reverse engineering project specifically so Andre can finally get a few fps back, ironically sacrificing all the other accuracy and performance improvements that could have been done during that time. 😸

Well what I see is my old i7 3770 running games like i9 9900k performance...if you don't think this is a deal not my fault...There are many developers, its an open source, i'm not asking him to stop doing anything...i'm just sharing my experience maybe someone could take an advantage with that...

**Comment by RainbowCookie32** [comment] 2019-06-16 00:59
This issue should be closed already. There's no dev that will waste the time in "reverse engineering" a mysterious build, especially considering that it's probably just a hack. Github is not the place for this kinds of things, and potentially big hacks like this one are not going to get into RPCS3 officially

**Comment by andregm3** [comment] 2019-06-16 01:06
You don't know and can't tell its a hack...I'am asking the developer if he asnwere me i'll post changes here.

**Comment by andregm3** [comment] 2019-06-16 01:09
![Untitled-1](https://user-images.githubusercontent.com/4154732/59557824-2b05cc00-8fba-11e9-8392-08bc66ef3ed8.jpg)

**Comment by RainbowCookie32** [comment] 2019-06-16 01:12
So this issue is based on a 2FPS difference? Man, I assumed that it'd at least be something noticeable. Even if it was a big performance improvement, you really think that this dude would come up with something no other dev has come up with so far that massively increases performance in a clean and accurate way? I'm 99% positive that it's a hack, the missing 1% is because I don't have access to the code.

But well, seems like you are convinced to keep this issue open until someone closes it so we'll have to wait until a GH mod is online

**Comment by andregm3** [comment] 2019-06-16 01:14
This is GOW 3, 2 fps on this its like 10fps change on other games...my like I said, the big change was playing MotorStorm games.

**Comment by dio-gh** [comment] 2019-06-16 01:19
Thing is, this is not an issue report, nor a feature request - this is why we would prefer it not to be ticketed on the tracker. It'd be a much better fit for the Discord server for example, I'm sure it would have generated some noise, if that improvement really is that significant.

Until the change is known, nothing will change. Otherwise this is just an invalid ticket. Maybe someone will look into it, but it's impractical to open a ticket about every single custom build. Please reconsider and close. Maybe reopen if the changeset becomes available.

**Comment by HerrHulaHoop** [comment] 2019-06-16 03:53
FFS whose dick do I have to suck to close and lock this issue thread

**Comment by legend800** [comment] 2019-06-16 04:00
Why you getting all worked up? Who cares? It'll get closed soon. Just enjoy it while you can. You don't get these kind of gems everyday. :)

**Comment by andregm3** [comment] 2019-06-16 04:34
![DAN MASTER](https://user-images.githubusercontent.com/4154732/59559100-dde42300-8fd6-11e9-86ad-fc858c8edafa.jpg)

**Comment by legend800** [comment] 2019-06-16 05:20
Of course you have a potato... The game is full speed for most people (on master). You must be rocking something pretty bad to only be getting 12 fps. I really question your rpcs3 configuration too. 

![2019-06-15 22_15_06-Why this Custom old version is faster than new ones _ I got more fps running on ](https://user-images.githubusercontent.com/20983844/59559394-2b529700-8fbb-11e9-803b-06c46f77dd52.png)

Let it go, you'll NEVER get whatever was hacked into that build so stop trying. Close issue and move on.

**Comment by andregm3** [comment] 2019-06-16 05:22
i7 3770

**Comment by Whatcookie** [comment] 2019-06-16 05:26
Looks like the build on the left has logging disabled, is that not responsible for the difference?

**Comment by andregm3** [comment] 2019-06-16 05:28
> Looks like the build on the left has logging disabled, is that not responsible for the difference?

nope, i realized that too, and test with Master logging off and no performance difference.

**Comment by win98and95** [comment] 2019-06-16 05:53
🔨 lock this issue when?

**Comment by Megamouse** [comment] 2019-06-16 06:30
This is useless

**Closed by Megamouse** 2019-06-16 06:30 UTC
