### ISSUE TITLE
Regression - WRC 3 FIA World Rally Championship Demo [NPEB90467] crashes when starting the race

### ISSUE THREAD

**Issue by CookiePLMonster** [RPCS3/rpcs3#8170] opened 2020-05-07 18:18 UTC
## Quick summary
Starting with the Shader Interpreter PR (#8106), WRC3 Demo (possibly the full game as well) consistently crashes in RSX Decompiler Thread when starting the race.

## Details
Last working build: **0.0.9-10298**
First broken build: **0.0.9-10307**

This issue seems to be strictly related to shader gathering and compilation - if shaders are gathered and compiled using an older, working build, the game goes into the race just fine even on the newest build. Therefore, **clear the shader cache** before every test.

![image](https://user-images.githubusercontent.com/7947461/81330081-d8d10c00-909f-11ea-8662-77ba816e3186.png)

Logs:
[RPCS3.10298.log.zip](https://github.com/RPCS3/rpcs3/files/4594948/RPCS3.10298.log.zip)
[RPCS3.10307.log.zip](https://github.com/RPCS3/rpcs3/files/4594932/RPCS3.10307.log.zip)

**Comment by legend800** [comment] 2020-05-07 19:31
Fine here on full version on latest build.

![2020-05-07 12_29_25-FPS_ 30 01 _ Vulkan _ 0 0 10-10340 _ WRC 3  NPEB01072](https://user-images.githubusercontent.com/20983844/81336648-8e7b6b00-905e-11ea-9786-9c215271323d.png)

[RPCS3.log.gz](https://github.com/RPCS3/rpcs3/files/4595283/RPCS3.log.gz)

**Comment by CookiePLMonster** [comment] 2020-05-07 19:32
> Fine here on full version on latest build.

The key here is starting with a clear cache - did you do that? It might also differ per stage, from what I know demo starts in Spain.

**Comment by legend800** [comment] 2020-05-07 19:38
Ah, that was it, track specific. @kd-11 

@CookiePLMonster Did you try all shader options?

[RPCS3.zip](https://github.com/RPCS3/rpcs3/files/4595307/RPCS3.zip)

![2020-05-07 12_35_42-Window](https://user-images.githubusercontent.com/20983844/81337111-5cb6d400-905f-11ea-88b5-b7cd1eecb87a.png)

![2020-05-07 12_35_58-FPS_ 30 00 _ Vulkan _ 0 0 10-10340 _ WRC 3  NPEB01072](https://user-images.githubusercontent.com/20983844/81337112-5de80100-905f-11ea-807d-484afe0ad3d7.png)

**Comment by CookiePLMonster** [comment] 2020-05-07 19:51
> @CookiePLMonster Did you try all shader options?

I tried Vulkan + OGL, and only async shaders. I did not try "shader interpreter only" or legacy/synchronous compilation.

**Comment by legend800** [comment] 2020-05-07 20:13
Works fine with Legacy/Single thread shader mode. So maybe not a regression?

![2020-05-07 13_11_32-Issues · RPCS3_rpcs3](https://user-images.githubusercontent.com/20983844/81340337-89211f00-9064-11ea-813c-bacf401ec5b4.png)
(forgot to turn on strict rendering)

**Comment by Fabianpaw** [comment] 2020-05-07 20:18
You say that you forgot to turn on Strict Rendering Mode, which causes broken graphics, I dont remember needing to turn that on either. Maybe another regression?

**Comment by CookiePLMonster** [comment] 2020-05-07 20:19
Asynchronous mode is equivalent to the old default behaviour (as in, without "Disable Async Shader Compiler" ticked) so if it crashes now but not before the Interpreter PR then it's a regression.

**Comment by legend800** [comment] 2020-05-07 20:25
@Fabianpaw That's been the case for close to a year for me.

**Comment by Fabianpaw** [comment] 2020-05-07 20:38
Maybe different between the Full Game and the Demo then (Or just some stages), since I only have the Demo.

**Comment by Fabianpaw** [comment] 2020-05-07 20:46
Just tried with with Legacy Shader Mode, and got a slightly different result. As expected, it didn't crash, but kept saying "Compiling Shaders...", infinitely looping with very poor performance. 
[RPCS3.log.gz](https://github.com/RPCS3/rpcs3/files/4595695/RPCS3.log.gz)

**Comment by legend800** [comment] 2020-05-09 05:14
FYI, looks like it affects other games too. Same behavior on MS Apoc. - also only happens on certain tracks too. 

![2020-05-08 22_11_55-FPS_ 22 38 _ Vulkan _ 0 0 10-d8fb7356-dma _ MOTORSTORM™_ APOCALYPSE Digital Edit](https://user-images.githubusercontent.com/20983844/81464767-50bf3500-9179-11ea-90b1-f12598ae152d.png)

[RPCS3.zip](https://github.com/RPCS3/rpcs3/files/4602710/RPCS3.zip)

**Comment by Fabianpaw** [comment] 2020-05-09 06:00
Yup, LittleBigPlanet Karting was broken for another user too.
[Their Log](https://github.com/RPCS3/rpcs3/files/4602785/RPCS3.log)

**Comment by kd-11** [comment] 2020-05-09 09:00
Check if https://github.com/RPCS3/rpcs3/pull/8178 fixes it.

**Comment by kd-11** [comment] 2020-05-10 17:17
Should be fixed by https://github.com/RPCS3/rpcs3/pull/8185

**Comment by Fabianpaw** [comment] 2020-05-10 18:02
Can confirm, it's fixed now.
![FPS_ 30 00 _ i5-8400 _ WRC 3 FIA World Rally Championship Demo  _  NPEB90467‎‎‎‎‎‎‎‎‎‎‎‎‎‎  10 05 2020 19_54_58](https://user-images.githubusercontent.com/62476228/81506791-2ac09e80-92f9-11ea-8e89-7295138b5bfa.png)

**Closed** 2020-05-10 18:54 UTC
