### ISSUE TITLE
Demons Souls BLES00932 random crashes 

### ISSUE THREAD

**Issue by SmoKeFather** [RPCS3/rpcs3#9250] opened 2020-11-11 18:16 UTC
hi, i got demons souls to work on my rig yesterday and i could play 1 hour without any problems till i sat down today and experienced crashes after 10-20 minutes of playtime =(

![capture 1](https://user-images.githubusercontent.com/74319758/98848481-1305d680-2452-11eb-98f3-efa39b8dbe86.JPG)
![Capture 2](https://user-images.githubusercontent.com/74319758/98848499-19944e00-2452-11eb-819f-f1a85f78000b.JPG)
![Capture  3JPG](https://user-images.githubusercontent.com/74319758/98848503-1b5e1180-2452-11eb-8acf-468feef1ee75.JPG)
![Capture 4](https://user-images.githubusercontent.com/74319758/98848510-1d27d500-2452-11eb-9605-794f148c6655.JPG)

log error messages:

E {PPU[0x100000a] Thread (Core.Res.FileLoader) [0x02092090]} SYS: 'sys_fs_open' failed with 0x80010006 : CELL_ENOENT, “/dev_hdd1/10/a49828b2bbcbe379023370c6fd6d1790” [1]
E {PPU[0x100000a] Thread (Core.Res.FileLoader) [0x02092090]} SYS: 'sys_fs_open' failed with 0x80010006 : CELL_ENOENT, “/dev_hdd1/21/21ab0e1a94579d7f4cf136d39b4fbf1a” [1]
E {PPU[0x100000a] Thread (Core.Res.FileLoader) [0x02092090]} SYS: 'sys_fs_open' failed with 0x80010006 : CELL_ENOENT, “/dev_hdd1/03/28216d87121d3662532bd73c0dd4c9ca” [1]
E {PPU[0x100000a] Thread (Core.Res.FileLoader) [0x02092090]} SYS: 'sys_fs_open' failed with 0x80010006 : CELL_ENOENT, “/dev_hdd1/03/4d06375fa30e969ca8d3df9d6cb032b5” [1]
E {PPU[0x100000a] Thread (Core.Res.FileLoader) [0x02092090]} SYS: 'sys_fs_open' failed with 0x80010006 : CELL_ENOENT, “/dev_hdd1/1c/663aea545cee22569c2b9c30a8beb90a” [1]
E {PPU[0x100000a] Thread (Core.Res.FileLoader) [0x02092090]} SYS: 'sys_fs_open' failed with 0x80010006 : CELL_ENOENT, “/dev_hdd1/19/f79552ce345e34a37358457d7b159a66” [1]
E {PPU[0x100000a] Thread (Core.Res.FileLoader) [0x02092090]} SYS: 'sys_fs_open' failed with 0x80010006 : CELL_ENOENT, “/dev_hdd1/0e/a26bcaaeb0493296323423d20b744791” [1]
E {PPU[0x100000a] Thread (Core.Res.FileLoader) [0x02092090]} SYS: 'sys_fs_open' failed with 0x80010006 : CELL_ENOENT, “/dev_hdd1/21/6b66d12d75f2022c27a3e7c45bb1f6c0” [1]
E {PPU[0x100000a] Thread (Core.Res.FileLoader) [0x02092090]} SYS: 'sys_fs_open' failed with 0x80010006 : CELL_ENOENT, “/dev_hdd1/12/a619969ebfb446d566fd129b36b48c5e” [1]
E {PPU[0x100000a] Thread (Core.Res.FileLoader) [0x02092090]} SYS: 'sys_fs_open' failed with 0x80010006 : CELL_ENOENT, “/dev_hdd1/1e/b273bbbff11a67044f136d3351b1c9d3” [1]
E {PPU[0x100000a] Thread (Core.Res.FileLoader) [0x02092090]} SYS: 'sys_fs_open' failed with 0x80010006 : CELL_ENOENT, “/dev_hdd1/0b/0b62fe12fe92ab3fa16ac124eb9e3010” [1]
E {PPU[0x100000a] Thread (Core.Res.FileLoader) [0x02092090]} SYS: 'sys_fs_open' failed with 0x80010006 : CELL_ENOENT, “/dev_hdd1/17/d0bb3397002f1313f3aa97427726ba56” [1]
E {PPU[0x100000a] Thread (Core.Res.FileLoader) [0x02092090]} SYS: 'sys_fs_open' failed with 0x80010006 : CELL_ENOENT, “/dev_hdd1/1d/425af14642ce31d10a8121173feeaf65” [1]
E {PPU[0x100000a] Thread (Core.Res.FileLoader) [0x02092090]} SYS: 'sys_fs_open' failed with 0x80010006 : CELL_ENOENT, “/dev_hdd1/10/a4e8bab7b27874327df916b61ac7e5ee” [1]
E {PPU[0x100000a] Thread (Core.Res.FileLoader) [0x02092090]} SYS: 'sys_fs_open' failed with 0x80010006 : CELL_ENOENT, “/dev_hdd1/04/739e1695a274ff0ca9d340ea9c06fe05” [1]
E {PPU[0x100000a] Thread (Core.Res.FileLoader) [0x02092090]} SYS: 'sys_fs_open' failed with 0x80010006 : CELL_ENOENT, “/dev_hdd1/0b/e9adae4e8a8b1bd483143d043a8470fc” [1]
E {PPU[0x100000a] Thread (Core.Res.FileLoader) [0x02092090]} SYS: 'sys_fs_open' failed with 0x80010006 : CELL_ENOENT, “/dev_hdd1/1c/1c23c583c72e5c2a8d9d6ecdd0a9145e” [1]
E {PPU[0x100000a] Thread (Core.Res.FileLoader) [0x02092090]} SYS: 'sys_fs_open' failed with 0x80010006 : CELL_ENOENT, “/dev_hdd1/21/46698465148d1c6e7fec502bb81db803” [1]
E {PPU[0x100000a] Thread (Core.Res.FileLoader) [0x02092090]} SYS: 'sys_fs_open' failed with 0x80010006 : CELL_ENOENT, “/dev_hdd1/1d/425d5389823e4e658ebf9bb59ae92add” [1]
E {PPU[0x100000a] Thread (Core.Res.FileLoader) [0x02092090]} SYS: 'sys_fs_open' failed with 0x80010006 : CELL_ENOENT, “/dev_hdd1/07/071c4bd8c33c85ef43b86ee5ed423da5” [1]
E {PPU[0x100000a] Thread (Core.Res.FileLoader) [0x02092090]} SYS: 'sys_fs_open' failed with 0x80010006 : CELL_ENOENT, “/dev_hdd1/18/f6569bb12a9976a9df5362742b5fd593” [1]
E {PPU[0x100000a] Thread (Core.Res.FileLoader) [0x02092090]} SYS: 'sys_fs_open' failed with 0x80010006 : CELL_ENOENT, “/dev_hdd1/20/fe9161551a1043596af6a58e64f72f30” [1]
E {PPU[0x100000a] Thread (Core.Res.FileLoader) [0x02092090]} SYS: 'sys_fs_open' failed with 0x80010006 : CELL_ENOENT, “/dev_hdd1/04/986b62ea02ddf3914d4ab4fc8e1c7a24” [1]
E {PPU[0x100000a] Thread (Core.Res.FileLoader) [0x02092090]} SYS: 'sys_fs_open' failed with 0x80010006 : CELL_ENOENT, “/dev_hdd1/05/055df587d53eb0b0136ff69aa4c9e8e4” [1]
S {RSX Decompiler Thread} RSX: New program compiled successfully x4
E {PPU[0x100000a] Thread (Core.Res.FileLoader) [0x02092090]} SYS: 'sys_fs_open' failed with 0x80010006 : CELL_ENOENT, “/dev_hdd1/1e/8d7a02a951d8c6a43da51055d2d2a347” [1]
E {PPU[0x1000000] Thread (main_thread) [0x009e1e70]} SYS: 'sys_cond_wait' failed with 0x00000000 : 0 [1]
E {PPU[0x1000001] Thread ((Dantelion2)PPURuntimeServi) [0x00b5f380]} SYS: 'sys_timer_usleep' failed with 0x00000000 : 0 [1]
E {PPU[0x1000007] Thread (HG_Watchdog) [0x00b5f380]} SYS: 'sys_timer_usleep' failed with 0x00000000 : 0 [1]
E {PPU[0x1000008] Thread (Core.Res.Decompressor) [0x009e1e70]} SYS: 'sys_cond_wait' failed with 0x00000000 : 0 [1]
E {PPU[0x100000c] Thread (hkSpuUtil Helper) [0x010c27e8]} SYS: 'sys_event_queue_receive' failed with 0x00000000 : 0 [1]
E {PPU[0x1000005] Thread (HighGraphics) [0x00b5f380]} SYS: 'sys_timer_usleep' failed with 0x00000000 : 0 [1]
E {PPU[0x1000015] Thread (NexusRevolution Event) [0x00b5f380]} SYS: 'sys_timer_usleep' failed with 0x00000000 : 0 [1]
E {PPU[0x100000b] Thread (Core.Res.TaskManager) [0x009e1e70]} SYS: 'sys_cond_wait' failed with 0x00000000 : 0 [1]
E {PPU[0x100000d] Thread (Havok PPU Thread) [0x015ca058]} SYS: 'sys_cond_wait' failed with 0x00000000 : 0 [1]
E {PPU[0x1000012] Thread (_sys_mixerSurBusReq) [0x01546aec]} SYS: 'sys_cond_wait' failed with 0x00000000 : 0 [1]
E {PPU[0x1000006] Thread (_gcm_intr_thread) [0x01fc833c]} SYS: 'sys_event_queue_receive' failed with 0x00000000 : 0 [1]
E {PPU[0x1000052] Thread (ChrInsManThread::Thread) [0x009e1e70]} SYS: 'sys_cond_wait' failed with 0x00000000 : 0 [1]
E {PPU[0x1000017] Thread (NexusRevolution Main) [0x00b5f380]} SYS: 'sys_timer_usleep' failed with 0x00000000 : 0 [1]
E {PPU[0x100001b] Thread (FXHGDrawEntityTracer) [0x009e1e70]} SYS: 'sys_cond_wait' failed with 0x00000000 : 0 [1]
E {PPU[0x1000019] Thread (SLSession) [0x00b0c05c]} SYS: 'sys_semaphore_wait' failed with 0x00000000 : 0 [1]
E {PPU[0x100000e] Thread (MOMainThread) [0x00b5f380]} SYS: 'sys_timer_usleep' failed with 0x00000000 : 0 [1]
E {PPU[0x1000016] Thread (NexusRevolution Surveillanc) [0x00b5f380]} SYS: 'sys_timer_usleep' failed with 0x00000000 : 0 [1]
E {PPU[0x1000002] Thread ((Dantelion2)SPURuntimeServi) [0x00c5f560]} SYS: 'sys_event_queue_receive' failed with 0x00000000 : 0 [1]
E {PPU[0x1000009] Thread (Core.Res.CacheDeviceHandler) [0x009e1e70]} SYS: 'sys_cond_wait' failed with 0x00000000 : 0 [1]
E {PPU[0x1000014] Thread (MOStreamingThread) [0x01554230]} SYS: 'sys_timer_usleep' failed with 0x00000000 : 0 [1]
E {PPU[0x100000f] Thread (MOMixerThread) [0x00b0c05c]} SYS: 'sys_semaphore_wait' failed with 0x00000000 : 0 [1]
E {PPU[0x100001c] Thread (FaceGenMan::Thread) [0x009e1e70]} SYS: 'sys_cond_wait' failed with 0x00000000 : 0 [1]
E {PPU[0x1000003] Thread (DLSpursManagerSpursHdlr1) [0x01feb604]} SYS: 'sys_event_queue_receive' failed with 0x00000000 : 0 [1]
E {PPU[0x100000a] Thread (Core.Res.FileLoader) [0x009e1e70]} SYS: 'sys_cond_wait' failed with 0x00000000 : 0 [1]
E {PPU[0x1000013] Thread (_cellsurMixerMain) [0x01549ec4]} SYS: 'sys_event_queue_receive' failed with 0x00000000 : 0 [1]
E {PPU[0x1000010] Thread (spu_printf_handler) [0x01551308]} SYS: 'sys_event_queue_receive' failed with 0x00000000 : 0 [1]
E {PPU[0x100001a] Thread (_fs_aio_thread) [0x0209f17c]} SYS: 'sys_cond_wait' failed with 0x00000000 : 0 [1]
E {PPU[0x100001d] Thread (DsTrophyMan::AsyncUpdateThr) [0x009e1e70]} SYS: 'sys_cond_wait' failed with 0x00000000 : 0 [1]
E {PPU[0x1000053] Thread (ChrProxyThreadMan::Thread) [0x009e1e70]} SYS: 'sys_cond_wait' failed with 0x00000000 : 0 [1]
E {PPU[0x1000004] Thread (DLSpursManagerSpursHdlr0) [0x01fe948c]} SYS: 'sys_spu_thread_group_join' failed with 0x00000000 : 0 [1]
E {PPU[0x1000000] main_thread } SYS: Stat: 'sys_ppu_thread_detach' failed with 0x80010005 : CELL_ESRCH [x15]
E {PPU[0x1000011] Thread (_sys_MixerChStripMain) [0x0154e5a4]} SYS: 'sys_cond_wait' failed with 0x00000000 : 0 [1]
E {PPU[0x1000013] _cellsurMixerMain } SYS: Stat: '_sys_lwmutex_lock' failed with 0x80010005 : CELL_ESRCH [x1488376]
E {PPU[0x1000011] _sys_MixerChStripMain } SYS: Stat: '_sys_lwmutex_lock' failed with 0x80010005 : CELL_ESRCH [x2976752]
E {PPU[0x1000013] _cellsurMixerMain } SYS: Stat: 'sys_mutex_lock' failed with 0x80010008 : CELL_EDEADLK [x372082]

my rig: 
8700K
16 gb ram
gtx 1070
SSD
everything is up to date

any help would be much appreciated. thanks!

**Comment by RainbowCookie32** [comment] 2020-11-11 18:18
Missing build that introduced the issue and a proper log. Might be a duplicate of #9238 

Please read [the issue template](https://github.com/RPCS3/rpcs3/blob/master/.github/ISSUE_TEMPLATE/1-regression-report.md) when opening an issue.

**Comment by SmoKeFather** [comment] 2020-11-11 18:31
ok, i hope this will help:

RPCS3 Version: 0.0.13-829a697c Alpha

[RPCS3.log.gz](https://github.com/RPCS3/rpcs3/files/5526011/RPCS3.log.gz)

**Comment by RainbowCookie32** [comment] 2020-11-11 19:46
Check if 0.0.13-11212 works (you can get old builds [here](https://rpcs3.net/compatibility?b)). If it does, then this issue it's a duplicate of #9238

**Comment by SmoKeFather** [comment] 2020-11-11 20:06
try it right now

**Comment by garballax** [comment] 2020-11-11 20:41
Greetings! I've run in to the same trouble with freezes/crashes in v0.0.13-11222-829a697c and can confirm that the issue does not occur in v0.0.13-11205. Thank you everyone! 
[RPCS3.log.gz](https://github.com/RPCS3/rpcs3/files/5526612/RPCS3.log.gz)

**Comment by RainbowCookie32** [comment] 2020-11-11 20:41
Another duplicate of #9238 then, close.

**Comment by SmoKeFather** [comment] 2020-11-11 21:05
so i just killed the first boss and so far it seems to work. if anything changes i will come back and post again. thanks for your help!

**Closed** 2020-11-11 21:25 UTC
