### ISSUE TITLE
RPCS3 no longer opening after 9366

### ISSUE THREAD

**Issue by TheNewClassics** [RPCS3/rpcs3#7279] opened 2020-01-18 19:13 UTC
Hey RPCS3 team, I'd like to report a possible regression with more recent updates. I recently was using version 0.0.8-9366 and attempted to update through the auto updater yesterday to version 9396. RPCS3 no longer opens, but instead stays in the Task manager. No log is generated. I was able to revert back to 9366 which does still work for me.

I read some previous troubleshooting about the video drivers/entries possibly hanging, so I used DDU to uninstall and reinstall my GeForce drivers after updating, but it still did not open. If there's any place I can look to provide more info that might help troubleshoot, please let me know. Thanks

**Comment by RainbowCookie32** [comment] 2020-01-18 19:17
Probably a duplicate of #7243

**Comment by TheNewClassics** [comment] 2020-01-18 20:28
You were definitely right; deleted the bearer folder and now it works. Thanks for the quick help

**Comment by RainbowCookie32** [comment] 2020-01-18 20:30
You can close the issue now. You should try asking in Discord next time before opening an issue, there's usually someone around to help

**Closed** 2020-01-18 20:46 UTC
