### ISSUE TITLE
Regression : Virtua Fighter 5:FS 

### ISSUE THREAD

**Issue by fenix008** [RPCS3/rpcs3#2171] opened 2016-09-28 06:54 UTC
Okay...after this commit https://github.com/RPCS3/rpcs3/pull/2161  Virtua Fighter 5:FS doesn't work anymore (in dojo mode: after character selection I can't choose arena stage; in arcade mode: after char. selection just infinite loading(I waited ~25 mins))

**Comment by kd-11** [comment] 2016-09-28 17:15
Is the game still going in the background and only invisible? If so, face culling is really broken and requires more tests.

**Comment by fenix008** [comment] 2016-09-28 18:49
In dojo: when I need choose the arena, there's just playing music and I can't see arenas for choose (even after I waited ~15 mins).
I just can't get gameplay...anyway.

**Comment by fenix008** [comment] 2016-09-29 15:35
Hmm, arcade mode works now, but it's toooooo slow. I have waited for loading *40* mins and it's run.

**Comment by kd-11** [comment] 2016-09-29 15:43
That pull request (https://github.com/RPCS3/rpcs3/pull/2161) does not affect performance or gameplay, it was to properly cull faces. If it affected your game, you'd still be able to play, just that characters would look wierd. Broken face culling looks like this: https://github.com/RPCS3/rpcs3/pull/1927#issuecomment-233192788

**Comment by fenix008** [comment] 2016-09-29 15:56
Maybe I'm not right, but after this (2161) commit, this game loads level ~40 mins instead ~5 mins.

But it's just my opinion.

**Comment by kd-11** [comment] 2016-09-29 16:00
Try deleting the data folder in the rpsc3 directory. It might help although you may lose some app data.

**Comment by fenix008** [comment] 2016-09-29 17:25
The same...
And dojo mode working too, I just waited for 20 mins.

**Comment by kd-11** [comment] 2016-09-29 17:32
Something else is up with that game then. Loading times are usually affected by cpu side changes, and gpu caching, but that has not been touched recently. 20 mins is abit much though. Maybe just change the title to show the issue is not with graphics, but loading time.

**Comment by Nezarn** [comment] 2016-09-29 18:16
@kd-11 @fenix008 if i need to guess, this game has some threading issue just as Project Diva F 2nd, and also aside from the slow loading, i didn't noticed the issues stated up above.

The only issue aside from slow loading is that it looks the same as the dreamy theater games (for those there are already an issue and kd-11 you said its a shader bug)

Also my loading time was ~13 min with LLVM (with interpreter its much slower) from choosing characters -> ingame

![rpcs3_2016-09-29_20-13-35](https://cloud.githubusercontent.com/assets/3817985/18966424/62227368-8681-11e6-9f63-59b073d42508.png)

**Comment by fenix008** [comment] 2016-09-29 18:54
Yeah, here's more like loading time problem. Thread about it already exist or this thread can be renamed for it?
...textures bug (or face culling, idk), as Nezarn said, Project Diva F2nd has it and maybe will be fixed in the near future.

**Comment by RainKikyou** [comment] 2016-10-11 09:19
This is the current graphics, has improved.load time is really long, should use llvm to get a better frame rate and load speed
![qq 20161011171617](https://cloud.githubusercontent.com/assets/20301499/19265124/6ec7b6ec-8fd6-11e6-8125-367ecb24f6aa.jpg)
![qq 20161011171256](https://cloud.githubusercontent.com/assets/20301499/19265159/90ea4172-8fd6-11e6-87b5-4a6835508e2d.jpg)

**Comment by fenix008** [comment] 2016-10-11 14:54
O M G! Good progress! <3
It's not freezing after 3-5 seconds on gameplay on Vulkan render?

**Comment by fenix008** [comment] 2016-10-12 00:34
Hhm, okay. I checked it on windows 10 and it's not freezing, but it's freezing on windows 7 (Vulkan render).

**Comment by fenix008** [comment] 2016-10-18 21:24
ooh god, it's almost perfect on OpenGL now!
![ss 2016-10-19 at 12 25 55](https://cloud.githubusercontent.com/assets/4106942/19496904/68e7b648-9592-11e6-8501-17b9ec5aa7e1.jpg)

**Comment by RainKikyou** [comment] 2016-10-19 04:57
yes， almost perfect.
the problem is still not loaded too long repair
vullkan video https://youtu.be/lJiKBa8VGYY

**Comment by RainKikyou** [comment] 2016-10-21 11:34
Oc to 4.4GHZ can improve a lot of 40fps,  use llvm can 50fps + 
![qq 20161021191026](https://cloud.githubusercontent.com/assets/20301499/19597152/5da84b1e-97c5-11e6-80df-cdb01cd2adc4.jpg)
![qq 20161021192546](https://cloud.githubusercontent.com/assets/20301499/19597154/63aa8eb4-97c5-11e6-891b-295aa8bb54da.jpg)

**Comment by Nezarn** [comment] 2016-10-21 11:51
@RainKikyou that still doesn't change the fact that it should run better and theres an issue somewhere like in Dremy Theater games.

**Comment by RainKikyou** [comment] 2016-10-21 11:56
Yes, graphics and load time problem

**Comment by raven02** [comment] 2017-01-28 04:54
i'm closing this one and will open a new one to be more specific on the graphics and load time issue.

**Closed by raven02** 2017-01-28 04:54 UTC
