### ISSUE TITLE
[Regression] UFC 3 - graphical artifacts and missing textures

### ISSUE THREAD

**Issue by FaraondalekiegoEgiptu** [RPCS3/rpcs3#14583] opened 2023-08-30 16:21 UTC
### Quick summary

When i played UFC Undisputed 3 three days ago everything was okay ... Today i decided to update my RPCS3 to newest version and game didin't launch ... After few minutes of waiting on title screen i turn off and on my PC and game started. I think that is normal case when i use emulator but no, game start only when i want to launch RPCS3 like first apllication wchich i use on my computer after start. When i staryed exhibition match a lot of red artifacts was spotted on the ground, something like blood or tomato souce buut it wasn't clear and i can see single pixels on that ... In game i have second problem too, when i play i cant see blood on character faces and sweat. It's visible only in replay. Game run much slower than before too, a few days ago i played in 60 FPS and game was very fluid, now after 2/3 minutes of playing game runs slower in 17-25 FPS.

### Details

UFC 3 don't launch
Game launch only when i turn RPCS3 on like first aplication on my PC
Game loading is very long
In game i can see a lot of graphical artifacts which i didn't see before
Game is much slower than before, perfect 60 FPS was changed on 27 FPS in higheest momeents :/

### Build with regression

RPCS3 Version: 0.0.29-15556-02b5cae2 Alpha | master

### Attach two log files

[RPCS3.log](https://github.com/RPCS3/rpcs3/files/12477908/RPCS3.log)
[RPCS3.log.gz](https://github.com/RPCS3/rpcs3/files/12477911/RPCS3.log.gz)

### System configuration

RTX 3070
i910900F 2,8 Ghz
32 GB RAM

**Comment by kd-11** [comment] 2023-08-30 22:22
It would be helpful if you could let us know the last build that worked well for you. Luckily if it only broke in the last few days there shouldn't be many versions to test.

**Comment by AniLeo** [comment] 2023-09-02 04:01
Invalid regression report, missing last good build, both log files are from the same version.

**Comment by AniLeo** [comment] 2024-01-01 16:18
Closing as invalid since the issue is still incomplete after 4 months

**Closed by AniLeo** 2024-01-01 16:18 UTC
Labels: Need Information
