### ISSUE TITLE
DX12/GL/Vulkan : Eiyuu Densetsu: Sen no Kiseki - missing background rendering

### ISSUE THREAD

**Issue by lightfirst** [RPCS3/rpcs3#2379] opened 2017-02-13 11:43 UTC
the miss 3D graphics can found by RenderDoc
![san](https://cloud.githubusercontent.com/assets/4612168/22882006/0ea6ce32-f224-11e6-8e69-5c13cd0090dd.PNG)

**Comment by lightfirst** [comment] 2017-02-13 12:14
screenshot from my PS3: ![tv_cam_ _20170213_201211 003](https://cloud.githubusercontent.com/assets/4612168/22883000/eedb7cba-f228-11e6-822f-6e303ef22270.jpg)

**Comment by kd-11** [comment] 2017-02-13 13:12
This is a known issue and is likely caused by broken buffer synchronization support. I have a work-in-progress branch, but haven't submitted it yet due to some bugs/regressions introduced to the texture cache. Should be resolved in a few days.

**Comment by scribam** [comment] 2017-08-04 11:50
@lightfirst Any progress with the latest build?

**Closed** 2017-08-04 11:57 UTC
Labels: Render: Direct3D 12, Render: OpenGL, Render: Vulkan
