### ISSUE TITLE
Crashes on Modern Linux (Wayland)

### ISSUE THREAD

**Issue by iMonZ** [RPCS3/rpcs3#10738] opened 2021-08-21 11:18 UTC
## Quick summary
Sadly,

 the game crashes on Modern Linux versions, since the display server has been changed to Wayland from X11

## Details
Running this tool with the Wayland display server crashes after running a game

Workaround:
Temporary until the Legacy X11 display server is still installed as a backup, you can set this environment variable: "QT_QPA_PLATFORM=xcb" after that the game will run

#### 1. Please attach RPCS3's log.
[RPCS3.log](https://github.com/RPCS3/rpcs3/files/7025392/RPCS3.log)

> 
> Debugger: 0
> Failed to set RLIMIT_MEMLOCK size to 2 GiB. Try to update your system configuration.
> QSocketNotifier: Can only be used with threads started with QThread
> QApplication: invalid style override 'kvantum' passed, ignoring it.
> 	Available styles: Adwaita-Dark, Adwaita, Breeze, Windows, Fusion
> MESA-INTEL: warning: Ivy Bridge Vulkan support is incomplete
> ATTENTION: default value of option mesa_glthread overridden by environment.
> ATTENTION: default value of option force_integer_tex_nearest overridden by environment.
> ATTENTION: option value of option mesa_glthread ignored.
> libpng warning: iCCP: known incorrect sRGB profile
> sh: line 1: xdg-mime: command not found
> libpng warning: iCCP: known incorrect sRGB profile
> MESA-INTEL: warning: Ivy Bridge Vulkan support is incomplete
> libpng warning: iCCP: known incorrect sRGB profile
> The Wayland connection experienced a fatal error: Protocol error

#### 2. Please provide your system configuration:

    SYS: RPCS3 v0.0.17-1-62102293 Alpha | master
    SYS: Intel(R) Core(TM) i7-3770 CPU @ 3.40GHz | 8 Threads | 15.51 GiB RAM | TSC: 3.400GHz | AVX
    SYS: Operating system: POSIX, Name: Linux, Release: 5.13.11-1-MANJARO, Version: 1 SMP PREEMPT Sun Aug 15 13:15:18 UTC 2021
         Display Server: Wayland
    RSX: Found vulkan-compatible GPU: 'Intel(R) HD Graphics 4000 (IVB GT2)' running on driver 21.1.4
    RSX: Found vulkan-compatible GPU: 'AMD RADV POLARIS10 (ACO)' running on driver 21.1.4
    SYS: Firmware version: 4.88

**Comment by kd-11** [comment] 2021-08-21 14:25
Duplicate of https://github.com/RPCS3/rpcs3/issues/9882

**Closed by kd-11** 2021-08-21 14:25 UTC
Labels: OS: Linux
