### ISSUE TITLE
PSF error when running games

### ISSUE THREAD

**Issue by Ekaseo** [RPCS3/rpcs3#1704] opened 2016-05-23 14:32 UTC
{PPU[0xce] Thread (NisSaveData_SystemLoad_Thread) [0x0039b86c]} class std::runtime_error thrown: Precondition failed: stream.read(value, indices[i].param_len)
(in file C:\rpcs3\rpcs3\Loader\PSF.cpp:151)

**Comment by Ekaseo** [comment] 2016-05-24 22:18
looks like there are some issues loading bigger games for some reason

**Comment by Nekotekina** [comment] 2016-05-26 19:48
Some PARAM.SFO files (savedata) could get damaged by #1696. I'm really sorry about that. You can try to delete savedata or restore only PARAM.SFO from the correct one and test again. Tell if the problem persists.

**Comment by Ekaseo** [comment] 2016-05-26 21:35
:/ , some games hang trying to load into the main menu, some in main menu after you press start, some when you select an option from main menu to go ingame, and some dont load the game files and the loading screen goes on without loading anything... (i deleted all my save files)

**Comment by Nekotekina** [comment] 2016-06-15 21:21
I think some other issues got mixed there.

**Comment by AniLeo** [comment] 2017-02-18 21:24
@Ekaseo Does the PSF error still persist?

**Comment by AniLeo** [comment] 2017-04-15 22:57
Closing since it never was reported as happening again.

**Closed by AniLeo** 2017-04-15 22:57 UTC
Labels: bug

**Comment by Zangetsu38** [comment] 2017-04-15 23:06
yes, resogun no change

**Comment by AniLeo** [comment] 2017-04-15 23:07
Resogun has the error mentioned there or is it a different one? I remember it would work just fine all the way Ingame

**Comment by Zangetsu38** [comment] 2017-04-15 23:08
no, have regression, now not works
 >·W 0:00:42.055306 {PPU[0x1000000] Thread (main_thread) [0x0096ace8]} cellSaveData: cellSaveDataAutoLoad2(version=1, dirName=“NPEA00433_00_SAVEDATA”, errDialog=0, setBuf=*0xd00fe5d4, funcStat=*0x996458, funcFile=*0x996460, container=0xffffffff, userdata=*0x25364c80)
·W 0:00:42.120535 {PPU[0x1000000] Thread (main_thread) [0x0096ace8]} PPU: 'cellSaveDataAutoLoad2' aborted
·! 0:00:42.120732 {PPU[0x1000000] Thread (main_thread) [0x0096ace8]}
·F 0:00:42.120787 {PPU[0x1000000] Thread (main_thread) [0x0096ace8]} class std::runtime_error thrown: Verification failed:
(in file C:\rpcs3\rpcs3\Loader\PSF.cpp:118)

**Comment by AniLeo** [comment] 2017-04-15 23:11
Oh that's another error on PSF though, I believe there's an issue for that one

**Comment by Zangetsu38** [comment] 2017-04-15 23:42
ok works after delete save
