### ISSUE TITLE
Guitar Hero Metallica [BLUS30257] VRAM Issue When Scaled to 4k with Vulkan

### ISSUE THREAD

**Issue by MrEWhite** [RPCS3/rpcs3#8191] opened 2020-05-12 02:55 UTC
## Quick summary
When using 3840x2160 resolution scale (300%) on Vulkan, GH Metallica quickly uses up all VRAM on my RTX 2080 Ti, slows down, then crashes. This doesn't occur on OpenGL, but the performance is worse on OpenGL, dropping below 60 a lot. This also does not occur at lower resolution scales such as 200%.

## Details

[RPCS3.log](https://github.com/RPCS3/rpcs3/files/4613119/RPCS3.log)

https://youtu.be/VRoLVU0vqyc Here's a video of the issue occurring.

**Comment by AniLeo** [comment] 2020-05-12 04:23
> MSAA: Auto

OpenGL doesn't have MSAA implemented, so you're comparing an MSAA Off vs MSAA On test, which is normal

Ping for reopening if you can reproduce big performance drop on Vulkan with MSAA Off

**Comment by AniLeo** [comment] 2020-05-12 04:25
Actually, the memory leak issue is not due to MSAA, and I've already stumbled upon a similar bug on GH which was fixed in the past

**Comment by kd-11** [comment] 2020-07-08 15:32
Retest and update.

**Comment by MrEWhite** [comment] 2020-07-25 18:15
> Retest and update.

Just gave it a shot and it works fine now!

**Comment by kd-11** [comment] 2020-07-25 18:19
Possibly fixed by https://github.com/RPCS3/rpcs3/pull/8618

**Closed by kd-11** 2020-07-25 18:19 UTC
