### ISSUE TITLE
[Regression] Games with empty root folder be loaded anymore after #8835

### ISSUE THREAD

**Issue by QuaiGoner** [RPCS3/rpcs3#8896] opened 2020-09-12 04:11 UTC
Broken after PR #8835
[RPCS3.log](https://github.com/RPCS3/rpcs3/files/5212170/RPCS3.log)

Here i am trying to load a repack of mine of Call of Duty classic + russian language from pc version packed in an iso. I am mounting iso via powershell script or simply by double clicking on an iso of a game (i keep all of my backups that way to play from FTP server). ISO is mounted in virtual BD-ROM and rpcs3 cant launch a game from that directory.
![Снимок](https://user-images.githubusercontent.com/41058180/92986973-b71de080-f4e8-11ea-83fb-0ca9d2929cfa.PNG)

**Comment by bevanweiss** [comment] 2020-09-12 04:22
I feel that you skipped over the whole Issue Template
You're missing this part
#### 2. Please attach TWO logs:
* One for the build with regression.
* One for the build that works as expected.

and this.  You've been told the likely problem is filename case sensitivity, so when you do a filename comparison between the PS3 disc, and your ISO contents, what does it show.. do all the filenames match (down to the case of each letter)?
#### 5. Please provide comparison with real PS3.

and this
#### 6. Please provide your system configuration:
* OS
* CPU
* GPU
* Driver version
* etc.

**Comment by elad335** [comment] 2020-09-12 04:36
Can someone tests what happens if you move the entire game to an empty real drive and try to boot by selecting the drive.

**Comment by shockdude** [comment] 2020-09-12 04:59
> 
> 
> Can someone tests what happens if you move the entire game to an empty real drive and try to boot by selecting the drive?
Copied a PS3 game to a ramdisk
0.0.12-10857 - game boots fine. [RPCS3_10857.log.gz](https://github.com/RPCS3/rpcs3/files/5212213/RPCS3_10857.log.gz)
0.0.12-10858 - game fails to boot. [RPCS3_10858.log.gz](https://github.com/RPCS3/rpcs3/files/5212214/RPCS3_10858.log.gz)
![image](https://user-images.githubusercontent.com/27760396/92987710-ee08dd80-f479-11ea-95b7-814bcf54b432.png)

**Comment by QuaiGoner** [comment] 2020-09-14 11:15
So basically we cant load games from a different drive anymore

**Comment by roger-** [comment] 2020-09-16 18:51
Same issue with verified ISOs on Windows 10 -- worked fine after mounting with 0.0.11 but fails with 0.0.12.

**Comment by Untz64** [comment] 2020-09-17 16:28
Just echoing the others here, unable to play any mounted .iso files. Verified working with 0.0.12-10857, regression is somewhere between that and 0.0.12-10891

**Comment by Z3USI0TA** [comment] 2020-09-18 14:20
hi. i tested and i did ISO file working.

1 - Game No Works in Last RPCS3. 
I create ISO File with game in root of ISO.
-Load ISO in D:\
D:\PS3_Game
D:\PS3_UPDATE
D:\PS3_DISC.SFB

2 - Game Works in Last RPCS3.
I create ISO File with game no in root of ISO.
-Load ISO in D:\
D:\Game\PS3_Game
D:\Game\PS3_UPDATE
D:\Game\PS3_DISC.SFB

I writon a old  code with this problem. i believe what the error happen because:
1 - File ISO in Root = load folder D: [without \]
2 - File ISO Game out Root = load folder D:\Game\

here, RPCS3  error if game in root hdd too. C:\ or  D:\

**Comment by elad335** [comment] 2020-09-20 17:31
Fixed by #8940

**Closed** 2020-09-21 03:35 UTC
