### ISSUE TITLE
Tekken Tag Tournament 2 RPCS3 - BLACK SCREEN ONLY

### ISSUE THREAD

**Issue by finecolors** [RPCS3/rpcs3#6022] opened 2019-05-26 10:46 UTC
OpenGL 4.3 - Windows 7 64 bit
Processor: Intel Core i3-4030U CPU @ 1.90 GHz 
I got this message--
E {RSX Decompiler Thread} RSX: Failed to compile shader: ERROR: 0:189: 'tex00' : undeclared identifier
![rpcs3](https://user-images.githubusercontent.com/51047845/58380676-8873b200-7fe6-11e9-9e12-295d156fe4fd.png)
![rpcs3 2](https://user-images.githubusercontent.com/51047845/58380683-932e4700-7fe6-11e9-8d45-03b49f42470a.png)

[RPCS3.log](https://github.com/RPCS3/rpcs3/files/3220215/RPCS3.log)

**Comment by 13xforever** [comment] 2019-05-26 10:48
Please don't use broken pirated copies, and definitely do not file false reports with them.

**Comment by finecolors** [comment] 2019-05-26 10:54
what broken pirated copies? I just screenshot the pictures that's why it's not HD

**Comment by finecolors** [comment] 2019-05-26 10:56
> Please don't use broken pirated copies, and definitely do not file false reports with them.

what broken pirated copies? I just screenshot the pictures that's why it's not HD

**Comment by 13xforever** [comment] 2019-05-26 11:01
1. it's a duplicate of #5690
2. you're using a broken pirated copy of the game
3. you don't have an ounce of common sense

please close this issue and remove the log

**Comment by AniLeo** [comment] 2019-05-26 11:45
what the fuck

**Closed by AniLeo** 2019-05-26 11:45 UTC
