### ISSUE TITLE
Remaining regressions from FBO_Fixes #5427

### ISSUE THREAD

**Issue by Asinin3** [RPCS3/rpcs3#5739] opened 2019-03-19 07:11 UTC
Original report: https://github.com/RPCS3/rpcs3/issues/5514#issuecomment-454017986

Assassins Creed Rogue is still crashing when using OpenGL when I press start during the Intro sequence (about 5seconds after the game starts) on the latest build of RPCS3. Resulting in this error: `·F 0:08:41.258704 {RSX [0x040c634]} RSX: class std::runtime_error thrown: Unhandled GL format 0x8058
(in file c:\projects\rpcs3\rpcs3\emu\rsx\gl\glhelpers.h:1610)`
Note: on my original report on an older build directly after FBO_Fixes merged the error was on line 1611 not 1610.

Sly Cooper Thieves in Time also still has issues with the smoke, but this time it looks quite a bit different on the latest builds of RPCS3.

Before FBO_Fixes
![7658beforefbo_2019-01-15_4134](https://user-images.githubusercontent.com/15137035/51135489-10280380-1832-11e9-9a26-45227ab299ca.jpg)

After FBO_Fixes
![image](https://user-images.githubusercontent.com/15137035/51135688-87f62e00-1832-11e9-88de-9bea31a00e45.png)

On latest master
https://my.mixtape.moe/gxaoey.mp4
Renderdoc 1.2 + OpenGL
https://mega.nz/#!7YRjWK7S!PkEkqCc1f0_o7_A1NYEo0nm0oUqIy_GHDijaqjAREfo

**Comment by kd-11** [comment] 2019-03-19 08:38
Sly cooper fixed by https://ci.appveyor.com/project/kd-11/rpcs3/builds/23182024

**Comment by Asinin3** [comment] 2019-03-19 12:00
Confirmed, will close when that PR merges. 
![image](https://user-images.githubusercontent.com/15137035/54604378-83badc80-4a3e-11e9-868b-9cfa3c28d967.png)

**Comment by legend800** [comment] 2019-03-19 15:32
Motorstorm Apoc still has the weird border issues:
![2019-03-19 08_27_39-Window](https://user-images.githubusercontent.com/20983844/54618901-046ae000-4a21-11e9-8427-7601a99556fb.png)
![2019-03-19 08_27_53-Window](https://user-images.githubusercontent.com/20983844/54618902-046ae000-4a21-11e9-8de2-d9c295345e72.png)
[RPCS3.log.gz](https://github.com/RPCS3/rpcs3/files/2984130/RPCS3.log.gz)

**Comment by Emulator-Team-2** [comment] 2019-03-19 16:10
@legend800 
You should post this here:
https://github.com/RPCS3/rpcs3/issues/5708

Because this issue is opened for regression after #5427.

**Comment by kd-11** [comment] 2019-03-19 19:59
Removed off-topic comments. This is about the original fbo fixes PR (actually named FBO fixes)

**Closed** 2019-03-20 07:05 UTC
