### ISSUE TITLE
[Demon's Souls] Lighting fails to apply to some surfaces

### ISSUE THREAD

**Issue by Nicholas-Steel** [RPCS3/rpcs3#10152] opened 2021-04-19 11:12 UTC
## Quick summary
shadow/lighting no longer works correctly in some situations.

#### Details
some surfaces seem to become dark as though they're no longer affected by light sources. Shifting camera angle causes lighting to either affect or not affect the surfaces.
Video demonstration: https://youtu.be/nhhVJi3Xo2M
Also at the start of 1-1, pan the camera in a circle around you and one of the cliff faces will have the same issue.

#### 1. Please provide _exact_ build (or commit) information that introduced the regression you're reporting.
I... can not recall when the problem was first noticed. I haven't been actively playing the game for a long time now and there have been many, many updates to RPCS3 since I last played.

#### 2. Log File
[RPCS3.log.gz](https://github.com/RPCS3/rpcs3/files/6335453/RPCS3.log.gz)

#### 3. If you describe graphical regression, please provide an RSX capture and a RenderDoc capture that demonstrate it.
Hmmm... I really don't want to but if I must than please let me know.

#### 4. Please provide your system configuration:
* Windows 10 (latest stable release)
* Ryzen 3700X
* Geforce 1070Ti
* 465.89

#### 5. Other
Redundant configuration settings were removed from the Global and Game Specific settings by a recent release of RPCS3.
Start of Area 2-1 in Demon's Souls.

**Comment by Nicholas-Steel** [comment] 2021-04-19 11:13
Does... that first message apply to my report? I completely glossed over that D:

**Comment by kd-11** [comment] 2021-04-19 13:00
1. Proof video is inaccessible (private)
2. Try to find the first broken build, or at least narrow it down. Action can not be taken until a broken build is identified.
3. Disable patches when doing regression tests. This ensures the exact code that runs on PS3 is running on RPCS3. I can see some patches are active in your log.

**Comment by Nicholas-Steel** [comment] 2021-04-19 13:37
I can already confirm the issue persists without patches.

**Comment by Nicholas-Steel** [comment] 2021-04-19 13:56
The smoke effect from the Thiefs Ring suffers the same issue. At certain camera angles relative to you the smoke will vanish.

**Comment by DerTodIstEinDandy** [comment] 2021-04-28 22:59
I can confirm the issue exists, and it looks like it was intoduced in #9377
The first affected build for me is rpcs3-v0.0.13-11347

Tested it on Windows 10, Ryzen 5 2600, RTX 2060 with 461.40 drivers

**Comment by kd-11** [comment] 2021-05-12 22:05
Thanks for testing. I have a fix for this, but it is one of those that requires a mini-redesign of a lot of code to get it working right.

**Comment by kd-11** [comment] 2021-05-15 18:16
This is fixed by https://github.com/RPCS3/rpcs3/pull/10285

**Closed** 2021-05-15 20:51 UTC
Labels: In Progress
