### ISSUE TITLE
Error MEM: Access violation writing location in Tekken 5 Dark Ressurection

### ISSUE THREAD

**Issue by Luffykun007** [RPCS3/rpcs3#3639] opened 2017-10-24 04:22 UTC
I am having this access violation error in the game Tekken 5 Dark ressurection in RPCS3, the game starts normally but when it will arrive in the game on the Versus screen  the error happens ... sometimes the sound only fails but I can enter the game but sometimes freezes completely.

![capturar3](https://user-images.githubusercontent.com/26087621/31924637-af896144-b861-11e7-8693-74ead4b23653.JPG)

My Specs:

i5 6400 + GTX 960.
Windows 10 Pro 64 Bits 

Log: [Tekken 5 Dark ressurection.zip](https://github.com/RPCS3/rpcs3/files/1409509/Tekken.5.Dark.ressurection.zip)

**Comment by Asinin3** [comment] 2017-10-24 04:25
Access violations are a very generic error, lot's of things can cause them. Many issues have been closed in the past which were reporting access violations as it's not really helpful for the devs. A recent example: https://github.com/RPCS3/rpcs3/issues/3583 so you can probably close this.

**Comment by AniLeo** [comment] 2017-10-25 21:18
Access violations are very generic errors that can be caused by nearly everything, needs further debugging to find the cause.

Anyways, read the guidelines when opening a future issue, as you didn't provide a proper log here (not that a log file would help in this scenario).

**Closed by AniLeo** 2017-10-25 21:18 UTC
