### ISSUE TITLE
Fist of the North Star: Ken’s Rage 2 BLES01801 0.0.18-12718 crash when loading save data

### ISSUE THREAD

**Issue by Augusto7743** [RPCS3/rpcs3#10850] opened 2021-09-11 02:27 UTC
When starting is displayed below the image1 to choice what save data to load and when finishing a stage what save data to save in image2.
That problem is random and will crash the emulator in both screens.
Another detail is if the trophy folder is deleted not happen that problem.
Also is happen problem when opening trophies because the user open an trophy and is opened an wrong trophy example finish stage 1 not is opened trophy finished stage 1 instead open another random trophy.

![1](https://user-images.githubusercontent.com/21184987/132933811-c137f7b1-4b6d-436f-9242-db11a2ecbbfb.jpg)

![2](https://user-images.githubusercontent.com/21184987/132933817-712f1ce6-d31e-4918-87f0-8bceaa7462f4.jpg)

[RPCS31.log](https://github.com/RPCS3/rpcs3/files/7147117/RPCS31.log)

**Comment by Augusto7743** [comment] 2021-09-11 02:29
file:///tmp/1.jpg

**Comment by Megamouse** [comment] 2021-09-11 07:53
Duplicate of your own issue.
Duplicate of #9584

**Closed by Megamouse** 2021-09-11 07:53 UTC

**Comment by Augusto7743** [comment] 2021-09-14 11:24
another wrong close.
That also not is exactly related with the "duplicate".
The duplicate is about changing UI settings.
Here that issue happen in other way.
