### ISSUE TITLE
DLC Crash.

### ISSUE THREAD

**Issue by dawnbomb** [RPCS3/rpcs3#5736] opened 2019-03-18 21:05 UTC
Posting this because i feel the issue doesn't have enough presence, despite it being up over and over again for a few months over discord, not only by me, but by many people, and hoping we can get someone to actually look at solving it. 

In both Xillia 1, and Xillia 2, (and a few other games) having more then 16 DLC folders installed at one time causes the game to crash at the title screen, and give the following error.

F {PPU[0x1000000] Thread (main_thread) [0x01012094]} MEM: Access violation reading location 0x0

because DLC has a 00 folder, having up to including DLC folder 16 installed, causes it to crash. there is something like 70ish DLC folders, and using any combinations, ect does not fix the problem. the issue has been reproduced by practically everyone who has ever tried to run the game with dlc, as it's kind of hard not to do on accident because of so much free dlc. 

Version of rpcs3 used: 0.0.6-7869-e9b6bead Alpha
CPU: Intel(R) Core(TM) i7-3930K CPU @ 3.20GHz  (actually overclocked to 4.2)
GPU: NVIDIA GeForce GTX 1080
RAM: 32GB DDR3

I can't provide a log because the emulator crashes, but it's been around quite awhile. i don't know how to create a backtrace. but i would appreciate if someone would look into DLC support.

**Comment by 13xforever** [comment] 2019-03-18 21:18
Duplicate of #4091

**Closed** 2019-03-18 21:19 UTC
