### ISSUE TITLE
[Bug] Enemy Territory: Quake Wars graphics flickering.

### ISSUE THREAD

**Issue by Satan86** [RPCS3/rpcs3#12425] opened 2022-07-30 13:47 UTC
### Quick summary

3D Graphics in Enemy Territory: Quake Wars flicker.

### Details

Tried all settings, nothing fixes it.

### Attach a log file

[RPCS3.log.gz](https://github.com/RPCS3/rpcs3/files/9226545/RPCS3.log.gz)

### Attach capture files for visual issues

RSX Capture: [NPUB90092_20220730142642_capture.zip](https://github.com/RPCS3/rpcs3/files/9226548/NPUB90092_20220730142642_capture.zip)

Renderdoc: https://drive.google.com/file/d/1_5XGcJdKnfdZsfuVdN28TWpT_fDtvY_P/view?usp=sharing

In the Renderdoc Capture, I had to look up to the Sky because the flickering only happened at 30 FPS and Renderdoc slowed the game down. I still managed to capture the flickering, however.  This is how it is supposed to look: 
![rpcs3 2022-07-30 14-44-34](https://user-images.githubusercontent.com/61447828/181917205-9606a0e4-34af-4e99-9437-856f51ea709d.png)
But on the capture, the vehicle on the bottom left corner is missing.

### System configuration

Ryzen 5 5600x, Windows 11, GTX 1050 Ti driver 516.59.

**Comment by kd-11** [comment] 2022-10-07 12:51
This is fixed by enabling RDB.

**Comment by Satan86** [comment] 2022-10-07 13:10
Not for me.

https://user-images.githubusercontent.com/61447828/194561517-e35ceaee-40d9-40ef-968f-3480e010c36a.mp4

**Comment by kd-11** [comment] 2022-10-07 13:12
Right. I'm using a special build with strict framebuffer sampling.
That's not something that will ever make it to the main branch though (extremely cpu intensive) :(

**Comment by kd-11** [comment] 2022-10-20 13:56
I have an idea how to resolve the RCB/RDB desync issues, I'll come back to this one later.

**Comment by Asinin3** [comment] 2023-07-24 16:12
Still an issue?

**Comment by kd-11** [comment] 2023-07-24 16:45
This is still a problem at least until the memory tagging system is changed.

**Comment by Satan86** [comment] 2023-07-24 20:21
It is, in fact, still an issue.

**Comment by kd-11** [comment] 2023-11-26 23:27
I worked on an alternate sampling strategy which unfortunately didn't help much. We could bump the number of samples for every framebuffer section, but these need to be checked every draw call which is insanely expensive if we scale up.
Instead I think hooking into the WCB/WDB mechanism will help with what I want here.

**Comment by kd-11** [comment] 2023-12-08 00:38
It seems to be a timing thing. Flushing immediately after the command to read the reports is seen completely fixes the issue. This means we're likely missing a sync signal from CELL somewhere. However, it is worth noting that the report reads are immediately followed by a backend semaphore release, so it is not clear how the CPU threads are deciding to proceed with the data access. Of course it is very likely that the game has synchronization problems itself.

**Comment by kd-11** [comment] 2023-12-08 19:41
Finally figured it out. This one is just caused by insane game code.

**Comment by kd-11** [comment] 2023-12-08 20:14
Fixed by https://github.com/RPCS3/rpcs3/pull/14880 in strict mode.

**Comment by Satan86** [comment] 2023-12-09 00:55
Indeed. Graphics are now working properly. Thank you.

**Closed** 2023-12-09 19:34 UTC
Labels: Bug
