### ISSUE TITLE
RSX: C7011: implicit cast from "vec4" to "vec2"

### ISSUE THREAD

**Issue by GhettoGirl** [RPCS3/rpcs3#2002] opened 2016-07-30 18:39 UTC
Tested games
 - BLJM-60527 (Project DIVA F JP)
 - BLJM-61079 (Project DIVA F 2n JP)
 - BLUS-31319 (Project Diva F US)

Linux, OpenGL

```
F {rsx::thread} N2gl4glsl21compilation_exceptionE thrown: compilation failed: '0(82) : error C7011: implicit cast from "vec4" to "vec2"
0(84) : error C7011: implicit cast from "vec4" to "vec2"
'
```

Maybe e297984e591f8fa5ffa118bcb4b98703ce6911cf caused this??? Worked fine before this commit.

**Comment by paulsapps** [comment] 2016-07-30 19:15
u32& m_offset_register; looks possibly suspect, added a comment

**Comment by raven02** [comment] 2016-07-31 10:53
@GhettoGirl , which scene reproduce it ? and how about VK and DX12?

**Comment by Nezarn** [comment] 2016-07-31 11:19
@raven02 linux doesn't have vulkan and dx12 :p (and this is a linux only issue, since for me Project Diva F 2nd works same with ogl as with dx12 in windows)

**Comment by GhettoGirl** [comment] 2016-07-31 21:45
@raven02 it happens very early at boot, not even enters the first loading screen. It may be special kind of bug caused by GCC or something. I'm not sure, will try Clang later to see if it works.

**Comment by GhettoGirl** [comment] 2016-07-31 22:01
There were some commits since I reported this issue. Still not fixed :(

PS: Compilation using Clang resulted in better performance on my machine :+1:  From now on RPCS3 will be compiled using Clang in the future. GCC seems to have a lot of problems with the code.

**Comment by raven02** [comment] 2016-08-01 14:28
I can reproduce it too on windows and looks like GL is affected (Vulkab and DX12 look ok)

**Comment by raven02** [comment] 2016-08-01 14:42
It breaks at https://github.com/RPCS3/rpcs3/pull/1983 . This makes sens since rsx_program_decoompiler only used by GL backend

**Comment by raven02** [comment] 2016-08-01 15:17
It is broken ddx/ddy

**Comment by raven02** [comment] 2016-08-01 15:25
@kd-11 , this looks correct ? 

				case (u32)opcode_t::ddx: return set_dst(base::ddx(src_swizzled_as_dst(0)), disable_swizzle_as_dst);
				case (u32)opcode_t::ddy: return set_dst(base::ddy(src_swizzled_as_dst(0)), disable_swizzle_as_dst);

**Comment by kd-11** [comment] 2016-08-01 15:38
I had a work in progress fix for this, but I've been overwhelmed with work lately. I can't remember the exact method I was using, but yea, basically disabling the swizzle as dst should work as long as dst is a vec2, anything else and you'll have the same problem, e.g value.x = ddy will fail since ddy is a vec2 and value.x is a single vector. Unfortunately the rsx_decompiler is heavily templated, so much so that its quite difficult to follow and set up special cases without looking at the code rather extensively.

Anyway, what is the glsl output with your workaround?

**Comment by kd-11** [comment] 2016-08-01 15:59
@raven02 I think your workaround is viable. My workaround removed the swizzle constraint completely, but that would break a misaligned assignment e.g dst.yz = ddx(). Since derivative functions are guaranteed to return a vec2 afaik, I dont expect any other dst configuration here. Of course we can keep an eye out for any such special case.

**Comment by raven02** [comment] 2016-08-02 01:39
This is the GL output

	r2.xy = dFdx(r2.zw);
	r0.xy = dFdy(r2.zw);

**Closed** 2016-08-02 02:45 UTC
Labels: regression
