### ISSUE TITLE
Ace Combat Assault Horizon Demo NPUB90530 and Ace Combat Infinity NPUB31347 inverted rotate graphics

### ISSUE THREAD

**Issue by Augusto7743** [RPCS3/rpcs3#9810] opened 2021-02-20 17:31 UTC
Linux Ubuntu 20.04 64 bits
RPCS3 0.0.14-11759

Both Ace Combat Assault Horizon Demo NPUB90530 and Ace Combat Infinity NPUB31347 has inverted rotate and wrong graphics.
Ace Combat Assault Horizon Demo crash in gameplay (screenshot 3).

![ACE COMBAT ASSAULT HORIZON Demo 1](https://user-images.githubusercontent.com/21184987/108603785-bc7d3200-7388-11eb-8d4b-96fee26e40ae.jpg)

![ACE COMBAT ASSAULT HORIZON Demo 2](https://user-images.githubusercontent.com/21184987/108603789-c1da7c80-7388-11eb-878c-70ca88a13c35.jpg)

![ACE COMBAT ASSAULT HORIZON Demo 3](https://user-images.githubusercontent.com/21184987/108603796-c9018a80-7388-11eb-8c33-fbeed567da4e.jpg)

![ACE COMBAT ASSAULT HORIZON Demo 4](https://user-images.githubusercontent.com/21184987/108603807-cef76b80-7388-11eb-879d-1279fba7772b.jpg)

![ACE COMBAT INFINITY 1](https://user-images.githubusercontent.com/21184987/108603814-d4ed4c80-7388-11eb-9e30-20985204f020.jpg)

![ACE COMBAT INFINITY 2](https://user-images.githubusercontent.com/21184987/108603821-d9b20080-7388-11eb-9171-fb82953e4001.jpg)

![ACE COMBAT INFINITY 3](https://user-images.githubusercontent.com/21184987/108603825-df0f4b00-7388-11eb-83f8-98df4af7d3a3.jpg)

[ACE COMBAT ASSAULT HORIZON Demo.log](https://github.com/RPCS3/rpcs3/files/6015860/ACE.COMBAT.ASSAULT.HORIZON.Demo.log)
[ACE COMBAT INFINITY.log](https://github.com/RPCS3/rpcs3/files/6015861/ACE.COMBAT.INFINITY.log)

**Comment by RainbowCookie32** [comment] 2021-02-20 17:37
Duplicate of #8905

**Closed** 2021-02-20 17:38 UTC
