### ISSUE TITLE
[Regression] Need for Speed: Rivals [BLUS31201] Squid Ink

### ISSUE THREAD

**Issue by Darkhost1999** [RPCS3/rpcs3#11328] opened 2022-01-03 18:34 UTC
Black splotches take up most the screen in NFS Rivals as shown in video below.
Possible Turing issue.

https://user-images.githubusercontent.com/60384196/147964628-920767c1-64f1-43c4-8343-a85768488635.mp4

[RPCS3.log.gz](https://github.com/RPCS3/rpcs3/files/7803416/RPCS3.log.gz)

**Comment by Darkhost1999** [comment] 2022-01-03 18:36
The issue as shown in the video if not clear enough is all the black rainbow ink covering the screen every time the vehicle moves. When not moving the issue is not present.

**Comment by illusion0001** [comment] 2022-01-04 00:34
Architecture memes

**Comment by Darkhost1999** [comment] 2022-01-04 01:33
enable all 4 RSX buffers
strict rendering mode
force cpu blit
disable native float16
But driver wakeup delay skyrockets with these settings and the game becomes so unstable I get FIFO errors so often I have increased all the way to 1,000 and these settings do not fix my issue anyways Just fixes a ton of other things.
[RPCS3.log](https://github.com/RPCS3/rpcs3/files/7804838/RPCS3.log)
Video comparison using these settings during the One time it worked out of 12 or more.
https://youtu.be/3k5TwltK9mQ
May need a couple minutes to upload

**Comment by Darkhost1999** [comment] 2022-01-08 23:27
Updated info

**Comment by Darkhost1999** [comment] 2022-02-21 03:57
Updated rsx link to intended 4 captures

**Comment by Darkhost1999** [comment] 2022-03-29 15:56
I spoke too soon.
It is only fixed when resolution scale is at 300% (possibly others but the game isn't stable)

FSR and default resolution are still effected
https://media.discordapp.net/attachments/272875751773306881/958393227508084746/Defaut_resolution_Trim.mp4

**Comment by Darkhost1999** [comment] 2022-06-11 03:01
WCB fixes a lot

[Video](https://media.discordapp.net/attachments/272875751773306881/985002919860531240/WCB.mp4)
[RPCS3.log](https://github.com/RPCS3/rpcs3/files/8882963/RPCS3.log)
[RSX Captures](https://mega.nz/folder/n4RiBZRQ#vatNZfoqhJWMrVdaM3CbHQ)
Res Scale fixes black squid ink (hack)
[Video](https://media.discordapp.net/attachments/272875751773306881/985007461679378532/RES.mp4)
[RPCS3.log](https://github.com/RPCS3/rpcs3/files/8882988/RPCS3.log)

Both Res Scale and WCB don't mix
[Video](https://media.discordapp.net/attachments/272875751773306881/985010559571329054/WCBRES.mp4)
[RPCS3.log](https://github.com/RPCS3/rpcs3/files/8883023/RPCS3.log)

I feel like I've tried every single exposed setting to the UI possible. I do not know what to do. I'm going to try to get a debug output now that stability has improved and upload that to the WCB + Atomic section.

**Comment by Darkhost1999** [comment] 2022-06-22 01:26
Regression from
https://github.com/RPCS3/rpcs3/pull/9848
I'm not saying the before was perfect but watch the vids

https://user-images.githubusercontent.com/60384196/174922946-c161f2cc-f17d-413d-bc13-95bc0ccc317c.mp4

[RPCS3.log](https://github.com/RPCS3/rpcs3/files/8953730/RPCS3.log)

https://user-images.githubusercontent.com/60384196/174923207-4e6ea124-6d48-45b3-9d64-8b429da3c189.mp4

[RPCS3.log](https://github.com/RPCS3/rpcs3/files/8953716/RPCS3.log)

**Comment by Darkhost1999** [comment] 2022-07-28 23:46
Now the blue is red

https://user-images.githubusercontent.com/60384196/181655070-55f7d7ce-4d5b-4ced-80a1-2c1a1d999d78.mp4

[RPCS3.log.gz](https://github.com/RPCS3/rpcs3/files/9214889/RPCS3.log.gz)

Sorry I booted twice because I forgot to enable WCB

**Comment by Darkhost1999** [comment] 2022-08-03 22:11
So about an OGL comparison
[config_BLUS31201.zip](https://github.com/RPCS3/rpcs3/files/9255327/config_BLUS31201.zip)
[RPCS3.log.gz](https://github.com/RPCS3/rpcs3/files/9255304/RPCS3.log.gz)
Default RES + WCB + Required firmware overrides in cell music to get in game

https://user-images.githubusercontent.com/60384196/182720968-459c08d8-59a7-490f-ad13-4874210d9b7e.mp4

Imma say squid ink hits this 1 a bit differently

**Comment by Darkhost1999** [comment] 2022-08-03 22:53
"Required firmware overrides" was sheer dumb luck

![image](https://user-images.githubusercontent.com/60384196/182724688-b19b8b87-b701-4786-bf23-302b2d750d48.png)

[RPCS3.log.gz](https://github.com/RPCS3/rpcs3/files/9255444/RPCS3.log.gz)
[RSX capture](https://mega.nz/file/WphS2T6L#9JShKvJLntU1k-GL7se6xWBrpxbCc1auU36KIkjhWEY)

**Comment by Darkhost1999** [comment] 2022-09-01 13:06
Pascal architecture graphics cards do NOT have this issue.
But I see the Nvidia RTX 3080 graphics card can replicate this regression. I asked that they commented here because I feel like people think I'm just the only 1 to get this stupid issue.
But no people just refuse to make comments on my issues.
So here it's not just me ->

https://discord.com/channels/272035812277878785/272875751773306881/1012056456582922280

![unknown.png](https://user-images.githubusercontent.com/60384196/187920048-0968d878-238d-4393-89c6-ba71ded43c94.png)

**Comment by Darkhost1999** [comment] 2022-10-20 20:05
Has this been triaged?

**Comment by kd-11** [comment] 2022-11-04 02:06
I did some testing. Unfortunately I cannot reproduce this bug as reported.
Tested with default settings + WCB + vulkan.
1. AMD proprietary - technically works, but has a driver bug that is messing up the tiles and they don't render.
2. AMD mesa (RADV) - I played for like 30 minutes. Visuals are mostly correct, terrain loads in as expected. The only issue is image is blurry and performance is poor,
3. NVIDIA (pascal) - Renders correctly like RADV for the most part.
I cannot see any obvious issues with the PR in the report for the moment.

**Comment by Darkhost1999** [comment] 2022-11-04 02:10
That's OK 150% resolution scaling doesn't impact performance too negatively and provides a clear image.
I just don't know why 100% resolution scale is broken for turing and ampere.

**Comment by kd-11** [comment] 2022-11-12 20:38
I committed a workaround for the AMD proprietary driver's point rasterization issue. It was a regression due to some odd interaction between line and point state in those drivers.
I still have no way to reproduce the squid ink, I'll have to revisit if I get a newer nvidia card at some point.

**Comment by Darkhost1999** [comment] 2022-11-17 01:37
I have singled out reverting https://github.com/RPCS3/rpcs3/pull/9848/commits/eb01b887c65ebfd66fb6aa64981a5379bf2046e0 resolves this issue.

**Comment by kd-11** [comment] 2022-11-17 05:54
Thanks.

**Closed** 2022-12-14 00:24 UTC
Labels: Bug, RSX
