### ISSUE TITLE
Regression: Black line (#6415)

### ISSUE THREAD

**Issue by Emulator-Team-2** [RPCS3/rpcs3#10671] opened 2021-08-07 07:15 UTC
**rpcs3-v0.0.6-8605:**
![2](https://user-images.githubusercontent.com/38318848/128591648-b71567a1-a904-41b5-b858-1ec3e02f464f.png)
**rpcs3-v0.0.6-8608:** (https://github.com/RPCS3/rpcs3/pull/6415)
![1](https://user-images.githubusercontent.com/38318848/128591645-6f1520cd-e7bb-470e-945a-ccfa7b340deb.png)
**rpcs3-v0.0.17-12611:**
![3](https://user-images.githubusercontent.com/38318848/128591650-598a474c-f4c8-44a6-8454-00f6900f140a.png)

**RSX Capture:**
**Link:** [RSX-Capture](https://drive.google.com/file/d/1Zk0ENKuk9Izyeity8Yuso-857KYPBI6L/view?usp=sharing)

**Details:**
-RPCS3 rpcs3-v0.0.17-12611 
-Game:  NARUTO Shippuden: Ultimate Ninja Storm Generations [BLES01481]
-Issue: The black contour line.

OS: Windows 10 64-bit
CPU: Intel i7-10700
GPU: GTX 1660 - ( Driver version: 471.41.0.0 )

**Comment by kd-11** [comment] 2021-08-07 10:24
![image](https://user-images.githubusercontent.com/15904127/128597078-b3939d17-2101-463f-aee4-547a36817546.png)
I am unable to reproduce this problem.

**Comment by kd-11** [comment] 2021-08-07 10:25
@Emulator-Team-2 Please share the log file as well, I need to reproduce your settings exactly.

**Comment by Emulator-Team-2** [comment] 2021-08-07 10:33
@kd-11 
It looks like this black line is invisible after loading the rsx capture.

**Comment by kd-11** [comment] 2021-08-07 10:35
Ok, I'll check what could be happening

**Comment by Emulator-Team-2** [comment] 2021-08-07 10:47
The game was tested with default settings.
[RPCS3.log.gz](https://github.com/RPCS3/rpcs3/files/6948963/RPCS3.log.gz)

**Comment by kd-11** [comment] 2021-08-07 11:07
![image](https://user-images.githubusercontent.com/15904127/128598123-cf30a0f6-53f9-4274-befb-ab00f257455c.png)
Still unable to reproduce natively. GTX1050 Ti with driver 471.41

**Comment by kd-11** [comment] 2021-08-07 11:08
Does it only happen on that one map?

**Comment by Emulator-Team-2** [comment] 2021-08-07 11:23
In the Naruto: UNSG it happens on almost every maps, but on the map from this thread it's more visible.
![Q](https://user-images.githubusercontent.com/38318848/128598541-4b00ca80-d85e-4758-b80a-5fe799e18e92.png)

**Comment by Emulator-Team-2** [comment] 2021-08-07 11:31
>1. Does the issue happen with OGL? If so grab a RDC
No,

**Comment by Emulator-Team-2** [comment] 2021-08-07 11:44
@kd-11 
1. Does the issue happen with OGL? If so grab a RDC
- No, It's only visiable with Vulkan.
2. If not, still get a vulkan RDC with the 1660Ti, I'll try and massage renderdoc to accept it
- **RenderDoc:**
**Link:** [Vulkan](https://drive.google.com/file/d/1gM-Yz3YGoYXXgFxGtO7uIYayIHsMrapb/view?usp=sharing)

**Comment by kd-11** [comment] 2021-08-07 14:31
I'll need another RDC for the old working build. The 'line' is actually cell shading outline of the rocks below the field. I'm not sure this is intended behavior.

**Comment by Emulator-Team-2** [comment] 2021-08-07 14:54
- **RenderDoc:**
rpcs3-v0.0.6-8605:
**Link:** [Vulkan](https://drive.google.com/file/d/1EEFrxYWqGEtddxHUGilHTuVEc5HE5mwp/view?usp=sharing)

**Comment by kd-11** [comment] 2021-08-07 16:06
Should be fixed by https://github.com/RPCS3/rpcs3/pull/10676. Please confirm.

**Comment by Emulator-Team-2** [comment] 2021-08-07 16:31
Fixed by  #10676  :D  
<img width="952" alt="NG" src="https://user-images.githubusercontent.com/38318848/128607225-6a4e74d7-0902-4cae-8fa2-ff7853302558.png">

**Closed** 2021-08-07 16:38 UTC
Labels: RSX, Regression
