### ISSUE TITLE
NCAA Football 12 [BLUS30745] Takes nearly 3 minutes to load ingame

### ISSUE THREAD

**Issue by connorwalks** [RPCS3/rpcs3#5947] opened 2019-05-11 00:32 UTC
RPCS3-v0.0.6-8086-fce9d6a7 Alpha
Intel i9 9900K
16 GB 3000MHz DDR4
NVIDIA RTX 2080 (Driver 425.31)

The game takes between 3-4 minutes to load ingame as seen in the video. It looks as if the game has simply frozen, but eventually it does load. Other NCAA Football games typically take about 30 seconds to load. Also worth noting that this game has some flickering and random crashing issues once ingame.

Log and video below

https://youtu.be/xLCcysDUnbI

[NCAA Football 12.log.gz](https://github.com/RPCS3/rpcs3/files/3168441/NCAA.Football.12.log.gz)

**Comment by incognitoh** [comment] 2019-05-15 21:46
Loading glitch seems to be fixed with newest master RPCS3 v0.0.6-8105-3753d27a.  for me, load time before games are less than 7 seconds.  Still has visual glitches though.

**Comment by connorwalks** [comment] 2019-05-16 17:38
What are your settings? It still takes forever for me and I'm using the same build on a fresh install of RPCS3 and it takes 3-4 minutes. Can you upload a log?

[RPCS3.log.gz](https://github.com/RPCS3/rpcs3/files/3188304/RPCS3.log.gz)

**Comment by incognitoh** [comment] 2019-05-16 18:53
Usual settings but I'm using SPU LLVM with Mega SPU block size. Try it with the latest master. Worth noting that I'm using the PSN digital version of the game while you have the disc version. Not sure if that matters although I also experienced the 3 minute wait as you did last week. Try it again and if it still doesn't work for you, I will post a log.

**Comment by connorwalks** [comment] 2019-05-17 18:35
Still takes forever for me. Have been using SPU LLVM and tried with Mega block size but get the same result

**Comment by incognitoh** [comment] 2019-05-18 18:05
Alright so I just tried it with a fresh install and the 3 minute wait is still there. But on my other install it isn't. So it might be settings related. let me try to narrow it down. i will post a log soon..

**Comment by incognitoh** [comment] 2019-05-18 18:19
Okay never mind, I figured it out.  

The delay is related to the PPU threads. in your NCAA 12 custom config file, change the ppu threads to 3. Maybe even 4 for your cpu. Each game should now load quickly. btw, try this with all the NCAA games as they all seem to benefit from it, especially NCAA 14. Not sure if the RPCS3 team would consider this a regression or not.

**Comment by connorwalks** [comment] 2019-05-19 00:13
How do you limit PPU threads? I only see a setting for SPU and even doing that doesn't help

**Comment by connorwalks** [comment] 2019-05-19 00:37
Nevermind, I found it in the congif file. Seems to work! Obviously not a permanent solution but definitely nice for testing and not having to wait 3-5 minutes each time. Thanks!

**Comment by Yahfz** [comment] 2019-08-31 13:56
Just tried 3 times on master (8620) and the game loads in 5-10 seconds for me. 
This issue can be closed.

**Comment by AniLeo** [comment] 2019-08-31 14:15
Closing as fixed, ping for reopening if you can somehow reproduce this still

**Closed by AniLeo** 2019-08-31 14:15 UTC
