### ISSUE TITLE
[BLUS30903] Tales of Graces f - Sound out of sync during conversations

### ISSUE THREAD

**Issue by suddenrage** [RPCS3/rpcs3#6625] opened 2019-09-23 14:56 UTC
Hello,

i noticed a problem while playing ToG.
Everytime a conversation scene appears (see picture below) the sound is out of sync with the text and the animations.
Additionally, the sound is faster than the text and the animations, which means that after the voiceover has ended, all i can do is to wait for the text and the animations to finish.

Maybe someone has a solution for this problem.
Thank you in advance.

best regards
Suddenrage

[RPCS3 OpenGL.log.gz](https://github.com/RPCS3/rpcs3/files/3642704/RPCS3.OpenGL.log.gz)
[RPCS3 Vulkan.log.gz](https://github.com/RPCS3/rpcs3/files/3642705/RPCS3.Vulkan.log.gz)

![2019-09-22 10_27_42-Window](https://user-images.githubusercontent.com/12772539/65434886-dcb96200-de1f-11e9-9646-443b7cdbd4d6.png)

**Comment by KatherineFtw** [comment] 2019-10-02 20:43
Not a dev, but:

All PS3 Tales of games use 30 FPS for some things, and 60 for others. Blame bad programming on Bandi's part. Either way it's a well known bug. Either set to 30 and get broken skits or set to 60 and get a broken overworld. 

Unless RPCS3 can either get accurate enough to not care or some "on the fly" switcher is implimented it's unlikely to get fixed.

**Comment by lextra2** [comment] 2019-10-07 16:38
> Not a dev, but:
> 
> All PS3 Tales of games use 30 FPS for some things, and 60 for others. Blame bad programming on Bandi's part. Either way it's a well known bug. Either set to 30 and get broken skits or set to 60 and get a broken overworld.
> 
> Unless RPCS3 can either get accurate enough to not care or some "on the fly" switcher is implimented it's unlikely to get fixed.

First of all, it is not bad programming just because the game uses 60FPS in menus/combat and 30FPS for everything else. They simply could only get 60FPS in these scenarios but only 30FPS in others.

Second of all, there are other games that do this as well which work just fine. (Kingdom Hearts 1.5 HD ReMix for example also has 60FPS in menus but 30 everywhere else. Another one is Final Fantasy 13. They both work just fine without having to manually change the Framelimit.)

So RPCS3 is already capable of changing the frame rate properly on the fly. It is just that tales games might have a different way of doing this which RPCS3 is not aware of.

**Comment by RainbowCookie32** [comment] 2020-06-09 01:22
Looking at the log you had your framelimiter set to 30fps, which means half speed outside of battles on Tales games. That'd point to this being caused by RPCS3's inability to switch the framerate limit in this game, making this issue a duplicate of #3020 
Can be closed as duplicate

**Closed** 2020-06-09 16:44 UTC
