### ISSUE TITLE
rsx: Working buffer not big enough (Sonic Unleashed)

### ISSUE THREAD

**Issue by SinonCaelum** [RPCS3/rpcs3#8667] opened 2020-08-02 00:11 UTC
I don't remember in which version this issue started, but my guess would be since v0.0.10. This issue happens ramdomly will I'm playing.
For more information please take a look at the error:

"·F 0:05:50.038122 {RSX [0x00d2190]} SIG: Thread terminated due to fatal error: [attrib buffer] Working buffer not big enough, buffer_length=67108864 allocated=8268288 requested=1109562000 guard=4194304 largest_pool=196096
(in file d:\a\1\s\rpcs3\Emu\RSX\Common\ring_buffer_helper.h:91)
·! 0:05:50.038253 {rsx::thread} SIG: Thread time: 316.421875s (1165.696789Gc); Faults: 0 [rsx:0, spu:0]; [soft:0 hard:0]; Switches:[vol:0 unvol:0]
·W 0:05:50.039109 {cellAudio Thread} cellAudio: Audio backend stopped unexpectedly, likely due to a buffer underrun"

Thanks for listening. I hope this is an on going issue, not reported ofc, and not a solved one already
[RPCS3.log](https://github.com/RPCS3/rpcs3/files/5011434/RPCS3.log)
.

**Comment by AniLeo** [comment] 2020-08-02 14:23
RPCS3 v0.0.11-10715-107129f9 Alpha | HEAD | Firmware version: 4.83
AMD Ryzen 7 2700X Eight-Core Processor | 16 Threads | 15.95 GiB RAM | TSC: 3.693GHz | AVX+ | FMA3
Operating system: Windows, Major: 10, Minor: 0, Build: 18363, Service Pack: none, Compatibility mode: 0
'GeForce GTX 1060 6GB' running on driver 451.67.0.0

·! 0:00:02.367512 SYS: Title: SONIC UNLEASHED
·! 0:00:02.367514 SYS: Serial: BLES00425

**Comment by RainbowCookie32** [comment] 2020-08-12 20:03
Is this no longer an issue? Otherwise it should be kept open

**Comment by windwhirl94** [comment] 2020-08-12 20:37
This issue is hard to trigger in what little experience I have. And it's been a while since I have encountered it. 

Not sure if it should be closed, but there isn't much to keep it open either.

**Comment by SinonCaelum** [comment] 2020-08-15 14:01
I was closing old requests, and closed this accidentally
The thing is, i dont know if i can reopen it....

**Comment by aquazeu** [comment] 2020-10-24 18:48
Why is this issue closed? Still getting a lot of those errors when playing Unleashed (1.02, BLES00425)
`F {RSX [0x00222b4]} SIG: Thread terminated due to fatal error: [attrib buffer] Working buffer not big enough, buffer_length=134217728 allocated=16999424 requested=1490510016 guard=4194304 largest_pool=28067840
(in file ../rpcs3/Emu/RSX/VK/../Common/ring_buffer_helper.h:91)`

**Comment by aquazeu** [comment] 2020-10-30 18:28
`RPCS3 v0.0.12-11119-f03d4cf8 Alpha | HEAD | Firmware version: 4.86
AMD Ryzen 5 1600X Six-Core Processor | 12 Threads | 15.63 GiB RAM | TSC: 3.593GHz | AVX+ | FMA3
Operating system: POSIX, Name: Linux, Release: 5.6.18-200.fc31.x86_64, Version: #1 SMP Wed Jun 10 22:18:55 UTC 2020
RSX: Found vulkan-compatible GPU: 'GeForce GTX 1060 6GB' running on driver 440.82.0.0`
[RPCS3.crash1.log.gz](https://github.com/RPCS3/rpcs3/files/5466940/RPCS3.crash1.log.gz)

**Comment by psennermann** [comment] 2021-01-10 13:31
Did you try to use the "Driver wake-up delay" option in the advanced settings? (maybe try with a value of 200)

**Comment by SinonCaelum** [comment] 2021-01-13 11:32
Well I did... It solve the problem(?). But in this later versions there's being a huge amount of crashes regarding this game (for me atleast), and I need to be lucky enough to even open the game without a crash at the first loading screen.

**Comment by windwhirl94** [comment] 2021-01-15 12:58
> 
> 
> Well I did... It solve the problem(?). But in this later versions there's being a huge amount of crashes regarding this game (for me atleast), and I need to be lucky enough to even open the game without a crash at the first loading screen.

That issue is being tracked in #9191

Build 0.0.12-11107 did not have that issue, so you may want to try that one.

**Comment by psennermann** [comment] 2021-01-16 16:47
I experienced the same buffer error in NHL14, but it seems to be fixed by disabling anti-aliasing in the emulator GPU tab

**Comment by Megamouse** [comment] 2021-07-27 21:36
probably fixed by #10617

**Comment by RinMaru** [comment] 2021-07-27 22:58
played unleashed 2 hours straiht and didnt have any crash so probably fixxed

**Comment by Megamouse** [comment] 2021-07-27 22:59
thx. with the mentioned build or on master ?

**Closed** 2021-07-27 23:17 UTC
Labels: RSX

**Comment by RinMaru** [comment] 2021-07-27 23:22
> thx. with the mentioned build or on master ?

On master. Haven't exp any crashes in unleashed.

**Comment by kd-11** [comment] 2021-07-28 06:54
The fix is unrelated to this bug, but if it cannot be reproduced its ok to close. A single draw call requesting 1GB of memory for vertex attributes is a sign of heap corruption.
