### ISSUE TITLE
Regression:- Demon's Souls [BLUS30443] freezes after building SPU cache upon reboot from 0.0.21-13378 onwards.

### ISSUE THREAD

**Issue by solarmystic** [RPCS3/rpcs3#11703] opened 2022-03-29 09:25 UTC
## Quick summary
Demon's Souls freezes/deadlocks after building SPU cache upon reboot in the same rpcs3 instance from 0.0.21-13378 onwards. #11691 

This is a different issue compared to the one mentioned by kd-11 in the #11701 PR. I have tested that build and it doesn't resolve this issue.

## Details

To reproduce this issue:-

1. Boot Demon's Souls with default settings on 0.0.21-13378 onwards.
2. Close it by clicking on the Stop Button.
3. Restart the game by clicking on the Restart button
4. Game freezes after building SPU Cache screen. In addition, the emulator will thread deadlock right after attempting to stop the frozen game.

![not working](https://user-images.githubusercontent.com/4345150/160578132-0c8d4e76-c8dc-43b1-8993-c0104b941790.PNG)
![not working2](https://user-images.githubusercontent.com/4345150/160578266-78dbd34c-d29f-4dfa-abb2-9dd1aff002f4.PNG)

Expected behavior is for the user to be able to reboot Demon Souls as many times as they wish in the same rpcs3 instance after stopping the game.

Last working build is 0.0.21-13371.

Current workaround is to close and restart rpcs3 for each Demon's Souls boot. 

## Log Files

0.0.21-13371 (Last good build)

[RPCS3.log.gz](https://github.com/RPCS3/rpcs3/files/8369908/RPCS3.log.gz)

0.0.21-13378 (First bad build)

[RPCS3.log](https://github.com/RPCS3/rpcs3/files/8369891/RPCS3.log)

## System configuration:

Intel i7 7700 @ 4.0 GHz
NVIDIA GTX 1070Ti with 497.29 drivers
32 GB DDR4 2400 MHz
Windows 10 21H1

**Comment by solarmystic** [comment] 2022-03-29 09:36
Ermm, i think it should be reopened since the problem was not fixed by the commits in #11701, which is a seperate issue

**Comment by solarmystic** [comment] 2022-03-29 10:03
Short videos demonstrating the issue

Freezing after reboot

https://user-images.githubusercontent.com/4345150/160586332-5096351a-e67b-4ee1-9812-96c6667d58f7.mp4

Expected behaviour in an older build

https://user-images.githubusercontent.com/4345150/160587178-b5b0baa1-ec29-443d-b709-db95b873e680.mp4

**Comment by kd-11** [comment] 2022-03-29 21:00
I'm unable to reproduce this on AMD RDNA2. My nvidia card has always crashed upon rebooting any title since driver 470 released, but that is outside the scope of the PR in question. I'll ask for more testers to verify its an emulator bug.

**Comment by kd-11** [comment] 2022-03-29 21:09
Actually, we had similar reports previously. Please update the NVIDIA drivers to something more recent.

**Comment by kd-11** [comment] 2022-03-29 21:10
Tried with 1050Ti and latest nvidia drivers 512.x - it works just as before too.

**Comment by Asinin3** [comment] 2022-03-29 21:13
Can't reproduce, RTX 3080 with latest driver

**Comment by Asinin3** [comment] 2022-03-29 21:16
Update GPU drivers, join our discord: https://discord.me/rpcs3 and use #help channel.
Closing as me, kd, and HTM are unable to reproduce (3080, 1050ti, 970) with new drivers.

**Closed by Asinin3** 2022-03-29 21:16 UTC

**Comment by solarmystic** [comment] 2022-04-10 10:26
Figured i'd update this "issue" with something i just found out, turning off native interface for the game actually fixes this problem for me.

**Comment by Asinin3** [comment] 2022-04-10 11:37
Well I had native interface on, and Im almost certain KD and Hold had it on too. I retested again just to check but still can't reproduce.

**Comment by itsnotEDDY** [comment] 2023-01-17 10:51
change spu decoder to static in cpu settings worked 4 mw2 may work for other games
