### ISSUE TITLE
Castlevania Harmony of Despair, Stuck while trying to update a local high score to RCPN

### ISSUE THREAD

**Issue by Patrickmanx** [RPCS3/rpcs3#12725] opened 2022-09-28 23:06 UTC
### Quick summary

While beating a Stage in the game Castlevania Harmony of Despair locally, the game will infinitely try to upload a score tp RCPN.

### Attach a log file

[RPCS3.log.gz](https://github.com/RPCS3/rpcs3/files/9678417/RPCS3.log.gz)

E rpcn: Attempted to register a score that is not better!
E SYS: 'Unknown function' failed with 0x8002a415 : SCE_NP_COMMUNITY_SERVER_ERROR_NOT_BEST_SCORE [1]
E rpcn: Attempted to register a score that is not better!
E SYS: 'Unknown function' failed with 0x8002a415 : SCE_NP_COMMUNITY_SERVER_ERROR_NOT_BEST_SCORE [2]
U sceNp TODO: sceNpScoreRecordGameDataAsync(transId=4100, boardId=3, score=39507, totalSize=92222, sendSize=92222, data=0x3250bc70, prio=0, option=0x0)

### Attach capture files for visual issues

https://media.discordapp.net/attachments/930217107155738654/1024807951736787035/Screenshot_2022-09-28_192033.png?width=1174&height=676

### System configuration

- SYS: RPCS3 v0.0.24-14203-8170b91f Alpha | master
- SYS: AMD Ryzen 5 3600 6-Core Processor | 12 Threads | 15.95 GiB RAM | TSC: 3.593GHz | AVX+ | FMA3
- SYS: Operating system: Windows, Major: 10, Minor: 0, Build: 19044, Service Pack: none, Compatibility mode: 0
- SYS: Current Time: 2022-09-28T20:05:57
- RSX: Found vulkan-compatible GPU: 'NVIDIA GeForce GTX 1050 Ti' running on driver 512.15.0.0
- SYS: Firmware version: 4.88
S UPDATER: RPCS3 is up to date!

**Comment by SummerX5** [comment] 2022-09-30 10:29
The same problem I met (also my friends).

**Comment by SummerX5** [comment] 2022-09-30 10:30
The same problem I met (also my friends).

**Comment by kyle788** [comment] 2022-09-30 23:37
Same problem here. Is this a simple fix to revert back?

**Comment by kyle788** [comment] 2022-10-06 20:30
Just to note, I tested this myself by running my own RCPN 5.0 version server and the last update of RPCS3 before the RCPN 6.0 merge (67c02e3522a576d1d739fa130f484ab9a64b5d62) and it works fine after competing the level. Should this issue then be marked as 'regression'?

**Comment by RipleyTom** [comment] 2022-10-17 13:32
Should be fixed since the merge of https://github.com/RPCS3/rpcs3/pull/12818.

**Closed by RipleyTom** 2022-10-17 13:32 UTC
