### ISSUE TITLE
report of gundam reborn (13-5-2018) same issue before....

### ISSUE THREAD

**Issue by song12347** [RPCS3/rpcs3#4571] opened 2018-05-14 12:25 UTC
Version RPCS3: 0.0.5-6737 (2018-05-13)
Game : Gundam Reborn
Spec:
i7-4790
GTX 980 with 4gb memory
16gb ddr3 ram
750W of power supply
3tb 7200rpm hdd
![dsadasdasadasdasd](https://user-images.githubusercontent.com/39214838/39997278-ea9378a4-57b4-11e8-9eca-35291ae21c84.png)

crash log:
F {PPU[0x1000044] Thread (CStageSceneBuilder) [0x0021dfc4]} MEM: Access violation reading location 0x10010010

LOG:RPCS3 v0.0.5-6737-a46ef4f29 Alpha | HEAD
Intel(R) Core(TM) i7-4790 CPU @ 3.60GHz | 8 Threads | 15.94 GiB RAM | AVX+
S LDR: Boot successful.
S {PPU[0x1000000] Thread (main_thread)} SPU: SPU Recompiler Runtime (ASMJIT) initialized...
E {PPU[0x1000000] Thread (main_thread)} SPU: [0x0b0bc] SPU Analyser failed, 21 vs 130
E {PPU[0x1000000] Thread (main_thread)} SPU: [0x0b514] SPU Analyser failed, 24 vs 331
S {PPU[0x1000000] Thread (main_thread)} SPU: SPU Runtime: Built 5206 functions.
S {PPU[0x1000000] Thread (main_thread)} PPU: LLVM: Loaded module v2+010200-37BE7BE390AD324B-haswell.obj
S {PPU[0x1000000] Thread (main_thread)} PPU: LLVM: Loaded module v2+0524E0-CE972BB1E8B5FB18-haswell.obj
S {PPU[0x1000000] Thread (main_thread)} PPU: LLVM: Loaded module v2+095200-EFF83BE83C3ADB3D-haswell.obj
S {PPU[0x1000000] Thread (main_thread)} PPU: LLVM: Loaded module v2+0D6538-EF47B49B95D1C803-haswell.obj
S {PPU[0x1000000] Thread (main_thread)} PPU: LLVM: Loaded module v2+117B44-160F5690357B119E-haswell.obj
S {PPU[0x1000000] Thread (main_thread)} PPU: LLVM: Loaded module v2+15925C-56751129E5C6902B-haswell.obj
S {PPU[0x1000000] Thread (main_thread)} PPU: LLVM: Loaded module v2+199828-E1683C33FDF4DB05-haswell.obj
S {PPU[0x1000000] Thread (main_thread)} PPU: LLVM: Loaded module v2+1DA318-684F51FD2A9CD88A-haswell.obj
S {PPU[0x1000000] Thread (main_thread)} PPU: LLVM: Loaded module v2+21C7B4-39CE8F2270752B5B-haswell.obj
S {PPU[0x1000000] Thread (main_thread)} PPU: LLVM: Loaded module v2+25D3B8-A2EA920CB762CA4A-haswell.obj
S {PPU[0x1000000] Thread (main_thread)} PPU: LLVM: Loaded module v2+29E188-ED1C04A50DFD902A-haswell.obj
S {PPU[0x1000000] Thread (main_thread)} PPU: LLVM: Loaded module v2+2DF110-AB0DCAD5E80B7D40-haswell.obj
S {PPU[0x1000000] Thread (main_thread)} PPU: LLVM: Loaded module v2+320204-CF7C661A5F7DD113-haswell.obj
S {PPU[0x1000000] Thread (main_thread)} PPU: LLVM: Loaded module v2+360B64-2041A66517BAA433-haswell.obj
S {PPU[0x1000000] Thread (main_thread)} PPU: LLVM: Loaded module v2+3A10C0-88769D3A8AB47532-haswell.obj
S {PPU[0x1000000] Thread (main_thread)} PPU: LLVM: Loaded module v2+3E2E20-8EC65AB14AA7E5CF-haswell.obj
S {PPU[0x1000000] Thread (main_thread)} PPU: LLVM: Loaded module v2+425148-7073D01BB81681F5-haswell.obj
S {PPU[0x1000000] Thread (main_thread)} PPU: LLVM: Loaded module v2+4676D0-534326908E74F69C-haswell.obj
S {PPU[0x1000000] Thread (main_thread)} PPU: LLVM: Loaded module v2+4A7A74-2F90EE2EDC7222B0-haswell.obj
S {PPU[0x1000000] Thread (main_thread)} PPU: LLVM: Loaded module v2+4E7CE0-AC6D58B82BFC4476-haswell.obj
S {PPU[0x1000000] Thread (main_thread)} PPU: LLVM: Loaded module v2-libsysmodule.sprx-E926430A8C1D5DCB-haswell.obj
U {PPU[0x1000000] Thread (main_thread) [0x00c23d8c]} HLE TODO: Unimplemented syscall sys_ss_access_control_engine -> CELL_OK
U {PPU[0x1000000] Thread (main_thread) [0x00c22efc]} sysPrxForUser TODO: sys_prx_load_module_list(count=7, path_list=**0xd0020bfc, flags=0x0, pOpt=*0x0, id_list=*0xd0020bdc)
S {PPU[0x1000000] Thread (main_thread) [0x00c22efc]} PPU: LLVM: Loaded module v2-libgcm_sys.sprx-92BB3C6B43076AD9-haswell.obj
S {PPU[0x1000000] Thread (main_thread) [0x00c22efc]} sys_prx: Loaded module: /dev_flash/sys/external/libgcm_sys.sprx
S {PPU[0x1000000] Thread (main_thread) [0x00c22efc]} PPU: LLVM: Loaded module v2-libsre.sprx-7BD57B68D8CA8EBC-haswell.obj
S {PPU[0x1000000] Thread (main_thread) [0x00c22efc]} sys_prx: Loaded module: /dev_flash/sys/external/libsre.sprx
S {PPU[0x1000000] Thread (main_thread) [0x00c22efc]} PPU: LLVM: Loaded module v2-libfs.sprx-BB8655E4C5C49381-haswell.obj
S {PPU[0x1000000] Thread (main_thread) [0x00c22efc]} sys_prx: Loaded module: /dev_flash/sys/external/libfs.sprx
S {PPU[0x1000000] Thread (main_thread) [0x00c200c4]} PPU: LLVM: Loaded module v2-libresc.sprx-868A23FA3425D270-haswell.obj
S {PPU[0x1000000] Thread (main_thread) [0x00c200c4]} sys_prx: Loaded module: /dev_flash/sys/external/libresc.sprx
S {PPU[0x1000000] Thread (main_thread) [0x00c200c4]} PPU: LLVM: Loaded module v2-libadec.sprx-C1FA8E97F96CF507-haswell.obj
S {PPU[0x1000000] Thread (main_thread) [0x00c200c4]} sys_prx: Loaded module: /dev_flash/sys/external/libadec.sprx
S {PPU[0x1000000] Thread (main_thread) [0x00c200c4]} PPU: LLVM: Loaded module v2-libat3dec.sprx-CF7CA4764ADFE9E1-haswell.obj
S {PPU[0x1000000] Thread (main_thread) [0x00c200c4]} sys_prx: Loaded module: /dev_flash/sys/external/libat3dec.sprx
S {PPU[0x1000000] Thread (main_thread) [0x00c200c4]} PPU: LLVM: Loaded module v2-libatxdec.sprx-6D48FF4B62CB07E2-haswell.obj
S {PPU[0x1000000] Thread (main_thread) [0x00c200c4]} sys_prx: Loaded module: /dev_flash/sys/external/libatxdec.sprx
S {PPU[0x1000000] Thread (main_thread) [0x00c200c4]} PPU: LLVM: Loaded module v2-libatrac3plus.sprx-579A6F0C799EE900-haswell.obj
S {PPU[0x1000000] Thread (main_thread) [0x00c200c4]} sys_prx: Loaded module: /dev_flash/sys/external/libatrac3plus.sprx
S {PPU[0x1000000] Thread (main_thread) [0x00c200c4]} PPU: LLVM: Loaded module v2-libl10n.sprx-CF794CD12F0202AD-haswell.obj
S {PPU[0x1000000] Thread (main_thread) [0x00c200c4]} sys_prx: Loaded module: /dev_flash/sys/external/libl10n.sprx
S {PPU[0x1000000] Thread (main_thread) [0x00c200c4]} PPU: LLVM: Loaded module v2-libac3dec.sprx-59DFFFC9625469CF-haswell.obj
S {PPU[0x1000000] Thread (main_thread) [0x00c200c4]} sys_prx: Loaded module: /dev_flash/sys/external/libac3dec.sprx
S {PPU[0x1000000] Thread (main_thread) [0x00c200c4]} PPU: LLVM: Loaded module v2-libsail.sprx-92282F9CBDEF4FDC-haswell.obj
S {PPU[0x1000000] Thread (main_thread) [0x00c200c4]} sys_prx: Loaded module: /dev_flash/sys/external/libsail.sprx
U {PPU[0x1000000] Thread (main_thread) [0x00ea41c4]} HLE TODO: Unimplemented syscall sys_ss_access_control_engine -> CELL_OK
S {PPU[0x1000000] Thread (main_thread) [0x00c200c4]} PPU: LLVM: Loaded module v2-librtc.sprx-9CB190F178FA7E82-haswell.obj
S {PPU[0x1000000] Thread (main_thread) [0x00c200c4]} sys_prx: Loaded module: /dev_flash/sys/external/librtc.sprx
S {PPU[0x1000000] Thread (main_thread) [0x00c200c4]} PPU: LLVM: Loaded module v2-libfiber.sprx-90B538A6D4A84178-haswell.obj
S {PPU[0x1000000] Thread (main_thread) [0x00c200c4]} sys_prx: Loaded module: /dev_flash/sys/external/libfiber.sprx
S {PPU[0x1000000] Thread (main_thread) [0x00c200c4]} PPU: LLVM: Loaded module v2-libspurs_jq.sprx-356285E488E56CBE-haswell.obj
S {PPU[0x1000000] Thread (main_thread) [0x00c200c4]} sys_prx: Loaded module: /dev_flash/sys/external/libspurs_jq.sprx
S {PPU[0x1000000] Thread (main_thread) [0x00c200c4]} PPU: LLVM: Loaded module v2-libnet.sprx-FFB9AC229DA8A825-haswell.obj
S {PPU[0x1000000] Thread (main_thread) [0x00c200c4]} sys_prx: Loaded module: /dev_flash/sys/external/libnet.sprx
U {PPU[0x1000000] Thread (main_thread) [0x00cc7d80]} sys_spu TODO: Unimplemented SPU Thread options (0x2) x5
U {PPU[0x1000000] Thread (main_thread) [0x00ccde58]} sys_prx TODO: _sys_prx_get_module_id_by_name(name=“cellLibprof”, flags=0, pOpt=*0x0)
E {PPU[0x1000000] Thread (main_thread) [0x00ccde58]} 'sys_prx_get_module_id_by_name' failed with 0x8001112e : CELL_PRX_ERROR_UNKNOWN_MODULE [1]
S {rsx::thread} RSX: New program compiled successfully x123
E {rsx::thread} RSX: NV3089_IMAGE_IN_SIZE: Invalid blit dimensions passed
U {PPU[0x1000000] Thread (main_thread) [0x00377ddc]} cellSysutil TODO: cellVideoOutConfigure(videoOut=0, config=*0xd0020470, option=*0xd0020480, waitForEvent=0)
E {PPU[0x1000000] Thread (main_thread) [0x004ba650]} 'sys_lwmutex_lock' failed with 0x80010005 : CELL_ESRCH [1]
E {PPU[0x1000000] Thread (main_thread) [0x004be5e4]} 'sys_lwmutex_unlock' failed with 0x80010009 : CELL_EPERM [1]
E {PPU[0x1000000] Thread (main_thread) [0x004be6f8]} 'sys_lwmutex_lock' failed with 0x80010005 : CELL_ESRCH [2]
E {PPU[0x1000000] Thread (main_thread) [0x004ba650]} 'sys_lwmutex_unlock' failed with 0x80010009 : CELL_EPERM [2]
E {PPU[0x1000000] Thread (main_thread) [0x004ba650]} 'sys_lwmutex_lock' failed with 0x80010005 : CELL_ESRCH [3]
E {PPU[0x1000000] Thread (main_thread) [0x004be5e4]} 'sys_lwmutex_unlock' failed with 0x80010009 : CELL_EPERM [3]
U {PPU[0x1000000] Thread (main_thread) [0x001bd7dc]} cellMusic TODO: cellMusicInitialize2(mode=0, spuPriority=250, func=*0x672830, userData=*0x0)
U {PPU[0x1000000] Thread (main_thread) [0x001bd830]} cellMusic TODO: cellMusicSetVolume2(level=0x0)
S {Audio Thread} XAudio 2.9 initialized
U {PPU[0x1000019] Thread (_GameStateInitialize) [0x00483c8c]} cellNetCtl TODO: cellNetCtlAddHandler(handler=*0x67a1d8, arg=*0x0, hid=*0x2250d1e8)
U {PPU[0x1000019] Thread (_GameStateInitialize) [0x003847e8]} sceNp TODO: sceNpBasicRegisterContextSensitiveHandler
E {PPU[0x100001a] Thread (CThread) [0x0035391c]} sceNpTrophy: sceNpTrophyRegisterContext(context=0x1, handle=0x1, statusCb=*0x6764e8, arg=*0x0, options=0x0)
E {PPU[0x100001a] Thread (CThread) [0x0035391c]} sceNpTrophy: sceNpTrophyGetTrophyUnlockState(context=0x1, handle=0x1, flags=*0x22235614, count=*0xd02a4c44)
E {PPU[0x1000000] Thread (main_thread) [0x0036b3bc]} Stat: 'sys_lwmutex_lock' failed with 0x80010005 : CELL_ESRCH [x24]
E {PPU[0x1000000] Thread (main_thread) [0x0036b3bc]} Stat: 'sys_lwmutex_unlock' failed with 0x80010009 : CELL_EPERM [x24]
S LDR: Boot successful.
S {PPU[0x1000000] Thread (main_thread)} SPU: SPU Recompiler Runtime (ASMJIT) initialized...
E {PPU[0x1000000] Thread (main_thread)} SPU: [0x0b0bc] SPU Analyser failed, 21 vs 130
E {PPU[0x1000000] Thread (main_thread)} SPU: [0x0b514] SPU Analyser failed, 24 vs 331
S {PPU[0x1000000] Thread (main_thread)} SPU: SPU Runtime: Built 5206 functions.
S {PPU[0x1000000] Thread (main_thread)} PPU: LLVM: Loaded module v2+010200-37BE7BE390AD324B-haswell.obj
S {PPU[0x1000000] Thread (main_thread)} PPU: LLVM: Loaded module v2+0524E0-CE972BB1E8B5FB18-haswell.obj
S {PPU[0x1000000] Thread (main_thread)} PPU: LLVM: Loaded module v2+095200-EFF83BE83C3ADB3D-haswell.obj
S {PPU[0x1000000] Thread (main_thread)} PPU: LLVM: Loaded module v2+0D6538-EF47B49B95D1C803-haswell.obj
S {PPU[0x1000000] Thread (main_thread)} PPU: LLVM: Loaded module v2+117B44-160F5690357B119E-haswell.obj
S {PPU[0x1000000] Thread (main_thread)} PPU: LLVM: Loaded module v2+15925C-56751129E5C6902B-haswell.obj
S {PPU[0x1000000] Thread (main_thread)} PPU: LLVM: Loaded module v2+199828-E1683C33FDF4DB05-haswell.obj
S {PPU[0x1000000] Thread (main_thread)} PPU: LLVM: Loaded module v2+1DA318-684F51FD2A9CD88A-haswell.obj
S {PPU[0x1000000] Thread (main_thread)} PPU: LLVM: Loaded module v2+21C7B4-39CE8F2270752B5B-haswell.obj
S {PPU[0x1000000] Thread (main_thread)} PPU: LLVM: Loaded module v2+25D3B8-A2EA920CB762CA4A-haswell.obj
S {PPU[0x1000000] Thread (main_thread)} PPU: LLVM: Loaded module v2+29E188-ED1C04A50DFD902A-haswell.obj
S {PPU[0x1000000] Thread (main_thread)} PPU: LLVM: Loaded module v2+2DF110-AB0DCAD5E80B7D40-haswell.obj
S {PPU[0x1000000] Thread (main_thread)} PPU: LLVM: Loaded module v2+320204-CF7C661A5F7DD113-haswell.obj
S {PPU[0x1000000] Thread (main_thread)} PPU: LLVM: Loaded module v2+360B64-2041A66517BAA433-haswell.obj
S {PPU[0x1000000] Thread (main_thread)} PPU: LLVM: Loaded module v2+3A10C0-88769D3A8AB47532-haswell.obj
S {PPU[0x1000000] Thread (main_thread)} PPU: LLVM: Loaded module v2+3E2E20-8EC65AB14AA7E5CF-haswell.obj
S {PPU[0x1000000] Thread (main_thread)} PPU: LLVM: Loaded module v2+425148-7073D01BB81681F5-haswell.obj
S {PPU[0x1000000] Thread (main_thread)} PPU: LLVM: Loaded module v2+4676D0-534326908E74F69C-haswell.obj
S {PPU[0x1000000] Thread (main_thread)} PPU: LLVM: Loaded module v2+4A7A74-2F90EE2EDC7222B0-haswell.obj
S {PPU[0x1000000] Thread (main_thread)} PPU: LLVM: Loaded module v2+4E7CE0-AC6D58B82BFC4476-haswell.obj
S {PPU[0x1000000] Thread (main_thread)} PPU: LLVM: Loaded module v2-libsysmodule.sprx-E926430A8C1D5DCB-haswell.obj
U {PPU[0x1000000] Thread (main_thread) [0x00c23d8c]} HLE TODO: Unimplemented syscall sys_ss_access_control_engine -> CELL_OK
U {PPU[0x1000000] Thread (main_thread) [0x00c22efc]} sysPrxForUser TODO: sys_prx_load_module_list(count=7, path_list=**0xd0020bfc, flags=0x0, pOpt=*0x0, id_list=*0xd0020bdc)
S {PPU[0x1000000] Thread (main_thread) [0x00c22efc]} PPU: LLVM: Loaded module v2-libgcm_sys.sprx-92BB3C6B43076AD9-haswell.obj
S {PPU[0x1000000] Thread (main_thread) [0x00c22efc]} sys_prx: Loaded module: /dev_flash/sys/external/libgcm_sys.sprx
S {PPU[0x1000000] Thread (main_thread) [0x00c22efc]} PPU: LLVM: Loaded module v2-libsre.sprx-7BD57B68D8CA8EBC-haswell.obj
S {PPU[0x1000000] Thread (main_thread) [0x00c22efc]} sys_prx: Loaded module: /dev_flash/sys/external/libsre.sprx
S {PPU[0x1000000] Thread (main_thread) [0x00c22efc]} PPU: LLVM: Loaded module v2-libfs.sprx-BB8655E4C5C49381-haswell.obj
S {PPU[0x1000000] Thread (main_thread) [0x00c22efc]} sys_prx: Loaded module: /dev_flash/sys/external/libfs.sprx
S {PPU[0x1000000] Thread (main_thread) [0x00c200c4]} PPU: LLVM: Loaded module v2-libresc.sprx-868A23FA3425D270-haswell.obj
S {PPU[0x1000000] Thread (main_thread) [0x00c200c4]} sys_prx: Loaded module: /dev_flash/sys/external/libresc.sprx
S {PPU[0x1000000] Thread (main_thread) [0x00c200c4]} PPU: LLVM: Loaded module v2-libadec.sprx-C1FA8E97F96CF507-haswell.obj
S {PPU[0x1000000] Thread (main_thread) [0x00c200c4]} sys_prx: Loaded module: /dev_flash/sys/external/libadec.sprx
S {PPU[0x1000000] Thread (main_thread) [0x00c200c4]} PPU: LLVM: Loaded module v2-libat3dec.sprx-CF7CA4764ADFE9E1-haswell.obj
S {PPU[0x1000000] Thread (main_thread) [0x00c200c4]} sys_prx: Loaded module: /dev_flash/sys/external/libat3dec.sprx
S {PPU[0x1000000] Thread (main_thread) [0x00c200c4]} PPU: LLVM: Loaded module v2-libatxdec.sprx-6D48FF4B62CB07E2-haswell.obj
S {PPU[0x1000000] Thread (main_thread) [0x00c200c4]} sys_prx: Loaded module: /dev_flash/sys/external/libatxdec.sprx
S {PPU[0x1000000] Thread (main_thread) [0x00c200c4]} PPU: LLVM: Loaded module v2-libatrac3plus.sprx-579A6F0C799EE900-haswell.obj
S {PPU[0x1000000] Thread (main_thread) [0x00c200c4]} sys_prx: Loaded module: /dev_flash/sys/external/libatrac3plus.sprx
S {PPU[0x1000000] Thread (main_thread) [0x00c200c4]} PPU: LLVM: Loaded module v2-libl10n.sprx-CF794CD12F0202AD-haswell.obj
S {PPU[0x1000000] Thread (main_thread) [0x00c200c4]} sys_prx: Loaded module: /dev_flash/sys/external/libl10n.sprx
S {PPU[0x1000000] Thread (main_thread) [0x00c200c4]} PPU: LLVM: Loaded module v2-libac3dec.sprx-59DFFFC9625469CF-haswell.obj
S {PPU[0x1000000] Thread (main_thread) [0x00c200c4]} sys_prx: Loaded module: /dev_flash/sys/external/libac3dec.sprx
S {PPU[0x1000000] Thread (main_thread) [0x00c200c4]} PPU: LLVM: Loaded module v2-libsail.sprx-92282F9CBDEF4FDC-haswell.obj
S {PPU[0x1000000] Thread (main_thread) [0x00c200c4]} sys_prx: Loaded module: /dev_flash/sys/external/libsail.sprx
U {PPU[0x1000000] Thread (main_thread) [0x00ea41c4]} HLE TODO: Unimplemented syscall sys_ss_access_control_engine -> CELL_OK
S {PPU[0x1000000] Thread (main_thread) [0x00c200c4]} PPU: LLVM: Loaded module v2-librtc.sprx-9CB190F178FA7E82-haswell.obj
S {PPU[0x1000000] Thread (main_thread) [0x00c200c4]} sys_prx: Loaded module: /dev_flash/sys/external/librtc.sprx
S {PPU[0x1000000] Thread (main_thread) [0x00c200c4]} PPU: LLVM: Loaded module v2-libfiber.sprx-90B538A6D4A84178-haswell.obj
S {PPU[0x1000000] Thread (main_thread) [0x00c200c4]} sys_prx: Loaded module: /dev_flash/sys/external/libfiber.sprx
S {PPU[0x1000000] Thread (main_thread) [0x00c200c4]} PPU: LLVM: Loaded module v2-libspurs_jq.sprx-356285E488E56CBE-haswell.obj
S {PPU[0x1000000] Thread (main_thread) [0x00c200c4]} sys_prx: Loaded module: /dev_flash/sys/external/libspurs_jq.sprx
S {PPU[0x1000000] Thread (main_thread) [0x00c200c4]} PPU: LLVM: Loaded module v2-libnet.sprx-FFB9AC229DA8A825-haswell.obj
S {PPU[0x1000000] Thread (main_thread) [0x00c200c4]} sys_prx: Loaded module: /dev_flash/sys/external/libnet.sprx
U {PPU[0x1000000] Thread (main_thread) [0x00cc7d80]} sys_spu TODO: Unimplemented SPU Thread options (0x2) x5
U {PPU[0x1000000] Thread (main_thread) [0x00ccde58]} sys_prx TODO: _sys_prx_get_module_id_by_name(name=“cellLibprof”, flags=0, pOpt=*0x0)
E {PPU[0x1000000] Thread (main_thread) [0x00ccde58]} 'sys_prx_get_module_id_by_name' failed with 0x8001112e : CELL_PRX_ERROR_UNKNOWN_MODULE [1]
S {rsx::thread} RSX: New program compiled successfully x123
E {rsx::thread} RSX: NV3089_IMAGE_IN_SIZE: Invalid blit dimensions passed
U {PPU[0x1000000] Thread (main_thread) [0x00377ddc]} cellSysutil TODO: cellVideoOutConfigure(videoOut=0, config=*0xd0020470, option=*0xd0020480, waitForEvent=0)
E {PPU[0x1000000] Thread (main_thread) [0x004ba650]} 'sys_lwmutex_lock' failed with 0x80010005 : CELL_ESRCH [1]
E {PPU[0x1000000] Thread (main_thread) [0x004be5e4]} 'sys_lwmutex_unlock' failed with 0x80010009 : CELL_EPERM [1]
E {PPU[0x1000000] Thread (main_thread) [0x004be6f8]} 'sys_lwmutex_lock' failed with 0x80010005 : CELL_ESRCH [2]
E {PPU[0x1000000] Thread (main_thread) [0x004ba650]} 'sys_lwmutex_unlock' failed with 0x80010009 : CELL_EPERM [2]
E {PPU[0x1000000] Thread (main_thread) [0x004ba650]} 'sys_lwmutex_lock' failed with 0x80010005 : CELL_ESRCH [3]
E {PPU[0x1000000] Thread (main_thread) [0x004be5e4]} 'sys_lwmutex_unlock' failed with 0x80010009 : CELL_EPERM [3]
S {Audio Thread} XAudio 2.9 initialized
U {PPU[0x1000000] Thread (main_thread) [0x001bd7dc]} cellMusic TODO: cellMusicInitialize2(mode=0, spuPriority=250, func=*0x672830, userData=*0x0)
U {PPU[0x1000000] Thread (main_thread) [0x001bd830]} cellMusic TODO: cellMusicSetVolume2(level=0x0)
S HLE: MMJOY Device 0 reconnected.
U {PPU[0x1000019] Thread (_GameStateInitialize) [0x00483c8c]} cellNetCtl TODO: cellNetCtlAddHandler(handler=*0x67a1d8, arg=*0x0, hid=*0x2250d1e8)
U {PPU[0x1000019] Thread (_GameStateInitialize) [0x003847e8]} sceNp TODO: sceNpBasicRegisterContextSensitiveHandler
E {PPU[0x100001a] Thread (CThread) [0x0035391c]} sceNpTrophy: sceNpTrophyRegisterContext(context=0x1, handle=0x1, statusCb=*0x6764e8, arg=*0x0, options=0x0)
E {PPU[0x100001a] Thread (CThread) [0x0035391c]} sceNpTrophy: sceNpTrophyGetTrophyUnlockState(context=0x1, handle=0x1, flags=*0x22235614, count=*0xd02a4c44)
E {PPU[0x1000013] Thread (KtslSeDriver) [0x004c25fc]} 'sys_lwmutex_lock' failed with 0x80010008 : CELL_EDEADLK [1]
E {PPU[0x1000013] Thread (KtslSeDriver) [0x004c2598]} 'sys_lwmutex_unlock' failed with 0x80010009 : CELL_EPERM [1]
E {PPU[0x1000013] Thread (KtslSeDriver) [0x004c25fc]} 'sys_lwmutex_lock' failed with 0x80010008 : CELL_EDEADLK [2]
E {PPU[0x1000013] Thread (KtslSeDriver) [0x004c2598]} 'sys_lwmutex_unlock' failed with 0x80010009 : CELL_EPERM [2]
U {PPU[0x1000000] Thread (main_thread) [0x001c4bb0]} cellMusic TODO: cellMusicSetVolume2(level=0x0)
E {PPU[0x100000f] Thread (KtslAt3Decoder) [0x004c25fc]} 'sys_lwmutex_lock' failed with 0x80010008 : CELL_EDEADLK [1]
E {PPU[0x100000f] Thread (KtslAt3Decoder) [0x004c2598]} 'sys_lwmutex_unlock' failed with 0x80010009 : CELL_EPERM [1]
E {PPU[0x1000013] Thread (KtslSeDriver) [0x004c25fc]} 'sys_lwmutex_lock' failed with 0x80010008 : CELL_EDEADLK [3]
E {PPU[0x1000013] Thread (KtslSeDriver) [0x004c2598]} 'sys_lwmutex_unlock' failed with 0x80010009 : CELL_EPERM [3]
E {PPU[0x100000d] Thread (KtslAt3Decoder) [0x004c25fc]} 'sys_lwmutex_lock' failed with 0x80010008 : CELL_EDEADLK [1]
E {PPU[0x100000d] Thread (KtslAt3Decoder) [0x004c2598]} 'sys_lwmutex_unlock' failed with 0x80010009 : CELL_EPERM [1]
E {PPU[0x100000f] Thread (KtslAt3Decoder) [0x004bf2dc]} 'sys_lwmutex_lock' failed with 0x80010008 : CELL_EDEADLK [2]
E {PPU[0x100000f] Thread (KtslAt3Decoder) [0x004ba650]} 'sys_lwmutex_unlock' failed with 0x80010009 : CELL_EPERM [2]
E {PPU[0x100000f] Thread (KtslAt3Decoder) [0x004c25fc]} 'sys_lwmutex_lock' failed with 0x80010008 : CELL_EDEADLK [3]
E {PPU[0x100000f] Thread (KtslAt3Decoder) [0x004c2598]} 'sys_lwmutex_unlock' failed with 0x80010009 : CELL_EPERM [3]
E {PPU[0x100000d] Thread (KtslAt3Decoder) [0x004bf2dc]} 'sys_lwmutex_lock' failed with 0x80010008 : CELL_EDEADLK [2]
E {PPU[0x100000d] Thread (KtslAt3Decoder) [0x004ba650]} 'sys_lwmutex_unlock' failed with 0x80010009 : CELL_EPERM [2]
E {PPU[0x100000d] Thread (KtslAt3Decoder) [0x004c25fc]} 'sys_lwmutex_lock' failed with 0x80010008 : CELL_EDEADLK [3]
E {PPU[0x100000d] Thread (KtslAt3Decoder) [0x004c2598]} 'sys_lwmutex_unlock' failed with 0x80010009 : CELL_EPERM [3]
E {PPU[0x1000014] Thread (KtslAt3Decoder) [0x004c25fc]} 'sys_lwmutex_lock' failed with 0x80010008 : CELL_EDEADLK [1]
E {PPU[0x1000014] Thread (KtslAt3Decoder) [0x004c2598]} 'sys_lwmutex_unlock' failed with 0x80010009 : CELL_EPERM [1]
E {PPU[0x1000014] Thread (KtslAt3Decoder) [0x004bf2dc]} 'sys_lwmutex_lock' failed with 0x80010008 : CELL_EDEADLK [2]
E {PPU[0x1000014] Thread (KtslAt3Decoder) [0x004ba650]} 'sys_lwmutex_unlock' failed with 0x80010009 : CELL_EPERM [2]
S {PPU[0x1000047] Thread (_libsail-control) [0x00c200c4]} PPU: LLVM: Loaded module v2-libpamf.sprx-9395500A1659F740-haswell.obj
S {PPU[0x1000047] Thread (_libsail-control) [0x00c200c4]} sys_prx: Loaded module: /dev_flash/sys/external/libpamf.sprx
S {PPU[0x1000047] Thread (_libsail-control) [0x00c200c4]} PPU: LLVM: Loaded module v2-libdmux.sprx-163476C36B290E2B-haswell.obj
S {PPU[0x1000047] Thread (_libsail-control) [0x00c200c4]} sys_prx: Loaded module: /dev_flash/sys/external/libdmux.sprx
S {PPU[0x1000047] Thread (_libsail-control) [0x00c200c4]} PPU: LLVM: Loaded module v2-libdmuxpamf.sprx-8A70960BBED2AB60-haswell.obj
S {PPU[0x1000047] Thread (_libsail-control) [0x00c200c4]} sys_prx: Loaded module: /dev_flash/sys/external/libdmuxpamf.sprx
S {PPU[0x1000047] Thread (_libsail-control) [0x00c200c4]} PPU: LLVM: Loaded module v2-libsmvd2.sprx-FFB2AC5120590192-haswell.obj
S {PPU[0x1000047] Thread (_libsail-control) [0x00c200c4]} sys_prx: Loaded module: /dev_flash/sys/external/libsmvd2.sprx
E {PPU[0x100000b] Thread (KtslAudioPort) [0x004c25fc]} 'sys_lwmutex_lock' failed with 0x80010008 : CELL_EDEADLK [1]
E {PPU[0x100000b] Thread (KtslAudioPort) [0x004c2598]} 'sys_lwmutex_unlock' failed with 0x80010009 : CELL_EPERM [1]
U {PPU[0x1000047] Thread (_libsail-control) [0x00c203a0]} sys_prx TODO: _sys_prx_unload_module(id=0x2304fd00, flags=0x0, pOpt=*0x0)
U {PPU[0x1000047] Thread (_libsail-control) [0x00c203a0]} sys_prx TODO: _sys_prx_unload_module(id=0x2304fc00, flags=0x0, pOpt=*0x0)
U {PPU[0x1000047] Thread (_libsail-control) [0x00c203a0]} sys_prx TODO: _sys_prx_unload_module(id=0x2304e800, flags=0x0, pOpt=*0x0)
U {PPU[0x1000047] Thread (_libsail-control) [0x00c203a0]} sys_prx TODO: _sys_prx_unload_module(id=0x2304e700, flags=0x0, pOpt=*0x0)
U {PPU[0x1000047] Thread (_libsail-control) [0x00c203a0]} sys_prx TODO: _sys_prx_unload_module(id=0x2304e400, flags=0x0, pOpt=*0x0)
S {rsx::thread} RSX: New program compiled successfully x3
E {PPU[0x1000014] Thread (KtslAt3Decoder) [0x004c25fc]} 'sys_lwmutex_lock' failed with 0x80010008 : CELL_EDEADLK [3]
E {PPU[0x1000014] Thread (KtslAt3Decoder) [0x004c2598]} 'sys_lwmutex_unlock' failed with 0x80010009 : CELL_EPERM [3]
S {rsx::thread} RSX: New program compiled successfully x4
F {PPU[0x1000044] Thread (CStageSceneBuilder) [0x0021dfc4]} MEM: Access violation reading location 0x10010010

**Comment by reaper185** [comment] 2018-05-15 00:33
Same issue with me. Already opened an issue some days ago haven't gotten an answer as to why this keeps happening.

CPU: Intel i7-7500u
GPU: Intel HD Graphics 620
RAM: 16GB
SSD 250GB
RPCS3 v0.0.5-6742-04ad49de4 Alpha
PPU: LLVM Recompiler
SPU: ASMJIT
Renderer: Vulkan
[RPCS3.log.gz](https://github.com/RPCS3/rpcs3/files/2003050/RPCS3.log.gz)

**Comment by AniLeo** [comment] 2018-05-20 19:15
Invalid report and duplicate of #4547

**Closed by AniLeo** 2018-05-20 19:15 UTC
Labels: Meta: Duplicate, Meta: Invalid
