### ISSUE TITLE
GT 6 error_freezing

### ISSUE THREAD

**Issue by sett-xp** [RPCS3/rpcs3#9713] opened 2021-02-03 13:30 UTC
these errors cause the emulator to freeze 

GT 6
F {SPU[0x1000100] Thread (PDICellSpursKernel1) [0x1033c]} SIG: Thread terminated due to fatal error: Unknown STOP code: 0x0 (op=0x0, Out_MBox=empty)
(rpcs3\Emu\Cell\SPUThread.cpp:4559[:22], in function stop_and_signal)

every time when loading the game gt 6 ppu decoder gives this error - due to which some races are impossible.

even if i change
to another decoder

**Comment by Satan86** [comment] 2021-02-03 13:34
Duplicate of #7765

**Comment by sett-xp** [comment] 2021-02-03 13:39
did not know!

**Closed** 2021-02-03 13:38 UTC
