### ISSUE TITLE
[Feature request] Implement a game updater.

### ISSUE THREAD

**Issue by Tydium** [RPCS3/rpcs3#13475] opened 2023-03-01 22:03 UTC
### Quick summary

I'm pretty sure this has been thought about before. However it would be really cool to have games auto/manual update inside of RPCS3. The RPCS3 discord already has a feature for searching for updates with the bot (with the links as well).

### Details

I have a few methods for having an auto update feature.

- RPCS3 on start-up can ask the user if they would like to auto update all games or a select few.
- Maybe in the Utilities tab we can have an Updates button.
- When right clicking the game you can have a download updates feature or "check for updates. Yet again it already does "Check for updates" when the application boots. So instead of checking for updates it should instead say "Download Updates" when an update appears.
- Like the normal PS3 you can also have the emulator ask the user to update the game when it boots. They can decline or accept here as well.

Those are just a few ideas I have. I think this would make lives pretty easy for everyone.

**Comment by AniLeo** [comment] 2023-03-01 22:07
We didn't implement this inside the emulator on purpose
Closing as duplicate of #10083

**Closed by AniLeo** 2023-03-01 22:07 UTC
