### ISSUE TITLE
DX12: Gradient Post Process not blending on screen on Bayonetta 

### ISSUE THREAD

**Issue by Kristiqn5** [RPCS3/rpcs3#1942] opened 2016-07-18 22:31 UTC
![i894 cimgpsh_orig](https://cloud.githubusercontent.com/assets/13494982/16932583/cd632a98-4d4f-11e6-99e9-792252e3a027.png)
In the demo theres no post process used in the first cutscene so you could see, the background rendered perfectly ( with some vertex corruptions here and there ) and models kinda did not
![bayonet 2](https://cloud.githubusercontent.com/assets/13494982/16932616/248db432-4d50-11e6-97a4-ecb6381610e1.png)
![bayonet 3](https://cloud.githubusercontent.com/assets/13494982/16932636/4c895b08-4d50-11e6-91ea-155a889dccfb.png)
I used PR #1931

**Comment by kd-11** [comment] 2016-07-20 08:29
Does this only affect dx12? What happens with other backends?

**Comment by Kristiqn5** [comment] 2016-07-20 08:49
bayonetta wont run on vulkan, crashes the emulator after the P+ intro, opengl goes little bit further into menu, but freezes on the loading screen when going ingame and gives this
{rsx::thread} class std::runtime_error thrown: OpenGL error: invalid operation. file 'C:\rpcs3\rpcs3\Emu\RSX\GL\GLGSRender.cpp' function 'GLGSRender::end' line 415

so yea currently only dx12 can run it

**Comment by raven02** [comment] 2016-07-20 08:57
Alright .Thanks for the report.

**Comment by Kristiqn5** [comment] 2016-07-21 22:16
@kd-11 
@raven02 

I think this should help somehow
http://cemu.info/changelog/cemu_1_5_0.txt
cemu had the same issue as rpcs3 with bayonetta and cemu 1.5.0 fixed the issue, might be worth looking in the changelog to see what fixed it 

cemu 1.4.2 : https://www.youtube.com/watch?v=zyKigIv2bL4
cemu 1.5.0 : https://www.youtube.com/watch?v=ddtrWLp5xuk

**Comment by kd-11** [comment] 2016-07-22 07:16
Looks like they fixed some texture formats. I dont have access to any amd dx12 debugging tools and I havent seen any good frame debuggers for dx12 except maybe nsight but that only works with nvidia gpus. Does vulkan crash the emulator from windows i.e "rpcs3 has stopped working" or in the emulator with a message?

**Comment by raven02** [comment] 2016-07-22 07:34
I run it in debug mode in VS2015 , it also breaks at the following line 

CHECK_RESULT(m_swap_chain->queuePresentKHR(m_swap_chain->get_present_queue(), &present));

**Comment by Kristiqn5** [comment] 2016-07-22 09:55
@kd-11 yea, as I said, vulkan crashes after the P+ intro with stopped working

**Comment by SakataGintokiYT** [comment] 2016-07-22 10:47
@kd-11 
What about this ?
 http://developer.amd.com/tools-and-sdks/graphics-development/gpu-perfstudio/

**Comment by kd-11** [comment] 2016-07-22 13:45
GPU Perf Studio is only useful for opengl. The vulkan and dx12 debugging has no frame debugger where you can inspect individual draw calls, just a command log. Its useful, but you cannot tell what draw call draws what part which is what is usually useful and has no real time shader editing. It also has some annoying bugs which I have reported but are yet to be resolved. Renderdoc is so much better and I moved to using it, but no dx12 support, only gl and vulkan.

**Comment by kd-11** [comment] 2016-07-22 13:48
@raven02 queuePresentKHR exception implies resource is being used concurrently, an issue that is very difficult to debug. We could add intentional stalls but that is usually a crazy solution. Is it a regression?

**Comment by raven02** [comment] 2016-07-22 17:24
@kd-11 .Not too sure if it is an regression .I will try to track back some very old build that first provide vulkan nvidia support to see if it crashes.

**Comment by kd-11** [comment] 2016-07-23 15:00
@raven02 Disable __glcheck in gl_helpers.h (change #if 1 to #ifdef _DEBUG, you can see the original commented out) for release builds and enable debug output instead. The driver will give more meaningful messages. __glcheck is only suitable when the developer is the one doing the debugging with the game.

**Comment by raven02** [comment] 2016-07-23 15:24
Alright .Will try it out shortly

**Comment by raven02** [comment] 2016-08-07 06:27
@kd-11 , regarding disable _glcheck , is it applicable for vulkan that we can use it to debug the queuePresentKHR exception ? (I just hit another queuePresentKHR exception in another game )

**Comment by raven02** [comment] 2016-08-07 06:39
Look like quite many game using Vulkan will suddently break and they all hit the  queuePresentKHR exception 

CHECK_RESULT(m_swap_chain->queuePresentKHR(m_swap_chain->get_present_queue(), &present));

![untitled](https://cloud.githubusercontent.com/assets/3000282/17460939/b0582ac2-5cac-11e6-9f61-bc488886341c.jpg)

**Comment by raven02** [comment] 2016-08-07 06:47
or i can test with intentional stalls ?

**Comment by kd-11** [comment] 2016-08-07 07:19
You can stall the pipeline manually (using sleep) to check whether we are skipping a wait somewhere. Its rather difficult to debug this without access to the hardware and drivers though. Is it for all games? If not, what is different about the games that cause the crash?

By the way, check if any gcm samples can trigger this. That would be so much easier to check.

**Comment by raven02** [comment] 2016-08-07 08:00
It is not for all games i believe and i checked few GCM samples also not able to trigger . 

I try to enable the debug output option to run this crash scene , other than hits the queuePresentKHR exception , the exact moment crash shows this 

·E {rsx::thread} RSX: ERROR: [DS] Code 32 : You must call vkBeginCommandBuffer() before this call to vkCmdBeginRenderPass()
·E {rsx::thread} RSX: ERROR: [DS] Code 32 : You must call vkBeginCommandBuffer() before this call to vkCmdBindPipeline()
·E {rsx::thread} RSX: ERROR: [DS] Code 32 : You must call vkBeginCommandBuffer() before this call to vkCmdBindDescriptorSets()
·E {rsx::thread} RSX: ERROR: [DS] Code 32 : You must call vkBeginCommandBuffer() before this call to vkCmdDraw()
·E {rsx::thread} RSX: ERROR: [DS] Code 52 : DS 0x822151 encountered the following validation error at draw time: Descriptor in binding #21 at global descriptor index 20 is being used in draw but has not been updated.
·E {rsx::thread} RSX: ERROR: [DS] Code 32 : You must call vkBeginCommandBuffer() before this call to vkCmdEndRenderPass()
·E {rsx::thread} RSX: ERROR: [DS] Code 32 : You must call vkBeginCommandBuffer() before this call to vkCmdSetViewport()
·E {rsx::thread} RSX: ERROR: [DS] Code 32 : You must call vkBeginCommandBuffer() before this call to vkCmdSetScissor()
·E {rsx::thread} RSX: ERROR: [DS] Code 32 : You must call vkBeginCommandBuffer() before this call to vkCmdSetLineWidth()
·E {rsx::thread} RSX: ERROR: [DS] Code 32 : You must call vkBeginCommandBuffer() before this call to vkCmdBeginRenderPass()
·E {rsx::thread} RSX: ERROR: [DS] Code 32 : You must call vkBeginCommandBuffer() before this call to vkCmdBindPipeline()
·E {rsx::thread} RSX: ERROR: [DS] Code 32 : You must call vkBeginCommandBuffer() before this call to vkCmdBindDescriptorSets()
·E {rsx::thread} RSX: ERROR: [DS] Code 32 : You must call vkBeginCommandBuffer() before this call to vkCmdDraw()
·E {rsx::thread} RSX: ERROR: [DS] Code 52 : DS 0x822151 encountered the following validation error at draw time: Descriptor in binding #21 at global descriptor index 20 is being used in draw but has not been updated.
·E {rsx::thread} RSX: ERROR: [DS] Code 32 : You must call vkBeginCommandBuffer() before this call to vkCmdEndRenderPass()
·E {rsx::thread} RSX: ERROR: [DS] Code 32 : You must call vkBeginCommandBuffer() before this call to vkEndCommandBuffer()
·E {rsx::thread} RSX: ERROR: [DS] Code 7 : Cannot submit cmd buffer using deleted image 0x821f17.

**Comment by raven02** [comment] 2016-08-07 08:14
I wonder would there some cases that fence is not unsignaled yet and we then try to submit queue.

**Comment by kd-11** [comment] 2016-08-07 09:24
Yea. The crash is here:
> ·E {rsx::thread} RSX: ERROR: [DS] Code 7 : Cannot submit cmd buffer using deleted image 0x821f17

You'll have to inspect the lifetime of vk::image objects to find out what was deleted while in use (probably a framebuffer). Try blocking after every queuePresentKHR before m_invalidated_resources is cleared. m_invalidated_resources contains rtt images that we deem to be not useful anymore and can be recycled or destroyed.

**Comment by raven02** [comment] 2016-08-07 09:37
humm i tried to comment out the //m_rtts.invalidated_resources.clear(); but it didn't help.

**Comment by raven02** [comment] 2016-08-07 11:08
Just wonder how to do blocking after queuePresentKHR before m_rtts.invalidated_resources.clear() ?

**Comment by kd-11** [comment] 2016-08-07 18:06
You can stall manually (thread sleep) or add a pipeline barrier with ALL_GRAPHICS_BIT and wait on that (should be similar to issuing a glFinish()). I think it will be easier to just add messages to any image creation and deletion points. I think VkImage will be a ptr handle so you can add messages to check which image gets created/deleted and compare with the output from the debug layer.

**Comment by raven02** [comment] 2016-08-08 03:37
Yep , will try to add messages to image create/delete and compare with log output

**Comment by raven02** [comment] 2016-08-08 14:06
I track it here 

		~image()
		{
			LOG_ERROR(RSX, "Deleted image 0x%x", value);
			vkDestroyImage(m_device, value, nullptr);
		}

·E {rsx::thread} RSX: Deleted image 0x4e2b9
·E {rsx::thread} RSX: ERROR: [DS] Code 7 : Cannot submit cmd buffer using deleted image 0x4e2b9.

**Comment by kd-11** [comment] 2016-08-08 14:14
@raven02 Are other images deleted before this one or is it possible to obtain a call stack by breaking with the debugger? It may be a simple case of bad code ordering (hopefully). If not, I can write a special build that tracks images with refs or at least tags them with descriptive strings.

**Comment by kd-11** [comment] 2016-08-08 14:15
By the way, any other games that exhibit this behaviour? If I own a copy, I can test rather quickly.

**Comment by raven02** [comment] 2016-08-08 14:16
I tried something stupid that comment out the vkDestroyImage . The crash gone .

**Comment by raven02** [comment] 2016-08-08 14:18
Another game exhit this crash is Dai-3-Ji Super Robot Taisen Z Jigoku-hen .This is the save 

[NPJB00520-STG-000.zip](https://github.com/RPCS3/rpcs3/files/406980/NPJB00520-STG-000.zip)

**Comment by kd-11** [comment] 2016-08-08 14:19
@raven02 Thanks.

**Comment by raven02** [comment] 2016-08-08 14:21
Fight the red one using green one and will trigger a scene then it will crash .

![untitled](https://cloud.githubusercontent.com/assets/3000282/17482919/69956ab8-5db6-11e6-91c4-3605c7c49c3d.png)

**Comment by raven02** [comment] 2016-08-08 14:23
Crash at this one

![untitled](https://cloud.githubusercontent.com/assets/3000282/17482981/bab7bef0-5db6-11e6-9824-2a462f75e2c3.jpg)

**Comment by raven02** [comment] 2016-08-08 14:26
And can always reproduce

**Comment by raven02** [comment] 2016-08-08 14:32
I tried something stupid that comment out the vkDestroyImage . The crash gone for both 1942 Strike and  Dai-3-Ji Super Robot Taisen Z Jigoku-hen

//vkDestroyImage((*owner), m_image_contents, nullptr);
//vkDestroyImage(m_device, value, nullptr);

**Comment by kd-11** [comment] 2016-08-08 14:37
Well, that'll crash your GPU in minutes with some games. GL and vulkan don't properly reuse their invalidated/old texture resources and discard immediately at the end of every frame. New surfaces are generated for each frame (If the game does not manage surfaces conservatively). I'll rewrite some parts of both renderers once rsx refactoring is finished.

**Comment by raven02** [comment] 2016-08-08 14:38
Cool . It is good we can confirm the deleted image trigger the crash.

**Comment by kd-11** [comment] 2016-08-08 20:48
I found the cause of this error. I'll upload a fix for this as well as the rtt recycling code soon.

**Comment by kd-11** [comment] 2016-08-08 21:16
https://github.com/RPCS3/rpcs3/pull/2045 should solve the texture-related issues.

**Comment by raven02** [comment] 2016-08-09 00:48
Thanks @kd-11 .

**Closed by raven02** 2016-08-09 00:48 UTC
Labels: dx12
