### ISSUE TITLE
Regression: Resolution Scale Threshold broken in some titles after #7271

### ISSUE THREAD

**Issue by Asinin3** [RPCS3/rpcs3#8931] opened 2020-09-19 04:37 UTC
Before https://github.com/RPCS3/rpcs3/pull/7271 merged, Modnation Racers and LittleBigPlanet Karting worked with resolution scaling IF you set resolution scale threshold to 1024x1024. If you try and do that now however, the aspect ratio is completely squished vertically. The same issue also affects MotorStorm: Apocalypse when using 1024x1024 threshold, however the game doesn't need it (potentially due to mlaa patch?).

Builds before/after with res scaling, but without 1024x1024 threshold rendered green graphics as seen below (same in LBP Karting):
![image](https://user-images.githubusercontent.com/15137035/93658887-c66bd380-fa7e-11ea-90e5-acd96a8cc650.png)

Before https://github.com/RPCS3/rpcs3/pull/7271 with res scaling AND 1024x1024 threshold (same in LBP Karting):
![9400_SMZZHVqlaE](https://user-images.githubusercontent.com/15137035/93658900-ec917380-fa7e-11ea-9e1b-9734ee55db5c.jpg)

After https://github.com/RPCS3/rpcs3/pull/7271 with res scaling and 1024x1024 threshold (same in LBP Karting):
![image](https://user-images.githubusercontent.com/15137035/93659042-4cd4e500-fa80-11ea-8fc8-2deea371d3ea.png)
[RPCS3.log.gz](https://github.com/RPCS3/rpcs3/files/5249099/RPCS3.log.gz)

Before log:
[RPCS3.log.gz](https://github.com/RPCS3/rpcs3/files/5249077/RPCS3.log.gz)

After Log:
[RPCS3.log.gz](https://github.com/RPCS3/rpcs3/files/5249106/RPCS3.log.gz)

Renderdoc at title screen (3mb) 
[modnation.rdc.gz](https://github.com/RPCS3/rpcs3/files/5249098/modnation.rdc.gz)

**Comment by kd-11** [comment] 2020-09-19 08:41
This is actually a good thing as we can see upscaling was not really working correctly earlier. I know what the problem is, will push a fix.

**Comment by kd-11** [comment] 2020-11-16 17:58
Should be fixed by https://github.com/RPCS3/rpcs3/pull/9281

**Closed** 2020-11-18 06:29 UTC
Labels: Bug, RSX
