### ISSUE TITLE
GoldenEye 007 Reloaded -  Light Bug -  ZCull Occlusion Queris bug 

### ISSUE THREAD

**Issue by Pointer1992** [RPCS3/rpcs3#9693] opened 2021-01-31 06:16 UTC
Hi 
GoldenEye 007 Reloaded Light bug 
more info by video 

ZCull Occlusion Queris - On 
https://youtu.be/9rcJpg2H-6M 

ZCull Occlusion Queris - Off
https://www.youtube.com/watch?v=2fP7w4ydLbU&feature=youtu.be

AMD Ryzen 2600
16gb ram 
Radeon RX 570 4gb 

rpcs3-v0.0.14-11644-bb2cc196_win64 - test

**Comment by kd-11** [comment] 2021-01-31 13:35
Duplicate of https://github.com/RPCS3/rpcs3/issues/8966. The cause is known, will be added in the next maintenance cycle.

**Closed** 2021-01-31 13:35 UTC
Labels: Meta: Duplicate

**Comment by Mew8000** [comment] 2021-06-03 15:28
Yoshi
