### ISSUE TITLE
Initial D Extreme Stage (While Compiling Shaders) 

### ISSUE THREAD

**Issue by Carlosss18** [RPCS3/rpcs3#6273] opened 2019-07-27 16:21 UTC
Initial D Extreme Stage (While Compiling Shaders)
E {RSX Decompiler Thread} RSX: Failed to compile shader: ERROR: 0:121: 'tex00' : undeclared identifier 
ERROR: 0:121: 'texture' : no matching overloaded function found (using implicit conversion) 
ERROR: 0:121: 'process_texel' : no matching overloaded function found (using implicit conversion) 
ERROR: 0:121: 'assign' :  cannot convert from 'const highp float' to 'inout 4-component vector of highp float'

**Comment by AniLeo** [comment] 2019-07-27 16:27
Missing every required information, no specs, no log file, but this is a known issue on Intel GPUs which we don't support

Closing as duplicate of #6199

**Closed by AniLeo** 2019-07-27 16:27 UTC

**Comment by d-apps** [comment] 2019-10-03 14:23
@Carlosss18 Read my comment on [Megathread](https://github.com/RPCS3/rpcs3/issues/6199)
