### ISSUE TITLE
N2gl4glsl14link_exceptionE thrown: linkage failed: 'error: fragment shader input `tc0' has no matching output in the previous stage

### ISSUE THREAD

**Issue by giovannilaura** [RPCS3/rpcs3#2735] opened 2017-04-27 07:34 UTC
Bayonetta fails on mesa git with this error under radeonsi and AMD RX480
The log File is too big to attach

**Comment by giovannilaura** [comment] 2017-04-27 07:35
BTW under LINUX

**Comment by kirbyfan64** [comment] 2017-04-27 14:13
> The log File is too big to attach

Why not upload to Pastebin or Gists or Termbin or Ghostbin or...?

**Comment by AniLeo** [comment] 2017-04-27 14:15
Compress it with 7zip using LZMA2 Ultra

**Comment by Behem0th** [comment] 2017-04-29 05:37
Hello! I have same error.
Linux x86-64
mesa-git, radeonsi, Radeon 7950
Game: Demon's Souls.
Menu normal. When start new game or load saved game, during loadscreen in left bottom corner animations loading stops and in log i see that error.
https://pastebin.com/Br7HkfGL

**Comment by Behem0th** [comment] 2017-04-29 05:55
I switch log to trace
Last ~400 line
https://pastebin.com/C8sftrja

**Comment by hcorion** [comment] 2017-04-30 06:00
Hi all, Mesa version? Which distro and version? Are you compiling this yourself or using a pre-compiled version?

**Comment by hcorion** [comment] 2017-04-30 06:06
Ok, I see your running mesa git, try updating to the latest git again, do other OpenGL games or emulators (like Dolphin) run fine?

**Comment by Behem0th** [comment] 2017-04-30 06:36
@hcorion 
Version rpcs3 compiled myself. https://aur.archlinux.org/cgit/aur.git/tree/PKGBUILD?h=rpcs3-git
>do other OpenGL
All normal. I test in rpcs3 two game. Catherin - play normal and Demon's Soul- this error.

I use LLVM 5.0.0svn.

**Comment by hcorion** [comment] 2017-05-01 01:53
I'm assuming this is a bug in mesa and not RPCS3, but some further tests should be done in with the same hardware in Windows and different hardware/drivers on linux.

**Comment by giovannilaura** [comment] 2017-05-01 05:07
NOTE i found the same type of error in wine under no mans sky game

**Comment by hcorion** [comment] 2017-05-01 05:16
@giovannilaura Well No Man's Sky is supposed to work perfectly on Wine, I'm 98% sure this is an issue with mesa and not one with RPCS3.

For those wondering the patch file contains at line 350: 
```c++
                        if (name == "tc9") name = "tc0"; //JoeFix Bayonetta
                        LOG_ERROR(RSX, "VERTEXPROGRAM: %s", name); //JoeFix inverstigate BAYONETTA
```

**Comment by hcorion** [comment] 2017-05-01 05:18
Could you try stable mesa and see if it works there?

**Comment by Behem0th** [comment] 2017-05-01 05:20
>No Man's Sky is supposed to work perfectly on Wine

On Nvidia blob. No Man's Sky use OpenGL compatible profile. Mesa OpenGL CP maximum 3.0. No Man's Sky dont work on mesa in wine.

**Comment by hcorion** [comment] 2017-05-01 05:21
Well RPCS3 doesn't work without minimum OpenGL 4.3

**Comment by Behem0th** [comment] 2017-05-01 05:24
>minimum OpenGL 4.3

Compatibility or Core profile?

**Comment by hcorion** [comment] 2017-05-01 05:25
I'm not sure, but the problem seems to be that Demon Souls and Bayonetta seem to using advanced OpenGL 4.3 features that your version of mesa doesn't yet support. Perhaps @kd-11 could shed some light?

**Comment by Behem0th** [comment] 2017-05-01 05:34
Current mesa:
    Max core profile version: 4.5
    Max compat profile version: 3.0
And no plans too support compat profile more than 3.0.
I think you right and problem in compat profile 3.0. That mean we mast wait support Vulcan in RPCS3 on linux or rewrite RPCS to use OpenGL core profile.
Any way wait what @kd-11 says.

**Comment by giovannilaura** [comment] 2017-05-01 06:14
sorry i was tryiing to help

**Comment by kd-11** [comment] 2017-05-01 11:05
RPCS3 needs some 4.3 extensions; only core profile methods are used, but core profile code is compatible with ARB_compatibility, so thats not an issue. However, mesa only supports core profile for any features past 3.3. On windows, we do get a core profile due to the bundled wx code, but on linux system provided wx libs are used. If compiled agains wx 3.1, you get core profile. Unfortunately linux distros are stuck with wx 3.0 which does not support core profile flags. As for this particular bug, I'll need more tests since the log does not show the  mismatched shader code. I'll try running demon's souls in linux+radeonsi and see what happens.

**Comment by Behem0th** [comment] 2017-05-01 11:40
As i can understand you (rpcs3 team) want use Qt instead wx. When this happens is this bug gone?

**Comment by kd-11** [comment] 2017-05-01 11:44
Hopefully, but I'll still try looking into why theres a mismatch with the current setup and why visual studio binaries dont hit the same bug.

**Comment by giovannilaura** [comment] 2017-05-01 11:59
LOG for bayonetta with dumped shader

**Comment by giovannilaura** [comment] 2017-05-01 12:04
lof for rayman 3 hd with dumped shader
[bayonetta.txt](https://github.com/RPCS3/rpcs3/files/967808/bayonetta.txt)
[rayman3.txt](https://github.com/RPCS3/rpcs3/files/967809/rayman3.txt)

**Comment by giovannilaura** [comment] 2017-05-01 12:06
hope i can help

**Comment by giovannilaura** [comment] 2017-05-01 15:35
I am on Fedora 25 and i have xwWidget 3.1 i tried to force a core profile of 4.3 in GLGSFRame.cpp but the error remains the same

**Comment by kd-11** [comment] 2017-05-12 16:40
Fixed via https://github.com/RPCS3/rpcs3/pull/2773

**Closed** 2017-05-12 17:14 UTC

**Comment by Behem0th** [comment] 2017-05-12 17:56
Confirmed, bug fixed for me in git master.

@kd-11 quick question, now when i in game select "load profile" game lock and in console i see error:
F {rsx::thread} N2gl4glsl14link_exceptionE thrown: linkage failed: 'error: fragment shader input `diff_color' has no matching output in the previous stage
Should i create new issue?

**Comment by kd-11** [comment] 2017-05-12 20:47
No need; I'll add diff_color to the list of shader outputs to force. In fact, it seems we can just always write any 'declared' channels as output to silence mesa. However, load profile will lock up the emulator very often in demon's souls due to other issues anyway.

**Comment by giovannilaura** [comment] 2017-05-12 21:46
it does not work for Rayman HD but it does work for super rub a dub
[RPCS3log.txt](https://github.com/RPCS3/rpcs3/files/998008/RPCS3log.txt)

**Comment by mrcmunir** [comment] 2017-06-16 14:20
Other game affected for this error after the menu press start "push X"

**Beyond GOOD & Evil HD NPUB30394**

>F {rsx::thread} : N2gl4glsl14link_exceptionE thrown: linkage failed: 'error: fragment shader input `diff_color' has no matching output in the previous stage
error: fragment shader input `tc0' has no matching output in the previous stage

**Comment by lvonasek** [comment] 2017-08-14 13:29
I fixed it but I am afraid that my pull request won't pass. For some reason there are modifications in submodules I did not touch. WHY???
