### ISSUE TITLE
[Regression] Gran Turismo 5 (Crash at Startup)

### ISSUE THREAD

**Issue by istalo** [RPCS3/rpcs3#13974] opened 2023-06-07 10:49 UTC
### Quick summary

Game doesn't boot up anymore, throws two E PPU errors on startup, started with build 15141, still persistent on 15143.

### Details

![image](https://github.com/RPCS3/rpcs3/assets/85691665/af5d27b6-0bc4-4245-b6ec-270954f563fd)

### Build with regression

v0.0.28-15141-6d918b56

### Attach two log files

Log made on 15143, tested both 15141 and 15143 as stated previously, stated on the regression the version where it first occurred.

15143 Log: [RPCS3.log](https://github.com/RPCS3/rpcs3/files/11676072/RPCS3.log)

15139 Log: [RPCS3.log](https://github.com/RPCS3/rpcs3/files/11676098/RPCS3.log)

### System configuration

Intel Core i7 10700KF @3.8GHz
PNY GeForce RTX 3070
Corsair Vengeance 4x8GB RAM running XMP I at 3600MHz
Windows 11 Pro (Insider Channel Build 23471.1000)

### Other details

I am a bit illiterate when it comes to programming but I'd assume the issue is related to **"0.0.28-15141: PPU: Sleep after returning from thread entry function"** which was introduced with 15141.

**Comment by elad335** [comment] 2023-06-07 10:57
Ah, I see you have HLEd liblv2.sprx
So it is a regression about the HLE of it then.

**Comment by istalo** [comment] 2023-06-07 11:07
> Ah, I see you have HLEd liblv2.sprx So it is a regression about the HLE of it then.

Glad to help by reporting the issue in any case, I'd assume it's not related tied directly to the game per se but rather what you mentioned given that then?

I'm not sure myself if ticking that even helps out with the stability given that I've had it set up like that on the previous builds within the custom configuration for the game (mostly 0.0.27) for added stability within the game, however I haven't tested it out without it ever since 0.0.28 rolled out.

**Comment by elad335** [comment] 2023-06-07 14:04
It's fixed in #13975 and that thing was and is not true. Due to the desyncs many people claimed to found different setting combinations to reduce the probability of desyncs but that is not relevant anymore.

**Comment by Satan86** [comment] 2023-06-07 14:05
> Same here for NFS Carbon. According to the wiki we have to HLE liblv2.

No. The wiki states you must LLE libvdec.sprx.

**Comment by ArbestRiAgain** [comment] 2023-06-08 20:40
Doesn't happen with the US version.

**Closed** 2023-06-09 11:07 UTC
Labels: Regression
