### ISSUE TITLE
Batman: Arkham Origins stucks on verifying trophies and doesn't go further

### ISSUE THREAD

**Issue by TotalCaesar659** [RPCS3/rpcs3#3949] opened 2017-12-19 16:38 UTC
[Batman_Arkham_Origins.zip](https://github.com/RPCS3/rpcs3/files/1572415/Batman_Arkham_Origins.zip)
![1](https://user-images.githubusercontent.com/14265316/34167835-f2b17b96-e4f3-11e7-8234-f50a6be1debf.png)

**Comment by AniLeo** [comment] 2018-07-06 18:03
This title has been Ingame for some time now and there were already several Trophy fixes since the date of this report, therefore I'm closing this issue since I'm pretty sure it's not an issue anymore.

If you're able to reproduce this on master build, ping for reopening.

**Closed by AniLeo** 2018-07-06 18:03 UTC
