### ISSUE TITLE
F.E.A.R. First Encounter Assault Recon [BLUS30003] - Flashlight no longer works as of Build 13531

### ISSUE THREAD

**Issue by TheBlueSwordsman** [RPCS3/rpcs3#11959] opened 2022-05-07 01:59 UTC
## Quick summary
On F.E.A.R First Encounter Assault Recon, the flashlight no longer turns on.

#### 0. Make sure you're running with settings as close to default as possible
Settings are mostly default except the following:

-Framelimit: Off
-Anisotropic Filter: 16x
-Anti-Aliasing: Auto
-Resolution Scale: 200% (2560x1440)
-Vsync: On
-VBlank Frequency: 120 Hz

#### 1. Please provide _exact_ build (or commit) information that introduced the regression you're reporting.
I discovered this glitch on build 13564. The regression occured on build 13531. The flashlight last worked on build 13528.

#### 2. Please attach a log:
[RPCS3.log](https://github.com/RPCS3/rpcs3/files/8644247/RPCS3.log)

#### 4. Please attach screenshots of your problem.
![Screenshot (1011)](https://user-images.githubusercontent.com/102117359/167233376-df6aba49-c8ca-4f18-8faf-d968014c8eec.png)

#### 6. Please provide your system configuration:
OS Windows 10 Home
CPU Intel Core i7-10700k
GPU Nvidia GeForce RTX 3060
Driver version 512.15
16 GB DDR4-3200 RAM

**Comment by Asinin3** [comment] 2022-05-07 02:16
Experiment with settings. Write color buffers on GPU tab, if that doesn't work try all the other buffer settings on advanced tab as well. If that doesn't work try all those settings with force cpu blit on debug settings (found in games custom config file in debug, right-click the game and create custom config then right-click and open custom config folder and open that file). if that doesn't work try turning all those off and using openGL.

**Comment by TheBlueSwordsman** [comment] 2022-05-07 02:52
Tried with Write Color Buffers, it didn’t work.

Tried with Read Depth Buffers + Write Depth Buffers + Read Color Buffers, it also didn’t work.

Tried with all Buffers & Force CPU Blit Emulation enabled, that didn’t work.

Tried with OpenGL, that didn’t work either.

**Comment by Asinin3** [comment] 2022-05-07 03:12
Cool thanks for testing. You said that the flashlight "no longer works" so now we just need to know when it broke. Can you go through old builds on https://rpcs3.net/compatibility?b and replace rpcs3.exe with a build from 3 months ago and see if it works. If it's still broken go back further, if its working go to a newer build. Basically just jump through many builds at a time to narrow it down then tell us what build broke it.

**Comment by TheBlueSwordsman** [comment] 2022-05-07 03:48
Okay, so the flashlight last worked on build 13528 and it stopped working on build 13531.

**Comment by illusion0001** [comment] 2022-05-07 03:53
#11867 I believe

**Comment by Asinin3** [comment] 2022-05-07 05:14
Confirmed
![13528_hQ6qthzcYn](https://user-images.githubusercontent.com/15137035/167239504-973d2da2-156a-4b33-9c7b-da0189a3f36f.jpg)
![13531_nvidia_accuracy_fix_cYaGF7GLV2](https://user-images.githubusercontent.com/15137035/167239532-2d7ec45a-979b-41e4-b2b5-ea0ce7c7a576.jpg)

**Comment by kd-11** [comment] 2022-05-07 10:39
RSX capture was not provided. I cannot investigate without it.

**Comment by Asinin3** [comment] 2022-05-07 10:53
Sorry thought OP included it, here are the RSX captures before/after
[captures.zip](https://github.com/RPCS3/rpcs3/files/8644957/captures.zip)

**Comment by Asinin3** [comment] 2022-05-07 12:13
Confirmed fixed with Float16 Support turned off (setting ticked on advanced tab)
![rpcs3_5Vb9Nem4aK](https://user-images.githubusercontent.com/15137035/167253889-4f3ce32a-f564-47b2-9081-c13b9cce2f88.jpg)
kd-11 to investigate

**Comment by kd-11** [comment] 2022-05-07 15:40
This is a hardware-dependent bug and unfortunately I do not have the required hardware to reproduce this. I'll look into other options.

**Comment by kd-11** [comment] 2022-05-08 10:20
Interestingly the player model even renders correctly on AMD without the weird transparent look.

**Comment by Asinin3** [comment] 2022-05-21 11:49
>anything we can do to fix it?

Did you not read the thread? change the float16 setting on advanced tab and it will fix it for Nvidia users.

**Comment by Animeman1000** [comment] 2022-05-21 13:24
> > anything we can do to fix it?
> 
> Did you not read the thread? change the float16 setting on advanced tab and it will fix it for Nvidia users.

OK Mr. Asshole. Clearly I missed that. lmao
You could've just pointed it out. But thanks.
Get that stick out your butt. lmao

**Comment by kd-11** [comment] 2022-10-10 18:02
Should be covered by https://github.com/RPCS3/rpcs3/pull/12788
Just use "High" shader precision (the default) and the native fp16 should  be disabled. Turns out the tolerances there are very tight and most desktop GPUs can handle the emulation just fine.

**Comment by TheBlueSwordsman** [comment] 2022-10-10 18:16
> Just use "High" shader precision (the default) and the native fp16 should be disabled.

Do you know where that is in the configuration settings tab?

**Comment by Megamouse** [comment] 2022-10-10 18:21
Seems to be working fine on default settings on both backends with that build:
![image](https://user-images.githubusercontent.com/23019877/194929807-b41dc365-b9ec-4bb1-91db-676a37d0dce7.png)

**Comment by Megamouse** [comment] 2022-10-10 18:22
@Asinin3 can you confirm no regression with your system?

**Closed** 2022-10-11 11:00 UTC
Labels: Regression, Driver: NVIDIA
