### ISSUE TITLE
BLES01780 - Tomb Raider: a lot of slowdowns and a lot of graphical issues during the opening

### ISSUE THREAD

**Issue by legolas119** [RPCS3/rpcs3#8801] opened 2020-08-29 23:03 UTC
## Quick summary
During the opening, the fps drops to 8/12 fps. The screen is black, it is not possible to see the menu. The game runs only at 15/18fps
## Details

Please describe the problem as accurately as possible.

#### 1. Please attach RPCS3's log.
see log attached

#### 2. If you describe graphical issue, please provide an RSX capture and a RenderDoc capture that demonstrate it.
as soon as the game starts, during the opening, it is not possible to see the menu. The screen is dark, the fpc count really low (between 8 and 14 fps). If I start the game, it runs only at about 15fps

#### 3. Please attach screenshots of your problem.
see the dark screen during the opening and when it should be possible to see the menu. It is only possible to see some water drops
![Immagine](https://user-images.githubusercontent.com/48774386/91647584-a5562b00-ea5c-11ea-83bd-75b326e85876.png)

#### 5. Please provide your system configuration:
CPU: AMD Ryzen 3700X
Motherboard: Gigabyte X570 I AORUS PRO WIFI
RAM: 2 x 8 GB Kingston HyperX Predator 3200-16
GPU: RTX 2060 Super
[RPCS3.log.gz](https://github.com/RPCS3/rpcs3/files/5146094/RPCS3.log.gz)

#### Please include.
* Anything else you deem to be important

**Comment by legolas119** [comment] 2020-09-02 20:33
Does anyone can help me please?

**Comment by Spikestuff** [comment] 2020-10-09 12:58
Duplicate of #5138 where this was mentioned back then.
To keep it short: It hasn't been fixed or hacked out when it was logged 2 years ago.

**Closed** 2020-10-18 16:18 UTC
