### ISSUE TITLE
My First Feature Request and Recommendation

### ISSUE THREAD

**Issue by NickDeBeenSAE** [RPCS3/rpcs3#14540] opened 2023-08-23 12:06 UTC
### Quick summary

Readable bootable media in it's games directory, such as PS1, 2 or 3 .iso's.

### Details

This allows RPCS3 to load and boot .iso files as opposed to the user having to 1. Install the game into the emulator as a .pkg first, or 2. Mount the .iso first before playing the game directly.

I think this would be very helpful, and would only affect the XMB of the emulator as a disk image icon would pop up before being replaced by the games .png image 😁.

The importance of this feature, as its more of a U.I. thing would be of low importance, and would probably be adopted later down the track 🙂.

Heres a log:

[RPCS3.log](https://github.com/RPCS3/rpcs3/files/12418965/RPCS3.log)

**Comment by AniLeo** [comment] 2023-08-23 12:07
Duplicate of #4021

**Closed** 2023-08-23 12:07 UTC
