### ISSUE TITLE
Provide AppImage for Linux

### ISSUE THREAD

**Issue by probonopd** [RPCS3/rpcs3#2744] opened 2017-05-01 13:54 UTC
Providing an [AppImage](http://appimage.org/) would have, among others, these advantages:
- Works for most Linux distributions (including Ubuntu, Fedora, openSUSE, CentOS, elementaryOS, Linux Mint, and others)
- One app = one file = super simple for users: just download one AppImage file, [make it executable](http://discourse.appimage.org/t/how-to-make-an-appimage-executable/80), and run
- No unpacking or installation necessary
- No root needed
- No system libraries changed
- Works out of the box, no installation of runtimes needed
- Optional desktop integration with `appimaged`
- Optional binary delta updates, e.g., for continuous builds (only download the binary diff) using AppImageUpdate
- Can optionally GPG2-sign your AppImages (inside the file)
- Works on Live ISOs
- Can use the same AppImages when dual-booting multiple distributions

[Here is an overview](https://github.com/probonopd/AppImageKit/wiki/AppImages) of projects that are already distributing upstream-provided, official AppImages.

References:
- https://github.com/RPCS3/rpcs3/issues/1561
- https://github.com/RPCS3/rpcs3/issues/2516
- https://github.com/RPCS3/rpcs3/issues/1964

__I am happy to help the team to turn the continuous builds on Travis CI into AppImages.__
See these examples:
https://github.com/cpvrlab/ImagePlay/pull/93/files
and
https://github.com/mavlink/qgroundcontrol/pull/3136/files

**Comment by probonopd** [comment] 2017-05-01 13:55
See these examples:
https://github.com/cpvrlab/ImagePlay/pull/93/files
and
https://github.com/mavlink/qgroundcontrol/pull/3136/files

**Comment by flash-fire** [comment] 2017-05-01 14:07
Before considering appimages, just note that we're currently [converting](https://github.com/RPCS3/rpcs3/pull/2645) to Qt.  So, work should begin on that build to save duplication of effort.

(Also, Linux is completely broken right now on my Qt branch. Sorry about that.  I want to fix it but my knowledge of cmake/travis/appveyor aren't good enough)

**Comment by kirbyfan64** [comment] 2017-05-01 14:12
FWIW there's actually a tool specifically for making AppImages out of Qt applications:

https://github.com/probonopd/linuxdeployqt

**Comment by al0xf** [comment] 2017-05-01 14:12
While Qt is nice it is not a deal breaker or anything, RPCS3 can work just fine on Linux already. The real problem is #2516. Fix that and you have finally and definitely fixed RPCS3 on Linux.

**Comment by flash-fire** [comment] 2017-05-01 14:17
Right. Qt isn't a deal breaker.  But, I haven't fixed the build yet to link against Qt. That's what I meant by completely broken. I just wanted to note that before someone considered trying to do things with that build. :)

**Comment by probonopd** [comment] 2017-05-01 14:34
Qt is not an issue for me, in fact I have made may AppImages from Qt-based and other apps and games. Right now I am failing to install to `appdir/usr/bin/` using

```
 cmake .. -DCMAKE_INSTALL_PREFIX=/usr
make -j 3
make DESTDIR=appdir install ; find appdir/
```

How would I do this?

**Comment by hcorion** [comment] 2017-05-01 18:34
@probonopd I'm 90% sure RPCS3 doesn't have an install section for make, you just need to copy the rpcs3 binary in the bin folder over to the appdir folder

**Comment by probonopd** [comment] 2017-05-01 18:46
@hcorion could you add such a section, that would also handle the icons, desktop files and such?

**Comment by probonopd** [comment] 2017-05-01 18:46
Btw, which branch should I focus on for the continuous AppImages?

**Comment by hcorion** [comment] 2017-05-01 18:58
The master branch, I am but a padawan when it comes to cmake programming. I would be happy to look into it though

**Comment by probonopd** [comment] 2017-05-03 19:55
Thanks for looking into adding a section to install the icons, desktop files, and such. Ping me once done, so that I can continue on making the AppImage. Thanks.

**Comment by hcorion** [comment] 2017-05-22 17:59
@probonopd Ok RPCS3 CMake/make now has an installation step (just `make install`), .desktop, icon etc.

**Comment by probonopd** [comment] 2017-05-22 21:52
Thanks @hcorion, now I am getting

```
Submodule path '3rdparty/pugixml': checked out 'f205aaf6e1c90f1dda943edd4f82922118a85648'
error: no such remote ref bc716868350f2d5a4fa2836ebf96bf83fc02a9be
Fetched in submodule path 'Utilities/yaml-cpp', but it did not contain bc716868350f2d5a4fa2836ebf96bf83fc02a9be. Direct fetching of that commit failed.
```

Do you know what might cause this? 

Here is my `.travis.yml` file:
https://github.com/probonopd/rpcs3/blob/patch-1/.travis.yml

And here is my build log:
https://travis-ci.org/probonopd/rpcs3/jobs/234994694#L667-L669

**Comment by AniLeo** [comment] 2017-05-22 21:54
Did you update submodules? It was updated recently

**Comment by probonopd** [comment] 2017-05-22 23:07
Thanks @AniLeo have it building now. 

Here is my `.travis.yml`:
https://github.com/probonopd/rpcs3/blob/master/.travis.yml

And here is the resulting AppImage (the URL can be found in the Travis CI build log):
https://transfer.sh/L2ZEf/RPCS3-git.df69e97-x86_64.AppImage

Unfortunately the font rendering is a bit messed up, but this can easily be fixed by removing the bundled libpango* libraries (further investigation needed) like this:

```
./RPCS3-git.df69e97-x86_64.AppImage --appimage-extract
cd squashfs-root
rm -rf usr/lib/libpango*
./AppRun # Runs 
```

**Comment by AniLeo** [comment] 2017-05-23 16:13
@probonopd can you please submit the changes as a pull request? If travis is building the AppImage, please make it upload via curl like it's currently doing with the broken artifacts it builds.

On https://github.com/probonopd/rpcs3/blob/master/.travis.yml#L97 there's a curl command that uploads rpcs3.zip. Just compress the AppImage file to inside the zip file if possible. After merged it will upload the builds to our server so we can then make them available for download.

**Comment by AniLeo** [comment] 2017-05-28 12:00
We are soon to merge #2645 that changes RPCS3 from using wxWidgets to QT since it's mostly ready.
Will the libpango issue no longer be an issue?

**Comment by probonopd** [comment] 2017-05-28 12:15
Correct @AniLeo

**Comment by al0xf** [comment] 2017-05-28 12:28
@probonopd Have you been able to replicate #2516? That is the only real issue blocking Linux builds.

**Comment by probonopd** [comment] 2017-05-29 06:11
"St11range_error thrown" seems to be an error related to running RPCS3 on Nvidia GPUs as https://www.reddit.com/r/linux_gaming/comments/68f9ll/rpcs3_april_2017_progress_report_rpcs3_works_on/dgydzdm/ would suggest. I don't think it is AppImage related. Do you think it is @al0xf?

**Comment by hcorion** [comment] 2017-05-29 06:12
@probonopd Nope, the issue has occurred on both Nvidia and AMD hardware. I'm on NVIDIA (GTX 1070) and have no problems.

**Comment by probonopd** [comment] 2017-05-29 06:13
Is there any indication that this may be caused by the AppImage rather than than the RPCS3/GPU driver combination itself?

**Comment by hcorion** [comment] 2017-05-29 06:15
The issue has occurred and still persists before and with the AppImage, so I can't see why it would be the issue. At this point I'm not sure if it has anything to do with the GPU or not.

**Comment by al0xf** [comment] 2017-05-29 11:35
The issue has nothing to do with the Appimage, the reason I'm asking is that kd-11 was investigating but couldn't reproduce: "We need to gather a list of conditions needed to recreate this bug, so I can recreate it in a VM."

**Comment by AniLeo** [comment] 2017-06-04 15:01
@probonopd we merged QT, this should be good to go now if you can provide a working AppImage

**Comment by probonopd** [comment] 2017-06-04 16:42
Thanks @AniLeo. I have generated one at https://transfer.sh/Hpd1H/RPCS3-git.9c5f3e9-x86_64.AppImage. It starts to launch but then crashes with

```
Fatal error: 
Segfault reading location 00000000502d0410 at 00007f425bbd3e8f.
HOW TO REPORT ERRORS: Check the FAQ, README, other sources.
Please, don't send incorrect reports. Thanks for understanding.
Aborted (core dumped)
```

This is on openSUSE Leap 42.2.

The `.travis.yml` is here:
https://github.com/probonopd/rpcs3/blob/patch-1/.travis.yml

**Comment by TotalCaesar659** [comment] 2017-06-05 01:33
@probonopd I've got the same result on Lubuntu 16.04.2 x64:
```
xxx@xxx:~$ /home/xxx/Downloads/RPCS3-git.9c5f3e9-x86_64.AppImage
libpng warning: Application built with libpng-1.2.50 but running with 1.6.21
libpng warning: Application built with libpng-1.2.50 but running with 1.6.21
libpng warning: Application built with libpng-1.2.50 but running with 1.6.21
libpng warning: Application built with libpng-1.2.50 but running with 1.6.21
pci id for fd 14: ffff:ffff, driver (null)
Fatal error: 
Segfault reading location 00007f7ee803a000 at 00007f7efaa06cd5.
HOW TO REPORT ERRORS: Check the FAQ, README, other sources.
Please, don't send incorrect reports. Thanks for understanding.
Aborted (core dumped)
```
P.S. Could you make the icon for appimage, like on another programs?
![1](https://cloud.githubusercontent.com/assets/14265316/26767365/105c2a48-49a8-11e7-81c7-3720ed2625bb.png)

**Comment by hcorion** [comment] 2017-06-05 05:55
@probonopd 
I'm the guy that made the CMake + Travis build for Qt work, but I've got no experience with AppImages.

Based on various screenshots I've seen, it appears like the rpcs3 binary is trying to use the system installed qt libs, which AFAIK are to old to be compatible with the ones used for the Travis build.

The Travis RPCS3 build links against this Qt 5.9 PPA: https://launchpad.net/~beineri/+archive/ubuntu/opt-qt59-trusty

which installs to `/opt`, and I think this may be screwing up your script.
At one point, your script does output the following:
`ERROR: Qt translations path could not be determined`

**Comment by probonopd** [comment] 2017-06-05 09:10
Where can I download an AppImage to inspect?

**Comment by AniLeo** [comment] 2017-06-05 09:26
AppImage Builds

GCC: http://rpcs3.net/cdn/builds/rpcs3-v0.0.2-2017-06-04-1c91dac-6649-gcc-5_linux64.zip
Clang: http://rpcs3.net/cdn/builds/rpcs3-v0.0.2-2017-06-04-1c91dac-6649-clang_linux64.zip

**Comment by probonopd** [comment] 2017-06-05 09:30
Thanks @AniLeo. I know that these links are for testing only and that is fine, but for releases please don't put AppImages into zip or other archives since this will [prevent](https://github.com/AppImage/AppImageKit/wiki/Creating-AppImages#common-mistake) the optional `appimaged` daemon from integrating them with the system automatically.

**Comment by AniLeo** [comment] 2017-06-05 09:32
Thanks, I'll make sure they're unzipped or even not zipped at all before they're put up for general availability

**Comment by probonopd** [comment] 2017-06-05 09:46
@hcorion linuxdeployqt patches the RPATH so that some libraries are loaded from within the AppImage:

```
/home/linux/Downloads/RPCS3-x86_64.AppImage --appimage-extract

linux@linux:~> ldd squashfs-root/usr/bin/rpcs3  | grep libQt
        libQt5Widgets.so.5 => /home/linux/squashfs-root/usr/bin/../lib/libQt5Widgets.so.5 (0x00007f01d8451000)
        libQt5Gui.so.5 => /home/linux/squashfs-root/usr/bin/../lib/libQt5Gui.so.5 (0x00007f01d7bed000)
        libQt5Core.so.5 => /home/linux/squashfs-root/usr/bin/../lib/libQt5Core.so.5 (0x00007f01d767c000)
```

It is using these libraries from the target system:

```
linux@linux:~> ldd squashfs-root/usr/bin/rpcs3  | grep -v squashfs-root
        linux-vdso.so.1 (0x00007ffde65f5000)
        libGL.so.1 => /usr/lib64/libGL.so.1 (0x00007fc2024e4000)
        libdl.so.2 => /lib64/libdl.so.2 (0x00007fc2020cc000)
        libpthread.so.0 => /lib64/libpthread.so.0 (0x00007fc201ca5000)
        libz.so.1 => /lib64/libz.so.1 (0x00007fc201a8f000)
        librt.so.1 => /lib64/librt.so.1 (0x00007fc201887000)
        libX11.so.6 => /usr/lib64/libX11.so.6 (0x00007fc201548000)
        libasound.so.2 => /usr/lib64/libasound.so.2 (0x00007fc201251000)
        libm.so.6 => /lib64/libm.so.6 (0x00007fc1fdb3d000)
        libstdc++.so.6 => /usr/lib64/libstdc++.so.6 (0x00007fc1fccdc000)
        libgcc_s.so.1 => /lib64/libgcc_s.so.1 (0x00007fc1fcac5000)
        libc.so.6 => /lib64/libc.so.6 (0x00007fc1fc721000)
        /lib64/ld-linux-x86-64.so.2 (0x000055a17de7f000)
        libexpat.so.1 => /usr/lib64/libexpat.so.1 (0x00007fc1fc4f7000)
        libxcb-dri3.so.0 => /usr/lib64/libxcb-dri3.so.0 (0x00007fc1fc2f4000)
        libxcb-present.so.0 => /usr/lib64/libxcb-present.so.0 (0x00007fc1fc0f0000)
        libxcb-sync.so.1 => /usr/lib64/libxcb-sync.so.1 (0x00007fc1fbeea000)
        libxshmfence.so.1 => /usr/lib64/libxshmfence.so.1 (0x00007fc1fbce7000)
        libglapi.so.0 => /usr/lib64/libglapi.so.0 (0x00007fc1fbab8000)
        libXext.so.6 => /usr/lib64/libXext.so.6 (0x00007fc1fb8a6000)
        libXdamage.so.1 => /usr/lib64/libXdamage.so.1 (0x00007fc1fb6a3000)
        libXfixes.so.3 => /usr/lib64/libXfixes.so.3 (0x00007fc1fb49c000)
        libX11-xcb.so.1 => /usr/lib64/libX11-xcb.so.1 (0x00007fc1fb29a000)
        libxcb-glx.so.0 => /usr/lib64/libxcb-glx.so.0 (0x00007fc1fb082000)
        libxcb-dri2.so.0 => /usr/lib64/libxcb-dri2.so.0 (0x00007fc1fae7c000)
        libxcb.so.1 => /usr/lib64/libxcb.so.1 (0x00007fc1fac5c000)
        libXxf86vm.so.1 => /usr/lib64/libXxf86vm.so.1 (0x00007fc1faa56000)
        libdrm.so.2 => /usr/lib64/libdrm.so.2 (0x00007fc1fa846000)
        libglib-2.0.so.0 => /usr/lib64/libglib-2.0.so.0 (0x00007fc1f8c35000)
        libXau.so.6 => /usr/lib64/libXau.so.6 (0x00007fc1f8a30000)
        libpcre.so.1 => /usr/lib64/libpcre.so.1 (0x00007fc1f6f52000)
```

It is using these bundled libraries from inside the AppImage:

```
linux@linux:~> ldd squashfs-root/usr/bin/rpcs3  | grep squashfs-root
        libopenal.so.1 => /home/linux/squashfs-root/usr/bin/../lib/libopenal.so.1 (0x00007fef39b06000)
        libGLEW.so.1.13 => /home/linux/squashfs-root/usr/bin/../lib/libGLEW.so.1.13 (0x00007fef3986d000)
        libGLU.so.1 => /home/linux/squashfs-root/usr/bin/../lib/libGLU.so.1 (0x00007fef395fe000)
        libudev.so.1 => /home/linux/squashfs-root/usr/bin/../lib/libudev.so.1 (0x00007fef3916b000)
        libatomic.so.1 => /home/linux/squashfs-root/usr/bin/../lib/libatomic.so.1 (0x00007fef38d5e000)
        libLLVM-4.0.so.1 => /home/linux/squashfs-root/usr/bin/../lib/libLLVM-4.0.so.1 (0x00007fef35322000)
        libQt5Widgets.so.5 => /home/linux/squashfs-root/usr/bin/../lib/libQt5Widgets.so.5 (0x00007fef34cd5000)
        libQt5Gui.so.5 => /home/linux/squashfs-root/usr/bin/../lib/libQt5Gui.so.5 (0x00007fef34471000)
        libQt5Core.so.5 => /home/linux/squashfs-root/usr/bin/../lib/libQt5Core.so.5 (0x00007fef33f00000)
        libcgmanager.so.0 => /home/linux/squashfs-root/usr/bin/../lib/libcgmanager.so.0 (0x00007fef314c5000)
        libnih.so.1 => /home/linux/squashfs-root/usr/bin/../lib/libnih.so.1 (0x00007fef312aa000)
        libnih-dbus.so.1 => /home/linux/squashfs-root/usr/bin/../lib/libnih-dbus.so.1 (0x00007fef3109f000)
        libdbus-1.so.3 => /home/linux/squashfs-root/usr/bin/../lib/libdbus-1.so.3 (0x00007fef30e57000)
        libffi.so.6 => /home/linux/squashfs-root/usr/bin/../lib/libffi.so.6 (0x00007fef30c4d000)
        libedit.so.2 => /home/linux/squashfs-root/usr/bin/../lib/libedit.so.2 (0x00007fef30a1b000)
        libtinfo.so.5 => /home/linux/squashfs-root/usr/bin/../lib/libtinfo.so.5 (0x00007fef307f0000)
        libpng12.so.0 => /home/linux/squashfs-root/usr/bin/../lib/libpng12.so.0 (0x00007fef305c8000)
        libicui18n.so.52 => /home/linux/squashfs-root/usr/bin/../lib/libicui18n.so.52 (0x00007fef30176000)
        libicuuc.so.52 => /home/linux/squashfs-root/usr/bin/../lib/libicuuc.so.52 (0x00007fef2fde0000)
        libicudata.so.52 => /home/linux/squashfs-root/usr/bin/../lib/libicudata.so.52 (0x00007fef2e05c000)
```

It looks like the crash happens when it tries to load `libLLVM*` from the target system rather than from the AppImage:

```
linux@linux:~> LD_DEBUG=libs  squashfs-root/usr/bin/rpcs3

     10375:     find library=libLLVMMCParser.so.3.8 [0]; searching
     10375:      search path=/usr/lib64/../lib64/../lib64/tls/x86_64:/usr/lib64/../lib64/../lib64/tls:/usr/lib64/../lib64/../lib64/x86_64:/usr/lib64/../lib64/../lib64          (RUNPATH from file /usr/lib64/../lib64/libLLVMAsmPrinter.so.3.8)
     10375:       trying file=/usr/lib64/../lib64/../lib64/tls/x86_64/libLLVMMCParser.so.3.8
     10375:       trying file=/usr/lib64/../lib64/../lib64/tls/libLLVMMCParser.so.3.8
     10375:       trying file=/usr/lib64/../lib64/../lib64/x86_64/libLLVMMCParser.so.3.8
     10375:       trying file=/usr/lib64/../lib64/../lib64/libLLVMMCParser.so.3.8
     10375:
     10375:     find library=libLLVMBitWriter.so.3.8 [0]; searching
     10375:      search path=/usr/lib64/../lib64/../lib64               (RUNPATH from file /usr/lib64/../lib64/libLLVMAsmPrinter.so.3.8)
     10375:       trying file=/usr/lib64/../lib64/../lib64/libLLVMBitWriter.so.3.8
     10375:
     10375:     find library=libLLVMInstrumentation.so.3.8 [0]; searching
     10375:      search path=/usr/lib64/../lib64/../lib64               (RUNPATH from file /usr/lib64/../lib64/libLLVMAsmPrinter.so.3.8)
     10375:       trying file=/usr/lib64/../lib64/../lib64/libLLVMInstrumentation.so.3.8
     10375:
     10375:     find library=libLLVMAsmParser.so.3.8 [0]; searching
     10375:      search path=/usr/lib64/../lib64/../lib64               (RUNPATH from file /usr/lib64/../lib64/libLLVMAsmPrinter.so.3.8)
     10375:       trying file=/usr/lib64/../lib64/../lib64/libLLVMAsmParser.so.3.8
     10375:
     10375:
     10375:     calling init: /usr/lib64/libLLVMSupport.so.3.8
     10375:
Fatal error: 
Segfault reading location 0000000056210410 at 00007fa19d8bae8f.
HOW TO REPORT ERRORS: Check the FAQ, README, other sources.
Please, don't send incorrect reports. Thanks for understanding.
Aborted (core dumped)
```

The question is, what causes it to load stuff like `libLLVMSupport`; nothing inside the AppImage seems to even contain that string (which is why `linuxdeployqt` did not bundle it as a dependency):

```
linux@linux:~> grep -r libLLVMSupport squashfs-root/
linux@linux:~> 
```

**Comment by kd-11** [comment] 2017-06-05 11:23
Do not bundle llvm. That package has internal problems that will cause problems down the line.

**Comment by probonopd** [comment] 2017-06-05 11:42
So how can we remove the dependency on `libLLVM-4.0.so.1`? If I just delete it from the AppImage, then the dependency is unmet and the application does not run.

**Comment by kd-11** [comment] 2017-06-05 20:29
Make libllvm load from system, not from within the image, otherwise we'll get the inconsistent linkage error again.

**Comment by probonopd** [comment] 2017-06-05 20:47
`libLLVM*` cannot reasonably be expected to be part of each target system, so we _have_ to bundle it. I guess we just need to bundle _all_ of it. Although I don't fully understand __how__ `libLLVM-4.0.so.1` loads the other `libLLVM*` stuff.

**Comment by kd-11** [comment] 2017-06-05 23:21
If you go through the llvm source you'll realize that it wont work. Give it a shot though if you are confident about it, but I'm cautiously optimistic. Like I said, the llvm runtime can only be loaded from a single lib and system components will thwart efforts to bundle it. Llvm will have to be installed by the user just like most other software.

**Comment by probonopd** [comment] 2017-06-06 00:05
Strangely enough, on an openSUSE Leap 42.2 system it tries to load `libLLVMSupport.so.3.8` from the system but this library is not even in Ubuntu for us to bundle... https://packages.ubuntu.com/search?mode=filename&suite=trusty&section=all&arch=any&keywords=libLLVMSupport.so&searchon=contents I don't understand this.

**Comment by kd-11** [comment] 2017-06-06 00:12
It is possible that a system library loads llvm 3.8 runtime. This is outside our control and is why I suggested to leave the whole thing alone. Almost any library that emits code will use some llvm runtime most notably mesa drivers. These will usually be compiled against the system's llvm (3.8 in your case). Its not a problem with the appimage, just conflicts with system libs. It is possible for the same appimage to run on another machine without issues.

**Comment by probonopd** [comment] 2017-06-06 05:53
If we don't bundle `libLLVM-4.0.so.1` then it won't run on openSUSE Leap 42.0 since that library is not there under this name. The libLLVM package contains many libraries with similar names but not this one: http://download.opensuse.org/repositories/openSUSE:/Leap:/42.2:/Update/standard/x86_64/libLLVM-3.8.0-2.3.1.x86_64.rpm

**Comment by kd-11** [comment] 2017-06-06 09:44
This means we cannot provide one appimage for all distros then. On most applications, it is possible to bundle almost every lib, down to syscall level, but when some system components are involved, this becomes impossible. The only way to package llvm requires that we modify the llvm source to "hide" our instance from the system one and link statically.

**Comment by hcorion** [comment] 2017-06-14 18:18
Ok, I may have fixed the AppImage by not using LLVM.
Please try out this AppImage:
https://rpcs3.net/cdn/builds/rpcs3-v0.0.2-2017-06-14-d6e4566-6814-gcc-5_linux64.zip

**Comment by probonopd** [comment] 2017-06-14 20:58
Thanks @hcorion, runs for me! This is on openSUSE LEAP 42.2.

**Comment by hcorion** [comment] 2017-06-14 22:08
@kd-11
Since it's really not an option to provide RPCS3 without LLVM, do you think you could modify the LLVM source to do the things you mentioned?
Unless I'm mistaken, this seems to be our only choice.

We're also in a unique situation, because using both OpenGL and LLVM is not something most (any?) binaries use, there are no examples, AFAIK, of AppImages that have worked around the situation we're currently in.

**Comment by kirbyfan64** [comment] 2017-06-14 22:10
As a random side note, wouldn't it be possible to link with LLVM static libraries, that way the whole shared library loading issue isn't even a problem anymore?

**Comment by hcorion** [comment] 2017-06-14 22:16
@kirbyfan64 I think the problem with that was RPCS3 was using LLVM and then it was trying to load mesa stuff, and so it was trying to load LLVM twice, which didn't go well.

**Comment by TotalCaesar659** [comment] 2017-06-15 00:28
@hcorion I've checked the AppImage and it's good, but:
1) there is no Vulkan. Is it bug or you've removed it with LLVM?
2) I've already wrote about the AppImage icon (https://github.com/RPCS3/rpcs3/issues/2744#issuecomment-306083044). Is it possible for implementing?
3) I've launched it on Lubuntu 16.04.2 x64 (it has libpng12-0 originally, but I've installed a program with libpng16-16 additionally, they both installed). The appimage tries to draw its images by libpng16-16, but not libpng12-0, can't do this and shows the output:

>libpng warning: Application built with libpng-1.2.50 but running with 1.6.21

![1](https://user-images.githubusercontent.com/14265316/27160111-63676ca0-517a-11e7-8131-4f51222a6e43.png)
Can it be fixed or I have to remove libpng16-16 with program at all?

**Comment by hcorion** [comment] 2017-07-22 06:07
@probonopd How might I go about deleting a lib that I want loaded from the system. ie, the libLLVM lib.
I tried in between `-bundle-non-qt-libs` and `-appimage` like this
```
      ./linuxdeployqt*.AppImage ./appdir/usr/share/applications/*.desktop -bundle-non-qt-libs ;
      sudo rm -f ./appdir/usr/lib/libLLVM* ;
      ./linuxdeployqt*.AppImage ./appdir/usr/share/applications/*.desktop -appimage ;
```
but libLLVM was still included?

**Comment by probonopd** [comment] 2017-07-22 07:35
Instead of your last line, you need to use `appimagetool` manually instead of `linuxdeployqt` (which uses `appimagetool` internally too) for the final step, converting the AppDir to an AppImage.

**Comment by hcorion** [comment] 2017-07-23 18:09
Alright, so I've got the AppImages mostly working, before we officially provide builds on the website, I'd like this bug fixed https://github.com/RPCS3/rpcs3/issues/3063 and @kirbyfan64's evdev joystick merged.

**Comment by hcorion** [comment] 2017-07-24 21:00
Hi! I possibly have fixed the llvm issue, can somebody (preferably multiple people) please try this build: https://transfer.sh/WDkF/3cb0b39-128-LLVM_linux64
I'd prefer if you're testing with AMD hardware running mesa drivers, but the more the merrier

**Comment by probonopd** [comment] 2017-07-24 22:04
Launches on openSUSE LEAP 42.2 with an AMD GPU.

**Comment by hcorion** [comment] 2017-07-24 22:05
Can it run any games @probonopd ?

**Comment by probonopd** [comment] 2017-07-24 22:41
I don't know, don't have any.

**Comment by al0xf** [comment] 2017-07-24 23:08
Try some homebrew or test program. For example this one. 
[gs_gcm_cube.zip](https://github.com/RPCS3/rpcs3/files/1171473/gs_gcm_cube.zip)

**Comment by probonopd** [comment] 2017-07-24 23:19
Getting

> F LDR: St13runtime_error thrown: Failed to load /dev_flash/sys/external/libsysmodule.sprx: Invalid stream or file not found
S LDR: (S)ELF: boot done.

**Comment by al0xf** [comment] 2017-07-24 23:29
"manually load selected libraries" (and select nothing)

This sample works fine with 100 % HLE.

**Comment by AniLeo** [comment] 2017-07-25 18:48
Starting today we're providing AppImages directly via our website.
https://rpcs3.net/download

Upon completion I'm now closing this

**Closed by AniLeo** 2017-07-25 18:48 UTC
Labels: linux
