### ISSUE TITLE
[Feature request] Ability to cache the PPU cache for the last booted game

### ISSUE THREAD

**Issue by jnackmclain** [RPCS3/rpcs3#14665] opened 2023-09-22 17:04 UTC
### Quick summary

I boot a specific title over and over and over via rpcs3, and the initial boot including analysing and linking and ppu caching can take a bit and gets slightly annoying over time, especially as i am booting the same game over and over.
Would it be possible for the emulator to persistently cache the last booted game for subsequent launches of the same title to skip a good portion of that boot up behavior? it will also help users who crash get back into the game quicker as well.
My assumption is it would be best to only cache the most recent title and wipe it upon booting a different title but im open to ideas!

**Comment by MSuih** [comment] 2023-09-22 17:34
Duplicate of https://github.com/RPCS3/rpcs3/issues/10452

**Closed by MSuih** 2023-09-22 17:34 UTC
