### ISSUE TITLE
Castlevania: Harmony of Despair [NPUB30505] - Game gets stuck on title screen after pressing Start

### ISSUE THREAD

**Issue by Rex000** [RPCS3/rpcs3#13417] opened 2023-02-20 08:19 UTC
### Quick summary

Title

### Details

Game just gets stuck on "Loading".

### Attach a log file

[RPCS3.log.gz](https://github.com/RPCS3/rpcs3/files/10781980/RPCS3.log.gz)

### Attach capture files for visual issues

![NPUB30505_screenshot_2023_02_20_12_44_08](https://user-images.githubusercontent.com/28770012/220044315-a02a760e-5d16-4964-a6d0-97e84cecbe7c.jpg)

**Comment by Rex000** [comment] 2023-02-20 21:26
It's a mere side-scroller. I can run God of War games among others fine. I don't think this particular issue has anything to do with a PC being "potato".

**Comment by Rex000** [comment] 2023-02-20 21:35
Guess what, found a similar issue #13262, and this time it's someone with a very powerful PC. Proves my point.

**Comment by RipleyTom** [comment] 2023-02-20 21:40
Duplicate of https://github.com/RPCS3/rpcs3/issues/13262

**Comment by Rex000** [comment] 2023-02-20 21:41
So it's the same issue after all?

**Closed by RipleyTom** 2023-02-20 21:40 UTC
Labels: Potato
