### ISSUE TITLE
Shouldn't it be a Drag Drop button ?

### ISSUE THREAD

**Issue by jokoputera** [RPCS3/rpcs3#11706] opened 2022-03-29 23:08 UTC
## Quick summary
xfloat button can be check both accurate AND approximate, shouldnt it be a drop down options?

## Details
as a general user POV, this two options seems contradicting

Please describe the problem as accurately as possible.
personally, i think either the description of these two function should be elaborate more in the description box, or rename the options
 
#### 1. Please attach RPCS3's log.
its a CPU Menu

#### 3. Please attach screenshots of your problem.
![image](https://user-images.githubusercontent.com/59791277/160720999-c52f37bb-f8fd-4820-8735-614b344cea62.png)

#### 5. Please provide your system configuration:
* OS Windows 10
* CPU Ryzen 5 3600
* GPU 1660
* Driver version latest
* etc.

**Comment by Megamouse** [comment] 2022-03-30 05:42
Duplicate of #11523

**Closed by Megamouse** 2022-03-30 05:42 UTC
Labels: Meta: Duplicate
