### ISSUE TITLE
DX 12 Error in Naruto Ultimate Ninja Storm

### ISSUE THREAD

**Issue by zerr10** [RPCS3/rpcs3#2230] opened 2016-11-23 17:29 UTC
DX 12 Error (bug) in Naruto Ultimate Ninja Storm

F {rsx::thread} class std::range_error thrown: bad conversion

My PC : i7 Sklake 6700 3.4Ghz , RAM 8 GB Dual 2133 Mhz , Card : RX 460 4GB OS Windows 10 1607 (14393.0)

in Future will by better in this processor ?

**Comment by SakataGintokiYT** [comment] 2016-11-23 17:36
Choose your graphics card  :P 
<img src="http://www.fotoszok.pl/upload/86d4b279.jpg" alt="Fotoszok.pl" />

**Comment by zerr10** [comment] 2016-11-23 23:06
i dont understand before i have windows 10 10586.164 (1511 ) and DX 12 work for now i have windows 10 
1607 (14393.0) and DX12 dont work.. 

someone have fix this ? maybe version 1607 is too much new...

**Comment by zerr10** [comment] 2016-11-23 23:08
vulkan work both version system in windows 10 10586.164 (1511 ) is problem whit system and memory compresed ram well i remove it and i install version 1607

**Comment by zerr10** [comment] 2016-12-04 22:18
this error what is ???:

F {rsx::thread} class std::range_error thrown: bad conversion

**Comment by zerr10** [comment] 2016-12-04 22:19
vulkan work DX12 no work

**Comment by raven02** [comment] 2016-12-15 14:20
Duplicate of https://github.com/RPCS3/rpcs3/issues/2235

**Closed by raven02** 2016-12-15 14:20 UTC
