### ISSUE TITLE
Regression: Nier Replicant [BLJM60223] (Vulkan)

### ISSUE THREAD

**Issue by Kojikun1** [RPCS3/rpcs3#3768] opened 2017-11-21 02:14 UTC
Nier Replicant - Vulkan with Write color Buffers enabled
Nvidia GPU - Driver 388.31
Crash with this error
F {rsx::thread} class std::runtime_error thrown: Verification failed (e=0x7e):
(in file c:\projects\rpcs3\rpcs3\emu\rsx\vk\VKTextureCache.h:57)
Start with this PR https://github.com/RPCS3/rpcs3/pull/3699
PS: The Game stay in White Screen in Gameplay Without Write color buffers

**Comment by tkashkin** [comment] 2017-11-23 20:42
Same on NVIDIA 388.13, was working before #3699

**Comment by AniLeo** [comment] 2017-11-28 18:25
Did it regress on OpenGL as well?

**Comment by tkashkin** [comment] 2017-11-28 19:33
@AniLeo no, it works on OpenGL.

**Comment by Illynir** [comment] 2017-12-08 17:10
The issue is fixed on https://ci.appveyor.com/project/kd-11/rpcs3/build/0.0.4-1183/artifacts. :)

**Comment by Kojikun1** [comment] 2017-12-18 10:28
closing Fixed by this PR (Thanks kd-11)https://github.com/RPCS3/rpcs3/pull/3931

**Closed** 2017-12-18 10:28 UTC
Labels: Regression, Render: Vulkan
