### ISSUE TITLE
ogl: Mortal Kombat Demo [NPUB90578] black screen

### ISSUE THREAD

**Issue by benderscruffy** [RPCS3/rpcs3#6612] opened 2019-09-22 05:53 UTC
just a black screen with music and sound fx  playing 
using differant settings dont change anything
[RPCS3.log.gz](https://github.com/RPCS3/rpcs3/files/3639418/RPCS3.log.gz)

**Comment by incognitoh** [comment] 2019-09-22 22:09
works fine with vk

![pr1 (2)](https://user-images.githubusercontent.com/39333810/65395085-1af14b80-dd64-11e9-8df5-88be5d06e1e5.JPG)

**Comment by benderscruffy** [comment] 2019-09-22 22:29
im using opengl

**Comment by AniLeo** [comment] 2019-09-22 23:47
OpenGL is known to currently have several issues, may be worth making a megathread for those

@kd-11 ?

**Comment by kd-11** [comment] 2019-09-23 12:12
Yea, a megathread would be preferrable. OpenGL has fallen behind in usability due to lack of use by the general public, making regressions difficult to spot.

**Comment by kd-11** [comment] 2019-09-29 10:25
Check if [this build](https://ci.appveyor.com/project/kd-11/rpcs3/builds/27745253) fixes the ogl problem for this game.

**Comment by Emulator-Team-2** [comment] 2019-09-29 15:52
@benderscruffy 
Set the aspect ratio to 16:9, because this game has a black screen with the auto setting.
Close this issue.

**Comment by benderscruffy** [comment] 2019-09-30 12:43
@Emulator-Team-2 
but you dont need to set the ratio on a real ps3 to play this demo so this is still a bug

**Comment by Emulator-Team-2** [comment] 2019-09-30 17:00
@benderscruffy 
The aspect ratio is set to 16:9 by default, not auto setting.

Close this issue and open a general issue about problems with the auto aspect ratio in some games.

**Comment by kd-11** [comment] 2019-09-30 17:23
Maybe we gave people too much freedom to choose aspect ratios. On PS3 you only choose the resolution and the aspect ratio is fixed. Not sure if this is the best option since Auto on rpcs3 tells the game to use its best judgement. I guess real PS3 never tells the game to do what it wants and always gives it a fixed aspect.

**Comment by kd-11** [comment] 2020-01-07 14:18
Closing as fixed by https://github.com/RPCS3/rpcs3/pull/7207

**Closed by kd-11** 2020-01-07 14:18 UTC
Labels: Render: OpenGL
