### ISSUE TITLE
Uncharted Drake's Fortune - Physics Bug for NVIDIA only

### ISSUE THREAD

**Issue by thuru** [RPCS3/rpcs3#10955] opened 2021-10-03 15:35 UTC
Ive noticed when watching RPCS3 gameplay of the game that NVIDIA GPU users (like me) always have a physics bug on the plants vegetation in the game, where plants keep bouncing and floating in the air. Whenever an AMD gpu user plays the game, it wont happen. Ive checekd on PS3 gameplay and it runs just like the AMD gpu RPCS3. Please watch below some samples

NVIDIA GPU RPCS3 gameplay (notice the plant above the rock)
[https://youtu.be/guXyjjzWnjU?t=671](url)

AMD GPU RPCS3 gameplay (the same plant stands still)
[https://youtu.be/jvRfd8fynow?t=607](url)

Real PS3 gameplay (the same plant behaves just like the amd rpcs3 footage)
[https://youtu.be/Z8UYBOqxSl4?t=35](url)

Observations:
- Already tried accurate xfloat and ASMJIT SPU, none of them solved it. No patches were enabled.
- Ive watched dozens of AMD and NVIDIA GPU's gameplays of this game on youtube, until now every one of them confirmed the point that for amd it is ok, but for nvidia plants bounce and float, so it is not some particular user issue.
- It may look like a small issue, but sometimes the bouncing becomes very annoying and ruins the experience. The game is running very well, so this issue drags too much attention. Also, undersating and solving it could help solve some more critical physics issues on other games, so I believe it was worthy submiting it here.
- Thank you all in advance

**Comment by Linear524** [comment] 2021-10-05 03:41
As far as I know - this vegetation swinging bug is old standing vertex shader bug and people with any GFX hardware has this issue. Can you proof your theory of AMD workaround with recorded video capture from RPCS3 ?

**Comment by Xcedf** [comment] 2021-10-05 15:10
This is quite real, found a couple vids on YT running on amd gpu
https://www.youtube.com/watch?v=QoVx9l9TnOY&t=305s
https://www.youtube.com/watch?v=6F1id8PbxpE&t=538s

**Comment by kd-11** [comment] 2021-10-05 15:36
This is unexpected, I use AMD as my primary card and thought the issue was fixed a long time ago. I'll take a look.

**Comment by kd-11** [comment] 2021-10-06 18:17
Confirmed, this happens because of NVIDIA's precision drift problems. Basically it does some math and ends up with a value of 2.99999999... while every other vendor gets 3.0000000 including the PS3 hw.
Later it does a comparison between this value and 3.0 and it fails to see that the two numbers are the same. Of course this can be comfortably worked around with custom float compare routines (and has been in some local patches) but this kind of coarse precision may break other games. I'll have to think of a proper alternative.

**Comment by thuru** [comment] 2021-11-04 18:36
@kd-11 , any new insights on this issue? Let me know if I can test anything different, and thanks a lot for all your work on the subject

**Comment by coolllman** [comment] 2022-04-13 02:33
Kd-11 any news with this bug?

**Comment by illusion0001** [comment] 2022-04-13 02:46
Try #11766

**Comment by JimScript** [comment] 2022-04-13 03:42
#11766 does not fix this issue for my RTX 2070 Super:
![BCUS98103_screenshot_2022_04_12_20_35_52](https://user-images.githubusercontent.com/66685584/163095503-faca8d00-ed01-4673-8ee8-4dfc210b02be.png)
That plant is suppose to be connected to that rock on the right.

**Comment by kd-11** [comment] 2022-04-22 19:45
I have a fix for this, I found a consistent way to introduce RSX-like comparison tolerances.

**Comment by kd-11** [comment] 2022-04-24 09:41
Fixed by https://github.com/RPCS3/rpcs3/pull/11867, please test.

**Comment by thuru** [comment] 2022-04-25 13:33
Tnx a lot will test asap, but I'm out of town for a few days with no PC gamer lol

**Closed** 2022-04-27 22:31 UTC
Labels: RSX, Driver: NVIDIA
