### ISSUE TITLE
gow ascension loop issue

### ISSUE THREAD

**Issue by RainKikyou** [RPCS3/rpcs3#4416] opened 2018-04-08 08:23 UTC
build：6638
Loop is here
https://cdn.discordapp.com/attachments/272875751773306881/432415651945119745/QQ20180408134505.png
video
https://www.bilibili.com/video/av21824535/
log
https://pan.baidu.com/s/1OLITkwbOjVkvXliDUDKOMQ

**Comment by Zangetsu38** [comment] 2018-04-08 18:42
Normal, all game fixed by Spu interupt is actyally broken for cpu without TSX

**Comment by AniLeo** [comment] 2018-05-22 13:15
Needs retesting

**Comment by Asinin3** [comment] 2018-05-22 13:20
I believe this was fixed after #4417 if it's the same issue that caused all the games that need spu interrupt to stop working.

**Comment by AniLeo** [comment] 2018-05-22 13:35
Will be closing soon if no one can reproduce the bug then

**Comment by RainKikyou** [comment] 2018-05-24 07:19
no change
![qq 20180524151553](https://user-images.githubusercontent.com/20301499/40470266-94411ec6-5f65-11e8-91b9-07fff5a6ba1b.png)

**Comment by benderscruffy** [comment] 2020-02-07 08:38
this can be closed
fixed

**Comment by benderscruffy** [comment] 2020-02-11 11:33
please close due to no activity for over a year

**Comment by AniLeo** [comment] 2020-02-22 11:40
Retest with and without recent Accurate RSX reservation setting

**Comment by AniLeo** [comment] 2020-04-03 03:41
Should be fixed with setting above or even by default. If you can still reproduce, ping for reopening. Closing as fixed and inactive.

**Closed by AniLeo** 2020-04-03 03:41 UTC
Labels: Regression
