### ISSUE TITLE
NFS Most Wanted 2012 graphical issues

### ISSUE THREAD

**Issue by jas0n098** [RPCS3/rpcs3#7198] opened 2020-01-04 17:23 UTC
RPCS3 v0.0.8-9317-49d5ce3b Alpha | master | Firmware version: 4.85
AMD Ryzen 5 3600 6-Core Processor | 12 Threads | 15.58 GiB RAM | TSC: Bad | AVX+
Operating system: POSIX, Name: Linux, Release: 5.5.0-rc4-1.g7e31c5e-default, Version: #1 SMP Mon Dec 30 06:30:53 UTC 2019 (7e31c5e)
·! 0:00:00.000000 RSX: Found vulkan-compatible GPU: 'AMD RADV/ACO POLARIS10 (LLVM 9.0.1)' running on driver 19.99.99

Reflections on cars have a weird blocky pattern, black shadows and some parts of the street appear too dark

Edit: [screenshot](https://i.imgur.com/GuPYTPm.jpg)

[rpcs3logs.zip](https://github.com/RPCS3/rpcs3/files/4022199/rpcs3logs.zip)
[captures.7z](https://mega.nz/#!koY2SYDJ!gaXfw4iC_ZwkqafgihzuU2Aq-fNPamU-EzDZ1W96C78)

**Comment by kd-11** [comment] 2020-01-04 17:38
Given the way this game works, its either that or get fps less than 1. Game operates on tiled regions which means they cross pages constantly. Its the worst possible scenario, software rendering using tiles emulated on PC where the rasterization step is done off-chip on a GPU. It'll never actually work at reasonable performance but maybe it can be tweaked to fix the holes in the image caused by tile 'submission'. How well the application is synchronized is yet to be seen as well, but there is little hope there as well.

**Comment by Triticum0** [comment] 2024-01-05 19:47
@kd-11 Can this be closed?  isn't #14981 show that the graphical issue fixed with RCB with WCB+RSX Tiled memory

**Comment by kd-11** [comment] 2024-01-05 19:56
Indeed. This was fixed by implementing tiled memory handling.

**Closed by kd-11** 2024-01-05 19:56 UTC
Labels: Bug
