### ISSUE TITLE
problem with dragonrise inc. generic usb joystick to configure in linux stick get stuck  in direction 

### ISSUE THREAD

**Issue by Traff199** [RPCS3/rpcs3#14530] opened 2023-08-21 23:01 UTC
### Quick summary

 hello i have a problem with rpcs3 on batocera (linux)   i create a arcade cabinet and i have arcade stick and button on it (dragonrise inc. generic usb joystick) and when  i start a  game the controller go up and rest blocked on up 

### Details

 i try with game pad and i don't have this problem its work perfectly witch other emulator and rpcs3 work perfectly with my xbox pad i try to remap on evdev but its not work  if someone have a solution ?  thanks      ps: sorry for my English

### Attach a log file

[RPCS3.log](https://github.com/RPCS3/rpcs3/files/12403236/RPCS3.log)

### Attach capture files for visual issues

 
![image](https://github.com/RPCS3/rpcs3/assets/142756222/24eb8e86-c747-4c8e-8803-8d0defa45e33)
if i touch anything is not blocked but i f touch the stick in one direction is get stucks ![image](https://github.com/RPCS3/rpcs3/assets/142756222/d290e59d-a925-4a26-8641-344a882c75c0)

### System configuration

gpu 1050  and intel i5 -3570k

**Comment by Megamouse** [comment] 2023-08-21 23:15
not an official build, not even on the latest commit.

**Comment by AniLeo** [comment] 2023-08-21 23:28
Needs retest and log on latest official build

**Comment by Megamouse** [comment] 2023-08-25 21:21
You're not making this easy for us by keeping the log of the latest version from us.

Anyway, I believe this is caused by your evdev setup.
You're basically using two Axes for the d-pad.
Looking at your images, you can see that the d-pad is only ever so slightly pressed.
This is caused by a missing deadzone (also known as flatness) in your linux's evdev config.

You can try to increase the deadzone value for these axes.
https://wiki.archlinux.org/title/Gamepad#Setting_up_deadzones_and_calibration

**Comment by Megamouse** [comment] 2023-08-26 09:13
You can also try the mentioned pull request build.

**Comment by Megamouse** [comment] 2023-08-26 16:10
Update to the newest version and increase the pressure sensitivity deadzone in the pad settings.
I'll close this issue because I think this should fix your problems.

**Closed by Megamouse** 2023-08-26 16:10 UTC
Labels: Need Information, OS: Linux, Input
