### ISSUE TITLE
Color inversion while in game (BLUS31076) with Vulkan

### ISSUE THREAD

**Issue by jantendog** [RPCS3/rpcs3#12271] opened 2022-06-22 14:39 UTC
## Quick summary
Color inversion while in game (BLUS31076) with Vulkan

## Details

As soon as i leave the main menu and the first cut scene the colors are almost like inverted. However Overlays and  cut scenes are unchanged. Open GL fixes the Problem, but runs at very slow speeds and more crashes. Nothing should be wrong with my Vulkan set up cording to VK Diag. I installed win 10 in dual boot and same config as on win 11, but it changed nothing. 

#### 1. Please attach RPCS3's log.
[log.txt](https://github.com/RPCS3/rpcs3/files/8958594/1.txt)

#### 3. Please attach screenshots of your problem.
![2 Screenshot 2022-06-22 163536](https://user-images.githubusercontent.com/75538139/175056660-46ec60a7-0025-496f-a5dc-67dd510c7d10.png)

#### 5. Please provide your system configuration:
* OS: Windows 11 Pro x64 Build 22621.160
* CPU: Intel Core i9-9900K
* GPU: NVIDIA RTX 2080 TI
* Driver version: 516.40
* RPCS3 version: 0.0.22-13810

#### Please include.
* Any Questions ? since i dont create many issue tickets.
![3 Screenshot 2022-06-22 164726](https://user-images.githubusercontent.com/75538139/175059305-11421cdd-bd3f-44fe-9c94-cb9c8df4e87b.png)

**Comment by YuriNator557** [comment] 2022-06-22 17:09
duplicate of #12008, would suggest mentioning this on there

**Closed** 2022-06-22 17:10 UTC
Labels: Meta: Duplicate, Render: Vulkan
