### ISSUE TITLE
Custom gamepad profiles aren't recognized by the emulator since 0.0.17-12637

### ISSUE THREAD

**Issue by ElTioRata** [RPCS3/rpcs3#10723] opened 2021-08-18 01:57 UTC
## Quick summary
It's literally in the title, custom gamepad profiles aren't recognized by the emulator since 0.0.17-12637 version.

## Details
Well, it doesn't recognize the custom gamepad profiles, I think that's detailed enough.

#### 1. Please provide _exact_ build (or commit) information that introduced the regression you're reporting.
* Please see [How to find the build that caused a regression](https://wiki.rpcs3.net/index.php?title=Help:Using_different_versions_of_RPCS3#How_to_find_the_build_that_caused_a_regression.3F) in our wiki.
* You can find [History of RPCS3 builds](https://rpcs3.net/compatibility?b) here.
0.0.17-12637, the pull request is #10704

**Comment by AniLeo** [comment] 2021-08-18 02:22
Old profiles aren't meant to be recognised, Have you tried to create new ones and they don't work?

**Comment by AniLeo** [comment] 2021-08-18 04:00
Creating new profiles and trying to change them works fine, closing as we can't reproduce plus there's likely no issue with trying to read new profiles

**Closed by AniLeo** 2021-08-18 04:00 UTC
