### ISSUE TITLE
RPCS3 Crashing when it interacts with my PS4 controller.

### ISSUE THREAD

**Issue by bumpss** [RPCS3/rpcs3#8494] opened 2020-06-24 20:23 UTC
I'll pick the handler DualShock 4 and if my controller is plugged in it will crash.

As far as I can tell, anytime RPCS3 interacts with my controller it'll crash, so if i unplug it and pick the DualShock 4 then save it, plug my controller back in then play the game it will crash.

[RPCS3.log.gz](https://github.com/RPCS3/rpcs3/files/4827727/RPCS3.log.gz)

![rpcs3_w9vZJRxnNH](https://user-images.githubusercontent.com/32973570/85623678-b18aca00-b660-11ea-926b-6358f2614506.png)

#### 5. Please provide your system configuration:
* OS: Windows 10
* CPU: Intel Core i5 6600K
* GPU: NVidia GTX 1080

**Comment by Megamouse** [comment] 2020-06-24 21:00
duplicate of #5985

**Closed by Megamouse** 2020-06-24 21:00 UTC
