### ISSUE TITLE
Resistance 3 [BCES01118] - graphic errors 

### ISSUE THREAD

**Issue by elogicuk** [RPCS3/rpcs3#14124] opened 2023-07-03 05:30 UTC
### Quick summary

Black lines all over the screen using the latest RPSC3 and v1.05 of the game.

Using the recommend config from here - https://wiki.rpcs3.net/index.php?title=Resistance_3

### Details

Soon as the game starts black lines all over the screen making the game unplayable

### Attach a log file

[RPCS3.zip](https://github.com/RPCS3/rpcs3/files/11933349/RPCS3.zip)

### Attach capture files for visual issues

![ksnip_20230703-134444](https://github.com/RPCS3/rpcs3/assets/25700447/e64bf9f7-afda-46c9-882e-3684a4908e61)

[BCES01118_recording_2023_07_03_13_16_34.zip](https://github.com/RPCS3/rpcs3/files/11933362/BCES01118_recording_2023_07_03_13_16_34.zip)

https://github.com/RPCS3/rpcs3/assets/25700447/c6821611-99b8-47ae-aa09-e88e060aec07

### System configuration

Intel(R) Core(TM) i9-9900K
NVIDIA GeForce RTX 4070

OS: Garuda Linux x86_64
Kernel: 6.3.8-zen1-1-zen

RPCS3 Version: 0.0.28-15277-21f5976d (latest)

**Comment by elogicuk** [comment] 2023-07-10 03:41
whats the point of reporting bugs if no one is going to reply?

**Comment by Asinin3** [comment] 2023-07-10 05:26
There is 853 open issues, and one graphics developer. And your report doesn't even include the information we ask for (RSX Capture or Renderdoc). The process for which is explained when you first made this issue, the template explains how to get all the required info.

Its also worth you trying an old build from a month or so ago and seeing if the issue only started recently, and if it did, try and narrow down exactly what build caused the problem. Being impatient after one week is ridiculous.

**Comment by kd-11** [comment] 2023-07-11 01:18
We'll also need test results at stock PS3 settings. The log file shows 300% upcaling and a bunch of patches applied which is not stock.

**Comment by dinosauriac** [comment] 2023-08-04 21:43
Have experienced a similar issue, but it does not seem to occur when using default emulation settings. Only appears when upscaling to a higher resolution. 

![BCES01353_screenshot_2023_08_04_22_25_58](https://github.com/RPCS3/rpcs3/assets/18335743/73956350-e7b0-4829-bed8-ec88eded4a3d)

Testing at 300%, the glitching is most noticeable on certain menu elements like the chapter select screen. Can be reliably trriggered by returning to the main menu after playing for a little while or loading a save. Haven't seen fullscreen black banding, only localized to certain areas.

**Comment by AliBharwani** [comment] 2023-12-03 17:01
I had  black banding too. It happens when using 1.00 "Extend FOV" patch

**Comment by AniLeo** [comment] 2024-01-01 16:16
Closing as invalid as the black banding is caused by "Extend FOV" game patch, issues caused by game patches are not valid

**Closed by AniLeo** 2024-01-01 16:16 UTC
Labels: Need Information

**Comment by Adnancomputer** [comment] 2024-01-22 17:16
hello folks.
 my name is adnan computer.

i am new to github and i am still a beginner to programming. i dont understand much code. i am a beginner software engineer.

the problem with resistance 3 graphics is. it doesnt use opengl. it use directx. 

okay in ps3 emulator file. there is in rpcs3/emu/rsx/gl/GLcompute.h

before presenting code. i want to explain the problem.

rpcs3 loads a buffer in this buffer gl commands are loaded texture are loaded and colour are loaded.
now look at this picture

![resistance 3 gun buffer](https://github.com/RPCS3/rpcs3/assets/150608907/b099c535-48b7-469a-b4a7-68d24ab3f441)

in this picture nathan hale gun and finger is shown the buffer are loaded with the last buffer(which is buffer 4) shows the gun aim and mark

now in GLcompute.h 
we have code 

	struct cs_ssbo_to_color_image : compute_task
	{
		cs_ssbo_to_color_image();
		

 let us translate this below code

void run(gl::command_context& cmd, const buffer* src, const texture_view* dst, const u32 src_offset, const coordu& dst_region, const pixel_buffer_layout& layout);

method is empty return type name is run(gl namespace access command_context(address) cmd(gl command), constant buffer(pointer address) src, constant texture_view*(pointer address) dst, constant 32 bits src_offset, constant coordu(address) dst)_region, constant pixel_buffer layout(address)layout):

now lets convert the above code from compiler based language to english type;

method has no return type(load gl namespace and access command context addresses number cmd(command),src is buffer addresses which has constant value, texture_view dst(destination) address is constant,constant is 32 bits address src_offset, constant load coordu(address) dst_region(destination_region), constant is pixel buffer layout(address) layout);

so ps3 emulator loads a buffer loads gl commands init, load textures addresses init , and buffer has source offset which is the last entry in buffer,

this picture will will convert above code to process
![glcomputer buffer](https://github.com/RPCS3/rpcs3/assets/150608907/ba1a3537-bb7e-4d67-a336-e51c33e42a75)

now ps3 emulator loads a buffer wth a constant first address and constant last src_offset then loads texture and colour information likewise.

the problem with resistance 3 graphics is resistance 3 graphics is using opengl api. and that opengl api is not providing it with proper buffer src.

in the first picture we saw that four buffer were loaded . but in ps3 emulator less buffer are loaded. so gun aim marks and further scenes are not loaded

we have to increase the buffer size.
to convert buffer to 64 bits use two 32 bits buffer and using pointer arithmetic increase 32 bits to 64 bits
like
for example
1st pointer of buffer=0
last pointer of  buffer(meaning the last value)=4,294,967,295(32 bits full binary numbers)
now increase to 64 bits
first 64 bits pointer value=4,294,967,295+1
second 64 bits pointer value=4,294,967,295+2

the method will be changed

void run(gl::command_context& cmd, const buffer* src, const buffer* src2, const texture_view* dst, const u32 src_offset, const u32 src_offset2,const coordu& dst_region, const pixel_buffer_layout& layout);

buffer* src2=u32 src_offset*(pointer)+1
src_offset2*(pointer)=something like this

okay so i think this is the solution

please reply back
