### ISSUE TITLE
VM: Access violation reading location 0x27b0e20 (unmapped memory)

### ISSUE THREAD

**Issue by saojoao** [RPCS3/rpcs3#8047] opened 2020-04-15 21:44 UTC
## Quick summary
NHL Legacy Edition
## Details
VM: Access violation reading location 0x27b0e20 (unmapped memory)
from version 0.0.9-10079 till last version

**Comment by AniLeo** [comment] 2020-04-15 21:46
So, versions prior to 10079 don't have this issue? Need a log for before and after, incomplete regression report

**Comment by saojoao** [comment] 2020-04-15 21:46
[RPCS3.log](https://github.com/RPCS3/rpcs3/files/4483873/RPCS3.log)

**Comment by saojoao** [comment] 2020-04-15 21:47
Yes, versions prior to 10079 don`t have this issue.

**Comment by saojoao** [comment] 2020-04-15 21:48
[RPCS3.log](https://github.com/RPCS3/rpcs3/files/4483876/RPCS3.log)
log from version 10078 with game working

**Comment by AniLeo** [comment] 2020-04-15 21:48
#7874 is @elad335 's PR

**Comment by evilynux** [comment] 2020-04-16 03:46
FWIW, also affects inFamous (NPEA00252). 

With the latest version I'm getting:
F {PPU[0x1000000] Thread (main_thread) [0x004550e8]} VM: Access violation reading location 0x209b6474 (unmapped memory)

With 0.0.9-10078 it gets ingame.

**Comment by elad335** [comment] 2020-04-16 07:16
Can you try disableding LLVM accurate DFMA in advanced settings tab?

**Comment by evilynux** [comment] 2020-04-17 22:42
Hmm... I would gladly try but I can't find such an option...
![Capture du 2020-04-17 18-40-14](https://user-images.githubusercontent.com/349857/79619544-372b5000-80db-11ea-86ad-f1587de287aa.png)

**Comment by Ghostotakoi** [comment] 2020-04-18 05:10
@evilynux  create a custom config for your game go to the folder config\custom_configs and find the serial number of the game like **config_BLUS31604.yml** edit with notepad and try to find **LLVM Accurate DFMA: true** and set it to false.

**Comment by elad335** [comment] 2020-04-18 06:29
At first glance seems like tagging the wrong pr, could it be #7845 instead?

**Comment by evilynux** [comment] 2020-04-18 16:46
Thanks for the workaround @Ghostotakoi ! Indeed, that fixes it in the sense that it gets ingame again. 
Looking at https://github.com/RPCS3/rpcs3/pull/7874/files , I don't see anything obviously wrong but I'm not familiar with rpcs3's code base. (IF and ony IF I understand correctly, I do find curious that the f64 version of FMA is used to then be truncated to f32, but that shouldn't be a big deal. Perhaps the PS3 does it with doubles?)

**Comment by evilynux** [comment] 2020-04-19 18:44
Perhaps line 3962 of PPUTranslator.cpp (https://github.com/RPCS3/rpcs3/blob/5101bc189e3cd13c2904a269dcb9d58236257ce4/rpcs3/Emu/Cell/PPUTranslator.cpp#L3962)? It's FNMSUBS so I'd expect the result to be negated.

**Comment by evilynux** [comment] 2020-04-19 19:47
Confirmed fixed with rpcs3-v0.0.9-10246-e5564467_linux64.AppImage . Thanks @elad335 !

**Closed** 2020-04-19 19:55 UTC
Labels: Need Information, Regression

**Comment by TalayGG** [comment] 2020-04-23 02:54
how can i fix this problem?
F {PPU[0x1000017] Thread (decodeProc) [0x00a87b6c]} VM: Access violation reading location 0x14 (unmapped memory)

**Comment by DocMAX** [comment] 2020-07-11 17:38
Getting same problem with God of War Ascenssion

**Comment by Loacoon1** [comment] 2020-11-06 19:41
I'm reopening it since it apparently happens with Killzone 3 now (Didn't a few weeks ago as far as I know)

**E {SPU[0x2000100] Thread (HiPrioCellSpursKernel2) [0x1ac40]} VM: Access violation reading location 0x5ba8e750 (unmapped memory) [type=u0]**

**Comment by y0d4a** [comment] 2021-01-11 11:41
> 
> 
> @evilynux create a custom config for your game go to the folder config\custom_configs and find the serial number of the game like **config_BLUS31604.yml** edit with notepad and try to find **LLVM Accurate DFMA: true** and set it to false.

hey, i have the same issue with SSX, but don`t have any config file inside custom_configs ?

**Comment by evilynux** [comment] 2021-01-11 14:11
@y0d4a The issue wasn't caused by a custom config, but worked around by creating a custom config.

**Comment by Leggo87** [comment] 2021-01-12 04:08
Same With Guilty Gear Xrd -Revelator- [BLUS31588]

**Comment by BRadDominator** [comment] 2021-01-14 13:36
I had this issue with college football revamped.  I was able to fix it by checking my quarantined items in my virus protection software.   It had quarantined the qkl_misc.ast file.  I restored this and everything is working again.

**Comment by Calboequish** [comment] 2021-09-21 19:58
I have the same problem with Gran Turismo 6, i did all what this issue says, and still doesn't work.

**Comment by Carbon4160** [comment] 2021-11-27 00:09
Hey having a problem with my game just freezing and just can't play collage football revamped. I tried changing  config_BLUS31604.yml edit with notepad and try to find LLVM Accurate DFMA: true and set it to false. and did not work anyone know what to do. the version of rpcs3 is 01.02 btw.

**Comment by Carbon4160** [comment] 2021-11-27 00:11
also this is what my error code says this in pink    F {PPU[0x100001b] Thread (realmemcard_ps3) [0x003adf98]} VM: Access violation reading location 0x1 (unmapped memory) [type=u0]

**Comment by AniLeo** [comment] 2021-11-27 00:14
Locking since the original issue has long been fixed, now it's just getting unrelated posts
