### ISSUE TITLE
Failed to compile on osx

### ISSUE THREAD

**Issue by ellipticaldoor** [RPCS3/rpcs3#1180] opened 2015-08-13 17:30 UTC
I'm getting this error when I try to compile rpcs3 after following all the steps indicated on the readme.md for osx.

```
[  0%] Building CXX precompiled header cotire/rpcs3_CXX_prefix.hxx.pch
In file included from /Users/miguel/src/source/rpcs3/rpcs3/cotire/rpcs3_CXX_prefix.hxx:4:
In file included from /Users/miguel/src/source/rpcs3/rpcs3/stdafx.h:139:
/Users/miguel/src/source/rpcs3/rpcs3/../Utilities/BEType.h:357:16: error: use of undeclared identifier '_mm_shuffle_epi8'
                return fromV(_mm_shuffle_epi8(val.vi, _mm_set_epi8(0, 1, 2, 3, 4, 5, 6, 7, 8, 9, 10, 11, 12, 13, 14, 15)));
                             ^
1 error generated.
CMake Error at cmake_modules/cotire.cmake:1545 (message):
  Error 1 precompiling
  /Users/miguel/src/source/rpcs3/rpcs3/cotire/rpcs3_CXX_prefix.hxx.
Call Stack (most recent call first):
  cmake_modules/cotire.cmake:2933 (cotire_precompile_prefix_header)


make[2]: *** [cotire/rpcs3_CXX_prefix.hxx.pch] Error 1
make[1]: *** [CMakeFiles/rpcs3.dir/all] Error 2
make: *** [all] Error 2
```

**Comment by danilaml** [comment] 2015-08-15 18:11
can you post full log on pastebin or git gist? I encountered similar problem (or exact same) trying to update cotire to the latest version.

**Comment by ellipticaldoor** [comment] 2015-08-15 18:24
here you go

http://pastebin.com/raw.php?i=Uy2zgzf1

**Comment by danilaml** [comment] 2015-08-15 19:09
Can you say what version of clang are you using? And what is your CPU?

**Comment by danilaml** [comment] 2015-08-15 22:39
@ellipticaldoor could you try if this PR https://github.com/RPCS3/rpcs3/pull/1182 fixes your problem?

**Comment by MorganBauer** [comment] 2015-08-16 08:43
Same thing here, pr#1182 doesn't help.
λ clang --version
Apple LLVM version 6.1.0 (clang-602.0.53) (based on LLVM 3.6.0svn)
Target: x86_64-apple-darwin14.4.0
Thread model: posix

λ sysctl -n machdep.cpu.brand_string
Intel(R) Core(TM) i7-4980HQ CPU @ 2.80GHz

If I add an include for tmmintrin.h it gets farther.

**Comment by danilaml** [comment] 2015-08-16 12:48
Can you add set(CMAKE_VERBOSE_MAKEFILE ON) to the top of rpcs3/CMakeLists.txt
and post full log after that?

**Comment by MorganBauer** [comment] 2015-08-17 00:06
set(CMAKE_VERBOSE_MAKEFILE ON) over pr1182
https://gist.github.com/MorganBauer/3213916cb706dd6c1d01
cherry-pick over pr1182
https://gist.github.com/MorganBauer/f50ec181fa62e4495058

**Comment by danilaml** [comment] 2015-08-17 01:18
@MorganBauer hm, very strange. It definitely builds with right flags (-mssse3) in the first case but stil can't find the right intrinsics. Could be some apple bug (as linux clang builds work correctly).

What about including <x86intrin.h> ?

**Comment by MorganBauer** [comment] 2015-08-17 02:23
https://gist.github.com/MorganBauer/10f737bcbbdafdb814ed
gets farther, but this was as far as my debugging skills could take me. Seems to be complaining about how the headers compile or something.

**Comment by danilaml** [comment] 2015-08-17 02:26
@MorganBauer can you add `message(STATUS "OSX ARCHS = ${CMAKE_OSX_ARCHITECTURES}")` here https://github.com/RPCS3/rpcs3/blob/master/rpcs3/CMakeLists.txt#L7
and see what it prints?

**Comment by MorganBauer** [comment] 2015-08-17 02:45
It's blank. What did I miss?
-- OSX ARCHS =

**Comment by danilaml** [comment] 2015-08-17 02:52
@MorganBauer nothing, probably it's no the case.
Maybe run cmake with `-DCMAKE_OSX_ARCHITECTURES=x86_64` to be completely sure, but I'm out of ideas for now. I'll try to get OSX into VM and see if I can reproduce this problem.

**Comment by MorganBauer** [comment] 2015-08-17 02:57
Alright cool. I'll stick around. I want to contribute.

**Comment by paulsapps** [comment] 2015-08-17 06:52
Seems to be a legit issue with "exception specification of overriding function is more lax than base version" on make_ptr?

I can't see the declaration of make_ptr but I guess its dtor has missing exception specification or some such?

**Comment by tambry** [comment] 2015-08-19 13:04
@ellipticaldoor @MorganBauer Neko said, that #1180 might fix some of the compilation problems.

**Comment by danilaml** [comment] 2015-08-19 13:06
@tambry it won't fix all of them though. I think I almost fixed it in my branch: https://github.com/danilaml/rpcs3/commits/travis-osx

**Comment by tambry** [comment] 2015-08-19 13:09
@danilaml Ah, didn't know that. Also, you should probably squash those small "fix" commits into one more bigger "fix" commit. At least squashing would be nice.

**Comment by danilaml** [comment] 2015-08-19 13:21
@tambry will do later. It's just a testing branch for now, since the only they for me to test changes is run them on travis (hence many small commits).

**Comment by danilaml** [comment] 2015-08-19 14:05
@ellipticaldoor @MorganBauer can you confirm that https://github.com/RPCS3/rpcs3/pull/1190 fixes your problem?

**Comment by ellipticaldoor** [comment] 2015-08-20 00:55
how I can check it? I made git pull but my local repo it is not updating

**Comment by MorganBauer** [comment] 2015-08-20 01:31
gets a hell of a lot farther, but doesn't finish.
https://gist.github.com/MorganBauer/bfaa63b45ae74c482089

**Comment by danilaml** [comment] 2015-08-20 02:21
@MorganBauer 
brew installs binaries also so you don't need to build llvm yourself.
Default apple llvm doesn't come with required cmake files (at least it seems so) so it can't be properly included in cmake build (and only latest xcode have new enough llvm for us).

It's strange however that It picked up llvm in your case. Maybe some old installation?
Anyway it seems that apple modified svn version conflicts with version we are using (3.6.2 stable) across all platforms and llvm itself isn't really good at keeping backwards compatibility (there are some changes needed to port to 3.7 for example) so installing specific version from brew/apt/etc seems to be a better way.

**Comment by danilaml** [comment] 2015-08-20 02:24
@ellipticaldoor 
You can try:
```
git fetch -q origin +refs/pull/1190/merge:
git checkout -qf FETCH_HEAD
```
Or you can just download zip of my `travis-osx` branch for testing.

**Comment by MorganBauer** [comment] 2015-08-20 02:24
Makes sense, but isn't it still compiling with the apple provided clang (llvm 3.6.0)?

**Comment by MorganBauer** [comment] 2015-08-20 04:25
```
CC=/usr/local/opt/llvm/bin/clang \
CXX=/usr/local/opt/llvm/bin/clang++ \
LLVM_DIR=/usr/local/opt/llvm/share/llvm/cmake/ \
cmake ..
```
works and uses the clang installed by `brew install llvm --with-clang`.

**Comment by danilaml** [comment] 2015-08-20 14:03
@MorganBauer clang is fine. You can use apple one. The problem is with llvm libs. The ones provided by apple are not base on official stable release, so they differ from what we use. And that part  of them we use is getting changed frequently so apple llvm libs already have some incompatible difs. (Also they don't usually come with needed cmake modules).

But - that's only for llvm includes/libs . Clang should be fine (if it's >= 3.5).

**Comment by danilaml** [comment] 2015-08-25 23:18
@ellipticaldoor I'm assuming you/we can close this issue?

**Comment by MorganBauer** [comment] 2015-08-26 02:31
Works for me. Close it.

**Closed** 2015-08-26 05:23 UTC
