### ISSUE TITLE
HLE syscall_988

### ISSUE THREAD

**Issue by LordLoras** [RPCS3/rpcs3#1974] opened 2016-07-23 10:51 UTC
The game i've been trying to run is TRANSFORMERS Devastation.It closes instantly when i try to boot with any settings and any renderer
 {PPU[0xa] Thread (main_thread) [0x0082e308]} HLE TODO: Unimplemented syscall syscall_988 -> CELL_OK

[RPCS3.txt](https://github.com/RPCS3/rpcs3/files/379504/RPCS3.txt)

**Comment by SakataGintokiYT** [comment] 2016-07-23 10:56
Duplicate of  #1693

**Comment by raven02** [comment] 2016-07-23 11:13
Please search for existing issue before open new one.

**Closed** 2016-07-23 11:12 UTC
