### ISSUE TITLE
FPS drops when window in focus

### ISSUE THREAD

**Issue by Rex000** [RPCS3/rpcs3#8811] opened 2020-08-31 08:45 UTC
## Quick summary

FPS drops when window in focus.

## Details

Whenever the game window is in focus, there is constant FPS drops and sound chopping. When I put focus on another window such as a browser, the FPS drops are gone and sound is fixed too.

[RPCS3.log.gz](https://github.com/RPCS3/rpcs3/files/5149215/RPCS3.log.gz)

## System configuration:
* OS - Win 7 x64
* CPU - Intel Core i5 3570K
* GPU - GTX 960
* RAM - 8GB DDR3

**Comment by Satan86** [comment] 2020-08-31 08:46
Duplicate of #8363

**Closed** 2020-08-31 08:48 UTC
