### ISSUE TITLE
DX12: Blade Arcus From Shining EX broken texture

### ISSUE THREAD

**Issue by SakataGintokiYT** [RPCS3/rpcs3#1681] opened 2016-04-24 16:50 UTC
@tambry 
@vlj 
@kd-11 
@Zangetsu38 

[d9caad4d]
_____________________________________________________________________________
DX12 ;
{rsx::thread} class fmt::exception thrown: rsx::to_surface_depth_format(): Unknow surface depth format 0
(in file C:\rpcs3\rpcs3\Emu\RSX\GCM.cpp:991)
_____________________________________________________________________________
OGL ;
{rsx::thread} class fmt::exception thrown: rsx::to_surface_color_format(): unknow surface color format 0
(in file C:\rpcs3\rpcs3\Emu\RSX\GCM.cpp:1036)
_____________________________________________________________________________
Video : https://www.youtube.com/watch?v=_x5XBPHlexU&feature=youtu.be

Settings:
-PPU - Interpreter  (Fast)
-SPU - Interpreter ASMJIT
-Vulkan
-1280x720 
-Xaudio2
-Frame limit OFF 

LLE:
-libsre  (cellSre_Library v1.1
-libspurs_jq  (cellSpursJq_Library v1.1)

Log : https://gist.github.com/SakataGintokiYT/f3294e54eabcf26d25ed2595e4765db3

{rsx::thread} RSX: Surface color buffer: Unsupported surface color format (0xc)

______________________________________________________________________________
<img src="http://www.fotoszok.pl/upload/00937a49.jpg" alt="Fotoszok.pl" />
<img src="http://www.fotoszok.pl/upload/59c052ec.jpg" alt="Fotoszok.pl" />
<img src="http://www.fotoszok.pl/upload/7171e1f7.jpg" alt="Fotoszok.pl" />
<img src="http://www.fotoszok.pl/upload/a5302cc7.jpg" alt="Fotoszok.pl" />
<img src="http://www.fotoszok.pl/upload/c4939135.jpg" alt="Fotoszok.pl" />

**Comment by raven02** [comment] 2016-05-25 16:22
@SakataGintokiYT  so only vulkan backend work but OGL and DX12 failed to start ?

**Comment by SakataGintokiYT** [comment] 2016-05-25 16:53
yes

**Comment by raven02** [comment] 2016-05-26 02:30
Try to change as follow in GCM.cpp and compile to see if it works 

rsx::surface_depth_format rsx::to_surface_depth_format(u8 in)
{
	switch (in)
	{
	case 0: // Unknown surface depth format 0
	case CELL_GCM_SURFACE_Z16: 
		return rsx::surface_depth_format::z16;
	case CELL_GCM_SURFACE_Z24S8: return rsx::surface_depth_format::z24s8;
	}
	throw EXCEPTION("Unknow surface depth format %x", in);
}

**Comment by SakataGintokiYT** [comment] 2016-05-26 10:10
@raven02 
Unknow surface depth format 0 - Fix probably 
  

DX12  [ surface color format 0]
*Now   
{rsx::thread} class fmt::exception thrown: rsx::to_surface_color_format(): unknow surface color format 0
(in file C:\rpcs3\rpcs3\Emu\RSX\GCM.cpp:1038)

**Comment by tambry** [comment] 2016-05-26 11:00
This seems like a hack. Very likely caused by a bug somewhere else, as noted by @MoochMcGee on #1711.

In headers there are only two such formats:
```
...
CELL_GCM_SURFACE_Z16 = (1),
CELL_GCM_SURFACE_Z24S8 = (2),
...
```

From CellGcmEnum in /target/ppu/include/cell/gcm/gcm_enum.h.

**Comment by raven02** [comment] 2016-05-26 13:59
Probably 0 is the default case . i remember @vlj did put a case 0 before in his PR .

**Comment by kd-11** [comment] 2016-05-27 21:48
Could also be a bug in the game that was hidden by the ps3 libraries. If this is the case, 0 would return the default format, probably one of the normalized 8-bit channel ones (RGBA8 BGRA8 ARGB8) so  VK_FORMAT_B8G8R8A8_UNORM might work. @SakataGintokiYT @raven02 You can just check if adding a zero case to the default catch-all block displays correctly.

**Comment by SakataGintokiYT** [comment] 2016-05-27 22:01
@kd-11 
Where put this command ? VKFormats.cpp ?

**Comment by kd-11** [comment] 2016-05-28 01:43
The 0 values are because a clear command is given before buffers are set up properly. We never expect the game to not have parameters set up which causes issues on opengl renderer. Some simple fixes later and it works the same as vulkan with missing visuals. @SakataGintokiYT How do you get ingame? The display is just black

**Comment by raven02** [comment] 2016-05-28 04:09
Probably he just press start to skip it .

**Comment by SakataGintokiYT** [comment] 2016-05-28 10:13
Kd-11 
I skip black screen by pressing c and enter

**Comment by kd-11** [comment] 2016-05-28 10:16
I'm submitting a fix that should allow the emulator to ignore clear commands if the current surface is set to none. That allows the game to work on all renderers and DX12 looks better in the intros than GL and vulkan. I'll look into the other two later.

**Comment by raven02** [comment] 2016-05-28 10:39
However i'm wondering why vulkan works in first place but not DX12 and OpenGL

**Comment by kd-11** [comment] 2016-05-28 10:45
With vulkan, there is a check for this. If we have not initialized any rendering, clearing does nothing since there is a check for a working present image, initialized to FFFF which is invalid. That is what caught the bogus clear request.

**Comment by kd-11** [comment] 2016-05-28 10:52
OGL and Vulkan should be ok now, except for the black textures. DX12 has better menus but no ingame graphics making it completely unplayable.

**Comment by SakataGintokiYT** [comment] 2016-05-28 11:01
@Kd-11 Try add commit  #1709

**Comment by kd-11** [comment] 2016-05-28 11:26
Its a blending issue for all backends actually. I'll submit a fix soon.

**Comment by raven02** [comment] 2016-05-28 11:41
@kd-11 .It would be nice if you can help to take a look this as well https://github.com/RPCS3/rpcs3/issues/1699

which DX12 shows the title screen but not Vulkan and OpenGL backend

**Comment by kd-11** [comment] 2016-05-28 11:43
@raven02 Its the blending factors for this game that are messed up. Probably a bug affecting multiple games.

**Comment by kd-11** [comment] 2016-05-28 14:24
It seems the game requests a surface format with discarded alpha and sets up the blending factors in the menus so that final alpha value becomes zero since it is assumed that alpha is always going to be read back as one. I've updated https://github.com/RPCS3/rpcs3/pull/1722 to respect alpha configuration requested (opengl only for now). @SakataGintokiYT Please test if there are any regressions caused by the pull request.

**Comment by SakataGintokiYT** [comment] 2016-05-28 14:43
@kd-11 
OGL :
<img src="http://www.fotoszok.pl/upload/296e57f9.jpg" alt="Fotoszok.pl" />
<img src="http://www.fotoszok.pl/upload/9f83a7ab.jpg" alt="Fotoszok.pl" />
<img src="http://www.fotoszok.pl/upload/ae053091.jpg" alt="Fotoszok.pl" />
<img src="http://www.fotoszok.pl/upload/6902ba85.jpg" alt="Fotoszok.pl" />
<img src="http://www.fotoszok.pl/upload/d0e19cef.jpg" alt="Fotoszok.pl" />

**Comment by kd-11** [comment] 2016-05-28 14:49
I'll look into the viewport after i get dx12 and vk up to speed.

**Comment by kd-11** [comment] 2016-05-30 14:34
I have updated the PR to also fix vulkan issues. @SakataGintokiYT please check for any issues

**Comment by raven02** [comment] 2016-05-30 15:25
Vulkan looks good on this game 

![untitled](https://cloud.githubusercontent.com/assets/3000282/15653156/b318ef8c-26bd-11e6-805f-f37569751c92.jpg)

**Comment by raven02** [comment] 2016-05-30 15:37
This is DX12

![1](https://cloud.githubusercontent.com/assets/3000282/15653389/5c41e7de-26bf-11e6-9383-418ed8a2f988.jpg)
![2](https://cloud.githubusercontent.com/assets/3000282/15653396/70fef2c0-26bf-11e6-893c-ef8b3cfee4c4.jpg)

**Comment by SakataGintokiYT** [comment] 2016-05-30 16:21
<img src="http://www.fotoszok.pl/upload/58af67e8.jpg" alt="Fotoszok.pl" />
<img src="http://www.fotoszok.pl/upload/82c97928.jpg" alt="Fotoszok.pl" />
<img src="http://www.fotoszok.pl/upload/713ac641.jpg" alt="Fotoszok.pl" />
<img src="http://www.fotoszok.pl/upload/ff7f702d.jpg" alt="Fotoszok.pl" />
<img src="http://www.fotoszok.pl/upload/d502550d.jpg" alt="Fotoszok.pl" />

**Comment by kd-11** [comment] 2016-05-30 17:47
@SakataGintokiYT I've updated the pull request to fix the channel swap issues

**Comment by SakataGintokiYT** [comment] 2016-06-01 20:49
@kd-11 
what about with dx12 ?

**Comment by kd-11** [comment] 2016-06-01 20:53
I'll fix dx12 in a separate pull request to keep changes manageable. There are some other incoming fixes for opengl and vulkan after https://github.com/RPCS3/rpcs3/pull/1722 gets merged. I can look at dx12 after that.

**Comment by SakataGintokiYT** [comment] 2016-06-13 16:14
@kd-11 
Do you have Fix for DX12  ?

**Comment by kd-11** [comment] 2016-06-13 16:24
Not yet. Haven't had a look at it just yet.

**Comment by SakataGintokiYT** [comment] 2016-06-19 21:26
@raven02 
LLVM 
https://www.youtube.com/watch?v=d-NZmQtzuU8&feature=youtu.be

**Comment by raven02** [comment] 2016-06-20 02:23
Nice speed . I got only 10-13 fps in title using LLVM

**Comment by SakataGintokiYT** [comment] 2016-06-26 11:45
Scoot Pilgrim VS The, World: The Game 

[6c45b880]
Game ID [NPUB30162]

{rsx::thread} class fmt::exception thrown: rsx::to_surface_color_format(): unknow surface color format 0
(in file C:\rpcs3\rpcs3\Emu\RSX\GCM.cpp:1036)

{rsx::thread} class fmt::exception thrown: rsx::to_surface_depth_format(): Unknow surface depth format 0
(in file C:\rpcs3\rpcs3\Emu\RSX\GCM.cpp:991)

**Comment by raven02** [comment] 2016-06-26 13:32
Did u boot and in-game or just black screen?

**Comment by SakataGintokiYT** [comment] 2016-06-26 15:19
@raven02 
<img src="http://www.fotoszok.pl/upload/9fbeb6f0.jpg" alt="Fotoszok.pl" />

**Comment by raven02** [comment] 2016-06-27 05:19
I see. Can you try this one to see if it helps ?

https://mega.nz/#!dE5iSQYA

**Comment by SakataGintokiYT** [comment] 2016-06-27 05:27
@raven02  I need your key :)

**Comment by SakataGintokiYT** [comment] 2016-06-27 05:29
@raven02 
Same on all backend   / no booting

**Comment by raven02** [comment] 2016-06-27 05:31
https://mega.nz/#!tJYlFLgR!kxbuetJVgK_LPntSdHDdSFwTV2DzHy52-oHWCvYoq88

**Comment by SakataGintokiYT** [comment] 2016-06-27 05:48
@raven02 
This issue not appears but still no booting 

Vulkan:
{rsx::thread} class fmt::exception thrown: vk::image::image(): Assertion failed! Result is C4650B07h
(in file c:\jacky\rpcs3-master\rpcs3\emu\rsx\vk\VKHelpers.h:369)

OpenGL : 
{rsx::thread} class std::logic_error thrown: 0x8cd6

DX12 : Win32 error : 
https://gist.github.com/SakataGintokiYT/e1ed3a4932317fa252b43f131767f349

**Comment by raven02** [comment] 2016-06-27 05:52
I see. Then probably other issues that we don't know.

**Comment by kd-11** [comment] 2016-06-27 12:09
@raven02 @SakataGintokiYT This is another example of a game that tries to draw something or clear a framebuffer before properly initializing; e.g sending a clear command before setting up frame buffers or just starting to draw before setting up render targets properly. I could take a look but it'd take a few days for my schedule to clear up a bit.

**Comment by SakataGintokiYT** [comment] 2016-06-30 11:13
@raven02 
@kd-11  
State:  Black screen / with some sound --{intro Rockstar}
##### GTA San Andreas  /The same error 
##### [DX12/OGL/]
{rsx::thread} class fmt::exception thrown: rsx::to_surface_color_format(): unknow surface color format 0
(in file C:\rpcs3\rpcs3\Emu\RSX\GCM.cpp:1036)

*Log : https://gist.github.com/SakataGintokiYT/8be4e75ad98159be112489e9fb803a7a

##### [Vulkan] 
{rsx::thread} class fmt::exception thrown: rsx::to_surface_depth_format(): Unknow surface depth format 0
(in file C:\rpcs3\rpcs3\Emu\RSX\GCM.cpp:991)

**Comment by raven02** [comment] 2016-07-10 10:30
@SakataGintokiYT , are you set the frame limit here to something like 60 or AUTO other than OFF?

**Comment by raven02** [comment] 2016-07-10 10:54
Take one example , Outrun arcade running in DX12

If frame limit set to OFF , it boots up okay
If frame limit set to 60 , 59.94 etc , it simply throw rsx::to_surface_depth_format(): Unknow surface depth format 0

**Comment by raven02** [comment] 2016-07-12 12:07
@SakataGintokiYT , please test it with https://github.com/RPCS3/rpcs3/pull/1898

**Comment by SakataGintokiYT** [comment] 2016-07-12 14:17
@raven02 
No change and still broken graphic

**Comment by raven02** [comment] 2016-07-12 14:39
I mean did you still encounter the surface depth format 0 ?

**Comment by SakataGintokiYT** [comment] 2016-07-12 15:11
@raven02 
In Blade Arcus From Shining EX   [ This error not appear ]

GTA San Andreas  
 {rsx::thread} class fmt::exception thrown: rsx::to_surface_depth_format(): Unknow surface depth format 0
(in file C:\rpcs3\rpcs3\Emu\RSX\GCM.cpp:991)


Scoot Pilgrim VS The, World: The Game
{rsx::thread} class fmt::exception thrown: rsx::to_surface_depth_format(): Unknow surface depth format 0
(in file C:\rpcs3\rpcs3\Emu\RSX\GCM.cpp:991)

**Comment by SakataGintokiYT** [comment] 2016-07-12 16:16
@raven02 

##### [OpenGL]  XD XDDDDXD ^_^
Master + vlj rsx-refactor-wip
http://www.fotoszok.pl/upload/08cd7dd5.jpg

_________________________________________________________________________________________________________

[ DX12]
##### Master + vlj rsx-refactor-wip  

GTA San Andreas  working on Vlj rsx-refactor-wip     [Fix  depth format 0]

Working Rockstar intro : 
<img src="http://www.fotoszok.pl/upload/0c9a44da.png" alt="Fotoszok.pl" />

{rsx::thread} RSX: FS build failed:E:\EMU\PS3\[ RPCS3 ]\FragmentProgram.hlsl(134,7-40): error X3037: constructors only defined for numeric base types

{rsx::thread} class fmt::exception thrown: D3D12Traits::build_pipeline(): fragment program compilation failure
(in file c:\rpcs3\rpcs3\emu\rsx\d3d12\D3D12PipelineState.h:162)

**Comment by SakataGintokiYT** [comment] 2016-07-12 16:21
@raven02 

[OGL] 
##### Master + vlj rsx-refactor-wip  
<img src="http://www.fotoszok.pl/upload/08cd7dd5.jpg" alt="Fotoszok.pl" />

---------------------------------------------------------------------------------------------

[ DX12]
##### Master + vlj rsx-refactor-wip  

GTA San Andreas  working on Vlj rsx-refactor-wip     [Fix  depth format 0]

Working Rockstar intro : 
<img src="http://www.fotoszok.pl/upload/0c9a44da.png" alt="Fotoszok.pl" />

{rsx::thread} RSX: FS build failed:E:\EMU\PS3\[ RPCS3 ]\FragmentProgram.hlsl(134,7-40): error X3037: constructors only defined for numeric base types

{rsx::thread} class fmt::exception thrown: D3D12Traits::build_pipeline(): fragment program compilation failure
(in file c:\rpcs3\rpcs3\emu\rsx\d3d12\D3D12PipelineState.h:162)

**Closed** 2016-08-09 08:42 UTC
Labels: bug, dx12
