### ISSUE TITLE
Revenant Saga [NPUB31863] nothing but a black screen

### ISSUE THREAD

**Issue by benderscruffy** [RPCS3/rpcs3#7050] opened 2019-12-02 15:50 UTC
F {PPU[0x1000005] Thread (UnityMain)} class std::runtime_error thrown: Trap! (0xff458)
[RPCS3.log.gz](https://github.com/RPCS3/rpcs3/files/3912033/RPCS3.log.gz)

**Comment by Illynir** [comment] 2019-12-02 17:05
PPU Interpreter works perfectly.

**Comment by RainbowCookie32** [comment] 2019-12-02 17:10
The playable report was done on PPU Fast. If running the game with it instead of LLVM fixes it, then comment in #5831 and close this one.

**Comment by benderscruffy** [comment] 2019-12-02 22:23
if i use ppu instead of LLVM it still crashes
F {PPU[0x1000005] Thread (UnityMain)} class std::runtime_error thrown: Trap!
(in file C:\projects\rpcs3\rpcs3\Emu\Cell\PPUInterpreter.cpp:3186)

**Comment by benderscruffy** [comment] 2020-01-28 07:08
still the same error
[RPCS3.zip](https://github.com/RPCS3/rpcs3/files/4121046/RPCS3.zip)

**Comment by digitaldude555** [comment] 2020-02-26 16:18
Last worked in 0.0.5-7338 build and broke 0.0.5-7345.
#5111 broke it. Same exact issue as #6365.

**Comment by benderscruffy** [comment] 2020-04-15 11:09
still happens in the latest master
here is an updated log and tty
[RPCS3.log.gz](https://github.com/RPCS3/rpcs3/files/4480817/RPCS3.log.gz)
[TTY.log](https://github.com/RPCS3/rpcs3/files/4480818/TTY.log)

**Comment by AniLeo** [comment] 2021-07-15 02:15
Closing as duplicate of #6365, please continue to discuss there

**Closed by AniLeo** 2021-07-15 02:15 UTC
