### ISSUE TITLE
J-Stars Victory VS+ [BLES02136] Crashes when using any special move

### ISSUE THREAD

**Issue by bajulador** [RPCS3/rpcs3#10128] opened 2021-04-16 22:06 UTC
I can confirm that the game still is crashing every time a special attack happens;
Tested on 0.0.15-12104-ae8d1a3a Alpha;
Error "E VM: Access violation writing location 0xffdead00 (unmapped memory) [type=u32]".
![0001](https://user-images.githubusercontent.com/59267216/115088569-d2b9f100-9ee6-11eb-893d-eb69de0cf755.png)

[RPCS3.log](https://github.com/RPCS3/rpcs3/files/6328018/RPCS3.log)

**Comment by AniLeo** [comment] 2021-04-16 22:08
Duplicate of #7858

**Closed by AniLeo** 2021-04-16 22:08 UTC

**Comment by bajulador** [comment] 2021-04-16 22:11
Oh sorry AniLeo, I thought I had to create another thread because of the different region. My bad.
