### ISSUE TITLE
RPCS3 runs slow-mo with jittery audio and missing graphics using --no-gui

### ISSUE THREAD

**Issue by klepp0906** [RPCS3/rpcs3#8248] opened 2020-05-17 12:50 UTC
## Quick summary
RPCS3 via command line is running in slow-motion and with missing graphics if launched with --no-gui

## Details
if i launch via the emulator itself.  all is well.  if i launch the same game via command line, all is  well.
if i launch the same game via command line using --no-gui,  its in slow-mo with jittery audio and the start screen is missing graphics.

this is from NNK

![image](https://user-images.githubusercontent.com/10392920/82147091-5cff5e00-981b-11ea-94cd-c6cc5e6d8cce.png)

**Comment by Megamouse** [comment] 2020-05-17 13:07
Provide log without and with nogui

**Comment by klepp0906** [comment] 2020-05-17 13:08
on it.  about to test with a few more games to ensures not game specific then ill upload logs with and without

**Comment by klepp0906** [comment] 2020-05-17 13:16
ok, definitely not game specific.

heres the log with --nogui

[RPCS3.log.gz](https://github.com/RPCS3/rpcs3/files/4640289/RPCS3.log.gz)

**Comment by klepp0906** [comment] 2020-05-17 13:18
here is the log without --nogui

[RPCS3.log.gz](https://github.com/RPCS3/rpcs3/files/4640295/RPCS3.log.gz)

**Comment by sampletext32** [comment] 2020-05-17 13:53
It seems like the only real difference in initialization is this piece of code.
```
m_emu_settings.reset(new emu_settings());
m_gui_settings.reset(new gui_settings());
m_persistent_settings.reset(new persistent_settings());
```
So I think it's something about settings reset.

**Comment by klepp0906** [comment] 2020-05-17 17:07
assume theres nothing to be done on my end as a workaround outside of launching without --nogui for now?

i tried with openGL as well as vulkan and it happens with both unfortunately.

**Comment by klepp0906** [comment] 2020-05-19 01:55
tested every single setting available.  nothing client side to circumvent it seems.

**Comment by klepp0906** [comment] 2020-05-25 21:35
I apologize if this comes across as pushy, it's not my intent.   I realize based on the number of issue reports alone, never mind active development on rpcs3 itself - you guys have more than enough to keep you busy.

I waited quite some time for this to be implemented, and its functioning is really important to me.  I noticed this is tagged with "need information" and I just wanted to be sure that you guys have all that you need from me information wise? 

I'd hate to be sitting here trying to be the prince of patience when a developer was waiting on me all along ;p

enjoy your memorial day :)

**Comment by Megamouse** [comment] 2020-05-26 05:54
I already tried but I couldn't see any difference in performance 🤷

**Comment by klepp0906** [comment] 2020-05-26 09:33
It’s not the performance in so much as the fact the textures at the startup screen don’t even load, music doesn’t even play.  Whereas launched through the GUI - normal as can be. 

Any suggestions on what it could be if it were on my end?  

Thanks again <3

**Comment by klepp0906** [comment] 2020-05-26 12:52
just eradicated my display drivers with DDU and reinstalled a different version.  Same issue.

Without some hand holding I have no idea.   I use a half a dozen other emulators and their equivalent of direct launch/no-gui all work without fail.   Certainly not pointing the finger, as the behavior could very well be rooted on my end.   I'll just need some developer expertise to uncover why it would launch perfectly fine without that flag, and that flag causes speed/graphical/audio anomalies.   

I tried from an admin command prompt and non admin fwiw.  No idea what else to do as a process of elimination. 

a more robust form of logging i can enable/submit perhaps?

**Comment by vsub** [comment] 2020-05-26 17:02
Are trying to play a game that have custom setting?
Are you starting rpcs3 with the command like from something like a launcher or a desktop shortcut

**Comment by ZombiJambi** [comment] 2020-05-26 17:08
I'm having the same issue. I'm using Steam ROM Manager to make links within Steam. I noticed this issue in Kingdom Hearts 1.5. When launching with --no-gui from the Steam shortcut, there was a small hitch every second or so. It seems to be an issue with frame pacing or frame limiting.
Then I tested using a separately created Windows shortcut with the same command line as the Steam shortcut, and got the same results. I'm attaching the logs of both with and without the flag.

[RPCS3 - --no-gui Steam Shortcut.log](https://github.com/RPCS3/rpcs3/files/4683791/RPCS3.-.--no-gui.Steam.Shortcut.log)

[RPCS3 - Steam Shortcut.log](https://github.com/RPCS3/rpcs3/files/4683792/RPCS3.-.Steam.Shortcut.log)

**Comment by ZombiJambi** [comment] 2020-05-26 17:19
> Are trying to play a game that have custom setting?

Yes, I'm assuming you're implying that the --no-gui option is just loading the game without the custom configuration, so I tried renaming the custom config file so it would load with default settings, and same results. Without the flag, no hitching; smooth frame pacing. With the flag, hitching.
> Are you starting rpcs3 with the command like from something like a launcher or a desktop shortcut

Tried with Steam shortcut, and with desktop shortcut; same thing. Also tried from an admin Command prompt, and same thing.

**Comment by vsub** [comment] 2020-05-26 20:32
I don't know if it will help but
Right click on the exe=>properties=>compatibility=>enable "Disable fullscreen optimizations"

**Comment by ZombiJambi** [comment] 2020-05-26 20:57
I already (unknowingly) had that option checked on the rpcs3.exe, but I enabled it on the shortcut I created, and I get the same hitching. Then just to double confirm, I simply removed the --no-gui flag, and voila, perfect frame pacing.

**Comment by ZombiJambi** [comment] 2020-05-26 21:04
I compared both logs, and here's something to look at: 

>>> ·! 0:00:00.745248 RSX: Found vulkan-compatible GPU: 'AMD Radeon (TM) R9 390 Series' running on driver 2.0.137
·E 0:00:00.767565 RSX: Your GPU does not support alpha-to-one for multisampling. Graphics may be inaccurate when MSAA is enabled.
·! 0:00:00.767581 RSX: GPU/driver lacks support for float16 data types. All float16_t arithmetic will be emulated with float32_t.
·! 0:00:00.790254 RSX: Vulkan: Renderer initialized on device 'AMD Radeon (TM) R9 390 Series'
·! 0:00:00.790278 RSX: Swapchain: present mode 2 in use.

**Comment by klepp0906** [comment] 2020-05-26 21:13
> Are trying to play a game that have custom setting?
> Are you starting rpcs3 with the command like from something like a launcher or a desktop shortcut

i tried through launchbox.  i tried through command prompt at desktop.  tried through command prompt at desktop as admin.

also purged all cache's and tried.

sorry was outside doing yard work all day, just now getting caught up on this.

**Comment by klepp0906** [comment] 2020-05-27 01:01
ah, just noticed your on amd and im on nvidia.   not vendor specific then.  not api specific.

**Comment by Megamouse** [comment] 2020-05-27 09:20
Sorry but I cannot reproduce this in any way. The game works as expected no matter how I start it.

What's the exact command that you use?

**Comment by klepp0906** [comment] 2020-05-27 09:48
> Sorry but I cannot reproduce this in any way. The game works as expected no matter how I start it.
> 
> What's the exact command that you use?

I'm using rpcs3.exe --no-gui "G:\Games\Consoles\Sony - PlayStation 3\BLUS30947\PS3_GAME\USRDIR\EBOOT.BIN"

No way as a developer to guess what could cause the different behavior based on launching via a double click within rpcs3 vs omitting that portion?  

youre testing on windows (unsure if rpcs3 has osx or linux builds?)

using 19041/2004 build or?   Unsure if that would have relevance but i know microsoft released wddm 2.7 with it so maybe?

appreciate your time looking into it either way.

**Comment by Megamouse** [comment] 2020-05-27 10:21
I really don't have a clue. Maybe test on another PC to see if it is some strange windows configuration issue on your machine.

**Comment by klepp0906** [comment] 2020-05-27 10:24
yea thats the last ditch effort, moving everything over.  Even though unsure where that would get me, it would at least point to it being config related.  (though ive just dumped my entire drivers and tried with a fresh version at default settings with the same result)

just wasnt sure if there was something obvious in the way it initializes from the GUI vs without the GUI.  Or some step that is skipped when using the GUI vs otherwise.

weiiiiird.

Will certainly post back once i dig up something relevant.  Thank you again.

**Comment by klepp0906** [comment] 2020-05-28 12:58
just as an update (havent had time to test much) to eliminate it being related to fullscreen i immediately windowed it after launching via cmd.

the difference is doing so via cmd line results in the fps bouncing between 22-26 and launching via the gui results in it being locked at 30fps.

so whatever is causing the different behavior between the modes, is effecting frame rate which obviously would affect audio, and apparently  somehow stymies proper rendering as well.

wondering if somehow a different form of buffering or something is being used between the two for some reason.

**Comment by klepp0906** [comment] 2020-05-28 15:45
well.  back from the gym.  transferred my rpcs3 to another pc.  entirely different platform amd instead of intel etc.

identical behavior.

one last thing to test which is going to be a separate rpcs3 install.  If that passes, its something inside the current rpcs3 config/folder.

if it fails - balls back in your court :(

**Comment by klepp0906** [comment] 2020-05-28 16:09
Well, i was really hoping it wasn't the case but even with a brand new fresh RPCS3 it happens.  Two separate machines i'd say thats enough evidence pointing towards it being not config related and something under the hood.

An additional bit of information that will hopefully be helpful.

Lets say I have the game running.  I change it from fullscreen to windowed so i can see the FPS in the titlebar etc.

if i click the X in the top right corner (i didnt notice this on the non-fresh install as i have the confirm dialog disabled) but when the confirm box pops up for closing, it speeds up/stops hitching/audio goes normal for a few seconds.  then it retreats back to its previous behavior.

**Comment by klepp0906** [comment] 2020-05-28 17:40
final test.

did a full clean boot/disabled all non microsoft services through msconfig.  ran through a brand spanking new/clean rpcs3. 

same result.

unless theres something else im overlooking.

taking all suggestions but im going to venture that something in the code surrounding what i noted prior (about how the pop up window returns it to full speed temporarily) has to be it.

I was even willing to entertain it was something with dual monitors, yet the other pc i tried on only has 1 display.

not sure what else to try at this point.

**Comment by klepp0906** [comment] 2020-05-28 18:50
going through the logs without knowing what im looking for, this pops up only in the no-gui variant.  same game.  same everything.  only difference is the launch method.  relevant?

```·W 0:00:09.317665 {cellAudio Thread} cellAudio: Audio backend stopped unexpectedly, likely due to a buffer underrun
·W 0:00:09.528116 {cellAudio Thread} cellAudio: Audio backend stopped unexpectedly, likely due to a buffer underrun```

**Comment by toratora** [comment] 2020-05-28 22:58
I checked this on my setup which is this, latest release as of 05/28/2020:
```
RPCS3 v0.0.10-10435-3df83e03 Alpha | HEAD | Firmware version: 4.84
Intel(R) Core(TM) i7-7700K CPU @ 4.20GHz | 8 Threads | 63.96 GiB RAM | TSC: 4.200GHz | AVX+ | FMA3 | TSX
```

I tested the following from command line and by creating a shortcut.

```
e:\Games\Emulation\rpcs3\rpcs3.exe "N:\PS3\Ni_No_Kuni_Wrath_Of_The_White_Witch\BLUS30947\PS3_GAME\USRDIR\EBOOT.BIN"
```

```
e:\Games\Emulation\rpcs3\rpcs3.exe --no-gui "N:\PS3\Ni_No_Kuni_Wrath_Of_The_White_Witch\BLUS30947\PS3_GAME\USRDIR\EBOOT.BIN"
```

The _only_ difference I noticed was a `~0.5fps` reduction with the `--no-gui` option.  Without that option the game ran at a solid `29.99fps`. With that option the fps dropped down to `29.56`.

No difference in graphics, music, or sounds.

This was without a custom game configuration.

**Comment by klepp0906** [comment] 2020-05-28 23:10
yea, i dont really know what else to even do.  It happens on both my machines.  both with fresh default rpcs3.   I tried a half a dozen nvidia drivers going back months.  

i tried admin and without.  ogl and vulkan.

i tried every single option within rpcs3 toggled this way and that.  

I tried a completely clean boot with nothing but M$ services running.

Are you guys using the new spring/may/2004 windows update?  could that be the difference?  the whole dx12 ultimate/wddm 2.7 thing?  Thats the only similarity between my 2 pc's.  every single piece of hardware in both of them is unique relative to one another.

also tried all nvcp options, forcing triple buffering, forcing vsync on/off.

I can take a vid if it'd be helpful.  Post more logs.  Whatever is needed. 

The one thing i hoped would point towards a potential cause is when i try to close the game window and the "Exit Game? Yes/No" box pops up it instantly speeds up to how it should be, locked at 30fps, audio goes normal - lasts about 5 seconds then fps drops back to bouncing between 25-27 with the audio skipping.

If i leave the exit game window up, and give something else focus aka click on my browser, then click back on the exit game window - it speeds back up to normal again for a few seconds.

repeatable over and over.  Of course  being a user I have no idea what that means outside of some kinda focus issue or something.  Or like a priority issue.  

About to look into if its possible to post a bounty for someone to debug this somehow or something lol.  As i mentioned in the OP i waited a good while for this to go in, and its central to my set-up as i play remotely.   Or had hoped to anyhow : P

**Comment by ZombiJambi** [comment] 2020-05-28 23:49
Ok, so I made a couple videos, using Ni no Kuni.

Ignore the exploding vertices, I'm not sure how to fix them, but the frame pacing issue is still visible.

Pay attention to the street light.

Video using --no-gui, and getting suttering; uneven frame pacing.
https://youtu.be/SUjruUWFpkE

Video not using --no-gui, and you can see it has even frame pacing:
https://youtu.be/t1kLCxubhD4

**Comment by klepp0906** [comment] 2020-05-29 00:08
seems like i simply get some kind of on-steroids version of the above  as i cant even get the games startup screens to show properly.  for example white knight chronicles is just black.   NNK is mostly black as in the OP.

I never thought to even try advancing beyond that point, but your post motivated me to.  I took a few vids as well.   Is that what this is a frame pacing thing?  

Here is the --no-gui version, you can see the fps in the window is stuck in that 25-27 span and you can hear the ghastly audio.   https://www.dropbox.com/s/smhxpm6mxzz0tcp/--no-gui.mkv?dl=0

Here is launched conventionally.  locked at 30fps and runs exactly as youd expect.  https://www.dropbox.com/s/tpvabln78nfvozz/gui.mkv?dl=0

**Comment by ZombiJambi** [comment] 2020-05-29 00:13
Yeah that's way worse than anything I've had to deal with. 

I have an AMD Ryzen 5 1600 and R9 390.

I think this makes it obvious that this is a RPCS3 issue, that just presents itself differently on different hardware. 
I would think the next step is to look at all the things RPCS3 does when it starts up its UI.

**Comment by klepp0906** [comment] 2020-05-29 00:17
the only thing shared between my 2 pc's are the type of monitor, and the make of the gpu.  (and the windows version)

I strongly believe its an rpcs3 issue as well.  Of course i'm willing to do whatever I can to narrow that down to being a certainty if thats what it takes to get it addressed.  having --no-gui is very very important to me lol.  

As for the differences between launching the GUI and not, thats sort of what I was hinting at earlier in the thread.  Unfortunately my development experience begins and ends with rudimentary ahk so i tried smooshing my face against things like resource monitor and procmon but nothing stood out to the layman.

**Comment by Megamouse** [comment] 2020-05-29 06:19
Well. I could reproduce it now and (with opengl) I'm getting like 29.5 fps with --no-gui.
Although I still don't know why this happens.
The only real difference is that the debugger and the log are NOT created. I'll probably have to test what happens if I never create them with the GUI

**Comment by klepp0906** [comment] 2020-05-29 10:41
> Well. I could reproduce it now and (with opengl) I'm getting like 29.5 fps with --no-gui.
> Although I still don't know why this happens.
> The only real difference is that the debugger and the log are NOT created. I'll probably have to test what happens if I never create them with the GUI

Thats great news you can reproduce it.  Odd that it effects me to a more severe degree by several orders of magnitude.

If it were worse on my older pc, id understand.  But my newer/higher end pc still gets the behavior so go figure.

If you'd like more up to date logs to peruse from a clean/fresh/default rcps3 install - or anything like that, just let me know.   (or anything else i can help with testing/debugging wise)

**Comment by klepp0906** [comment] 2020-06-28 23:41
ever end up with the time to look into this a bit yet?

please dont take this as impatience, as i sincerely appreciate all you guys do.   After all, rpcs3 command line or no command line wouldnt exist without you :)

I just want to stay on top of it and i figured since its been about a month,  i'd feel marginally less douche'y "bumping the post" so to speak.

**Comment by SuperOkazaki** [comment] 2020-08-17 18:53
@klepp0906, I unknowingly made a duplicate issue report about the same symptoms. Very odd indeed. Clean Windows, clean drivers, same issue. Hopefully a resolution of this issue comes at some point.

**Comment by Jayinem** [comment] 2020-09-05 17:40
I have the same problem.

Processor	Intel(R) Core(TM) i5-9300H CPU @ 2.40GHz, 2400 Mhz, (can go up to 4.1GHz) 4 Core(s), 8 Logical Processor(s)
Nvidia GTEForce GTX 1650 1650 RAM

I was running the script perfectly fine then tried --no-gui and it stutters and skips music. Removed it again and it's back to normal. So it only happens with --no-gui in the script. Tried with 3 different games.

**Comment by klepp0906** [comment] 2020-09-07 19:03
yea ive been updating religiously and re-trying over time hoping it would get inadvertently fixed.  No such luck.

The label on the issue is "Need More Information" which might be deterring people from looking at it?  Would be great if someone with the ability to do so could remove that label, unless of course more information IS needed?

**Comment by SuperOkazaki** [comment] 2020-09-07 19:07
Agreed, I fail to see what more information is needed. About a month ago, I posted an issue outlining the same thing, with images, logs, and system specs. It was closed and I was redirected to this thread.
https://github.com/RPCS3/rpcs3/issues/8744
I would be chuffed to find out what information, exactly, is needed. Perhaps a contributor can enlighten us?

**Comment by Jayinem** [comment] 2020-09-08 04:08
> Agreed, I fail to see what more information is needed. About a month ago, I posted an issue outlining the same thing, with images, logs, and system specs. It was closed and I was redirected to this thread.
> #8744
> I would be chuffed to find out what information, exactly, is needed. Perhaps a contributor can enlighten us?

They probably don't see it as very important, because it's not a necessity to run the game without the GUI. Especially when over half the games for PS3 still don't even work.

**Comment by Megamouse** [comment] 2020-09-22 21:45
Does anyone have this issue on a linux system?

**Comment by kd-11** [comment] 2020-09-22 21:49
Results on archlinux show no difference between no-gui and normal CLI operation under both Vulkan and OpenGL. Performance is smooth and all visuals are working fine, making this likely another windows-only issue.

**Comment by Megamouse** [comment] 2020-09-22 21:52
For the record:
With GUI:
![image](https://user-images.githubusercontent.com/23019877/93941341-87fc4000-fd2e-11ea-96c9-607a8ab9f3fa.png)

Without:
![image](https://user-images.githubusercontent.com/23019877/93941375-9b0f1000-fd2e-11ea-9567-2519b31bde40.png)

**Comment by klepp0906** [comment] 2020-09-24 17:23
looks to be related to frametime eh?  wonder why im effected so much more severely than you are.  you dip to 29.55 i dip to like 25-27fps and it causes all kinds of anomalies as per the OP.

gonna have to try and find out what/where i can get that gamepad test thing to do some comparisons of my own.

**Comment by SuperOkazaki** [comment] 2020-09-24 17:26
Yep, it's super severe for me too. My framerate basically _halves_ when running a game with the `--no-gui` flag. If there is any additional testing I can do to help nail down the problem, let me know and I can help.

**Comment by klepp0906** [comment] 2020-10-26 23:59
any changes on this guy?  anyone have any luck with a workaround or anything?  Since its a windows only issue i tried mucking around with hardware gpu scheduling but that was a wash :(

**Comment by mattsoft** [comment] 2021-01-02 00:54
Same issue on my Win10/64 i5/GTX 1070 emulation rig. RPCS3 launched with --no-gui is unplayable. Without that flag, RPCS3 works great.

**Comment by pcone** [comment] 2021-03-03 05:04
I'm reproing this too in Demon's Souls and it's pretty noticeable because the audio skips when launching with --no-gui.

Running a Ryzen 3600 and a 6800xt on the Vulkan renderer.

**Comment by pcone** [comment] 2021-03-03 05:12
The settings.reset() stuff that @sampletext32 posted looks pretty suspicious to me, anyone know why that's happening?

**Comment by klepp0906** [comment] 2021-03-03 10:54
> I'm also running a freesync display. Has anyone reprod this that _isn't_ using freesync/gsync?

No free/gsync here.

coming up on a year of this being broken though.  has kept me from playing remotely for a long time now.

**Comment by Nekotekina** [comment] 2021-03-19 20:29
The issue is most likely fixed, the PR #9988 is merged. I'll wait for more testing before closing this.

**Comment by klepp0906** [comment] 2021-03-19 21:29
something something worth having, something something worth waiting for.

seems you guys did it.  works perfectly here.  I feel like saying thank you is entirely inadequate, but its the best i have.  if the countless hours i'll now be able to blissfully enjoy from any room in my house (along with my kids) are any consolation <3

**Comment by Megamouse** [comment] 2021-03-19 21:59
Turns out all we needed to do was to randomly mention the problem to the right person 😅

**Closed by Megamouse** 2021-03-19 21:59 UTC
Labels: CLI, OS: Windows

**Comment by Ohio5plus1** [comment] 2021-07-22 02:44
@klepp0906 how do I stop using --no-gui on rpcs3? (I just got rpcs3 and had this problem with NCAA FOOTBALL 14 but I've seen videos where they had the game run just fine and normal

**Comment by MSuih** [comment] 2021-07-22 03:12
No-GUI mode (RPCS3 interface isn't visible at all) isn't something that you can just accidentally use. Your issue is probably unrelated to this. Visit our Discord server to get help with improving performance.
