### ISSUE TITLE
Deadstorm Pirates:  Enemies have transparency issues

### ISSUE THREAD

**Issue by legend800** [RPCS3/rpcs3#5567] opened 2019-01-17 02:55 UTC
Some enemies have transparency issues.  ~70% are fine, but others (same models, maybe distance related?) only partially appear. 

![2019-01-16 18_47_57-window](https://user-images.githubusercontent.com/20983844/51292555-092efb80-19c0-11e9-8c46-4178a879ebd3.png)

![2019-01-16 18_48_35-fps_ 59 95 _ vulkan _ 0 0 5-b96edb69-kd-11_master _ time crisis_ razing storm b](https://user-images.githubusercontent.com/20983844/51292556-092efb80-19c0-11e9-86f6-d72ccd71935a.png)

[BLUS30528_20190116184859_capture.zip](https://github.com/RPCS3/rpcs3/files/2766973/BLUS30528_20190116184859_capture.zip)

[RPCS3.log.gz](https://github.com/RPCS3/rpcs3/files/2766972/RPCS3.log.gz)

Config:
Windows 10 64-bit
GeForce GTX 1080
i7-6700k @ 4GHZ
16GB RAM

**Comment by kd-11** [comment] 2019-01-17 12:17
Comparison screenshots vs real PS3 will be needed here. I have no idea what the problem is from the provided screenshots.

**Comment by legend800** [comment] 2019-01-17 16:34
Here's a pic of real PS3:
![2019-01-17 08_32_54-window](https://user-images.githubusercontent.com/20983844/51333457-96129d00-1a32-11e9-9269-3c5318ddbd0c.png)

The enemies (skeletons) should not be transparent or have black spots, etc.

Thanks for checking this out!

**Comment by kd-11** [comment] 2019-01-17 16:52
Does it look any different with https://github.com/RPCS3/rpcs3/pull/5565

**Comment by legend800** [comment] 2019-01-17 16:57
Sorry, no. Looks to be the same on latest commit. Thanks for trying!

![2019-01-17 08_55_19-window](https://user-images.githubusercontent.com/20983844/51334983-d1629b00-1a35-11e9-84e2-139d3889f396.png)

![2019-01-17 08_55_32-window](https://user-images.githubusercontent.com/20983844/51334984-d1629b00-1a35-11e9-884a-4afb8829bf76.png)

**Comment by Emulator-Team-2** [comment] 2019-01-17 19:32
**[Nvidia]**
![bez tytulu1](https://user-images.githubusercontent.com/38318848/51343027-adcf3d00-1a95-11e9-9110-1df825e79d78.png)
[RSX Capture-Nvidia](https://mega.nz/#!1YJ20AzK!lO38pL6f55Ou9h7qWJwGanqRL5dJfZ5pD00LpeCO9_Q)

**[AMD]**
![bez tytulu2](https://user-images.githubusercontent.com/38318848/51343141-f71f8c80-1a95-11e9-82f4-4d030d9d00e3.png)
[RSX Capture-AMD](https://mega.nz/#!JIRg3azR!R0UNop_d5Rxm-rfWqnbcG5TlpphhXjzzMSh946B9SeU)

**Comment by legend800** [comment] 2019-01-17 19:43
Interesting. As you pointed out Ridge Racer 7 has probably the same issue - flickering/transparency issues ONLY on Nvidia. 

https://github.com/RPCS3/rpcs3/issues/5343

Note, this is the only remaining issue for both titles. Once fixed, every aspect of these games would be perfect (perf, stability, audio, gfx, etc.)

**Comment by kd-11** [comment] 2019-04-18 14:06
Retest with https://github.com/RPCS3/rpcs3/pull/5860

**Comment by Emulator-Team-2** [comment] 2019-04-18 15:07
Fixed by #5860

**Comment by legend800** [comment] 2019-04-18 15:32
Confirmed, thanks so much kd-11! I'll close once in master.

![2019-04-18 08_31_09-Window](https://user-images.githubusercontent.com/20983844/56372781-85e69700-61b4-11e9-9ae8-0c20afdb7930.png)

**Comment by kd-11** [comment] 2019-04-25 13:47
Fixed by https://github.com/RPCS3/rpcs3/pull/5860

**Closed by kd-11** 2019-04-25 13:47 UTC
Labels: Driver: NVIDIA

**Comment by Sairan305** [comment] 2022-08-25 07:37
> It seems that, it's only a problem on Nvidia graphics cards.
> 
> **[Nvidia]** ![bez tytulu1](https://user-images.githubusercontent.com/38318848/51343027-adcf3d00-1a95-11e9-9110-1df825e79d78.png) RSX Capture: -(Deleted).
> 
> **[AMD]** ![bez tytulu2](https://user-images.githubusercontent.com/38318848/51343141-f71f8c80-1a95-11e9-82f4-4d030d9d00e3.png) RSX Capture: -(Deleted).

i have AMD card and i have this problem (Only eyes and weapons but no enemy but when enemy close to me i can enemy)
