### ISSUE TITLE
coop user account issue

### ISSUE THREAD

**Issue by Ilovelbpcoopbutcantsaveplayertwoimsad** [RPCS3/rpcs3#8510] opened 2020-06-26 23:33 UTC
## Quick summary
When playing a game using the user accounts tab I am unable to have two signed in at once, I'm unsure whether this is a bug or a feature that hasn't been added, but I would love to be able to sign in two accounts and play together with separate saved data.

## Details
When I make two accounts I load up lbp 1 and get both characters in, but only my user will save data from our adventures, any outfits my p2 saves will be gone upon closing the game. I tried logging in the second user while in game, but for whatever reason the option is greyed out the moment I start the game. I'm sure this is either for a technical reason or something that was easily looked over in the development for the user account feature.

I have seen that other users reported the same issue with some other coop games and someone said that the controller presets are the same as making separate users, but that isn't the case because I have made two presets for the controllers as well and the p2 is still viewed as guest

# Screenshot
![image](https://user-images.githubusercontent.com/67487602/85908641-7f51a780-b7db-11ea-8968-222f423d3efc.png)

**Comment by Megamouse** [comment] 2020-06-28 12:25
duplicate of #8472

**Closed by Megamouse** 2020-06-28 12:25 UTC

**Comment by LoganRicardo** [comment] 2023-02-26 06:20
> duplicate of #8472

How can I implement this on my emulator? I don't understand
