### ISSUE TITLE
Can't open rpcs3 anymore after r6697-753d8170

### ISSUE THREAD

**Issue by Jorerim** [RPCS3/rpcs3#4735] opened 2018-06-10 21:09 UTC
I have RPCS3 on a network drive shared through SMB. I tested with a lot of different compiled versions and the last that works is r6697-753d8170. With version r6718-737db900 and up, the process rpcs3.exe shows in task manager but doesn't load the GUI. Win10 v1803, Nvidia 398.11 driver and VulkanRT 1.1.73.0 installed. Tried r6817-b7728926 and nothing through SMB. but if I extract r6817-b7728926 to a USB drive it opens fine! There is no entry inside "HKEY_LOCAL_MACHINE\SOFTWARE\Khronos\Vulkan\Drivers"

**Comment by Megamouse** [comment] 2018-06-10 21:16
https://github.com/RPCS3/rpcs3/issues/4625

**Comment by AniLeo** [comment] 2018-06-10 22:19
Closing as duplicate of #4625

**Closed by AniLeo** 2018-06-10 22:19 UTC
