### ISSUE TITLE
GUI is messed up

### ISSUE THREAD

**Issue by rtentser** [RPCS3/rpcs3#8323] opened 2020-06-02 10:03 UTC
![rpcs3](https://user-images.githubusercontent.com/34958119/83507270-880fd000-a4f2-11ea-9dbc-2b1bdf2f1b8e.png)
I can workaround it with `QT_AUTO_SCREEN_SCALE_FACTOR=0`
I use lxqt on arch linux. Latest rpcs3 git.
There is [similar bug](https://github.com/qbittorrent/qBittorrent/issues/12441) in qbittorrent, i've found a workaround there. Maybe it'll help.

**Comment by lextra2** [comment] 2020-06-02 10:36
duplicate of #7772 & #8052
Your workaround is the correct fix

**Closed** 2020-07-18 09:55 UTC
Labels: Meta: Duplicate
