### ISSUE TITLE
rsx: Red Dead Redemption - excessively bright street lamps

### ISSUE THREAD

**Issue by Raijin56** [RPCS3/rpcs3#7812] opened 2020-03-20 22:38 UTC
## Quick summary
Hi,
This is with Read Dead Redemption: Game of the Year Edition (BLES01294).

The street lamps look overly bright. Here are some screenshots comparing RPCS3 0.0.9-9960-c577bd21 Alpha with another Xbox 360 emulator:
This behaviour appears to occur when the lights are relatively distant.
Pic 1
RPCS3:
<img width="960" alt="1 RPCS3" src="https://user-images.githubusercontent.com/1304436/77210946-91e48280-6b02-11ea-94e2-4a97f090bfe1.png">

X360:
![1 X360](https://user-images.githubusercontent.com/1304436/77210953-95780980-6b02-11ea-899c-5acd9f27c333.png)

Pic 2
RPCS3:
<img width="960" alt="2 RPCS3" src="https://user-images.githubusercontent.com/1304436/77210961-9a3cbd80-6b02-11ea-8437-eadca41fa104.png">

X360:
![2 X360](https://user-images.githubusercontent.com/1304436/77210966-9dd04480-6b02-11ea-9388-38b1e042c338.png)

But when the character is under the lights, they seem to be correct, except the distant ones:
RPCS3:
<img width="960" alt="3 RPCS3" src="https://user-images.githubusercontent.com/1304436/77211075-fef81800-6b02-11ea-9ba1-72d2e1ce34b5.png">

X360:
![3 X360](https://user-images.githubusercontent.com/1304436/77211079-03bccc00-6b03-11ea-94cb-90866759d2a5.png)

Sorry for not getting the screenshots in the same weather, the difference is noticeable anyway.

The "Write color buffers" option is on so it's not related to this issue, without it enabled the night looks like a concert.

Windows 10 (10.0.18363)
Intel Core i9-9900K
Nvidia RTX 2080 (drivers 442.50)

[RPCS3.log.gz](https://github.com/RPCS3/rpcs3/files/4362028/RPCS3.log.gz)

**Comment by AniLeo** [comment] 2020-03-20 23:17
RPCS3 is not an Xbox 360 emulator. You're not comparing the same game, you're comparing a PS3 game with a Xbox 360 game, and the Xbox360 port is known to be very different.

**Comment by Raijin56** [comment] 2020-03-20 23:41
@AniLeo 
Here you have some screenshot of a YouTube video made in the original PS3.

![Captura de pantalla (1194)](https://user-images.githubusercontent.com/1304436/77213799-77170b80-6b0c-11ea-872f-d01db6cc121b.png)
![Captura de pantalla (1195)](https://user-images.githubusercontent.com/1304436/77213800-77afa200-6b0c-11ea-9e41-8e04e87bf089.png)
![Captura de pantalla (1196)](https://user-images.githubusercontent.com/1304436/77213801-78483880-6b0c-11ea-9f6f-c326ce25972d.png)
![Captura de pantalla (1193)](https://user-images.githubusercontent.com/1304436/77213802-7aaa9280-6b0c-11ea-9ede-e1b57fc7b691.png)

**Comment by AniLeo** [comment] 2020-03-20 23:44
If it doesn't happen on a PS3, then it should be an issue

An RSX capture of a frame with distant lighting is needed, or/and just post savedata for the game with easy access to that part

**Comment by Raijin56** [comment] 2020-03-21 01:13
Lol, I wrote Read Dead Redemption and I can't blame the corrector.

I tested different settings. The glitch happens when using Vulkan. I tried to test with OpenGL but the world becomes yellow and pink, not very appropriate for a West game. I also tried "Accurate xfloat", but that only decreases performance in this case.
With PPU Decoder set to "Interpreter (precise)" the game starts but the glitch continues. With SPU Decoder set to "Interpreter (precise)" the game doesn't start and gives 16 exceptions, one for each SPU Worker, so I set it up to "Interpreter (fast)" and "ASMJIT Recompiler (faster)", with unfortunately no solution for the street lamps' light.

- Here you have the RSX capture:
https://mega.nz/#!gxZBjSgQ!s-oprfjhbHbW5igUMyeeRy5moGHf845lXgV3tiGKlcs
- And a savegame in the night and in the same place, MacFarlane's Ranch:
https://mega.nz/#!YpRgAAja!98ulR_L7kVvkRe-dJ5KCpv2VRgbTJSnhe0Tt00pcBq8

The serial of the game is the BLES01294.

Thank you very much!

Also, there's some minimally possibly related glitch. If you run outside and around some houses that have lights inside that are displayed through the windows, they sometimes blink. You can see that in the houses that are around the bonfire that is just going out of the house, to the left, after loading the savegame.

**Comment by Yahfz** [comment] 2020-03-21 01:42
The blinking windows issue and many others are caused by relaxed zcull. Can you check if the lamps light works properly without it?

**Comment by Raijin56** [comment] 2020-03-21 01:53
Hi. I didn't have that option turned on. Anyway, I have tried to activate it to see if it solved something, but the lights are seen at the same high intensity with Relaxed ZCULL Sync being on or off, also it didn't resolve the blinking windows issue. Thank you for the suggestion.

**Comment by avindra** [comment] 2020-05-23 15:08
Here is what it looks like on my system:

![2020-05-23_11-03](https://user-images.githubusercontent.com/126848/82733911-3a6eb880-9ce5-11ea-9fc6-a81454daa95e.png)

@Raijin56 mentioned that the lighting is correct when the player is under the light source, but I don't see this happening in my test:

![under](https://user-images.githubusercontent.com/126848/82733939-6d18b100-9ce5-11ea-9173-73a4599e1709.png)

**Comment by Raijin56** [comment] 2020-05-23 22:31
Hey @avindra. Thanks for testing. Yes, I think the effect is worst occasionally, so sometimes it looks so bad.

**Comment by Kingo64** [comment] 2020-05-24 11:45
@avindra That overly bright lighting issue is caused by having 'Write Color Buffers' disabled. Make sure you switch it on. However, the bright street lamps are still unresolved currently.

**Comment by avindra** [comment] 2020-05-27 03:08
@Kingo64  good call, when I enable `Write Color Buffers`, I get a similar result to @Raijin56 

![2020-05-26_23-08](https://user-images.githubusercontent.com/126848/82973568-cadb2080-9fa5-11ea-9eda-065ebe1bc7d4.png)

**Comment by jeremybris** [comment] 2020-06-06 20:32
Is this fixed with #8367 ?

**Comment by MarioSonic2987** [comment] 2020-06-06 20:40
I think it is. I'll test master soon.
![image](https://user-images.githubusercontent.com/20027681/83954117-96d5ea00-a846-11ea-9b1a-4cb795bae436.png)

**Comment by jeremybris** [comment] 2020-06-06 20:51
Seems fixed, but the game still has a bloom issue for me, similar to #8122 . That is another issue.

Before:
![Capture6468](https://user-images.githubusercontent.com/11889359/83954277-d89a6c80-a815-11ea-9efa-d25528554d33.PNG)

After:
![Capture567](https://user-images.githubusercontent.com/11889359/83954280-dcc68a00-a815-11ea-8e5a-b039bf477c63.PNG)

**Comment by MarioSonic2987** [comment] 2020-06-06 20:53
@jeremybris Enable Write Color Buffers to fix broken lighting in night-time.

**Comment by jeremybris** [comment] 2020-06-06 20:55
> @jeremybris Enable Write Color Buffers to fix broken lighting in night-time.

Thanks, that worked, I didn't read any of the previous comments. My bad.

**Closed** 2020-06-07 09:07 UTC
Labels: Bug, RSX

**Comment by Raijin56** [comment] 2020-06-07 15:08
Now the lights are shown as it should be. Thanks for your amazing work!

<img width="960" alt="Base Profile Screenshot 2020 06 07 - 15 18 53 05" src="https://user-images.githubusercontent.com/1304436/83972609-67c08680-a8e1-11ea-9810-29cb13dd6555.png">
