### ISSUE TITLE
Issue Installing MGS4 -v0.0.7-8642-aaae437c

### ISSUE THREAD

**Issue by starlink89** [RPCS3/rpcs3#6486] opened 2019-09-06 00:51 UTC

**Comment by mark007** [comment] 2019-09-29 00:01
Looks the same as https://github.com/RPCS3/rpcs3/issues/6457

**Comment by HHCHunter** [comment] 2019-10-13 10:33
@AniLeo dupe of #6457 which is resolved, pls close.

**Closed** 2019-10-18 11:05 UTC
