### ISSUE TITLE
Star Ocean 5 - Integrity And Faithlessness BLJM61325 Game wont start no matter what

### ISSUE THREAD

**Issue by AntiGrieferGames** [RPCS3/rpcs3#14644] opened 2023-09-13 18:22 UTC
### Quick summary

Make the Game Compatbiliy Status from "Ingame" into "Loadable"

When i running that game, it wont start no matter what! It even wont stopping so i had to force close using task manager!

The logs says after triying start

U sys_prx TODO: _sys_prx_get_module_id_by_name(name=“cellLibprof”, flags=0, pOpt=*0x0)
E SYS: '_sys_prx_load_module' failed with 0x80010006 : CELL_ENOENT, /dev_bdvd/PS3_GAME/USRDIR/sprx/Izumo.sprx [1]
E SYS: 'sys_ppu_thread_join' failed with 0x80010005 : CELL_ESRCH [1]
F {PPU[0x1000000] Thread (main_thread) [0x00016700]} VM: Access violation reading location 0x0 (unmapped memory)

### Attach a log file

[RPCS3.log](https://github.com/RPCS3/rpcs3/files/12600736/RPCS3.log)

**Comment by Megamouse** [comment] 2023-09-16 07:33
Does the game contain this file?
`/PS3_GAME/USRDIR/sprx/Izumo.sprx`
It may be written in lowercase, so: `izumo.sprx`

**Comment by tedios** [comment] 2023-09-22 17:28
Yep, same random crash with access memory violations, only fix so far is clearing memory via RAMMap,

> Does the game contain this file? `/PS3_GAME/USRDIR/sprx/Izumo.sprx` It may be written in lowercase, so: `izumo.sprx`

Yes it does have it.

**Comment by Megamouse** [comment] 2023-09-22 22:03
lowercase or uppercase?

**Comment by tedios** [comment] 2023-09-24 16:34
> lowercase or uppercase?

Uppercase "Izumo.sprx"

**Comment by AniLeo** [comment] 2023-11-11 23:40
Duplicate of #6825

**Closed by AniLeo** 2023-11-11 23:40 UTC
