### ISSUE TITLE
Regression: Final Fantasy XIII series stopped working

### ISSUE THREAD

**Issue by GitArUs** [RPCS3/rpcs3#9406] opened 2020-12-10 18:56 UTC
Since commit 36c8654f FFXIII, FFXIII-2 and Lightning Returns show only black screen after Square logo. Log file is spammed with one line until emulation is stopped:

`·W 0:00:31.530626 {SPU[0x0000200] Thread (SystemSpursCellSpursKernel0) [0x0a898]} SPU: sys_spu_thread_send_event(spup=1, data0=0x0, data1=0x1fa80): error (CELL_ENOTCONN)
`

OS: Linux
Self-compiled executable and appimage behave the same way. 

Last good version: d25c401a
First bad version: 36c8654f

Log file: 
[RPCS3.log.gz](https://github.com/RPCS3/rpcs3/files/5674937/RPCS3.log.gz)

Other games (at least Unnamed) work.

**Comment by kd-11** [comment] 2020-12-10 20:24
Duplicate of https://github.com/RPCS3/rpcs3/issues/9410

**Closed by kd-11** 2020-12-10 20:24 UTC
