### ISSUE TITLE
[Regression]Killzone 3 black screen in menu

### ISSUE THREAD

**Issue by davewuk** [RPCS3/rpcs3#9014] opened 2020-10-02 07:41 UTC
After PR #8984 the menus in Killzone 3 (BCES01007/BCUS98234) are no longer rendered correctly and appear blank. The menus can be interacted with and it is still possible to go in-game but they appear as a black screen. The in game pause menu is also affected.

![Image1](https://user-images.githubusercontent.com/55807111/94899281-ed68d300-048a-11eb-97d2-e6d806e678f5.png)

rpcs3-v0.0.12-10950-264df111_win64 is the last working build
[RPCS3-10950.zip](https://github.com/RPCS3/rpcs3/files/5316509/RPCS3-10950.zip)

rpcs3-v0.0.12-10953-9baef8c7_win64 is the build where the problem first appeared
[RPCS3-10953.zip](https://github.com/RPCS3/rpcs3/files/5316513/RPCS3-10953.zip)

**System specs**
i5 6600k oc'd to 4.5ghz
Nvidia GTX 970 with latest drivers
16gb RAM
Windows 10 Pro

**Comment by AniLeo** [comment] 2020-10-02 07:44
> ·! 0:00:00.033842 RSX: Found vulkan-compatible GPU: 'GeForce GTX 970' running on driver 452.6.0.0

Not latest drivers.

**Comment by AniLeo** [comment] 2020-10-02 07:45
Duplicate of #9006

**Closed by AniLeo** 2020-10-02 07:44 UTC

**Comment by davewuk** [comment] 2020-10-02 07:48
OK will check with latest *latest* drivers...
