### ISSUE TITLE
IDOLM@STER OFA Quintet lives slow down FPS

### ISSUE THREAD

**Issue by OmnomP** [RPCS3/rpcs3#8087] opened 2020-04-24 01:55 UTC
So i cannot play quintet lives properly because it drops FPS to 50 but on Trio/Duo/Solo it runs fine at 60. Also, it causes audio jitters, so i cannot enjoy quintet MVs either, so i feel limited to playing the game.  

RPCS 0.0.8-9581-93344b214 Alpha
Vulkan | 0.0.8-9581 | アイドルマスター ワンフォーオール [NPJB00611]

Windows 10 Pro 64-bit (10.0, Build 18363)
AMD Ryzen 5 2600 Six-Core Processor (12 CPUs, ~3.4 Ghz)
NVIDIA GeForce GTX 1660

**Comment by RainbowCookie32** [comment] 2020-04-24 03:12
> RPCS3 0.0.8-9581-93344b214 Alpha
Please update to the latest build when opening issues. 

Also, we don't have issues for overall low performance. They should only be opened when it's caused by a regression, otherwise we'd have a lot of extra issues for a lot of games.

**Comment by OmnomP** [comment] 2020-04-24 03:15
I wont lose my save files if i use the latest build?

**Comment by RainbowCookie32** [comment] 2020-04-24 03:16
No

**Comment by OmnomP** [comment] 2020-04-24 03:39
Well, I updated RPCS3 now, but now im having audio jitters but animations are running smoothly now at 60 FPS

**Comment by RainbowCookie32** [comment] 2020-04-24 03:43
Sounds more like a case for [Discord support ](https://discord.me/RPCS3) than an issue then. As I said before, we don't open issues for low performance unless it's a regression.

**Comment by AniLeo** [comment] 2020-04-24 16:15
---

**Please read [**the guidelines**](https://github.com/RPCS3/rpcs3/blob/master/.github/CONTRIBUTING.md) before opening an issue.**

Remember that the GitHub Issue Tracker is not the place to [**ask for support**](https://github.com/RPCS3/rpcs3/wiki/How-to-ask-for-Support) or to [**submit Game Compatibility reports**](https://github.com/RPCS3/rpcs3/wiki/Game-Compatibility).

The issue has been marked as **Invalid** and closed.

**Closed by AniLeo** 2020-04-24 16:15 UTC
