### ISSUE TITLE
New Idea to Settle the DirectX 12 Debate

### ISSUE THREAD

**Issue by niko1point0** [RPCS3/rpcs3#5064] opened 2018-08-31 01:18 UTC
Many people have different opinions, whether we should keep DirectX 12 support, or trash it. Here is an idea that maybe we can all agree on

In the Visual Studio project (and cmake, and everything else), let's put a boolean;

Setting this boolean to false, will ignore the Dx12 code, not compile it, and then this particular RPCS3 build will not support Dx12 in any way

Setting this boolean to true, will compile the Dx12 code, along with GL and VK, and then this particular RPCS3 build will support Dx12, equally as well as it does now

As a result, people who are not working on Dx12 (I assume the majority of the RPCS3 Team) will not have Dx12 in their way, and in the future, if somebody wants to go back and fix the Dx12 code, it will be there in the background, ready for programmers to return, and finish what was started

**Comment by niko1point0** [comment] 2018-08-31 01:31
The other forum was two weeks old. Besides, this is only ONE additional issue, spamming would be more like 10 issues.

Personally, I would like it if Dx12 were removed. However, then other people would disagree and not want it to be removed. This idea is supposed to resolve the conflict in a way that EVERYONE can agree on. It's only a suggestion

**Comment by Relsig** [comment] 2018-08-31 01:32
Duplicate of #5000 also I've personally said the same thing as ruipin because for all intents and purposes it is the best option. People are arguing points because they think they have one, but they don't. Removing the code from the current build doesn't magically delete git's history. This should be closed, as should the other one tbh.

**Comment by niko1point0** [comment] 2018-08-31 01:34
That's a good point, I completely forgot about git's history. We can remove Dx12 support, then go right back to the previous builds. Good idea. The other forum should be closed because it is long, and nobody wants to put in the time to read it all. I hope this one stays open so that RPCS3 Team sees the it, without having to read 6 pages of opinions

**Comment by ruipin** [comment] 2018-08-31 01:35
If you're adding information to an issue, it doesn't matter that it's a 2 weeks or 2 months old issue - opening new issues just spams the issue tracker and annoys people who have to actually use it.

To be honest, it doesn't really matter if people don't want Dx12 to go. As long as nobody steps up to maintain it, it's dead code, and liable to be removed if the project leads want to. Anyone who disagrees needs to either volunteer to maintain it, find someone to do it, or just live with the decision.

**Closed** 2018-08-31 01:36 UTC
