### ISSUE TITLE
Long loading time in Project DIVA F

### ISSUE THREAD

**Issue by spiraluc** [RPCS3/rpcs3#10418] opened 2021-06-07 19:47 UTC
After pressing the PLAY button I have to wait about 12 seconds before I get to the song list. I have to wait the same time when I come back to song list after the song is finished. But in the old build (0.0.6-8119) I wait only about 1 second.

I tried different settings, but nothing helped. I don't know which build exactly caused it, but build 0.0.12-10950 have same problem.

CPU: i5 2430M
GPU: NVIDIA GT525M (openGL only)
RAM: 8GB
[RPCS3 0.0.6-8119.log](https://github.com/RPCS3/rpcs3/files/6611580/RPCS3.0.0.6-8119.log)
[RPCS3 0.0.16-12375.log](https://github.com/RPCS3/rpcs3/files/6611581/RPCS3.0.0.16-12375.log)

**Comment by AniLeo** [comment] 2021-06-07 19:51
This is below minimum requirements (no OpenGL 4.3)

**Comment by spiraluc** [comment] 2021-06-07 19:52
OpenGL 4.6 is supported on this GPU

**Comment by AniLeo** [comment] 2021-06-07 19:53
Yeah, wrong one, it supports OpenGL 4.3 but with old drivers
Could be solvable

**Comment by Megamouse** [comment] 2021-12-23 11:15
Cannot reproduce

**Comment by Megamouse** [comment] 2022-04-21 20:52
It looks like the "slow" loading times are caused by spu compilation, which is missing from the old log.
Closing, assuming that the combination of low end mobile CPU and SPU comp is at fault.

**Closed by Megamouse** 2022-04-21 20:52 UTC
Labels: Need Information, Potato
