### ISSUE TITLE
Save State Loading since #13172 broken (0.0.26-14527), Crash "Scanning PPU Modules"

### ISSUE THREAD

**Issue by svensvond** [RPCS3/rpcs3#13212] opened 2023-01-11 16:35 UTC
### Quick summary

Cant resume save-state.
Games tested: 
- Borderlands BLUS30386 V1.07
- Ridge Racer Unbounded BLES01341 V1.02

### Details

RPCS3 hangs on "Scanning PPU modules" - 0% progress, crash.

### Attach a log file

[RPCS3.log](https://github.com/RPCS3/rpcs3/files/10394263/RPCS3.log)

### System configuration

Intel(R) Core(TM) i7-8750H CPU @ 2.20GHz | 12 Threads | 15.92 GiB RAM | TSC: 2.208GHz | AVX+ | FMA3
Operating system: Windows, Major: 10, Minor: 0, Build: 19043, Service Pack: none, Compatibility mode: 0
vulkan-compatible GPU: 'NVIDIA GeForce RTX 2060' running on driver 528.2.0.0

### Other details

issue already posted #13204

**Comment by Megamouse** [comment] 2023-01-11 18:09
duplicate of #13204

**Closed by Megamouse** 2023-01-11 18:09 UTC
