### ISSUE TITLE
Sonic 2006 issue

### ISSUE THREAD

**Issue by RenegadeSaiyan** [RPCS3/rpcs3#1189] opened 2015-08-17 23:31 UTC
![image](https://cloud.githubusercontent.com/assets/13460618/9318896/83f45d6a-4516-11e5-83e8-9a9cd6101e5d.png)

**Comment by RenegadeSaiyan** [comment] 2015-08-17 23:31
This is a problem since it almost ran on the older builds but I don't know how to fix this issue in the newer builds.

**Comment by kacek** [comment] 2015-08-18 07:52
which settings are you using?

**Comment by RenegadeSaiyan** [comment] 2015-08-18 09:43
PPU Interperter and SPU Interperter

**Comment by kacek** [comment] 2015-08-18 10:10
have you tried recompilers?

**Comment by RenegadeSaiyan** [comment] 2015-08-18 12:37
How would I go about doing that?

**Comment by RenegadeSaiyan** [comment] 2015-08-18 12:56
EDIT: I tried recompliers didn't work

**Comment by kacek** [comment] 2015-08-18 15:46
Just select that it settings, names contains "JIT", there are also 2nd interpreters.

**Comment by tambry** [comment] 2015-08-18 19:10
@kacek If the game doesn't run with Interpreters, it's a lot more likely to not work with the recompilers/JITs. Recompiler is much more inaccurate currently and shouldn't be used for reference. Same goes for graphics backends, currently OpenGL should be slightly better in compatibility (on AMD cards especially), but DirectX12 will most likely surpass it soon. That function is throwing an exception, since it's not implemented and wasn't encountered often. I implemented the given function on my branch a couple days ago.

**Comment by kacek** [comment] 2015-08-19 16:44
So either @RenegadeSaiyan will post full log (use pastebin for that) and we can mark this issue as regression, or we can close it for lack of informations.

**Comment by tambry** [comment] 2015-08-19 18:14
@kacek The given function has been implemented here: https://github.com/tambry/rpcs3/commit/3e6ad53d151c2f2149e7d623cee1de483b21fdb1

**Comment by vgturtle127** [comment] 2015-09-22 05:17
"Sonic 2006 issues"

nopenopenopenopenopenopenopenopenopenopenopenopenopenopenopenopenopenopenopenopenopenopenopenopenopenopenopenopenopenopenopenopenopenopenopenopenopenopenopenopenopenopenopenopenopenopenopenopenopenopenopenopenopenopenopenopenopenopenopenopenopenopenopenopenopenopenopenopenopenopenopenopenopenopenopenopenopenopenopenopenopenopenopenopenopenopenopenopenopenopenopenopenopenopenopenopenopenopenopenopenopenopenopenopenopenopenopenopenopenopenope

**Comment by tambry** [comment] 2015-09-22 06:05
Closed as this has been resolved.

**Closed** 2015-09-22 06:05 UTC
