### ISSUE TITLE
Skate 3 [BLUS30464] Anti-aliasing broken

### ISSUE THREAD

**Issue by TheFrenchGhosty** [RPCS3/rpcs3#7006] opened 2019-11-17 21:07 UTC
Anti-aliasing is broken in Skate 3 and what looks like collision/debug lines are displayed when it's enabled:

Enabled:

![enabled](https://user-images.githubusercontent.com/47571719/69013995-d6f27f80-097d-11ea-93a4-3799bb48dd8d.jpg)

Disabled:

![disabled](https://user-images.githubusercontent.com/47571719/69014003-e1147e00-097d-11ea-901c-a761d3767919.jpg)

## Details:

RPCS3 version: v0.0.7-9143 Alpha [2019-11-17]  (#7002 (2de3c067) by Niram7777)

Renderer: Vulkan

OS: Windows 10

System Specs:

Ryzen 7 3800X

RX 5700XT

**Comment by 13xforever** [comment] 2019-11-17 21:12
duplicate of #6999

**Closed** 2019-11-17 23:18 UTC
