### ISSUE TITLE
Persona 5 BlackScreen with OpenGL

### ISSUE THREAD

**Issue by ReadofGlass** [RPCS3/rpcs3#3237] opened 2017-08-16 04:57 UTC
![image](https://user-images.githubusercontent.com/31057774/29347881-5793646a-8258-11e7-9ded-3569206bf8a8.png)
![image](https://user-images.githubusercontent.com/31057774/29347896-68eca7b2-8258-11e7-9a71-210700288570.png)
With my current settings, when i try to open Persona 5 it shows a block screen and this code repeadetly appears on my log
E {rsx::thread} RSX: FBO check failed: 0x8cdb
Also I'm not good at PC spec things so;
Here is my CPU: Intel(R) Core(TM) i5-3450 
And here is my GPU: AMD Radeon HD 6670
Can you help me?

**Comment by Asinin3** [comment] 2017-08-16 11:18
This is not the place to ask for assistance, please read https://github.com/RPCS3/rpcs3/blob/master/CONTRIBUTING.md before making an issue report. If you want assistance join the RPCS3 #help channel on discord here: https://discord.me/RPCS3 and someone such as myself will help you.

Please close this issue as there isn't enough information for it to be useful anyway.

**Comment by kd-11** [comment] 2017-08-16 11:31
Ask for help in the forums, its obviously a GPU driver issue afaict. I'm not sure if the 6670 can still run rpcs3, but other users might have more information on that. I'm closing this since its not a bug in the emulator itself.

**Closed by kd-11** 2017-08-16 11:31 UTC
