### ISSUE TITLE
Nvidia/OGL: Visible wireframe

### ISSUE THREAD

**Issue by daitoqu** [RPCS3/rpcs3#2512] opened 2017-03-12 12:39 UTC
Wireframe is visible in Catherine. Everything's OK for Vulkan.

![screenshot_1](https://cloud.githubusercontent.com/assets/24293295/23831844/cb2bde72-074a-11e7-96c1-9762cbbd3f27.png)

**Comment by SakataGintokiYT** [comment] 2017-03-12 13:06
Duplicate of #2241

**Comment by kd-11** [comment] 2017-03-14 14:04
Retest with current master

**Comment by Zangetsu38** [comment] 2017-03-14 14:10
@kd-11 No change, line Allayws here

**Comment by darkredflame** [comment] 2017-03-19 19:52
This issue no longer appears to be occurring on OpenGL.

![discord_2017-03-19_13-50-46](https://cloud.githubusercontent.com/assets/12888227/24084195/30a6a574-0cab-11e7-8d75-4c7e7c41711c.png)
[RPCS3.zip](https://github.com/RPCS3/rpcs3/files/853490/RPCS3.zip)

**Comment by Zangetsu38** [comment] 2017-03-19 20:34
sorry but not, master build tested and last kd build same, line always here
![capture d ecran 2017-03-19 21 33 40](https://cloud.githubusercontent.com/assets/5261759/24084508/cbfa9fea-0ceb-11e7-92f9-5f4855db473b.png)

**Comment by kd-11** [comment] 2017-03-30 04:56
Please retest with https://github.com/RPCS3/rpcs3/pull/2612
This bug seems to depend on the build of catherine used it seems.

**Comment by AnonJump** [comment] 2017-03-30 07:11
@kd-11, nah. The problem didn't go away.

**Comment by darkredflame** [comment] 2017-03-30 07:16
I believe this is a Nvidia specific issue since I haven't had this issue occur for me at all in any of the previous builds either. @AnonJump Are you using a Nvidia card too?

**Comment by AnonJump** [comment] 2017-03-30 07:26
@darkredflame, yes, I'm using NV card

**Comment by daitoqu** [comment] 2017-03-30 07:39
I'am using nvidia card also, and issue is still present.

**Comment by kd-11** [comment] 2017-03-30 16:22
Looks to be an NV issue then. Either way, the clamp behaviour on opengl was wrong, so maybe will fix visuals on some other title.

**Comment by Zangetsu38** [comment] 2017-03-30 16:24
Splatterhouse have a same Wireframe in ogl

**Comment by Xuthos** [comment] 2017-03-31 02:04
Just want to add that I'm having the same issues using a Nvidia gpu as well

**Comment by christ776** [comment] 2017-03-31 13:06
Same issue with an Nvidia card Geforce GT 750M.

**Comment by raven02** [comment] 2017-04-09 15:54
Duplicate of https://github.com/RPCS3/rpcs3/issues/2241

**Closed by raven02** 2017-04-09 15:54 UTC
Labels: NVIDIA, vulkan
