### ISSUE TITLE
Regression: [NPUA80069] LocoRoco Cocoreccho

### ISSUE THREAD

**Issue by aakh1361** [RPCS3/rpcs3#2749] opened 2017-05-02 21:14 UTC
LocoRoco Cocoreccho [NPUA80069]

> F {PPU[0x100001c] Thread (brokenGame) [0x002f2108]} class std::runtime_error thrown: Unimplemented
(in file Emu\Cell\Modules\cellGame.cpp:204)
[RPCS3.zip](https://github.com/RPCS3/rpcs3/files/971986/RPCS3.zip)

**Comment by AniLeo** [comment] 2017-05-02 21:27
That is cellHddGameBroken , the issue is elsewhere, the game is already aborting when it reaches that function.

**Comment by aakh1361** [comment] 2017-05-03 08:00
already game show first screen
![npua80069_v0 0 1-8-60bd2fb_01](https://cloud.githubusercontent.com/assets/25039098/25652188/3338dc20-2ffc-11e7-87ec-40ea2c8f72ef.jpg)

http://www.emunewz.net/forum/showthread.php?tid=177157&highlight=NPUA80069

**Comment by AniLeo** [comment] 2017-05-11 17:01
Which was the commit or build that broke it?

**Comment by aakh1361** [comment] 2017-05-13 11:50
build --->  RPCS3 v0.0.2-5-61ce693 Alpha

I Now Test whit Last build today
same result

Vulkan

select LV2 Only

> F {PPU[0x100001c] Thread (brokenGame) [0x002f5d68]} class std::runtime_error thrown: Unimplemented
(in file C:\rpcs3\rpcs3\Emu\Cell\Modules\cellGame.cpp:204)

[RPCS3.zip](https://github.com/RPCS3/rpcs3/files/998591/RPCS3.zip)

**Comment by AniLeo** [comment] 2017-05-14 17:04
You need to remove .edat extension from all game files for some reason.

I updated the thread with some information http://www.emunewz.net/forum/showthread.php?tid=177157&pid=259606#pid259606

I made a bat file and added it there that you can run to automatically remove .edat extension from all game files (for this game only).

**Comment by Zangetsu38** [comment] 2017-05-14 17:12
with this show screen eula, but freezed with this fatal error
F {PPU[0x1000004] Thread (ptnBgQueTh) [0x0008dcbc]} MEM: Access violation reading location 0x50dfab9e

**Comment by AniLeo** [comment] 2017-05-14 17:19
On master showed eula screen?

**Comment by aakh1361** [comment] 2017-05-15 17:32
AniLeo 
I Do IT And Remove all extensions whit your bat
same Result whit DX12 / OpenGL / Vulkan
only Screen Black white LV2 And Automatioc select LLE
FPS Freeze
Can You Upload Your Log ?

**Comment by AniLeo** [comment] 2017-06-11 16:39
Already fixed in master

**Closed by AniLeo** 2017-06-11 16:39 UTC
Labels: regression
