### ISSUE TITLE
Bug: Broken graphics in Tom Clancy's Splinter Cell: Blacklist - [BLES01766]

### ISSUE THREAD

**Issue by Emulator-Team-2** [RPCS3/rpcs3#15019] opened 2024-01-06 22:15 UTC
## Quick summary
Please briefly describe what is not working correctly.

* Broken shader / lighting.
* Flickering and disappearing models, object etc.
* Broken graphics as shown in the screenshot below.

## Details

* RPCS3 settings: (WCB enabled).
-Tested with the latest master build: (rpcs3-v0.0.30-15916).

**Screenshots:**
RPCS3:
**1.** ![1](https://github.com/RPCS3/rpcs3/assets/38318848/b339a6a7-7de9-45c6-b61d-6f9423a7de93)
**2.** ![2](https://github.com/RPCS3/rpcs3/assets/38318848/55e2ca3e-b856-4d5d-b2d3-746fe63124d3)
**3.** ![3](https://github.com/RPCS3/rpcs3/assets/38318848/883732f2-479c-4122-ba7f-7e1c1f9859b7)
PS3:
![4](https://github.com/RPCS3/rpcs3/assets/38318848/6fe00a2b-e6eb-4fe4-a86c-070494b8fce0)
![5](https://github.com/RPCS3/rpcs3/assets/38318848/4131fa3b-cc8e-4d74-9e54-6c05aaecd13d)
![6](https://github.com/RPCS3/rpcs3/assets/38318848/f801cb7d-d9ea-4ee2-9604-0983b36462f5)

## Log files
Provide a log file that includes the bug you're reporting.

**Attach a log file:**
[RPCS3.log.gz](https://github.com/RPCS3/rpcs3/files/13851478/RPCS3.log.gz)

## Other details
If you describe a graphical issue, please provide an RSX capture and/or a RenderDoc capture that demonstrate it.

**Attach capture files for visual issues:**
[RDC Capture - (Screenshots-1)](https://drive.google.com/file/d/1HxZ8eUaL20PWli_QiQLHtt1zk7cbo_Jc/view?usp=sharing)
[RDC Capture - (Screenshots-2)](https://drive.google.com/file/d/1lVOCwovZkOh4uK4KZdDgbjEuHhjyOtBS/view?usp=sharing)
[RDC Capture - (Screenshots-3)](https://drive.google.com/file/d/169kM1tnZVgwMOi8l0mo542UaUNtZxAqL/view?usp=sharing)

##
**System configuration:**
* OS: Windows 11
* CPU: Intel i7-10700
* Memory: 16GB RAM
* GPU: RTX 3060
* Driver version: 545.84.0.0

##
* Game Engine: (Unreal Engine 2.5)
* No changes with enabled (WDB+RCB+RDB) or (Strict Rendering) Mode settings.

**Comment by FlexBy420** [comment] 2024-01-06 23:37
Duplicate of #14396

**Comment by Triticum0** [comment] 2024-01-07 15:26
Can This be closed then?

**Closed** 2024-01-07 15:26 UTC
Labels: Meta: Duplicate
