### ISSUE TITLE
Firmware compilation not working on SSE2 CPUs

### ISSUE THREAD

**Issue by szm1gluu** [RPCS3/rpcs3#4877] opened 2018-07-12 03:07 UTC
![1](https://user-images.githubusercontent.com/41135145/42610329-541b0ecc-8591-11e8-87c0-39ffb0ddabdb.jpg)
like on screen.
Athlon 64 x2 5600+
4GB RAM
GT610
using latest version downloaded from site and latest fw from sony site

**Comment by AniLeo** [comment] 2018-07-12 03:11
I've seen this before, looks like SSE2 path bug

**Comment by szm1gluu** [comment] 2018-07-12 03:13
So it's the processor fault?

**Comment by AniLeo** [comment] 2018-07-12 04:07
No. Just that it happens only on those CPUs without SSSE3. 

Obviously they will never be able to run RPCS3 properly because they're too bad, but this is an actual bug.

**Comment by szm1gluu** [comment] 2018-07-12 04:33
But B970 have SSSE3, maybe i'll give it a try.

**Comment by AniLeo** [comment] 2018-07-12 04:36
Sure, don't forget to set Render to Null since you have no hardware support for the OpenGL Render.

Anyways, this is not appropriate to this issue, I'll be hiding the comments when I'm on a PC.

**Comment by gandalfthewhite19890404** [comment] 2018-10-13 09:42
Tested on AMD Athlon 6000+ with 7435, firmware 4.83 - installed without issues. Issuestarter - please, test it, and close this issue.

**Comment by AniLeo** [comment] 2018-11-15 22:57
I've seen several successful installs of firmware on SSE2 CPUs on current builds for a while now. Closing as solved. If this is still an issue, provide updated information so it can be reopened.

**Closed by AniLeo** 2018-11-15 22:57 UTC
Labels: Bug

**Comment by maticres03** [comment] 2020-12-21 04:28
Hello, I wanted to tell you that a week ago I bought a notebook with i7 1065g7 with IRIS PLUS GPU and I have the problem that I cannot install firmware 4.87 to RPCS3. Does this processor have no SSSE3? Is there any way I can make it work? Greetings from Argentina.

**Comment by maticres03** [comment] 2020-12-21 05:04
I just used the Coreinfo program and confirmed that my notebook supports SSE, SSE2, SSE3, and SSSE3, but however, I cannot update the firmware. I have little or no computer knowledge at the moment. But I hope you can help me.
