### ISSUE TITLE
Kingdom Hearts HD 1.5 ReMIX [BLUS31212] Freezes 

### ISSUE THREAD

**Issue by LindsNemesis** [RPCS3/rpcs3#5866] opened 2019-04-20 05:09 UTC
v0.0.6-8000 Alpha [2019-04-19] 

After finishing **ANY** Kingdom Hearts game and watching the last cutscene after the credits, the game freezes in a black screen and does not show the ending stats for the completion of the game thus does not save after beating the boss. 

**Have the same issue in menu cutscene**  

Microsoft Windows 10 Pro 
Intel(R) Core(TM) i7-4790K @ 4.4GHz
16 GB DDR3
NVIDIA GeForce GTX 1080TI

Videos: [After Credits Freeze](https://www.youtube.com/watch?v=4-V0xFILLqM&feature=youtu.be)
[Menu Freeze](https://youtu.be/dbiTlf2HF3U)

[RPCS3.log.gz](https://github.com/RPCS3/rpcs3/files/3099775/RPCS3.log.gz)

**Comment by elad335** [comment] 2019-04-20 05:11
Does it freeze with spu interpreter as well?

**Comment by LindsNemesis** [comment] 2019-04-20 05:12
> Does it freeze with spu interpreter as well?

Yes

**Comment by elad335** [comment] 2019-04-20 05:17
Duplicate of #4851.

**Comment by LindsNemesis** [comment] 2019-04-20 05:19
> Duplicate of #4851.

Yes sorry but #4851 not mentioned Menu Freeze and is a old request

**Comment by AniLeo** [comment] 2019-04-20 05:52
Discuss on the existing issue, no need to spawn a new one

**Closed by AniLeo** 2019-04-20 05:52 UTC
Labels: Meta: Duplicate
