### ISSUE TITLE
DX12/OGL/Vulkan : memory leaking

### ISSUE THREAD

**Issue by B1ackDaemon** [RPCS3/rpcs3#1544] opened 2016-03-06 06:34 UTC
See http://rghost.ru/private/72Bww6Sdn/cc1139f4a71811b411e3e267e7e39ac5

Doesn't occur, when using DX12 renderer.

**Comment by kd-11** [comment] 2016-03-09 08:56
I've seen something similar for hitman 2 under opengl and vulkan. The ram usage skyrockets and ultimately crashes the emu. Probably has to do with the cache implementation. I'll look into it.

**Comment by kd-11** [comment] 2016-03-09 17:46
Ok found it. GL isn't destroying invalidated rtts from the cache. I'll submit a fix soon.

**Comment by B1ackDaemon** [comment] 2016-03-09 19:22
@kd-11, thank you! :)

**Comment by Nekotekina** [comment] 2016-03-09 19:25
Not fixed, still leaks in other games.

**Comment by kd-11** [comment] 2016-03-09 19:29
Any other games that are leaking only in opengl mode? This ought to fix the fast leaking (e.g when game is paused, or character is standing still).

**Comment by Nekotekina** [comment] 2016-03-09 19:31
I'll recheck, it actually suddenly raises memory consumption for few gigs and crashes at rsx_gl_texture.cpp line 316 in glTexSubImage2D call.

**Comment by kd-11** [comment] 2016-03-09 19:32
for ridge-racer 7?

**Comment by Nekotekina** [comment] 2016-03-09 19:32
No, sorry

**Comment by Nekotekina** [comment] 2016-03-09 19:33
Can you just recheck all the resource management? Because nothing gets magically released.

**Comment by danilaml** [comment] 2016-03-09 19:33
I know that there is slow leaking in dx12 (though it could be not related to render but rather to ppu/spu interp 2). After about an hour or less of neo burn climax menu running in the background it leaked over 8GB iirc (I've got low memory warnings on my 16GB system).

**Comment by kd-11** [comment] 2016-03-09 19:35
Its unfortunately not so simple in this case. Alot of resources are cache managed. One issue i'd expect is slow leaking, since old resources are not invalidated even when they are not in use, but are still valid. Think about, say, how a game would need to unload textures at the end of a level or section. If the texture region isnt clobbered the resources remain intact despite the expired lifetime.

**Comment by kd-11** [comment] 2016-03-09 19:37
@Nekotekina In the case you mention, is it fast or slow leaking? I'll submit a fix for the slow leaking stuff soon, using some basic lifetime checks. Most of it is actually already present for openGL.

**Comment by Nekotekina** [comment] 2016-03-09 20:00
It was instant, almost vertical, leak. Maybe took 1-2 seconds.

**Comment by kd-11** [comment] 2016-03-09 20:02
Which game was it? I might need to reproduce this case.

**Comment by vlj** [comment] 2016-03-09 20:44
The rtt are never released except if format/texture change but so far it never made dx12 backend exhaust all memory. 

Usually an app only use a small amount of rtt and reuse them. And since rtt can be sampled we can't really ditch a rtt if memory overlaps. Cell writing to rtt memory may be used as a hint though. 

I guess the proper solution is to implement least recently used heuristic if memory pressure is high and write data to memory before discarding rtt resources.

**Comment by kd-11** [comment] 2016-03-09 20:49
On GL, i had the framectr system, but i think it isnt really used properly right now. If a texture in the main cache unused for say, X frames, it should be removed. The problem with the rtts is that some games such as hitman 2 for instance, were causing the create members of the surface store to be called repeatedly, almost every frame and invalidated resources are not reused, despite it being a pattern of 2 rtt sizes and formats. The game would crash in seconds afterwards. https://github.com/RPCS3/rpcs3/issues/1559 fixed that particular issue though. I think a frame counter can be adapted and added to the surface store as well.

**Comment by scribam** [comment] 2017-09-03 16:27
@B1ackDaemon @kd-11 Is it still an issue?

**Comment by kd-11** [comment] 2017-09-06 22:06
Shouldn't be an issue anymore so I'll close this.

**Closed by kd-11** 2017-09-06 22:06 UTC
Labels: Bug, Render: Direct3D 12, Render: OpenGL, Render: Vulkan, RSX
