### ISSUE TITLE
Using Sony's DS4 Adapter can cause crashes after launching.

### ISSUE THREAD

**Issue by Renari** [RPCS3/rpcs3#3399] opened 2017-09-05 15:38 UTC
https://forums.rpcs3.net/thread-196910.html

If you use Sony's DS4 Adapter Which makes the controller show up in devices as "DUALSHOCK®4 USB Wireless Adaptor". This remains an available device even when the controller is powered off. If you attempt to launch a game with the controller powered off it will crash with a Win32 exception.

**Comment by Talkashie** [comment] 2017-09-05 16:14
This issue had me so confused as to why RPCS3 sometimes wouldn't work. Figured out the cause about two weeks ago. Jarves was looking into it I believe. He may have forgotten or something, but this was his attempt to fix it from a few days ago:

https://github.com/RPCS3/rpcs3/compare/master...jarveson:ds4donglefix

**Comment by RipleyTom** [comment] 2017-09-05 16:42
He's actually waiting for pad refactoring to be merged, we don't forget anything 😉 .

**Closed** 2017-09-24 19:03 UTC
