### ISSUE TITLE
Final Fantasy XIII [BCAS25005]cant load game save only can save

### ISSUE THREAD

**Issue by Myoko** [RPCS3/rpcs3#6610] opened 2019-09-22 01:32 UTC
i can save files, but everytime i got no load option in main menu!
i remember this issues it's been for a long time, until now still cant load.
has anyone noticed the problem?

![FFXIII](https://user-images.githubusercontent.com/3013386/65381021-7f87b880-dd1a-11e9-9e1d-7abafe38c614.png)

log
[RPCS3.log.gz](https://github.com/RPCS3/rpcs3/files/3639231/RPCS3.log.gz)

**Comment by AniLeo** [comment] 2019-09-22 23:54
Can you see your save file properly through save manager?

**Comment by Myoko** [comment] 2019-09-23 08:47
yeah! i can see the files in save manager. but i cannot loaded!

**Comment by Metasynic** [comment] 2019-09-23 10:28
What version of RPCS3 are you using? I'm on 8674 and can't get past the end of the tutorial battle. :(

**Comment by Myoko** [comment] 2019-09-23 10:31
im using 0.0.7 8752

**Comment by AniLeo** [comment] 2020-03-04 12:43
Duplicate of #7687

**Closed by AniLeo** 2020-03-04 12:43 UTC
Labels: Bug, Savedata
