### ISSUE TITLE
BLES00070 doesn't boot

### ISSUE THREAD

**Issue by leskal** [RPCS3/rpcs3#5488] opened 2019-01-02 13:00 UTC
Doesn't boot as of **rpcs3-v0.0.5-7624-cfe07098_win64**. Get `'sys_fs_stat' failed with 0x8001003a : CELL_ENOTMOUNTED, “/dev_bdvd”`

Tested in:
i7 6700k
gtx1060 6gb
16gb ddr3
[PPU LLVM.log.gz](https://github.com/RPCS3/rpcs3/files/2720785/PPU.LLVM.log.gz)
[PPU Interpreter fast.log.gz](https://github.com/RPCS3/rpcs3/files/2720786/PPU.Interpreter.fast.log.gz)
[PPU Interpreter precise.log.gz](https://github.com/RPCS3/rpcs3/files/2720787/PPU.Interpreter.precise.log.gz)

**Comment by 13xforever** [comment] 2019-01-02 15:44
Github is not for support questions, use discord or forums instead.
You have broken config. Please close this issue and ask in an appropriate channel if you still can't fix it.

**Comment by leskal** [comment] 2019-01-02 15:47
> Github is not for support questions, use discord or forums instead.
> You have broken config. Please close this issue and ask in an appropriate channel if you still can't fix it.

I have test clean install of rpcs3 and the problem exists. So it's not config prob

**Comment by nitrohigito** [comment] 2019-01-02 16:35
@leskal That's not what he meant. If by "as of rpcs3-v0.0.5-7624-cfe07098_win64" you meant that the game with the same configuration set was working on the previous build but is now broken with that, this report is completely fine.

If not, and you just tried said build and the game didn't work, this doesn't belong here, as it's not a regression. For support, the project's Discord server is to be used, not this issue tracker.

**Comment by leskal** [comment] 2019-01-02 16:37
> @leskal That's not what he meant. If by "as of rpcs3-v0.0.5-7624-cfe07098_win64" you meant that the game with the same configuration set was working on the previous build but is now broken with that, this report is completely fine.
> 
> But if not, and you just tried said build and the game didn't work, this doesn't belong here, as it's not a regression. For support, the project's Discord server is to be used, not this issue tracker.

I have test with the two previous builds and was the same prob. I just mension the build number i take the logs

**Comment by nitrohigito** [comment] 2019-01-02 16:59
I see that you have also commented in the appropriate topic in the forums, thank you for that.

Nevertheless, this report is still incomplete currently, as it misses which build actually broke it (if it is truly broken). If you could determine it and add it to the original post, the issue could remain open and devs could attempt fixing it much easier.

The easiest way to do this is by bisecting builds. Pick a build from long before and test if it works with that. If not, go for an even older one. When you found one that the game does work with, you then test it with the build in the middle between the last non-working and the working build you just found. Rinse & repeat, till you find the build that broke it. With this, you can minimize the time looking for the regressed build.

Before you attempt this, I'd definitely recommend testing the validity of your dump with an IRD checker with the tool you can find [here.](http://jonnysp.bplaced.net/) If you are not sure what that means, or you are unsure whether this is truly a regression, ask for help at the project's Discord in #help.

**Comment by leskal** [comment] 2019-01-02 18:20
> I see that you have also commented in the appropriate topic in the forums, thank you for that.
> 
> Nevertheless, this report is still incomplete currently, as it misses which build actually broke it (if it is truly broken). If you could determine that and add it to the original post, the issue could remain open and devs could attempt fixing it much easier.
> 
> The easiest way to do this is by bisecting builds. Pick a build from long before and test if it works with that. If not, go for an even older one. When you found one that the game does work with, you then test it with the build in the middle between the last non-working and the working build you just found. Rinse & repeat, till you find the build that broke it. With this, you can minimize the time looking for the build that regressed it.
> 
> Before you attempt this, I'd definitely recommend testing the validity of your dump with an IRD checker via a tool you can find [here.](http://jonnysp.bplaced.net/) If you are not sure what that means, or you are unsure whether this is truly a regression, ask for help at the project's Discord in #help.

I will try to find the last build that works with this game and i will report here

**Comment by nitrohigito** [comment] 2019-01-02 18:21
Thanks!

**Comment by leskal** [comment] 2019-01-02 19:37
> Thanks!

Last working build with this game is 0.0.5-7549:
![screenshot_1](https://user-images.githubusercontent.com/11486824/50608735-28189280-0ed6-11e9-9a01-1cf00422caeb.png)

With 0.0.5-7550:
![screenshot_2](https://user-images.githubusercontent.com/11486824/50608863-93fafb00-0ed6-11e9-9c57-c5d28d839ec2.png)

**Comment by nitrohigito** [comment] 2019-01-02 19:39
Awesome, thank you for your report!

**Comment by NicknineTheEagle** [comment] 2019-01-02 19:49
This boots for me. Check your files with PS3-ISO-Rebuilder.

**Comment by leskal** [comment] 2019-01-02 20:17
> This game boots for me. Check your files with PS3-ISO-Rebuilder.

I 'll check it and report back!

**Comment by NicknineTheEagle** [comment] 2019-01-02 20:18
Make sure there are no excess files either, they can cause problems.

**Comment by NicknineTheEagle** [comment] 2019-01-02 20:19
Post a screenshot of the results when you're done.

**Comment by leskal** [comment] 2019-01-02 20:22
> Post a screenshot of the results when you're done.

Ok, if helps, I will also provide folder tree

**Comment by leskal** [comment] 2019-01-02 23:45
> > Post a screenshot of the results when you're done.
> 
> Ok, if helps, I will also provide folder tree

![screenshot_1](https://user-images.githubusercontent.com/11486824/50618075-3926cb00-0ef9-11e9-8189-eec789097bf9.png)

**Comment by nitrohigito** [comment] 2019-01-02 23:54
As you can see, your copy of the game is corrupted, which is why the code breaks, probably. I'm sure the code could handle this a bit more gracefully though.

**Comment by NicknineTheEagle** [comment] 2019-01-02 23:56
His dump has additional PS3_DISC.SFB inside PS3_GAME dir for whatever reason which screws up the checks. And PIC0.PNG is modified. Kind of looks like a pirated copy.

**Comment by 13xforever** [comment] 2019-01-02 23:59
Remove `/ps3_game/ps3_disc.sfb`.

Dump is corrupted, yes. Please do not jump to conclusions tho.

**Comment by nitrohigito** [comment] 2019-01-03 00:03
@NicknineTheEagle I peeked through the changes of the PR quickly, why would that screw up the checks? It's just that the PIC0.png is corrupted. I'm fairly sure if he fixed that, the game would work.

**Comment by leskal** [comment] 2019-01-03 00:03
Removing this: `/ps3_game/ps3_disc.sfb` fixes the boot. But how a modified picture and a missing ps3 firmware prevents from booting the game?

**Comment by NicknineTheEagle** [comment] 2019-01-03 00:05
It's the extra ps3_disc.sfb, the code looks for this file to determine if the app is a disc game, this file being in the wrong location screws things up.

**Comment by nitrohigito** [comment] 2019-01-03 00:17
I peeked harder and it makes sense now :)

**Closed** 2019-01-06 16:47 UTC
