### ISSUE TITLE
GL/Vulkan:  Naruto Shippuden: UNS Generations / RenderDoc

### ISSUE THREAD

**Issue by SakataGintokiYT** [RPCS3/rpcs3#2149] opened 2016-09-21 16:53 UTC
@kd-11 
**Vulkan:**
<img src="http://www.fotoszok.pl/upload/1e01a6f3.jpg" alt="Fotoszok.pl" />

[Title Screen.rdc](https://mega.nz/#!Md51wQqK!v9zVBzpUHUB8_EzwStNEzCx_qVs148rwK043oqoNGF4)
[Menu.rdc](https://mega.nz/#!sJpEVRBB!xkoSRX-I9M5qHxzQ-ff-Wq3h_yIjnUl_mzyM5b8EyDA)

------------------------------------------------------------------------------------------------------------

**OpenGL:**
<img src="http://www.fotoszok.pl/upload/aeb52dea.jpg" alt="Fotoszok.pl" />

[Title Screen.rdc](https://mega.nz/#!RAJzmYbJ!z8PLBsqnXXLGpR6R1GAYRtx1PvkKpkVZov_iPqHXGnY)
[Menu.rdc](https://mega.nz/#!hcwgAYSS!od1_EKBulDH3Hfd9LN9G3g-rS1acAjkyU2Woglqtjbk )

**Comment by kd-11** [comment] 2016-09-22 14:51
I think this is related to https://github.com/RPCS3/rpcs3/issues/1949
I'll start working on this as it has been on the list of graphical issues for a while.

**Comment by kd-11** [comment] 2016-09-22 20:37
Please test https://ci.appveyor.com/project/kd-11/rpcs3/build/1.0.262/artifacts when its done building (opengl only)

**Comment by kd-11** [comment] 2016-09-22 20:39
If its still not working, get the title screen renderdoc trace with opengl and the build i've posted.

**Comment by SakataGintokiYT** [comment] 2016-09-22 21:30
<img src="http://www.fotoszok.pl/upload/3fbf51d9.jpg" alt="Fotoszok.pl" />
[Title Screen.rdc](https://mega.nz/#!sBRXGLIA!8RqMo9n9CC2tSoLAmEQrpWYKnSGEElyDSVKhNAgbBrE)

**Comment by kd-11** [comment] 2016-09-22 22:56
Oops. I messed up generating the reconstruction function; its missing a constructor declaration. This should have that specific issue fixed. Check if anything has changed.
https://ci.appveyor.com/project/kd-11/rpcs3/build/1.0.263/artifacts

**Comment by kd-11** [comment] 2016-09-23 09:53
https://ci.appveyor.com/project/kd-11/rpcs3/build/1.0.264/artifacts Should fix the black and white bug when using regular textures.

**Comment by SakataGintokiYT** [comment] 2016-09-23 13:56
@kd-11 
**#1  [ 8c730029 ]**
<img src="http://www.fotoszok.pl/upload/9055a5e8.jpg" alt="Fotoszok.pl" />
[Title Screen.rdc](https://mega.nz/#!MUJQmAbZ!D2LtMZZc8QYj6Ui3b_giUDMOg1Ikp-omyTAyQF-snHU)
[Menu.rdc](https://mega.nz/#!wI4xSQLC!_WLpr5gACn6BOuu3ota9OyjBOTeiJ4bXPTlxHtEEouw)

____________________________________________________________________________________________________________

**#2 [ 98329e72 ]**
<img src="http://www.fotoszok.pl/upload/3d295e82.jpg" alt="Fotoszok.pl" />
[Title Screen.rdc](https://mega.nz/#!YAR0nZTZ!D78ZzXecftvaQOGaLPw5QIQ4fWGdKawRzicLcJAbHm4)
[Menu.rdc](https://mega.nz/#!VZZ1lawK!vtqh7l6Fn_yFjHgvKB5EWZit5-Y6dgmnY1HNWB-AQjY)

**Comment by kd-11** [comment] 2016-09-24 12:59
https://ci.appveyor.com/project/kd-11/rpcs3/build/1.0.267/artifacts
Hopefully it works better this time.

**Comment by kd-11** [comment] 2016-09-24 13:04
Uggh. I forgot something else. Will update with a better build.

**Comment by SakataGintokiYT** [comment] 2016-09-24 13:26
Pixels are rendered , in menu and at title screen
[ 9fce47fa ]
<img src="http://www.fotoszok.pl/upload/fe8e310c.jpg" alt="Fotoszok.pl" />
[Title Screen.rdc](https://mega.nz/#!1A4HSRZK!KwnKgNW-rLbwiLKHBs658pTBPH7Ln8do0yNUlNp8DfE)
[Menu.rdc](https://mega.nz/#!ZNhQRKiI!hNwpX9rvOZ7iydDSYAYSMXohR1f48lyeCty2ZS-0_A8)

**Comment by kd-11** [comment] 2016-09-24 13:30
There's another problem with early exit in fragment shader: we should write depth before returning. I've started to understand the algorithm in place here.

![image](https://cloud.githubusercontent.com/assets/15904127/18808775/0a594c6c-8274-11e6-8342-b81a3d95ff64.png)

**Comment by kd-11** [comment] 2016-09-24 14:29
https://ci.appveyor.com/project/kd-11/rpcs3/build/1.0.268/artifacts Manually re-uploads the texture data. I'll need it to compare my reconstruction with the proper upload.

**Comment by SakataGintokiYT** [comment] 2016-09-24 14:52
[ 96d8fdd3 ]
<img src="http://www.fotoszok.pl/upload/e43d57a1.jpg" alt="Fotoszok.pl" />

Title Screen.rdc(https://mega.nz/#!8AZm0CSa!99s19jhgR-jtNbzO0qVxFd6znmjuJDxvfNmdOPfZ3hQ)
Menu.rdc(https://mega.nz/#!1ZoFWLjb!U524S4FvuR-4-T9Uv-rod6nzY7v0k-RxiFp4rVCV5Ak)

**Comment by kd-11** [comment] 2016-09-25 09:03
Fixed re-upload of the texture. If this doesnt work, we probably have another error elsewhere. If it runs correctly (or somewhat correctly) using dx12, i'd like to take a look at the dx12 shaderlog.

**Comment by SakataGintokiYT** [comment] 2016-09-25 09:41
@kd-11 
<img src="http://www.fotoszok.pl/upload/f1dafb05.jpg" alt="Fotoszok.pl" />

[Shaderlog-GL:](https://mega.nz/#!BZJGHAiT!Vqqp4yPBiPDkR4NAgz7RHVxAqEEF2GshpsKuFIKe8Tk)
[Shaderlog-DX12:](https://mega.nz/#!kY5QhIzQ!FCIRo8WcD9C_p-urE33DxetYDvpnhRwI1dxl1MLZ7KA)

**Comment by kd-11** [comment] 2016-09-25 10:36
The problem is elsewhere. There's another RTT being sampled even before we reach the code where depth reconstruction is done. As such, I think the reconstruction function works quite well.
The problem seems to be the fact that OGL and VK ignore render target swizzles, but DX12 has select cases enabled. Will have to implement some RTT channel remapping.

**Comment by kd-11** [comment] 2016-09-25 10:54
https://ci.appveyor.com/project/kd-11/rpcs3/build/1.0.270/artifacts
Remaps render targets as well.

**Comment by Nezarn** [comment] 2016-09-25 11:20
@kd-11 its not just "might" break some games, it does break some :P (project diva games)
http://i.imgur.com/tm3hXs3.png
http://i.imgur.com/l9HqzsW.png

**Comment by kd-11** [comment] 2016-09-25 11:22
I know it does; its hacky right now. I removed this from the vulkan renderer for this very reason, but if there are games that rely on the remap behaviour, I need to know.

**Comment by SakataGintokiYT** [comment] 2016-09-25 11:24
@kd-11 
No change

**Comment by kd-11** [comment] 2016-09-25 11:28
That means something else is broken. Its not the same issue as https://github.com/RPCS3/rpcs3/issues/1949 then. Something about the texture coordinates used is wierd.

**Comment by kd-11** [comment] 2016-09-25 12:21
![image](https://cloud.githubusercontent.com/assets/15904127/18815146/4c30efac-8330-11e6-8fc9-36fcdc66ef85.png)

With the texture reconstruction and some minor tinkering:
Now, to make thes changes stick.

P.S: I've finally figured out why this is happening. Will need to rewrite parts of the glsl code generator. The method "return" as inserted in the middle of a shader does not mean exit and abandon all, we have discard for that. The main_end has to be invoked upon routine termination. I was right here: https://github.com/RPCS3/rpcs3/issues/2149#issuecomment-249364984

**Comment by SakataGintokiYT** [comment] 2016-09-25 12:23
@kd-11 
Nice

**Comment by kd-11** [comment] 2016-09-25 14:29
https://ci.appveyor.com/project/kd-11/rpcs3/build/1.0.271/artifacts Should fix this on opengl. The depth reconstruction is still WIP so if you can get ingame, check for depth artifacts.

**Comment by SakataGintokiYT** [comment] 2016-09-25 14:41
@kd-11 
I get this error before the title screen 

```
E {rsx::thread} RSX: Failed to compile vertex shader: 0(79) : error C1038: declaration of "dst_reg6" conflicts with previous declaration at 0(79)
0(221) : error C1038: declaration of "dst_reg6" conflicts with previous declaration at 0(211)

F {rsx::thread} class gl::glsl::link_exception thrown: linkage failed: 'Vertex info
-----------
0(79) : error C1038: declaration of "dst_reg6" conflicts with previous declaration at 0(79)
0(221) : error C1038: declaration of "dst_reg6" conflicts with previous declaration at 0(211)
(0) : error C2003: incompatible options for link
'
```

**Comment by kd-11** [comment] 2016-09-25 14:44
I'm guessing the shader contains a tc9 input. Could you attach the shader. Just clear the  shaderlog folder and attach the last vertex shader generated. It will have the largest number.

**Comment by SakataGintokiYT** [comment] 2016-09-25 14:50
@kd-11
[shaderlog](https://mega.nz/#!MAgXjZwK!piSYKZNj5_maUynrCcykXbIGrpWyPEZ2V6fVcKubtYA)

**Comment by kd-11** [comment] 2016-09-25 14:54
https://ci.appveyor.com/project/kd-11/rpcs3/build/1.0.272/artifacts

**Comment by SakataGintokiYT** [comment] 2016-09-25 16:00
<img src="http://www.fotoszok.pl/upload/111579e6.jpg" alt="Fotoszok.pl" />

@kd-11 
I can't run any mode, because a game stuck at black screen after choosing mode  

@Nekotekina 
Regression by #2043

**Comment by kd-11** [comment] 2016-09-25 16:11
I'm creating a PR with the shader stuff without the depth reinterpret stuff as it seems kinda broken at the moment. Also, depth read sample binds a depth buffer as RGBA, but expects to read a normal depth value from it, not a reconstructed one. At least until we can go ingame, then we can proceed.

**Comment by kd-11** [comment] 2016-09-25 16:54
https://github.com/RPCS3/rpcs3/pull/2155 should fix this issue without the wierd depth reconstruction glitches

**Comment by SakataGintokiYT** [comment] 2016-09-25 17:31
<img src="http://www.fotoszok.pl/upload/1f207926.jpg" alt="Fotoszok.pl" />
<img src="http://www.fotoszok.pl/upload/4f9d8bbf.jpg" alt="Fotoszok.pl" />

**Comment by SakataGintokiYT** [comment] 2016-09-25 18:44
@kd-11 
**Naruto Shippuden: UNS 3  ( In Game )** 
<img src="http://www.fotoszok.pl/upload/1c383588.jpg" alt="Fotoszok.pl" />
<img src="http://www.fotoszok.pl/upload/c974a591.jpg" alt="Fotoszok.pl" />

[Shaderlog-GL](https://mega.nz/#!NJRUzLZS!334tT-aFMl1ZUiRRMGnnV1pgA_x9j1Ul7SL0FyWtkUE)
[Shaderlog-Vulkan]

**Comment by kd-11** [comment] 2016-09-25 19:04
Is the red color present in the title screen and menus as well? Also, a trace of opengl would help a lot.

**Comment by SakataGintokiYT** [comment] 2016-09-25 19:09
Naruto Shippuden: UNS Generations  ( Menu works well  )

**Comment by kd-11** [comment] 2016-09-25 19:11
okay. then just attach the renderdoc trace for that red UNS scene. Does it show correctly using DX12?

**Comment by SakataGintokiYT** [comment] 2016-09-25 19:16
<img src="http://www.fotoszok.pl/upload/0c2f99c4.jpg" alt="Fotoszok.pl" />
**[Shaderlog-DX12](https://mega.nz/#!JYpxSLrL!PaVYXukaA7u19wsO7sS7SO3dn5SB1brmzUu_9MNeIL8)**

**Comment by SakataGintokiYT** [comment] 2016-09-25 19:29
@kd-11 
**[OpenGL-Trace]**
**[red-scene](https://mega.nz/#!dcxHFZjJ!QWKSlcZoOxmdbCNkbHwWfGF6M9PM0QVnhdk3ZT0tEIA)**

**Comment by SakataGintokiYT** [comment] 2016-09-26 04:52
**[OpenGL]**
<img src="http://www.fotoszok.pl/upload/bc5db35c.jpg" alt="Fotoszok.pl" />
**[Vulkan]** Perfect 
<img src="http://www.fotoszok.pl/upload/96996179.jpg" alt="Fotoszok.pl" />

**Comment by kd-11** [comment] 2016-09-26 10:36
https://github.com/RPCS3/rpcs3/pull/2155 might solve this.

**Comment by SakataGintokiYT** [comment] 2016-09-26 12:06
@kd-11 
Naruto Shippuden: UNS 3   still not fixed yet

**Comment by kd-11** [comment] 2016-09-26 12:46
Actually, the image has changed from the look of things. You can see the correct scene covered by the fullscreen effect. Only the post-process stuff needs some adjustment now. Attach a new opengl trace.

**Comment by kd-11** [comment] 2016-09-26 13:20
The scene is now correctly rendered but the post-process effects are upside-down. Can you retest with current master? Some fixes have been implemented opengl side. I'm not sure its anything that'll fix it, but just take a look.

**Comment by kd-11** [comment] 2016-09-26 13:22
The problem is that the game is using an input texture as the render target which is just crazy. Maybe I should force copying of surfaces in cases like these

**Comment by SakataGintokiYT** [comment] 2016-09-26 14:31
@kd-11 
**Naruto Shippuden: UNS 3**

***OpenGL-Trace**
**[Moon](https://mega.nz/#!9N5wkA5C!WLseYJZ4SbGOWsT5LttG4ZjzrJU8sdGEbBl52jdRH7E)**
**[Village](https://mega.nz/#!oAZhiJ7R!R8akeLjvMSYABr0SyRkmcyOHRLy1E4UP4rBWl9v5cmc)**
**[VS Fox](https://mega.nz/#!ERoxGKpQ!kZE0jA9qfIzyaJ_NhjuVbn2CCEL-bt9qna5TL-Z6KN4)**

**Comment by kd-11** [comment] 2016-09-27 09:26
GL and vulkan dont mirror wpos based on window origin!
Will submit a fix ASAP

**Comment by kd-11** [comment] 2016-09-28 10:01
This should have been fixed now. If its fixed, please close this ticket.

**Closed** 2016-09-28 11:06 UTC
Labels: opengl, vulkan

**Comment by Ronaldo-brazil** [comment] 2016-09-29 20:00
I'm getting this error in Naruto storm generations and can not go in the game, with WHAT this could be related?
![capturar](https://cloud.githubusercontent.com/assets/20917247/18970062/2755cc8c-8666-11e6-96ef-1796ce05c10d.JPG)
