### ISSUE TITLE
RIDGE RACER 7 [BCES00009] desyncing right after launching

### ISSUE THREAD

**Issue by Emogop** [RPCS3/rpcs3#7305] opened 2020-01-21 20:26 UTC
... after a different amount of time (5-50 sec)
The cause may be my 2-cores CPU i3 6100 4,45 Ghz but some other games work fine. (PeeFive, Nier and others)
rpcs3 v 9428
It often (but not always) goes like this: screen gets dark, but the game's still running: audio is playing and gamepad is working, the annoing voice keeps tracking your actions, though you can't see them because the screen was frozen or black. And here's what the log is saying:
E {PPU[0x1000011] Thread (CPamfDemuxer::ReadThread) [0x0071ff0c]} '_sys_prx_get_module_id_by_name' failed with 0x8001112e : CELL_PRX_ERROR_UNKNOWN_MODULE [1]
E {RSX [0x10a0dd8]} RSX: FIFO error: possible desync event (last cmd = 0x3030303) x12
E {RSX [0x0c90044]} RSX: FIFO: RET found without corresponding CALL. Discarding queue
E {PPU[0x1000000] Thread (main_thread) [0x0039342c]} 'sys_ppu_thread_set_priority' failed with 0x80010005 : CELL_ESRCH [1]

[RPCS3.log](https://github.com/RPCS3/rpcs3/files/4093624/RPCS3.log)

**Comment by AniLeo** [comment] 2020-01-21 20:28
Missing log file

**Comment by elad335** [comment] 2020-01-21 20:29
Try using RSX wake-up delay in advanced tab.

**Comment by Emogop** [comment] 2020-01-21 20:44
> Missing log file

it's tens of megs, how can I make it ligher?



> Try using RSX wake-up delay in advanced settings tab.

Lol, it's acrually making thing worse up until 1000 (never went farther than that). It's instant black screen now.

**Comment by AniLeo** [comment] 2020-01-21 20:53
It's very unlikely it's tens of megs by just playing the start, unless you're trying to upload an uncompressed version, in that case manually compress it yourself

**Comment by Emogop** [comment] 2020-01-21 20:56
> It's very unlikely it's tens of megs by just playing the start, unless you're trying to upload an uncompressed version, in that case manually compress it yourself

It's a little more than 3 mb, please look at the 1st message.

**Comment by elad335** [comment] 2020-01-25 07:06
Retest with rsx wake-up delay.

**Comment by Emogop** [comment] 2020-01-25 08:51
> Retest with rsx wake-up delay.

I already did that, with every delay other than default I'm getting this screen, the game itself goes on.

![Screenshot_166](https://user-images.githubusercontent.com/42875723/73118724-f521c080-3f68-11ea-8173-19264eb6fc3b.png)

**Comment by Emogop** [comment] 2020-05-06 20:41
So things have improved quite a lot since I opened this issue. Now I can even finish some races before the inevitable hanging. But sometimes it still happens in the menu. There's no consisnancy to it.
Although increasing Driver Wake-Up Delay is still doing whatever its been doing, but decreasing  the value to 0 seems to improve the overall stability. Or am I imagining things?

**Comment by pidgey84** [comment] 2020-09-30 11:29
Hello, Emogop is totally right, i get some of these issues, the games looks that crash (it get freeze on screen but music and sounds continue like normal) randomly, after some play or even after a long play, is more easy to make it crash if you put a replay after do a course and leave the pad untoch, the emulator ask about wakeup feature or some like that, but using it just make the game go to a black screen.

**Comment by LogosTP** [comment] 2020-10-28 01:48
I find using OpenGL to be much more stable, although it still crashes either halfway through a race or shortly after completing one. Maybe the issue is using Vulkan?

**Comment by elad335** [comment] 2022-06-21 20:46
Retest with atomic RSX FIFO Accuracy.

**Comment by Megamouse** [comment] 2023-03-07 21:47
closing this assuming it's fixed

**Closed by Megamouse** 2023-03-07 21:47 UTC
Labels: Potato
