### ISSUE TITLE
[Feature Request] would you pls release a uwp version for XBOX DEV Mode?

### ISSUE THREAD

**Issue by fanchengfei** [RPCS3/rpcs3#9331] opened 2020-11-24 06:36 UTC
the new xbox series's DEV Mode seems like a emulation hotspot.
because it has a 3.5ghz+ zen2 cpu

**Comment by illusion0001** [comment] 2020-11-24 06:38
Duplicate of #9315

**Closed** 2020-11-24 06:39 UTC
Labels: Meta: Duplicate

**Comment by BM-Hicham19** [comment] 2024-11-23 17:22
this would be awesome if it really happened
