### ISSUE TITLE
[Regression] Some games crash on boot on Ryzen CPUs and LLVM CPU znver* (#13534)

### ISSUE THREAD

**Issue by icyDouble** [RPCS3/rpcs3#13656] opened 2023-04-14 00:51 UTC
### Quick summary

whenever i try to launch beijing 2008 it will load up for a bit then crash, no errors pop up

### Attach a log file

[RPCS3.log](https://github.com/RPCS3/rpcs3/files/11227672/RPCS3.log)

### Attach capture files for visual issues

https://user-images.githubusercontent.com/130714971/231913482-2cd876b5-c99b-4556-a229-ef290192ea15.mp4

### System configuration

RPCS3 v0.0.27-14870-79d09d02 Alpha | master | FW 4.90 | Windows 11 22H2
AMD Ryzen 9 5900X | 24 Threads | 31.92 GiB RAM | AVX+ | FMA3
GPU: NVIDIA GeForce RTX 2080 Ti (531.41)

**Comment by AniLeo** [comment] 2023-04-14 11:49
Needs retest with latest build

**Comment by icyDouble** [comment] 2023-04-14 14:20
> Needs retest with latest build

Same deal happens, heres the new log 

[RPCS3.log](https://github.com/RPCS3/rpcs3/files/11233752/RPCS3.log)

https://user-images.githubusercontent.com/130714971/232070734-88b0f653-5ba4-449c-851d-8684374dba93.mp4

**Comment by Asinin3** [comment] 2023-04-15 05:02
Does it work on https://github.com/RPCS3/rpcs3-binaries-win/releases/download/build-6fbca1acfd5ee7da782f93995cff99dd09cfe48d/rpcs3-v0.0.27-14854-6fbca1ac_win64.7z ?

If not, does it work on https://github.com/RPCS3/rpcs3-binaries-win/releases/download/build-7081b89e976ad7f931c926022bd93ddd9778347c/rpcs3-v0.0.27-14845-7081b89e_win64.7z ?

**Comment by icyDouble** [comment] 2023-04-15 06:44
> Does it work on https://github.com/RPCS3/rpcs3-binaries-win/releases/download/build-6fbca1acfd5ee7da782f93995cff99dd09cfe48d/rpcs3-v0.0.27-14854-6fbca1ac_win64.7z ?
> 
> If not, does it work on https://github.com/RPCS3/rpcs3-binaries-win/releases/download/build-7081b89e976ad7f931c926022bd93ddd9778347c/rpcs3-v0.0.27-14845-7081b89e_win64.7z ?

going back to 14845 seemed to fix whatever problem i was having!

**Comment by Asinin3** [comment] 2023-04-15 06:48
The issue is not fixed, don't close it... You just worked-around the problem by using an old build.
If its working on 14845 but not 14854 (you didn't confirm if you tried both or not) then its broken by #13534

**Comment by icyDouble** [comment] 2023-04-15 06:59
no, it doesnt work on 14854

**Comment by Asinin3** [comment] 2023-04-15 09:28
@icyDouble Test https://github.com/RPCS3/rpcs3/pull/13670

**Comment by icyDouble** [comment] 2023-04-15 15:40
latest build 14876 still does not resolve the issue

**Comment by AniLeo** [comment] 2023-05-02 18:06
I can reproduce on Linux, black screen after linking stage

```
- SYS: RPCS3 v0.0.27-14957-bf190fd3 Alpha | master
- SYS: AMD Ryzen 9 5900HX with Radeon Graphics | 16 Threads | 15.01 GiB RAM | TSC: 3.294GHz | AVX+ | FMA3
- SYS: Operating system: POSIX, Name: Linux, Release: 6.2.13-1-MANJARO, Version: #1 SMP PREEMPT_DYNAMIC Wed Apr 26 21:52:27 UTC 2023
- RSX: Found vulkan-compatible GPU: 'AMD Radeon RX 6700M (RADV NAVI22)' running on driver 23.0.3
- RSX: Found vulkan-compatible GPU: 'AMD Radeon Graphics (RADV RENOIR)' running on driver 23.0.3
- SYS: Firmware version: 4.89
```

```
E SIG: Invalid or unsupported instruction (op=0, reg=24, d_size=0, a_size=0x0, i_size=0)
E SIG: decode_x64_reg_op(00007fb9b8b37a62): unsupported opcode: 0xc46270f734034585f64c897518c6853c
F {PPU[0x1000000] Thread (main_thread) [0x00815654]} SIG: Thread terminated due to fatal error: Segfault reading location 00000003e0044014 at 00007fb9b8b37a62.
Emu Thread Name: 'PPU[0x1000000] main_thread'.
```

**Comment by AniLeo** [comment] 2023-05-03 04:56
List of games from 13534:

- Blitz: The League II 
- Ratchet and Clank Future: Tools of Destruction
- Resistance 2
- 007: Goldeneye

**Comment by Nekotekina** [comment] 2023-05-05 09:41
Try #13807

**Comment by AniLeo** [comment] 2023-05-05 19:56
Verified as fixed, closed

**Closed by AniLeo** 2023-05-05 19:56 UTC
Labels: CPU, Regression
