### ISSUE TITLE
The Guide Fate Paradox hang , not booting

### ISSUE THREAD

**Issue by zminhquanz** [RPCS3/rpcs3#1803] opened 2016-06-20 02:06 UTC
![image](https://cloud.githubusercontent.com/assets/11285640/16181460/5cbf87cc-36c6-11e6-88de-b831fa719c54.png)

{PPU[0x1] Thread (main_thread) [0x0039af28]} cellResc TODO: cellRescSetConvertAndFlip(cntxt=*0x15f4000, idx=0x0)
{PPU[0x1] Thread (main_thread) [0x0039aec8]} cellResc TODO: cellRescSetWaitFlip()
Log bug appear similarly Disgaea 4 , it can't boot
CPU : Core 2 Quad Q6600
GPU : Geforce GT 730 GDDR5 Kepler
API : OpenGL , DirectX 12
I remember past build 0.0.0.6 , Disgaea 4 and The Guide Fate Paradox , it have worked on my spec PC . But when build 0.0.0.9 release , it haven't worked and appear log bug
My Log : https://gist.github.com/zminhquanz/ffa65aeaafbbaea89558922233700a54

**Comment by raven02** [comment] 2016-06-20 02:18
It is a known issue .It can boot up using LLE modules (vdec+dumx+dumxpamf) however still not able to in-game .

Duplicate of https://github.com/RPCS3/rpcs3/issues/1725

**Closed by raven02** 2016-06-20 02:18 UTC

**Comment by AniLeo** [comment] 2016-06-20 16:43
(You need to LLE cellResc)
