### ISSUE TITLE
Stuck unpacking PS3UPDAT.PUP

### ISSUE THREAD

**Issue by d33tah** [RPCS3/rpcs3#2474] opened 2017-03-05 14:04 UTC
Tested on file with MD5 b2483b4abc157494447c9c409c036041. Judging by file descriptors, 191MB (97%) of the file was read. Please let me know what other details you need.

**Comment by SakataGintokiYT** [comment] 2017-03-05 14:14
Duplicate of #2462

**Comment by raven02** [comment] 2017-03-05 14:18
@d33tah , on linux or windows platform ?

**Comment by d33tah** [comment] 2017-03-05 14:56
@raven02 Linux

**Comment by raven02** [comment] 2017-03-05 15:17
Thanks @d33tah .Then i close this one as duplicate of #2462

**Closed by raven02** 2017-03-05 15:17 UTC
