### ISSUE TITLE
Persona 5 crash in neutral fights

### ISSUE THREAD

**Issue by Kratoszx** [RPCS3/rpcs3#2997] opened 2017-07-13 09:58 UTC
allways crashes on same spot when facing an enemy
this is whats pops up in Log
 
F {rsx::thread} class std::runtime_error thrown: Invalid location (offset=0x0, location=0xffffffff)
(in file C:\rpcs3\rpcs3\Emu\RSX\RSXThread.cpp:83)...

Have tried all kind of setting and this is what allways bothers me
i managed to obtain in game 23-30fps now its playable  

my machine:
 i7-6700k 4.0ghz
GTX1050ti 4gb
RAM: 16GB

Setings that i use for Persona 5 
PPU: (LLVM)
SPU: (ASMJIT)
Firmware: Automatically
VULKAN
Framelimit: Auto

**Comment by AniLeo** [comment] 2017-07-13 10:12
Duplicate of #2936

**Closed** 2017-07-13 10:12 UTC
