### ISSUE TITLE
Toolbar icons missing (Linux/Qt)

### ISSUE THREAD

**Issue by gasinvein** [RPCS3/rpcs3#3279] opened 2017-08-20 11:03 UTC
Subj. Buttons on toolbar work, but they are very small and missing icons.
![screenshot_20170820_140012](https://user-images.githubusercontent.com/4569691/29494316-2cae0cf4-85b0-11e7-8349-7b5452e3959d.png)

**Comment by Megamouse** [comment] 2017-08-20 11:12
assign to hcorion hehe

**Comment by scribam** [comment] 2017-09-02 20:46
@gasinvein Would you mind testing the PR #3376 and telling me if the issue is still there ?

**Comment by gasinvein** [comment] 2017-09-02 23:02
@scribam Yes, it works.

**Closed** 2017-09-11 19:45 UTC
