### ISSUE TITLE
Diagonal triangles with gas effects in NieR on Vulkan

### ISSUE THREAD

**Issue by linkmauve** [RPCS3/rpcs3#6952] opened 2019-11-05 20:44 UTC
This is on rpcs3 508ffcb7759b1a9290e61e86a62775757b66b0c0 but it has been happening for as long as I’ve used this emulator, about two weeks ago. I’m running it using anv on an i5-8350u CPU with an UHD 620 GPU.

Another game where this happens is MGS4, on the bottom-right tomb in this rrc for instance: https://files.sshnuke.net/BLUS30109_20191029014409_capture.7z

This doesn’t happen on OpenGL at all.

![wayland-screenshot-2019-10-28_22-46-44](https://user-images.githubusercontent.com/7755816/68243853-bccab000-0013-11ea-9f03-569c2fd0ce3e.png)

![wayland-screenshot-2019-11-05_21-41-22](https://user-images.githubusercontent.com/7755816/68244510-43cc5800-0015-11ea-800c-eff2f27f38fd.png)

**Comment by AniLeo** [comment] 2019-11-05 23:32
Strict Rendering Mode fixes that, it's a problem on Intel iGPUs

**Comment by linkmauve** [comment] 2019-11-06 00:02
Do you have a link to a bug report for their driver?

**Comment by kd-11** [comment] 2019-11-06 09:13
> This doesn’t happen on OpenGL at all.

Which OpenGL driver? There is a mesa one and an intel one. Afaik the mesa one barely works at all.

As for steps, firstly, check if the problem is fixed with strict mode. You'll also have to check if the problem is also there using their proprietary drivers on windows, or get someone else to help you with that. As for bug reports; there are no bug reports for intel graphics hardware as it is not supported. Feel free to open one but you may want to temper your expectations.

**Comment by AniLeo** [comment] 2019-11-06 09:37
I don't think it happens on Windows proprietary, just mesa Intel

**Comment by AniLeo** [comment] 2020-03-20 19:25
I'm still able to reproduce completely broken output on mesa, even with new Iris mode

**Comment by AniLeo** [comment] 2020-04-30 06:14
Being tracked on mesa at https://gitlab.freedesktop.org/mesa/mesa/issues/2671

RPCS3 already has an alternative path that avoids this, using Strict Rendering Mode. Since we're following spec either way, I'll close the issue here since this is a driver bug, and therefore will be tracked on mesa.

**Closed by AniLeo** 2020-04-30 06:14 UTC
Labels: Driver: Intel, OS: Linux
