### ISSUE TITLE
[Regression] Dragon Quest Builders crashes with "Working buffer not big enough" after pull 6069

### ISSUE THREAD

**Issue by lostromb** [RPCS3/rpcs3#6417] opened 2019-08-27 04:34 UTC
Testing on Dragon Quest Builders BLJM61311 and the latest master build I have (0.0.6-8568).
After about a minute of gameplay it crashes with this log message:
```
F {RSX [0x003d224]} RSX: class std::runtime_error thrown: [texture upload buffer] Working buffer not big enough, buffer_length=268435456 allocated=251657728 requested=16777224 guard=33554432 largest_pool=16777728
(in file C:\projects\rpcs3\rpcs3\Emu\RSX\Common\ring_buffer_helper.h:80)
```

I bisected versions and found the regression occurred in [PR 6069](https://github.com/RPCS3/rpcs3/pull/6069), which was merged to master in 0.0.6-8204
This in on Windows 10, Ryzen 2600X, Nvidia Titan X, Vulkan, and all settings (including resolution scale) set to default. Log file is attached.
[RPCS3.log.gz](https://github.com/RPCS3/rpcs3/files/3544274/RPCS3.log.gz)

**Comment by alafieno** [comment] 2019-09-01 00:36
Same issue here on v0.0.7-8623-432364cb, on Vulkan. Log file attached.

Windows 10, i7-4770k, GTX 1060
[RPCS3.log.gz](https://github.com/RPCS3/rpcs3/files/3562975/RPCS3.log.gz)

**Comment by kd-11** [comment] 2019-10-02 08:53
Provide a save file and preferrably attach a small clip of how exactly you get the error to appear. I generally have little to no understanding of mechanics in JP games.

**Comment by Illynir** [comment] 2019-10-02 11:37
Works normally for me.

**Comment by lostromb** [comment] 2019-10-05 04:43
It seems to happen a lot more reliably in Terra Incognita mode. It might have something to do with the amount of custom assets that get loaded in that mode.
Also note that I am playing with the [unofficial English patch for the game](https://froidromhacks.com/index.php/2018/02/15/dragon-quest-builders-bljm61311-v0-9-english-patch-ps3/), but it is unrelated to this bug because the game used to emulate perfectly with the patch.

Anyways, my save files are attached, and the [video to repro the bug is here](https://www.youtube.com/watch?v=e-Xx45xIIf0).
[Dragon Quest Builders BLJM61311 save file.zip](https://github.com/RPCS3/rpcs3/files/3692867/Dragon.Quest.Builders.BLJM61311.save.file.zip)

**Comment by Illynir** [comment] 2019-10-05 21:57
Yes, I have already confirmed the problem and pointed to the game's streaming mechanism.
The problem being that it takes much longer to trigger for us, it takes almost 15 minutes so it's quite annoying to debug.

The rest will depend on KD.

**Comment by kd-11** [comment] 2019-10-05 22:28
I was unsuccessful in reproducing this last time I tried. I gave up after wandering around for a half hour. I''ll push some commits with theoretical fixes for the crash tomorrow and you guys can check if it gets fixed. Fortunately there aren't many parts that deal with texture streaming, so it may be fixable without me reproducing.

**Comment by lostromb** [comment] 2019-10-06 01:49
Sure, that should be fine. For whatever reason my hardware always seems to trigger it within a minute or so of gameplay so if you've got a WIP build then it'll be super easy for me to test. (I'll just hand the controller over to my 5-year-old and she'll handle the rest)

**Comment by kd-11** [comment] 2019-10-08 08:11
After thinking about it some more, it would be better to restructure memory management once and for all. The current solution is not optimal and greatly limits emulator architecture due to fears of triggering heap memory issues. I should have something working in a few days.

**Comment by kd-11** [comment] 2019-11-09 13:48
Test with https://ci.appveyor.com/project/kd-11/rpcs3/builds/28737093

**Comment by lostromb** [comment] 2019-11-09 23:33
Seems to work great! I can't reproduce the DQB crash anymore. I tested a smattering of other games (Driver SF, Katamari, Burnout Paradise) and didn't see any noticeable regressions. Do you want logs or anything?

**Comment by kd-11** [comment] 2019-11-10 14:53
Fixed by https://github.com/RPCS3/rpcs3/pull/6972

**Closed by kd-11** 2019-11-10 14:53 UTC
Labels: Need Information
