### ISSUE TITLE
red dead redemption not worked anymore

### ISSUE THREAD

**Issue by JIuBeP** [RPCS3/rpcs3#9158] opened 2020-10-28 16:55 UTC
## Quick summary

red dead redemption doesn't work anymore, it doesn't even load up to the menu!

## Details
win 7 x64 ryzen 2600/ ram 8gb/gtx 950 
vulkan beta driver 451.98

game doesn't work anymore, it doesn't even load up to the menu! a month ago I could run at 5-17fps. im also loading log, I don't know what happened, can you help?

#### 1. Please attach RPCS3's log.
[RPCS3.log](https://github.com/RPCS3/rpcs3/files/5453506/RPCS3.log)

**Comment by RainbowCookie32** [comment] 2020-10-28 17:04
Can't reproduce. There's also a pirated game in the log and horrible settings
![image](https://user-images.githubusercontent.com/16805474/97470564-6c381b00-1926-11eb-9fd9-dbeb6c1c521f.png)

**Comment by AniLeo** [comment] 2020-10-28 17:07
---

**Please read [**the guidelines**](https://github.com/RPCS3/rpcs3/blob/master/.github/CONTRIBUTING.md) before opening an issue.**

Remember that the GitHub Issue Tracker is not the place to [**ask for support**](https://github.com/RPCS3/rpcs3/wiki/How-to-ask-for-Support) or to [**submit Game Compatibility reports**](https://github.com/RPCS3/rpcs3/wiki/Game-Compatibility).

The issue has been marked as **Invalid** and closed.

**Closed** 2020-10-28 17:07 UTC
