### ISSUE TITLE
[Regression] Discord RPC not working on linux.

### ISSUE THREAD

**Issue by justunscored** [RPCS3/rpcs3#14941] opened 2023-12-27 01:18 UTC
### Quick summary

After testing many builds today
**rpcs3-v0.0.20-13177-d6aa834b_linux64.AppImage**: RPC works 
**rpcs3-v0.0.20-13178-580bd2b2_linux64.AppImage**: RPC Does not work.

### Details

I was able to identify the commit that caused the issue with RPC on linux: https://github.com/RPCS3/rpcs3/pull/11315/commits/580bd2b25eba04f9f30d3ed1df3b3f31e0387b02#diff-8ea4f7e8cc31210570cb9ef50d9b3ebc3cc94114d59fbcaff82e2f4e2103fd53

![RPCS3 0 0 20-13177-d6aa834b](https://github.com/RPCS3/rpcs3/assets/130622945/aeb0aeb0-dbbc-4226-b33c-75e2b4857fae)

I found that, that it is necessary to either launch a game or to disable and enable discord RPC for RPC to function on builds that had it working.

This was using flatpak discord with file links so that RPC works, flatpak isn't the issue here though as it was working previously from my testing in build 0.0.20-13177. 

### Build with regression

rpcs3-v0.0.20-13178

### Attach two log files

**N/A**
[rpcs3-v0.0.20-13177-d6aa834b_linux64.log](https://github.com/RPCS3/rpcs3/files/13774378/rpcs3-v0.0.20-13177-d6aa834b_linux64.log)
[rpcs3-v0.0.20-13178-580bd2b2_linux64.log](https://github.com/RPCS3/rpcs3/files/13774379/rpcs3-v0.0.20-13178-580bd2b2_linux64.log)

### System configuration

Operating System: Arch Linux

**Comment by Mrlinkwii** [comment] 2023-12-27 09:27
duplicate of #13519 i think

**Closed** 2023-12-27 10:05 UTC
Labels: OS: Linux
