### ISSUE TITLE
Ratchet and Clank tools of destruction - E3 build. Ratchet fall though floor.

### ISSUE THREAD

**Issue by atomic83GitHub** [RPCS3/rpcs3#7130] opened 2019-12-24 11:52 UTC
I use the latest build of RPCS3 until now. https://github.com/RPCS3/rpcs3/commit/b47eef77f4b6b9ffc711a11aac07dfc9b8719c2a

This issue is exclusive to the E3 preview version of the game.
- When starting a level (Metropolis in the preview) Ratchet fall though floor and you can't progress. 
- The game is also prone to crashing.

My specs: AMD FX 8350 / GTX 1060 / Windows 10 64bits.

**Comment by Hopefullyidontgetbanned** [comment] 2019-12-27 02:17
do you have a link to this build?, otherwise this can't be fixed or even looked into

**Comment by AniLeo** [comment] 2019-12-27 02:18
Without someone having the game and testing or alternatively any debug information that shows what's the issue is provided, yeah, there's nothing to do here

**Comment by Hopefullyidontgetbanned** [comment] 2019-12-27 02:19
i should mention this is common in the normal build of the game on most levels

**Comment by atomic83GitHub** [comment] 2019-12-27 13:59
It is available here: https://drive.google.com/file/d/1B49Y16TkP7SC1Q7VeockxkPdCbZc_PwQ/view

**Comment by LadyLeia001** [comment] 2019-12-28 02:09
im experiencing the same problems though the game randomly works fine, i can walk around shoot and everything even finish the level with a few other problems for some resion i can move up and left but not up and right, not sure if its my control setup but i havent had it happen with other games but most of the time i fall though the ground. hopeing this problem can be fixed soon due to the build haveing a lot of unused content in its files im working on datamineing. (that link atomic83GitHub posted is the same disk as the one ive been useing)

**Comment by LadyLeia001** [comment] 2019-12-28 03:39
as i understand it, the files todo with the collision are stored sepretly from the rest of the level data, the bug is triggered by some kind of inability to load the collisions, often it fixes after 1-4 deaths but other times it will never fix itself, thats at least how i understand it, due to how baddys can be seen falling as well, though the same cant be said about boxes as well as partical effects can be seen when you hit the ground as you fall.

so its as likely its a bug todo with the enemy/player controller thinking its falling when its not the case. this could be todo with the player landing on the ground but instead of being pushed up a mathematical error is happing making the enitys fall down into the void, or something else, i cant say due to not having the time to debug the emulator but those are what i expect to be the problems (with my limited knowledge on how emulators work).

**Comment by AniLeo** [comment] 2019-12-29 11:55
Sorry, you can't link to the game, even though it's not a release version they're still copyrighted files.

**Comment by LadyLeia001** [comment] 2019-12-30 20:27
yeah AniLeo that's why i didn't link to it, i was just saying that that build was the same one im haveing problems with its serial is: "BCUS98153" if there is anything i can do to help you fix this problem ill do it.

**Comment by jeremybris** [comment] 2020-02-18 21:42
I think this may have been fixed recently. It is also reported within #4258 , if it is not. So, this should probably be closed.

**Comment by AniLeo** [comment] 2020-02-29 19:49
Closing as fixed, ping if you still can reproduce

**Closed by AniLeo** 2020-02-29 19:49 UTC
Labels: Need Information
