### ISSUE TITLE
PR #6381 by Nekotekina (build 8559) creates error 

### ISSUE THREAD

**Issue by huskereurocat** [RPCS3/rpcs3#6391] opened 2019-08-22 02:48 UTC
PR #6381 by Nekotekina (build 8559) creates error below. The issue is now contained in the PR#6385 (8561 build) as well. 

Asinine told me that this build contains the fix. https://github.com/RPCS3/rpcs3-binaries-win/releases/download/build-7c5bde4aebf0251a5566d3fd133687dc9ae0f7e7/rpcs3-v0.0.6-8546-7c5bde4a_win64.7z
![Desktop Screenshot 2019 08 21 - 20 39 03 11](https://user-images.githubusercontent.com/52609668/63482109-4fb86d00-c45d-11e9-8536-5a52d756ab47.png)

**Comment by Nekotekina** [comment] 2019-08-22 04:00
Need RPCS3.log

**Comment by huskereurocat** [comment] 2019-08-22 04:04
[RPCS3.log](https://github.com/RPCS3/rpcs3/files/3528210/RPCS3.log)

**Comment by Nekotekina** [comment] 2019-08-22 04:15
It's empty.

**Comment by huskereurocat** [comment] 2019-08-22 04:48
That's probably because I can't get the program to open how without this error popping up. 

![Desktop Screenshot 2019 08 21 - 23 47 21 37](https://user-images.githubusercontent.com/52609668/63486690-2ce28480-c46e-11e9-8989-ffd310eb90e6.png)

**Comment by huskereurocat** [comment] 2019-08-22 04:50
this may be of more help. 
[RPCS3.log](https://github.com/RPCS3/rpcs3/files/3528306/RPCS3.log)

**Comment by huskereurocat** [comment] 2019-08-22 05:21
[RPCS3.log](https://github.com/RPCS3/rpcs3/files/3528374/RPCS3.log)
This is a log of trying to rebuild the PPU cache. When you say its empty you mean the log wayyyyy at the bottom of the printout?

**Comment by SutandoTsukai181** [comment] 2019-08-22 08:35
Didn't happen to me since I don't use that build, but someone in #help got a similar issue using build 8561 that was fixed by using an older build (kd-11's fbo-fixes branch)

![unknown-11](https://user-images.githubusercontent.com/52977072/63499445-8d0a1280-c4d0-11e9-9251-6f59622f0327.png)

They posted their log, the bot said it wasn't empty 
[RPCS3.log](https://github.com/RPCS3/rpcs3/files/3529097/RPCS3.log)

**Comment by huskereurocat** [comment] 2019-08-22 08:52
With build 8566 we made a little progress. I can now get back to the point where I was at the beginning of this issue. I get into RPCS3 and open NCAA14. When in the menu to go into an exhibition game and I double click to move into the game from the menus,I get this error. 
![Desktop Screenshot 2019 08 22 - 03 50 22 50](https://user-images.githubusercontent.com/52609668/63500734-06cddc00-c490-11e9-89c9-8d9816226957.png)
Here is the RPCS3 Log as well. 
[RPCS3.log](https://github.com/RPCS3/rpcs3/files/3529177/RPCS3.log)

**Comment by spyropt** [comment] 2019-08-22 09:29
even with 8560 i get a fatal error with gt5
[RPCS3.zip](https://github.com/RPCS3/rpcs3/files/3529353/RPCS3.zip)
![image](https://user-images.githubusercontent.com/34097932/63503620-becaab80-c4c7-11e9-8b65-3f3bd2c015c9.png)

**Comment by huskereurocat** [comment] 2019-08-22 09:36
That's because everything coming forward from build 8559 has the code that creates the error. 8546 is the last build that won't create the error, for me at least. Be patient, the dev team will get it corrected!

**Comment by Asinin3** [comment] 2019-08-22 11:32
Not really correct. 8559 introduced the issue where not a single game would boot which was immediately fixed. However, the fix wasn't made in a pull-request, it was pushed directly. As such if you download 8559 normally e.g through https://rpcs3.net/compatibility?b you get the build from when 8559 merged aka broken. So don't ever use that. Instead you need to commit that neko pushed shortly after https://ci.appveyor.com/api/buildjobs/t3ywpgh8ra4g0fpu/artifacts/rpcs3-v0.0.6-8560-c43a126f_win64.7z so use this if you want to test 8559/neko's PR.

This is the only time I'm aware of something like this has happened in the two years I've been here.

**Comment by huskereurocat** [comment] 2019-08-22 11:44
Sorry for the mistake. I just tested the build that Asinin3 linked above 8560 and the error is created just before a going into a live game, during the last screen of the menus.  Attached pic below. 
![Desktop Screenshot 2019 08 22 - 06 41 12 28](https://user-images.githubusercontent.com/52609668/63511999-43a5cd00-c4a8-11e9-81a5-fd3218f53942.png)

**Comment by B-Knight49** [comment] 2019-08-22 12:01
Same issue here for LittleBigPlanet 2. Build 8559 causes instant crashing (Like @Asinin3 mentions) but 8561 and 8566 cause crashing just as the intro cinematic starts. 
Let me know if you need logs.

![image](https://user-images.githubusercontent.com/26165117/63512961-e8da9880-c4dc-11e9-9d12-59dba03f1391.png)

**Comment by adrianocolvero** [comment] 2019-08-22 13:12
[RPCS3.log](https://github.com/RPCS3/rpcs3/files/3530255/RPCS3.log)

**Comment by Asinin3** [comment] 2019-08-22 13:34
So no one tested the build i linked? What needs to be tested is 8560 https://ci.appveyor.com/api/buildjobs/t3ywpgh8ra4g0fpu/artifacts/rpcs3-v0.0.6-8560-c43a126f_win64.7z

Against https://github.com/RPCS3/rpcs3-binaries-win/releases/download/build-ec9b896fbf6339911b9b8dd1b2feae88ca68df96/rpcs3-v0.0.6-8561-ec9b896f_win64.7z and https://github.com/RPCS3/rpcs3-binaries-win/releases/download/build-7c5bde4aebf0251a5566d3fd133687dc9ae0f7e7/rpcs3-v0.0.6-8546-7c5bde4a_win64.7z

If its working in 8546 but broken by 8560 then Neko's PR is the cause even with the fix he pushed. If its working in 8560 but broken in 8561 then it was caused by Elad's PR directly afterwards. Thats what the devs need to know. Regardless im testing NCAA 14 right now.

**Comment by Asinin3** [comment] 2019-08-22 13:44
Nekotekina has informed me that it was broken by VS 2017, he has an open Pull Request to move to 2019 which should fix it, you can test it here https://github.com/RPCS3/rpcs3/pull/6394

**Comment by Nekotekina** [comment] 2019-08-22 16:57
#6394 built successfully, please test.

**Comment by digitaldude555** [comment] 2019-08-22 17:16
NCAA crash is fixed.

**Comment by huskereurocat** [comment] 2019-08-22 21:50
Crash is fixed. Thank you!!!!

**Comment by B-Knight49** [comment] 2019-08-24 12:24
Fixed crash for LBP2.

**Comment by AniLeo** [comment] 2019-08-29 12:10
Closing as fixed

**Closed by AniLeo** 2019-08-29 12:10 UTC
