### ISSUE TITLE
Buzz! Quiz World crashing issue

### ISSUE THREAD

**Issue by MarcusRivet** [RPCS3/rpcs3#13505] opened 2023-03-06 06:00 UTC
### Quick summary

The game Buzz Quiz World used to work fine half a year ago, now it crashes. I've made a clean new reinstall of Windows and every single file related to RPCS3 and the game to ensure the fault is not on my end.

### Details

There has been an issue since an update half a year ago where Buzz Quiz World started crashing randomly. I have now finally been able to reinstall my windows, make a complete new copy of RPCS3 and of the game to ensure that the crash is NOT caused by any bad or corrupt files on my half. It happens very randomly, sometimes you can play the game just fine for an hour, other times you just get a crash after 5 minutes, but most often happens around 15 minutes of playing the game. I let the game run over night with a macro until it crashed so I could get the log file. Unfortunately I was banned a year ago from your discord server for unknown reason (Think I posted a controversial political opinion or just a controversial message), so I haven't been able to check the log files with the RPCS3 bot, but I will drop it here.

### Build with regression

0.0.27-14800-0d34b979

### Attach two log files

Log file 1: https://mega.nz/file/lHZEAA4Z#-ip3ib_Okzyy7b-2C68O2b_cA1VDWLbIC3E67smZ-z8
Log file 2: https://mega.nz/file/UWgBEBab#dF9_LHIm1lUd7AYQ8c6_4Uxyhf7Vn6BftGv6pLHHqOM

### System configuration

RTX 3090
i7-12700k (e-cores disabled, avx-512 enabled)
2x16gb RAM
asus z690 MBO

**Comment by RipleyTom** [comment] 2023-03-18 16:20
Download link for the log expired.

**Comment by MarcusRivet** [comment] 2023-03-19 14:23
Ah sorry, I should have known wetransfer only holds uploads for a week. Anyhow I got 2 log files now after running it over night. 

Log file 1: https://mega.nz/file/lHZEAA4Z#-ip3ib_Okzyy7b-2C68O2b_cA1VDWLbIC3E67smZ-z8
Log file 2: https://mega.nz/file/UWgBEBab#dF9_LHIm1lUd7AYQ8c6_4Uxyhf7Vn6BftGv6pLHHqOM

**Comment by dmandrone** [comment] 2023-04-17 17:02
Can confirm, happening with me as well

**Comment by dotunomidiora** [comment] 2023-04-19 23:38
I can also confirm the game crashes.

**Comment by Asinin3** [comment] 2023-07-23 02:48
>The game Buzz Quiz World used to work fine half a year ago, now it crashes

Crashes.. where? When you launch the game.. what?
Also you say it used to work fine but didn't bother testing old builds to find where it broke. 

First: Check if its still broken on latest build of RPCS3. If it is, do proper regression testing. 
Go to https://rpcs3.net/compatibility?b and download old builds, go back ~3 months at a time until you find the build where it works, then narrow it down between the last working and last broken build by going inbetween those build dates to quickly find the exact build with the issue. Then tell us exactly where it broke. If you don't this issue is unlikely to be fixed anytime soon.

Remember you only need to replace the RPCS3.exe file, all other files can remain in your RPCS3 folder when going back to old builds.

**Comment by johntaxmi** [comment] 2023-07-23 21:30
I do not know if my comment will help. But the game Buzz! Quiz World [BCES 00647] works perfectly on 0.0.17-12650.
If someone want to start the research they can have that version as the base to work upwards to the latest one.

*PS I can also confirm that it crashes randomly while playing in random times. (idk how random they are though, maybe there is a patern but I did not get into more trynig)

**Comment by MarcusRivet** [comment] 2023-07-23 23:28
I also recently noticed after testing with the latest builds now that it seems to be working again (so far). I did test with some old builds, but wasn't able to locate after which build the crashing started.. The crashing seemed to only happen while playing multiple people together, and it could take anywhere from 10 minutes to 5 hours sometimes of playing before a crash occured. It has been overall very hard to troubleshoot and figure out where or what or when this started happening or if there was anything specific causing the crash (I even tried resetting all my overclock settings and clean reinstalling everything multiple times thinking it was my PC being the culprit, but I've tried multiple PC's so I've ruled that out by now as well as other people confirming my issue here). BUT nevertheless it does seem to work again with the latest builds, I really hope so and will keep testing. I've set up a macro so that the game plays by itself with 4 players through the night on repeat and it has survived 2 nights so far and a couple games I've played with my family (which could just be really lucky, but it hasn't survived an entire night before), so ill keep testing and ill keep you updated.

**Comment by MarcusRivet** [comment] 2023-07-23 23:33
That does help a lot so thank you so much!

> I do not know if my comment will help. But the game Buzz! Quiz World [BCES 00647] works perfectly on 0.0.17-12650. If someone want to start the research they can have that version as the base to work upwards to the latest one.
> 
> *PS I can also confirm that it crashes randomly while playing in random times. (idk how random they are though, maybe there is a patern but I did not get into more trynig)

**Comment by johntaxmi** [comment] 2023-07-28 21:24
> I also recently noticed after testing with the latest builds now that it seems to be working again (so far). I did test with some old builds, but wasn't able to locate after which build the crashing started.. The crashing seemed to only happen while playing multiple people together, and it could take anywhere from 10 minutes to 5 hours sometimes of playing before a crash occured. It has been overall very hard to troubleshoot and figure out where or what or when this started happening or if there was anything specific causing the crash (I even tried resetting all my overclock settings and clean reinstalling everything multiple times thinking it was my PC being the culprit, but I've tried multiple PC's so I've ruled that out by now as well as other people confirming my issue here). BUT nevertheless it does seem to work again with the latest builds, I really hope so and will keep testing. I've set up a macro so that the game plays by itself with 4 players through the night on repeat and it has survived 2 nights so far and a couple games I've played with my family (which could just be really lucky, but it hasn't survived an entire night before), so ill keep testing and ill keep you updated.

Is there any way that you can share with me your configuration settings? CPU/GPU/EMULATOR etc

**Comment by AniLeo** [comment] 2024-01-01 15:42
Closing as completed since the OP stated the issue is solved for them. If someone else can reproduce the issue, you can open a new report referencing this one with new logs.

**Closed by AniLeo** 2024-01-01 15:42 UTC
Labels: Need Information
