### ISSUE TITLE
Atelier Rorona Plus (BLES02050) crash

### ISSUE THREAD

**Issue by ddurschlag** [RPCS3/rpcs3#7507] opened 2020-02-17 01:54 UTC
## Quick summary
Game froze, looks like a null ref:
F {PPU[0x1000000] Thread (main_thread) [0x00154550]} VM: Access violation reading location 0x0 (unmapped memory)

## Details
Windows 10, i7-9700k, GTX 1660 Ti
Was hitting back from item selection screen during synthesis.
RPCS3 subsequently hung when I tried to exit.

Might be the same as #3042 , but that mentions random addresses and this is notably 0x0.

[RPCS3.log](https://github.com/RPCS3/rpcs3/files/4211472/RPCS3.log)

**Comment by Asinin3** [comment] 2021-09-15 23:25
Closing, game not listed as playable. Fatal access violations are a symptom of an issue and not the cause so not helpful for debugging. Plus no clear way to reproduce.

**Closed by Asinin3** 2021-09-15 23:25 UTC
