### ISSUE TITLE
Can't select Null pad handler

### ISSUE THREAD

**Issue by RainbowCookie32** [RPCS3/rpcs3#8841] opened 2020-09-05 23:10 UTC
## Quick summary
Can't use the Null handler on Pad settings.

## Details
The option can be selected but when you click Save, the Keyboard handler is used instead. It always goes back to that, regardless of what handler was previously selected.

Log doesn't really show anything of use, [but here it is anyways.](https://github.com/RPCS3/rpcs3/files/5178837/RPCS3.log)

**Comment by Megamouse** [comment] 2020-09-09 19:00
It's a fallback if no controller was assigned.
Idk why you would select null for all players

**Comment by Megamouse** [comment] 2020-09-09 19:01
I guess it can be removed, since we now have ingame reassignment

**Comment by dio-gh** [comment] 2020-09-19 17:32
> Idk why you would select null for all players @Megamouse

The actual issue is that I/we wanted to test keyboard and mouse passthrough without regular controllers interfering. WIth any other option set, most games will complain about controller not being attached (e.g. if i set a DS4 handler and my DS4 isn't on), or will ignore the keyboard and mouse input (because they'll assume it's for a 2nd player or something, couldn't figure that one out).

I wanted to use kb&m passthrough as normal, and I could only achieve that by hacking in the `Null` pad option into the config files directly. Used CS:GO for testing, Unreal Tournament I didn't manage to get to work proper no matter what. This used to work a year or so ago, so this is a regression.

**Closed** 2020-09-22 04:59 UTC
Labels: GUI, Input
