### ISSUE TITLE
Silent Hill Downpour fails to load with "Verification failed" error

### ISSUE THREAD

**Issue by Psycho-A** [RPCS3/rpcs3#5879] opened 2019-04-22 19:13 UTC
Since the build 0.0.6-7967 and bumping PPU modules to v3, game is no longer loading with this log error:
`F {PPU[0x1000000] Thread (main_thread) [0x01e304d8]} class std::runtime_error thrown: Verification failed: (in file c:\projects\rpcs3\rpcs3\loader\psf.cpp:116)`

Tested on Windows 7 x64 with NVidia GTX 750 Ti, Core i5-760 CPU. 
The emulator or renderer settings don't matter.

**Comment by kd-11** [comment] 2019-04-22 21:21
This is likely just a corrupt save. Try removing all the savedata for the game and see if it boots.

**Comment by elad335** [comment] 2019-04-23 01:25
duplicate of #3449, solution is there as well.

**Closed** 2019-04-23 05:46 UTC

**Comment by Psycho-A** [comment] 2019-04-23 09:03
I didn't knew about that. Thanks! Killing old savegames helped.
