### ISSUE TITLE
[Feature request] Suspend support, mainly to improve experience on Steam Deck

### ISSUE THREAD

**Issue by cmalvi** [RPCS3/rpcs3#12704] opened 2022-09-25 09:07 UTC
### Quick summary

Would be very cool to have suspend support so you don't have to close rpcs3 if you want to put the device on suspend mode

**Comment by AniLeo** [comment] 2022-09-25 13:56
Duplicate of #12123

**Closed by AniLeo** 2022-09-25 13:56 UTC
