### ISSUE TITLE
BLUS30128 NFL Head Coach 09

### ISSUE THREAD

**Issue by Kiely403** [RPCS3/rpcs3#11915] opened 2022-05-02 18:47 UTC
## Quick summary
When loading into a career mode game it freezes jut after coin toss when choosing play for kick-off.
![NFLHC09Crash](https://user-images.githubusercontent.com/104738446/166305808-bcf9f512-03e8-4455-944c-ea05da4bd73a.jpg)

## Details

Game loads fine all menus work, Load into career mode and attempt to play a game and it freezes at described point. This screenshot is the exact point every time. The following error is displayed in the log: 
F {RSX [0x0997500]} SIG: Thread terminated due to fatal error: Verification failed
(in file C:\Users\ContainerAdministrator\AppData\Local\Temp\cirrus-ci-build\rpcs3\Emu\RSX\Common\texture_cache.h:305[:7], in function is_expired) (error=0x7e)

Please provide your system configuration:
* Windows 10
* AMD Ryzen 5 4600H
* GeForce GTX 1650 Ti
* Driver version: 30.0.15.1169
* etc.

####  Please attach RPCS3's log.
[RPCS3.zip](https://github.com/RPCS3/rpcs3/files/8605364/RPCS3.zip)

**Comment by Kiely403** [comment] 2022-05-02 19:10
Attached screenshot with details overlay
![Untitled](https://user-images.githubusercontent.com/104738446/166309795-d755bf06-fada-4015-9ed8-1e31a731c099.jpg)

**Comment by Juan12233** [comment] 2022-05-03 15:39
> ## Por favor, no pida ayuda ni informe regresiones de compatibilidad aquí, use el servidor o [foros ](https://forums.rpcs3.net/)[RPCS3 Discord en](https://discord.me/RPCS3) su lugar.[](https://forums.rpcs3.net/)
> ## Sumario rápido
> Cuando se carga en un juego en modo carrera, se congela justo después del lanzamiento de la moneda al elegir el juego para el inicio. ![NFLHC09Accidente](https://user-images.githubusercontent.com/104738446/166305808-bcf9f512-03e8-4455-944c-ea05da4bd73a.jpg)
> 
> ## Detalles
> El juego se carga bien, todos los menús funcionan, carga en el modo carrera e intenta jugar un juego y se congela en el punto descrito. Esta captura de pantalla es el punto exacto cada vez. El siguiente error se muestra en el registro: F {RSX [0x0997500]} SIG: Subproceso terminado debido a un error fatal: Verificación fallida (en el archivo C:\Users\ContainerAdministrator\AppData\Local\Temp\cirrus-ci-build\rpcs3 \Emu\RSX\Common\texture_cache.h:305[:7], en función is_expired) (error=0x7e)
> 
> Proporcione la configuración de su sistema:
> 
> * ventanas 10
> * AMD Ryzen 5 4600H
> * GeForce GTX 1650 Ti
> * Versión del controlador: 30.0.15.1169
> * etc.
> 
> #### Adjunte el registro de RPCS3.
> [RPCS3.zip](https://github.com/RPCS3/rpcs3/files/8605364/RPCS3.zip)

Hello good! I have read your error and the truth is that when playing The Sims 3 Pet It gives me the same error since yesterday hopefully RPCS3 will fix it soon because the truth is that this error prevents playing The Sims 3 Pets in a stable way and has NFL Head Coach 09

Have a nice day :D

**Comment by kd-11** [comment] 2023-08-01 23:50
Closing pre-emptively. This shouldn't happen anymore. Request to reopen if the issue can still be reproduced.

**Closed by kd-11** 2023-08-01 23:50 UTC
Labels: Bug, RSX
