### ISSUE TITLE
Pre-existing SPU cache kills performance in LittleBigPlanet games (#10003)

### ISSUE THREAD

**Issue by Kilowog01** [RPCS3/rpcs3#10497] opened 2021-06-26 06:54 UTC
## Quick summary
Pre-existing SPU cache kills LittleBigPlanet 2 performance.

## Details
During my adventures trying to reach 100% in LBP2, tweaking a setting here, installing a DLC there, new savegame, new build etc. I noticed that sometimes the game ran at 30fps, especially on the first run. That wasn't normal, I was used to 17ish fps. 
I started the investigations, downloaded a new build, installed the minimum necessary and bam, constant 30fps. But when i restarted the game, there was loss of 12fps with instability.
So I found that if I delete all caches, the game goes back to 30fps. While the shader cache is being compiled the fps drops a bit, but then I can play at 30 for as long as I want(I tested for about 2 hours), the fps doesn't decrease over time, it's always around 30fps. But if I restart the game, the fps drops back to 17ish.

The logs contained here are with default settings, with the exception of the overlay performance. 

Pre-existing cache:
https://user-images.githubusercontent.com/16064499/123503758-44bb5e80-d62b-11eb-9591-3c2fb1ba0abe.mp4
[RPCS3_old cache.log.gz](https://github.com/RPCS3/rpcs3/files/6719643/RPCS3_old.cache.log.gz)

Fresh cache:
https://user-images.githubusercontent.com/16064499/123503750-3c632380-d62b-11eb-9e18-0e17db93b043.mp4
[RPCS3_fresh cache.log.gz](https://github.com/RPCS3/rpcs3/files/6719642/RPCS3_fresh.cache.log.gz)

Fresh cache after a while:
https://user-images.githubusercontent.com/16064499/123504482-083e3180-d630-11eb-932e-2b7fd0b07192.mp4

System configuration:
* Windows 10 
* AMD Ryzen 7 3700X
* NVIDIA GeForce GTX 1080 (466.77)
* 31.91 GiB RAM

**Comment by Kilowog01** [comment] 2021-06-26 07:14
SPU cache is what makes the most difference between the 3.

**Comment by LamaLED** [comment] 2021-07-06 21:37
same problem but on LBP1
[RPCS3.log.gz](https://github.com/RPCS3/rpcs3/files/6772919/RPCS3.log.gz)

**Comment by Kilowog01** [comment] 2021-07-16 04:41
Issue [#10045](https://github.com/RPCS3/rpcs3/issues/10045) talks about the same problem, but the reported pull is incorrect, in fact this problem is a regression caused by the pull [#10003](https://github.com/RPCS3/rpcs3/pull/10003) by @elad335
The generally recommended build ([RPCS3.log.gz](https://github.com/RPCS3/rpcs3/files/6827861/RPCS3.log.gz)) was the problem all along, the only reason people reported improvement was the fact that they were running the game for the first time, with no pre-existing spu cache.
Build 12023 doesn't have this problem.

Logs (pre-existing spu cache)
[12023](https://github.com/RPCS3/rpcs3/files/6827854/RPCS3.log.gz)
[12025](https://github.com/RPCS3/rpcs3/files/6827862/RPCS3.log.gz)

**Comment by Long-FA** [comment] 2021-07-26 08:53
Interesting. I started LittleBigPlanet 1 for the first time and got a solid 30fps. The next time it dropped to 23FPS for no reason and I was wondering what's wrong with my machine. Maybe this is the cause.

**Comment by Nekotekina** [comment] 2021-07-26 09:02
Can someone upload SPU cache dat file after FPS is dropped?

**Comment by LamaLED** [comment] 2021-07-26 12:08
\cache\BCES00141\ppu-Jo3ijKqksCR388Rnxnw5vwpisVCV-EBOOT.BIN\"spu-safe-v1-tane.dat" right ?
https://cdn.discordapp.com/attachments/861214916290674718/869188821839925298/spu-safe-v1-tane.dat

**Comment by Kilowog01** [comment] 2021-07-26 19:03
[spu-safe-v1-tane.zip](https://github.com/RPCS3/rpcs3/files/6880555/spu-safe-v1-tane.zip)
Using 4.46 fw because VSH

**Comment by Nekotekina** [comment] 2021-07-31 05:15
I'd like to ask for logs, but with a few debug options set in config:

1. Open config.yml in an appropriate text editor
2. Find "SPU Debug" and change its value from false to true
3. Find "SPU Profiler" and change its value from false to true
4. - Provide two logs, with deleted SPU cache and with a cache that initiates the slowdown.
    - Pause and unpause game when in the area showing the FPS difference, wait at least 20 seconds before stopping the emulation

**Comment by Kilowog01** [comment] 2021-07-31 06:02
> I'd like to ask for logs (make sure to use latest version), but with a few debug options set in config:
> 
> 1. Open config.yml in an appropriate text editor
> 2. Find "SPU Debug" and change its value from false to true
> 3. Find "SPU Profiler" and change its value from false to true
> 4. * Provide two logs, with deleted SPU cache and with a cache that initiates the slowdown.
>    * Pause and unpause game when in the area showing the FPS difference, wait at least 20 seconds before stopping the emulation

Okay, I had a problem while doing it with pre-existing cache. I did what you asked but game won't boot with SPU debug on, only with profiler. At the end of "building spu cache" RPCS3 closes without any error. The log with deleted cache is exactly as requested.
[RPCS3 SPU - Pre-existing cache - SPU DEBUG CRASH.log](https://github.com/RPCS3/rpcs3/files/6910758/RPCS3.SPU.-.Pre-existing.cache.-.SPU.DEBUG.CRASH.log)
[RPCS3 SPU - Pre-existing cache - SPU Profiler ONLY.log.gz](https://github.com/RPCS3/rpcs3/files/6910759/RPCS3.SPU.-.Pre-existing.cache.-.SPU.Profiler.ONLY.log.gz)
[RPCS3_DELETED CACHE.log.gz](https://github.com/RPCS3/rpcs3/files/6910760/RPCS3_DELETED.CACHE.log.gz)

**Comment by KryptonicDragon** [comment] 2021-08-01 22:43
I am having the same issue, where having existing SPU caches causes performance to tank in NPUA80662 (LittleBigPlanet 2).

Here are some logs from me as well, with "SPU Debug" and "SPU Profiler" enabled in (the game's custom) `config.yml`:
[NPUA80662 SPU cache slowdown - 1st run (cleared SPU cache).log.gz](https://github.com/RPCS3/rpcs3/files/6913538/NPUA80662.SPU.cache.slowdown.-.1st.run.cleared.SPU.cache.log.gz)
[NPUA80662 SPU cache slowdown - 2nd run (existing SPU cache).log.gz](https://github.com/RPCS3/rpcs3/files/6913539/NPUA80662.SPU.cache.slowdown.-.2nd.run.existing.SPU.cache.log.gz)

Unlike @Kilowog01, my game successfully booted with "SPU Debug" enabled when running the 2nd time (with existing SPU cache).

In both runs, I launched the game, spammed `start` to skip the warnings/intros, went into the same level, and walked/jumped around for a bit. Both times, I paused the emulator for about 1-2 seconds, un-paused, waited 20 seconds, then exited RPCS3.

The slowdown exists throughout the entire game, no matter what level I'm playing (or even if I'm not in a level and am in the "pod" (the game's "lobby")).

Here is a screenshot from the 1st (cleared SPU cache) run:
![image](https://user-images.githubusercontent.com/10343367/127787449-0bca978f-efc2-4226-9a8f-8f7d4bd8dca0.png)
And here is one from the 2nd (existing SPU cache) run:
![image](https://user-images.githubusercontent.com/10343367/127787465-85fdc044-fa1c-4c87-915d-60ae8630402a.png)


RPCS3 Version: `0.0.17-12565-8af694da Alpha`
OS: `Windows 10 x64 v20H2`
CPU: `AMD Ryzen 7 5800X`
GPU: `NVIDIA RTX 3070` 
GPU Driver version: 466.27

**Comment by Kilowog01** [comment] 2021-08-01 23:03
it seems that Neko fixed SPU debug, i can run the game now.
[RPCS3 WITH CACHE.log.gz](https://github.com/RPCS3/rpcs3/files/6913559/RPCS3.WITH.CACHE.log.gz)
[RPCS3 WITHOUT CACHE.log.gz](https://github.com/RPCS3/rpcs3/files/6913560/RPCS3.WITHOUT.CACHE.log.gz)
And yes, the main menu/pod is technically already a level. I pause when sackboy hits the ground, count to 5, unpause and then count to 20 before closing. The logs should look very similar.

**Comment by LamaLED** [comment] 2021-08-02 21:14
I still have this problem personally.

**Comment by AphelionWasTaken** [comment] 2021-09-03 23:24
This issue appears to be related to logging. I can reproduce this to some extent on builds going all the way back to January (probably further, but that's where I stopped).

With logs silenced, performance is consistent boot after boot:
Launch 1:
![image](https://user-images.githubusercontent.com/61633628/132073723-61ae071f-b605-46b2-a1d7-a4e12c806c9c.png)
Launch 2, 3, 4, etc...:
![image](https://user-images.githubusercontent.com/61633628/132073768-8740ba38-4d25-471d-b4ac-e62aa9c9f6cd.png)

With logs enabled, performance takes a dip. Launching the game with no SPU cache results in the performance below:
![image](https://user-images.githubusercontent.com/61633628/132072037-96e9c266-0257-48df-acf7-8901fa80def8.png)
[RPCS3 NO CACHE.log.gz](https://github.com/RPCS3/rpcs3/files/7108858/RPCS3.NO.CACHE.log.gz)

Closing the emulator and relaunching the game with logs enabled and an existing SPU causes performance to tank
![image](https://user-images.githubusercontent.com/61633628/132072771-70b5f6d8-a312-41be-9d0d-24637c1b9258.png)
[RPCS3 CACHE.log.gz](https://github.com/RPCS3/rpcs3/files/7108859/RPCS3.CACHE.log.gz)

**Comment by elad335** [comment] 2024-05-29 09:35
Heavily outdated and probably fixed, also log spam iirc is reduced significantly since.

**Closed by elad335** 2024-05-29 09:35 UTC
Labels: CPU
