### ISSUE TITLE
sys_net: sys_net_bnet_select(): exceptfds not implemented (LittleBigPlanet NPUA)

### ISSUE THREAD

**Issue by Anoraki** [RPCS3/rpcs3#6462] opened 2019-08-31 16:46 UTC
**Version**: 0.0.7 (c4d99f9)

**Issue**: `sys_net: sys_net_bnet_select(): exceptfds not implemented` endlessly fills the output, sending around 60 of these per second. When using the LLVM Recompiler as the SPU Decoder, the game will freeze up after the load screen and only print this line, though it doesn't happen on the other options.

**Specs**: i5 4440, GTX 980 Ti, 32GB DDR3 @1600Mhz, 7200RPM HDD

**Log**: [RPCS3.log](https://github.com/RPCS3/rpcs3/files/3562641/RPCS3.log)

**Comment by RainbowCookie32** [comment] 2019-08-31 18:34
The freeze with SPU LLVM is a regression that I already reported on #5965, caused apparently by the SPU PIC PR (#5944)

**Comment by elad335** [comment] 2020-02-08 10:37
Close issue.

**Comment by elad335** [comment] 2020-02-08 13:49
I mean it's fixed and it was already a duplicate of #5965.

**Closed** 2020-02-08 13:51 UTC
Labels: Network, Unimplemented
