### ISSUE TITLE
Gran Turismo 5 Incorrect Time

### ISSUE THREAD

**Issue by Kian-Stevens** [RPCS3/rpcs3#6084] opened 2019-06-13 11:08 UTC
The digital clock in Gran Turismo 5 consistently displays the incorrect time, as it's fast by an hour and a half (time when thread was opened: 12:05 pm)
![image](https://user-images.githubusercontent.com/31938249/59427898-ae18fd80-8dd3-11e9-8074-29fe54954540.png)

I'm not sure whether there's a way to change the system clock, but it may be related to this issue

**Comment by AniLeo** [comment] 2019-06-13 20:13
Pretty sure this is just related to when you opened the emulator plus the hardcoded timezone being Moscow

**Comment by Kian-Stevens** [comment] 2019-06-13 21:25
> Pretty sure this is just related to when you opened the emulator plus the hardcoded timezone being Moscow

Could be a combination of both I guess
Booted GT5 as soon as I launched the emulator... The time right now is 22:24, yet the clock in GT5 is displaying 00:24, which is Moscow time

**Comment by AniLeo** [comment] 2019-06-13 22:15
Then it's just as I said

Clock won't progress further, the offset is the time you wait until you launch the game

**Comment by RainbowCookie32** [comment] 2020-06-09 01:34
Isn't this a duplicate of #5804? Could just turn that one into a tracker for unimplemented time stuff instead of having two issues for basically the same

**Closed** 2020-06-09 16:44 UTC
