### ISSUE TITLE
crash when i try to open config UI [macos]

### ISSUE THREAD

**Issue by nsklaus** [RPCS3/rpcs3#14997] opened 2024-01-02 10:42 UTC
### Quick summary

immediate crash upon opening config ui.
running on macos 14.3 beta. 
this problem started to happen with all recent builds since a little while now, maybe a month or such.

### Details

when i click "config" button on rpcs3 toolbar, or if i try to do the same (open config UI) from system menu bar, i get immediate popup indicating a crash and rpcs3 exit.

the popup shows this: 
```
Segfault reading location 000000000000000c at 000000000cf03861.
Thread: Main Thread.
Title: "" (emulation is stopped)
Build: "0.0.29-15900-d6dde225 Alpha | HEAD"
Date: "2024-01-02T11:30:16"
Title: "" (emulation is stopped)
Build: "0.0.29-15900-d6dde225 Alpha | HEAD"
Date: "2024-01-02T11:30:16"
```

to note: 
if i don't try to open the config UI, and i just double click a game in the list, i still get a crash mesage but i can click 'continue/ignore' and the game actualy starts and is playable. i also tried to delete rpcs3 config directory in `~/Library/Application Support/rpcs3/` and start fresh, but the result was the same. no matter what i try, i cannot access config UI anymore.

### Attach a log file

[RPCS3.log](https://github.com/RPCS3/rpcs3/files/13809139/RPCS3.log)

### Attach capture files for visual issues
<img width="1058" alt="Screenshot 2024-01-02 at 11 47 29" src="https://github.com/RPCS3/rpcs3/assets/6810861/c60e698e-2402-45cb-8e9f-857fb92f1278">

### System configuration
macos 14.3 beta

### Other details
apparently last known build to allow opening config UI, was build `0.0.29-15773` back from november 29-2023 (thanks duke on discord for that info).

**Comment by agnosticlines** [comment] 2024-01-08 18:11
Also experienced this, seems to happen 100% of the time when launched as an .app, but when you cd to the directory and run ./rpcs3 you can launch the config UI fine, it's just when you stop emulation it crashes.

```
2024-01-08 17:40:40.400297+0000 rpcs3[68793:947642] WARNING: AVCaptureDeviceTypeExternal is deprecated for Continuity Cameras. Please use AVCaptureDeviceTypeContinuityCamera and add NSCameraUseContinuityCameraDeviceType to your Info.plist.
2024-01-08 17:40:54.723075+0000 rpcs3[68793:947642] [General] *** -[__NSArrayM objectAtIndexedSubscript:]: index 0 beyond bounds for empty array
2024-01-08 17:40:54.725120+0000 rpcs3[68793:947642] [General] (
	0   CoreFoundation                      0x00007ff814c4185e __exceptionPreprocess + 242
	1   libobjc.A.dylib                     0x00007ff81473467f objc_exception_throw + 48
	2   CoreFoundation                      0x00007ff814bbbace -[__NSArrayM objectAtIndexedSubscript:] + 534
	3   libqcocoa.dylib                     0x000000002a45a06a _ZN20QCocoaSystemTrayIcon13emitActivatedEv + 296154
	4   libqcocoa.dylib                     0x000000002a45a10b _ZN20QCocoaSystemTrayIcon13emitActivatedEv + 296315
	5   libqcocoa.dylib                     0x000000002a458981 _ZN20QCocoaSystemTrayIcon13emitActivatedEv + 290289
	6   QtWidgets                           0x000000000d218a33 _ZN9QListView16selectionChangedERK14QItemSelectionS2_ + 195
	7   QtCore                              0x000000000de5e70a _ZN11QMetaObject8activateEP7QObjectPKS_iPPv + 3994
	8   QtCore                              0x000000000e0472de _ZN19QItemSelectionModel20emitSelectionChangedERK14QItemSelectionS2_ + 814
	9   QtCore                              0x000000000e046c7c _ZN19QItemSelectionModel6selectERK14QItemSelection6QFlagsINS_13SelectionFlagEE + 764
	10  QtCore                              0x000000000e0468dc _ZN19QItemSelectionModel6selectERK11QModelIndex6QFlagsINS_13SelectionFlagEE + 60
	11  QtCore                              0x000000000e047b80 _ZN19QItemSelectionModel15setCurrentIndexERK11QModelIndex6QFlagsINS_13SelectionFlagEE + 224
	12  QtWidgets                           0x000000000d05a7e8 _ZNK9QComboBox5countEv + 808
	13  QtWidgets                           0x000000000d05e11e _ZN9QComboBoxC1ER16QComboBoxPrivateP7QWidget + 2446
	14  QtCore                              0x000000000de5e43d _ZN11QMetaObject8activateEP7QObjectPKS_iPPv + 3277
	15  QtCore                              0x000000000e02f3dc _ZN18QAbstractItemModel13endInsertRowsEv + 220
	16  QtGui                               0x000000001f713084 _ZN18QStandardItemModel11itemChangedEP13QStandardItem + 884
	17  QtWidgets                           0x000000000d061ba0 _ZN9QComboBox11insertItemsEiRK5QListI7QStringE + 384
	18  rpcs3                               0x0000000000e3ed64 _ZN15settings_dialog10SnapSliderEP7QSlideri + 5268
	19  rpcs3                               0x0000000000e2779c _ZN15settings_dialogC2ENSt3__110shared_ptrI12gui_settingsEENS1_I12emu_settingsEERKiP7QWidgetPK8GameInfob + 20396
	20  rpcs3                               0x0000000000c9c1ed _ZNK15game_list_frame11GetGameInfoEv + 57309
	21  QtCore                              0x000000000de5e43d _ZN11QMetaObject8activateEP7QObjectPKS_iPPv + 3277
	22  QtGui                               0x000000001f78b56d _ZN7QAction8activateENS_11ActionEventE + 397
	23  QtWidgets                           0x000000000d0e75a7 _ZN5QMenu7setIconERK5QIcon + 5383
	24  QtWidgets                           0x000000000d0e4e68 _ZN5QMenu20internalDelayedPopupEv + 2152
	25  QtWidgets                           0x000000000d0ec562 _ZN5QMenu17mouseReleaseEventEP11QMouseEvent + 482
	26  QtWidgets                           0x000000000cf722ca _ZN7QWidget5eventEP6QEvent + 538
	27  QtWidgets                           0x000000000d0eccdf _ZN5QMenu5eventEP6QEvent + 1391
	28  QtWidgets                           0x000000000cf22c87 _ZN19QApplicationPrivate13notify_helperEP7QObjectP6QEvent + 247
	29  QtWidgets                           0x000000000cf24f43 _ZN12QApplication6notifyEP7QObjectP6QEvent + 5795
	30  QtCore                              0x000000000de0fe0a _ZN16QCoreApplication15notifyInternal2EP7QObjectP6QEvent + 170
	31  QtWidgets                           0x000000000cf23245 _ZN19QApplicationPrivate14sendMouseEventEP7QWidgetP11QMouseEventS1_S1_PS1_R8QPointerIS0_Ebb + 885
	32  QtWidgets                           0x000000000cf89d97 _ZNK21QWidgetRepaintManager3rhiEv + 13959
	33  QtWidgets                           0x000000000cf885d0 _ZNK21QWidgetRepaintManager3rhiEv + 7872
	34  QtWidgets                           0x000000000cf22c87 _ZN19QApplicationPrivate13notify_helperEP7QObjectP6QEvent + 247
	35  QtWidgets                           0x000000000cf23a92 _ZN12QApplication6notifyEP7QObjectP6QEvent + 498
	36  QtCore                              0x000000000de0fe0a _ZN16QCoreApplication15notifyInternal2EP7QObjectP6QEvent + 170
	37  QtGui                               0x000000001f422086 _ZN22QGuiApplicationPrivate17processMouseEventEPN29QWindowSystemInterfacePrivate10MouseEventE + 2182
	38  QtGui                               0x000000001f4800bc _ZN22QWindowSystemInterface22sendWindowSystemEventsE6QFlagsIN10QEventLoop17ProcessEventsFlagEE + 444
	39  libqcocoa.dylib                     0x000000002a3f4adf qt_plugin_instance + 63039
	40  CoreFoundation                      0x00007ff814bcf716 __CFRUNLOOP_IS_CALLING_OUT_TO_A_SOURCE0_PERFORM_FUNCTION__ + 17
	41  CoreFoundation                      0x00007ff814bcf6b9 __CFRunLoopDoSource0 + 157
	42  CoreFoundation                      0x00007ff814bcf488 __CFRunLoopDoSources0 + 215
	43  CoreFoundation                      0x00007ff814bce0f8 __CFRunLoopRun + 919
	44  CoreFoundation                      0x00007ff814bcd799 CFRunLoopRunSpecific + 557
	45  HIToolbox                           0x00007ff81faa29d9 RunCurrentEventLoopInMode + 292
	46  HIToolbox                           0x00007ff81faa2616 ReceiveNextEventCommon + 201
	47  HIToolbox                           0x00007ff81faa2531 _BlockUntilNextEventMatchingListInModeWithFilter + 66
	48  AppKit                              0x00007ff81813dd69 _DPSNextEvent + 880
	49  AppKit                              0x00007ff818a47834 -[NSApplication(NSEventRouting) _nextEventMatchingEventMask:untilDate:inMode:dequeue:] + 1304
	50  AppKit                              0x00007ff81812f2e2 -[NSApplication run] + 603
	51  libqcocoa.dylib                     0x000000002a3f285d qt_plugin_instance + 54205
	52  QtCore                              0x000000000de198f6 _ZN10QEventLoop4execE6QFlagsINS_17ProcessEventsFlagEE + 486
	53  QtWidgets                           0x000000000d0eaf7e _ZN5QMenu4execERK6QPointP7QAction + 334
	54  QtWidgets                           0x000000000d0eae61 _ZN5QMenu4execERK6QPointP7QAction + 49
	55  rpcs3                               0x0000000000c84342 _ZN15game_list_frame15ShowContextMenuERK6QPoint + 24818
	56  QtCore                              0x000000000de5e43d _ZN11QMetaObject8activateEP7QObjectPKS_iPPv + 3277
	57  QtWidgets                           0x000000000cf73080 _ZN7QWidget5eventEP6QEvent + 4048
	58  QtWidgets                           0x000000000d00938b _ZN6QFrame5eventEP6QEvent + 43
	59  QtWidgets                           0x000000000d1d3f8c _ZN17QAbstractItemView13viewportEventEP6QEvent + 1116
	60  QtCore                              0x000000000de100a5 _ZN23QCoreApplicationPrivate29sendThroughObjectEventFiltersEP7QObjectP6QEvent + 229
	61  QtWidgets                           0x000000000cf22c73 _ZN19QApplicationPrivate13notify_helperEP7QObjectP6QEvent + 227
	62  QtWidgets                           0x000000000cf2492d _ZN12QApplication6notifyEP7QObjectP6QEvent + 4237
	63  QtCore                              0x000000000de0fe0a _ZN16QCoreApplication15notifyInternal2EP7QObjectP6QEvent + 170
	64  QtWidgets                           0x000000000cf899b3 _ZNK21QWidgetRepaintManager3rhiEv + 12963
	65  QtWidgets                           0x000000000cf885d0 _ZNK21QWidgetRepaintManager3rhiEv + 7872
	66  QtWidgets                           0x000000000cf22c87 _ZN19QApplicationPrivate13notify_helperEP7QObjectP6QEvent + 247
	67  QtWidgets                           0x000000000cf23a92 _ZN12QApplication6notifyEP7QObjectP6QEvent + 498
	68  QtCore                              0x000000000de0fe0a _ZN16QCoreApplication15notifyInternal2EP7QObjectP6QEvent + 170
	69  QtGui                               0x000000001f422086 _ZN22QGuiApplicationPrivate17processMouseEventEPN29QWindowSystemInterfacePrivate10MouseEventE + 2182
	70  QtGui                               0x000000001f4800bc _ZN22QWindowSystemInterface22sendWindowSystemEventsE6QFlagsIN10QEventLoop17ProcessEventsFlagEE + 444
	71  libqcocoa.dylib                     0x000000002a3f4adf qt_plugin_instance + 63039
	72  CoreFoundation                      0x00007ff814bcf716 __CFRUNLOOP_IS_CALLING_OUT_TO_A_SOURCE0_PERFORM_FUNCTION__ + 17
	73  CoreFoundation                      0x00007ff814bcf6b9 __CFRunLoopDoSource0 + 157
	74  CoreFoundation                      0x00007ff814bcf488 __CFRunLoopDoSources0 + 215
	75  CoreFoundation                      0x00007ff814bce0f8 __CFRunLoopRun + 919
	76  CoreFoundation                      0x00007ff814bcd799 CFRunLoopRunSpecific + 557
	77  HIToolbox                           0x00007ff81faa29d9 RunCurrentEventLoopInMode + 292
	78  HIToolbox                           0x00007ff81faa2616 ReceiveNextEventCommon + 201
	79  HIToolbox                           0x00007ff81faa2531 _BlockUntilNextEventMatchingListInModeWithFilter + 66
	80  AppKit                              0x00007ff81813dd69 _DPSNextEvent + 880
	81  AppKit                              0x00007ff818a47834 -[NSApplication(NSEventRouting) _nextEventMatchingEventMask:untilDate:inMode:dequeue:] + 1304
	82  AppKit                              0x00007ff81812f2e2 -[NSApplication run] + 603
	83  libqcocoa.dylib                     0x000000002a3f285d qt_plugin_instance + 54205
	84  QtCore                              0x000000000de198f6 _ZN10QEventLoop4execE6QFlagsINS_17ProcessEventsFlagEE + 486
	85  QtCore                              0x000000000de103f7 _ZN16QCoreApplication4execEv + 119
	86  rpcs3                               0x000000000002ff17 main + 30903
	87  dyld                                0x0000000105ac3386 start + 1942
)
Process 68793 stopped
* thread #1, queue = 'com.apple.main-thread', stop reason = EXC_BAD_ACCESS (code=1, address=0x30)
    frame #0: 0x000000000cf7458f QtWidgets`QWidgetPrivate::childAtRecursiveHelper(QPoint const&, bool) const + 127
QtWidgets`QWidgetPrivate::childAtRecursiveHelper:
->  0xcf7458f <+127>: testb  $0x1, 0x30(%r15)
    0xcf74594 <+132>: je     0xcf74560                 ; <+80>
    0xcf74596 <+134>: movq   0x20(%r14), %rdi
    0xcf7459a <+138>: testb  $0x1, 0xc(%rdi)
Target 0: (rpcs3) stopped.I
```

There's a null check at the start of the `settings_dialog::SnapSlider` and in the lambda connection function, so I'm not too sure what the root cause is, I also can't build the latest release on Mac because Foundation 13 has issues with old style casts, which I don't feel like trawling through make files and build systems to try omit that argument.

**Comment by PrideChung** [comment] 2024-01-08 18:33
>  I also can't build the latest release on Mac because Foundation 13 has issues with old style casts, which I don't feel like trawling through make files and build systems to try omit that argument.

there's a PR to fix build errors on mac already: #14452

**Comment by PrideChung** [comment] 2024-01-08 18:37
> > I also can't build the latest release on Mac because Foundation 13 has issues with old style casts, which I don't feel like trawling through make files and build systems to try omit that argument.
> 
> there's a PR to fix build errors on mac already: #14452

Yet another PR addressing the same problem: #15008. Looks promising, will give it a try.

**Comment by agnosticlines** [comment] 2024-01-08 18:45
> > > I also can't build the latest release on Mac because Foundation 13 has issues with old style casts, which I don't feel like trawling through make files and build systems to try omit that argument.
> > 
> > 
> > there's a PR to fix build errors on mac already: #14452
> 
> Yet another PR addressing the same problem: #15008. Looks promising, will give it a try.

If you can get a debug build with symbols going that'd be awesome, I'll look into this when I have time otherwise but hopefully someone more knowledgable in the code will fix it, I'm kinda just flying blind in a debugger atm

**Comment by shinra-electric** [comment] 2024-01-08 20:24
For what it's worth, I can't replicate this issue on Sonoma 14.3 Beta (I'm on Beta 2 now, but I never had the issue on Beta 1 either). I have no issue with either the release builds or my own local builds. 

I'm on an M1 Pro, From the OP's log it looks like they are on an Apple Silicon Mac too. What processor? 

To build with debug symbols you can set the CMake setting `-DCMAKE_BUILD_TYPE=Debug` or `-DCMAKE_BUILD_TYPE=RelWithDebInfo`

**Comment by agnosticlines** [comment] 2024-01-08 21:31
> For what it's worth, I can't replicate this issue on Sonoma 14.3 Beta (I'm on Beta 2 now, but I never had the issue on Beta 1 either). I have no issue with the config menu on the release builds or my own local builds. Although I can't currently get a working build of RPCS3 using Sonoma, I have to use Ventura. 
> 
> 
> 
> I'm on an M1 Pro, From the OP's log it looks like they are on an Apple Silicon Mac too. ~~What processor?~~  Ah, it says M2 Pro in the logs. Does anyone else with this issue have an M2 or M3? 
> 
> 
> 
> To build with debug symbols you can set the CMake setting `-DCMAKE_BUILD_TYPE=Debug` or `-DCMAKE_BUILD_TYPE=RelWithDebInfo`

I'm on an M1 Pro too, and yeah I know how to build it but there's issues with the foundation sdk, there's an open PR to fix them though.

Interesting that you don't have this issue though, for some reason it also only repros on one game for me, Little Big Planet 3, the rest it works fine

**Comment by shinra-electric** [comment] 2024-01-08 22:27
> there's issues with the foundation sdk, there's an open PR to fix them though.

Interesting, do you have a link to that?

**Comment by nsklaus** [comment] 2024-01-09 09:45
@agnosticlines 
reading what you've said, i've just tried to get latest build and start it directly through command line:
```
cd Downloads/rpcs3-v0.0.30-15924-7504503d_macos/RPCS3.app/Contents/MacOS/
MacOS % ./rpcs3 
[mvk-info] MoltenVK version 1.2.6, supporting Vulkan version 1.2.268.
	The following 102 Vulkan extensions are supported:
....
[mvk-info] GPU device:
		model: Apple M2 Pro
....
[mvk-info] Created VkInstance for Vulkan version 1.0.0, as requested by app, with the following 0 Vulkan extensions enabled:
[mvk-info] Destroyed VkPhysicalDevice for GPU Apple M2 Pro with 0 MB of GPU memory still allocated.
[mvk-info] Destroying VkInstance for Vulkan version 1.0.0 with 0 Vulkan extensions enabled.
qt.gui.imageio: libpng warning: iCCP: known incorrect sRGB profile
RPCS3: SYS: 
Segfault reading location 000000000000000c at 000000000cf20861.
Thread: Main Thread.

RPCS3: SIG: Thread terminated due to fatal error: Segfault reading location 000000000000000c at 000000000cf20861.
Thread: Main Thread.

RPCS3: Segfault reading location 000000000000000c at 000000000cf20861.
Thread: Main Thread.

Title: "" (emulation is stopped)
Build: "0.0.30-15924-7504503d Alpha | HEAD"
Date: "2024-01-09T10:32:31"
Debugger: 0
zsh: abort      ./rpcs3
```
so for me, it's the same as when i start it as an app, meaning, immediate crash upon trying to open anything related config UI. for info i'm also on 14.3 beta2 (23D5043d), my system is a macbook pro 14" m2pro 16gb of ram (from 2023).

**Comment by agnosticlines** [comment] 2024-01-09 11:23
> @agnosticlines reading what you've said, i've just tried to get latest build and start it directly through command line:
> 
> ```
> cd Downloads/rpcs3-v0.0.30-15924-7504503d_macos/RPCS3.app/Contents/MacOS/
> MacOS % ./rpcs3 
> [mvk-info] MoltenVK version 1.2.6, supporting Vulkan version 1.2.268.
> 	The following 102 Vulkan extensions are supported:
> ....
> [mvk-info] GPU device:
> 		model: Apple M2 Pro
> ....
> [mvk-info] Created VkInstance for Vulkan version 1.0.0, as requested by app, with the following 0 Vulkan extensions enabled:
> [mvk-info] Destroyed VkPhysicalDevice for GPU Apple M2 Pro with 0 MB of GPU memory still allocated.
> [mvk-info] Destroying VkInstance for Vulkan version 1.0.0 with 0 Vulkan extensions enabled.
> qt.gui.imageio: libpng warning: iCCP: known incorrect sRGB profile
> RPCS3: SYS: 
> Segfault reading location 000000000000000c at 000000000cf20861.
> Thread: Main Thread.
> 
> RPCS3: SIG: Thread terminated due to fatal error: Segfault reading location 000000000000000c at 000000000cf20861.
> Thread: Main Thread.
> 
> RPCS3: Segfault reading location 000000000000000c at 000000000cf20861.
> Thread: Main Thread.
> 
> Title: "" (emulation is stopped)
> Build: "0.0.30-15924-7504503d Alpha | HEAD"
> Date: "2024-01-09T10:32:31"
> Debugger: 0
> zsh: abort      ./rpcs3
> ```
> 
> so for me, it's the same as when i start it as an app, meaning, immediate crash upon trying to open anything related to config UI. for info i'm also on 14.3 beta2 (23D5043d), my system is a macbook pro 14" m2pro 16gb of ram (from 2023).

Hey, had a look again, went to record a video, you're right, it happens for me sometimes when I open it with ./rpcs3 too, it definitely seems to happen more when I open it as an app, not sure if that's a coincidence, I'm starting to think it's a timing issue or race, given that it seems to be pretty random when it decides to crash, but if I click config the second I can, it crashes 90-95% of the time, that lambda is seeming quite suspect:


```
void settings_dialog::SnapSlider(QSlider *slider, int interval)
{
	if (!slider)
	{
		return;
	}

	// Snap the slider to the next best interval position if the slider is currently modified with the mouse.
	connect(slider, &QSlider::valueChanged, [this, slider, interval](int value)
	{
		if (!slider || slider != m_current_slider)
		{
			return;
		}
		slider->setValue(utils::rounded_div(value, interval) * interval);
	});

	// Register the slider for the event filter which updates m_current_slider if a QSlider was pressed or released with the mouse.
	// We can't just use sliderPressed and sliderReleased signals to update m_current_slider because those only trigger if the handle was clicked.
	slider->installEventFilter(this);
	m_snap_sliders.insert(slider);
}
``` 

Particularly the `connect` lambda, but there's a check if it's null in there, I guess the pointer is never truly null, it's always offset by some bytes, so it could be getting corrupted, possibly in a race between it and the `objc_msgSend` ?

**Comment by agnosticlines** [comment] 2024-01-09 11:34
> > there's issues with the foundation sdk, there's an open PR to fix them though.
> 
> Interesting, do you have a link to that?

Same ones mentioned earlier in the thread: #14452 and #15008

**Comment by shinra-electric** [comment] 2024-01-09 13:18
> > > there's issues with the foundation sdk, there's an open PR to fix them though.
> > 
> > 
> > Interesting, do you have a link to that?
> 
> Same ones mentioned earlier in the thread: #14452 and #15008

Ah sorry. I thought you meant a PR to fix the issues in the foundation sdk.

**Comment by D-elias** [comment] 2024-01-26 18:24
On OSX 14.3, M2 Macbook Pro, the only build that works is Rcps3 0.0.28-15308. I click on config and pads on this version, then opened Rcps3 0.0.30-15914 and booted the game, changed the resolution in the older version and it works. After removing all of the Rcps3 system files with a clean install, the current builds only boot the game but clicking on config or pads crashes it. Then when I changed the settings in 0.0.28-15308 and the current build stopped booting games. So I booted in 0.0.30-15914 and it boots in 0.0.28-15308 now.

**Comment by meh7an** [comment] 2024-01-28 07:45
> On OSX 14.3, M2 Macbook Pro, the only build that works is Rcps3 0.0.28-15308. 

I have the issue on M3 Max MacOS 14.3, and the last build that boots games and opens config UI is ```0.0.29-15696```. From what I understood, just after booting the game, it freezes the UI on latest 16011. The freeze is alongside the game window not opening at all. By tapping on enter button, the modal of "Do you really want to boot another game?" appears, unfreezing the UI and showing the logs after the freeze, but just after tapping on no, it will freeze again. Tapping on yes just crashes the app by a Segfault reading location on main thread.

There were some various ways of app's behavior in the updates forward though, there was a build about 159xx that after tapping on No, the game window would open and work, but I'm not sure if it was about my settings or not.

Anyways, I just named 15696 as "RPCS3 LTS" on my apps until a functional build is there.

**Comment by meh7an** [comment] 2024-01-28 08:11
Something else that I have realized from the config UI crash is that opening one of the options from Configuration menu (like GUI or Audio) has a possibility of opening the UI (let's say 10% times). Directly tapping on Config button on the app never opens it for me.

**Comment by meh7an** [comment] 2024-02-03 10:07
> > On OSX 14.3, M2 Macbook Pro, the only build that works is Rcps3 0.0.28-15308.

Except the Config UI crash problem, everything else was related to SDL plugin and #14999, meaning that disabling SDL gamepad plugin temporarily fixes them all. The effect of the bug just became worse possibly after QT update to 6.6.1, causing the games to not even get opened. 

So basically the workaround for it is to open the game with SDL disabled, and then enabling it while the game is open.
Although this action won't affect the config UI.

**Comment by KevDoy** [comment] 2024-02-10 07:56
Can confirm this is also happening to me

**Comment by mavethee** [comment] 2024-02-22 19:40
Same here, this was fixed with updating RPCS3 to new Qt version

**Closed** 2024-02-22 19:40 UTC
Labels: Regression, OS: Mac
