### ISSUE TITLE
Asura's Wrath failing to boot

### ISSUE THREAD

**Issue by LeKingCarnage** [RPCS3/rpcs3#4561] opened 2018-05-13 14:42 UTC
S LDR: Boot successful.
S {PPU[0x1000000] Thread (main_thread)} SPU: SPU Recompiler Runtime (ASMJIT) initialized...
F {PPU[0x1000000] Thread (main_thread)} class std::runtime_error thrown: Verification failed (e=0xb7) (0): 
(in file Emu\Cell\SPUASMJITRecompiler.cpp:2753)

**Comment by Megamouse** [comment] 2018-05-13 14:43
sttooooooop

**Comment by SiTWulf** [comment] 2018-05-13 17:49
Same problem but with all games...
Looks like a problem with handle of System Files...

This is a example of Silent Hill:
E {PPU[0x1000000] Thread (main_thread) [0x01f22090]} 'sys_fs_open' failed with 0x80010006 : CELL_ENOENT, “/dev_hdd0/game/BLUS30565/USRDIR/settings-1” [1]
U {PPU[0x1000000] Thread (main_thread) [0x0181c7e8]} cellSysutil TODO: cellVideoOutConfigure(videoOut=0, config=*0xd00404f0, option=*0x0, waitForEvent=0)
U {PPU[0x1000000] Thread (main_thread) [0x01ee7c8c]} sys_spu TODO: Unsupported SPU Thread Group type (0x18)
U {PPU[0x1000000] Thread (main_thread) [0x01ee7d80]} sys_spu TODO: Unimplemented SPU Thread options (0x2) x5
U {PPU[0x1000000] Thread (main_thread) [0x01e5ff0c]} sys_prx TODO: _sys_prx_get_module_id_by_name(name=“cellLibprof”, flags=0, pOpt=*0x0)
E {PPU[0x1000000] Thread (main_thread) [0x01e5ff0c]} '_sys_prx_get_module_id_by_name' failed with 0x8001112e : CELL_PRX_ERROR_UNKNOWN_MODULE [1]
U {PPU[0x1000000] Thread (main_thread) [0x01ee7d80]} sys_spu TODO: Unimplemented SPU Thread options (0x2)
U {PPU[0x1000000] Thread (main_thread) [0x01e5ff0c]} sys_prx TODO: _sys_prx_get_module_id_by_name(name=“cellLibprof”, flags=0, pOpt=*0x0)
E {PPU[0x1000000] Thread (main_thread) [0x01e5ff0c]} '_sys_prx_get_module_id_by_name' failed with 0x8001112e : CELL_PRX_ERROR_UNKNOWN_MODULE [2]
S HLE: XInput device 0 reconnected
U {PPU[0x1000000] Thread (main_thread) [0x0075058c]} sceNp TODO: sceNpManagerGetAccountRegion(countryCode=*0xd0020a48, language=*0xd0020940)
U {PPU[0x1000000] Thread (main_thread) [0x0181d3b8]} sceNp TODO: sceNpManagerUnregisterCallback()
E {PPU[0x1000000] Thread (main_thread) [0x01f21ee4]} 'sys_fs_stat' failed with 0x80010006 : CELL_ENOENT, “/dev_bdvd/PS3_GAME/USRDIR/SHGAME/COOKEDPS3/LOC_GENERAL-JPN_SF.XXX” [1]
E {PPU[0x1000000] Thread (main_thread) [0x01f21ee8]} cellGame: cellGameCreateGameData(init=*0xd003f348, tmp_contentInfoPath=*0xd003f248, tmp_usrdirPath=*0xd003f2c8)
S {PPU[0x1000000] Thread (main_thread) [0x01f21ee8]} cellGame: cellGameCreateGameData(): temporary directory '/dev_hdd1/game/BLUS30565' has been created
E {PPU[0x100000a] Thread (fios mediathread 2) [0x01f21ee4]} 'sys_fs_stat' failed with 0x80010006 : CELL_ENOENT, “/dev_hdd1/game/BLUS30565/USRDIR/FIOS-UNREALENGINE3” [1]
E {PPU[0x100000a] Thread (fios mediathread 2) [0x01f21ee4]} 'sys_fs_stat' failed with 0x80010006 : CELL_ENOENT, “/dev_hdd1/game/BLUS30565/USRDIR/FIOS-UNREALENGINE3/SHGAME” [1]
E {PPU[0x100000a] Thread (fios mediathread 2) [0x01f21ee4]} 'sys_fs_stat' failed with 0x80010006 : CELL_ENOENT, “/dev_hdd1/game/BLUS30565/USRDIR/FIOS-UNREALENGINE3/SHGAME/COOKEDPS3” [1]
E {PPU[0x100000a] Thread (fios mediathread 2) [0x01f21ee4]} 'sys_fs_stat' failed with 0x80010006 : CELL_ENOENT, “/dev_hdd1/game/BLUS30565/USRDIR/MOVIES” [1]
E {PPU[0x100000a] Thread (fios mediathread 2) [0x01f21ee4]} 'sys_fs_stat' failed with 0x80010006 : CELL_ENOENT, “/dev_hdd1/game/BLUS30565/USRDIR/FIOS-UNREALENGINE3/BINARIES” [1]
E {PPU[0x100000a] Thread (fios mediathread 2) [0x01f21ee4]} 'sys_fs_stat' failed with 0x80010006 : CELL_ENOENT, “/dev_hdd1/game/BLUS30565/USRDIR/FIOS-UNREALENGINE3/BINARIES/PS3” [1]
E {PPU[0x100000a] Thread (fios mediathread 2) [0x01f21ee4]} 'sys_fs_stat' failed with 0x80010006 : CELL_ENOENT, “/dev_hdd1/game/BLUS30565/USRDIR/FIOS-UNREALENGINE3/BINARIES/PS3/SAVE” [1]
S {PPU[0x1000000] Thread (main_thread) [0x01e5521c]} cellGame: cellGameContentPermit(): directory '/dev_hdd0/game/BLUS30565' has been created
E {PPU[0x1000000] Thread (main_thread) [0x01f22090]} 'sys_fs_open' failed with 0x80010006 : CELL_ENOENT, “/dev_hdd0/game/BLUS30565/USRDIR/done” [1]
E {PPU[0x100000d] Thread (fios mediathread 5) [0x01f21ee4]} 'sys_fs_stat' failed with 0x80010006 : CELL_ENOENT, “/dev_hdd1/cache/BLUS30565/fios” [1]
E {PPU[0x100000d] Thread (fios mediathread 5) [0x01f21ee4]} 'sys_fs_stat' failed with 0x80010006 : CELL_ENOENT, “/dev_hdd1/cache/BLUS30565/fios” [2]
E {PPU[0x1000010] Thread (fios mediathread 8) [0x01f21ee4]} 'sys_fs_stat' failed with 0x80010006 : CELL_ENOENT, “/dev_hdd0/game/BLUS30565/USRDIR/FIOS-UNREALENGINE3/INSTALL” [1]
E {PPU[0x1000010] Thread (fios mediathread 8) [0x01f21ee4]} 'sys_fs_stat' failed with 0x80010006 : CELL_ENOENT, “/dev_hdd0/game/BLUS30565/USRDIR/PROFILE” [1]
E {PPU[0x1000010] Thread (fios mediathread 8) [0x01f21ee4]} 'sys_fs_stat' failed with 0x80010006 : CELL_ENOENT, “/dev_hdd0/game/BLUS30565/USRDIR/FIOS-UNREALENGINE3/INSTALL” [2]
E {PPU[0x1000010] Thread (fios mediathread 8) [0x01f21ee4]} 'sys_fs_stat' failed with 0x80010006 : CELL_ENOENT, “/dev_hdd0/game/BLUS30565/USRDIR/PROFILE” [2]
E {PPU[0x1000010] Thread (fios mediathread 8) [0x01f21ee4]} 'sys_fs_stat' failed with 0x80010006 : CELL_ENOENT, “/dev_hdd0/game/BLUS30565/USRDIR/FIOS-UNREALENGINE3/INSTALL” [3]
E {PPU[0x1000010] Thread (fios mediathread 8) [0x01f21ee4]} 'sys_fs_stat' failed with 0x80010006 : CELL_ENOENT, “/dev_hdd0/game/BLUS30565/USRDIR/PROFILE” [3]
E {PPU[0x1000010] Thread (fios mediathread 8) [0x01f21ee4]} 'sys_fs_stat' failed with 0x80010006 : CELL_ENOENT, “/dev_hdd0/game/BLUS30565/USRDIR/FIOS-UNREALENGINE3/SHGAME/PS3TOC.TXT” [1]
E {PPU[0x1000010] Thread (fios mediathread 8) [0x01f21ee4]} 'sys_fs_stat' failed with 0x80010006 : CELL_ENOENT, “/dev_hdd0/game/BLUS30565/USRDIR/FIOS-UNREALENGINE3/SHGAME/PS3TOC.TXT” [2]
E {PPU[0x1000010] Thread (fios mediathread 8) [0x01f21ee4]} 'sys_fs_stat' failed with 0x80010006 : CELL_ENOENT, “/dev_hdd0/game/BLUS30565/USRDIR/FIOS-UNREALENGINE3/SHGAME/PS3TOC.TXT” [3]
E {PPU[0x1000010] Thread (fios mediathread 8) [0x01f21ee4]} 'sys_fs_stat' failed with 0x80010006 : CELL_ENOENT, “/dev_hdd0/game/BLUS30565/USRDIR/FIOS-UNREALENGINE3/SHGAME/PS3TOC_ESM.TXT” [1]
E {PPU[0x1000010] Thread (fios mediathread 8) [0x01f21ee4]} 'sys_fs_stat' failed with 0x80010006 : CELL_ENOENT, “/dev_hdd0/game/BLUS30565/USRDIR/FIOS-UNREALENGINE3/SHGAME/PS3TOC_ESM.TXT.EDAT” [1]
E {PPU[0x1000010] Thread (fios mediathread 8) [0x01f22000]} 'sys_fs_opendir' failed with 0x80010006 : CELL_ENOENT, “/dev_hdd0/game/BLUS30565/USRDIR/DLC” [1]
E {PPU[0x1000010] Thread (fios mediathread 8) [0x01f22000]} 'sys_fs_opendir' failed with 0x80010006 : CELL_ENOENT, “/dev_bdvd/PS3_GAME/USRDIR/DLC” [1]
E {PPU[0x1000010] Thread (fios mediathread 8) [0x01f21ee4]} 'sys_fs_stat' failed with 0x80010006 : CELL_ENOENT, “/dev_hdd0/game/BLUS30565/USRDIR/FIOS-UNREALENGINE3/INSTALL/___LOCK” [1]
E {PPU[0x1000010] Thread (fios mediathread 8) [0x01f21ee4]} 'sys_fs_stat' failed with 0x80010006 : CELL_ENOENT, “/dev_hdd0/game/BLUS30565/USRDIR/FIOS-UNREALENGINE3/INSTALL/___LOCK” [2]
E {PPU[0x1000010] Thread (fios mediathread 8) [0x01f21ee4]} 'sys_fs_stat' failed with 0x80010006 : CELL_ENOENT, “/dev_hdd0/game/BLUS30565/USRDIR/FIOS-UNREALENGINE3/___LOCK” [1]
E {PPU[0x1000010] Thread (fios mediathread 8) [0x01f21ee4]} 'sys_fs_stat' failed with 0x80010006 : CELL_ENOENT, “/dev_hdd0/game/BLUS30565/USRDIR/FIOS-UNREALENGINE3/INSTALL/___LOCK” [3]
E {PPU[0x1000014] Thread (TrophyInfo) [0x0181c4a0]} sceNpTrophy: sceNpTrophyRegisterContext(context=0x1, handle=0x1, statusCb=*0x1c4c6c8, arg=*0x0, options=0x0)
E {PPU[0x1000010] Thread (fios mediathread 8) [0x01f21ee4]} 'sys_fs_stat' failed with 0x80010006 : CELL_ENOENT, “/dev_hdd0/game/BLUS30565/USRDIR/FIOS-UNREALENGINE3/BINARIES/EPICINTERNAL.TXT” [1]
E {PPU[0x1000014] Thread (TrophyInfo) [0x0181c318]} sceNpTrophy: sceNpTrophyGetGameInfo(context=0x1, handle=0x1, details=*0xd01d478c, data=*0x0)
E {PPU[0x1000014] Thread (TrophyInfo) [0x0181d5e8]} sceNpTrophy: sceNpTrophyGetTrophyUnlockState(context=0x1, handle=0x1, flags=*0xd01d4114, count=*0xd01d40f0)
E {PPU[0x1000010] Thread (fios mediathread 8) [0x01f21ee4]} 'sys_fs_stat' failed with 0x80010006 : CELL_ENOENT, “/dev_hdd0/game/BLUS30565/USRDIR/FIOS-UNREALENGINE3/SHGAME/COOKEDPS3/COALESCED_ESM.BIN” [1]
E {rsx::thread} RSX: nv406e::semaphore_acquire has timed out. semaphore_address=0x40300FE0
S LLVM: Created module: v2-libnet.sprx-FFB9AC229DA8A825-skylake.obj
S {PPU[0x1000000] Thread (main_thread) [0x01e609ac]} sys_prx: Loaded module: /dev_flash/sys/external/libnet.sprx
U {PPU[0x1000000] Thread (main_thread) [0x0181b9b0]} cellNetCtl TODO: cellNetCtlAddHandler(handler=*0x1c4c288, arg=*0x0, hid=*0xd0040550)
E {PPU[0x1000010] Thread (fios mediathread 8) [0x01f22000]} 'sys_fs_opendir' failed with 0x80010006 : CELL_ENOENT, “/dev_bdvd/PS3_GAME/USRDIR/SHGAME/PS3CACHE” [1]
E {PPU[0x1000010] Thread (fios mediathread 8) [0x01f22000]} 'sys_fs_opendir' failed with 0x80010006 : CELL_ENOENT, “/dev_bdvd/PS3_GAME/USRDIR/SHGAME/PS3CACHE” [2]
E {PPU[0x1000010] Thread (fios mediathread 8) [0x01f22000]} 'sys_fs_opendir' failed with 0x80010006 : CELL_ENOENT, “/dev_hdd0/game/BLUS30565/USRDIR/DLC” [2]
E {PPU[0x1000010] Thread (fios mediathread 8) [0x01f22000]} 'sys_fs_opendir' failed with 0x80010006 : CELL_ENOENT, “/dev_bdvd/PS3_GAME/USRDIR/DLC” [2]
E {PPU[0x1000000] Thread (main_thread) [0x01e554ec]} '_sys_lwmutex_lock' failed with 0x80010005 : CELL_ESRCH [1]
E {PPU[0x1000000] Thread (main_thread) [0x01e554ec]} '_sys_lwmutex_lock' failed with 0x80010005 : CELL_ESRCH [2]
E {PPU[0x1000000] Thread (main_thread) [0x01e554ec]} '_sys_lwmutex_lock' failed with 0x80010005 : CELL_ESRCH [3]
S {Audio Thread} XAudio 2.9 initialized
E {PPU[0x1000010] Thread (fios mediathread 8) [0x01f21ee4]} 'sys_fs_stat' failed with 0x80010006 : CELL_ENOENT, “/dev_hdd0/game/BLUS30565/USRDIR/FIOS-UNREALENGINE3/PROFILE/PROFILE_1.BIN” [1]
E {PPU[0x1000010] Thread (fios mediathread 8) [0x01f21ee4]} 'sys_fs_stat' failed with 0x80010006 : CELL_ENOENT, “/dev_hdd0/game/BLUS30565/USRDIR/FIOS-UNREALENGINE3/PROFILE/PROFILE_1.BIN” [2]
E {PPU[0x1000010] Thread (fios mediathread 8) [0x01f21ee4]} 'sys_fs_stat' failed with 0x80010006 : CELL_ENOENT, “/dev_hdd0/game/BLUS30565/USRDIR/PROFILE/PROFILE_1.BIN” [1]
E {PPU[0x1000010] Thread (fios mediathread 8) [0x01f21ee4]} 'sys_fs_stat' failed with 0x80010006 : CELL_ENOENT, “/dev_hdd0/game/BLUS30565/USRDIR/FIOS-UNREALENGINE3/PROFILE/PROFILE_1.BIN.EDAT” [1]
E {PPU[0x1000010] Thread (fios mediathread 8) [0x01f21ee4]} 'sys_fs_stat' failed with 0x80010006 : CELL_ENOENT, “/dev_hdd0/game/BLUS30565/USRDIR/FIOS-UNREALENGINE3/PROFILE/PROFILE_1.BIN.EDAT” [2]
E {PPU[0x1000010] Thread (fios mediathread 8) [0x01f21ee4]} 'sys_fs_stat' failed with 0x80010006 : CELL_ENOENT, “/dev_hdd0/game/BLUS30565/USRDIR/FIOS-UNREALENGINE3/PROFILE” [1]
E {PPU[0x1000010] Thread (fios mediathread 8) [0x01f21ee4]} 'sys_fs_stat' failed with 0x80010006 : CELL_ENOENT, “/dev_hdd0/game/BLUS30565/USRDIR/FIOS-UNREALENGINE3/PROFILE” [2]
E {PPU[0x1000010] Thread (fios mediathread 8) [0x01f21ee4]} 'sys_fs_stat' failed with 0x80010006 : CELL_ENOENT, “/dev_hdd0/game/BLUS30565/USRDIR/FIOS-UNREALENGINE3/PROFILE/PROFILE_1.BIN” [3]
E {PPU[0x1000000] Thread (main_thread) [0x01f22090]} 'sys_fs_open' failed with 0x80010006 : CELL_ENOENT, “/dev_hdd0/game/BLUS30565/USRDIR/settings-1” [2]
E {PPU[0x1000014] Thread (TrophyInfo) [0x0181d770]} 'sceNpTrophyGetTrophyInfo' failed with 0x80022913 : SCE_NP_TROPHY_ERROR_HIDDEN [1]
E {PPU[0x1000014] Thread (TrophyInfo) [0x0181d770]} sceNpTrophy: sceNpTrophyGetTrophyUnlockState(context=0x1, handle=0x1, flags=*0xd01d40f4, count=*0xd01d40e4)
S {rsx::thread} RSX: New program compiled successfully x22
E {PPU[0x1000000] Thread (main_thread) [0x01f22090]} 'sys_fs_open' failed with 0x80010006 : CELL_ENOENT, “/dev_hdd0/game/BLUS30565/USRDIR/settings-1” [3]
S {rsx::thread} RSX: New program compiled successfully x4
E {PPU[0x1000010] Thread (fios mediathread 8) [0x01e55ae0]} Stat: 'sys_fs_stat' failed with 0x80010006 : CELL_ENOENT, “/dev_hdd0/game/BLUS30565/USRDIR/PROFILE” [x4]

**Comment by Megamouse** [comment] 2018-05-13 17:53
This is a duplicate of #4553

**Comment by Megamouse** [comment] 2018-05-14 08:33
This should be fixed now

**Comment by eldrGungnir** [comment] 2018-05-14 12:37
Can confirm issue is fixed in 6737

**Closed** 2018-05-18 20:08 UTC
Labels: Meta: Invalid
