### ISSUE TITLE
One Piece Pirate Warriors all 3 don't work 

### ISSUE THREAD

**Issue by JohnSmithSor** [RPCS3/rpcs3#15973] opened 2024-08-20 01:00 UTC
### Quick summary

I'll be talking about One Piece Pirate Warriors 1 but all 3 (One Piece Pirate Warriors Trilogy on the Ps3) don't work 
![OnePiece1Failed](https://github.com/user-attachments/assets/1843a773-4c12-424a-807a-df6d45c8a3d5)

I put it on a lower setting yet it still doesn't work, 
I redisc'd the game and tried to start from the beginning against but it seems its not a disc issue but a ps3 console issue

Its the same issue for One Piece Pirate Warriors 2 
![FailedOnePiece](https://github.com/user-attachments/assets/fcf3a3f3-b7c1-426f-885d-fea6dfcf8a5b)

### Details

Gameplay lags immensely when it used to work about 5 versions ago from now

### Attach a log file

- SYS: RPCS3 v0.0.32-16843-fbcd8e32 Alpha | master
- SYS: Intel(R) Core(TM) i7-7700HQ CPU @ 2.80GHz | 8 Threads | 15.89 GiB RAM | TSC: 2.808GHz | AVX+ | FMA3
- SYS: Operating system: Windows, Major: 10, Minor: 0, Build: 19045, Service Pack: none, Compatibility mode: 0
- SYS: Current Time: 2024-08-19T20:03:11
- RSX: Found Vulkan-compatible GPU: 'Intel(R) HD Graphics 630' running on driver 0.404.63
E SIG: Thread [Vulkan Device Enumeration Thread] is too sleepy. Waiting for it 252609.265µs already!
- SYS: Firmware version: 4.90
S UPDATER: RPCS3 is up to date!
E PAT: Skipping patch data entry: [ be32, 0x00460434, 0x388000013 ] (key: PPU-c5d2fd31933f88313956774b84346d242979eba6, location: line 10297, column 6, file: C:/Games/Emulators/PS3_Emulator_#2 [Using this one]/patches/patch.yml) yaml-cpp: error at line 10298, column 27: bad conversion
E PAT: Skipping invalid patch node Disable Fisheye: (key: PPU-c5d2fd31933f88313956774b84346d242979eba6, location: line 10325, column 4, file: C:/Games/Emulators/PS3_Emulator_#2 [Using this one]/patches/patch.yml)
E PAT: Skipping patch data entry: [ be32, 0x00460434, 0x388000013 ] (key: PPU-8fd7b704255420d0e9a6b337b6d1bcaae39ff569, location: line 10297, column 6, file: C:/Games/Emulators/PS3_Emulator_#2 [Using this one]/patches/patch.yml) yaml-cpp: error at line 10298, column 27: bad conversion
E PAT: Skipping invalid patch node Disable Fisheye: (key: PPU-8fd7b704255420d0e9a6b337b6d1bcaae39ff569, location: line 10354, column 4, file: C:/Games/Emulators/PS3_Emulator_#2 [Using this one]/patches/patch.yml)
S SYS: Updates found at /dev_hdd0/game/BLES01672/
E SIG: Thread [Performance Sensor] is too sleepy. Waiting for it 22423.708µs already!
E SIG: Thread [Performance Sensor] is too sleepy. Waiting for it 42623.377µs already!
E SIG: Thread [Performance Sensor] is too sleepy. Waiting for it 84593.845µs already!
E SIG: Thread [Performance Sensor] is too sleepy. Waiting for it 169635.107µs already!
E PAT: Skipping patch data entry: [ be32, 0x00460434, 0x388000013 ] (key: PPU-c5d2fd31933f88313956774b84346d242979eba6, location: line 10297, column 6, file: C:/Games/Emulators/PS3_Emulator_#2 [Using this one]/patches/patch.yml) yaml-cpp: error at line 10298, column 27: bad conversion
E PAT: Skipping invalid patch node Disable Fisheye: (key: PPU-c5d2fd31933f88313956774b84346d242979eba6, location: line 10325, column 4, file: C:/Games/Emulators/PS3_Emulator_#2 [Using this one]/patches/patch.yml)
E PAT: Skipping patch data entry: [ be32, 0x00460434, 0x388000013 ] (key: PPU-8fd7b704255420d0e9a6b337b6d1bcaae39ff569, location: line 10297, column 6, file: C:/Games/Emulators/PS3_Emulator_#2 [Using this one]/patches/patch.yml) yaml-cpp: error at line 10298, column 27: bad conversion
E PAT: Skipping invalid patch node Disable Fisheye: (key: PPU-8fd7b704255420d0e9a6b337b6d1bcaae39ff569, location: line 10354, column 4, file: C:/Games/Emulators/PS3_Emulator_#2 [Using this one]/patches/patch.yml)
S SPU: Found 23 SPU function(s)
S SPU: Found 16 SPU function(s)
S SPU: Found 19 SPU function(s)
S SPU: Found 6 SPU function(s)
S SPU: Found 11 SPU function(s)
S SPU: Found 43 SPU function(s)
S SPU: Found 73 SPU function(s)
S SPU: Found 26 SPU function(s)
S SPU: Found 14 SPU function(s) x2
S SPU: Found 194 SPU function(s)
S SPU: Found 40 SPU function(s)
S SPU: Found 29 SPU function(s)
S SPU: Found 92 SPU function(s)
S SPU: Found 287 SPU function(s)
S SPU: Found 73 SPU function(s)
S SPU: Found 15 SPU function(s)
S PPU: Found SPURS GUID Pattern at 0x9ef280
S PPU: Found SPURS GUID Pattern for terminator at 0xa00380
S PPU: Found valid roaming SPU code at 0x9ef280..0xa00380 (guessed_ls_addr=0x0)
S SPU: Found 73 SPU function(s)
S PPU: Found SPURS GUID Pattern at 0xa00380
S PPU: Found SPURS GUID Pattern for terminator at 0xa12f00
S PPU: Found valid roaming SPU code at 0xa00380..0xa12f00 (guessed_ls_addr=0x0)
S SPU: Found 67 SPU function(s)
S PPU: Found SPURS GUID Pattern at 0xa12f00
S PPU: Found SPURS GUID Pattern for terminator at 0xa22180
S PPU: Found valid roaming SPU code at 0xa12f00..0xa22180 (guessed_ls_addr=0x0)
S SPU: Found 47 SPU function(s)
S PPU: Found SPURS GUID Pattern at 0xa22180
S PPU: Found SPURS GUID Pattern for terminator at 0xa26100
S PPU: Found valid roaming SPU code at 0xa22180..0xa26100 (guessed_ls_addr=0x0)
S SPU: Found 19 SPU function(s)
S PPU: Found SPURS GUID Pattern at 0xa26100
S PPU: Found SPURS GUID Pattern for terminator at 0xa27500
S PPU: Found valid roaming SPU code at 0xa26100..0xa27500 (guessed_ls_addr=0x0)
S SPU: Found 2 SPU function(s)
S PPU: Found SPURS GUID Pattern at 0xa27500
S PPU: Found SPURS GUID Pattern for terminator at 0xa29680
S PPU: Found valid roaming SPU code at 0xa27500..0xa29680 (guessed_ls_addr=0x0)
S PPU: Found SPURS GUID Pattern at 0xa29680
S PPU: Found SPURS GUID Pattern for terminator at 0xa2cc00
S PPU: Found valid roaming SPU code at 0xa29680..0xa2cc00 (guessed_ls_addr=0x0)
S SPU: Found 44 SPU function(s)
S PPU: Found SPURS GUID Pattern at 0xa2cc00
S PPU: Found SPURS GUID Pattern for terminator at 0xa30480
S PPU: Found valid roaming SPU code at 0xa2cc00..0xa30480 (guessed_ls_addr=0x0)
S SPU: Found 8 SPU function(s)
S PPU: Found SPURS GUID Pattern at 0xa30480
S PPU: Found SPURS GUID Pattern for terminator at 0xa35400
S PPU: Found valid roaming SPU code at 0xa30480..0xa35400 (guessed_ls_addr=0x0)
S SPU: Found 18 SPU function(s)
S PPU: Found SPURS GUID Pattern at 0xa35400
S PPU: Found SPURS GUID Pattern for terminator at 0xa36f00
S PPU: Found valid roaming SPU code at 0xa35400..0xa36f00 (guessed_ls_addr=0x0)
S SPU: Found 2 SPU function(s)
S SPU: Found 1 SPU function(s) x2
S PPU: Enabled: Non-Java Mode Fixup
S Input: The pad mode was changed to Single-threaded
S GUI: Boot successful.
E RSX: OpenGL: initialization of glTextureBarrierNV failed.
E RSX: OpenGL: initialization of glDepthRangedNV failed.
E RSX: OpenGL: initialization of glDepthBoundsdNV failed.
S RSX: GL RENDERER: Intel(R) HD Graphics 630 (Intel)
S RSX: GL VERSION: 4.3.0 - Build 31.0.101.2111
S RSX: GLSL VERSION: 4.30 - Build 31.0.101.2111
S PPU: LLVM: Loaded module v6-kusa-88sUWpmF4nJKquA1dpXdw5-00001G-skylake.obj
S PPU: LLVM: Loaded module v6-kusa-5T6419f3ArP00zxmiqvsuz-00001G-skylake.obj
S PPU: LLVM: Loaded module v6-kusa-eyXmh3yxWj0HGnaMqy2wyR-00001G-skylake.obj
S PPU: LLVM: Loaded module v6-kusa-C7ob4vuZFFYk6F5Jpsv7Vy-00001G-skylake.obj
S PPU: LLVM: Loaded module v6-kusa-NrU2H0jyc3zfKJKoyeGNa0-00001G-skylake.obj
S PPU: LLVM: Loaded module v6-kusa-fuANZ2wQTcAHKvNgxfXRFc-00001G-skylake.obj
S PPU: LLVM: Loaded module v6-kusa-Gt0iTYiTsUJCJnLnaEpZUG-00001G-skylake.obj
S PPU: LLVM: Loaded module v6-kusa-KVfXa3dSKgqYgJqF2QPKHp-00001G-skylake.obj
S PPU: LLVM: Loaded module v6-kusa-tn5gnrsUHwUf25mfiri03V-00001G-skylake.obj
S PPU: LLVM: Loaded module v6-kusa-LfFdeoRwYHMSRqNoV1Sd0j-00001G-skylake.obj
S PPU: LLVM: Loaded module v6-kusa-jG3CTtdz9TRZohgW6NaKNf-00001G-skylake.obj
S PPU: LLVM: Loaded module v6-kusa-m8pr3sQjXnd42x8V0dYmww-00001G-skylake.obj
S PPU: LLVM: Loaded module v6-kusa-2wPWbn5HXWWGWmTZduMRe0-00001G-skylake.obj
S PPU: LLVM: Loaded module v6-kusa-YSfoeoVXRe7LJNsiAe9qnX-00001G-skylake.obj
S PPU: LLVM: Loaded module v6-kusa-s58ksb6rzN9L3HLkLffmzd-00001G-skylake.obj
S PPU: LLVM: Loaded module v6-kusa-qUqMRbVpU6UHujiV01wZ0u-00001G-skylake.obj
S PPU: LLVM: Loaded module v6-kusa-oxf0P9SpU63fbQmzbcA8AE-00001G-skylake.obj
S PPU: LLVM: Loaded module v6-kusa-ktzEwxfyETQZ5Fn7gxqj4j-00001G-skylake.obj
S PPU: LLVM: Loaded module v6-kusa-Mq7PVjgxd9LRXqCg21Tr46-00001G-skylake.obj
S PPU: LLVM: Loaded module v6-kusa-J374xG1NW613L0qX6iUL83-00001G-skylake.obj
S PPU: LLVM: Loaded module v6-kusa-sacN1982xEXTpkA6vXwWXC-00001G-skylake.obj
S PPU: LLVM: Loaded module v6-kusa-WcNFL22qoJmUns12p4f5eJ-00001G-skylake.obj
S PPU: LLVM: Loaded module v6-kusa-AJkfxFjccrVS3Wi9otjhGn-00001G-skylake.obj
S PPU: LLVM: Loaded module v6-kusa-XCiiHJuLVKoWdAkNspfgdm-00001G-skylake.obj
S PPU: LLVM: Loaded module v6-kusa-ZGoTJAtFNEJR7MUSRUW8Y1-00001G-skylake.obj
S PPU: LLVM: Loaded module v6-kusa-s61JXAzF9ki8beRkLSy7Qo-00001G-skylake.obj
S PPU: LLVM: Loaded module v6-kusa-J206WGdnSh7TQKGM0MLjh1-00001G-skylake.obj
S PPU: LLVM: Loaded module v6-kusa-5CC4uChagusKpPwPXhpUwW-00001G-skylake.obj
S PPU: LLVM: Loaded module v6-kusa-QJoJJZaAbiihJQf4SJb38x-00001G-skylake.obj
S PPU: LLVM: Loaded module v6-kusa-meJLkp9dwgY6rjspZMKH9i-00001G-skylake.obj
S PPU: LLVM: Loaded module v6-kusa-sq2sKo0LxKxEUzuY23yZyR-00001G-skylake.obj
S PPU: LLVM: Loaded module v6-kusa-ML8kxYvwTnQpMgJC80E947-00001G-skylake.obj
S PPU: LLVM: Loaded module v6-kusa-EV4A4qVxdFqYxvYfvuXsfS-00001G-skylake.obj
S PPU: LLVM: Loaded module v6-kusa-JJS5rQy626ukXaKq2h4kpq-00001G-skylake.obj
S PPU: LLVM: Loaded module v6-kusa-fft8kF4rQFA7qxuzKy68w5-00001G-skylake.obj
S PPU: LLVM: Loaded module v6-kusa-G2UZrKya8gqfs1d6cTqwpZ-00001G-skylake.obj
S PPU: LLVM: Loaded module v6-kusa-ajcx5vHFS9k4VLsKZfzkXu-00001G-skylake.obj
S PPU: LLVM: Loaded module v6-kusa-sXCJKc9eGdk5ggShRHtff4-00001G-skylake.obj
S PPU: LLVM: Loaded module v6-kusa-7E8YbpCuAegc6a9gkW40F5-00001G-skylake.obj
S PPU: LLVM: Loaded module v6-kusa-Xz1Mn7vyociCRetpf15WYt-00001G-skylake.obj
S PPU: LLVM: Loaded module v6-kusa-skk1jqadCouHFsmsJgXxN3-00001G-skylake.obj
S PPU: LLVM: Loaded module v6-kusa-FrMhUpqZx4qo6pr3Rf6Vmu-00001G-skylake.obj
S PPU: LLVM: Loaded module v6-kusa-Q00yVQGAqbdJweotxkZ2VK-00001G-skylake.obj
S PPU: LLVM: Loaded module v6-kusa-hpPb7iu4xmiVFb0woGNCdk-00001G-skylake.obj
S PPU: LLVM: Loaded module v6-kusa-Zj5mdRZ5X6Acaoyz4aj5hi-00001G-skylake.obj
S PPU: LLVM: Loaded module v6-kusa-qkVV3eELiHUUMcfXdzAEHc-00001G-skylake.obj
S PPU: LLVM: Loaded module v6-kusa-gx0r5gVw7jMimG1YS5gLZ4-00001G-skylake.obj
S PPU: LLVM: Loaded module v6-kusa-7fL2X23Fuwp7WVkUGrRU16-00001G-skylake.obj
S PPU: LLVM: Loaded module v6-kusa-jkPg74iUvVEC4KMG0ehvsG-00001G-skylake.obj
S PPU: LLVM: Loaded module v6-kusa-jZ6be3CUckdaGNdLpPg8k4-00001G-skylake.obj
S PPU: LLVM: Loaded module v6-kusa-TSoYQ6mnRqK4WEuMLpxn2w-00001G-skylake.obj
S PPU: LLVM: Loaded module v6-kusa-dTJ76hoRq4FGRgCYEUi4bT-00001G-skylake.obj
S PPU: LLVM: Loaded module v6-kusa-aFtw6VJYFzLdpiCpCtKgcn-00001G-skylake.obj
S PPU: LLVM: Loaded module v6-kusa-UTXUqup2NsUa7ebNR3aweN-00001G-skylake.obj
S PPU: LLVM: Loaded module v6-kusa-4ZN2wyN4WjP4qn6RHycGx8-00001G-skylake.obj
S PPU: LLVM: Loaded module v6-kusa-dmQUwgx0UNzeEwqrfaYdkE-00001G-skylake.obj
S PPU: LLVM: Loaded module v6-kusa-UjdSzHVzw4WFiPqAfF8Rf1-00001G-skylake.obj
S PPU: LLVM: Loaded module v6-kusa-p3J2RaK6WaSazuT7R6Cy23-00001G-skylake.obj
S PPU: LLVM: Loaded module v6-kusa-9pzL6TJACcA2npJG0Y4kfS-00001G-skylake.obj
S PPU: LLVM: Loaded module v6-kusa-Ge4wsJm8hNUi3ZoF9h2iMo-00001G-skylake.obj
S PPU: LLVM: Loaded module v6-kusa-jUwCfUJ0Sj4EdEY9dWxmHU-00001G-skylake.obj
S PPU: LLVM: Loaded module v6-kusa-sVYSgaG0Ejtf28feYxW0TL-00001G-skylake.obj
S PPU: LLVM: Loaded module v6-kusa-TjMUjfFATyVYSiQs2PtSJf-00001G-skylake.obj
S PPU: LLVM: Loaded module v6-kusa-7M0ETAtUEUbV9qGKq6kCeU-00001G-skylake.obj
S PPU: LLVM: Loaded module v6-kusa-bbHV22wdqkCW4rGFWjSeWU-00001G-skylake.obj
S PPU: LLVM: Loaded module v6-kusa-sxs9A4eMECcGzJtQhJixJt-00001G-skylake.obj
S PPU: LLVM: Loaded module v6-kusa-tazCUqoy6aLNTpsdSrwU6W-00001G-skylake.obj
S PPU: LLVM: Loaded module v6-kusa-rpgLnabuvh22MYzjFcQ9eM-00001G-skylake.obj
S PPU: LLVM: Loaded module v6-kusa-NbhWXPTTUEh9Pj5eUWhChd-00001G-skylake.obj
S PPU: LLVM: Loaded module v6-kusa-mn5Hc6FFFSa2ZK18ucJCRW-00001G-skylake.obj
S PPU: LLVM: Loaded module v6-kusa-0QMdqW9vUXr6d5NZpMGKeq-00001G-skylake.obj
S PPU: LLVM: Loaded module v6-kusa-eMzWxmR6AZWie6za4cWjXZ-00001G-skylake.obj
S PPU: LLVM: Loaded module v6-kusa-LG0AnfvuN6MdLtHPphddeh-00001G-skylake.obj
S PPU: LLVM: Loaded module v6-kusa-iS1r3CrTWUa9rtaspcf2ps-00001G-skylake.obj
S PPU: LLVM: Loaded module v6-kusa-1jgWNv3TcxW7XY7WoFGYeN-00001G-skylake.obj
S PPU: LLVM: Loaded module v6-kusa-SWN2M2gYfAXbqmPeu8ZuXK-00001G-skylake.obj
S PPU: LLVM: Loaded module v6-kusa-qE4MT3WJ5Cz8q8W61dAL6y-00001G-skylake.obj
S PPU: LLVM: Loaded module v6-kusa-MQobXskisUJYgj2ya4sEh4-00001G-skylake.obj
S PPU: LLVM: Loaded module v6-kusa-ncKxfzt79EKbSAx74iAPZk-00001G-skylake.obj
S PPU: LLVM: Loaded module v6-kusa-YANKdNoqT1f5Jbt26iVLud-00001G-skylake.obj
S PPU: LLVM: Loaded module v6-kusa-4Fy9Rfwa0x9XhMsdQYZd2c-00001G-skylake.obj
S PPU: LLVM: Loaded module v6-kusa-mF4UNzFx4d0kx9jJ0JRvgW-0004Xj-skylake.obj
S PPU: LLVM: Loaded module v6-kusa-UAxtfWCozPHiv30yoG2Ucd-0004Xj-skylake.obj
S SPU: SPU Runtime: Built the interpreter.
S SPU: Detected cellSync function at 0x16274, disabling reservation notification.
S SPU: PUTLLC0 Pattern Detected! (put_pc=0x162f8, QWQgxT1syJQPAbiYsai06R26xwZR) (putllc0=1, putllc16+0=1, all=4)
S SPU: Detected cellSync function at 0x31e24, disabling reservation notification.
S SPU: PUTLLC0 Pattern Detected! (put_pc=0x31ea8, Ws8gdPF5EnUNufQjGcnUv5G0x7US) (putllc0=2, putllc16+0=2, all=11)
S SPU: Detected cellSync function at 0x31fc0, disabling reservation notification.
S SPU: Detected cellSync function at 0x38b18, disabling reservation notification.
S SPU: Detected cellSync function at 0x3897c, disabling reservation notification.
S SPU: PUTLLC0 Pattern Detected! (put_pc=0x38a00, Lihi3j2YMmJVwsh8qciNyPfJVYTN) (putllc0=3, putllc16+0=3, all=17)
S SPU: STQR/LQR Atomic Loop Hack: abs_pos=0x18e0, abs=0x2b10, i16*4=0x1848, ls_bound=0x17f
S SPU: Detected cellSync function at 0x16410, disabling reservation notification.
S SPU: Detected cellSync function at 0x16274, disabling reservation notification.
S SPU: PUTLLC0 Pattern Detected! (put_pc=0x162f8, gptpxGcYc4bmLdUdtnZGVXPetc47) (putllc0=4, putllc16+0=4, all=71)
S SPU: Detected cellSync function at 0x116dc, disabling reservation notification.
S SPU: PUTLLC0 Pattern Detected! (put_pc=0x11760, N8d4kzqQSktUEMpVepp7gcfKP0wk) (putllc0=5, putllc16+0=5, all=80)
S SPU: Detected cellSync function at 0x11878, disabling reservation notification.
S SPU: SPU Runtime: Built 7293 functions.
U sys_prx TODO: _sys_prx_register_module(name=“cellProcessElf”, opt=*0xd0020c90)
S PPU: LLVM: Loaded module v6-kusa-7LHmPKQURuTbHwAhSpWFH6-0004Xj-skylake.obj
S sys_prx: Loaded module: “/dev_flash/sys/external/libsysmodule.sprx” (id=0x23000b00)
U sys_ss TODO: sys_ss_access_control_engine(pkg_id=0x1, a2=0x1, a3=0xd0020a00)
E SYS: 'sys_ss_access_control_engine' failed with 0x80010003 : CELL_ENOSYS [1]
U sys_ss TODO: sys_ss_access_control_engine(pkg_id=0x2, a2=0xd0020a00, a3=0x0)
S PPU: LLVM: Loaded module v6-kusa-XCgQWMc1s99n1WTwrpWvw4-0004Xj-skylake.obj
S sys_prx: Loaded module: “/dev_flash/sys/external/libgcm_sys.sprx” (id=0x23000e00)
S PPU: Found SPURS GUID Pattern at 0xeb1380
S PPU: Found SPURS GUID Pattern for terminator at 0xeb3580
S PPU: Found valid roaming SPU code at 0xeb1380..0xeb3580 (guessed_ls_addr=0x0)
S PPU: Found SPURS GUID Pattern at 0xeb5400
S PPU: Found SPURS GUID Pattern for terminator at 0xeb5a80
S PPU: Found valid roaming SPU code at 0xeb5400..0xeb5a80 (guessed_ls_addr=0x0)
S PPU: Found SPURS GUID Pattern at 0xeb5a80
S PPU: Found SPURS GUID Pattern for terminator at 0xeb6200
S PPU: Found valid roaming SPU code at 0xeb5a80..0xeb6200 (guessed_ls_addr=0x0)
S PPU: Found SPURS GUID Pattern at 0xeb6200
S PPU: Found SPURS GUID Pattern for terminator at 0xeba080
S PPU: Found valid roaming SPU code at 0xeb6200..0xeba080 (guessed_ls_addr=0x0)
S PPU: Found SPURS GUID Pattern at 0xeba080
S PPU: Found valid roaming SPU code at 0xeba080..0xebde00 (guessed_ls_addr=0x0)
S PPU: LLVM: Loaded module v6-kusa-1Au1tg93M0j9aPxhbpVJAC-00001G-skylake.obj
S PPU: LLVM: Loaded module v6-kusa-5MR5UPWcNoRKHsUNJqHbKV-0004Xj-skylake.obj
S sys_prx: Loaded module: “/dev_flash/sys/external/libsre.sprx” (id=0x23001100)
S PPU: LLVM: Loaded module v6-kusa-fLV79QqHgPi90UziTsWrHo-0004Xj-skylake.obj
S sys_prx: Loaded module: “/dev_flash/sys/external/libfs.sprx” (id=0x23001200)
U sys_prx TODO: _sys_prx_register_module(name=“_sysProcessElf”, opt=*0xd0020da0)
S PPU: LLVM: Loaded module v6-kusa-e6Ztz5quEuXfyACR7GqJvc-0004Xj-skylake.obj
S sys_prx: Loaded module: “/dev_flash/sys/external/libresc.sprx” (id=0x23003400)
S PPU: LLVM: Loaded module v6-kusa-cUEpGE22ysPsPTHS4qXRmR-0004Xj-skylake.obj
S sys_prx: Loaded module: “/dev_flash/sys/external/libadec.sprx” (id=0x23003500)
S PPU: LLVM: Loaded module v6-kusa-jJwzGJv5R9eZMHq9J8MkYv-0004Xj-skylake.obj
S sys_prx: Loaded module: “/dev_flash/sys/external/libat3dec.sprx” (id=0x23003600)
S PPU: LLVM: Loaded module v6-kusa-Pkr7XAuXfpc5E5k8wfApJc-0004Xj-skylake.obj
S sys_prx: Loaded module: “/dev_flash/sys/external/libatxdec.sprx” (id=0x23003700)
S PPU: LLVM: Loaded module v6-kusa-KSs9JzJU0dS673WTN14GGy-0004Xj-skylake.obj
S sys_prx: Loaded module: “/dev_flash/sys/external/libatrac3plus.sprx” (id=0x23003800)
S PPU: LLVM: Loaded module v6-kusa-jJoZ07PrzerYWWhZciLzhv-0004Xj-skylake.obj
S sys_prx: Loaded module: “/dev_flash/sys/external/libl10n.sprx” (id=0x23003900)
S PPU: LLVM: Loaded module v6-kusa-KteEiVsCbuKT791v7VZYwX-0004Xj-skylake.obj
S sys_prx: Loaded module: “/dev_flash/sys/external/libac3dec.sprx” (id=0x23003a00)
E PPU: 118 instructions will be compiled on per-instruction basis in total
S PPU: LLVM: Loaded module v6-kusa-dkJsxGRq256WzgT9Jdm1sE-00001G-skylake.obj
S PPU: LLVM: Loaded module v6-kusa-ek9iYJASYznPhTZm1YXJRz-0004Xj-skylake.obj
S sys_prx: Loaded module: “/dev_flash/sys/external/libsail.sprx” (id=0x23003b00)
U sys_ss TODO: sys_ss_access_control_engine(pkg_id=0x1, a2=0x1, a3=0xd00207a8)
E SYS: 'sys_ss_access_control_engine' failed with 0x80010003 : CELL_ENOSYS [2]
S PPU: LLVM: Loaded module v6-kusa-0YGzaLrMF50X8yE9c59dd2-0004Xj-skylake.obj
S sys_prx: Loaded module: “/dev_flash/sys/external/libfiber.sprx” (id=0x23004100)
S PPU: Found SPURS GUID Pattern at 0x10b7200
S PPU: Found valid roaming SPU code at 0x10b7200..0x10bea80 (guessed_ls_addr=0x0)
S PPU: LLVM: Loaded module v6-kusa-fNAFCrZ8xY5ftqnyUQLfTd-0004Xj-skylake.obj
S sys_prx: Loaded module: “/dev_flash/sys/external/libspurs_jq.sprx” (id=0x23004200)
S PPU: LLVM: Loaded module v6-kusa-t1xTtC1PVoW6Jh636RxJVQ-00001G-skylake.obj
S PPU: LLVM: Loaded module v6-kusa-2wS6UCQGvL8KpqZwEg6HX7-0004Xj-skylake.obj
S sys_prx: Loaded module: “/dev_flash/sys/external/libnet.sprx” (id=0x23004400)
U sys_prx TODO: _sys_prx_get_module_id_by_name(name=“cellLibprof”, flags=0, pOpt=*0x0)
E SYS: '_sys_lwmutex_lock' failed with 0x80010005 : CELL_ESRCH [1]
E SYS: '_sys_lwmutex_lock' failed with 0x80010005 : CELL_ESRCH [2]
E SYS: '_sys_lwmutex_lock' failed with 0x80010005 : CELL_ESRCH [3]
E SYS: 'cellNetCtlInit' failed with 0x80130102 : CELL_NET_CTL_ERROR_NOT_TERMINATED [1]
U cellNetCtl TODO: cellNetCtlAddHandler(handler=*0xae05f0, arg=*0x0, hid=*0x3326c284)
E sys_fs: 'sys_fs_opendir' failed with 0x80010006 : CELL_ENOENT, “/dev_hdd0/game/BLES01672/USRDIR/DLC” [1]
S PPU: LLVM: Loaded module v6-kusa-4RvCp1PnzhcZcunZsLjmcG-0004Xj-skylake.obj
S sys_prx: Loaded module: “/dev_flash/sys/external/libdmux.sprx” (id=0x2303cf00)
S PPU: LLVM: Loaded module v6-kusa-VZcVmykW24Mqf5UJab7kxN-0004Xj-skylake.obj
S sys_prx: Loaded module: “/dev_flash/sys/external/libdmuxpamf.sprx” (id=0x2303d000)
S PPU: LLVM: Loaded module v6-kusa-ttuWcrR8vkrZXRoK2sr771-0004Xj-skylake.obj
S sys_prx: Loaded module: “/dev_flash/sys/external/libsmvd2.sprx” (id=0x2303e500)
S sys_prx: _sys_prx_unload_module(id=0x2303e500, flags=0x0, pOpt=*0x0): name='libsmvd2.sprx'
S sys_prx: _sys_prx_unload_module(id=0x2303e400, flags=0x0, pOpt=*0x0): name='libvdec.sprx'
S sys_prx: _sys_prx_unload_module(id=0x2303d000, flags=0x0, pOpt=*0x0): name='libdmuxpamf.sprx'
S sys_prx: _sys_prx_unload_module(id=0x2303cf00, flags=0x0, pOpt=*0x0): name='libdmux.sprx'
S sys_prx: _sys_prx_unload_module(id=0x2303cc00, flags=0x0, pOpt=*0x0): name='libpamf.sprx'
U sys_net TODO: sys_net_infoctl(cmd=53, arg=*0xd00203d8)
E SYS: 'sys_net_bnet_recvfrom' failed with 0xffffffea : -SYS_NET_EINVAL [1]
E SYS: 'sys_net_bnet_recvfrom' failed with 0xffffffea : -SYS_NET_EINVAL [2]
E SYS: 'sys_net_bnet_recvfrom' failed with 0xffffffea : -SYS_NET_EINVAL [3]

**Comment by AniLeo** [comment] 2024-08-20 05:20
Duplicate of #15958

**Closed by AniLeo** 2024-08-20 05:20 UTC
