### ISSUE TITLE
Dragon Quest Builders [NPJB00765] - Access violation at 0x0

### ISSUE THREAD

**Issue by fureloka** [RPCS3/rpcs3#4232] opened 2018-02-28 05:14 UTC
Dragon Quest Builders crashes with an access violation at address 0x0, this mostly seem to happen at random whenever a shader is compiling, though I could be wrong. It's guaranteed to happen  ﻿before the end of the beginner tutorial.

Have tried with OpenGL, Vulkan, different PPU Decoder and SPU Decoder, same end result.

I noticed the Blu-ray version [BLJM61311] is listed as playable, could be a regression?

RPCS3 v0.0.5-6464-b61a69c87 Alpha | master
OS: Gentoo Linux (~amd64)
CPU: AMD FX-6100
GPU: Nvidia GTX 970
Memory: 16GB DDR3
Log: [RPCS3.log.gz](https://github.com/RPCS3/rpcs3/files/1765636/RPCS3.log.gz)

**Comment by Asinin3** [comment] 2018-02-28 05:19
Try some old builds starting from say December, and try to find where the game regressed if it did. Memory Access Violations could be caused by many different things so it's not very useful unless you can find what change broke the game.

**Comment by fureloka** [comment] 2018-02-28 07:09
Wasn't sure if there was a significant difference between Blu-ray and PSN titles, thus felt like asking first.

I've tried commit 0.0.4-6209-d8ae94df, which was "confirmed" to work and sadly the same result, so probably not a regression. I'll do the same test on Windows 10, just to be sure it isn't OS specific.

**Comment by kd-11** [comment] 2018-02-28 07:47
Looks like MFC thread crashed for some reason. There have been alot of changes to SPU+MFC interaction lately (since early december), might be what has caused the issue to surface.

**Comment by fureloka** [comment] 2018-03-05 13:36
The last stable commit for Windows 10 seem to be [ad97780c4](https://github.com/RPCS3/rpcs3/commit/ad97780c4ff81d25d6749c64106ccd17d428ec31).
[8b476b5bf](https://github.com/RPCS3/rpcs3/commit/8b476b5bfa04d975dc188d7e71dd4a9748a5ffd1) and [34e01ba3d](https://github.com/RPCS3/rpcs3/commit/34e01ba3d8ec11f610ff1206a4942c04d9b2f0b3) couldn't be built separately due to [8b476b5bf](https://github.com/RPCS3/rpcs3/commit/8b476b5bfa04d975dc188d7e71dd4a9748a5ffd1)'s  dependency on [d17093e65](https://github.com/RPCS3/rpcs3/commit/d17093e65bdf6fa558e3f2b1146ce297cebc06d8), which is where the access violation starts showing up on Windows.

On Linux I haven't been able to find a commit that doesn't end with an access violation after 2+ hours of play, but [ad97780c4](https://github.com/RPCS3/rpcs3/commit/ad97780c4ff81d25d6749c64106ccd17d428ec31) is by far the most stable even for Linux. Then again, it could be a separate problem, since any commit after [ad97780c4](https://github.com/RPCS3/rpcs3/commit/ad97780c4ff81d25d6749c64106ccd17d428ec31) usually get an access violation within 1-20 minutes in-game.

**Comment by scribam** [comment] 2018-05-10 13:40
@fureloka can you check again if this issue persists on master (737db90058beb93d83d12ea94c405476ee594bfc)?

**Comment by fureloka** [comment] 2018-05-11 02:57
Tested 737db90 and it's rock solid on Windows 10, 5 hours (1 hour of active play and 4 of idling) in-game, no violation or any other hiccups.

I'll check Linux tomorrow, as well as running a secondary run for Windows, just to be sure.

**Comment by fureloka** [comment] 2018-05-17 02:17
Sorry for the late feedback on Linux, RL can be busy at times 😭 
Anyways, had the same experience on Linux, rock solid, no violation of any kind.
 
I guess this issue could be closed, unless there's an interest in figuring out which commit solved the access violation?

**Comment by scribam** [comment] 2018-10-13 12:34
@fureloka I think this issue can be closed without having to figure out which commit solved it.

**Comment by AniLeo** [comment] 2019-01-09 01:47
Closing as fixed

**Closed by AniLeo** 2019-01-09 01:47 UTC
