### ISSUE TITLE
RPCS3 not read mounted ISO in Linux

### ISSUE THREAD

**Issue by Augusto7743** [RPCS3/rpcs3#10204] opened 2021-04-28 09:13 UTC
I had used RPCS3 in windows in 2018 and had used PowerISO to mount ISO. RPCS3 read correctly the virtual drive and the game start with gameplay.
In Linux Ubuntu 20.04 using GCDEMU is possible mount ISO and all files are read correctly if using file managers, but RPCS3 not start mounted ISOs. The mounted game ISO title is displayed in RPCS3, but RPCS3 only read and recompile the EBOOT.BIN and after when stop start task. game window not will be created.
I not has information if current release read correctly ISOs in windows.
Linux file security not allowing RPCS3 to read the virtual drive or RPCS3 Linux version not support file system to be redirected to an virtual drive ?
ISO mount is extremely good feature. Is possible create and compressed ISO and thus using much less disk space and also is possible create hardlinks to games that need hard disk installation.

Thanks for read my topic.

**Comment by Megamouse** [comment] 2021-04-28 09:13
duplicate of #4021

**Closed by Megamouse** 2021-04-28 09:13 UTC
