### ISSUE TITLE
[Regression] Blitz: The League II - Emu Closes on Boot (#13534)

### ISSUE THREAD

**Issue by Hinkiii** [RPCS3/rpcs3#13731] opened 2023-04-22 18:43 UTC
### Quick summary

It'll compile PPU modules then close the entire EMU.

### Details

It would freeze when succeeding but now it straight won't even show boot logos.

### Build with regression

 v0.0.27-14846-fb88e1c1

### Attach two log files

[RPCS3.log (v0.0.27-14845-7081b89e)](https://github.com/RPCS3/rpcs3/files/11302062/RPCS3.log)
[RPCS3.log (v0.0.27-14846-fb88e1c1)](https://github.com/RPCS3/rpcs3/files/11302064/RPCS3.log)

### System configuration

Ryzen 7 3700X
GTX 1070 - 531.41
24GB RAM

**Comment by Hinkiii** [comment] 2023-04-22 18:51
Will boot on PPU interpreter, not PPU recompiler

**Comment by AniLeo** [comment] 2023-04-23 13:47
Can you try with #13738?

**Comment by Hinkiii** [comment] 2023-04-26 19:27
> #13738

Also closes after compiling PPU modules on recompiler

**Comment by AniLeo** [comment] 2023-05-03 04:53
Duplicate of #13731, verified regression on Ryzen CPUs with LLVM CPU znver*

**Closed by AniLeo** 2023-05-03 04:53 UTC
Labels: Regression
