### ISSUE TITLE
DX12 to_surface_depth_format 0

### ISSUE THREAD

**Issue by SakataGintokiYT** [RPCS3/rpcs3#1711] opened 2016-05-24 16:44 UTC
@raven02 
{rsx::thread} class fmt::exception thrown: rsx::to_surface_depth_format(): Unknow surface depth format 0
(in file C:\rpcs3\rpcs3\Emu\RSX\GCM.cpp:991)

Log : https://gist.github.com/SakataGintokiYT/67c52f9ef72835243f327d80b2a12694

**Comment by MoochMcGee** [comment] 2016-05-24 21:58
According to the folks at nouveau, this is the result of a bogus command.

**Comment by danilaml** [comment] 2016-05-24 22:16
@SakataGintokiYT can you test on some relatively old (pre 0.0.0.9) build and see if it was an issue back then?

**Comment by SakataGintokiYT** [comment] 2016-05-25 17:45
@danilaml 
On older builds 0.0.0.9 the same issue

**Comment by raven02** [comment] 2016-05-26 03:38
Please close this .It is duplicate of

**Comment by raven02** [comment] 2016-05-26 03:38
Please close this .It is duplicate of #1681

**Closed** 2016-05-26 06:10 UTC
