### ISSUE TITLE
Vulkan API call failed [BLUS30718]

### ISSUE THREAD

**Issue by nxgensoftware** [RPCS3/rpcs3#14017] opened 2023-06-13 08:29 UTC
### Quick summary

I'm getting a failed assertion error from the Vulkan API (Vulkan API call failed with unrecoverable error: Unknown Code (C462C118h, -1000161000))

The title that caused this crash was The Tomb Raider Trilogy [BLUS30718] (only attempted to run Tomb Raider Legend, might not occur on Anniversary and/or Underworld)

Last few lines in log:

 F {RSX [0x023c6ac]} SIG: Thread terminated due to fatal error: Assertion Failed! Vulkan API call failed with unrecoverable error: Unknown Code (C462C118h, -1000161000)
(in file C:\Users\ContainerAdministrator\AppData\Local\Temp\cirrus-ci-build\rpcs3\Emu\RSX\VK\vkutils\descriptors.cpp:241[:4], in function next_subpool)
(in file C:\Users\ContainerAdministrator\AppData\Local\Temp\cirrus-ci-build\rpcs3\Emu\RSX\VK\vkutils\descriptors.cpp:241[:4], in function next_subpool)
(in file C:\Users\ContainerAdministrator\AppData\Local\Temp\cirrus-ci-build\rpcs3\Emu\RSX\VK\vkutils\shared.cpp:111[:24], in function die_with_error)

### Attach a log file

[RPCS3.log](https://github.com/RPCS3/rpcs3/files/11732073/RPCS3.log)

### System configuration

LG Gram 15'' 15Z90Q
Specs:
CPU: Intel Core i5-1240P
GPU: Intel Iris Xe
OS: Windows 11 10.0.22621

RPCS3 build: 0.0.28-15172-5d7e75c5 Alpha

**Comment by MSuih** [comment] 2023-06-13 08:36
Duplicate of #13997. Try the linked pull request on that issue and report your findings on the PR. [Here are instructions on how to download it](https://wiki.rpcs3.net/index.php?title=Help:Using_different_versions_of_RPCS3#How_to_download_builds_from_a_pull_request_on_GitHub?).

**Closed by MSuih** 2023-06-13 08:36 UTC
