### ISSUE TITLE
Regression: AMD GPU crashes on RDR after #12020

### ISSUE THREAD

**Issue by xddxd** [RPCS3/rpcs3#12191] opened 2022-06-07 06:36 UTC
The AMD Vulkan driver crashes on Red Dead Redemption (and L.A Noire) since PR #12020. Either RPCS3 force closes or Windows TDR kicks in. This does not seem to affect Nvidia GPUs.

![image](https://user-images.githubusercontent.com/1712979/172312090-887a3de9-d107-48da-82bf-257fb1f94b7f.png)

[RPCS3.log](https://github.com/RPCS3/rpcs3/files/8850689/RPCS3.log)

**Comment by kd-11** [comment] 2022-06-07 06:56
I need more data here, because I'm not experiencing this on my AMD card.

**Comment by kd-11** [comment] 2022-06-07 18:42
I'm still not able to reproduce on Adrenalin 22.5.1 + 6700XT
We need more users with AMD cards to verify this one.

**Comment by jr1991-g** [comment] 2022-06-07 19:28
It's the same bug as issue #12061, now on Windows. Antialiasing is the culprit. It does happens on top spin 4 aswell.

**Comment by kd-11** [comment] 2022-06-08 18:36
I'm not able to reproduce 100% but I got a crash with validation layers that gives me a clue.

**Comment by kd-11** [comment] 2022-06-08 19:06
Should be fixed by https://github.com/RPCS3/rpcs3/pull/12200

**Comment by xddxd** [comment] 2022-06-08 22:07
Fixed by #12200

**Comment by jr1991-g** [comment] 2022-06-08 22:08
> Should be fixed by #12200

Confirmed fixed.

**Closed** 2022-06-08 23:13 UTC
Labels: Bug, Render: Vulkan
