### ISSUE TITLE
Possible regression in Castlevania: Harmony of Despair 

### ISSUE THREAD

**Issue by TheNewClassics** [RPCS3/rpcs3#6617] opened 2019-09-22 14:45 UTC
The compatibility reports for Castlevania: Harmony of Despair have it listed as playable, however no matter what settings I've used I'm getting an RSX verification error. I can't pinpoint when it regressed exactly. 

Log below:

[RPCS3.log.gz](https://github.com/RPCS3/rpcs3/files/3639854/RPCS3.log.gz)

**Comment by AniLeo** [comment] 2019-09-22 16:53
If it's a regression, we need to know in what build it regressed

**Comment by TheNewClassics** [comment] 2019-09-22 17:00
Taking a look back at the compatibility reports, it looks as if 0.0.5-7444 was the last time when it was working properly.

**Comment by KMetalmind** [comment] 2019-09-23 09:18
Are you sure is not a config or DLC problem?

I've downloaded the latest version of the website and the game is working perfectly. I usually copy the latest files on the previous RPCS3 folder, replacing old files.

On the log it breaks at this line:
RSX: class std::runtime_error thrown: Verification failed: 
(in file C:\projects\rpcs3\rpcs3\Emu\RSX\rsx_cache.h:93)

Have you tried redownloading RPCS3 or clearing the cache for the game? Searching for that error, it seems it may trigger for some people but not for others. It seems the error happened on Top Spin 4 before, the solution was: Remove the checkmark "Use GPU Texture Scaling".

**Comment by TheNewClassics** [comment] 2019-09-23 21:23
Thanks for the input. I tried redownloading and clearing the cache. Also tried switching pretty much every extra graphical setting. Could you share your exact config? Something keeps tripping it with my setup.

**Comment by KMetalmind** [comment] 2019-09-29 12:08
Here it is, sorry for the delay:
[config_NPEB00563.zip](https://github.com/RPCS3/rpcs3/files/3667290/config_NPEB00563.zip)

I hope it fixes the problem...

**Comment by kd-11** [comment] 2019-10-01 21:21
Actually this games was heavily tested (including by me) very recently for [this issue.](https://github.com/RPCS3/rpcs3/issues/6259) Seems to work fine with every setting I tried, which makes it more likely to be corrupt game files.

**Comment by RokkumanX** [comment] 2019-11-26 09:12
Other than the DLC character crashes this game works really good these days, thanks once again @kd-11 for fixing that issue with the missing effects!

**Comment by RokkumanX** [comment] 2020-01-31 11:32
Is this still a thing?

**Comment by digitaldude555** [comment] 2020-02-26 19:53
@TheNewClassics  well?

**Comment by AniLeo** [comment] 2020-03-03 09:58
We can't reproduce this, the game is Playable, I'll be closing this. It's either fixed or an issue with your dump. If you can reproduce this, ping with RPCS3.log file.

**Closed by AniLeo** 2020-03-03 09:58 UTC
Labels: Need Information
