### ISSUE TITLE
WWE Smackdown Vs Raw 2011 [BLUS30621] with flickering textures and slow gameplay during backstage

### ISSUE THREAD

**Issue by vaishnav67** [RPCS3/rpcs3#12669] opened 2022-09-17 04:45 UTC
### Quick summary

WWE Smackdown Vs Raw 2011 with flickering textures on wrestlers in all game modes and slow gameplay but normal audio during Road to WrestleMania. Playing this on 0.0.24-14162-9d9e18f6 Alpha | master.

### Details

How the game plays right now: 

https://user-images.githubusercontent.com/32519167/190840486-ff49b364-19be-4423-8d85-960fdb103c45.mp4

How it's actually supposed to be: https://www.youtube.com/watch?v=eoIBqAmFtb4

### Attach a log file

[RPCS3.log.gz](https://github.com/RPCS3/rpcs3/files/9590921/RPCS3.log.gz)

### Attach capture files for visual issues

[BLUS30621_20220917100615_capture.zip](https://github.com/RPCS3/rpcs3/files/9590931/BLUS30621_20220917100615_capture.zip)

### System configuration

OS: Windows 11
CPU: Intel(R) Core(TM) i7-8750H CPU @ 2.20GHz
GPU: Nvidia RTX 2060 Mobile (Driver version 516.94)

**Comment by AniLeo** [comment] 2022-09-17 14:19
Should be filed as a compatibility report, specially since it's not on the compatibility list

**Comment by AniLeo** [comment] 2022-09-17 14:20
Closing as a duplicate of #12649

**Closed by AniLeo** 2022-09-17 14:20 UTC
