### ISSUE TITLE
Kingdom Hearts 1.5 Black screen in Wonderland

### ISSUE THREAD

**Issue by LeonoIV** [RPCS3/rpcs3#8923] opened 2020-09-17 16:16 UTC
So i am playing KH1 1.5 Remix and when i open the proof in wonderland (the tribunal), after the cutscene the game go in black screen

[RPCS3.log](https://github.com/RPCS3/rpcs3/files/5240504/RPCS3.log)

* OS Windows 10
* CPU i5 4440 
* GPU GTX 1050ti
* RAM 16GB

**Comment by Satan86** [comment] 2020-09-17 16:20
Duplicate of #8743

**Comment by kd-11** [comment] 2020-10-18 16:25
Duplicate and already fixed.

**Closed by kd-11** 2020-10-18 16:25 UTC
