### ISSUE TITLE
OpenGl broken on Linux (Mesa) after #4265

### ISSUE THREAD

**Issue by toccata10** [RPCS3/rpcs3#4284] opened 2018-03-13 22:16 UTC
All my games give either a black screen or strange displays with OpenGl. With Vulkan, the rendering is correct (but slow: about 30fps, when I get 60fps on OGl).
It seems to follow the #4265
R9 Fury, mesa 17.3, ArchLinux
I join 2 logs.
[RPCS3.log-VF5.gz](https://github.com/RPCS3/rpcs3/files/1808833/RPCS3.log-VF5.gz)
[RPCS3.log-JoJo.gz](https://github.com/RPCS3/rpcs3/files/1808834/RPCS3.log-JoJo.gz)
![selection_048](https://user-images.githubusercontent.com/7478580/37372854-94d179d2-2714-11e8-94d2-196413aba2c8.jpg)

**Comment by hcorion** [comment] 2018-03-14 01:10
I can't reproduce, most likely an issue with mesa.
Arch Linux
GTX 1070
i7 4770

**Comment by toccata10** [comment] 2018-03-14 07:58
I'll wait a bit to see what @kd-11 and other testers say, then I'll report to mesa.

**Comment by MSuih** [comment] 2018-03-14 08:51
The kd-11's commit has some issues on AMD Windows drivers as well, so this could be partially RPCS3's fault. Nothing as severe as that, though.

**Comment by kd-11** [comment] 2018-03-14 08:55
This is something else. Everything doesnt work. Afaik the changeset only breaks amd vulkan in some titles not opengl and certainly not everything run through rpcs3.
@toccata10 Try booting the sample tests that ship with rpcs3 like the basic triangle test and see if it renders fine. I had to butcher glx config on my system to get the nvidia driver to work so it might take some time before I'm able to test radeonsi.

**Comment by toccata10** [comment] 2018-03-14 09:47
Black screen with Ogl on the basic tests. Vulkan is fine.
On rpcs3-v0.0.5-6510-f2e5b6c3_linux64 these tests are working fine.
[RPCS3-SimpleTest.log](https://github.com/RPCS3/rpcs3/files/1810430/RPCS3-SimpleTest.log)
![rpcs3 0 0 5-6541-5f047034a alpha_049](https://user-images.githubusercontent.com/7478580/37394740-c4878b5c-2774-11e8-9daf-5edb934d6988.jpg)
![fps 59 84 vulkan 0 0 5-6541 -home-jo-tmp-rpcs3-rpcs3-bin-dev_hdd0-game-test12345-usrdir-gs_gcm_basic_triangle elf_050](https://user-images.githubusercontent.com/7478580/37394774-de598ee0-2774-11e8-9edd-168338eaf826.jpg)

**Comment by kd-11** [comment] 2018-03-14 10:01
enable mesa debugging MESA_DEBUG=1 then run rpcs3. If there is a problem it should be logged in the terminal

**Comment by toccata10** [comment] 2018-03-14 10:09
On basic triangle
```
WARNING: radv is not a conformant vulkan implementation, testing use only.
Mesa: User error: GL_INVALID_VALUE in glTextureBufferRange(offset=0 + size=2147483647 > buffer_size=268435456)
QOpenGLContext::swapBuffers() called with non-exposed window, behavior is undefined
QOpenGLContext::swapBuffers() called with non-exposed window, behavior is undefined
QOpenGLContext::swapBuffers() called with non-exposed window, behavior is undefined
QOpenGLContext::swapBuffers() called with non-exposed window, behavior is undefined
QOpenGLContext::swapBuffers() called with non-exposed window, behavior is undefined
QOpenGLContext::swapBuffers() called with non-exposed window, behavior is undefined
QOpenGLContext::swapBuffers() called with non-exposed window, behavior is undefined                                                                                                                     
QOpenGLContext::swapBuffers() called with non-exposed window, behavior is undefined                                                                                                                     
QOpenGLContext::swapBuffers() called with non-exposed window, behavior is undefined                                                                                                                     
QOpenGLContext::swapBuffers() called with non-exposed window, behavior is undefined     
```

**Comment by kd-11** [comment] 2018-03-14 10:12
Ok, I know what it is. Will fix soon. Its strange that the window handle becomes invalid after being already created, almost as if the OS creates another window to replace the existing one on some event

**Comment by kd-11** [comment] 2018-03-14 10:26
https://github.com/kd-11/rpcs3/commit/f46b154683258855d7ffd17ca860da01dc5000b7 should fix this issue

**Comment by toccata10** [comment] 2018-03-14 11:12
Maybe I'm making a mistake, but I can't compile from master (I just changed the rpcs3/rpcs3qt/gl_gs_frame.cpp file)
```
cc1plus: warning: /home/jo/tmp/rpcs3/kd11/rpcs3_build/rpcs3/cotire/rpcs3_CXX_prefix.hxx.gch : non utilisé parce que « __STDC_CONSTANT_MACROS » est défini [-Winvalid-pch]
/home/jo/tmp/rpcs3/kd11/rpcs3/rpcs3/rpcs3qt/gl_gs_frame.cpp: Dans la fonction membre « virtual void gl_gs_frame::flip(draw_context_t, bool) »:
/home/jo/tmp/rpcs3/kd11/rpcs3/rpcs3/rpcs3qt/gl_gs_frame.cpp:75:20: error: « ctx » n'a pas été déclaré dans cette portée
  ((QOpenGLContext*)ctx)->makeCurrent(this);
                    ^~~
make[2]: *** [rpcs3/CMakeFiles/rpcs3.dir/build.make:6677: rpcs3/CMakeFiles/rpcs3.dir/rpcs3qt/gl_gs_frame.cpp.o] Error 1
make[1]: *** [CMakeFiles/Makefile2:240: rpcs3/CMakeFiles/rpcs3.dir/all] Error 2
make: *** [Makefile:152: all] Error 2

```

**Comment by Megamouse** [comment] 2018-03-14 11:14
@toccata10 change ctx to context

**Comment by toccata10** [comment] 2018-03-14 12:26
@Megamouse : it segfaults. Here's the backtrace:
```
(in file /home/jo/tmp/rpcs3/kd11/rpcs3/Utilities/mutex.cpp:191)

Thread 1 "rpcs3" received signal SIGABRT, Aborted.
0x00007ffff25b4860 in raise () from /usr/lib/libc.so.6
(gdb) bt
#0  0x00007ffff25b4860 in raise () from /usr/lib/libc.so.6
#1  0x00007ffff25b5ec9 in abort () from /usr/lib/libc.so.6
#2  0x00007ffff2bdcd57 in __gnu_cxx::__verbose_terminate_handler ()
    at /build/gcc/src/gcc/libstdc++-v3/libsupc++/vterminate.cc:95
#3  0x00007ffff2bda8c6 in __cxxabiv1::__terminate (handler=<optimized out>)
    at /build/gcc/src/gcc/libstdc++-v3/libsupc++/eh_terminate.cc:47
#4  0x00007ffff2bd979a in __cxa_call_terminate (ue_header=ue_header@entry=0x7fffe0028f60)
    at /build/gcc/src/gcc/libstdc++-v3/libsupc++/eh_call.cc:54
#5  0x00007ffff2bda189 in __cxxabiv1::__gxx_personality_v0 (version=<optimized out>, 
    actions=<optimized out>, exception_class=5138137972254386944, ue_header=0x7fffe0028f60, 
    context=<optimized out>) at /build/gcc/src/gcc/libstdc++-v3/libsupc++/eh_personality.cc:676
#6  0x00007ffff2946ca3 in _Unwind_RaiseException_Phase2 (exc=exc@entry=0x7fffe0028f60, 
    context=context@entry=0x7fffffffc790) at /build/gcc/src/gcc/libgcc/unwind.inc:62
#7  0x00007ffff29474ce in _Unwind_Resume (exc=0x7fffe0028f60)
    at /build/gcc/src/gcc/libgcc/unwind.inc:230
#8  0x0000000000d9f949 in fmt::raw_verify_error(char const*, fmt_type_info const*, unsigned long)
    ()
#9  0x00000000006faa78 in auto verify_impl<0u>::operator,<bool>(bool&&) const [clone .isra.5] [clone .part.6] ()
#10 0x0000000000dac7d3 in shared_mutex::imp_unlock(long) ()
#11 0x0000000000dad345 in safe_writer_lock::~safe_writer_lock() ()
#12 0x0000000000c548a2 in vfs::mount(std::__cxx11::basic_string<char, std::char_traits<char>, std::allocator<char> > const&, std::__cxx11::basic_string<char, std::char_traits<char>, std::allocator<char> > const&) ()
#13 0x0000000000c46a70 in Emulator::Load(bool) ()
#14 0x0000000000c4af3b in Emulator::BootGame(std::__cxx11::basic_string<char, std::char_traits<char>, std::allocator<char> > const&, bool, bool) ()
#15 0x0000000000cfda84 in main_window::Boot(std::__cxx11::basic_string<char, std::char_traits<char>, std::allocator<char> > const&, bool, bool) ()
#16 0x0000000000cfe6ac in main_window::BootRecentAction(QAction const*) ()
#17 0x00007ffff31a27ef in QMetaObject::activate(QObject*, int, int, void**) ()
   from /usr/lib/libQt5Core.so.5
#18 0x00007ffff50ef533 in QAction::triggered(bool) () from /usr/lib/libQt5Widgets.so.5
#19 0x00007ffff50f1db6 in QAction::activate(QAction::ActionEvent) ()
   from /usr/lib/libQt5Widgets.so.5
#20 0x00007ffff5278515 in ?? () from /usr/lib/libQt5Widgets.so.5
#21 0x00007ffff527fbdc in ?? () from /usr/lib/libQt5Widgets.so.5
#22 0x00007ffff5280a44 in QMenu::mouseReleaseEvent(QMouseEvent*) ()
   from /usr/lib/libQt5Widgets.so.5
#23 0x00007ffff5136188 in QWidget::event(QEvent*) () from /usr/lib/libQt5Widgets.so.5
#24 0x00007ffff5282d7c in QMenu::event(QEvent*) () from /usr/lib/libQt5Widgets.so.5
#25 0x00007ffff50f5fec in QApplicationPrivate::notify_helper(QObject*, QEvent*) ()
   from /usr/lib/libQt5Widgets.so.5
#26 0x00007ffff50fdf41 in QApplication::notify(QObject*, QEvent*) ()
   from /usr/lib/libQt5Widgets.so.5
#27 0x00007ffff3171da0 in QCoreApplication::notifyInternal2(QObject*, QEvent*) ()
   from /usr/lib/libQt5Core.so.5
#28 0x00007ffff50fceca in QApplicationPrivate::sendMouseEvent(QWidget*, QMouseEvent*, QWidget*, QWi---Type <return> to continue, or q <return> to quit---
dget*, QWidget**, QPointer<QWidget>&, bool) () from /usr/lib/libQt5Widgets.so.5
#29 0x00007ffff5151677 in ?? () from /usr/lib/libQt5Widgets.so.5
#30 0x00007ffff5154060 in ?? () from /usr/lib/libQt5Widgets.so.5
#31 0x00007ffff50f5fec in QApplicationPrivate::notify_helper(QObject*, QEvent*) ()
   from /usr/lib/libQt5Widgets.so.5
#32 0x00007ffff50fd9c6 in QApplication::notify(QObject*, QEvent*) ()
   from /usr/lib/libQt5Widgets.so.5
#33 0x00007ffff3171da0 in QCoreApplication::notifyInternal2(QObject*, QEvent*) ()
   from /usr/lib/libQt5Core.so.5
#34 0x00007ffff3a71434 in QGuiApplicationPrivate::processMouseEvent(QWindowSystemInterfacePrivate::MouseEvent*) () from /usr/lib/libQt5Gui.so.5
#35 0x00007ffff3a72f86 in QGuiApplicationPrivate::processWindowSystemEvent(QWindowSystemInterfacePrivate::WindowSystemEvent*) () from /usr/lib/libQt5Gui.so.5
#36 0x00007ffff3a4a29c in QWindowSystemInterface::sendWindowSystemEvents(QFlags<QEventLoop::ProcessEventsFlag>) () from /usr/lib/libQt5Gui.so.5
#37 0x00007fffe887048d in ?? () from /usr/lib/libQt5XcbQpa.so.5
#38 0x00007ffff31703db in QEventLoop::exec(QFlags<QEventLoop::ProcessEventsFlag>) ()
   from /usr/lib/libQt5Core.so.5
#39 0x00007ffff31797d8 in QCoreApplication::exec() () from /usr/lib/libQt5Core.so.5
#40 0x000000000079e1a5 in main ()

```

**Comment by mrcmunir** [comment] 2018-03-16 12:15
Broken too for Intel in Opengl backend under intel Skylake mesa3d black screen.

```
Mesa: User error: GL_INVALID_ENUM in glDisable(GL_DEPTH_BOUNDS_TEST_EXT)
``
Previously OpenGL worked well.

**Comment by kd-11** [comment] 2018-03-19 14:10
Closing via https://github.com/RPCS3/rpcs3/pull/4296

**Closed by kd-11** 2018-03-19 14:10 UTC
