### ISSUE TITLE
Gamepads Settings window cut off when display scaling is set to 150% on Windows 10

### ISSUE THREAD

**Issue by nicktiberi** [RPCS3/rpcs3#5760] opened 2019-03-24 19:41 UTC
- **OS:** Windows 10
- **Build:** 0.0.6-7888
- **Display Resolution:** 1920x1080

As shown in the screenshot, the Gamepads Settings window gets cut off at the bottom of the screen when I have display scaling set to 150% (I'm playing on a TV) and I am unable to resize the window to show the buttons at the bottom, so I can't save settings without turning display scaling down.

![padsdisplayscaling](https://user-images.githubusercontent.com/639920/54884786-480f8080-4e4b-11e9-8d93-45bd4025a24b.png)

I'm a developer so I would be willing to potentially help with this issue if someone has a good idea for a solution. One thought was to wrap the controls in a scroll view (I don't know a ton about QT, so this may be incorrect terminology) so that the user can scroll down to access the buttons if the window is cut off.

**Comment by vsub** [comment] 2019-03-24 20:11
I don't think that's a rpcs3 problem,at 150% everything is too big,not just rpcs3
You need higher resolution to make everything to look normal or lower the DPI and keep 1080p
You can also do this:
rpcs3.exe=>Properties=>Compatibility=>Change High DPI Settings=>High DPI scaling overwrite=>System
That way everything is visible but the window still barely fits in the area between the top of the desktop and the top of the taskbar

**Comment by creeperjedi** [comment] 2019-03-24 20:41
This was caused by PR #4908 and Issue #5455 was opened in response to the new issues it created. Sadly, doesn't seem like this will be solved anytime soon as it is a problem with toolkit they use to create the GUI and not a problem with the emulator itself. The solution that vsub suggested does work, but makes the whole interface look blocky and low-resolution. A workaround that I have found is to move that taskbar off to the side which will reveal a few pixels of the "save" button that you can click on, and then move the taskbar back.

**Comment by Megamouse** [comment] 2019-07-13 10:20
I'll close this as a duplicate of #5455 .
All the necessary information is there as well.

**Closed by Megamouse** 2019-07-13 10:20 UTC
Labels: GUI
