### ISSUE TITLE
SPU: Channel Loop Pattern Detected! Report to developers!

### ISSUE THREAD

**Issue by Darkhost1999** [RPCS3/rpcs3#16075] opened 2024-09-13 14:39 UTC
### Quick summary

I was able to find this error after clearing my SPU cache for all titles.
I was also able to replicate it on the same game by removing SPU cache for that specific title.
The error does not occur if SPUcache has already been created.

### Details

I was testing if trophies were working for a different issue when I stumbled across
`·E 0:10:08.766592 {SPU[0x1000100] Thread (PrimaryCellSpursKernel1) [0x015c4]} SPU: Channel Loop Pattern Detected! Report to developers! (read_pc=0x15c4, branch_pc=0x15c8, branch_target=0x15c4, 0x15c4-NLWSK5vNUJzqrgq2T2KSYViLHjZG)`
and now I'm following what the error says and reporting it.
I found that when rebooting the game the error didn't occur on consecutive boots but remembered from some GitHub messages that I felt the desire to remove my cache just in case it fixes some new errors. So I tested right click -> remove spu cache for the game I encountered the error and sure enough on a new cache generation I can replicate this issue.

### Attach a log file

[RPCS3.log](https://github.com/user-attachments/files/16995315/RPCS3.log)

### Attach capture files for visual issues

N/A

### System configuration

Windows 11 pro
Gtx 1660 super
Ryzen 7 7700x

### Other details

I encountered this error in more than 1 game. I haven't compiled a full list of games I can replicate the error in.
From my memory I know I tested God of War 3 as well and got the message. If necessary I can compile a list of games.

**Comment by AniLeo** [comment] 2024-09-13 16:09
Duplicate of #15948

**Closed by AniLeo** 2024-09-13 16:09 UTC
