### ISSUE TITLE
RPCS3 does not open

### ISSUE THREAD

**Issue by Marukito** [RPCS3/rpcs3#8597] opened 2020-07-18 09:35 UTC
Hi ! (sorry for my bad english)
I have a problem with RPCS3 which means I was never able to play it
When I run RPCS3, the software appears in the "Details" of Task Manager, but not in the taskbar

To solve this problem, I already tried to reinstall the drivers of my GPU with DDU, download a old versions of RPCS3, and install "Vulkan SDK" but the problem persists :/
So thank you so much if anyone can solve my problem I'm desperate ://

My specs : 
i7 8700 3.20 GHz
GTX 1060 6GB
16GB RAM

**Comment by Megamouse** [comment] 2020-07-18 09:56
Duplicate of #8409

**Closed by Megamouse** 2020-07-18 09:56 UTC
