### ISSUE TITLE
Regressions from #5785 pes 2016 

### ISSUE THREAD

**Issue by uaqlover** [RPCS3/rpcs3#5826] opened 2019-04-11 23:23 UTC
![45444](https://user-images.githubusercontent.com/45731484/55999019-c0f93f80-5c75-11e9-8908-3f504b2f790a.png)

even try it with https://github.com/RPCS3/rpcs3/pull/5749 is same 

before https://github.com/RPCS3/rpcs3/pull/5785 was working fine 
log file 

[RPCS3 pes.zip](https://github.com/RPCS3/rpcs3/files/3070959/RPCS3.pes.zip)

**Comment by AniLeo** [comment] 2019-04-11 23:24
Try with #5813

**Comment by uaqlover** [comment] 2019-04-11 23:29
the branch is out-of-date with elad335 Commit https://github.com/RPCS3/rpcs3/pull/5749 so game can run with llvm

**Comment by AniLeo** [comment] 2019-04-11 23:35
I've rebased, test when it's built

**Comment by uaqlover** [comment] 2019-04-12 00:27
it fixed in https://github.com/RPCS3/rpcs3/pull/5813 play the game almost 30 minutes and it fine 

![FPS_ 49 18 _ Vulkan _ 0 0 6-837f11ad-fbo_fixes _ Pro Evolution Soccer 2016  BLUS31564  11_04_2019 5_24_11 PM](https://user-images.githubusercontent.com/45731484/56004206-e3dc2180-5c7e-11e9-8659-ecb1bb3d5939.png)

@AniLeo thanks again for fast respond when https://github.com/RPCS3/rpcs3/pull/5813 will marge i will close the issue

**Comment by AniLeo** [comment] 2019-04-12 00:29
Closing as duplicate of #5807 
Proceed discussion there

**Closed by AniLeo** 2019-04-12 00:29 UTC
Labels: Need Information, Regression
