### ISSUE TITLE
Gran Turismo 5 [BCUS98114] Frozen image but game still running (desynchronization of emulator)

### ISSUE THREAD

**Issue by EATYOURVITAMIN5** [RPCS3/rpcs3#6748] opened 2019-10-11 22:37 UTC
RPCS3 v0.0.7-8861-0172e097
Ryzen 5 1600x
8GB
RTX2060 6GB

Gran Turismo 5 will run for less than a minute where the picture will then freeze but the game continues to run in the background. Inspection of task manager shows 0% GPU usage (usually around 50% for me with 4K textures)

This happens on both Vulkan and OpenGL, Nvidia drivers updated to latest and various debug settings changed. Same result.

Log attached
[RPCS3.log.gz](https://github.com/RPCS3/rpcs3/files/3719824/RPCS3.log.gz)

**Comment by HHCHunter** [comment] 2019-10-12 11:31
If you're talking about the crowd moving in the background while the car is stationary, yes this regression is recent

**Comment by EATYOURVITAMIN5** [comment] 2019-10-12 13:19
Not necessarily the crowd itself, I mean the literal game. I will be racing for less than a lap, the screen will freeze but I will still be able to control the car. I hear the engine going and I feel the vibration when I hit a wall. However, all visuals are frozen and gpu usage drops to 0%

**Comment by HHCHunter** [comment] 2019-10-12 14:45
> The screen will freeze

ofc have you tried turning off anti-aliasing?

**Comment by EATYOURVITAMIN5** [comment] 2019-10-12 17:05
I have yes. No dice

**Comment by ijoshvirk** [comment] 2019-10-14 11:33
Experiencing this issue as well. The car itself freezes however you can still see the crowd in the background moving. Sometimes I am able to get in and do 1 or 2 laps however majority of the time I run into this problem.

**Comment by HHCHunter** [comment] 2019-10-14 12:04
>  The car itself freezes however you can still see the crowd in the background moving. Sometimes I am able to get in and do 1 or 2 laps however majority of the time I run into this problem.

I would say this regression has started happening in the past two weeks, however it's becoming more prevalent.
E {PPU[0x1000000] Thread (main_thread) [0x01c75ae0]} '_sys_lwcond_queue_wait' failed with 0x00000000 : 0 [1]
E {PPU[0x1000001] Thread (MpAnk) [0x00c060a4]} 'sys_event_queue_receive' failed with 0x00000000 : 0 [1]
E {PPU[0x1000004] Thread (ZBm9Y) [0x00bf0df8]} 'sys_timer_usleep' failed with 0x00000000 : 0 [1]
E {PPU[0x1000008] Thread (ksF3) [0x01c75ae0]} '_sys_lwcond_queue_wait' failed with 0x00000000 : 0 [1]
E {PPU[0x1000006] Thread (kFeqg) [0x01c75ae0]} '_sys_lwcond_queue_wait' failed with 0x00000000 : 0 [1]
E {PPU[0x100000a] Thread (ksF3) [0x01c75ae0]} '_sys_lwcond_queue_wait' failed with 0x00000000 : 0 [1]
E {PPU[0x1000002] Thread (PDISpursHdlr1) [0x01d0b604]} 'sys_event_queue_receive' failed with 0x00000000 : 0 [1]
E {PPU[0x1000003] Thread (PDISpursHdlr0) [0x01d0948c]} 'sys_spu_thread_group_join' failed with 0x00000000 : 0 [1]
E {PPU[0x100000d] Thread (ksF3) [0x01c75ae0]} '_sys_lwcond_queue_wait' failed with 0x00000000 : 0 [1]
E {PPU[0x1000011] Thread (_gcm_intr_thread) [0x01ce833c]} 'sys_event_queue_receive' failed with 0x00000000 : 0 [1]
E {PPU[0x1000009] Thread (ksF3) [0x01c75ae0]} '_sys_lwcond_queue_wait' failed with 0x00000000 : 0 [1]
E {PPU[0x100001a] Thread (libusbd_usbd_thread) [0x0204242c]} 'sys_event_queue_receive' failed with 0x00000000 : 0 [1]
E {PPU[0x100000a] Thread (ksF3)} Stat: 'sys_fs_stat' failed with 0x80010006 : CELL_ENOENT, “/dev_hdd0/game/BCES00569/USRDIR/db/system.db-journal” [x99]
E {PPU[0x1000000] Thread (main_thread)} Stat: 'cellKbGetConfiguration' failed with 0x80121007 : CELL_KB_ERROR_NO_DEVICE [x254]
E {PPU[0x1000015] Thread (sgx-spurs-SpursHdlr0) [0x01c75ae0]} '_sys_lwcond_queue_wait' failed with 0x00000000 : 0 [1]
E {PPU[0x100001e] Thread (8mBKi) [0x00ce8e1c]} 'sys_cond_wait' failed with 0x00000000 : 0 [1]
E {PPU[0x100003e] Thread (ZAbZY) [0x01c75ae0]} '_sys_lwcond_queue_wait' failed with 0x00000000 : 0 [1]
E {PPU[0x1000018] Thread (prsIy) [0x00c0e3a0]} 'sys_event_queue_receive' failed with 0x00000000 : 0 [1]
E {PPU[0x1000017] Thread (sgx-audio-thr) [0x008fe588]} 'sys_event_queue_receive' failed with 0x00000000 : 0 [1]
E {PPU[0x1000007] Thread (ksF3) [0x01c75ae0]} '_sys_lwcond_queue_wait' failed with 0x00000000 : 0 [1]
E {PPU[0x1000012] Thread (8mBKi) [0x00ce8e1c]} 'sys_cond_wait' failed with 0x00000000 : 0 [1]
E {PPU[0x1000013] Thread (lwCH) [0x00ce8e1c]} 'sys_cond_wait' failed with 0x00000000 : 0 [1]
E {PPU[0x100000e] Thread (ksF3) [0x01c75ae0]} '_sys_lwcond_queue_wait' failed with 0x00000000 : 0 [1]
E {PPU[0x100001c] Thread (9ZWAM) [0x00bf0df8]} 'sys_timer_usleep' failed with 0x00000000 : 0 [1]
E {PPU[0x100001f] Thread (fmBKi) [0x01c75ae0]} '_sys_lwcond_queue_wait' failed with 0x00000000 : 0 [1]
E {PPU[0x1000005] Thread (kFeqP) [0x01c75ae0]} '_sys_lwcond_queue_wait' failed with 0x00000000 : 0 [1]
E {PPU[0x100001d] Thread (vyENO) [0x01c75ae0]} '_sys_lwcond_queue_wait' failed with 0x00000000 : 0 [1]
E {PPU[0x1000026] Thread (n3FKY) [0x01c75ae0]} '_sys_lwcond_queue_wait' failed with 0x00000000 : 0 [1]
E {PPU[0x1000027] Thread (n3FKY) [0x01c75ae0]} '_sys_lwcond_queue_wait' failed with 0x00000000 : 0 [1]
E {PPU[0x100002b] Thread (OEyq) [0x01c75ae0]} '_sys_lwcond_queue_wait' failed with 0x00000000 : 0 [1]
E {PPU[0x1000024] Thread (vyENO) [0x01c75ae0]} '_sys_lwcond_queue_wait' failed with 0x00000000 : 0 [1]
E {PPU[0x100000b] Thread (ksF3) [0x01c75ae0]} '_sys_lwcond_queue_wait' failed with 0x00000000 : 0 [1]
E {PPU[0x1000021] Thread (MEfYS) [0x008cfd14]} 'sys_event_queue_receive' failed with 0x00000000 : 0 [1]
E {PPU[0x100000c] Thread (ksF3) [0x01c75ae0]} '_sys_lwcond_queue_wait' failed with 0x00000000 : 0 [1]
E {PPU[0x1000025] Thread (n3FKY) [0x01c75ae0]} '_sys_lwcond_queue_wait' failed with 0x00000000 : 0 [1]
E {PPU[0x100001b] Thread (lgFF) [0x00c20e08]} 'sys_event_queue_receive' failed with 0x00000000 : 0 [1]
E {PPU[0x1000022] Thread (9qstY) [0x009002a8]} 'sys_timer_usleep' failed with 0x00000000 : 0 [1]
E {PPU[0x1000023] Thread (ZYWAP) [0x01c75ae0]} '_sys_lwcond_queue_wait' failed with 0x00000000 : 0 [1]
E {PPU[0x100000c] Thread (ksF3)} Stat: 'sys_fs_stat' failed with 0x80010006 : CELL_ENOENT, “/dev_hdd1/cache/BCES00569/game249.db-journal” [x308]
E {PPU[0x100002d] Thread (AEIVZ) [0x01c75ae0]} '_sys_lwcond_queue_wait' failed with 0x00000000 : 0 [1]
E {PPU[0x1000039] Thread (ZYWr6) [0x01c75ae0]} '_sys_lwcond_queue_wait' failed with 0x00000000 : 0 [1]
E {PPU[0x100003a] Thread (Z1kIS) [0x01c75ae0]} '_sys_lwcond_queue_wait' failed with 0x00000000 : 0 [1]
E {PPU[0x1000038] Thread (PDI) [0x01c75ae0]} '_sys_lwcond_queue_wait' failed with 0x00000000 : 0 [1]
E {PPU[0x1000031] Thread (ZWAP) [0x00bf0df8]} 'sys_timer_usleep' failed with 0x00000000 : 0 [1]
E {PPU[0x100002c] Thread (CYYqg) [0x01c75ae0]} '_sys_lwcond_queue_wait' failed with 0x00000000 : 0 [1]
E {PPU[0x1000016] Thread (sgx-spurs-printf-handler) [0x009001b0]} 'sys_event_queue_receive' failed with 0x00000000 : 0 [1]
E {PPU[0x100003b] Thread (Z11K6) [0x01c75ae0]} '_sys_lwcond_queue_wait' failed with 0x00000000 : 0 [1]
E {PPU[0x1000014] Thread (sgx-spurs-SpursHdlr1) [0x01d0b604]} 'sys_event_queue_receive' failed with 0x00000000 : 0 [1]
E {PPU[0x1000010] Thread (ksF3) [0x01c75ae0]} '_sys_lwcond_queue_wait' failed with 0x00000000 : 0 [1]
E {PPU[0x100000f] Thread (ksF3) [0x01c75ae0]} '_sys_lwcond_queue_wait' failed with 0x00000000 : 0 [1]
E {PPU[0x1000010] Thread (ksF3)} Stat: 'sys_fs_stat' failed with 0x80010006 : CELL_ENOENT, “/dev_hdd0/game/BCES00569/USRDIR/PDIPFS/9/SV/K7” [x4]
E {PPU[0x1000010] Thread (ksF3)} Stat: 'sys_fs_stat' failed with 0x80010006 : CELL_ENOENT, “/dev_hdd0/game/BCES00569/USRDIR/PDIPFS/9/45/92” [x4]

**Comment by ijoshvirk** [comment] 2019-10-14 19:08
> > The car itself freezes however you can still see the crowd in the background moving. Sometimes I am able to get in and do 1 or 2 laps however majority of the time I run into this problem.
> 
> I would say this regression has started happening in the past two weeks, however it's becoming more prevalent.
> 
> ```
> E {PPU[0x1000000] Thread (main_thread) [0x01c75ae0]} '_sys_lwcond_queue_wait' failed with 0x00000000 : 0 [1]
> E {PPU[0x1000001] Thread (MpAnk) [0x00c060a4]} 'sys_event_queue_receive' failed with 0x00000000 : 0 [1]
> E {PPU[0x1000004] Thread (ZBm9Y) [0x00bf0df8]} 'sys_timer_usleep' failed with 0x00000000 : 0 [1]
> E {PPU[0x1000008] Thread (ksF3) [0x01c75ae0]} '_sys_lwcond_queue_wait' failed with 0x00000000 : 0 [1]
> E {PPU[0x1000006] Thread (kFeqg) [0x01c75ae0]} '_sys_lwcond_queue_wait' failed with 0x00000000 : 0 [1]
> E {PPU[0x100000a] Thread (ksF3) [0x01c75ae0]} '_sys_lwcond_queue_wait' failed with 0x00000000 : 0 [1]
> E {PPU[0x1000002] Thread (PDISpursHdlr1) [0x01d0b604]} 'sys_event_queue_receive' failed with 0x00000000 : 0 [1]
> E {PPU[0x1000003] Thread (PDISpursHdlr0) [0x01d0948c]} 'sys_spu_thread_group_join' failed with 0x00000000 : 0 [1]
> E {PPU[0x100000d] Thread (ksF3) [0x01c75ae0]} '_sys_lwcond_queue_wait' failed with 0x00000000 : 0 [1]
> E {PPU[0x1000011] Thread (_gcm_intr_thread) [0x01ce833c]} 'sys_event_queue_receive' failed with 0x00000000 : 0 [1]
> E {PPU[0x1000009] Thread (ksF3) [0x01c75ae0]} '_sys_lwcond_queue_wait' failed with 0x00000000 : 0 [1]
> E {PPU[0x100001a] Thread (libusbd_usbd_thread) [0x0204242c]} 'sys_event_queue_receive' failed with 0x00000000 : 0 [1]
> E {PPU[0x100000a] Thread (ksF3)} Stat: 'sys_fs_stat' failed with 0x80010006 : CELL_ENOENT, “/dev_hdd0/game/BCES00569/USRDIR/db/system.db-journal” [x99]
> E {PPU[0x1000000] Thread (main_thread)} Stat: 'cellKbGetConfiguration' failed with 0x80121007 : CELL_KB_ERROR_NO_DEVICE [x254]
> E {PPU[0x1000015] Thread (sgx-spurs-SpursHdlr0) [0x01c75ae0]} '_sys_lwcond_queue_wait' failed with 0x00000000 : 0 [1]
> E {PPU[0x100001e] Thread (8mBKi) [0x00ce8e1c]} 'sys_cond_wait' failed with 0x00000000 : 0 [1]
> E {PPU[0x100003e] Thread (ZAbZY) [0x01c75ae0]} '_sys_lwcond_queue_wait' failed with 0x00000000 : 0 [1]
> E {PPU[0x1000018] Thread (prsIy) [0x00c0e3a0]} 'sys_event_queue_receive' failed with 0x00000000 : 0 [1]
> E {PPU[0x1000017] Thread (sgx-audio-thr) [0x008fe588]} 'sys_event_queue_receive' failed with 0x00000000 : 0 [1]
> E {PPU[0x1000007] Thread (ksF3) [0x01c75ae0]} '_sys_lwcond_queue_wait' failed with 0x00000000 : 0 [1]
> E {PPU[0x1000012] Thread (8mBKi) [0x00ce8e1c]} 'sys_cond_wait' failed with 0x00000000 : 0 [1]
> E {PPU[0x1000013] Thread (lwCH) [0x00ce8e1c]} 'sys_cond_wait' failed with 0x00000000 : 0 [1]
> E {PPU[0x100000e] Thread (ksF3) [0x01c75ae0]} '_sys_lwcond_queue_wait' failed with 0x00000000 : 0 [1]
> E {PPU[0x100001c] Thread (9ZWAM) [0x00bf0df8]} 'sys_timer_usleep' failed with 0x00000000 : 0 [1]
> E {PPU[0x100001f] Thread (fmBKi) [0x01c75ae0]} '_sys_lwcond_queue_wait' failed with 0x00000000 : 0 [1]
> E {PPU[0x1000005] Thread (kFeqP) [0x01c75ae0]} '_sys_lwcond_queue_wait' failed with 0x00000000 : 0 [1]
> E {PPU[0x100001d] Thread (vyENO) [0x01c75ae0]} '_sys_lwcond_queue_wait' failed with 0x00000000 : 0 [1]
> E {PPU[0x1000026] Thread (n3FKY) [0x01c75ae0]} '_sys_lwcond_queue_wait' failed with 0x00000000 : 0 [1]
> E {PPU[0x1000027] Thread (n3FKY) [0x01c75ae0]} '_sys_lwcond_queue_wait' failed with 0x00000000 : 0 [1]
> E {PPU[0x100002b] Thread (OEyq) [0x01c75ae0]} '_sys_lwcond_queue_wait' failed with 0x00000000 : 0 [1]
> E {PPU[0x1000024] Thread (vyENO) [0x01c75ae0]} '_sys_lwcond_queue_wait' failed with 0x00000000 : 0 [1]
> E {PPU[0x100000b] Thread (ksF3) [0x01c75ae0]} '_sys_lwcond_queue_wait' failed with 0x00000000 : 0 [1]
> E {PPU[0x1000021] Thread (MEfYS) [0x008cfd14]} 'sys_event_queue_receive' failed with 0x00000000 : 0 [1]
> E {PPU[0x100000c] Thread (ksF3) [0x01c75ae0]} '_sys_lwcond_queue_wait' failed with 0x00000000 : 0 [1]
> E {PPU[0x1000025] Thread (n3FKY) [0x01c75ae0]} '_sys_lwcond_queue_wait' failed with 0x00000000 : 0 [1]
> E {PPU[0x100001b] Thread (lgFF) [0x00c20e08]} 'sys_event_queue_receive' failed with 0x00000000 : 0 [1]
> E {PPU[0x1000022] Thread (9qstY) [0x009002a8]} 'sys_timer_usleep' failed with 0x00000000 : 0 [1]
> E {PPU[0x1000023] Thread (ZYWAP) [0x01c75ae0]} '_sys_lwcond_queue_wait' failed with 0x00000000 : 0 [1]
> E {PPU[0x100000c] Thread (ksF3)} Stat: 'sys_fs_stat' failed with 0x80010006 : CELL_ENOENT, “/dev_hdd1/cache/BCES00569/game249.db-journal” [x308]
> E {PPU[0x100002d] Thread (AEIVZ) [0x01c75ae0]} '_sys_lwcond_queue_wait' failed with 0x00000000 : 0 [1]
> E {PPU[0x1000039] Thread (ZYWr6) [0x01c75ae0]} '_sys_lwcond_queue_wait' failed with 0x00000000 : 0 [1]
> E {PPU[0x100003a] Thread (Z1kIS) [0x01c75ae0]} '_sys_lwcond_queue_wait' failed with 0x00000000 : 0 [1]
> E {PPU[0x1000038] Thread (PDI) [0x01c75ae0]} '_sys_lwcond_queue_wait' failed with 0x00000000 : 0 [1]
> E {PPU[0x1000031] Thread (ZWAP) [0x00bf0df8]} 'sys_timer_usleep' failed with 0x00000000 : 0 [1]
> E {PPU[0x100002c] Thread (CYYqg) [0x01c75ae0]} '_sys_lwcond_queue_wait' failed with 0x00000000 : 0 [1]
> E {PPU[0x1000016] Thread (sgx-spurs-printf-handler) [0x009001b0]} 'sys_event_queue_receive' failed with 0x00000000 : 0 [1]
> E {PPU[0x100003b] Thread (Z11K6) [0x01c75ae0]} '_sys_lwcond_queue_wait' failed with 0x00000000 : 0 [1]
> E {PPU[0x1000014] Thread (sgx-spurs-SpursHdlr1) [0x01d0b604]} 'sys_event_queue_receive' failed with 0x00000000 : 0 [1]
> E {PPU[0x1000010] Thread (ksF3) [0x01c75ae0]} '_sys_lwcond_queue_wait' failed with 0x00000000 : 0 [1]
> E {PPU[0x100000f] Thread (ksF3) [0x01c75ae0]} '_sys_lwcond_queue_wait' failed with 0x00000000 : 0 [1]
> E {PPU[0x1000010] Thread (ksF3)} Stat: 'sys_fs_stat' failed with 0x80010006 : CELL_ENOENT, “/dev_hdd0/game/BCES00569/USRDIR/PDIPFS/9/SV/K7” [x4]
> E {PPU[0x1000010] Thread (ksF3)} Stat: 'sys_fs_stat' failed with 0x80010006 : CELL_ENOENT, “/dev_hdd0/game/BCES00569/USRDIR/PDIPFS/9/45/92” [x4]
> ```

That is the exact print I am seeing in the Log, hopefully there is a work around or a fix.

**Comment by Resident007** [comment] 2019-10-15 07:18
Recently someone said that this issue might be caused by desynchronization of emulator, when it’s actually dead, but RSX doesn’t know about it and is still trying to run. Correct me if I’m wrong.

**Comment by HHCHunter** [comment] 2019-10-15 13:17
Someone able to test PR #6772
https://github.com/RPCS3/rpcs3/pull/6772

**Comment by elad335** [comment] 2019-10-15 13:27
I don't think it is related.

**Comment by Attelee** [comment] 2019-10-16 09:34
I have same problem. See this video https://www.youtube.com/watch?v=4wXJZV73qOE ,i try these settings,but not helped. Only different,is the TSX option. This guy have Intel CPU, you and me 
/ Ryzen 2600 3.9Ghz / have Ryzen cpu. So i think this problem only Ryzen specific!!!!
 Only way for working this game,and not freezing,is install latest Vulkan sdk here https://vulkan.lunarg.com/sdk/home ,and in the Debug Option ,select the Debug Output. 
Not freezing when loading the map ,and compilling shaders,but very very slow the game 8-10 FPS.

**Comment by EATYOURVITAMIN5** [comment] 2019-10-16 10:28
> I have same problem. See this video https://www.youtube.com/watch?v=4wXJZV73qOE ,i try these settings,but not helped. Only different,is the TSX option. This guy have Intel CPU, you and me
> / Ryzen 2600 3.9Ghz / have Ryzen cpu. So i think this problem only Ryzen specific!!!!
> Only way for working this game,and not freezing,is install latest Vulkan sdk here https://vulkan.lunarg.com/sdk/home ,and in the Debug Option ,select the Debug Output.
> Not freezing when loading the map ,and compilling shaders,but very very slow the game 8-10 FPS.

I really appreciate your advice. I will try out the updated Vulkan SDK. I was also starting to suspect it may be only on Ryzen setups.

**Comment by Attelee** [comment] 2019-10-16 11:13
Update your Game BCUS98114 (02.17 version),and try these settings.

*CPU*
PPU Decoder : LLVM
SPU Decoder: LLVM
Firmware Settings: Load Liblv2.sprx only
Preferred SPU Threads: Auto
SPU Block Size: Safe
TSX Instructions: Not supported
SPU Cache: Enabled

*GPU*
Anistropic Filter: Automatic
Framelimit: 60
Anti-Aliasing: Disabled
Default Resolution: 1280X720
Resolution Scale: 300% (3840X2160)
Resolution Scale Threshold: 16X16
Multithreaded RSX: True

*Audio*
Downmix to Stereo : True
Enable Buffering: False (100ms)
Enable Time Stretching: False (75%)

*Advanced*
Vblank Frequency: 60 Hz

*Debug Menu*
To enable debug menu, go to RPCS3 Folder, GUIconfigs, open CurrentSettings, change *showDebugTab* to true

Debug output : True
Use GPU Texture Scaling : True

**Comment by EATYOURVITAMIN5** [comment] 2019-10-16 11:36
All settings matched and still same result.

**Comment by Wizzy2018** [comment] 2019-10-16 12:36
It's Ryzen probably i have the same issue

**Comment by Resident007** [comment] 2019-10-16 20:04
This issue is definitely not Ryzen-only. I am getting the same result with i7-3770

**Comment by HHCHunter** [comment] 2019-10-20 12:43
Update:

#8820 - De-synchronized pretty much straight away
#8790 - De-synchronize's after a bit say 5 minutes.
#8725
This version is MUCH, MUCH more stable however isn't as stable as it used to be prior, after a solid 30 minutes of gameplay, de-synchronization finally happens. 
	Noteably, this happened when I had a smoke effect on screen and looked back which must have rendered quite a lot of cars.

I could continue tracking down to the PR which causes this, but it starts to become less and less prevalent with each PR I go back.

**Comment by EATYOURVITAMIN5** [comment] 2019-10-20 13:53
@HHCHunter will do

**Comment by Wizzy2018** [comment] 2019-10-20 14:05
I start testing

**Comment by EATYOURVITAMIN5** [comment] 2019-10-20 15:40
Latest build 

> v0.0.7-8948 Alpha [2019-10-20]

Same issue

**Comment by MidnightLocke** [comment] 2019-10-21 07:23
I'm getting the same desync issue as well. I don't even have a Ryzen CPU. 8950HK Here. Running the latest build 8959. It happens for me in a matter of 5 minutes or less

**Comment by SKYMEE1** [comment] 2019-10-21 16:42
I got the same issue and 2 month ago I opend this exact problem too. I don't know if it is related to the issue because it's very specific. People with newer Processors don't have this issue and everybody with older cpus ( or ryzen cpus ) have this issue. My question now is why did I never saw somebody with a cpu that not support tsx, running this game fine .All intel cpus that support tsx can play this game just fine. ( That are my observations on that ). Tsx is like a memory manager ( Restricted Transactional Memory ) to not overcommplicate things. Just a little explanation there. I am into this but somebody who is can maybe figure a way out to fix this problem. Even somebody with a i7 of the 4. generation like a i7 4770k can install a microcode that's before august 2014 and see if this freezing still happen. Maybe, just maybe this the fix. I cannot install a microcode before august 2014 because my cpu came out at the exact date and there is no microcode from before....

**Comment by spyropt** [comment] 2019-10-21 16:47
> I got the same issue and 2 month ago I opend this exact problem too. I don't know if it is related to the issue because it's very specific. People with newer Processors don't have this issue and everybody with older cpus ( or ryzen cpus ) have this issue. My question now is why did I never saw somebody with a cpu that not support tsx, running this game fine .All intel cpus that support tsx can play this game just fine. ( That's my observation on that ). Tsx is like a memory manager ( Restricted Transactional Memory ) to not overcommplicate things. Just a little explanation there. I am not into this but somebody who is can maybe figure a way out to fix this problem. Even somebody with a i7 of the 4. generation like a i7 4770k can install a microcode that's before august 2014 and see if this freezing still happen. Maybe, just maybe this the fix. I cannot install a microcode before august 2014 because my cpu came out at the exact date and there is no microcode from before....

I think it's only working on the tsx path 
I have a ryzen 3600, i7 3770 and a xeon x5675 and all have the same problem  970 gtx/760gtx/950 gtx

**Comment by SKYMEE1** [comment] 2019-10-21 16:50
@spyropt This would proof my thoughts.

**Comment by ijoshvirk** [comment] 2019-10-21 17:02
@SKYMEE1 I mentioned it not working on my coffee lake. I do not have an option to turn on or turn off TSX as it is not supported by my CPU.

**Comment by SKYMEE1** [comment] 2019-10-21 17:07
@ijoshvirk Ok that's intresting. So it's not bound to the generation but more to the prozessor it self.

**Comment by MidnightLocke** [comment] 2019-10-21 17:11
@spyropt Actually I have an intel processor supporting TSX as well, mine being fairly new and i'm still getting this issue no matter the build. Now tested on latest and 8725 (Considering it was stated to be most stable above). This is with TSX enabled of course. That might not be the issue, i'm unsure. i9 8750 isn't old at all.

**Comment by SKYMEE1** [comment] 2019-10-21 17:15
> @spyropt Actually I have an intel processor supporting TSX as well, mine being fairly new and i'm still getting this issue no matter the build. Now tested on latest and 8725 (Considering it was stated to be most stable above). This is with TSX enabled of course. That might not be the issue, i'm unsure. i9 8750 isn't old at all.

I am so confused. I could be the problem but also not? Is the i9 8750 a mobile processor it's maybe another thing to consider?

**Comment by ijoshvirk** [comment] 2019-10-21 17:20
When the error happens for me (Unsure about OP) I usually get 'CELL_ENOENT' in the log as well, unsure if it has any relevance or if it is just my side.

**Comment by SKYMEE1** [comment] 2019-10-21 17:35
@ijoshvirk I got in a race and the game froze but in my log is nothing like that.

This is the end of my log when it's freeing:

·! 0:07:03.503414 {SPU[0x2000002] Thread (PDICellSpursKernel2) [0x0ad30]} SPU: Stats: Block Weight: 1501109895 (Retreats: 296);
·! 0:07:03.503693 {PPU[0x1000024] Thread (gFKsE)} Thread time: 38.906250s (132.214075Gc); Faults: 6804 [rsx:6796, spu:0];
·! 0:07:03.503693 {SPU[0x2000002] Thread (PDICellSpursKernel2)} Thread time: 26.312500s (98.741355Gc); Faults: 5289 [rsx:5249, spu:0];
·! 0:07:03.503770 {Timer Thread} Thread time: 0.000000s (0.358180Gc); Faults: 0 [rsx:0, spu:0];
·! 0:07:03.503794 {Camera Thread} Thread time: 0.000000s (1.116356Gc); Faults: 0 [rsx:0, spu:0];
·! 0:07:03.503824 {SPU[0x2000003] Thread (PDICellSpursKernel3) [0x07108]} SPU: Stats: Block Weight: 1516436218 (Retreats: 160);
·! 0:07:03.503830 {SPU[0x2000003] Thread (PDICellSpursKernel3)} Thread time: 25.859375s (98.435154Gc); Faults: 5477 [rsx:5434, spu:0];
·! 0:07:03.503863 {SPU[0x2000000] Thread (PDICellSpursKernel0) [0x0b240]} SPU: Stats: Block Weight: 1516045178 (Retreats: 247);
·! 0:07:03.503872 {SPU[0x2000000] Thread (PDICellSpursKernel0)} Thread time: 26.421875s (101.044896Gc); Faults: 5947 [rsx:5903, spu:0];
·E 0:07:03.503895 {PPU[0x1000026] Thread (9qstY) [0x0088ba44]} 'sys_timer_usleep' failed with 0x00000000 : 0 [1]
·! 0:07:03.503905 {PPU[0x1000026] Thread (9qstY)} Thread time: 24.875000s (85.882882Gc); Faults: 2924 [rsx:2920, spu:0];
·! 0:07:03.504751 {VBlank Thread} Thread time: 0.000000s (0.305929Gc); Faults: 0 [rsx:0, spu:0];
·! 0:07:03.504792 {RSX Decompiler Thread} Thread time: 4.031250s (15.371367Gc); Faults: 0 [rsx:0, spu:0];
·! 0:07:03.511739 {Timer Thread} Thread time: 0.000000s (0.168032Gc); Faults: 0 [rsx:0, spu:0];
·! 0:07:03.511739 {Timer Thread} Thread time: 0.000000s (0.160437Gc); Faults: 0 [rsx:0, spu:0];
·! 0:07:03.513735 {rsx::thread} Thread time: 75.296875s (263.406122Gc); Faults: 160 [rsx:160, spu:0];
·! 0:07:03.513735 {RSX offloader} Thread time: 88.421875s (303.428748Gc); Faults: 0 [rsx:0, spu:0];
·! 0:07:04.814145 All CPU threads have been stopped.
·! 0:07:05.020102 {cellAudio Thread} Thread time: 0.000000s (1.703338Gc); Faults: 0 [rsx:0, spu:0];
·! 0:07:05.056762 {Usb Manager Thread} Thread time: 0.000000s (0.012662Gc); Faults: 0 [rsx:0, spu:0];
·! 0:07:05.058270 {Network Thread} Thread time: 0.015625s (2.841989Gc); Faults: 0 [rsx:0, spu:0];
·! 0:07:05.087978 {Microphone Thread} Thread time: 0.000000s (1.187434Gc); Faults: 0 [rsx:0, spu:0];
·! 0:07:05.088016 {CPU Profiler} Thread time: 0.000000s (0.000295Gc); Faults: 0 [rsx:0, spu:0];
·! 0:07:05.088824 {GDB Server} Thread time: 0.000000s (1.027386Gc); Faults: 0 [rsx:0, spu:0];
·! 0:07:05.278566 Objects cleared...


The emulator just like quits.

**Comment by MidnightLocke** [comment] 2019-10-21 17:58
@SKYMEE1 It is a mobile processor.

**Comment by SKYMEE1** [comment] 2019-10-21 18:04
> @SKYMEE1 It is a mobile processor.

Ok maybe this also makes a diffrence. But we all have to wait that a dev will look into this..

**Comment by AniLeo** [comment] 2019-10-22 16:02
Closing as a duplicate of #6427, please discuss a single issue on a single ticket

**Closed by AniLeo** 2019-10-22 16:02 UTC
