### ISSUE TITLE
Add RTC for demos that stop working after a certain timestamp

### ISSUE THREAD

**Issue by ProtoFgt** [RPCS3/rpcs3#4481] opened 2018-04-23 07:05 UTC
hcorion asked that I open this ticket otherwise he'd forget.

Some titles (mainly demos) have an issue where a time past a certain timestamp will render them non-functional (example off hand would be Sonic Generations 20 day demo). Allowing an RTC variable of sorts, preferably set to 01/01/2000 would be ideal in circumventing this issue.

**Comment by JMC47** [comment] 2018-04-23 07:12
Maybe it could be implemented like Dolphin where by default it uses the PC's clock, but if you enable RTC override then you can set your own time/date.  During emulation, it could increment as per normal, so you could simulate something like the demo ending as you're playing it!

**Comment by CookiePLMonster** [comment] 2019-09-01 08:51
I tried to look into this, but looks like Sonic Generations Demo actually **does** run even after expiration? It's possible that the lock was not done from the game but from PS3 OS.

**Comment by CookiePLMonster** [comment] 2020-01-19 22:44
Note to self or anyone who wishes to look into this in the future: Sonic Generations Demo **is** time locked but boots fine in RPCS3 because `sceNpDrmGetTimelimit` is stubbed or unimplemented.

**Comment by bevanweiss** [comment] 2020-09-04 09:16
Is this still a desirable feature?
It sounds like most demos have been resolved with the sceNpDrmGetTimeLimit change.

The way I was thinking to implement this was:
A per-game game time, determined as an offset from current OS time.
The offset would be calculated when adjusting the current game-time in the configuration dialog (potentially per-game).
There would also be a button to reset this offset to 0 (i.e. game time = current OS time).

**Comment by NicknineTheEagle** [comment] 2020-09-04 12:07
> 
> 
> Is this still a desirable feature?
> It sounds like most demos have been resolved with the sceNpDrmGetTimeLimit change.
> 
> The way I was thinking to implement this was:
> A per-game game time, determined as an offset from current OS time.
> The offset would be calculated when adjusting the current game-time in the configuration dialog (potentially per-game).
> There would also be a button to reset this offset to 0 (i.e. game time = current OS time).

Most games indeed use sceNpDrmGetTimeLimit but there are some games that just call sys_time_get_current_time like Need for Speed™ The Run Demo [NPEB90355].

**Comment by bevanweiss** [comment] 2020-09-05 07:01
@NicknineTheEagle @ProtoFgt @JMC47 
Any chance you'd be interested in testing a PR for me?
https://github.com/RPCS3/rpcs3/pull/8837

**Comment by bevanweiss** [comment] 2020-09-23 22:15
The PR for this got merged today, so it should be in the current release.
There's still a bit of roughness around the edges of the implementation (just related to handling the offset from wall clock adjustment in the settings dialog), but it should work fine for 99% of use cases (you only get minute resolution on setting the clock currently).

**Comment by NicknineTheEagle** [comment] 2020-12-03 17:16
@bevanweiss The implementation in https://github.com/RPCS3/rpcs3/pull/8837 is flawed, since time is stored as an offset, it keeps shifting forward which poses a problem for time-limited demos as you have to keep re-setting the time back to play.

**Comment by Megamouse** [comment] 2021-06-10 17:41
I'll close this since the basic functionality is implemented and having a minor convenience in a workaround such as this one doesn't warant a redesign that might lead to regressions in other games.

**Closed by Megamouse** 2021-06-10 17:41 UTC
Labels: Firmware: HLE, GUI
