### ISSUE TITLE
Regression - 1942: Joint Strike[NPUB30024] - run game when MISSION START get error "Verification failed (e=0x57)"

### ISSUE THREAD

**Issue by kokutoukiritsugu** [RPCS3/rpcs3#3598] opened 2017-10-14 13:57 UTC
OS - Windows 10 Pro x64 1703
CPU - i7 6700k@4.5
GPU - gtx 1070
Vulkan and OpenGL ,whatever ppu/spu 1 or 3

load game , continue press X ,when "MISSION START" text disappears, will get error.

build:
no error
https://ci.appveyor.com/project/rpcs3/rpcs3/build/0.0.3-6396/artifacts

1942: Joint Strike - run game when MISSION START get error "Verification failed (e=0x57)"
https://ci.appveyor.com/project/rpcs3/rpcs3/build/0.0.3-6402/artifacts

error:
F {rsx::thread} class std::runtime_error thrown: Verification failed (e=0x57): 
(in file C:\rpcs3\Utilities\VirtualMemory.cpp:83)

**Comment by kd-11** [comment] 2017-10-15 10:18
Post your log so we can see the configuration. I cannot reproduce this issue on latest master.

**Comment by kokutoukiritsugu** [comment] 2017-10-15 10:36
[RPCS3.log.gz](https://github.com/RPCS3/rpcs3/files/1385355/RPCS3.log.gz)

**Comment by weitingchua** [comment] 2017-10-18 17:58
This error is also happening for Super Puzzle Fighter II Turbo HD Remix (NPUB30017).

6396 works but not 6402.

Log:
[NPUB30017.txt](https://github.com/RPCS3/rpcs3/files/1395738/NPUB30017.txt)

**Comment by ebidon** [comment] 2017-10-18 18:04
This regression also happens for Super Puzzle Fighter II Turbo (NPUB30017)

Works with build 6396 but breaks in 6402.

Log:
[NPUB30017.txt](https://github.com/RPCS3/rpcs3/files/1395757/NPUB30017.txt)

**Comment by kd-11** [comment] 2017-10-24 09:04
Fixed by https://github.com/RPCS3/rpcs3/pull/3638

**Closed** 2017-10-25 09:37 UTC
