### ISSUE TITLE
RPCS3 Crashes when loading cached shaders without native interface

### ISSUE THREAD

**Issue by miguel-nunes** [RPCS3/rpcs3#4609] opened 2018-05-18 20:45 UTC
This is a long lasting bug that I mentioned to @hcorion, he ask me to open an issue and I always forget.

How to test:
1. Let any game generate some cached shaders
2. Disable the native interface
3. Load the game again and the RPCS3 just crashes

This was reproduced in Linux and Windows. I tested on Linux, some guys at discord notice the same thing on windows.

I hope that opened issue will help fixes this long last bug on RPCS3!

**Comment by kd-11** [comment] 2018-05-18 20:57
I'm assuming you meant shaders and not textures

**Comment by miguel-nunes** [comment] 2018-05-18 21:17
Yeah @kd-11, shaders. Sorry by the mistake

**Comment by AniLeo** [comment] 2018-05-18 21:19
On Windows I'm assuming it crashes every time you try afterwards too? What if you change the emulator's executable name? On NVIDIA at least, that forces it to generate a new shader cache. 
I think there's some fuckery going on on the driver's cache, as that solves the issue for me generally.

**Comment by kd-11** [comment] 2018-05-20 19:47
I cannot reproduce this on linux. I tried both vulkan and ogl with a pretty large shaders cache and it boots fine. Hopefully not another issue that needs appimage fixes.

**Comment by kd-11** [comment] 2018-05-21 09:12
@greentop Thats unrelated and only happens on linux. The c runtime detects a heap corruption during malloc and aborts the process. Still not sure why/where the heap structure is getting trashed.

**Comment by Asinin3** [comment] 2018-05-22 14:37
Isn't this fixed with #4628 ?

**Comment by kd-11** [comment] 2018-07-14 13:18
This was fixed a while ago.

**Closed by kd-11** 2018-07-14 13:18 UTC
