### ISSUE TITLE
Kingdom hearts 1.5 remix BLES01897 Vulkan crash

### ISSUE THREAD

**Issue by JorgeRiveiro** [RPCS3/rpcs3#4074] opened 2018-01-17 18:38 UTC
Hi, I have a problem and when I start kingdom hearts 1.5 remix, the game starts well until the screen where I select the game I want to play, after selecting the kingdom hearts final mix I get the following error:

 F {rsx :: thread} class std :: runtime_error thrown: Assertion Failed! Vulkan API call failed with unrecoverable error: Device lost (Driver crashed with unspecified error or stopped responding and recovered) (VK_ERROR_DEVICE_LOST)
(in file c: \ projects \ rpcs3 \ rpcs3 \ emu \ rsx \ vk \ VKHelpers.h: 1133)

I have an i7 6700, a gtx 970 and 16gb of ram ddr4.

Could someone help me with this?

**Comment by Illynir** [comment] 2018-01-17 21:11
OpenGL with GPU texture scaling or use Vulkan without.

**Comment by scribam** [comment] 2018-04-25 20:09
@JorgeRiveiro Is it still an issue?

**Comment by Illynir** [comment] 2018-04-25 20:28
No, you can close. :)

**Comment by Illynir** [comment] 2018-04-25 20:29
Yes. Not really a problem, just don't use GPU Texture scaling with Vulkan on this game.

**Comment by AniLeo** [comment] 2018-07-06 18:07
Closing as GPU Texture Scaling is no longer a default option, and it's not supposed to be used on every game since it doesn't work well with some - this is one of them.

If you're able to reproduce without GPU Texture Scaling on master provide a proper report and issue will be reopened.

**Closed by AniLeo** 2018-07-06 18:07 UTC
