### ISSUE TITLE
Madden 08 Blus30037 Missing field textures

### ISSUE THREAD

**Issue by bluedragon2k9** [RPCS3/rpcs3#14698] opened 2023-10-02 18:02 UTC
### Quick summary

Field is completely black when using Vulkan OpenGL the field is solid brown. 

### Details

When using Vulkan the field is completely black no field textures load. Everything else looks good. When switching to OpenGL the field is a solid mud brown color. Once again everything else is fine.

### Attach a log file

[RPCS3.log.gz](https://github.com/RPCS3/rpcs3/files/12785179/RPCS3.log.gz)

### Attach capture files for visual issues

![vulkan](https://github.com/RPCS3/rpcs3/assets/146439561/4007e54d-8d3a-4cab-b524-7366787fd9f4)

### System configuration

Processor	AMD Ryzen 7 5800X 8-Core Processor                4.20 GHz
Installed RAM	16.0 GB
rtx 2080 super
System type	64-bit operating system, x64-based processor

**Comment by AniLeo** [comment] 2023-10-02 18:47
Duplicate of #9133

**Closed by AniLeo** 2023-10-02 18:47 UTC
