### ISSUE TITLE
Persona 5- Exaggerated "Heat Wave" Effect 

### ISSUE THREAD

**Issue by ApexAqua** [RPCS3/rpcs3#6993] opened 2019-11-15 07:42 UTC
It started happening past a certain point in the game (before 3rd palace) and this effect is greatly exaggerated during a "Heat Wave" day but is still present any other normal day with a lesser effect. This heat wave effect is present on console, but is not near this extremity. Currently using RPCS3 Build -v0.0.7-8925. Have also tried build v0.0.7-8619. Tried using LLVM or ASMJIT and Vulkan/OpenGL and the issue still persists. I have tried pretty much every setting in the emu to no avail. Is this effect at this extremity considered normal?  Any input or fixes would be greatly appreciated, thank you. 

RPCS3 Screenshots
![image](https://user-images.githubusercontent.com/57788068/68925202-c228a880-073f-11ea-8269-a20064e20ca0.png)

![image](https://user-images.githubusercontent.com/57788068/68925242-d7053c00-073f-11ea-96af-fa4bfe39777d.png)

Specs 
-i7-9750H
-RTX 2060
-16gb RAM

**Comment by kd-11** [comment] 2019-11-19 20:39
Well, here's where it gets complicated. You'd have to get footage of what its supposed to look like on PS3 and compare with rpcs3 without any patches/mods/enhancements enabled.

**Comment by Asinin3** [comment] 2019-11-19 21:05
Well did you check if its still broken at 100% res scaling? If it's just caused by res scaling then im not so sure it will be looked into

**Comment by ApexAqua** [comment] 2019-11-20 07:53
This persists regardless of patches, mods and enhancements. It is also present on default resolution and strict rendering.  This effect is part of the game itself, but I'm almost positive it is a bit overdone on the emu. Issue #4086 has a similar issue with the distortion effect in the game, however I can't say whether or not it is relevant. https://github.com/RPCS3/rpcs3/issues/4086 

This video is for the PS4 version but obtaining a clip for specific days and events in the game on my console is not feasible at the moment. 
https://www.youtube.com/watch?v=3eskqVoHouk

Clips of Build v0.0.7-9080 at default settings and resolution except Vulkan. The compression from converting clips to GIF and upload limitations is making this a pain to showcase. 

https://giphy.com/gifs/PmLlhMOLms6neoRq2t/fullscreen
https://giphy.com/gifs/llDRpDvY0u4ynKUvWu/fullscreen

**Comment by dio-gh** [comment] 2020-05-21 20:40
Could you retest? Might have changed with a recent PR.

**Comment by Megamouse** [comment] 2021-03-06 22:44
Needs update from other sources

**Comment by Megamouse** [comment] 2021-07-27 21:50
is this still an issue?

**Comment by Asinin3** [comment] 2021-09-15 13:31
No update from OP. Closing.

**Closed by Asinin3** 2021-09-15 13:31 UTC
Labels: Need Information
