### ISSUE TITLE
Freezing When I Re-Enter the Pod in Little Big Planet 2.

### ISSUE THREAD

**Issue by RyleeTime** [RPCS3/rpcs3#11643] opened 2022-03-10 23:53 UTC
I've been having HUGE craving to go back and play Little Big Planet 2 again all these years later, and I've managed to get it to run extremely well on my PC! There is one issue, however, with the came crashing when I re-enter the pod, whether it be from beating a level or returning mid-level. I've been troubleshooting this to the best of my abilities, but I've gotten to a place now where there doesn't seem to be much documentation on this issue. So I'll leave everything I have on me in hopes this helps.

When it freezes, it does it on the same frame every time, here's an example with two different costumes to highlight this:
![image](https://user-images.githubusercontent.com/63830828/157772752-5692faf3-d517-460e-8f39-06f677dab79e.png)
![image](https://user-images.githubusercontent.com/63830828/157773021-a7cbab58-25b9-47ed-bcae-341dbc4b25a5.png)

I've tried changing between Vulkan/OpenGL renderers, and SPU/PPU Decoding modes with varying changes to performance, but they all replicate the same issue. I've turned on and off each setting in the GPU/CPU settings one by one, once again with varying changes to performance, but still replicating the same issue. 

Via trial and error, and a little bit of help from the community, I was able to get the game to run very well very consistently with seemingly the best settings, but this issue seems to be deeper than something I can fix through the settings. 

I have my log open, it gives me this message every time it freezes
(I will just screenshot as much as the log as I can)
![image](https://user-images.githubusercontent.com/63830828/157774109-78ed6be8-4fb9-4c7f-b222-b9e793cae3c2.png)

The application freezes along with the game, giving me this error after a few seconds:
![image](https://user-images.githubusercontent.com/63830828/157774227-3df09791-54c8-40ce-8fbc-0335fc9e18f1.png)

Here's the log file if anyone is interested into diving into it:
[log.zip](https://github.com/RPCS3/rpcs3/files/8227851/log.zip)

And my specs:

CPU: Intel(R) Core(TM) i7-9700K CPU @ 3.60GHz (8 CPUs), ~3.6GHz
Memory: 16GB RAM
GPU: NVIDIA GeForce RTX 2080 SUPER

**Comment by nitroos-ai** [comment] 2022-03-11 04:35
Try enabling WCB and CPU blit for that specific part of the game.

**Comment by Megamouse** [comment] 2022-03-11 07:11
Issue reports with patches applied are invalid. Please test without patches. otherwise this issue will be closed.

**Comment by kd-11** [comment] 2022-03-11 07:45
Caused by https://github.com/RPCS3/rpcs3/issues/9133
Enable "Write depth buffer" in the advanced tab to fix it.

**Comment by RyleeTime** [comment] 2022-03-11 12:38
> Issue reports with patches applied are invalid. Please test without patches. otherwise this issue will be closed.

I forgot to mention that I have tested it with and without the patch with no change to the issue.

**Comment by RyleeTime** [comment] 2022-03-11 12:38
> Caused by #9133 Enable "Write depth buffer" in the advanced tab to fix it.

Thanks for the help, but this didn't solve the issue.

**Comment by JimScript** [comment] 2022-03-11 22:51
This might be a stretch, but have you tried disabling logs? LBP2 and LBP3 have major performance drawbacks when enabled, it could also break something.

**Comment by RyleeTime** [comment] 2022-03-11 22:54
I have! It improves performance drastically, but the problem still occurs, unfortunately.

**Comment by RyleeTime** [comment] 2022-03-11 22:59
> 

So sorry, I completely overlooked this! I have both of these options on already, but is there a way for me to make them turn on only when this happens?

**Comment by RyleeTime** [comment] 2022-03-11 22:59
> This might be a stretch, but have you tried disabling logs? LBP2 and LBP3 have major performance drawbacks when enabled, it could also break something.

I have! It improves performance drastically, but the problem still occurs, unfortunately.

**Comment by JimScript** [comment] 2022-03-11 23:09
Well I did say it was a stretch. Anyway, I've had trouble with this issue too, or at least something similar.
"F {RSX [0x00931dc]} SIG: Thread terminated due to fatal error: Verification failed
(in file D:\a\1\s\rpcs3\Emu\RSX\VK\VKRenderTargets.h:81[:10], in function as_rtt)"
I get this when I return to my pod after a level, but only if I have force cpu blit emulation and write color buffers enabled. It clears up when I turn them off, but your problem might be different.

**Comment by RyleeTime** [comment] 2022-03-12 02:09
> Well I did say it was a stretch. Anyway, I've had trouble with this issue too, or at least something similar. "F {RSX [0x00931dc]} SIG: Thread terminated due to fatal error: Verification failed (in file D:\a\1\s\rpcs3\Emu\RSX\VK\VKRenderTargets.h:81[:10], in function as_rtt)" I get this when I return to my pod after a level, but only if I have force cpu blit emulation and write color buffers enabled. It clears up when I turn them off, but your problem might be different.

OH You're right, disabling both of those fixed it for me!

**Comment by JimScript** [comment] 2022-03-12 03:31
Glad I could help, I don't disable MLAA anyways because for some reason fog lights are connected to it and disappear when turned off.

**Comment by kd-11** [comment] 2022-03-13 14:56
Is it a problem if both 'write color buffers' and 'write depth buffer' are enabled together with CPU blit? If it happens in that scenario it should remain open. If it doesn't I can close this. The response given earlier had no logs so I have no idea what configuration was being used.

**Comment by RyleeTime** [comment] 2022-03-13 15:35
> 



> Is it a problem if both 'write color buffers' and 'write depth buffer' are enabled together with CPU blit? If it happens in that scenario it should remain open. If it doesn't I can close this. The response given earlier had no logs so I have no idea what configuration was being used.

Yes. The problem was only there if all three of those were on, I think. I still had Write Depth Buffers enabled on its own without Write Color Buffers and CPU Blit and it works fine, but when I turn those both on, the problem is there again.

**Comment by JimScript** [comment] 2022-03-13 20:17
I've had it happen consistently with only write color buffer and cpu blit on without write depth buffer. Tried WDB+WCB and WDB+cpu blit, but only WCB+cpu blit matters in crashing the emulator.

**Comment by kd-11** [comment] 2022-03-13 20:32
Ok, I think the significance of my question gets lost in translation a bit.
There is a known problem where we lose track of surfaces and the crash happens. The cause is that we separated WCB and WDB which should be one option and will be made into one option in the future. As long as enabling both WCB and WDB at the same time fixes the crashing, then we already know why it happens and we know how to fix it. In that case, we can close the ticket, and wait for the options merge to take place.
However, if it still crashes despite both WCB and WDB being enabled at the same time (CPU blit doesn't matter, whichever method makes it crash is fine) then there are far more serious issues going on that need long-term investigation. From the emulator's caching logic, the crash is possible if one of WCB/WDB is enabled without the other one matching the same state, but it should be impossible to lose track of surface contents while the pages are locked from modification which is what WCB/WDB do behind the scenes.

**Comment by RyleeTime** [comment] 2022-03-13 20:44
> Ok, I think the significance of my question gets lost in translation a bit. There is a known problem where we lose track of surfaces and the crash happens. The cause is that we separated WCB and WDB which should be one option and will be made into one option in the future. As long as enabling both WCB and WDB at the same time fixes the crashing, then we already know why it happens and we know how to fix it. In that case, we can close the ticket, and wait for the options merge to take place. However, if it still crashes despite both WCB and WDB being enabled at the same time (CPU blit doesn't matter, whichever method makes it crash is fine) then there are far more serious issues going on that need long-term investigation. From the emulator's caching logic, the crash is possible if one of WCB/WDB is enabled without the other one matching the same state, but it should be impossible to lose track of surface contents while the pages are locked from modification which is what WCB/WDB do behind the scenes.

Oh ok, so you're planning on merging WCB and WDB, yeah? Those two together specifically don't cause the crash, however, if I enable CPU blit, it crashes again, but only if WCB is enabled. WDB seems to make no difference either way.

**Comment by JimScript** [comment] 2022-03-13 20:48
Yeah, I just realized that having a mismatched configuration might invalidate things a bit after I posted, but like @RyleeTime said if all WCB+cpu blit is on, there is a crash. From a user standpoint, WDB doesn't change anything.

**Comment by kd-11** [comment] 2022-03-13 21:21
Ok, so something is horribly wrong behind the scenes then. I'll have to circle back to this later.

**Closed** 2022-03-28 16:55 UTC
Labels: Bug, RSX
