### ISSUE TITLE
Persona 4 Arena Ultimax [BLUS31469]: Freeze after the intro video in every build after 0.0.5-6664

### ISSUE THREAD

**Issue by acceleration3** [RPCS3/rpcs3#4730] opened 2018-06-09 19:02 UTC
The game appears to freeze after the intro video when using SPU ASMJIT Recompiler in versions after 0.0.5-6664 albeit it still has a chance of happening in previous builds, altough much less frequently. The issue can be fixed by switching to Interpreter (fast) at the cost of lower performance and sound cutting off randomly.

Specs:
i5-6500, RX 480, 8GB RAM, Win 10

Settings used in 0.0.5-6664:
![settings](https://user-images.githubusercontent.com/13179090/41195025-a3d52bce-6c1d-11e8-9e7e-3c468e6d3c4f.png)

0.0.5-6907 Log:
[RPCS3.log.gz](https://github.com/RPCS3/rpcs3/files/2087257/RPCS3.log.gz)

**Comment by Relsig** [comment] 2018-06-10 01:55
Duplicate of #4706

**Comment by AniLeo** [comment] 2018-06-10 14:41
Closing as duplicate of #4706

**Closed by AniLeo** 2018-06-10 14:41 UTC
Labels: Meta: Duplicate
