### ISSUE TITLE
Beyond Good & Evil HD - NPEB00435 - Crash at loading Hellys

### ISSUE THREAD

**Issue by sabatale** [RPCS3/rpcs3#10801] opened 2021-08-31 16:25 UTC
## Quick summary
Random crash during loading when leaving the city to go to Hellys. It happened twice during my walkthrough.

## Details

Leaving the city towards Hellys starts a loading screen. After a few seconds, the loading icon and stops, and rpcs3 crashes.

I need to check whether [this comment](https://github.com/RPCS3/rpcs3/issues/10623#issuecomment-889330663) fixes the issue.

#### 1. Please attach RPCS3's log.
[TTY.log](https://github.com/RPCS3/rpcs3/files/7085404/TTY.log)

#### 5. Please provide your system configuration:
* OS: Windows 10
* CPU: Intel i7
* GPU: RTX 3070
* Driver: Latest

**Comment by Megamouse** [comment] 2021-08-31 20:39
no log file present

**Comment by sabatale** [comment] 2021-08-31 23:47
See attachment.
[RPCS3 - Dump.zip](https://github.com/RPCS3/rpcs3/files/7087299/RPCS3.-.Dump.zip)

**Comment by AniLeo** [comment] 2021-09-23 19:54
as_rtt verification failed, duplicate of #10643

**Closed by AniLeo** 2021-09-23 19:54 UTC
Labels: Need Information
