### ISSUE TITLE
LittleBigPlanet 2 - Level not functioning correctly, impossible to complete

### ISSUE THREAD

**Issue by Pixel3000nerd** [RPCS3/rpcs3#15246] opened 2024-02-26 04:46 UTC
### Quick summary

In Story Mode, in the level called "Brainy Cakes" by Victoria Von Bathysphere, there's a section that is behaving differently on RPCS3 compared to on the native PS3, rendering the level impossible to complete.

### Details

In LittleBigPlanet 2, Story Mode, when trying to complete the level "Brainy Cakes" on the chapter with Victoria Von Bathysphere, reaching the section where you have to grab a cupcake and use it as support on a rotating wheel, in RPCS3 the deadly gas barrier that's supposed to disappear 1 second after it is spawned each interval, it does not disappear, whereas in native PS3 it does.

Here's footage showcasing how it acts on RPCS3 vs how it should with native PS3:
[RPCS3 Clip](https://youtu.be/qYeiHcWDOc8)
[Native PS3 - timestamped](https://www.youtube.com/watch?v=xElKaaoiwbY&t=2870s)

This was tested on 3 different versions/editions of the game, US region, same configuration and no game patches:
LittleBigPlanet™2 [BCUS98245]
LittleBigPlanet™2 Digital Version [NPUA80662]
LittleBigPlanet™2: Special Edition [BCUS98372]

All running version 1.33 of the game with all the needed update packages

### Attach a log file

[RPCS3.log](https://github.com/RPCS3/rpcs3/files/14399713/RPCS3.log)

**Comment by RipleyTom** [comment] 2024-02-26 10:38
Duplicate of https://github.com/RPCS3/rpcs3/issues/15178

**Closed by RipleyTom** 2024-02-26 10:38 UTC
