### ISSUE TITLE
[Bug] RPCS3 Doesn't Boot Correctly For Some Systems

### ISSUE THREAD

**Issue by Monsterman07** [RPCS3/rpcs3#16260] opened 2024-10-28 13:53 UTC
### Quick summary

RPCS3 no longer correctly boots always for some systems and leaves a ghost process in Task Manager.
The build with the bug: rpcs3-v0.0.33-17062-84217917

### Details

![Screenshot 2024-10-28 153053](https://github.com/user-attachments/assets/3db19525-8677-4ebf-b8ea-690761649388)

### Attach a log file

Can't make a log as it won't boot correctly in the first place

### System configuration

CPU: 7 5800X3D
GPU: RX 7900 GRE
RAM:  DDR4 32G

**Comment by FlexBy420** [comment] 2024-10-28 14:04
Do you by perhaps keep some of your games on NAS?

**Comment by Hasster1** [comment] 2024-10-28 14:30
Duplicate of https://github.com/RPCS3/rpcs3/issues/16258

**Comment by Hasster1** [comment] 2024-10-29 07:45
Since first issue got closed, because apparently it's somehow a 'windows defender bug', which is something that seems very farfetched for me, i might as well copy this message from there.
The emulator only generates RPCS3.buf before being stuck as an empty background process that only takes about 500kb of ram, which prevents rpcs3 from being run again, giving the 'RPCS3 is already running', unless you delete that RPCS3.buf or end the task.
The bug also possibly occurs when using shortcuts, though i can't get any consistent results.
Also admin rights don't always help with it, for me it might just randomly work again after a while.

**Comment by Hasster1** [comment] 2024-10-29 07:59
Also, disabling real-time protection + adding rpcs3 folder an an exclusion for the windows security does nothing to fix this, adding it just in case.

**Comment by alessiot89** [comment] 2024-10-29 12:37
Same issue:
Windows 10 22H2, Ryzen 3600X, 32GB RAM, RX 6700XT

Windows Event viewer reports errors like that:

```XML
[-](https://github.com/RPCS3/rpcs3/issues/16260#) <Event xmlns="http://schemas.microsoft.com/win/2004/08/events/event">
[-](https://github.com/RPCS3/rpcs3/issues/16260#) <System>
  <Provider Name="Application Error" /> 
  <EventID Qualifiers="0">1000</EventID> 
  <Version>0</Version> 
  <Level>2</Level> 
  <Task>100</Task> 
  <Opcode>0</Opcode> 
  <Keywords>0x80000000000000</Keywords> 
  <TimeCreated SystemTime="2024-10-29T11:31:01.5333144Z" /> 
  <EventRecordID>129402</EventRecordID> 
  <Correlation /> 
  <Execution ProcessID="0" ThreadID="0" /> 
  <Channel>Application</Channel> 
  <Computer>DESKTOP[-](https://github.com/RPCS3/rpcs3/issues/16260#)ALESSIO</Computer> 
  <Security /> 
  </System>
- <EventData>
  <Data>rpcs3.exe</Data> 
  <Data>0.0.0.0</Data> 
  <Data>67201d3c</Data> 
  <Data>rpcs3.exe</Data> 
  <Data>0.0.0.0</Data> 
  <Data>67201d3c</Data> 
  <Data>c0000005</Data> 
  <Data>0000000000e5f002</Data> 
  <Data>2e7c</Data> 
  <Data>01db29f60834b3c9</Data> 
  <Data>I:\_runtime\RPCS3\rpcs3.exe</Data> 
  <Data>I:\_runtime\RPCS3\rpcs3.exe</Data> 
  <Data>04d2fe9f-aac9-46fc-b857-703addf35740</Data> 
  <Data /> 
  <Data /> 
  </EventData>
  </Event>
```

**Comment by elad335** [comment] 2024-10-29 19:11
Retest on master

**Comment by yeahme49** [comment] 2024-10-29 19:36
> Retest on master

Working for me now on latest

**Closed** 2024-10-29 19:54 UTC
