### ISSUE TITLE
Heavenly Sword [BCUS98132] Crashes in Cutscene

### ISSUE THREAD

**Issue by Rpcs3tester** [RPCS3/rpcs3#4395] opened 2018-04-06 00:53 UTC
hello guys

i don't know if this the right place to share problems . 

however ,, 

i manged to proceed through this game to Roach BOSS < after first fight followed by cutscene it's freez randomly with this cutscene ( look to the picture attached )

one time i could pass this cutscene by mashing START button till it's end to 2ND BOSS FIGHT
[RPCS3.log.gz](https://github.com/RPCS3/rpcs3/files/1882293/RPCS3.log.gz)
![untitled](https://user-images.githubusercontent.com/38118895/38398690-11d2382c-394e-11e8-83aa-7de489ecadfe.png)

**Comment by Asinin3** [comment] 2018-04-07 01:48
It's just a random crash, happens a lot with this game especially during the beginning.

**Comment by Rpcs3tester** [comment] 2018-04-07 23:37
@Asinin3  thanks for your comment , you'r right it's hangs alot during gameplay but at least it's goes ingame for about 30 Min or 1 Hour , this the only cutscene that keeps hang with random time ..

i'll wait for new Builds and keep testin it .

**Comment by pitkevich80** [comment] 2018-04-27 14:40
same problem.. Actually until this moment game very seldom  crash for me..  (I can call it playable)
Buit until this moment.. This cut scene freez / crash .. Any way to fix it?

**Comment by pitkevich80** [comment] 2018-06-15 17:11
Hmm still no chance to fix it? or bypass somehow?

**Comment by dio-gh** [comment] 2019-10-13 01:13
Needs retesting. **Please attach a savegame** right before that boss if the issue persists.

The game's compat status is listed as Ingame, if this hang/crash is not particularly frequent or hard to reproduce for others, this issue should be closed.

**Comment by pitkevich80** [comment] 2019-10-13 05:06
I think game must be playable status. I done that game till the end ;) 
It work now :)

**Comment by RainbowCookie32** [comment] 2019-10-13 05:57
If the problem is gone, then close the issue.

And if the game is playable, please make a report in the forums

**Comment by yavimaya** [comment] 2020-01-03 18:32
still hangs in gameplay. Maybe at the first 5 minutes of gameplay

**Comment by Asinin3** [comment] 2020-09-12 00:21
There are some RSX crashes still when running out of VRAM on lower-end GPU's when resolution scaling is being used and a multi-screen scene comes on. But aside from that, this issue is resolved, can close.

**Closed** 2020-09-12 08:28 UTC
Labels: Bug
