### ISSUE TITLE
Disgaea 4 Will Not Launch

### ISSUE THREAD

**Issue by PowerPlayPone** [RPCS3/rpcs3#16224] opened 2024-10-18 02:39 UTC
### Quick summary

![image](https://github.com/user-attachments/assets/ad0939a3-a96c-45b3-9dea-1d8aa3357ed4)
Tested on literal latest release. This game does not launch without sound files.

### Details

Steps taken:
Launch game
Game does not boot
Close RPCS3
Reset settings to default
Launch game
Game is still obstinate in its refusal to boot
File bug report
Error codes are in image summary

### Attach a log file

https://www.dropbox.com/scl/fi/47xw6ygqgumqm2wpfhaiw/RPCS3.log?rlkey=6mcvw4jcl8dxt0216kheqh39s&st=xp8rexe5&dl=0

The file was 2 MB over the limit.

### System configuration

![image](https://github.com/user-attachments/assets/f839ed5a-d072-4bd2-a02b-a3a21bcb59b7)
![image](https://github.com/user-attachments/assets/b143a61e-f51a-4a89-bd7e-caf2415b5fe9)
It incorrectly lists the OS as 10 when it is 11, thus I made the crude correction.

**Comment by ReLyf47** [comment] 2024-10-18 02:54
Duplicate of #15885

**Comment by ReLyf47** [comment] 2024-10-18 02:55
different game version but same "error" nonetheless

**Comment by PowerPlayPone** [comment] 2024-10-18 03:07
I got the latest version of the game because I want all the patches. Same with the other games on the list. Has https://github.com/RPCS3/rpcs3/issues/15885 been resolved and how do we resolve it?

**Comment by ReLyf47** [comment] 2024-10-18 04:04
it clearly still an open issue
theres no fix other than downgrading to the specified working version

**Comment by Megamouse** [comment] 2024-10-22 21:24
closing as duplicate

**Closed by Megamouse** 2024-10-22 21:24 UTC
