### ISSUE TITLE
Fifa 14 60 fps?

### ISSUE THREAD

**Issue by altiereslima** [RPCS3/rpcs3#5398] opened 2018-12-04 15:07 UTC
RPCS3 displays 60 fps but the game seems to run at 5 fps.

![sem titulo](https://user-images.githubusercontent.com/18044879/49451059-819d7c80-f7c5-11e8-809a-342db7a50b2b.png)
[RPCS3.log.gz](https://github.com/RPCS3/rpcs3/files/2644564/RPCS3.log.gz)

**Comment by MSuih** [comment] 2018-12-04 15:50
The screen is being updated at 60 fps, but the physics/gameplay simulation is running far slower than that. It's not a bug, the emulation is just too slow for that game to be playable.

**Comment by altiereslima** [comment] 2018-12-04 16:13
Ok

**Comment by blackman91** [comment] 2018-12-06 08:59
Close this then

**Comment by MSuih** [comment] 2018-12-06 09:03
You should have a close button next to the comment field, try clicking on it.
![image](https://user-images.githubusercontent.com/19759300/49573405-8fc6d680-f946-11e8-806a-9fed3d5595cf.png)

**Closed** 2018-12-06 10:14 UTC
