### ISSUE TITLE
The Last of Us constant crash at hotel elevator (spoiler)

### ISSUE THREAD

**Issue by psennermann** [RPCS3/rpcs3#8313] opened 2020-05-31 20:44 UTC
## Quick summary
The Last of Us (BCUS98174) always crashes just after the hotel elevator falls down and Joel falls with it in the water: after Joel's head comes out from water and begins to speak with Ellie, the image always get stuck but the sound continue to play (you can hear the voices still playing), also the rumble on joypad get stuck as well.
I've tried to change almost every single emulator setting (also tried to enable/disable mlaa, traps etc patches) but with no avail.
Both Vulkan and OpenGL have this problem.
Here below you can see the image of the stuck frame. 

![image](https://user-images.githubusercontent.com/6342467/83361944-998b9780-a38d-11ea-8d2a-a9beb07510b8.png)

Win10 - Intel i7-7700 - rtx 2060 super

[RPCS3log.zip](https://github.com/RPCS3/rpcs3/files/4708369/RPCS3log.zip)

**Comment by Ghostotakoi** [comment] 2020-05-31 20:54
@psennermann https://youtu.be/6bQVWhOvqOg follow the video, and please close the issue

**Comment by psennermann** [comment] 2020-05-31 21:47
This is NOT a trap issue, that video doesn't solve anything

**Comment by Ghostotakoi** [comment] 2020-06-01 03:00
> 
> 
> This is NOT a trap issue, that video doesn't solve anything

IDK try to read the patch section https://wiki.rpcs3.net/index.php?title=Help:Game_Patches&oldid=14778#The_Last_of_Us i think each floor has an specific trap and for some floor you need to use some wake up delay to avoid desync... anyway you should ask support on discord git is not for support. https://discord.me/RPCS3

**Comment by lainiwaku** [comment] 2020-06-01 05:59
it's still a bug that need to be fixed nativeky, even if a patch is available 
maybe not a priority through ?

**Comment by psennermann** [comment] 2020-06-01 07:26
> > This is NOT a trap issue, that video doesn't solve anything
> 
> IDK try to read the patch section https://wiki.rpcs3.net/index.php?title=Help:Game_Patches&oldid=14778#The_Last_of_Us i think each floor has an specific trap and for some floor you need to use some wake up delay to avoid desync also read this pull #7233 ...anyway you should ask support on discord git is not for support. https://discord.me/RPCS3

Please stop spamming this issue

**Comment by psennermann** [comment] 2020-06-01 07:31
> it's still a bug that need to be fixed nativeky, even if a patch is available
> maybe not a priority through ?

The patch was already applied (trap errors), but the game crashes anyway

**Comment by elad335** [comment] 2020-06-01 07:35
That confuses things, try it without any hack/patch. (including PPU traps stubbing disabled)

**Comment by elad335** [comment] 2020-06-01 08:17
I.e. if it traps instead of hangs in this case then the issues should be updated to reflect that.

**Comment by Xcedf** [comment] 2020-06-01 16:29
Clone of my issue https://github.com/RPCS3/rpcs3/issues/6296

**Comment by stumts** [comment] 2020-06-01 20:09
I've bypassed this problem disabling all trap errors patches and changing Stub PPU Traps from 0 to 1 in The Last of Us config file. After that I got a black screen but it wasn't freezed anymore. To fix the black screen I disable MLAA patch to pass this part of the game.

**Comment by psennermann** [comment] 2020-06-02 21:15
I tried what you wrote, but on my system it still freezes the same way; tomorrow I will try on my old PC to see if it has a different behaviour...

> I've bypassed this problem disabling all trap errors patches and changing Stub PPU Traps from 0 to 1 in The Last of Us config file. After that I got a black screen but it wasn't freezed anymore. To fix the black screen I disable MLAA patch to pass this part of the game.
> 
> I found the solution in this video:
> https://www.youtube.com/watch?v=ZbKzWHsTCgk

I tried your solution, but on my system it still freezes the same way; tomorrow I will try on my old PC to see if it has a different behaviour...

**Comment by psennermann** [comment] 2020-06-02 21:26
> That confuses things, try it without any hack/patch. (including PPU traps stubbing disabled)

I can't disable both RSX trap errors patch and PPU traps stubbing option at the same time, because there is a trap error (0x7bb5c4) just before this crash (the trap error happens when the elevator starts to fall), so I really need one of these two patches/option enabled to bypass that trap error and come to this issue...

**Comment by schuan01** [comment] 2020-06-02 21:49
> I've bypassed this problem disabling all trap errors patches and changing Stub PPU Traps from 0 to 1 in The Last of Us config file. After that I got a black screen but it wasn't freezed anymore. To fix the black screen I disable MLAA patch to pass this part of the game.
> 
> I found the solution in this video:
> https://www.youtube.com/watch?v=ZbKzWHsTCgk

Same freeze after the fall in the elevator scene. No black screen, just freeze with background sound.
I tried disabling MLAA, Traps Patch, both and PPU traps stubbing option  to 1.

**Comment by raffi00** [comment] 2020-06-03 12:09
Same here, it is not a trap error,
But you need to have Stub PPU Traps or traps patches or game will hang a moment faster.
I tried removing all patches except for stub trap, it dosen't help.
It's locking in exact same place, voice is still running, cpu close to 100% but nothing is working.

**Comment by schuan01** [comment] 2020-06-06 17:46
Hi guys, following this guy's guide solved the issue.
https://www.youtube.com/watch?v=6vDM8UCJAMA

I think this is a regression issue. Black screen is expected but Freeze is done in current master build.

I am pretty sure there is no need of Cheat Engine as the video suggested, probably only applying the patch with Traps fix enabled.

Steps to solve it:
1. Download rpcs3 build 10297(required)
2. Apply the patch.yml(with trap fix enabled)
3. Start the game, waits until Joel fall and then after that Black screen, with background sound and Subtitles but all black.
4. Wait until Press L3
5. Close the emulator, comment the patch.yml line realted to Traps erros
6. Open game and autosave should start after the fall(Joel inside the water) with No Freeze.
7. If still wants to use latest version of RPCS3, just copy the savegame files to the lasted version and ready to go.

If some steps are not working just read the description in video https://www.youtube.com/watch?v=6vDM8UCJAMA and follow the steps.

**Comment by psennermann** [comment] 2020-06-07 14:41
I followed the instructions and this indeed worked (without using CheatEngine), but for me only putting v. 10297 in a brand new directory (not overwriting) and then using OpenGl...

**Comment by jjouh** [comment] 2020-06-07 20:36
I tried every thing above with no success!
Can psennermann or someone else share with use the savefile after this Elevator bug.
Thank you so much

**Comment by elad335** [comment] 2020-07-23 10:43
Hnm, the log is of the "FARCRY CLASSIC", upload correct log.

**Comment by Xcedf** [comment] 2020-07-25 11:22
Duplicate of #6296, fixed with https://github.com/RPCS3/rpcs3/pull/8617 as well

**Closed** 2020-07-25 16:19 UTC
