### ISSUE TITLE
DX12/GL/Vulkan: Minecraft Vertex Shader Syntax error

### ISSUE THREAD

**Issue by Nezarn** [RPCS3/rpcs3#2175] opened 2016-09-30 08:32 UTC
OpenGL: https://www.dropbox.com/s/km1r4o1obms3ios/rpcs3_ogl.zip?dl=0

> ·E {rsx::thread} RSX: Failed to compile vertex shader: Vertex shader failed to compile with the following errors:
> ERROR: 0:89: error(132) Syntax error: "=" parse error
> ERROR: error(273) 1 compilation errors.  No code generated

Vulkan: https://www.dropbox.com/s/z80qzgaru6ubk2a/rpcs3_vulkan.zip?dl=0

> ·E {rsx::thread} RSX: Warning, version 450 is not yet complete; most version-specific features are present, but some are missing.
> ERROR: 0:90: '' :  syntax error
> ERROR: 1 compilation errors.  No code generated.
> ·E {rsx::thread} RSX: 
> ·F {rsx::thread} class std::runtime_error thrown: Failed to compile vertex shader
> (in file C:\rpcs3\rpcs3\Emu\RSX\VK\VKVertexProgram.cpp:391)

DX12: https://www.dropbox.com/s/5gsfrn0kg3bxsmq/rpcs3_dx12.zip?dl=0

> ·E {rsx::thread} RSX: VS build failed:0000000004f5a6b0
> ·F {rsx::thread} class std::runtime_error thrown: Vertex program compilation failure
> (in file c:\rpcs3\rpcs3\emu\rsx\d3d12\D3D12PipelineState.h:157)

**Comment by kd-11** [comment] 2016-09-30 14:48
Shader decompiler bug with an unknown dst type.

**Comment by clienthax** [comment] 2017-02-26 22:12
To update this.

Seems to work fine on opengl now.

vulkan flat out crashs with vertex buffer not found

and directx
E {rsx::thread} RSX: FS build failed:C:\Programming\ps3\new\rpcs3-ReleaseLLVM-fb56c148\FragmentProgram.hlsl(161,7-42): error X3037: constructors only defined for numeric base types

F {rsx::thread} class std::runtime_error thrown: fragment program compilation failure
(in file c:\programming\ps3\new\src\rpcs3\rpcs3\emu\rsx\d3d12\D3D12PipelineState.h:162)

**Comment by SakataGintokiYT** [comment] 2017-03-07 14:11
**Vulkan**
```
F {rsx::thread} class std::runtime_error thrown: vertex buffer not found
(in file C:\rpcs3\rpcs3\Emu\RSX\VK\VKProgramPipeline.cpp:104)
```

**[Log: ](https://gist.github.com/SakataGintokiYT/213b8f6404b20899cde8bcd81b728aa1)**



**DX12**
```
E {rsx::thread} RSX: FS build failed:D:\EMU\PS3\RPCS3\FragmentProgram.hlsl(161,7-42): error X3037: constructors only defined for numeric base types

F {rsx::thread} class std::runtime_error thrown: fragment program compilation failure
(in file c:\rpcs3\rpcs3\emu\rsx\d3d12\D3D12PipelineState.h:162)
```
**[Log:](https://gist.github.com/SakataGintokiYT/dcb3d405167f3f465395e4ac1da7b88d)**

**Comment by AniLeo** [comment] 2017-06-16 19:05
Please retest, mainly with Vulkan

**Comment by SakataGintokiYT** [comment] 2017-07-07 09:06
@AniLeo 
I tested with latest master now this game works in OpenGL /Vulkan /DX12

**Comment by SakataGintokiYT** [comment] 2017-07-11 07:24
@AniLeo 
Close this

**Comment by Zangetsu38** [comment] 2017-07-11 07:27
no, for dx12 no solved

**Comment by SakataGintokiYT** [comment] 2017-07-11 07:35
@Zangetsu38 
**DX12**
![bez tytulu](https://user-images.githubusercontent.com/13681488/28056177-38309758-661c-11e7-8de3-37bb5f5b97ca.png)

**Comment by Zangetsu38** [comment] 2017-07-11 07:41
not works for me with last master, image freeze in first logo

**Comment by SakataGintokiYT** [comment] 2017-07-11 07:48
@Zangetsu38 
I tested this game on latest master build / 4b431543

**Comment by Zangetsu38** [comment] 2017-07-11 07:50
what settting cpu/gpu ?

**Comment by SakataGintokiYT** [comment] 2017-07-11 07:52
![bez tytulu](https://user-images.githubusercontent.com/13681488/28056811-977e306a-661e-11e7-9543-d7c72e62f9b9.png)

**Comment by Zangetsu38** [comment] 2017-07-11 07:53
oki works now with same settting, but have 
>F {rsx::thread} RSX: Invalid RSX method 0x8 (arg=0x41840)
(in file Emu\RSX\rsx_methods.cpp:44)

**Comment by Zangetsu38** [comment] 2017-07-11 07:57
Works randomly also i have all time in auto mode, lv2 not works 
>F {PPU[0x1000000] Thread (main_thread) [0x01b73930]} class std::runtime_error thrown: Unimplemented
(in file Emu\Cell\Modules\sys_libc_.cpp:300)

**Comment by Zangetsu38** [comment] 2017-07-11 08:13
ok Works good in master with auto mode, lv2 not works, same think in my build, but i don't know if problem caused by pr neko or by gcm hmm 
i have this in my build in auto mode
>F {PPU[0x1000000] Thread (main_thread) [0x01b73930]} class std::runtime_error thrown: Unimplemented
(in file Emu\Cell\Modules\sys_libc_.cpp:300)

**Comment by Zangetsu38** [comment] 2017-07-11 08:24
i have found, caused by last neko PR :/

**Closed** 2017-07-11 12:21 UTC
Labels: d3d12, opengl, shaders, vulkan
