### ISSUE TITLE
[Feature request] Support for compressing/reading games into .zar

### ISSUE THREAD

**Issue by carlosgamer23** [RPCS3/rpcs3#15873] opened 2024-08-01 14:48 UTC
### Quick summary

Recently Xenia started using .zar (format created by ZArchive, not something exclusive to xbox360), it is a simple format that does not interfere with reading the game disc, I believe you could also study the possibility to use this type of format in extracted games, as unlike .chd it does not accept compressing an iso, it just compresses the game folder in .zar in a way that the emulator can read it.

https://github.com/Exzap/ZArchive/releases/

### Details

I know about the differences between emulators, obviously, but the Xbox 360 emulation was previously much more complex than the PS3, and it would be great to get rid of the infernal accumulation of folders weighing more than 6GB. Studying the use of .zar would reduce the emulator installation process, improve the organization of games and mainly save space, rpcs3 itself could do the process, converting the game's installation folder into .zar along with what it needs to start. Well, I just ask that you study this new file format and its practicality, Xenia was mentioned here only as a practical example, since before it only worked with games extracted in folders like RPCS3

**Comment by FlexBy420** [comment] 2024-08-01 14:52
Kinda duplicate of #4021 tbh

**Comment by carlosgamer23** [comment] 2024-08-01 15:06
> Kinda duplicate of #4021 tbh

No, .zar is not chd!

**Comment by carlosgamer23** [comment] 2024-08-01 15:07
> Kinda duplicate of #4021 tbh

.zar does not compress iso or .pkg, it compresses the folder extracted from the game, leaving it readable by the emulator, VERY DIFFERENT from .chd

**Comment by ddmdareal** [comment] 2024-08-01 15:35
#4021 Doesnt specifically state .chd, so at the end of the day its another type of archive.

**Comment by AniLeo** [comment] 2024-08-01 15:39
Duplicate of #4021.

**Closed by AniLeo** 2024-08-01 15:39 UTC

**Comment by Nihilhem** [comment] 2026-05-05 11:09
> Duplicate of [#4021](https://github.com/RPCS3/rpcs3/issues/4021).

As it turned out, that issue was modified to only tackle ISO support. One could argue that the new issue for CHD could be a duplicate, but as it's been mentioned, ZAR (or an equivalent) would be a very different implementation than CHD. It's ok if this is "not planned" but I believe that the "Duplicate" tag is not accurate anymore.
