### ISSUE TITLE
RPCS3 window scaling regression (#4908)

### ISSUE THREAD

**Issue by paxsyr** [RPCS3/rpcs3#5455] opened 2018-12-24 18:23 UTC
Beginning with PR #4908, all of RPCS3's windows, including the settings menu and the game window its self, are now being displayed at extremely large sizes compared to the versions before. I have tried every high DPI compatibility setting in the troubleshooting menu for the rpcs3 .exe file, but they did not help. The images below show how everything is displayed without any resizing of the windows.

Before (rpcs3-v0.0.5-7594-9717e19b):
<img width="960" alt="before" src="https://user-images.githubusercontent.com/38361979/50404992-58488e80-077c-11e9-9b29-f851e8b3ef49.png">

After (rpcs3-v0.0.5-7596-e80574cb / PR #4908):
<img width="960" alt="after" src="https://user-images.githubusercontent.com/38361979/50404994-5f6f9c80-077c-11e9-9c5b-703d890bf428.png">

Past that screen seen in the image above, the game window turns black and none of the game's graphics are displayed, even when I try to resize the window.

This issue seems to be related to the 150% scaling I have set in my Windows settings because when I set it back to 100%, everything displays normally (though of course slightly smaller). 

<details><summary>Update: More images</summary>

Before:
<img width="673" alt="Before New Scaling" src="https://user-images.githubusercontent.com/38361979/61740553-e4e01d00-ad5c-11e9-9871-eee1c168f813.png">

After:
<img width="673" alt="After New Scaling" src="https://user-images.githubusercontent.com/38361979/61740594-004b2800-ad5d-11e9-994e-f68e05648e85.png">
</details>

**Comment by Zangetsu38** [comment] 2018-12-31 00:13
@creeperjedi for simplify, now that is zoomed by 2x if you used scaling windows with 200 % like me, and yes, is problem :(  i have removed temporary this commit on my build for fix that, i waiting all is fixed

**Comment by darkash** [comment] 2019-01-09 13:36
> This isn't really a regression. It's just how windows works with Qt right now.
> Qt scaling is rounded to integer values at the moment:
> https://bugreports.qt.io/browse/QTBUG-53022
> 
> Some possible fix for people who can't manage:
> https://stackoverflow.com/a/49278365/8353754
> 
> The post above also mentions the old dpi setting that we had in place earlier, which was really just upscaling the original window and therefore making the games actually look blurry.

Actually I tried the set environment variable solution and it doesn't really work like charm
The font is resized as if I set the windows scale down, it also breaks full screen. It would be nice to be able to have the option to disable new behaviour. For now I manually change windows scaling whenever I need to change pad config for rpcs3. I hope you and other contributors can consider this option if it doesn't really require extensive effort.

**Comment by Asinin3** [comment] 2019-01-09 13:56
Yeah megamouse plans on reverting it at some stage, I've been having a lot of issues with the changes myself since i often record gameplay while RPCS3 is windowed and rely on pixel perfect window sizes. I just  use crop filters in OBS. It's also nice to be able to take screenshots that are an exact resolution like 1920x1080 while having DPI scaling on.

I don't think the above solution will work well for users like me who switch screens a lot which have different or no dpi scaling.

**Comment by creeperjedi** [comment] 2019-01-21 16:30
After looking into this some more it seems with OpenGL, resizing the window, as is done automatically by this bug, causes the game window to only display black. With Vulkan, the resizing of the game window only streches what the game would normally display. 

A workaround that I have found to work well is to download a program called Sizer (link:http://www.brianapps.net/sizer4/) and create a custom resolution of 1282x766. This will compensate for the borders of the window and have the game itself run at 1280x720, fixing the issuses with OpenGL and Vulkan.

**Comment by Johndeep** [comment] 2019-03-20 20:09
Using `export QT_SCALE_FACTOR=0.5` would render the GUI useless, since it becomes too small, BUT this unironically get rid of all
`E {RSX [<some address>]} RSX: Swapchain: Swapchain creation failed because dimensions cannot fit. Max = 1920, 1023, Requested = 1920, 1024`
errors because of wrong size calculation due to the upscaling. Furthermore, the game window finally has the correct size!

But yeah, no offence, but I agree this to be a regression, since the font and element size mismatches and furthermore, it produces GUI related errors. The best would be to disable/reverting the HighDpiScaling option. And hope that either qt 5.11 resolve this correctly or just use the export options manually.

**Comment by Zangetsu38** [comment] 2019-03-20 22:28
Juste need remplace code set last time "AA_EnableHighDpiScaling" by "AA_DisableHighDpiScaling"
Disable Scaling is normal for Game/video/and here emulator, with scaling, all is broken and get wrong proportion

**Comment by creeperjedi** [comment] 2019-03-21 06:12
I would be in favor of a toggle button on the GUI tab of the options menu, but I assume that is much easier said than done.

**Comment by Johndeep** [comment] 2019-03-21 12:10
@creeperjedi if you suggest something like a toggle button, then this means that this PR #4908 does resolve the problem for somebody? Because otherwise keeping a regression seems not to be wise, especially after what @Zangetsu38 said about scaling and Game/Video/or anything with graphical viewport.

Just daydreaming, but if I were talking about something more like a far away "not-too-bad-for-a-goal", then the way of the ppsspp emulator is the best and most elegant in my opinion, since they just shovel everything into the native UI altogether. Then just let something like SDL2 handle the window stuff and with that, you would never ever have those nasty GUI this, GUI that problem ever again. Especially since the real goal is to improve the emulation, not the GUI. And we could just drop QT support (one less headache). Also, with this, a direct control with a controller for everything would be possible. A much more natural feeling than having to switch from controller to mouse for configurations/trophies and other off-game stuffs. But just like I said (and I probably brought something already discussed up again, sorry for that), just daydreaming.

**Comment by Zangetsu38** [comment] 2019-07-11 16:15
all user here with this issue can use this build
https://ci.appveyor.com/project/Zangetsu38/rpcs3/builds/25912322/artifacts
that fix this issue for get like before and works normally

**Comment by Asinin3** [comment] 2019-07-11 16:24
The problem is that without Megamouse's changes DPI scaling doesn't work properly, and im not just talking about the UI. But lets say you have 300% resolution scaling (4k) on a 4k monitor and are using let's say 200% DPI scaling. Before this change was made RPCS3 would render at 4k, then downscale to the 2k viewport then upscale back to 4k for the window, it wasn't a true 4k output. After the changes were made it renders the viewport and everything at 4k as intended.

We talked about this a lot on Discord already and it was proven months ago so im not sure why its still being discussed as an "issue". Yes it isn't ideal, and I'd like to have it work in such a way that i can have the GS frame be a specific pixel size that didn't account for windows DPI scaling so i could have a perfect 1920x1080 window for screenshots etc but with the way QT works its not really doable atm.

**Comment by Zangetsu38** [comment] 2019-07-11 16:33
for me and user is issue ^^ if with dpi 200 % with 4K screen yopu get all zoomed x2 is probleme, only one solution disable read dpi value, for works normally and kepp all good size , and that is very simple.
And i have all time user that, i have never see your probleme with scaling bad for me i get good

**Comment by Asinin3** [comment] 2019-07-11 16:41
Mate, we've had this discussion multiple times and all the devs gave up trying to explain it to you because it was pointless when you wouldn't even try taking a screenshot of both builds so you could compare for yourself.


100% scaling, 720p window size
https://cdn.discordapp.com/attachments/272035812277878785/526220623538683914/rpcs3-7596_ZRO4yauJ0s.png

150% scaling, same window size, old build
https://cdn.discordapp.com/attachments/272035812277878785/526220738441773067/rpcs3-7563_1njgAJYuXK.png

150% scaling, same window size, new build
https://cdn.discordapp.com/attachments/272035812277878785/526220694015705089/rpcs3-7596_F7rSkJYBxC.png

**Comment by Zangetsu38** [comment] 2019-07-11 16:48
Yes, i know this screen, i see little small change on blur, it more clear, but i have said and tested also this, and see is same result with both build.
And i have also share screen for compare no have issue for me with Real High dpi monitor in arkedo.
And all user with 4K monitor have probleme here with gamepad dialog or just all is zoomed x2.
So no idea if this blur issue affect only normal monitor and if you enable scaling windows for it, for me on my 4K tv and on monitor 4K i get same, is perfect without

**Comment by Zangetsu38** [comment] 2019-07-11 18:28
so finnaly, with lot test and compare, us have see i have right, no have any blur issue, just now disable this read dpi value and close this issue :)

**Comment by Asinin3** [comment] 2019-07-11 18:40
The issue is that the old build we used for comparing (before and after Megamouse's PR was built with new QT dll file via GitHub, so even though we want to do a proper re-test with how it was we cant. But it does look like Qt fixed the underlying issue. What I said above is still correct if you consider the current state of the emulator back when the change was made.

**Comment by CookiePLMonster** [comment] 2019-07-11 18:44
Is making the window DPI-unaware (which what seems to be done by #6192) really a correct fix? I somehow doubt it.

**Comment by Zangetsu38** [comment] 2019-07-11 18:45
yes, is real fix, never enable read dpi value for anythings have resolution render, like game/video etc, if you en,able that, you broken all and get out of box render etc

**Comment by Megamouse** [comment] 2019-07-11 18:59
It's not. Stop hacking

**Comment by Zangetsu38** [comment] 2019-07-12 01:15
I hack nothings, i set it on disable like you have set in before on enable...
Just in my code is just disable by default, like exactly you have set enable by default, but so if i listen you, want said you have hacking aslo ? :)

**Comment by creeperjedi** [comment] 2019-09-19 23:28
Fixed by #6110 and it looks like Qt has fixed it on their end too because the bug that Megamouse linked to is now successfully closed.
Thank you for your work!

**Comment by Zangetsu38** [comment] 2019-09-19 23:30
ah yes, i have forget close this issue after mega put disable read scaling dpi value ^^

**Comment by Zangetsu38** [comment] 2019-10-05 01:40
@creeperjedi for me probleme is back again, you can test for see if same for you ? c

**Comment by creeperjedi** [comment] 2019-11-11 20:48
I can confirm Zangetsu28's finding that this issue was reintroduced by #6704. 

Last tested with: 0.0.7-9123

**Closed** 2020-01-14 09:15 UTC
Labels: GUI
