### ISSUE TITLE
lastest version error report

### ISSUE THREAD

**Issue by h188cm** [RPCS3/rpcs3#2995] opened 2017-07-13 02:00 UTC
---------------------------
Fatal error
---------------------------
Unhandled Win32 exception 0xC0000005.
Segfault reading location ffffffffffffffff at 0000000058216572.
Instruction address: 0000000058216572.
Function address: 0000000058216460 (base+0x246460).
Module name: 'Qt5Widgets.dll'.
Module base: 0000000057fd0000.
RPCS3 image base: 0000000000010000.

HOW TO REPORT ERRORS: Check the FAQ, README, other sources.
Please, don't send incorrect reports. Thanks for understanding.
Press (Ctrl+C) to copy this message.
---------------------------

**Comment by flash-fire** [comment] 2017-07-13 02:03
Try deleting your gui config folder. Also, can you attach a copy of your zipped guiconfig folder?

**Comment by ikki84** [comment] 2017-07-13 02:10
The same is happening here, in the latest master build, but just when I click to run any game in grid mode.
Using list mode it doesn´t happen, also didn´t solve delete the gui config.

Maybe you can reproduce it trying to run a game using grid mode in the latest master build.

**Comment by flash-fire** [comment] 2017-07-13 02:32
I can reproduce.  I'll see what I can do

**Comment by flash-fire** [comment] 2017-07-13 02:46
I can't say I know exactly why but I know how to fix it.  I suspect something with SetCentralWidget deleting the preexisting grid widget when refresh is called on 702.... Removing the refresh fixes the crash.  I have a guess since it seems to crash in a random place deep in Qt later that it's something to do with the deletion of the grid widget when SetCentralWidget is called. I believe SetCentralWidget has a deferred delete on the existing central widget.

Anyhow, easy to patch a build to remove the crash. I'll PR it in a sec

**Comment by Megamouse** [comment] 2017-07-13 05:50
The refresh crash is also happening with right click -> boot game (you forgot to change it as well).

But it actually happens on every second boot with said boot method, unrelated to gamegrid and unrelated to the first boot method

**Comment by AniLeo** [comment] 2017-07-17 12:50
Fixed on master, closing

**Closed by AniLeo** 2017-07-17 12:50 UTC
