### ISSUE TITLE
Unhandled Win32 exception 

### ISSUE THREAD

**Issue by erfanmola** [RPCS3/rpcs3#11229] opened 2021-12-05 19:11 UTC
Hi, Im facing the error below while trying to launch God Of War 3 on latest build of rpcs3 on Windows 11 :
![](https://s9.picofile.com/file/8281917092/Untitled.png)

* OS : Windows 11 Pro (x64)
* CPU : i7 11370H
* GPU : RTX 3060
* Driver version : Nvidia 496.76

I'm using 4.88 Firmware and logs are fine just until I click the play, it gives this error and no more log (app crashes, so no logs)

- SYS: RPCS3 v0.0.19-13083-cb471120 Alpha | HEAD
- SYS: 11th Gen Intel(R) Core(TM) i7-11370H @ 3.30GHz | 8 Threads | 15.69 GiB RAM | TSC: 3.302GHz | AVX-512+ | FMA3
- SYS: Operating system: Windows, Major: 10, Minor: 0, Build: 22000, Service Pack: none, Compatibility mode: 0
- RSX: Found vulkan-compatible GPU: 'NVIDIA GeForce RTX 3060 Laptop GPU' running on driver 496.76.0.0
- RSX: Found vulkan-compatible GPU: 'Intel(R) Iris(R) Xe Graphics' running on driver 0.402.589
- SYS: Firmware version: 4.88
S UPDATER: RPCS3 is up to date!

**Comment by kunit1** [comment] 2021-12-06 02:37
Most likely same as [11230](https://github.com/RPCS3/rpcs3/issues/11230)

**Comment by kunit1** [comment] 2021-12-08 00:18
Some potential fixes have been merged. Can you please test with the latest version.

**Comment by erfanmola** [comment] 2021-12-08 01:05
Tried the latest version, It logs : 

https://pastebin.mozilla.org/J9yALAjU

**Comment by kd-11** [comment] 2021-12-08 21:12
Do a little regtesting to get it resolved quickly while the issue is still fresh. Try some older builds from the downloads page and find the first one that is broken. That will at least point us to the right person to investigate the issue.

**Comment by Megamouse** [comment] 2021-12-15 21:48
Is this still happening? if yes, upload a new log file please.

**Comment by Megamouse** [comment] 2021-12-23 08:44
Closing due to inactivity

**Closed by Megamouse** 2021-12-23 08:44 UTC
Labels: Need Information, Regression
