### ISSUE TITLE
Gran Turismo 6 graphics error in all versions

### ISSUE THREAD

**Issue by papagoghub** [RPCS3/rpcs3#15016] opened 2024-01-06 07:11 UTC
### Quick summary

In all versions of Gran Turismo 6 v1.02~v1.22, when Default Resolution 1920x1080 is set, WCB, RCB, RDB, WDB, and CPU Blit are not used as long as there are no 2D elements on the screen.
This allows MLAA to render correctly without flickering or light and shadow errors. Could the developers please see if it is possible to correct this current error?

### Attach a log file

[RPCS3.log](https://github.com/RPCS3/rpcs3/files/13848659/RPCS3.log)

### Attach capture files for visual issues

Differences in setting the 2D UI display switch in the game
[BCAS25018_recording_2024_01_06_15_02_56.zip](https://github.com/RPCS3/rpcs3/files/13848668/BCAS25018_recording_2024_01_06_15_02_56.zip)

### System configuration

OS Windows10 21h2
CPU i5-12500
GPU RTX2060 Driver 537.63

**Comment by Satan86** [comment] 2024-01-06 21:13
Duplicate of #12567.

**Comment by papagoghub** [comment] 2024-01-07 02:49
Thanks for the reply, I hope smart developers can find a good solution one day.

**Closed** 2024-01-07 10:07 UTC
