### ISSUE TITLE
GTA IV RSX error spam

### ISSUE THREAD

**Issue by xddxd** [RPCS3/rpcs3#8773] opened 2020-08-25 22:53 UTC
When WCB is enabled on GTA IV (needed to fix the water reflections), the game constantly spams 
`RSX: Surface at 0xc4c00000 inherited stale references`
`RSX: Surface at 0xc4ac0400 inherited stale references`
`RSX: Surface at 0xc36c0400 inherited stale references`
`RSX: Surface at 0xc36c0000 inherited stale references`
`RSX: Surface at 0xc3724000 inherited stale references`
`RSX: Cannot invalidate a currently bound render target!`
`RSX: Cache miss at address 0xC36C0400. This is gonna hurt...`
`RSX: Cache miss at address 0xC36C0000. This is gonna hurt...`

RPCS3 v0.0.12-11032-9e14d24
Ryzen 7 2700
RX 580
Log: 
[RPCS3.log](https://github.com/RPCS3/rpcs3/files/5394435/RPCS3.log)

**Comment by kd-11** [comment] 2020-10-18 16:11
Yikes.

**Comment by xddxd** [comment] 2021-02-17 08:21
The game no longer spams
RSX: Cannot invalidate a currently bound render target!
but is still spamming the lines above and
`·W 0:01:11.286433 {RSX [0x00421a8]} RSX: Could not match buffer requirements and host pointer properties.`
[RPCS3.log.gz](https://github.com/RPCS3/rpcs3/files/5994238/RPCS3.log.gz)

**Comment by kd-11** [comment] 2021-08-09 17:43
Needs an update.
`could not match buffer requirements` error is a driver bug on AMD side, but it doesn't matter since it is caused by DMA passthrough which is now disabled by default.
`cache miss at XXXX` is not anything for users to concern themselves with either.
`.. inherited stale references` message no longer exists in the codebase either.

**Comment by kd-11** [comment] 2021-08-09 17:44
Closing pre-emptively. Request to reopen if it still needs investigation otherwise.

**Closed by kd-11** 2021-08-09 17:44 UTC
Labels: Bug, RSX
