### ISSUE TITLE
Persona 5: Thread terminated due to fatal error: Failed to compile fragment shader

### ISSUE THREAD

**Issue by LucasGabrant** [RPCS3/rpcs3#10650] opened 2021-08-03 22:20 UTC
Persona 5 always runned smootly on my setup(60 fps- 720p) , but lastely it has been crashing a lot, and now at random times. 
in the log the error message is the one from the title. 
Thread terminated due to fatal error: Failed to compile fragment shader
my setup - ryzen 7 1600 rx 5500 8 gb, 16 ram 3000 mz.
![image](https://user-images.githubusercontent.com/88407680/128093595-68dd0e83-b960-4205-8a49-9cdae6835dc9.png)
![image](https://user-images.githubusercontent.com/88407680/128093614-91e7894a-7514-4b52-8fdd-e1eb3a982a82.png)

**Comment by AniLeo** [comment] 2021-08-03 22:21
Duplicate of #10645

**Closed by AniLeo** 2021-08-03 22:21 UTC
