### ISSUE TITLE
Regression: Tales of Graces f [BLUS30903] freezes when detecting DLC

### ISSUE THREAD

**Issue by blivveries** [RPCS3/rpcs3#9407] opened 2020-12-10 19:21 UTC
## Quick summary
Game freezes when it detects DLC

## Details
Game freezes after opening logos, at "Checking downloadable content" window before opening cutscene, if DLC is installed. Error log returns `F {PPU[0x1000021] Thread () [0x00435fd8]} VM: Access violation reading location 0x0 (unmapped memory) [type=u64]`. Regression occurs at 0.0.13-11364, pull request #9400

[RPCS3bad.log](https://github.com/RPCS3/rpcs3/files/5675080/RPCS3bad.log)
[RPCS3good.log](https://github.com/RPCS3/rpcs3/files/5675081/RPCS3good.log)
![tog](https://user-images.githubusercontent.com/75806344/101818983-4471d080-3aea-11eb-80d5-ea6f1d5fb7ad.png)

* OS: Windows, Major: 10, Minor: 0, Build: 18363, Service Pack: none, Compatibility mode: 0
* CPU: Intel(R) Core(TM) i5-4690K CPU @ 3.50GHz | 4 Threads | 11.87 GiB RAM | TSC: 3.500GHz | AVX+ | FMA3
* GPU: Radeon RX 580 Series
* Driver version: 2.0.159

I reinstalled both the game and DLC as part of troubleshooting, but nothing changed. The freeze only happens when the DLC is installed, otherwise it proceeds normally. The freeze is non-fatal and the game can be closed with no issues.

**Comment by kd-11** [comment] 2020-12-10 20:25
Duplicate of https://github.com/RPCS3/rpcs3/issues/9410

**Closed by kd-11** 2020-12-10 20:25 UTC
