### ISSUE TITLE
DS4 Handler crashes after connecting controller mid-emulation

### ISSUE THREAD

**Issue by AniLeo** [RPCS3/rpcs3#5985] opened 2019-05-17 15:43 UTC
1. Start gs_gcm_cube.elf or anything with DS4 selected and a disconnected PS4 Pad
2. Turn on your DS4 after booting the game
3. Open pads in the middle of the game and press refresh until DS4 Pad shows as connected
4. Save changes
5. RPCS3 will hard crash (Unhandled exception at 0x000007FEFBBF1454 in rpcs3.exe: 0xC0000005: Access violation executing location 0x000007FEFBBF1454.)

Crashes on
https://github.com/RPCS3/rpcs3/blob/master/rpcs3/Input/ds4_pad_handler.cpp#L786
on
https://github.com/RPCS3/hidapi/blob/master/windows/hid.c#L393

Tested on Windows 7, current master (https://github.com/RPCS3/rpcs3/commit/4037225e989ec798593d64e0ac1a1f887469d11e) and with an official DS4 controller

**Comment by dio-gh** [comment] 2019-07-16 20:05
Still an issue, can confirm.

**Comment by AniLeo** [comment] 2019-08-29 11:54
Still an issue here as well.

**Comment by AniLeo** [comment] 2020-01-08 20:55
Not getting this issue while using Linux, should be a Windows only thing

**Comment by Megamouse** [comment] 2020-06-24 17:56
I can't reproduce this (anymore?)

**Comment by bumpss** [comment] 2020-06-28 17:47
Still getting the issue however using handler "MMJoystick" seemed to fix. I'm using Windows 10 Version 10.0.18362.900

**Comment by dio-gh** [comment] 2020-06-30 19:37
That's not a workaround, the issue is specifically with the DS4 handler to begin with.

**Comment by bumpss** [comment] 2020-06-30 21:16
> That's not a workaround, the issue is specifically with the DS4 handler to begin with.

Pardon, just trying to be helpful to anyone whos having this issue.

**Comment by bevanweiss** [comment] 2020-08-01 08:56
Is this still a problem?
I just tried it (Windows 10 2004, latest RPCS3), and it seems to work for me.
I have DS4 disconnected (USB unplugged), in Pads, it shows all DS4 Devices (1->7) Disconnected (and hence all settings greyed out)
I fire up gs_gcm_cube.elf, and the cube starts spinning
I go back into Pads, and it still shows my controller as Disconnected.
I plug in USB, and hear the USB enumeration (Windows OS) chirp.. press Refresh and it detects as Device 1, controls no longer greyed out.
I press Save (without changing any settings manually) and it returns me back to the spinning cube without any crash.

The log trace shows:
S ppu_loader: PPU executable hash: PPU-90d2b6606e789fc4f4559d7613ad55a4028bd3b1 (<- 0)
S ppu_loader: PRX library hash: PRX-aba8af845072f7dc2664b5a958a9a4f2496f59a8 (<- 0)
E Input: Failed to bind device DS4 Pad #1 to handler DualShock 4
S GUI: Boot successful.
S {PPU[0x1000000] main_thread } SPU: SPU Runtime: Built the interpreter.
E {PPU[0x1000000] Thread (main_thread) [0x00373c0c]} SYS: '_sys_process_get_paramsfo' failed with 0x80010006 : CELL_ENOENT [1]
U {PPU[0x1000000] Thread (main_thread) [0x0037fe64]} sys_prx TODO: _sys_prx_register_module()
U {PPU[0x1000000] Thread (main_thread) [0x003800bc]} sys_prx TODO: _sys_prx_register_library(library=*0x3826a0)
S {PPU[0x1000000] Thread (main_thread) [0x003809ac]} ppu_loader: PRX library hash: PRX-6bf437f05980eee0257bc1d29d8ec0fec0f166f5 (<- 0)
S {PPU[0x1000000] Thread (main_thread) [0x003809ac]} sys_prx: Loaded module: “/dev_flash/sys/external/libsysmodule.sprx” (id=0x23000b00)
U {PPU[0x1000000] Thread (main_thread) [0x003c3d8c]} sys_ss TODO: sys_ss_access_control_engine(pkg_id=0x1, a2=0x1, a3=0xd0010a50)
E {PPU[0x1000000] Thread (main_thread) [0x003c3d8c]} SYS: 'sys_ss_access_control_engine' failed with 0x80010003 : CELL_ENOSYS [1]
U {PPU[0x1000000] Thread (main_thread) [0x003c3d24]} sys_ss TODO: sys_ss_access_control_engine(pkg_id=0x2, a2=0xd0010a50, a3=0x0)
S {PPU[0x1000000] Thread (main_thread) [0x003814d0]} ppu_loader: PRX library hash: PRX-f50c4616d91abb2d4c167950dade5df60ddce6ab (<- 0)
S {PPU[0x1000000] Thread (main_thread) [0x003814d0]} sys_prx: Loaded module: “/dev_flash/sys/external/libgcm_sys.sprx” (id=0x23000e00)
S {PPU[0x1000000] Thread (main_thread) [0x003814d0]} ppu_loader: PRX library hash: PRX-1889244c374c6adc2402efeb808f29656036ea6c (<- 0)
S {PPU[0x1000000] Thread (main_thread) [0x003814d0]} sys_prx: Loaded module: “/dev_flash/sys/external/libsre.sprx” (id=0x23001100)
S {PPU[0x1000000] Thread (main_thread) [0x003814d0]} ppu_loader: PRX library hash: PRX-4b754af5b92c5cc0603a0d11b63aa8dad1f3ca27 (<- 0)
S {PPU[0x1000000] Thread (main_thread) [0x003814d0]} sys_prx: Loaded module: “/dev_flash/sys/external/libfs.sprx” (id=0x23001200)
U {PPU[0x1000000] Thread (main_thread) [0x0038061c]} sys_prx TODO: _sys_prx_register_module()
S {RSX Decompiler Thread} RSX: New program compiled successfully x2
S DS4: Controllers found: 1 x5
S Input: DualShock 4 device 0 connected

**Comment by Megamouse** [comment] 2020-08-01 10:25
From what I've heard this seems to be an issue with custom drivers or ds4windows or what it's called and so on.

**Comment by AniLeo** [comment] 2020-08-01 10:28
I didn't have 3rd party input tools or any other drivers

**Comment by dio-gh** [comment] 2020-08-01 10:42
Correct, this was just regular ol' native DS4 on my end as well. Will also retest in a minute.

**Comment by dio-gh** [comment] 2020-08-01 10:46
Can't repro on current master. One other issue I've noticed however is that if I connect my DS4 with the game already started, RPCS3 won't pick it up without me opening the Pad settings. This is pretty annoying, even if that's the expected behavior.

Regardless, I'd say this issue is already fixed.

**Comment by bevanweiss** [comment] 2020-08-01 12:16
I just had native RPCS3 DS4... I'll try tomorrow with installing DS4Windows and seeing if perhaps there is a USB access conflict that causes any issue.

**Comment by bevanweiss** [comment] 2020-08-02 01:13
Just tested it with DS4Windows, and didn't have any issue either.
I suspect that something had fixed this.
@AniLeo if you can confirm that it's working now for you, then I think it's 'case closed' :)

**Comment by illusion0001** [comment] 2020-08-07 16:56
I can reproduce when connecting to any of the usb ports on my external usb hub, but crash doesn't occur on the motherboard usb ports.
![](https://cdn.discordapp.com/attachments/319224795785068545/741337764137533580/unknown.png)
Log (not very useful): [RPCS3.log](https://cdn.discordapp.com/attachments/319224795785068545/741337733397610536/RPCS3.log)

**Comment by bevanweiss** [comment] 2020-08-09 06:52
I've just tried this with an external USB hub also (albeit a USB3.0 hub.. so maybe it's not a valid comparison), and I didn't get any crash / lockup.

I note in your log the line
DS4: DS4 controller may not be genuine. Workaround enabled.
Is your controller genuine?

There are some comments in the code which suggest the non-genuine controllers:
a. provide a bad response to the 0x81 feature request
b. don't handle calibration data the same as the genuine controllers (even when on USB, they provide calibration data in bluetooth 'format')

So that might be the difference.  I've only got the original genuine DS4 v1 controller, but have just ordered a cheap knock-off.
I suspect it will take a while to arrive however.

**Comment by illusion0001** [comment] 2020-08-09 08:02
> Is your controller genuine?

Yes, It's from my PS4.

**Comment by bevanweiss** [comment] 2020-08-24 22:48
I wasn't able to reproduce with an external USB 3.0 hub.  What kind of USB hub do you have?
I suspect that it's an issue with libusb/hidapi and might relate to the timing of usb enumeration... we are a little bit behind libusb/hidapi trunk.
But there were some CMake issues which prevented it being quite as easy as I first thought.  I'll have a look this weekend again to see if I can get things working.

**Comment by bevanweiss** [comment] 2020-09-27 02:32
It would be great if this could be retested under the PR I just submitted.  It would be more luck that it solves it, and given it's just versioning up libusb, it may well introduce more problems than it solves.. but it's worth a try I think.
#8987

**Comment by Megamouse** [comment] 2021-02-27 23:09
Is this still an issue?
hid stuff was refactored and I haven't noticed any crashes with any of the sony pads so far

**Comment by Megamouse** [comment] 2021-03-30 09:07
closing as info was requested but never provided

**Closed by Megamouse** 2021-03-30 09:07 UTC
Labels: Bug, In Progress, Input, Need Information, OS: Windows

**Comment by octopoulos** [comment] 2021-04-03 19:20
It's still an issue. 
RPCS3 Version: 0.0.15-12040-b7eefeac Alpha
![image](https://user-images.githubusercontent.com/7278312/113489057-2b8a9200-94c2-11eb-87ab-8bdacdc0192f.png)

**Comment by michaeldenijs** [comment] 2022-01-31 19:30
> closing as info was requested but never provided

Necroing here so as to not start yet another thread on this issue: For me at least I have this exact same problem, when using the PS4 controller (genuine one, works fine with other emulators not using ds4, tried reinstalling both drivers and rpcs3, tried updating windows, tried updating graphics driver, tried another controller too and lastly also i have the firmware for the controllers per the instructions) The controller is detected just fine in windows itself, you can see it registers the input in the little test window in set up game controllers part of control panel. It works in steam games (i made sure to turn steam off tho when using rpcs3 bc I've seen this interferres sometimes in previous threads.

So here's the basic process which consistently gives me the error
1. Open the program normally or administrator privilege (seemingly makes no difference)
2. Click 'pads' while the controller is plugged in
3. Freezing of first the small pads window, then the error "
![image](https://user-images.githubusercontent.com/43672203/151857450-d44df3dd-3a12-4f6e-94c5-6758d96c192b.png)" comes each time
4. Click to close that error, the bigger rpcs3 windows freezes and closes itself.

 I also tried variations of the above 4  steps, like first configuring a ps4 controller in Pads, then saving and closing program. Then putting in the PS4 controller and then opening the program, then go on trying to configure the pads, but i get the same error+crash combo. Also tried just launching the game after having configured it beforehand without the controller plugged in, not touch the pads section at all (cause that crashes it etc) and just plug in and then launch the game, but this als just spits out the same error.

I hope that makes it easier to reproduce for y'all: The strange thing is that if I do use 3rd party software like ds4windows, i get the exact same error when I select it (my ps4 controller) with it in DS4windows  configured as a ps4 controller, so that seems to not be a workaround either.  The log included is just what I got when i did the 4 steps above. Please note: I've tried this thing on the latest version aswell, for this session rn I was playing on an old version that is better for playing with 'The Godfather: Don's Edition', however the problem persists on the latest build too (also when I try playing other games on the latest build
[RPCS3.log](https://github.com/RPCS3/rpcs3/files/7973605/RPCS3.log)
)
However when i make it XInput (so make it like a xbox controller via ds4windows ) RCPS3 has no issue recognizing my controller anymore, i can open the pads window just fine and configure it as if i had an xbox controller irl, then also play games all ok, it's only drawback is that ofc you have no sixaxis.
Included is the logs, if i can help anymore with providing some info, just say the word. It might seem like a minor thing, but being able to play with the PS4 controller without ds4windows would be much easier, being able to play with sixaxis (the godfather game is my favorite!) would also be great.

Hopefully i provided enough info, if there is another thread on it that is not dead/more recent then my apologies for necoring it, this seemed to be the one which seemed most recent and most identical to my issue.
