### ISSUE TITLE
Ratchet and Clank: ToD [BCES00052] - Regression After #7253

### ISSUE THREAD

**Issue by SpeddieSwagetti** [RPCS3/rpcs3#7359] opened 2020-02-01 04:14 UTC
After #7253 game will randomly crash in-game. OpenGL and Vulkan are affected and no variations in settings resolve the issue.
RSX [0x215d1a4] RSX: class std::runtime_error thrown: Verification failed: 
(in file C:\projects\rpcs3\rpcs3\Emu\RSX\Common\texture_cache.h:2658)

Log: [RPCS3.log.gz](https://github.com/RPCS3/rpcs3/files/4142128/RPCS3.log.gz)

**Comment by kd-11** [comment] 2020-02-01 10:17
I have no idea what is going on here, upload a log from current master. There is no assert on line 2658, and even in that PR you mention I could not find any assert on that line.

**Comment by SpeddieSwagetti** [comment] 2020-02-01 12:28
Still the same on latest master
[RPCS3.log.gz](https://github.com/RPCS3/rpcs3/files/4142513/RPCS3.log.gz)

Here is the log for the #7253 build when the issue started occurring:
[RPCS3.log.gz](https://github.com/RPCS3/rpcs3/files/4142533/RPCS3.log.gz)

**Comment by kd-11** [comment] 2020-02-01 12:29
`Experimental Build Warning! Build origin: RPCS3/rpcs3/master/=7353` Wrong log. Build ID is also incorrect.

**Comment by kd-11** [comment] 2020-02-01 12:30
Ahh, its from sections PR. Ok.

**Comment by SpeddieSwagetti** [comment] 2020-02-01 12:31
Sorry I am a novice with Github

**Comment by kd-11** [comment] 2020-02-01 12:44
It's ok, I have the right information now.

**Comment by kd-11** [comment] 2020-02-01 18:25
No amount of running around and waiting caused this issue to appear on my system making it difficult to deal with. I'll revisit this one at a later time.

**Comment by TeamZXXX** [comment] 2020-02-03 03:36
game crashes for me too in the first world after trying to play the level for less than a minute

**Comment by kd-11** [comment] 2020-02-06 17:49
Myself and some testers were unable to reproduce this issue on latest master, so it is getting downgraded for the moment.

**Comment by SpeddieSwagetti** [comment] 2020-02-06 22:12
Still crashes on certain sections despite fresh drivers, new caches, etc. The only way to prevent the crashes from occurring is by enabling the Force CPU Blit option.

On the Ublik Passage level, I have found two consistent spots where the crash always happens.
![Ublik Passage](https://user-images.githubusercontent.com/48142631/73982287-ad932f80-497f-11ea-8c0e-db0767a891b0.PNG)
![Ublik Passage 2](https://user-images.githubusercontent.com/48142631/73982289-aec45c80-497f-11ea-9655-13bd6ae1c69b.PNG)
Would it be helpful if I provided you the save data to test that level?

**Comment by kd-11** [comment] 2020-02-07 06:51
> Would it be helpful if I provided you the save data to test that level?

Yes and instructions on what to do as well.

**Comment by SpeddieSwagetti** [comment] 2020-02-08 02:23
Savedata: [BCES00052_SAVE_1.zip](https://github.com/RPCS3/rpcs3/files/4173647/BCES00052_SAVE_1.zip)

After loading the save data, the characters will fall through the ground due to collision issues. This will loop anywhere from 20-100 times and eventually the collision will work (Use cheat engine to speed the process up).  
Walk towards the enemy and shoot it. Upon killing the enemy and walking forward, the game should crash.

**Comment by kd-11** [comment] 2020-02-08 16:18
Turns out this particular tactic is not very suitable for actually debugging where one would need to repeatedly cause an error to happen. If you can find a more accessible spot that triggers the issue, update the ticket with details.

**Comment by Cervoxx** [comment] 2020-03-02 04:54
This crash happens constantly on Clanks second level where he is sent in to fix the IRIS supercomputer. No specific place but somewhere in that level. To get to it, just hop on the teleporter after you load in and walk forward.

I'm aware that at the time of writing the build I'm using (rpcs3-v0.0.9-9791-ffd5a9e9_linux64) is outdated, however until #7667 is fixed I cannot use a later build.

Save file: https://files.catbox.moe/zgu6io.7z

Logs: https://files.catbox.moe/5k9js2.gz

**Comment by 8hodgsonkh** [comment] 2020-03-02 10:30
The level where you collect parts to fix the ship and play as clank, it crashes literally everytime I've been in there and I've attempted it about 6-7 times now

**Comment by Cervoxx** [comment] 2020-03-02 23:58
> The level where you collect parts to fix the ship and play as clank, it crashes literally everytime I've been in there and I've attempted it about 6-7 times now

Interesting, I haven't had that experience and was able to beat it just fine. The second clank level, now thats giving me the same issues you describe.

**Comment by 8hodgsonkh** [comment] 2020-03-03 00:16
Hmm. I managed to play 3 hours until it crashed by enabling a CPU option in
debug mentioned here. Game is nearly fully playable

**Comment by Cervoxx** [comment] 2020-03-03 00:18
What CPU debug option?

**Comment by 8hodgsonkh** [comment] 2020-03-03 00:22
Force CPU blit emulatomion

**Comment by 8hodgsonkh** [comment] 2020-03-03 00:22
It says it will greatly effect performance but I seen not difference maybe
1-2 FPS

**Comment by Cervoxx** [comment] 2020-03-03 01:06
Now that ratchet and clank ToD seems to work on the latest build agan, here are logs from the latest build: https://files.catbox.moe/gqv1xu.gz

**Comment by Cervoxx** [comment] 2020-03-03 01:58
Same error, same build, but now happening from using openGL as the renderer. At least I got much farther then I did before with that renderer: https://files.catbox.moe/12h81s.gz

**Comment by Cervoxx** [comment] 2020-03-03 04:18
Enabling force CPU blit along with write color buffers to fix weird graphics finally allowed me to beat the level! Logs: https://files.catbox.moe/zzup4r.gz

**Comment by kd-11** [comment] 2020-03-14 12:32
If you can reliably trigger this error, upload a crash log with [this](https://www.dropbox.com/s/5fpnezeqb0vo4au/rpcs3-debug-tod.7z?dl=1) build.

**Comment by Cervoxx** [comment] 2020-03-14 18:08
@kd-11 The download link is 404ing

**Comment by kd-11** [comment] 2020-03-14 20:31
Should be fixed by https://github.com/RPCS3/rpcs3/pull/7779.

@Cervoxx Sorry for the 404, we ended up doing a ton of testing on discord and that build became outdated.

**Closed** 2020-03-15 13:51 UTC
Labels: RSX
