### ISSUE TITLE
TMNT Re-Shelled graphics glitch

### ISSUE THREAD

**Issue by Keleanor** [RPCS3/rpcs3#8069] opened 2020-04-20 18:10 UTC
My PC:
Core i3 9100f
GTX 1660 ti
16 gb ddr4
Windows 10

OpenGL and Vulkan mode have same bugs.

https://imgur.com/H6ITkjS

https://imgur.com/TkclJim

**Comment by jedinjapan** [comment] 2020-05-10 04:27
The exact graphics glitch is unclear here. Is the shadow smooth in the original?

Take an RSX Capture of the scene and upload that as well as your Log file from when you paused the emulator.

**Comment by Asinin3** [comment] 2020-10-31 07:10
Closing due to no RSX/Render doc capture of the issue. And no log file. Retest and confirm the issue is still happening provide the requested information and we can re-open this.

##### How to obtain RPCS3's log:
* Run the game until you find the regression.
* Completely close RPCS3, or move to the next step in case it has crashed.
* Locate RPCS3's log file:
	+ ```RPCS3.log``` (It can show up as just RPCS3 and have a notepad icon)
	or
	+ ```RPCS3.log.gz``` (It can show up as RPCS3.log and have a zip or rar icon)
![image](https://user-images.githubusercontent.com/44116740/84433247-aa15fa80-ac36-11ea-913e-6fe25a1d040e.png)
	On Linux it will be in ```~/.cache/rpcs3/```.
	On Windows it will be near the executable.
* Attach the log:
	+ Drag and drop your log file into the issue.
	+ Or upload it to the cloud, such as Dropbox, Mega etc. 


* To create an RSX capture, use _Create_ _RSX_ _Capture_ under _Utilities_.
Captures will be stored in RPCS3 folder → captures.
	+ Compress your capture with 7z, Rar etc. 
	And drag and drop it into the issue.
	+ Or upload it to the cloud, such as Dropbox, Mega etc.
* To create a RenderDoc capture, please refer to [RenderDoc's documentation](https://renderdoc.org/docs/how/how_capture_frame.html).

**Closed by Asinin3** 2020-10-31 07:10 UTC
