### ISSUE TITLE
SPU PIC Issues PR5944

### ISSUE THREAD

**Issue by Xcedf** [RPCS3/rpcs3#5965] opened 2019-05-14 20:57 UTC
PR #5944 is absolutely awesome, but there are few issues compare to previous state
1) Safe spu cache mode broken for games like Killzone 2/3, Uncharted series, TLoU, GoW3, maybe more
2) GoW 3 has emu crash where's first fmv intro supposed to be
maybe other bugs i do not know

**Comment by Nekotekina** [comment] 2019-05-14 21:35
Yes, I need to have a look.

**Comment by legend800** [comment] 2019-05-14 23:16
Add Wipeout HD to #1 (broken on Safe, fine on Mega).

GOW3 is broken for me on Safe and Mega. Same for Motorstorm Apocalypse. Both with cleared caches and default settings.

**Comment by Tom-Neverwinter** [comment] 2019-05-15 05:53
regression for WipEout® HD Fury [BCES00664] textures pop in and out. stutter. audio is even more out of sync. 8096 seemed to work fairly well. https://pastebin.com/qZuf5Hyt

 (might be a good time to address the bloom issue as well ingame.)

**Comment by mavethee** [comment] 2019-05-15 13:51
Ratchet & Clank: A Crack in Time [BCES00511]:
SPU ASMJIT + SPU Safe:
Black screen after compiling shaders.
![image](https://user-images.githubusercontent.com/47083527/57779325-27b2c280-7726-11e9-9291-d3b74fbad314.png)
[RPCS3.log.gz](https://github.com/RPCS3/rpcs3/files/3182715/RPCS3.log.gz)
SPU ASMJIT + SPU Mega:
After compling shaders from disk, RPCS3 closes itself.
[RPCS3.log](https://github.com/RPCS3/rpcs3/files/3182735/RPCS3.log)
SPU ASMJIT + SPU Giga:
After compling shaders from disk, RPCS3 closes itself.
[RPCS3.log](https://github.com/RPCS3/rpcs3/files/3182746/RPCS3.log)
SPU LLVM + SPU Safe:
After compling shaders from disk, RPCS3 closes itself.
[RPCS3.log](https://github.com/RPCS3/rpcs3/files/3182755/RPCS3.log)
SPU LLVM + SPU Mega:
![image](https://user-images.githubusercontent.com/47083527/57780377-69446d00-7728-11e9-81fe-a967f1b1c7ce.png)
Works fine! (Low framerate caused by Google Chrome killing my memory.)
[RPCS3.log.gz](https://github.com/RPCS3/rpcs3/files/3182773/RPCS3.log.gz)
SPU LLVM + SPU Giga:
RPCS3 closes itself after building SPU cache, but should work in second boot ^-^
[RPCS3.log](https://github.com/RPCS3/rpcs3/files/3182794/RPCS3.log)

**Comment by legend800** [comment] 2019-05-16 03:59
Wipeout HD and GOW3 are fixed with Safe. 

Motorstorm Apoc. works on Mega now, but still freezes on one of the boot screens on Safe.

[RPCS3.log.gz](https://github.com/RPCS3/rpcs3/files/3185333/RPCS3.log.gz)

**Comment by Xcedf** [comment] 2019-05-16 13:58
Confirm games now works with safe again, yet GoW3 still broken with mega, damn even giga works

**Comment by legend800** [comment] 2019-05-16 15:20
GOW3 has been fine with Mega for awhile. You just need to wait longer or clear your spu cache.

**Comment by Xcedf** [comment] 2019-05-17 13:10
Don't know why it's just crashes the emu on Mega, tried everything.

**Comment by connorwalks** [comment] 2019-05-19 05:11
This release breaks FIFA 19 [BLUS31617]. Prior to #5944 the game is completely playable. After #5944 the game gets to kickoff as usual but then freezes while audio continues.

before #5944 :
[playable.log.gz](https://github.com/RPCS3/rpcs3/files/3194782/playable.log.gz)

after #5944 :
[Freezes at kickoff.log.gz](https://github.com/RPCS3/rpcs3/files/3194778/Freezes.at.kickoff.log.gz)

**Comment by Xcedf** [comment] 2019-05-19 20:27
Fed my old mega non-pic cache to GoW3 and it works, but game still unable to create it's own or accept ASMJit

**Comment by RainbowCookie32** [comment] 2019-06-18 23:07
Little Big Planet regressed after this PR too, freezes on a black screen after the intro video with SPU LLVM. ASMJIT works fine
[RPCS3.log.gz](https://github.com/RPCS3/rpcs3/files/3303745/RPCS3.log.gz)
[spu-safe-v1-tane.zip](https://github.com/RPCS3/rpcs3/files/3303752/spu-safe-v1-tane.zip)

**Comment by connorwalks** [comment] 2019-11-19 00:36
I haven't been able to narrow down exactly which one, but it seems as if the issue has been fixed by a recent PR. That is for FIFA games at least. They are all playable once again

I have GoW 3 so if someone can describe the exact issue I'll be happy to test if this PR still has some regressions left over. Maybe someone else with a better grasp of the actual issue can discern whether or not the issue should be closed

**Comment by elad335** [comment] 2020-02-07 17:37
Any update?

**Comment by RainbowCookie32** [comment] 2020-02-07 17:38
LBP games now work with SPU LLVM, so that's fixed

**Comment by digitaldude555** [comment] 2020-02-07 18:53
Killzone games are fine as well.

**Comment by kd-11** [comment] 2020-02-07 19:33
Seemingly fixed, so closing. Request to reopen otherwise.

**Closed by kd-11** 2020-02-07 19:33 UTC
