### ISSUE TITLE
 NINJA GAIDEN Σ2 [NPUB30852] (VK_ERROR_OUT_OF_DEVICE_MEMORY)

### ISSUE THREAD

**Issue by whoisme007** [RPCS3/rpcs3#5652] opened 2019-02-11 11:28 UTC
rpcs3-0.0.6-7795_win64

Windows 10 | i5-7500@ 3.6GHz | GTX 1030  2G VRAM | 16GB RAM

NINJA GAIDEN Σ2 [NPUB30852]

F {RSX [0x01537a0]} RSX: class std::runtime_error thrown: Assertion Failed! Vulkan API call failed with unrecoverable error: Out of video memory (VRAM) (VK_ERROR_OUT_OF_DEVICE_MEMORY)
(in file c:\projects\rpcs3\rpcs3\emu\rsx\vk\vkhelpers.h:693)

the first level end，then  game stop……

![1](https://user-images.githubusercontent.com/6497382/52560341-085c7e80-2e33-11e9-9796-ee647dd4c1a6.png)

![2](https://user-images.githubusercontent.com/6497382/52560369-1ca07b80-2e33-11e9-8587-3089e63cf7ba.png)

**Comment by 13xforever** [comment] 2019-02-11 11:31
> PLEASE READ [THE GUIDELINES](https://github.com/RPCS3/rpcs3/blob/master/.github/CONTRIBUTING.md) BEFORE OPENING AN ISSUE

Provide logs as required by the guidelines

**Comment by whoisme007** [comment] 2019-02-11 12:02
ingame is normal..
![03](https://user-images.githubusercontent.com/6497382/52561676-0f858b80-2e37-11e9-8a36-f5dc8a25919d.png)
after boss down,take like this.
![04](https://user-images.githubusercontent.com/6497382/52561680-114f4f00-2e37-11e9-91ef-882b8bc1199f.png)

![07](https://user-images.githubusercontent.com/6497382/52561913-b702be00-2e37-11e9-8eb4-ec5bf38ca8af.png)


[RPCS3.log](https://github.com/RPCS3/rpcs3/files/2850907/RPCS3.log)

**Comment by kd-11** [comment] 2019-04-05 13:43
How much vram does that 1030 have? Does this game need strict mode? Strict rendering mode can eat up a lot of VRAM per frame instance. Memory optimizations are planned for down the road which could lighten the memory load, but the issue here is likely that 1030.

**Comment by whoisme007** [comment] 2019-04-12 11:52
> How much vram does that 1030 have? Does this game need strict mode? Strict rendering mode can eat up a lot of VRAM per frame instance. Memory optimizations are planned for down the road which could lighten the memory load, but the issue here is likely that 1030.

Gt1030 usually have 2G vram GDDR5 or GDDR4.
my gt1030 is 2g vram Gddr5...and windows 10 can give 8g  GPU shared memory...

if not use Strict rendering mode, then game(NINJA GAIDEN Σ2 [BLAS50160])(HK) close like this...

![001](https://user-images.githubusercontent.com/6497382/56035084-bf09ac00-5d5b-11e9-8ecb-b0539aae8ee6.png)

[RPCS3.log](https://github.com/RPCS3/rpcs3/files/3073100/RPCS3.log)

**Comment by kd-11** [comment] 2019-09-26 12:12
This issue reported by the OP is caused by lack of enough VRAM for high resolutions although the situation may have already improved. The other crashes listed are unrelated and caused by Cell and RSX desynchronization which is highly dependent on performance. Anyway, there is already another ticket tracking that bug, so I'm closing this one.

**Closed by kd-11** 2019-09-26 12:12 UTC
