### ISSUE TITLE
wiepout hd/fury rsx thread crash

### ISSUE THREAD

**Issue by zelurker** [RPCS3/rpcs3#12698] opened 2022-09-23 10:44 UTC
### Quick summary

RPCS3: RSX [0x00a24b8]: SIG: Thread terminated due to fatal error: rsx::get_address(offset=0x64150, location=0x66626660): Local RSX REPORT offset out of range!
(in file ../rpcs3/Emu/RSX/rsx_methods.cpp:674, in function get_report_data_impl) (errno=11=Ressource temporairement non disponible)
(in file ../rpcs3/Emu/RSX/RSXThread.cpp:245, in function get_address) (errno=11=Ressource temporairement non disponible)
corrupted size vs. prev_size while consolidating

This is with RPCS3 v0.0.24-14176-bd1fb864 Alpha

Other variation of the same crash :+1: 
RPCS3: RSX [0x0074130]: SIG: Thread terminated due to fatal error: Segfault reading location 00000008038822ec at 0000000000c790e4.
Emu Thread Name: 'rsx::thread'.

### Details

This seems to happen a little less if setting cpu spu decoder to asmjit, but it still happens.
zcull accuracy setting doesn't seem to make any difference.

It happens a lot less, almost never with RPCS3 v0.0.20-13189-000ec716 and the same configuration, except that this version doesn't seem to support rpcn connection.

Now we have rpcn connection, but the game is very unstable again... !
Sorry I can't give any precise estimation of the build where it happened I don't update rpcs3 often.
Of course the log without the crash won't have all the net warning so it's a lot shorter !

### Build with regression

RPCS3 v0.0.24-14176-bd1fb864 Alpha

### Attach two log files

[RPCS3.log.gz](https://github.com/RPCS3/rpcs3/files/9632926/RPCS3.log.gz)
[RPCS3.log.gz](https://github.com/RPCS3/rpcs3/files/9632949/RPCS3.log.gz)

### System configuration

linux, amd ryzen 7 2700, nvidia gtx 1060

**Comment by Darkhost1999** [comment] 2022-09-23 12:31
Having a range of builds from version 20 to 24 won't help anyone. You can download and replace your appimage from here https://rpcs3.net/compatibility?b and narrow it down a bit. Probably start by Version bumps 21, 22, 23, 24 then disect from there until you find the exact build. Being specific let's us identify what code changed when to be capable of fixing this issue.
If you're using something like flatpak then flatpak is not even maintained by RPCS3 and you'll need to retest entirely over again.

**Comment by kd-11** [comment] 2022-09-23 15:42
Try setting FIFO accuracy to atomic in the advanced tab. And enable accurate RSX reservations as well.
This combination eliminates like 90% of all desyncs.

**Comment by zelurker** [comment] 2022-09-23 16:09
> Try setting FIFO accuracy to atomic in the advanced tab. And enable accurate RSX reservations as well. This combination eliminates like 90% of all desyncs.

Thanks for the tip, I didn't know this option, but sadly it crashed again in the 3rd lap of vineta k, venom, with the ikaras...
It just gave me time to improve my time in the 2nd lap ! ;-)

The message this time :
RPCS3: RSX [0x0075130]: SIG: Thread terminated due to fatal error: Segfault reading location 00000008038822ec at 0000000000c790e4.
Emu Thread Name: 'rsx::thread'.

corrupted size vs. prev_size while consolidating
and core dump

**Comment by kd-11** [comment] 2022-09-23 16:31
Hmm, that's worrying, but I've seen it before on linux. I'll have to investigate.

**Comment by solarmystic** [comment] 2022-09-23 19:33
Definitely seems to be Linux specific. I've just gone through the Vineta k multiple times on Windows now during a Tournament run, and it was perfect.

**Comment by kd-11** [comment] 2022-09-23 21:04
I see you have the debug setting "Use GPU texture scaling" enabled. Please disable that. I'll also make some code changes to remove it, it's not meant to be used outside dev stuff.

**Comment by zelurker** [comment] 2022-09-24 03:16
> I see you have the debug setting "Use GPU texture scaling" enabled. Please disable that. I'll also make some code changes to remove it, it's not meant to be used outside dev stuff.

I could not find this setting anywhere in the gui, so I edited directly the custom config file to set it to false. I don't remember how it could be set to true... !
After that I could do 5 laps with the feisar, then switched to the Ikaras and it crashed on start ! Thanks for your investigation anyway !

**Comment by AniLeo** [comment] 2022-09-24 13:33
Missing build where it regressed

**Comment by zelurker** [comment] 2022-09-24 15:14
It would take hours to find it, a test on 1 build requires a few laps, it
doesn't always crash at the beginning, I even could make 5 laps once
without crashing, and then it crashed almost on the start line of the next
race !
Plus even in the old build I mentioned, it happens, the difference is that
it was very rare you could make a few races before it happens so I could
live with it, now it's so fast to happen that you are lucky when you can
finish 1 race.
It's not an easy target, sorry.

**Comment by YuriNator557** [comment] 2022-09-24 16:05
The regression must be found if you want it fixing, even if it takes a long time

**Comment by kd-11** [comment] 2022-09-24 18:30
I've removed the regression in the title. It is mentioned in the OP's description that it already used to happen. Frequency doesn't matter - the bug either exists or it doesn't.
Unfortunately I am unable to reproduce this issue even after leaving the game running for an extended amount of time. Grabbing a debug log requires a full dev environment for this kind of bug as well especially on linux where the affected system would need a proper local build with debug symbols present in the binary, something we don't have with appimages.

**Comment by zelurker** [comment] 2022-09-24 21:10
Ok, I might take the time to try to install the sources from git and see if
I can build this debug build, tomorrow or in the coming days...
I just had another crash after 4 laps, it's a kind of motivation to try to
help on that...

**Comment by zelurker** [comment] 2022-09-24 22:31
I have just tested from the arch linux native build, and it has the same
stability as v0.0.20-13189-000ec716 !
Actually I thought it was fixed 1st, 3 races without problem which was
totally impossible with the appimage, but then it crashed on a restart from
the same race.
Then I relaunched the program and did 3 more ! Totally incomparable with
what I get from the appimage...
No idea why the appimage is less stable though !
I have installed the vulkan sdk, and cloned the git repo, I guess it's very
long to build seeing all the submodules, but it wouldn't be too surprising
that this kind of crash doesn't happen in a debug build (linked to
optimizations maybe). I can try it though, I'll try to make one later...

Le sam. 24 sept. 2022 à 23:10, Emmanuel Anne ***@***.***> a
écrit :

> Ok, I might take the time to try to install the sources from git and see
> if I can build this debug build, tomorrow or in the coming days...
> I just had another crash after 4 laps, it's a kind of motivation to try to
> help on that...
>

**Comment by kd-11** [comment] 2022-09-25 00:23
I'll push a debug branch somewhere to get more information and some stacktraces.

**Comment by zelurker** [comment] 2022-09-25 08:11
Well my debug build finally failed after 2 errors that I was able to fix
during compilation, but the last one was an undefined reference at link
time and for this one I can do nothing.
The errors were :
3rdparty/SoundTouch/soundtouch/include/FIFOSamplePipe.h: 62 : some warning
made an error about a bad transtype to char *
for ST_THROW_RT_ERROR("Error: Illegal number of channels");
I just removed the transtype in
3rdparty/SoundTouch/soundtouch/include/STTypes.h:128 to read
    #define ST_THROW_RT_ERROR(x)    {assert(x);}
and it didn't complain after that.

The next one was about an error about a suggested noreturn attribute for a
function, apparently it can happen if building without optimizations, and
since I am trying to build a debug build...
this happened for 3rdparty/GPUOpen/include/vk_mem_alloc.h, I don't remember
which line.
Here I just removed all -Werror=xxx where xxx contains noreturn directly
from my build directory for
rpcs3/Emu/CMakeFiles/rpcs3_emu.dir/flags.make
rpcs3/CMakeFiles/rpcs3.dir/flags.make
rpcs3/rpcs3qt/CMakeFiles/rpcs3_ui.dir/flags.make

after that it went until the final link where it failed on
rpcs3/util/init_mutex.hpp:191 : undefined reference to
« stx::init_mutex::c_init_bit »
!!! For this one I have absolutely no idea !!!

**Comment by zelurker** [comment] 2022-09-25 21:12
I am not sure yet, but it might be related to vblank speed. I followed the
advice on the wiki and set the vblank speed at 120 Hz, but I have a monitor
which has a refresh rate of 59.88 Hz, yes, not even 60 Hz, I know, and I
had a very strange behavior, sometimes the ship becomes like limited in
speed, as if there was some strong speed limiter enabled. I finally turned
this setting back to 60 Hz, and enabled the ntsc vblank fixup below, and
recovered my normal speed, and at the same time crashes seem to be a lot
less frequent, actually I was unable to crash the game again after that.
It would require some more testing to be sure, and I won't do that today,
but it looks like an interesting possibility... !

Le dim. 25 sept. 2022 à 10:11, Emmanuel Anne ***@***.***> a
écrit :

> Well my debug build finally failed after 2 errors that I was able to fix
> during compilation, but the last one was an undefined reference at link
> time and for this one I can do nothing.
> The errors were :
> 3rdparty/SoundTouch/soundtouch/include/FIFOSamplePipe.h: 62 : some warning
> made an error about a bad transtype to char *
> for ST_THROW_RT_ERROR("Error: Illegal number of channels");
> I just removed the transtype in
> 3rdparty/SoundTouch/soundtouch/include/STTypes.h:128 to read
>     #define ST_THROW_RT_ERROR(x)    {assert(x);}
> and it didn't complain after that.
>
> The next one was about an error about a suggested noreturn attribute for a
> function, apparently it can happen if building without optimizations, and
> since I am trying to build a debug build...
> this happened for 3rdparty/GPUOpen/include/vk_mem_alloc.h, I don't
> remember which line.
> Here I just removed all -Werror=xxx where xxx contains noreturn directly
> from my build directory for
> rpcs3/Emu/CMakeFiles/rpcs3_emu.dir/flags.make
> rpcs3/CMakeFiles/rpcs3.dir/flags.make
> rpcs3/rpcs3qt/CMakeFiles/rpcs3_ui.dir/flags.make
>
> after that it went until the final link where it failed on
> rpcs3/util/init_mutex.hpp:191 : undefined reference to
> « stx::init_mutex::c_init_bit »
> !!! For this one I have absolutely no idea !!!
>
>

**Comment by zelurker** [comment] 2022-09-26 11:22
And of course, it would have been too easy, still happens... !

Le dim. 25 sept. 2022 à 23:11, Emmanuel Anne ***@***.***> a
écrit :

> I am not sure yet, but it might be related to vblank speed. I followed the
> advice on the wiki and set the vblank speed at 120 Hz, but I have a monitor
> which has a refresh rate of 59.88 Hz, yes, not even 60 Hz, I know, and I
> had a very strange behavior, sometimes the ship becomes like limited in
> speed, as if there was some strong speed limiter enabled. I finally turned
> this setting back to 60 Hz, and enabled the ntsc vblank fixup below, and
> recovered my normal speed, and at the same time crashes seem to be a lot
> less frequent, actually I was unable to crash the game again after that.
> It would require some more testing to be sure, and I won't do that today,
> but it looks like an interesting possibility... !
>
> Le dim. 25 sept. 2022 à 10:11, Emmanuel Anne ***@***.***> a
> écrit :
>
>> Well my debug build finally failed after 2 errors that I was able to fix
>> during compilation, but the last one was an undefined reference at link
>> time and for this one I can do nothing.
>> The errors were :
>> 3rdparty/SoundTouch/soundtouch/include/FIFOSamplePipe.h: 62 : some
>> warning made an error about a bad transtype to char *
>> for ST_THROW_RT_ERROR("Error: Illegal number of channels");
>> I just removed the transtype in
>> 3rdparty/SoundTouch/soundtouch/include/STTypes.h:128 to read
>>     #define ST_THROW_RT_ERROR(x)    {assert(x);}
>> and it didn't complain after that.
>>
>> The next one was about an error about a suggested noreturn attribute for
>> a function, apparently it can happen if building without optimizations, and
>> since I am trying to build a debug build...
>> this happened for 3rdparty/GPUOpen/include/vk_mem_alloc.h, I don't
>> remember which line.
>> Here I just removed all -Werror=xxx where xxx contains noreturn directly
>> from my build directory for
>> rpcs3/Emu/CMakeFiles/rpcs3_emu.dir/flags.make
>> rpcs3/CMakeFiles/rpcs3.dir/flags.make
>> rpcs3/rpcs3qt/CMakeFiles/rpcs3_ui.dir/flags.make
>>
>> after that it went until the final link where it failed on
>> rpcs3/util/init_mutex.hpp:191 : undefined reference to
>> « stx::init_mutex::c_init_bit »
>> !!! For this one I have absolutely no idea !!!
>>
>>

**Comment by tr1p0p** [comment] 2022-09-29 00:32
I have this too, on linux fedora last appimage relase

**Comment by italoghost** [comment] 2022-09-29 00:43
I have the same segfault as @zelurker but on The Last Of Us:

·F 0:02:18.330845 {RSX [0x0011000]} SIG: Thread terminated due to fatal error: Segfault reading location 0000000803a98a74 at 0000000000d4b79b.
Emu Thread Name: 'rsx::thread'.

Arch Linux Gnome 42 Wayland
Using both the rpcs3-git (0.0.24-14203-8170b91f Alpha) and the AppImage (latest).

**Comment by kd-11** [comment] 2022-09-30 20:49
Fixed by https://github.com/RPCS3/rpcs3/pull/12735

**Closed by kd-11** 2022-09-30 20:49 UTC
Labels: Bug, Need Information
