### ISSUE TITLE
Linux : Graphic interface

### ISSUE THREAD

**Issue by Aisyk** [RPCS3/rpcs3#8637] opened 2020-07-26 12:44 UTC
Hi !

I uses PopOS 20.04, and when i launch RPCS3, i have a buggy interface. Cannot launch anything, or test... my mouse cursor don't point the accurate elements in interface.

Is there anything to do ?

![88071371-05aba000-cb74-11ea-9f66-ad04ff4c552b](https://user-images.githubusercontent.com/5584650/88479300-53e2e980-cf4e-11ea-9f1c-cde69a152c01.png)

Thanks !

**Comment by jacob1218** [comment] 2020-07-26 12:52
duplicate of #8095

**Comment by Aisyk** [comment] 2020-07-26 12:59
Nope,
This bug is closed, my bug is not resolved with the commands in this thread.

**Comment by AniLeo** [comment] 2020-07-26 13:06
How does it look with QT_AUTO_SCALE_FACTOR=0 ?

**Comment by Aisyk** [comment] 2020-07-26 13:11
Same.
![Capture d’écran du 2020-07-26 15-10-53](https://user-images.githubusercontent.com/5584650/88479828-3748b080-cf52-11ea-82b6-23917b892e71.png)

**Comment by AniLeo** [comment] 2020-07-26 17:37
You're exporting an env variable to that console environment and then launching the emulator elsewhere...

**Closed by AniLeo** 2020-07-26 17:37 UTC
Labels: OS: Linux
