### ISSUE TITLE
Save data randomly removed overnight

### ISSUE THREAD

**Issue by Raspbarrel** [RPCS3/rpcs3#16041] opened 2024-09-04 09:59 UTC
### Quick summary

I was just about to play Ratchet & Clank Crack in Time when the game said to me: "Failed to save or load data".

I went to see the save data folder and saw that all the files for the save file are gone except 'PARAM.SFO'

How can this even happen? Is there a way to fix it, or do I have to start the game all over?

### Attach a log file

[RPCS3.log.gz](https://github.com/user-attachments/files/16868371/RPCS3.log.gz)

### Attach capture files for visual issues

![image](https://github.com/user-attachments/assets/2ac891e3-89c8-4595-9e66-8a79acf4802f)

![image](https://github.com/user-attachments/assets/8f39f1a1-438f-4fc4-84f9-3d06cb7a9769)

**Comment by AniLeo** [comment] 2024-09-04 20:24
RPCS3 doesn't remove savedata out of nowhere. This was caused by an external factor, such as a filesystem error, or interference from a third party software, such as a file sync software or an anti-virus.

If the savedata is fully deleted and the drive sections overwritten there's nothing to do. Try using file recovery software to see if the files can still be recovered from the unwritten sections of your partition.

Closing as Invalid.

**Closed** 2024-09-04 20:24 UTC
Labels: Meta: Invalid
