### ISSUE TITLE
consistent popping sound when audio buffering is on in demon's souls

### ISSUE THREAD

**Issue by esanscoopsers** [RPCS3/rpcs3#15827] opened 2024-07-23 04:57 UTC
### Quick summary

a consistent popping sound in demons souls when audio buffering is on

### Details

this is NOT audio stuttering or crackling but rather a consistent popping sound whenever audio is played in the game. it's like it plays in a pattern because of how consistent and repetitive it sounds. this sound only plays when audio buffering is on. through testing I have found that lowering the audio buffer duration slows down the sound. the pops play further apart and are quieter. when audio buffer duration is increased the pops play quicker or closer together and are louder.

I would just turn audio buffering off but then that causes actual audio stuttering.

### Attach a log file

rpcs3 has not creating a log file. there is no ~/.cache/rpcs3/ folder

### System configuration

I am on linux using the latest flatpak version.

**Comment by RipleyTom** [comment] 2024-07-23 05:08
Duplicate of https://github.com/RPCS3/rpcs3/issues/13310

**Closed by RipleyTom** 2024-07-23 05:08 UTC
