### ISSUE TITLE
 Dualshock 4 not working on evdev

### ISSUE THREAD

**Issue by oangelo** [RPCS3/rpcs3#4390] opened 2018-04-04 21:45 UTC
I am using "rpcs3-v0.0.5-6633-b0352d6e_linux64.AppImage" and I am having problems with the analog zones of Dualshock 4. Everything works great with my xbox one game pad...
![image](https://user-images.githubusercontent.com/1669411/38336493-518d67aa-3838-11e8-939e-f2bb51821ceb.png)

**Comment by hcorion** [comment] 2018-04-04 21:46
Are you using the DualShock 4 backend, or the evdev backend?

**Comment by oangelo** [comment] 2018-04-04 21:51
@hcorion, I am using evdev, if i try the "DualShock 4 backend" I get: 
E HLE: [DS4] No controllers found!

**Comment by miguel-nunes** [comment] 2018-04-04 21:51
Did you give the right permissions to the DS4?

Try this:

mnunes@cloud-strife:~/apps/rpcs3/build$ cat /lib/udev/rules.d/99-ds4-controllers.rules 
# DualShock 4 over USB hidraw
KERNEL=="hidraw*", ATTRS{idVendor}=="054c", ATTRS{idProduct}=="05c4", MODE="0666"
#
# # DualShock 4 wireless adapter over USB hidraw
KERNEL=="hidraw*", ATTRS{idVendor}=="054c", ATTRS{idProduct}=="0ba0", MODE="0666"
#
# # DualShock 4 Slim over USB hidraw
# KERNEL=="hidraw*", ATTRS{idVendor}=="054c", ATTRS{idProduct}=="09cc", MODE="0666"
#
# # DualShock 4 over bluetooth hidraw
# KERNEL=="hidraw*", KERNELS=="*054C:05C4*", MODE="0666"
#
# # DualShock 4 Slim over bluetooth hidraw
# KERNEL=="hidraw*", KERNELS=="*054C:09CC*", MODE="0666"

Stopped work for me at some moment and I added those rules. Working flawlessly now.

Don't forget to restart your machine after add those settings

**Comment by miguel-nunes** [comment] 2018-04-04 21:54
Note: With those settings above you can use the DS4 backend without problems. Evdev never worked right to me at least.

**Comment by hcorion** [comment] 2018-04-04 22:28
> I think the msg "EHLE: [DS4] No controllers found!" must be made more clear.

that sounds like a good idea, maybe change the title, or close this issue and create a new one.
> And still, evdev has an issue.

This sounds like a bug in evdev itself, not something we can fix, but I don't have a ds4, so I can't say for sure.

**Comment by oangelo** [comment] 2018-04-04 22:35
@hcorion, I think the dualshock 4 works on an old version... but I am not sure. Anyway, would be nice to have a warning for the user to not use the evde with dualshock 4.

**Comment by HugoSantiagoBecerraAdan** [comment] 2018-05-23 17:22
I have the same issue with the analog zones and a Dualshock 3 controller on Kubuntu 18.04. The rest of the controller buttons, triggers and even the vibration works fine.

By using the Windows binary with Wine the right analog is missing.

**Comment by dogtopus** [comment] 2019-05-14 07:01
> This sounds like a bug in evdev itself, not something we can fix

What can be possibly done on the RPCS3 side is to add a "set analog stick center position" option to the gamepad settings (or even automatically correct the offset by letting the user rotating the analog sticks). DS4 uses 0-255 for analog stick values with 128 as the center point and the evdev HID driver is just being honest about it.

**Comment by RipleyTom** [comment] 2019-05-14 07:09
@dogtopus you realize we have a ds4 pad handler that works with DS4 and supports sixaxis, why would you use evdev for a DS4?

**Comment by dogtopus** [comment] 2019-05-14 17:08
Similar things can be said for evdev as well: there's kernel support for DS4, why supporting it again in userspace software? 😉
Just kidding. Seriously though, the problem is more about not respecting the minimum/maximum value defined in HID descriptor for a gamepad. Just because most gamepads use -127/127 does not mean it is the only way and every gamepad should do the same. I can imagine that there might be other gamepads that have non-zero center position for analog sticks, and blaming these for firmware bug/upstream bug probably won't do anything other than adding another gamepad to unsupported list

**Comment by Megamouse** [comment] 2019-05-14 17:36
sorry but the evdev specs define a stick as having -x to +x.
If that's not the case then your drivers are wrong and someone didn't care enough to follow the specs.

**Comment by dogtopus** [comment] 2019-05-21 00:33
> sorry but the evdev specs define a stick as having -x to +x.

Well That was interesting. Any drivers for other devices that actually resolve this explicitly? If not it could be an oversight on the documentation/spec.

**Comment by Megamouse** [comment] 2019-05-21 18:11
It makes sense because there's no flag to differentiate sticks from triggers. So +-x is the only way to tell them apart

**Comment by dogtopus** [comment] 2019-05-22 06:13
Well USB HID also doesn't differentiate between an analog stick and a trigger, so the Linux generic HID driver would never know if some axis is supposed to be an analog stick either and therefore unable to convert the raw values to fit within +-127 range

**Comment by Megamouse** [comment] 2019-06-20 07:21
Anyway. I won't add hardcoded controller presets.
And I also refuse to workaround some form of calibration for now since 99% of the users don't have any issues and we actually have this config file "evdev_positive_axis.yml" in which you can set these yourself.
I don't know why I didn't mention this earlier.

Is the original issue here resolved?

**Comment by osirase** [comment] 2019-06-20 08:47
I've followed this: https://wiki.rpcs3.net/index.php?title=Help:Controller_Configuration and the above comment which specified a similar thing at this directory /lib/udev/rules.d/99-ds4-controllers.rules 

I'd really like to get this working. It picks up in Evdev just fine but I'm getting the same off center joysticks, so I can't configured it. All the DS4 slots show as 'Disconnected'.

I'm running Fedora 30 on a Ryzen 2200g, rpcs3-v0.0.6-8266-5753b322_linux64.AppImage.

The logs say:
E HLE: [DS4] hid_open_path failed! Reason: 0000000000000000
E HLE: [DS4] One or more DS4 pads were detected but couldn't be interacted with directly
E HLE: [DS4] Check https://wiki.rpcs3.net/index.php?title=Help:Controller_Configuration for intructions on how to solve this issue

How can I confirm the udev rules I made are in effect? as it looks like a read access issue. Any help would be greatly appreciated.

**Comment by osirase** [comment] 2019-06-20 08:47
I've followed this: https://wiki.rpcs3.net/index.php?title=Help:Controller_Configuration and the above comment which specified a similar thing at this directory /lib/udev/rules.d/99-ds4-controllers.rules 

I'd really like to get this working. It picks up in Evdev just fine but I'm getting the same off center joysticks, so I can't configured it. All the DS4 slots show as 'Disconnected'.

I'm running Fedora 30 on a Ryzen 2200g, rpcs3-v0.0.6-8266-5753b322_linux64.AppImage.

The logs say:
E HLE: [DS4] hid_open_path failed! Reason: 0000000000000000
E HLE: [DS4] One or more DS4 pads were detected but couldn't be interacted with directly
E HLE: [DS4] Check https://wiki.rpcs3.net/index.php?title=Help:Controller_Configuration for intructions on how to solve this issue

How can I confirm the udev rules I made are in effect? as it looks like a read access issue. Any help would be greatly appreciated.

**Comment by osirase** [comment] 2019-06-22 00:59
> Anyway. I won't add hardcoded controller presets.
> And I also refuse to workaround some form of calibration for now since 99% of the users don't have any issues and we actually have this config file "evdev_positive_axis.yml" (has to be created) in which you can set these yourself.
> I don't know why I didn't mention this earlier.
> 
> Is the original issue here resolved?

Hey Megamouse,

I'm not sure I follow, forgive me for not understanding. Will 'evdev_positive_axis.yml' fix the issue first cited in this thread, being off centre Dualshock 4 joysticks? I'd really like to play some games but I have no way to progress my userspace Dualshock 4 detection issue and evdev seems to be 99% working apart from the joysticks... anyhow, thanks for taking the time to read.

**Comment by dogtopus** [comment] 2019-06-22 02:04
>Will 'evdev_positive_axis.yml' fix the issue first cited in this thread, being off centre Dualshock 4 joysticks?
Yes. Set `ABS_{X,Y,RX,RY}` to `true`.

**Comment by osirase** [comment] 2019-06-22 03:51
So I added this line to /home/<user>/.config/rpcs3/evdev_positive_axis.yml

ABS_{X,Y,RX,RY}: true

They're still off centre though. Maybe I have to enumerate each one individually? E.g.
ABS_X: true
ABS_Y: true
etc.

I'll let you know how I go.

**Comment by osirase** [comment] 2019-06-22 03:55
Yup, that was it!

I should have actually read the file as those lines were explicitly saying false. So it was probably overriding 'ABS_{X,Y,RX,RY}: true' as I put it at the very begging of the file rather than the end. 

Thanks for your help. Maybe this should be added here: https://wiki.rpcs3.net/index.php?title=Help:Controller_Configuration as this was the first place I looked from the logs.

Am I able to contribute to adding that to that page?

**Comment by osirase** [comment] 2019-06-22 03:58
I also have DS3 controllers. They're detected in the Dualshock 3 userspace thing but when I go to configure them in the tool, the light turns off and they become completely unresponsive from the perspective of the userspace dualshock 3 configure tool in rpcs3. They appear in evdev though, responding but with the same off centre joystick issue. There doesn't appear to be anything in the logs.

**Comment by osirase** [comment] 2019-06-22 04:54
Huh, evdev seems to have stopped working somewhat. It appears to be picked up in the rpcs3 pad tool. Each button is assignable and reconfigurable. When launching a game in rpcs3, even after selecting evdev and confirming the buttons and joysticks all work, it appears to only pick up the keyboard.

Retroarch picks up and still works with controllers just fine (Hotplugging and everything), and the fact that it detects all inputs just fine in the rpcs3 gamepad tool indicates its working as it should. One weird quirk is that no matter what I select, it always appears to revert back to keyboard input. Even selecting Null. This is under 'Handlers' in the gamepad tool.

Is there anything I can do to provide better details to investigate this issue better? There are no logs that I can see related to evdev or controllers in general.

**Comment by osirase** [comment] 2019-06-22 05:08
> I am using "rpcs3-v0.0.5-6633-b0352d6e_linux64.AppImage" and I am having problems with the analog zones of Dualshock 4. Everything works great with my xbox one game pad...
> ![image](https://user-images.githubusercontent.com/1669411/38336493-518d67aa-3838-11e8-939e-f2bb51821ceb.png)

Hey  @oangelo, can you please download the latest version of rpcs3 snap and retest evdev on your DS4? I'm using rpcs3-v0.0.6-8266-5753b322_linux64.AppImage and it was working fine on the version before that (Apart from the off centre joysticks which is now resolvable) which I unfortunately deleted so I'm not sure how to get that previous version to confirm...

**Comment by Megamouse** [comment] 2019-11-16 15:32
closing for inactivity

**Closed by Megamouse** 2019-11-16 15:32 UTC
Labels: Input, OS: Linux
