### ISSUE TITLE
Prince of Persia Classic [NPUB30031] crashes out on Opengl only on Ubisoft screen

### ISSUE THREAD

**Issue by benderscruffy** [RPCS3/rpcs3#6963] opened 2019-11-08 07:10 UTC
F {RSX [0x006546c]} RSX: class std::runtime_error thrown: VirtualProtect failed (0000000331952000, 0xe2000, addr=0x331952000, error=0x1e7)
doesnt happen on Vulkan
[RPCS3.log.gz](https://github.com/RPCS3/rpcs3/files/3823318/RPCS3.log.gz)

**Comment by benderscruffy** [comment] 2020-01-28 06:56
still happens
[RPCS3.zip](https://github.com/RPCS3/rpcs3/files/4121004/RPCS3.zip)

**Comment by digitaldude555** [comment] 2020-02-04 21:33
Doesnt happen anymore.

**Comment by RainbowCookie32** [comment] 2020-02-04 21:57
The issue is still there, but I'm getting different errors.
![Screenshot from 2020-02-04 18-55-38](https://user-images.githubusercontent.com/16805474/73790869-fda3a380-477f-11ea-9fed-903a5d693ec4.png)
and `·F 0:01:46.915810 {RSX [0x007b294]} RSX: St13runtime_error thrown: GetAddress(offset=0xa6b680, location=0x1): RSXIO memory not mapped
(in file ../rpcs3/Emu/RSX/RSXThread.cpp:74)` on the log.


[RPCS3.zip](https://github.com/RPCS3/rpcs3/files/4156348/RPCS3.zip)

**Comment by AniLeo** [comment] 2020-05-14 15:02
Cannot reproduce.

**Comment by RainbowCookie32** [comment] 2020-05-14 15:37
Can't reproduce here either. Seems fixed in latest master

**Closed** 2020-05-14 15:38 UTC
Labels: Render: OpenGL
