### ISSUE TITLE
Problem with read flashATRAC.pic on several games.

### ISSUE THREAD

**Issue by Zangetsu38** [RPCS3/rpcs3#1293] opened 2015-11-11 13:34 UTC
With Several  games, rpcs3 stop execution, and show nothing any more after this 
Exemple :+1: 
>HLE: W {PPU[0x1] Thread (main_thread)[0x0025be84]} sys_fs: *** path = '/dev_flash/sys/external/flashATRAC.pic'
HLE: W {PPU[0x1] Thread (main_thread)[0x0025c1c4]} cellSpurs: cellSpursEventFlagWait(eventFlag=*0x4e7e00, mask=*0x4c0d24, mode=1)

After show nothing

**Comment by tambry** [comment] 2015-11-11 16:47
@Zangetsu38 I'm pretty sure that's caused by cellSpurs implementation being disabled and not complete. And could you please include the full log and also mention a couple games, where the problem is present?

Also, I think your title is inaccurate. I'm pretty sure that the flashATRAC.pic is read without any problems, but then the spurs fails.

**Comment by Zangetsu38** [comment] 2015-11-11 16:51
No need log, but just look here https://github.com/Zangetsu38/Log-Rpcs3/search?utf8=%E2%9C%93&q=flashATRAC.pic

**Comment by tambry** [comment] 2015-11-11 16:56
@Zangetsu38 Do you happen to a see pattern? All of those games use cellSpursEventFlag*, which has been disabled for a while and probably wont be implemented any time soon.

You're reporting the wrong issue - cellSpurs is at fault here.. Open an issue for implementing/improving cellSpurs, if you don't mind.

**Closed by tambry** 2015-11-11 16:56 UTC

**Comment by Zangetsu38** [comment] 2015-11-11 17:00
@tambry hmm, I see, in this case, had just renamed the issue, not closed.

**Comment by tambry** [comment] 2015-11-11 17:13
@Zangetsu38 I have created #1294 for this.

**Comment by Zangetsu38** [comment] 2015-11-11 17:17
@tambry At ok I see, so perfect :)
And I managed circumvented the problem.
No need to rename the file now.
You think we should do a PR for this?
I've changed
> return _spurs :: event_flag_wait (ppu, eventFlag, mask, fashion, 1);
by
> return _spurs :: event_flag_wait (ppu, eventFlag, mask, fashion, 0);

It disables I suppose, but it works well at least now the games.
