### ISSUE TITLE
RPCS3 Fails to compile [Linux]

### ISSUE THREAD

**Issue by Shoegzer** [RPCS3/rpcs3#9271] opened 2020-11-14 20:07 UTC
RPCS3 now fails to compile on linux systems.  This seems to be related to atomic.

**Test info:**

* OS: Linux Mint 20, kernel 5.4
* CPU: Intel i7-7700HK
* GPU: Nvidia 1070M, driver 450.80
* Compiler: gcc 9.3.0.
* Problem commit: 7cd1e767beffb4d6d63162129050c07da7710b72
    
Build log: [here](https://pastebin.com/KY6kASqx)

**Comment by fisch2** [comment] 2020-11-15 04:30
I have the same issue and did a git bisect. This is the problematic commit: 7cd1e767beffb4d6d63162129050c07da7710b72

**Comment by Nekotekina** [comment] 2020-11-15 05:35
I'll check what's wrong with it. Try to compile with no precompiled headers.

**Comment by fisch2** [comment] 2020-11-15 11:50
Everything compiles successfully without precompiling headers.

**Comment by GitArUs** [comment] 2020-11-16 08:15
@fisch2 - does emulation work after compilation ? For me rpcs3 just hangs when I try to boot any game, without any trace in log, I must press ctrl-c in console to exit.

**Comment by fisch2** [comment] 2020-11-16 08:25
> @fisch2 - does emulation work after compilation ? For me rpcs3 just hangs when I try to boot any game, without any trace in log, I must press ctrl-c in console to exit.

It does, I have successfully tested Kingdom Hearts HD 2.5 Remix, specifically KH2, Tekken 6 and Lightning Returns: Final Fantasy XIII. Although in Lightning Returns, after the cutscene plays out, the first battle scene is completely black, except for the UI and control seems to work fine, as sound effects play correctly when pushing buttons to attack and in KH2, in some of the cutscenes at the beginning, parts of the ocean are drawn on top of the rest of the scene. But this doesn't seem to relate to this issue.

**Comment by Shoegzer** [comment] 2020-11-16 17:21
@GitArUs I too had encountered emulation freezing with every game on a recent build before discovering this issue.  I didn't report it as I didn't want to snow the issue log with what I figured was "noise" due to a temporary regression that would be discovered and fixed like many others.  However, based on what you've seen the issue seems to persist and I'll probably see it again once rpcs3 compiles again in linux. If you could open a separate issue for along with your system specs and @ me, I'll comment there when the time comes.

**Comment by Shoegzer** [comment] 2020-11-17 17:59
Update: Tried testing against commit 68931b4c431761cbbeba79bdc4fa3aa248900711 which includes a potential [linux fix](https://github.com/RPCS3/rpcs3/commit/984e97cbdc5fd50d7685a4a5b2970fc2f42c08fc) but compilation still failed at about the same spot.

Updated compile log is [here](https://pastebin.com/9B30XZ50) in case it helps.

**Comment by D-Marshman** [comment] 2020-11-20 20:27
Same here.. compile failure with latest git version due to problems with "rpcs3/util/atomic.cpp"
[System: Ubuntu 20.10, Kernel: 5.9.8, Mesa Ryzen 5 CPU, Mesa 21.0.0-devel (git-54e8138 2020-11-20 groovy-oibaf-ppa]

I can also verify that going back to "Last known good commit: b05d12d" from the OP, I am able to successfully build and run [just completed 2 races in Motorstorm].

**Comment by Shoegzer** [comment] 2020-11-20 20:51
@D-Marshman Compilation continues failing on linux systems here too, as retested with 5f010c2f4c39d75d92569353d4c39db18fad4d66 from earlier today.   Also you may want to try testing the commit before https://github.com/RPCS3/rpcs3/commit/7cd1e767beffb4d6d63162129050c07da7710b72, as that one seems to be the problem commit as determined by bisect.  I've updated my OP with this info.

**Comment by papjul** [comment] 2020-11-21 10:26
I have no issue on my side, so it's not a "Linux issue".
- OS: Gentoo Linux
- CPU: AMD Ryzen 5
- Compiler: GCC 9.3.0 / LLVM 11.0.0

Here are some of my compilation options in case it helps:
<pre>
-DUSE_NATIVE_INSTRUCTIONS=OFF
-DWITH_LLVM=ON
-DUSE_PRECOMPILED_HEADERS=OFF
-DBUILD_SHARED_LIBS=OFF
</pre>

Precompiled headers were disabled due to #8443 but it's maybe outdated.

**Comment by AniLeo** [comment] 2020-11-21 10:38
This is confirmed fixed by #9310 and will be closed when the PR is merged

**Closed** 2020-11-21 15:27 UTC
Labels: Build and CI
