### ISSUE TITLE
Framebuffer validation is broken

### ISSUE THREAD

**Issue by Psycho-A** [RPCS3/rpcs3#3681] opened 2017-10-30 13:33 UTC
Appeared probably after #3664. When some 3D space loaded, the screen now start flickering by black, and emulator log spams this crap. Appears only when native resolution selected (720p) and Strict mode enabled.

> S {rsx::thread} RSX: New program compiled successfully
> E {rsx::thread} RSX: Framebuffer memory occupied by regular texture! x84
> S {rsx::thread} RSX: New program compiled successfully
> E {rsx::thread} RSX: Framebuffer memory occupied by regular texture! x58
> S {rsx::thread} RSX: New program compiled successfully
> E {rsx::thread} RSX: Framebuffer memory occupied by regular texture! x28
> S {rsx::thread} RSX: New program compiled successfully
> E {rsx::thread} RSX: Framebuffer memory occupied by regular texture! x51
> S {rsx::thread} RSX: New program compiled successfully
> ...and so on to infinity.

Tested game is Silent Hill Downpour.

**Comment by AniLeo** [comment] 2017-10-30 21:37
Happens on One Piece Pirate Warriors too, don't know since when. Probably is the cause of the game’s flickering textures.

**Comment by Psycho-A** [comment] 2017-10-31 12:35
Checked more carefully.
The issue reproduces both OGL and Vulkan when Strict Rendering is enabled. 
Never repeated before merging #3668! Game is now unplayable.

**Comment by kd-11** [comment] 2017-11-01 14:59
retest https://github.com/RPCS3/rpcs3/pull/3689

**Comment by Psycho-A** [comment] 2017-11-01 18:12
@kd-11 
> retest #3689

Flickerings were decreased (but not 100%), but "E {rsx::thread} RSX: Framebuffer memory occupied by regular texture!" still spams almost for every frame. This also causes overall slowdown.

**Comment by Psycho-A** [comment] 2017-11-02 12:03
Didn't fixed after merging #3689 too. Also, new shader programs compiles every one-two seconds at some screens that didn't change its state, and it's never been before.

**Comment by kd-11** [comment] 2017-11-03 16:07
Confirm if fixed by https://github.com/RPCS3/rpcs3/pull/3696

**Comment by Psycho-A** [comment] 2017-11-03 19:47
> Confirm if fixed by #3696 

Didn't fixed. Except removing log spamming there's all the same.
And as I told, I see just a crazy shader compiling that never been before. For example, there were compiled about 40 shaders just during showng title screen (before it was about 7 during loading it's first frame), about 110 during loading first two seconds of intro (~30-40 before), and about 50 every following seconds when we staying at the same place (never happened at all). All of this process is accompanied by a texture flickerings that never seen before too.

**Comment by kd-11** [comment] 2017-11-03 20:01
And it still only appears in strict mode?

**Comment by kd-11** [comment] 2017-11-03 20:36
That can only mean the game is using offsets into the declared areas for rendering and actually using the base address for shader ucode stuff. In that case it will be fixed when the current batch of cache rewrites is finished as properly detecting it requires functionality not present in master right now.

**Comment by Psycho-A** [comment] 2017-11-03 21:19
> And it still only appears in strict mode?
Yes.

**Closed** 2017-11-19 16:03 UTC
Labels: Regression, RSX
