### ISSUE TITLE
Aggressive texture flickering in Ratchet & Clank: Crack in Time & Into the Nexus

### ISSUE THREAD

**Issue by pierr3** [RPCS3/rpcs3#14196] opened 2023-07-14 01:38 UTC
### Quick summary

Textures fail to render with certain camera angles. However, some camera angles, mostly looking down, will allow everything to render properly, see attached screenshots, this quickly reverts as change the camera angle. When the textures fail to render, they also aggressively flicker causing huge performance issues. In the current state, the game is not playable. This might not be a texture issue, but a shader issue, however I am not sure.

### Details

I have also tried with Read Color Buffers as recommended, and both Antialising to Auto and off, to no avail. I initially suspected lack of compatibility with MoltenVK, but since sometimes textures do render properly, it does not seem to be the case.

I have also tried to update the moltenVK dylib to the latest one available with no changes.

Examples of textures rendering incorrectly:
![Screenshot 2023-07-13 at 01 38 57](https://github.com/RPCS3/rpcs3/assets/1833515/ca3c415d-cfc4-4a1b-a77e-86e12189ef54)
<img width="1281" alt="Screenshot 2023-07-13 at 18 10 03" src="https://github.com/RPCS3/rpcs3/assets/1833515/4fbdf7fc-02ae-4eb9-b15e-bc8fce891988">

Example where most textures do render corretly:
<img width="1282" alt="Screenshot 2023-07-13 at 18 09 50" src="https://github.com/RPCS3/rpcs3/assets/1833515/7baa0d26-5706-4edc-b215-31866c0f6fc7">

### Attach a log file

[RPCS3.log.gz](https://github.com/RPCS3/rpcs3/files/12045529/RPCS3.log.gz)

### System configuration

macOS 14.0 Sonoma beta 3
Apple Silicon M2
8GB Memory

Running from an external SSD, using an XBox Controller.

### Other details

I will provide the RSX Capture ASAP.

**Comment by kd-11** [comment] 2023-07-14 11:44
You have shader precision set to low which enables some optimizations on apple hardware. Apple GPUs aren't the best when it comes to standards compliance, so you'll get such problems.
Set shader quality to auto or high instead. You'll get worse performance due to all the corrections moltenvk has to make to get the shaders working but the visual output will be correct.

**Comment by pierr3** [comment] 2023-07-14 18:28
Playing with this setting was to no avail unfortunately, attached is log and capture using shader precision set to high. This issue also seems to cause audio stuttering despite relatively consistent but low FPS. When things do render properly, this seems to begin to go away.

Here is the latest log file, and the capture. Let me know how I can help
[NPUA80966_20230714112502_capture.rrc.zip](https://github.com/RPCS3/rpcs3/files/12052996/NPUA80966_20230714112502_capture.rr
[RPCS3.log.gz](https://github.com/RPCS3/rpcs3/files/12053000/RPCS3.log.gz)
c.zip)

**Comment by kd-11** [comment] 2023-07-14 18:39
I remember this issue from years ago and iirc it was a moltenvk option that causes it. It's why there are no reports for the other platforms.
Pinging @nastys

**Comment by nastys** [comment] 2023-07-14 18:52
Try Advanced -> Disable MSL Fast Math

**Comment by pierr3** [comment] 2023-07-14 19:28
Thanks! That seems to have fixed it, but got a crash almost immediately after starting to play:

```
F {RSX [0x003c7e8]} SIG: Thread terminated due to fatal error: Dead FIFO commands queue state has been detected!
Try increasing "Driver Wake-Up Delay" setting or setting "RSX FIFO Accuracy" to "Atomic", both in Advanced settings. Called from 
(in file /private/var/folders/76/zy5ktkns50v6gt5g8r0sf6sc0000gn/T/cirrus-ci-build/rpcs3/Emu/RSX/rsx_methods.cpp:29[:4], in function invalid_method) (errno=60=Operation timed out)
(in file /private/var/folders/76/zy5ktkns50v6gt5g8r0sf6sc0000gn/T/cirrus-ci-build/rpcs3/Emu/RSX/RSXThread.cpp:3073[:4], in function recover_fifo) (errno=60=Operation timed out)
```

Swtiching RSX FIFO Accuracy to Atomic does seem to prevent that.

However, with MSL Fast Math disabled, CPU and GPU usage shot through the roof and performance tanked :(

**Comment by kd-11** [comment] 2023-07-14 20:24
For performance, I think you can disable MSAA. Graphics will suffer but fps should be a bit better. You can also play around with the ZCULL accuracy option, though relaxed doesn't fully engage on macOS due to the how the apple GPU works internally.

Either way, I think we should close this then as there is no product failure.
Maybe we should make shader quality ultra force-disable MSL fast math, but that's a UX feature request and not a bug report.

**Closed by kd-11** 2023-07-14 20:24 UTC

**Comment by pierr3** [comment] 2023-07-14 21:05
Thanks for the help!
