### ISSUE TITLE
[Regression] FINAL FANTASY XIII [MRTC00003] Crashing to desktop again (#14822)

### ISSUE THREAD

**Issue by Darkhost1999** [RPCS3/rpcs3#14909] opened 2023-12-19 02:38 UTC
### Quick Summary

Final Fantasy XIII started crashing again to the desktop. This time changing the date of regression as there was a moment when this issue was resolved or at least working.

### Details

![image](https://github.com/RPCS3/rpcs3/assets/60384196/eea4dbbd-fbde-4752-975f-5c1ac502dcd1)
At this time it appears the broken log changes its behavior to do something with SYS where it didn't do this before.
Again the symptoms are that the cache used from working builds will continue working on master. 
So **to reproduce this issue** users need to clear their cache. Boot the game and soon find that RPCS3 is closed.

### Build with regression

RPCS3 v0.0.29-15753-fdb2fecd

### Attach two log files

[Broken.log](https://github.com/RPCS3/rpcs3/files/13709135/Broken.log)
[Working-Kinda.log](https://github.com/RPCS3/rpcs3/files/13709136/Working-Kinda.log)

### System configuration

Windows 11 pro
Ryzen 5 3600
GTX 1660 Super

### Other details

What do you mean by kinda works?
There are 12 instances of
```
·F 0:02:03.346525 {SPU Worker 2} SIG: Thread terminated due to fatal error: Verification failed
(in file D:\a\1\s\rpcs3\Emu\Cell\SPURecompiler.cpp:3538[:3], in function analyse)
```
in the working log. The SPU DMA option only worked, before this regression, on 2nd boots and not on the first boots.
After the regression, FFXIII only works with the PPU interpreter again.

**Comment by AniLeo** [comment] 2024-01-01 15:30
Possibly fixed by #14959, needs retesting

**Comment by Darkhost1999** [comment] 2024-01-01 15:43
[RPCS3.log](https://github.com/RPCS3/rpcs3/files/13805098/RPCS3.log)
RPCS3 v0.0.29-15897-195e7e18 Closes to desktop

**Comment by AniLeo** [comment] 2024-01-01 15:44
Linking PR that introduced the regression: #14822

**Comment by elad335** [comment] 2024-02-15 18:53
Test #15212

**Comment by elad335** [comment] 2024-02-16 07:04
I fixed the SPU analyser btw. Not sure what is why the PPU, perhaps it's a concurrency bug in PPU LLVM.

**Comment by Darkhost1999** [comment] 2024-02-29 20:47
```
F {PPU[0x1000028] Thread (white::sound::layout::load) [0x013d6d8c]} SIG: Thread terminated due to fatal error: Verification failed
(in file D:\a\1\s\rpcs3\util\serialization.hpp:135[:5], in function raw_serialize)
F {PPU[0x1000010] Thread (QixFiberWorker0) [0x013d6d8c]} SIG: Thread terminated due to fatal error: Verification failed
(in file D:\a\1\s\rpcs3\util\serialization.hpp:135[:5], in function raw_serialize)
F {PPU[0x1000027] Thread (white::sound::AsyncRegistrant) [0x013d6d8c]} SIG: Thread terminated due to fatal error: Verification failed
(in file D:\a\1\s\rpcs3\util\serialization.hpp:135[:5], in function raw_serialize)
F {PPU[0x100000d] Thread (CDevSd StreamHandler) [0x013d6d8c]} SIG: Thread terminated due to fatal error: Verification failed
(in file D:\a\1\s\rpcs3\util\serialization.hpp:135[:5], in function raw_serialize)
```
[RPCS3.log](https://github.com/RPCS3/rpcs3/files/14453332/RPCS3.log)

![image](https://github.com/RPCS3/rpcs3/assets/60384196/c531ce01-2d35-40b4-93d0-70f20d91da01)

AMD Ryzen 7 7700X
Not closing to the desktop and fatal errors are after closing the game during the intro video

**Comment by elad335** [comment] 2024-02-29 21:46
so this is an liblv2.sprx hle regression

**Comment by Darkhost1999** [comment] 2024-03-01 14:29
That liblvl2.sprx HLE testing was an accident from other tests and currently seems to be appropriately resolved but not the root issue for the close-to desktop. I don't know what got me to the main menu past compiling the LLVM cache.

[RPCS3.log](https://github.com/RPCS3/rpcs3/files/14462259/RPCS3.log)

Here is a current log where I cleared all cache and right-clicked -> boot with default configuration. Shortly later closed to desktop.

**Comment by Darkhost1999** [comment] 2024-03-19 17:28
> Not sure why the PPU crashed, perhaps it's a concurrency bug in PPU LLVM.
Testing #15333 and the PPU crash appears to be gone now. 
[RPCS3.log](https://github.com/RPCS3/rpcs3/files/14654145/RPCS3.log)
![image](https://github.com/RPCS3/rpcs3/assets/60384196/2fa4c690-b088-4fe8-bb37-4fe3ec748a9e)
After that PR is merged there will be no settings other than default needed to boot FFXIII.
If for some reason anyone experiences a crash try using a clean cache.

**Comment by bigol83** [comment] 2024-03-20 12:55
Yesterday i tested this Pr, it fixed this issue. Now that it is merged the game crashes again. Removed all caches, reset to default configuration, still crashes.

**Comment by bigol83** [comment] 2024-03-27 20:51
It is weird how this PR https://github.com/RPCS3/rpcs3/pull/15333 fixed this issue but when it was merged it reappeared.

**Comment by bigol83** [comment] 2024-04-18 18:46
If you want to go ingame you can only use Interpreter PPU decoder.

**Comment by AstroDot** [comment] 2024-05-18 11:45
Hello,

FINAL FANTASY XIII [MRTC00003]

PPU Decoder:
LLVM - crashes RPCS3 on loading PPU
Static - works

RPCS3 Version: 0.0.32-16476-9ceb22a2 Alpha | master

**Comment by Darkhost1999** [comment] 2024-07-18 01:00
Tested RPCS3 v0.0.32-16683-065a6437
[RPCS3.log](https://github.com/user-attachments/files/16276284/RPCS3.log)
Still an issue. To reproduce use a clean LLVM cache. The close to desktop happens when building a new cache not loading an old cache.

**Comment by bigol83** [comment] 2024-07-28 10:35
With the latest main build it crashes a little later at 84/119, it creates a bit more functions compared to last week log 

·! 0:00:56.213189 {PPUW.1.11} PPU: LLVM: 4176 functions generated
·! 0:00:57.684742 {PPUW.1.10} SYS: 

but in the end still crashes to desktop

**Comment by elad335** [comment] 2024-07-29 09:54
who can get stacktrace for it?

**Comment by bigol83** [comment] 2024-07-31 08:49
> who can get stacktrace for it?

I don't know how to do that, i would do it otherwise. I expected someone else to answer this request but It seems there is not enough interest

**Comment by Darkhost1999** [comment] 2024-07-31 13:10
![image.png](https://github.com/user-attachments/assets/762f01d9-f19e-4c4b-96b6-8de13b0730e0)

I've googled and searched, I've asked and asked.
All I ever have gotten answered is that stack trace is just another name for Call Stack. So I assume this is what is being asked for.

**Comment by bigol83** [comment] 2024-07-31 14:18
Nice, thanks, hopefully it helps.

**Comment by TailsGuy** [comment] 2024-08-12 21:09
I just tried this out in RPCS3, the PPU recompiler unfortunately doesn't work still. Static works, but performance is... strange. You can't create a cache with any version from 2024 as far as I can tell.

**Comment by bigol83** [comment] 2024-08-13 11:04
> I just tried this out in RPCS3, the LLVM recompiler unfortunately doesn't work still. Static works, but performance is... strange. You can't create a cache with any version from 2024 as far as I can tell.
> 
> EDIT: I can't get into game even with builds going back a year, I don't know if this is my PC but was it always an issue trying to get in game with the LLVM recompiler?

There was a small period of time when it booted fine with ppu lvm but then went back to crashing. Yeah, i know PPU performance is weird with Interpreter, it definitely is a lot slower. When i could go ingame and play it with PPU LLVM it was basically 60 fps locked while with Interpreter it struggles a lot.

**Comment by TailsGuy** [comment] 2024-08-13 16:33
Well shit I was gonna put a log but I found somewhat of a security concern in logs instead

**Comment by Darkhost1999** [comment] 2024-08-13 16:35
It's okay, the logs are in the original post

**Comment by TailsGuy** [comment] 2024-08-13 16:39
No what I mean is I realized that in logs, you can see the user's names, and if they used their real name as their user name that's kind of an issue isn't it? I don't think I've seen that in PCSX2 or Dolphin or anything like that. That might need to get looked into

**Comment by TailsGuy** [comment] 2024-08-13 16:43
Here's my log but I had to edit that, that's concerning cause so many people have contributed.
[RPCS3.log](https://github.com/user-attachments/files/16602709/RPCS3.log)

**Comment by ReLyf47** [comment] 2024-08-13 16:46
> No what I mean is I realized that in logs, you can see the user's names, and if they used their real name as their user name that's kind of an issue isn't it? I don't think I've seen that in PCSX2 or Dolphin or anything like that. That might need to get looked into.

This is a user skill issue

If you put your RPCS3 folder inside the download folder or desktop ofc it will contain the windows install user name

Simply put it on C:/ or D:/ instead of under C:/Users/[Your Name]/[Any of the folder here]

**Comment by ReLyf47** [comment] 2024-08-13 16:48
Or in your case somehow you put your emulators under document for some reason

**Comment by TailsGuy** [comment] 2024-08-13 16:53
> > No what I mean is I realized that in logs, you can see the user's names, and if they used their real name as their user name that's kind of an issue isn't it? I don't think I've seen that in PCSX2 or Dolphin or anything like that. That might need to get looked into.
> 
> This is a user skill issue
> 
> If you put your RPCS3 folder inside the download folder or desktop ofc it will contain the windows install user name
> 
> Simply put it on C:/ or D:/ instead of under C:/Users/[Your Name]/[Any of the folder here]

Well yeah it's a user skill issue, nevertheless being clipped in log isn't something everyone has in mind when they literally make a Windows user. I sure didn't five years ago, when I was a *child*.

**Comment by TailsGuy** [comment] 2024-08-13 16:59
> Or in your case somehow you put your emulators under document for some reason

It's my business where I put my stuff, it's easily accessible, it's grouped with my other stuff, and that's how it's been for years.

**Comment by bigol83** [comment] 2024-08-15 19:57
With rpcs3 0.0.32 1680 (actual master) this issue has been fixed. I managed to compile all PPU modules with LLVM.

**Comment by ItsLaguna** [comment] 2024-08-15 20:12
Can confirm that it's working again with LLVM IN 0.0.32-16830.

**Comment by Behodar** [comment] 2024-08-15 20:20
While this did fix the original issue, it's now freezing at "Loading PPU Modules, Progress: module 119 of 120 (1s remaining)" with 0.0.32-16830 on MacOS 14.6.1. I'm not sure whether this is a Mac issue or a me issue (deleting all the caches didn't help).

**Comment by bigol83** [comment] 2024-08-15 20:22
> While this did fix the original issue, it's now freezing at "Loading PPU Modules, Progress: module 119 of 120 (1s remaining)" with 0.0.32-16830 on MacOS 14.6.1. I'm not sure whether this is a Mac issue or a me issue (deleting all the caches didn't help).
> 
> Are any other Mac users able to try it?

Try deleting PPU cache

**Comment by TailsGuy** [comment] 2024-08-15 20:27
Just went through some of the prologue scenes and gameplay, it's all in working order. Even locked 60FPS on a Ryzen 7 5700X.
Though I can't say it's fully playable until Chapter Nine's crash is fixed (or has already been fixed and no one knew since you couldn't boot into the game for a year)

**Closed** 2024-08-15 20:32 UTC
Labels: Regression

**Comment by Darkhost1999** [comment] 2024-08-15 20:36
For Future reference, if this issue gets revived make a new regression report.
The confirmed working build is 0.0.32-16830 give or take a small handful of builds if you'd like to find the exact build that fixed this issue.
A new regression report will not ask what build solved this issue, it'll ask for the last known working build and the build that caused the new regression.

**Comment by Behodar** [comment] 2024-08-15 20:37
> Try deleting PPU cache. It's also weird to me it counts 120, the game PPU modules are 119

I moved the rpcs3 folders out of Application Support and Caches, essentially starting from fresh, installed the firmware, booted up... and same issue.

At this point I'm wondering whether it's Mac issue, or whether it affects Linux too (are the rest of you on Windows?). I'm also not sure whether this is a different bug or still related to this particular one.

**Comment by Darkhost1999** [comment] 2024-08-15 20:45
I believe Elad was looking into this if there are still residual issues on Mac the executive decision to revive this or request a new ticket is up to Elad.
I would think a new ticket referencing this one as the original post is officially resolved. But that's an unusual one.
And I'm curious too is this only solved on Windows so far? Was anybody testing Linux?

**Comment by Behodar** [comment] 2024-08-24 08:59
For what it's worth, I tried this on another Mac - one that's never had RPCS3 on it - and it did exactly the same thing. I'll log a "proper" ticket for it when I have time to collect logs etc.

**Comment by mtmrc** [comment] 2024-09-08 13:17
Broken again from build 0.0.32-16848. I'm lazy to open new issue.

**Comment by AniLeo** [comment] 2024-09-08 13:18
#15961

**Comment by devanteweary** [comment] 2024-09-22 08:06
> > Try deleting PPU cache. It's also weird to me it counts 120, the game PPU modules are 119
> 
> I moved the rpcs3 folders out of Application Support and Caches, essentially starting from fresh, installed the firmware, booted up... and same issue.
> 
> At this point I'm wondering whether it's a Mac issue, or whether it affects Linux too (are the rest of you on Windows?). I'm also not sure whether this is a different bug or still related to this particular one.
> 
> [Edit: Your comment came in while I was typing, so I hope you don't feel like I was stepping on your toes]

I'm on Windows 10.

Just tried a brand new, fresh portable "install" of RPCS3 using version **0.0.33-16940-02362a48 Alpha | master**
Installed PS3 firmware 4.91.

It gets pretty far into the pre-compiling of shaders / PPU (sorry not too familiar with the lingo) and then completely crashes / closes RPCS3.
