### ISSUE TITLE
Vulkan Bomberman Ultra [NPUB30051] Issue

### ISSUE THREAD

**Issue by SakataGintokiYT** [RPCS3/rpcs3#1596] opened 2016-03-18 15:43 UTC
@vlj 
@kd-11 
[f99e4f8]
GPU Nvidia [GTX 650TI]
Log : https://gist.github.com/SakataGintokiYT/e36f99ce8c7a6322c98c
Freezing after pressing X

<img src="http://www.fotoszok.pl/upload/7e878d0c.jpg" alt="2015-12-13 20_52_51-xenia" style="max-width:50%;">
<img src="http://www.fotoszok.pl/upload/dcfe0cc0.png" alt="2015-12-13 20_52_51-xenia" style="max-width:50%;">

**Comment by tambry** [comment] 2016-04-04 16:48
Could you check with #1653, once it finishes building?

**Comment by SakataGintokiYT** [comment] 2016-04-04 17:13
@tambry 
<img src="http://www.fotoszok.pl/upload/eb33932e.jpg" alt="Fotoszok.pl" />

**Comment by raven02** [comment] 2016-06-11 16:40
@SakataGintokiYT , please close this one . It is duplicate of Vulkan scaling issue #1655

**Closed** 2016-06-11 18:40 UTC
Labels: bug, rsx, vulkan
