### ISSUE TITLE
Enabling AA under vulkan causes game to freeze completely - Ratchet & Clank Future: A Crack In Time [NPUA80966]

### ISSUE THREAD

**Issue by K1ngfish3r** [RPCS3/rpcs3#12061] opened 2022-05-22 08:20 UTC
## Quick summary
Please briefly describe what is not working correctly.
Game freezes within first two seconds of gameplay. Disable AA to fix
## Details
Please describe the problem as accurately as possible.
Move up on the analog stick after the intro cutscene as clank and the game freezes. Closing the game causes the emulator to crash/close by itself.

#### 0. Make sure you're running with settings as close to default as possible
Enabled Read Color Buffers as per Wiki https://wiki.rpcs3.net/index.php?title=Ratchet_%26_Clank_Future%3A_A_Crack_in_Time
* **Do NOT enable any emulator game patches when reporting issues** ok
* Only change settings that are required for the game to work 

#### 1. Please attach RPCS3's log.
* [RPCS3.log](https://github.com/RPCS3/rpcs3/files/8749045/RPCS3.log)

#### 2. If you describe graphical issue, please provide an RSX capture and a RenderDoc capture that demonstrate it.
not graphical

#### 3. Please attach screenshots of your problem.
* Enable performance overlay with at least medium level of detail.
You can find it in _Emulator_ tab in _Settings_.
![image](https://user-images.githubusercontent.com/26593485/169685401-1f0f75d3-3269-4447-bdb6-d924af09383e.png)

#### 4. Please provide comparison with real PS3.
looks the same.

#### 5. Please provide your system configuration:
* OS Fedora 36
* CPU Ryzen 2400g
* GPU Radeon R9 Fury X
* Driver version MESA 23.0.0 (ACO)
* etc.

#### Please include.
* Anything else you deem to be important

**Comment by brunoczim** [comment] 2022-05-24 22:15
I am having the same problem, except disabling Anti-Aliasing does not solve for me.

**Comment by K1ngfish3r** [comment] 2022-05-25 09:39
> I am having the same problem, except disabling Anti-Aliasing does not solve for me.

May i see your log file please?

**Comment by jr1991-g** [comment] 2022-05-25 17:14
Top Spin 4 suffers from this aswell. This bug was introduced after #12020. It happens in Ubuntu and Windows, latest mesa and 22.5.1/2
![Captura de pantalla de 2022-05-25 14-10-54](https://user-images.githubusercontent.com/75588345/170321997-edcc137b-7b13-40cc-91c2-f13c5d4c2879.png)

**Comment by kd-11** [comment] 2022-05-25 17:33
> Top Spin 4 suffers from this aswell. This bug was introduced after #12020. It happens in Ubuntu and Windows, latest mesa and 22.5.1/2 ![Captura de pantalla de 2022-05-25 14-10-54](https://user-images.githubusercontent.com/75588345/170321997-edcc137b-7b13-40cc-91c2-f13c5d4c2879.png)

The original PR had some deadlock problems that have since been resolved. Are you running the current master head? I am unable to reproduce this with the current code, but I can easily reproduce with the original PR code.

**Comment by jr1991-g** [comment] 2022-05-25 18:02
> > Top Spin 4 suffers from this aswell. This bug was introduced after #12020. It happens in Ubuntu and Windows, latest mesa and 22.5.1/2 ![Captura de pantalla de 2022-05-25 14-10-54](https://user-images.githubusercontent.com/75588345/170321997-edcc137b-7b13-40cc-91c2-f13c5d4c2879.png)
> 
> The original PR had some deadlock problems that have since been resolved. Are you running the current master head? I am unable to reproduce this with the current code, but I can easily reproduce with the original PR code.
![Captura de pantalla de 2022-05-25 15-00-52](https://user-images.githubusercontent.com/75588345/170332331-c9cbcc72-771e-4ab0-acad-ebf309ff1e4b.png)


Yes I'm. I thought it was the flatpak version but I just tested it on the latest appimage and it does the same.

**Comment by kd-11** [comment] 2022-05-25 18:31
May be a linux thing, I'll investigate later.

**Comment by gamrXerus** [comment] 2022-06-05 14:07
I can confirm this issue happens to me as well. Need for Speed Carbon and Mortal Kombat Komplete Edition crash with Anti Aliasing enabled on Lubuntu 22.04 with oibaf ppa. Using the latest AppImage.

**Comment by kd-11** [comment] 2022-06-08 19:05
Should be fixed by https://github.com/RPCS3/rpcs3/pull/12200

**Comment by gamrXerus** [comment] 2022-06-08 21:11
@kd-11 I can confirm that PR #12200 fixed the issue for me. Thank you.

**Comment by jr1991-g** [comment] 2022-06-08 22:09
Confirmed fixed. Also fixes #12191

**Closed** 2022-06-08 23:13 UTC
Labels: RSX, OS: Linux, Driver: RADV (Mesa)
