### ISSUE TITLE
MGS3 HD visual glitch in the ending cutscene

### ISSUE THREAD

**Issue by ivanproff** [RPCS3/rpcs3#13556] opened 2023-03-16 17:41 UTC
### Quick summary

MGS3 HD visual glitch in the ending cutscene

### Attach a log file

[RPCS3.log.gz](https://github.com/RPCS3/rpcs3/files/10993883/RPCS3.log.gz)

### Attach capture files for visual issues

![Metal Gear Solid 3_ Snake Eater HD Remastered (PS3 4k) Longplay Walkthrough Full Gameplay 8-46-50 screenshot](https://user-images.githubusercontent.com/19212996/225703611-8b41a956-cf62-406d-a5b0-78b1341ea725.png)
https://drive.google.com/file/d/1PWeZsjbYxR7w-KVrdjZJJLc5L1HxbK59/view?usp=share_link

### System configuration

Intel Core i7-13700KF
Nvidia RTX 3080
32gb RAM
Win10 Pro

**Comment by Jonathan44062** [comment] 2023-03-16 18:04
Replicated of https://github.com/RPCS3/rpcs3/issues/10657

**Comment by MSuih** [comment] 2023-03-16 18:04
Duplicate of https://github.com/RPCS3/rpcs3/issues/10657

**Closed by MSuih** 2023-03-16 18:04 UTC
