### ISSUE TITLE
Gran Turismo 6 , GT5 Prologue and Gran Turismo 5 track is not rendering 

### ISSUE THREAD

**Issue by Scrembu** [RPCS3/rpcs3#15416] opened 2024-04-07 15:40 UTC
### Quick summary

in gt5 prologue the map renders like 5 to 10 meters. in gt6 it doesnt render at all and gt5 same

### Details

in gt5 prologue the map renders like 5 to 10 meters. in gt6 it doesnt render and gt5 same in gt6 and gt5 the track doesnt render at all. in gt5 prologue it rendered fully at first and then broke fully but the track still rendered but like 5 meters infront of the car a screenshot is attached. What i think is its caused by spu . I will still attach a log file incase the issue is present but i think it isnt there. I will try to include a RSX capture as well. ... RSX and Log file i didnt attach but if needed much ill attach it because the game kept crashing afterwards and i couldnt get it to launch.

### Attach a log file

[RPCS3.log](https://github.com/RPCS3/rpcs3/files/14897773/RPCS3.log)
This one above is of a crash that occurred on default settings.
Below are ones of the rendering issues. (UPDATED)
[RPCS3.log](https://github.com/RPCS3/rpcs3/files/14897866/RPCS3.log)
[RPCS3.log.gz](https://github.com/RPCS3/rpcs3/files/14897867/RPCS3.log.gz)

### Attach capture files for visual issues (UPDATED)

Google Drive Link.

https://drive.google.com/file/d/1Ls2swGUGDXMVAn09pWDbgC-3jjsSPbFi/view?usp=sharing

### System configuration

I5 6300u
Intel HD 520
8 GB DDR4 2133 mhz

### Other details

https://www.youtube.com/watch?v=P-7pBz20Rv8 

just watch this video because its exactly like that except his rendered at first and he was on a ps3 and im on rpcs3 and mine doesnt render at all even from start 

(UPDATED)

<img width="960" alt="render issues" src="https://github.com/RPCS3/rpcs3/assets/104835833/0fff2c2a-ea22-4294-a7ec-eff49a51bce1">
<img width="960" alt="renderissues2" src="https://github.com/RPCS3/rpcs3/assets/104835833/c87a17cc-885c-4cf4-84fa-f9fe5322d16c">
<img width="960" alt="renderissues3" src="https://github.com/RPCS3/rpcs3/assets/104835833/669b2c03-83f9-4a2b-b598-82fea1c564d1">
<img width="960" alt="renderissues4" src="https://github.com/RPCS3/rpcs3/assets/104835833/a4732b03-eeda-4a96-af3c-e24fa52b8e4b">

**Comment by AniLeo** [comment] 2024-04-07 15:43
Shitty Intel drivers are unsupported, I'd say this is a won't fix due to the used drivers but I'll wait for @kd-11 to decide

**Comment by Scrembu** [comment] 2024-04-07 15:58
i dont think its the drivers tho btw please see it again i edited and added new log files and rsx capture

**Comment by AniLeo** [comment] 2024-04-07 16:26
Any basis for that? Did you test on an NVIDIA or AMD GPU with proper drivers? Looks very much like a driver issue.

**Comment by Scrembu** [comment] 2024-04-07 16:27
I dont have a pc YET that has a nvidia or amd gpu my dad has a amd machine but its a radeon hd 4250 which doesnt have vulkan or ogl

**Comment by Scrembu** [comment] 2024-04-07 16:28
I am planning to buy a I5 9500 next month which i think should be enough for this emulator. But for now i want to get rid of the texture issues. fyi gran turismo hd concept works just fine no render issues and same map as the pics

**Comment by Scrembu** [comment] 2024-04-07 16:29
im current installing a newer intel driver. Maybe it works? maybe not

**Comment by FlexBy420** [comment] 2024-04-07 16:29
9500 is a terrible value to buy in 2024, and it doesn't even meet recommended specs for RPCS3. You will be better off saving a bit more and get at least 12gen PC

**Comment by Scrembu** [comment] 2024-04-07 16:38
- RSX: Found Vulkan-compatible GPU: 'Intel(R) HD Graphics 520' running on driver 0.404.67
E RSX: Your GPU does not support depth bounds testing. Graphics may not render correctly.
E RSX: INTEL driver does not support passthrough DMA buffers

this is what i found maybe this is the reason of the track not rendering?

Also 9500 is just a thing i chose i can upgrade upto a 9700 i7 or a 10th gen if i have my budget but if not ill have to stay with 9500 . also it isnt that bad it is still above the minimum requirements for rpcs3 and way better than what im trying to emulate with right now. Considering im not building the pc for only rpcs3 i think it is alright for now. It will run games at 30 fps atleast when paired with a gtx 1080 ti (which is what im aiming to buy as a gpu) , its just my assumption it might be better or worse. But for sure its going to be better than my current cpu

**Comment by Scrembu** [comment] 2024-04-07 16:57
New Discovery . 
[RPCS3.log](https://github.com/RPCS3/rpcs3/files/14898099/RPCS3.log)
[RPCS3.log.gz](https://github.com/RPCS3/rpcs3/files/14898101/RPCS3.log.gz)
Log Files Incase
Pics Looks like it tried to load the track full at first but then failed and in the 1st pic you can see half of the car is covered with what looks like a weird blob of void
<img width="960" alt="car half gone" src="https://github.com/RPCS3/rpcs3/assets/104835833/7359b753-fae4-4207-b667-0692cb7703b1">
<img width="960" alt="tryigntoload2" src="https://github.com/RPCS3/rpcs3/assets/104835833/723e87a8-2b00-4b73-a6da-24a0f4296370">
<img width="960" alt="tryingtoload1" src="https://github.com/RPCS3/rpcs3/assets/104835833/2ca84736-a720-4b2f-8657-d5afd91d39db">
<img width="934" alt="void" src="https://github.com/RPCS3/rpcs3/assets/104835833/8f928283-3a0a-4ebd-b049-06eeb56f6fa1">

**Comment by kd-11** [comment] 2024-04-07 17:15
This is likely caused by missing depth-bounds support. Try enabling strict rendering and see if it does anything. Keep everything else at default.
Intel drivers before Arc (and tbh even with Arc) have always been terrible. They're just now trying to improve this after 20+ years of subpar software.

**Comment by Scrembu** [comment] 2024-04-07 17:19
alright

**Comment by Scrembu** [comment] 2024-04-07 17:25
> This is likely caused by missing depth-bounds support. Try enabling strict rendering and see if it does anything. Keep everything else at default. Intel drivers before Arc (and tbh even with Arc) have always been terrible. They're just now trying to improve this after 20+ years of subpar software.

I just did what you said the strict rendering but it didnt do anything . Im starting to give up. If theres any final things to try ill be happy to try them if not then i give up. And yea i do think its driver as well.

**Comment by Scrembu** [comment] 2024-04-07 17:26
When i try open GL the game just crashes

**Comment by AniLeo** [comment] 2024-04-07 17:36
Closing as a driver issue, won't fix.

**Closed by AniLeo** 2024-04-07 17:36 UTC
