### ISSUE TITLE
Castlevania Lords of Shadow 1 & 2

### ISSUE THREAD

**Issue by JamieeLee** [RPCS3/rpcs3#4094] opened 2018-01-21 09:53 UTC
Latest build of RPCS3, 
       Issue 1, Lords of shadow 1 wont read input once at press start , even though you can hit any button to bypass the intro video.
 Issue 2 ,  Lords of Shadow 2 you can bypass video you can get into menu to the book, but wont read input after the book opens and you need to select brightness, slider works input for x does not.. 

![2018-01-21 1](https://user-images.githubusercontent.com/1132278/35198526-04f315f6-fea5-11e7-9a25-758e2f70468d.png)
![2018-01-21](https://user-images.githubusercontent.com/1132278/35198527-050cfffc-fea5-11e7-8c67-8bb8c4e6f3a3.png)

![2018-01-21 2](https://user-images.githubusercontent.com/1132278/35198566-8f0ab4e2-fea5-11e7-9e3b-adfced17fe7f.png)
![2018-01-21 3](https://user-images.githubusercontent.com/1132278/35198567-8f2179c0-fea5-11e7-9da4-8ca303c93942.png)

Updated with pictures as it was 3 am was tired when I was writing this sorry for that. 

log to LOS 1
[RPCS3.log](https://github.com/RPCS3/rpcs3/files/1650279/RPCS3.log)

log to LOS 2
[RPCS3.log](https://github.com/RPCS3/rpcs3/files/1650281/RPCS3.log)

**Comment by Asinin3** [comment] 2018-01-21 09:56
LOS2 works perfectly for me i finished a 5hour play session half an hour ago. haven't tried LOS1 yet.

**Comment by JamieeLee** [comment] 2018-01-21 10:06
There is no error in the log, and the fact it reads any input before that point.....

**Comment by elad335** [comment] 2018-01-21 10:08
Yeah something is broken for sure

**Comment by Asinin3** [comment] 2018-01-21 13:21
It works for me on multiple ID's, i even checked LOS1. All tested today with the latest build.

LOS2 Demo:
![rpcs3_2018-01-21_14-22-51](https://user-images.githubusercontent.com/15137035/35194586-c666491e-ff05-11e7-9676-e4cd81d7730a.jpg)

LOS2 PSN:
![rpcs3_2018-01-21_15-55-51](https://user-images.githubusercontent.com/15137035/35194582-b718a6fa-ff05-11e7-9616-321040afbdf5.jpg)

LOS2 Disc:
![rpcs3_2018-01-21_22-03-18](https://user-images.githubusercontent.com/15137035/35194581-b0833f6c-ff05-11e7-9dfc-ccfa27c56d66.jpg)

LOS Disc:
![image](https://user-images.githubusercontent.com/15137035/35194593-d917ad8c-ff05-11e7-9c1e-e44fca94e2ca.png)

**Comment by spyropt** [comment] 2018-01-21 18:35
LOS2 Works perfectly for me

**Comment by Megamouse** [comment] 2018-01-21 18:37
you didn't even provide logs or a concrete version number. so this issue is kinda invalid

**Comment by Zangetsu38** [comment] 2018-01-21 20:21
for me, first game is complettely glitched, with ogl and vulkan, instable, blur etc, for 2 is good

**Comment by JamieeLee** [comment] 2018-01-21 20:22
There updated with pictures....

**Comment by Asinin3** [comment] 2018-01-21 21:21
but still no log. The issue is most likely from your input configuration or the rip itself

**Comment by AniLeo** [comment] 2018-01-29 20:20
The game is working, if you're having specific issues to hardware you must submit a proper report with enough debug information.
Just saying the game isn't working isn't a valid issue. Use the forums for compatibility reports.

---

**Please read [**the guidelines**](https://github.com/RPCS3/rpcs3/blob/master/CONTRIBUTING.md) before opening an issue.**

Remember that the GitHub Issue Tracker is not the place to ask for support or to submit Game Compatibility reports. You must use [**our forums**](https://forums.rpcs3.net/forum-18.html) for that.

The issue has been marked as **Invalid** and closed.

**Closed by AniLeo** 2018-01-29 20:20 UTC
