### ISSUE TITLE
No games booting after new update

### ISSUE THREAD

**Issue by GalaxisBeast** [RPCS3/rpcs3#13944] opened 2023-06-03 13:55 UTC
### Quick summary

None of my games will boot after updating to version 0.0.28-15112
The games are Rock Band 2, Rock Band 3 and The Beatles: Rock Band.

### Details

When I try to launch a game, it just crashes the entire emulator. I have tried making sure I had no invalid configuration settings and nothing changed

### Attach a log file

[RPCS3.log](https://github.com/RPCS3/rpcs3/files/11642918/RPCS3.log)

**Comment by AniLeo** [comment] 2023-06-04 14:35
Log hints to game corruption, other people with these games need to try

**Comment by AniLeo** [comment] 2023-06-11 15:50
You can alternatively verify your game dumps and post the output from the verification tool

Otherwise this issue will be closed for inactivity + lack of reproducibility since no one else can reproduce this issue at all

**Comment by mark952231** [comment] 2023-06-14 05:13
Me too!
None of my games will boot after updating to version 0.0.28 and new version
When I try to launch a game,Simulator shuts down immediately

**Comment by AniLeo** [comment] 2023-06-24 15:12
Closing due to the lack of information, plus no one else can reproduce this

**Closed by AniLeo** 2023-06-24 15:12 UTC
Labels: Need Information
