### ISSUE TITLE
Demons Souls BLUS30443 Has Stopped Working After Power Outage...

### ISSUE THREAD

**Issue by TheMadHatta** [RPCS3/rpcs3#10137] opened 2021-04-18 01:42 UTC
Hey guys, wasn't sure if this fit here but didn't know where else to ask for help regarding this issue.
I was playing demons souls on rpcs3 a while ago when the power went out on me, I believe I was able to boot my computer back up and get back into the game, but then the power went out again. Not sure if the game was autosaving but I don't think it was.
Now, when I try to boot up the game I can get the game to the point where I hit the autosave warning screen and press ok, and then it starts checking the trophy set and hangs.

When I check the log these are the last 3 lines of text:

S {RSX.W3} RSX: Program compiled successfully
E {PPU[0x100001d] Thread (DsTrophyMan::AsyncUpdateThr) [HLE:0x01d300d4, LR:0x0005f474]} sceNpTrophy: sceNpTrophyRegisterContext(context=0x1, handle=0x1, statusCb=*0x191a630, arg=*0x301e2ef4, options=0x0)
F {PPU[0x1000019] Thread (SLSession) [HLE:0x01d30794, LR:0x00eb3ab0]} SIG: Thread terminated due to fatal error: Verification failed
(in file D:\a\1\s\rpcs3\Loader\PSF.cpp:123[:3], in function load_object)

I've tried reinstalling rpcs3 fresh and manually moving my save files and I still get the same problem. I then tried removing my save game files for demons souls and now the game launches fine.
However, I had a lot of work in my saves and id probably stop playing the game if I can't recover my saves. Does anyone know if it's possible to recover this save or get it working again?

- Thanks for your time <3

**Comment by dio-gh** [comment] 2021-04-18 02:04
This sounds more like a support request than an issue with RPCS3 tbh, you'll need to find some savegame editor and recreate a new savefile with it somehow, since it most probably got corrupted.

I don't think the PS3 makes any further IO guarantees than a regular PC does, and the game probably just wasn't prepared for such a scenario. It's an issue with the game, really.

**Comment by elad335** [comment] 2021-04-18 03:26
It's fixed in latest master.

**Comment by TheMadHatta** [comment] 2021-04-18 03:31
> This sounds more like a support request than an issue with RPCS3 tbh, you'll need to find some savegame editor and recreate a new savefile with it somehow, since it most probably got corrupted.
> 
> I don't think the PS3 makes any better IO guarantees than a regular PC does, and the game probably just wasn't prepared for such a scenario. It's an issue with the game, really.

Yeah i figured as such, if its a support request is there a better place for me to post about this issue if i wanna continue to try and fix the save? I had no idea save game editors even existed for this game. Any chance u can point me in the right direction for posting about this issue and to find save game editor stuff? Thanks for your reply man <3



> It's fixed in latest master.

Does that mean i can update my rpcs3 and attempt to load my save again? Or what do you mean by fixed, like it wouldnt happen again? My main concern is trying to get back to playing my temple knight faith build i was half way through finishing >< starting over is not something i wanna have to do unless i pick the game back up years later or however long it takes me :P
Also thanks for the reply <3

**Comment by dio-gh** [comment] 2021-04-18 03:48
> It's fixed in latest master. @elad335 

What is? Is this the DeS regression people been talking about and OP just didn't mention that he updated RPCS3 inbetween his attempts?

**Comment by elad335** [comment] 2021-04-18 03:51
@TheMadHatta It wouldn't crash but your save is probably lost, you should latest rpcs3 in order yo precent corrupted saves as well.

**Comment by TheMadHatta** [comment] 2021-04-18 04:06
Alright guys thanks for the help, was hoping it wasnt basically lost but if it is thats too bad ><
Btw i dont think i updated rpcs3 i had the crash, tried the save, no luck, reinstalled with same update iirc, and no luck, then i updated at some point later down the road i believe, but havent been using rpcs3 since des is the only game i was playing on rpcs3. I will definitely be updating next time i launch rpcs3.

**Comment by elad335** [comment] 2021-04-19 04:41
Close issue?

**Closed** 2021-04-19 04:52 UTC
