### ISSUE TITLE
Kingdom Hearts 2 FM (Via 2.5) Twilight Town Sun renders on top 

### ISSUE THREAD

**Issue by Magnymbus** [RPCS3/rpcs3#8668] opened 2020-08-02 04:04 UTC
The sun in Twilight Town renders on top of buildings and other landscape objects rather than being properly occluded.

![Screenie](https://user-images.githubusercontent.com/14867244/89114900-6b364100-d43e-11ea-966b-3671ccfbd4f5.jpg)

* OS: Windows 10
* CPU: AMD Ryzen 5 2600 6-Core, 12 threads
* GPU: GeForce RTX 2060
* Driver version: 26.21.14.4614
* Renderer: Vulkan
* Memory: 31.95
* RPCS3 Version: 0.0.11-10715

[RPCS3 log](https://github.com/RPCS3/rpcs3/files/5011594/RPCS3.log)
[RSX Cap](https://github.com/RPCS3/rpcs3/files/5011604/BLES02070_20200801212650_capture.zip)
[RD Frame Cap](https://mega.nz/file/pF4TkRAD#7YJWq-v2DHS2lgt3nDC6BN6lvZu37FhlL-wL6-jwojs)

**Comment by Asinin3** [comment] 2020-08-02 04:16
Quite sure this is the normal vulkan zcull issue. Affected a lot of games, was originally fixed y Confirmed with Magnymbus it's fine on OpenGL. Originally fixed by https://github.com/RPCS3/rpcs3/pull/3827 but there has been regressions with it since then.

**Comment by HotDogger** [comment] 2020-08-09 14:20
If needed, i've found that first version with this regression is 0.0.10-10560, on 0.0.10-10542 there is no issue with Vulkan backend.

**Comment by kd-11** [comment] 2020-10-18 15:56
This should be fixed now. Please retest.

**Comment by jeremybris** [comment] 2020-10-19 23:21
I still get this.

**Comment by MarioSonic2987** [comment] 2020-11-29 09:48
This regression was caused by PR #8479.

**Comment by kd-11** [comment] 2020-11-29 17:00
Blocked by https://github.com/RPCS3/rpcs3/issues/9352. In the meantime, please provide a save so I can reproduce without using RSX captures.

**Comment by MarioSonic2987** [comment] 2020-11-29 17:12
@kd-11 It's the fourth savedata. Then, skip the next cutscene. And rotate the camera to the left.

[Savegame](https://github.com/RPCS3/rpcs3/files/5612512/BLES02070-BISLPM66675FM.zip)

**Comment by kd-11** [comment] 2020-11-29 18:28
Should be fixed by https://github.com/RPCS3/rpcs3/pull/9354

**Closed** 2020-11-29 21:46 UTC
Labels: Regression, Render: Vulkan
