### ISSUE TITLE
[BLUS30380] Ninja Gaiden Sigma 2 - Broken Rainbow Textures/Graphics

### ISSUE THREAD

**Issue by Anon34829** [RPCS3/rpcs3#11235] opened 2021-12-06 20:37 UTC
Tried almost every settings ( I think) but the game still have broken rainbow texture when the character attacks.

Inside: video obs
Renderdoc
rpcs3 log

https://mega.nz/file/NMY0QBjD#9X8PwlxjEN-_WDUTQZNHBnrTwboVRyNe_bWP1lsG014

OS Name	Microsoft Windows 10 Home	
Version	10.0.19044 Build 19044	
Other OS Description 	Not Available	
OS Manufacturer	Microsoft Corporation	
System Manufacturer	ASUS	
System Model	System Product Name	
System Type	x64-based PC	
System SKU	SKU	
Processor	AMD Ryzen 5 5600X 6-Core Processor, 3701 Mhz, 6 Core(s), 12 Logical Processor(s)	
BaseBoard Product	TUF GAMING B550-PLUS	
BaseBoard Version	Rev X.0x	
Platform Role	Desktop	
Secure Boot State	Off	
NVIDIA GTX 980 
Nvidia 497.09
Installed Physical Memory (RAM)	32.0 GB

**Comment by Megamouse** [comment] 2021-12-06 21:18
same here:
![image](https://user-images.githubusercontent.com/23019877/144924121-11e3519c-e22b-4b5d-ad37-a18da299c1e8.png)

**Comment by Megamouse** [comment] 2021-12-06 21:54
Regression caused by #10938

**Comment by Megamouse** [comment] 2021-12-06 22:05
Broken with Vulkan and OpenGl

**Comment by kd-11** [comment] 2021-12-07 20:16
Should be fixed by https://github.com/RPCS3/rpcs3/pull/11242

**Closed** 2021-12-08 20:58 UTC
Labels: RSX, Regression
