### ISSUE TITLE
RPCS3 Won't launch fresh download

### ISSUE THREAD

**Issue by Zheafer** [RPCS3/rpcs3#14575] opened 2023-08-29 03:28 UTC
### Quick summary

I had just downloaded RPCS3 on my MacBook along with PS3 firmware as per the websites instructions. Yet every attempt at launch is met with the "RPCS3 quit unexpectedly" error. Ive tried searching everywhere for why the problem occurs and I think I've found the possible reason but lack the knowledge on how to fix the issue. Also apologies if this is the wrong place I'm new to forums and have never posted on one before.

### Details

-------------------------------------
Translated Report (Full Report Below)
-------------------------------------

Process:               rpcs3 [2197]
Path:                  /Applications/RPCS3.app/Contents/MacOS/rpcs3
Identifier:            net.rpcs3.rpcs3
Version:                ()
Code Type:             X86-64 (Translated)
Parent Process:        launchd [1]
User ID:               501

Date/Time:             2023-08-28 20:11:39.8546 -0700
OS Version:            macOS 13.5.1 (22G90)
Report Version:        12
Anonymous UUID:        2E0C8740-C267-BF01-A8DF-4E040738C848

Time Awake Since Boot: 480 seconds

System Integrity Protection: enabled

Crashed Thread:        0

Exception Type:        EXC_CRASH (SIGABRT)
Exception Codes:       0x0000000000000000, 0x0000000000000000

Termination Reason:    Namespace DYLD, Code 1 Library missing
Library not loaded: @loader_path/../../../../opt/libvpx/lib/libvpx.8.dylib
Referenced from: <0E60638F-B9DA-3CB7-ABCC-E8B0B55FCD0D> /Applications/RPCS3.app/Contents/Frameworks/libavcodec.60.dylib
Reason: tried: '/Applications/RPCS3.app/Contents/Frameworks/../../../../opt/libvpx/lib/libvpx.8.dylib' (no such file), '/usr/local/lib/libvpx.8.dylib' (no such file), '/usr/lib/libvpx.8.dylib' (no such file, not in dyld cache)Library not loaded: @loader_path/../../../../opt/libbluray/lib/libbluray.2.dylib
Referenced from: <75FABDBA-7243-3871-A022-1253ADA086B7> /Applications/RPCS3.app/Contents/Frameworks/libavformat.60.dylib
Reason: tried: '/Applications/RPCS3.app/Contents/Frameworks/../../../../opt/libbluray/lib/libbluray.2.dylib' (no such file), '/usr/local/lib/libbluray.2.dylib' (no such file), '/usr/lib/libbluray.2.dylib' (no such file, not in dyld cache)Library not loaded: @loader_path/../../../../opt/libx11/lib/libX11.6.dylib
Referenced from: <6DBC22E7-450B-3C70-9F8A-C72FC2673597> /Applications/RPCS3.a
(terminated at launch; ignore backtrace)

### Attach a log file

Can't obtain

### System configuration

Apple M1 Pro Chip
16GB Memory
MacOS Ventura 13.5.1

### Other details

Like I previously mentioned I'm new to forums and also don't have much knowledge in regards to actual software nowadays any help would be greatly appreciated.

**Comment by FlexBy420** [comment] 2023-08-29 03:29
Duplicate of #14532

**Comment by Zheafer** [comment] 2023-08-29 03:32
> Duplicate of #14532

My bad not trying to spam anything was just relaying my problem.

**Comment by Zheafer** [comment] 2023-08-29 03:39
Problem fix here 
https://api.cirrus-ci.com/v1/artifact/task/4521499416068096/Artifact/artifacts/rpcs3-v0.0.29-15551-2073675d_macos.dmg

**Closed** 2023-08-29 05:54 UTC
