### ISSUE TITLE
RPCS3 crashes on macOS after stopping any game

### ISSUE THREAD

**Issue by n-batalha** [RPCS3/rpcs3#15254] opened 2024-02-27 21:36 UTC
### Quick summary

Stopping any game emulation on macOS will result in RPCS3 segfaulting

### Details

See video. Any game I tried leads to this. Closing the game window rather explicitly stopping the emulation (as in the video) results in the same.

https://github.com/RPCS3/rpcs3/assets/2240845/47988770-be15-4174-afaa-1acdd686563c

### Attach a log file

[RPCS3.log.zip](https://github.com/RPCS3/rpcs3/files/14426019/RPCS3.log.zip)

### System configuration

* RPCS3 v0.0.30-16148-f64d6bc6 Alpha | HEAD
* macOS, Version: 14.3.1
* Apple M1 Pro running on driver 0.2.991
* Firmware version: 4.89

### Other details

This is with the latest version of macOS and RPCS3 but has been happening in all versions I tried before too.

**Comment by AniLeo** [comment] 2024-02-27 21:45
Duplicate of #14760

**Closed by AniLeo** 2024-02-27 21:45 UTC
