### ISSUE TITLE
Arch: build fails

### ISSUE THREAD

**Issue by whbdupree** [RPCS3/rpcs3#1802] opened 2016-06-19 16:37 UTC
$ make
[  0%] Generating something_that_never_exists
-- Found Git: /usr/bin/git (found version "2.8.3") 
-- GIT_VERSION: 4474-ff0bb52
[  0%] Built target GitVersion
[  0%] Building CXX object CMakeFiles/rpcs3.dir/Emu/Cell/SPUASMJITRecompiler.cpp.o
In file included from /home/barnett/sw/rpcs3/rpcs3/Emu/Cell/SPUASMJITRecompiler.cpp:6:0:
/home/barnett/sw/rpcs3/rpcs3/Emu/Cell/SPUThread.h:379:31: warning: ignoring attributes on template argument ‘__m128 {aka __vector(4) float}’ [-Wignored-attributes]
   std::array<__m128, 155 + 174> m_data;
                               ^
c++: internal compiler error: Segmentation fault (program cc1plus)

**Comment by GhettoGirl** [comment] 2016-06-19 16:51
You must use GCC 5.4 or lower to compile RPCS3.
See this regression bug: https://gcc.gnu.org/bugzilla/show_bug.cgi?id=70869

Download GCC 5.4 source code and than happy compiling I guess ^^
Don't forget to set the install prefix of GCC to something like ```/opt/gcc``` or something.

You should close this bug since it has nothing todo with RPCS3.
Regards.

**Comment by GhettoGirl** [comment] 2016-06-20 02:48
Maybe someone of the project members should update the ```README.md```, until this bug is fixed in GCC. But even than, most people may still use GCC 6.1 after 6.2 is released, so they know that they are wasting their time when trying to build RPCS3 with GCC 6.1

Even after such an obvious line like ```c++: internal compiler error: Segmentation fault (program cc1plus)``` many people think (for some reason) this is a problem of the project, rather than the compiler itself. Just saying.

Here are my suggestions
```md
* GCC 5.1 ~ 5.4 (6.1 doesn't work) or Clang 3.5.0+
* GCC 5.1 ~ 5.4 or Clang 3.5.0+
* GCC 5.1+ (not 6.1) or Clang 3.5.0+
* GCC 5.1+ (but not 6.1) or Clang 3.5.0+
```

**Comment by GhettoGirl** [comment] 2016-06-20 03:01
Here is a test program
```c++
#include<initializer_list>

struct A
{
  void f(){}
  void f2(){}
};

int main(void){
  for(const auto& m: {&A::f,&A::f2}){
    A a;
    (a.*m)();
  }
}
```

```bash
$ g++ gcc61cannotcompilethis.cxx
g++: internal compiler error: Segmentation fault (program cc1plus)
Please submit a full bug report,
with preprocessed source if appropriate.
See <https://gcc.gnu.org/bugzilla/> for instructions.
$ /opt/gnu/gcc/5.4.0/bin/g++ -std=c++11 gcc61failsatthis.cxx
(compiles fine)
```

**Comment by GhettoGirl** [comment] 2016-06-30 16:10
I opened a PR to add better compiler checks, which should avoid such useless issues like this one in the future.

**Comment by Enverex** [comment] 2016-07-01 10:04
Has this been resolved? I'm seeing compilation reach 44% now with GCC 6.1.1 (before failing with another issue related to SPUOpcodes.h).

**Comment by vadixidav** [comment] 2016-07-07 10:21
@Enverex 

You can make it compile on GCC 6.1 by replacing that file with this one I made that builds on it: https://gist.github.com/vadixidav/f9f3f696448f3562f006ae3d0154f9ac

I seem to be getting a problem with git-version.h after I do that though on Arch Linux, so I am investigating to see if that can be resolved.

**Comment by vadixidav** [comment] 2016-07-08 03:20
Yeah, I couldn't fix the git-version.h thing, so I'm giving up building for now on Arch.

**Comment by GhettoGirl** [comment] 2016-07-08 08:48
@vadixidav 

The ```git-version.h``` is generated when executing ```cmake```, if this file isn't generated than there is usally a problem either with ```git``` or with your version of ```cmake```. In case you are interested this is the content of the file:
```c++
// This is a generated file.

#define RPCS3_GIT_VERSION "4536-0dc00b8"

// If you don't want this file to update/recompile, change to 1.
#define RPCS3_GIT_VERSION_NO_UPDATE 0
```

Place it here inside the repository root: ```rpcs3/git-version.h```

--

This is my version of git and cmake
```
cmake version 3.5.2
git version 2.9.0
```

**Comment by vadixidav** [comment] 2016-07-09 06:30
@GhettoGirl Sadly, I now have linker errors with the YAML library. I think I'll just have to give it a rest for now.

**Comment by GhettoGirl** [comment] 2016-07-09 12:30
@vadixidav I don't know what are you doing here, but make sure you build and link against the builtin version of yaml-cpp and not the shared one, which shouldn't actually happen, when you didn't modify the cmake files.

I recommend to use the cmake file from the repository root and not from from the rpcs3 subdirectory.

**Closed** 2016-07-10 08:15 UTC
Labels: linux
