### ISSUE TITLE
Ratchet & Clank: A Crack in Time particles get progressively more broken

### ISSUE THREAD

**Issue by JimScript** [RPCS3/rpcs3#11205] opened 2021-11-27 18:38 UTC
Starting with A Crack in Time, every ratchet and clank game has used particles fixed by #10637, but if too many of the effects are overlapped or in memory it will break. It often manifests as white boxes, but it can get to the point where you can see ghosting.
![BCUS98124_screenshot_2021_11_27_10_05_05](https://user-images.githubusercontent.com/66685584/143708919-ee53058b-60b3-4979-9346-ea980ef9540d.png)
RSX Capture:
[BCUS98124_20211127100521_capture.zip](https://github.com/RPCS3/rpcs3/files/7612254/BCUS98124_20211127100521_capture.zip)

System:
- SYS: RPCS3 v0.0.19-13055-44fe6f6d Alpha | HEAD
- SYS: AMD Ryzen 5 3600 6-Core Processor | 12 Threads | 15.95 GiB RAM | TSC: 3.600GHz | AVX+ | FMA3
- SYS: Operating system: Windows, Major: 10, Minor: 0, Build: 19043, Service Pack: none, Compatibility mode: 0
- RSX: Found vulkan-compatible GPU: 'NVIDIA GeForce RTX 2070 SUPER' running on driver 471.68.0.0
- SYS: Firmware version: 4.85

**Comment by dragonDScript** [comment] 2021-11-27 18:41
Can you reproduce this with the latest RPCS3 update? Seems like they fixed this

**Comment by JimScript** [comment] 2021-11-27 18:48
By latest update do you mean #11204?
![BCUS98124_screenshot_2021_11_27_10_45_24](https://user-images.githubusercontent.com/66685584/143718594-9fb21b5a-26f8-4d93-bb05-27e64e4b343c.png)
Because it is still broken there, but if you are talking about something else please tell me.

**Comment by Xcedf** [comment] 2021-11-27 19:01
@JimScript did you try Read Color Buffers?
I have this in QForce
![15](https://user-images.githubusercontent.com/7060586/143718924-39c5f371-13b0-492b-83da-2d7e40b64f01.jpg)
fixed by using RCB
![14](https://user-images.githubusercontent.com/7060586/143718995-fcbe9ac5-cd48-4ec0-a3b5-7387242b6895.jpg)

**Comment by JimScript** [comment] 2021-11-27 19:05
I have, and it would be a lot worse if I didn't have it on, but it is still there when things get bad enough.

**Comment by dragonDScript** [comment] 2021-11-27 19:48
+1

**Comment by kd-11** [comment] 2021-12-01 14:09
Known issue, the game basically renders special effects to some offscreen memory but doesn't bother to clean it up first leading to this slow corruption depending on what is being rendered.

**Comment by JimScript** [comment] 2021-12-01 16:33
So how does a real PS3 deal with this issue? Because this issue starts as soon as you touchdown on Torren IV. Do the effects successfully overwrite the old memory so this problem never appears on a ps3?

**Comment by JimScript** [comment] 2021-12-21 06:42
I don't know if this is related as it displays a moving image, but when fighting the Blaze Bot in Into the Nexus, there are screen effects that are offset at times when looking at the Blaze Bot:

https://user-images.githubusercontent.com/66685584/146882120-4cc414c2-325b-4583-851b-9e8006efff0f.mp4


RSX Capture:
[NPUA80908_20211219184024_capture.zip](https://github.com/RPCS3/rpcs3/files/7750118/NPUA80908_20211219184024_capture.zip)

If this is a separate issue I will open it up as one.

**Comment by JimScript** [comment] 2022-01-31 07:57
The above issue is _caused_ by Read Color Buffers, as it turns out. I don't know how much the main issue needs Read Color Buffers to work properly in ITN, but this could be a problem for it as it gets very distracting at points.

**Comment by ScottieD** [comment] 2022-02-15 22:58
This looks like the same issue as #8440

**Comment by kd-11** [comment] 2022-08-05 19:02
Test https://github.com/RPCS3/rpcs3/pull/12469

**Closed** 2022-08-07 19:14 UTC
Labels: Bug
