### ISSUE TITLE
build problems on llvm

### ISSUE THREAD

**Issue by 111111111111111111111111** [RPCS3/rpcs3#1247] opened 2015-10-12 04:26 UTC
the project compiles good apart from one error when compiling rpcs3
It says fatal error can't find asmjit.lib

**Comment by sasukedotca** [comment] 2015-10-12 06:22
already solved here : https://github.com/RPCS3/rpcs3/issues/1234

**Comment by 111111111111111111111111** [comment] 2015-10-12 07:00
Thanks

**Comment by Zangetsu38** [comment] 2015-10-12 09:36
@111111111111111111111111  @sasukedotca fixed here in My PR 
https://github.com/RPCS3/rpcs3/pull/1242

**Comment by Bigpet** [comment] 2015-10-12 10:54
should be fixed, comment if the issue is still present

**Closed by Bigpet** 2015-10-12 10:54 UTC
