### ISSUE TITLE
[NPJB00521] Super Robot War Dark Prison - RSX: struct gsl::fail_fast thrown: GSL: Precondition failure

### ISSUE THREAD

**Issue by QiQiRyan** [RPCS3/rpcs3#5750] opened 2019-03-20 08:22 UTC
OS: Windows 10
Graphics card: Geforce 970 - 419.17
Processor: Intel Core i7- 5820k
version: v0.0.6-7888 [2019-03-20]
default setting rpcs3

This game stuck after intro video .

![NPJB00521](https://user-images.githubusercontent.com/47705932/54669114-22206e00-4b23-11e9-8ad5-e14d66567c70.png)
[RPCS3.log.gz](https://github.com/RPCS3/rpcs3/files/2987083/RPCS3.log.gz)

**Comment by AniLeo** [comment] 2019-03-26 16:13
Duplicate of #5095

**Closed by AniLeo** 2019-03-26 16:13 UTC
