### ISSUE TITLE
Silent Hill Homecoming [BLES-00460] fails when LLVM option enabled.

### ISSUE THREAD

**Issue by isshininu** [RPCS3/rpcs3#4142] opened 2018-02-03 01:54 UTC
Silent Hill Homecoming [BLES-00460] fails when LLVM option enabled.

So it is works only when LLVM recompiler is NOT checked.

F {PPU[0x1000000] Thread (main_thread) [0x00041810]} MEM: Access violation reading location 0x981c0136
[RPCS3.log.gz](https://github.com/RPCS3/rpcs3/files/1691301/RPCS3.log.gz)

**Comment by AniLeo** [comment] 2018-02-03 01:57
Duplicate of #2909

**Closed by AniLeo** 2018-02-03 01:57 UTC
