### ISSUE TITLE
GOW 2 Broken, Pegasus first part, not fully playable.

### ISSUE THREAD

**Issue by nyto0012** [RPCS3/rpcs3#6305] opened 2019-08-05 01:48 UTC
Good morning Rpcs3 team, sorry for bothering you with this nonsense that clearly could be my own incompetence, how the title says I believe  GOW2 is  broken because in this emulator despite being posted as playable, I am having an issue  in a specific part of the game.

well, when I am playing the game everything seem to be  working flawlessly,  nevertheless when I reach certain part the game partially crashes,  this is after beating the big  statue when kratos  return  from a demonic pit with arms everywhere,  kratos speaks with a remaining soldier alive ( this scene does has the sound crashed as well ) and after that scene kratos has to ride a horse with wings but  when kratos goes up the Pegasus the game crash in part, because only the Pegasus crashes, the rest of the game seems to carry on working. 

I know you guys have sth more important to deal with, but could you please check what is happening ?, I have already tested several versions and several different configurations with vulcan and open GL and nothing seem to work, the game always crashes at the same exact place nothing more nothing less.

I am using the  v0.0.6-8442 Alpha [2019-08-04]  but previous versions also are given the same mistake to me.

---my build ----
mainboard asrock B450M pro4 Bios version 3.50
32 gb of ram corsair ballistix 3200mhz
Ryzen 3600 3.6 ghz
evo plus nvme m2 samsung drive 1tb
evga nvidea 1060 6 gb
windows 10 pro x64

below is the log 
[RPCS3.log](https://github.com/RPCS3/rpcs3/files/3465670/RPCS3.log)

savedata below.
[BCUS98229_GOW2.zip](https://github.com/RPCS3/rpcs3/files/3477456/BCUS98229_GOW2.zip)

below are the images that illustrate my problem properly explained with a text.

====================================================
![non crasehd part](https://user-images.githubusercontent.com/53713924/62432487-faaaf600-b6fd-11e9-8710-949ba30466f9.png)

![crashed part](https://user-images.githubusercontent.com/53713924/62432491-00a0d700-b6fe-11e9-9271-bc850d2483e8.png)

I am new at this site so if my post is placed at the wrong place feel free to move it to the correct place, also forgive my English, I am barely a learner ,  if this problem is already posted by sb else and furthermore solved please provide me with the site and I immediately will erese this post , note that I am not lazy I Tried to look for a solution on google on my own but gave up after days of searching with no success .

finally, this could be my hardware that is too recent,t if so, please confirm me this and I shall erase this post .

thanks folk.

**Comment by RainbowCookie32** [comment] 2019-08-05 01:55
The log is a copy paste from RPCS3's window, please attach RPCS3.log from the emulator's folder instead

**Comment by nyto0012** [comment] 2019-08-05 01:58
ok, I will try it and edit it.

**Comment by nyto0012** [comment] 2019-08-05 02:16
> The log is a copy paste from RPCS3's window, please attach RPCS3.log from the emulator's folder instead

I already did it, thank you for answering.

**Comment by EnekoT2001** [comment] 2019-08-06 00:06
So is this a regression? Can anyone confirm?

**Comment by nyto0012** [comment] 2019-08-07 12:52
> So is this a regression? Can anyone confirm?

seem to be pal,  could you tell me in which version is this game playable to download it meanwhile ? since seem to be nobody has sth to offer about this topic,  I will let the thread  open for a while though.

**Comment by nyto0012** [comment] 2019-08-07 12:54
> So is this a regression? Can anyone confirm?
seem to be pal, could you tell me in which RPCS3 version is this game playable to download it meanwhile ? since seem to be nobody has sth to offer about this topic, I will let the thread open for a while though.

**Comment by nyto0012** [comment] 2019-08-07 12:55
> So is this a regression? Can anyone confirm?

seem to be pal, could you tell me in which version is this game playable to download it meanwhile ? since seem to be nobody has sth to offer about this topic, I will let the thread open for a while though.

**Comment by nyto0012** [comment] 2019-08-07 12:56
> So is this a regression? Can anyone confirm?

seem to be pal, could you tell me in which RPCS3 version is this game playable to download it meanwhile ? since seem to be nobody has sth to offer about this topic, I will let the thread open for a while though.

**Comment by HerrHulaHoop** [comment] 2019-08-07 12:59
@nyto0012 please stop commenting, deleting and then recommenting the same message over and over. Every time you do this, you trigger a notification in RPCS3's discord server that has over 40K members in it.

**Comment by nyto0012** [comment] 2019-08-07 13:03
> @nyto0012 please stop commenting, deleting and then recommenting the same message over and over. Every time you do this, you trigger a notification in RPCS3's discord server that has over 40K members in it.

my greatest apologies pal, it was not my intention, I did not know this at all, again sorry, this wont  be repeated again.

**Comment by EnekoT2001** [comment] 2019-08-07 13:49
> > So is this a regression? Can anyone confirm?
> 
> seem to be pal, could you tell me in which RPCS3 version is this game playable to download it meanwhile ? since seem to be nobody has sth to offer about this topic, I will let the thread open for a while though.

Tbh i dont know, try one build from last month and see if that helps, i cant help you, is just trial and error :c good luck btw

**Comment by HerrHulaHoop** [comment] 2019-08-07 14:01
@nyto0012 also, can you share the savefile so we can try to reproduce the issue. It should be located in `\dev_hdd0\home\00000001\savedata\`.

**Comment by nyto0012** [comment] 2019-08-07 14:31
> @nyto0012 also, can you share the savefile so we can try to reproduce the issue. It should be located in `\dev_hdd0\home\00000001\savedata\`.

Done my friend, I have updated my post and included the savedata file,  thanks for helping partner.
a question, do you believe it could be because of my processor Ryzen 3600 is too recent so RPCS3 has not fully support yet ?

whise you luck reproducing the same error so you can fix it, I would fix it myself if I were coder though.

**Comment by nyto0012** [comment] 2019-08-07 14:36
> > > So is this a regression? Can anyone confirm?
> > 
> > 
> > seem to be pal, could you tell me in which RPCS3 version is this game playable to download it meanwhile ? since seem to be nobody has sth to offer about this topic, I will let the thread open for a while though.
> 
> Tbh i dont know, try one build from last month and see if that helps, i cant help you, is just trial and error :c good luck btw

do not wory pal, there is nothing to worry about if you cant...have an astonishing day anyway.

**Comment by kd-11** [comment] 2019-08-13 10:23
Here's my take on this one:
God of war has always had this kind of problem even on a real PS2. It seems to be a problem with the engine. In GOW1 you may go to the pandora's box room and find it missing. In GOW2 there are cases where you can't progress in the titan's cave because the event does not trigger. The reason for this has never been identified. I encountered the missing pandora's box bug and was able to fix it by some luck after messing around with the filesystem for a while, but it was a fluke and I have no idea what actually made it start working again. On PS2 you just had to start a new game.

**Comment by kd-11** [comment] 2019-08-13 10:26
For some more hilarious ways this game can break, see https://forums.afterdawn.com/threads/possible-god-of-war-2-glitch.537797/

**Comment by nyto0012** [comment] 2019-08-13 13:07
> Here's my take on this one:
> God of war has always had this kind of problem even on a real PS2. It seems to be a problem with the engine. In GOW1 you may go to the pandora's box room and find it missing. In GOW2 there are cases where you can't progress in the titan's cave because the event does not trigger. The reason for this has never been identified. I encountered the missing pandora's box bug and was able to fix it by some luck after messing around with the filesystem for a while, but it was a fluke and I have no idea what actually made it start working again. On PS2 you just had to start a new game.

thanks man, I got it, so these are problems with the game itself rather than the emulator, now that I remember I saw this same error several years in the past with the ps2 itself .

I will start another two games and see if this happens again, if it  happens I suppose I ought to grab a new GOW 2 version from a friend or sth and see if it works.

should I let this post open a while further so I can inform you or close it already ?

again, thanks for taking the time to clear  my mind .

**Comment by Asinin3** [comment] 2019-08-13 13:31
It could be an issue with the game itself that RPCS3 is just encountering more often than real-hardware due to how it's running. Persona 5 is a good example of this, when you get extremely low performance in Persona 5 you can walk out of bounds through the invisible walls in the map. This only occurs when your fps is at like below 8fps. So, in the early stages of RPCS3 it appeared quite often. The issue exists on real-hardware as well its just that the game speed never got that low on real hardware so it didn't appear.

**Comment by kd-11** [comment] 2019-08-19 22:20
We can close this for now unless it happens to be a persistent issue.

**Closed by kd-11** 2019-08-19 22:20 UTC
