### ISSUE TITLE
Nvidia drivers - Device lost (Driver crashed with unspecified error or stopped responding and recovered) (VK_ERROR_DEVICE_LOST)

### ISSUE THREAD

**Issue by jy95** [RPCS3/rpcs3#10926] opened 2021-09-25 19:21 UTC
## Quick summary
```bash
Assertion Failed! Vulkan API call failed with unrecoverable error: Device lost (Driver crashed with unspecified error or stopped responding and recovered) (VK_ERROR_DEVICE_LOST)
(in file D:\a\1\s\rpcs3\Emu\RSX\VK\vkutils\sync.cpp:200[:5], in function wait_for_event) (e=0x0000007e[126])
(in file D:\a\1\s\rpcs3\Emu\RSX\VK\vkutils\shared.cpp:107[:24], in function die_with_error) (e=0x0000007e[126])
```

## Details

I can reproduce this every time on [Ratchet & Clank: ACiT](https://github.com/RPCS3/rpcs3/issues/10649).
Here is my latest try : [RPCS3.log](https://github.com/RPCS3/rpcs3/files/7230243/RPCS3.log)
Due to Nvidia 470 drivers ? I am starting to think Nvidia again mess up with their drivers ...

#### Please provide your system configuration:
* OS : Windows, Major: 10, Minor: 0, Build: 19042, Service Pack: none, Compatibility mode: 0
* CPU Intel(R) Core(TM) i7-8750H CPU @ 2.20GHz | 12 Threads | 15.85 GiB RAM | TSC: 2.208GHz | AVX+ | FMA3
* GPU 'NVIDIA GeForce GTX 1050' running on driver 472.12.0.0

**Comment by Linear524** [comment] 2021-10-05 03:52
I have GTX 1080 on 471.41, tried 472 today and all my titles runs fine without hardware problems or drivers crash.
I don't have Ratchet & Clank: ACiT, but is there everything alright with your power supply unit and AC voltage level ?

**Comment by kd-11** [comment] 2021-10-10 13:43
Requires saves to be provided for testers to reproduce the problem.

**Comment by jy95** [comment] 2021-11-07 19:50
Here is the log on the most recent version at this day ( RPCS3 v0.0.19-12990-53f25949 Alpha )
[RPCS3.log](https://github.com/RPCS3/rpcs3/files/7492982/RPCS3.log)

**Comment by jy95** [comment] 2021-11-20 17:39
On today build : 
![image](https://user-images.githubusercontent.com/9306961/142736012-3570e8d0-639f-4dbf-9e69-ac5cb6bdad9e.png)

**Comment by jy95** [comment] 2021-12-28 16:56
For info, I just tested today with :

- `RPCS3 v0.0.19-13136-900d7df4`
- `'NVIDIA GeForce GTX 1050' running on driver 497.29.0.0`

And I passed the crashing point (I am now before the final boss), that was : 
![crashBug](https://user-images.githubusercontent.com/9306961/128055074-08c6c6d6-ba05-43b7-9ec6-689931af8e8a.PNG)

**Comment by itsTyrion** [comment] 2021-12-31 00:38
I just tested with
* RPCS3 0.0.19-13137-cb2748ae Alpha
* GTX 1070 on drivers 456.71, 466.77 and 497.29
* Ryzen 3 3100 @ 4.1GHz, 16GB RAM, Windows 10 21H2 (Build 19044.1288)

Freezes with Vulkan, crashes with OpenGL.
[RPCS3_ACiT_OGL_466.log](https://github.com/RPCS3/rpcs3/files/7794976/RPCS3_ACiT_OGL_466.log)
[RPCS3_ACiT_Vulkan_466.log](https://github.com/RPCS3/rpcs3/files/7794982/RPCS3_ACiT_Vulkan_466.log)
[Savegame on my VPS, GH doesn't eat the ZIP](https://v.itstyrion.de/random/BCES00511_SAVE_1.zip)

**Comment by Yahfz** [comment] 2022-01-10 20:49
I've played both of your guys saves and never managed to reproduce it. Anything more specific than what you guys mentioned so i can try it?

**Comment by coolllman** [comment] 2022-01-12 15:56
Resistance 3 same error

**Comment by Xcedf** [comment] 2022-01-15 11:34
Have this error in GTA V, and I'm on old drivers btw 458.36, gtx1070
Always get an error trying to play first tow truck mission
![14](https://user-images.githubusercontent.com/7060586/149620307-3e7e1196-c666-44ae-a3c5-7481d63c3ce8.jpg)
here's the log
[RPCS3.log.gz](https://github.com/RPCS3/rpcs3/files/7874853/RPCS3.log.gz)
and here's the save to get there
[BLUS31156SGTA50000.gz](https://github.com/RPCS3/rpcs3/files/7874854/BLUS31156SGTA50000.gz)

**Comment by itsTyrion** [comment] 2022-01-15 22:05
Can we maybe remove the "47x" from the title? I was able to reproduce the issue with 45x and 49x, too.

**Comment by kd-11** [comment] 2022-01-17 18:47
I'm unable to reproduce any crashing in ACiT. Is it still a problem with latest master?

**Comment by coolllman** [comment] 2022-01-18 05:20
Resistance 3 same error on latest master

**Comment by coolllman** [comment] 2022-01-18 08:45
Resistance e savedata
https://drive.google.com/file/d/1Gip-70HtV3kI8kgrxLjTEwIRrkxOPzWS/view?usp=sharing

**Comment by Darkhost1999** [comment] 2022-01-18 17:02
Bioshock infinite. Just click continue game
Saves
[BLUS30629-AUTO-0.zip](https://github.com/RPCS3/rpcs3/files/7890925/BLUS30629-AUTO-0.zip)
F 0:01:12.110662 {RSX [0x00abbec]} SIG: Thread terminated due to fatal error: Assertion Failed! Vulkan API call failed with unrecoverable error: Device lost (Driver crashed with unspecified error or stopped responding and recovered) (VK_ERROR_DEVICE_LOST)
[regular.log](https://github.com/RPCS3/rpcs3/files/7890946/regular.log)

debug output wouldn't fatal error
[Debug.zip](https://github.com/RPCS3/rpcs3/files/7890958/Debug.zip)
`vkCreateShaderModule(): The SPIR-V Capability (Float16) was declared, but none of the requirements were met to use it.`
so [disable float16.log](https://github.com/RPCS3/rpcs3/files/7890981/disable.float16.log)

**Comment by kd-11** [comment] 2022-01-18 20:04
Float16 error is a khronos bug. See https://github.com/KhronosGroup/Vulkan-Docs/issues/1739
I'll check what's going on with the crash itself, the spec problem shouldn't cause crashing, just false errors.

**Comment by kd-11** [comment] 2022-01-18 21:55
Please check https://github.com/RPCS3/rpcs3/pull/11401 improves things.

**Comment by Darkhost1999** [comment] 2022-01-18 22:30
Bioshock infinite
F {RSX [0x04e48bc]} SIG: Thread terminated due to fatal error: rsx::get_address(offset=0x204e5730, location=0xffffffff): Invalid location!
(in file C:\Users\ContainerAdministrator\AppData\Local\Temp\cirrus-ci-build\rpcs3\Emu\RSX\RSXThread.cpp:1632[:33], in function prefetch_fragment_program)
(in file C:\Users\ContainerAdministrator\AppData\Local\Temp\cirrus-ci-build\rpcs3\Emu\RSX\RSXThread.cpp:197[:23], in function get_address)
[RPCS3.log](https://github.com/RPCS3/rpcs3/files/7892781/RPCS3.log)

**Comment by kd-11** [comment] 2022-01-18 22:45
Unrelated. We're discussing VK_ERROR_DEVICE_LOST not fifo desync which is what you posted @Darkhost1999

**Comment by Darkhost1999** [comment] 2022-01-18 22:47
Ok. I just haven't seen that invalid location error before and that was my test of the PR

**Comment by Darkhost1999** [comment] 2022-01-18 22:53
PR is working now so far. Thanks.

**Comment by kd-11** [comment] 2022-01-20 17:35
Closing as fixed by https://github.com/RPCS3/rpcs3/pull/11401

**Closed by kd-11** 2022-01-20 17:35 UTC
Labels: Need Information, Render: Vulkan, Driver: NVIDIA

**Comment by itsTyrion** [comment] 2022-01-20 22:37
good job!
