### ISSUE TITLE
[Feature request] Database for custom configuration files

### ISSUE THREAD

**Issue by willianholtz** [RPCS3/rpcs3#14910] opened 2023-12-19 13:54 UTC
### Quick summary

RPCS3 has a wiki in which all games have some small adjustments to improve performance or make the game work stable.

### Details

It would be interesting to create a database for users to just download the already configured files instead of doing it manually. I myself have a (tiny) base of games that I have on my HD, and this saves me time when I want to play a game with customized settings.

[RPCS3 Custom Files](https://github.com/willianholtz/custom_configs)

It would be very interesting to do something so that the user could just click a button, and the customized configuration file for that game in question would be downloaded and played without any problems. And this would also help to improve how the game should behave.

**Comment by AniLeo** [comment] 2023-12-19 14:04
Duplicate of #4434

**Closed by AniLeo** 2023-12-19 14:04 UTC
