### ISSUE TITLE
GL: Demon Souls - Garbage Graphics

### ISSUE THREAD

**Issue by Trevonn** [RPCS3/rpcs3#2755] opened 2017-05-06 02:17 UTC
CPU: i7 4790K 4GHz
GPU: RX 480 8GB (17.5.1)

[Log.zip](https://github.com/RPCS3/rpcs3/files/980625/RPCS3.zip)

![image](https://cloud.githubusercontent.com/assets/3117355/25769114/99d446f4-3209-11e7-9957-9e732e45c23f.png)

![image](https://cloud.githubusercontent.com/assets/3117355/25769117/a4244262-3209-11e7-8956-e33fffdb3254.png)

![fps_16 76__opengl__demon s_souls__ blus30443 _2017-05-06_00-38-34](https://cloud.githubusercontent.com/assets/3117355/25769107/80f1058c-3209-11e7-9677-51ff840efdd8.jpg)

**Comment by kd-11** [comment] 2017-05-06 11:23
Is it consistent? If not, you're looking at a freakish instance of the sync bug. Need other 480 users to confirm this as well.

**Comment by Trevonn** [comment] 2017-05-06 15:18
Every time I open the game yeah

**Comment by Margen67** [comment] 2017-05-06 15:23
Do you have the latest video driver installed?

**Comment by Trevonn** [comment] 2017-05-06 15:39
17.5.1 It's in the OP also.

**Comment by kd-11** [comment] 2017-05-07 09:21
I strongly suspect one of the spu threads isnt running, cant remember which one, but its not related to video output, just content streaming. I'm guessing it was fine until you entered a building or went outside and then suddenly no graphics, right?

**Comment by Trevonn** [comment] 2017-05-07 21:46
It starts before you get into the game you can see the same effect on the character heads on the load save screen

A video demonstration
https://www.youtube.com/watch?v=Okc2E2WlPck&feature=youtu.be

**Comment by kd-11** [comment] 2017-05-08 08:16
This seems to be an opengl sync issue. I'm not sure why fences are not working for you, but this seems to only affect your setup. I also have an AMD GPU and no such issue. Try with older drivers maybe?
Also, does this affect other games as well?

**Comment by kd-11** [comment] 2017-05-08 08:16
Wrong button

**Comment by Megamouse** [comment] 2017-05-08 08:34
I'm geting the same with above settings. RX480 as well. 17.4.2. driver
![image](https://cloud.githubusercontent.com/assets/23019877/25796364/8ef6d4d2-33d9-11e7-9c6f-755b783d0087.png)


[RPCS3.zip](https://github.com/RPCS3/rpcs3/files/982840/RPCS3.zip)

**Comment by kd-11** [comment] 2017-05-08 08:37
Any other games affected? Does legacy opengl buffers cause any change or is it also the same?

**Comment by Megamouse** [comment] 2017-05-08 08:43
still the same with legacy buffers.

Haven't seen it on other games yet

**Comment by kd-11** [comment] 2017-05-08 08:50
Do you also get the flickering on the savegame list? Does it ficker with vulkan/dx12 as well? Something about this bug report is off. I'm guessing the OP also has the same game version as you otherwise there'd be alot more people with this complaint.

**Comment by Megamouse** [comment] 2017-05-08 08:58
![image](https://cloud.githubusercontent.com/assets/23019877/25797349/1f54c00e-33dd-11e7-9582-c5d695069b89.png)

they flicker... I'll try with vulkan  now

**Comment by Megamouse** [comment] 2017-05-08 09:03
Vulkan seems to be fine.
DX12 gets stuck on title loading, not sure if this is supposed to happen

**Comment by kd-11** [comment] 2017-05-08 09:10
Seems to be an issue with the opengl driver then, possibly due to the way fences are handled not agreeing with the driver model for some reason. DX12 issue is a known sync bug.

**Comment by kd-11** [comment] 2017-05-08 09:25
I just remembered ring buffer fence sync with OGL needs some rewrites; probably not an issue for other GPUs but newer AMD chips are highly asynchronous which could cause these issues to flare up.

**Comment by Trevonn** [comment] 2017-05-08 19:23
I can get to the save load menu with Vulkan but the game crashes the driver on the load screen @Megamouse Do you also experience this?

**Comment by Megamouse** [comment] 2017-05-08 23:44
no @Trevonn  but:

![image](https://cloud.githubusercontent.com/assets/23019877/25829788/f3845116-3458-11e7-87b4-32758087a475.png)

uuups- seems to be black in vulkan

**Comment by kd-11** [comment] 2017-05-09 06:37
It has been working for a while with vulkan on my wip branch, you'll have to wait for the changes to get merged, or fetch the build from appveyor.

**Comment by kd-11** [comment] 2017-05-09 16:33
After rebase my wip code on current master, this issue has appeared for me as well. Affects all backends, but no changes to the graphics code have taken place. Will try to find the corrupting changeset.

**Comment by kd-11** [comment] 2017-05-09 18:02
I have confirmed the issue to be a regression caused here https://github.com/RPCS3/rpcs3/pull/2719. To be fixed soon.

**Comment by kd-11** [comment] 2017-05-12 16:39
Fixed via https://github.com/RPCS3/rpcs3/pull/2773

**Closed** 2017-05-12 17:12 UTC
Labels: opengl, regression
