### ISSUE TITLE
Audio crackling after ~5 minutes of emulation

### ISSUE THREAD

**Issue by Tom3kk** [RPCS3/rpcs3#6343] opened 2019-08-13 22:18 UTC
( Tested on: Persona 5 NA Disc, Skate 3 NA Disc, Demon's Souls EU Disc )
The only fix I've found with the help of a helper on discord was to pause and unpause the emulation, but that's temporary and resumes after about 5 mintues.   
[Log from Skate 3](https://github.com/RPCS3/rpcs3/files/3499107/RPCS3.log.gz)
Per request: Xaudio2, downmix to stereo

**Comment by Korados** [comment] 2019-08-14 02:36
I already asked about this on Discord a while ago. In the CPU tab of the cofigurations, try to disable SPU loop detection and set the preferred SPU threads to 2. The boot might be a bit slower then but the audio is fine. This helped me a lot!

**Comment by dawnbomb** [comment] 2019-08-14 14:29
i actually can confirm what your saying, don't know why it's happening, but it is.  (Demon Souls)

**Comment by vsub** [comment] 2019-08-14 16:44
Not sure if my settings have anything to do with it but I played P5 for ~20 minutes(beat a boss and watch a cutscene)but the audio was fine

From your settings @takhlaq there are two differes
Preferred SPU Threads - Auto
FPS Limit is set to 59.54

I am using the 60fps patch
But man,what an fps improvement since the last time played the game,few months ago.
When you exit the train at the beginning of the game,I was getting ~14 or less,and now it can go above 30fps

**Comment by adrianocolvero** [comment] 2019-08-22 13:24
Same happening on Guitar Hero games here, but only when i don't use the audio buffer cause it adds some extra overhead on my old i7 4th gen cpu and makes the emulation slower.

**Comment by AniLeo** [comment] 2020-01-08 21:25
I can't reproduce this, can you test on OpenAL vs XAudio2 (if you use Windows) / ALSA (if you use Linux)

Also, check SPU LLVM vs SPU ASMJIT

**Comment by adrianocolvero** [comment] 2020-01-09 02:31
> I can't reproduce this, can you test on OpenAL vs XAudio2 (if you use Windows) / ALSA (if you use Linux)
> 
> Also, check SPU LLVM vs SPU ASMJIT

I can confirm it do not happens while using OpenAL as audio backend. Anyway, can you please give a look into a long term glitch on the emulation of this game (Guitar Hero 5)? Characters randomly flickers or even get invisible/disappears the whole time, except from this, the game is running almost perfectly, this happens since a long ago, i will share a video link for reference here:

  https://youtu.be/4jw1whwxJQU

I tried both LLVM and ASMJIT decoders, nothing changes, same behavior. (The same happens on the Guitar Hero 6 too).
Thank you.

**Comment by AniLeo** [comment] 2020-01-09 05:01
That has nothing to go with this issue, I recently moved GH5 to Playable so I'm aware myself, if you want to submit an issue on that go ahead but you need an rsx capture from a frame where the characters are glitched.

**Comment by Tom3kk** [comment] 2020-04-10 22:47
Open AL fixes the issue, latest builds don't seem to have this issue, but instead my game now has a random chance to freeze in the first minute of emulation lol

**Comment by Megamouse** [comment] 2021-01-25 18:38
closing as original issue seems to be fixed.

**Closed by Megamouse** 2021-01-25 18:38 UTC
Labels: Audio, Need Information
