### ISSUE TITLE
BLUS30359 Tekken6 boot stuck now

### ISSUE THREAD

**Issue by fuhuan416** [RPCS3/rpcs3#10051] opened 2021-04-01 17:20 UTC
## Quick summary
Stuck on the screen of Loading PPU modules 
![QQ图片20210402011746](https://user-images.githubusercontent.com/6281757/113330410-45589780-9351-11eb-9644-ea867d6c40f8.png)

## Details
In this interface, RPCS3 is completely stuck and can only end the process

[RPCS3.zip](https://github.com/RPCS3/rpcs3/files/6245311/RPCS3.zip)

**Comment by Nekotekina** [comment] 2021-04-01 18:59
Did you retry multiple times?

**Comment by DiNozzo787** [comment] 2021-04-03 16:26
Im having the same problem

**Comment by DiNozzo787** [comment] 2021-04-03 16:26
![Uploading Screenshot (182).png…]()

**Comment by joker5bb** [comment] 2021-04-03 16:27
i also have the same problem 
[RPCS3.log](https://github.com/RPCS3/rpcs3/files/6253018/RPCS3.log)

**Comment by fuhuan416** [comment] 2021-04-03 16:29
> Did you retry multiple times?

Yes, I have tried more than 10 times and tried to remove all caches, and the problem remains.
I updated the emulator to 0.0.15-12039 and the problem remains.

**Comment by AniLeo** [comment] 2021-04-03 16:36
Duplicate of #10060, does not follow regression report template

**Comment by Megamouse** [comment] 2021-04-03 16:37
Please disable the native user interface for now.
![image](https://user-images.githubusercontent.com/23019877/113484993-9c727f80-94ab-11eb-8c6c-92c6a17917b1.png)

**Comment by DiNozzo787** [comment] 2021-04-03 16:39
i tried it didnt work

**Comment by joker5bb** [comment] 2021-04-03 16:47
> 
> 
> Please disable the native user interface for now.
> ![image](https://user-images.githubusercontent.com/23019877/113484993-9c727f80-94ab-11eb-8c6c-92c6a17917b1.png)

this worked for me, game booted.
there is still red text in the log

`U sys_prx TODO: _sys_prx_register_module(name=“cellProcessElf”, opt=*0xd0010ce0)
S PPU: LLVM: Loaded module v4-kusa-1z3Pyu8YVnnorJiQ2hfu1e-00000G-broadwell.obj
S sys_prx: Loaded module: “/dev_flash/sys/external/libsysmodule.sprx” (id=0x23000b00)
U sys_ss TODO: sys_ss_access_control_engine(pkg_id=0x1, a2=0x1, a3=0xd0010a50)
E SYS: 'sys_ss_access_control_engine' failed with 0x80010003 : CELL_ENOSYS [1]
U sys_ss TODO: sys_ss_access_control_engine(pkg_id=0x2, a2=0xd0010a50, a3=0x0)
S PPU: LLVM: Loaded module v4-kusa-XCgQWMc1s99n1WTwrpWvw4-00000G-broadwell.obj
S sys_prx: Loaded module: “/dev_flash/sys/external/libgcm_sys.sprx” (id=0x23000e00)
S PPU: LLVM: Loaded module v4-kusa-GsbjiwC5Sm3exFcR5udHpE-00000G-broadwell.obj
S PPU: LLVM: Loaded module v4-kusa-gRWSbPdZHFQq5essKqQVjk-00000G-broadwell.obj
S sys_prx: Loaded module: “/dev_flash/sys/external/libsre.sprx” (id=0x23001100)
U sys_prx TODO: _sys_prx_register_module(name=“_sysProcessElf”, opt=*0xd0010df0)
S PPU: LLVM: Loaded module v4-kusa-fLV79QqHgPi90UziTsWrHo-00000G-broadwell.obj
S sys_prx: Loaded module: “/dev_flash/sys/external/libfs.sprx” (id=0x23002f00)
S PPU: LLVM: Loaded module v4-kusa-t1xTtC1PVoW6Jh636RxJVQ-00000G-broadwell.obj
S PPU: LLVM: Loaded module v4-kusa-2wS6UCQGvL8KpqZwEg6HX7-00000G-broadwell.obj
S sys_prx: Loaded module: “/dev_flash/sys/external/libnet.sprx” (id=0x23004600)
S PPU: LLVM: Loaded module v4-kusa-ttuWcrR8vkrZXRoK2sr771-00000G-broadwell.obj
S sys_prx: Loaded module: “/dev_flash/sys/external/libsmvd2.sprx” (id=0x23004800)
S PPU: LLVM: Loaded module v4-kusa-HiPA6t49xGUA4vnZ3HFZ0a-00000G-broadwell.obj
S sys_prx: Loaded module: “/dev_flash/sys/external/libavcdec.sprx” (id=0x23004900)
S PPU: LLVM: Loaded module v4-kusa-gchiVUbW1b4kPJPTmwJ8QL-00000G-broadwell.obj
S sys_prx: Loaded module: “/dev_flash/sys/external/libadec.sprx” (id=0x23004a00)
S PPU: LLVM: Loaded module v4-kusa-KteEiVsCbuKT791v7VZYwX-00000G-broadwell.obj
S sys_prx: Loaded module: “/dev_flash/sys/external/libac3dec.sprx” (id=0x23004b00)
S PPU: LLVM: Loaded module v4-kusa-jJwzGJv5R9eZMHq9J8MkYv-00000G-broadwell.obj
S sys_prx: Loaded module: “/dev_flash/sys/external/libat3dec.sprx” (id=0x23004c00)
S PPU: LLVM: Loaded module v4-kusa-Pkr7XAuXfpc5E5k8wfApJc-00000G-broadwell.obj
S sys_prx: Loaded module: “/dev_flash/sys/external/libatxdec.sprx” (id=0x23004d00)
S PPU: LLVM: Loaded module v4-kusa-4RvCp1PnzhcZcunZsLjmcG-00000G-broadwell.obj
S sys_prx: Loaded module: “/dev_flash/sys/external/libdmux.sprx” (id=0x23004e00)
S PPU: LLVM: Loaded module v4-kusa-VZcVmykW24Mqf5UJab7kxN-00000G-broadwell.obj
S sys_prx: Loaded module: “/dev_flash/sys/external/libdmuxpamf.sprx” (id=0x23004f00)
S PPU: LLVM: Loaded module v4-kusa-XPMH8ztYKnZCkeMcGCePPX-00000G-broadwell.obj
S sys_prx: Loaded module: “/dev_flash/sys/external/libpamf.sprx” (id=0x23005000)
U sys_prx TODO: _sys_prx_get_module_id_by_name(name=“cellLibprof”, flags=0, pOpt=*0x0)
S PPU: LLVM: Loaded module v4-kusa-KSs9JzJU0dS673WTN14GGy-00000G-broadwell.obj
S sys_prx: Loaded module: “/dev_flash/sys/external/libatrac3plus.sprx” (id=0x23007500)
U sys_prx TODO: _sys_prx_unload_module(id=0x2300a600, flags=0x0, pOpt=*0x0)
U sys_net TODO: sys_net_infoctl(cmd=53, arg=*0xd000fd78)
U cellNetCtl TODO: cellNetCtlAddHandler(handler=*0x8c98e0, arg=*0xb41390, hid=*0xb413b0)
S cellSysutil: Mounted existing cache at C:/Users/user/Desktop/rpcs3/dev_hdd1//caches/BLES00635_BLES00635/
E SYS: 'sys_fs_stat' failed with 0x80010006 : CELL_ENOENT, “/dev_bdvd/PS3_GAME/USRDIR/game/DATA2” [1]
S PPU: LLVM: Loaded module v4-kusa-ZAhea3FFhakpfMa36ZvaNx-00000G-broadwell.obj
S sys_prx: Loaded module: “/dev_flash/sys/external/librtc.sprx” (id=0x2300f200)
E SYS: 'cellSaveDataAutoLoad2' failed with 0x8002b401 : CELL_SAVEDATA_ERROR_CBRESULT [1]
S PPU: LLVM: Loaded module v4-kusa-qAE5LW7t8xT9tNggSrSJhv-00000G-broadwell.obj
S PPU: LLVM: Loaded module v4-kusa-1v8Qb7coSU1k54TtmJzrt4-00000G-broadwell.obj
S sys_prx: Loaded module: “/dev_flash/sys/external/libpngdec.sprx” (id=0x23010200)
U sys_prx TODO: _sys_prx_get_module_id_by_name(name=“cellLibprof”, flags=0, pOpt=*0x0)
S RSX: Program compiled successfully x2
S SPU: New block compiled successfully x1064`

**Comment by DiNozzo787** [comment] 2021-04-03 17:30
mine says in log F VM: Access violation reading location 0x4 (unmapped memory) [type=u32]

**Closed** 2021-04-03 18:37 UTC
