### ISSUE TITLE
BLES00188 [FIFA Street 3] - From Intro state to Not Launchable

### ISSUE THREAD

**Issue by LaneSh4d0w** [RPCS3/rpcs3#8071] opened 2020-04-20 19:51 UTC
Pull 7601 states that BLES00188 is in Intro state.

Latest build (10246) shows that game isn't playable.

Log data : 
[RPCS3.log](https://github.com/RPCS3/rpcs3/files/4505832/RPCS3.log)

Screenshot : 
![image](https://user-images.githubusercontent.com/30985701/79794005-d5c0e680-8351-11ea-846e-338a493e6553.png)

Cannot show Log data for Pull 7601 since RPCS3 litterally crashes in front of me when I try launching it.

**Comment by AniLeo** [comment] 2020-04-20 19:53
Missing log file, does not follow guidelines

**Comment by LaneSh4d0w** [comment] 2020-04-20 19:56
Updated.

**Comment by AniLeo** [comment] 2020-04-20 19:59
Duplicate of #5591

**Closed** 2020-04-20 19:59 UTC
Labels: Need Information
