### ISSUE TITLE
RPCS3 doen´t start, no solution worked

### ISSUE THREAD

**Issue by RivterDR** [RPCS3/rpcs3#9240] opened 2020-11-10 21:42 UTC
[Hello everyone,
i hope someone can help me.
Whenever i start RPCS3, it pop out in thask manager, but not as a window or a program.
Every solution, which is listed on Discord and on the website wont help.
New GPU driver, older GPU driver, Vulkan is finde as well, Visual C++ is installed too.

![EmulatorFolder](https://user-images.githubusercontent.com/74271394/98736689-7259dd00-23a5-11eb-983c-aec80854ded5.PNG)

![VulkanDiagnostics](https://user-images.githubusercontent.com/74271394/98736697-7685fa80-23a5-11eb-98d9-5f70e860046d.PNG)

I don´t know, what to do. None of the solutions helped. No one on Discord could help me as well with that problem.

[RPCS3.log.zip](https://github.com/RPCS3/rpcs3/files/5520338/RPCS3.log.zip)

**Comment by RivterDR** [comment] 2020-11-10 21:49
I already installed the newest driver 457.30  (listed on 2020.11.9)
But on the VkDiag tool it still the driver from (11-6-2020).

**Comment by RainbowCookie32** [comment] 2020-11-10 21:50
Maybe #8409?

**Comment by RivterDR** [comment] 2020-11-10 21:51
I tried the versions of the last 1.5 months too. No ones worked

**Comment by RainbowCookie32** [comment] 2020-11-10 21:53
Well, the last build to work for the people on that issue is 155 days old
https://github.com/RPCS3/rpcs3-binaries-win/releases/download/build-b75af69cf90418d18af2fa9af282e23b772e53d1/rpcs3-v0.0.10-10477-b75af69c_win64.7z

**Comment by RivterDR** [comment] 2020-11-10 21:55
should i update it to the newer version or not?

**Comment by RainbowCookie32** [comment] 2020-11-10 21:55
Test if that build works for you.

If it does, then close this issue as it's a duplicate of the other one I linked above.

**Comment by RivterDR** [comment] 2020-11-10 21:57
It starts, but when i update it, it wont start a window again.

**Comment by RainbowCookie32** [comment] 2020-11-10 21:58
Well, of course. 
The next build is the one that introduced the issue. Duplicate of #8409

**Closed** 2020-11-10 21:58 UTC
