### ISSUE TITLE
Does not compile PPU LLVM cache through option in context menu

### ISSUE THREAD

**Issue by Andryshik345** [RPCS3/rpcs3#5852] opened 2019-04-16 13:58 UTC
when trying to compile the cache in games `Flower [NPEA00250]` and `Journey [NPEA00288]`, this is written to the log(this is for Journey, but Flower is the same):
```
E {SPRX Loader} LDR: SELF: Failed to decrypt metadata info!
E {SPRX Loader} LDR: SELF: Failed to load SELF file metadata!
E {SPRX Loader} LDR: Failed to load SPRX 'D:/PS3/dev_hdd0/game/NPEA00288/USRDIR/Data/Prx/elfEUGold.sprx' (Invalid stream or file not found)
E {SPRX Loader} LDR: SELF: Failed to decrypt metadata info!
E {SPRX Loader} LDR: SELF: Failed to load SELF file metadata!
E {SPRX Loader} LDR: Failed to load SPRX 'D:/PS3/dev_hdd0/game/NPEA00288/USRDIR/Data/Prx/HotLoadEUGold.sprx' (Invalid stream or file not found)
```
But in `Gran Turismo®6 [BCES01893]` and `Persona 5 [NPEB02436]`, the compilation window flashes and the log is empty. I also tried clear PPU cache before each attempt, but everything remains the same.
P.S.: What exactly does this option do?

**Comment by AniLeo** [comment] 2019-04-16 14:02
Compiles executables that don't need to be decrypted

There's no issue here, creating llvm cache for encrypted stuff without booting the game is not yet implemented

**Comment by Andryshik345** [comment] 2019-04-16 14:13
Then why GT6 and P5 don't want to compile? Or they also is encrypted?
In the rpcs3.log only this:
```
·! 0:00:09.839405 {SPRX Loader} LDR: Scanning directory: D:/PS3/dev_hdd0/game/NPEB02436/
·! 0:00:09.839741 {SPRX Loader} LDR: Scanning directory: D:/PS3/dev_hdd0/game/NPEB02436/TROPDIR/
·! 0:00:09.839904 {SPRX Loader} LDR: Scanning directory: D:/PS3/dev_hdd0/game/NPEB02436/USRDIR/
·! 0:00:09.840992 {SPRX Loader} LDR: Scanning directory: D:/PS3/dev_hdd0/game/NPEB02436/TROPDIR/NPWR11866_00/
·! 0:00:09.841284 {SPRX Loader} Thread time: 0.000000s (0.004685Gc); Faults: 0 [rsx:0, spu:0];
```

**Comment by AniLeo** [comment] 2019-04-16 14:17
The only executable in P5 is the EBOOT. Probably the same for GT6, so it's correct.

**Comment by MSuih** [comment] 2019-04-16 14:20
I can't remember the techinal details of it but games are allowed to load more PPU modules at any point they want. The compile option only compiles modules that are loaded immidiately at launch, if the game loads more modules after that (most games do) then they have to be compiled by launching the game.

**Comment by AniLeo** [comment] 2019-04-16 21:45
Closing as this is intended behavior, not an issue but rather unimplemented stuff

**Closed by AniLeo** 2019-04-16 21:45 UTC
