### ISSUE TITLE
Musou Orochi Z [BLJM60139]

### ISSUE THREAD

**Issue by Sasha349** [RPCS3/rpcs3#11994] opened 2022-05-10 23:55 UTC
## Quick summary
{PPU[0x1000000] Thread (main_thread) [0x00145ed4]} VM: Access violation reading location 0x10000000 (unmapped memory)

## Details
Crash after start any mission.
Run on Default RPCS3 settings.

#### System configuration:
* Windows 10 Build: 19044
* Ryzen 5950x
* RTX 3070 Ti Game Ready Driver 512.59
[RPCS3.log.gz](https://github.com/RPCS3/rpcs3/files/8665596/RPCS3.log.gz)

**Comment by nitroos-ai** [comment] 2022-05-11 01:52
Duplicate of #8491.

**Closed** 2022-05-11 04:37 UTC
Labels: Meta: Duplicate
