### ISSUE TITLE
Ni No Kuni [BLES01555] Unknown magnify filter 0x0

### ISSUE THREAD

**Issue by Metasynic** [RPCS3/rpcs3#5527] opened 2019-01-08 17:19 UTC
When a certain trick is used by a familiar, Ni No Kuni crashes with the following fatal error:
`{RSX [0x0c3a564]} RSX: class std::runtime_error thrown: Unknown magnify filter 0x0`
This can be reproduced by going to the Solosseum and fighting in Rank E. The final gauntlet has an enemy familiar which will almost definitely use the crash-triggering trick during the battle.

I've tested it with builds 7658 and 7678, and the error occurs in both. Let me know if I should try with another version or if more information is needed!

System specs: Ryzen 5 1500X, GTX 970, Win10, Vulkan
Log: [RPCS3.log (NNK, Magnify filter).gz](https://github.com/RPCS3/rpcs3/files/2737780/RPCS3.log.NNK.Magnify.filter.gz)

**Comment by elad335** [comment] 2019-01-08 17:20
duplicate of #3973

**Comment by Metasynic** [comment] 2019-01-08 17:21
Apologies, feel free to close this.

**Closed** 2019-01-08 17:22 UTC
