### ISSUE TITLE
BLJS10050 Gundam battlefield record 0081 does not boot after installing 1.02 update

### ISSUE THREAD

**Issue by PesaDag** [RPCS3/rpcs3#14117] opened 2023-07-01 10:57 UTC
### Quick summary

the game wont boot after installing patch 1.02 but it works fine with update 1.00

### Details

the game works fine with the base version 1.00 but when i install update 1.02 i get a black screen. this happens when i install the game on hdd and when i boot it normally 

### Attach a log file

[before_patch_RPCS3.log.gz](https://github.com/RPCS3/rpcs3/files/11925614/before_patch_RPCS3.log.gz)
[after_patch_RPCS3.log.gz](https://github.com/RPCS3/rpcs3/files/11925616/after_patch_RPCS3.log.gz)

**Comment by Gael2433** [comment] 2023-07-02 06:44
Please try with Internet set to disabled and RPCN disabled in the network tab for the custom config.

**Comment by PesaDag** [comment] 2023-07-02 10:18
i tried, i still get a black screen

**Comment by GundamSenpai** [comment] 2023-07-14 01:14
Yes same issue with me, 1.02 gives the black screen after booting process is complete. browsing on the internet regarding the issue, reveals that eboot seems to be the culprit.

replacing the eboot of the gundam battlefield record 0081 v1.02 with original one let's the game boot up again but the patch content doesn't work.

really hoping someone has resolution to this.

**Comment by FlexBy420** [comment] 2023-09-24 12:38
This is a duplicate of #11731

**Closed** 2023-09-24 12:59 UTC
