### ISSUE TITLE
EBOOT.BIN error. i launched the game yesterday and it was fine but today this happened

### ISSUE THREAD

**Issue by Thelastofusgamer** [RPCS3/rpcs3#7866] opened 2020-03-26 14:42 UTC
U {PPU[0x1000000] Thread (main_thread) [0x0026061c]} sys_prx TODO: _sys_prx_register_module()
U {PPU[0x1000000] Thread (main_thread) [0x00261038]} sys_prx TODO: _sys_prx_unload_module(id=0x23003400, flags=0x0, pOpt=*0x0)
E {PPU[0x1000000] Thread (main_thread) [0x00321ee4]} SYS: 'sys_fs_stat' failed with 0x8001003a : CELL_ENOTMOUNTED, “/dev_bdvd/PS3_GAME/USRDIR/EBOOT.BIN” [1]
U {PPU[0x1000000] Thread (main_thread) [0x00012eac]} PPU TODO: Unimplemented syscall syscall_988 -> CELL_OK
U {PPU[0x1000000] Thread (main_thread) [0x00260364]} sys_prx TODO: _sys_prx_stop_module(): cmd is 8 (stop function = *0x3304d8)
U {PPU[0x1000000] Thread (main_thread) [0x00260364]} sys_prx TODO: _sys_prx_stop_module(): cmd is 8 (stop function = *0x2d0814)
E {PPU[0x1000000] Thread (main_thread) [0x00321ee4]} SYS: 'sys_fs_stat' failed with 0x8001000d : CELL_EFAULT [1]
U {PPU[0x1000000] Thread (main_thread) [0x00012eac]} PPU TODO: Unimplemented syscall syscall_988 -> CELL_OK
E {PPU[0x1000000] Thread (main_thread) [0x0032261c]} SYS: 'sys_mutex_lock' failed with 0x80010005 : CELL_ESRCH [1]
U {PPU[0x1000000] Thread (main_thread) [0x00260364]} sys_prx TODO: _sys_prx_stop_module(): cmd is 8 (stop function = *0x3304d8)
U {PPU[0x1000000] Thread (main_thread) [0x00260364]} sys_prx TODO: _sys_prx_stop_module(): cmd is 8 (stop function = *0x2d0814)
U {PPU[0x1000000] Thread (main_thread) [0x000133e0]} PPU TODO: Unimplemented syscall syscall_988 -> CELL_OK

and ill attached the logs
[RPCS3.log](https://github.com/RPCS3/rpcs3/files/4387879/RPCS3.log)

**Comment by elad335** [comment] 2020-03-26 14:45
???

**Comment by AniLeo** [comment] 2020-03-26 14:46
This being a regression report, which is the last build where it works?

**Comment by AniLeo** [comment] 2020-03-26 14:50
In fact, this looks like user error somewhere. I'll preemptively close this, follow the appropriate steps for asking for support. If support determines this is an actual issue, the issue will be properly filed.

**Closed by AniLeo** 2020-03-26 14:50 UTC
Labels: Need Information

**Comment by Thelastofusgamer** [comment] 2020-03-26 14:51
2 build ago this one is the latest

**Comment by Thelastofusgamer** [comment] 2020-03-26 14:51
the build number is

**Comment by Thelastofusgamer** [comment] 2020-03-26 14:52
0.0.9-10023-158e34fa

**Comment by AniLeo** [comment] 2020-03-26 14:54
That version is the same one as your log. As I suspected, you did not check properly, so the correct thing to do here is a support request, not an issue report.
