### ISSUE TITLE
Crash in Jak & Daxter Trillogy

### ISSUE THREAD

**Issue by badasahog** [RPCS3/rpcs3#13247] opened 2023-01-17 18:31 UTC
### Quick summary

I had a crash in Jak & Daxter Trilogy. I was playing the first game, and I was warping to Gol and Mia's citadel via the teleporter gate, when the game (and emulator) crashed.

I've played through the whole game several times (probably 10+), but this is the first crash I've experienced when playing the first game.

### Attach a log file

[RPCS3.log](https://github.com/RPCS3/rpcs3/files/10438286/RPCS3.log)

### System configuration

default configuration

**Comment by Asinin3** [comment] 2023-07-23 04:00
Retest on latest. If its reproduceable provide a save file at the location where it happens. If it's not.. I would close the issue as without any easy way to test its not going to be very useful

**Comment by badasahog** [comment] 2023-07-23 07:26
@Asinin3 It's definitely not easily reproducible. The reason I posted this issue in the first place was to document a very rare error.

What if any use that information can be for development is not obvious to me

**Comment by Asinin3** [comment] 2023-07-23 11:53
Closing this then. The fatal error doesn't tell us where the issue is, it needs to be something unique or atleast have a way to reproduce otherwise how would we know how to fix it, if it was already fixed, or even ask you to test it.

**Closed by Asinin3** 2023-07-23 11:53 UTC
Labels: Need Information
