### ISSUE TITLE
Persona 5: Slow transition screen when exiting castle second time

### ISSUE THREAD

**Issue by Muramas** [RPCS3/rpcs3#3177] opened 2017-08-08 04:25 UTC
[RPCS3.zip](https://github.com/RPCS3/rpcs3/files/1206947/RPCS3.zip)
After Ryuji unlocks his persona and you leave the palace there is a cut-scene with red swirly lines that brings the game to a halt running around 1.5~2.5 fps and does not progress the game.
0.0.3-5601
PPU, SPU Recompiler, 1 SPU thread, Vulkan
Enable SPU loop detection checked
No GPU settings checked
Xaudio2, downmix to stereo checked

Nvidia 970
i5 6600k @ 4.38
16gb ram

Edit: I attempted to repeat the issue but was able to pass though it properly this time.

![Red Swirly](http://i.imgur.com/HwECVuN.png)

**Comment by Asinin3** [comment] 2017-08-08 04:50
You need to post the rpcs3.log file what's shown in the window is not enough.

**Comment by kd-11** [comment] 2017-08-13 21:32
Since it seems to not be reproducible, I'm closing this.

**Closed by kd-11** 2017-08-13 21:32 UTC
