### ISSUE TITLE
Demon's Souls [BLES00932] flickering on AMD Vega

### ISSUE THREAD

**Issue by megamaan** [RPCS3/rpcs3#6287] opened 2019-07-31 01:02 UTC
Hello everyone. Unfortunately I think that going from Nvidia to AMD has brought me some headaches, as is the case of trying to emulate Demon's Souls. 
The game works excellent in terms of framerate, sound and graphics, but promptly I have a flickering problem that is really unbearable. I have tried using both the latest version of the emulator and previous versions, I have also reinstalled drivers, I have deleted the shader cache files but the problem continues.
There is a permanent flickering which makes the game literally unplayable.

You can see the Flickering issue here:
https://imgur.com/6Tg3oB9

My hardware is:
Ryzen 2600
RX Vega 56.
Windows 10 x64

Rpcs3 build: 0.0.6-8437
I'm using Vulkan api.

[RPCS3.log.gz](https://github.com/RPCS3/rpcs3/files/3449351/RPCS3.log.gz)

Thank you!

**Comment by kd-11** [comment] 2019-08-13 10:29
Try the following:
SPU loop detection: OFF
TSX: Disabled
Vsync: Disabled
I'd start with disabling Vsync and SPU loop detection which are known to cause issues. TSX can also sometimes interfere with this one.

**Comment by kd-11** [comment] 2019-08-25 15:57
I was finally able to reproduce this on my system, but it seems confined to the nexus. Likely caused by a fault in uninterruptible code. I'll see about a solution.

**Comment by ajme1215** [comment] 2019-08-31 19:03
I'm having the same issue withy Vega 64. Is this isolated only to Vega cards?

**Comment by kd-11** [comment] 2019-09-03 20:25
I upgraded drivers recently and suddenly I cannot reproduce this by loading the nexus like I could before. Verify if it still happens on a clean 19.8.2 install. I recently had to DDU my system and reinstall drivers after I seriously messed up my configuration and suddenly the bug isn't there anymore. I also went back and tried some older builds, no flickering in the nexus. Please update with more information on how to reproduce if this is still an issue for you @megamaan

**Comment by AxiR2** [comment] 2019-09-03 22:19
Still the same issue for me on the lastes build with 19.8.2.

**Comment by kd-11** [comment] 2019-09-03 22:21
You did not explain how to reproduce though. Does it happen immediately on loading your character, anywhere? How frequent are the flashes? I think a short clip would help with recreating the conditions.

**Comment by ajme1215** [comment] 2019-09-03 22:22
I'm also experienceing black flickering issue after following your steps

**Comment by ajme1215** [comment] 2019-09-03 22:24
The flashes for me start as soon as you gain control of character. And happen constantly. Frame rate is solid though. I followed your steps and got the same issue. I traveled to the Nexus and to first Archstone and issue was still present. Ive tried various settings with no improvent and went back to recommended settings.

**Comment by kd-11** [comment] 2019-09-03 22:25
How about directly loading into the nexus without going through the tutorial?

**Comment by ajme1215** [comment] 2019-09-03 22:35
Happens when I directly load as well. I have a capture of what it looks like. I have a 9700k oc to 4.9 on all cores and a Vega 64. If you want to check it out how would you like me to post the capture?

**Comment by kd-11** [comment] 2019-09-03 22:42
No need. Can you try disabling native fp16 in your config file? You have to edit the file itself as there is no option in the gui.

**Comment by ajme1215** [comment] 2019-09-03 22:47
I changed this value from this:  
Disable native float16 support: false
to this
  Disable native float16 support: true
I still got the same results

**Comment by kd-11** [comment] 2019-09-03 22:49
Ok then, just attach the new log.

**Comment by ajme1215** [comment] 2019-09-03 22:51
Here it is I believe.
[RPCS3.log.gz](https://github.com/RPCS3/rpcs3/files/3571956/RPCS3.log.gz)

**Comment by AxiR2** [comment] 2019-09-03 23:03
> 
> 
> No need. Can you try disabling native fp16 in your config file? You have to edit the file itself as there is no option in the gui.

https://www.twitch.tv/videos/476483521

Complete clean install, Ryzen 3600/Vega 56. The slowdowns happen because of OBS, but the black frames are pretty much constantly like seen in the video. Runs beatifully otherwise...

I've tried pretty much every combination of settings/rpcs3 builds to no avail.

[Log.txt](https://github.com/RPCS3/rpcs3/files/3571990/Log.txt)

**Comment by alexhunt7** [comment] 2019-09-04 03:17
I also have this flickering issue, but I don't even make it through the tutorial before it crashes. I actually think it breaks my graphics driver, since I get a black screen on both monitors until I hit Esc to leave fullscreen.

The flickering looks just like the captures from the other posters, with black frames in between. The crash happens when entering the tunnel after the second tutorial enemy.

Windows 10, Ryzen 3600, Vega 56.

[RPCS3.log](https://github.com/RPCS3/rpcs3/files/3572544/RPCS3.log)

**Comment by kd-11** [comment] 2019-09-04 12:46
This seems isolated to AMD VEGA. I have Polaris and everything is ok, I was only able to witness the flickering shown in that video when I ran through the tutorial a few times and warped to the nexus, and even then it was confined to the nexus area. Haven't seen it since.
I initially thought faulting in uninterruptible code was the cause, but this would mostly not show up with MTRSX enabled.

**Comment by GorthHaur** [comment] 2019-09-04 13:23
I have the same issue, Radeon R5 2600, RX 590.
Video driver is 19.8.2

**Comment by GorthHaur** [comment] 2019-09-04 13:26
[RPCS3.log.gz](https://github.com/RPCS3/rpcs3/files/3574692/RPCS3.log.gz)

**Comment by kd-11** [comment] 2019-09-04 14:27
So whats the common denominator here then? I have RX470 + R7 1700 and no flickering. Is it processor maybe? Anyone with an 8-core actually encountering this?

**Comment by ajme1215** [comment] 2019-09-04 14:31
I do have an 8 core 9700k with the flickering.

**Comment by GorthHaur** [comment] 2019-09-04 14:53
Also I have crackling and repeating game sounds. I tried to on/off SPU loop detection, VSync, sound buffer. Strange thing

**Comment by kd-11** [comment] 2019-09-04 14:54
That's completely unrelated to this issue.

**Comment by GorthHaur** [comment] 2019-09-04 15:14
Sorry for that "out of theme". 
But about flickering issue: can it be unstable overclocked processor? Like throttling

**Comment by kd-11** [comment] 2019-09-04 15:23
As there is no common factor determined as of now, it is not possible to say what the real cause could be.

**Comment by ajme1215** [comment] 2019-09-04 15:54
I removed the OC and still had issues so it's not an unstable OC on my side.

**Comment by AxiR2** [comment] 2019-09-04 15:58
> 
> 
> As there is no common factor determined as of now, it is not possible to say what the real cause could be.

Only thing I can see is that so far it's only happend on amd GPUs?

**Comment by Lenox548** [comment] 2019-09-04 16:59
I have an i3 8100 and a rx 570 8g and I have the same issue, but there's a patch maded by Whatcookie that solves the flickering disabling the dynamic exposure, but it makes the game sligthly darker 

[patch.zip](https://github.com/RPCS3/rpcs3/files/3575670/patch.zip)

**Comment by AxiR2** [comment] 2019-09-04 17:08
> 
> 
> I have an i3 8100 and a rx 570 8g and I have the same issue, but there's a patch made by Whatcookie that solves the flickering disabling the dynamic exposure, but it makes the game sligthly darker
> 
> [patch.zip](https://github.com/RPCS3/rpcs3/files/3575670/patch.zip)

Can I add the lines to the 60 fps patch?

**Comment by AxiR2** [comment] 2019-09-04 17:16
> 
> 
> I have an i3 8100 and a rx 570 8g and I have the same issue, but there's a patch made by Whatcookie that solves the flickering disabling the dynamic exposure, but it makes the game sligthly darker
> 
> [patch.zip](https://github.com/RPCS3/rpcs3/files/3575670/patch.zip)

I tried the patch with 30 fps, doesn't work unfortunately

**Comment by ajme1215** [comment] 2019-09-04 17:17
I got the flickering to stop. In your patch file under:


PPU-83681f6110d33442329073b72b8dc88a2f677172: #BLUS30443
#OPTIONAL: Disable dynamic exposure (can turn off WCB for 20% faster performance)
#Enable this if you experience flickering

 # - [be16, 0x00025EDC, 0x981f]
remove the hash tag on this line so it looks like this:
  - [be16, 0x00025EDC, 0x981f]
after i removed the hash tag do disable dynamic exposure the flickering is completely gone

**Comment by Lenox548** [comment] 2019-09-04 17:20
> > I have an i3 8100 and a rx 570 8g and I have the same issue, but there's a patch made by Whatcookie that solves the flickering disabling the dynamic exposure, but it makes the game sligthly darker
> > [patch.zip](https://github.com/RPCS3/rpcs3/files/3575670/patch.zip)
> 
> Can I add the lines to the 60 fps patch?

I think it's already in the 60 fps patch but it's disabled, you have to delete the # that is written next to it

![deletethis](https://user-images.githubusercontent.com/54904556/64276721-f8b39d00-cf1e-11e9-85e3-53c243e6ceff.jpg)

**Comment by ajme1215** [comment] 2019-09-04 17:22
Yes depending on what region disc your playing you'll have to remove it for the "BLUS30443" line or the "BLES00932" line.

**Comment by AxiR2** [comment] 2019-09-04 19:03
OH MY FUCKING GOD I LOVE YOU ALL!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!

ITS GONE ITS GONE ITS FUCKING FINALLY GONE AFTER ALL THE HOURS AND THE PAIN 
THANK YOUUUUUUUUUUUUUUUUU

**Comment by AxiR2** [comment] 2019-09-04 19:26
I cannot belive this, a month ago I completely gave up on this game, then the 60 fps patch comes out, and now THIS!

**Comment by alexhunt7** [comment] 2019-09-05 01:48
Confirmed that uncommenting that line in the patch file fixes the flickering, though it does make the game significantly darker.

I still crash at the tutorial tunnel, though. I guess that should be a separate issue.

**Comment by kd-11** [comment] 2019-09-05 12:32
Retest with [this build](https://ci.appveyor.com/project/rpcs3/rpcs3/builds/27203683/artifacts) without the patch enabled and see if it fixes the flickering. Remember to enable WCB before testing.

**Comment by megamaan** [comment] 2019-09-05 14:10
Yes! It fixes the flickering! ;)

**Comment by ajme1215** [comment] 2019-09-05 14:47
> Retest with [this build](https://ci.appveyor.com/project/rpcs3/rpcs3/builds/27203683/artifacts) without the patch enabled and see if it fixes the flickering. Remember to enable WCB before testing.

I downloaded that build and enabled WCB and the flickering returned. I went ahead and just turned WCB off for now.

**Comment by rpjc** [comment] 2019-09-15 15:24
Rx 580 with driver 19.5.2 and the same issue.

The build above(2f54aba8) doesn't fixes the problem, but the patch(Disable dynamic exposure) does. 

Changing the display color in Radeon Settings to "brightness 125, contrast 150, saturation 125" makes up for the darkening of the screen due the patch.

**Comment by kd-11** [comment] 2019-09-15 15:28
Why such an old driver though? Also, please mention your CPU; something else is triggering this other than the GPU alone. The build fixed the flickering for the OP and for me as well, but somehow some people still have the problem. The OP and myself have something in common - Ryzen CPUs. This makes me wonder if something is interfering with TSX or other intel-specific options.

**Comment by rpjc** [comment] 2019-09-15 15:37
Newer drivers cause freesync to not work, beside other issues, but it still happened in newer drivers the last time I tried.
CPU is i5-3470. 
The only difference from the wiki default settings is resolution scale to 200%, but it still happens in default resolution.
I can create a log or something if it helps.

**Comment by rpjc** [comment] 2019-09-15 17:31
Tested with 19.9.2, flickering persists:
[RPCS3.oldrivers.log.gz](https://github.com/RPCS3/rpcs3/files/3614056/RPCS3.oldrivers.log.gz)
[RPCS3.new19.9.2.log.gz](https://github.com/RPCS3/rpcs3/files/3614057/RPCS3.new19.9.2.log.gz)

**Comment by Miltrivd** [comment] 2019-09-23 01:32
Flickering is gone for me, using 60 fps patch but not disabling Dynamic Exposure, Write Color Buffers is on.

RPCS3: v0.0.7-8751-3121fecc
Vulkan renderer

CPU: AMD Ryzen 7 2700X
GPU: AMD R9 390 (Driver 19.7.3)

I was testing the lens flare fix (a mod) so I was rebuilding the shader cache and noticed the flicker gone (I always test re-enabling Dynamic Exposure and enabling Write Color Buffers when changing versions). Just in case I cleared the cache again and tried without the mod.

I initially thought it was activating Strict Rendering Mode that did it (was testing that too) but once disabled it kept working fine. Flickering gone with Strict Rendering Mode, with default rendering settings or 150% rendering scale (1080p). Vsync on or off also shows no flicker.

**Comment by kd-11** [comment] 2019-11-10 14:57
Needs a retest with new rpcs3 versions and AMD drivers.

**Comment by Miltrivd** [comment] 2019-11-13 02:31
> Needs a retest with new rpcs3 versions and AMD drivers.

GPU: MSI 390 Gaming
CPU: Ryzen 7 2700X (@stock)
GPU Driver: 19.11.1
RPCS3 version: v0.0.7-9124-abbf3c4d_win64

I see no issues and even slightly better performance versus v0.0.7-8939-59382e02_win64

Video of play session in case is useful: https://www.twitch.tv/videos/507462319

**Comment by kd-11** [comment] 2020-01-15 18:52
Closing as fixed.

**Closed by kd-11** 2020-01-15 18:52 UTC
Labels: Driver: AMD, OS: Windows

**Comment by jkh0208** [comment] 2020-01-21 02:45
I'm having this same exact issue on a RPCS3 0.0.8-9422-98a8eeaa, using an Nvidia GTX 1660 Ti.  All settings default except "write color buffers" checked.
