### ISSUE TITLE
Illegal instruction (0xC000001D) - Tales of Vesperia [BLJS10053]

### ISSUE THREAD

**Issue by purifiedst0rm** [RPCS3/rpcs3#6188] opened 2019-07-11 03:00 UTC
RPCS3 v0.0.6-8355-537d3f25 Alpha | HEAD | FW 4.84 | Windows 10 1809
AMD Ryzen 7 2700X Eight-Core Processor | 16 Threads | 15.93 GiB RAM | AVX+
GPU: GeForce RTX 2070 (431.36) 
[BLJS10053] Tales of Vesperia
Ingame since 2017-07-07
10 mins into playing my tales of vesperia game it crashes and says: Fatal error
---------------------------
Unhandled Win32 exception 0xC000001D.
Exception address: 00000000005E00AE.
Image base: 0000000000010000.

[RPCS3.log](https://github.com/RPCS3/rpcs3/files/3380077/RPCS3.log)

**Comment by RainbowCookie32** [comment] 2019-07-11 03:02
Follow the guidelines when opening an issue and attach a log with system specs.

**Comment by purifiedst0rm** [comment] 2019-07-11 03:04
RPCS3 v0.0.6-8355-537d3f25 Alpha | HEAD | FW 4.84 | Windows 10 1809
AMD Ryzen 7 2700X Eight-Core Processor | 16 Threads | 15.93 GiB RAM | AVX+
GPU: GeForce RTX 2070 (431.36) 

10 mins into playing my tales of vesperia game it crashes and says: Fatal error
---------------------------
Unhandled Win32 exception 0xC000001D.
Exception address: 00000000005E00AE.
Image base: 0000000000010000.

[RPCS3.log](https://github.com/RPCS3/rpcs3/files/3380077/RPCS3.log)

**Comment by illusion98** [comment] 2019-07-11 03:25
wtf

**Comment by AniLeo** [comment] 2019-07-12 17:26
Needs a stack trace very likely

**Comment by AniLeo** [comment] 2020-01-08 21:17
Any update? Since this is the only report of illegal instruction there is and no one else is able to reproduce this, I'm going to go ahead and close it since it shouldn't be an actual issue on our side.

If you're able to provide correct steps for reproducing this or a stack trace, feel free to ping for reopening.

**Closed by AniLeo** 2020-01-08 21:17 UTC
Labels: Bug, CPU, Need Information
