### ISSUE TITLE
vk/AMD: Broken background on God of War 2

### ISSUE THREAD

**Issue by Sarutu** [RPCS3/rpcs3#5318] opened 2018-11-09 10:39 UTC
God of War 2 background is not visualized in vulkan. 
### VULKAN
![default](https://user-images.githubusercontent.com/44894808/48257732-3fbe2800-e40b-11e8-8e36-d935c23eca90.jpg)
### OpenGL
![2](https://user-images.githubusercontent.com/44894808/48257840-8d3a9500-e40b-11e8-98b3-3eb48ce1c8e7.jpg)
CPU: Xeon x3460
GPU: AMD R9 270
Windows 10
Vulkan 1.1.85

[NPEA00256_capture.zip](https://github.com/RPCS3/rpcs3/files/2565705/NPEA00256_capture.zip)
[RPCS3.log.gz](https://github.com/RPCS3/rpcs3/files/2565706/RPCS3.log.gz)

**Comment by Sarutu** [comment] 2018-11-09 15:50
ok
[NPEA00256_20181109204707_capture.zip](https://github.com/RPCS3/rpcs3/files/2566494/NPEA00256_20181109204707_capture.zip)

**Comment by Asinin3** [comment] 2018-11-09 15:55
I don't need another capture, i just want to know if the issue is still happening for you with the settings I suggested. Also, make sure your GPU drivers are up to date.

**Comment by Sarutu** [comment] 2018-11-09 16:03
I have the latest gpu driver, this problem does not change from the settings and this problem has been known to me for a long time. During this time I installed a clean system many times.

**Comment by QuaiGoner** [comment] 2018-11-09 17:52
Same issue with all settings on vulkan.
Ryzen 5 2400g
Vega 11

**Comment by Asinin3** [comment] 2018-11-09 18:48
Must be an AMD GPU issue.

**Comment by Sarutu** [comment] 2018-11-09 18:50
+ AMD GPU, Nvidia GTX Normal visualized

**Comment by kd-11** [comment] 2018-11-10 13:46
Tested on RADV (R9 270x) and its ok, will check AMD on windows later, but at least its not a hardware bug. As I have the same GPU as the OP this will make isolation easier if a problem does exist. Its likely some kind of driver issue.

**Comment by Ghostotakoi** [comment] 2018-11-13 08:05
try disabe the gpu overlay

**Comment by Sarutu** [comment] 2018-11-13 09:38
cannot disable overlay.you can disable only the key combination.strange problem R9 270x its ok, vega11 and R9 270 have problem.This was a problem for both old drivers a year ago and for new ones.hardly a driver problem

**Comment by kd-11** [comment] 2019-03-19 21:12
I've never been able to reproduce this, which makes me wonder if its caused by interference by afterburner overlay or drivers. There is no difference between a 270x and a 270 outside of name and factory clock which raises even more questions.
Retest with recent RPCS3 builds and update.

**Comment by kd-11** [comment] 2019-04-05 12:59
Closing as 'cannot reproduce' - request to reopen if you can still reproduce with latest rpcs3 version and AMD drivers.

**Closed by kd-11** 2019-04-05 12:59 UTC
Labels: Bug, Driver: AMD, Render: Vulkan
