### ISSUE TITLE
[FIXED] LittleBigPlanet low fps when playing levels

### ISSUE THREAD

**Issue by LB200** [RPCS3/rpcs3#8840] opened 2020-09-05 17:18 UTC
When in the Pod, I get around 30 fps, maybe 24 fps at lowest but it's not noticeable. (Edit: I know this is normal, I meant it runs smoothly in the Pod, but in game it's slow).
When I go into a level, it goes into slow motion, with fps below 24. The game runs well but when moving it's just slow. 
I also get so many errors in the logs, it's just spams the logs with red text like: 

E {PPU[0x100001f] Thread (FMOD thread for FMOD_NONBLO) [0x0048290c]} SYS: 'sys_semaphore_wait' failed with 0x00000000 : 0 [1]
E {PPU[0x1000020] Thread (FMOD file thread) [0x0048290c]} SYS: 'sys_semaphore_wait' failed with 0x00000000 : 0 [1]
E {PPU[0x1000004] Thread (JobManagerWorker) [0x00513924]} SYS: 'sys_semaphore_wait' failed with 0x00000000 : 0 [1]
E {PPU[0x1000000] main_thread } SYS: Stat: 'sceNpUtilCmpNpId' failed with 0x8002ab0f : SCE_NP_UTIL_ERROR_NOT_MATCH [x91899]

**Full logs:** 
https://www.dropbox.com/s/gwx3p1nhsg6n1dw/RPCS3.log?dl=0

I've tried everything, turning off Anti-Aliasing (which used to help but now doesn't), turning off logs (I think this helped a little, can't remember), and pretty much everything else I think.

Also, why are the logs 322,591kb, isn't that 300mb? 

I don't know if it's an issue with my PC or something, the only game that I have on RPCS3, besides LittleBigPlanet, is PlayStation Home and it runs perfectly.

I get this error in the logs when LittleBigPlanet is starting:
E RSX: Your GPU does not support alpha-to-one for multisampling. Graphics may be inaccurate when MSAA is enabled.

Windows
AMD Ryzen 7 4700U
Radeon Graphics

(Edit) 
### FIX:
In the GPU section in settings, lower the Resolution Scale (Disable Strict Mode) to 50% (fasted) or 75% (somewhat fast) as 100% (Default) makes the game slower than usual (on some PCs, of course).

**Beware**: 50% won't look that good, but the game probably doesn't look that different to how it did on the PS3.

Also, Write Color Buffers in additional settings (in CPU) might make the game slower, but it fixes graphical issues in LittleBigPlanet like gas being invisible.

this is only here for people with similar issues.

I added [FIXED] to the title and I don't know if I'm allowed to do that, if not, let me know.

**Comment by Asinin3** [comment] 2020-09-05 17:52
Not a bug, game's physics are tied to frame-rate so when you have low fps the game is in slow-motion. Similarly, if you go over 30fps then the game runs too fast. You won't go over 30 unless you uncap frame-rate though.

Issue here is just performance, you're on a laptop CPU so it's not ideal. But you can try changing preferred spu threads to 1, 2 or 3 and see which one is faster for you.

>Also, why are the logs 322,591kb, isn't that 300mb?

You uploaded the rpcs3.log which is uncompressed. When you close RPCS3 it creates a compressed RPCS3.log.gz file which is much smaller.

**Comment by LB200** [comment] 2020-09-05 18:18
Turning off Write Color Buffers (which is like the only thing I haven't tried) seemed to help boost performance, I reached average 20fps when I would reach average 12fps I think.  


Okay so I fixed the issue, I turned the resolution scale to 50% and it helped so so much! I guess the resolution was to high. It looks kinda bad but it kinda looks like it does on PS3, and that's okay.

**Comment by RainbowCookie32** [comment] 2020-09-05 23:00
Close the issue if it's fixed

**Comment by AniLeo** [comment] 2020-09-06 06:00
Turning down resolution scale isn't anywhere near of a fix, but all of this issue is lack of performance on a mobile U CPU, so it's invalid either way

**Closed by AniLeo** 2020-09-06 06:00 UTC
