### ISSUE TITLE
[BLES01035] Call of Duty Black Ops - Access Violation error

### ISSUE THREAD

**Issue by QuaiGoner** [RPCS3/rpcs3#5725] opened 2019-03-15 11:22 UTC
Call of Duty Black Ops [BLES01035]
Emulator freezes after Access Violation error after playing last Intro video not even goes in to Menu
Default settings with exception of LLVM SPU Recompiler
Ryzen 2400g + GTX1050 Latest Drivers
[RPCS3.log](https://github.com/RPCS3/rpcs3/files/2970751/RPCS3.log)
Call of Duty Modern Warfare have simillar issue. but it goes in to menu (maybe because its menu does not have 3D graphics but Black Ops does) crashes after loading level
![image](https://user-images.githubusercontent.com/41058180/54428397-faf72480-474f-11e9-94a3-e0c4b5931358.png)
[RPCS3.log](https://github.com/RPCS3/rpcs3/files/2970772/RPCS3.log)
 If there is any additional info needed?

Same with Call of Duty World at War [BLES00404] but it can compile some shaders (3 actually)
![BLES00404](https://user-images.githubusercontent.com/41058180/54428756-07c84800-4751-11e9-8020-9a702a0f9b5a.PNG)
[RPCS3.log](https://github.com/RPCS3/rpcs3/files/2970797/RPCS3.log)

**Comment by QuaiGoner** [comment] 2019-03-15 11:28
Call of Duty Modern Warfare have simillar issue. but it goes in to menu (maybe because its menu does not have 3D graphics but Black Ops does) crashes after loading level
![image](https://user-images.githubusercontent.com/41058180/54428397-faf72480-474f-11e9-94a3-e0c4b5931358.png)
[RPCS3.log](https://github.com/RPCS3/rpcs3/files/2970772/RPCS3.log)

**Comment by QuaiGoner** [comment] 2019-03-15 11:35
Same with Call of Duty World at War [BLES00404] but it can compile some shaders (3 actually)
![BLES00404](https://user-images.githubusercontent.com/41058180/54428756-07c84800-4751-11e9-8020-9a702a0f9b5a.PNG)
[RPCS3.log](https://github.com/RPCS3/rpcs3/files/2970797/RPCS3.log)

**Comment by RainbowCookie32** [comment] 2019-03-15 16:58
Modern Warfare and World at War are marked "Intro", so it's not really surprising (or issue-worthy imo). One ID of Black Ops is marked Intro, the others are ingame, but it seems like it regressed. If you find when BO regressed, that'd be more useful, for regression tracking. The other two aren't unexpected behaviors, Intro games don't go much further than the menu or intro videos

**Comment by arcadee1977** [comment] 2019-03-16 10:20
Call of duty series have PC version too, why do you play it with RPCS3??

**Comment by elad335** [comment] 2019-05-08 14:26
Looks like someone tried to optimize the wrong way, will fix soon.

**Comment by QuaiGoner** [comment] 2019-05-08 14:33
Thank you very much, elad! Hope i helped

**Comment by elad335** [comment] 2019-05-08 14:48
Fixed by #5893.

**Comment by QuaiGoner** [comment] 2019-05-08 15:25
It does progress further with this fix, but now BO1 has this error
![image](https://user-images.githubusercontent.com/41058180/57387231-24787d80-71e0-11e9-8d89-c1dace05e8f9.png)

**Comment by elad335** [comment] 2019-05-08 15:32
@QuaiGoner Thats a different issue though, the original regression is fixed. I suspect one of the commits from the time it first regressed to latest master caused another regression for BO1 which you couldn't knew about.

**Comment by QuaiGoner** [comment] 2019-05-08 15:34
I should probably close the issue i think after your PR merges with master

**Closed** 2019-05-08 20:48 UTC
