### ISSUE TITLE
Bugs Ni No Kuni: Wrath of the white Witch [BLUS30947]

### ISSUE THREAD

**Issue by Oky12** [RPCS3/rpcs3#3335] opened 2017-08-28 13:11 UTC
I am Found Bugs in Ni No Kuni: Wrath of the white Witch [BLUS30947]. 
1. In the main menu looks very bright .....
2. Shadow (Look at the second screenshot)
3. Stuck after Cutscene animation

My Spec
Intel Core i5 4460 3.4Ghz
Ram 8Gb
Nvidia Gefoce GTX 1050 TI

i hope this Bugs is Fixed

![screenshot 125](https://user-images.githubusercontent.com/30838114/29774425-971999ce-8c2b-11e7-914c-6f2d25b7ed74.png)
![screenshot 126](https://user-images.githubusercontent.com/30838114/29774426-9726dfb2-8c2b-11e7-9d76-a1546333b43e.png)

**Comment by AniLeo** [comment] 2017-08-28 13:24
I'm guessing user error. Invalidate cache every frame should be off, but will check once you comply with guidelines.

---

**Please read [**the guidelines**](https://github.com/RPCS3/rpcs3/blob/master/CONTRIBUTING.md) before opening an issue.**

Remember that the GitHub Issue Tracker is not the place to ask for support or to submit Game Compatibility reports. You must use [**our forums**](https://forums.rpcs3.net/forum-18.html) for that.

**Comment by Oky12** [comment] 2017-08-28 13:28
i understand. so..... i close this issue or not?

**Comment by Asinin3** [comment] 2017-08-28 13:28
Shadow bug is caused by you not having invalidate cache every frame off most likely however on certain occasions it can still occur with it set to ON (I have a report on this already.)

Cutscene bug is tracked here: https://github.com/RPCS3/rpcs3/issues/2930 you must skip them before they finish currently.

The only thing that is odd to me is the white menu screen, haven't seen that before post log so we can see what build you're using.

**Comment by SaltyCucumber** [comment] 2017-08-28 13:58
@Oky12 Invalidate Cache Every Frame: false
Set this to on and try again, it's in GPU settings.

**Comment by Asinin3** [comment] 2017-08-28 13:59
Yeah, and if it fixes your issue then you can close this as the bugs are already being tracked. Make sure you check github and see if there isn't already a report on your issue before making one.

**Comment by AniLeo** [comment] 2017-08-28 14:12
Closing. Don't submit redundant or incorrect reports in the future.

**Closed by AniLeo** 2017-08-28 14:12 UTC
