### ISSUE TITLE
[BCES00511] Ratchet & Clank: A Crack in Time - Missing/Glitchy Texture

### ISSUE THREAD

**Issue by NoXCxC** [RPCS3/rpcs3#8086] opened 2020-04-23 16:01 UTC
Hello everyone,

I tried to run Ratchet & Clank a Crack In Time, and for the most part the game run pretty smooth. But there's some texture that are missing or won't be loaded in diffrent case. Here's some exemple:

This ennemy is firing at me and i'm losing life, but none of his shot are visible
![Sans titre](https://user-images.githubusercontent.com/46874841/80119716-59fdae80-858a-11ea-8382-8adecf134d7e.png)

Here i'm firing with one of the weapon and you can see on the statue that shots are registerd but there not showing either
![Sans titre2](https://user-images.githubusercontent.com/46874841/80119917-9c26f000-858a-11ea-8870-1bab9037d261.png)

The last one is a little diffrent since the texture of the water is visible, but kind of glitchy, and when you drop in water, RPCS3 start to loop the message texture missing in the log
![Sans titre4](https://user-images.githubusercontent.com/46874841/80120150-e1e3b880-858a-11ea-8804-95f6f1ffed06.png)

Game still can be played but kind of hard when you can't see ennemy shot

Tested on RPCS3 v0.0.9-10258-256c74de Alpha
Intel(R) Core(TM) i5-6600K overclocked at 4.3 GHz / 16 GB Ram / GTX 1060 6GB

[RPCS3.log](https://github.com/RPCS3/rpcs3/files/4523658/RPCS3.log)

**Comment by AniLeo** [comment] 2020-05-05 16:08
The water issue is likely related to unimplemented texture sampling #8154

**Comment by NoXCxC** [comment] 2020-05-05 16:19
Do you think that's the same reason for explosion and firing weapon texture not being shown?

I tried to go a little further in the game and encounter the same kind of bug in the space ship. None of the shot fired are shown on screen

**Comment by elad335** [comment] 2020-10-27 12:41
Duplicate of #8500, normally I had close the other one because its newer but its a more detailed report so closing this one.

**Closed by elad335** 2020-10-27 12:41 UTC
