### ISSUE TITLE
 J-Stars Victory VS+ Crashing issue 

### ISSUE THREAD

**Issue by Bensouda98** [RPCS3/rpcs3#13108] opened 2022-12-22 11:41 UTC
### Quick summary

Whenever you play J-Stars Victory VS+ when you do an ultimate attack or when enough time passes in the match the game just crashes. 

### Details

after checking the logs its seems that the one or more SPU threads crashes with non fatal unmapped memory error usually followed by a few more SPU threads crashing. in the official game list it is listed as playable for the disc version and not playable for the PSN version but no matter what version you are using the crash happens and no matter how good your hardware is the crash happens. 

### Attach a log file

[RPCS3.log.gz](https://github.com/RPCS3/rpcs3/files/10286551/RPCS3.log.gz)

### System configuration

Windows 11/I7 12700KF/RTX 3060 TI/Driver version 527.56 DCH

**Comment by Megamouse** [comment] 2022-12-22 11:52
Duplicate of #7858

**Closed by Megamouse** 2022-12-22 11:52 UTC
