### ISSUE TITLE
Ghostbusters: The Video Game [BLUS30307]: Major memory leak?

### ISSUE THREAD

**Issue by Shoegzer** [RPCS3/rpcs3#7209] opened 2020-01-07 00:48 UTC
Testing this game against commit e7845357e21bb79c799f2f0b9b99b80a713a000c, there seems to be a major memory leak that happens on loading.  The first time the game is run (before rpcs3 creates caches), it's possible to go ingame but it freezes a few minutes in.  With any subsequent attempts to load the game without first deleting caches, rpcs3 stops stops at 99% of building the spu cache and the system seems to run out of memory, slowing to a crawl in the process until rpcs3 crashes.  

Tested with linux mint 19.3, kernel 5.0 built with gcc 9.2.1.  

Logfile is here: [RPCS3.log.gz](https://github.com/RPCS3/rpcs3/files/4028403/RPCS3.log.gz)

**Comment by AniLeo** [comment] 2020-01-07 01:05
Duplicate of #7172

**Closed** 2020-01-07 01:05 UTC
Labels: Meta: Duplicate
