### ISSUE TITLE
Call of Duty Classic [NPEB00101] Wont work with LLVM Recompiler

### ISSUE THREAD

**Issue by bolsonaro18** [RPCS3/rpcs3#5604] opened 2019-01-27 23:29 UTC
Only boot with Interpreter(Fast) or (precise)

F {PPU[0x1000006] Thread (Miles Thread) [0x003635a8]} class std::runtime_error thrown: Unregistered PPU function

![codlog](https://user-images.githubusercontent.com/29050273/51808358-fa76fd00-2279-11e9-897d-b21da82ad6d9.png)

[RPCS3.log.gz](https://github.com/RPCS3/rpcs3/files/2800900/RPCS3.log.gz)

Config:
Windows 10 64-bit
GeForce GTX 1050
i5-7400@ 3GHZ
16GB RAM

**Comment by AniLeo** [comment] 2019-01-27 23:33
Duplicate of #2909

**Closed by AniLeo** 2019-01-27 23:33 UTC
