### ISSUE TITLE
Dragon Ball Raging Blast 2 [BLUS30581] Infinite Loading/ Trophy Set Data Processing

### ISSUE THREAD

**Issue by Jayzus3** [RPCS3/rpcs3#5088] opened 2018-09-05 23:12 UTC
Version: 0.0.5-7299

It's as the title says Game hangs on the initial processing Trophy Data screen. If I close this and reload then it hangs on the initial loading screen. 

This is with OpenGL and Vulkan using all default settings.

![stuck on trophy data](https://user-images.githubusercontent.com/43018364/45125843-6d060580-b13e-11e8-92f7-02701c6851ff.png)

Here is the error in the Log: 

E {PPU[0x1000014] Thread (DbPrize thread) [0x003056c4]} sceNpTrophy: sceNpTrophyRegisterContext(context=0x1, handle=0x1, statusCb=*0x6c6370, arg=*0x3c7db5a0, options=0x1)

SPECS:
CPU: Intel i7 - 7700K
GPU: Geforce GTX 1080
RAM: 8 Gigabytes

**Comment by AniLeo** [comment] 2018-09-06 00:03
Duplicate of #5056

**Closed by AniLeo** 2018-09-06 00:03 UTC
