### ISSUE TITLE
Borderlands 2: GOTY [BLES01684] only loadable #6572

### ISSUE THREAD

**Issue by ESRDEV** [RPCS3/rpcs3#6578] opened 2019-09-18 17:28 UTC
RPCS3 v0.0.7-8726-bd4d86f8 Alpha | HEAD | Firmware version: 4.85
Intel(R) Core(TM) i7-5960X CPU @ 3.00GHz | 16 Threads | 7.91 GiB RAM | TSC: Bad | AVX+
GeForce GTX 1080 Ti running on driver 436.30

Borderlands 2: GOTY [BLES01684] just loadble since #6416 (RPCS3 v0.0.7-8667) the game in the latest emulator versions #6572 gets infinite loop after game introduction or error occurs:
 
class std :: runtime_error thrown: Verification failed:
(in file C: \projects\rpcs3\rpcs3\Emu\RSX\VK\VKGSRender.cpp: 3212)

RPCS3 Log:
[RPCS3.log](https://github.com/RPCS3/rpcs3/files/3627636/RPCS3.log)

Screen:
![rpcs3-bl2-goty_error](https://user-images.githubusercontent.com/54099898/65170850-edcd3200-da1f-11e9-96dd-94bb9c481670.png)

**Comment by kd-11** [comment] 2019-09-18 18:56
Duplicate of https://github.com/RPCS3/rpcs3/issues/6540. I'm looking into it.

**Closed by kd-11** 2019-09-18 18:56 UTC
