### ISSUE TITLE
SDL controller handler causes crash when exiting games on macOS

### ISSUE THREAD

**Issue by saturnotaku** [RPCS3/rpcs3#15484] opened 2024-04-19 02:08 UTC
### Quick summary

When using a controller with the SDL handler, RPCS3 always crashes when exiting a game. 

### Details

When using RPCS3 for macOS with a non-DualShock controller and the SDL handler, the emulator always crashes upon exiting a game. I've tested with first- and third-party Xbox as well as an Amazon Luna controller, and the result is the same every time. The controller works while in-game but the emulator crashes with the error message in the screenshot whenever the game is exited. No such errors are observed when using an official DualSense or third-party DualShock 4 with their respective handlers enabled. The problem only occurs when using the SDL handler with non-Sony controllers.
<img width="563" alt="Screenshot 2024-04-18 at 9 03 02 PM" src="https://github.com/RPCS3/rpcs3/assets/39625857/5c2c06cc-8181-45f2-a58f-46a90975c650">

### Attach a log file

[RPCS3.log](https://github.com/RPCS3/rpcs3/files/15032151/RPCS3.log)

### System configuration

System: MacBook Pro 14 2021
CPU: M1 Max 10-core
GPU: M1 Max 32-core
RAM: 64 GB
OS: macOS Sonoma 14.4.1

**Comment by Megamouse** [comment] 2024-04-19 02:11
Duplicate of #14760

**Closed by Megamouse** 2024-04-19 02:11 UTC
Labels: Input, OS: Mac
