### ISSUE TITLE
Regression : Persona 5 wrong color issue (NVIDIA only)

### ISSUE THREAD

**Issue by M220** [RPCS3/rpcs3#4174] opened 2018-02-14 03:54 UTC
After merging #4093 PR that includs #4089 PR, Persona 5 shows wrong colors in main menu as can be seen : 
Screenshot from persona 5 gameplay on PS3 that is showing right color just like the RPCS3 before merging #4093 : 
![screenshot_ -](https://user-images.githubusercontent.com/26696487/36186896-31d204fa-1157-11e8-99dd-6d4f8e7b82b4.png)

Screenshot from RPCS3 after merging #4093 ( look at the color of chairs ) : 
![screenshot_ -](https://user-images.githubusercontent.com/26696487/36187039-fe4c5620-1157-11e8-97fc-b10156c4427a.png)

Edit : My GPU is GTX 1080ti and GPU Driver version is 390.78 ( i think, it's latest anyway because i updated it yesterday ;) )

**Comment by AniLeo** [comment] 2018-02-14 03:57
Need information. GPU and drivers.

**Comment by M220** [comment] 2018-02-14 10:54
Sorry i forgot it again 😄
Updated information just now

**Comment by 13xforever** [comment] 2018-02-14 19:19
Can confirm. Win10 1709, 1080 Ti, 390.77 drivers.

f908daf3 from Jan 19:
![f908daf3](https://user-images.githubusercontent.com/36445/36223319-db223f3c-11e5-11e8-9913-cdb546de84fc.png)

95c6ac69 from Feb 12:
![95c6ac69](https://user-images.githubusercontent.com/36445/36223329-e1b966a4-11e5-11e8-9a6f-bf39a0d325b4.png)

**Comment by kd-11** [comment] 2018-03-25 13:33
This bug is nvidia-specific. Tagging appropriately

**Comment by HerrHulaHoop** [comment] 2018-07-12 10:15
Contrary to what has been mentioned above, this bug was not caused by #4093 but was in fact caused by #4127. 

Intel(R) Core(TM) i7-3630QM CPU @ 2.40GHz | 8 Threads | 7.89 GiB RAM | AVX
NVIDIA GeForce GT 630M

<details>
<summary>PR #4093 - Colours are still accurate</summary>

![PR #4093 - Colours are still accurate](https://user-images.githubusercontent.com/31934788/42627045-81cb6e22-85e9-11e8-90f5-42c9d9cdda8a.png)
</details>
<details>
<summary>PR #4113 (Master just before #4127) - Colours are still accurate</summary>

![PR #4113 (Master just before #4127) - Colours are still accurate](https://user-images.githubusercontent.com/31934788/42627046-81ff3450-85e9-11e8-86be-c58e5b72add0.png)
</details>
<details>
<summary>PR #4127 - Colours are messed up</summary>

![PR #4127 - Colours are messed up](https://user-images.githubusercontent.com/31934788/42627049-82327892-85e9-11e8-99de-85540d757e5f.png)
</details>
<details>
<summary>Current master (#4872) - Colours are still messed up</summary>

![Current master (#4872) - Colours are still messed up](https://user-images.githubusercontent.com/31934788/42627050-82704884-85e9-11e8-9788-1168a3f3d2a0.png)
</details>

**Comment by ruipin** [comment] 2018-08-16 23:32
@al3x on Discord bisected this issue to commit https://github.com/RPCS3/rpcs3/commit/33bcdd476cea0a4c3a8960c4e7666db853bc1e01

Armed with that information, the only hunk in that file that seemed to change behavior (not just an optimization) was https://github.com/RPCS3/rpcs3/commit/33bcdd476cea0a4c3a8960c4e7666db853bc1e01#diff-9a62be0c4e83eae188cd568947c4b7a5L50. Reverting this hunk on the latest master (#4970) resolves the issue, as predicted.

I've tracked this down to the `RSX_FP_OPCODE_NRM` doing nothing. Moving that opcode so that it executes the `default` path is enough to resolve this issue, e.g.:

https://github.com/ruipin/rpcs3/commit/faed15cf7959fc251b1b00339e2503666ceb6ea0

I assume this opcode does normalization, though I have no idea why it needs to be clamped.

**Comment by kd-11** [comment] 2018-08-17 07:00
Its some kind of precision bug on nvidia hardware. Its absurd to need clamp on normalized result which means on nvidia normalize(n) can return nan or inf.

**Comment by kd-11** [comment] 2019-04-12 13:38
NRM(0) should and does return Nan. However on Geforce, clamp() affects nans and treats them as -INF instead of leaving them as-is. This causes NaNs to not propagate down the pipeline like they would on PS3. This build fixes this issue https://ci.appveyor.com/project/kd-11/rpcs3/builds/23802725.

**Comment by HerrHulaHoop** [comment] 2019-04-12 15:59
Confirmed! Bug is fixed in the linked build.
![rpcs3_kd11_p5colors_2019-04-12_21-27-17](https://user-images.githubusercontent.com/31934788/56050558-d6e82c80-5d69-11e9-8002-f71b690d490d.png)

**Comment by kd-11** [comment] 2019-04-25 13:46
Fixed by https://github.com/RPCS3/rpcs3/pull/5860

**Closed by kd-11** 2019-04-25 13:46 UTC
Labels: Driver: NVIDIA
