### ISSUE TITLE
Error when trying to play with microphone

### ISSUE THREAD

**Issue by JuanTheTropper** [RPCS3/rpcs3#13535] opened 2023-03-11 19:29 UTC
### Quick summary

The emulator won't let me play with my active microphone

### Details

Tried to play with microphone "Guitar hero - Warriors of rock"
The game works perfectly without the microphone but I want to use it

### Attach a log file

[RPCS3.log](https://github.com/RPCS3/rpcs3/files/10949276/RPCS3.log)

### System configuration

RPCS3 v0.0.27-14811-776b3b5e Alpha | master | FW 4.90 | Windows 10 22H2
AMD Ryzen 5 5600X | 12 Threads | 31.91 GiB RAM | AVX+ | FMA3
GPU: NVIDIA GeForce RTX 3060 (526.47)
microphone: logitech g733 (wireless)

**Comment by Megamouse** [comment] 2023-03-11 20:34
Duplicate of #11266

**Closed by Megamouse** 2023-03-11 20:34 UTC
Labels: Microphone

**Comment by JuanTheTropper** [comment] 2023-03-12 02:26
> Duplicate of #11266

no, my game crashes when I have the microphone connected
