### ISSUE TITLE
[Windows]Low FPS on Dragon Ball: Raging Blast

### ISSUE THREAD

**Issue by BlackShadow306** [RPCS3/rpcs3#3189] opened 2017-08-10 04:52 UTC
RPCS3 Log:

https://pastebin.com/Sp5ysyRE

My Specs:

AMD FX 8350 4.40GHz - Eight Core
8GB DDR3 2400MHz RAM - GSkill
Sapphire Toxic R9 280X 384 Bit 3GB
Windows 10 PRO - x64

**Comment by Asinin3** [comment] 2017-08-10 04:53
Low FPS isn't an issue if you wan't assistance you can ask on the EmuNewz forum or ask in discord.

**Comment by BlackShadow306** [comment] 2017-08-10 04:55
I also pasted my log maybe they can see something. Don't be so judgemental.

**Comment by Asinin3** [comment] 2017-08-10 04:58
Don't bother the developers asking them to help you, they are busy you are free to ask anywhere else... I'm offering you help and your not taking it. You will not be getting any assistance here.

**Comment by BlackShadow306** [comment] 2017-08-10 05:01
Ah, hello? I think you mistaken me here? If i wanted help i would go Discord right away. Also if you read any part of the issue, you'll see that i didn't even intended to use help word. I saw few errors on log so i decided to post it so i can help to developers. Christ.

**Comment by Asinin3** [comment] 2017-08-10 05:02
https://github.com/RPCS3/rpcs3/blob/master/CONTRIBUTING.md
At least read this before posting.

**Comment by BlackShadow306** [comment] 2017-08-10 05:06
The game works pretty fine on others, it's probaly related about my hardware. So let the devs check it out the post for a second.

**Comment by Asinin3** [comment] 2017-08-10 05:17
The game is slow because your hardware is not the best and your settings may not be optimal, the developers can't do anything with this. Apart from say "change x setting" as the emulator improves so will your speed.

**Comment by BlackShadow306** [comment] 2017-08-10 05:23
My hardware may not be the best but its still good.

https://www.youtube.com/watch?v=1b2UmR_W9kk

This guy has

i7 6700K (4.0 Ghz)
GTX 960
8GB DDR4

280X better than GTX 960 8350 may not better as 6700K but still catches up. For RAM's only difference is DDR Slot. And DDR3 and DDR4 theres no significant changes. Do you even know hardwares?

**Comment by Asinin3** [comment] 2017-08-10 05:30
You have an FX cpu which has low IPC (yes clock speed isn't the only thing that matters) it's very far off from a 6700k performance in RPCS3. GPU also barely affects RPCS3 as long as it supports Vulkan you will get decent performance as most of the work is being done on the CPU at the moment until things like the Vertex_rewrite are merged into the master which helps get the GPU usage up to around 40%

**Comment by Talkashie** [comment] 2017-08-10 05:34
FX 8350 is a weak processor to be brutally honest. It hasn't aged well.

**Comment by BlackShadow306** [comment] 2017-08-10 05:36
I'm not saying like FX-8350 is the best one in the market. But for RCPS3 is should be enough when they optimized it.

**Comment by slx7R4GDZM** [comment] 2017-08-10 05:38
https://www.anandtech.com/bench/product/1543?vs=697

**Comment by Asinin3** [comment] 2017-08-10 05:46
"Edit: You could been say something like RPCS3 isn't optimized for AMD yet. But blaming to my hardware like they're not really that good, it's just funny."
I have a ryzen r7 1700 overclocked to 3.9ghz it works fine on AMD the problem is that CPU in particular has a low IPC.

**Comment by SakataGintokiYT** [comment] 2017-08-10 05:49
@BlackShadow306 

Try with these settings : 
[CPU]

*Preferred SPU Threads: 1
*Additional Settings:
-Lower SPU thread priority
-SPU loop detection

**Comment by BlackShadow306** [comment] 2017-08-10 06:03
Found a fix by myself. And getting 50fps straight. Despite someone was saying my hardware was bad. Lol, sure.

**Comment by Asinin3** [comment] 2017-08-10 06:04
You found a fix by changing your settings, in which case providing a log achieved nothing.

**Closed** 2017-08-10 06:03 UTC

**Comment by paulsapps** [comment] 2017-08-10 06:45
Thanks for actually telling everyone what the "fix" is. Very helpful and totally not a waste of everyone's time..

**Comment by Asinin3** [comment] 2017-08-10 07:25
@paulsapps The video he linked was generally not above 50fps (outside the cinematic/fight transition) if he can achieve that high of a frame rate in rpcs3 he must've used liquid nitrogen to oc it. Yeah, doubtful
