### ISSUE TITLE
QTCore.dll crash with Top Spin 4 (fatal error)

### ISSUE THREAD

**Issue by Syl191** [RPCS3/rpcs3#6250] opened 2019-07-22 23:44 UTC
Hi, When i'm playing TS4 with the latest build, after 5min of playing i got a QTCore 5 fatal error message.
This happen with the 0.0.06-8406 build. This is not happening with an old version which is : 0.0.5 - 6887 and 0.0.5 - 6889. I have this message with my two PC (one with i5 4670k, GTX 970, and I7 7700, GTX 1060)

Vulkan and LLVM for both decoder (same for 0.0.5 - 6889 which is not having error)
 
Thanks you very much

Here is the message : 

![image](https://user-images.githubusercontent.com/16281142/61672237-2a640200-aceb-11e9-904d-f2b38080f672.png)

**Comment by AniLeo** [comment] 2019-07-22 23:44
Seems like a case of wrong DLLs

Upload your Qt5Core.dll here to check what version is it from

**Comment by Syl191** [comment] 2019-07-22 23:50
Wow, thanks for this fast answer
Sorry for the missing log file

Here's the two files needed.
[RPCS3.log](https://github.com/RPCS3/rpcs3/files/3419492/RPCS3.log)
[Qt5Core.zip](https://github.com/RPCS3/rpcs3/files/3419495/Qt5Core.zip)

Thanks you again

**Comment by AniLeo** [comment] 2019-07-22 23:51
The log is empty, but the DLL is the correct one, so it should be an actual issue with the GUI

**Comment by Syl191** [comment] 2019-07-22 23:52
This is the only log i have. I will delete it and retry the error.
Dou you want de Qt5gui file ?

**Comment by AniLeo** [comment] 2019-07-22 23:58
No need to check anything else on the QT Libraries

Just post a log file and steps to reproduce this with this game

**Comment by Syl191** [comment] 2019-07-23 00:02
Gotcha, this time with only 2minutes of playing. There is no particular steps to do, just playing the game and you will have this error. It can be 10 minutes like 1 minute.
The new log file is here
Thanks you.
[RPCS3.log](https://github.com/RPCS3/rpcs3/files/3419517/RPCS3.log)

**Comment by fithosxxx** [comment] 2019-07-29 20:12
Hi, I am also experiencing the same exact error message that will pop up within 5 to 10 minutes of playing Tales of Xillia 2. This is not happening on alder builds as well.

**Comment by Syl191** [comment] 2019-07-30 14:28
Hi,
Any news about this issue ? Thanks

**Comment by Syl191** [comment] 2019-08-10 21:20
Still here on newest builds

**Comment by Syl191** [comment] 2019-08-11 14:44
@AniLeo Anything about this ? I have made some test and with the 0.0.6-8200 build this is not happening. With today build i got the error. Thanks you and keep this amazing work

**Comment by Oorn** [comment] 2019-08-22 11:15
@AniLeo the issue seems to be Anti-Aliasing related - if AA is set to disabled, crash does not happen. Similarly, it does not happen on builds earlier than 8253.

Interestingly, emulation continues to work for a while after Fatal Error pops up - but oking fatal error dialog crashes it immediately.
(tested in Tales of Xillia 2 on 7972, 8231, 8253, 8300, 8566)

**Comment by digitaldude555** [comment] 2020-02-21 19:02
@Oorn @Syl191 Fixed now?

**Comment by AniLeo** [comment] 2020-03-31 13:23
Should be fixed, no reports of this happening with Top Spin 4 lately. Closing as fixed, if someone can still reproduce, ping for reopening.

**Closed by AniLeo** 2020-03-31 13:23 UTC
Labels: Need Information
