### ISSUE TITLE
Reflective/refractive materials rendering incorrectly in LBP1

### ISSUE THREAD

**Issue by ikzoid** [RPCS3/rpcs3#15539] opened 2024-04-30 23:25 UTC
### Quick summary

Reflective/refractive materials rendering incorrectly in LBP1.

### Details

Prize bubble is lacking reflection or refraction which it has on the PS3.
![image](https://github.com/RPCS3/rpcs3/assets/75356720/6b0cdcb3-c4b5-45f6-8575-dcb1f9eafcdb)
Buttons are transparent and have a ghost-like appearance to them.
![image](https://github.com/RPCS3/rpcs3/assets/75356720/29442387-d8cd-41f9-931c-2d60240175b2)
Glass is shiny and refractive on the PS3. On RPCS3, it is flat.
![image](https://github.com/RPCS3/rpcs3/assets/75356720/cd8a79c1-57b1-46e8-86d5-74a5c8911ad5)
Refractive objects almost seem to have a grid over them.
![image](https://github.com/RPCS3/rpcs3/assets/75356720/5b67b7b1-1c50-41be-a435-b4df94f8182a)

This issue doesn't seem to happen with water, just prize bubbles and glass.
Adjusting any RPCS3 settings from what is recommended on the wiki has no effect.

### Attach a log file

[RPCS3.log](https://github.com/RPCS3/rpcs3/files/15171989/RPCS3.log)

### Attach capture files for visual issues

[Capture 1 - Taken in Skate to Victory](https://www.dropbox.com/scl/fi/e2nzj4pf604zdcnrp2iil/BCUS98208_20240430172515_capture.rrc.gz?rlkey=t3e6m8azzqfue38e8lbkk2x57&st=lxzpxdg2&dl=1)
[Capture 2 - Taken in Swinging Safari](https://www.dropbox.com/scl/fi/kqsgz1u4upcxxpjk3ojdk/BCUS98208_20240430181056_capture.rrc.gz?rlkey=e0y1vcbl89elguyqd4jb4zlxr&st=cowsr134&dl=1)

### System configuration

Ryzen 7 7700X, 
RTX 3080 Ti, driver version 551.76. Absolutely no difference on 552.22.
Windows 10

**Comment by ItsLaguna** [comment] 2024-04-30 23:28
#11818 covers this iirc

**Comment by ikzoid** [comment] 2024-04-30 23:30
> #11818 covers this iirc
Looking at the screenshots on that issue, that looks markedly different from what I'm experiencing- though maybe related.

**Comment by TorutheRedFox** [comment] 2024-05-01 16:15
> > #11818 covers this iirc
> 
> Looking at the screenshots on that issue, that looks markedly different from what I'm experiencing- though maybe related.

it's the same thing but slightly different looking symptom

**Comment by ItsLaguna** [comment] 2024-05-01 21:42
> Looking at the screenshots on that issue, that looks markedly different from what I'm experiencing- though maybe related.

Just checked your log and saw you have Res Scale at 200%, which alleviates the stripping issue. I had mentioned it in the other issue, but had forgotten until now lmao.

**Comment by AniLeo** [comment] 2024-05-01 21:42
Closing as duplicate of #11818

**Closed by AniLeo** 2024-05-01 21:42 UTC

**Comment by AniLeo** [comment] 2024-05-01 21:47
PS: You need to use resolution scale at 100% to file these kind of bugs, as it can interfere with the results, that's why the guidelines say to use base settings and only change what is required for the game to work
