### ISSUE TITLE
Demon's Souls and Vulkan: very dark enviroment

### ISSUE THREAD

**Issue by oangelo** [RPCS3/rpcs3#3896] opened 2017-12-04 23:58 UTC
The pictures tell the whole story. Using the same configuration, changing only from OpenGL to Vulkan:
![screenshot_20171204_214141](https://user-images.githubusercontent.com/1669411/33582698-966e1dce-d93d-11e7-82e1-e77c144b3727.png)
![screenshot_20171204_215122](https://user-images.githubusercontent.com/1669411/33582699-968b6ac8-d93d-11e7-87fa-911144573d62.png)
I am using Archlinux, with nvidia driver extra/nvidia 387.34-7, and the video card is GeForce GTX 660 Ti.
rpcs3 version: rpcs3-v0.0.4-2017-12-02-bfb3144-9055_linux64.AppImage

**Comment by hcorion** [comment] 2017-12-05 02:46
duplicate of https://github.com/RPCS3/rpcs3/issues/3095

**Comment by kd-11** [comment] 2017-12-05 13:49
Closing as duplicate. Also it seems to be a driver bug since it affects a specific setup to trigger - not really too much we can do about that.

**Closed by kd-11** 2017-12-05 13:49 UTC
