### ISSUE TITLE
[Feature Request] Allow mouse cursor in full screen.

### ISSUE THREAD

**Issue by dawnbomb** [RPCS3/rpcs3#7977] opened 2020-04-07 11:26 UTC
For people with multiple monitors, i'm requesting a option (Probably in the global GUI menu) to turn on/off having mouse access while in full screen. This is useful for streaming, chatting on discord, or when net playing online with others over parsec.

I'm not sure why this wasn't a made optional when hiding the mouse was first implemented, and i can understand not regressing back to how it was in 2017, but surely it should just be a option we can turn on/off.

**Comment by Megamouse** [comment] 2020-04-08 15:17
I just tried, but it stays invisible. Maybe it's the nvidia driver

**Comment by vsub** [comment] 2020-04-08 18:03
Yes that will be a nice feature(the mouse disappearing was always bothering me)
Btw I just tried it on intel gpu and it also disappears

ppsspp,pcsx2 - disappears after a second of not moving it and appear when you move the mouse
Dolphin,Cemu - the mouse don't disappear

**Comment by auranticus** [comment] 2020-04-10 04:09
> Dolphin,Cemu - the mouse don't disappear

Dolphin's setting allows the mouse to be hidden, while in Cemu the mouse behaves the same as pcsx2

**Comment by dawnbomb** [comment] 2020-04-10 14:02
Yes, over history as far as i'm aware, *literally* every other popular emulator that anyone uses, each and every single one of them give you mouse access, let it appear when you move it, or make it a option in a options menu. RPCS3 is the only emulator to completely kill your mouse. This is 2020, lets fix it.

**Comment by bevanweiss** [comment] 2020-08-30 06:24
@dawnbomb @auranticus @vsub It would be appreciated if you could try out the PR and provide feedback around what other changes might need to be made to it to close out this issue (please comment against the PR itself).

**Comment by vsub** [comment] 2020-08-31 16:46
RPCS3 is not compiled anymore so unless a compiled version is posted,I cannot try it

**Comment by bevanweiss** [comment] 2020-09-08 04:22
@dawnbomb 
Is this still an issue, or did the mouse hide and lock changes address it?

**Comment by vsub** [comment] 2020-09-08 15:37
@bevanweiss 
The only problem I find is with the timer
If I set for example 5 seconds,this will happen

1.Go to full screen and the mouse disappear after 5 seconds which is the expected behavior
2.If move the mouse and stop moving it after 4 seconds,it will disappear after 1
3.If am still moving it after the 5 seconds,the timer starts again counting 5 seconds and when you stop moving it,the mouse will disappear after the time based on 5 second minus the elapsed time since the timer started.

It's not really a big deal because I can just move the mouse where I don't see it and disable the auto hiding feature

**Comment by Megamouse** [comment] 2020-09-08 17:00
should be fixed in #8868

**Closed** 2020-09-29 07:41 UTC
Labels: GUI
