### ISSUE TITLE
Gran Turismo 5 Issues

### ISSUE THREAD

**Issue by Herier44** [RPCS3/rpcs3#7984] opened 2020-04-08 01:23 UTC
## Quick summary
Game freezes and needs to be restarted, some graphics seems to be missing/have viewable wireframes.

## Details
-The game will run well for about an hour then it freezes(including sound) and needs to be restarted.

-Some graphics or textures don't seem to be loading at all and can be seen right through.

-You can see the wireframe of things when AA is turned on,  and it seems to be tracing them while moving(couldn't find anything on the second part so thought I'd include it).

- Windows 10, Ryzen 5 3600, Rx 5600 xt on the 20.2.2 drivers.

-Some of the files were too large to be put here so I uploaded them to my google drive:
https://drive.google.com/open?id=1hoDJInt_NcSPG27TWIeoFf3R1e6he-1y

**Comment by AniLeo** [comment] 2020-04-08 01:26
Wireframe is a known issue on that GPU architecture when using MSAA
Freezes are a general issue that don't warrant an issue unless a cause is detected but there are already many issues on GT regarding that
Duplicate of #6999

**Closed by AniLeo** 2020-04-08 01:26 UTC

**Comment by Herier44** [comment] 2020-04-08 01:33
Closed?  You didn't mention anything about the other two issues?
