### ISSUE TITLE
Sonic Unleashed (disc) regression

### ISSUE THREAD

**Issue by MinaeKitsune** [RPCS3/rpcs3#8123] opened 2020-04-30 04:26 UTC
## Quick summary
The game don't boot after the loading

## Details
Good : Build #8118 
Bad : Build #8121 
[RPCS3.log.gz](https://github.com/RPCS3/rpcs3/files/4556124/RPCS3.log.gz)
[RPCS3.log.gz](https://github.com/RPCS3/rpcs3/files/4556130/RPCS3.log.gz)

**Comment by elad335** [comment] 2020-04-30 04:32
try turning off tsx.

**Comment by MinaeKitsune** [comment] 2020-04-30 04:49
TSX ? What is that ? Can't find it in the config

**Comment by RainbowCookie32** [comment] 2020-04-30 04:50
It's a 2700x, no TSX there

**Comment by elad335** [comment] 2020-04-30 15:39
Maybe it's random, try build #8118 a few times and a build before it. #8121 is a TSX only change which is out of the perspective of affected builds on your hw config.

**Comment by AniLeo** [comment] 2020-04-30 18:34
Cannot reproduce.

![image](https://user-images.githubusercontent.com/10283761/80746363-ab251980-8b19-11ea-89e0-36ddfd211b7f.png)

**Comment by AniLeo** [comment] 2020-05-04 20:06
Will be closed if no one else can reproduce or provide steps for reproducing, since no one else is reporting this issue. Retry with latest build, clear caches if you have to.

**Comment by windwhirl94** [comment] 2020-05-11 16:57
FWIW, the provided logs are for Sonic Unleashed NPEB01347, PSN title, not Disc.

**Comment by AniLeo** [comment] 2020-05-11 18:12
Closing then since there's no issue

**Closed by AniLeo** 2020-05-11 18:12 UTC
Labels: Need Information
