### ISSUE TITLE
[Regression] VSH/XMB no longer works (#15496)

### ISSUE THREAD

**Issue by GoonyBaloney** [RPCS3/rpcs3#15529] opened 2024-04-29 14:02 UTC
### Quick summary

Trying to boot VSH/XMB gives you an error that says "This PS3 application has likely crashed, you can close it." and stayed on a black screen.

### Details

It worked fine on v0.0.31-16381-b38ce945 (commit b38ce945) and earlier.
but since v0.0.31-16387-e2402b1c (commit e2402b1c), when trying to boot VSH/XMB, a hint pops up that says "This PS3 application has likely crashed, you can close it." and the PPU compilation hint stays on indefinitely. It'll stay on a black screen until the emulation is stopped.

### Build with regression

v0.0.31-16387-e2402b1c

### Attach two log files

[before-regression.log.gz](https://github.com/RPCS3/rpcs3/files/15150065/before-regression.log.gz)
[after-regression.log.gz](https://github.com/RPCS3/rpcs3/files/15150066/after-regression.log.gz)

### System configuration

Windows 10 22H2
i7-7700K
GTX 1060 6GB (546.17)

### Other details

I did every troubleshooting method beforehand but it still won't boot in the latest version.

**Comment by st12q** [comment] 2024-04-29 16:07
Confirming, after updating RPCS3, XMB no longer works.
Firmware version: 4.91
F {PPU[0x1000000] Thread (main_thread) [0x0047aff8]} SIG: Thread terminated due to fatal error: Null function: sys_time_get_system_time
(in file D:\a\1\s\Utilities\JITLLVM.cpp:59[:22], in function null) (error=0x7e) - this is what it's writes in log in RPCS3 after trying boot into XMB.
It doesn't crash with Interpreter (static) on PPU.
Tried removing PPU, SPU and disk caches and creating LLVM caches from RPCS3, didn't helped.
System configuration:
Windows 11 23H2
i5 12400
RTX 4060 (552.22, Studio)
Log:
[RPCS3-XMB-Issue.log.gz](https://github.com/RPCS3/rpcs3/files/15151855/RPCS3-XMB-Issue.log.gz)

**Comment by AniLeo** [comment] 2024-04-29 16:22
Issue seems to be because sys_time_get_system_time is not declared as a NULL_FUNC syscall anymore @capriots from #15496

**Comment by capriots** [comment] 2024-04-29 16:27
Clearing PPU cache should solve it

**Comment by GoonyBaloney** [comment] 2024-04-29 16:31
> Clearing PPU cache should solve it

I did do that multiple times but the issue persisted

**Comment by AniLeo** [comment] 2024-04-29 16:34
From what I saw, it's because you unregistered a valid syscall, I pushed a fix on #15530

**Comment by capriots** [comment] 2024-04-29 16:50
From a quick glance it doesn't seem like VSH is using that other syscall. The problem is that I changed the name. @GoonyBaloney can you try deleting all the folders starting with "ppu-" in the cache folder and then start VSH again?

**Comment by AniLeo** [comment] 2024-04-29 17:08
@capriots you're right, a full clean of all the caches does work. I think my PR incorrectly fixes the issue by restoring the previous functionality (the 0x92 syscall calling 0x95 instead of the correct one).

Do you have any ideas on how to solve this without bumping the PPU cache version?

Also it doesn't help that we're missing a clean VSH PPU cache option in the UI, so I opened issue #15531

**Closed** 2024-04-29 17:25 UTC
Labels: Firmware: HLE, Regression, VSH

**Comment by Beathlefun** [comment] 2024-06-30 16:34
how do you clean the cache?
