### ISSUE TITLE
Missing completion notice and progress indicator for save loads.

### ISSUE THREAD

**Issue by schm1dtHL** [RPCS3/rpcs3#11183] opened 2021-11-21 22:10 UTC
## Issue summary + Details
When loading a savegame on RPCS3, after confirming that you wish to load the save, RPCS3 immediately loads it and dismisses the dialog, and does not show the progress of loading the save or a completion dialog when it is done.
I'm not sure why RPCS3 omits the 2 dialogs mentioned above, it might be due to load speed concerns and whatnot, but ideally the behaviour regarding those dialogs should be to keep them reasonably accurate to an actual PS3's behaviour. 

### Comparison with real PS3.
A real PS3 shows the progress of loading the savedata in it's overlay, and when the save load is completed, it shows a prompt stating that the load is complete, which is manually dismissed by the user, as can be seen here: https://youtu.be/1teXxtjYUzk?t=96
Here's RPCS3's behaviour for reference: https://streamable.com/svbork

Notes: Having a progress bar isn't strictly necessary, as systems with fast enough storage load saves quickly enough for it to be pointless to show in those cases, but the completion dialog should be present to match PS3 behaviour. Not sure if this affects saving games too as I'm not sure about how the PS3 behaves there, think it may also be affected though.

**Comment by Megamouse** [comment] 2021-11-21 22:38
Duplicate of #8900

**Closed by Megamouse** 2021-11-21 22:38 UTC
Labels: Meta: Duplicate, Savedata, Overlay
