### ISSUE TITLE
Vulkan: Hatsune Miku: Project DIVA F scaling issue

### ISSUE THREAD

**Issue by BlackRocksShooter** [RPCS3/rpcs3#1714] opened 2016-05-25 07:53 UTC
![vulkan problem](https://cloud.githubusercontent.com/assets/19566893/15531989/a9ed6b40-225d-11e6-9789-1f05b1ea1dc6.png)
I tried 3-4 RPCS3 but all make me the same problem "I speak of the newer ones like the one of today 05/25/2016"
is my problem or of RPCS3 emulator?
Video: Nvidia Geforce GTX 970

**Comment by raven02** [comment] 2016-05-25 14:24
It works fine in AMD but not Nvidia

**Comment by raven02** [comment] 2016-05-25 16:25
Probably change to title to "Vulkan : Hatsune Miku: Project DIVA F scaling issue"

**Comment by Nezarn** [comment] 2016-05-25 17:18
duplicate of #1655

**Comment by raven02** [comment] 2016-05-26 09:50
Does https://github.com/RPCS3/rpcs3/pull/1718 fix this scaling issue as well ?

**Comment by Nezarn** [comment] 2016-05-26 09:59
nope

**Closed** 2016-05-26 20:48 UTC
