### ISSUE TITLE
Broken Buggy UI

### ISSUE THREAD

**Issue by alkaris2** [RPCS3/rpcs3#9554] opened 2021-01-05 16:02 UTC
## Quick summary
The UI is completely broken and unusable

## Details

An application built with Qt5 I'd expected a usable GUI, but this is just so broken and unusable. Menus are all glitched, can't see anything that the UI is supposed to have.

#### 1. Please attach RPCS3's log.

[RPCS3.log](https://github.com/RPCS3/rpcs3/files/5771140/RPCS3.log)

#### 3. Please attach screenshots of your problem.

![flameshot_2021-01-06__01_19_52_AM](https://user-images.githubusercontent.com/73155407/103666064-0de18580-4fc4-11eb-9d28-55425d8d5300.png)
![flameshot_2021-01-06__02_03_52_AM](https://user-images.githubusercontent.com/73155407/103666074-1043df80-4fc4-11eb-9abd-755868e6ee28.png)

#### 5. Please provide your system configuration:
* **OS:** Manjaro Linux
* **CPU:** i7-7700K
* **GPU:** ASUS GTX 1070
* **Driver version:** 450.45.1

#### Please include.
I've tried both from source download straight from GitHub, and from AUR, both are broken the same way as shown in the screenshots provided.

this also pops up when running from CLI

```
Debugger: 0
Failed to set RLIMIT_MEMLOCK size to 2 GiB. Try to update your system configuration.
Gtk-Message: 02:12:12.945: Failed to load module "xapp-gtk3-module"
```

You shouldn't be needing to set RLIMIT_MEMCLOCK size on the system and should be left alone, and use the already set on RLIMIT_MEMCLOCK when it's set unlimited as reported by `ulimit`.

GTK3 xapp module  probably should be using GTK3_MODULES instead of GTK_MODULES and it'll find the correct files its suppose to use.

**Comment by AniLeo** [comment] 2021-01-05 16:08
Regarding the issue, the UI works fine on my install of Manjaro Gnome, this is related to a specific DE / config.

> You shouldn't be needing to set RLIMIT_MEMCLOCK size on the system and should be left alone, and use the already set on RLIMIT_MEMCLOCK when it's set unlimited as reported by ulimit.

It's RLIMIT_MEMLOCK and the default is 64kb, so yes, we need higher limit as 64kb is useless as it doesn't allow locking anything, it's a leftover from the 90s. Other limits such as max open files already got updated from 4k to 500k but limits like that one are still on ridiculous defaults.

**Comment by alkaris2** [comment] 2021-01-05 16:46
> It's RLIMIT_MEMLOCK and the default is 64kb, so yes, we need higher limit as 64kb is useless as it doesn't allow locking anything, it's a leftover from the 90s. Other limits such as max open files already got updated from 4k to 500k but limits like that one are still on ridiculous defaults.

thing is you can't change it on the user level, it has to be root, and even then it's hard-coded. It's been discussed elsewhere that there's a reason for the current limits, and whether if it should be 'few' or 'many' → https://github.com/kubernetes/kubernetes/issues/3595

Changing the limit in user level cannot be done unless you modify files or add an entry for it within `/etc/security/limits.d`

**Comment by AniLeo** [comment] 2021-01-05 17:23
Then use root to change it, no problem there. root is still an user and as an user you need to have access to elevated permissions for other operations such as package updates including installing the emulator itself. 

`sudo nano /etc/security/limits.conf` and add 

```
*               hard    memlock         unlimited
*               soft    memlock         unlimited
```

Or don't change it at all, the emulator will still work but you'll get more crashes and freezes as the emulator can't emulate memory locking correctly.

Either way, that's completely unrelated to the UI issue at hand, I'd guess your setup is overriding our program stylesheet and breaking things but this is way too broken for it to be that. As mentioned, can't reproduce on my Manjaro Gnome laptop and desktop, so can't know for sure.

**Comment by AniLeo** [comment] 2021-01-05 17:35
Of course you have to use root permissions to change it, limits.conf is owned by root. I just said how above - exactly by editing the limits.conf file and rebooting.

Either way, triaging this as an UI issue for anyone with Cinnamon that can reproduce and wants to debug/fix. I'm pretty sure we don't have any active contributors on Cinnamon though, so it could take a while before someone shows up.

**Comment by autofire372** [comment] 2021-01-05 18:17
Manjaro Cinnamon user here. Just compiled from source and tested, and I could not reproduce this issue.

**Comment by JohnHolmesII** [comment] 2021-01-06 06:44
Just installed Manjaro Cinammon fresh in a VM, also unable to reproduce.
@alkaris2 Do you have any custom themes installed or something? I imagine the issue is related to the gtk warning, but no one else seems to get them. Can you give more details about your system? You mention that it could be related to GTK3_MODULES, but that env isnt set by default in this fresh install. Do you have gtk2 installed on the side perhaps?

**Comment by YU2Lhr7U** [comment] 2021-01-10 12:52
Arch Linux using i3wm here, I have the same issue. All UI seems to be shifted a little to one side.
This occurs whether the window is tiled, floating or fullscreen.
[Screenshot](https://raw.githubusercontent.com/YU2Lhr7U/plzhltr/main/2021-01-10-134749_2365x680_scrot.png)

**Comment by alkaris2** [comment] 2021-01-25 09:46
I've come to learn that the UI rendering issue is a bug within Qt, not supporting render scaling properly.

If I create a startup script with the following the issue goes away.

```BASH
export QT_SCALE_FACTOR_ROUNDING=PassThrough
export QT_FONT_DPI=96
export QT_SCALE_FACTOR=1
```

Qt doesn't properly render its applications if the scaling is using fractional values less than 1. For example if you have scale rendering at 0.8 everything becomes garbled and glitched. It's not a matter of globally setting the scale display higher, especially for HIDPI monitors, it's more a matter of Qt fixing this and supporting fractional scaling, but the time being a temporary fix by externally setting the scale factor, either soft coding it.

**Comment by Megamouse** [comment] 2021-03-29 15:36
in order to enable PassThrough, try to boot rpcs3 with
--dpi-rounding 5

(https://doc.qt.io/qt-5/qt.html#HighDpiScaleFactorRoundingPolicy-enum)

The default is RoundPreferFloor

**Comment by Megamouse** [comment] 2021-03-29 15:39
alternatively you can disable hidpi with --hidpi 0

btw the env variable is called QT_SCALE_FACTOR_ROUNDING_POLICY and not QT_SCALE_FACTOR_ROUNDING.

**Comment by Megamouse** [comment] 2021-03-29 19:04
I'll close this issue since this seems to be either a Qt bug or a user environment problem.

A couple of fixes have been implemented and solutions/workarounds were proposed (by the author themself).

**Closed by Megamouse** 2021-03-29 19:04 UTC
Labels: Bug, GUI, OS: Linux
