### ISSUE TITLE
God Of war 2 hd.....blue and red interchange for vulkan.....and Open Gl :-cant increase size of screen

### ISSUE THREAD

**Issue by Alyn3103** [RPCS3/rpcs3#6370] opened 2019-08-18 08:10 UTC
Playing God of War 2 hd on rpcs3 --version 0.06--8512
Sys spec--i3 2120 3.3 Ghz and  a gt 710(overclocked)

heres the problem

Using vulkan as a renderer--

Blue and red colour interchanged
for example---blood appear as blue
also My fps Drops from 60 to 45
![Annotation 2019-08-18 130750](https://user-images.githubusercontent.com/54231190/63221605-38f1ec00-c1b9-11e9-9a66-67ebfc989a63.jpg)

Using Opengl as a renderer--

Fixes the colour issue and fps goes till  60
But i cant increase the size of the screen (even tried changing the resolution of desktop)
heres the orignal-
![Annotation 2019-08-18 130751](https://user-images.githubusercontent.com/54231190/63221727-ed404200-c1ba-11e9-9af6-1ec97da25ba0.jpg)
and after increasing screen size--
![Annotation 2019-08-18 131438](https://user-images.githubusercontent.com/54231190/63221773-8e2efd00-c1bb-11e9-8d5a-355dcaf4d7e6.jpg)

this is specifically not the problem with only god of war 2 hd as i tested opengl with  other games such  as demon soul or hatsune miku but still screen turns black after trying to change it

**Comment by Emulator-Team-2** [comment] 2019-08-18 08:19
Duplicate of https://github.com/RPCS3/rpcs3/issues/6103.
Close this issue.

**Comment by Alyn3103** [comment] 2019-08-18 08:21
Anything about the opengl problem?

**Closed** 2019-08-18 08:21 UTC

**Comment by Emulator-Team-2** [comment] 2019-08-18 09:08
@Alyn3103 
God of War 1/2 HD have the options to stretch the screen size to a full screen. 
Options:
-Full Screen / Full Frame.
