### ISSUE TITLE
Demon's Souls - [BLUS30443] crashes or freezes RPCS3 in first minute

### ISSUE THREAD

**Issue by GogzillaOG** [RPCS3/rpcs3#5171] opened 2018-09-24 21:33 UTC
On Vulkan RPCS3 crashes to desktop within 1 minute (got as far as character creation), on OGL it freezes within 30 secs.
Only way I got the game to work but with glitchy graphics is with Win8 compatibility, but framerate makes it unplayable.

Windows 10, version 1803
RPCS3 v0.0.5-7388-dab30c00 Alpha | HEAD
Intel(R) Core(TM) i5-7500 CPU @ 3.40GHz | 4 Threads | 15.97 GiB RAM | AVX+ | TSX
GTX 1060 6GB (Nvidia 411.63)

Any advice is welcome! Thanks in advance.

[RPCS3.log](https://github.com/RPCS3/rpcs3/files/2412957/RPCS3.log)

**Comment by mizinin** [comment] 2018-09-27 15:54
Same problem here on 4670k.

[RPCS3.zip](https://github.com/RPCS3/rpcs3/files/2424839/RPCS3.zip)

**Comment by SeppNel** [comment] 2018-09-27 20:02
Same here, only managed to get to the very first window (usually crashes while loading)
Messing around with the setting doesnt seem have any effect.

Windows 10, version 1803
RPCS3 v0.0.5-7402
i3-6100 CPU 3.70GHz | 4 Threads | 12 GB RAM | AVX+
GTX 1060 3GB (Nvidia 411.70)

[RPCS3.zip](https://github.com/RPCS3/rpcs3/files/2425712/RPCS3.zip)

**Comment by HerrHulaHoop** [comment] 2018-10-01 07:34
This seems to be a duplicate of #4861. All users here seem to have 4C4T CPUs.

**Closed** 2018-10-01 07:36 UTC
Labels: Meta: Duplicate

**Comment by GogzillaOG** [comment] 2018-10-01 09:41
I've managed to get it working on an older version (6697) with OGL and it actually works nice. You just gotta be patient in the beginning with shaders compiling, but there's no avoiding that and it stops/becomes a tiny rarity.

**Comment by mizinin** [comment] 2018-10-02 15:15
> This seems to be a duplicate of #4861. All users here seem to have 4C4T CPUs.

Problems are not related. In context of this issue I be able to start game and play some before freeze/crash. But in #4861 problem is happening on logo screen.
So I think this must be reopened. @AniLeo

**Comment by AniLeo** [comment] 2018-10-02 15:22
I'm pretty sure the root issue is the same, you even said Windows 8 compatibility mode fixes the crashes

**Comment by HerrHulaHoop** [comment] 2018-10-02 15:48
@mizinin Easiest way to check if this is a different issue is to find the PR that caused your issue. If that differs from the PRs causing the 4C4T and related issues, then this issue can be reopened. Would recommend joining our [discord server](https://discord.me/RPCS3) to debug this issue faster.

**Comment by elhaya** [comment] 2018-10-02 20:28
did any of you try to change the log level to 'fatal' (from success). to me it did wonders...

**Comment by SeppNel** [comment] 2018-10-03 13:06
@elhaya That actually worked! but now im stuck in the loading screen. I wonder why the log leves has any effect on the crashes.

**Comment by PCMR42** [comment] 2018-10-09 18:10
> did any of you try to change the log level to 'fatal' (from success). to me it did wonders...

tried it before, better but still crashes
