### ISSUE TITLE
Game crashing on open when using Vulkan

### ISSUE THREAD

**Issue by Tachmag** [RPCS3/rpcs3#9224] opened 2020-11-08 02:12 UTC
When booting the game using the Vulkan renderer, an error message is launched instead of the game launching. This does not happen when using OpenGL. 
Attached to this is the log file when using Vulkan. I've also attached the OpenGL log file in case its necessary.

[RPCS3_OpenGL.log](https://github.com/RPCS3/rpcs3/files/5505766/RPCS3_OpenGL.log)
[RPCS3_Vulkan.log](https://github.com/RPCS3/rpcs3/files/5505765/RPCS3_Vulkan.log)

System Configuration
OS: Windows 10
CPU: AMD FX-6100
GPU: Nvidia 970 GTX
Geforce Driven: 456.38

Note:
ReShade is not being used.

**Comment by birdcat87** [comment] 2020-11-13 21:27
So looking through the Vulkan log, the problem seems to be:

·! 0:00:14.255527 RSX: GPU/driver lacks support for float16 data types. All float16_t arithmetic will be emulated with float32_t.
·F 0:00:14.259071 SYS: 
Unhandled Win32 exception 0xC0000005.

Which leads to the segfault.  This seems to be a GPU driver problem with the emulation of float16 data types.  Thus I would recommend uninstalling the old NVIDIA drivers and installing the latest version of the NVIDIA GPU proprietary drivers and trying again. 

Furthermore, I would recommend changing your operating system to Linux if you can.  Windows 10 is a privacy nightmare, and GNU/Linux tends to have better application logging for debugging and more community support than Windows in no small part due to the distros being largely composed of Libre software.   RPCS3 does have a Linux version due to it also being free software (as in freedom), and since it emulates the PS3 instead of Windows, changing operating systems should not negatively affect the performance of RPCS3.

**Comment by RainbowCookie32** [comment] 2020-11-13 21:47
A clean drivers install is probably a good idea, but the lack of support for float16 data types is probably not the cause of this. As the error says, support is emulated instead.

There's also no need to recommend moving to Linux, especially just for RPCS3. The emulator works fine on both operating systems (and most people rely on certain apps that don't run on Linux, even under Wine/Proton, but that's off topic)

**Comment by Tachmag** [comment] 2020-11-15 22:41
I'll try re-installing my drivers then. Thanks for the help.

**Comment by Megamouse** [comment] 2021-10-04 19:33
did it help?

**Comment by Megamouse** [comment] 2021-11-16 00:45
Closing due to inactivity

**Closed by Megamouse** 2021-11-16 00:45 UTC
Labels: Need Information, Render: Vulkan
