### ISSUE TITLE
RPCS3 Disables CPU1 Thread after booting anything.

### ISSUE THREAD

**Issue by Swilleh** [RPCS3/rpcs3#16385] opened 2024-12-08 18:00 UTC
### Quick summary

RPCS3 Disables CPU1 Thread after booting anything.

### Details

After booting ANYTHING in the RPCS3 including PS3 Interface it disables cpu1 thread. 
Issue is still present after closing the emulator. Only pc restart helps.
Happens every time i boot anything in the emulator.
Clean RPCS3 still disables my cpu1 thread.
Someone else had a similar problem before. https://forums.rpcs3.net/showthread.php?tid=208470 (no one responded)
Starting any PC game before the emulator doesn't cause any issues until i boot anything in the emulator.
I've tried forcing the emulator to use only cpu1 and it actually uses it until i set it to use more than one. It's like it prefers to not use cpu1 at all.

![2024-12-08_19-28-04](https://github.com/user-attachments/assets/23c6f497-e8a6-4b83-bc82-d0676c78d6f5)

### Attach a log file

[RPCS3.zip](https://github.com/user-attachments/files/18053368/RPCS3.zip)

### System configuration

Ryzen 5 3600 **Not overclocked**
24gb ram: **2x8gb Goodram 3200mhz + 1x8gb Crucial 2133mhz AUTO boosted until 3200mhz**
GPU1 **Gigabyte GTX 950 2GB**
GPU2 **Asus Dual GTX1060 6gb OC version <Main GPU 560.94 Nvidia Driver.**
SSD WD 240gb **Windows 10 Pro 22H2 19045.5131**
HDD 1TB **Clean RPCS3**
Nvme m2 SSD 512gb **Main RPCS3**

**Comment by Swilleh** [comment] 2024-12-08 18:51
> Try to refresh the game list repeatedly, I am interested to know if it behaves any differently there when no game is running

Before restarting PC: nothing changed
After restarting PC: Nothing changed
Before booting the game: nothing changed
While the game is booting: nothing changed
After the game has been closed: nothing changed.

**Comment by Darkhost1999** [comment] 2024-12-08 19:08
Thread Scheduler Mode: Operating System
Is in your original log.
What happens with RPCS3 Scheduler or RPCS3 Alternative Scheduler in the CPU tab of your config?

If 1 of them work let's let a maintainer close the issue or observe why operating system doesn't work.

**Comment by Swilleh** [comment] 2024-12-08 19:17
> Thread Scheduler Mode: Operating System Is in your original log. What happens with RPCS3 Scheduler or RPCS3 Alternative Scheduler in the CPU tab of your config?
> 
> If 1 of them work let's let a maintainer close the issue or observe why operating system doesn't work.

are you talking about this? I've tried to enable this thing to see if it would fix anything. That issue appeared before i've enabled it. I had it enabled when saving the log. After that i've disabled it.
My config was set to default.
![2024-12-08_22-14-49](https://github.com/user-attachments/assets/8eb55f2d-857b-4368-adfe-ada9da5d34e4)

**Comment by Swilleh** [comment] 2024-12-08 19:26
> Thread Scheduler Mode: Operating System Is in your original log. What happens with RPCS3 Scheduler or RPCS3 Alternative Scheduler in the CPU tab of your config?
> 
> If 1 of them work let's let a maintainer close the issue or observe why operating system doesn't work.

Oh, i didn't understand what you meant by that. I just tried both of them in the config and nothing changed.

**Comment by Megamouse** [comment] 2024-12-09 07:44
Probably duplicate of #14517

**Comment by Swilleh** [comment] 2024-12-09 09:52
> Probably duplicate of #14517

Thanks! Installing the latest audio driver for my motherboard did fix it! 
![image](https://github.com/user-attachments/assets/07cfcfd2-dc78-4cdb-bebf-f9b8f01ccb11)

**Closed** 2024-12-09 09:53 UTC
