### ISSUE TITLE
some strange sort of issue #4981

### ISSUE THREAD

**Issue by kabosov333** [RPCS3/rpcs3#13571] opened 2023-03-22 10:24 UTC
### Quick summary

when im playing skate 3 im randomly falling under the map for some period
i attached a video with moment of that bug with game log 
https://user-images.githubusercontent.com/128589594/226865348-326141f4-ce92-47ee-9092-f337e6286ca8.mp4

### Details

also here are my game settings (i attached all sections just in case)
![Снимок экрана 2023-03-22 135243](https://user-images.githubusercontent.com/128589594/226867439-5876a941-5855-4df5-8e58-c404e274f4fb.png)
![Снимок экрана 2023-03-22 135306](https://user-images.githubusercontent.com/128589594/226867442-2c2e8cc3-9c53-43c3-86a0-d7b70b7200b4.png)
![Снимок экрана 2023-03-22 135430](https://user-images.githubusercontent.com/128589594/226867512-0b5a0740-374f-4476-8512-0899740e85e2.png)
![Снимок экрана 2023-03-22 135418](https://user-images.githubusercontent.com/128589594/226867523-e254aacd-22bf-41f8-a8c6-7140d6bbb081.png)
![Снимок экрана 2023-03-22 135404](https://user-images.githubusercontent.com/128589594/226867527-a08e3698-598e-4962-abf6-b33e532b42f2.png)
![Снимок экрана 2023-03-22 135349](https://user-images.githubusercontent.com/128589594/226867529-49e9ed8e-d0f7-4b87-94af-9abde1838d8b.png)
![Снимок экрана 2023-03-22 135327](https://user-images.githubusercontent.com/128589594/226867532-10eab448-f5b3-4744-854d-9f96c81ca7c8.png)
![Снимок экрана 2023-03-22 135504](https://user-images.githubusercontent.com/128589594/226867534-92be4d55-f1b6-4333-b455-8c6d9006c5be.png)
![Снимок экрана 2023-03-22 135447](https://user-images.githubusercontent.com/128589594/226867537-fc8adeab-f230-440c-a010-2e7298af6a1b.png)

### Attach a log file

https://user-images.githubusercontent.com/128589594/226874298-eb7e9257-aaa6-4e76-94a0-8394c3875ec2.mp4

the same video, but got to attach to get permission to publish(sorry i couldnt crop video)

### System configuration

acer aspire 3
amd ryzen 5 3500u w/ radeon vega mobile gfx 2.10ghz
amd radeon vega 8 graphics
5.94 gigabytes of ram

### Other details

And yeah ik that issue of such kind was already discussed but i couldnt fix it with that thread

**Comment by MSuih** [comment] 2023-03-22 14:32
1. You seem to have changed xfloat accuracy to relaxed, which is known to affect things like physics simulation. Try changing this back to approximate.
2. You're below our recommended system specs and Skate 3 is notable for not running well on weaker hardware. This could also be causing issues if the time between each physics simulation steps is too long.
3. Your log shows that you're compiling SPU modules while this happens, which probably makes performance even worse. These should get rarer if you keep playing the game.

I'm closing this issue as it seems to be caused by hardware that is below our recommendations or invalid configuration.

**Closed by MSuih** 2023-03-22 14:32 UTC

**Comment by kabosov333** [comment] 2023-03-23 17:58
> 1. You seem to have changed xfloat accuracy to relaxed, which is known to affect things like physics simulation. Try changing this back to approximate.
> 2. You're below our recommended system specs and Skate 3 is notable for not running well on weaker hardware. This could also be causing issues if the time between each physics simulation steps is too long.
> 3. Your log shows that you're compiling SPU modules while this happens, which probably makes performance even worse. These should get rarer if you keep playing the game.
> 
> I'm closing this issue as it seems to be caused by hardware that is below our recommendations or invalid configuration.

Thanks for commenting, but i already fixed this bug, i just swithced llvm to asmjit. But got another problem :/
