### ISSUE TITLE
Heavenly Sword Shadows Display Improperly

### ISSUE THREAD

**Issue by HyperBitHero** [RPCS3/rpcs3#7869] opened 2020-03-26 18:10 UTC
## Quick summary
Heavenly Sword seems to be pretty perfect aside from the shadows that display improperly. It's a weird phenomenon where, as you move closer towards shadows, they regress and disappear. The same thing happens to the entire area if you move the camera; shadows will shift and move around the entire area. Basically, as you move around, the shadows are constantly shifting and wrapping around the entire area. 

## Details
Using a Ryzen 3950x and RTX 2080 Super. Win 10.
RSX Log: https://mega.nz/#!cfhVgKzZ

I've included some examples.
![screenshot-2020_03_26_16_33_17](https://user-images.githubusercontent.com/62716880/77681192-5ea96400-6fd8-11ea-8550-5532644b67f4.png)
![screenshot-2020_03_27_00_14_32](https://user-images.githubusercontent.com/62716880/77681240-6832cc00-6fd8-11ea-9ee2-ac1279e999d2.png)
![screenshot-2020_03_26_16_09_16](https://user-images.githubusercontent.com/62716880/77681264-6cf78000-6fd8-11ea-8152-7f27d02d4fcf.png)
![screenshot-2020_03_26_16_11_32](https://user-images.githubusercontent.com/62716880/77681286-74b72480-6fd8-11ea-8620-f39d0db4c68d.png)

**Comment by jokoputera** [comment] 2020-03-27 03:55
Log please. If you can, please also log the last version that worked correctly.

**Comment by RainbowCookie32** [comment] 2020-03-27 03:57
Not everything is a regression, and a log wouldn't be too helpful here since it's a graphical issue. RSX captures would be more useful

**Comment by kd-11** [comment] 2020-03-31 10:57
This is a known issue. The shadows in this game never actually rendered correctly.

**Comment by jokoputera** [comment] 2020-06-06 20:59
Kindly check with this:
https://github.com/RPCS3/rpcs3/pull/8367

**Comment by kd-11** [comment] 2020-07-09 16:31
Fixed by https://github.com/RPCS3/rpcs3/pull/8575.

**Closed** 2020-07-10 12:59 UTC
Labels: Bug, RSX
