### ISSUE TITLE
Loading screen error past build (#11935)

### ISSUE THREAD

**Issue by cooors** [RPCS3/rpcs3#12609] opened 2022-09-04 23:38 UTC
### Quick summary

Loading screen for Installing Trophies overlaps the game and doesn't let you move past the main menu.

### Details

Seems that for every build past #11935 (not including it since #11935 does work) causes a loading bar with text saying "Installing Trophies..." above it to appear over Silent Hill HD Collection and not disappear. This was not happening for other games.
You can move around in the main menu but clicking on anything causes it to stop letting you move around. It does not let you play past the main menu.

I am on Manjaro Linux. I will attach screenshot of the loading screen overlap.

### Attach a log file

[RPCS3.log.gz](https://github.com/RPCS3/rpcs3/files/9485691/RPCS3.log.gz)

### Attach capture files for visual issues

![image](https://user-images.githubusercontent.com/98668907/188337867-e57ca4aa-9ebe-4dd0-9640-9a7e22e6a17b.png)

### System configuration

![image](https://user-images.githubusercontent.com/98668907/188337903-51612382-e654-47e4-b862-ecb95727cd55.png)

**Comment by AniLeo** [comment] 2022-09-05 00:29
The build after that one only touches HLE code that is not actually used since the lib is loaded from firmware by default, very sure it can't cause this issue

**Comment by cooors** [comment] 2022-09-05 00:33
> The build after that one only touches HLE code that is not actually used since the lib is loaded from firmware by default, very sure it can't cause this issue

No idea man, I don't know anything about this. All I know is that the #11935 and all the ones before it I opened worked and anything after that I tested didn't. I didn't test all of them just skipped around until I found the most recent working version.

**Comment by Megamouse** [comment] 2023-01-31 22:01
Is this still happening?

**Comment by SpoonyOrbit** [comment] 2023-02-14 09:09
Yes this is still happening

**Comment by Megamouse** [comment] 2023-06-16 22:59
Please test with https://github.com/RPCS3/rpcs3/pull/14040

**Comment by AniLeo** [comment] 2023-06-24 15:48
Duplicate of #12862

**Closed by AniLeo** 2023-06-24 15:48 UTC
Labels: Regression, Trophies
