### ISSUE TITLE
rsx/vulkan: AMD driver crash while using ASync + Shader Interpreter mode

### ISSUE THREAD

**Issue by gudiofor** [RPCS3/rpcs3#8200] opened 2020-05-12 19:19 UTC
**- full logs:**

https://textbin.net/aoahStRtgw

**- screenshots:**
https://i.imgur.com/4tdYbCS.png

**- System configuration**

OS: Windows 10 pro 1909
CPU: AMD Ryzen™ 5 3600 6-core processor 3.99 Ghz
GPU: Rx 590 8GB sapphire
Driver version: 20.2.2

**Comment by LaneSh4d0w** [comment] 2020-05-12 19:20
What's the issue though ? Apart from the thread name, you litterally do not explain what's going on.

**Comment by RainbowCookie32** [comment] 2020-05-12 19:23
I think that the Shader Interpreter can cause that kind of crash. Try using just Async

**Comment by gudiofor** [comment] 2020-05-13 00:36
> Eu acho que o Shader Interpreter pode causar esse tipo de falha. Tente usar apenas Async

This solved the problem, but I had a minimal drop in performance, but I can play until then. After I did that I managed to get past the stage where I was giving the error, I will later continue the game and if there is an error again I will return here in this publication.

**Comment by kd-11** [comment] 2020-05-13 20:17
Duplicate of https://github.com/RPCS3/rpcs3/issues/8159

**Closed by kd-11** 2020-05-13 20:17 UTC
Labels: Bug, Render: Vulkan, Shaders
