### ISSUE TITLE
RPCS3 freezes at random intervals in Ridge Racer 7 BCES00009

### ISSUE THREAD

**Issue by eSportsRat** [RPCS3/rpcs3#11134] opened 2021-11-10 17:36 UTC
## Quick summary
When playing the BCES00009, the emulator will freeze to the point where a CTRL-ALT-DEL is required.

## Details
An issue has appeared with this title since circa update 0.0.8, in which an update was introduced to fix a stage loading in as completely black. I've gone back and forth between different versions of RPCS3 with default settings (though I at points also tried messing with settings to no avail), and have found that the last version without the freezing issue was 0.0.7-9102.

The freezes themselves seem entirely timebased, happening about 15-30 minutes into gameplay. Up until the freeze, everything plays perfectly. Upon the emulator freezing, the PC will lock up entirely, though sounds from the game can still be heard. The only way to get back control is by hitting CTRL-ALT-DEL.

#### 4. Please provide comparison with real PS3.
Freezing issue doesn't occur on my Slim PS3.

#### 5. Please provide your system configuration:
* OS
Windows 10 Home
* CPU
Ryzen 5 2400G
* GPU
Radeon RX 580 4GB
* Driver version
Radeon Software 21.8.2
* etc.
16 GB RAM, NVMe drive

#### Please include.
* Anything else you deem to be important
Issue seems to differ from other open issues including this title, as it is not related to the car viewing mode, or similar menus. The freeze happens regardless of gameplay events and menus, and seems to be almost entirely related to time and or having loaded multiple tracks.

[RPCS3.zip](https://github.com/RPCS3/rpcs3/files/7514785/RPCS3.zip)

**Comment by YuriNator557** [comment] 2021-11-10 18:02
Seems to be a duplicate of #9380

**Comment by eSportsRat** [comment] 2021-11-10 18:05
> 
> 
> Seems to be a duplicate of #9380
No, I have no crashing issue when pressing start at the title screen. That is not the issue I've described here

**Comment by YuriNator557** [comment] 2021-11-10 18:08
> > Seems to be a duplicate of #9380
> 
> No, I have no crashing issue when pressing start at the title screen. That is not the issue I've described here

Sorry I didn't read the issue properly, though RPCS3 shouldn't be locking your PC up

**Comment by Virtua64** [comment] 2021-11-15 22:06
Looking at your log file, it looks like you downloaded the game from the internet.  You shouldn't submit issues on here with pirated games since many of them online are broken and will cause issues with RPCS3..

**Comment by eSportsRat** [comment] 2021-11-15 22:16
> 
> 
> Looking at your log file, it looks like you downloaded the game from the internet. You shouldn't submit issues on here with pirated games since many of them online are broken and will cause issues with RPCS3..


That's true, I don't own a BD-R drive, so I can't dump my own game. Aside from that though, my issues with earlier versions line up with other reports, so the copy of the game doesn't seem to be the issue

**Closed** 2021-11-15 22:26 UTC

**Comment by postalesdeamor** [comment] 2021-12-30 08:03
The same thing happens to me. The game works once yes and once no, intermittently. This did not happen in previous versions of RPCS3 (although I do not know in which version it started to crash).

`E SELF: SELF: Failed to decrypt metadata info!
E SELF: SELF: Failed to load SELF file metadata!
E SYS: Failed to decrypt SELF: D:/hyperspin/Emulators/RPCS3/dev_hdd0/game/BCES00009/USRDIR/main.self
F sys_process: Failed to boot from exitspawn! (path="D:/hyperspin/Emulators/RPCS3/dev_hdd0/game/BCES00009/USRDIR/main.self", error=Failed to decrypt content)`
