### ISSUE TITLE
[BLUS30073] Stuntman Ignition Crash

### ISSUE THREAD

**Issue by SlipKnotSic** [RPCS3/rpcs3#14567] opened 2023-08-28 05:37 UTC
### Quick summary

Stuntman Ignition v01.11 crashes in game after starting career level, And will crash on all others, I am Positive

### Details

F {PPU[0x1000000] Thread (main_thread) [0x0040b2e4]} VM Access violation reading location 0x20871880 (unmapped memory)(first level)
VM Access violation reading location (unmapped memory) error code is gonna be different with every other start of career level, 
some levels infinite load, with no error in rpcs3 log box, I have tried different configs still crash same VM access error Even tried the existing "patch" patch says may still crash, meaning will, as I tested it so (doesn't work) as the vm access violation reading location also varies from level, P.S some textures appear broken in game in different levels I can't provide a RSX capture because it wont let me drop the archive says wrong format, some textures load just fine while other times they appear broken, if I remember correctly. [End Of Description] 

### Attach a log file

[Stuntman Ignition [BLUS30073].log](https://github.com/RPCS3/rpcs3/files/12450456/Stuntman.Ignition.BLUS30073.log)

### System configuration

x64 windows 10, Rog Crosshair VIII Dark Hero, NVIDIA GeForce RTX 4080, AMD Ryzen 9 3950X, Mastercooler Rm1000x Cpu Cooler,
1000W power supply (Forgot Model)

**Comment by FlexBy420** [comment] 2023-08-28 05:42
Duplicate of #10954

**Closed** 2023-08-28 05:43 UTC

**Comment by SlipKnotSic** [comment] 2023-08-28 06:17
> Duplicate of #10954
Not Really In My Opinion as I listed More Issues

**Comment by CookiePLMonster** [comment] 2023-08-28 08:34
> Not Really In My Opinion as I listed More Issues

I made this shaky "patch" you used to advance further through the game, and I absolutely cannot guarantee that those other issues (infinite loading, corrupted textures) are not caused by it. For this reason, IMO these issues should not be tracked until https://github.com/RPCS3/rpcs3/issues/10954 is fixed, and the "patch" is removed entirely.
