### ISSUE TITLE
Skylanders Imaginators sensei skylanders not working

### ISSUE THREAD

**Issue by Borotalko** [RPCS3/rpcs3#10713] opened 2021-08-15 14:31 UTC
Whenever i create a sensei skylander the game shows that the figure is corrupt but when i use any other skylander from other games the skylanders work fine. Trying to recover the skylander does nothing and returns you to the same screen. 

Windows 10
AMD Ryzen 5 2600X Six-Core Processor
NVIDIA GeForce GTX 1660 Ti
Driver version 10.0.19041.789

![Screenshot_1](https://user-images.githubusercontent.com/88975596/129481918-9413276b-af5c-4e81-93aa-b03e4afc6b21.png)

**Comment by RipleyTom** [comment] 2021-08-16 06:49
Duplicate of https://github.com/RPCS3/rpcs3/issues/9449

**Closed by RipleyTom** 2021-08-16 06:49 UTC

**Comment by GiacomoMaresca** [comment] 2021-08-28 15:15
it happens to me too

**Comment by GiacomoMaresca** [comment] 2021-08-28 15:16
i can't use sensei and i can't find the creation crystals

**Comment by GiacomoMaresca** [comment] 2021-08-28 15:17
how can i fix?

**Comment by AniLeo** [comment] 2021-08-28 15:18
Duplicate of #9449
