### ISSUE TITLE
RDR with TSX

### ISSUE THREAD

**Issue by mika123565** [RPCS3/rpcs3#8587] opened 2020-07-14 01:39 UTC
Me again. lol
RDR on 8700k with tsx. The game glitches after I cross the rail road on the horse.

The horse just starting to float in the air. If you go down, the character just stays.

Music, menu are all working. Nothing crashes...

https://postimg.cc/gallery/bwL7r1T

**Comment by Yahfz** [comment] 2020-07-15 13:36
Run the game again, reproduce the issue and post the log.

**Comment by mika123565** [comment] 2020-07-15 19:15
Thanks for the answer. 
I just did. However, I went a bit further without tsx, but not too much. 
Enabled tsx. Same thing, it either like textures half loading and the character stops moving, or the game just freezes during loading screens.
[RPCS3.log](https://github.com/RPCS3/rpcs3/files/4927469/RPCS3.log)

**Comment by elhaya** [comment] 2020-07-16 04:47
I think the bug is caused by relaxed z-cull

**Comment by mika123565** [comment] 2020-07-16 05:09
If I have it on without tsx, it runs fine, playable to me. But with tsx on and z -cull off I get line 5-7 fps less which is noticeable...

**Comment by GreenEagle555** [comment] 2020-07-21 05:11
9700k here, couldn't recreate the glitch mentioned but I recall playing a few days ago and the game freezing during loading screens multiple times. Seemed to get better after the shaders were cached.

**Comment by mika123565** [comment] 2020-08-11 00:15
Yes. I seem can't have both tsx and z-cull enabled at the same time. I get infinite loading screens all the time.

**Comment by mika123565** [comment] 2020-09-02 04:26
Any updates on that?

**Comment by AniLeo** [comment] 2020-10-19 15:39
Should be fixed, there were several TSX related bugfixes

**Comment by mika123565** [comment] 2020-10-20 00:17
Guys. Thank you for your hard work on this emulator. 
I just tested on 11042 build. 
No issues with tsx on AND relux zcull!!!! I played around 40 min and it used to give me infinite loading screens or weird glitches. No issues so far!

**Closed** 2020-10-20 00:24 UTC
Labels: Need Information

**Comment by mika123565** [comment] 2020-12-06 08:04
You can reopen this guys... I tried updating the 11042 build and we back again with the same issue, All good on 11042 though.
