### ISSUE TITLE
REGRESSION: P5 Artifacts, Vega 56 Not in #4113

### ISSUE THREAD

**Issue by meladath** [RPCS3/rpcs3#4132] opened 2018-01-30 22:50 UTC
Tested on RPCS3 v0.0.4-6368-70fe0cc22 Alpha | master
However also noticed on 4f7d3e5d

Does not occur on d37aa466

4790K, Vega 56

https://i.imgur.com/TwXzqeX.jpg
https://i.imgur.com/TLMVegj.png

See artifacts around the black shapes surrounding the menu.
Also occurs in intro cutscene (not menu) and door model during transition into velvet room.

[RPCS3.log.gz](https://github.com/RPCS3/rpcs3/files/1679734/RPCS3.log.gz)

**Comment by Asinin3** [comment] 2018-01-30 22:51
Image doesn't work and no log. I'm guessing https://github.com/RPCS3/rpcs3/pull/4127 was the cause but can you please try some different builds to figure it out?

**Comment by kd-11** [comment] 2018-01-31 14:19
Does reverting https://github.com/RPCS3/rpcs3/commit/4f7d3e5dc1932e32b682858b70d69c3f536d94c0 fix it? In that case I'd like to get a list of GPUs which need explicit subpass dependecies to work correctly. Usually only newer GCN since tonga might be affected with the increase in hardware dispatch units and asynchronous draw execution.

**Comment by meladath** [comment] 2018-01-31 22:45
I have tested the most recent master builds. The problem occurs with 4f7d3e5 and after. Reverting 4f7d3e5 fixes the issue. Not sure about the list of GPU's, would be nice if anyone could help out. I have a 290 lying around I could test with if needed. This issue occurs on my Vega 56.

**Comment by kd-11** [comment] 2018-02-01 06:21
The GCN 1.0, 1.1 and 1.2 chips should be fine, its a known issue due to the bump in ACE units on later models making draws execute without strict ordering. Does strict mode help hide the bug? I'm working on a proper solution that should not need manually tracking chip types.

**Comment by kd-11** [comment] 2018-02-01 07:50
Check if https://ci.appveyor.com/project/kd-11/rpcs3/build/0.0.4-1321 fixes the issue.

**Comment by kd-11** [comment] 2018-02-01 08:46
https://github.com/RPCS3/rpcs3/pull/4136 is confimed to fix the RAW hazard on framebuffers

**Comment by JoJose89** [comment] 2018-02-01 09:51
Not sure if all that related with this, but with this build I have "grayer" (?) colors here and there with my GT630 (old GPU, I know). For example:

Before: https://imgur.com/3Vi3bV2
After: https://imgur.com/OQ7yzdg

#4136 doesn't fix it:
https://imgur.com/5jxgu5A

**Comment by kd-11** [comment] 2018-02-01 10:51
4136 is the same build as the one linked. Also, to determine the "correct" output, run older master with strict mode and compare. The grayer version may be the correct one.

**Comment by JoJose89** [comment] 2018-02-01 11:35
First image correspond to [0.0.4-7823](https://ci.appveyor.com/project/rpcs3/rpcs3/build/0.0.4-7823/artifacts), second one to [0.0.4-7826](https://ci.appveyor.com/project/rpcs3/rpcs3/build/0.0.4-7826/artifacts). Doesn't happen with the first one while running strict mode, still happens in the second one with it.

**Comment by meladath** [comment] 2018-02-01 12:39
I can confirm #4136 fixes the problems I stated in the bug on my hardware.

**Comment by AniLeo** [comment] 2018-02-02 18:57
Fixed by #4136

**Closed by AniLeo** 2018-02-02 18:57 UTC
Labels: Need Information
