### ISSUE TITLE
Ratchet & Clank: ACiT - Thread terminated due to fatal error

### ISSUE THREAD

**Issue by jy95** [RPCS3/rpcs3#10649] opened 2021-08-03 17:08 UTC
## Quick summary
Game crashes during a dialogue with Lawrence in Nefarious Space Station.
(after destroying meteors with the laser)

## Details

In Nefarious Space Station, the bug occurs when Ratchet impersonate Dr. Nefarious during a specific speech with Lawrence .
After you destroy meteors with the laser, you must ask Lawrence to make Nefarious fleet land.
After selecting the right dialog option, the game crashes.

#### 1. Please attach RPCS3's log.

[RPCS3.log on v0.0.17-12565-8af694da](https://github.com/RPCS3/rpcs3/files/6925822/RPCS3-crash.log)
[RPCS3.log on 0.0.17-12571-af89eb54](https://github.com/RPCS3/rpcs3/files/6925828/RPCS3.log)

#### 3. Please attach screenshots of your problem.
![crashBug](https://user-images.githubusercontent.com/9306961/128055074-08c6c6d6-ba05-43b7-9ec6-689931af8e8a.PNG)
![crashBug2](https://user-images.githubusercontent.com/9306961/128055094-d1e67249-c21b-481a-930b-abde29a86396.PNG)

#### 4. Please provide comparison with real PS3.
It doesn't crash and load a cutscene where Nefarious fleet land.

#### 5. Please provide your system configuration:
* OS : Windows, Major: 10, Minor: 0, Build: 19042, Service Pack: none, Compatibility mode: 0
* CPU Intel(R) Core(TM) i7-8750H CPU @ 2.20GHz | 12 Threads | 15.85 GiB RAM | TSC: 2.208GHz | AVX+ | FMA3
* GPU 'NVIDIA GeForce GTX 1050' running on driver 471.41.0.0

#### 6. Anything else you find important ?
I checked if my backup wasn't corrupted and it isn't the case :

![124376940-a2921b00-dca9-11eb-822c-39f1213163d3](https://user-images.githubusercontent.com/9306961/128055725-69e9ceb7-11aa-45bc-9d0a-d638c57c9bc4.png)

I tested that game on several RPCS3 versions (none of them didn't have this bug) :
- v0.0.17-12437-770a607b Alpha
- v0.0.17-12521-867f0e1f Alpha
- v0.0.17-12565-8af694da Alpha
- v0.0.17-12571-af89eb54 Alpha

**Comment by CirkuitBreaker** [comment] 2021-08-31 20:30
I can confirm that I have the exact same issue on Manjaro Linux.

**Comment by kd-11** [comment] 2021-10-10 13:42
Closing as a duplicate of https://github.com/RPCS3/rpcs3/issues/10926

**Closed by kd-11** 2021-10-10 13:42 UTC
