### ISSUE TITLE
WxWidgets broken in latest git''

### ISSUE THREAD

**Issue by thx3ever** [RPCS3/rpcs3#1579] opened 2016-03-15 21:24 UTC
When i try to run any game now it show this error, it show this error in opengl, vulkan and directX12

---------------------------
Fatal error
---------------------------
Unhandled Win32 exception 0x80000003.
Exception address: 00000000003E666A.
ExceptionInformation[0x0]: 0000000000000000.
Instruction address: 00000000003E666A.
Image base: 0000000000010000.

An unknown internal exception has occured. Please report this to the developers.

![sem titulo](https://cloud.githubusercontent.com/assets/17690807/13794531/1a1230d2-eadb-11e5-856d-0f6abd58c310.jpg)

**Comment by MyaniPT** [comment] 2016-03-15 21:51
Did you update submodules?
I tested it on my fork which is 2 commits behind upstream master and it worked, since nothing related to wxWidgets was commited it should still work

**Comment by thx3ever** [comment] 2016-03-15 21:53
the game Hitman 2 silent assassin HD works for u in latest git? Try this game if u can

**Comment by MyaniPT** [comment] 2016-03-15 22:01
I'm on my laptop which doesn't have hardware support for any of RPCS3's renderers, I can only test that tomorrow night for you.
Post your full RPCS3.log file (zip it and upload directly into github)

**Comment by tambry** [comment] 2016-03-16 05:50
Duplicate of #1375.

**Closed by tambry** 2016-03-16 05:50 UTC
