### ISSUE TITLE
RESIDENT EVIL 5 GOLD EDITION [BLUS30491] (#7222)

### ISSUE THREAD

**Issue by Rpcs3tester** [RPCS3/rpcs3#5078] opened 2018-09-04 01:06 UTC
it's stuck to install with huge FPS counter

![2018-09-04_4-04-42](https://user-images.githubusercontent.com/38118895/45004739-cfa0b980-aff7-11e8-972a-08937da27ad7.png)
[RPCS3.log.gz](https://github.com/RPCS3/rpcs3/files/2346797/RPCS3.log.gz)

**Comment by Rpcs3tester** [comment] 2018-09-05 05:03
with this build 0.0.5-6499 

![2018-09-05_8-00-39](https://user-images.githubusercontent.com/38118895/45072118-1ec31900-b0e2-11e8-8cd8-400bdf4c26b6.png)

**Comment by AniLeo** [comment] 2018-09-05 14:00
Missing in what PR it regressed.

**Comment by Rpcs3tester** [comment] 2018-09-05 15:35
0.0.5-7222

**Comment by AniLeo** [comment] 2018-09-09 18:48
Nope, that's not possible. That build only touches VSync and you're not even using it.
I'm closing this as a false report, since it can't be trusted if you pick random builds to flag the regression.

**Closed by AniLeo** 2018-09-09 18:48 UTC
Labels: Need Information
