### ISSUE TITLE
Running AppImage on wayland is missing dependency

### ISSUE THREAD

**Issue by HoboDev** [RPCS3/rpcs3#12102] opened 2022-05-27 11:43 UTC
## Quick summary
After exporting QT_QPA_PLATFORM=wayland
I'm greeted with a missing dependency: xcb

## Details
I did ```export QT_QPA_PLATFORM=wayland```
And received this error message:
qt.qpa.plugin: Could not find the Qt platform plugin "wayland" in ""
This application failed to start because no Qt platform plugin could be initialized. Reinstalling the application may fix this problem.

Available platform plugins are: xcb.

This dependency is not available on my distribution (Void Linux) but it also seems not to be included in the AppImage.
Reading the description of AppImage it claims that all necessary dependencies should be included to just run the AppImage.

#### Please provide your system configuration:
* OS: Void Linux

**Comment by MSuih** [comment] 2022-05-27 11:49
We can't bundle xcb with emulator because it causes conflicts, you need to install it manually. Check that you have the following installed: `libx11-xcb1 libxcb1 libxcb-xinerama0`

Closing as duplicate of #9008.

**Closed by MSuih** 2022-05-27 11:49 UTC

**Comment by HoboDev** [comment] 2022-05-30 04:33
Seems when all packages are installed on my side and then I only end up with:
`ERROR: Incompatible compiler options cross compiler instances!Segmentation fault`
happens with both `export QT_QPA_PLATFORM=wayland` and `export QT_QPA_PLATFORM=xcb`
But RLIMIT is already set.
