### ISSUE TITLE
Regression: Streets of Rage 2 - cellVdec Unsupported time_base

### ISSUE THREAD

**Issue by ghost** [RPCS3/rpcs3#2550] opened 2017-03-17 21:41 UTC
When loading either the EU or US region of this disc, on OGL & Vulkan it gives the following error message below.
```
F {PPU[0x1000016] Thread (HLE Video Decoder)} class std::runtime_error thrown: Unsupported time_base.num (1000/1, tpf=1)
(in file C:\rpcs3\rpcs3\Emu\Cell\Modules\cellVdec.cpp:332)
```

DX12 crashes the application with this error message I screenshot below.

Last known good build: https://github.com/RPCS3/rpcs3/commit/e4631f9
![rpcs3_2017-03-17_14-59-27](https://cloud.githubusercontent.com/assets/12888227/24064081/28c5686a-0b28-11e7-986b-ccc9837e8df6.png)
[RPCS3-NPUB30444.zip](https://github.com/RPCS3/rpcs3/files/851844/RPCS3-NPUB30444.zip)
[RPCS3-OGL.zip](https://github.com/RPCS3/rpcs3/files/851847/RPCS3-OGL.zip)
[RPCS3-Vulkan.zip](https://github.com/RPCS3/rpcs3/files/851845/RPCS3-Vulkan.zip)
[RPCS3-DX12.zip](https://github.com/RPCS3/rpcs3/files/851846/RPCS3-DX12.zip)

**Comment by raven02** [comment] 2017-03-18 10:57
In latest build , it even crashes with cellSysutilAvc2: Unknown media type 0x0

**Comment by scribam** [comment] 2017-07-21 17:34
@darkredflame Can you try to run this game with the latest build available ? I haven't had any problems with OpenGL.

**Comment by darkredflame** [comment] 2017-07-22 01:21
When I run the game with Vulkan, I still get the same error message. As for OpenGL, the game doesn't even attempt to load for me.

[RPCS3 OpenGL.zip](https://github.com/RPCS3/rpcs3/files/1167030/RPCS3.OpenGL.zip)
[RPCS3 Vulkan.zip](https://github.com/RPCS3/rpcs3/files/1167031/RPCS3.Vulkan.zip)

**Comment by scribam** [comment] 2017-07-22 07:57
Strange, I don't have any references in the log about "HLE Video Decoder". Game loads fine for me.

![screenshot from 2017-07-22 09-52-59](https://user-images.githubusercontent.com/25406440/28489419-ed1caa94-6ec3-11e7-9c0b-656793d62f07.png)

**Comment by scribam** [comment] 2017-08-10 17:12
@darkredflame I tried again with LLVM and OpenGL, still no problems to load the menu. Would you mind trying again with the latest build? If it doesn't work, maybe you can clear the configuration and the generated files from the game to do a fresh run.

**Comment by darkredflame** [comment] 2017-08-10 17:14
I can definitely try again when I get a chance, may not be for a bit since
I am pretty busy with real life stuff.

**Comment by darkredflame** [comment] 2017-08-10 17:14
I can definitely try again when I get a chance, may not be for a bit since I am pretty busy with real life stuff.

**Comment by scribam** [comment] 2017-10-14 20:16
@darkredflame Did you get a chance to try again this game with a recent build?

**Comment by 16bitblastprocessing** [comment] 2017-10-15 18:30
Issue still occurs in this game with the same error regardless of PPU/SPU options used on this build.


·F 0:00:13.623732 {PPU[0x1000013] Thread (HLE Video Decoder)} class std::runtime_error thrown: Unsupported time_base.num (1000/1, tpf=1)

**Comment by scribam** [comment] 2017-10-15 18:47
Do you use also Windows?
I have no issue on Linux.

**Comment by 16bitblastprocessing** [comment] 2017-10-15 19:04
Yep, I also use windows. Windows 10 specifically.

**Comment by scribam** [comment] 2017-12-01 19:50
The game still works fine for me with build 3fbc960c44403e9dce363941b07bf1aeadbc2937 on Linux. Can someone try again ? If possible on Linux and Windows as I would like to know if the issue is specific to Windows.

![screenshot from 2017-12-01 20-44-05](https://user-images.githubusercontent.com/25406440/33500360-d62b340e-d6d8-11e7-9336-379781c47663.png)

**Comment by elad335** [comment] 2018-07-21 12:13
needs retesting

**Comment by HerrHulaHoop** [comment] 2018-11-02 11:36
RPCS3 v0.0.5-7454-eba2216c Alpha | HEAD | Windows 10
Intel(R) Core(TM) i7-3630QM CPU @ 2.40GHz | 8 Threads | 7.89 GiB RAM | AVX

The game works for me. But the error mentioned in above is still spammed in the log, only now it's an error instead of a fatal. I played the game for only about 10 minutes and the this error was spammed 16,000 times.
`·E 0:01:04.019427 {PPU[0x1000013] Thread (HLE Video Decoder)} cellVdec: Unsupported time_base.num (1000/1, tpf=1)`

However, the game still ran at fullspeed regardless.
![streets of rage 2](https://user-images.githubusercontent.com/31934788/47912993-6e467b00-dec0-11e8-922a-caf283499544.png)

[RPCS3.log.gz - Build 7454](https://github.com/RPCS3/rpcs3/files/2542273/RPCS3.log.gz)

**Comment by benderscruffy** [comment] 2019-09-19 09:56
RPCS3 v0.0.7-8739-c50119ae Alpha
still goes ingame 
but stilll spams the error
·E 0:00:31.046623 {PPU[0x1000013] Thread (HLE Video Decoder)} cellVdec: Unsupported time_base.num (1000/1, tpf=1)
[RPCS3.log.gz](https://github.com/RPCS3/rpcs3/files/3630572/RPCS3.log.gz)

**Comment by bevanweiss** [comment] 2020-09-06 07:53
I suspect that you have the Frame Limit set to 'Off', and this game really doesn't require any GPU, so the frames are flying out much much faster than the 30Hz/60Hz etc that the cellVdec is expecting.

I can't see where we might be doing any calculated updates for the time_base (either num, denom, or ticks_per_frame), but those settings shown in your log don't align with a 'good' refresh rate (i.e. a PS3 PAL/NTSC standard).

I'd recommend trying one of the other options (not 'Off') for this setting under this particular game, and report the findings.

**Comment by dio-gh** [comment] 2020-09-20 02:38
I tested with every single one of the fps limiter options and couldn't observe a change in behaviour. This is still an issue.

**Comment by HerrHulaHoop** [comment] 2021-04-11 08:43
RPCS3 v0.0.15-12069-7a105333 Alpha
Spam still occurs

**Comment by Megamouse** [comment] 2021-05-29 10:52
Spam has been reduced to a single log Message per stream.
I guess this suffices to close the issue for now.
A new issue can be opened if the current code leads to problems in other games.

**Closed by Megamouse** 2021-05-29 10:52 UTC
Labels: Bug, Firmware: HLE, Regression
