### ISSUE TITLE
Unknown magnify filter 0x0 [NPUB30932]

### ISSUE THREAD

**Issue by vasiliyaltunin** [RPCS3/rpcs3#3973] opened 2017-12-22 23:27 UTC
Vulkan
RPCS3 v0.0.4-6269-58d8d126 Alpha | HEAD
Intel(R) Core(TM) i5-7400 CPU @ 3.00GHz | 4 Threads | 7.97 GiB RAM | AVX+

It hapens in ingame cinematics

```
E {PPU[0x1000015] Thread (fios mediathread 6) [0x01e38090]} 'sys_fs_open' failed with 0x80010006 : CELL_ENOENT, “/dev_hdd0/game/NPUB30932/USRDIR/data/sound/voice/en/03/0301660.sgh.zarc” [1]
E {PPU[0x1000015] Thread (fios mediathread 6) [0x01e37ee4]} 'sys_fs_stat' failed with 0x80010006 : CELL_ENOENT, “/dev_hdd0/game/NPUB30932/USRDIR/data/sound/voice/en/03/0301670.sgh.zarc” [1]
E {PPU[0x1000015] Thread (fios mediathread 6) [0x01e37ee4]} 'sys_fs_stat' failed with 0x80010006 : CELL_ENOENT, “/dev_hdd0/game/NPUB30932/USRDIR/data/sound/voice/en/03/0301670.sgh.zarc” [2]
E {PPU[0x1000015] Thread (fios mediathread 6) [0x01e38090]} 'sys_fs_open' failed with 0x80010006 : CELL_ENOENT, “/dev_hdd0/game/NPUB30932/USRDIR/data/sound/voice/en/03/0301670.sgh.zarc” [1]
F {rsx::thread} class std::runtime_error thrown: Unknown magnify filter 0x0
(in file Emu\RSX\gcm_enums.cpp:631)
```

[231217- v0.0.4-6269-58d8d126-vulkan-log-1.zip](https://github.com/RPCS3/rpcs3/files/1583671/231217-.v0.0.4-6269-58d8d126-vulkan-log-1.zip)

**Comment by Zangetsu38** [comment] 2017-12-23 09:50
cinematic have problem for moment, need skip that

**Comment by Kadaban** [comment] 2018-01-16 09:22
I just had the same crash related to "Unknown magnify filter 0x0" in Ni No Kuni. Granted it's BLES01555, the disc version but that doesn't seem to change much.
The crash happened in Hamelin (the pig city) while simply running around inside the city. No cutscenes involved.
I had similar crashes related to that magnify filter thing in other cities and on the overworld map as well.



[BLES01555 Unknown magnify filter 0x0.zip](https://github.com/RPCS3/rpcs3/files/1634334/BLES01555.Unknown.magnify.filter.0x0.zip)

**Comment by Kravickas** [comment] 2018-01-18 14:41
I had this error in gameplay of NHL 13

**Comment by Metasynic** [comment] 2019-01-08 17:45
Can confirm this error is still happening in Ni No Kuni on builds 7658 and 7678 at least, and can be reproduced by fighting the last gauntlet in Rank E of the Solosseum. I'll leave my log here but see the above closed issue [5227](https://github.com/RPCS3/rpcs3/issues/5527) for more information. Let me know if anyone wants a save outside the Solosseum to help reproduce the issue.

Log: [RPCS3.log (NNK, Magnify filter).gz](https://github.com/RPCS3/rpcs3/files/2737884/RPCS3.log.NNK.Magnify.filter.gz)

**Comment by psennermann** [comment] 2019-01-09 09:57
On my system the only way to get rid of this problem in NiNoKuni is, while in-game, to set rpcs3 process priority to real time

**Comment by psennermann** [comment] 2019-01-13 22:40
I think this error get triggered only when fps are below 30...I have a save state near a location where pointing in a particular direction fps are 28,5 (months ago they were 20, but now thanks to various improvements - especially #5435 not yet merged - game is much faster) and after a little while the Unknown Magnify Filter error shows Always up, but when I point the view in a direction where my system handles 30 fps, the error never shows up (not even after hours). Also using process priority to "real time" gives a boost to fps reaching 30 fps in every game-scene and so the error never comes out (could this be a coincidence?).
In the next months, hopefully with another little fps improvement, I'll be able to tell if my impressions are correct...

**Comment by Zardas81** [comment] 2019-02-14 17:07
Still happening in build 7795.

`·F 0:07:59.400041 {RSX [0x0caabd4]} RSX: class std::runtime_error thrown: Unknown magnify filter 0x0
(in file c:\projects\rpcs3\rpcs3\emu\rsx\gcm_enums.cpp:632)`

[RPCS3.zip](https://github.com/RPCS3/rpcs3/files/2866026/RPCS3.zip)

**Comment by psennermann** [comment] 2019-02-14 22:25
I've just upgraded to an i7 7700 and I can confirm that this error only gets triggered when beeing below 30 fps: now that I have steady 30 fps I don't get it anymore (or at least not in the place where I used to get it 100% of the times)

**Comment by MWallenberg** [comment] 2019-03-02 20:16
Just ran into this issue, with 7825 build. My FPS varies between 20 and 30. Increasin process priority in windows bumped my frame rate up slightly, and seems to have resolved it (or at least alleviated it) for me.

Specs:

RPCS3 v0.0.6-7825-ebb24375 Alpha | HEAD | Windows
Intel Core i5-6600K | 4 Threads | 15.92 GiB RAM | AVX+ | TSX
GPU: GeForce RTX 2080 (417.35)

**Comment by digitaldude555** [comment] 2020-02-07 14:26
It's been 1 year with no updates.

**Comment by elad335** [comment] 2020-02-07 14:27
try rsx wake up delay.

**Comment by benderscruffy** [comment] 2020-02-11 11:34
please close due to no activity for over a year

**Comment by elad335** [comment] 2020-02-11 11:38
its also known to be fixed in Ni No Kuni with driver wake up delay as commented in #7233.

**Comment by MWallenberg** [comment] 2020-02-11 11:40
I solved it by buying a new, much more powerful computer. That worked as well.

**Comment by AniLeo** [comment] 2020-04-03 03:40
Closing as fixed, no one is able to reproduce this issue anymore

**Closed by AniLeo** 2020-04-03 03:40 UTC
