### ISSUE TITLE
[Regression] LittleBigPlanet 1 (BCUS98148) Freezing up at seemingly random

### ISSUE THREAD

**Issue by kuulover** [RPCS3/rpcs3#16130] opened 2024-09-26 17:46 UTC
### Quick summary

LittleBigPlanet 1 frequently freezes at seemingly random as of v0.0.32-16431 / #15562

### Details

Regression: Game freezes up at seemingly random; Causes video to freeze and game to stop taking inputs, but BGM will continue to play. Without a proper crash, logs are acquired by alt+f4'ing the game from here, closing the emulator, then copying the RPCS3.log.gz file by hand.

There is no one thing that can cause a freeze. It seems to happen at any point, but here are some example situations that can go on when the game freezes (which is in no way an exhaustive list):
- Loading a level in the Pod in the Story Mode menu
- During the spawn animation when entering a level
- For no reason during gameplay mid-level
- While painting shapes using the Goodies Bag>Materials in Create mode

While the random freezing may still occur in the versions labeled "good", it happens at a much, much lower frequency (Hours, even days in between freezes) and is very playable. In versions labeled "bad", it can happen from not even a couple minutes after launching the game to up to around 15 minutes on average, making the game frustrating to play (or even impossible if a single level takes longer to clear than that.)

For this list, all versions were tested with NO patches despite my preference of the LittleBigRefresh or Beacon patch applied. The words 'freeze', 'crashed' and 'crash' in the following list are used interchangeably to refer to the aforementioned freeze issue. For the most part, I went with a binary search method, as instructed, to determine the problem build. Testing was difficult as there is no one method to cause the game to freeze.

- v0.0.31-16388 - GOOD | The build I used to play on before a recent RPCN update requiring me to update the emulator to connect to RPCN. Very stable, did not have the issue.
- v0.0.32-16407 - LIKELY GOOD | Seems stable after ~1hr
- v0.0.32-16422 - LIKELY GOOD
- v0.0.32-16424 - LIKELY GOOD | Seems very stable so far.
- v0.0.32-16430 - GOOD | Seems stable after several hours of playing.
- v0.0.32-16431 - BAD | Did Eventually Crash, Then crashed quite soon again after, two times. (Tested in Get a Grip, Serpent Shrine & Create Mode primarily)
- v0.0.32-16433 - BAD | Crashed after ~10-15 min but in a custom level while cheating in bombs, will continue testing - Crashed a second time after 25 min 
- v0.0.32-16434 - BAD | Crashed after ~5 min and once more in <1 min. Then a third time in ~15 min (Tested in Get a Grip, Create Mode & Skate to Victory)
- v0.0.32-16435 - BAD | Crashed once after ~2-3 min (Tested in Get a Grip)
- v0.0.32-16436 - BAD | Crashed twice after ~1-2 min (Tested in Get a Grip)
- v0.0.32-16500 - BAD | Crashed once after ~10-15 min
- v0.0.32-16627 - BAD | Crashed once after ~30-45 min
- v0.0.33-16941 - BAD | Crashed
- v0.0.33-16959 - BAD | Crashed

### Build with regression

v0.0.32-16431

### Attach two log files

**v0.0.32-16430 Log** - No freeze, seems to be the version before the regression appeared
[RPCS3.log.gz](https://github.com/user-attachments/files/17153123/RPCS3.log.gz)

**v0.0.32-16431 Log** - Freeze. These are three separate instances of a freeze occurring each with their own log.
[RPCS3.log.gz](https://github.com/user-attachments/files/17153130/RPCS3.log.gz)
[RPCS3-2.log.gz](https://github.com/user-attachments/files/17153131/RPCS3-2.log.gz)
[RPCS3-3.log.gz](https://github.com/user-attachments/files/17153132/RPCS3-3.log.gz)

### System configuration

My System 
- Arch Linux x86_64
- Kernel: 6.10.6-arch1-1
- CPU: 12th Gen Intel i7-12700K (20) @ 4.900
- GPU: AMD Radeon RX 6750 XT
- GPU Drivers: mesa 1:24.1.6-1, vulkan-radeon 1:24.1.6-1

This also happens to my friends I invited to play with me - They use Windows 10/Windows 11, but I don't have any of their logs/system information atm.

Other users on LBP custom server Discords such as LBP Union have also reported the game being unstable until they switched to a version of RPCS3 prior to v0.0.32-16431 (Which is now incompatible for online play with RPCN as of earlier this month.)

### Other details

Let me know if any other information may be needed. Thank you.

**Comment by Lisible** [comment] 2024-09-26 17:49
Encountering the same issue on W11 with a GTX1080, I'll add a log the next time it happens

**Comment by yuvia08** [comment] 2024-09-27 19:00
>it also seem to happen on LBP2.

it has been happening on LBP2 for a while now... sad to see it spreading to lbp1 now :disappointed:

**Comment by Lyicx** [comment] 2024-09-27 19:22
just had this happen to me on LBP3 as i was playing the level "Tinpot Towers" and another time looking at the adventure map trying to get the level name for this very message (Build 0.0.33-16971). but for the past few months its been happening to me on LBP2 (happened yesterday twice as i was sorting my goodies bag and leaving it open doing literally nothing) and LBP1 varying in frequency. haven't got anything to share sadly besides that given how inconsistent things are. some days i wont encounter it at all but occasionally ill get freeze after freeze. gonna leave the logs on to see if i can provide anything useful asides just a witness account

**Comment by Lisible** [comment] 2024-09-28 20:03
Just played a bit on build 0.0.33-16977 and it froze at the end of a story level.

Here are the logs.
[LittleBigPlanet [NPEA00241].log.gz](https://github.com/user-attachments/files/17176111/LittleBigPlanet.NPEA00241.log.gz)

**Comment by Mert5666** [comment] 2024-10-04 09:03
lbp 2 has had the same issue since may 5

**Comment by RipleyTom** [comment] 2024-10-04 11:12
Just for proper documentation, 16431 introduced a bug(or rather made a pre-existing bug a lot more likely to occur) that made LBP games hang, it was fixed in 16611, so all testing before 16611 should be ignored. I looked at 16977's logs but I don't see any obvious cause in the log.

**Comment by martinsaenz96** [comment] 2024-10-08 02:00
I too have been experiencing the same issue nonstop. I've been playing LBP1 on my Steam Deck, while it runs fine (write color buffers makes it lag) the game has been crashing at any given time, even during inactivity. This issue has been driving me crazy,  I asked in the RPCS3 discord server, and I asked on Reddit, and I haven't gotten any help.

**Comment by eyeffects** [comment] 2024-10-16 16:36
Looks very similar to #15575

**Comment by eyeffects** [comment] 2024-10-16 16:49
[RPCS3.zip](https://github.com/user-attachments/files/17399819/RPCS3.zip)
Just got the same issue in LittleBigPlanet 3. Froze after about 30min of gameplay
Build 17042

**Comment by eyeffects** [comment] 2024-10-17 11:44
[RPCS3.log.gz](https://github.com/user-attachments/files/17411722/RPCS3.log.gz)
Another day another freeze. Build 17045

**Comment by ItsLaguna** [comment] 2024-10-17 11:54
> [RPCS3.log.gz](https://github.com/user-attachments/files/17411722/RPCS3.log.gz) Another day another freeze. Build 17045

This does nothing to solve the issue, as Ripley said comments ago, the testing has to be done from build 16611 onwards.
Reporting a build where the issue is known to happen and not finding the build that regressed is pointless.

**Comment by ItsLaguna** [comment] 2024-10-17 16:55
Tested 16611 and it froze after +1h alternating between sitting afk and playing, all this in a separate install.
RPCN and Network settings on disconnected (though I can't even access RPCN since it's outdated in this build), default settings, no patches.
The next build (16614) froze/crashed earlier than this one (around ~30mins of playing), newer builds take as long or less.

[16611.log](https://github.com/user-attachments/files/17416228/16611.log)
[16614.log](https://github.com/user-attachments/files/17416234/16614.log)

Not attaching anything newer than these since it probably won't contribute much to the issue.

@RipleyTom if you don't see anything weird in these, should try older builds until reaching 16431 again? Even if it technically is the build that introduced/aggravated what 16611 fixed.

**Comment by martinsaenz96** [comment] 2024-10-17 17:09
So what could be the issue well in my case with the Steam Deck?

**Comment by eyeffects** [comment] 2024-10-20 04:34
Played about 3 hours in 16430 - nothing happened, but 16431 crashed after 1,5 hours. Maybe, 16611 just didn't fix the issue?

**Comment by Mert5666** [comment] 2024-11-01 04:14
lbp 2 has had the same issue since may 5 or before but I couldn't find the build that caused it back then so it may have happened before then

**Comment by AwesomeSavage** [comment] 2024-11-05 00:46
I have an issue that's probally under this, but its with Little Big Planet Karting. I'm on the latest released build, for clarification.
Log: [RPCS3.log](https://github.com/user-attachments/files/17625399/RPCS3.log)

**Comment by HidekoHaruna** [comment] 2024-11-08 14:09
Same, I'm playing LBP2 on RPCS3 v0.0.34-17098-2262ac16 Alpha.
[rpcs3.log.gz](https://github.com/user-attachments/files/17679742/rpcs3.log.gz)

**Comment by AwesomeSavage** [comment] 2024-11-08 20:46
I adjusted my graphics settings and karting works fine for me now, but it may have been a coincidence that I adjusted the settings, and it didn't break while I was playing.

**Comment by FoilGear** [comment] 2024-11-15 18:59
LittleBigPlanet 2, tested in v0.0.32-16611-feff2ba0 and v0.0.34-17114-e7faec6b, roughly 15-20 minutes until freeze for both.
[16611 RPCS3.log.gz](https://github.com/user-attachments/files/17779934/16611.RPCS3.log.gz)
[17114 RPCS3.log.gz](https://github.com/user-attachments/files/17779935/17114.RPCS3.log.gz)

**Closed as completed** 2024-11-22 16:44 UTC
