### ISSUE TITLE
Demon's Souls [BLUS30443]: Vanguard boss not rendering

### ISSUE THREAD

**Issue by Pacundito** [RPCS3/rpcs3#3456] opened 2017-09-16 21:25 UTC
Hello i have a rare issue, vanguard boss is not rendering, my specs are:

Intel Core i7 4970
Mem 16 GB DDR3 1866mhz
GPU GeForce GTX 970
RPCS3 build 6172

https://i.imgur.com/ff1A0sx.jpg

**Comment by kd-11** [comment] 2017-09-21 14:08
Does it happen more than once. Demon's souls has rather interesting glitches even on real hardware.

**Comment by Pacundito** [comment] 2017-09-22 03:09
It happend all the time,everytime i tried with every version of rpcs3

**Comment by Asinin3** [comment] 2017-09-22 03:44
How is it a rare issue if it happens every time?

**Comment by Pacundito** [comment] 2017-09-22 12:30
It's rare for me because i didn't see other people posting this issue in particular, i searched a lot before posting

**Comment by kd-11** [comment] 2017-09-22 13:50
So it might be a bad dump of the game? If it always happens for you but not for anyone else, you probably have a corrupted dump.

**Comment by AniLeo** [comment] 2017-10-08 13:59
Needs more information as per the guidelines.
We can't do anything if we can't reproduce the issue to start with.
Used version (retest with latest), drivers' version and log files.

**Comment by kd-11** [comment] 2017-10-19 10:25
I'm convinced this is a bad dump of the game otherwise a missing boss in Demon's souls would have been mentioned by other users. As such, I will close this issue for now unless someone else can confirm the same is happening to them.

**Closed by kd-11** 2017-10-19 10:25 UTC
Labels: needinfo

**Comment by Pacundito** [comment] 2017-10-19 19:06
i tried another dump with same result
