### ISSUE TITLE
Tha Last of Us Hotel Lobby Fatal Error

### ISSUE THREAD

**Issue by loreeffe** [RPCS3/rpcs3#8231] opened 2020-05-15 22:56 UTC
The Last of Us crash when Joel boost up Ellie on the elevator roof in the Hotel Lobby, image freezes with log reporting:
"Thread terminated due to fatal error, Trap!" no matter what configuration is set nothing changes.

My Specs: 
Intel Xeon 1231v3 E3 3.4Ghz (Haswell)
NVIDIA 650 Ti 2Gb
Config:
PPU LLVM
SPU LLVM
WCB
Force CPU blit
Read Depth Buffer
Read Color Buffer

**Comment by RainbowCookie32** [comment] 2020-05-15 23:00
Missing a log file from the crash

**Comment by sampletext32** [comment] 2020-05-15 23:39
Could you please provide a Save file, so others can try it out.

**Comment by loreeffe** [comment] 2020-05-15 23:55
Sure sorry i was on Mac but now i will attach logs and savefile
[RPCS3.log](https://github.com/RPCS3/rpcs3/files/4637498/RPCS3.log)
[TTY.log](https://github.com/RPCS3/rpcs3/files/4637501/TTY.log)
[savedata.zip](https://github.com/RPCS3/rpcs3/files/4637502/savedata.zip)

**Comment by AniLeo** [comment] 2020-05-15 23:57
Known behavior, game ASSERT
`ASSERTION: IsFinite(deltaTransform)`
Throws a trap and RPCS3 stops

**Comment by loreeffe** [comment] 2020-05-15 23:58
So no way to go past this for now i assume

**Comment by illusion0001** [comment] 2020-05-16 00:34
Duplicate of #6296

**Closed** 2020-05-16 00:35 UTC
