### ISSUE TITLE
[GTA V] Matchmaking

### ISSUE THREAD

**Issue by Lethality5001** [RPCS3/rpcs3#14719] opened 2023-10-07 17:18 UTC
### Quick summary

Matchmaking for GTA V Online as "GTA:OG" has become a thing, many are requesting this, old gen is much more fun

### Details

Being able to connect to other player's job invites etc

**Comment by FlexBy420** [comment] 2023-10-07 17:21
Duplicate of #14670

**Closed** 2023-10-07 20:30 UTC
