### ISSUE TITLE
Keyboard not working

### ISSUE THREAD

**Issue by bighairydaddy** [RPCS3/rpcs3#3981] opened 2017-12-24 12:37 UTC
Im using v0.0.4

When i start up Persona 5 it opens with the screen that asks to choose either you want to play online or offline, it only lets me use my arrow keys, any other key doesnt do anything, i cant select anything, i have tried everything to resolve this problem, it just doesnt accept any other keyboard input.

Any idea if this is something my computer is doing or? Any way to fix this

**Comment by AniLeo** [comment] 2017-12-24 12:38
What commit/version exactly, 0.0.4 doesn't mean anything

**Comment by bighairydaddy** [comment] 2017-12-24 12:39
v0.0.4-6271-8a3759f4 Alpha is what it says

**Comment by Megamouse** [comment] 2017-12-24 12:47
reset your controller layout.

**Comment by bighairydaddy** [comment] 2017-12-24 12:49
tried doing it multiple times, even deleted the emulator and reinstalled it, its both set to keyboard and keyboard, defaul settings, everything is at default, nothing works

**Comment by Megamouse** [comment] 2017-12-24 12:58
did it ever work for you?

**Comment by bighairydaddy** [comment] 2017-12-24 13:00
I just downloaded it today, even watched a setup guide to see if i have accidently fucked up anything, i do the same thing they you are supposed to do, start the game and the keyboard doesnt work
![image](https://user-images.githubusercontent.com/34811552/34326653-33b3216a-e8bb-11e7-8877-d645fcc57cc7.png)

**Comment by Megamouse** [comment] 2017-12-24 13:02
maybe not setting every single player to keyboard would help 🤦‍♂️

**Comment by bighairydaddy** [comment] 2017-12-24 13:08
hey i said i tried everything, it was set to only player 1 at keyboard still the same thing, it just doesnt work

**Comment by Megamouse** [comment] 2017-12-24 13:13
is your keyboard set to use some weird layout like chinese or cyrillic or whatever?

**Comment by bighairydaddy** [comment] 2017-12-24 13:15
nope, although its an english/crillic keyboard, its set to english

**Comment by Megamouse** [comment] 2017-12-24 13:17
does it work on the configure keyboard window?

**Comment by bighairydaddy** [comment] 2017-12-24 13:19
yes, i am able to change them
![image](https://user-images.githubusercontent.com/34811552/34326770-c6fe54b0-e8bd-11e7-92eb-8af131d6ac6f.png)

**Comment by Megamouse** [comment] 2017-12-24 13:20
does it work in P5 after you changed them and saved

**Comment by bighairydaddy** [comment] 2017-12-24 13:21
No, i still can only use up and down arrow to change between the "Yes" and "No" option in the choose if online or offline menu, NOTHING else does anything

**Comment by Megamouse** [comment] 2017-12-24 13:22
what if you set the up and down arrow to something like W and S and use the up arrow for Cross button

**Comment by bighairydaddy** [comment] 2017-12-24 13:25
i set everything to the "E" key and it let me select an option, so i guess i just have to map everything differently or something , im just confused now

**Comment by Megamouse** [comment] 2017-12-24 13:35
show me your config_kbpad_qt.yml file once you remapped it and saved

**Comment by Altaiar** [comment] 2017-12-24 14:12
keyboard works in this build rpcs3-v0.0.4-2017-12-23-8a3759f4_win64

**Comment by Megamouse** [comment] 2017-12-24 14:55
Anyway this is a duplicate of #3452 and can therefore be closed

**Closed** 2017-12-24 14:59 UTC

**Comment by TetramoffTR** [comment] 2018-06-06 09:31
Hello I see this is closed but I have the same problem with v0.0.5-6887-84ae64369 Alpha
Is there a way to fix this now?

**Comment by AniLeo** [comment] 2018-06-06 14:01
Don't post on duplicates, post on the main issue indicated above your comment..
