### ISSUE TITLE
[Regression]: Fairy Fencer F BLUS31423 crash with "Verification failed" error.

### ISSUE THREAD

**Issue by y-salnikov** [RPCS3/rpcs3#5766] opened 2019-03-26 21:26 UTC
**Fairy fencer F** crashes immediately after boot. With vulkan renderer it shows following fatal error in log:
 <pre>
E {PPU[0x100001c] Thread (SetupDataBaseCore)} Stat: 'sys_mutex_unlock' failed with 0x80010005 : CELL_ESRCH [x43]
E {PPU[0x100001c] Thread (SetupDataBaseCore)} Stat: 'sys_mutex_lock' failed with 0x80010005 : CELL_ESRCH [x43]
<b>F {RSX [0x00cf3b4]} RSX: St13runtime_error thrown: Verification failed (e=39):</b>
<b>(in file /mnt/d/linux_files/.cache/pacaur/rpcs3-git/src/rpcs3/rpcs3/Emu/RSX/VK/VKCompute.h:139)</b>
</pre>
With OpenGL renderer game freeze presumably at same place. And with null renderer it works fine, i think. 
I use RPCS3 v0.0.6-7906-956d0394 Alpha | master. This game was booting without problems on older builds of RPCS3, for example v0.0.5-7619-dbd48145. Also, does new versions of rpcs3 creates log file?

**Comment by Asinin3** [comment] 2019-04-01 18:07
Can you try more builds inbetween those two to find exactly where it broke? no need to try each one-by one, just use process of elimination. Try one directly inbetween then repeat that until you can narrow it down. Once you find the exact build that broke the game then developers can identify the issue and fix it easier. Since it's an RSX error, it was probably one of kd-11's changes that broke it.

Provide log file, and if you know how, tag the pull-request that broke it in the github issue itself. This kind of testing is necessary when reporting a regression, as it's not up to the developers to do testing to find what caused a regression it's up to the person reporting the problem.

**Comment by Emulator-Team-2** [comment] 2019-04-01 18:21
@Asinin3 
This is already fixed in KD-11 fbo_fixes branch.

**Comment by Emulator-Team-2** [comment] 2019-04-02 13:14
Fixed by #5785

**Comment by kd-11** [comment] 2019-04-09 10:43
Closing as fixed.

**Closed by kd-11** 2019-04-09 10:43 UTC
