### ISSUE TITLE
Rpcs3 won't open

### ISSUE THREAD

**Issue by Gunzerker111** [RPCS3/rpcs3#4952] opened 2018-08-04 16:15 UTC
Whenever i try to run Rpcs3, it doesn't open and if i close the program in Task Manager and open it again, it just runs in the background and never opens?

**Comment by legend800** [comment] 2018-08-04 16:39
Does this look like a help forum? Close this and follow the instructions on how to get help on the main site.

**Comment by elad335** [comment] 2018-08-04 16:42
its a duplicate of #4625 anyway

**Closed** 2018-08-04 16:58 UTC
