### ISSUE TITLE
Demon's Souls - no sound after boot screen.

### ISSUE THREAD

**Issue by isshininu** [RPCS3/rpcs3#8791] opened 2020-08-28 16:52 UTC
I have noticed, that in last builds there is no sound in Demon's souls (BLES00932).
The start screen when you need to press OK have whiiish sound, but video and the rest of the game have no sound.

[RPCS3.zip](https://github.com/RPCS3/rpcs3/files/5143241/RPCS3.zip)

**Comment by Asinin3** [comment] 2020-08-28 16:53
If you've noticed it in the "last builds" then do some testing and find where it broke please.

**Comment by isshininu** [comment] 2020-08-28 17:24
I can't make it work even with three month old build?

**Comment by sampletext32** [comment] 2020-08-28 17:29
> I can't make it work even with three month old build?

In this case, it's likely some problem on your side. Because others don't experience such an issue. Even on 3-months-old builds.

**Comment by isshininu** [comment] 2020-08-28 17:33
> > I can't make it work even with three month old build?
> 
> In this case, it's likely some problem on your side. Because others don't experience such an issue. Even on 3-months-old builds.

Perhaps. I reinstalled DirectX and Visual Redistributable 2019, still no effect... What could cause this?

**Comment by RainbowCookie32** [comment] 2020-08-28 17:34
Maybe a bad dump, or the disc cache getting corrupt? Try to validate the dump and delete the contents on dev_hdd**1**

**Comment by RainbowCookie32** [comment] 2020-08-28 17:54
Just checked locally on latest master and the game has sound all the way from booting to getting ingame

**Comment by isshininu** [comment] 2020-08-28 18:16
I have replaced game files with 100% working copy, cleared hdd1, cleared RPCS3 install and reinstalled 4.86 firmware.
All other games have sound, Demon's souls have sound only on "This game is compatible..." screen, when I press OK.

**Comment by bevanweiss** [comment] 2020-08-29 05:59
@isshininu What OS version are you running?
Perhaps you could try running this with OpenAL for the Audio Out setting to see if this would change anything.
In fact it's worth you going through all the various audio settings, and just confirming that none work for your configuration on this game.
Is there a reason you didn't just provide the RPCS3.log.gz file, and instead zipped up the log yourself?
Can you supply a screenshot of the game audio config screen?

**Comment by isshininu** [comment] 2020-08-30 08:27
> What OS version are you running?

Windows 10 LTSC, version 1809 (17763.1432)
> Perhaps you could try running this with OpenAL for the Audio Out setting to see if this would change anything.
> In fact it's worth you going through all the various audio settings, and just confirming that none work for your configuration on this game.

OpenAL and XAudio not working past "OK" screen either.

> Can you supply a screenshot of the game audio config screen?
![Снимок экрана (550)](https://user-images.githubusercontent.com/6324523/91654706-30b2d900-eabc-11ea-8780-69ebd8aaf628.png)

**Comment by bevanweiss** [comment] 2020-08-30 08:44
There are some funny things in the log:
·E 0:00:34.976274 {PPU[0x1000000] Thread (main_thread) [0x01543ce8]} SYS: 'sys_mutex_lock' failed with 0x80010008 : CELL_EDEADLK [1]
But as far as I can see, this is the first sys_mutex_lock call in the execution, so Dead Lock prevention shouldn't be in place.

But I think it might be this one that's the reason for the audio stopping.
·E 0:00:36.753751 {PPU[0x1000013] Thread (_cellsurMixerMain) [0x01549a28]} SYS: 'sys_mutex_lock' failed with 0x80010008 : CELL_EDEADLK [1]

As to why it's triggering the deadlock prevention.. unsure if it's just the game code (i.e. it should happen), or if there might be something on the emu side.  It probably needs @elad335 or similar to look into it.

**Comment by elad335** [comment] 2020-10-27 14:53
its been a few months yet noone repriduced this issue other than the authour, could be a bad dump as suggested.
Closing until more information about how to reproduce is added.

**Closed by elad335** 2020-10-27 14:53 UTC
Labels: Need Information

**Comment by isshininu** [comment] 2020-10-28 07:01
I were testing this issue today on new hardware.
On clean installation sound present, after I copy and pasted it's content into old folder with basically same file structure  - sound disappears. I will try to isolate issue later.

**Comment by isshininu** [comment] 2020-10-28 20:34
It looks like I have sound disabled in game settings
