### ISSUE TITLE
Save data issue in Utawarerumono [BLJM61288] [BLJM61331]

### ISSUE THREAD

**Issue by heyrict** [RPCS3/rpcs3#5505] opened 2019-01-05 06:41 UTC
Instead of using separate folders, the game seems to store all save data in the same folder.

```
BLJM61288-UT2/
├── GAME-000.DAT
├── GAME-001.DAT
├── GAME-002.DAT
├── ICON0.PNG
├── PARAM.SFO
├── PIC1.PNG
├── SYSTEM.DAT
└── THUMB.DAT
```

Except for the save data listed in `PARAM.SFO` location `0xf5`, all other save data will not load.
Overwriting `PARAM.SFO` will cause the corresponding save data to be loaded.

To reproduce, e.g.

1. Save in the 001 save slot, location `0xf5` to `0x100` in `PARAM.SFO` will be updated with `GAME-001.DAT`.
2. Save in the 002 save slot, location `0xf5` to `0x100` in `PARAM.SFO` will be updated with `GAME-002.DAT`.
3. Restart game, the 001 save cannot be loaded, while 002 save works.
4. Edit `PARAM.SFO`, replace `GAME-002.DAT` with `GAME-001.DAT`.
5. Restart game, the 002 save cannot be loaded, while 001 save works.

build 7639

The savedata for [BLJM61288] and [BLJM61331]: [savedata.tar.gz](https://github.com/RPCS3/rpcs3/files/2729252/savedata.tar.gz)

PS: If system data is not saved along with normal save data, there will be no `GAME-???.DAT` in `PARAM.SFO` and all save data will not load.

PS2: Deleting a save data will pop an error dialog in rpcs3 and the corresponding DAT file will not be deleted.

**Comment by benderscruffy** [comment] 2020-02-11 12:16
time to update the issue

**Comment by magiruuvelvet** [comment] 2020-02-11 12:30
experienced this issue a couple days ago, there was some regression in rpcs3 because past versions could load the saves just fine

creating a new save works without issues, just the old saves can't be loaded anymore

**Comment by AniLeo** [comment] 2020-09-04 10:13
Can be closed as the issue was solved per your report, there was also a similar fix recently (after your report) for a similar issue happening on Call of Duty games, the older behavior was incorrect thus glitching the old saves, if this still happens with the latest build, please ping for reopening

**Closed by AniLeo** 2020-09-04 10:13 UTC
Labels: Bug, Savedata
