### ISSUE TITLE
COD Black Ops 2 [NPUB31054] - Text not visible

### ISSUE THREAD

**Issue by Krishster** [RPCS3/rpcs3#8718] opened 2020-08-11 16:42 UTC
In COD Black Ops 2 [NPUB31054] text in the menu as well as ingame not visible properly. It is just showing as some blocks (screenshot 1 & 2). But in the cut scenes text is properly visible (screenshot 3). Screen shots, RSX capture and log is attached.
1. ![2020-08-03 01-21_page_3](https://user-images.githubusercontent.com/64323517/89924181-45b7ed00-dc1f-11ea-922c-17a5038f252c.jpg)
2. ![2020-08-03 01-21_page_4](https://user-images.githubusercontent.com/64323517/89924200-4badce00-dc1f-11ea-9faa-06492e83d898.jpg)
3. ![2020-08-03 01-21_page_5](https://user-images.githubusercontent.com/64323517/89924211-4fd9eb80-dc1f-11ea-8e48-0f2b20cc6d59.jpg)

RSX capture -[NPUB31054_20200811215312_capture.zip](https://github.com/RPCS3/rpcs3/files/5058228/NPUB31054_20200811215312_capture.zip)
LOG - [RPCS3.log.zip](https://github.com/RPCS3/rpcs3/files/5058236/RPCS3.log.zip)

**Comment by Yahfz** [comment] 2020-08-12 16:11
You said it's a regression, what is the commit that broke it?

**Comment by Krishster** [comment] 2020-08-12 16:31
> You said it's a regression, what is the commit that broke it?

sorry for that

**Comment by QuentinLeloire** [comment] 2020-10-10 18:11
I have same troubleshooting, I think it's due to .ff and / or .ipak files that are missing in your game USRDIR folder.
I found the same issue because I downloaded a copy, that not contains all files. My Blu-ray original disk is broken and I haven't found other solutions yet

**Comment by AniLeo** [comment] 2020-10-10 18:14
No, it seems VERY doubtful this issue is caused by missing files at all, whatever issues you have with broken copies are unrelated

**Comment by Krishster** [comment] 2020-10-10 18:24
> I have same troubleshooting, I think it's due to .ff and / or .ipak files that are missing in your game USRDIR folder.
> I found the same issue because I downloaded a copy, that not contains all files. My Blu-ray original disk is broken and I haven't found other solutions yet

this blurred text seems to happen also with other versions of cod black ops 2 ... i have checked with youtube..

**Comment by QuentinLeloire** [comment] 2020-10-13 22:24
> > I have same troubleshooting, I think it's due to .ff and / or .ipak files that are missing in your game USRDIR folder.
> > I found the same issue because I downloaded a copy, that not contains all files. My Blu-ray original disk is broken and I haven't found other solutions yet
> 
> this blurred text seems to happen also with other versions of cod black ops 2 ... checked from youtube

Yes, It was issued with Xemu emulator in some forums, maybe have you seen similarity on non-emulated cases ?

**Comment by QuentinLeloire** [comment] 2020-12-27 10:46
It seems to be a duplicated issue ?

https://github.com/RPCS3/rpcs3/issues/6461

**Comment by MetOffi** [comment] 2021-08-08 22:11
DId anyone find a fix for this in the end? Or is it better to run the game on another platform?

**Comment by Satan86** [comment] 2021-08-08 22:12
The bug still happens, and yes, playing on PC natively is the best experience for this game

**Comment by kd-11** [comment] 2022-01-23 14:09
We need some updated captures for this.

**Comment by gamrXerus** [comment] 2022-01-23 15:30
Here you go @kd-11 . RSX capture: https://drive.google.com/file/d/1gIX1Hw_XDVbbq5XsqXVmnjph2SUjtqVI/view?usp=sharing
Renderdoc: https://drive.google.com/file/d/1TEFd4nkyN3Kq-c8KcpsFZ9GsHf3RkJSk/view?usp=sharing

**Comment by pemberton79** [comment] 2022-02-11 20:14
Any updates?

**Comment by mtrevor2** [comment] 2022-04-25 04:31
anyone find a fix?

**Comment by Fabxx** [comment] 2022-08-12 14:14
Can confirm this bug on last build of RPCS3 and BLUS31011

**Comment by Darkhost1999** [comment] 2022-09-11 03:03
Does anyone want to provide new logs?
1 normal + 1 with ppu and spu debug enabled.
Can also provide an up to date RSX capture if you'd like. Just a simple alt + c will pause and capture. And a Ctrl + R will let you continue playing as if nothing happened. Then when you're done enjoying the game find your capture inside your captures folder.

Up to date information not only allows for comparitive data with old information, but provides the latest error codes and loggings that may have changed as the emulator has improved thus exposing the issue to be investigated.

So when you comment "still an issue" please don't forget to attach a log to the message else only the OP from 2 years ago will have provided a log when nobody else has.

**Comment by TigiHof** [comment] 2022-09-11 14:14
> Does anyone want to provide new logs?

There you go.

![BLES01719_screenshot_2022_09_11_15_54_58](https://user-images.githubusercontent.com/31275840/189531739-bb2fa337-d61f-4229-b090-8eb807e96cd2.png)

RSX Capture (split due to github file size limit):
[BLES01719_20220911155656_capture.001.zip](https://github.com/RPCS3/rpcs3/files/9542713/BLES01719_20220911155656_capture.001.zip)
[BLES01719_20220911155656_capture.002.zip](https://github.com/RPCS3/rpcs3/files/9542715/BLES01719_20220911155656_capture.002.zip)

Normal Log:
[RPCS3.log.normal.gz](https://github.com/RPCS3/rpcs3/files/9542716/RPCS3.log.normal.gz)

Debug Log:
[RPCS3.log.debug.gz](https://github.com/RPCS3/rpcs3/files/9542718/RPCS3.log.debug.gz)

**Comment by Julovibe** [comment] 2022-12-10 06:14
> > Does anyone want to provide new logs?
> 
> There you go.
> 
> ![BLES01719_screenshot_2022_09_11_15_54_58](https://user-images.githubusercontent.com/31275840/189531739-bb2fa337-d61f-4229-b090-8eb807e96cd2.png)
> 
> RSX Capture (split due to github file size limit): [BLES01719_20220911155656_capture.001.zip](https://github.com/RPCS3/rpcs3/files/9542713/BLES01719_20220911155656_capture.001.zip) [BLES01719_20220911155656_capture.002.zip](https://github.com/RPCS3/rpcs3/files/9542715/BLES01719_20220911155656_capture.002.zip)
> 
> Normal Log: [RPCS3.log.normal.gz](https://github.com/RPCS3/rpcs3/files/9542716/RPCS3.log.normal.gz)
> 
> Debug Log: [RPCS3.log.debug.gz](https://github.com/RPCS3/rpcs3/files/9542718/RPCS3.log.debug.gz)

Is there a step by step tutorial I can find for this or that someone may provide if possible?

**Comment by kd-11** [comment] 2023-01-02 19:46
Fixed by https://github.com/RPCS3/rpcs3/pull/13158

**Closed** 2023-01-02 20:03 UTC
Labels: Bug
