### ISSUE TITLE
Ratchet and Clank: A Crack in Time crashes

### ISSUE THREAD

**Issue by tomtriggs** [RPCS3/rpcs3#10623] opened 2021-07-28 22:40 UTC
## Quick summary
Crashing, predominantly when entering or exiting vendors menus.
## Details
Emulator crashes, mainly when entering or exiting menus. Has happened at other times though, such as when jumping on a moon and landing on a moon. Seems to only happens on moons as have not experienced on a planet or in space. I have never experienced this issue on a ps3.
I am also experiencing effects in the world having black squares around them, but do not have a screenshot at the time.

* OS - Windows 10
* CPU - Ryzen 3600
* GPU - Radeon 5700
* Driver version - 21.6.1
* etc.

[RPCS3 Crash.log](https://github.com/RPCS3/rpcs3/files/6896797/RPCS3.Crash.log)

**Comment by kd-11** [comment] 2021-07-29 17:03
Enable "Read Color Buffers" for the black squares.

**Comment by kd-11** [comment] 2021-07-29 17:31
Disable "Write color buffers" and enable "Read color buffers".
The crash described here is a known issue and is part of ongoing work.
Closing as a duplicate of https://github.com/RPCS3/rpcs3/issues/9049
See https://github.com/RPCS3/rpcs3/issues/9133 for technical details

**Closed by kd-11** 2021-07-29 17:31 UTC
