### ISSUE TITLE
Loading Problem with Vulkan

### ISSUE THREAD

**Issue by Wowie4** [RPCS3/rpcs3#13125] opened 2022-12-26 05:59 UTC
I have a game for the RPCS3 emulator that has continuously crashes indicating the problem with my renderer, being vulkan.

OS - MacOS Monterey
CPU - 1.6 GHz Dual-Core Intel Core i5
GPU - Intel HD Graphics 6000 1536 MB

[RPCS3 log.log](https://github.com/RPCS3/rpcs3/files/10301806/RPCS3.log.log)
![Screen Shot 2022-12-25 at 10 58 56 PM](https://user-images.githubusercontent.com/121417809/209509233-28810d02-071d-4ae9-a523-0ad4fb934b75.png)

I'm seriously confused about whats wrong with my macbook and I'm just looking for anyone who can understand what needs to be fixed or anyways to by pass the fatal errors.

**Comment by AniLeo** [comment] 2022-12-26 06:08
We do not support Intel iGPUs on macOS, you need a dedicated GPU, but seeing as your CPU is incredibly weak, you need a whole new PC altogether.
Duplicate of #12404

**Closed by AniLeo** 2022-12-26 06:08 UTC
