### ISSUE TITLE
Audio : Project Diva F Music not synchronized

### ISSUE THREAD

**Issue by giandiablo33** [RPCS3/rpcs3#1861] opened 2016-07-03 00:14 UTC
Using XAudio2. After 1-2 minutes playing Project Diva F the music starts to de-synchronize with the PV, the rest of the audio is synchronized. OpenAl also de-synchronize. Game running at 25-30 fps on DX12 and Vulkan
Edit: GitHub doesn't let me attach the log file, uploaded to an alternative server:
http://www.mediafire.com/download/be9r93a11v62q6n/RPCS3.log

**Comment by Nezarn** [comment] 2016-07-03 08:46
can you post how to reproduce this bug? (i've never encountered music desync\garbage outside DX12....also since new ogl renderer is merged game can't even go ingame with ogl, so idk how you tested it.)

**Comment by giandiablo33** [comment] 2016-07-03 15:06
Well, I just start playing a song, game drops to 25 fps for 5-10 seconds and the music start to de-synchronize, in Vulkan starts to desynch a little bit later. with OpenAl music starts desynched from the beginning and sutters.

**Comment by giandiablo33** [comment] 2016-07-03 15:08
Oh, I put OGL in the tag? My bad.

**Comment by giandiablo33** [comment] 2016-07-03 15:49
I have a a8-7650k Overclocked (4.0 Ghz) with a R7 7650k 2GB (The integrated GPU, also overclocked) and 8GB of ram. This happens on all songs, some just a little bit later than others. Music in the menus works fine. Also, when i pause the game for 1-2 minutes the desynch fixes only for a moment and desynchs again

**Comment by giandiablo33** [comment] 2016-07-03 15:58
Also, if i start another song or retry the same songe, the de-sync is still there

**Comment by Nezarn** [comment] 2016-07-08 12:23
I was able to reproduce this with running recording software in the background + chrome with a twitch stream + on integrated Intel HD4600. (with DX12)

Someone should test this on a real graphics card. (since when i had my 970 i didn't had this issue, so im guessing some kinda cpu\gpu bottleneck...)

**Comment by paulsapps** [comment] 2016-07-08 12:47
Isn't it expected that audio will lag/fall out of sync if under too much load?

**Comment by giandiablo33** [comment] 2016-07-08 12:51
Problem is, music is only out of sync

**Comment by giandiablo33** [comment] 2016-07-08 12:51
Pd: fucked up and closed the thread sry

**Comment by kd-11** [comment] 2016-07-09 17:13
Xaudio 2 is not synced to framerate. OpenAL is synchronized and thats what causes stuttering i8f your fps is below the max. A true fix would be synchronization plus timestretch filtering, but I'm not sure anyone is willing to undertake that task.

**Comment by AniLeo** [comment] 2017-02-27 11:58
This is no longer an issue - I can play the game on Interpreter fast without audio desync. (I have an i7 6700HQ)

Could you check as well?

**Comment by raven02** [comment] 2017-02-27 13:35
I also tested it and it works very well on both LLVM and interpreter fast . I'll close it at this moment .

**Closed by raven02** 2017-02-27 13:35 UTC
Labels: audio, longterm
