### ISSUE TITLE
Games Haven't Retested For 2 Years

### ISSUE THREAD

**Issue by Rafidmuhaiminwafi** [RPCS3/rpcs3#4343] opened 2018-03-26 07:07 UTC
I Found Three Games From Loadable Section Which Haven't Retested For More Than Two Years. I Think That These Game Must More Compatible Than Before. But In My Country I Need To Buy 1 Gb Spending 300 Money. So It Is Not Possible To Download Those Games. So I Am Posting The Id Of Those Games So Anyone Could Test.

1.NPEA00008 Last Test 2016-01-15
2.NPUA80128 Last Test 2016-01--11
3NPUA80133 Last Test 2016-01-11

**Comment by Asinin3** [comment] 2018-03-26 09:18
Last tested date is only updated when status for a game changes, it is very inaccurate to think that no one has tested since that date. Also many testers will not update a thread unless status changes (I try to unless last update was recent). Tested date for one specific ID largely doesn't matter if the other IDs were updated as well.

Github is for tracking issues such as regressions with code please don't spam it. We have a forum for compatibility reports and if you want to make a list of games that need testing then you can make a thread under the General Discussion topic. But even then, it would largely not be that useful because as I said, last tested date is not accurate.

Piracy is also absolutely against our rules.

**Comment by Nicba1010** [comment] 2018-03-26 09:18
1. We do not support piracy
2. This is an abomination
3. At least edit it to look nicer before this issue gets closed

Edited version:
> I found three games from Loadable section which haven't been retested for more than two years. I think that these games could be more compatible than before. But bandwidth in my country is very expensive (I need to pay 300 of my local currency which is XXX to get 1 GigaByte). This way it is not viable for me to download these games. Therefore I'll post the IDs of the games so someone can test them.
> 
> 1. NPEA00008 Last Test 2016-01-15
> 2. NPUA80128 Last Test 2016-01-11
> 3. NPUA80133 Last Test 2016-01-11

**Comment by digitaldude555** [comment] 2018-03-26 11:37
@Rafidmuhaiminwafi  I tested just now, nothing improved.

**Comment by kd-11** [comment] 2018-03-26 12:00
This is a discussion for forums, not code analysis. Closing as invalid

**Closed by kd-11** 2018-03-26 12:00 UTC
