### ISSUE TITLE
[NVIDIA] Demon's Souls [BLES00932] Sun shines through solid objects

### ISSUE THREAD

**Issue by ao8833** [RPCS3/rpcs3#7213] opened 2020-01-07 17:42 UTC
![snapshot](https://user-images.githubusercontent.com/55032464/71915096-51b86980-317b-11ea-86f4-75b77fa69354.jpg)
**[Video 1](https://imgur.com/a/V2LOWDe) | [Video 2](https://imgur.com/a/aa1HE2W)**

rpcs3-v0.0.8-9342-ad845861_win64
renderer Vulkan
write color buffers on
xinput controller
default settings for everything else

Windows 10, Ryzen 3700, GeForce GTX 1060 6GB (driver 441.41)

The bug can take a minute to appear. It also happens in fullscreen mode and regardless of vsync and frame limit.

**Comment by ao8833** [comment] 2020-01-07 18:37
Side note: At the time of posting I still had [this lens flare mod](https://www.nexusmods.com/demonssouls/mods/3) installed. I hoped it would fix anything. Obviously it didn't. Anyway, this is how it looks without modification:
![2](https://user-images.githubusercontent.com/55032464/71919173-4cabe800-3184-11ea-8f4e-d341e25a05ad.jpg)

**Comment by kd-11** [comment] 2020-01-07 18:58
Check older builds and see if the issue is a regression or maybe newer nvidia drivers changed something.

**Comment by ao8833** [comment] 2020-01-07 20:51
It looks to me like the issue was introduced in build 0.0.7-9271-1b27ccec.
Build 0.0.7-9259-0b784043 is fine.

The sun always pops up around 105 seconds after the "now loading" screen has gone away. No controller input necessary. Warping between Nexus and 1-1 or returning to the title screen will not reset it, i.e. the sun will peek through immediately.

**Comment by kd-11** [comment] 2020-01-07 22:28
Thanks for testing. I had suspected this regression existed for some time. To fix it is very simple, but would likely cause some performance losses, I'll think of another way to do it.

**Comment by kd-11** [comment] 2020-01-08 13:57
After running more tests this is not present on RADV drivers. They run the occlusion tests correctly. This means something is wrong with NV drivers and they need a workaround.

**Comment by kd-11** [comment] 2020-01-08 13:58
Tested by hanging around in the nexus for around 10 minutes. Nothing breaks.

**Comment by kd-11** [comment] 2020-01-08 14:49
Retest with https://github.com/RPCS3/rpcs3/pull/7216

**Comment by kd-11** [comment] 2020-01-08 16:04
I have tested a few games with the PR and it seems to resolve the problem on my 1050Ti. If you still have the problem with the newest master, please ask to reopen.

Closing as fixed by https://github.com/RPCS3/rpcs3/pull/7216

**Closed by kd-11** 2020-01-08 16:04 UTC
Labels: Driver: NVIDIA, Render: Vulkan

**Comment by ao8833** [comment] 2020-01-08 17:05
rpcs3-v0.0.8-9350-ef3b0db7_win64 fixed the issue for me as well. Good detective work!

Nvidia driver 441.87 (released yesterday) showed the same behavior, by the way.

**Comment by GitArUs** [comment] 2022-09-10 19:46
@kd-11 This happens again after PR #12632.

**Comment by kd-11** [comment] 2022-09-10 19:56
Open a new ticket.
