### ISSUE TITLE
WALL-E [BLUS30151] on macOS silicon, severe camera glitch

### ISSUE THREAD

**Issue by domrozum** [RPCS3/rpcs3#14876] opened 2023-12-05 17:11 UTC
### Quick summary

Ever since the glitched blue textures was fixed this year, WALL-E [BLUS30151] is unplayable, specifically on macOS Silicon (possibly Intel too), where some camera movement that is done by the game completely distorts the view, and even breaks the movement of the player as the camera is moving. Videos attached. Note that this issue does not appear in Windows builds.

macOS:
https://github.com/RPCS3/rpcs3/assets/101346841/b70e21b9-7999-48c6-91be-3dca96009e06

Windows:
https://github.com/RPCS3/rpcs3/assets/101346841/59eebee7-5ed4-4e99-b208-777b8fd7ac96

### Attach a log file

[RPCS3.log.gz](https://github.com/RPCS3/rpcs3/files/13564641/RPCS3.log.gz)

### Attach capture files for visual issues

[BLUS30151_20231205120927_capture.rrc.gz](https://github.com/RPCS3/rpcs3/files/13564961/BLUS30151_20231205120927_capture.rrc.gz)

### System configuration

MacBook Pro
M3 Pro
11-core CPU, 18-core GPU
18GB RAM

### Other details

I don't believe this issue occurred before the major blue-textures glitch was fixed..

**Comment by AniLeo** [comment] 2023-12-19 19:18
Likely the same root cause as #14794, needs confirmation on macOS 12/13

**Comment by shinra-electric** [comment] 2023-12-22 07:17
If this has the same cause as #14794, then it would be fixed in Sonoma 14.3 beta.

**Comment by AniLeo** [comment] 2024-01-01 16:20
I'm closing this one as duplicate since the issue was made on macOS 14.1.1, which we do not support as it's impacted by the Rosetta 2 bug that causes random issues.

**Closed by AniLeo** 2024-01-01 16:20 UTC
Labels: Need Information, OS: Mac
