### ISSUE TITLE
Native resolution Game

### ISSUE THREAD

**Issue by aakh1361** [RPCS3/rpcs3#2436] opened 2017-02-27 00:35 UTC
Hi
I Have offer To every Game Boot in Self Native resolution By Default
We Can Read resolution of PARAM.SFO

if do maybe we don't have Error "E {rsx::thread} RSX: NV3089_IMAGE_IN_SIZE:unknown origin (0)"

**Comment by raven02** [comment] 2017-02-27 13:36
Duplicate of #2282

**Closed** 2017-02-27 13:36 UTC
