### ISSUE TITLE
Kingdom Hearts 1.5 Final mix [BLUS31212] Specific Cutscenes Glitch

### ISSUE THREAD

**Issue by eroden** [RPCS3/rpcs3#3134] opened 2017-08-01 13:42 UTC
Hello. Kingdom Hearts 1.5 Final mix [BLUS31212] is very playable. Cutscenes in few parts of the game fail to load properly and display an
 image of the last paused screen. For example it occurs during final boss cutscene in Agrabah and in the beginning cutscene in Atlantica. 

![screenshot_41](https://user-images.githubusercontent.com/30627339/28828049-d8cfac4e-76cf-11e7-8368-557f315890cd.png)
![screenshot_42](https://user-images.githubusercontent.com/30627339/28828054-da7be4ae-76cf-11e7-9647-6e4c1061e710.png)
![screenshot_43](https://user-images.githubusercontent.com/30627339/28828050-d8d69928-76cf-11e7-89ae-6e45ce20ad00.png)

The first time it occured in the Agrabah cutscene, I've managed to fix it by switching renders from Vulkano to Opengl and ticking some graphic fixes. But now in the Atlantica cutscene it doesn't seem to work.

It might be related to this "wave'ing special effect" (sorry not sure how exactly do you call it), because it only appears during cutscenes that have this effect.

I will attach a save file, just warp to the Atlantica and disembark on the world.

[BLUS31212-BISLPS25198.zip](https://github.com/RPCS3/rpcs3/files/1190719/BLUS31212-BISLPS25198.zip)

spec.

GTX 970 
I5-4440
8 RAM
Windows 10

I'm using the most recent rpcs3 build.

**Comment by anoadragon453** [comment] 2017-08-02 01:31
Hey trying to confirm this, real noob question. I'm stick the files from the file in `dev_hdd0/home/00000001/savedata/BLUS31212-BISLPM66676LAUNCHER/` but am unable to find any of the saves in the in-game loading dialog. Should they be dropped somewhere else?

**Comment by Zardas81** [comment] 2017-08-02 07:33
Yeah, go back one folder and put them in savedata. Saves are just stored bulk there, there's no folder structure per game.

**Comment by Camaro67** [comment] 2017-08-03 23:40
I am facing the same problem...final boss in agrabah setting to Open GL and enabling write color buffers and texture scaling fixed it, but in atlantica nothing works..using latest build btw..

I5 6400 and GTX 960

**Comment by anoadragon453** [comment] 2017-08-04 02:08
@Zardas81 Yeah not sure, I've got the SYS-* and USR-* files in `dev_hdd0/home/00000001/savedata/BLUS31212-BISLPM66676LAUNCHER/` as well as `dev_hdd0/home/00000001/savedata/` (of which I'm sure the latter is incorrect, but no matter) however now I'm getting the following in the log:

```
E {PPU[0x1000000] Thread (main_thread) [0x02c63ee4]} sys_fs: sys_fs_stat(“/dev_hdd1/cache/BLUS31212//SaveData0/BISLPS-25198-90/BISLPS-25198-90”) failed: not found
E {PPU[0x1000000] Thread (main_thread) [0x02c63ee4]} 'sys_fs_stat' failed with 0x80010006 : CELL_ENOENT
```

Should probably make my own issue with that tbh, but yeah, can't test this until that's resolved.

**Comment by anoadragon453** [comment] 2017-08-04 03:51
Alright, had to rename the game folder to the one you had in your zip.

I can confirm the same issue. Switching to OpenGL does not work.

![screenshot_20170804_034214](https://user-images.githubusercontent.com/1342360/28953361-0bb15c68-78c7-11e7-8bd2-d570648e3af3.png)
![screenshot_20170804_034226](https://user-images.githubusercontent.com/1342360/28953362-0bb71176-78c7-11e7-89a3-138e54176ad5.png)

Also getting some blue on characters in the save menu, and during scene transitions.
![screenshot_20170804_034435](https://user-images.githubusercontent.com/1342360/28953393-3e1092f0-78c7-11e7-97ae-0ee348406f38.png)

And that 'Easy for you to say' message keeps appearing and the text scrolls, even though we've clearly passed that bit of dialogue in the game.

[RPCS3.zip](https://github.com/RPCS3/rpcs3/files/1199191/RPCS3.zip)

**Comment by eroden** [comment] 2017-08-09 20:01
Hello. Not sure if that was fixed in the latest build, but thanks to jarvis

[rpcs3.zip](https://github.com/RPCS3/rpcs3/files/1212708/rpcs3.zip)


here's the working fix.

**Comment by anoadragon453** [comment] 2017-08-10 00:35
@eroden Is that just a build of master?

**Comment by Asinin3** [comment] 2017-08-10 00:49
Well the build says 5586 so it should just be this: https://ci.appveyor.com/project/rpcs3/rpcs3/build/0.0.3-5586 right?

**Comment by anoadragon453** [comment] 2017-08-10 03:15
@Asinin3 Build version depends on a version variable contained within the codebase. IIRC it has to be manually updated.

**Comment by Asinin3** [comment] 2017-08-10 03:25
Build count is updated when a PR is merged into master, they get automatically? built (providing they don't have any compile errors) then checked again to make sure no malware or any critical issues were in the code. Then pushed to the main website as far as I can tell, which is why you should always use: https://rpcs3.net/compatibility?b not the history page on appveyor unless you know what your doing.

_Hopefully that's correct anyway_

**Comment by Dokman** [comment] 2017-08-10 08:31
i will test if i have this bug tomorrow

**Comment by apathyrecharge** [comment] 2017-08-10 20:40
+1, i would only get this error on cutscenes however the entire genie jafar fight is hidden behind this glitch - its as if the glitch outputs a still image, but everything will still be rendered behing this "image".

trying @eroden s build caused rpcs3 to crash when launching the game.

**Comment by Asinin3** [comment] 2017-08-10 23:04
Did you try deleting the data folder?

**Comment by macray125** [comment] 2017-08-29 23:43
Hi Ma'am/Sir
I also got the same issue about "Cutscenes Glitch" when landing to atlantica

I also used the fix that @eroden posted and delete data files but didn't work

result when I applied the @eroden posted
![Uploading atlantica3.png…]()
![atlantica4](https://user-images.githubusercontent.com/4024193/29848972-8073dcb2-8d56-11e7-941b-8f37053e52a1.png)

here the **log files**.
[rpcs3 BLUS31212.txt](https://github.com/RPCS3/rpcs3/files/1262035/rpcs3.BLUS31212.txt)

the version of my rpcs3 before applying the fix is "rpcs3-v0.0.3-2017-08-27-25709112_win64"

**Comment by AniLeo** [comment] 2017-08-29 23:48
@macray125 That's not a log file. Log file is RPCS3.log next to the main executable

**Comment by macray125** [comment] 2017-08-30 00:25
ok. @AniLeo here is the log file.
[RPCS3.zip](https://github.com/RPCS3/rpcs3/files/1262084/RPCS3.zip)

**Comment by AniLeo** [comment] 2017-08-30 00:27
Video:
  Renderer: D3D12

This is not supported. Use Vulkan or OpenGL.

**Comment by macray125** [comment] 2017-08-30 00:32
@AniLeo there's no Vulkan on my list, and Yes already used OpenGL and still not working

![solution1](https://user-images.githubusercontent.com/4024193/29850052-5c0d8b8c-8d5d-11e7-9aa7-1b65e049257e.png)

**Comment by AniLeo** [comment] 2017-08-30 00:34
Then it's an user error, your drivers aren't properly installed to start with. 950M has Vulkan support in NVIDIA's drivers.
https://developer.nvidia.com/vulkan-driver

**Comment by macray125** [comment] 2017-08-30 00:40
@AniLeo ok thanks I'll try to install it. I'll message you if everything's work. Thanks.

**Comment by macray125** [comment] 2017-08-30 01:34
@AniLeo Vulkan also not working also in latest build of rpcs3.

**Comment by JacobAL** [comment] 2017-09-03 09:52
This is still an issue for me. Using vulkan. Has happened before in sections of the game but I can't get into atlantica with this bug.

**Comment by JacobAL** [comment] 2017-09-30 09:48
Here's a video, if it helps at all: https://www.youtube.com/watch?v=BHnDMKhSdd0

**Comment by JacobAL** [comment] 2017-10-06 20:18
Still broken in newer builds.

**Comment by RealZaramir** [comment] 2017-10-21 17:28
Does anyone have an agrabah save file i can use? i deleted mine accidently when i tryed to switch versions...

**Closed** 2017-10-28 09:46 UTC

**Comment by JacobAL** [comment] 2017-11-12 15:45
Seems to be broken once more. (https://i.imgur.com/WYjR6Wp.png)

**Comment by Illynir** [comment] 2017-11-12 16:51
GPU texture scaling crashes KH 1 and KH 2 on Vulkan, tries without or uses OGL.

**Comment by JacobAL** [comment] 2017-11-12 21:48
Thanks
