### ISSUE TITLE
{rsx::thread} class std::runtime_error thrown: Unknown primitive type 65 (in file Emu\RSX\gcm_enums.cpp:45) in Silent Hill Downpour

### ISSUE THREAD

**Issue by Psycho-A** [RPCS3/rpcs3#4283] opened 2018-03-13 20:50 UTC
Met this at the Diner level of game using OpenGL renderer (with GPU scaling) and latest emu master build, and then game was stopped. Never seen this before. Seems to regression...

**Comment by isshininu** [comment] 2018-03-14 02:46
Uh, and no log?

**Comment by Psycho-A** [comment] 2018-03-14 05:26
Ah, you right. I'll save it if this will happen again.

**Comment by kd-11** [comment] 2018-03-14 05:37
This is a spurious error that occurs when rsx runs too fast and cell is still writing stuff to render. This is not ny itself an error. Just restart the game, its unlikely to happen again. You may also use the slower opengl renderer to improve stability, vulkan is a recording api (very fast cpu side) and opengl is immediate so commands uniformly take a small fixed amount of time to execute.

**Comment by kd-11** [comment] 2018-03-17 15:02
Duplicate of https://github.com/RPCS3/rpcs3/issues/2359

**Closed** 2018-03-17 15:03 UTC
