### ISSUE TITLE
Regression: Sonic Unleashed (#9161)

### ISSUE THREAD

**Issue by vanderleivieirainacio** [RPCS3/rpcs3#9191] opened 2020-10-31 23:20 UTC
Good night.
I would like to report that the Sonic Unleashed game was working well but now, as soon as the game logo presentation videos go on, when you enter the game, simply the screen goes black, the game stops, it totally crashes, including the emulator.

![Captura de tela 2020-10-31 195456](https://user-images.githubusercontent.com/46516229/97791877-0feb2a80-1bb6-11eb-84ef-7a551ac4b3d4.png)

[RPCS3.log](https://github.com/RPCS3/rpcs3/files/5469959/RPCS3.log)

**Comment by AniLeo** [comment] 2020-10-31 23:22
Cannot reproduce.

![image](https://user-images.githubusercontent.com/10283761/97791951-e8a15700-1bcf-11eb-98b2-d066d8defcb7.png)

**Comment by vanderleivieirainacio** [comment] 2020-10-31 23:31
It doesn't really work here. My PC is:
Radeon RX 580 4GB Sapphiretech
AMD Ryzen 7 1700
Windows 10 x64 latest version
The SONIC UNLEASHED version is the American version by download (NPUB31204)
And it's still crashing, I did several tests.

**Comment by vanderleivieirainacio** [comment] 2020-10-31 23:39
Unfortunately the only information I can give you is above: Game after the video of logo presentations doesn't even enter the "press start" screen, the game stops before and the screen is black.

**Comment by Asinin3** [comment] 2020-11-01 02:44
You can try old builds. You can validate your game dump. You can let us know if it is a regression (working previously). If you're trying old builds try 111092 https://rpcs3.net/compatibility?b and the latest version.

**Comment by vanderleivieirainacio** [comment] 2020-11-01 05:42
Thanks. I did the test in the old version RPCS3 11088 and the game Sonic Unleashed worked perfectly but the game Ninja Gaiden 3 Razor's Edge does not work in this old version, only in the current version from version 11140.

**Comment by vanderleivieirainacio** [comment] 2020-11-01 06:23
It is a bug in the current version that does not let Sonic Unleashed work and as I said it only shows the presentation videos and before entering the "press start" screen everything is black and locks the emulator. I have already passed my hardware settings and unfortunately I would only know if they tested with the same settings as me, I think. I'm sorry but it is as much as I can answer about the problem.

**Comment by windwhirl94** [comment] 2020-11-01 15:24
This one has happened to me recently, too, with BLES00425 (the disc version of Unleashed). However, in my case emulation stopping happened only if I repeatedly pressed the Start button while it showed the initial loading screens (the one with the SEGA logo animation and the ones for Havok and Hedgehog Engine), with a custom config. Previous to this testing, I erased all caches and removed all custom configs for the games and RPCS3 itself, and then I made a new custom config for Unleashed.

System specs:
Windows 10 (mind, this is a Dev channel preview, build 20246.1, but for most things it can be treated as Windows 10 2004)
Ryzen 5 3600
Gigabyte Aorus RX 580, Radeon Adrenaline driver 20.10.1
RPCS3 0.0.12.11147

During the first test I simply let the game load, I didn't press any buttons. Everything ran OK until the start screen appeared, which is where I ended that first test run. No problems there.

Second test run, I pressed the Start button on my gamepad repeatedly, and once the havok logo faded to black the game stopped suddenly. When I tried to close the game, this happened:
![20201101-115901](https://user-images.githubusercontent.com/61765524/97806281-aad91880-1c39-11eb-9d88-d63182d2325d.png)
Attaching log down below. Has both test runs.
[RPCS3.log](https://github.com/RPCS3/rpcs3/files/5471173/RPCS3.log)

**Comment by vanderleivieirainacio** [comment] 2020-11-01 15:36
I also did as you said and erased all caches and custom settings and at first it worked but after I closed and opened the emulator it didn't work anymore and even after I cleared the cache and custom settings again it didn't work. The problem is as you described: the game crashes after the logo videos (SEGA, Hedgerog Engine, Havock) and the screen goes black and the emulator crashes.

**Comment by vanderleivieirainacio** [comment] 2020-11-01 15:38
My hardware is all AMD like yours. It may be a problem only on AMD hardware maybe ...

**Comment by vanderleivieirainacio** [comment] 2020-11-01 16:09
I tested it again and whenever I delete the game's cache folder and the "config.yml" file, the game works again, but after closing it and I opened the game again, it has the same problem, crashes after the logo videos (SEGA , Hedgehog Engine, Havok). I can assume that it has something to do with the cache and the config.yml file because the game only works if you delete both but it only works once, then you have to delete the folder and the config.yml file and start all over again.

**Comment by windwhirl94** [comment] 2020-11-01 17:10
I retested with the configuration you had in your log. The emulator crashed after the Havok logo fades to black in the first run. The second run went fine, the third crashed again. 
The fourth run went fine until at some point in Apotos Act 2 the emulator threw me an error about an incompatible driver (log attached).
[RPCS3.log](https://github.com/RPCS3/rpcs3/files/5471352/RPCS3.log)

Nothing changed between each run. Always using the same config. 

I'm gonna poke at this thing a little more. Maybe there's a setting that's screwing with the game.

**Comment by vanderleivieirainacio** [comment] 2020-11-01 17:23
Thank you very much for your attention!

**Comment by windwhirl94** [comment] 2020-11-02 00:40
Well, running Unleashed with the emulator in "stock" settings. First run went fine until I got memory error
`·F 0:05:13.640952 {RSX [0x00b0050]} VM: Access violation reading location 0xcf900000 (unmapped memory) [type=u0]`
Still, I managed to play quite a bit of a level, so that seems to be a different issue and I will not post the log for that here.
Second run, with stock settings, crashed just like the runs I did with custom config. Log below.
[RPCS3 - BLES00425 - Unknown Crash with default settings.log](https://github.com/RPCS3/rpcs3/files/5471499/RPCS3.-.BLES00425.-.Unknown.Crash.with.default.settings.log)

**Comment by windwhirl94** [comment] 2020-11-02 00:45
Now, I went back and tested quite a few previous builds, starting from 11088. The error we are discussing here could be reproduced only with build 0.0.12.11117 and probably latter ones. Build 11107 (which was the one right before 11117) worked fine.

Log for 11107 attached.
[RPCS3.log](https://github.com/RPCS3/rpcs3/files/5472170/RPCS3.log)

Build 11117 was born from https://github.com/RPCS3/rpcs3/pull/9161

**Comment by AniLeo** [comment] 2020-11-02 01:13
Try with "Accurate SPU DMA" and see if the issue still happens (You need to enable it by editing config.yml)

**Comment by windwhirl94** [comment] 2020-11-02 01:38
> 
> 
> Try with "Accurate SPU DMA" and see if the issue still happens (You need to enable it by editing config.yml)

No changes. During the first test-run the game works fine, the next one it crashes before reaching the start screen, the third one runs fine, and the fourth fails again. Btw, I close the whole emulator between test runs, not just the game (clarifying, since I didn't say it before), so I shouldn't be keeping anything in memory between runs to justify this... constant switch between working and not-working.

Anyway, log down below.
[RPCS3.log](https://github.com/RPCS3/rpcs3/files/5472294/RPCS3.log)

**Comment by windwhirl94** [comment] 2020-11-07 20:09
[RPCS3.log](https://github.com/RPCS3/rpcs3/files/5505374/RPCS3.log)
Tested with Linux on the latest build (11194). No changes, the emulator still crashes.

**Comment by Huskatron** [comment] 2020-11-22 07:18
This is happening to me too. On BLES00425 (European disc).

[RPCS3.log](https://github.com/RPCS3/rpcs3/files/5579114/RPCS3.log)

**Comment by JSKorbit** [comment] 2020-11-24 18:21
This has been crashing when attempting to load the title screen for the last month or so on default settings, but as of trying the latest build(11312), it worked only when changing the PPU decoder from Recompiler(LLVM) to Interpreter(Fast). Other changes didnt seem to have any impact. In another note, the game is no longer covered in wireframe on my system, though there's a lot of misrendered motion blur.

Specs:
Windows 10 19042.630 20H2
Ryzen 5 3600 w/ 3000mhz CL15 16GB
MSI 5600 XT Mech OC, Radeon driver 20.11.2
RPCS3 0.0.13.11312

**Comment by vanderleivieirainacio** [comment] 2020-12-10 15:35
I discovered two problems now: One as the friend above said, which is the game freezing and getting the black screen after the logos (SEGA, Sonic Team, Hedgehog Engine, Havok) and this freezing happens in the SPU LLVM mode. The other most recent problem now is a freeze right at the beginning of the game loading and I cannot say if it is the pre-loading of shaders or any memory error.
![Captura de tela 2020-12-10 123157](https://user-images.githubusercontent.com/46516229/101792796-e17d3b00-3ae3-11eb-9b1f-678f4df7e9e9.png)
![Captura de tela 2020-12-10 123227](https://user-images.githubusercontent.com/46516229/101792823-ea6e0c80-3ae3-11eb-93ef-a877e4e298f8.png)
[RPCS3.log](https://github.com/RPCS3/rpcs3/files/5673830/RPCS3.log)

**Comment by vanderleivieirainacio** [comment] 2020-12-12 15:10
The loading error disappeared but the problem of the screen going black after the logos continues and happens with all SPU modes, both interpreters (in quick mode sometimes) and recompilers (ASMJIT, LLVM).

**Comment by Huskatron** [comment] 2021-01-01 16:50
Can this get fixed already?

**Comment by AniLeo** [comment] 2021-01-01 16:51
Feel free to if you can reproduce, pull requests are open

**Comment by Huskatron** [comment] 2021-01-01 17:04
Spredsheet dev getting brave

**Comment by AniLeo** [comment] 2021-01-01 17:06
Imagine fixing less core/rsx regressions than spreadsheet dev

**Comment by Huskatron** [comment] 2021-01-01 17:06
Please can this not become an argument? I love getting involved in the emulation community and this is just sad. Let's code together!

**Comment by Yahfz** [comment] 2021-01-01 17:08
>starts an argument
>asks to not start an argument when he gets owned
???????????

**Comment by AniLeo** [comment] 2021-01-01 17:09
I am being serious, if no one else can reproduce how do you want this to get fixed, specially when there's no actual crash, only a deadlock. If there was a crash you could provide a stack trace and it could be possible to guess what's wrong from the code.

**Comment by Huskatron** [comment] 2021-01-01 17:10
You could inject a RAM tracker into it and then track when it locks and stop it

**Comment by AniLeo** [comment] 2021-01-01 17:11
coredump doesn't work with RPCS3 as is due to high amount of virtually reserved memory

**Comment by Huskatron** [comment] 2021-01-01 17:12
You don't need to use coredump, use a RAM tracker like IDA

**Comment by Huskatron** [comment] 2021-01-01 17:16
Thank you ^-^

**Comment by AniLeo** [comment] 2021-01-01 17:20
Seems easier to use gdb, don't see how IDA would be useful in this scenario, but any kind of captures would have to be done by someone who can reproduce this and you'd also have to find someone with IDA willing to debug them

But since this is a regression from 9161 I can guess it wouldn't help either way

**Comment by Huskatron** [comment] 2021-01-02 14:16
Please fix it I wanna play the game

**Comment by windwhirl94** [comment] 2021-01-02 15:21
> 
> 
> Please fix it I wanna play the game

For now, build 11107 is the last one that works OK with Unleashed, which I commented about [earlier](https://github.com/RPCS3/rpcs3/issues/9191#issuecomment-720181816) in the thread...

> 
> 
> Now, I went back and tested quite a few previous builds, starting from 11088, while using OP' settings. The error we are discussing here could be reproduced only with build 0.0.12.11117 and probably latter ones. Build 11107 (which was the one right before 11117) worked fine.
> 
> Log for 11117 attached.
> [RPCS3.log](https://github.com/RPCS3/rpcs3/files/5472170/RPCS3.log)
> 
> Build 11117 was born from #9161

 You may find that build in the [Builds History](https://rpcs3.net/compatibility?b)

**Comment by Huskatron** [comment] 2021-01-02 15:47
Hi u said 11107 but I can only see 9526 to 1175 so halp me pls

**Comment by windwhirl94** [comment] 2021-01-02 15:48
> 
> 
> Hi u said 11107 but I can only see 9526 to 1175 so halp me pls

Build number is on the right side.

**Comment by Huskatron** [comment] 2021-01-02 15:48
> 
> 
> > Hi u said 11107 but I can only see 9526 to 1175 so halp me pls
> 
> Build number is on the right side.

oh ty ^-^

**Comment by DavidPires** [comment] 2021-01-16 02:11
Steps to reproduce: 
-> delete the file patch_config.yml in the config folder
-> open RPCS3, go to Manage and then Game Patches 
-> go into Sonic Unleashed and browse the patch list like this (or else it won't work): 
![Capturar](https://user-images.githubusercontent.com/18236868/104794427-6f151000-579f-11eb-8ec6-6f0323fd68ec.PNG)
-> save and apply 
-> run the game and there will be a guaranteed crash after the logos. 

Solutions i found: 
1 - empty the file manually or add a patch
2 - go to Settings and in the Advanced tab enable the option Silence All Logs.

**Comment by windwhirl94** [comment] 2021-01-16 04:10
> 
> 
> Steps to reproduce:
> -> delete the file patch_config.yml in the config folder
> -> open RPCS3, go to Manage and then Game Patches
> -> go into Sonic Unleashed and browse the patch list like this (or else it won't work):
> ![Capturar](https://user-images.githubusercontent.com/18236868/104794427-6f151000-579f-11eb-8ec6-6f0323fd68ec.PNG)
> -> apply and then save
> -> run the game and there will be a guaranteed crash after the logos.
> 
> Solutions i found:
> 1 - empty the file manually or add a patch
> 2 - go to Settings and in the Advanced tab enable the option Silence All Logs.

Well, that works for me.

**Comment by JSKorbit** [comment] 2021-01-16 04:17
> 
> 
> Steps to reproduce:
> -> delete the file patch_config.yml in the config folder
> -> open RPCS3, go to Manage and then Game Patches
> -> go into Sonic Unleashed and browse the patch list like this (or else it won't work):
> ![Capturar](https://user-images.githubusercontent.com/18236868/104794427-6f151000-579f-11eb-8ec6-6f0323fd68ec.PNG)
> -> apply and then save
> -> run the game and there will be a guaranteed crash after the logos.
> 
> Solutions i found:
> 1 - empty the file manually or add a patch
> 2 - go to Settings and in the Advanced tab enable the option Silence All Logs.

Can confirm that Silence All Logs fixes this crash.

**Comment by vanderleivieirainacio** [comment] 2021-01-16 05:32
I tested here and actually scoring the Silence All Logs option causes the game to load and to play something but the game freezes and the emulator closes alone in certain parts when I'm playing and it happens in a few minutes of gameplay.

**Comment by Huskatron** [comment] 2021-01-16 20:29
> 
> 
> Steps to reproduce:
> -> delete the file patch_config.yml in the config folder
> -> open RPCS3, go to Manage and then Game Patches
> -> go into Sonic Unleashed and browse the patch list like this (or else it won't work):
> ![Capturar](https://user-images.githubusercontent.com/18236868/104794427-6f151000-579f-11eb-8ec6-6f0323fd68ec.PNG)
> -> apply and then save
> -> run the game and there will be a guaranteed crash after the logos.
> 
> Solutions i found:
> 1 - empty the file manually or add a patch
> 2 - go to Settings and in the Advanced tab enable the option Silence All Logs.

omg thanks so much bestie. that works!

**Comment by windwhirl94** [comment] 2021-06-18 02:59
It seems this issue was fixed by #9593 (I tested a few builds, it seems that 11568 was the last one to exhibit this problem, while 11569 no longer has it), at least on my end.

Also, if closing this issue, check #9481, which seems like a duplicate of this one.

**Closed** 2021-06-18 10:21 UTC
Labels: Regression
