### ISSUE TITLE
Illegal Instruction (SIGILL) when launch RPCS3

### ISSUE THREAD

**Issue by Sunderland93** [RPCS3/rpcs3#4187] opened 2018-02-18 08:21 UTC
RPCS3 version: master (commit 00b1ff752d918d2690b1b87e63072d16c55b2788)
Debian 9, KDE, Intel Xeon X3440, GTX 760 with Nvidia driver 378.111

When launch RPCS3 it failed with SIGILL signal:

```
`Starting program: /usr/bin/rpcs3 
[Thread debugging using libthread_db enabled]
Using host libthread_db library "/lib/x86_64-linux-gnu/libthread_db.so.1".

Program received signal SIGILL, Illegal instruction.
ppu_static_module::ppu_static_module (this=0x23de580 <ppu_module_manager::cellAdec>, name=0x1a7c026 "cellAdec")
    at ./rpcs3/Emu/Cell/PPUModule.cpp:72
72      ./rpcs3/Emu/Cell/PPUModule.cpp: Нет такого файла или каталога.`
```

**Comment by kd-11** [comment] 2018-02-18 08:51
Run under gdb and disassemble around the crashing instruction. Likely some instruction not supported by your Xeon. To disassemble, type `layout asm` into the gdb prompt. Ask around on the discord server if you need assistance.

**Comment by Sunderland93** [comment] 2018-02-18 09:07
@kd-11 Ok, but AppImage version run's well...

**Comment by kd-11** [comment] 2018-02-18 13:55
Appimage is only compiled with upto sse2. Makes sense that appimage doesn't crash. I think your xeon is reporting ssse3 support without actually supporting it. There is a command to check default arch options used when compiling, it usually includes all sse and ssse3 on modern cpus. That assembly layout should help determine which code is being executed without checking for support.

**Comment by Sunderland93** [comment] 2018-02-18 14:52
@kd-11 I build RPCS3 on Open Build Service, not on local machine with Xeon CPU.

**Comment by hcorion** [comment] 2018-02-19 00:09
ah

**Comment by kd-11** [comment] 2018-02-19 09:57
obviously the offline building is allowing optimizations not compatible with your pc. hcorion's PR has code to disable optimizing offline builds with newer instructions.

**Comment by Sunderland93** [comment] 2018-02-19 13:03
#4192 doesn't help

**Comment by kd-11** [comment] 2018-02-19 18:45
The native arch option defaults to ON. You must set it to OFF manually. `cmake -DUSE_NATIVE_INSTRUCTIONS=OFF ...`. Its set to on by default because most people will build on the target machine not a building service.

**Comment by kd-11** [comment] 2018-02-19 18:47
If that still doesn't work, provide the asm layout dump or if you're familiar with configuring cmake use CMAKE_CXX_FLAGS to use -msse2 for sse2 only support. Or just build on the target xeon to avoid all this trouble.

**Comment by hcorion** [comment] 2018-02-19 18:49
(or just use the AppImage)

**Comment by Sunderland93** [comment] 2018-02-19 20:58
@kd-11 how I can get layout asm dump?

**Comment by kd-11** [comment] 2018-02-28 07:43
I don't need the dump anymore since we already agreed the issue was caused by compiling on a different machine with different specs than yours. You have to configure GCC differently in that case - this is intentional and allows users compiling their own builds to enjoy the benefits of compiler optimizations. I'll close this as a non-issue (fixed by https://github.com/RPCS3/rpcs3/pull/4192); use the cmake configuration flag mentioned there `DUSE_NATIVE_INSTRUCTIONS=OFF` to disable compiler optimizations which should fix your problem.

**Closed by kd-11** 2018-02-28 07:43 UTC
