### ISSUE TITLE
Animation-tied-to-FPS issue in Tales of Graces f, possibly others

### ISSUE THREAD

**Issue by tonygiang** [RPCS3/rpcs3#6345] opened 2019-08-14 13:49 UTC
This is an issue that I spotted in [a mostly-unrelated merge request](https://github.com/RPCS3/rpcs3/issues/5243#issuecomment-475367338). You can follow the link to find what it was about, but the relevant part is quoted below:

> whats strange is tales of Graces F. it's battles are supposed to be 60FPS, but they run at 30FPS in RPCS3. however it uses AFPS in graces F battles, so if you double it to 60, rather then running smoother as intended, it runs at double speed instead. i've been told **Graces F battles being at 30 is a bug caused by rpcs3, but i don't know if anyone is looking into it**.
> 
> another example, is skits in graces F are 60AFPS, so you have to be at 60 when they start or they get out of sync, but running around (much like xillia) is 30AFPS, so you need to use this build that lets you swap fps with the L3 button because again, due to whatever bug, rpcs3 doesn't auto switch it's FPS when a skit happens, so it looks all out of sync between voices and mouth movements.

Emphasis was added by me. The most apparent effect of this issue is that when rpcs3 runs at 60fps, the combat animations in Tales of Graces f run faster than their real speed, whereas when rpcs3 runs at 30fps, the combat animations run slower than their real speed. There is no config to make Graces f run at a correct speed.

Like the quoted commenter, I don't know if anyone is looking into this bug either, so I'm creating this as a separate issue, to at least bring awareness to it.

**Comment by I-Dreu** [comment] 2019-08-15 15:37
Been hoping and waiting for this to gain traction. I appreciate you trying to put more of the spotlight on it.

I'll add to this by posting what a user on the rpcs3 forums seems to have recently discovered and posted in [Tales of Graces f's compatibility thread](https://forums.rpcs3.net/thread-187713-post-306032.html#pid306032):
```
So I found a quick fix for the FPS issues (latest RPCS3 version):
- Right click Graces F and Configure. Set your framelimit to 60. 
- Go to your RPCS3 folder config/custom_config and open your file.
- Find vblank Rate and set it around 35 to 40 (Actually, 30 is ideal but may be unstable).

Now my game has properly synced skits. the field and battles = 35-40 fps, and menus = 60 fps.
The only remaining issues are minor FPS dips and slightly sped up gameplay (Still much slower than default vblank Rate).
```

Wonder if there's more to this than meets the eye? (Whether it be negative or positive.)

**Comment by vsub** [comment] 2019-08-15 16:50
The fmvs don't seems to like it(they are running at lower speed even if it says that the game is running at 30/60 fps)but tweaking the "Clocks scale" also seems to help

I don't know what is the best value but just for a test I set it to 50 and I couldn't believe how properly at the same normal speed Asbel was running in the Orlen Woods without speeding up\slowing down even once

Clocks scale: 50
Frame limit: 60
Vblank Rate: 30(or 32)

Some race condition is probably the problem

**Comment by digitaldude555** [comment] 2020-02-26 15:42
Duplicate of #3020

**Closed** 2020-09-18 06:28 UTC
