### ISSUE TITLE
Audio: XAudio2Thread : AddData() failed(0x88960001)

### ISSUE THREAD

**Issue by zminhquanz** [RPCS3/rpcs3#1973] opened 2016-07-23 10:23 UTC
![image](https://cloud.githubusercontent.com/assets/11285640/17077398/01bd61a2-50fa-11e6-94ea-a0db9b1b7243.png)
![image](https://cloud.githubusercontent.com/assets/11285640/17077400/1822054c-50fa-11e6-993c-679295a2faf1.png)
E {Audio Thread} XAudio2Thread : AddData() failed(0x88960001)

**Comment by raven02** [comment] 2016-07-23 10:27
Occasionally i also hit this error 

E {Audio Thread} XAudio2Thread : AddData() failed(0x88960001)

**Comment by Nezarn** [comment] 2016-07-23 10:30
@raven02 same here. (but its quite random, most of the times it works fine.)

**Comment by raven02** [comment] 2016-07-23 10:31
@Nezarn . Agreed .It is quite random.

**Comment by raven02** [comment] 2016-07-23 10:33
@zminhquanz / @Nezarn . Are you both using windows 10 ?

**Comment by zminhquanz** [comment] 2016-07-23 10:34
yes , i'm using Windows 10

**Comment by zminhquanz** [comment] 2016-07-23 10:37
while i'm start emulation Project Diva F , run intro , it's occasionally hit this error , not run perfectly

**Comment by raven02** [comment] 2016-07-23 10:44
Can you try this and run mltiple times to see if it is still hitting this error .


[rpcs3.zip](https://github.com/RPCS3/rpcs3/files/379497/rpcs3.zip)

**Comment by Nezarn** [comment] 2016-07-23 10:53
@raven02 yep im using win10, with this build i can't reproduce the issue, (ran games over 10 times, didn't get the error) but wait for the other guy to report back

**Comment by raven02** [comment] 2016-07-23 11:12
Thanks I tried to load up the XAudio2_9.dll instead of 2.8

**Comment by Nekotekina** [comment] 2016-07-23 11:34
Did someone report to MS about 2.8? However it looks like purposeful sabotage to kill backward compatibility at max possible level.

**Comment by raven02** [comment] 2016-07-23 11:44
On one of the windows 10 system , it has 2.8 and 2.9 but no 2.7

XAudio2_8.dll   11k
XAudui2_9.dll   585k

**Comment by kd-11** [comment] 2016-07-23 11:55
Happens when the thread stalls for too long. You can trigger this if you pause the game using a debugger and then resume/step through code. Its still random but that seems to trigger this faster.

**Comment by Kristiqn5** [comment] 2016-07-23 12:45
I get this only if I set priority on rpcs3 to realtime

**Comment by zminhquanz** [comment] 2016-07-23 14:44
how do i to fix that ?

**Comment by zminhquanz** [comment] 2016-07-23 14:53
i try to run multiple time , but it's still hit this error

**Comment by raven02** [comment] 2016-07-25 00:39
I'll close it atm and open if we still need it.

**Comment by zminhquanz** [comment] 2016-07-25 05:16
![image](https://cloud.githubusercontent.com/assets/11285640/17091107/679bfba6-5261-11e6-831b-eed7074171b4.png)
Error what still there , try to using build 53b2e19d

**Comment by raven02** [comment] 2016-07-30 00:20
Somehow latest build is still encountering AddDatafailed() especially when using LLVM PPU . Can trigger 4 of 5 running.

**Comment by zminhquanz** [comment] 2016-07-31 02:21
I'm using this build 0578430 , i don't hear the sound when i'm play this game , but it's fixed XAudio2Thread : AddData() failed(0x88960001)

**Comment by zminhquanz** [comment] 2016-07-31 02:21
#2003

**Comment by raven02** [comment] 2016-07-31 03:30
Yes , somehow the intro movie playback stop the sound playback and thus no sound when reach title as well.

**Comment by raven02** [comment] 2016-07-31 03:42
i will close it and open another one specific for no sound in Project Diva F which the last working version is #1998

**Closed by raven02** 2016-07-31 03:42 UTC
Labels: audio
