### ISSUE TITLE
Missing texture in Dragon Ball z Burst Limit (Vulkan)

### ISSUE THREAD

**Issue by HawkSoft3** [RPCS3/rpcs3#3205] opened 2017-08-12 07:27 UTC
Hello developers keep doing this hard we really appreciate ur effort .
OK! Now their is an issue in Dragon Ball Z Burst limit game (BLUS30117-Dragon Ball Z Burst Limit) In the moutain area of the game texture are missing while using vulkan. Snapshot has been provided by me giving u the issue. Please fix this.
my specs:
**GTX 970
DDR4 16 GB 2133MHz RAM
Windows 10 64Bit
Intel Core i5 6600 3.3ghz (~3.9ghz)**
[RPCS3.txt](https://github.com/RPCS3/rpcs3/files/1219568/RPCS3.txt)

![capture](https://user-images.githubusercontent.com/26644945/29238911-d5be4764-7f5c-11e7-8c1e-8f05112aeb32.JPG)

**Comment by Quadronomic** [comment] 2017-08-12 12:22
I found this as an issue in other maps as well, just use OpenGl as gameplay feels smoother and there are no missing textures.

**Comment by Zangetsu38** [comment] 2017-08-12 12:25
use DX12, no have this issue

**Comment by HawkSoft3** [comment] 2017-08-12 14:22
hey! Zangetsu38 i know dx12 have no issue thats why i wrote only the vulkan and vulkan gives more improved frames than dx12 in the game dx12 - (37.86~42.35) | Vulkan (42.32~46.36)

**Comment by HawkSoft3** [comment] 2017-08-12 14:31
Hey! Quadronomic OpenGL Gives even worst performance (25-28)fps a total disaster than both of them

**Comment by Quadronomic** [comment] 2017-08-12 14:39
Opengl shows fewer frames but feels much smoother, in vulkan u can feel the lag.
Don't use d12 as it it's unstable and causes game crashes especially during story mode.

**Comment by HawkSoft3** [comment] 2017-08-12 14:43
Its because it is not able to achieve 30 fps let hope vulkan get a fix soon

**Comment by Quadronomic** [comment] 2017-08-12 14:53
That's weird I get constant 30 fps with i5 4670k

**Comment by raven02** [comment] 2017-08-13 14:33
Duplicate of https://github.com/RPCS3/rpcs3/issues/2759 . Closed

**Closed by raven02** 2017-08-13 14:33 UTC
