### ISSUE TITLE
Resistance: Fall of Man (BCUS98017) severe "error" flickering.

### ISSUE THREAD

**Issue by LaykaKiro** [RPCS3/rpcs3#12697] opened 2022-09-22 19:16 UTC
### Quick summary

Colored flashes of error-like geometry/shapes.

### Details

During certain missions or after playing for a moderate period of time, a lot of flickering occurs. I have no idea what the cause is as I have changed many different options and due to a lack of "live settings update" I have to restart segments, giving me less time to test things as I am a little impatient sometimes.
Note that the flickering happens really fast and causes problems with performance.
FLASHING LIGHT WARNING:
https://user-images.githubusercontent.com/34409251/191831557-30745e74-1d46-4d9d-bc40-85e3327b14c8.mp4

### Attach a log file

It literally won't let me upload one. I hate Github sometimes.

### System configuration

CPU: AMD Ryzen 5
GPU: NVIDIA GeForce RTX 3070
RAM: 32.0GB
AUDIO DEVICE: Many...
Patience: Low...

**Comment by kd-11** [comment] 2022-09-23 15:24
Try some older builds to verify if it is a regression of some kind.

**Comment by AniLeo** [comment] 2022-11-15 21:30
Closing due to missing information, no log file, no RSX capture, no build information or regression investigation of any kind

**Closed by AniLeo** 2022-11-15 21:30 UTC
Labels: Need Information
