### ISSUE TITLE
[Developer Request] Remove Direct X as a renderer

### ISSUE THREAD

**Issue by HexyFify** [RPCS3/rpcs3#5081] opened 2018-09-04 23:21 UTC
Direct X support has been dead for months and only adds confusion. Windows supports many graphics api's so there is no need to have a proprietary renderer on a operating system that supports frankly better api's for this project. Most Users of rpcs3 are on windows but it would a farce if they all used an proprietary API. Direct X is similar to vita support in rpcs3 since nobody cares about it and it only adds more time to compile. Vulkan and OpenGL are both on Linux and Windows with Mac support it would be only moltenVK
Direct X has no reason to exist for such a large project that is still in alpha phases.
This is my Opinion and I will respect your opinion if this discussion is civil, Thank You.

**Comment by AniLeo** [comment] 2018-09-04 23:28
No need to keep asking, it has already been decided it will be removed

Duplicate of #5000

**Closed** 2018-09-04 23:27 UTC
