### ISSUE TITLE
Unable to unlock the full version of  trial games with edats

### ISSUE THREAD

**Issue by benderscruffy** [RPCS3/rpcs3#7066] opened 2019-12-05 01:25 UTC
most games that use edats  are unable to unlock the full version
eg Rush'N Attack Ex-Patriot Demo [NPUB30112]
Time Machine: Rogue Pilot Demo [NPUB30474]
and before people start i know you can rename the edats to raps
but that is not the proper way

**Comment by Margen67** [comment] 2019-12-05 11:14
Duplicate of #3097.

**Comment by benderscruffy** [comment] 2019-12-05 14:35
yes but that one is closed  and  they have not reopened it

**Comment by blackstade** [comment] 2019-12-12 23:34
Just wrote an an post regarding these in the rpcs3 forum for NPUB30505 Castlevania, seems like sth wents complete wrong with these c00 (demo) games, to summ it up u can download these games for officialy for free, even without an ps3, since u get the downloadlinks for the pkg from the psn store. To unlock these games u need to buy them what gives u another pkg containing an edat, for these then an rap exists (for that u actually need a ps3).
in the example of Castlevania NPUB30505 these files would look like 
UP0101-NPUB30505_00-CASTHARMONYOFDES.pkg gamedemo
UP0101-NPUB30505_00-CVHDZDLCZUNLOCKZ.pkg pkg with just an edat to unlock the game
UP0101-NPUB30505_00-CVHDZDLCZUNLOCKZ.rap license belonging to unlock pkg.
The big problem now is, the game just checks if the rap file exists, it doesnt matter what is insidethe rap file, thats why the renaming thing of the edat works like in https://github.com/RPCS3/rpcs3/issues/3097 described. It even can be an empty stub, aslong the name is correct. 
So basicly we have alot of demo games which are legally obtainable by just signing up on the psnstore (no need for an ps3 and) are unlockable for free with 0 effort on the one side and on the other side all demos who try to decrypt some sprx or edat files at some point crashes. 

To summ this up at some point rpcs3 doesnt handle c00 games right.

Gonna link my forum post which describes this issue when its approved.

**Comment by Shoegzer** [comment] 2020-03-15 23:52
@blackstade I was not able replicate the issue with empty stub rap files, at least with the Zen Pinball 2 DLC "Balls Of Glory Pack" that I tested.  This DLC has the following files:

UP4042-NPUB30573_00-ZENPINBALL2FOX00_bg_1_6a00e89544d6c710c84320fac5d5b18e28f96735.pkg
(152MB file that I assume is the actual game package)

UP4042-NPUB30573_00-ZENPINBALL2FOX0K_bg_1_9d6987c2960b008bf881ed786e5d2911fefa5d81.pkg
(100K file that I assume is the unlock package)

I installed the game package first.  Then I installed the unlock package which installs two edat files (fox01.edat and license.edat) to the game directory.  However this causes Zen Pinball 2 itself to freeze before loading.  

According to rpcs3 logs, the game looks for a rap file called "UP4042-NPUB30573_00-ZENPINBALL2FOX0K.rap"  I created an empty stub rap file with that name and put it in exdata, but the game still freezes.  I believe it needs the actual rap file to stop freezing and go ingame again with the unlocked DLC unless I'm missing something?

**Comment by 13xforever** [comment] 2020-03-16 09:13
yes, you're missing your license for unlock dlc, which you should have if you follow the quickstart guide

**Comment by Shoegzer** [comment] 2020-03-16 16:34
@13xforever Thanks and you're certainly right, assuimng you're referring to the [guide's](https://rpcs3.net/quickstart) statement that you can get the rap license file through the rif and act.dat etc.  I realize that can be done, I was just testing the theory that any empty stub rap would work, and at least in this case it doesn't.

**Comment by piratesephiroth** [comment] 2020-11-11 06:59
> 
> 
> @blackstade I was not able replicate the issue with empty stub rap files

He stated that it's a quirk specific to c00 demos, not DLC.

**Comment by Shoegzer** [comment] 2021-09-26 21:36
May want to check this one against master which merged #10581 and close if possible.

**Comment by AniLeo** [comment] 2021-09-26 21:39
Yeah, this issue was solved, safe to close.

**Closed by AniLeo** 2021-09-26 21:39 UTC

**Comment by piratesephiroth** [comment] 2022-01-06 05:08
That pull request is locked so we can't reply anymore but the interesting part is that it's an innacurate implementation.
A real PS3 works as @blackstade wrote above: it doesn't require a .rap file for unlocking demos because it never reads the contents of the .edat, it only checks for its existence.
