### ISSUE TITLE
PPU decoder needs improvment for some games

### ISSUE THREAD

**Issue by Pouncha** [RPCS3/rpcs3#9715] opened 2021-02-04 11:54 UTC
I take motorstorm as example to explain
This game runs nice with PPU decoder recompiler (LLVM) but this setting making the main sprite flickering.
You must change the setting with PPU decoder as Interpreter (Fast) to avoid flickering glitches, but the game runs too slow (15FPS).
I tried with patches and differents setting changes (CPU,Zcull,SPU,etc...) nothing change : PPU decoder is the source of the bug.

Windows 10 with I9 9900KF,GTX 1080 last drivers and 32gb RAM.
[Motorstorm with PPU Decoder as Recompiler (LLVM) - Flickering Glitches but works at 30FPS.log.gz](https://github.com/RPCS3/rpcs3/files/5925510/Motorstorm.with.PPU.Decoder.as.Recompiler.LLVM.-.Flickering.Glitches.but.works.at.30FPS.log.gz)
[Motorstorm with PPU Decoder as Interpreter (Fast) - No Glitches but works too slows at 15FPS.log.gz](https://github.com/RPCS3/rpcs3/files/5925511/Motorstorm.with.PPU.Decoder.as.Interpreter.Fast.-.No.Glitches.but.works.too.slows.at.15FPS.log.gz)

**Comment by DefaltBR** [comment] 2021-02-04 12:07
TLoU (BCUS98174) also started flickering a week ago or so... Artifacts all over textures and objects when entering new areas even with all SPU/Shader cache compiled

**Comment by AniLeo** [comment] 2021-02-04 12:12
Duplicate of #5831

**Closed by AniLeo** 2021-02-04 12:12 UTC

**Comment by DefaltBR** [comment] 2021-02-04 12:16
In The Last of Us it was working fine before. Thing is: Artifacts started happening after some recent builds...

**Comment by Pouncha** [comment] 2021-02-04 13:05
@DefaltBR 
I didn't get any flickering glitches with my config (even with GPU patches enabled) since the RPCS3 lastest version.
The game works perfectly with just  some fps drops (I think coz of my graphic card).Only light doesn't work sometimes but works after restart.
Here's the The Last of Us log
[RPCS3.log.gz](https://github.com/RPCS3/rpcs3/files/5925849/RPCS3.log.gz)

**Comment by DefaltBR** [comment] 2021-02-04 13:28
> 
> 
> @DefaltBR
> I didn't get any flickering glitches with my config (even with GPU patches enabled) since the RPCS3 lastest version.
> The game works perfectly with just some fps drops (I think coz of my graphic card).Only light doesn't work sometimes but works after restart.
> Here's the The Last of Us log
> [RPCS3.log.gz](https://github.com/RPCS3/rpcs3/files/5925849/RPCS3.log.gz)

Yes, the game works fine... I have over 200h of playtime on RPCS3 for TLoU Lmao... But what began to happen in latest builds is: Everytime you load the game it'll cause a few flickering artifacts in textures, objects and/or landscape, including inventory HUD and then it goes away after a few seconds. It evetually happens later on but the more you play, the less it seems to happen (even with spu/shader cache built, so it's not because it is compiling anything)... And it wasn't there on older builds... I've cleared all caches to make sure.... I'm using every patches, right settings, same i was using before... Ryzen 5 5600X, RTX 2060 Super, 16gb 3200mhz.

Here's a log: 
[RPCS3.log.gz](https://github.com/RPCS3/rpcs3/files/5925965/RPCS3.log.gz)

**Comment by Pouncha** [comment] 2021-02-04 17:30
@DefaltBR
The glitches you mensioned are effectly caused by GPU light patch but this patch is needed.
The authors said that it's an incomplete patch and it can make issues.

**Comment by Pouncha** [comment] 2021-02-06 12:24
@DefaltBR 
Ok,To avoid glitches you mensioned, put WCB ON. It will make FPS drops but no more glitches
I tested it when you start at '20 years later chapter'.Close emulator and restart at the same chapter.Hadn't glitches with WCB ON.

**Comment by DefaltBR** [comment] 2021-02-06 12:41
@Pouncha You're right! WCB fixes it!
