### ISSUE TITLE
dialouge and some image blanked when open super robot war z3

### ISSUE THREAD

**Issue by nanase74** [RPCS3/rpcs3#3517] opened 2017-10-01 03:41 UTC
i have some problem when open super robot war z3 using rpcs3,the picture and dialouge will become this
[https://imgur.com/a/w0CHl](url)

and this is the serial no. of the game  BLJS10256

and this is my log file

[RPCS3.log.gz](https://github.com/RPCS3/rpcs3/files/1346903/RPCS3.log.gz)

i have tried 
white color buff
strict rdr mode
vulkan
openGL
load liblv2 only
auto load libraries

my cpu is I7-4771
GPU: GTX960
RAM:8G
OS:WIN7 64

**Comment by raven02** [comment] 2017-10-01 08:19
Duplicate of https://github.com/RPCS3/rpcs3/issues/3474 and this issue will be fixed shortly

**Closed by raven02** 2017-10-01 08:19 UTC

**Comment by Asinin3** [comment] 2017-10-01 08:33
@raven02 Beat me to it 👍
