### ISSUE TITLE
[Regression] Demon's Souls

### ISSUE THREAD

**Issue by BraveDave420** [RPCS3/rpcs3#14700] opened 2023-10-02 23:44 UTC
### Quick summary

Game was launching fine yesterday. I updated RPCS3 today and tried launching Demon's Souls. The game doesn't launch and hangs up on the "building SPU cache" screen and never finishes. 

### Details

Game is completely broken. Won't launch.

### Build with regression

Build 0.0.29-15665

### Attach two log files

[
[RPCS3.log](https://github.com/RPCS3/rpcs3/files/12787219/RPCS3.log)

### System configuration

Windows 11
CPU
AMD Ryzen 7 3700X 8-Core Processor
Graphics
AMD Radeon RX 5700 XT

### Other details

Game has been working but after today's update it won't launch. I also noticed that when I viewed the configuration settings a message box popped up telling me that some settings were no longer compatible and asked me if I wanted to auto remove them. After experiencing Demon's Souls not booting I tried that option but that did nothing.

**Comment by AniLeo** [comment] 2023-10-02 23:52
Wrong report, the flagged version is incorrect and has no issues, the broken version is 15667.

Closing as duplicate of #14699.

**Closed** 2023-10-02 23:53 UTC
