### ISSUE TITLE
Broken memory barriers with AA enabled (GoW 3 Demo)

### ISSUE THREAD

**Issue by AniLeo** [RPCS3/rpcs3#6156] opened 2019-07-02 14:28 UTC
**Tested with**
CPU: FX-8350 @ 4.62GHz
GPU: R9 280X 3GB
RAM: 8GB
OS: Windows 7 SP1
GPU Driver: 19.6.1

**Settings:**
Default with Write Color Buffers enabled
I also tested SPU ASMJIT vs SPU LLVM and VSync On vs VSync Off with no difference in results

**Menu screen flickers if AA is enabled. Does not happen if it's disabled.**

**Screenshot**
![image](https://user-images.githubusercontent.com/10283761/60519578-bc27b300-9cdb-11e9-8ec8-08a4474a1ffe.png)

**Video**
https://www.youtube.com/watch?v=DO8lEZ_Y5B4
_This video is not recorded on master but I have tested on current master (690cdff0d3f14a0375a193d3cee1f64a853d0b04) and the current commit of kd-11/optimizations and the issue still persists._

I am unable to take and reproduce a RSX Capture because it dies with 
```
F {RSX [0x100a25c4]} RSX: class std::runtime_error thrown: Assertion Failed! Vulkan API call failed with unrecoverable error: Out of video memory (VRAM) (VK_ERROR_OUT_OF_DEVICE_MEMORY)
(in file c:\projects\rpcs3\rpcs3\emu\rsx\vk\vkhelpers.h:274)
```
when attempting to replay it

I'm unable to test OpenGL right now because it's behaving in a weird way, I'll update the issue when I have more information

**Comment by AniLeo** [comment] 2019-07-10 20:01
Tested with 537d3f25487e025cb197fed15ebc64e74c7cf9a9 and newer AMD GPU Driver 19.7.1

Issue persists

**Comment by AniLeo** [comment] 2019-09-08 23:32
Still an issue on master and on @kd-11 dma branch

**Comment by dio-gh** [comment] 2019-09-09 00:12
The issue is specific to the Win7 AMD driver. I also noticed the same behaviour a month prior on my machine.

**Comment by AniLeo** [comment] 2019-09-09 01:22
I have the same results you had on OGL, but this issue doesn't happen with MSAA off, and only started being an issue after the commit removing memory barriers suggested by the AMD profiling tool

**Comment by AniLeo** [comment] 2019-09-09 15:40
Update

The OGL issue where it looks like it has WCB Off is not related to this, I tested with the previous build to #6112 and the issue already exists there.

**Comment by kd-11** [comment] 2020-01-01 19:48
Update/Note to self

This problem is caused by low performance and can be reproduced in all hardware configurations, likely data being overwritten before use?

**Comment by kd-11** [comment] 2020-01-29 13:50
Could not reproduce this issue anymore with latest builds even with performance hobbled down to almost single digits. Retest @AniLeo

**Comment by kd-11** [comment] 2020-01-29 13:59
Might have just been fixed in the newer drivers, I'm not sure. AMD has refined the vulkan driver a lot recently.

**Comment by AniLeo** [comment] 2020-01-29 15:29
I have no way of retesting this unfortunately

**Comment by kd-11** [comment] 2020-01-29 16:04
Closing as fixed then.

**Closed by kd-11** 2020-01-29 16:04 UTC
Labels: RSX, Render: Vulkan
