### ISSUE TITLE
The emulator crashes when exiting some races in Gran Turismo 5 prologue [NPUA80075]

### ISSUE THREAD

**Issue by PY3AN** [RPCS3/rpcs3#9568] opened 2021-01-08 16:43 UTC
The emulator crashes when exiting some races (5:50 on video). Perhaps there is a connection with the loss of sound during the race (#9567), if the sound has not disappeared, but the race is over, then the crash is not always observed.

https://youtu.be/9bX7_1O9g64

Sound_&_Exit_race_issue.log.gz

System configuration:

RPCS3 v0.0.14-11527
Firmware version: 4.86
OS Windows 10 20H2, 19042.685
CPU AMD Ryzen 5 3600
GPU AMD Radeon RX 580 8G
Memory Crucial Ballistix Sport 2x8G
Driver version 2.0.168

**Comment by Satan86** [comment] 2021-01-08 16:45
Yes, it freezes when exiting a race only if the audio cuts out. If it doesn't you can exit a race fine, so it's the same as #9567

**Comment by AniLeo** [comment] 2021-01-08 17:06
Duplicate of #9567

**Closed** 2021-01-08 17:06 UTC
Labels: Meta: Duplicate

**Comment by PY3AN** [comment] 2021-01-08 17:45
On the version of about a year ago, the emulator crashed after the race even if the sound remained (I cannot name a specific version, no evidence has saved either from that time), on the current version in 2 days I could not cause only the emulator to crash without mute the sound. I think you might be right and there is a connection between GT5 P, GT5 and GT 6.
