### ISSUE TITLE
Some problems on Madden 12 

### ISSUE THREAD

**Issue by MakiSalonga** [RPCS3/rpcs3#12968] opened 2022-11-20 17:13 UTC
### Quick summary

I managed to find a few things that irked me with Madden 12:
1. Whenever I try to edit a player, the screen freezes, yet I can still move up and down. 
2. There were some two lines on the screen throughout that I found weird, so I assume it's a kind of graphical error. 

### Attach a log file

[RPCS3.log](https://github.com/RPCS3/rpcs3/files/10050268/RPCS3.log)

### Attach capture files for visual issues

![2022-11-21 (2)](https://user-images.githubusercontent.com/60142215/202915694-3b65ab33-9f01-4c2b-bbd7-ed27c96b1672.png)
![2022-11-21 (3)](https://user-images.githubusercontent.com/60142215/202915699-c5f5e102-23a4-475a-9024-67ada4d633a6.png)

### System configuration

- SYS: RPCS3 v0.0.25-14385-b639f3c8 Alpha | master
- SYS: 11th Gen Intel(R) Core(TM) i5-1135G7 @ 2.40GHz | 8 Threads | 11.77 GiB RAM | TSC: 2.419GHz | AVX-512+ | FMA3
- SYS: Operating system: Windows, Major: 10, Minor: 0, Build: 19044, Service Pack: none, Compatibility mode: 0
- SYS: Current Time: 2022-11-21T01:11:44
- RSX: Found vulkan-compatible GPU: 'Intel(R) Iris(R) Xe Graphics' running on driver 0.402.247
- SYS: Firmware version: 4.89

**Comment by AniLeo** [comment] 2022-11-20 17:17
Intel GPUs / proprietary drivers are not officially supported

We need someone with AMD or NVIDIA to verify if these issues are GPU/driver specific or not

**Comment by MakiSalonga** [comment] 2022-11-20 17:20
So are there compatible NVIDIA Drivers I can use? I don't want to damage my laptop' s RAM if I get a new graphics driver.

**Comment by AniLeo** [comment] 2022-11-20 17:20
Do you have an NVIDIA GPU? The log file only shows an Intel GPU.

**Comment by MakiSalonga** [comment] 2022-11-20 17:21
No I don't. But I want to look for one.

**Comment by AniLeo** [comment] 2022-11-20 17:22
Then you obviously can't install drivers for a GPU you don't have.

Seeing as this is a low-end laptop CPU so you can't just pop in a new GPU, when you get a new PC with a dedicated GPU you can check that then.

**Comment by MakiSalonga** [comment] 2022-11-20 17:24
Alright. Thank you for the advice

**Comment by ChwaraeTeg** [comment] 2022-11-26 12:13
Tested on NVIDIA GeForce GTX 1060 6GB running on driver 517.48.0.0 and I get a load of black horizontal lines on menu screens when using Vulkan:
![Vulkan _ 0 0 25-14393 _ Madden NFL 12  BLUS30770](https://user-images.githubusercontent.com/104720038/204087952-53a21af4-c63c-4970-a37f-ce6d1c4ab1bc.png)

[RPCS3.log.gz](https://github.com/RPCS3/rpcs3/files/10096170/RPCS3.log.gz)
[BLUS30770_20221126114953_capture.rrc.gz](https://github.com/RPCS3/rpcs3/files/10096194/BLUS30770_20221126114953_capture.rrc.gz)

It looks OK in OpenGL:

![2022-11-26 11_47_19-FPS_ 60 00 _ OpenGL _ 0 0 25-14393 _ Madden NFL 12  BLUS30770](https://user-images.githubusercontent.com/104720038/204087982-fe76299b-b9a3-463c-aa4b-b9ff643335db.png)
[RPCS3.log.gz](https://github.com/RPCS3/rpcs3/files/10096171/RPCS3.log.gz)

Only seemed to affect menu screens for me - Intro video, loading screens and in-game didn't have the lines in either Vulkan or OpenGL

**Comment by ChwaraeTeg** [comment] 2022-11-27 13:13
Did some further testing using Intel, and similar to the NVIDIA issue, the black lines seem to be a regression between v0.0.21-13393 and v0.0.21-13399:

![0 0 21-13393 _ Madden NFL 12  BLUS30770](https://user-images.githubusercontent.com/104720038/204137058-a8b4bf52-08ca-4120-8a8b-2e6e64c03c90.png)

![0 0 21-13399 _ Madden NFL 12  BLUS30770](https://user-images.githubusercontent.com/104720038/204137060-45dcd7a0-e3d3-435e-a935-16b7b89acadd.png)

(Both screenshots from Intel(R) HD Graphics 520 running on driver 0.404.314)

**Comment by SnarkNark** [comment] 2022-12-03 13:10
> Tested on NVIDIA GeForce GTX 1060 6GB running on driver 517.48.0.0 and I get a load of black horizontal lines on menu screens when using Vulkan: ![Vulkan _ 0 0 25-14393 _ Madden NFL 12 BLUS30770](https://user-images.githubusercontent.com/104720038/204087952-53a21af4-c63c-4970-a37f-ce6d1c4ab1bc.png)
> 
> [RPCS3.log.gz](https://github.com/RPCS3/rpcs3/files/10096170/RPCS3.log.gz) [BLUS30770_20221126114953_capture.rrc.gz](https://github.com/RPCS3/rpcs3/files/10096194/BLUS30770_20221126114953_capture.rrc.gz)
> 
> It looks OK in OpenGL:
> 
> ![2022-11-26 11_47_19-FPS_ 60 00 _ OpenGL _ 0 0 25-14393 _ Madden NFL 12 BLUS30770](https://user-images.githubusercontent.com/104720038/204087982-fe76299b-b9a3-463c-aa4b-b9ff643335db.png) [RPCS3.log.gz](https://github.com/RPCS3/rpcs3/files/10096171/RPCS3.log.gz)
> 
> Only seemed to affect menu screens for me - Intro video, loading screens and in-game didn't have the lines in either Vulkan or OpenGL
> 
> EDIT: I see this issue on NVIDIA has already been reported - #12514
> 
> I also have a similar issue in the player editor - for me the game appears to freeze and stop responding to any button presses, however the music continues to play.

Regressing to v0.0.21-13393 doesn't seem to fix the player editor freezing either. I can hear button inputs and music continues to play, but the screen freezes.

**Comment by G4TEN** [comment] 2023-05-27 15:43
Any news on the player editor issue? Ive been having the same issue @AniLeo Getting the same issue with a Nividia card

**Comment by G4TEN** [comment] 2023-05-27 16:35
![DirectX Diagnostic Tool 5_27_2023 11_42_33 AM](https://github.com/RPCS3/rpcs3/assets/134795619/48336dc1-e86d-4912-9e60-e12d5f503507)

**Comment by VRVegas** [comment] 2023-05-28 16:05
yeah i need this fix, i need to edit a player to continue my franchise

**Comment by b1rds0nf1re** [comment] 2023-07-04 03:06
any news about a fix? It's something about madden nfl 11 and madden nfl 12 they both have the same issue. I can't get through a game in either without freezing even though I hear the game still working in the background. I'm guessing they have the same if not a similar fix since I'm pretty sure it's the same cause. now what that cause is I have no damn clue.

**Comment by Jkicksme** [comment] 2023-10-30 02:31
How can we contact those who run rpcs3 to check on this issue? I can edit any of create team uniforms or players without it freezing ?

**Comment by Jkicksme** [comment] 2023-10-30 02:31
I cant*

**Comment by Jkicksme** [comment] 2023-10-30 02:32
This needs to get fixed please

**Comment by ChwaraeTeg** [comment] 2023-11-05 15:10
The graphics issue was fixed in PR #14131.  There is a standalone issue open for the player edit crash at #14778 so I'd suggest closing this combined one.

**Closed** 2023-11-05 15:29 UTC
Labels: Driver: Intel
