### ISSUE TITLE
7736 4 of 4 tested games now freezing with std::runtime_error thrown: Unregistered PPU function very often (menu/intro), at least on TSX CPU

### ISSUE THREAD

**Issue by ruthan** [RPCS3/rpcs3#5575] opened 2019-01-19 12:10 UTC
I just tried few games on 7736 on not TSX CPU and all 4 of 4 tested games froze on same error in menu, intro (Oblivion,Skyrim, Wet, Farming Simulator) - F {PPU[0x1000003] Thread (Miles Thread) [0x010055e4]} class std::runtime_error thrown: Unregistered PPU function.

Win10 1809, Nvidia G970 last driver.
  
  Here is log: 
[RPCS3.zip](https://github.com/RPCS3/rpcs3/files/2775502/RPCS3.zip)

  I sure that these games in the past worked better.

**Comment by elad335** [comment] 2019-01-19 12:11
duplicate of #2909

**Closed** 2019-01-19 12:17 UTC

**Comment by ruthan** [comment] 2019-01-19 15:41
Maybe its duplicated but now this error is much more often..
