### ISSUE TITLE
Ninja gaiden 3:RAZOR's EDGE crashes after "TECMO" logo !

### ISSUE THREAD

**Issue by arcadee1977** [RPCS3/rpcs3#6231] opened 2019-07-19 13:46 UTC
Ninja gaiden 3:RAZOR'S EDGE [NPUB31184] crashes after "TECMO" logo , game is freezing with black screen, Or  can enter the game occasionally, but still crashes before the gameplay . the logs is following :

F {PPU[0x1000000] Thread (main_thread) [0x0304c3c0]} MEM: Access violation reading location 0x38
F {PPU[0x100002c] Thread (_libsail-control) [0x030580a8]} MEM: Access violation writing location 0x0

OS: win10 1803
CPU:8700k
16g ram
1070TI

![未标题-1](https://user-images.githubusercontent.com/47111657/61539693-a0a80080-aa6e-11e9-9ba5-72650708ff83.jpg)

![未标题-2](https://user-images.githubusercontent.com/47111657/61539906-1613d100-aa6f-11e9-8ed0-e7aa38fbc47f.jpg)

[RPCS3.zip](https://github.com/RPCS3/rpcs3/files/3411322/RPCS3.zip)

**Comment by Whatcookie** [comment] 2019-07-19 14:51
As far as I can tell, this seems to be a race condition relating to RSX performance. I can no longer reproduce this crash in linux, but it still occurs under windows about 40% of the time for me. 

Anyways, I see that you mentioned that https://github.com/RPCS3/rpcs3/pull/6228 would be likely to fix transparency in this game. Sadly I can report that it's still an issue after it's been merged.

**Comment by arcadee1977** [comment] 2019-07-19 15:54
> As far as I can tell, this seems to be a race condition relating to RSX performance. I can no longer reproduce this crash in linux, but it still occurs under windows about 40% of the time for me.
> Anyways, I see that you mentioned that #6228 would be likely to fix transparency in this game. Sadly I can report that it's still an issue after it's been merged.

I have set rpcs3.exe to WIN7 Compatibility Mode + Active GPU-> Disable async shader compiler , Ninja gaiden 3 get playable on WIN10. But I guessed wrong , the fog's transparency still not fixed :(

**Comment by pitkevich80** [comment] 2019-11-23 18:30
Yeah, crash after logo Tecmo (( 
[RPCS3.zip](https://github.com/RPCS3/rpcs3/files/3882802/RPCS3.zip)

**Comment by TheClicheDetective** [comment] 2020-01-16 04:57
For me if I do manage to get past the loading screen then I suffer extreme lag from the broken particle effects that risk crashing the game. the particles are 2-D instead of 3-D for some odd reason as well as oversized and they follow me which results in me playing blindly most of the time. I don't know anything about coding or programming so that's the best I can explain it.

**Comment by islandking2000** [comment] 2020-03-10 05:02
v0.0.9-9878 Alpha
BLUS31175
Black screen after Tecmo logo
[RPCS3.log.gz](https://github.com/RPCS3/rpcs3/files/4310347/RPCS3.log.gz)

**Comment by arcadee1977** [comment] 2020-06-08 15:19
As long as this game plays CG video, it may be crash before playing the video. Not only the beginning, but also the cutscenes video of any chapter may be crash in a moment before playing it. I have passed the game. If  encounter crash, you will enter the game again. If  try several times more, you will encounter a time that it don't crash (usually two or three times). In addition, it is better to directly press Select to skip the last cutscenes video, so as to avoid crash .

All crashes are the same error log:
**F {PPU[0x1000000] Thread (main_thread) [0x0324c3c0]} VM: Access violation reading location 0x38 (unmapped memory)**

**Comment by MegaBlast98** [comment] 2020-07-03 17:12
Getting the same error about 80% of the time I launch the game.. And even then when I get through the first chapter opening cutscene usually crashes with the same access violation.

Shame because when I do manage to get into gameplay it works fantastic. Cemu still has transparency issues while the recent RPCS3 builds have no major rendering issues as far as I could tell from Ch1.

Not sure if this helps at all so I'll just post 2 logs but about 50% the log shows the Access violation and the other half it just crashes without it at the exact same place (After Tecmo logo).

Access violation
[RPCS3.log.gz](https://github.com/RPCS3/rpcs3/files/4870734/RPCS3.log.gz)

Crash missing error lines.
[RPCS3.log.gz](https://github.com/RPCS3/rpcs3/files/4870760/RPCS3.log.gz)

**Comment by nitroos-ai** [comment] 2022-05-11 19:43
I tried the demo under linux and it didn't crash.

**Comment by Megamouse** [comment] 2022-05-12 18:35
cannot reproduce

**Closed by Megamouse** 2022-05-12 18:35 UTC
