### ISSUE TITLE
Problem on 1st and 2nd start of the game "Super Robot Wars OG: The Moon Dwellers"

### ISSUE THREAD

**Issue by Wizzy2018** [RPCS3/rpcs3#5263] opened 2018-10-18 11:30 UTC
Hi guys 
I using RPCS3 0.0.5-7439-4ab777b4 Alpha
Problem is starting when i start Super Robot Wars OG: The Moon Dwellers (BLJS10335) 2nd time.
On 1st start of the game you have a screen where it says HDD and press X after that a game starts and sometimes freezes on start game screen but when i start a game 2nd time than a hell starts :( 
On 2nd start of game the game stops at first screen where it need to load a HDD but there is now nothing showing only errors like this one.

E {rsx::thread} RSX: NV3089_IMAGE_IN_SIZE: Invalid blit dimensions passed
U {PPU[0x1000000] Thread (main_thread) [0x00335fe4]} cellSysutil TODO: cellVideoOutConfigure(videoOut=0, config=*0xd0020660, option=*0x0, waitForEvent=0)
E {PPU[0x1000005] Thread (GameThread) [0x00ad4428]} 'sys_mutex_lock' failed with 0x80010008 : CELL_EDEADLK [1]
E {PPU[0x1000005] Thread (GameThread) [0x00ad503c]} 'sys_mutex_unlock' failed with 0x80010009 : CELL_EPERM [1]
U {PPU[0x1000005] Thread (GameThread) [0x01197d80]} sys_spu TODO: Unimplemented SPU Thread options (0x2)
U {PPU[0x1000005] Thread (GameThread) [0x0110ff0c]} sys_prx TODO: _sys_prx_get_module_id_by_name(name=“cellLibprof”, flags=0, pOpt=*0x0)
E {PPU[0x1000005] Thread (GameThread) [0x0110ff0c]} '_sys_prx_get_module_id_by_name' failed with 0x8001112e : CELL_PRX_ERROR_UNKNOWN_MODULE [1]
E {PPU[0x1000005] Thread (GameThread) [0x011054ec]} '_sys_lwmutex_lock' failed with 0x80010005 : CELL_ESRCH [1]
E {PPU[0x1000005] Thread (GameThread) [0x011054ec]} '_sys_lwmutex_lock' failed with 0x80010005 : CELL_ESRCH [2]
E {PPU[0x1000005] Thread (GameThread) [0x011054ec]} '_sys_lwmutex_lock' failed with 0x80010005 : CELL_ESRCH [3]
S {Audio Thread} XAudio 2.9 initialized
E {PPU[0x1000006] Thread (fios mediathread 2) [0x011d2090]} 'sys_fs_open' failed with 0x80010006 : CELL_ENOENT, “/dev_bdvd/PS3_GAME/USRDIR/Dat/Window/WindowToolData/Texture/otehon_waku_01.dds” [1]
E {PPU[0x1000006] Thread (fios mediathread 2) [0x011d2000]} 'sys_fs_opendir' failed with 0x80010006 : CELL_ENOENT, “/dev_bdvd/PS3_GAME/USRDIR/Dat/Map/Seqence/SeqUnit” [1]

My system specs:
CPU Intel I5-4590
8GB DDR3 Ram
GPU RX470 4GB

Here are a screenshots on 2nd start of the game
![screenshot 1](https://user-images.githubusercontent.com/44261686/47150984-b66a7880-d2d8-11e8-9c49-82c37c98872a.png)
 
![screenshot 3](https://user-images.githubusercontent.com/44261686/47151030-d437dd80-d2d8-11e8-9813-05c733c8d2c9.png)

And here is what happens on 1st start of the game when game frezzes
Here are a screenshots and log

![screenshot 5](https://user-images.githubusercontent.com/44261686/47151278-96878480-d2d9-11e8-8f77-ccc09b9dcd8a.png)

![screenshot 6](https://user-images.githubusercontent.com/44261686/47151326-b323bc80-d2d9-11e8-9756-7cd2e2a9daee.png)

Log file here

[RPCS3.log](https://github.com/RPCS3/rpcs3/files/2491643/RPCS3.log)
[RPCS3.log.gz](https://github.com/RPCS3/rpcs3/files/2491644/RPCS3.log.gz)

**Comment by tarkungZ** [comment] 2019-06-18 18:23
I have the same problem when star the game 2nd time.

This problem include all SRW series.

**Comment by Wizzy2018** [comment] 2019-06-18 18:29
I gived up from emulator.I had this semaphore fucking error in every game
so i decided fuck it i try it in future like in 2030 when it works 😁

**Comment by tarkungZ** [comment] 2019-06-18 19:13
I just found something useful, you have to re-install game data to internal HDD or "dev_hdd0/game" folder every time when you launch the game after you close emulator.

You just have to delete a game data folder (BLJS10335) from "dev_hdd0/game" so you can install game data again.

I hope dev read and fix this.

**Comment by Megamouse** [comment] 2020-07-12 12:02
This looks like a duplicate of #2532

**Closed by Megamouse** 2020-07-12 12:02 UTC
