### ISSUE TITLE
MotorStorm: Pacific Rift online lobbies break with more than 9 players

### ISSUE THREAD

**Issue by Silense03** [RPCS3/rpcs3#13312] opened 2023-01-28 20:41 UTC
### Quick summary

When in an online lobby on MotorStorm: Pacific Rift, RPCS3 players can't play in lobbies when there are more than 9 players in it.

### Details

When trying to play a game when the lobby has ≥ 10 players in it, the game never starts for anyone since RPCS3 players never get to the "Select Vehicle" screen. The game only starts when either people leave so the players are 9 or less, or if the people on RPCS3 leave. 

### Attach a log file

The log files don't show anything concerning the issue.

**Comment by Megamouse** [comment] 2023-01-28 20:43
missing log file

**Comment by Megamouse** [comment] 2023-01-28 20:44
duplicate of #13126

**Closed by Megamouse** 2023-01-28 20:44 UTC
Labels: Network
