### ISSUE TITLE
Never Ending Save Screen - After Burner Climax Europe

### ISSUE THREAD

**Issue by OperatorUmbra** [RPCS3/rpcs3#6530] opened 2019-09-11 06:04 UTC
When a game is ended or Ex-Options are exited the following apperes: Savein content. Please don't turn your Playstation 3 system.   The screen doesn't go away. RPCS3 Version: 0.07-8689-c1b0934f Alpha

**Comment by Megamouse** [comment] 2019-09-11 07:08
Duplicate of #6508

**Closed by Megamouse** 2019-09-11 07:08 UTC
