### ISSUE TITLE
Random Freeze on Another Century's Episode R and Mobile Suit Gundam UC

### ISSUE THREAD

**Issue by 4XPG** [RPCS3/rpcs3#10176] opened 2021-04-22 14:43 UTC
## Quick summary
Identical issue to #10175 and once again both games share identical game engine. Both games runs almost flawlessly at first, but after several days the stutter becomes more and more noticeable to the point the screen is filled with flickering and jerky camera movement, which usually ends with emulator softlock shortly afterwards.

Both games are tested on v0.0.15, v0.0.14 and v0.07 all of which nets the same outcome but I'm providing the logs with RPCS3 v0.0.15-12141-61450335.

## Details

1. Open RPCS3
2. Launch game
3. If the game boots at 60 FPS, it'll run consistently at 40-60 FPS until you close the emulator
4. Quit RPCS3 and/or wait for several days, then start the game again. When the symptoms like jerky camera movement or broken speed lines effect is visible, chances the emulator may freeze afterwards.
5. On Gundam UC the symptom is accompanied with extreme screen flicker when locking on an enemy. On Another Century Episode R it's accompanied with severe performance drop despite performance overlay's FPS readout is at constant 60.

#### 1. Please attach RPCS3's log.
Another Century's Episode R
[RPCS3.log (2).gz](https://github.com/RPCS3/rpcs3/files/6359178/RPCS3.log.2.gz)

Gundam UC
[RPCS3.log.gz](https://github.com/RPCS3/rpcs3/files/6359141/RPCS3.log.gz)

#### 3. Please attach screenshots of your problem.
Another Century's Episode R
https://streamable.com/fa171i

Gundam UC
![Untitled3](https://user-images.githubusercontent.com/4043537/115734076-a0f7cd00-a3b3-11eb-9d7b-a759eec445f1.png)

Performance overlay when the game freezes
![Untitled4](https://user-images.githubusercontent.com/4043537/115734162-b0771600-a3b3-11eb-947c-3a17594b0dda.png)

#### 5. Please provide your system configuration:
OS: Windows 10 build 19042.685
CPU: Ryzen 5 3600 @ 3.6GHz
GPU: Nvidia Geforce RTX3070
Memory: 16GB
Driver version: 465.89

**Comment by Megamouse** [comment] 2021-04-23 21:27
duplicate of #10175

**Closed by Megamouse** 2021-04-23 21:27 UTC
