### ISSUE TITLE
Downloading patches/compat database results in error

### ISSUE THREAD

**Issue by ildiem** [RPCS3/rpcs3#15965] opened 2024-08-18 19:39 UTC
### Quick summary

When I try to download patches or the compatibility database, I get an error in the log that reads:
`E NET: curl_easy_perform(): Curl error (77): Problem with the SSL CA cert (path? access rights?)
Details: error setting certificate verify locations: CAfile: none CApath: none`

### Attach a log file

[RPCS3.log](https://github.com/user-attachments/files/16651465/RPCS3.log)

### System configuration

macOS 14.6.1, Apple M1 Max, RPCS3 0.0.32-16843-fbcd8e32

**Comment by Megamouse** [comment] 2024-08-18 19:42
Duplicate of #15891

**Closed by Megamouse** 2024-08-18 19:42 UTC
