### ISSUE TITLE
The latest beta is asking to install the games again and games icons dissapear after I run a game

### ISSUE THREAD

**Issue by vsub** [RPCS3/rpcs3#4852] opened 2018-07-06 15:49 UTC
1.Even if I set all of the paths manually in the Virtual File System,when I run any game that requires instalation,it will ask to install it again
2.When I run a game,the gamelist is reloaded and it displays only games that I have run at least once on this version
If I close the game window and choose after that View=>Game List Refresh then the other games also appear that I did not run yet

rpcs3-v0.0.5-7069
I am settings the paths because I want to try the version before deleting the old one(rpcs3-v0.0.5-7005)which at least for now is working fine.

**Comment by AniLeo** [comment] 2019-04-02 03:14
Probably caused by cache system updates back then, closing since it's very old and likely is not happening on master, if you can reproduce this somehow with updating recent builds please open a new issue

**Closed by AniLeo** 2019-04-02 03:14 UTC
