### ISSUE TITLE
Performance issue after update RPCS3 - God of War Collection [BCUS98229]

### ISSUE THREAD

**Issue by cwirek91** [RPCS3/rpcs3#4515] opened 2018-05-03 21:24 UTC
Hi,

last time I've updated RPCS3 emulator from v0.0.5-6652 to v0.0.5-6694. I've run God of War Collection and I've got ~40 FPS. In earlier version I had ~130 FPS. I've tested few versions of emulator on default settings and here are my conclusions:

RPCS3 v0.0.5-6652 ~130 FPS
RPCS3 v0.0.5-6663 ~130 FPS
RPCS3 v0.0.5-6675 ~130 FPS
RPCS3 v0.0.5-6692 ~40 FPS
RPCS3 v0.0.5-6693 ~40 FPS
RPCS3 v0.0.5-6694 ~40 FPS

forum: https://forums.rpcs3.net/thread-198685.html

here screenshots:
https://images84.fotosik.pl/1060/968a5cc5dd22756b.png
https://images81.fotosik.pl/1061/78d4f824507eab5d.png
https://images82.fotosik.pl/1061/74ab7b162d928a01.png

My specification:
Intel i5-6500
Nvidia GTX 1060 6GB
DDR4 16 GB RAM

It looks like changes in Pull request: #4469 have negative effects for performance in God Of War Collection (or maybe for every game?).
Could you investigate this issue?

**Comment by TigiHof** [comment] 2018-05-03 21:25
I already reported this issue, see https://github.com/RPCS3/rpcs3/issues/4506

**Comment by cwirek91** [comment] 2018-05-03 21:35
Thx for the info, I currently play on the latest 'good' version - 0.0.5-6675

**Comment by AniLeo** [comment] 2018-05-03 22:02
Please comment on the existing issue

Closing as duplicate of #4506

**Closed by AniLeo** 2018-05-03 22:02 UTC
