### ISSUE TITLE
TLOU sound desync in some areas

### ISSUE THREAD

**Issue by Pouncha** [RPCS3/rpcs3#10021] opened 2021-03-26 11:43 UTC
I've got sound desync in cinematic Bidonville"s area.But it's only when ennemy talk
The black guy's dialog script is running as the same time of Tess's dialog.That's makes a 'mixed' dialog' .
I use TLOU BCES01584 in french version,running on Windows 10 with Nvidia GTX 1080 lastest's drivers on a I9 9900KF.
I tried to change vsync,fps limit,shaders async,sound drivers,...nothing change.
If someone can help...
[RPCS3.log.gz](https://github.com/RPCS3/rpcs3/files/6211517/RPCS3.log.gz)

**Comment by 13xforever** [comment] 2021-03-26 11:58
Duplicate of #9788. Petition to ban due to repeated low quality submissions.

**Closed** 2021-03-26 11:58 UTC
Labels: Meta: Duplicate

**Comment by Pouncha** [comment] 2021-03-26 17:59
#9788 has been deleted,so I thought it was fixed,but no.That's why I put new issue about it.
And you wanna ban me for that ?
