### ISSUE TITLE
Alice Madness Returns[BLUS30607] - glitches+corrupted sound

### ISSUE THREAD

**Issue by Parthorisian** [RPCS3/rpcs3#4948] opened 2018-07-31 14:07 UTC
glitches **[streamable](https://streamable.com/skmmi)** before going to menu since bld7130 (PR4300) log
[glitchesAlice_RPCS3.zip](https://github.com/RPCS3/rpcs3/files/2245559/glitchesAlice_RPCS3.zip)

**Comment by Megamouse** [comment] 2018-07-31 17:00
Yes. They might rip your ears out if you dont turn the volume down

**Comment by desperateCoder** [comment] 2019-11-18 17:52
I guess this game is still unplayable, right?

**Comment by digitaldude555** [comment] 2021-01-28 13:03
Still an issue.

**Comment by Megamouse** [comment] 2022-04-03 10:38
@digitaldude555 please re-test

**Comment by Jonathan44062** [comment] 2022-04-03 17:45
Still an issue (Using the settings from the wiki does not fix the problem), link to the video https://www.youtube.com/watch?v=b4IUGTSNA1M
Log file from the forum
https://forums.rpcs3.net/thread-196564-post-318145.html#pid318145

**Comment by Jonathan44062** [comment] 2022-04-13 06:37
Tested the PR #11754 , no changes with the Spicy horse and UE3 logo intro, still happen, log file just in case
[RPCS3.log.gz](https://github.com/RPCS3/rpcs3/files/8478748/RPCS3.log.gz)

**Comment by digitaldude555** [comment] 2022-05-12 14:05
Retest @Jonathan44062

**Comment by Jonathan44062** [comment] 2022-05-12 17:24
Still an issue, I thougt it was fixed for the first boot, but, I was re-booting the game a few times to confirm
![image](https://user-images.githubusercontent.com/78843189/168133057-c22141d8-7c15-4b1d-987f-46dfb34bd503.png)

**Comment by Megamouse** [comment] 2022-05-13 05:50
this does not seem to be caused by vdec as lle doesn't fix it

**Comment by Jonathan44062** [comment] 2023-07-06 19:39
Closing as fixed 
![image](https://github.com/RPCS3/rpcs3/assets/78843189/94be7e76-518b-406d-af8c-67f4a3ca2a4c)

**Closed** 2023-08-21 14:31 UTC
