### ISSUE TITLE
Giana Sisters: Twisted Dreams bad graphics at 720p (480p works fine)

### ISSUE THREAD

**Issue by benderscruffy** [RPCS3/rpcs3#6752] opened 2019-10-12 07:00 UTC
using Vulkan and 1280x720 graphics keep flashing and are missing most of the time
but using 720x480 the graphics are fine
![giana](https://user-images.githubusercontent.com/2696404/66696734-05d36100-ed01-11e9-8ebe-71bb32ca8461.PNG)
[RPCS3.log.gz](https://github.com/RPCS3/rpcs3/files/3720287/RPCS3.log.gz)
[NPUB31272_20191012150256_capture.zip](https://github.com/RPCS3/rpcs3/files/3720292/NPUB31272_20191012150256_capture.zip)

doesnt happen on opengl

**Comment by digitaldude555** [comment] 2020-02-26 16:59
if you have wcb + cpu blit the flashing changes not sure if significant info anyway still an issue on that resolution. [wcb + cpu blit](https://streamable.com/a49x0) [default](https://streamable.com/n0s3k)

**Comment by Asinin3** [comment] 2021-09-15 13:25
Still an issue?

**Comment by benderscruffy** [comment] 2021-10-02 03:23
yes
still an issue

**Comment by nitroos-ai** [comment] 2021-10-17 16:07
With GPU:"Shader Interpreter Only" it doesn't flash at all but has missing graphics.

**Comment by nitroos-ai** [comment] 2022-01-21 03:06
it seems to be fixed.

**Comment by Asinin3** [comment] 2022-01-21 06:06
Fixed with async or just when set to interpreter only?

**Comment by Megamouse** [comment] 2023-02-01 19:17
I can't reproduce this. please test again

**Closed** 2023-02-12 00:00 UTC
Labels: Bug
