### ISSUE TITLE
how to fix fear2 gun is transparent

### ISSUE THREAD

**Issue by tee4341** [RPCS3/rpcs3#11678] opened 2022-03-19 23:44 UTC
how to fix fear2 gun is transparent
[[BLUS30251] F.E.A.R. 2: Project Origin]
![fear2 hi](https://user-images.githubusercontent.com/48321898/159142119-372bdde0-de52-4e3a-8b22-c7cbc19f8c0e.gif)
[RPCS3.log.gz](https://github.com/RPCS3/rpcs3/files/8310313/RPCS3.log.gz)

**Comment by RainbowCookie32** [comment] 2022-03-20 01:21
Playable report on the forums says to enable Write color buffers. Regardless, support is provided on Discord and Forums, not here.

**Comment by tee4341** [comment] 2022-03-21 19:15
> Playable report on the forums says to enable Write color buffers. Regardless, support is provided on Discord and Forums, not here.

After turn on Write Depth Buffers is not working
![screenshot 1](https://user-images.githubusercontent.com/48321898/159347317-6101cb3a-d968-4883-a6d4-8f3d0d21a9a1.jpg)
![fear2 hi2](https://user-images.githubusercontent.com/48321898/159347366-8d3d1c9d-a4f5-4af9-926f-2a099b56a1fb.gif)

**Comment by Jonathan44062** [comment] 2022-03-21 19:52
Try using Read Depth Buffers and Read Color Buffers (Advanced tab of the settings), see which one works

**Comment by tee4341** [comment] 2022-03-21 22:39
> Try using Read Depth Buffers and Read Color Buffers (Advanced tab of the settings), see which one works

still not workin
![screenshot 3](https://user-images.githubusercontent.com/48321898/159374570-21c14ddc-ded2-4104-9792-ef818f5e340e.jpg)
![screenshot 4](https://user-images.githubusercontent.com/48321898/159374592-4355dcd4-8725-49b1-b10e-4bbf6c2de985.jpg)
g

**Comment by Xcedf** [comment] 2022-03-22 14:08
This is an ancient issue, still actual for Condemned/FEAR games, there's no settings to fix that stuff.
But there's a hacky way exists, in file graphics_pipeline_state.hpp you can disable depth bias
![3](https://user-images.githubusercontent.com/7060586/159500272-c7582ab5-b61c-4666-b25b-963167ef8244.jpg)
here's the result:
Before:
![1](https://user-images.githubusercontent.com/7060586/159500506-d041cd5d-97ff-4f19-9a08-b4ae2b944e71.jpg)
After:
![2](https://user-images.githubusercontent.com/7060586/159500575-ea8ef71b-8af0-4083-ac9d-92bdaf25e1f5.jpg)

**Comment by kd-11** [comment] 2022-03-27 16:51
Why is there no RSX capture provided here? It's not possible to analyze without one.

**Comment by tee4341** [comment] 2022-03-28 06:08
> Why is there no RSX capture provided here? It's not possible to analyze without one.

Sorry
[BLUS30251_20220328130313_capture.zip](https://github.com/RPCS3/rpcs3/files/8360028/BLUS30251_20220328130313_capture.zip)

**Comment by Asinin3** [comment] 2022-05-08 12:17
Confirmed fixed by using high precision z-buffer on debug settings. Same issue is in F.E.A.R 1 btw. Also seems to be Nvidia specific as it isn't present on kd-11's AMD GPU.

**Comment by kd-11** [comment] 2022-09-26 23:26
I have an idea how to fix this for nvidia.

**Closed** 2022-10-11 11:00 UTC
Labels: Bug, Driver: NVIDIA
