### ISSUE TITLE
Lighting regression in NCAA14 Build 11336

### ISSUE THREAD

**Issue by huskereurocat** [RPCS3/rpcs3#9359] opened 2020-12-01 13:57 UTC
I was using a 3 month old build and updated to the newest build this morning. The lighting is now affected. If we view the plays from far away as pictured, we have proper lighting. If we zoom in, or on close up replays, the lighting goes away and it is as if there is no sun out or the player is in the shade. And no, the player is not in the shade.

I updated to build 11336 this morning on 12-1-20. This seems to be an issue caused by pull request [https://github.com/RPCS3/rpcs3/pull/8769]

Ok, in doing a little testing I found that 10781 was the last build that had working lighting, but the micro stutter was still present. Starting with 10790 through 10807 froze NCAA 14 at the selection screen just before going into game play. Beyond that all builds have the lighting issue as described above but actual game play is possible.

Here is the log for build 10781. The last build with working lighting. And it has the micro stuttering video as well.
https://github.com/RPCS3/rpcs3/files/5624482/RPCS3.log

Here is the log for 10808 where the lighting works from afar but when you have any player closeup the lighting will not work on the players and referees. Sun still shines on the field of play.
https://github.com/RPCS3/rpcs3/files/5624429/RPCS3.log

I've tried to create an RSX capture and the game freezes on me. 

Here is a short vid with the build that works. I only updated because the game was having micro stutters that you can see in the vid. [https://streamable.com/2ojf7i](url)

And here is a vid where the updated build is not having issues with the micro stuttering, but is having lighting issues. [https://streamable.com/34jkvm](url)

**Comment by AniLeo** [comment] 2020-12-01 14:17
Missing which build regressed it

**Comment by huskereurocat** [comment] 2020-12-01 14:26
Build 11336 is the one that I just downloaded this morning.   I just tried to load build 10810 because I thought the regression may have surfaced with the move to version 12 instead of 11, but 10810 is version 11 and it didn't work either. So somewhere between 10758 and 10810 is where the regression is. Do you need me to try all of them?

**Comment by huskereurocat** [comment] 2020-12-01 14:39
Here is the log for build 10810 where the regression is in it. [RPCS3.log](https://github.com/RPCS3/rpcs3/files/5623238/RPCS3.log)

**Comment by Asinin3** [comment] 2020-12-01 15:46
> 10758 and 10810 is where the regression is. Do you need me to try all of them?

You need to determine where it broke exactly and what pull request caused the problem. Issue reports are on the tester to provide proper information. It's not up to the devs to retest old builds just so they can work out where something broke, that's the responsibility of the tester.

Logs here for graphical issues are mainly only going to be useful for seeing hardware/settings used since it's a graphical issue, it doesn't help determine where the issue is in most cases. There was no RSX/Render doc capture provided before/after either.

**Comment by huskereurocat** [comment] 2020-12-01 16:25
Alright, I can't provide a RSX capture since the game crashes when I go to the utility menu to try to create one. So is my option now to test all the builds after 10758 up to 10810 and see where the problem is?

**Comment by kd-11** [comment] 2020-12-01 16:30
Use a bisect pattern. Start with a build between 10758 and 10810 and see if its broken. If its not broken you check between this new build and 10810, if its broken you check the build between the new build and 10758. Repeat until you figure out the first one that breaks. Usually this is doable in a very few steps.

**Comment by huskereurocat** [comment] 2020-12-01 16:40
You got it!

**Comment by huskereurocat** [comment] 2020-12-01 18:02
Ok, in doing a little testing I found that 10781 was the last build that had working lighting, but the micro stutter was still present.   Starting with 10790 through 10807 froze NCAA 14 at the selection screen just before going into game play. Beyond that all builds have the lighting issue as described above but actual game play is possible. 

Here is the log for build 10781. The last build with working lighting.  And it has the micro stuttering video as well. 
[RPCS3.log](https://github.com/RPCS3/rpcs3/files/5624482/RPCS3.log)


Here is the log for 10808 where the lighting works from afar but when you have any player closeup the lighting will not work on the players and referees. Sun still shines on the field of play.  
[RPCS3.log](https://github.com/RPCS3/rpcs3/files/5624429/RPCS3.log)

Is there anything else that I need to get to you?

**Comment by kd-11** [comment] 2020-12-01 18:07
That's enough to isolate the regression.

**Comment by Asinin3** [comment] 2020-12-01 18:07
If that's the case then it means it was caused by this Pull Request: https://github.com/RPCS3/rpcs3/pull/8769

I would update the first post and link the pull request that broke it, add new logs and look into potentially making some renderdocs of the issue. Then just remove or hide the old outdated posts here.

Renderdoc instructions can be found by going to https://github.com/RPCS3/rpcs3/issues/new?assignees=&labels=&template=1-regression-report.md&title=

**Comment by kd-11** [comment] 2020-12-01 18:23
The regression trigger is too complex for user to provide any meaningful information in this case, so it is not necessary. The major issue is that there were many follow-up PRs touching the same code so a full investigation is required for this one. It may not even be a regression in accuracy, it may be that the new behavior is the correct one and old code was hiding bugs.

**Comment by kd-11** [comment] 2020-12-08 22:08
Should be fixed by https://github.com/RPCS3/rpcs3/pull/9396

**Comment by huskereurocat** [comment] 2020-12-09 12:16
Sorry, but it would seem this didn't do the trick!  Shaders, or lighting, whatever you wish to call it, still work fine with a zoomed out pic like they did before, but anytime you zoom in or on replays the players and refs are not in the sunlight. You can see in the second pic that the field has the sun shining on it and the players it does not. 
![image](https://user-images.githubusercontent.com/52609668/101628197-0dfe5d80-39e5-11eb-8d74-239b4e732d47.png)

![image](https://user-images.githubusercontent.com/52609668/101628753-e360d480-39e5-11eb-95cc-836fde4f5d1f.png)

**Comment by huskereurocat** [comment] 2020-12-09 12:24
This is a screenshot of the players and refs up close. In this setting, the sun is shining and the players and refs are shaded, but shouldn't be. You can see it is a sunny day from the crowd in the background. 
![image](https://user-images.githubusercontent.com/52609668/101629317-ca0c5800-39e6-11eb-8ef5-e1633e74200a.png)

**Comment by kd-11** [comment] 2020-12-09 12:48
Hmm interesting. Maybe I didn't fix the full issue afterall.

**Comment by kd-11** [comment] 2020-12-09 18:08
I forgot to commit a similar change on another line. Should be fixed now by https://github.com/RPCS3/rpcs3/pull/9401

**Closed** 2020-12-09 18:30 UTC
Labels: Bug, RSX, Regression

**Comment by huskereurocat** [comment] 2020-12-10 05:27
Thank you!!!  NCAA 14 works great now.
