### ISSUE TITLE
RPCS3 crashes with a std::vector error

### ISSUE THREAD

**Issue by ozz-is-here** [RPCS3/rpcs3#11699] opened 2022-03-27 16:03 UTC
## Quick summary
RPCS3 crashes after a game started.

## Details
The emulator crashes with this error:

```
/usr/lib/gcc/x86_64-unknown-linux-gnu/11.2.0/../../../../include/c++/11.2.0/bits/stl_vector.h:1045: std::vector::reference std::vector<vertex>::operator[](std::vector::size_type) [_Tp = vertex, _Alloc = std::allocator<vertex>]: Assertion '__n < this->size()' failed.
```

A game may start and render something (menu, for example) but after that the emulator crashes. Not with all the games, nor not every time.

[RPCS3.log](https://github.com/RPCS3/rpcs3/files/8357956/RPCS3.log)

Fedora Linux 35
AMD Ryzen 5 1500X
AMD Radeon RX 460
Mesa 21.3.7 with RADV Vulkan
RPCS3 Version: 0.0.21-1-e66d6a93 Alpha (not only this version, it has been started about a week ago, I haven't updated it for a month).
libc version: 2.34-29
libcxx version: 13.0.0-1

**Comment by MSuih** [comment] 2022-03-27 16:07
You seem to be using the flatpak version. Does this also happen on appimage from rpcs3.net?

**Comment by kd-11** [comment] 2022-03-27 16:25
We've had several bugs reported with the flatpak version that do not happen with official builds, always the same out of bounds error, but different parts pointed at. Seems like something is off with the flatpak build.

**Comment by AniLeo** [comment] 2022-03-27 16:26
Closing since it's not using the official build, ask to reopen if you can reproduce on the official build

**Closed by AniLeo** 2022-03-27 16:26 UTC

**Comment by ozz-is-here** [comment] 2022-03-27 16:29
Yes, it seems the problem is only with the Flatpak versions. 

Sorry. Please ignore this issue.

**Comment by Lctrs** [comment] 2022-03-28 16:40
@ozz-is-here https://github.com/flathub/net.rpcs3.RPCS3/pull/820 may fix your problem on flatpak. Could you test it please ?

**Comment by ozz-is-here** [comment] 2022-03-28 18:25
> @ozz-is-here [flathub/net.rpcs3.RPCS3#820](https://github.com/flathub/net.rpcs3.RPCS3/pull/820) may fix your problem on flatpak. Could you test it please ?

I've checked this build out, and it works fine. Thank you.
