### ISSUE TITLE
[Regression] FIFA 10 AND FIFA World Cup South Africa 2010

### ISSUE THREAD

**Issue by davedoc1984** [RPCS3/rpcs3#14138] opened 2023-07-05 11:31 UTC
### Quick summary

Both of these games "Crash to Desktop" after doing SPU Caches and it starts to launch the game.

These both worked in a previous build of RPCS3 from 2 weeks or so ago but now with the latest update of the Emulator, they both do not.

### Details

Both of these games "Crash to Desktop" after doing SPU Caches and it starts to launch the game.

These both worked in a previous build of RPCS3 from 2 weeks or so ago but now with the latest update of the Emulator, they both do not.

### Build with regression

0.0.28-15306-d41fe80b Alpha | master

### Attach two log files

Unfortunately haven't got the log files as I have lost the previous version of RPCS3 in which these 2 games worked.

It last worked on a build from 2 weeks ago

### System configuration

CPU Intel Core i7 12700H
GPU Nvidia RTX 3070 Laptop - Latest Driver at time of writing this. 536.40
16GB of RAM

**Comment by davedoc1984** [comment] 2023-07-05 11:38
Both games worked on this version of RPCS3

0.0.28-15225-715e3856 Alpha | master

**Comment by YuriNator557** [comment] 2023-07-05 11:56
So build 15227 broke the games?

**Comment by kd-11** [comment] 2023-07-05 19:20
@davedoc1984 You need to be clear on which is the first build that doesn't work.

**Comment by FlexBy420** [comment] 2023-07-05 19:26
Pretty sure this is a duplicate of #14094

**Comment by AniLeo** [comment] 2023-08-19 07:42
Closing as duplicate, to be tracked on the other ticket

**Closed by AniLeo** 2023-08-19 07:42 UTC
