### ISSUE TITLE
No Vulkan device was created on 7336

### ISSUE THREAD

**Issue by notxrandr** [RPCS3/rpcs3#5124] opened 2018-09-13 17:57 UTC
Manjaro Linux x64
RPCS3 0.0.5-7336
Intel i5-6500, AMD RX470

In GPU settings Vulkan option is no longer available for no apparent reason. 7298 didn't have this issue and games worked just fine with Vulkan enabled.

**Comment by AniLeo** [comment] 2018-09-14 23:33
Need RPCS3.log file and driver information, also post `vulkaninfo` output.
This is likely not a RPCS3 issue but just want to make sure in the case it is - could unlikely be related to #5120.

**Comment by toccata10** [comment] 2018-09-15 10:04
Culprit is #5112 
Archlinux, r9 fury, mesa 18.2
7326 is ok, 7328 can't create vulkan. Compiling gives the same result as precompiled binaries
Log files attached
[RPCS3.log-7326.gz](https://github.com/RPCS3/rpcs3/files/2385586/RPCS3.log-7326.gz)
[RPCS3.log-7328.gz](https://github.com/RPCS3/rpcs3/files/2385587/RPCS3.log-7328.gz)

**Comment by kd-11** [comment] 2018-09-15 13:06
Likely some library changed when building, otherwise makes no sense. I'll run some tests on linux later but I built on linux as recently as yesterday and everything was working.

**Comment by AniLeo** [comment] 2018-09-15 13:07
How is it #5112, it doesn't touch Vulkan at all

It's a mesa issue then? I tested on NVIDIA proprietary on Ubuntu and Vulkan works.

**Comment by notxrandr** [comment] 2018-09-16 03:30
I have Mesa 18.1.8 and rpcs3 v7298 can still run with Vulkan enabled just fine. That's part of the reason I didn't attach the logs, it doesn't look like issue is in vulkan implementation or hardware since previous versions don't have any issue with it.

**Comment by kd-11** [comment] 2018-09-16 10:40
![image](https://user-images.githubusercontent.com/15904127/45595515-df37df00-b9b5-11e8-8889-296c484df4b4.png)
Latest AppImage (7345) with mesa 18.0.5. Also works with nvidia, tried both self-compiling and using appimage.

**Comment by toccata10** [comment] 2018-09-16 12:07
On Arch, mesa was updated very recently to 18.2
Working as it should on 7326, but doesn't show up on 7328 and later versions
![7326](https://user-images.githubusercontent.com/7478580/45596251-82d6be80-b9b9-11e8-92b4-9661b937035b.jpeg)
![7328](https://user-images.githubusercontent.com/7478580/45596253-866a4580-b9b9-11e8-94e0-baf9cb1985f1.jpeg)

**Comment by kd-11** [comment] 2018-09-16 13:52
Something else must have changed, maybe a new Qt release. Which qt version are you compiling against locally? Did you recently update it?

**Comment by toccata10** [comment] 2018-09-18 07:37
Compiling latest master (7352) this morning: Vulkan device is back and working fine. AppImage 7352 is not available for linux (should be, but isn't) and AppImage 7350 still shows no Vulkan device.

**Comment by hcorion** [comment] 2018-10-31 06:54
> Compiling latest master (7352) this morning: Vulkan device is back and working fine.
So then the issue is fixed?

**Comment by toccata10** [comment] 2018-11-04 11:17
Tested on Arch, rev7470: the issue is fixed for me: when I compile or when I download the AppImage,I always have the Vulkan option.

**Comment by AniLeo** [comment] 2018-11-05 21:05
Closing as reported fixed, if issue still persists for OP then it can be reopened.

**Closed by AniLeo** 2018-11-05 21:05 UTC
Labels: Need Information, OS: Linux
