### ISSUE TITLE
[Regression] God of War Ascension broken shadows

### ISSUE THREAD

**Issue by prfd** [RPCS3/rpcs3#12778] opened 2022-10-08 18:31 UTC
### Quick summary

#12762 probably broke it somehow.

0.0.24-14228 has no shadows issues.

### Details

![Captura de tela 2022-10-08 131438](https://user-images.githubusercontent.com/84674931/194721398-04f295b8-aa13-47f8-a61d-12a15d5b774b.png)

https://user-images.githubusercontent.com/84674931/194721411-bf168823-b1f7-47ca-a6e7-2b6f393dc7f7.mp4

### Build with regression

0.0.24-14232

### Attach two log files

[RPCS3-issue.log.gz](https://github.com/RPCS3/rpcs3/files/9740031/RPCS3-issue.log.gz)
[RPCS3-working.log.gz](https://github.com/RPCS3/rpcs3/files/9740032/RPCS3-working.log.gz)

### Attach capture files for visual issues

https://drive.google.com/file/d/1K5Np9-pL2j6oWckFJoAjw86uplyqJjI8/view?usp=sharing

**Comment by kd-11** [comment] 2022-10-08 20:59
Is it still broken? That PR had a major known regression that got fixed a few hours later.

**Comment by prfd** [comment] 2022-10-08 21:31
> Is it still broken? That PR had a major known regression that got fixed a few hours later.

Yeah, can you reproduce it with the capture?

**Comment by solarmystic** [comment] 2022-10-08 22:40
> > Is it still broken? That PR had a major known regression that got fixed a few hours later.
> 
> Yeah, can you reproduce it with the capture?

Which chapter is this? Let me try to reproduce this issue.

**Comment by kd-11** [comment] 2022-10-08 23:03
I was able to reproduce. I know what the issue is, a fix will be provided shortly.

**Comment by kd-11** [comment] 2022-10-08 23:24
This should be fixed by https://github.com/RPCS3/rpcs3/pull/12779

**Closed** 2022-10-09 00:00 UTC
