### ISSUE TITLE
"Thrustmaster FFB" doesn't work correctly in Gran Turismo 5

### ISSUE THREAD

**Issue by JeanNong** [RPCS3/rpcs3#10669] opened 2021-08-07 04:14 UTC
![1628307900(1)](https://user-images.githubusercontent.com/88017533/128586907-ff72f4d3-c48d-412a-a76e-478022965a3e.png)

I use "Thrustmaster FFB" to play Gran Turismo 5, and the hardware ID is correct. RPCS3 (it should be GT5) detected my steering wheel and it turned by itself when starting GT5.
But when I enter the game, it cannot be operated. All the buttons have no response and no force feedback. When I want to change the controller setting, it displays "Reserved" under Handles and cannot be changed.
 I searched all steering wheels on the market, there is no Thrustmaster FFB Wheel. So I use my T300RS GT as "Thrustmaster FFB"

Please guys, I really want to use the steering wheel to play GT5 4K 60FPS

[RPCS3.zip](https://github.com/RPCS3/rpcs3/files/6948568/RPCS3.zip)

PS. I uploaded my RPCS3.log at https://github.com/RPCS3/rpcs3/issues/9689 but there was no response, so I decided to open a new issue.

**Comment by JeanNong** [comment] 2021-08-07 04:33
I tried to add my device hardware ID (Thrustmaster T300RS Racing Wheel USB\VID_044F&PID_B66E\5&7813E2C&3&9) in sys_usbd.cpp. and built RPCS3.exe with Visual Studio but it failed...
Can anyone help me, because T300RS supports GT5 in PS3, so as long as RPCS3 detects my T300 then it will definitely work in GT5

**Comment by Florin9doi** [comment] 2021-08-07 09:07
No idea if rpcs3 supports USB hot plug, but can you check what happens after you start the game? Somehow the controller changes its id from `044f:b65d` to `044f:b65e` or something else? You may have to install WinUSB for the new device id too.

**Comment by JeanNong** [comment] 2021-08-07 10:22
@Florin9doi Yes, I deleted the driver of T300 and changed it to Thrustmaster FFB Wheel. So GT5 installed some kind of driver for it, so when it enters GT5, it will turn to calibrate the wheel by itself.
But I didn’t find any new input devices. The hardware ID of Thrustmaster FFB Wheel is still the original.
![1628331570(1)](https://user-images.githubusercontent.com/88017533/128597018-b1750b7a-4fa7-4d27-9da6-310589e70c31.png)

**Comment by JeanNong** [comment] 2021-08-07 10:27
> @Florin9doi是的，我删除了 T300 的驱动程序并将其更改为 Thrustmaster FFB Wheel。所以GT5为它安装了某种驱动，所以当它进入GT5时，它会自动校准车轮。
> 但是我没有找到任何新的输入设备。Thrustmaster FFB Wheel 的硬件 ID 仍然是原始的。
> ![1628331570(1)](https://user-images.githubusercontent.com/88017533/128597018-b1750b7a-4fa7-4d27-9da6-310589e70c31.png)

Oh, where are you @Florin9doi     😨

**Comment by Megamouse** [comment] 2021-08-07 21:34
duplicate of #9689

**Closed by Megamouse** 2021-08-07 21:34 UTC
