### ISSUE TITLE
Texts Issue on Metal Gear Solid 3 (Snake Eater) HD Edition

### ISSUE THREAD

**Issue by avex22** [RPCS3/rpcs3#12622] opened 2022-09-07 21:22 UTC
### Quick summary

in having an issue with Metal Gear Solid Snake Eater HD Versión BLES01419 the texts are wrong, like crashed symbols is kinda weird, i'm leaving screenshots. I will downgrade

adding info about my pc... Windows 10 Pro, MSI Katana GF66 RTX 3060 6GB

### Attach a log file

![1](https://user-images.githubusercontent.com/100171457/188983512-86e9534c-b775-413e-9a73-355f1dc8d764.PNG)
![2](https://user-images.githubusercontent.com/100171457/188983514-0c7a2e9c-6e36-4926-8331-c283e0cb765d.PNG)
![3](https://user-images.githubusercontent.com/100171457/188983515-c104b387-ae1f-4b68-af85-de7e2ade2b50.PNG)

**Comment by YuriNator557** [comment] 2022-09-07 21:38
Potentially a duplicate of #12618

**Comment by solarmystic** [comment] 2022-09-07 22:51
Also affects MGS Peace Walker, according to a user on discord
https://discord.com/channels/272035812277878785/272035812277878785/1017132015218327663
(read the message and replies)

**Comment by MSuih** [comment] 2022-09-08 04:36
This is missing log files and a rsx capture.

**Comment by solarmystic** [comment] 2022-09-08 18:58
Issue seems to have been resolved as of 0.0.24-14135, so it was definitely a duplicate of #12618 

![image](https://user-images.githubusercontent.com/4345150/189203692-cefa2d4d-e528-4747-9483-2a2d0dba0e3e.png)

![image](https://user-images.githubusercontent.com/4345150/189203754-2210cbe4-b044-43f8-a271-18a1af14893e.png)

**Comment by Nekotekina** [comment] 2022-09-09 09:18
Seems fixed.
Reopen it necessary.

**Closed by Nekotekina** 2022-09-09 09:18 UTC
Labels: Need Information
