### ISSUE TITLE
Issues with MGS4 on recent updates (models bugging out, freezing)

### ISSUE THREAD

**Issue by TheKrzysiek** [RPCS3/rpcs3#15124] opened 2024-01-30 09:56 UTC
### Quick summary

On the newest builds of the emulator I, aswell as multiple other people, have encountered issues that we didn't have before. Not sure which version brought them, but I remember not having them around a month ago.

### Details

During the chase sequences in Act 2 and Act 3 (didn't test 4 and 5) Snake's model can start freaking out, or even completely disappear, making you unable to fire.
![image](https://github.com/RPCS3/rpcs3/assets/30327354/3a8e7db9-d7f7-46bf-8e1a-fcbabac8dc16)
![image](https://github.com/RPCS3/rpcs3/assets/30327354/bd69cfa7-06e6-4b4c-994d-8f5046790bc6)

The screen can go fully black.
![image](https://github.com/RPCS3/rpcs3/assets/30327354/4a440c8e-ecdf-436e-ab66-0795f146d900)

And on some systems, it can even fully freeze in certain scenarios (attached log).

The issues were similar for multiple people with diffrent systems.

### Attach a log file

[RPCS3.log](https://github.com/RPCS3/rpcs3/files/14095829/RPCS3.log)

### Attach capture files for visual issues

[video1.zip](https://github.com/RPCS3/rpcs3/files/14095902/video1.zip)
[video2.zip](https://github.com/RPCS3/rpcs3/files/14095939/video2.zip)

### Other details

RPCS3 0.0.30-16014

**Comment by OlegVolgin** [comment] 2024-02-04 02:21
Ryzen 5 5600X, GTX 1060, Windows 10 22H2, same issues, along with the gray screens (mentioned in another issue) and often random crashes

**Comment by OddOttAllen** [comment] 2024-02-06 22:16
same issues here with my Intel i7 11700K CPU and AMD Radeon RX 6750 XT. i'm on Windows 11 23H2. didn't have any of these issues until the more recent updates... glad i was able to finish the game before them

**Comment by Amoneleais** [comment] 2024-02-11 01:03
Anyone found how to solve this? or, which version is working?

**Comment by kd-11** [comment] 2024-02-11 01:09
First someone needs to identify when it started happening so that we know who needs to be contacted to investigate.

**Comment by AniLeo** [comment] 2024-02-11 01:55
This was wrongly submitted as a regular bug report, it's a regression so it needs to follow the regression report template instead, need to know first affected build in order for this ticket to start being looked into.

**Comment by TheKrzysiek** [comment] 2024-02-11 08:26
> This was wrongly submitted as a regular bug report, it's a regression so it needs to follow the regression report template instead, need to know first affected build in order for this ticket to start being looked into.

I sadly only know that that it was fine around end of December, but I don't know which was the last build exactly

**Comment by RipleyTom** [comment] 2024-02-13 14:35
Can you check if it is still an issue with latest build?

**Comment by ItsLaguna** [comment] 2024-02-13 15:02
I can't reproduce, tried with and without patches while using the recommended settings from the wiki.

**Comment by RipleyTom** [comment] 2024-02-13 15:23
@TheKrzysiek the log you posted in the issue is empty, please provide log so we can verify settings.

**Comment by TheKrzysiek** [comment] 2024-02-13 16:55
> @TheKrzysiek the log you posted in the issue is empty, please provide log so we can verify settings.

Oh sorry about that, I didn't notice it, this one should be good
[RPCS3.log](https://github.com/RPCS3/rpcs3/files/14269693/RPCS3.log)

**Comment by ItsLaguna** [comment] 2024-02-13 17:19
> Oh sorry about that, I didn't notice it, this one should be good [RPCS3.log](https://github.com/RPCS3/rpcs3/files/14269693/RPCS3.log)

Grabbed your config, got the error, changed Relaxed xfloat to Approximate, booted again, no more error.
There's also random settings enabled like SPU loop detection, WDB+RCB, Multithreaded RSX...

**Comment by RipleyTom** [comment] 2024-02-13 17:22
Yes, Relaxed XFloat is definitely NOT recommended for this game!
Closing as relaxed is inherently janky.

**Closed by RipleyTom** 2024-02-13 17:22 UTC
Labels: Need Information
