### ISSUE TITLE
MotorStorm car flickering

### ISSUE THREAD

**Issue by MilanRL** [RPCS3/rpcs3#13129] opened 2022-12-26 13:01 UTC
### Quick summary

All cars are flickering. It is really annoying and makes the game nearly unplayable. 

https://user-images.githubusercontent.com/121428638/209551085-298404b2-4d68-47b6-800f-ea23ea1afd04.mp4

https://user-images.githubusercontent.com/121428638/209551096-ba735483-af66-4221-97b0-b97f96e837f9.mp4

https://user-images.githubusercontent.com/121428638/209551104-eb13e524-3301-43bd-a038-e14d7640b38a.mp4

Here are a few examples

### Details

Cars are flickering around which should normally not be the case. I showed it in the clips above. The flickering doesn't appear on PS3 / only on RPCS3

### Attach a log file

[RPCS3.log](https://github.com/RPCS3/rpcs3/files/10303528/RPCS3.log)

**Comment by Juansero29** [comment] 2022-12-26 14:08
Also experiencing this in Windows... What can we do to help solve this?

**Comment by Satan86** [comment] 2022-12-26 14:48
Duplicate of #8376.

**Comment by MilanRL** [comment] 2022-12-26 14:55
> Ich habe das auch in Windows erlebt ... Was können wir tun, um dieses Problem zu lösen?

i think the RPCS3 devs have to fix it

**Comment by MSuih** [comment] 2022-12-26 16:25
Closing as duplicate

**Closed by MSuih** 2022-12-26 16:25 UTC
