### ISSUE TITLE
Sixaxis support feature for xinput controllers

### ISSUE THREAD

**Issue by Krishster** [RPCS3/rpcs3#9849] opened 2021-02-25 20:33 UTC
If any xinput controller natively support sixaxis feature then rpcs3 should not limits its functionality rather let the controller use its full potential like DS4 controller.

**Comment by 13xforever** [comment] 2021-02-25 20:48
xinput doesn't have any motion support; it doesn't have anything besides what xbox360 gamepad offers, by design

**Comment by Megamouse** [comment] 2021-02-25 21:00
Closing. Not possible

**Closed by Megamouse** 2021-02-25 21:00 UTC
