### ISSUE TITLE
Autoupdate?

### ISSUE THREAD

**Issue by Hasster1** [RPCS3/rpcs3#5769] opened 2019-03-29 04:30 UTC
I was thinking about autoupdating master builds (Of course with permission of the user).
Wouldn't it will be easier, than every time open the rpcs3 site, then download new version, unpack it, and etc?

**Comment by RainbowCookie32** [comment] 2019-03-29 05:15
At the moment there are more important things for devs to focus on than auto-updating. If someone wants to implement it I'm pretty sure no one will stop them, but considering the emulator is on Alpha stage I don't see how an auto-updater is relevant (at least at this point).

**Comment by AniLeo** [comment] 2019-03-29 18:53
Duplicate of #3595

**Closed by AniLeo** 2019-03-29 18:53 UTC
