### ISSUE TITLE
SONIC UNLEASHED[BLES00425] crash issues !

### ISSUE THREAD

**Issue by arcadee1977** [RPCS3/rpcs3#5712] opened 2019-03-11 11:13 UTC
The game will crash in the following circumstances (All day stage are works perfectly) :
(1) Loading the most night stage

(2) Appearance of enemies at night stage

(3) Break the door at night stage

The error log is:
F {PPU[0x1000000] Thread (main_thread) [0x0294694c]} MEM: Access violation writing location 0xXXXX
(eg:F {PPU[0x1000000] Thread (main_thread) [0x0294694c]} MEM: Access violation writing location 0xacf4)

**If you use "Interpreter" PPU Decoder, the night stages are playable. But it's slow :(**

==================================================================
![未标题-1](https://user-images.githubusercontent.com/47111657/54119825-413b4380-4431-11e9-8d22-ac66bdf6fe77.jpg)
crash 1: Loading the most night stage

==================================================================

![未标题-3](https://user-images.githubusercontent.com/47111657/54119857-5a43f480-4431-11e9-9ec9-22624cac901d.jpg)
crash 2: Appearance of enemies at night stage

===================================================================

![未标题-2](https://user-images.githubusercontent.com/47111657/54119897-6fb91e80-4431-11e9-8b3c-706fba51ba84.jpg)
crash 3: Break the door at first night stage

===================================================================
MY PC:
CPU:8700K 
1070TI
16G DDR4

**Comment by MarioSonic2987** [comment] 2019-03-11 15:08
Duplicate of #4087.

**Comment by AniLeo** [comment] 2019-03-11 15:16
Closing as duplicate of #4087 , please continue discussion there

**Closed** 2019-03-11 15:16 UTC
