### ISSUE TITLE
[Feature Request] Native Apple Silicon

### ISSUE THREAD

**Issue by iMonZ** [RPCS3/rpcs3#11922] opened 2022-05-03 19:24 UTC
We already got this issue here: https://github.com/RPCS3/rpcs3/issues/11913

Unfortunately there was an misunderstanding

No one wanted a Native metal version.

MoltenVK is doing perfectly fine.
What is missing is a native ARM version instead of x86 to avoid using and installing the x86 emulator.

**Comment by AniLeo** [comment] 2022-05-03 22:08
Duplicate of #715

**Comment by Asinin3** [comment] 2022-05-03 22:10
Bold of you to assume i misunderstood just because i mentioned the metal api not happening as a side note

**Comment by Megamouse** [comment] 2022-05-04 07:18
Duplicate and not helpful. Everyone knows what you are requesting.

**Closed by Megamouse** 2022-05-04 07:18 UTC
Labels: OS: Mac
