### ISSUE TITLE
Vulkan not showing as an option in GPU

### ISSUE THREAD

**Issue by Cosmic-Gary** [RPCS3/rpcs3#7620] opened 2020-02-28 04:29 UTC
My Persona 5 keeps blackscreening on launch and I am unsure on how to get vulkan as an option
![image](https://user-images.githubusercontent.com/61487890/75510214-0bbf9b00-599f-11ea-88af-566c75db8f36.png)

Launching Persona 5 I get a black screen but the fps is showing
RPCS3.log
![image](https://user-images.githubusercontent.com/61487890/75510472-f6973c00-599f-11ea-9743-f26d856568c0.png)

Specs:
16.0GB RAM
Intel Core i7-7700 CPU
3.60 GHz
OS: Win 10
64 bit
Config Menu
CPU
![image](https://user-images.githubusercontent.com/61487890/75510489-04e55800-59a0-11ea-8b9a-dce5d0338bd4.png)
GPU
![image](https://user-images.githubusercontent.com/61487890/75510504-0c0c6600-59a0-11ea-9b15-68b6b959d90f.png)
Audio
![image](https://user-images.githubusercontent.com/61487890/75510518-129add80-59a0-11ea-8021-ce0e32341820.png)
Advanced
![image](https://user-images.githubusercontent.com/61487890/75510522-1890be80-59a0-11ea-90f1-219008768615.png)
Emulator
![image](https://user-images.githubusercontent.com/61487890/75510526-1e869f80-59a0-11ea-8033-872ad362db61.png)

I have tried reinstalling Nvidia drivers but an error occurs during that which is a separate issue
![image](https://user-images.githubusercontent.com/61487890/75510420-ccde1500-599f-11ea-8cb0-55857ff4a614.png)

so that plan is pretty much a dead end

**Comment by RainbowCookie32** [comment] 2020-02-28 04:31
Please move to discord and close the issues. It's clearly a support case and not an actual emulator issue

**Comment by AniLeo** [comment] 2020-02-28 10:52
Also a support case, not a bug in the emulator, closing.

**Closed** 2020-02-28 10:52 UTC

**Comment by jeremybris** [comment] 2020-03-01 00:09
Older graphics cards do not support vulkan. You may need a newer graphics card. I don't know why you can not update your graphics card.

**Comment by xCENTx** [comment] 2021-09-25 23:36
This is still an issue. Driver updates will break the RPCS3 vulkan support

**Comment by AniLeo** [comment] 2021-09-25 23:37
Driver's fault, not our problem. We can't detect what's not there.

**Comment by xCENTx** [comment] 2021-09-25 23:42
I wouldn't be too sure about that. There is a definitely a GPU in my system and every other application on the system detects it just fine

**Comment by AniLeo** [comment] 2021-09-25 23:47
You aren't sure but I am, if your driver updates keep breaking Vulkan on your system, complain to your vendor, not to us. We load Vulkan as other applications do, it's on the Vulkan standard. It's either there to detect or it isn't. Most applications don't even use Vulkan so chances are you don't even have another application that uses it.

Locking this to avoid further spam, don't open more issues on this as they'll be closed, there's nothing wrong on RPCS3.
