### ISSUE TITLE
[ALSOFT] (EE) Failed to set real-time priority for thread

### ISSUE THREAD

**Issue by cinnamonmatexfce** [RPCS3/rpcs3#9816] opened 2021-02-21 12:06 UTC
As in title, I get these messages when starting emulator. Also, the emulator take up to 30secs to open up, and also same time when opening "Configuration" menu.

`5.10.16-zen1-1-zen`
`GTX 1660 SUPER (nvidia 460.39)`

**Comment by kattjevfel** [comment] 2021-02-21 13:53
I used to have this, but I can no longe reproduce it. It was related to using pipewire and not having a microphone connected.

**Comment by cinnamonmatexfce** [comment] 2021-02-21 15:44
I'm on ArchLinux with KDE. Now I tried removing `pipewire` related packages; btw I cannot completely remove `pipewire` at all, 'cause it's needed by `kwin`. The error `[ALSOFT] (EE) Failed to set real-time priority for thread` is still here, but now rpcs3 loads up instantly, as expected.

**Comment by arabek** [comment] 2021-02-22 11:09
Setting real-time priority for threads is very system-dependant (and kernel config) in linux. Some systems allow it, some not - but it's not up to the emulator to fix this. I would close as invalid.

**Comment by hcorion** [comment] 2021-02-23 18:08
Going to close this issue because the loading issue was resolved, and since as arabek mentioned, the alsoft warning is not really an issue in RPCS3, but with OpenAL itself and your specific system config.

**Closed by hcorion** 2021-02-23 18:08 UTC
Labels: Need Information, OS: Linux

**Comment by cinnamonmatexfce** [comment] 2021-02-24 18:27
OK.
BTW, in case anyone needs help in future:
```
# usermod -G realtime -a $(whoami)
```

Tested on ArchLinux with `5.11.1-zen1-1-zen`

**Comment by Un1Gfn** [comment] 2021-07-13 14:15
BTW BTW if you get the following

    usermod: group 'realtime' does not exist

please refer to [Realtime_process_management](https://wiki.archlinux.org/title/Realtime_process_management).

(tl; dr - install [realtime-privileges](https://archlinux.org/packages/community/any/realtime-privileges))

**Comment by Parakleta** [comment] 2022-02-27 03:20
If you don't want to activate realtime privileges you can disable realtime (or just the nag) as described in the following thread.

https://github.com/kcat/openal-soft/issues/554

**Comment by JustTemmie** [comment] 2023-12-11 18:37
BTW BTW BTW
the realtime-privleges package has been moved from the AUR into the extra repos:
[realtime-privileges](https://archlinux.org/packages/extra/any/realtime-privileges/)
