### ISSUE TITLE
The Orange Box [BLES00153] Lighting issue

### ISSUE THREAD

**Issue by JusicP** [RPCS3/rpcs3#4188] opened 2018-02-18 15:02 UTC
RPCS3 v0.0.4-6440-877b296fc Alpha | HEAD
Lighting of the game too dark and has green tint. Tried with Strict Rendering Mode, GPU Texture Scaling etc but nothing changed. With Vulkan and DX12 game is fully dark.

Original PS3:
![hl2 should be](https://user-images.githubusercontent.com/25232950/36353108-e44e6c7e-14ca-11e8-9baa-e15e246baafd.png)

RPCS3:
![hl2 too dark](https://user-images.githubusercontent.com/25232950/36353115-e7d75090-14ca-11e8-962f-37e2f6de065b.png)
[The Orange Box.zip](https://github.com/RPCS3/rpcs3/files/1734811/The.Orange.Box.zip)

**Comment by MSuih** [comment] 2018-02-18 15:46
Duplicate of #3031, this same issue affects dozens of different titles.

**Closed** 2018-02-18 16:28 UTC

**Comment by JusicP** [comment] 2018-02-18 16:30
ok
