### ISSUE TITLE
Mass Effect 3 Demo texture format regression

### ISSUE THREAD

**Issue by Xcedf** [RPCS3/rpcs3#4304] opened 2018-03-18 10:00 UTC
Mass Effect 3 Demo NPEB90387 has overbright issue caused by fcd702c8

master
![5 1](https://user-images.githubusercontent.com/7060586/37564699-4587a6d0-2aac-11e8-8830-3e9e62fd3088.jpg)

build before the regression
![5](https://user-images.githubusercontent.com/7060586/37564689-1c75146c-2aac-11e8-8669-6ee45b66eaf2.jpg)

revertig X16 format rules or setting the second value from ONE to R fixes it

applied this to newest master and it seems overall render ingame is imroved, the last time i ran it the game looked uglier, selfshadowing now working, yet groundsurface shadows are still missing like in any other UE3 game
![27](https://user-images.githubusercontent.com/7060586/37564691-293c4c9c-2aac-11e8-9042-7b85b178e045.jpg)

**Comment by kd-11** [comment] 2018-03-18 13:53
The issue is alot more complex than that, details will be made publicly available soon. Closing in favor of the epic ue3 tracker.

**Closed by kd-11** 2018-03-18 13:53 UTC

**Comment by Zangetsu38** [comment] 2018-03-18 23:35
@kd-11 revert x16 also fix flash ligh inside resistence on Window in wall, same probleme so 
![image](https://user-images.githubusercontent.com/5261759/37572572-6a4f5132-2b0d-11e8-9b4c-2403cafe9137.png)
