### ISSUE TITLE
Save data interface cannot be shown in full screen mode

### ISSUE THREAD

**Issue by raven02** [RPCS3/rpcs3#3273] opened 2017-08-20 03:10 UTC
The save data interface only shown in windows mode but not visible in full screen mode.

Workaround: switch back to window mode to select save entry .

**Comment by flash-fire** [comment] 2017-08-20 03:19
I think this only happens with multiple monitors because I can't reproduce when using a single monitor.  That's also fairly annoying because it'll be hard for me to fix it since I'm unable to reproduce.

**Comment by Asinin3** [comment] 2017-08-20 03:36
Yeah, confirmed the same thing happens with the dialog pop-ups from RPCS3 for games where the in-game setting is skipped. e.g DLC has been enabled messages when starting a new game with persona 5.

**Comment by raven02** [comment] 2017-08-20 06:07
I basically use single monitor .It happen for games that used to save game and select entry .

**Comment by raven02** [comment] 2017-08-20 06:26
Tried setWindowFlags(Qt::WindowStaysOnTopHint); but in vain

**Comment by Megamouse** [comment] 2017-08-20 07:26
I think it's because it should have the game window as a parent.
but as far as I can tell it has a nullptr as parent. (maybe I couldn't find the place where we set the parent though.)

**Comment by raven02** [comment] 2017-08-20 09:27
Probably here ?

https://github.com/RPCS3/rpcs3/blob/master/rpcs3/rpcs3qt/save_data_list_dialog.h#L20

**Comment by Megamouse** [comment] 2017-08-20 10:54
works for me both on master as well as my own parented build.
But both cases don't work for raven02.

we believe it is something with his system. msgdialog seems to work though.

maybe pirhoman can make it work identical to that and use a callback for s32 instead

**Comment by raven02** [comment] 2017-08-20 10:56
BTW, I'm using Nvidia .I will try to re-install driver clean

**Comment by Asinin3** [comment] 2017-08-20 11:56
But it happens to me as well, not just with the dialog windows but with the save menu as well.

Win 10 with latest nvidia drivers and a single monitor.

**Comment by Megamouse** [comment] 2017-08-20 12:00
yeah we figured it is nvidia by now

**Comment by AniLeo** [comment] 2017-10-08 14:38
This is not an issue for me on latest NVIDIA drivers 385.69, but I'm using an Optimus set-up with Intel HD 530 (21.20.16.4664)

**Comment by Megamouse** [comment] 2017-10-08 18:25
I had the issue on some other build recently. I think it was the osk that didn't show on DES

**Comment by Asinin3** [comment] 2018-01-01 11:23
Fixed by https://github.com/RPCS3/rpcs3/pull/4011 
(WiP screenshot)
![rpcs3_2018-01-01_21-22-05](https://user-images.githubusercontent.com/15137035/34467325-26939d96-ef3e-11e7-84a8-622fdf61224d.jpg)

**Comment by Megamouse** [comment] 2018-01-01 11:25
this doesn't look like fullscreen to me.... but it will be fixed anyway

**Comment by Asinin3** [comment] 2018-01-01 11:27
It is fixed in full-screen, I just took a windowed screenshot earlier so uploaded that.

**Comment by Megamouse** [comment] 2018-01-22 13:38
can be closed

**Closed** 2018-01-22 14:25 UTC
Labels: Driver: NVIDIA
