### ISSUE TITLE
[Feature Request] add more languages 

### ISSUE THREAD

**Issue by uaqlover** [RPCS3/rpcs3#5836] opened 2019-04-13 03:36 UTC
adding more languages to Emulator

https://stackoverflow.com/questions/5432793/c-multilanguage-localisation-support

i will add 
Arabic 
Urdu

and need members help to add 

Chinese
Spanish
Portuguese
Japanese
French
Russian
Hebrew 
German
Hindi
Thai
Turkish

**Comment by MSuih** [comment] 2019-04-13 03:41
Duplicate of #4259

**Closed** 2019-04-13 03:42 UTC
