### ISSUE TITLE
God of War 3 [BCES-00510]

### ISSUE THREAD

**Issue by Trollking121** [RPCS3/rpcs3#8351] opened 2020-06-05 01:53 UTC
Game keeps getting invalid enum or integer and not even starting.
The log all is available at the bottom.
All most all combination of settings were used. None worked 
[RPCS3.log.gz](https://github.com/RPCS3/rpcs3/files/4733478/RPCS3.log.gz)

**Comment by AniLeo** [comment] 2020-06-05 03:42
Bad config value, delete main and custom config and let the emulator generate a clean one

**Comment by Trollking121** [comment] 2020-06-05 09:02
I tried that, but the game still won`t start. the "invalid enum or integer" is gone though.
[RPCS3.log.gz](https://github.com/RPCS3/rpcs3/files/4734996/RPCS3.log.gz)

**Comment by Asinin3** [comment] 2020-10-31 04:56
God of War 3 is very stable now with Wake-up-delay set to 50us on advanced settings tab. Are you still experiencing this issue?

**Comment by Trollking121** [comment] 2020-11-01 22:49
Not able to check as I have concluded that it’s not able to run due to my laptops hardware limitations. Will check when I get a better system.

**Comment by Yahfz** [comment] 2020-11-01 23:04
Closing since the user won't be able to provide more information with said system.  You can open a new one if you manage to reproduce it with your new parts/computer.

**Closed by Yahfz** 2020-11-01 23:04 UTC
Labels: Need Information
