### ISSUE TITLE
Regression: Catherine (#5038)

### ISSUE THREAD

**Issue by Borinius** [RPCS3/rpcs3#5060] opened 2018-08-30 16:48 UTC
In update 0.0.5-7257 the textures of the blocks in the first gameplay you get to are missing, cant say for the rest of the game as I have no save in this game. But I presume that its broken across the game as the texture is consitently broken on over 20 boots and a few completely new installs of the emulator and game.

System specs:
https://i.imgur.com/5K5Rmz5.png

Log:
[RPCS3.log.gz](https://github.com/RPCS3/rpcs3/files/2337047/RPCS3.log.gz)

Screenshot of the working texture [0.0.5-7254]:
https://i.imgur.com/ZrgfFqr.jpg

Screenshot of the borken texture[0.0.5-7257]: 
https://i.imgur.com/CTO96A5.png

**Comment by kd-11** [comment] 2018-08-31 08:29
Duplicate of https://github.com/RPCS3/rpcs3/issues/5066

**Closed by kd-11** 2018-08-31 08:29 UTC
Labels: Regression
