### ISSUE TITLE
[Regression] Mortal Kombat Komplete Edition [BLES01508] Blood Texture Rendering Issue

### ISSUE THREAD

**Issue by lastavenger2004** [RPCS3/rpcs3#16308] opened 2024-11-10 09:26 UTC
### Quick summary

I checked the older versions of RPCS3 and I noticed that the blood was fine before, but in some later builds, the blood got glitchy and was flickering green textures. 

Game was working great up to v0.0.11-10722-2cdb46b1
Then, it was unplayable in 0.0.12 and 0.0.13, and then in 0.0.14, the texture rendering failure issue began. And then since a version (not 0.0.27 but after 0.0.27), the blood texture rendering got worse to the point the color of the blood changed.

I attached two logs and two videos below.

### Build with regression

v0.0.14-11765-e76d8eb0

### Attach two log files

build that works - v0.0.11-10722-2cdb46b1
[RPCS3.log.gz](https://github.com/user-attachments/files/17690734/RPCS3.log.gz)

build with regression - v0.0.14-11765-e76d8eb0
[RPCS3.log.gz](https://github.com/user-attachments/files/17690735/RPCS3.log.gz)

### Attach capture files for visual issues

I have two videos, build that works and build with regression

build that works - v0.0.11-10722-2cdb46b1
https://github.com/user-attachments/assets/793bdc83-3d5b-43ac-8f70-134b40476580

build with regression - v0.0.14-11765-e76d8eb0
https://github.com/user-attachments/assets/872e5190-e4c9-497e-99c2-987fb8eb9e3b

**Comment by Megamouse** [comment] 2024-11-10 09:55
duplicate of #15571

**Closed by Megamouse** 2024-11-10 09:55 UTC

**Comment by lastavenger2004** [comment] 2024-11-10 10:12
How is this duplicate???

That is green blood

my case is glitching blood

**Comment by lastavenger2004** [comment] 2024-11-10 11:32
Nevermind. I'll delete my github account since no one is listening. You guys (mostly Metamouse) only close tickets without listening, without even checking the issue. There are over 1000 open tickets that you didn't check. You don't even address the issues. If you had problems with me or anything else you could just tell instead of this kind of apathy or ignorance. Even if some tickets are duplicate, I still believe it is worth listening and fixing. I tried to contribute, but you just ignore and no one takes the job. I don't care anymore. My name is Lastavenger2004 and I'm deleting my github account for my mental health.
