### ISSUE TITLE
inFamous Games - Failed to compile fragment shader Error

### ISSUE THREAD

**Issue by hockland** [RPCS3/rpcs3#9944] opened 2021-03-11 08:18 UTC
Note that this affects all 3 games in the inFamous series on the ps3 (inFamous, inFamous 2 and inFamous 2 - Festival of Blood).

## Quick summary
On reloading to a check point or saved game, the games will lock up on occasion with the error "Thread terminated due to fatal error: Failed to compile fragment shader."

After closing the game down, emulator crashes and closes itself.

## Details

Occurs in all inFamous games on the PS3, if you happen to fail a mission or die, which requires a reload then the game on occasion will lock up with the error - "Thread terminated due to fatal error: Failed to compile fragment shader. " Game then freezes and must be closed down, after which the emulator itself crashes and closes.

#### 1. Please attach RPCS3's log.
[RPCS3.log](https://github.com/RPCS3/rpcs3/files/6121364/RPCS3.log)

#### 4. Please provide comparison with real PS3.

Does not happen on a real PS3.

#### 5. Please provide your system configuration:
* OS - Windows
* CPU - i7 10700KF
* GPU - ASUS GeForce RTX 2060 Dual OC Mini6GB
* Driver version - 461.72

**Comment by hockland** [comment] 2021-03-11 08:25
Please also refer to the threads on all 3 games on the forums, where I posted game play through videos and which feature the issue occurring semi-often.

https://forums.rpcs3.net/thread-178946-page-3.html
https://forums.rpcs3.net/thread-190416-page-2.html?highlight=infamous+2

Festival of Blood in particular appears to be particularly affected by this issue:
https://forums.rpcs3.net/thread-198293-post-314998.html

**Comment by Darkhost1999** [comment] 2022-04-23 16:38
Can reproduce
F {RSX [0x05db890]} SIG: Thread terminated due to fatal error: Failed to compile fragment shader
(in file C:\Users\ContainerAdministrator\AppData\Local\Temp\cirrus-ci-build\rpcs3\Emu\RSX\VK\VKProgramPipeline.cpp:29[:25], in function compile)
[RPCS3.log](https://github.com/RPCS3/rpcs3/files/8547623/RPCS3.log)

Windows 11
GTX 1660S
Ryzen 5 3600

**Comment by Xcedf** [comment] 2022-04-23 16:56
Try to disable native float16 support

**Comment by kd-11** [comment] 2022-09-26 22:58
Should be fixed by setting RSX FIFO to "Atomic" in the advanced tab.
This error usually happens because we're too fast and start loading shaders before they have been copied over by CELL.

**Comment by Darkhost1999** [comment] 2022-09-27 00:52
I jumped into water like 10 times for Infamous 1 and infamous 2. Because I was able to trigger the issue when dying. But I can't get the issue again. There wasn't exactly a real trigger other than just die as to what I know. But I'll keep playing around in the games and see what happens.
This needs retest from OP

**Comment by MSuih** [comment] 2022-09-27 02:29
I've finished infamous 1 and 2 recently and I haven't encountered this issue. Infamous 1 is very stable and 2 has some crashes but not in the way described here.

**Comment by Darkhost1999** [comment] 2022-09-27 03:03
> I've finished infamous 1 and 2 recently and I haven't encountered this issue. Infamous 1 is very stable and 2 has some crashes but not in the way described here.

Afaik it only occurs when you die. So I mean this isn't an issue if you just play good.

**Comment by MSuih** [comment] 2022-09-27 03:17
I did die a plenty of times and never had a crash happen at that moment.

**Comment by YuriNator557** [comment] 2022-10-05 09:17
This is apparently still an issue.
[LOG.zip](https://github.com/RPCS3/rpcs3/files/9714387/LOG.zip)

**Comment by MSuih** [comment] 2022-10-05 09:20
```
·E 0:24:44.419552 {RSX [0x06595c8]} RSX: ERROR: 0:251: 'dot' : ambiguous best function under implicit type conversion 
ERROR: 0:251: '' : compilation terminated 
```

**Comment by MSuih** [comment] 2022-10-11 12:28
Actually the shader compiler crashes because the game desynced. The specific error happens because of f16 support, but it'd probably crash in different way if the same conditions were triggered on different GPU.

16-bit floats aren't enabled by default anymore either, so I think this can be closed.

**Closed by MSuih** 2022-10-11 12:28 UTC
Labels: Render: Vulkan
