### ISSUE TITLE
Monopoly Streets Freeze after long gaming session

### ISSUE THREAD

**Issue by darkmage1991** [RPCS3/rpcs3#8282] opened 2020-05-24 07:51 UTC
## Quick summary
Game ran great for 2.5 hours then locked up for what seems like no reason at all.

## Details

- full logs attached
- Win10 1909, 8GB RAM, Ryzen 3200G, IGPU, Latest drivers(20.4.2)
-More Details: Was playing single player, using vulkan renderer, game was running phenomenal then after roughly 2.5 hours constant playing the game froze up. I did nothing special at the time of the freeze that would make me assume i did something that would cause it to freeze at that moment.

[logs.zip](https://github.com/RPCS3/rpcs3/files/4673104/logs.zip)

**Comment by RainbowCookie32** [comment] 2020-05-24 07:55
Seems like a duplicate of #8153

**Closed** 2020-05-24 08:27 UTC
