### ISSUE TITLE
error: invalid declarator before '*' token

### ISSUE THREAD

**Issue by DocMAX** [RPCS3/rpcs3#10322] opened 2021-05-21 21:10 UTC
Now i did like BUILDING.mk says. But getting this error:

```
[ 96%] Building CXX object rpcs3/rpcs3qt/CMakeFiles/rpcs3_ui.dir/game_list_frame.cpp.o
[ 96%] Building CXX object rpcs3/rpcs3qt/CMakeFiles/rpcs3_ui.dir/save_manager_dialog.cpp.o
[ 96%] Building CXX object rpcs3/rpcs3qt/CMakeFiles/rpcs3_ui.dir/screenshot_manager_dialog.cpp.o
[ 96%] Building CXX object rpcs3/rpcs3qt/CMakeFiles/rpcs3_ui.dir/trophy_manager_dialog.cpp.o
In file included from /usr/include/qt5/QtConcurrent/qtconcurrentiteratekernel.h:49,
                 from /usr/include/qt5/QtConcurrent/qtconcurrentfilterkernel.h:47,
                 from /usr/include/qt5/QtConcurrent/qtconcurrentfilter.h:47,
                 from /usr/include/qt5/QtConcurrent/QtConcurrent:8,
                 from /usr/src/github/rpcs3/rpcs3/rpcs3qt/screenshot_manager_dialog.cpp:15:
/usr/include/qt5/QtConcurrent/qtconcurrentthreadengine.h:250:50: error: invalid declarator before '*' token
  250 |     ThreadEngineStarter<void>(ThreadEngine<void> *_threadEngine)
      |                                                  ^
/usr/include/qt5/QtConcurrent/qtconcurrentthreadengine.h:250:49: error: expected ')' before '*' token
  250 |     ThreadEngineStarter<void>(ThreadEngine<void> *_threadEngine)
      |                              ~                  ^~
      |                                                 )
make[2]: *** [rpcs3/rpcs3qt/CMakeFiles/rpcs3_ui.dir/build.make:871: rpcs3/rpcs3qt/CMakeFiles/rpcs3_ui.dir/screenshot_manager_dialog.cpp.o] Error 1
make[2]: *** Waiting for unfinished jobs....
In file included from /usr/include/qt5/QtConcurrent/qtconcurrentiteratekernel.h:49,
                 from /usr/include/qt5/QtConcurrent/qtconcurrentfilterkernel.h:47,
                 from /usr/include/qt5/QtConcurrent/qtconcurrentfilter.h:47,
                 from /usr/include/qt5/QtConcurrent/QtConcurrent:8,
                 from /usr/src/github/rpcs3/rpcs3/rpcs3qt/save_manager_dialog.cpp:12:
/usr/include/qt5/QtConcurrent/qtconcurrentthreadengine.h:250:50: error: invalid declarator before '*' token
  250 |     ThreadEngineStarter<void>(ThreadEngine<void> *_threadEngine)
      |                                                  ^
/usr/include/qt5/QtConcurrent/qtconcurrentthreadengine.h:250:49: error: expected ')' before '*' token
  250 |     ThreadEngineStarter<void>(ThreadEngine<void> *_threadEngine)
      |                              ~                  ^~
      |                                                 )
make[2]: *** [rpcs3/rpcs3qt/CMakeFiles/rpcs3_ui.dir/build.make:857: rpcs3/rpcs3qt/CMakeFiles/rpcs3_ui.dir/save_manager_dialog.cpp.o] Error 1
In file included from /usr/include/qt5/QtConcurrent/qtconcurrentiteratekernel.h:49,
                 from /usr/include/qt5/QtConcurrent/qtconcurrentfilterkernel.h:47,
                 from /usr/include/qt5/QtConcurrent/qtconcurrentfilter.h:47,
                 from /usr/include/qt5/QtConcurrent/QtConcurrent:8,
                 from /usr/src/github/rpcs3/rpcs3/rpcs3qt/trophy_manager_dialog.cpp:18:
/usr/include/qt5/QtConcurrent/qtconcurrentthreadengine.h:250:50: error: invalid declarator before '*' token
  250 |     ThreadEngineStarter<void>(ThreadEngine<void> *_threadEngine)
      |                                                  ^
/usr/include/qt5/QtConcurrent/qtconcurrentthreadengine.h:250:49: error: expected ')' before '*' token
  250 |     ThreadEngineStarter<void>(ThreadEngine<void> *_threadEngine)
      |                              ~                  ^~
      |                                                 )
make[2]: *** [rpcs3/rpcs3qt/CMakeFiles/rpcs3_ui.dir/build.make:969: rpcs3/rpcs3qt/CMakeFiles/rpcs3_ui.dir/trophy_manager_dialog.cpp.o] Error 1
In file included from /usr/include/qt5/QtConcurrent/qtconcurrentiteratekernel.h:49,
                 from /usr/include/qt5/QtConcurrent/qtconcurrentfilterkernel.h:47,
                 from /usr/include/qt5/QtConcurrent/qtconcurrentfilter.h:47,
                 from /usr/include/qt5/QtConcurrent/QtConcurrent:8,
                 from /usr/src/github/rpcs3/rpcs3/rpcs3qt/game_list_frame.cpp:33:
/usr/include/qt5/QtConcurrent/qtconcurrentthreadengine.h:250:50: error: invalid declarator before '*' token
  250 |     ThreadEngineStarter<void>(ThreadEngine<void> *_threadEngine)
      |                                                  ^
/usr/include/qt5/QtConcurrent/qtconcurrentthreadengine.h:250:49: error: expected ')' before '*' token
  250 |     ThreadEngineStarter<void>(ThreadEngine<void> *_threadEngine)
      |                              ~                  ^~
      |                                                 )
make[2]: *** [rpcs3/rpcs3qt/CMakeFiles/rpcs3_ui.dir/build.make:395: rpcs3/rpcs3qt/CMakeFiles/rpcs3_ui.dir/game_list_frame.cpp.o] Error 1
make[1]: *** [CMakeFiles/Makefile2:17950: rpcs3/rpcs3qt/CMakeFiles/rpcs3_ui.dir/all] Error 2
make: *** [Makefile:156: all] Error 2

```

**Comment by AniLeo** [comment] 2021-05-21 21:12
Duplicate of #10291

**Closed by AniLeo** 2021-05-21 21:12 UTC
