### ISSUE TITLE
The Guided Fate Paradox  Utilities\File.cpp:791 / Game freeze 

### ISSUE THREAD

**Issue by SakataGintokiYT** [RPCS3/rpcs3#1683] opened 2016-04-25 23:27 UTC
@Nekotekina 
@tambry 

{PPU[0x6d] Thread (fios mediathread 11) [0x0039cfc8]} class fmt::exception thrown: Win32 error: 998.
(in file C:\rpcs3\Utilities\File.cpp:791)

- Log : https://gist.github.com/SakataGintokiYT/bb5e9b09adb549e25676e7328d7a0664

##### Video : https://youtu.be/mIl-l6wpVl4

**Comment by tambry** [comment] 2016-04-26 04:42
Duplicate of #1466. Added The Guided Fate Paradox there.

**Closed by tambry** 2016-04-26 04:42 UTC
