### ISSUE TITLE
[Feature request] Toggle-able Pause Menu to Show Trophies/Options Like PCSX2

### ISSUE THREAD

**Issue by FOSSilizedDaemon** [RPCS3/rpcs3#13112] opened 2022-12-22 22:12 UTC
### Quick summary

In emulators like PCSX2 you can bind your controller's guide button so that when tapped it pauses the emulator and opens a pause menu with options to resume emulation, exit the game, look at the games trophies, etc. I think adding this feature would make gaming sessions with RPCS3 much more enjoy-able when trophy hunting.

### Details

Basically as described above. Allow the user to bind a hotkey, such as the guide or ps button on a controller, to pause the current emulation and show a "pause menu" with the following options:

1. Resume Game (resumes the current game being emulated)
2. Trophies (shows the current list of trophies for the current game like on a PS3)
3. Save & Exit
4. Exit Without Saving

Ideally this menu would be toggle-able with the respective hotkey. This feature is available in RetroArch and PCSX2 (however, PCSX2 does not make it toggle-able). I cannot figure out how to screenshot the menu from RetroArch or PCSX2, however [here](https://preview.redd.it/1ft8tbs9sy781.png?width=960&format=png&auto=webp&s=73f8489c23064eb8846a90953d179685aabd4c01) is an image of the RetroArch toggle-able pause menu, though it does not show the entire menu. Thank you for your time.

**Comment by Megamouse** [comment] 2022-12-22 22:26
Duplicate of #5444

**Closed by Megamouse** 2022-12-22 22:26 UTC
Labels: Overlay
