### ISSUE TITLE
[Regression] Silent Hill Downpour Flickering Issue

### ISSUE THREAD

**Issue by mrchrismania** [RPCS3/rpcs3#14830] opened 2023-11-18 21:39 UTC
### Quick summary

Silent Hill Downpour has a flickering problem i,e white flashes and pop ins. the trigger usually happens when your roaming around the Silent Hill City Town area and bringing up the Map/Inventory triggers it to start flashing. This issue doesn't happen on last years build version RPCS3 v0.0.20-13273-7895d43a Alpha.

but happens on that latest version RPCS3 v0.0.29-15724-ab8a12e2 Alpha
 

The only workaround that fixes this issue is enabling the Disable Vertex Cache option in Advanced Tab in the config menu

### Details

here is a short clip i made showcasing this bug

https://youtu.be/E0OUb8NAf6g

My Settings are 300% Resolution Scale and 512x512 Resolution Scale Threshold this is needed to fix the Red menu screen.
rest are default with Vblank set to 120% In Advanced Tab

### Build with regression

v0.0.29-15724-ab8a12e2

### Attach two log files

[RPCS3.log.gz](https://github.com/RPCS3/rpcs3/files/13401526/RPCS3.log.gz)

### System configuration

CPU: i9-10900k
GPU: EVGA RTX 3080
RAM: 32GB DDR4 3600mhz
NVME: Samsung 980 Pro 2TB
Operating System: Windows 11 Pro

### Other details

another issue ive noticed is when the end game credits roll and you press back it freezes.

**Comment by AniLeo** [comment] 2023-11-18 21:45
Invalid regression report, the two mentioned builds are more than 2000 commits apart and there's no evidence whatsoever that the regression was introduced in the blamed 15724 build. 

Need Information: Missing last good build and first broken build.

**Comment by mrchrismania** [comment] 2023-11-18 21:50
> Invalid regression report, the two mentioned builds are more than 2000 commits apart and there's no evidence whatsoever that the regression was introduced in the blamed 15724 build.
> 
> Need Information: Missing last good build and first broken build.

 v0.0.20-13273-7895d43a is a build from last year and works with no flickering issues. Its only the latest v0.0.29-15724-ab8a12e2 thats doing it and ive even went and reinstalled the latest build twice and redumped the game. The only setting that fixes the problem is the disable vertex cache option in advanced tab

**Comment by AniLeo** [comment] 2023-11-18 21:59
If the issue is only on 15724 then you need to test the unregressed behaviour on 15723 and provide the second log file from there, not some random ancient build

**Comment by mrchrismania** [comment] 2023-11-18 22:01
> If the issue is only on 15724 then you need to test the unregressed behaviour on 15723 and provide the second log file from there, not some random ancient build

Okay i understand my apologies i will go back and test out a previous build and let you know

**Comment by mrchrismania** [comment] 2023-11-18 23:12
> If the issue is only on 15724 then you need to test the unregressed behaviour on 15723 and provide the second log file from there, not some random ancient build

so far ive tested about 13 different RPCS3 going backwards even tried one from 29 days ago all of them had the flickering issue. It seems to be a Vertex Issue or atleast a Vertex Caching issue as Disabling the Vertex Cache stops the flickering entirely

**Comment by kd-11** [comment] 2023-11-23 11:20
Closing as fixed by config.

**Closed by kd-11** 2023-11-23 11:20 UTC
Labels: Need Information
