### ISSUE TITLE
Supersonic Acrobatic Rocket-Powered Battle Cars audio stutter. Build 6796 #4378

### ISSUE THREAD

**Issue by XASAZA7** [RPCS3/rpcs3#4619] opened 2018-05-19 21:48 UTC
As stated in the title, Supersonic Acrobatic Rocket-Powered Battle Cars has pretty much broken audio. Is it my PC, or just an emulator issue that still has to be fixed?
My specs
Windows 10 Pro x64
i5 6500 3.2 GHz
GTX 1060 3GB OC
HyperX Fury 1x8GB DDR4 2133MHz
RPCS3 0.0.5-6796

**Comment by AniLeo** [comment] 2018-05-19 21:54
Not a specific issue, it's caused by lower performance. The game is not Playable as per the compatibility list.

---

**Please read [**the guidelines**](https://github.com/RPCS3/rpcs3/blob/master/.github/CONTRIBUTING.md) before opening an issue.**

Remember that the GitHub Issue Tracker is not the place to ask for support or to submit Game Compatibility reports. You must use [**our forums**](https://forums.rpcs3.net/forum-18.html) for that.

The issue has been marked as **Invalid** and closed.

**Closed by AniLeo** 2018-05-19 21:54 UTC
