### ISSUE TITLE
RSX: Attempting to sample a currently bound depth surface (Tokyo Jungle)

### ISSUE THREAD

**Issue by EchoDev** [RPCS3/rpcs3#3406] opened 2017-09-07 19:13 UTC
[NPEA00275]Tokyo Jungle 

Video: https://vid.me/BIQPX

OpenGL makes the game flicker a lot, Vulkan seems to fix this but there is still a weird tearing issue on the right (and sometimes on the left). Outside of this issue the game seems to run fine in Vulkan, mostly 20-30fps. (Game is 30fps locked I think)

OS: Win 7 x64
CPU:  Intel i7 3770k 
GPU: nVidia GTX1070

[RPCS3.log.gz](https://github.com/RPCS3/rpcs3/files/1285849/RPCS3.log.gz)

**Comment by AniLeo** [comment] 2017-09-08 16:19
`{rsx::thread} RSX: Attempting to sample a currently bound depth surface @ 0xc0740000`
49k counts on that 175k lines log

**Comment by kd-11** [comment] 2017-09-08 17:00
That's not a real error on the emulator's part - its something unexpected that the game itself is doing (and shouldn't be doing, but games are written by human beings so these things happen). Strict rendering mode works around such issues. Flashing is caused by a completely different issue, which is the flip hack. It will be fixed when fbo_fixes is ready, but that will take some time.

**Closed by kd-11** 2017-09-08 17:00 UTC
Labels: Bug, RSX

**Comment by EchoDev** [comment] 2017-09-08 17:31
So I enabled strict rendering mode in OpenGL and it gives me about the same ish output. The right side doesn't tear like with Vulkan but flashes a black block now.

https://vid.me/io8T9

The log mentions this with OpenGL
`{rsx::thread} RSX: Overlapping surface exceeds bounds; returning full surface region`

[RPCS3.log.gz](https://github.com/RPCS3/rpcs3/files/1288646/RPCS3.log.gz)

[This youtube video](https://www.youtube.com/watch?v=AayeX7LX4IE) has Tokyo Jungle working without issues. I could try and find out which build did work properly with Tokyo Jungle and which one breaks it if you are interested @kd-11

**Comment by kd-11** [comment] 2017-09-08 19:12
Just wait for fbo_fixes. I know why it wasn't flashing in that video, its not a proper way of doing things and worked by chance.
