### ISSUE TITLE
[BLUS30377] Call of Duty Modern Warfare 2 - RSX: Unknown blend eq 0x0

### ISSUE THREAD

**Issue by dyno0** [RPCS3/rpcs3#7270] opened 2020-01-17 18:47 UTC
I was able to get through 4 missions, and in the 5th, Takedown, only when you rotate the camera towards the favela scenery the game crashes and pops:

```
{RSX [0x002f8cc]} RSX: class std::runtime_error thrown: Unknown blend eq 0x0
(in file C:\projects\rpcs3\rpcs3\Emu\RSX\gcm_enums.cpp:723)
```
[RPCS3.log.gz](https://github.com/RPCS3/rpcs3/files/4078378/RPCS3.log.gz)

**Comment by elad335** [comment] 2020-01-17 18:47
Duplicate of #6459

**Closed** 2020-01-17 18:50 UTC
