### ISSUE TITLE
Wipeout HD Fury: Working with Vulkan

### ISSUE THREAD

**Issue by SpeedouTM** [RPCS3/rpcs3#5737] opened 2019-03-18 23:24 UTC
Wipeout HD Fury (BCES00664) is working quite stable on Vulkan.

Little problems : 
- Textures take a bit too long to load
- Sound is glitchy

Except of this, the game is stable at : 
- ~60fps
- 1080p
- Resolution scale 200 %
- Anisotropic x16

My config : 
- Ryzen 7 1800x
- GTX 1060 (EXOC)
- 2x8 gb

**Comment by AniLeo** [comment] 2019-03-18 23:30
> Textures take a bit too long to load

This is a "non-issue", it's due to how recompiling shaders works, you'll always have to wait for those to be recompiled. Of course, there are things that can be done to improve on it like better predicting what the shaders will look like before they're recompiled, but the point is that that's working as designed.

--- 

Sound being glitchy is caused due to CPU issues usually, specially for people that can't maintain stable framerate. It's a general issue.

---

Game reports should be submitted on our forums instead:

Remember that the GitHub Issue Tracker is not the place to [**ask for support**](https://github.com/RPCS3/rpcs3/wiki/How-to-ask-for-Support) or to [**submit Game Compatibility reports**](https://github.com/RPCS3/rpcs3/wiki/Game-Compatibility).

The issue has been marked as **Invalid** and closed.

**Closed** 2019-03-18 23:30 UTC
