### ISSUE TITLE
ISSUE: Stuck on Setting up trophy information

### ISSUE THREAD

**Issue by markcagatandavis** [RPCS3/rpcs3#4684] opened 2018-06-01 16:16 UTC
Game: Odin Sphere Leifthrasir
Serial: BLUS31601
RPCS3 0.0.5-6882
Issue: Game hangs on Setting up trophy information

```
U {PPU[0x1000000] Thread (main_thread) [0x00722d00]} cellSysutil TODO: cellVideoOutConfigure(videoOut=0, config=*0xd00ff840, option=*0x0, waitForEvent=0)
U {PPU[0x1000000] Thread (main_thread) [0x00da4948]} cellSysutil TODO: cellVideoOutConfigure(videoOut=0, config=*0xd00ff600, option=*0x0, waitForEvent=0)
U {PPU[0x1000000] Thread (main_thread) [0x00d07d80]} sys_spu TODO: Unimplemented SPU Thread options (0x2) x5
E {PPU[0x1000000] Thread (main_thread) [0x00d07d84]} '_sys_spu_printf_attach_group' failed with 0x00000000 : 0 [1]
U {PPU[0x1000000] Thread (main_thread) [0x00d0de58]} sys_prx TODO: _sys_prx_get_module_id_by_name(name=“cellLibprof”, flags=0, pOpt=*0x0)
E {PPU[0x1000000] Thread (main_thread) [0x00d0de58]} 'sys_prx_get_module_id_by_name' failed with 0x8001112e : CELL_PRX_ERROR_UNKNOWN_MODULE [1]
S {PPU[0x1000000] Thread (main_thread) [0x00c600c4]} PPU: LLVM: Loaded module v2-libspurs_jq.sprx-356285E488E56CBE-haswell.obj
S {PPU[0x1000000] Thread (main_thread) [0x00c600c4]} sys_prx: Loaded module: /dev_flash/sys/external/libspurs_jq.sprx
U {PPU[0x1000000] Thread (main_thread) [0x00d60368]} sys_prx TODO: _sys_prx_get_module_id_by_name(name=“cellLibprof”, flags=0, pOpt=*0x0)
E {PPU[0x1000000] Thread (main_thread) [0x00d60368]} 'sys_prx_get_module_id_by_name' failed with 0x8001112e : CELL_PRX_ERROR_UNKNOWN_MODULE [2]
U {PPU[0x1000000] Thread (main_thread) [0x00d60368]} sys_prx TODO: _sys_prx_get_module_id_by_name(name=“cellLibprof”, flags=0, pOpt=*0x0)
E {PPU[0x1000000] Thread (main_thread) [0x00d60368]} 'sys_prx_get_module_id_by_name' failed with 0x8001112e : CELL_PRX_ERROR_UNKNOWN_MODULE [3]
U {PPU[0x1000000] Thread (main_thread) [0x00d65310]} sysPrxForUser TODO: sys_crash_dump_set_user_log_area(unk1=127, unk2=*0xd0100a50 “Log”, unk3=*0x208)
U {PPU[0x1000000] Thread (main_thread) [0x0071f1c8]} cellNetCtl TODO: cellNetCtlGetInfo(code=0x2 (INFO_ETHER_ADDR), info=*0x28b02908)
S {Audio Thread} XAudio 2.9 initialized
E {PPU[0x1000015] Thread (FiberFunc) [0x0072935c]} cellSaveData: cellSaveDataEnableOverlay(enable=1)
E {PPU[0x1000016] Thread (FiberFunc) [0x0072935c]} cellSaveData: cellSaveDataEnableOverlay(enable=1)
E {PPU[0x1000017] Thread (FiberFunc) [0x00720cb8]} sceNpTrophy: sceNpTrophyRegisterContext(context=0x1, handle=0x1, statusCb=*0xb39608, arg=*0x28b029ac, options=0x1)
E {PPU[0x1000018] Thread (FiberFunc) [0x0071f514]} sceNpTrophy: sceNpTrophyGetTrophyUnlockState(context=0x1, handle=0x1, flags=*0x28b029bc, count=*0x28b029cc)
```

**Comment by AniLeo** [comment] 2018-06-01 16:23
Duplicate of #3009

**Closed by AniLeo** 2018-06-01 16:23 UTC
