### ISSUE TITLE
SPU Interrupts not implemented issue over 10 games

### ISSUE THREAD

**Issue by uaqlover** [RPCS3/rpcs3#7095] opened 2019-12-15 02:11 UTC
sorry i don't want to make Duplicate issue 

but i was testing games over 10 game in intro because 

SPU Interrupts not implemented issue

https://github.com/RPCS3/rpcs3/issues/5591
https://github.com/RPCS3/rpcs3/pull/4845

i hope someone makes hotfix or fix the issue

**Comment by AniLeo** [comment] 2019-12-15 04:12
Duplicate of #5591

**Closed** 2019-12-15 04:12 UTC
