### ISSUE TITLE
Regression: Vulkan device creation fails

### ISSUE THREAD

**Issue by MSuih** [RPCS3/rpcs3#9827] opened 2021-02-23 08:58 UTC
When launching games, users are reporting this following error:

![unknown](https://user-images.githubusercontent.com/19759300/108821223-f25b2a00-75c5-11eb-82ed-5c4a5383a169.png)

It seems to be caused by #9825

**Comment by Nekotekina** [comment] 2021-02-23 13:18
Can someone test https://github.com/RPCS3/rpcs3/pull/9828 regarding this issue?

**Comment by MSuih** [comment] 2021-02-23 15:08
Unfortunately we're having really difficult time to find someone who can reproduce the issue and is willing to test things.

**Comment by MSuih** [comment] 2021-02-23 18:27
I got a report saying that it now causes vulkan-1,dll crash instead of verification failure. I guess we need to let kd address this.

**Comment by no1d** [comment] 2021-02-23 18:37
Latest build
![image](https://user-images.githubusercontent.com/11740438/108890848-1bf46f80-761f-11eb-93fe-7f4340bda606.png)
[RPCS3.log.zip](https://github.com/RPCS3/rpcs3/files/6031154/RPCS3.log.zip)

**Comment by Blakevlv** [comment] 2021-02-23 19:35
Same error no1d is having. Willing to try to reproduce the issue on another build.

![image](https://user-images.githubusercontent.com/41490380/108897311-d27a3500-75ca-11eb-8095-53207a99c05f.png)

[RPCS3.log](https://github.com/RPCS3/rpcs3/files/6031419/RPCS3.log)

**Comment by MSuih** [comment] 2021-02-23 19:37
You could check if #9834 fixes the issue. It should, since it's a revert, but it'd be nice if we had at least someone testing things before they get merged.

**Comment by MSuih** [comment] 2021-02-23 19:42
Alternatively, #9835 seems to try to properly address this.

**Comment by kd-11** [comment] 2021-02-23 19:50
This issue is caused by users with rather outdated GPUs that don't have an async compute queue, or at least one that also supports doing transfer operations. Should be fixed by https://github.com/RPCS3/rpcs3/pull/9835 which will pick a best-fit alternative if possible.

**Comment by Blakevlv** [comment] 2021-02-23 19:59
> This issue is caused by users with rather outdated GPUs that don't have an async compute queue, or at least one that also supports doing transfer operations. Should be fixed by #9835 which will pick a best-fit alternative if possible.

Makes sense as I have to use a Nvidia 660Ti until I can replace my dead GPU. Unfortunately I'm actually unable to test other builds because I can't install the necessary programs to build #9834 or #9835 right now, but as you said, the issue should be fixed already.

**Comment by kd-11** [comment] 2021-02-23 20:14
@Blakevlv Please test the PR build from [this URL](https://artprodsu6weu.artifacts.visualstudio.com/Ad52971ce-2651-462c-a71a-8019f393a0cf/3598951b-4d39-4fad-ad3b-ff2386a649de/_apis/artifact/cGlwZWxpbmVhcnRpZmFjdDovL25la290ZWtpbmEvcHJvamVjdElkLzM1OTg5NTFiLTRkMzktNGZhZC1hZDNiLWZmMjM4NmE2NDlkZS9idWlsZElkLzY1NTQvYXJ0aWZhY3ROYW1lL1JQQ1MzK2ZvcitXaW5kb3dz0/content?format=zip) so we can close this.

**Comment by Blakevlv** [comment] 2021-02-23 20:19
> @Blakevlv Please test the PR build from [this URL](https://artprodsu6weu.artifacts.visualstudio.com/Ad52971ce-2651-462c-a71a-8019f393a0cf/3598951b-4d39-4fad-ad3b-ff2386a649de/_apis/artifact/cGlwZWxpbmVhcnRpZmFjdDovL25la290ZWtpbmEvcHJvamVjdElkLzM1OTg5NTFiLTRkMzktNGZhZC1hZDNiLWZmMjM4NmE2NDlkZS9idWlsZElkLzY1NTQvYXJ0aWZhY3ROYW1lL1JQQ1MzK2ZvcitXaW5kb3dz0/content?format=zip) so we can close this.

Same game I was testing on before is now fully working with no other issues.

**Comment by kd-11** [comment] 2021-02-23 20:23
Thanks for testing. Closed as fixed.

**Closed** 2021-02-23 20:22 UTC
Labels: RSX, Regression, Render: Vulkan
