### ISSUE TITLE
SPU : Interpreter fast/precise is a lot faster than ASMJIT

### ISSUE THREAD

**Issue by raven02** [RPCS3/rpcs3#3678] opened 2017-10-29 05:26 UTC
Dynasty Warrior Gundam 3 

- ASMJIT (12FPS)
![asmjit](https://user-images.githubusercontent.com/3000282/32140926-c426e50a-bcac-11e7-8d2d-c956918531c6.jpg)

- Interpreter Fast (47FPS)
![intre](https://user-images.githubusercontent.com/3000282/32140925-c1e0be4c-bcac-11e7-84d7-83c8da348085.jpg)

**Comment by raven02** [comment] 2018-04-02 07:13
Just checked latest build , still happened that Interpreter Fast is much faster than ASMJIT

**Comment by sheddup** [comment] 2018-04-06 06:59
If you go in game you'll see its not faster

**Comment by scribam** [comment] 2018-04-25 20:36
@raven02 Fixed by #4422?

**Comment by AniLeo** [comment] 2018-05-20 19:26
Retest

**Comment by raven02** [comment] 2018-08-19 14:06
Tested with latest build and issue still remains

**Comment by elad335** [comment] 2019-01-31 16:06
Still an issue?

**Comment by creeperjedi** [comment] 2019-01-31 22:31
Though the first boot of the game is slower, subsequent boots have performance that is equivalent or superior to that of the fast/precise interpreters (The performance boots seems to come when the SPU cache reaches a certain size). Though using ASMJIT will cause the game to crash within a minute or two with a "JIT: Out of memory" error.

**Comment by AniLeo** [comment] 2019-05-02 14:31
Needs retesting

**Comment by creeperjedi** [comment] 2019-05-10 01:58
The fast/precise interpreters are still faster than ASMJIT with LLVM only displaying a black screen.

**Comment by Emulator-Team-2** [comment] 2019-06-16 09:59
@raven02 
@creeperjedi 
Can you retest with the latest master?

**Comment by creeperjedi** [comment] 2019-06-29 05:13
Retested with master (RPCS3 v0.0.6-8313) and ASMJIT, as well as LLVM, have seen massive performance increases. Both hold a constant 60 fps, with occasional dips to 40-30 fps during explosions. 

Fast causes the game to run between 55-35 fps depending on the area, with a drop down to 25-20 fps once enemies appear.

Precise is insanely slow with around 20 fps and drops down to 5 once enemies appear.

All of these cause the game to freeze before I could finish the first mission with the exception of Precise, though this was likely due to the fact that I played with it for less than a minute due to its performance.

I believe that this issue can be closed but if someone such as @raven02 could confirm my findings, then that would be superb.

**Comment by AniLeo** [comment] 2019-07-12 18:29
Closing as fixed as reported above

If you can still reproduce this somehow, it can be reopened

**Closed by AniLeo** 2019-07-12 18:29 UTC
Labels: CPU, Need Information
