### ISSUE TITLE
Ratchet & Clank 3 slowdown after a bit of full-speed gameplay

### ISSUE THREAD

**Issue by VelocityRa** [RPCS3/rpcs3#10235] opened 2021-05-03 03:32 UTC
## Quick summary
- Ratchet & Clank 3 runs at 60 in the beginning, but after ~10 mins of gameplay (always in a a specific area) framerate & game speed (it's tied to fps) drops to half.
- Slowdown seems to depend on % of resolution upscaling but not sure.
- Host GPU Usage in Task Manager is at 100%.
- If I die there & respawn to the earlier point in the level, it jumps to 60 again. 

#### 1. Please attach RPCS3's log.
[RPCS3.log.gz](https://github.com/RPCS3/rpcs3/files/6412745/RPCS3.log.gz)

#### 3. Please attach screenshots of your problem.

![image](https://user-images.githubusercontent.com/6632271/116838536-6114bf00-abd7-11eb-92b8-72be4a434b7b.png)

Left at starting area, right as it's slowing down.

Draw call setup jumps to 42ms.

#### 5. Please provide your system configuration:
* OS: Windows 10
* CPU: Ryzen 7 3700X
* GPU: **GTX 970**
* Driver version: 465.89.0.0

#### Anything else you deem to be important
Tested a build from 9 months ago, same issue.

Let me know if I can help debug or fix this.

**Comment by Yahfz** [comment] 2021-05-03 18:37
This is an issue caused by the high texture uploads. This issue is a duplicate of #8294

**Comment by Yahfz** [comment] 2021-05-03 18:42
Actually i'm blind, i totally read drawcall setup as texture upload, reopening

**Comment by kd-11** [comment] 2021-05-04 21:18
Yea, this is a side-effect of how this engine places things in RSX memory. I'll add to my list.

**Comment by kd-11** [comment] 2021-07-27 11:04
Time for a retest. I don't expect the issue is fully fixed, but maybe it can have improved to some extent.

**Comment by marcoluc97** [comment] 2022-01-01 22:51
@VelocityRa still happening?

**Comment by kd-11** [comment] 2022-09-26 23:00
Closing due to inactivity.
From what I can tell, it may have been caused by our fledgling memory manager at the time. The number of unreleased textures goes up, framerate tanks. In fact we were losing track of texture cache resources often and leaking VRAM over time. We have a much more advanced system now, so this shouldn't happen anymore.

**Closed by kd-11** 2022-09-26 23:00 UTC
