### ISSUE TITLE
Prototype [BLES00269] unknown/illegal offset (0x322c) & crashes RPCS3

### ISSUE THREAD

**Issue by darkredflame** [RPCS3/rpcs3#2581] opened 2017-03-24 09:02 UTC
Prototype seems to have triggered something in one of the newer builds, it now crashes the emulator instead of giving the [following error message.](http://www.emunewz.net/forum/showthread.php?tid=179600)

`·F 0:00:03.707161 {PPU[0x1000000] Thread (main_thread) [0x00ace52c]} struct vm::access_violation thrown: Access violation reading address 0xe004322c`

The game now shows this in the log, I also pasted a screenshot of the error message RPCS3 shows below.

`·E 0:00:08.649379 {PPU[0x1000000] Thread (main_thread) [0x00ace52c]} SPU: RawSPUThread[0]: Read32(0xe004322c): unknown/illegal offset (0x322c)`

[RPCS3.zip](https://github.com/RPCS3/rpcs3/files/867327/RPCS3.zip)
![rpcs3-rsx_2017-03-22_18-23-55](https://cloud.githubusercontent.com/assets/12888227/24287203/575c90ac-103e-11e7-820f-c7d6fc4facf4.png)

**Comment by SakataGintokiYT** [comment] 2017-09-01 21:37
@darkredflame 
retry with latest master.

**Comment by SakataGintokiYT** [comment] 2017-09-04 15:32
@AniLeo 
https://forums.rpcs3.net/thread-196895.html

**Comment by AniLeo** [comment] 2017-09-04 16:47
Yeah, now the issue is with SPU Interrupt Threads
This one is fixed though, so closing

**Closed by AniLeo** 2017-09-04 16:47 UTC
Labels: Bug, CPU
