### ISSUE TITLE
Illegal instruction on older CPUs

### ISSUE THREAD

**Issue by aakh1361** [RPCS3/rpcs3#8085] opened 2020-04-23 01:12 UTC
hi

after this build every build show me error ppu compile in LLVM

last good ppu compile
rpcs3-v0.0.9-**10202**-adfc9d93_win64 

![image](https://user-images.githubusercontent.com/25039098/80047783-9b0ea800-8523-11ea-9de8-7cca017ece49.png)
[RPCS3.log.gz](https://github.com/RPCS3/rpcs3/files/4519670/RPCS3.log.gz)

of rpcs3-v0.0.9-**10215**-074b9f94_win64 -- rpcs3-v0.0.9-**10256**-18219afb_win64 crash for me 
all builds was crash in ppu compile for me in PPU LLVM

interpreter precise and fast is good only PPU LLVM is crash

last build
[RPCS3.zip](https://github.com/RPCS3/rpcs3/files/4519636/RPCS3.zip)

![image](https://user-images.githubusercontent.com/25039098/80048310-115fda00-8525-11ea-9436-e1bb6af1d42b.png)

maybe relate to this
https://github.com/RPCS3/rpcs3/pull/8023

**Comment by RainbowCookie32** [comment] 2020-04-23 01:48
Can't reproduce here. 
Tried a clean install of master (0.0.9-10256 currently) and the firmware and its modules were installed and compiled properly. For good measure I ran a game and it also compiled its modules and booted just fine.
[RPCS3.log.gz](https://github.com/RPCS3/rpcs3/files/4519789/RPCS3.log.gz)

**Comment by aakh1361** [comment] 2020-04-23 06:04
i do clean install three version in three Different folder on Desktop Now again

rpcs3-v0.0.9-10202-adfc9d93_win64
No Problem

rpcs3-v0.0.9-10215-074b9f94_win64 
PPU Compile Crash

rpcs3-v0.0.9-10256-18219afb_win64
PPU Compile Crash

I download more ten version different
rpcs3-v0.0.9-10202 and older no probelm and everything fine

but
rpcs3-v0.0.9-10215 and every build after this version is crash on PPU LLVM for me

i know this is relate to RPCS3 no my setting

**Comment by Nerboruto** [comment] 2020-04-25 14:07
I confirm everything !!! same problem on my old pc core duo...
after cleaning cache folder... if you don't clean it, the problem doesn't show up...
latest build that works is rpcs3-v0.0.9-10202..
any other build from v0.0.9-10206-4d8bfe32 crash with:
Unhandled Win32 exception 0xC000001D.
Exception address: 0000000000a57089.
Emu Thread Name: 'PPUW.1.2'.
Thread id = 3360.
Instruction address: 0000000000a57089.
Function address: 0000000000a57040 (base+0xa47040).
Module name: 'rpcs3.exe'.
Module base: 0000000000010000.
RPCS3 image base: 0000000000010000.

·F 0:00:04.974574 {PPUW.1.1} SYS: 
Unhandled Win32 exception 0xC000001D.
Exception address: 0000000000a57089.
Emu Thread Name: 'PPUW.1.1'.
Thread id = 1616.
Instruction address: 0000000000a57089.
Function address: 0000000000a57040 (base+0xa47040).
Module name: 'rpcs3.exe'.
Module base: 0000000000010000.
RPCS3 image base: 0000000000010000.

[log.zip](https://github.com/RPCS3/rpcs3/files/4533090/log.zip)

**Comment by AniLeo** [comment] 2020-04-25 14:09
Illegal instruction on older CPUs

**Comment by Nekotekina** [comment] 2020-04-25 18:14
Should be fixed

**Comment by Nerboruto** [comment] 2020-04-25 19:19
it's ok.. doesn't crash for me...

**Closed** 2020-04-25 20:50 UTC
Labels: Bug, CPU

**Comment by aakh1361** [comment] 2020-04-26 05:15
fix for me too
