### ISSUE TITLE
Persona 4 Arena Ultimax setup?

### ISSUE THREAD

**Issue by Noochester** [RPCS3/rpcs3#2242] opened 2016-12-18 01:25 UTC
So I just downloaded P4AU and I can't find anywhere what LLE's I need for it. When I tried to launch it with Marvel's it said Access violation reading address 0x0

log: http://pastebin.com/TkuDDfU5

Marvel's LLE:

libatxdec
libfiber
libl10n
libpamf
libresc
librt
libsail
libsail_avi
libspurs_jq
libsre

**Comment by ssshadowww** [comment] 2016-12-18 11:22
This is not a bug report, please read [this](http://www.emunewz.net/forum/showthread.php?tid=174352) and [this](http://www.emunewz.net/forum/showthread.php?tid=171465) and close the issue.

tl;dr no real game that you want to play works at all.

**Closed** 2016-12-18 15:07 UTC
