### ISSUE TITLE
[Regression] All Pro Football 2k8 - flimmering on helmets + pixelated banners (#13236)

### ISSUE THREAD

**Issue by Dude85** [RPCS3/rpcs3#13253] opened 2023-01-18 11:10 UTC
### Quick summary

Game worked fine with build rpcs3-v0.0.26-14568-1852b370. Latest updates show graphical glitches (flimmering on helmets + pixelated banners)

### Build with regression

v0.0.26-14570

### Attach two log files

[RPCS3.log.gz](https://github.com/RPCS3/rpcs3/files/10445221/RPCS3.log.gz)
[RPCS3.log.gz](https://github.com/RPCS3/rpcs3/files/10445233/RPCS3.log.gz)

### Attach capture files for visual issues

![Screenshot 2023-01-18 120642](https://user-images.githubusercontent.com/25846541/213156646-0c0d934f-f4a9-421c-99aa-2ad73c49645b.jpg)

**Comment by mysteria25** [comment] 2023-01-19 00:19
Your log says you have WCB and CPU blit enabled.  Why have them enabled?  afaik, this game doesnt need those On.  does it fix it if you disable those options?

**Comment by Dude85** [comment] 2023-01-19 07:03
You need both. Either if one is turned off or both, 3D animations in the menus are gone. It`s a common behavior which is well described in several forums or on Reddit.

**Comment by Dude85** [comment] 2023-01-19 16:31
Did some more testing. Without both options, the graphical glitches described are gone, but as mentioned the 3D anim
![WCB and CPU blit activated latest build 1](https://user-images.githubusercontent.com/25846541/213498921-23e4adb3-83be-4344-805b-4d1d5b9c9d0a.jpg)
![WCB and CPU blit activated latest build 2](https://user-images.githubusercontent.com/25846541/213498925-f3be9a16-b924-48c7-893b-e33172f29dcf.jpg)
![WCB and CPU blit deactivated](https://user-images.githubusercontent.com/25846541/213498929-347e8a76-c9ce-4deb-979f-5904f8c35b61.jpg)
ations are missing and ther're glitches in the menu.

**Comment by Dude85** [comment] 2023-01-19 19:28
All versions tested with same custom config (CPU blit ON & WBC ON):

0.0.26-14542: OK
0.0.26-14564: OK
0.0.26-14568: OK
0.0.26-14573: NOK
0.0.26-14577: NOK
0.0.26-14580: NOK
0.0.26-14584: NOK

**Comment by YuriNator557** [comment] 2023-01-19 19:30
14573 is PR #13232 , not sure how that could break it

**Comment by Darkhost1999** [comment] 2023-01-19 19:34
There is still a range greater than 1 PR of builds that could be causing the issue. They just need to bisect a little more

**Comment by Dude85** [comment] 2023-01-19 20:40
0.0.26-14569: OK
**0.0.26-14570: NOK**

**Comment by Asinin3** [comment] 2023-01-20 08:21
If that's the case then it was broken by https://github.com/RPCS3/rpcs3/pull/13236

**Comment by kd-11** [comment] 2023-01-23 00:19
The regression is simply an unhidden bug. We're missing a signal elsewhere and letting through some updates incorrectly triggers the right behavior. I'm still investigating.

**Comment by Dude85** [comment] 2023-01-23 19:24
Thanks for your feedback and checking this issue. Fingers crossed that you find a solution quickly.

**Comment by kd-11** [comment] 2023-01-25 20:32
No luck so far. The problem is caused by the interaction between CPU blit and write color buffers, but it seems to be timing dependent and not consistent. Injecting random calls to memory protection hides the bug, which is why the old code that spammed surface dirty was working, but it was completely wrong to do that. The biggest issue here is that the affected resources are only created once during loading and then remain so you cannot debug traditionally.
I'll have to circle back to this one at a later time.

**Comment by Dude85** [comment] 2023-01-26 15:53
Damn, that doesn't sound so easy. Thanks for the feedback and good luck finding this bug, even if it needs some more time to be spend on!

**Comment by Imdakine1** [comment] 2023-03-17 07:21
Ongoing inconsistent graphical glitch. ![image](https://user-images.githubusercontent.com/120328140/225838828-8790e847-2edc-4bbb-a613-5cc3ce13b7c1.jpeg)

**Comment by kd-11** [comment] 2024-08-12 23:58
I checked this one earlier today. The glitches are gone, but it was crashing when CPU blit is enabled. That crash is fixed by https://github.com/RPCS3/rpcs3/pull/15931

**Closed** 2024-08-13 16:23 UTC
Labels: RSX, Regression
