### ISSUE TITLE
NVidia card not found only when attempting to use vulkan rendering system

### ISSUE THREAD

**Issue by chuggafan** [RPCS3/rpcs3#4055] opened 2018-01-14 03:08 UTC
Issue: RCPS3 no longer can find my graphics card as a valid vulkan GPU
Version: 0064976c43250ea89a407225813a6f760894c7f5 (0.0.4 ALPHA release)
OS: Windows with Intel(R) Core(TM) i7-7700HQ CPU @ 2.80GHz | 8 Threads | 15.89 GiB RAM | AVX+ and a NVIDIA GTX 1050 (specific amazon for more specs if nessecary: https://www.amazon.com/Strix-GL503VS-Gaming-Laptop-G-SYNC/dp/B0753MSN75?th=1)
I have no idea this has happened, but it currently can only find the Intel HD graphics device specifically for vulkan, but it can find both for D3D12, as you can see here https://imgur.com/1qAODdK (sorry for all the whitespace, I literally made this in paint)

I literally have no idea how someone would go about reproducing this. Before anyone asks aswell: I have already updated my drivers, I have reinstalled my drivers, I have restarted my computer (3 times), I have uninstalled, restarted my computer, then reinstalled my drivers, and vulkaninfo outputs for the 1.0.65 version of vulkan the NVIDIA GPU.

I do not know when this started exactly, but I am going to assume since between I last played and now there was a driver update that the root cause is using the latest drivers rather than the previous drivers for NVIDIA (390.65 is what I have and am currently using), if you want me to go back 2 versions and test again I can.

Thank you for your time

**Comment by AniLeo** [comment] 2018-01-14 03:13
Not our bug, duplicate of #4036 
Will be fixed by #4053 , but what makes it be undetected right now is a driver problem

**Closed by AniLeo** 2018-01-14 03:13 UTC
Labels: Meta: Duplicate

**Comment by chuggafan** [comment] 2018-01-14 03:15
Thank you for the fast response, I didn't see that issue

**Comment by cybertronicgames** [comment] 2018-01-14 14:54
@chuggafan Roll back Nvidia driver to version 388.71 & it will back fixed.

**Comment by chuggafan** [comment] 2018-01-15 02:25
I just added nv-vk64.json to my DWORD keylist and it worked

**Comment by gamergamer75** [comment] 2019-04-19 15:52
uhhh i have the same issue but not smart enough to understand what you guys were saying, do i need to update my gpu drivers?

pc specs:
windows10 x64bit-i7 8550u, gtx 1050, 8gb RAM
