### ISSUE TITLE
Vulkan : Not resize window in newest build

### ISSUE THREAD

**Issue by zminhquanz** [RPCS3/rpcs3#1799] opened 2016-06-19 04:33 UTC
![image](https://cloud.githubusercontent.com/assets/11285640/16175287/2b94ef8a-3611-11e6-9579-98b001760270.png)

It haven't fix yet on Vulkan #1787
Spec : Core 2 Quad Q6600
Graphic : NVIDIA GT 730 GDDR5 Kepler
my log : https://gist.github.com/zminhquanz/7a5834a56f7518785eaf8b5caa456d4e

**Comment by raven02** [comment] 2016-06-19 04:58
Duplicate of https://github.com/RPCS3/rpcs3/issues/1655

**Closed by raven02** 2016-06-19 04:58 UTC
