### ISSUE TITLE
Vulkan renders with very low brightness - 電撃文庫 FIGHTING CLIMAX IGNITION [NPJ00785]

### ISSUE THREAD

**Issue by SonicMastr** [RPCS3/rpcs3#7636] opened 2020-02-29 09:32 UTC
Playing "Dengeki Bunko: Fighting Climax Ignition" using the Vulkan Renderer actually renders everything seemingly perfectly, with the only downside being that the entire game's brightness is extremely low. I've tried this with and without Resolution Scale, and as many combinations of the additional settings as I could to no avail.
![g4j4xx4aFf190281803292020192010801237](https://user-images.githubusercontent.com/40341589/75604858-c4223780-5aa2-11ea-9537-cd7d7435e2d8.jpg)
![weLiBsG7Zo956311703292020192010801236](https://user-images.githubusercontent.com/40341589/75604860-c4223780-5aa2-11ea-89db-a0219e234d5b.jpg)
![ivfwI24fWx587511603292020192010801235](https://user-images.githubusercontent.com/40341589/75604861-c4bace00-5aa2-11ea-8b72-eeff09ff915f.jpg)

Ryzen 2700X
XFX RX 5700XT THICC II - Radeon 20.2.2 drivers (Happened on 20.2.1 as well)
16GB DDR4 3200Mhz

Tested on RPCS3 v0.0.8-9761-cb047fcc Alpha

[RPCS3.log](https://github.com/RPCS3/rpcs3/files/4270126/RPCS3.log)

**Comment by digitaldude555** [comment] 2020-02-29 10:15
![Screenshot (1264)](https://user-images.githubusercontent.com/26138653/75605609-f193d300-5aec-11ea-8822-627d19229ea8.png)
No issue here might be AMD gpu issue.

**Comment by kd-11** [comment] 2020-02-29 10:36
Or RX5700 problems. MSAA is set to 'Auto' which is known to break vulkan on RDNA. I'd try with that disabled first.

**Comment by SonicMastr** [comment] 2020-02-29 18:49
> Or RX5700 problems. MSAA is set to 'Auto' which is known to break vulkan on RDNA. I'd try with that disabled first.

Disabled Anti-Aliasing and that fixed the problem. Just another AMD bug.

![pYrCIOq41736949471229202012827521240](https://user-images.githubusercontent.com/40341589/75613310-b7790000-5af1-11ea-8346-955cefc21887.jpg)

**Comment by kd-11** [comment] 2020-03-01 06:11
I think we can close as duplicate of https://github.com/RPCS3/rpcs3/issues/6999

**Closed by kd-11** 2020-03-01 06:11 UTC
Labels: Driver: AMD, Render: Vulkan
