### ISSUE TITLE
It is recommended to add multi language selection

### ISSUE THREAD

**Issue by xiaolang0668** [RPCS3/rpcs3#12952] opened 2022-11-14 12:10 UTC
### Quick summary

![english](https://user-images.githubusercontent.com/74450832/201655468-19c25ae9-f0b8-44c3-8501-bd61350d2a26.jpg)
![Chinese](https://user-images.githubusercontent.com/74450832/201655735-976b659a-cabf-4e3e-a1e3-3ea6f4b8400d.jpg)
As shown in the figure above.
Want to add multi language selection.

### Details

![Multilingual](https://user-images.githubusercontent.com/74450832/201656531-97516f1e-9b5f-4877-979e-e3dd7a27dc8b.jpg)
It is suggested to add more national languages here, so that more people will like your works.

**Comment by MSuih** [comment] 2022-11-14 12:37
Duplicate of #4259

**Closed by MSuih** 2022-11-14 12:37 UTC
