### ISSUE TITLE
[BUG, POSSIBLE REGRESSION] Dante's Inferno™ [BLES00713] - Game-Breaking Bug, Game Freeze on Bridge

### ISSUE THREAD

**Issue by jjw410** [RPCS3/rpcs3#9112] opened 2020-10-21 23:20 UTC
## Quick summary
A very elusive, but consistent game-breaking bug that has been in the game for what looks to be a long time, the game will lock up on a particular bridge. Depending on the build used the game may freeze instantly, after a few deaths, or even a little earlier. Logs show no noticeable errors and other RPCS3 staff have been unable to find anything.

## Details
There's a point at the end of the Shores of Acheron, just after you rip the head off of Mr Boaty McBoatface, where you climb up the side of a falling cliff on the back of an enemy. Once you get to the top, the bridge you're standing on will begin to fall. At this point the game freezes. I've attached a picture of where this happens, sometimes it'll happen a little bit later or earlier but the picture shows the most common spot. Unfortunately, this is about 10 minutes after a save point, so testing different builds for a possible regression took HOURS.

Because some builds will not lockup sometimes until after 5+ deaths, I thought I'd found a good build. Retried it, got to the same area and it crashed instantly, so it's very confusing. And even more annoyingly, once you go back to build about 10720, current save files are no longer detected. To be clear, the game will lock up, the audio will still play normally, but performance overlays will freeze and the emulator needs to be restarted.

#### RPCS3 Log:
There are no "good" logs but here are 4 of 15+ logs from the builds I tested.

[10725_bad.log.gz](https://github.com/RPCS3/rpcs3/files/5419095/10725_bad.log.gz)
[10815_bad.log.gz](https://github.com/RPCS3/rpcs3/files/5419096/10815_bad.log.gz)
[10816_bad.log.gz](https://github.com/RPCS3/rpcs3/files/5419097/10816_bad.log.gz)
[10821_bad.log.gz](https://github.com/RPCS3/rpcs3/files/5419098/10821_bad.log.gz)

#### Screenshot:
Location of the crash, while it can happen a little earlier than this, the pictured moment is the most common location in which the game will lockup.

![PotPlayerMini64_WRnPNytNpD](https://user-images.githubusercontent.com/44265824/96799531-3dd4b000-13fb-11eb-9518-ebc7cfaf8866.jpg)

#### System Config:
* OS - Microsoft Windows 10 Pro
* MOBO - ASRock B450 Steel Legend
* CPU - AMD Ryzen 5 3600 6-Core Processor
* GPU - Geforce GTX 970
* Driver version - 456.38

#### Extra Notes
After posting on the official forum a user popped up to say they had experienced the same issue months back. And that they'd made this video to get past it:

https://youtu.be/XFCJxAzE3Uc 

It has pretty random settings and a weird 2nd condition where you have to defeat enemies in a specific order. It doesn't affect things in a consistent manner so I'm assuming the person using it just got lucky and attributed it to his odd settings. This appears to be something that's been around for a while but no one's brought to the team's attention.

**Comment by bevanweiss** [comment] 2020-10-23 07:03
You'll probably need to provide a game save for the nearest point to the crash, and as precise as possible instructions for how to reproduce.

**Comment by jjw410** [comment] 2020-10-23 11:59
> You'll probably need to provide a game save for the nearest point to the crash, and as precise as possible instructions for how to reproduce.

You're right, I have to pop away for the afternoon but I will return later with a good explanation video and the saves!

**Comment by jjw410** [comment] 2020-10-24 14:01
Made a short little explanatory video and have attached the save file :)

**SAVE:** [BLES00713_Dantes_Inferno.zip](https://github.com/RPCS3/rpcs3/files/5431414/BLES00713_Dantes_Inferno.zip)
**VIDEO:** https://youtu.be/KRdVsy7-PiM

**Comment by hell1233** [comment] 2020-10-28 07:45
Hi guys, I decided to go through dante inferno, and faced with the fact that the game hangs on a crumbling bridge every time that I can not reach the checkpoint, you do not accidentally have a solution to my problem, or could you share the preserves right after this bridge?

**Comment by hell1233** [comment] 2020-10-28 07:47
> Сделал небольшое пояснительное видео и прикрепил файл сохранения :)
> 
> **СОХРАНИТЬ: ** [BLES00713_Dantes_Inferno.zip ](https://github.com/RPCS3/rpcs3/files/5431414/BLES00713_Dantes_Inferno.zip)
> **ВИДЕО: ** https://youtu.be/KRdVsy7-PiM



> Вероятно, вам потребуется сохранить игру для ближайшей точки сбоя и как можно более точные инструкции по воспроизведению.

Hi guys, I decided to go through dante inferno, and faced with the fact that the game hangs on a crumbling bridge every time that I can not reach the checkpoint, you do not accidentally have a solution to my problem, or could you share the preserves right after this bridge?

**Comment by hell1233** [comment] 2020-10-28 07:48
> Made a short little explanatory video and have attached the save file :)
> 
> **SAVE:** [BLES00713_Dantes_Inferno.zip](https://github.com/RPCS3/rpcs3/files/5431414/BLES00713_Dantes_Inferno.zip)
> **VIDEO:** https://youtu.be/KRdVsy7-PiM



> You'll probably need to provide a game save for the nearest point to the crash, and as precise as possible instructions for how to reproduce.

Hi guys, I decided to go through dante inferno, and faced with the fact that the game hangs on a crumbling bridge every time that I can not reach the checkpoint, you do not accidentally have a solution to my problem, or could you share the preserves right after this bridge?

**Comment by hell1233** [comment] 2020-10-29 09:17
I solved the problem from 1 time by doing as in the video there is no thanks :)
[https://www.youtube.com/watch?v=XFCJxAzE3Uc](url)

**Comment by jjw410** [comment] 2020-10-30 16:03
Okay, I think what @hell1233 is trying to say is that they're having trouble too. Also lol, that youtube link redirects to an empty Github page.

**Comment by hell1233** [comment] 2020-10-30 16:48
> Okay, I think what @hell1233 is trying to say is that they're having trouble too. Also lol, that youtube link redirects to an empty Github page.

https://www.youtube.com/watch?v=XFCJxAzE3Uc

**Comment by jjw410** [comment] 2020-10-30 21:21
I already mentioned that video in the original video at the top of the page. It's luck whether not it'll happen in some cases, I doubt any of the steps in that video made an actual impact. The original uploader even said it doesn't work for lots of other people.

**Comment by hell1233** [comment] 2020-10-30 22:44
> I already mentioned that video in the original video at the top of the page. It's luck whether not it'll happen in some cases, I doubt any of the steps in that video made an actual impact. The original uploader even said it doesn't work for lots of other people.



I did not see the same video, I made the settings as in that video, I did everything and everything worked. The truth is not for long: D the game constantly sags every now and then, in different places. Configuration r5 2600 + 1060-6, + 8 ram + ssd: D but I learned how to deal with this by the example of video without showers)))))

**Comment by digitaldude555** [comment] 2021-02-07 13:33
This is a duplicate of #8495

**Closed** 2021-02-07 13:33 UTC

**Comment by JinChaoloveJESUS** [comment] 2021-02-12 11:46
> > 制作了一段简短的说明性视频，并随附了保存文件:)
> > **保存：** [BLES00713_Dantes_Inferno.zip](https://github.com/RPCS3/rpcs3/files/5431414/BLES00713_Dantes_Inferno.zip)
> > **视频：** [https ](https://youtu.be/KRdVsy7-PiM)**: **[//youtu.be/KRdVsy7-PiM](https://github.com/RPCS3/rpcs3/files/5431414/BLES00713_Dantes_Inferno.zip)[](https://youtu.be/KRdVsy7-PiM)
> 
> > 您可能需要为距崩溃最近的位置提供游戏保存，并尽可能精确地说明如何重现。
> 
> 嗨，大家好，我决定经过dante inferno，然后面对这样一个事实，即每次我无法到达检查站时，游戏都会挂在摇摇欲坠的桥上，您不会偶然地解决我的问题，或者可以分享一下保留在这座桥之后吗？

here you are
[PS3但丁的地狱存档.zip](https://github.com/RPCS3/rpcs3/files/5971505/PS3.zip)

**Comment by snowboundmage2** [comment] 2021-06-01 18:36
this is still a thing, posted an update #8495
