### ISSUE TITLE
[NPJB00135] Biohazard Code: Veronica - Textures missing or displayed incorrectly

### ISSUE THREAD

**Issue by kapdap** [RPCS3/rpcs3#9422] opened 2020-12-13 01:23 UTC
## Details
Textures are either missing or not displaying correctly (eg. flickering).

#### Please provide _exact_ build (or commit) information that introduced the regression you're reporting.
Regression happened since commit #9377 build 0.0.13-11347.

#### Please attach TWO logs:
[0.0.13-11347](https://github.com/RPCS3/rpcs3/files/5684027/RPCS3.log.gz) (Regression)
[0.0.13-11346](https://github.com/RPCS3/rpcs3/files/5684026/RPCS3.log.gz) (Working)

#### Please attach screenshots of your problem.
Regression
![0.0.13-11347](https://user-images.githubusercontent.com/30880441/102000612-20aec480-3d4e-11eb-9de1-42b0361a9321.png)

Working
![0.0.13-11346](https://user-images.githubusercontent.com/30880441/102000615-260c0f00-3d4e-11eb-893a-4dee088deab3.png)

#### Please provide your system configuration:
* OS: Windows 10
* CPU: Intel(R) Core(TM) i7-4870HQ CPU @ 2.50GHz
* GPU: GeForce GTX 970M
* Driver: 460.79

**Comment by kd-11** [comment] 2020-12-13 11:59
Duplicate of https://github.com/RPCS3/rpcs3/issues/9422

**Closed by kd-11** 2020-12-13 11:59 UTC
