### ISSUE TITLE
HLE: Unknown/illegal channel in Sly games

### ISSUE THREAD

**Issue by MarioSonic2987** [RPCS3/rpcs3#1943] opened 2016-07-19 06:53 UTC
{SPU[0x2b] Thread (ApeCoreCellSpursKernel0) [0x02bbc]} class fmt::exception thrown: SPUThread::set_ch_value(): Unknown/illegal channel (ch=1 [$SPU_WrEventMask], value=0x2)
	(in file C:\rpcs3\rpcs3\Emu\Cell\SPUThread.cpp:1125) - Sly 2
	{SPU[0x2f] Thread (ApeCoreCellSpursKernel4) [0x02bbc]} class fmt::exception thrown: SPUThread::set_ch_value(): Unknown/illegal channel (ch=1 [$SPU_WrEventMask], value=0x2)
	(in file C:\rpcs3\rpcs3\Emu\Cell\SPUThread.cpp:1125) - Sly 3
	{SPU[0x2d] Thread (ApeCoreCellSpursKernel2) [0x02bbc]} class fmt::exception thrown: SPUThread::set_ch_value(): Unknown/illegal channel (ch=1 [$SPU_WrEventMask], value=0x2)
	(in file C:\rpcs3\rpcs3\Emu\Cell\SPUThread.cpp:1125) - Sly 1

- Opens a GSFrame.

Games affected:
- Sly Cooper and the Thievius Raccoonus/Sly Raccoon [NPEA-00341]
- Sly 2: Band of Thieves [NPEA-00342]
- Sly 3: Honour Among Thieves [NPEA-00343]

Settings:
- PPU/SPU: Interpreter (precise)
- LLE: CellSre
- Graphics: DX12/OGL/VK

Tested in PR #1939

**Comment by raven02** [comment] 2016-07-19 07:10
Duplicate of https://github.com/RPCS3/rpcs3/issues/1479

**Closed** 2016-07-19 07:10 UTC
