### ISSUE TITLE
Ni No Kuni Random Crashes

### ISSUE THREAD

**Issue by jwilliams90** [RPCS3/rpcs3#3136] opened 2017-08-02 15:06 UTC
Experiencing random hangs whilst playing Ni No Kuni on the latest build of rpcs3.

log gave me this error
E {rsx::thread} HLE: Getting the real address failed. (addr=0x750597ac)
E {rsx::thread} RSX: Invalid FIFO queue get/put registers found, get=0x750597AC, put=0x1902FC

**Comment by AniLeo** [comment] 2017-08-02 15:09
If you can provide more insight to how this is happening and in which build did it start, please comment. Otherwise will be closed due to lack of information. 

---

**Please read [**the guidelines**](https://github.com/RPCS3/rpcs3/blob/master/CONTRIBUTING.md) before opening an issue.**

Remember that the GitHub Issue Tracker is not the place to ask for support or to submit Game Compatibility reports. You must use [**our forums**](http://www.emunewz.net/forum/forumdisplay.php?fid=172) for that.

**Comment by jwilliams90** [comment] 2017-08-02 16:26
i'm using RPCS3 v0.0.3-6-180e0a4 Alpha and it happens when playing the game for around 10-15 minutes or so. i've only recently started using the emulator for this game because i assumed it was fully playable but when playing it the game would hang up and give me the error mentioned in the OP.

**Comment by hcorion** [comment] 2017-08-02 20:29
post RPCS3.log.
The log file rpcs3.log is found right next to rpcs3.exe and is not the same as the console output in the emulator. Please upload it to a site like pastebin, **don't** just paste it here.

**Comment by jwilliams90** [comment] 2017-08-03 02:18
Link to the log is below, i found that the crash occurs around 30 minutes to 1 hour of playtime.
log: https://drive.google.com/open?id=0B1vbIhPd5D_uRVhtUEVnamt0RUE

**Comment by jwilliams90** [comment] 2017-08-03 02:26
link to the log file below too large to put on pastebin so used google drive instead. the crash seems to occur when playing the game for 30 minutes or so.

log: https://drive.google.com/open?id=0B714z0FqLlleb1FRN2tjclZtcWs

**Comment by jwilliams90** [comment] 2017-08-04 17:22
here's the log: [RPCS3.zip](https://github.com/RPCS3/rpcs3/files/1201105/RPCS3.zip)

**Comment by hcorion** [comment] 2017-08-04 17:34
You have Write Color Buffers on, you don't need that on for Ni No Kuni, that's your problem.

**Comment by jwilliams90** [comment] 2017-08-05 00:08
Disabled Write Color Buffers in settings and still got the crash with the same error message from the OP. This happened after the Rusty's Nightmare boss fight in Motorville on my recent test

Here's the log: [RPCS3.zip](https://github.com/RPCS3/rpcs3/files/1201952/RPCS3.zip)

**Comment by Asinin3** [comment] 2017-08-09 01:30
@jwilliams90 You should be using the build from: https://rpcs3.net/compatibility?b instead. I haven't ran into this issue yet either but will play up to that point and see if it happens.

**Comment by kd-11** [comment] 2017-09-21 13:36
@jwilliams90 Retest with current master

**Comment by Daist** [comment] 2017-10-09 20:50
@kd-11 Been retesting every couple of weeks with the latest build every time, mostly getting "HLE: Getting the real address failed" error after 2-10 minutes :(
This time I managed to play for unbelievable 27 minutes without an error, and had a different error - "E {rsx::thread} RSX: Invalid RSX method 0x6d24 (arg=0xc22f4130)
(in file C:\rpcs3\rpcs3\Emu\RSX\rsx_methods.cpp:45)", I almost managed to save the game after a boss fight.
[RPCS3.log.gz](https://github.com/RPCS3/rpcs3/files/1369791/RPCS3.log.gz)

**Comment by kd-11** [comment] 2017-10-09 21:06
Other game threads are corrupting the main rsx data. If it did not recover after the error, things must have been really bad. There's no way around that until the synchronization bugs that cause it are fixed - look for mutex and lwcond errors before the rsx crash

**Comment by Daist** [comment] 2017-10-09 21:42
"·W 0:03:04.248938 {PPU[0x1000000] Thread (main_thread) [0x00035534]} sys_mutex: sys_mutex_destroy(mutex_id=0x8500a700)" - this is the last mention of mutex in the log, not sure if it is what I'm looking for.
"·W 0:00:55.275156 {PPU[0x1000035] Thread (_libsail-control) [0x020cce64]} sys_lwcond: _sys_lwcond_destroy(lwcond_id=0x97028100)" - this is the last mention of lwcond in the log. 

I'll try another release [NPUB30932] and see if it makes any difference, and I'll try to get a log with an HLE error.

**Comment by P1llus** [comment] 2017-10-11 08:09
There has been at least one reported place where several people have had the same "random" crash including me, at that is very close to the start of the game, when you speak to the ghost girl the first time. I just manage to reproduce it again, and created a save game right before you enter that scene, so if you load up this savegame, and try to walk towards the objective, you should be managing to reproduce a crash several times.

Settings:

GPU: 
Both OpenGL and Vulcan
Resolution 1920x1080 and 1280x720
Invalidate Cache Every Frame
Use GPU Texture Scaling
Framelimit Auto

CPU:
LLVM
ASMJIT
Load liblv2.sprx only
2 Preferred threads
SPU loop detection

APP: RPCS3 v0.0.3-3-5a03db7 Alpha | HEAD

Spec:
7700k
GTX 1080
16GB RAM

Log:
[RPCS3.log.gz](https://github.com/RPCS3/rpcs3/files/1374707/RPCS3.log.gz)

Savegame:
[BLES01555_00003.zip](https://github.com/RPCS3/rpcs3/files/1374705/BLES01555_00003.zip)

Errors:
```
E {rsx::thread} RSX: Invalid RSX method 0x250 (arg=0x4168c)
(in file C:\rpcs3\rpcs3\Emu\RSX\rsx_methods.cpp:45)
F {rsx::thread} class std::runtime_error thrown: Unknown surface target 0x80
(in file C:\rpcs3\rpcs3\Emu\RSX\gcm_enums.cpp:645)
```

**Comment by kd-11** [comment] 2017-10-25 21:48
Closing as a duplicate of https://github.com/RPCS3/rpcs3/issues/2359

**Closed by kd-11** 2017-10-25 21:48 UTC
