### ISSUE TITLE
Silent Hill: Downpour regressed to In-game

### ISSUE THREAD

**Issue by Psycho-A** [RPCS3/rpcs3#5160] opened 2018-09-21 20:26 UTC
On all September builds I'm getting emulator crash when intro level ends. I tried various settings and checked on two OSes (7 and 10) - no matter. My CPU is Core i5-2500, Video is Geforce GTX 750 Ti.

This is the error I'm getting before crash (also see the last RPCS3 log string).
![regression](https://user-images.githubusercontent.com/1223276/45904390-92109e80-bdf5-11e8-8474-32d3e4bc0957.jpg)

And this is the crash report from OS (sorry for Russian).
> Сигнатура проблемы:
>   Имя события проблемы:	APPCRASH
>   Имя приложения:	rpcs3.exe
>   Версия приложения:	0.0.0.0
>   Отметка времени приложения:	5ba404e0
>   Имя модуля с ошибкой:	ucrtbase.DLL
>   Версия модуля с ошибкой:	10.0.10586.9
>   Отметка времени модуля с ошибкой:	5642c48d
>   Код исключения:	40000015
>   Смещение исключения:	000000000006990f
>   Версия ОС:	6.1.7601.2.1.0.768.3
>   Код языка:	1049
>   Дополнительные сведения 1:	7217
>   Дополнительные сведения 2:	7217cfed4254ce51a527b436c655fe19
>   Дополнительные сведения 3:	14de
>   Дополнительные сведения 4:	14de29579c06380af41965f5e8f72079

**Comment by hcorion** [comment] 2018-09-22 16:04
Please test which PR caused the issue.

**Comment by isshininu** [comment] 2018-09-22 18:49
Your CPU is 4 core/4 threads, perhaps?
I didn't face this issue...

**Comment by Psycho-A** [comment] 2018-09-22 21:34
@isshininu Just try to pass the intro slowly, carefully looking around, and the place on my screenshot will guarantee make crash or hanging. If we're passing it maximally fast, we may not encounter it sometimes. Yes, I have 4-core/4-threads CPU.

@hcorion I took random build of 67xx-68xx periods, and the issues is still there.

**Comment by isshininu** [comment] 2018-09-22 21:57
What version of Windows 10 you are using?

Also, errors in ucrtbase.DLL may indicate that you are using outdated version of Microsoft Visual C++ 2017 Redistributable.

**Comment by Psycho-A** [comment] 2018-09-22 22:47
@isshininu I'm using 1607, as well as Windows 7 Home Premium, and errors are the same.

How can the certain place in certain game be connected to Visual Studio? I'm running other games and even other locations of subj. game, and they works normally.

**Comment by Psycho-A** [comment] 2018-09-23 00:33
I tried to increase buffers count for XAudio using config, the last two strings are gone, but first one is always on its place.

> ·E 0:09:13.843216 {rsx::thread} RSX: Could not get super_ptr for memory block 0xe13bfd54+0x4

And as you can see, memory block is always different. What kind of memory is meant here?

**Comment by isshininu** [comment] 2018-09-23 00:40
I can only recommend to always keep **all** original disc files in dev_hdd0/disc
to avoid strange bugs

**Comment by HerrHulaHoop** [comment] 2018-09-23 11:37
Could you join our discord server? It'll be much easier to test different combinations over there.

**Comment by isshininu** [comment] 2018-09-25 12:41
Well, here is my settings: 
[config.yml.LOG](https://github.com/RPCS3/rpcs3/files/2415215/config.yml.LOG)

**Comment by Psycho-A** [comment] 2018-09-29 06:37
> Well, here is my settings:

No changes :(

**Comment by AniLeo** [comment] 2018-10-01 19:38
Missing build where it regressed to be a complete Regression report

**Comment by kd-11** [comment] 2019-03-19 21:24
Retest and update.

**Comment by Psycho-A** [comment] 2019-03-22 09:33
From #5675 I'm getting permanent image flickering in the menus every one second when Strict rendering mode is disabled (Vulkan, both Windows 7/10). Also, game doesn't start without Strict mode until we enable Force CPU blit.

**Comment by Psycho-A** [comment] 2019-03-22 09:47
About the crash in hallway scene - it's still exist to me, and always happen when we're passing through intro scene slowly.

**Comment by kd-11** [comment] 2019-09-11 20:34
Five months since last update, retest.

**Comment by xVxXPrinceXxVx** [comment] 2019-12-12 23:46
[RPCS3.log](https://github.com/RPCS3/rpcs3/files/3958245/RPCS3.log)

I'm having the same issue and just like the screenshot @Psycho-A posted the emulator crashes exactly in that moment in the game.

Build: v0.0.7-9143
My PC: I7 7700 - GTX 1070 8gb - 16gb RAM - Windows 10 x64

**Comment by isshininu** [comment] 2019-12-13 00:35
I simply cannot continue from last save - game stuck reading save data.
[RPCS3.log.gz](https://github.com/RPCS3/rpcs3/files/3958402/RPCS3.log.gz)

**Comment by jokoputera** [comment] 2020-02-02 10:35
I checked using latest master 0.0.8-9489, save game still cant load...

**Comment by isshininu** [comment] 2020-02-04 16:01
Old games are not loaded.
New can be created and loaded. 
I don't know what happen, but if it is not possible to load old saves anymore, then this issue can be closed.
This issue is a duplicate: https://github.com/RPCS3/rpcs3/issues/6558

**Comment by digitaldude555** [comment] 2020-02-08 16:13
![Screenshot (1123)](https://user-images.githubusercontent.com/26138653/74088269-0e645a00-4a9d-11ea-91ca-0c60f5f0ef92.png)
Can get pass this part now, can close the issue.

**Closed** 2020-02-08 16:24 UTC
Labels: Need Information
