### ISSUE TITLE
[Vulkan] Far Cry Classic no longer goes ingame

### ISSUE THREAD

**Issue by Shoegzer** [RPCS3/rpcs3#6983] opened 2019-11-12 01:24 UTC
Far Cry Classic now hangs on loading before displaying anything onscreen.  Tested with commit abbf3c4d16f7b1e7a3a2b29ff7546750625318f9.  This seems to be a regression from a commit over the past week or so, though haven't traced the specific commit via bisect.

Note that this is a different issue than https://github.com/RPCS3/rpcs3/issues/5968 which was previously reported for this game.

Test system is Linux Mint 19.2 with kernel 5.0 and Nvidia GTX M 1070 with 440.26 drivers.

[RPCS3.log](https://github.com/RPCS3/rpcs3/files/3833888/RPCS3.log)

**Comment by Asinin3** [comment] 2019-11-12 01:29
Tracing the specific commit isn't completely necessary. But I think you should always try to nail it down to a single PR so we know what developer needs to take a look at it, otherwise these things don't really get looked at.

**Comment by Augusto7743** [comment] 2019-11-12 06:41
Try not use LLVM

**Comment by Shoegzer** [comment] 2019-11-12 17:10
Tried without LLVM on both PPU and SPU but it didn't make a difference.   However, switching to OpenGL does "work" as before (this game always had major issues with OpenGL stuttering).  So it's Vulkan related.

Also, I found time to perform a bisect, which took quite a while.  The bad commit is aa3eeaa4171e7ca26febfe44357af0fc54d428cc.  @kd-11 any thoughts here?

**Comment by kd-11** [comment] 2019-11-12 17:45
I would have guessed its the same issue as https://github.com/RPCS3/rpcs3/issues/6971 but I can't tell from a glance since the description here is rather vague. Does it just freeze? I mean, the regression from that commit would have crashed the driver or something instead. Silent death is uncommon with vulkan issues.

**Comment by kd-11** [comment] 2019-11-12 17:46
After checking the log, the emulator clearly crashes with a fatal error message, which was not mentioned in the description. Closing as duplicate of https://github.com/RPCS3/rpcs3/issues/6971

**Closed by kd-11** 2019-11-12 17:46 UTC

**Comment by Shoegzer** [comment] 2019-11-12 19:35
Yes @kd-11, right after the SPU cache is built and the game launches you hear a few notes of the Ubisoft jingle and then it locks up.  I should have mentioned the fatal error in the description rather than let the log speak for itself.  In any event, good to hear there's a fix on the way - I'll test and report back to #6971.  Thanks.
