### ISSUE TITLE
MSAA causes issues in MGS3

### ISSUE THREAD

**Issue by NotBeanz** [RPCS3/rpcs3#6766] opened 2019-10-14 14:24 UTC
Having MSAA enabled causes some weird graphical glitches in Metal Gear Solid 3 that I'd like to demonstrate:

The intro section with MSAA enabled:
![screenshot-2019_10_13_23_16_37](https://user-images.githubusercontent.com/54376483/66758241-913a2700-eea6-11e9-9f0c-d0ae266fdd85.png)

The intro section with MSAA disabled:
![screenshot-2019_10_14_17_01_38](https://user-images.githubusercontent.com/54376483/66758268-a2833380-eea6-11e9-9835-4b2110e765f3.png)

Enabling anti-aliasing is somewhat necessary since it also fixes some missing graphics such as:
- The cockpit showing incorrectly when MSAA is disabled:
![screenshot-2019_10_14_17_01_23](https://user-images.githubusercontent.com/54376483/66758633-5389ce00-eea7-11e9-94e8-68c8490108e4.png)

- The same scene showing correctly with MSAA enabled:
![screenshot-2019_10_14_17_03_51](https://user-images.githubusercontent.com/54376483/66758405-e0805780-eea6-11e9-9ebf-238c44591414.png)

Creating RSX captures of these screens crashes the emulator so I had to use Renderdoc instead.
The Renderdoc captures were done on an RX 570 with the latest drivers on Windows. (Though I'd like to mention that this issue is the same on Linux as well with RADV)

The Renderdoc with MSAA enabled: https://drive.google.com/open?id=1CHyrgidDsXqCcqC-KNDMH0i4oHlCXyOW
The Renderdoc with MSAA disabled: https://drive.google.com/open?id=18mRM3XpIDJs2y2Xc1LbqbM2WIq-cOTMl

**Comment by kd-11** [comment] 2020-06-13 12:46
Turns out this is caused by an optimization I added to speed up surface operations. Removing it fixes the graphical problems but drops fps by something like 70%, I need to rethink the solution.

**Comment by kd-11** [comment] 2020-06-14 11:31
Fixed by https://github.com/RPCS3/rpcs3/pull/8434, you can test using the build in the PR to verify.

**Comment by NotBeanz** [comment] 2020-06-14 12:03
The issue is indeed fixed. Nice work!

**Closed** 2020-06-14 17:13 UTC
Labels: Bug, RSX
