### ISSUE TITLE
rsx: Verification failed on texture_cache.h:3066[:8] - Ratchet & Clank: A Crack in Time

### ISSUE THREAD

**Issue by zeroking1998** [RPCS3/rpcs3#11471] opened 2022-01-31 17:09 UTC
This error happens, more frequently, when I do the quest, where I need to save the children

[RPCS3.log](https://github.com/RPCS3/rpcs3/files/7972727/RPCS3.log)

**Comment by Megamouse** [comment] 2022-01-31 19:53
update your game and try default settings

**Comment by zeroking1998** [comment] 2022-01-31 23:28
> update your game and try default settings

with the default settings, i can play longer but it's crash with the same error

the update,  crashes RPCS3 after 3 min of gameplay

**Comment by AniLeo** [comment] 2022-02-08 23:00
Log file shows debug setting (force) `GPU Texture Scaling` being used, needs retest

Verification failed
(in file D:\a\1\s\rpcs3\Emu\RSX\Common\texture_cache.h:3066[:8], in function upload_scaled_image) (e=0x00000578[1400])

**Comment by readywer** [comment] 2022-02-09 20:53
Hy 
With build 13259 i played 30m and i had no crash, but the read color buffers won't fix the black boxes around effects and the looked really different from the original and i had load where i my ratchet model won't loaded  and can't move, but the menus work. 

Where i can't move:
![Képernyőfelvétel (479)](https://user-images.githubusercontent.com/90259918/153287210-55c9495a-7778-4a42-864a-365569101f4e.png)

The black box without read color buffers:
![Képernyőfelvétel (485)](https://user-images.githubusercontent.com/90259918/153287381-e81354c2-1901-4bad-9265-3900183b6727.png)

With color buffers on:
![Képernyőfelvétel (480)](https://user-images.githubusercontent.com/90259918/153287467-69ca1bdf-138c-4a4f-b3f9-2dc61d050c80.png)
![Képernyőfelvétel (481)](https://user-images.githubusercontent.com/90259918/153287476-712065c6-57f4-48ac-9082-93292526501a.png)

And the water on ps3:
![Képernyőfelvétel (486)](https://user-images.githubusercontent.com/90259918/153287875-4dd6878d-98c7-4c0b-a69e-a53935739d98.png)

In emulator:
![Képernyőfelvétel (482)](https://user-images.githubusercontent.com/90259918/153287931-af19542f-7354-42cf-aa9e-9ab0443af1b5.png)

The can't move log: 
[RPCS3.log.gz](https://github.com/RPCS3/rpcs3/files/8036140/RPCS3.log.gz)

The graphical glitcs log:
[RPCS3.log.gz](https://github.com/RPCS3/rpcs3/files/8036145/RPCS3.log.gz)

**Comment by kd-11** [comment] 2022-02-15 22:19
This ticket is about the crash. Visual glitches are known and unrelated

**Comment by kd-11** [comment] 2022-02-19 08:11
Crash likely caused by the incorrect use of a debug setting (Force GPU texture scaling). Closing.
Request to reopen if incorrect.

**Closed by kd-11** 2022-02-19 08:11 UTC
Labels: RSX, Need Information
