### ISSUE TITLE
Regression : Dragon's Crown - audio cut off & black screen

### ISSUE THREAD

**Issue by davoodinator** [RPCS3/rpcs3#2673] opened 2017-04-10 21:16 UTC
http://www.emunewz.net/forum/showthread.php?tid=174291

Summary:

1. game was working at some point around build 4087 or so. we can't seem to lock down which commit broke it.
2. game works flawlessley until tutorial start.
3. tutorial start -> sound dies
4. end of first tutorial room -> black screen of death

This happens with all PPU/SPU selection combinations.

I will try and find some time today to post some logs.  the thread is full of information though (and logs).

**Comment by gum661** [comment] 2017-04-11 18:38
I can confirm this issue - in my case, 4088 is the version which introduced it.

**Comment by davoodinator** [comment] 2017-04-14 21:54
evidence that it was working at one point

https://www.youtube.com/watch?v=9cSN5p2Bhqo

**Comment by davoodinator** [comment] 2017-04-14 22:02
apparently the last time this happened.

the fix was this

https://github.com/RPCS3/rpcs3/commit/c785b14c1836bb322af56cc663186d8c5462c8fd

**Comment by davoodinator** [comment] 2017-04-18 09:13
log files from recent fail
rpcs3-v0.0.2-2017-04-16-038c4add_win64


[rpcs3-v0.0.2-2017-04-16-038c4add_win64.zip](https://github.com/RPCS3/rpcs3/files/928114/rpcs3-v0.0.2-2017-04-16-038c4add_win64.zip)

file is actually .7z i renamed it so github would let me upload

**Comment by davoodinator** [comment] 2017-04-18 11:34
#1870  seems to be related to this. i posted in there with relevant bits

**Comment by RipleyTom** [comment] 2017-05-07 20:57
I tracked the commit that stops the game working to exactly #2404 which is a massive rewrite and not something easy to reverse.
When the screen gets black after the first zone all the threads are locked either trying to lock a mutex(with no timeout), on _sys_cond_wait or a similar multithreading locking(basically all waiting for something to happen). It may not be related to the actual problem though(they may get to this state because something else messed up).

**Comment by raven02** [comment] 2017-05-08 15:32
This should be the audio cut off in some other games as well after reservation rewritten.

**Comment by RipleyTom** [comment] 2017-05-15 18:46
After many days working on it I figured a fix.
One spu threads hangs when trying to RdTagStat after writing as a mask a 0(which from what I've read should not happen, it may has some special significance that is not documented).

Changing the SpuThread.cpp function SPUThread::get_ch_value to add a special case for this fixed both audio issue and the black screen.

	case MFC_RdTagStat:
	{
		if (ch_tag_mask == 0) return 0xFFFFFFFF;
		return read_channel(ch_tag_stat);
	}

Notice that it's a dirty hack I implemented just to test if it was the issue and it was.

**Comment by davoodinator** [comment] 2017-05-17 07:59
<3

killed harpy boss

**Comment by davoodinator** [comment] 2017-05-20 05:49
failed @ entering last floor of ancient capital.


it was wroking fine until i stopped moving just near the "next -->" indicator and let my wizard try to eat an apple.

music continued but game seemed visually frozen.
[!RPCS3.zip](https://github.com/RPCS3/rpcs3/files/1015907/RPCS3.zip)

**Comment by davoodinator** [comment] 2017-05-20 05:49
^ log

**Comment by AniLeo** [comment] 2017-09-04 14:10
This regression was fixed. Other unrelated issues with the game are discussed in #3013
Closing

**Closed by AniLeo** 2017-09-04 14:10 UTC
Labels: Audio, Regression
