### ISSUE TITLE
Samurai Warriors 4: Empires - Audio "Corruption?"

### ISSUE THREAD

**Issue by KatherineFtw** [RPCS3/rpcs3#7290] opened 2020-01-19 21:53 UTC
Seg Mousou 4/Samurai Warrior 4: Empires has audio corruption? (I don't know the accurate term) issues, particularly on the politics screen and during battle. 

Footage via Youtube.
https://youtu.be/bwLX9rx7ekU

Logs.
https://drive.google.com/file/d/1chyVCdTaWoxT6wIKhJW2pIcGoJhOPSN2/view?usp=sharing

Specs:
i7-8700
16GB of DDR4
RX580 (8GB)

RPCS3 stuff
Version - Latest Build (0.0.8-9412-858ce014)
Backend - Vulkan
Settings - https://imgur.com/a/ep20TGi

Hopefully I'm doing this right.

**Comment by digitaldude555** [comment] 2020-02-22 11:21
@KatherineFtw try without spu loop.

**Comment by KatherineFtw** [comment] 2020-02-23 06:58
Well, in battle stability improves a bit, but audio still corrupts. 

Youtube Video
https://youtu.be/1wZMWd8gy28

Logs
https://drive.google.com/file/d/1pZ6-9PU3Kc-yfGnASTnptWBrwUFNhQEo/view?usp=sharing

Tested on latest: 0.0.8-9682

**Comment by Asinin3** [comment] 2020-10-29 13:19
@KatherineFtw Your log shows you using ` Accurate xfloat: true` which is slow as fuck and should only be used when its absolutely required. Likely the cause of this audio corruption. Can you retest with it off.

**Comment by Megamouse** [comment] 2021-03-06 22:47
@KatherineFtw please retest with recommended settings for the game

**Comment by Asinin3** [comment] 2021-09-15 13:40
Closing. OP used Accurate Xfloat which is likely cause of the issue and didn't retest.

**Closed by Asinin3** 2021-09-15 13:40 UTC

**Comment by KatherineFtw** [comment] 2022-03-10 02:41
Apologies, I've been busy and just sort of forgot about this. I retested with Accurate XFloat off. It improves it, but there's still some hiccups that I don't know if are due to lag or actual corruption.

-Youtube-
https://youtu.be/qC0z74X0Fuk 

-Logs-
https://drive.google.com/file/d/1TiRAbqHh6YS3k3Y-T-IUVwp0F5alBJsH/view?usp=sharing
