### ISSUE TITLE
Suggestion: Various UX changes

### ISSUE THREAD

**Issue by yuritsuri** [RPCS3/rpcs3#5390] opened 2018-12-03 10:27 UTC
![image](https://user-images.githubusercontent.com/14804553/49367186-a72b7700-f72e-11e8-8c7c-18a081892017.png)
**Search Bar** should be aligned relatively to the right side of the window, not from the **Toolbar**

![image](https://user-images.githubusercontent.com/14804553/49367272-ebb71280-f72e-11e8-9bc1-53265d75c876.png)
Add separators between elements of the **Toolbar** that arent related to eachother (makes it clearer what is related and what isnt)

![image](https://user-images.githubusercontent.com/14804553/49367488-90395480-f72f-11e8-8a24-b0cd2e6e66ae.png)
Hide relatively useless button based on context (playing/idle)

![image](https://user-images.githubusercontent.com/14804553/49367545-b828b800-f72f-11e8-8320-73d95b7e3299.png)
Make **List** and **Grid** a toggle instead of two separate button, they display the exact same content, not specific contents, therefore it is pointless to separate them when all they do is change the point of view

![image](https://user-images.githubusercontent.com/14804553/49367651-0b9b0600-f730-11e8-8c04-bfd3ccca5833.png)
Remove the **Slider** altogether, it isnt very useful in my opinion

![image](https://user-images.githubusercontent.com/14804553/49368085-3afe4280-f731-11e8-96de-9da695151283.png)
if we keep it then move it inside the window like steam does, i think this is a good place to put the grid/list toggle as well 

I have some other stuff but its ui related, this post is only for ux, please give some feedback

**Comment by 13xforever** [comment] 2018-12-03 10:36
Slider isn't useful in your opinion only because you don't have a mix of normal and hidpi displays, and do not use grid view that often.

**Comment by shinnyuu** [comment] 2018-12-03 10:50
true that but imo it should be moved elsewhere, the steam way seems better than the current one

**Comment by MSuih** [comment] 2018-12-03 13:19
I do agree that the steam's way looks better visually, but I'm not sure how to implement that in Qt. But it's better to have it at current position than removing it alltogether.

Other suggestions seem fine, and I might consider implementing some myself. We'll see.

**Comment by MSuih** [comment] 2018-12-03 15:32
Adding the separators is easy, just requires a couple of lines to .ui file
<details><p>

```diff
diff --git a/rpcs3/rpcs3qt/main_window.ui b/rpcs3/rpcs3qt/main_window.ui
index 18767da..ecf9568 100644
--- a/rpcs3/rpcs3qt/main_window.ui
+++ b/rpcs3/rpcs3qt/main_window.ui
@@ -332,11 +332,14 @@
    </attribute>
    <addaction name="toolbar_open"/>
    <addaction name="toolbar_refresh"/>
+   <addaction name="separator"/>
    <addaction name="toolbar_fullscreen"/>
    <addaction name="toolbar_stop"/>
    <addaction name="toolbar_start"/>
+   <addaction name="separator"/>
    <addaction name="toolbar_config"/>
    <addaction name="toolbar_controls"/>
+   <addaction name="separator"/>
    <addaction name="toolbar_list"/>
    <addaction name="toolbar_grid"/>
   </widget>
```
</p></details>
However, the issue is that Qt doesn't seem to have any way of styling them. I tried adding all of the color properties and the only ones which had any impact were border and background colors, both of which affected the whole "bounding box" of the element instead of just the line in it. So the separators work fine in lighter themes but appear as inconsistent spacing in darker themes:

![image](https://user-images.githubusercontent.com/19759300/49382080-1fd60780-f71e-11e8-95df-bebedc84a4a1.png)

Also I'm not sure what you mean with the hiding stuff. Fullscreen button does not affect the game window but rather the main window, and play button doubles as "start last played game" button when no games are being emulated. So the only button which has no purpose outside of a game is Stop, and I think it can stay there for now.

**Comment by Megamouse** [comment] 2018-12-03 17:43
Every change you suggest was delibaretaly not chosen in the last ui change

**Comment by Megamouse** [comment] 2021-05-29 10:25
Oh. seems like I completely missed this comment.

- The vertical seperators were removed at one point deliberately. It just looked better without them as far as I remember. So I guess it can be considered if/when there eventually is a GUI redesign.
- The search bar was similarly moved to that position. In my opinion it would be too far away from the game names if I put the bar to the right. And maybe there was some bug that prevented the suggested behaviour (I don't remember, but it was a pain to work with the toolbar)
- I'm with 13xForever regarding the slider. And I don't think there's an easy way to move the stuff into the list. Also, it will reduce valuable vertical screen estate, whereas now it's just cleanly tugged at the top bar (which can be hidden btw).
- The toolbar Icons should not be hidden, as any of the buttons can still be used during gameplay, and many would complain if you couldn't.

The only thing that can be done without problems is merging the grid/list buttons. :)

**Comment by Asinin3** [comment] 2021-09-15 12:32
Closing issue. Agree with Mega on this, most suggestions especially search/slider are look worse to me. And its clear its not going to be implemented.

**Closed by Asinin3** 2021-09-15 12:32 UTC
Labels: GUI, Discussion
