### ISSUE TITLE
Metal Gear Solid: HD Collection - Metal Gear Solid 2 Rendering Issues. (On the Master Build of RPCS3 dated 17/06/2019)

### ISSUE THREAD

**Issue by EtchJackon** [RPCS3/rpcs3#6104] opened 2019-06-17 18:38 UTC
RPCS3 Version:
RPCS3 v0.0.6-8261-d52953fc Alpha
Computer Info:
Intel(R) Core(TM) i7-7700HQ CPU @ 2.80GHz | 8 Threads | 15.87 GiB RAM | AVX+
NVIDIA GTX 1050 TI 

Issue Description

The opening of Metal Gear Solid 2: Sons of Liberty (tanker) is rife with tons of missing graphics that cannot be repaired by any of the available settings in RPCS3. I've provided screenshot the game running on the latest Master Build of RPCS3 (as of 17/06/2019).
This post is a is a continuation of the post submitted by: JMC47 on: Apr 29, 2018

Reproducing this issue is easy as it happens on all builds of RPCS3 and watching the first 10 minutes of cinematic show all of the errors below.  

The Errors:

Issue 1 - Missing Rain Effects

The rain and weather effects at the start of the game do not render. 

![image](https://user-images.githubusercontent.com/46559631/59627433-1fd7ab00-9136-11e9-938e-4e396a4d0512.png)

Issue 2 - Missing Lighting Effects and models.

The cars in this scene do not render correctly, the lights that are on the car do not render at all.

![image](https://user-images.githubusercontent.com/46559631/59627573-7218cc00-9136-11e9-991c-46fca3ed86f6.png)

Issue 3 - Missing Stealth Camouflage Effect

When jumping from the bridge, Snake's stealth suit transparency effect does not render at all, neither do the lighting effects from when he is uncloaking.

![image](https://user-images.githubusercontent.com/46559631/59627683-b5733a80-9136-11e9-8d79-2de4bcca133a.png)

Issue 4 - Snake is Missing in Codec Scenes

Snakes model portrait does not render at all.  

![image](https://user-images.githubusercontent.com/46559631/59627777-f4a18b80-9136-11e9-825e-de522e6d8c14.png)

Issue 5 - Water Does Not Render

The water around the tanker does not render in RPCS3 at all.

![image](https://user-images.githubusercontent.com/46559631/59627875-287cb100-9137-11e9-8b49-f91e5c52a997.png)

Issue 6 - Laser Dot is Missing

When aiming in first and third person, the red dot and laser from underneath Snakes M9 are not rendering.

![image](https://user-images.githubusercontent.com/46559631/59627972-67126b80-9137-11e9-82ed-f37c8aae392d.png)

**Comment by Megamouse** [comment] 2019-06-17 18:39
duplicate of #4494
please add your findings there if necessary

**Closed** 2019-06-17 18:41 UTC

**Comment by EtchJackon** [comment] 2019-06-17 18:42
> duplicate of #4499
> 
> please add your findings there if necessary
> 
> edit: oups i linked the wrong issue first :(

yeah it was my bad I mean to post it within the that issue
