### ISSUE TITLE
NP Remote Authentication bugged when using RPCN

### ISSUE THREAD

**Issue by ryanrox333** [RPCS3/rpcs3#11396] opened 2022-01-17 23:59 UTC
## Quick summary
RPCN errors out when using NP Remote Authentication. I found this error while working on the D1CS project. We decided to put the error here just incase it is something that can be fixed inside of RPCS3.

## Details

Please describe the problem as accurately as possible.

#### 0. Make sure you're running with settings as close to default as possible
Like I said in the last bug report, we only change the Host/IP Switch.

#### 1. Please attach RPCS3's log.
[RPCS3.log](https://github.com/RPCS3/rpcs3/files/7885199/RPCS3.log)

#### 2. If you describe graphical issue, please provide an RSX capture and a RenderDoc capture that demonstrate it.
No graphical issues.

#### 3. Please attach screenshots of your problem.
![image](https://user-images.githubusercontent.com/44746268/149849093-4b3cee9e-11f8-4514-b1e9-90875dfd8cc4.png)

#### 5. Please provide your system configuration:
* OS Microsoft Windows 11 Home 10.0.22000 Build 22000
* CPU Intel(R) Core(TM) i7-9700F CPU @ 3.00GHz, 3000 Mhz, 8 Core(s), 8 Logical Processor(s)
* GPU NVIDIA GeForce GTX 1660
* Driver version 30.0.14.9709

#### Please include.
* Anything else you deem to be important
I think this should be enough. If you need anything else, please reach out to me and I'll do so.

**Comment by Crafty-The-Fox** [comment] 2022-01-19 02:37
this could be related to a PSN cookie issue. however im not sure if that applies to other games other than activation games.


you may need to patch it out.

**Comment by RipleyTom** [comment] 2022-01-21 14:36
I'm not sure what you think the issue is here.
The game requests a ticket and then sends it to a server for authentication (server which you haven't redirected).

Those tickets are digitally signed by PSN so ofc the RPCN version of them won't work with an official server.
Closing as it's a non-issue as far as I can tell.

**Closed by RipleyTom** 2022-01-21 14:36 UTC
Labels: Network
