### ISSUE TITLE
[BLJM61140, BLES02057]Dynasty Warriors Gundam: Reborn have Stopped after Gundam Rising video

### ISSUE THREAD

**Issue by egeoda** [RPCS3/rpcs3#9756] opened 2021-02-10 06:04 UTC
## Quick summary
Game have stopped(black screen+stop) after Gundam Rising video. 
Europe(BLES02057), JPN(BLJM61140) both same problem..
rpcs3-v0.0.14-11727-8d6504d6_win64
Default Settings by the way

## Details

Game have stopped(black screen+stop) after Gundam Rising video. 
Start the game -> make a save file -> select official mode -> select first gundam(top of the list) -> push start(enter) and select skip -> select start battle(the bottom of the list) -> start the video -> After this video Game stop whether you skip it or not

I tried applying the existing patch to BLES02057 but it didn't work. 
Patch 1.02 has been applied to BLJM61140.
Both have DLC installed. 

#### 1. Please attach RPCS3's log.

* Attach the log:
[RPCS3_BLES02057_DWGR.log.gz](https://github.com/RPCS3/rpcs3/files/5955998/RPCS3_BLES02057_DWGR.log.gz)
[RPCS3_BLJM61140_DWGR_JPN.log.gz](https://github.com/RPCS3/rpcs3/files/5955999/RPCS3_BLJM61140_DWGR_JPN.log.gz)

	+ Drag and drop your log file into the issue.
	+ Or upload it to the cloud, such as Dropbox, Mega etc. 

#### 3. Please attach screenshots of your problem.
* Enable performance overlay with at least medium level of detail.
You can find it in _Emulator_ tab in _Settings_.

#### 5. Please provide your system configuration:
* OS : Windows 10 Pro 20H2 19042.746
* CPU : Intel Whiskeylake i7-8565U 1.8 Ghz
* GPU : nVidia GeForce MX 150
* Driver version : CPU : Intel 10.0.19041.546(?)    GPU : GeForce Driver(Game) 461.9
* etc. : I haven't installed Intel DPTF(Intel Dynamic Platform and Thermal Framework)

#### Please include.
[import_patch.zip](https://github.com/RPCS3/rpcs3/files/5956082/import_patch.zip)

**Comment by egeoda** [comment] 2021-02-10 06:15
After writing, there is a forum. Should I post it on the forum instead of here? i'm newbie here

**Comment by reaper185** [comment] 2021-02-10 12:15
There is already an issue for this #4522 unfortunately the patch that @isJuhn made does not work for BLJM61140 that I know of but last time I checked it works for BLES02057. They have updated the patch system several times so I haven't tested it. In the forum, they posted the new patch format and the instructions to do it so check that.

**Comment by AniLeo** [comment] 2021-02-10 15:32
Duplicate of #4522

**Closed by AniLeo** 2021-02-10 15:32 UTC
