### ISSUE TITLE
DX12/GL/Vulkan: Dragon Ball: Raging blast [BLUS30431], RSX Issues, crashes

### ISSUE THREAD

**Issue by Raduq91** [RPCS3/rpcs3#3298] opened 2017-08-22 09:05 UTC
Dragon Ball: Raging blast [BLUS30431]

    PPU interpreter (fast)
    SPU Recompiler (ASMJIT)
    720x576
    Aspect Ratio 4:3
    Audio Null

    fiber
    sre
    spursqs_jq
    resc
    l10n
    vdec
    smvd2

4690k
GTX 1060 3GB
8GB Ram

All tested at Versus, character select.

Using https://ci.appveyor.com/project/rpcs3/rpcs3/build/1.0.3082/artifacts :
![bun](https://user-images.githubusercontent.com/31180871/29557356-7abd7b00-8731-11e7-928c-db7bb44acbc4.png)

Vulkan: seems to work, no crashes so far(can select characters, stage and it goes ingame and works)
OpenGL: F {rsx::thread} class std::logic_error thrown: bad destination swizzle.
DX12: F {rsx::thread} class fmt::exception thrown: `anonymous-namespace'::upload_single_texture(): HRESULT = The GPU device instance has been suspended. Use GetDeviceRemovedReason to determine the appropriate action.
(in file C:\rpcs3\rpcs3\Emu\RSX\D3D12\D3D12Texture.cpp:137)

Using https://ci.appveyor.com/project/rpcs3/rpcs3/build/1.0.3090/artifacts :
![b2008](https://user-images.githubusercontent.com/31180871/29557423-b54004aa-8731-11e7-9fd7-b6fd03bdb80d.png)

Vulkan: prob changes in this build made it unstable, sometimes it freeze, sometimes crashes, sometimes works
OpenGL: F {rsx::thread} class std::logic_error thrown: bad destination swizzle.
DX12: F {rsx::thread} class fmt::exception thrown: `anonymous-namespace'::upload_single_texture(): HRESULT = The GPU device instance has been suspended. Use GetDeviceRemovedReason to determine the appropriate action.
(in file C:\rpcs3\rpcs3\Emu\RSX\D3D12\D3D12Texture.cpp:137)

Using https://ci.appveyor.com/project/rpcs3/rpcs3/build/1.0.3092/artifacts :
![b2005](https://user-images.githubusercontent.com/31180871/29557477-e300c366-8731-11e7-80db-6f0b18caa57e.png)

Vulkan: E {rsx::thread} RSX: Invalid RSX method 0xac00 (arg=0x10800140)
(in file C:\rpcs3\rpcs3\Emu\RSX\rsx_methods.cpp:
OpenGL: E {rsx::thread} RSX: Invalid RSX method 0xac00 (arg=0x10800140)
(in file C:\rpcs3\rpcs3\Emu\RSX\rsx_methods.cpp:
DX12: E {rsx::thread} RSX: Invalid RSX method 0xac00 (arg=0x10800140)
(in file C:\rpcs3\rpcs3\Emu\RSX\rsx_methods.cpp:

Using latest build https://ci.appveyor.com/project/rpcs3/rpcs3/build/0.0.3-5822/artifacts : 
![latest opengl](https://user-images.githubusercontent.com/31180871/29557207-f5d49f72-8730-11e7-837f-4486733fba75.png)

Vulkan: E {rsx::thread} RSX: Invalid RSX method 0xac00 (arg=0x10800140)
(in file C:\rpcs3\rpcs3\Emu\RSX\rsx_methods.cpp:
OpenGL: E {rsx::thread} RSX: Invalid RSX method 0xac00 (arg=0x10800140)
(in file C:\rpcs3\rpcs3\Emu\RSX\rsx_methods.cpp:
DX12: E {rsx::thread} RSX: Invalid RSX method 0xac00 (arg=0x10800140)
(in file C:\rpcs3\rpcs3\Emu\RSX\rsx_methods.cpp:
Null(navigated by sound): E {rsx::thread} RSX: Invalid RSX method 0xac00 (arg=0x10800140)
(in file C:\rpcs3\rpcs3\Emu\RSX\rsx_methods.cpp:

Recap:
Build https://ci.appveyor.com/project/rpcs3/rpcs3/build/1.0.3082/artifacts : Game works in Vulkan only(in versus can select character, stage and it goes in game and works)
Build https://ci.appveyor.com/project/rpcs3/rpcs3/build/1.0.3090/artifacts : Game unstable in Vulkan(in versus at character select sometimes it freezes, crashes or works
Build https://ci.appveyor.com/project/rpcs3/rpcs3/build/1.0.3092/artifacts : Game freeze at character select
Latest build https://ci.appveyor.com/project/rpcs3/rpcs3/build/0.0.3-5822/artifacts: Game freeze at character select

**Comment by kd-11** [comment] 2017-08-22 12:33
Duplicate of https://github.com/RPCS3/rpcs3/issues/2359.
Its a known issue - method 0xac00 seems to be indexed and probably alters texture state in some way. It is not currently known what its supposed to do so the game stops.

**Closed by kd-11** 2017-08-22 12:33 UTC
