### ISSUE TITLE
Minecraft crashes

### ISSUE THREAD

**Issue by niko1point0** [RPCS3/rpcs3#4976] opened 2018-08-13 03:02 UTC
Regardless what CPU and GPU settings are chosen, if you walk around for a few minutes, you will always get the following error messages. I wish I could give more information, but that's it. Create a new map while playing Tutorial and just walk around for a minute. The only time this bug does not appear is when creating a new map in Super Flat Mode, which basically means its a blank map with nothing in it

U {PPU[0x1000000] Thread (main_thread) [0x00dac864]} HLE TODO: Unimplemented syscall syscall_988 -> CELL_OK
U {PPU[0x1000000] Thread (main_thread) [0x00dac7d0]} HLE TODO: Unimplemented syscall syscall_988 -> CELL_OK

**Comment by Relsig** [comment] 2018-08-13 03:14
Duplicate of #3627

**Closed** 2018-08-14 05:31 UTC
