### ISSUE TITLE
Tales of Graces F [BLUS30903] Always black screen with saved shader cache, and also major graphical glitches

### ISSUE THREAD

**Issue by P1llus** [RPCS3/rpcs3#3579] opened 2017-10-11 15:37 UTC
Game has stable FPS, music works, menus work (except that the background is resized to only fit half the screen on menues, without strict rendering it is just totally black background), though it has some weird issues.

**#1**
First issue is the shader cache. If you boot up the game once, it works just fine, music plays, video is shown and you can start up your game. Though after this you will always need to clear your shader cache before booting the game. If you try, you will be presented with a black screen, though the menu and intro music are still heard in the background.

_Logs without shader cache:_
[RPCS3.log.gz](https://github.com/RPCS3/rpcs3/files/1376161/RPCS3.log.gz)

_Logs with shader cache already there when booting:_
[RPCS3.log.gz](https://github.com/RPCS3/rpcs3/files/1376165/RPCS3.log.gz)

**#2**
Other issue is the graphical glitches, which are very different with or without Strict Rendering Mode:

_With strict rendering mode_ (the blue glitches on the top right will flicker constantly, though after i reproduced it so many times, it never showed up again..):
![image](https://user-images.githubusercontent.com/8027539/31449947-7f4b47b2-aea8-11e7-81d7-37c62163f2d8.png)

_Characters are see-through compared to all objects behind them:_
![image](https://user-images.githubusercontent.com/8027539/31450253-3f6fabc8-aea9-11e7-9ea3-5714ce7e088a.png)

_Logs with strict rendering mode:_
[RPCS3.log.gz](https://github.com/RPCS3/rpcs3/files/1376188/RPCS3.log.gz)

_Without strict rendering mode:_
Same location as with strict rendering:
![image](https://user-images.githubusercontent.com/8027539/31450681-571278e0-aeaa-11e7-9414-383edec3473c.png)

_Black backgrounds:_
![image](https://user-images.githubusercontent.com/8027539/31450811-b51324b2-aeaa-11e7-840a-3668149ec148.png)

_Logs without strict rendering mode:_
[RPCS3.log.gz](https://github.com/RPCS3/rpcs3/files/1376204/RPCS3.log.gz)

GPU:
Both OpenGL and Vulcan
Resolution 1920x1080 and 1280x720
Invalidate Cache Every Frame
Use GPU Texture Scaling
Strict Rendering Mode ON/Off
Framelimit 30/60

CPU:
LLVM
ASMJIT
Load liblv2.sprx only / Automatic
3 Preferred threads
SPU loop detection

Version:
RPCS3 v0.0.3-3-9bcc298 Alpha | HEAD

Spec:
7700k
GTX 1080
16GB RAM

**Comment by Marthgun** [comment] 2017-10-11 16:05
are you getting blurred skits on your end?  Skits are pretty much essential to the game, the transparency issue pretty minor all things considered.  I've used renderdoc during the prologue, the skits seem to be like a video overlay, no information is recieved through renderdoc.  i'm still having problems compiling the source, debug obv doesn't work, LLVM keeps giving me fatal error on booting any game.  haven't had the will to try the non LLVM.  also haven't looked at the debugging tools that's on the emulator.

![togf_strictrenderopglblur](https://user-images.githubusercontent.com/15056246/31452260-03adbc72-ae74-11e7-9b27-1313b704a479.PNG)

**Comment by P1llus** [comment] 2017-10-11 17:29
They are indeed blurry for me as well, so not much we can do that until someone got time to look into the issues :)

**Comment by GeniusMage** [comment] 2017-10-18 11:45
Duplicate, an issue already exists for this game's issues.
https://github.com/RPCS3/rpcs3/issues/3020

**Comment by P1llus** [comment] 2017-10-18 11:52
@GeniusMage Actually the main issue i wanted to report was the unable to boot with shader caches, as that is not a bug only relevant to this game. Would it help if i edit the issue to only include this? I still feel it is a bug so.

**Comment by GeniusMage** [comment] 2017-10-18 12:03
I've already reported it here : https://github.com/RPCS3/rpcs3/issues/3243#issuecomment-323032676
But yeah, limiting this to the shader cache seems better. Things may get confusing if there are several identical issues opened and some are not updated.

**Comment by asbel123** [comment] 2017-10-24 20:45
there is new issue is where to go to duke dalan mansion its goes black screen and music stop i find the issue is F {rsx::thread} class std::runtime_error thrown: Verification failed (e=0x57): 
(in file ..\Utilities\VirtualMemory.cpp:83) thats the one fix its please old version doesnt do that

**Comment by Asinin3** [comment] 2017-10-24 20:46
@asbel123 Try latest master, a fix was merged half an hour ago that may fix it.

**Comment by Marthgun** [comment] 2017-10-25 00:31
I've tried running OpenGL and Vulkan on the kd's newest rsx fixes, nothing has changed.  maybe Vulkan is a tad bit faster, OpenGL is still slow and both need Strict Rendering enabled to work right, all of the issues mentioned above are still there, i.e., transparency lines, blurred skits, black-out if no delete shader cache, etc.

**Comment by Katanab** [comment] 2017-10-25 19:39
Not stuck in manor anymore, with the latest build , just tested here

**Comment by Katanab** [comment] 2017-10-25 19:39
Just turn off stric rendering mode, go to the manor, skip scenes and go back and save reload and you are set

**Comment by kd-11** [comment] 2018-01-22 12:14
Update if anything has changed

**Comment by GeniusMage** [comment] 2018-01-22 13:09
Blur in skits and black screen with existing shader cache were fixed a while ago (already reported on the forums on Dec 1st).
Do note however that the blur in skits is completely gone, while it should actually affect the background. But that's minor.
Other issues are still there, only one I can't test is the crash at the duke mansion.

**Comment by kd-11** [comment] 2018-07-14 13:35
Closing after reports of all issues being fixed.

**Closed by kd-11** 2018-07-14 13:35 UTC
