### ISSUE TITLE
"The module vulkan-1.dll was incorrectly installed"

### ISSUE THREAD

**Issue by EnforcerRidley** [RPCS3/rpcs3#15846] opened 2024-07-27 21:49 UTC
### Quick summary

![RPCS3 Fatal Error0750](https://github.com/user-attachments/assets/27bf5a65-59ab-4117-b1a9-2e64bab2aa0f)

### Details

"The module vulkan-1.dll was incorrectly installed at
'C:\WINDOWS\SYSTEM32\vulkan-1.dll''"

I get this error as soon as I run rpcs3.exe. I've been getting this error for a while now on this emulator but haven't gotten around to reporting it until now (as it wasn't a priority) but I decided to try to tackle this issue.

I'm using rpcs3-v0.0.32-16711-501e9260_win64, the latest download of the emulator as of now.

I made a post to the RPCS3 Forums but I've received no response for over a month.

### Attach a log file

Unable to locate RPCS3.log.gz nor RPCS3.log.

### Attach capture files for visual issues

![RPCS3 Folder Dir](https://github.com/user-attachments/assets/2395e463-cc52-4ca0-9474-33b7d5fa73eb)
[VkDiag_Log.txt](https://github.com/user-attachments/files/16401535/VkDiag_Log.txt)
[vulkaninfo.txt](https://github.com/user-attachments/files/16401536/vulkaninfo.txt)

### System configuration

OS: Microsoft Windows 10 Education
Version: 10.0.19045 (Windows 10 22H2)
CPU: 12th Gen Intel® Core™ i7-12700KF
GPU: NVIDIA GeForce GTX 4060 Ti
Driver version: 32.0.15.6070 (7-10-2024)
System Vulkan loader version: 1.3.280.0

### Other details

Other games and emulators not associated with RPCS3 which use Vulkan work without issue.

**Comment by AniLeo** [comment] 2024-07-28 01:50
This is not exactly an RPCS3 issue, it could be caused by incorrectly running the emulator as administrator which is a no go.

Your vkdiag shows residual registration for older NV GPUs, use DDU to fully reinstall your NVIDIA drivers and try again.

**Comment by EnforcerRidley** [comment] 2024-07-28 11:35
> This is not exactly an RPCS3 issue, it could be caused by incorrectly running the emulator as administrator which is a no go.
The emulator is not set run as administrator.
![RPCS3 Compatibility Settings](https://github.com/user-attachments/assets/57da867f-015b-4f09-bf57-774dd302435c)

> Your vkdiag shows residual registration for older NV GPUs, use DDU to fully reinstall your NVIDIA drivers and try again, ensure RPCS3 is not set to run as admin.
I ran DDU, reinstalled my NVIDIA drivers and tried again. Here's the updates:
![RPCS3 Fatal Error0750](https://github.com/user-attachments/assets/7efe8b04-13a1-4826-816d-32ac7de3a897)
[VkDiag_Log.txt](https://github.com/user-attachments/files/16403055/VkDiag_Log.txt)
[vulkaninfo.txt](https://github.com/user-attachments/files/16403056/vulkaninfo.txt)

I should note that I was having this issue even with the previous GPU. That was when I made a post to the RPCS3 Forums about the issue but it hasn't been resolved.

**Comment by EnforcerRidley** [comment] 2024-08-04 00:18
I just updated RPCS3 to rpcs3-v0.0.32-16742-0be1c41e_win64. I get the same Vulkan error as before, however a log file is now generated.
[RPCS3.log](https://github.com/user-attachments/files/16483273/RPCS3.log)

Could installing the NVIDIA drivers via NVCleanStall with these settings be the issue?
![image](https://github.com/user-attachments/assets/de7ef609-9768-4a53-9e74-2bb8b7f7989d)
![image](https://github.com/user-attachments/assets/1b20ef40-455d-4b0c-8a4d-89b8227e24bc)
![image](https://github.com/user-attachments/assets/5c2b3608-877f-4e1f-a0e1-c05f029e186e)

**Comment by kd-11** [comment] 2024-08-04 02:04
I'll push a fix for this soon.

**Closed** 2024-08-04 13:46 UTC

**Comment by EnforcerRidley** [comment] 2024-08-09 13:26
I just update to Build 0.0.32-16785, and I got this:
![image](https://github.com/user-attachments/assets/32a516ef-6045-421c-90e4-911ffa21f295)

Thank you for helping to fix this issue for me. Thank you.
