### ISSUE TITLE
God of War III (BCES00510) regression - black screen and 0.96FPS since 0.0.4 6439

### ISSUE THREAD

**Issue by Josivan88** [RPCS3/rpcs3#4237] opened 2018-03-01 18:28 UTC
Version 0.0.4 6439 (https://github.com/RPCS3/rpcs3/pull/4162)
PPU: Recompiler (LLVM)
SPU: Recompiler (ASMJIT)
SPU threads: auto
Automatically load libraries
Enable SPU loop detection
Renderer: Vulkan
Aspect 16:9
Anisotropic: Automatic
Resolution Scale: 300%
Everything else defaults.

Since this version God of War III
 no longer works, only get 0.96FPS and black screen telling:
E {rsx::thread} RSX: nv406e::semaphore_acquire has timed out. semaphore_address=0x40300510

Many users report that
https://forums.rpcs3.net/thread-188995.html
and on discord

System specs:
i7 4790 3.6GHz
Nvidia 1070GTX
16 Gb of RAM

More info atached
![problema](https://user-images.githubusercontent.com/36341425/36862111-ae26f33a-1d64-11e8-99c7-40690767ac5b.jpg)
[RPCS3.log.gz](https://github.com/RPCS3/rpcs3/files/1772333/RPCS3.log.gz)

**Comment by AniLeo** [comment] 2018-03-01 18:30
Duplicate of #4236

**Closed by AniLeo** 2018-03-01 18:30 UTC

**Comment by Josivan88** [comment] 2018-03-01 18:32
OK
