### ISSUE TITLE
Fifa Street [NPEB00822] say not enough space on the disk

### ISSUE THREAD

**Issue by greggameplayer** [RPCS3/rpcs3#4201] opened 2018-02-21 18:08 UTC
## Tested Build :
Tested in RPCS3 0.0.4-6448-1b26ec56e Alpha with Vulkan and Automatically load required libraries

## Hardware Specs : 
- Nvidia GeForce GTX 960
- AMD FX-6300
- 8 GB Of Ram
- Windows 7 Pro

## Issue :
In that game we are not able to pass through the press start screen because  a dialog appear in game in order to say that there is not enough space in the disk.
So can you correct this issue or find a solution in order to bypass this issue ?

## Log :
[→ Click Here ←](https://gist.github.com/greggameplayer/692d90a37721c36761823ffe62c08e60)

## Screenshot of that issue
[→ Click Here ←](https://imgur.com/a/d4f0J)

**Comment by hcorion** [comment] 2018-02-22 05:51
duplicate of https://github.com/RPCS3/rpcs3/issues/3506

**Comment by greggameplayer** [comment] 2018-02-22 17:12
no it's not a duplicate because here it's the game that saying that, not RPCS3.

**Comment by hcorion** [comment] 2018-02-22 17:13
It is, we're grouping all of these issues into one.

**Comment by greggameplayer** [comment] 2018-02-22 19:10
ok

**Comment by Zangetsu38** [comment] 2018-02-22 20:42
very old issue for him few game have same think

**Comment by greggameplayer** [comment] 2018-02-23 18:57
in my opinion it's just a variable to set in order to share the space of the disk inside games. But maybe it's not so easy that i think.

**Comment by greggameplayer** [comment] 2018-03-07 17:03
Anyone can fix this issue please ? @kd-11 @Nekotekina @Zangetsu38

**Comment by Asinin3** [comment] 2018-03-07 17:22
Don't tag the developers for no reason, do you see how many issues are open already? There's no need to try and get your issue fixed first over everyone else's. It will be looked at when people have time, this is also a duplicate of #3506 and should be closed as hcorion said.

**Closed** 2018-03-08 00:05 UTC
