### ISSUE TITLE
Heavenly Sword (BCUS98132) colors broken on Intel UHD 630 (Vulkan only)

### ISSUE THREAD

**Issue by Wagnard** [RPCS3/rpcs3#8866] opened 2020-09-08 13:59 UTC
Hi,
Heavenly Sword (BCUS98132) have weird pink colors everywhere on Intel UHD 630 (Vulkan only).
There is no issue on OpenGL
[RPCS3.log.gz](https://github.com/RPCS3/rpcs3/files/5188764/RPCS3.log.gz)

![2020-09-08](https://user-images.githubusercontent.com/11493785/92486300-ea473380-f1b9-11ea-80c7-6b672c1c3fd2.png)

Windows 10 (2004) with Intel driver 27.20.100.8587
i9 9900K
Asus Strix Z390-H
32GB Ram

RSX capture: https://www.wagnardsoft.com/BCUS98132_20200908101234_capture.zip

**Comment by AniLeo** [comment] 2020-09-08 14:07
Needs testing with anv on an unix based OS

**Comment by AniLeo** [comment] 2020-09-08 14:10
Missing RSX Capture as indicated on the issue guidelines

If you describe graphical issue, please provide an RSX capture and a RenderDoc capture that demonstrate it.
* To create an RSX capture, use _Create_ _RSX_ _Capture_ under _Utilities_.
Captures will be stored in RPCS3 folder → captures.
	+ Compress your capture with 7z, Rar etc. 
	And	drag and drop it into the issue.
	+ Or upload it to the cloud, such as Dropbox, Mega etc.

**Comment by Wagnard** [comment] 2020-09-08 14:15
RSX capture added in first post.

**Comment by AniLeo** [comment] 2020-09-08 14:27
RSX Replay mechanism seems to be buggy, I get a black screen while replaying that, cc @kd-11 

However, I'm inclined towards thinking this is an Intel proprietary driver issue, as I've seen this pattern in the past in issues such as #4979 (although it was never confirmed), and also because this game has been widely tested on AMD and NVIDIA without reports of such artifacts

I may be able to test this eventually, I have the game but not at hand right now. That happens right away in the beginning of the game or only starts at that checkpoint?

**Comment by Wagnard** [comment] 2020-09-08 14:33
It's everywhere except videos and the main menu.

**Comment by kd-11** [comment] 2020-09-09 08:38
```
·! 0:05:06.111185 RSX: Found vulkan-compatible GPU: 'Intel(R) UHD Graphics 630' running on driver 0.402.395
·E 0:05:06.111319 RSX: Your GPU does not support depth bounds testing. Graphics may not work correctly.
·! 0:05:06.111325 RSX: GPU/driver supports float16 data types natively. Using native float16_t variables if possible.
·W 0:05:06.120434 RSX: Unsupported device: Intel(R) UHD Graphics 630
```
1. Intel hardware does not have bounds checking which can cause problems. Obviously replaying the capture is pointless, if it is executed on other GPUs it will render correctly. I'll still take a look to figure out why its even rendering on OpenGL, but that could very well be because of...
2. MSAA is enabled. Please disable it, until we validate that intel behaves correctly in the compute passes. Retest and update if problem is still present.

**Comment by Wagnard** [comment] 2020-09-09 14:59
Disabling MSAA workaround the issue. I guess it must be something with the Intel driver as with MSAA enabled, it work with Opengl.

**Comment by AniLeo** [comment] 2020-09-09 15:00
Note that we don't have MSAA implemented on OpenGL, so even if you enable it while using OpenGL it does nothing

**Comment by digitaldude555** [comment] 2021-02-05 18:20
@Wagnard update?

**Comment by Wagnard** [comment] 2021-02-05 20:45
> @Wagnard update?

I have not tried to re-enable MSAA with Vulkan with that Intel UHD 630. (the computer is not avail ATM)
Will do later if the devs are asking me to test again.

**Comment by Megamouse** [comment] 2021-12-15 21:10
Please test again @Wagnard

**Comment by YuriNator557** [comment] 2021-12-15 21:35
would this not be related to #6199 ?

**Comment by Wagnard** [comment] 2021-12-21 04:26
@Megamouse Still not working correctly with Intel UHD 630. instead of pink stuff , now the screen is mostly black.
No issue with Antialiasing disabled. tested on 13109

**Comment by BiZkViT96** [comment] 2022-12-18 05:38
Has the bug been fixed? UHD 770 driver 30.0.101.3790 Windows 11 Since Anti-Aliasing was set to Auto, the game is not running at full speed. But game runs full speed if AA is disabled.

I don't know if it makes sense to create a new bug report, but I had to change a couple of settings to make the game work properly. RSX FIFO accuracy: should be set to Atomic and in the config Stub PPU Traps: 1 instead of 0. If this is not do the game will crash.
![2022-12-18 12_20_37-FPS_ 22 21 _ Vulkan _ 0 0 25-14489 _ Heavenly Sword™   BCUS98132](https://user-images.githubusercontent.com/88586431/208283175-49478345-9195-4f40-952a-a816d9d3e56f.png)

**Comment by kd-11** [comment] 2022-12-18 10:34
Intel drivers have been improving, so maybe it is indeed fixed. We can close the issue if no more reports of AA being broken are reported.

**Comment by AniLeo** [comment] 2023-01-29 14:10
Closing as assumed fixed due to the screenshot from UHD 770 above without the issue when using Anti Aliasing = Auto. If you can still reproduce on UHD 630, ask for the ticket to be reopened please.

**Closed by AniLeo** 2023-01-29 14:10 UTC
Labels: Need Information, Render: Vulkan, Driver: Intel
