### ISSUE TITLE
[BCUS98296] Gran Turismo 6: RSXIO memory not mapped

### ISSUE THREAD

**Issue by kirbyguy22** [RPCS3/rpcs3#5802] opened 2019-04-07 23:07 UTC
Upon attempting to purchase your first car, the game will stop with this error message:
`RSX: class std::runtime_error thrown: GetAddress(offset=0x358df80, location=0x1): RSXIO memory not mapped
(in file c:\projects\rpcs3\rpcs3\emu\rsx\rsxthread.cpp:67)`

Log:
[RPCS3_gt6_7933.log.gz](https://github.com/RPCS3/rpcs3/files/3052124/RPCS3_gt6_7933.log.gz)

**Comment by kirbyguy22** [comment] 2019-04-07 23:40
Updating Gran Turismo 6 to version 1.02 fixes this issue, not sure if I should close this.

**Comment by elad335** [comment] 2019-04-15 04:35
If the issue is game version specific theres no reason to close.
just state the versions it works and tge versions it doesnt.

**Comment by kirbyguy22** [comment] 2019-04-15 05:11
Sorry, reopening. Issue still persists on 7981 on version 1.00 only. 1.02 and above will progress, but it will progress very slowly with this error message constantly printing:
`E {RSX [0x12b60bc]} RSX: nv406e::semaphore_acquire has timed out. semaphore_address=0x70300570`
It'll take a few minutes but it will eventually progress and return to normal speed.

Log file for 1.02 running on 7981
[RPCS3_gt6_7981.log.gz](https://github.com/RPCS3/rpcs3/files/3078502/RPCS3_gt6_7981.log.gz)

**Comment by jenci8888** [comment] 2019-07-18 18:36
This game on v1.00 version is fixed in #6224 PR.
![image](https://user-images.githubusercontent.com/40495799/61482761-a97bd200-a99b-11e9-869f-fd60a4913f83.png)

**Comment by aabd2** [comment] 2020-07-05 20:23
This issue does still happen on BCES01893 version 1.00

**Closed** 2021-01-10 15:40 UTC
