### ISSUE TITLE
Sly 2 and Sly 3 think saves are corrupted when manually saving

### ISSUE THREAD

**Issue by SlyCooperReloadCoded** [RPCS3/rpcs3#10569] opened 2021-07-18 00:07 UTC
## Quick summary
Letting Sly 2 and Sly 3 autosave on their own works and produces working save files, however manually selecting the "Save Game" option makes them think that the save data is corrupted, and it'll turn off autosaving.

## Details

Letting Sly 2 and Sly 3 autosave on their own works and produces working save files, however manually selecting the "Save Game" option makes them think that the save data is corrupted, and it'll turn off autosaving.  This affects all the digital versions and disc versions (NPUA80664, NPUA80665, NPHA80175, NPHA80176, NPEA00342, NPEA00343, BCUS98246, and BCJS30061).  Note that the manual saves do work, save data is saved, but the game doesn't realize this.

#### 1. Please attach RPCS3's log.

[RPCS3.log.gz](https://github.com/RPCS3/rpcs3/files/6835455/RPCS3.log.gz)

#### 3. Please attach screenshots of your problem.

![RPCS3](https://user-images.githubusercontent.com/58268914/126051873-ccafb53f-f76f-4bec-af48-d5b982953249.PNG)

#### 4. Please provide comparison with real PS3.

Real PS3 doesn't display this, it just closes the menu and the save completes.

#### 5. Please provide your system configuration:
* Windows 10 19043
* Intel Core i9-10900K
* NVIDIA RTX 2080 Super
* 466.27

#### Please include.
* Solving issue #8708 did not solve this.  It's existed since the games reached the menus for the first time.

**Comment by Yoshi9800** [comment] 2021-07-18 17:26
@Megamouse maybe like cause problem sky 2 and 3 saving and how going get fixed once this is fixed sly 2 added to playable. Sly 3 is really hard on cpu specs.

**Comment by YuriNator557** [comment] 2021-08-19 12:26
Manually saving the game to a new slot now works as intended for both Sly 2 and Sly 3. Unfortunately it still gives the same error message if you try to overwrite a save.

**Comment by SlyCooperReloadCoded** [comment] 2021-08-19 21:07
That's always worked.  The issue is saving to an existing save slot.

**Comment by YuriNator557** [comment] 2021-08-19 21:10
> That's always worked. The issue is saving to an existing save slot.

Strange, I remember it not working at some point, that's why I thought it was worth mentioning

**Comment by YuriNator557** [comment] 2023-03-04 19:37
Fixed by #13492 

https://user-images.githubusercontent.com/76178650/222925468-a47a44cc-8b98-4bf6-9c5d-71656f72ac98.mp4


https://user-images.githubusercontent.com/76178650/222925474-c93d39c4-5e23-4ee6-a19a-185edcebb040.mp4

**Closed** 2023-03-07 12:01 UTC
Labels: Savedata
