### ISSUE TITLE
Dengeki Bunko: Fighting Climax Ignition [NPJB00785] - Green Outlines

### ISSUE THREAD

**Issue by SuchMisfortune** [RPCS3/rpcs3#10014] opened 2021-03-23 20:14 UTC
RPCS3 Version:
rpcs3-v0.0.15-11997-2f333424 Alpha

Every time I launch the game, everything looks normal until I reach the Character selection, where everyone has this disgusting green texture. I've tried messing with my settings multiple times and, still no luck.

OS: Windows 10 x64
CPU: Intel (R) Core(TM) i5-8400 CPU @ 2.80GHz 2.81 GHz
GPU: Intel (R) UHD Graphics 630
Ram: 8GB

![Screenshot (6218)](https://user-images.githubusercontent.com/81260753/112204656-49b2e100-8bea-11eb-8ed8-125fc000f25b.png)
![Screenshot (6229)](https://user-images.githubusercontent.com/81260753/112208578-e5dee700-8bee-11eb-920a-e517b5116276.png)

Log:
[RPCS3.log](https://github.com/RPCS3/rpcs3/files/6192341/RPCS3.log)

**Comment by MsDarkLow** [comment] 2021-03-23 20:56
Doesn't seem to be an issue with novideo, RTX 3080 (461.92). You seem to be an intel igpu user, so that's likely to be the major issue here, even if its on the latest driver.
![@MsLow#2316](https://user-images.githubusercontent.com/9060436/112217204-46cfe480-8c1a-11eb-9c5d-5826ace1f41a.jpg)
![#anime](https://user-images.githubusercontent.com/9060436/112217210-48011180-8c1a-11eb-836c-3e447acacaa6.jpg)
[RPCS3.log.gz](https://github.com/RPCS3/rpcs3/files/6192668/RPCS3.log.gz)

**Comment by SuchMisfortune** [comment] 2021-03-23 21:34
So, unless I get a different GPU type, I'll be stuck with the green sprites?

Also, on an older build, I didn't get these green sprites when I tested P4AU. I might try an older version and see if it still pops up.

**Comment by SuchMisfortune** [comment] 2021-03-25 16:58
> Doesn't seem to be an issue with novideo, RTX 3080 (461.92). You seem to be an intel igpu user, so that's likely to be the major issue here, even if its on the latest driver. (edit: be sure to have it updated nonetheless!)
> ![@MsLow#2316](https://user-images.githubusercontent.com/9060436/112217204-46cfe480-8c1a-11eb-9c5d-5826ace1f41a.jpg)
> ![#anime](https://user-images.githubusercontent.com/9060436/112217210-48011180-8c1a-11eb-836c-3e447acacaa6.jpg)
> [RPCS3.log.gz](https://github.com/RPCS3/rpcs3/files/6192668/RPCS3.log.gz)

So, unless I get a different GPU type, I'll be stuck with the green sprites?

Also, on an older build, I didn't get these green sprites when I tested P4AU. I might try an older version and see if it still pops up.

**Comment by SeongGino** [comment] 2021-09-18 13:24
Going to corroborate this.

Windows 10 2004, Intel i7 4790k, NVIDIA GTX 1060 6GB w/ 471.96.

![ew](https://user-images.githubusercontent.com/7321839/133890299-aded9df1-8e73-459d-adb0-1372a5116bb7.png)
![Untitled](https://user-images.githubusercontent.com/7321839/133890412-a8442fb1-e37f-40fa-a946-e5ffde2d5e9e.png)

Sidenote, RPCS3 wasn't toggling the `Enable GPU Texture Scaling` bit properly for DBFCI on its own; I had to manually modify the custom yml, as was suggested in #6090.

[RPCS3.log.gz](https://github.com/RPCS3/rpcs3/files/7189951/RPCS3.log.gz)

**Comment by Asinin3** [comment] 2021-09-18 13:28
Set anisotropic filtering to auto. Looks like same issue blazblue has when using it... Always try default settings before making issue report. I'm not 100% sure auto will fix it but it looks like it will.

**Comment by Asinin3** [comment] 2021-09-24 04:45
Closing, ask to re-open if I was wrong about anisotropic filtering but this bug looks **exactly** like it was caused by it. Regardless of the log in OP having it off, the other posters had it on. And OP log is more than likely old/wrong.

**Closed by Asinin3** 2021-09-24 04:45 UTC
Labels: Need Information

**Comment by SeongGino** [comment] 2021-11-17 03:13
Can confirm, setting Anisostrophic Filtering to Auto fixes player rendering
![2021-11-16_221237](https://user-images.githubusercontent.com/7321839/142127930-67d4410c-1db5-496b-8400-eefa7c16e64e.png)
.
