### ISSUE TITLE
Accurate PPU Non-Java Mode/PPU Decoder setting bug.

### ISSUE THREAD

**Issue by Satan86** [RPCS3/rpcs3#12832] opened 2022-10-18 00:43 UTC
### Quick summary

This is a very specific setting/UI bug. When you set PPU Decoder to Interpreter, it allows the user to toggle Accurate PPU Non-Java Mode, which is greyed out on LLVM, but if you set the PPU Decoder back to LLVM, it greys out the setting again, but it doesn't turn it off, and this causes games to crash on boot with `F {PPU[0x1000000] main_thread} SIG: Thread terminated due to fatal error: NJ Not implemented (in file C:\Users\ContainerAdministrator\AppData\Local\Temp\cirrus-ci-build\rpcs3\Emu\Cell\PPUThread.cpp:3652[:115], in function ppu_initialize)`. Of course, changing back to Interpreter allows you to turn off the setting, but it should turn off automatically as you set PPU LLVM.

### Attach a log file

[RPCS3.log.gz](https://github.com/RPCS3/rpcs3/files/9805410/RPCS3.log.gz)

**Comment by Megamouse** [comment] 2022-10-18 06:14
I think it shouldn't be toggled.
It should just not crash, but log some warning instead or something like that

**Comment by elad335** [comment] 2022-10-18 08:14
Maybe disabled in gui.

**Comment by Darkhost1999** [comment] 2022-10-18 13:34
How other settings work is that the GUI disables and deactivates settings that are incompatible with each other.
Like when you enable strict rendering mode for example. I believe when you disable strict render it even restores the settings that were Disabled to what the user set them to.

But I do like the idea of a warning and it saying "accurate non java mode is unimplemented when using LLVM. In order to use this setting please continue using PPU Interpreter. Switching to non-java mode fixup. Or disabling for this run."
At least until it's implemented into LLVM.

**Comment by Darkhost1999** [comment] 2022-11-09 20:13
Testing the PR but Master acts the same. Aka not caused by PR
File -> all titles -> create PPU cache

![image](https://user-images.githubusercontent.com/60384196/200929363-da337773-71ff-422d-9547-a49536ff7e16.png)

Closing the game window just continues to the next game so I got multiple examples here in my log
[RPCS3.log](https://github.com/RPCS3/rpcs3/files/9974728/RPCS3.log)
But for some reason Batch creator only partially loads your custom config and

![image](https://user-images.githubusercontent.com/60384196/200930373-03fcb860-367d-4143-b29b-f7a1bff5ad2c.png)

Meanwhile, ignoring batch creator and going to normal natural boot
`U SYS TODO: The setting 'PPU Accurate Non-Java Mode' is currently not supported with PPU decoder type 'Recompiler (LLVM)' and will therefore be disabled during emulation.` everything works just fine for the intent and solves the issue.
[RPCS3.log](https://github.com/RPCS3/rpcs3/files/9974774/RPCS3.log)

**Comment by Megamouse** [comment] 2022-11-09 22:20
The Fatals in batch creation are probably also fixed in the PR now.

**Comment by Darkhost1999** [comment] 2022-11-09 22:39
Unfortunately not yet 
![image](https://user-images.githubusercontent.com/60384196/200957097-fd3a5194-139f-494d-80ad-930c751ab804.png)
[RPCS3.log](https://github.com/RPCS3/rpcs3/files/9975660/RPCS3.log)
although the intended issue is solved

**Comment by Darkhost1999** [comment] 2022-11-09 22:43
This just presents itself as if that the batch creator knows I'm using accurate non-java mode but that it doesn't know if I'm using Interpreter or llvm

**Comment by Megamouse** [comment] 2022-11-09 22:50
Then it would also fail with static set in all configs of the games that currently fail

**Comment by Darkhost1999** [comment] 2022-11-09 23:01
Yea it does fail for every game I have accurate non-java mode enabled for and ppu interperter selected. It's only needed for Assassin's Creed Brotherhood through to rogue. So Assasssin's Creed 1 and 2 are safe and don't need those settings.
But you're right and I don't know if how it presents itself is how it is.

**Comment by Megamouse** [comment] 2022-11-09 23:14
The issue here is that it will fail with static on different modules during gameplay as well, not only with precompilation.
But I don't know if I can just disable the checks in general, since there are other places that also check these flags.

So it might indeed be better to disable the setting in the config and then just tell the users with old "dirty" configs to save the settings dialog to "clean up" those settings.

**Comment by Megamouse** [comment] 2022-11-09 23:18
ugh, this makes no sense either xD

**Comment by Megamouse** [comment] 2022-11-10 00:19
The next build should fix the issue during Create PPU Caches.

**Comment by Darkhost1999** [comment] 2022-11-10 00:39
Thanks now it just skips compiling for those games and logs the todo message. Works for me.

**Closed** 2022-11-12 08:23 UTC
Labels: Bug
