### ISSUE TITLE
[Feature request] Ignore Windows Keyboard Language Influence On Pads

### ISSUE THREAD

**Issue by sampletext32** [RPCS3/rpcs3#8072] opened 2020-04-20 21:13 UTC
I've got Windows 10 with Russian Localization and while I'm without an actual gamepad I've had to do some tests with keyboard as a PAD.
I found out that RPCS3 completely ignores my keyboard clicks when it's not in english.
Easy auto-fix - set keyboard language to english.

I think this is kind of annoying, it took me a couple of minutes to figure out why my pads aren't working. I think that emulation should work with any kind of keyboard, no matter of system language.

Here is my pads setup.
![image](https://user-images.githubusercontent.com/44116740/79799901-ed08cf80-8363-11ea-8330-e3d772ddbbc1.png)

I've been doing tests with [BCES01585] but I think it's irrelevant for this kind of problem.

Here is a log, as requested, but I think, it's also irrelevant.
[RPCS3.log.gz](https://github.com/RPCS3/rpcs3/files/4506196/RPCS3.log.gz)

**Comment by Megamouse** [comment] 2020-04-20 21:16
duplicate of #3452

**Comment by sampletext32** [comment] 2020-04-20 21:18
> duplicate of #3452

My bad. But quick lookup over repository showed nothing, so - decided to open.

**Closed** 2020-04-20 22:20 UTC
Labels: Meta: Duplicate
