### ISSUE TITLE
Regression: TIME CRISIS: RAZING STORM [BLUS30528] TC4 has bloom issues on Vulkan now

### ISSUE THREAD

**Issue by legend800** [RPCS3/rpcs3#4949] opened 2018-08-01 02:36 UTC
Within the past month or so, the gfx on Time Crisis 4 have regressed and now wash everything out on Vulkan. WCB is on and tried numerous other gfx related settings but didn't find a fix. OpenGL doesn't have this issue but it slower AND has some weird vertical lines (also seem bloom related).

Vulkan:
![2018-07-31 19_22_33-window](https://user-images.githubusercontent.com/20983844/43497828-ff04a41c-94f8-11e8-8d45-fef9f07cae0d.png)

OpenGL:
![2018-07-31 19_24_15-window](https://user-images.githubusercontent.com/20983844/43497837-02ca71da-94f9-11e8-9f84-62a12af154df.png)

OpenGL vertical artifacts example:
![2018-07-31 19_24_35-window](https://user-images.githubusercontent.com/20983844/43497848-09bfd02a-94f9-11e8-8c0d-406d9785b0fd.png)

[RPCS3.log.gz](https://github.com/RPCS3/rpcs3/files/2247813/RPCS3.log.gz)

Config:
Windows 10 64-bit
GeForce GTX 1080
i7-6700k @ 4GHZ
16GB RAM

**Comment by legend800** [comment] 2018-09-06 00:37
@kd-11 Just FYI, this is still an issue on today's mainline (9/4). Let me know if there's anything else I can provide.

**Comment by ruipin** [comment] 2018-11-03 15:38
I tried latest master and could sadly not reproduce this issue. It might be system-dependent?

**Comment by kd-11** [comment] 2018-12-04 11:01
"Vertical artifacts" is the camera looking into a barrier, not an RSX issue. You can see this on a PS3 [here]( https://youtu.be/mQJ5KNpLKc0?t=171)
I cannot reproduce the bloom issues with the original TC4 release [BLUS30093]. Can you confirm that only the Razing Storm version is affected?

**Comment by legend800** [comment] 2018-12-05 04:32
Strange. I can't image the games are different enough to cause rendering deltas, but maybe.

Check today's master and no change:
-- OGL has lines that are not there in Vulkan
-- Vulkan has bad bloom, fine on OGL - rsx capture here:
[BLUS30528_20181204201738_capture.zip](https://github.com/RPCS3/rpcs3/files/2647188/BLUS30528_20181204201738_capture.zip)

VK:
![vk](https://user-images.githubusercontent.com/20983844/49490177-8d0f9880-f803-11e8-8dfa-6b4d4744331b.png)

OGL:
![2018-12-04 20_25_09-window](https://user-images.githubusercontent.com/20983844/49490183-94cf3d00-f803-11e8-8a20-a23a253934de.png)

![2018-12-04 20_24_32-window](https://user-images.githubusercontent.com/20983844/49490184-94cf3d00-f803-11e8-8504-2aed53ea668d.png)

Thanks for looking into this.

**Comment by legend800** [comment] 2018-12-19 16:38
Fixed by https://github.com/RPCS3/rpcs3/pull/5404

**Comment by legend800** [comment] 2019-01-14 02:30
Aaaand rebroken on today's master. :( Even broken on OpenGL this time too.

![2019-01-13 18_05_05-window](https://user-images.githubusercontent.com/20983844/51094378-477aaf80-1761-11e9-9324-956215f05925.png)

**Comment by RainbowCookie32** [comment] 2019-01-14 02:33
> 
> 
> Aaaand rebroken on today's master. :( Even broken on OpenGL this time too.
> 
> ![2019-01-13 18_05_05-window](https://user-images.githubusercontent.com/20983844/51094378-477aaf80-1761-11e9-9324-956215f05925.png)

Can you find which build caused the regression? It'd probably be useful for devs to fix it

**Comment by legend800** [comment] 2019-01-14 06:14
Reintroduced by https://github.com/RPCS3/rpcs3/pull/5427

**Comment by kd-11** [comment] 2019-01-17 10:01
Duplicate of https://github.com/RPCS3/rpcs3/issues/5514

**Closed by kd-11** 2019-01-17 10:01 UTC
