### ISSUE TITLE
Gran Turismo 5 [BCUS98114] crash on loading circuit after PR6213 0.0.6-8391 VK_ERROR_DEVICE_LOST with antialiasing on

### ISSUE THREAD

**Issue by Pontifice** [RPCS3/rpcs3#6258] opened 2019-07-24 16:50 UTC
When loading a circuit 

It fails with error 

`·F 0:01:41.675731 {RSX [0x0a4efd0]} RSX: class std::runtime_error thrown: Assertion Failed! Vulkan API call failed with unrecoverable error: Device lost (Driver crashed with unspecified error or stopped responding and recovered) (VK_ERROR_DEVICE_LOST) (in file c:\projects\rpcs3\rpcs3\emu\rsx\vk\vkhelpers.h:1051)`

It doesn't matter if i choose SPU ⁪Block ⁪Size Safe or Mega, SPU Decorder LLVM or ASMJIT, or PPU Decoder LLVM or Interpreter (fast)

I had attached logs from previous version (8386-397e5dd1), this version (8391-ea2f4d57 #6213) and the last at the moment (8412-49aefc07)

[RPCS3-8386.log.gz](https://github.com/RPCS3/rpcs3/files/3427847/RPCS3-8386.log.gz)
[RPCS3-8391.log.gz](https://github.com/RPCS3/rpcs3/files/3427848/RPCS3-8391.log.gz)
[RPCS3-8412.log.gz](https://github.com/RPCS3/rpcs3/files/3427901/RPCS3-8412.log.gz)

**Comment by RainbowCookie32** [comment] 2019-07-24 16:54
Is it a specific circuit? I've been playing for a few days now without issues

**Comment by Pontifice** [comment] 2019-07-24 17:03
I know it works for some people, maybe it's related to non-tsx path (old cpu)

At least it fails loading tsukuba, high speed ring, monza ... 

If i did not load a circuit before and i try it on MASTER i could get to see the circuit menu, probably because some shaders were compiling and that delayed the failure

![image](https://user-images.githubusercontent.com/31481691/61813278-98244100-ae45-11e9-9759-11ef4c458702.png)

**Comment by RainbowCookie32** [comment] 2019-07-24 17:10
Can't reproduce here, R7 1700 and RX570 and it works just fine. Maybe someone else can

**Comment by spyropt** [comment] 2019-07-24 18:43
same problem llvm spu
[RPCS3.log.gz](https://github.com/RPCS3/rpcs3/files/3428296/RPCS3.log.gz)

asmjit spu
[RPCS3.log.gz](https://github.com/RPCS3/rpcs3/files/3428301/RPCS3.log.gz)

![image](https://user-images.githubusercontent.com/34097932/61819447-fe5f9280-ae4a-11e9-8f35-730f992f6211.png)


gt6 sound stops worjking and after i just get an endless loading screen
![image](https://user-images.githubusercontent.com/34097932/61819645-5b5b4880-ae4b-11e9-882e-2fd95bb1f2fe.png)

**Comment by kd-11** [comment] 2019-07-24 18:44
@Pontifice Install vulkan SDK from here: https://vulkan.lunarg.com/sdk/home#windows and then enable the debug option called "debug output". If you do not have access to the debug tab, you can edit this directly in the config file and change the value to true. Once you have this, run the game until it crashes then attach the new log. You will know the option took effect because performance will be terrible. Attach the new log with SDK messages here.

**Comment by RainbowCookie32** [comment] 2019-07-24 18:46
To enable the debug tab go to GuiConfigs on RPCS3's folder, open CurrentSettings.ini, and change showDebugTab=false to showDebugTab=true

**Comment by spyropt** [comment] 2019-07-24 19:04
is this ok?
[RPCS3.log.gz](https://github.com/RPCS3/rpcs3/files/3428393/RPCS3.log.gz)

**Comment by Pontifice** [comment] 2019-07-24 19:10
[RPCS3.log.gz](https://github.com/RPCS3/rpcs3/files/3428414/RPCS3.log.gz)

**Comment by kd-11** [comment] 2019-08-19 19:14
Looks like its a spurious crash. The debug layers don't see any reason why the crash should be happening.
Give https://github.com/RPCS3/rpcs3/pull/6376 a try, fixes a different crash in GT6.

**Comment by Pontifice** [comment] 2019-08-20 13:56
No luck, i attach another log from #6376, but it seems to be the same


[RPCS3.zip](https://github.com/RPCS3/rpcs3/files/3520946/RPCS3.zip)

**Comment by Pontifice** [comment] 2019-09-02 12:27
I have narrowed the problem to Anti-Aliasing, with it disabled it works, the last version i tried is PR6467 (i don't want to link to the pr)

I will not close the issue unless instructed, in case kd-11 wants to investigate it farther

**Comment by kd-11** [comment] 2019-09-02 12:32
The challenge here is reproducing the crash and determining the cause. I haven't encountered this yet (I have both AMD and NV cards for reference, but AMD CPU). Without easy way to reproduce debugging becomes difficult.

**Comment by kd-11** [comment] 2019-10-01 18:04
Still happening with latest builds?

**Comment by HHCHunter** [comment] 2019-10-04 05:11
> 
> 
> Still happening with latest builds?

@kd-11 Yeah I can confirm this is still happening in latest builds, it seems shader related as I only noticed it after I completely wiped my shaders for this game.

It's VULKAN specific

**Comment by kd-11** [comment] 2019-10-04 10:13
Does Anti-aliasing work at standard resolution?

**Comment by HHCHunter** [comment] 2019-10-04 11:02
> 
> 
> Does Anti-aliasing work at standard resolution?

Nope, it crashes with Vulkan Error

**Comment by kd-11** [comment] 2019-10-04 12:59
Which vulkan error? VkTexture.cpp error or driver crash error (DEVICE_LOST)?

**Comment by HHCHunter** [comment] 2019-10-04 13:32
> driver crash error (DEVICE_LOST)?

This one

**Comment by HHCHunter** [comment] 2019-10-27 08:09
@Pontifice Can we rename this issue to 
"Gran Turismo 5 - Anti-Aliasing: Auto = (VK_ERROR_DEVICE_LOST)"
Since that seems to be the actual issue?

@kd-11 Sorry for spam, I can see you've already assigned yourself to the issue.
However just pinging since I've updated the issue with more information, and also updated for latest build/ closed pull.

**Comment by kd-11** [comment] 2020-02-24 18:10
Is this still an issue? I recently went cleaning the vulkan code to avoid crashing, should be ok now.

**Comment by Pontifice** [comment] 2020-02-24 18:36
No more VK_ERROR_DEVICE_LOST, but for me it only works with antialiasing off, so another issue, i will try to open a new issue.

Thanks

**Comment by kd-11** [comment] 2020-02-24 18:43
What happens if antialiasing is on? Crash? hang? I don't understand what you mean by saying it doesn't work.

**Comment by Pontifice** [comment] 2020-02-24 21:28
My bad, the first time i tried with antialiasing on it seems it was still compiling and the error was lost in the log.

With antialising on i still get 

F {RSX [0x19e4f74]} RSX: class std::runtime_error thrown: Assertion Failed! Vulkan API call failed with unrecoverable error: Device lost (Driver crashed with unspecified error or stopped responding and recovered) (VK_ERROR_DEVICE_LOST)
(in file C:\projects\rpcs3\rpcs3\Emu\RSX\VK\VKHelpers.cpp:912)

**Comment by kd-11** [comment] 2020-05-26 19:02
Still crashing?

**Comment by Pontifice** [comment] 2020-05-26 19:55
With the last version 0.0.10-10429 there are some new issues so i am not able to go to a race

1.- It does not recognize my previous savegames

2.- when going in to the GT Mode for the first time, for a demonstration, it crashes with every setting i tried

```
F {RSX [0x1a89430]} SIG: Thread terminated due to fatal error: Assertion Failed! Vulkan API call failed with unrecoverable error: Device lost (Driver crashed with unspecified error or stopped responding and recovered) (VK_ERROR_DEVICE_LOST)
(in file d:\a\1\s\rpcs3\Emu\RSX\VK\VKHelpers.h:3165)
```

**Comment by Pontifice** [comment] 2020-05-27 09:47
Update with "Interpreter (fast)" for PPU (and antialiasing on for the purpose of this thread), it recognizes the savegames again (strange?) when going to a race it crashes with 

```
F {RSX [0x1944b28]} SIG: Thread terminated due to fatal error: Assertion Failed! Vulkan API call failed with unrecoverable error: Device lost (Driver crashed with unspecified error or stopped responding and recovered) (VK_ERROR_DEVICE_LOST)
(in file d:\a\1\s\rpcs3\Emu\RSX\VK\VKHelpers.cpp:957)
```

**Comment by kd-11** [comment] 2020-06-03 20:06
![image](https://user-images.githubusercontent.com/15904127/83683802-9e9b5180-a5ee-11ea-97a2-6f7a82bba230.png)
I am not able to recreate this crash. This is a practice track on a 1050Ti with Antialiasing on and it loaded just fine. There is some other problems related to zcull and vulkan that I found when running this with SDK output enabled, but antialiasing itself doesn't seem to affect much.
I am using everything default here except for SDK debug output and using PPU interpreter instead of LLVM.

**Comment by xddxd** [comment] 2020-06-03 20:19
One of the tracks affected is SSR7.

**Comment by kd-11** [comment] 2020-06-04 17:53
I was finally able to see the problem. Doesn't crash for me, but I can see why AA would cause crashing from some logs. With extra PPU threads the game doesn't hang on startup for me anymore which made it impossible to debug before.

**Comment by kd-11** [comment] 2020-06-04 18:58
Should be fixed by https://github.com/RPCS3/rpcs3/pull/8347. Retest when the build is ready.

**Closed** 2020-06-05 14:19 UTC
