### ISSUE TITLE
Can't run games in RPCS3 anymore (thread deadlocking?)

### ISSUE THREAD

**Issue by Mandraxon** [RPCS3/rpcs3#10517] opened 2021-07-08 01:35 UTC
## Quick summary
Please briefly describe what is not working correctly.

## Details
None of my games run anymore in RPCS3. I believe this is due to the SPU cache not fully loading, though there could be other issues. Also, I receive fatal errors when trying to stop emulation, and I get a text box saying "Some thread has probably deadlocked. Aborting." I'm using Vulkan for the renderer, though switching to OpenGL did not seem to make a difference. I also tried to use the fast interpreter for PPU Decoder and the ASMJIT Recompiler for SPU Decoder. The SPU block size is set to Safe and Preferred SPU Threads is at 2.

#### 0. Make sure you're running with settings as close to default as possible
* **Do NOT enable any emulator game patches when reporting issues**
* Only change settings that are required for the game to work

#### 1. Please attach RPCS3's log.

[RPCS3.log](https://github.com/RPCS3/rpcs3/files/6780832/RPCS3.log)

#### 3. Please attach screenshots of your problem.
See attached images here: https://imgur.com/a/WnVOx1L

#### 5. Please provide your system configuration:
* OS: Windows 10
* CPU: AMD Ryzen 7 3700X 8-Core Processor                3.59 GHz
* GPU: NVIDIA GeForce RTX 3070
* Driver version: 471.11
* 16 GB of RAM

#### Please include.
* Ran Ico & Shadow of the Colossus collection just fine with the settings mentioned above about 3 months ago (I don't remember what specific build I was on).

**Comment by AniLeo** [comment] 2021-07-08 02:04
Duplicate of #10486 since you have that enabled with 471.11

Multithreaded RSX is also enabled for no reason, no game *needs* that to work

> **Only change settings that are required for the game to work**

**Closed by AniLeo** 2021-07-08 02:04 UTC
