### ISSUE TITLE
Regression: Heavy Rain glitched textures PR5726

### ISSUE THREAD

**Issue by Xcedf** [RPCS3/rpcs3#5872] opened 2019-04-20 20:19 UTC
Heavy Rain broken texturing of characters, regressed after https://github.com/RPCS3/rpcs3/pull/5726 commit 74eeacd0
here's the current state
![33](https://user-images.githubusercontent.com/7060586/56461885-953b2f80-63c2-11e9-8179-ea99aee3ad4c.jpg)
And some old version with 74eeacd0 reverted
![32](https://user-images.githubusercontent.com/7060586/56461890-adab4a00-63c2-11e9-9858-8567ca0a61d9.jpg)
here's the log
[RPCS3.log.gz](https://github.com/RPCS3/rpcs3/files/3100568/RPCS3.log.gz)

**Comment by kd-11** [comment] 2019-05-01 11:54
Need some kind of trace to even attempt debugging this. You can also check if https://github.com/RPCS3/rpcs3/pull/5895 has any effect on it.

**Comment by Xcedf** [comment] 2019-05-01 15:04
Nope #5895 doesn't fix it, and what kind of trace?

**Comment by kd-11** [comment] 2019-05-01 17:50
RRC and/or RDC

**Comment by Xcedf** [comment] 2019-05-01 19:03
RenderDoc
https://mega.nz/#!XM50lIjA!Beb__Wk_qzNWsPa_QF5bR2dskpsWmRFOeRxhn7nWuWU

**Comment by Xcedf** [comment] 2019-05-02 21:16
Made some more debugging of this to minimize the revert, i found that smth wrong in surface_store.h queue_tag function, so i made this diff with equations based on previous file state, 
[heavy_rain.zip](https://github.com/RPCS3/rpcs3/files/3139982/heavy_rain.zip)
maybe it'll help

**Comment by kd-11** [comment] 2019-05-03 10:34
Unfortunately those old equations often read out of bounds and are therefore incorrect (they were changed because they caused memory access problems). Remove the tags one by one and see which one is triggering. My money is on the centroid. You can disable tags by setting the address to 0, but the first instance that is 0 will abort the tests so you have to start with 1 then 2...4. I don't have this game so I can't test directly at the moment.

**Comment by Xcedf** [comment] 2019-05-03 12:40
Not quite understand what i need to do, can you please give an example.
Yet i reduced my hack to one line and those equations are fine the line is
const u32 last_row_offset = pitch2 * (h - 1); 
making it like this
const u32 last_row_offset = pitch2 * h; 
or even just removing the braces
const u32 last_row_offset = pitch2 * h - 1; 
working just fine

**Comment by kd-11** [comment] 2019-05-03 13:08
I mean there are 5 sampling points and all except the first are optional. I need them commented out one-by-one in reverse order, starting with https://github.com/RPCS3/rpcs3/blob/master/rpcs3/Emu/RSX/Common/surface_store.h#L182, then https://github.com/RPCS3/rpcs3/blob/master/rpcs3/Emu/RSX/Common/surface_store.h#L178 then https://github.com/RPCS3/rpcs3/blob/master/rpcs3/Emu/RSX/Common/surface_store.h#L177 and report the first change that affects the output.

**Comment by Xcedf** [comment] 2019-05-03 16:32
None of them making any difference even commented all 4 at once and nothing the only thing that game reacts on is line  const u32 last_row_offset = pitch2 * (h - 1);

**Comment by kd-11** [comment] 2019-05-03 18:23
Thats because you're now sampling from the adjacent image, which probably has not changed. Looks like this is a lot more complex than just the sampling points then and needs direct debugging. I'll self-assign and investigate after the next PR.

**Comment by stride21** [comment] 2019-06-21 00:07
PR #5726 also regressed the water reflections in Ratchet and Clank Future: A Crack in Time which were fixed in PR #5675. 

Before:
![before](https://user-images.githubusercontent.com/37915864/59888387-08462f80-938d-11e9-8277-b2a86fb0738a.PNG)
After:
![broken](https://user-images.githubusercontent.com/37915864/59888369-f2386f00-938c-11e9-9246-1155aa92c859.PNG)
[RPCS3.log.gz](https://github.com/RPCS3/rpcs3/files/3312454/RPCS3.log.gz)

**Comment by kd-11** [comment] 2019-08-19 22:43
This needs retesting.

**Comment by stride21** [comment] 2019-08-19 23:39
@kd-11 Still an issue on master. 

![water](https://user-images.githubusercontent.com/37915864/63306537-95840280-c2b0-11e9-9915-a9fc5e8f5fb7.PNG)

**Comment by Xcedf** [comment] 2019-08-20 02:25
Mot fixed not on master neither on misc PR

**Comment by kd-11** [comment] 2020-01-14 11:59
May require a quick retest and new RSX capture files for both games. I'm tracking long-standing regressions.

**Comment by stride21** [comment] 2020-01-14 17:46
Ratchet and Clank Future: A Crack in Time still has the issue with the water looking red.

 [RSX_capture.zip](https://github.com/RPCS3/rpcs3/files/4060528/RSX_capture.zip)

**Comment by Xcedf** [comment] 2020-01-15 22:03
@kd-11 i noticed this issue is in your list https://github.com/RPCS3/rpcs3/issues/7220, i did some searching a while ago but didn't even found the code which made difference for me.
anyway here's the capture, if rdc needed just tell
https://mega.nz/#!nY5mFYJR!b9TpkoDqBgDnnL6Z7IQo42Jy9n3TkYDG2a8jLsv4ukU

**Comment by kd-11** [comment] 2020-02-03 12:52
Glitch appears to be triggered by WCB, finally working on a permanent fix for this.

**Comment by kd-11** [comment] 2020-02-03 15:03
It seems this bug was actually already fixed a long time ago, but a hack was placed to avoid breaking other games. I'll see about a general solution to the problem.

**Closed** 2020-02-04 13:20 UTC
Labels: Regression
