### ISSUE TITLE
nvoglv64.dll crash Many games

### ISSUE THREAD

**Issue by woj1993** [RPCS3/rpcs3#3328] opened 2017-08-27 14:15 UTC
It sems this bug affect many games so list of affected games:
-Bayonetta Demo
-Dead Space 2 demo.
-Tekken 6

P.S. @raveskirza Any other know games?

Old coment:
Bayonetta demo crashes in random moment with error pointing at nvoglv64.dll .
Log: [RPCS3.zip](https://github.com/RPCS3/rpcs3/files/1254441/RPCS3.zip)

**Comment by AniLeo** [comment] 2017-08-27 14:17
·W 0:00:00.000000 Experimental Build Warning! Build origin: RPCS3/rpcs3/master/=3324

**Comment by woj1993** [comment] 2017-08-27 15:02
@AniLeo Don't be so fast because you will burn yourself. This error is in main branch too. Log is from experimental branch because i was testing if one of experimental branch fixes it or not.
Here log from main branch after crash: [RPCS3.zip](https://github.com/RPCS3/rpcs3/files/1254460/RPCS3.zip)
My pc config:
Intel I5 2300 2,8 GHz 4 Cores
4 Gb ram 
Asus GT440 1 GB DDR3

**Comment by AniLeo** [comment] 2017-08-27 15:06
Haha, funny. Issue reproduction needs to be conducted on master builds, even if happens on experimental ones, specially if they touch important code.

**Comment by woj1993** [comment] 2017-08-27 15:13
I watched other closed issues and now I understand why you closed it so fast. :)
Do you need anything else or log is enought.

P.S. I tested with both with Load liblv2 and Auto.

**Comment by AniLeo** [comment] 2017-08-27 15:17
Log won't probably be enough in this case, someone will need to debug on a dev environment like Visual Studio

**Comment by raveskirza** [comment] 2017-08-27 18:16
This has started happening n Tekken 6 and other games also after the commit 3315 was merged. If you try the previous master build 0.0.3-5891(https://rpcs3.net/compatibility?b) rpcs3 does not crash the nvidia driver

**Comment by kd-11** [comment] 2017-08-28 11:43
I'm fairly certain its caused by the vertex rewrite commits. I have fixes for several other bugs in the vulkan renderer implementation incoming.

**Comment by kd-11** [comment] 2017-10-19 10:21
Please retest.

**Comment by raveskirza** [comment] 2017-10-21 20:55
Tekken 6 seems to no longer hit this error

**Comment by AniLeo** [comment] 2017-10-24 14:14
Need someone to confirm at least one of the other two games so issue can be closed

**Comment by woj1993** [comment] 2017-10-26 12:06
Bayonetta Demo works. I will test Dead Space 2 demo but one test is not enought (I might get lucky). 
@AniLeo This bug looks like it is solved. Close this issue, if it need to been reopen then I will ask you.

**Closed** 2017-10-26 12:20 UTC
