### ISSUE TITLE
[Regression] LBP1 and LBP2 consistently crash after latest patch.

### ISSUE THREAD

**Issue by ikzoid** [RPCS3/rpcs3#15509] opened 2024-04-26 23:13 UTC
### Quick summary

LBP1 will randomly freeze and crash after the latest patch.

### Details

LBP1 will randomly freeze and crash after the latest patch. 
Reverting back to the previous version of RPCS3 (0.0.31-16376) without changing any of my set configs fixes the problem. 
When the game freezes, all video output and controller input is frozen, but audio continues to play.

### Build with regression

0.0.31-16378

### Attach two log files

[Log of LBP in latest version](https://www.dropbox.com/scl/fi/t56xe87ak980xzwsjffrb/RPCS3-broken.log?rlkey=x3ie1kfqimvhgb97mk5h73o0m&st=abxmqfa6&dl=1)
[Log of LBP in previous version, significantly longer because I could actually keep playing.](https://www.dropbox.com/scl/fi/wdgp9rjun8cx3uc4lgf9o/RPCS3.log?rlkey=ix0nfuwl7s3cratjk9mejdfv9&st=99duevpe&dl=1)

**Comment by AniLeo** [comment] 2024-04-26 23:17
There's a gap of more than one build in both your flagged builds. I'm pretty sure the flagged build is wrong and that it is a duplicate of #15510

**Closed by AniLeo** 2024-04-26 23:17 UTC
