### ISSUE TITLE
The Darkness (2007) [BLES00058] borked GPU blit path

### ISSUE THREAD

**Issue by dio-gh** [RPCS3/rpcs3#7388] opened 2020-02-03 20:02 UTC
The regression is twofold:

It broke after #7260 first: the game wouldn't show graphics in VK, became incredibly sluggish in general, and wouldn't reach the main menu. It eventually ends up halting with a `vk::wait_for_event has timed out!` error, and the emulator stops responding.

[RPCS3.log-9388.gz](https://github.com/RPCS3/rpcs3/files/4149887/RPCS3.log-9388.gz)

It also broke OpenGL, though instead of eventual hanging, it now showcases us a probably bootlegged copy of the not-yet-released Matrix 4 movie (ignore the version number, the graphical corruption looks the same ever since with minor alterations):

![image](https://user-images.githubusercontent.com/10439488/73685519-91b13480-46c6-11ea-8ae5-485eead88dec.png)

But this wasn't the end of the story, as the game regressed even further, breaking in a 2nd way since. #7268 is the PR that broke it further, now the game will just flat out fatal it's way out before reaching the menu, eventually crashing the emulator upon trying to boot something else. This is in VK, the exact error is `F 0:01:14.069216 {RSX [0x032b83c]} RSX: class std::runtime_error thrown: Assertion Failed! Vulkan API call failed with unrecoverable error: Device lost (Driver crashed with unspecified error or stopped responding and recovered) (VK_ERROR_DEVICE_LOST)
(in file C:\projects\rpcs3\rpcs3\Emu\RSX\VK\VKHelpers.cpp:906)`. OGL continues to work the same Matrix 4-y way.

[RPCS3.log-9396.gz](https://github.com/RPCS3/rpcs3/files/4149914/RPCS3.log-9396.gz)

**When forcing the use of CPU blit, the issues do not occur (in either of the builds).**

**Other tidbits:**
- I've noticed that on OpenGL, the game doesn't display 3D graphics behind the main menu. I don't have the time to test when that broke, but I don't think it used to work that way. Especially since it's the "compatibility backend", while VK does display that proper 3D background.
- The emulator seems to miscount the framerate heavily? It's almost guaranteed to lie about it when I launch the game with OpenGL. Shows 180 fps (even though it should be locked to 60 tops), and runs at like 4. Heard it's a general issue recently though, so whatever.

**Comment by kd-11** [comment] 2020-02-04 18:20
Bug was there since texture cache rewrite early last year, drivers were just more tolerant of it until the code was optimized so skip some other work and exposed this one.

**Comment by kd-11** [comment] 2020-02-05 15:18
Remaining OpenGL bugs are unrelated to the gpu blit regression and will be fixed separately.

**Closed** 2020-02-05 15:18 UTC
