### ISSUE TITLE
Regression: Sky Fighter [NPUB30144] freezes when starting a level (#12544, #12523)

### ISSUE THREAD

**Issue by Schroedingers-Cat** [RPCS3/rpcs3#12642] opened 2022-09-11 17:41 UTC
### Quick summary

Sky Fighter [NPUB30144] freezes when starting a level with the error `E VM: Access violation reading location 0x0 (unmapped memory)`. 

### Details

Since `rpcs3-v0.0.23-14080-ee87fdc8`, I'm unable to start a level in Sky Fighter [NPUB30144]. After the loading screen is over, directly at the start of the level, there'll be a freeze with the error message `E VM: Access violation reading location 0x0 (unmapped memory)` in the console.  

While previous versions could still freeze randomly in a level, this was never reproducible and not directly at the start of a level. Since 14080, the freeze happens consistently at the start of a level.

### Build with regression

v0.0.23-14080-ee87fdc8

### Attach two log files

Log from `rpcs3-v0.0.23-14080-ee87fdc8_win64` directly freezing when loading the tutorial level: 
[RPCS3.log.gz](https://github.com/RPCS3/rpcs3/files/9543073/RPCS3.log.gz)
Log from `rpcs3-v0.0.23-14068-a74d3005_win64` with no freeze at level start but a random freeze several minutes in the tutorial level: [RPCS3.log.gz](https://github.com/RPCS3/rpcs3/files/9543164/RPCS3.log.gz)

### System configuration

Win 10  
AMD Ryzen 9 3950X
AMD Radeon RX 6900 XT (v22.8.1)
128GB RAM

**Comment by kunit1** [comment] 2022-09-11 20:14
PR that broke it: [12544](https://github.com/RPCS3/rpcs3/pull/12544)

**Comment by AniLeo** [comment] 2022-09-25 14:01
Either #12544 or #12523 (marked as broken)
Adding @elad335

**Comment by elad335** [comment] 2022-09-25 14:04
Try accurate SPU GETLLAR in debug tab.

**Comment by benderscruffy** [comment] 2023-02-17 10:28
RPCS3 v0.0.26-14720-bbd308a9 Alpha | master
still an issue
[RPCS3.log.gz](https://github.com/RPCS3/rpcs3/files/10765762/RPCS3.log.gz)

**Comment by Triticum0** [comment] 2023-02-20 22:37
Using  Accurate SPU DMA fixes the issue.

**Comment by benderscruffy** [comment] 2023-02-23 09:50
but now the issue is the music stops near the end of the level and freezes up when you complete the level

**Comment by elad335** [comment] 2023-10-03 05:21
I think it should be closed, use accurate GETLLAR from now. Maybe if you tried many msny times you had experience a freeze when starting a level too. This behavior changed because performance has been improved affecting the race condition.

**Closed by elad335** 2023-10-03 05:21 UTC
Labels: Regression

**Comment by Triticum0** [comment] 2024-01-04 18:02
@elad335 I tested with accurate GETLLAR and it does fix the freeze. Only SPU DMA Fixes the freeze also the error code has changed:
`E VM: [SPU[0x4000100] S5CellSpursKernel4] Access violation writing location 0x42617400 (unmapped memory)`
