### ISSUE TITLE
diablo 3 and reaper of souls freezes alike in the same phase of the game fix it please

### ISSUE THREAD

**Issue by locomia40** [RPCS3/rpcs3#9986] opened 2021-03-18 00:23 UTC
I am Spanish and well I don't know where or how to put a paragraph or almost correctly write to you in your language, I only ask to accelerate the fluency in the game diablo 3 waiting many weeks for the game to be played.

**Comment by RainbowCookie32** [comment] 2021-03-18 00:33
Invalid issue, duplicate of #5593 

Progress isn't done on a per-game basis.

**Closed** 2021-03-18 00:53 UTC

**Comment by locomia40** [comment] 2021-03-18 01:03
matias - he directed me to the previous comments for the causes and the imbalances in the emulator, I am testing without reaching level 50 with my amd 2700 processor and a range of 8 mb of memory but it does not stop me almost at boot time The game will be as in level 8 it would be almost impossible to add a filter to that emulator I don't know what I'm saying heh heh
