### ISSUE TITLE
Crash on shutdown (macOS)

### ISSUE THREAD

**Issue by MajmunX** [RPCS3/rpcs3#15658] opened 2024-06-05 12:34 UTC
### Quick summary

On macOS, Sonoma latest update, whenever I exit a game, stop emulation, or close the game window, RPCS3 shuts down with the attached error (photo and log file)

### Details

<img width="560" alt="Screenshot 2024-06-05 at 12 26 24" src="https://github.com/RPCS3/rpcs3/assets/58711564/8aeb33e6-e007-4c5c-a63d-5d8f082dd2bd">

### Attach a log file

<img width="560" alt="Screenshot 2024-06-05 at 12 26 24" src="https://github.com/RPCS3/rpcs3/assets/58711564/94412cc5-844f-408c-837b-84507a9d8bc8">

### System configuration

Mac mini M2, 8 copre cpu, 10 core gpu
Running Sonoma 14.5

**Comment by MajmunX** [comment] 2024-06-05 12:35
[](url) reattached log file

**Comment by jcmoore1977** [comment] 2024-06-08 21:19
Are you using an SDL controller. I have noticed if I disable the SDL controller all the crashes stop. I am also on Sonoma 14.5

**Comment by Megamouse** [comment] 2024-06-09 05:07
missing log file

**Comment by jcmoore1977** [comment] 2024-06-09 13:52
I have attached 2 logs, one with using SDL(XBOX Controller) which causes crash, the other without using SDL (KEYBOARD). I hope this will help
[RPCS3.log.gz](https://github.com/user-attachments/files/15752710/RPCS3.log.gz)
[withoutSDL_RPCS3.log.zip](https://github.com/user-attachments/files/15752711/withoutSDL_RPCS3.log.zip)

**Comment by MajmunX** [comment] 2024-06-09 17:14
> Are you using an SDL controller. I have noticed if I disable the SDL controller all the crashes stop. I am also on Sonoma 14.5

Hi,

I think I read that somewhere and it crashed either way. I used keyboard and disconnected all controllers.


I will try again tonight and send both logs

**Comment by MajmunX** [comment] 2024-06-14 11:53
I can confirm it is an SDL issue,

I removed both SDL from 1 and 2 and it stopped crashing on exit

Is there a way to resolve this? I only have DualShock PS3 controller that do not work with Sonoma only Big Sur, the rest are all xbox 


here is the log file and screen shot as I exited a game with SDL (xbox series bluetooth) controller connected and configured as SDL on controller 1 and 2
<img width="570" alt="Screenshot 2024-06-14 at 11 42 40" src="https://github.com/RPCS3/rpcs3/assets/58711564/768cd7e8-d8fc-43b9-94c7-33418bf6e6c2">

**Comment by MajmunX** [comment] 2024-06-14 22:18
> missing log file

added the log file in a previous reply.

After more testing, It is an SDL issue, same that has been present in #14760
https://github.com/RPCS3/rpcs3/issues/14760

This was also making games with collctions (i.e: ice /sotc  and GOW collections) shut down on the choice page as RPCS3 quits the game and boots back into your choice,, when SDL not connected, it crashes after I make the game choice, with no SDL connected, it just boots the game I selected. 

Is there any way around this SDL issue? 

Will this be resolved by replacing the SDL.lib file with a previous working one?

I had a similar issue on PCSX2, when using intel HD4000 (Mac mini 2012) and was resolved by using an older version of SDL.lib

also forgive my question, but If I take the SDL file from my PCSX2 or an and replace it with this one, could it work? or does the lib need to be built for RPCS3?

**Comment by RolandTi** [comment] 2024-06-19 09:52
> > missing log file
> 
> added the log file in a previous reply.
> 
> After more testing, It is an SDL issue, same that has been present in #14760 #14760
> 
> This was also making games with collctions (i.e: ice /sotc and GOW collections) shut down on the choice page as RPCS3 quits the game and boots back into your choice,, when SDL not connected, it crashes after I make the game choice, with no SDL connected, it just boots the game I selected.
> 
> Is there any way around this SDL issue?
> 
> Will this be resolved by replacing the SDL.lib file with a previous working one?
> 
> I had a similar issue on PCSX2, when using intel HD4000 (Mac mini 2012) and was resolved by using an older version of SDL.lib
> 
> also forgive my question, but If I take the SDL file from my PCSX2 or an and replace it with this one, could it work? or does the lib need to be built for RPCS3?

Hello, I tried to replace the `libSDL2-2.0.0.dylib` with the last packed with SDL 2.30.4 from homebrew and RPCS3 didn't start.

**Comment by Megamouse** [comment] 2024-06-23 05:20
Closing as duplicate of #14753

**Closed by Megamouse** 2024-06-23 05:20 UTC
Labels: Need Information, OS: Mac
