### ISSUE TITLE
Missing object in Demon Souls 7367

### ISSUE THREAD

**Issue by dukenukemx** [RPCS3/rpcs3#5153] opened 2018-09-21 03:02 UTC
In Demon's Souls in world 3-2 when you destroy both chain the giant hive or heart or whatever falls down and you're suppose to see it and walk on it to get to the treasure.  You can see I'm on it, but nothing is there.  Using RPCS3 7367.

![demon souls 3-2](https://user-images.githubusercontent.com/31163475/45857945-177a4d00-bd29-11e8-9a46-63362b48db87.jpg)

**Comment by elhaya** [comment] 2018-09-21 04:51
there's also the missing soldier shield bug. they're probably connected

**Comment by isshininu** [comment] 2018-09-21 07:14
Duplicate of https://github.com/RPCS3/rpcs3/issues/4302

**Comment by AniLeo** [comment] 2018-09-21 11:01
Closing as duplicate of #4302

**Closed by AniLeo** 2018-09-21 11:01 UTC
