### ISSUE TITLE
RSX: Depth Texture / Black Screen / Crash Invalid RSX Method 0xfffc / FIFO Queue - Sly Cooper 4 [BCES01284]

### ISSUE THREAD

**Issue by alexmaurizio** [RPCS3/rpcs3#3923] opened 2017-12-09 23:23 UTC
RPCS3 Version Tested: Last Official + Last kd-11 commit (v0.0.4-6216-acccca5e)
Hardware: i9 7900X + Aorus GTX1080Ti + 64GB DDR4
Settings: LLVM + Vulkan / 1280x720

When setting more than 1280x720, game refuses to pass the "Sony Presents" screen with a crash.
Some textures are flashing badly and videos sometimes flash intermittently very fast (epilepsy-unfriendly!)

Game can reach in-game status (compatibility list is outdated), some serious graphic fixes with the last KD11 commit VS the official version at the moment.

The main problem is the black screen (UI is rendered, Textures are all black except for some animations and very faint model that you can see) that can be fixed sometimes by moving the camera, and the random crash after a certain point. The "Depth Texture" Warning is spammed in both versions continuously.

I had two different type crashes on various tests, happening randomly on menu or ingame:

1) Crash with a FIFO pipeline problem (official version, happens on KD-11 too):

```
·E 0:00:58.249209 {rsx::thread} RSX: Depth texture bound to pipeline with unexpected format 0x8B
·W 0:00:58.256759 {rsx::thread} RSX: NV4097_GET_REPORT: Unimplemented type 1
·W 0:00:58.258105 {PPU[0x1000000] Thread (main_thread) [0x0121bbb4]} sys_rsx: sys_rsx_context_attribute(context_id=0x55555555, package_id=0x10a, a3=0x1, a4=0x7fffffff, a5=0x0, a6=0x0)
·W 0:00:58.258119 {rsx::thread} RSX: NV4097_GET_REPORT: Unimplemented type 1
·E 0:00:58.263548 {rsx::thread} HLE: Getting the real address failed. (addr=0xd21da860)
·E 0:00:58.263553 {rsx::thread} RSX: Invalid FIFO queue get/put registers found, get=0xD21DA860, put=0x6EEC
·E 0:00:58.265060 {rsx::thread} HLE: Getting the real address failed. (addr=0xd21da860)
·E 0:00:58.265066 {rsx::thread} RSX: Invalid FIFO queue get/put registers found, get=0xD21DA860, put=0x6EEC
·E 0:00:58.266558 {rsx::thread} HLE: Getting the real address failed. (addr=0xd21da860)
·E 0:00:58.266563 {rsx::thread} RSX: Invalid FIFO queue get/put registers found, get=0xD21DA860, put=0x6EEC
·E 0:00:58.268061 {rsx::thread} HLE: Getting the real address failed. (addr=0xd21da860)
·E 0:00:58.268072 {rsx::thread} RSX: Invalid FIFO queue get/put registers found, get=0xD21DA860, put=0x6EEC
·E 0:00:58.268073 {rsx::thread} RSX: Application has failed to recover, discarding FIFO queue
```

2) Crash on Invalid RSX Method (KD-11 version, happens on official too):

```
·E 0:06:43.430022 {rsx::thread} RSX: Depth texture bound to pipeline with unexpected format 0x8B
·W 0:06:43.430054 {rsx::thread} RSX: NV4097_GET_REPORT: Unimplemented type 1
·W 0:06:43.431599 {PPU[0x1000000] Thread (main_thread) [0x0121bbb4]} sys_rsx: sys_rsx_context_attribute(context_id=0x55555555, package_id=0x10a, a3=0x1, a4=0x7fffffff, a5=0x0, a6=0x0)
·W 0:06:43.431625 {rsx::thread} RSX: NV4097_GET_REPORT: Unimplemented type 1
·W 0:06:43.433123 {rsx::thread} RSX: unaligned command: Unknown/illegal method [0x00003fff] (0x3fff from 0xffff)
·E 0:06:43.433129 {rsx::thread} RSX: Invalid RSX method 0xfffc (arg=0xa00ffff)
(in file Emu\RSX\rsx_methods.cpp:45)
```

The logs:
[RPCS3.log.gz (KD-11 Version - Invalid Method)](https://github.com/RPCS3/rpcs3/files/1545196/RPCS3.log.gz)
[RPCS3.log.gz (Official Version - FIFO Pipeline)](https://github.com/RPCS3/rpcs3/files/1545202/RPCS3.log.gz)

In-game Screenshot when not bugged:
![In-Game Screenshot](https://user-images.githubusercontent.com/15074818/33800390-4f065aae-dd3f-11e7-9d22-7a4c10ad833b.png)

Keep up the great job guys! Hope this is something that can help you.

**Comment by kd-11** [comment] 2017-12-10 23:11
Desynchronization crash is a duplicate of https://github.com/RPCS3/rpcs3/issues/2359. Not sure what the other issues are since I dont have any reference. Just a tip - you can reduce desync by removing all spu emulation hints  - threads on auto, lower priority off, spu loop detection off. This will hit your cpu hard but its less likely to enter a situation where rsx runs too far ahead of the other parts.

**Comment by destructor3** [comment] 2017-12-14 00:00
Ok, quick update.
Trying with all SPU detection helps, threads on auto and resolution on 720x480 removes the "hyper flashing" stuff during cutscenes, which is good! But anyway I had the same crashes ingame with 

```
E {rsx::thread} RSX: Depth texture bound to pipeline with unexpected format 0x8B
E {rsx::thread} RSX: Depth texture bound to pipeline with unexpected format 0x8B
E {rsx::thread} HLE: Getting the real address failed. (addr=0x11337000)
E {rsx::thread} RSX: Invalid FIFO queue get/put registers found, get=0x11337000, put=0xABFC
E {rsx::thread} HLE: Getting the real address failed. (addr=0x11337000)
E {rsx::thread} RSX: Invalid FIFO queue get/put registers found, get=0x11337000, put=0xABFC
E {rsx::thread} HLE: Getting the real address failed. (addr=0x11337000)
E {rsx::thread} RSX: Invalid FIFO queue get/put registers found, get=0x11337000, put=0xABFC
E {rsx::thread} HLE: Getting the real address failed. (addr=0x11337000)
E {rsx::thread} RSX: Invalid FIFO queue get/put registers found, get=0x11337000, put=0xABFC
E {rsx::thread} RSX: Application has failed to recover, discarding FIFO queue
```

and of course Depth Texture spamming.

I managed to take a screenshot of the game while "bugged" before the crash (that actually happened DURING the bug phase) and it looks like (from an ignorant point of view) to be related to lightning, since models are there and UI too.

![Bug Screenshot](https://user-images.githubusercontent.com/15074818/33968773-0c5083b4-e06a-11e7-8de5-8474130d4161.png)

Any ideas for this? I don't obviously need a fix to play this game - I just want to help if possible with this specific testing.

Thanks!

**Comment by kd-11** [comment] 2018-01-02 18:45
Desynchronization should be less of an issue with current master. Depth complaints might be gone too - time to retest.

**Comment by alexmaurizio** [comment] 2018-02-10 16:04
Hello!
I only had time now for some retests, with latest cce0ad0c version. Sorry!

Soo... no more crashes!! I only had a crash in 30 mins but was a common one and not specific, I guess it was a standard crash, and no useful log.

Still, the missing texturing problem is still present, but since I managed to get forward in game (and this looks playable enough! If I have more time i'll try to go forward) I have found a way to manually trigger the black screens.

Basically it happens when you trigger the "float" jets which deploy some lightning and a new texture. I attach a gif of the situation. I still think this is related to lightning effects somehow. The only log is still the "Depth Texture Bound to Pipeline" spam, but it's much less spammy than before.

https://imgur.com/a/Pzr8w
![RPCS3 - Sly Cooper 4: Thieves In Time - Rendering Bug](https://i.imgur.com/oyYxyOF.mp4)

So for recap:
Playing in 1920x1080 or higher -> Instant crash after "Sony Presents" title
Playing in 1280x720 -> Game works with blackscreens AND cutscenes flash very fast intermittently
Playing in 720x480 -> Game runs fine but black screens are still there

Let me know if you need some more testing

**Comment by yogablabla** [comment] 2018-06-23 11:18
E {rsx::thread} RSX: Depth texture bound to pipeline with unexpected format 0x8B x994

My game always freeze when in Feudal japan, in the 1st mission. It freeze exactly when i try to take photo of the 5th picture. I currently running it at 720x480

**Comment by kd-11** [comment] 2019-03-19 21:52
Retest. And no, the depth texture message is not a real problem/glitch/crash, its meaning is only useful to developers.

**Comment by elad335** [comment] 2020-01-25 07:12
Retest with rsx wake-up delay.

**Comment by MSuih** [comment] 2020-01-25 07:14
I played through Sly 4 a week ago, only remaining issue from this post was the unexpected format spam. This can probably be closed.

**Closed** 2020-01-25 13:41 UTC
