### ISSUE TITLE
Red Colors when using Vulkan

### ISSUE THREAD

**Issue by oxygennn02** [RPCS3/rpcs3#12298] opened 2022-06-30 00:34 UTC
Been having this red color issue when running this game only when using Vulkan only with this game too.

![Screenshot_1](https://user-images.githubusercontent.com/108439757/176567929-a07697eb-40ff-45be-8bff-ac11d2ac6ee2.png)

* GTX 1660

**Comment by Jonathan44062** [comment] 2022-06-30 00:37
Duplicate of https://github.com/RPCS3/rpcs3/issues/12008, would suggest mentioning this on there

**Comment by MSuih** [comment] 2022-06-30 09:38
Yes, it's almost certainly the same underlying issue so there's no need to have two tickets for it.

**Closed by MSuih** 2022-06-30 09:38 UTC
