### ISSUE TITLE
(LLVM) Unregistered PPU function. Pro Baseball Spirits 2015

### ISSUE THREAD

**Issue by kirksoul** [RPCS3/rpcs3#4219] opened 2018-02-26 13:10 UTC
*Pro Baseball Spirits 2015*

1.Recompiler(LLVM) ==> F {PPU[0x1000000] Thread (main_thread) [0x00dc2174]} class std::runtime_error thrown: Unregistered PPU function

2.Interpreter(fast)==> Running ok but very slow

vulcan, win10 64bit, GTX 970, i5-4570
Emulator version is 0.0.5-6464

**Comment by Megamouse** [comment] 2018-02-26 16:42
duplicate of https://github.com/RPCS3/rpcs3/issues/2909

**Closed** 2018-02-26 18:02 UTC
