### ISSUE TITLE
HLE TODO Unimplemented syscall

### ISSUE THREAD

**Issue by LordLoras** [RPCS3/rpcs3#1972] opened 2016-07-23 10:13 UTC
U {PPU[0x5] Thread (main_thread) [0x00bb2680]} HLE TODO: Unimplemented syscall syscall_512 -> CELL_OK
U {PPU[0x5] Thread (main_thread) [0x00bb964c]} HLE TODO: Unimplemented syscall syscall_510 -> CELL_OK
U {PPU[0x5] Thread (main_thread) [0x00bb967c]} HLE TODO: Unimplemented syscall syscall_514 -> CELL_OK

**Comment by raven02** [comment] 2016-07-23 10:14
Duplicate of https://github.com/RPCS3/rpcs3/issues/1867

**Closed by raven02** 2016-07-23 10:14 UTC
