### ISSUE TITLE
Every 10-15 minutes I get an error in SH Downpour

### ISSUE THREAD

**Issue by StalkerDolg** [RPCS3/rpcs3#5917] opened 2019-05-04 20:52 UTC
This problem exist already a year 
Here screenshot of error https://pp.userapi.com/c845219/v845219245/1f4786/tZ-HmK3YS2I.jpg
[RPCS3.zip](https://github.com/RPCS3/rpcs3/files/3144847/RPCS3.zip)

**Comment by RainbowCookie32** [comment] 2019-05-04 20:59
The link for the log you provided seems to be private. 
```
Error
This document is available only to its owner
```

**Comment by AniLeo** [comment] 2019-05-04 21:02
Looks like NVIDIA fullscreen issue, may be a duplicate.

**Comment by StalkerDolg** [comment] 2019-05-04 21:07
Private link to log? Ok, new link, its free http://fayloobmennik.cloud/7360279

**Comment by AniLeo** [comment] 2019-05-04 21:10
Use a reputable website or upload here, otherwise I'll just mark as invalid

![image](https://user-images.githubusercontent.com/10283761/57184827-7d32d800-6eb9-11e9-8855-e9964f4c91fe.png)

**Comment by StalkerDolg** [comment] 2019-05-04 21:13
[RPCS3.zip](https://github.com/RPCS3/rpcs3/files/3144845/RPCS3.zip)
Soor, I did not notice that the site has the ability to insert files

**Comment by AniLeo** [comment] 2019-05-04 21:17
> 'GeForce GTX 980' running on driver 419.35.0.0

Very probably duplicate of #5351, try playing on windowed mode (not borderless, not fullscreen) or reverting the driver to 399

**Comment by StalkerDolg** [comment] 2019-05-04 21:20
I'll try. I will write if the error appears again. I thought this could be fixed with emulator

**Comment by StalkerDolg** [comment] 2019-05-05 00:54
[RPCS3.zip](https://github.com/RPCS3/rpcs3/files/3145006/RPCS3.zip)
Windowed mode, error not disappeared

**Comment by StalkerDolg** [comment] 2019-05-05 01:04
I"ll install 399, if it will not help, i"ll write

**Comment by StalkerDolg** [comment] 2019-05-05 03:31
[RPCS3.zip](https://github.com/RPCS3/rpcs3/files/3145095/RPCS3.zip)
Driver change also did not help

**Comment by digitaldude555** [comment] 2020-02-07 18:12
Close this ani.

**Closed** 2020-02-07 19:29 UTC
