### ISSUE TITLE
As of the later 4XX.XX NVIDIA drivers and onwards, all games give me device lost errors

### ISSUE THREAD

**Issue by SlyCooperReloadCoded** [RPCS3/rpcs3#12084] opened 2022-05-25 03:43 UTC
## Quick summary
As of the later 4XX.XX NVIDIA drivers, all games give me device lost errors under certain circumstances.

## Details
Soon after installing the v497.29 for my NVIDIA RTX 2080 Super GPU, I started to notice that more and more of the games in my library would randomly start crashing with Vulkan-related device lost errors, but not very frequently.  However, as time went on I kept my GPU driver up to date, each time doing a clean install with Guru3D's DDU tool, but the device lost errors were increasing.  At first I thought it was only Just Cause 2 (hence issue 11768) but after some testing, I've confirmed every single game in my library does this, even ones that have been marked as playable years ago and have no reports of any issues.  During my testing, something I've noticed that is consistent is that the larger the game's shader cache, the sooner it'll throw the device lost errors.  Watch Dogs has upwards of 20000 shaders, it'll throw a device lost error within 5-10 minutes of gameplay.  Just Cause 2 has around 8000 shaders, it takes up to 30 minutes before it happens.  Lego Star Wars: The Complete Saga has only 2000-ish shaders, and I can play that game for hours before it happens.  Something to note is that clearing the shader cache temporarily prevents the device lost errors, until it happens again of course.

Also, I should point out this isn't a hardware fault.  I've left very demanding PC games on for weeks with no issues, and I AI upscale/interpolate regularly.  Other emulators also have never had any problems as long as I keep my GPU drivers up to date, which I do.  I realize this sounds absurd, but the emulator has been borderline unusable for me for the past few months.  I do remember that I started noticing this issue around PR 11717 but this could be a coincidence, especially since it happens even when MSAA is disabled.

#### 1. Please attach RPCS3's log.
I don't have any logs on hand, but every single time it crashes, it throws this exact error, but with a different location next to "RSX":

F {RSX [0x0077f10]} SIG: Thread terminated due to fatal error: Assertion Failed! Vulkan API call failed with unrecoverable error: Device lost (Driver crashed with unspecified error or stopped responding and recovered) (VK_ERROR_DEVICE_LOST)
(in file C:\Users\ContainerAdministrator\AppData\Local\Temp\cirrus-ci-build\rpcs3\Emu\RSX\VK\vkutils\sync.cpp:187[:6], in function wait_for_fence)
(in file C:\Users\ContainerAdministrator\AppData\Local\Temp\cirrus-ci-build\rpcs3\Emu\RSX\VK\vkutils\shared.cpp:107[:24], in function die_with_error)

#### 3. Please attach screenshots of your problem.
These are two screenshots I have of when Just Cause 2 threw the error, but they all look like this:

![Capture](https://user-images.githubusercontent.com/58268914/170174143-25152ade-9f63-40df-af5a-1e18b851fc47.PNG)

![Capture1](https://user-images.githubusercontent.com/58268914/170174164-c53e124b-fc2e-4519-8f77-b2663b0fa922.png)

#### 5. Please provide your system configuration:
* OS: Windows 10 Pro x64 Build 19043
* CPU: Intel Core i9-10900K
* GPU: NVIDIA RTX 2080 SUPER
* Driver version: 512.15

#### Please include.
I've done weeks of testing on every game in my library with almost every possible combination of settings, GPU driver version, and RPCS3 build released in the past three months - none of them have fixed this.

**Comment by kd-11** [comment] 2022-05-25 07:54
The nvidia driver was restructured after the 470.x release and stability went downhill.
Things have improved a lot with the 51x series though.
Either way, I'll need a lot more information on this one, as it is there isn't much to go on. If we can get more reports from more uers to narrow down the cause, then the ticket can be workable. The other option is to enable vulkan debugging with the SDK installed and try to reproduce a crash, but it is likely to spam a lot of errors if strict mode is not enabled and will be very slow, which usually makes the crash go away.
By the way, do run vkdiag tool and check for conflicting vulkan layers. Conflicting layers are known to trigger device lost crashes as well for us.

**Comment by SlyCooperReloadCoded** [comment] 2022-05-25 08:03
What's vkdiag?

**Comment by Asinin3** [comment] 2022-05-25 08:40
VK Diag: https://github.com/13xforever/vkdiag/releases/latest
Vulkan SDK (Needed for debug output): https://vulkan.lunarg.com/sdk/home#windows

**Comment by SlyCooperReloadCoded** [comment] 2022-05-25 18:18
I apparently had the SDK already from when I built from source.  I ran vkdiag and it gave me this:
![Capture](https://user-images.githubusercontent.com/58268914/170337906-b542c99e-b498-49ad-9691-93b5c30442f9.PNG)

**Comment by SlyCooperReloadCoded** [comment] 2022-05-25 19:19
I did that and started playing a game, and I got a device lost error.  The game window is up now, how exactly do I use Vulkan SDK?

**Comment by kd-11** [comment] 2022-05-25 20:06
1. Find a game that crashes easily.
2. Enable 'Debug output' option from the debug tab. You can also enable it in config.yml for the game you're testing.
3. Run the game until it crashes. You will know the validation is active if your framerate is terrible.
4. Wait for the game to crash. Attach the log file here for analysis.

**Comment by SlyCooperReloadCoded** [comment] 2022-05-25 20:50
I've been playing the game that gives me device lost errors every 2-5 minutes, the most crashy game in my library.  I've been playing it at 6 FPS for almost an hour and there's been no device lost errors.  I have a feeling that the low framerate is preventing the games from giving device lost errors.  Do you have any other ideas?

**Comment by Darkhost1999** [comment] 2022-05-25 20:54
That happens a lot. Try uploading what you have. You may need to use. Mega upload link or Google drive public link to fit the file.

**Comment by SlyCooperReloadCoded** [comment] 2022-05-25 20:57
Got an almost 100 MB log here, compressed it using .gz.  If you spot the problem in this, all games do this for me, so keep that in mind.

[RPCS3.log.gz](https://github.com/RPCS3/rpcs3/files/8774474/RPCS3.log.gz)

**Comment by SlyCooperReloadCoded** [comment] 2022-05-26 00:06
No idea if it helps, but here's a Debug Output log for Lego Star Wars The Complete Saga.  It too doesn't give device lost errors due to the decreased performance but it also doesn't have as much log spam.  Interestingly, turning on Debug Output causes weird graphical issues in this game.

[RPCS3.log.gz](https://github.com/RPCS3/rpcs3/files/8775255/RPCS3.log.gz)

**Comment by SilentHeII** [comment] 2022-07-30 22:11
Any news on this? This made RPCS3 borderline unplayable with random crashes.

**Comment by Darkhost1999** [comment] 2022-07-30 22:15
> Any news on this? This made RPCS3 borderline unplayable with random crashes.

It looks like to me they still need a log with the device crash error while debug output is enabled and the Vulkan sdk is installed.
If you can do that it'll help them.

**Comment by SlyCooperReloadCoded** [comment] 2022-07-30 23:15
The issue has either disappeared or gotten significantly less frequent.  I played a game that constantly gave me those errors with Debug Log enabled and it stopped happening, so it probably can't happen at low performance.  If it's happening to others then it's probably still an issue.  It seems random, it'll stop happening for months then start happening again.

**Comment by kd-11** [comment] 2022-07-31 09:58
There is also lack of a common denominator here. There simply aren't enough users getting the crashes to determine what exactly is causing it. Usually if we have a universal bug we get hundreds of reports flooding in which makes it easy to find the pattern. All I know so far with this is that some nvidia cards with some driver versions are affected. It also happens to be a generation of card that I do not own making things even harder.

**Comment by SlyCooperReloadCoded** [comment] 2022-08-12 04:37
The issue is now back for me.  My entire computer freezes for a few seconds and boom, device lost error, same exact error as all the other times.  All games are now unplayable for me again.  Between now and the last time it happened, I've done clean driver reinstalls at least three times, and all other PC programs continued to work perfectly, even PCSX2's Vulkan renderer gave me no issues whatsoever and continues to work fine.  I hope this common denominator can be found sooner or later, I hate wanting to use RPCS3 but thinking "okay, will this strange unsolvable emulator-breaking issue happen to me this time?" and then being disappointed when I can't play any game in my library for more than 5 minutes.
![Capture](https://user-images.githubusercontent.com/58268914/184285896-c6007882-5f3e-4e9c-a9ce-106a1703e805.PNG)

Log:
https://drive.google.com/file/d/1B-0p3rcQqELhWhnttrOBCbKAKFk0nGAf/view?usp=sharing

**Comment by SlyCooperReloadCoded** [comment] 2022-08-20 15:46
Got some good news - I played Just Cause 2 again with Debug Log enabled, and very quickly got the same exact device lost error as I've been getting with every game in my library, hopefully this log reveals more than before:
[RPCS3.log.gz](https://github.com/RPCS3/rpcs3/files/9387608/RPCS3.log.gz)

**Comment by kd-11** [comment] 2022-08-20 16:24
> Got some good news - I played Just Cause 2 again with Debug Log enabled, and very quickly got the same exact device lost error as I've been getting with every game in my library, hopefully this log reveals more than before: [RPCS3.log.gz](https://github.com/RPCS3/rpcs3/files/9387608/RPCS3.log.gz)

This one is just caused by async texture streaming.

**Comment by SlyCooperReloadCoded** [comment] 2022-08-20 18:43
So async is causing issues with every game in my library starting with this driver version?  Also Debug Log causes lots of missing graphics in most games, is that normal?

**Comment by kd-11** [comment] 2022-08-21 10:22
> So async is causing issues with every game in my library starting with this driver version? Also Debug Log causes lots of missing graphics in most games, is that normal?

I mean for that debug log it is definitely caused by async. Tons of errors about sharing resources between two queues. That's something to investigate for sure, but easy to work around for now.
So, yes, if you have been using async for all the tests, try turning it off and see if the crashing goes away.

**Comment by kd-11** [comment] 2022-08-21 10:23
> Also Debug Log causes lots of missing graphics in most games, is that normal?

Usually not but I'm not surprised it breaks things due to how it slows things down.

**Comment by SlyCooperReloadCoded** [comment] 2022-09-09 13:24
I've been doing some testing with Async Texture Streaming turned off, and I think it's safe to say that this option is just broken with the 4XX.XX and newer RTX 2080 SUPER drivers.  I've been playing with the option turned off, not a single device lost error, even with those games that constantly give them.  The issue isn't really solved since that option is broken when it shouldn't be, and it's entirely possible that the option significantly increases the chances of a device lost error, not the root cause, so I'll leave this open but it's looking like this is the problem.

**Comment by kd-11** [comment] 2022-09-09 15:59
@SlyCooperReloadCoded 
I found a bug with async compute that is addressed in https://github.com/RPCS3/rpcs3/pull/12632
Please retest.

**Comment by SlyCooperReloadCoded** [comment] 2022-09-09 17:03
I've set up that PR and enabled Async again.  While I haven't gotten any device lost errors yet (sometimes takes a while to crash, very random), another issue has revealed itself, one that I experienced before but I didn't realize it went away when I turned off Async - water disappearing completely for long periods of time.  I assumed it was just doing that while compiling shaders but no, apparently Async was causing that without me realizing.

**Comment by SlyCooperReloadCoded** [comment] 2022-09-09 19:48
Okay the issue is most likely fixed in that PR, except for water disappearing at times.  I did get an unmapped memory error as I closed the game though, pink text.

**Comment by kd-11** [comment] 2022-09-09 20:17
Thanks for confirming.

**Comment by kd-11** [comment] 2022-09-09 20:19
If you're not able to reproduce the crash after the fix, you may close this issue.

**Comment by kd-11** [comment] 2022-09-26 23:43
Closing as fixed.

**Closed by kd-11** 2022-09-26 23:43 UTC
Labels: Render: Vulkan, Driver: NVIDIA
