### ISSUE TITLE
VK: Alex Kid In Miracle World [NPUB30323]

### ISSUE THREAD

**Issue by woody2014** [RPCS3/rpcs3#1833] opened 2016-06-26 10:49 UTC
![screenshot 17](https://cloud.githubusercontent.com/assets/6561856/16361820/0799f5b6-3b94-11e6-983e-36aba3ae7a9f.png)

**Comment by AniLeo** [comment] 2016-06-26 11:08
What's the issue here?

**Comment by woody2014** [comment] 2016-06-26 11:12
background is in foreground,making game very hard to see.

**Comment by raven02** [comment] 2016-06-26 13:50
How it looks like in GL and DX12 then?

**Comment by woody2014** [comment] 2016-06-26 14:44
just shows background and no gameplay

**Comment by AniLeo** [comment] 2017-02-18 15:33
This is no longer an issue. The game is flickering weirdly though.
**Only happens in Vulkan.** OpenGL doesn't flicker between colors.

**Vulkan**
![screenshot_387](https://cloud.githubusercontent.com/assets/10283761/23094355/47563870-f5ef-11e6-9017-bd3610a83865.png)
![screenshot_388](https://cloud.githubusercontent.com/assets/10283761/23094356/47582270-f5ef-11e6-9d8b-3b1bcf171ee5.png)
![screenshot_389](https://cloud.githubusercontent.com/assets/10283761/23094358/4758e854-f5ef-11e6-9b18-b6f711fff00e.png)
![screenshot_390](https://cloud.githubusercontent.com/assets/10283761/23094357/4758182a-f5ef-11e6-84ed-de42e6209880.png)

**OpenGL**
![screenshot_391](https://cloud.githubusercontent.com/assets/10283761/23094375/8b360ce6-f5ef-11e6-8b98-2e535c2167fb.png)

@kd-11

**Comment by AniLeo** [comment] 2017-06-02 15:02
Confirmed that it no longer flickers on Vulkan, closing this issue.

**Closed by AniLeo** 2017-06-02 15:02 UTC
Labels: vulkan
