### ISSUE TITLE
Regression: Motorstorm [BCES00006] screen flickering (#9613)

### ISSUE THREAD

**Issue by Satan86** [RPCS3/rpcs3#9752] opened 2021-02-09 13:33 UTC
Screen flickers after 0.0.14-11619-22584fb2 (#9613), as shown in the video below.

https://user-images.githubusercontent.com/61447828/107370115-54456b00-6ac1-11eb-9b15-615cd57d4a2b.mp4

Broken version log: [RPCS3.log.gz](https://github.com/RPCS3/rpcs3/files/5951331/RPCS3.log.gz)
Working version log: [RPCS3.log](https://github.com/RPCS3/rpcs3/files/5951349/RPCS3.log)
Win 10 20H2, 5600x, 1050 Ti driver version 461.40

**Comment by AphelionWasTaken** [comment] 2021-02-09 14:00
I'm unable to reproduce the flickering exactly as shown above, but vehicles are flickering/stuttering a bit. It seems to be happening at similar intervals to Satan's issue, so perhaps they are the same? Unrelated, but also note the black rectangle surrounding one of the vehicles when it becomes obscured.

https://user-images.githubusercontent.com/61633628/107373703-6c5ebf80-6aac-11eb-96e4-4d4af4a90397.mp4

Win 10 2004, 9900k, 3080 driver version 460.79
[RPCS3.log](https://github.com/RPCS3/rpcs3/files/5951738/RPCS3.log)

**Comment by Satan86** [comment] 2021-02-09 14:20
I also get flickering in vehicles, which did not occur before. I remember the 60 FPS patch used to cause that, but now it seems to happen regardless of it being on/off. I tried a version without the screen flashing issue and it still happened there, so probably unrelated and would require more testing to find the PR that broke it

**Comment by kd-11** [comment] 2021-02-09 14:42
@AphelionWasTaken @Satan86  The vehicle rubber-banding glitch has been there since the beginning. It is also a physics issue not a graphical one.  The strength of the glitch depends on the user's CPU and is entirely absent on linux, pointing to a timing issue since linux and windows do not measure thread time the same way.
I'm also unable to reproduce the OPs issue with full-screen flashing.

**Comment by Satan86** [comment] 2021-02-09 14:44
Ah, that might be why I don't remember having it back then, I had an i7-4770, and I just never noticed it because the CPU was too weak to trigger it heavily like it does now.

**Comment by Satan86** [comment] 2021-02-09 15:07
About the flashing, I tried a few different levels and the issue was a lot less present/gone in those, so try the "Seven and Seven" event in ticket 3, that's the one where I initially tested and reported the bug. Here's my save to help test
[BCES00006.zip](https://github.com/RPCS3/rpcs3/files/5952143/BCES00006.zip)

**Comment by kd-11** [comment] 2021-02-09 16:16
For now, all regressions (NVIDIA-only) are being handled in this ticket: https://github.com/RPCS3/rpcs3/issues/9648
The underlying problem is known and a fix has been in writing for the past few days. If that fix doesn't work, then we can revisit this separately.

**Comment by Yahfz** [comment] 2021-03-11 23:43
![image](https://user-images.githubusercontent.com/17715080/110869997-5d854b80-82aa-11eb-980b-3da3e71aef57.png)
closing since it fixes it and it got merged.

**Closed by Yahfz** 2021-03-11 23:43 UTC
Labels: Driver: NVIDIA, Regression
