### ISSUE TITLE
Lair [BCUS98112]  Varius Graphicsl, Performence issues and game freeze.

### ISSUE THREAD

**Issue by Nuke10** [RPCS3/rpcs3#13523] opened 2023-03-09 21:08 UTC
### Quick summary

the game have several graphical issues. frame drop, audio sync problems. and it also freezes on the 2nd level somewere arround the part were I was attacking the enemy ships.

I created a video that dmonstrate the issue:

Update: its seem like the freezing only happens when i attack this specific ship.

### Attach a log file

Log:
https://mega.nz/file/NYU1QSaY#1A3V5ltJnfb0XW-1Q4RWe8v4ypnTQniUZwOf_j5z1J0

### Attach capture files for visual issues

https://youtu.be/ipyA1_B9mu8

**Comment by Darkhost1999** [comment] 2023-03-09 21:20
Can we open multiple issue tickets?
1 for each issue instead of making a 2 to 3 years down the road "but this issue still remains" tracker report?

**Comment by Nuke10** [comment] 2023-03-10 15:04
> Can we open multiple issue tickets? 1 for each issue instead of making a 2 to 3 years down the road "but this issue still remains" tracker report?

Ohh I AM sorry. i didn't realised it would cuase problem

**Comment by Asinin3** [comment] 2023-03-12 11:59
Framedrop/performance issues are not valid. Do not make issues for that. Also audio sync issues are often caused by performance issues so be careful when making issues for that too cause its often not valid either. You should make an issue for the graphical problems with the video and a renderdoc or rsx capture. but the rest.. not so much.

**Comment by Nuke10** [comment] 2023-03-12 15:19
te
What about the part when the game just freezes? don't this warrant a an issue?

> Framedrop/performance issues are not valid. Do not make issues for that. Also audio sync issues are often caused by performance issues so be careful when making issues for that too cause its often not valid either. You should make an issue for the graphical problems with the video and a renderdoc or rsx capture. but the rest.. not so much.

Thanks for the Guidance.
what about the part when the game just freezes? aint this something that warranted an issue?

**Comment by RipleyTom** [comment] 2023-03-18 12:42
Closing as the separate issues are now tracked in:
-https://github.com/RPCS3/rpcs3/issues/13554
-https://github.com/RPCS3/rpcs3/issues/13555

**Closed by RipleyTom** 2023-03-18 12:42 UTC
