### ISSUE TITLE
Uncharted 2 new graphics problem (bces00509)

### ISSUE THREAD

**Issue by Krishster** [RPCS3/rpcs3#9013] opened 2020-10-02 07:31 UTC
New graphics problem arise while playing uncharted 2 (bces00509). after applying zerox & illusion patches, game is running smoothly, but in chapter 6 desperate times, following graphics problem arise. this problem is not faced by zerox as confirmed by him. screen shots and log file enclosed. plz look into the issue.

1.
![Screenshot_1](https://user-images.githubusercontent.com/64323517/94898402-2450e000-04af-11eb-835f-a4f6987e719d.jpg)
2. 
![Screenshot_2](https://user-images.githubusercontent.com/64323517/94898419-2c108480-04af-11eb-8240-480e797249c4.jpg)
3. 
![Screenshot_3](https://user-images.githubusercontent.com/64323517/94898436-329efc00-04af-11eb-9c17-7ab4c08e51d3.jpg)

log file - 
[RPCS3.log.gz](https://github.com/RPCS3/rpcs3/files/5316500/RPCS3.log.gz)

**Comment by kd-11** [comment] 2020-10-02 07:47
Disable all the patches and test again; patches are not officially supported. If it is still having issues after patches removal, attach the required data (RSX capture + log file)

**Comment by Krishster** [comment] 2020-10-02 08:59
same graphics problem. rsx capture and log file attached.

as i failed to attach rsx due to huge file size, therefore i am providing gdrive link. 
https://drive.google.com/file/d/1hvelJxRyHKaRVVyucie_BK3qrlyqo6zv/view?usp=drivesdk

[RPCS3.log.gz](https://github.com/RPCS3/rpcs3/files/5316804/RPCS3.log.gz)

**Comment by kd-11** [comment] 2020-10-02 09:12
1. You have 'force CPU blit' enabled, which is a developer option that is known to intentionally break game logic. Disable and try again with stock options.
2. Install latest nvidia beta drivers which fix some silly bugs that the mainline drivers have. This is possibly a duplicate of the glitch in #9006

**Comment by Krishster** [comment] 2020-10-02 18:42
@kd-11 as per your tips, the broken graphics problem is fixed and the game progressed a little bit, but one new problem arises. when the cut scene starts the whole screen become dark and after skipping the movie, game freezes.

rsx capture is - 
[BCES00509_20201002235213_capture.zip](https://github.com/RPCS3/rpcs3/files/5319709/BCES00509_20201002235213_capture.zip)

rpcs3 log - 
[RPCS3.log.gz](https://github.com/RPCS3/rpcs3/files/5319712/RPCS3.log.gz)

can you look the matter.

**Closed** 2020-10-04 17:18 UTC
Labels: Need Information
