### ISSUE TITLE
Backbreaker Vengenance [NPEB00592] Freezes constantly with PPU error

### ISSUE THREAD

**Issue by legend800** [RPCS3/rpcs3#5097] opened 2018-09-07 17:10 UTC
The Backbreaker series remains to be unstable. After a few mins of gameplay, a PPU error inevitably causes the game to freeze. Occurs even on PPU Interpreter. 

Happens on BACKBREAKER [BLUS30334] as well

PPU error:
F {PPU[0x1000002] Thread (Pool thread 0) [0x0057f8a0]} class std::runtime_error thrown: Verification failed (e=0x57): 
(in file c:\projects\rpcs3\rpcs3\emu\cell\lv2\sys_cond.cpp:279)

[RPCS3.log.gz](https://github.com/RPCS3/rpcs3/files/2361891/RPCS3.log.gz)

Windows 10 64-bit
GeForce GTX 1080
i7-6700k @ 4GHZ
16GB RAM

**Comment by elad335** [comment] 2018-09-07 17:54
duplicate of #3634

**Comment by AniLeo** [comment] 2018-09-07 17:55
Closing as duplicate of #3634

**Closed by AniLeo** 2018-09-07 17:55 UTC
