### ISSUE TITLE
Metal Gear Solid 4 [BLES00246] - Visual and Audio instabilities with Write Colour Buffers Enabled.

### ISSUE THREAD

**Issue by Bjorn29512** [RPCS3/rpcs3#12665] opened 2022-09-16 06:34 UTC
### Quick summary

WCB seems to cause crashes when calling Otacon with codec and severe audio crackling in FMVs

### Details

The very first commercial FMVs that play after selecting a new game will have severe audio crackling, Once you load into the game and get to control snake calling otacon on codec will always cause the "VM: Access violation reading location 0xff00000c (unmapped memory)" Crash. 

### Attach a log file

[RPCS3.log](https://github.com/RPCS3/rpcs3/files/9581312/RPCS3.log)

### Attach capture files for visual issues

Audio Issue : 
https://user-images.githubusercontent.com/110204265/190572217-46fe7f73-3ad0-4ccc-9b7e-60a393055894.mp4

Crash : 
![image](https://user-images.githubusercontent.com/110204265/190572267-17708e08-c722-45b5-a7b5-6fe8f345c15e.png)

### System configuration

SPECS: 
- 12th Gen Intel(R) Core(TM) i5-12400F | 12 Threads | 31.82 GiB RAM | TSC: 2.496GHz | AVX-512+ | FMA3
- Operating system: Windows, Major: 10, Minor: 0, Build: 22000, Service Pack: none, Compatibility mode: 0
- vulkan-compatible GPU: 'NVIDIA GeForce GTX 1660 SUPER' running on driver 516.94.0.0
- Firmware version: 4.88

### Other details

All these issues can be "fixed" by disabling WCB but i felt its still worth making a report for record purposes.

**Comment by solarmystic** [comment] 2022-09-16 07:23
Can reproduce the crashing issue when calling Otacon with WCB enabled 
[RPCS3.log.gz](https://github.com/RPCS3/rpcs3/files/9581640/RPCS3.log.gz)

**Comment by Tarek2013** [comment] 2022-09-16 16:23
I had the same pb before but I found that the balance between frequency and frame limit was pb.

So,try with this settings : 
Renderer : Vulkan
Frame limit : 60
Anisotropic filter : x6
Anti-Aliasing : Auto
ZCULL Accuracy : Relaxed
Resolution Scale Threshold : 512x512 (if you play up to original resolution)
Write Color Buffer : On
Shader Mode : Async (Multi threaded)

Disable TSX and Accurate RSX reservation
PPU LLVM : ON
Silence All logs : ON
Force disable exclusive Fullscreen : ON
RSX FIFO Accuracy : Atomic
Driver Wake-up Delay : 200
Vblank Frequency : 60hz

Let me know if it could help ;)

**Comment by kd-11** [comment] 2022-10-02 12:49
This bug is insane :laughing:
Even just locking one specific page causes the game to freak out. There are signs of memory corruption, where it seems the game is storing a list of pointers immediately after a memory block it is using as a rendertarget. I've checked WCB and it seems to be working as it is supposed to, now I just need to figure out why the memory is getting overwritten with opaque black (0xff000000) where there was a pointer address before.

**Comment by Bjorn29512** [comment] 2022-10-02 12:54
> This bug is insane 😆 Even just locking one specific page causes the game to freak out. There are signs of memory corruption, where it seems the game is storing a list of pointers immediately after a memory block it is using as a rendertarget. I've checked WCB and it seems to be working as it is supposed to, now I just need to figure out why the memory is getting overwritten with opaque black (0xff000000) where there was a pointer address before.

Appreciate your hard work 🙏 , WCB also causes audio issues in the intro FMVs not sure why it does that, if you need anything from my end testing/info etc feel free to ask.

**Comment by kd-11** [comment] 2022-10-02 15:26
Fixed by https://github.com/RPCS3/rpcs3/pull/12746

**Comment by Jonathan44062** [comment] 2022-10-02 21:02
Testing the PR build, but the audio kinda breaks when you pause the menu
https://user-images.githubusercontent.com/78843189/193476014-7292e879-504d-4c03-83ac-5baa8380ce3a.mp4
[RPCS3.log.gz](https://github.com/RPCS3/rpcs3/files/9693591/RPCS3.log.gz)

**Comment by Bjorn29512** [comment] 2022-10-02 22:09
> Fixed by #12746

the codec crashes have been fixed 🙏  but the audio crackling in FMVs still persists, that doesnt happen with WCB disabled.

**Comment by kd-11** [comment] 2022-10-02 22:59
That's a CPU utilization thing, I don't have it for example because I have enough cores, but it is a known issue with WCB enabled. WCB causes the game to interrupt whenever we need GPU data to get copied back, there is no way around that. We could pause the renderer when doing this and give the other threads more performance, but then we get a constant performance hit around the game. Try enabling time stretching in the audio tab, it helps a lot with crackling.

**Comment by Bjorn29512** [comment] 2022-10-02 23:29
Alright thanks a lot, will close this issue then since the core issue is resolved

**Comment by AniLeo** [comment] 2022-10-03 00:09
Pull request is still not merged

**Closed** 2022-10-03 09:57 UTC
Labels: Bug

**Comment by Tarek2013** [comment] 2022-10-18 12:24
@kd-11 
Personally , I didn't manage any issues like you mentioned before with the config I posted.
But I play with a 5950X with a 3080TI and, as you said, maybe it could be a processors number issue
Could you confirm it ?

**Comment by TheSorrowJoy** [comment] 2022-12-21 22:37
> Yes, if you have a wide cpu with many threads you are unlikely to encounter some issues such as the crackling audio one.

Hello,

there's more to I think. Switching from Ryzen 5600x to 5800x (6 cores vs 8 cores) didn't help at all, but i noticed one thing: this bug only appears when i use 60 fps limiter. Without it there're no sound problems, but fps is too high and cutscenes are unstable.
