### ISSUE TITLE
Final Fantasy XIII resolution scale does not work correctly

### ISSUE THREAD

**Issue by lextra2** [RPCS3/rpcs3#6717] opened 2019-10-06 18:47 UTC
CPU: Ryzen 5 3600
GPU: RX 580 4GB - Driver: 19.9.2
OS: Windows 10 1903
RPCS3 Build: 0.0.7-8829

The game looks insanely jagged even with a resolution scale of 350% (4480x2520)
On the real PlayStation 3 it uses 2xMSAA. Maybe this causes a conflict with the upscaling. It almost looks like the AA gets reversed when using a higher than native resolution scale. So instead of smoothing edges it increases the sharpness of them.

You can also observe a kind of shimmering on 2D elements. It is most obviously on font. If you check the font in the title screen you will see it.

[Example Video for the jaggies](https://drive.google.com/file/d/1ypzjKxSw3zwiOcKc13lGqUZaY9ZgJEQm/view)

[RPCS3.log](https://github.com/RPCS3/rpcs3/files/3694738/RPCS3.log)

**Comment by kd-11** [comment] 2019-10-06 19:35
Duplicate of https://github.com/RPCS3/rpcs3/issues/6348

**Closed by kd-11** 2019-10-06 19:35 UTC
