### ISSUE TITLE
Dark Souls: Prepare to Die Edition stuck on linking PPU modules/building SPU cache

### ISSUE THREAD

**Issue by kotn3l** [RPCS3/rpcs3#10591] opened 2021-07-20 11:54 UTC
## Quick summary
Dark Souls Prepare to Die Edition [BLES01765] worked wonderfully before, but now, it doesn't even start.

## Details
Updated or base version doesn't matter. It either gets stuck on PPU linking, or SPU cache building, usually at the very end. Attempting to stop the emulation crashes the whole app: "Some threads have probably deadlocked" If I delete the SPU cache it gets stuck on linking PPU modules. If I start it again, it stops at SPU cache building. If I delete all caches, it compiles PPU modules, then stops at linking again.

#### 1. Please provide _exact_ build (or commit) information that introduced the regression you're reporting.
Latest working build: I can't find it. After trying out many many builds, even a build from 56 days ago fails. I'll keep testing. Maybe it's something on my end?

#### 2. Please attach TWO logs:
These two logs are from different builds since I tested a lot, one stops at the SPU building, one stops at PPU linking.
[regressedSPUbuilding_RPCS3.log](https://github.com/RPCS3/rpcs3/files/6847975/regressedSPUbuilding_RPCS3.log)
[regressedPPUlinking_RPCS3.log](https://github.com/RPCS3/rpcs3/files/6847978/regressedPPUlinking_RPCS3.log)

#### 4. Please attach screenshots of your problem.
![stuck](https://user-images.githubusercontent.com/32578937/126318705-070c7b45-92d4-467d-a74f-cc30297c5b1d.png)
It gets stuck.

#### 6. Please provide your system configuration:
* OS Windows 10 x64 Build: 19043
* CPU Ryzen 5 1600X
* GPU GTX 1070 
* Driver version 471.11
* etc.

**Comment by AniLeo** [comment] 2021-07-20 11:59
Duplicate of #10486

**Closed** 2021-07-20 11:58 UTC
Labels: Meta: Duplicate
