### ISSUE TITLE
[BLUS31212] Kingdom Hearts HD 1.5 ReMIX Chain of Memories Freezing

### ISSUE THREAD

**Issue by gsingh93** [RPCS3/rpcs3#6945] opened 2019-11-03 23:21 UTC
RPCS3 Version: 0.0.7-8713-cea975f6 Alpha
OS: Windows 10 Home Version 1903 OS Build 18362.418
Processor: Intel(R) Core(TM) i5-6400 CPU @ 2.70 GHz
GPU: NVIDIA GeForce GTX 970

---

I've played through all of KH1.5 Final Mix with no issues on this version (after changing the render to Vulkan and some SPU settings as suggested on the forums) other than the after credits freeze (https://github.com/RPCS3/rpcs3/issues/4851) which isn't a big deal.

Now I'm trying to play Chain of Memories and I haven't changed any settings. Sometimes I freeze during the initial cut scene, sometimes I freeze after the cut scene when I get to the logo, and even if I skip this cut scene I freeze in the next cut scene.

I've seen two different errors so far in the log shown in UI, the most common one being `RSX: nv406e::semaphore_acquire has timed out. semaphore_address=0x403008D0`. Here is the screenshot and logs:
![KHCOM Freeze 1](https://user-images.githubusercontent.com/1012677/68093638-9575b680-fe4c-11e9-8681-6ca1ddcc0371.png)
[RPCS3.log.gz](https://github.com/RPCS3/rpcs3/files/3802285/RPCS3.log.gz)

Once I got this error instead: `cellVdecDecodeAu failed with 0x80610103 : CELL_VDEC_ERROR_BUSY [1]`. Screenshot and logs:
![KHCOM Freeze](https://user-images.githubusercontent.com/1012677/68093682-f604f380-fe4c-11e9-9d67-dd01eabe8afc.PNG)
[RPCS3.log.gz](https://github.com/RPCS3/rpcs3/files/3802291/RPCS3.log.gz)

**Comment by Baxusfox** [comment] 2019-12-11 04:07
I'm getting this same error 
![Kingdom Hearts HD 1 5 Error](https://user-images.githubusercontent.com/40281591/70590807-d080ad80-1ba1-11ea-89ca-bf3ac03072ea.jpg)

**Comment by digitaldude555** [comment] 2020-02-22 11:08
@gsingh93 @Baxusfox still freezing?

**Comment by Puremin0rez** [comment] 2020-02-23 03:57
> 
> 
> @gsingh93 @Baxusfox still freezing?

I'm not them, but this still occurs.

There's something going on with the FMVs in KH 1 & CoM. It will either randomly crash during FMV play back, or right after it ends.

I've worked around the issue by renaming the PAM video files in the game dump so the game no longer attempts to load FMVs. This workaround also fixes the credits crash in KH 1 since you can't skip that cutscene. Definitely not a real fix, but it's suitable for me until a proper solution is discovered.

https://github.com/RPCS3/rpcs3/issues/4851 is probably the same issue, but the difference is that one is always reproducible for me

**Comment by Baxusfox** [comment] 2020-02-26 01:53
As of [RPCS3 v0.0.8-9724-df1813b4 Alpha], I am still having the same issue.
[RPCS3.log.gz](https://github.com/RPCS3/rpcs3/files/4253024/RPCS3.log.gz)

**Comment by fgiannesini** [comment] 2020-12-17 07:55
On my side, the game does not freeze on the opening FVM. 
By the way, the emulator crash and exit after the following dialogs, before controlling the character.

[RPCS3.log](https://github.com/RPCS3/rpcs3/files/5707752/RPCS3.log)

**Comment by fgiannesini** [comment] 2021-01-26 12:12
The workaround of issue https://github.com/RPCS3/rpcs3/issues/9655 solves this problem too

**Comment by archbunkz** [comment] 2021-02-18 22:50
is there any chance of another workaround or solution? i'm unable to disable accurate dfma due to my cpu supporting FMA

**Comment by Darkhost1999** [comment] 2021-10-11 15:42
Workaround is simply to hit the start button and skip the cinematic.
You can get in game this way. Otherwise you're still today stuck on the cutscene as soon as the title of the game shows up.

**Comment by Darkhost1999** [comment] 2022-05-10 22:44
@gsingh93 retest
I got some slowdown but can no longer reproduce freeze on latest Master. Don't forget to use new cache.
No workaround needed
[RPCS3.log.gz](https://github.com/RPCS3/rpcs3/files/8665398/RPCS3.log.gz)
Driver Wake-up Delay is set to 200 µs

**Comment by Asinin3** [comment] 2022-05-22 08:12
So, I have no idea why no one tested this, but libvdec.sprx fixes the issue of the game freezing when intro cutscene ends. I figured this out myself and couldn't work out why an aI figured it may have been fixed by one of megamouse's recent libvdec PR's which was why no one mentioned it... But I went back to an old build, and it was still working.

https://user-images.githubusercontent.com/15137035/169685005-ac2f329f-3c67-4fcf-ac0c-91c8a0deb7a3.mp4

**Closed by Asinin3** 2022-05-22 08:12 UTC
