### ISSUE TITLE
Gran Turismo 5 - BCUS98114 v2.11

### ISSUE THREAD

**Issue by kn0xx01** [RPCS3/rpcs3#10192] opened 2021-04-25 16:19 UTC
## Quick summary
Please briefly describe what is not working correctly.

Fatal Error

·F 0:06:14.863049 {RSX [0x1ace87c]} SIG: Thread terminated due to fatal error: Verification failed
(in file D:\a\1\s\rpcs3\Emu\RSX\VK\VKTextureCache.h:813[:4], in function create_new_texture)
·W 0:06:14.862700 {PPU[0x1000040] Thread (ZYWr6) [0x01b74f74]} sys_lwmutex: _sys_lwmutex_create(lwmutex_id=*0xd018a890, protocol=0x2, control=*0xd018aae0, has_name=0x80000001, name=0xd018ab90 (“”))
·W 0:06:14.863665 {cellAudio Thread} cellAudio: Audio backend stopped unexpectedly, likely due to a buffer underrun
·! 0:06:29.972497 SYS: Stopping emulator...

## Details

Please describe the problem as accurately as possible.
B-Spec -> Beginner Series -> World Compact Car Race -> Choose "CIRCUIT MADRID Mini"
It loads all car, and screen. after click "Start" ....it goes fatal error.

#### 1. Please attach RPCS3's log.
[RPCS3.zip](https://github.com/RPCS3/rpcs3/files/6372358/RPCS3.zip)

#### 3. Please attach screenshots of your problem.

![image_1](https://user-images.githubusercontent.com/25436327/116000945-2795ef80-a5ea-11eb-86b8-a5f81dc723d1.PNG)

#### 5. Please provide your system configuration:
* OS: Windows 10 64-bit
* CPU: AMD Ryzen 5 2600 @ 3.85 fixed.
* GPU: RTX 2070 
* Driver version: Nvidia 466.11
* etc.

#### Please include.
* Anything else you deem to be important
Current config most stable i could find for my specs.

[config_BCUS98114.zip](https://github.com/RPCS3/rpcs3/files/6372387/config_BCUS98114.zip)

**Comment by Satan86** [comment] 2021-04-25 16:21
duplicate of #9845

**Closed** 2021-04-25 16:21 UTC

**Comment by kn0xx01** [comment] 2021-04-25 16:22
Suzuka circuit didnt gave any errors.

**Comment by AniLeo** [comment] 2021-04-25 16:23
Same assert nevertheless
