### ISSUE TITLE
Uncharted - master 6675 vs 6692 - Bad performance with Vulkan

### ISSUE THREAD

**Issue by DeadorAlive5** [RPCS3/rpcs3#4525] opened 2018-05-06 05:46 UTC
OpenGL
![6692og](https://user-images.githubusercontent.com/39018728/39670243-9aec8f6e-50d6-11e8-8d35-d8283fd17242.png)
![6675og](https://user-images.githubusercontent.com/39018728/39670246-a68d7248-50d6-11e8-97bc-d6981b7a274c.png)

Vulkan
![6692vk](https://user-images.githubusercontent.com/39018728/39670256-c44ab9d0-50d6-11e8-89f7-eaa845824be2.png)
![6675vk](https://user-images.githubusercontent.com/39018728/39670258-ca65c77e-50d6-11e8-93c8-12edaad526f2.png)

Windows 10, i5-7600K, gtx 970.

**Comment by Asinin3** [comment] 2018-05-06 05:48
Duplicate of #4506

**Closed** 2018-05-06 11:37 UTC
Labels: Meta: Duplicate
