### ISSUE TITLE
Regression in current master branch

### ISSUE THREAD

**Issue by jobs-git** [RPCS3/rpcs3#4560] opened 2018-05-13 12:38 UTC
Fatal Error on Game Boot up

`F {PPU[0x1000000] Thread (main_thread)} class std::runtime_error thrown: Verification failed (e=0xb7) (0): 
(in file Emu\Cell\SPUASMJITRecompiler.cpp:2753)`

G: D3 BLUS31437
Vulkan
SPUASMJIT
PPU LLVM

The binary I used are the updated files just before kd-11 merged it, its now the master. 

Based from the error, I think this must be related to the SPUASMJIT cache.

[RPCS3.log](https://github.com/RPCS3/rpcs3/files/1998445/RPCS3.log)

**Comment by Megamouse** [comment] 2018-05-13 12:40
duplicate of #4556

**Closed** 2018-05-13 12:57 UTC
