### ISSUE TITLE
Vulkan broken on Linux by #3994

### ISSUE THREAD

**Issue by zekesonxx** [RPCS3/rpcs3#4044] opened 2018-01-12 00:18 UTC
Title. Vulkan works on 51a2b43d8195622328a30667c2b0662c8dc4fe65, but not on fbceec47b84c16d73ab53188ee33e504fbbb0808 (#3994).

`F RSX: Could not find a vulkan compatible GPU driver. Your GPU(s) may not support Vulkan, or you need to install the vulkan runtime and drivers`

Tested on Arch Linux, kernel 4.13.12, Nvidia drivers 386.34, Wayland version 1.14, xfce4 (Wayland not in use, obviously).

Issue created with @hcorion's love and support.

**Comment by hcorion** [comment] 2018-01-12 00:22
I can also reproduce, Arch Linux, NVIDIA GTX 1070, driver version 387.34, KDE Plasma 5.11.5. Wayland is installed, but not in use.

Tagging @myfreeweb

**Comment by hcorion** [comment] 2018-01-12 00:28
Works with the latest AppImage downloaded from https://rpcs3.net/download , presumably because the AppImages don't build with wayland.

**Comment by myfreeweb** [comment] 2018-01-12 10:59
huh. Looks like this error happens when this function fails https://github.com/RPCS3/rpcs3/blob/5959411aeb204fdccf2798040f29a9906527d4e5/rpcs3/Emu/RSX/VK/VKHelpers.h#L1204 not much was changed here, why would it fail on nvidia specifically? Are the `VK_KHR_XLIB_SURFACE_EXTENSION_NAME` etc. defines somehow wrong?

**Comment by kd-11** [comment] 2018-01-12 12:12
Maybe we just need to edit the cmake file to not enable wayland unless explicitly requested via config. When wayland is not available, vulkan runs fine.

**Comment by kd-11** [comment] 2018-01-12 12:55
Ugh
```
#else
				VK_KHR_XLIB_SURFACE_EXTENSION_NAME,
#endif
#ifdef VK_USE_PLATFORM_WAYLAND_KHR
				VK_KHR_WAYLAND_SURFACE_EXTENSION_NAME,
#endif
```
Only one should be requested at a time, not both. Either wayland or X but not wayland and X

**Comment by kd-11** [comment] 2018-01-12 13:00
Retest with https://github.com/kd-11/rpcs3/commit/73442a74a8b3cc4cba2220eac87067fe414fa7e4

**Comment by kd-11** [comment] 2018-01-12 13:08
A potentially better way of doing it https://github.com/kd-11/rpcs3/commit/5369d2a2a2244176af44fb0fd7ec52e2858bbb4e
To enable wayland, pass USE_WAYLAND_EGL=ON to cmake, otherwise it should use X
I dont have wayland on my setup to actually test this

**Comment by myfreeweb** [comment] 2018-01-12 15:43
Oh. Yeah, right, that's a list where everything must be present. I'll make it a runtime decision.

(BTW, what nvidia doesn't support is GBM – Wayland compositors can work on their proprietary driver if they implement EGLStreams. They just didn't implement the Wayland surface, it seems.)

**Comment by kd-11** [comment] 2018-01-12 18:02
Yea, its best to compile globally with xlib and have a cmake arg for wayland support, at least until support is universal. All vulkan drivers on linux support xlib surface but not all support wayland, and it might be that way for a while.

**Comment by greentop** [comment] 2018-01-13 01:37
PR #4048 corrects the Vulkan problem also seen in Ubuntu 16.04 using Nvidia 387.34.

**Comment by kd-11** [comment] 2018-01-18 12:29
Closing as fixed

**Closed by kd-11** 2018-01-18 12:29 UTC
