### ISSUE TITLE
[Feature request] Add GameControllerDB

### ISSUE THREAD

**Issue by IAmTheRedSpy** [RPCS3/rpcs3#14434] opened 2023-08-06 05:33 UTC
### Quick summary

SDL support is amazing but some controller don't work with SDL. https://github.com/gabomdq/SDL_GameControllerDB provides mappings for these controllers.

### Details

This feature will affect UI, specifically input handling, and will increase the number of game controllers which can be used. 

[gamecontrollerdb.txt](https://github.com/gabomdq/SDL_GameControllerDB/blob/master/gamecontrollerdb.txt) contains a list of mappings which allow many controllers to be used with SDL applications. Some controllers may still require user-side remapping in RPCS3, but RPCS3 would be able to read the buttons and axes properly.

 ---

The change would be pretty simple: 

- Include [gamecontrollerdb.txt](https://github.com/gabomdq/SDL_GameControllerDB/blob/master/gamecontrollerdb.txt) under the [3rdparty folder](https://github.com/RPCS3/rpcs3/tree/master/3rdparty)
- Add [SDL_GameControllerAddMappingsFromFile](https://wiki.libsdl.org/SDL2/SDL_GameControllerAddMappingsFromFile) for SDL2 or SDL_AddGamepadMappingsFromFile for SDL3 to [Input/sdl_pad_handler.cpp](https://github.com/RPCS3/rpcs3/blob/master/rpcs3/Input/sdl_pad_handler.cpp) with error handling
  - [SDL/test/testcontroller.c](https://github.com/libsdl-org/SDL/blob/080b1dfbdb7db0b3db3bf2f750cb645cf3397b74/test/testcontroller.c#L1875) has an example of using SDL_AddGamepadMappingsFromFile for SDL3

**Comment by eVenent** [comment] 2023-08-17 17:54
This is a great idea! GameControllerDB is the biggest list of mappings for controllers. It works well on [Ryujinx](https://github.com/Ryujinx/Ryujinx). You just have to press one button and the rest of the inputs are filled automatically. For sure it's worth implementing this feature.

**Comment by Megamouse** [comment] 2023-08-26 11:39
Wait. so is this meant for SDL to recognize controllers, or is this meant for auto-mapping ?

**Comment by eVenent** [comment] 2023-08-26 13:09
GameControllerDB is [helping auto-mapping](https://github.com/gabomdq/SDL_GameControllerDB#mapping-guide) every controller from the list. It can work like you are pressing one button, and other are automatically filled with proper buttons or the same by pressing AutoMap button. 

I would recommend add somewhere version check of GameControllerDB file or button for manual update of the list, to always have the newest version. Community is updating it very frequently.

**Comment by Megamouse** [comment] 2023-08-26 13:12
Well, I'm not gonna add an automap button for now.
Which is why I'm wondering if just adding the database helps to some degree.

**Comment by IAmTheRedSpy** [comment] 2023-08-27 01:38
My understanding is that it applies automatically but I've never written anything using it myself. I have a controller that only works in the SDL test app using these mappings, so I can test.

**Comment by dirkNlerxst** [comment] 2023-08-27 17:56
Thank you for looking into this, I'm hoping implementing this may also help my issue here: #13195 

Will this then support controllers that are not on the GameControllerDB? This is where my issue falls, as these controllers are recognized and mappable by SDL Gamepad Tool and all emus using SDL on macOS (dolphin, pcsx2, duckstation). RPCS3 is only recognizing them once I use SDL Gamepad Tool to map and then using "Set Mapping as Environment Variable", which then creates a shell script setenv.sh:
`launchctl setenv SDL_GAMECONTROLLERCONFIG "03000000ba1200000002000013030000,Harmonix Guitar for PlayStationÃ3,platform:Mac OS X,a:b1,b:b2,back:b8,dpdown:h0.4,dpleft:h0.8,dpright:h0.2,dpup:h0.1,guide:b12,leftshoulder:b4,leftstick:b10,lefttrigger:a3,leftx:a0,lefty:a1,rightshoulder:b5,rightstick:b11,righttrigger:a4,rightx:a2,righty:a5,start:b9,x:b0,y:b3,"
`
Which then has RPCS3 recognize the controller. But it cannot recognize it natively without doing this.

**Comment by Darkhost1999** [comment] 2023-08-27 21:05
> Will this then support controllers that are not on the GameControllerDB?

What you're talking about is the create a new mapping feature on the game controller database github page.
It's a text file. Just edit it in your text editor and add the controller to the database. The only problem is if we ship this database file out with rpcs3 is you'll need to update it manually every single time RPCS3 updates.
Which is why most other emulators require the user to download the database file and put it in the typical location right next to the .exe.

Your information about setting the environment looks exactly like the information you just put in the text file and be done with it. Currently sounds like you may have needed to do that before this upcoming PR. But definitely shouldn't be needed after.

If you do create a new mapping you can open a pull request in the database github to get them to update their database and if RPCS3 pulls and ships the file with every update then the next RPCS3 update following the database update will have your new mappings.

**Comment by IAmTheRedSpy** [comment] 2023-08-28 00:59
The current merge request looks to **automatically** update the DB while packaging RPCS3, so the latest version of RPCS3 will always have a reasonably recent version of the DB.

@dirkNlerxst your best bet is to submit an issue to https://github.com/gabomdq/SDL_GameControllerDB/issues. I've seen some mappings get added by just posting that mapping string in your comment, so you won't even need to edit the DB yourself.

**Comment by Megamouse** [comment] 2023-08-28 19:23
Please just test the PR.
So far nobody confirmed that it works.

**Comment by IAmTheRedSpy** [comment] 2023-08-28 22:56
Is there a packaged version somewhere? I'm struggling to build it locally

**Comment by dirkNlerxst** [comment] 2023-08-28 22:57
Just got a hold of a windows machine, I can confirm the database is pulled correctly and am testing in game.

**Comment by dirkNlerxst** [comment] 2023-08-28 22:57
@IAmTheRedSpy I grabbed it from here : https://cirrus-ci.com/task/5663416950456320

**Comment by IAmTheRedSpy** [comment] 2023-08-28 23:09
Thanks!
The version from https://cirrus-ci.com/task/6226366903877632 works perfectly too. Tested in the gamepad settings which can now read my controller's axes and buttons, whereas before it was nonsense.

**Comment by dirkNlerxst** [comment] 2023-08-28 23:43
Two issues I'm having:

1) Entering game seems to be mapping Player 1 and Player 2 to SDL, despite only mapping Player 1 to SDL and Player 2-7 to null. Going to Gamepad settings while in game Player 2 is now set to "Reserved"

2) After closing game and going to Gamepad settings, SDL no longer locates the controller and throws `E SDL: Could not open device 0! SDL Error: IDirectInputDevice8::SetCooperativeLevel() DirectX error 0x80070006 x4`

[RPCS3.log](https://github.com/RPCS3/rpcs3/files/12458872/RPCS3.log)

**Comment by IAmTheRedSpy** [comment] 2023-08-29 00:11
I am unable to reproduce either issue on Linux.

**Closed** 2023-08-29 01:19 UTC
Labels: Input
