### ISSUE TITLE
Strang gta 5 glitch

### ISSUE THREAD

**Issue by Simplr69** [RPCS3/rpcs3#14039] opened 2023-06-16 19:14 UTC
### Quick summary

The title says it all
![wiered](https://github.com/RPCS3/rpcs3/assets/106102428/9db83efe-c136-4612-ac1c-fd0eaa3cfcd1)

### Attach a log file

https://1drv.ms/u/s!Agy4iUurctyugc4NaBeJF7fGfHddiw?e=r83iLX

**Comment by MarioSonic2987** [comment] 2023-06-16 19:54
Cannot reproduce on NVIDIA GTX 1060 (536.23)
![image](https://github.com/RPCS3/rpcs3/assets/20027681/cb39c940-41a9-45ba-a7c7-e9a4316b8e6d)
![image](https://github.com/RPCS3/rpcs3/assets/20027681/d969dbc6-227a-4a98-9bad-1ce7d537bd7f)

**Comment by Simplr69** [comment] 2023-06-16 20:18
did you do the father-son mission? cuz its on there

**Comment by Simplr69** [comment] 2023-06-16 20:18
plus i use amd

**Comment by MarioSonic2987** [comment] 2023-06-16 22:07
I can't reproduce that glitch in that mission:
![image](https://github.com/RPCS3/rpcs3/assets/20027681/1fc8fb8c-7b4d-4f4c-ab7e-38b3b7134079)

**Comment by ynhhoJ** [comment] 2023-06-17 06:38
Are you sure that your GPU is not dying?

**Comment by AniLeo** [comment] 2023-06-17 20:21
Log shows outdated AMD GPU drivers.
Needs to be retested with latest drivers.

**Comment by AniLeo** [comment] 2023-06-24 15:11
Closing due to the lack of information, plus using outdated GPU drivers prior to 23.2.1

**Closed by AniLeo** 2023-06-24 15:11 UTC
Labels: Need Information
