### ISSUE TITLE
[Feature Request] Desktop shortcut for games

### ISSUE THREAD

**Issue by boutzamat** [RPCS3/rpcs3#10811] opened 2021-09-02 07:19 UTC
## Quick summary
An option to launch games directly from the desktop.

## Details
Would be awesome to be able to create shortcuts to launch games directly from the desktop like a native PC game.
If RPCS3 supports launch arguments it can be done manually but an option in the right-click menu would be nice to have.

#### 1. Please describe, what part of RPCS3 would be affected by your feature:
Etc.

#### 2. Please tell us, why your feature is important to RPCS3.
Would be more user-friendly and seamless on PC.

#### 3. Please attach screenshots of the feature implemented in other projects.
*Steam*

#### 4. Please provide your system configuration:
* OS: Windows 11
* CPU: Intel 10900K
* GPU: Nvidia 2080ti

**Comment by Megamouse** [comment] 2021-09-02 09:03
Duplicate of #9806

**Closed by Megamouse** 2021-09-02 09:03 UTC
Labels: Meta: Duplicate, Enhancement, GUI
