### ISSUE TITLE
God of War Ascension - VM: Access violation reading location 0x8 (unmapped memory)

### ISSUE THREAD

**Issue by sikron** [RPCS3/rpcs3#9445] opened 2020-12-16 13:41 UTC
Hi!
thx for this great emulator and helping me out :-) !

### Details
i got this error consistently at the same point in the game (BCUS98232):
```
·F 0:06:41.687028 {PPU[0x1000000] Thread (main_thread) [0x0020afbc]} VM: Access violation reading location 0x8 (unmapped memory) [type=u32]
```

#### My system configuration:
* RPCS3 v0.0.13-11409-6b3f722f Alpha | HEAD | Firmware version: 4.85
* Operating system: Windows, Major: 10, Minor: 0, Build: 18363, Service Pack: none, Compatibility mode: 0
* AMD Ryzen 5 3600 6-Core Processor, 16GB RAM 3200 Mhz
* ·A 0:00:00.206741 RSX: Found vulkan-compatible GPU: 'GeForce GTX 950' running on driver 442.59.0.0

**Comment by AniLeo** [comment] 2020-12-16 14:48
---

**Please read [**the guidelines**](https://github.com/RPCS3/rpcs3/blob/master/.github/CONTRIBUTING.md) before opening an issue.**

Remember that the GitHub Issue Tracker is not the place to [**ask for support**](https://github.com/RPCS3/rpcs3/wiki/How-to-ask-for-Support) or to [**submit Game Compatibility reports**](https://github.com/RPCS3/rpcs3/wiki/Game-Compatibility).

The issue has been marked as **Invalid** and closed.

**Closed by AniLeo** 2020-12-16 14:48 UTC

**Comment by sikron** [comment] 2020-12-16 14:55
ah, really sorry, i forgot the log :-( can you re-open again plz?
[RPCS3.log.gz](https://github.com/RPCS3/rpcs3/files/5703455/RPCS3.log.gz)

**Comment by AniLeo** [comment] 2020-12-16 14:56
You have some other things wrong in your setup, it's better if you submit a support request so it's solved through there, if it's determined it's an application bug we can reopen with full reproduction instructions

**Comment by sikron** [comment] 2020-12-16 18:42
for reference: i switched to `Interpreter (fast)` for PPU Decoder and `ASMJIT Recompiler` for SPU Decoder temporarily and could so play through that problematic part without issues (albeit a little slow :-) )

**Comment by AniLeo** [comment] 2020-12-16 18:45
The issue is likely fixed properly through other settings, if it is what I think it is then you're working around the problem by not using LLVM, and it very likely works when using LLVM Recompilers with the correct settings, you can check on support
