### ISSUE TITLE
NINJA GAIDEN 3 Razors Edge[BLJM61010] often crashes before play CG video

### ISSUE THREAD

**Issue by arcadee1977** [RPCS3/rpcs3#8381] opened 2020-06-07 14:06 UTC
For example, after the tecmo logo , before play the "Teamninja" video,  the game crashes .

This is the error log (All crashes are the same error) : 
**F {PPU[0x1000000] Thread (main_thread) [0x0324c3c0]} VM: Access violation reading location 0x38 (unmapped memory)**

**Comment by Megamouse** [comment] 2020-06-07 14:13
duplicate of #6231

**Closed by Megamouse** 2020-06-07 14:13 UTC
