### ISSUE TITLE
Dragons Crown NPUB31235

### ISSUE THREAD

**Issue by Stressoteric** [RPCS3/rpcs3#3835] opened 2017-12-03 08:08 UTC
Game no longer boots and hangs at "Now Loading" screen after trophy screen.

**Comment by AniLeo** [comment] 2017-12-26 04:42
Need information where it regressed otherwise it's an invalid issue

**Comment by Sukunda** [comment] 2017-12-27 06:50
It was last working on
Pull:#3688
Author:Megamouse
Build Date:35 days ago (2017-11-20)
Download 0.0.4-6960

And does NOT work on from this build onward
Pull:#3729
Author:Megamouse
Build Date: 33 days ago (2017-11-22)
Download 0.0.4-6985

**Comment by scribam** [comment] 2018-01-02 18:23
@Stressoteric, @Sukunda Is it still an issue?
The game boots fine for me with the latest build.

![screenshot from 2018-01-02 19-19-29](https://user-images.githubusercontent.com/25406440/34494711-010638c2-eff2-11e7-9d36-535be3d2d7c4.png)

**Comment by Sukunda** [comment] 2018-01-02 19:42
On the Windows build, the same issue still occurs. Changing the renderer as well as changing the SPU or PPU doesn't seem to fix the problem. I've tried just about every option that I thought could make it load and it failed to do so with all of them. I tried with the build you used as well as the current build (0.0.4-7423).

**Comment by spyropt** [comment] 2018-01-02 19:57
I am using the same build and it works fine with vulkan default settings
![image](https://user-images.githubusercontent.com/34097932/34497837-23bd2b14-eff7-11e7-987f-448e9dce77e1.png)

**Comment by Sukunda** [comment] 2018-01-03 02:54
I'm not sure as to what I could be doing wrong. The old build still functions properly but the new builds do not.

**Comment by AniLeo** [comment] 2018-01-06 02:19
Compare checksums, the hardware you're using perhaps.

It's either bad dump or some hardware specific bug.

**Comment by Stressoteric** [comment] 2018-01-10 23:13
Refused to boot for me under recent versions until I tried a completely clean install of the emulator, under which it now boots no problem.

**Comment by AniLeo** [comment] 2018-01-11 21:43
Closing issue then as solved

**Comment by Sukunda** [comment] 2018-01-13 18:08
I still have the issue and I always use a clean install when testing new builds.

**Comment by jimmyshiau** [comment] 2018-06-07 07:17
@Sukunda 
https://github.com/RPCS3/rpcs3/issues/3013#issuecomment-341941818
Set `Load liblv2.sprx only` works for me

**Comment by Megamouse** [comment] 2018-06-24 09:13
no logs and confirmed to be working by multiple users.
This should be closed

**Comment by AniLeo** [comment] 2018-07-06 18:01
Closing, no one is able to reproduce and there is no proper information to even attempt debugging this assuming it is an issue

**Closed by AniLeo** 2018-07-06 18:01 UTC
