### ISSUE TITLE
RPCS3 randomly when using totally VRAM freeze the OS Linux

### ISSUE THREAD

**Issue by Augusto7743** [RPCS3/rpcs3#14655] opened 2023-09-18 08:18 UTC
### Quick summary

Hello.
Thanks for reading my topic.
I have used RPCS3 Linux version since 2020.
Always when the VRAM is totally used in RPCS3 log window is showed message about not was possible allocate enough memory in VRAM and stopping the emulation. Thus was need to use less resolution size.
I have used some recent version since 2023-04 and when the VRAM is totally the emulation continue running being an behavior never had happened before, but happen an problem.
Randomly when RPCS3 use totally VRAM freeze the OS Linux Ubuntu 20.04 and screen will be black. Some times will continue having process, but no any screen output. Need luck to screen image return. if not need press computer power button and wait if the OS will be done an correct shutdown or need an forced reset button.

Using Nvidia driver 470 in an Geforce GT 640.
Ubuntu is using X11. Not tested usig wayland.
That problem is happening with other users too ?
Here using RPCS3 0.0.29-15620 recent version.

If happen again I will try upload an log.

Have an nice week.

### Attach a log file

[zero size.log](https://github.com/RPCS3/rpcs3/files/12645800/zero.size.log)

**Comment by kd-11** [comment] 2023-11-23 11:26
This is obviously a driver bug. The old versions managed memory differently and were not efficient while the new version will spill into your system RAM when VRAM runs out which is still driver managed. The general rule is that (non-malicious) usermode cannot kill the kernel, so if your system really is locked up then you have a problem somewhere else. Try upgrading the kernel to the latest one and see if the problem goes away.

**Comment by Augusto7743** [comment] 2023-11-23 14:55
Hello kd-11.
Thanks very much replying and your amazing work in rsx code.

In moment using geforce updated driver and kernel 6.2.16.
Not seeing that problem happening again.

I had started an game with RPCS3 using default 1280X720 upscaled to OS resolution 1920X1080 and emulation was stopped with RPCS3 log message "not available VRAM".
For run the game was need use 960X540 and Fidelity FX for fix the aliasing.
BTW thanks for your latest rsx coding about WCB and RCB. I not understand if you have done any optimization because are more faster.
I not have an powerful machine, but the enough to run all my PS3 console games. Even being an AMD FX 6 cores now in the latest versions enabling WCB+RCB not an big hit in performance. In other words in current version WCB+RCB disabled an game run in 55 FPS and enabling both plus Handle RSX Memory Tiling run average 50 FPS. Others games have similar performance when enabling both settings.
Perhaps for current good machines WCB+RCB not does any performance hit.

"The old versions managed memory differently and were not efficient while the new version will spill into your system RAM when VRAM runs out which is still driver managed"
Is possible system RAM being "extra RAM" for GPU when VRAM was totally used ? If yes need enable it or is automatic ?
If yes is the reply I will try information in Nvidia forums.

Have an nice day and good luck in your life.

**Comment by kd-11** [comment] 2023-11-24 00:05
> In moment using geforce updated driver and kernel 6.2.16.
Not seeing that problem happening again.

In that case I will close this ticket since the issue is solved with a driver update.

> Is possible system RAM being "extra RAM" for GPU when VRAM was totally used ? If yes need enable it or is automatic ?

It is implemented automatically. If you check memory usage, once VRAM is full it will start to use RAM for some things. If it still has an error, you just have to turn off some settings like MSAA and use low resolution scale.

**Closed by kd-11** 2023-11-24 00:05 UTC

**Comment by Augusto7743** [comment] 2023-11-24 10:15
Thanks very much.
Have an good friday.

**Comment by Augusto7743** [comment] 2023-12-20 13:37
only sharing an information.
see the link below
https://forums.developer.nvidia.com/t/non-existent-shared-vram-on-nvidia-linux-drivers/260304
https://forums.developer.nvidia.com/t/vram-allocation-issues/239678/19

Linux not has exactly vram shared in system memory.
Now I understand because Linus Torvalds demand an better driver support from Nvidia in Linux drivers.
However is as Nvidia not does any priority for Linux.
