### ISSUE TITLE
2 Bugs in The Simpsons Game

### ISSUE THREAD

**Issue by tomaseyu** [RPCS3/rpcs3#13137] opened 2022-12-28 13:15 UTC
### Quick summary

Bug 1: The game doesn't detect the controller on start up.
Bug 2: The game crashes, making it unplayable (at 1080p).

### Details

Bug 1: The game doesn't detect the controller on start up.

When starting the game it asks to press start to continue, it detects the inital start, but then takes me to a screen where it asks me to reconnect my controller and press start to continue. Disconnecting and reconnecting my controller takes care of this problem. 
![Screenshot 2022-12-28 135038](https://user-images.githubusercontent.com/72070675/209816681-71fd6b15-186a-4727-b82e-032cb73e754f.png)

Bug 2: The Game crashes making it unplayable (crashes when I select 1080p)

I initially played with 1080p as the default resolution and the very first mission worked well, but after completing the first level  the game crashes. Now every time I restart the game and press continue the game crashes. This crash only happens when I use 1080p as the default resolution, when I select 720p it works.
![Screenshot 2022-12-28 135544](https://user-images.githubusercontent.com/72070675/209817044-ca78deb7-20b8-4305-a05a-85747a4a2d6f.png)

### Attach a log file

This is the log file of when I start the game and press continue.
[RPCS3.log](https://github.com/RPCS3/rpcs3/files/10314362/RPCS3.log)

This is the last few things the console within RPCS3 says.
![Screenshot 2022-12-28 135831](https://user-images.githubusercontent.com/72070675/209817240-dc329b7a-e1e1-4405-a133-c5ee1b0e3d5a.png)

### System configuration

Intel 7-11800H
Nvidia 3050 Ti (Laptop) Studio Driver 527.56
48GB Ram
1080p 120Hz Screen

### Other details

**Crashes when I set 1080p as default resolution within RPCS3 settings.**

**Comment by YuriNator557** [comment] 2022-12-28 13:24
Bug 1 is a duplicate of #6093
For Bug 2, it is not recommended to change the base resolution from 1280x720 due to issues like this, this is far from the only game that has issues when you do that

**Closed** 2022-12-28 13:36 UTC
