### ISSUE TITLE
Gran Turismo 5 RSX Class std ERROR

### ISSUE THREAD

**Issue by Wizzy2018** [RPCS3/rpcs3#6568] opened 2019-09-16 12:33 UTC
Hi guys.
I getting this error almost every time idk why it happens randomly when i play GT 5.The whole emulator frezzes.
{RSX [0x135cbd4]} RSX: class std::runtime_error thrown: Verification failed: 
(in file C:\projects\rpcs3\rpcs3\Emu\RSX\VK\VKTexture.cpp:85)
Here is a log to
[RPCS3.log.gz](https://github.com/RPCS3/rpcs3/files/3616216/RPCS3.log.gz)

CPU-Ryzen 7 1700
RAM-DDR4-2400Mhz
GPU-RX 470 4Gb

Latest RPCS3 build 0.0.7-8712

**Comment by kd-11** [comment] 2019-09-16 13:06
Duplicate of https://github.com/RPCS3/rpcs3/issues/5938. Ease up on the resolution upscaler.

**Closed by kd-11** 2019-09-16 13:06 UTC
