### ISSUE TITLE
Ratchet & Clank: Tools of Destruction/Resistance: Fall of Man instanced mesh system broken

### ISSUE THREAD

**Issue by JimScript** [RPCS3/rpcs3#10754] opened 2021-08-23 22:41 UTC
## Quick summary
In some early Insomniac games, only one foliage instance can be visible at a time 

## Details
In Ratchet & Clank: Tools of Destruction, New minor foliage will replace rather than supplement other older foliage.
Foliage fades in as normal:
![screenshot-2021_08_23_15_09_26](https://user-images.githubusercontent.com/66685584/130527671-7c243930-2b5c-49dd-b5b9-37ec83c5cdbc.png)
![screenshot-2021_08_23_15_09_37](https://user-images.githubusercontent.com/66685584/130527719-dd14f795-7e0e-40ca-a08c-608034aa0ff4.png)

And then when a new foliage loads in it completely replaces the old one:
![screenshot-2021_08_23_15_09_48](https://user-images.githubusercontent.com/66685584/130527798-380a594e-b83d-4445-a93b-8ef39528e0cb.png)

Now this would be a minor nitpick, if Resistance: Fall of Man (another insomniac game) didn't use the system more extensively and for a gameplay purpose like hiding mines.

Here is an RSX Capture:
[BCUS98127_20210823151612_capture.zip](https://github.com/RPCS3/rpcs3/files/7035282/BCUS98127_20210823151612_capture.zip)

And here is the system:
- SYS: RPCS3 v0.0.17-12659-d0451932 Alpha | HEAD
- SYS: AMD Ryzen 5 3600 6-Core Processor | 12 Threads | 15.95 GiB RAM | TSC: 3.600GHz | AVX+ | FMA3
- SYS: Operating system: Windows, Major: 10, Minor: 0, Build: 19043, Service Pack: none, Compatibility mode: 0
- RSX: Found vulkan-compatible GPU: 'GeForce RTX 2070 SUPER' running on driver 456.38.0.0
- SYS: Firmware version: 4.85

**Comment by JimScript** [comment] 2021-11-20 12:15
Well I might as well show an example of Resistance: Fall of Man:
![BCUS98107_screenshot_2021_11_20_04_05_48](https://user-images.githubusercontent.com/66685584/142725888-faa93518-8999-4bc4-843a-d8e5d70cb854.png)
![BCUS98107_screenshot_2021_11_20_04_05_52](https://user-images.githubusercontent.com/66685584/142725895-ca79b1fe-f561-4d79-9aeb-f7b40e2e238e.png)
![BCUS98107_screenshot_2021_11_20_04_05_58](https://user-images.githubusercontent.com/66685584/142725900-432ad45b-8434-4f8d-9d15-3736f3f3be46.png)

RSX Capture:
[BCUS98107_20211120040735_capture.zip](https://github.com/RPCS3/rpcs3/files/7574509/BCUS98107_20211120040735_capture.zip)

**Comment by JimScript** [comment] 2021-11-20 15:35
Sorry if this is confusing, here is a video of it in action:


https://user-images.githubusercontent.com/66685584/142732140-f40f2eef-92c8-493a-adfe-36ea8a87b6e0.mp4

**Comment by JimScript** [comment] 2022-02-06 23:58
Here is a visual aid on the differences between ps3 and rpcs3 foliage sorting logic in Ratchet and Clank Future: Tools of Destruction.
PS3:
![FoliageDemoPS3](https://user-images.githubusercontent.com/66685584/152706967-8ae6c899-a4ae-4814-9d52-b33ea703c1c3.gif)
RPCS3:
![FoliageDemoRPCS3](https://user-images.githubusercontent.com/66685584/152706975-7b2fc785-2b09-4f08-b59a-d7f03f2c4fc3.gif)

Sorry I couldn't get a photo or video of a real ps3, I don't own a capture card or something like that. But there is a surprising amount of foliage missing in these games because of this error, more so than I originally thought.

**Comment by JimScript** [comment] 2022-02-12 20:19
Ok, so I figured my phone picture was good enough to compare so...
PS3:
![0212221204 1](https://user-images.githubusercontent.com/66685584/153726855-834de136-3e50-4cf9-9b42-6800db9f1178.jpg)

RPCS3:
![BCUS98127_screenshot_2022_02_12_12_08_42](https://user-images.githubusercontent.com/66685584/153726869-ce06fc52-40ec-4985-b7a0-5cb746e8c7d9.png)

And with this I see that some of the foliage is in clusters that are never seen even in the culling order that RPCS3 produces for some reason. I wonder what causes it to only show one mesh at a time, but 2-3 in Resistance?

**Comment by JimScript** [comment] 2022-02-15 23:18
Along with the previously stated sorting issue, it appears that some foliage is rendering only as an outline. This example is in Quest for Booty, but it has much the same rendering as ToD does, so it is applicable to both games:
![NPUA80145_screenshot_2022_02_15_14_14_41](https://user-images.githubusercontent.com/66685584/154165955-1b6e9ac4-b53a-410f-a8a3-664ce8a6463d.png)
RSX Capture:
[NPUA80145_20220215141422_capture.zip](https://github.com/RPCS3/rpcs3/files/8075368/NPUA80145_20220215141422_capture.zip)

**Comment by JimScript** [comment] 2022-02-17 19:38
OK, so I have been playing around with renderdoc to see what the problem is and this is what I found. The missing foliage is well and truly not there, no draw calls except for one solitary plant in this foliage system, which leads me to believe this is a cpu problem. I would guess this is an spu problem as a task like this seems too minor for the ppu. What I think what is suppose to happen is this spu function is to go around and update the foliage to different levels of opacity as the camera gets closer, but in RPCS3 the function stays at the first foliage it can find until it has to make a unique mesh fully opaque wherein it goes to the new foliage and dumps the old one.

As for the outline shader, I may not know much about these things, but I don't think a single minor mesh is suppose to draw over a thousand times in a single frame. A third of the frame render time is dedicated to that one plant, and to add to that the first several hundred draws just draw the same few pixels on the screen. Although that could be just how the game does it, but that seems like a horrible optimization.

Anyway that is just some speculation on my part.

**Comment by kd-11** [comment] 2022-02-18 14:43
Needs testing on AMD/INTEL. NVIDIA is notorious for having rounding issues that can cause strange visuals like this.

**Comment by Shadowsplace** [comment] 2022-02-19 09:02
I tested it on two different machines in Tools of Destruction and got the same result.

- SYS: RPCS3 v0.0.20-13288-4be9e0d3 Alpha | HEAD
- SYS: Intel(R) Core(TM) i7-4700MQ CPU @ 2.40GHz | 8 Threads | 15.92 GiB RAM | TSC: 2.394GHz | AVX+ | FMA3
- SYS: Operating system: Windows, Major: 10, Minor: 0, Build: 19043, Service Pack: none, Compatibility mode: 0
- RSX: Found vulkan-compatible GPU: 'GeForce GTX 770M' running on driver 425.31.0.0
- SYS: Firmware version: 4.88

https://user-images.githubusercontent.com/100016968/154794078-005533c0-7fb9-48c2-82e4-9464bf43c466.mp4

- SYS: RPCS3 v0.0.20-13288-4be9e0d3 Alpha | HEAD
- SYS: AMD Ryzen 3 2200U with Radeon Vega Mobile Gfx | 4 Threads | 7.66 GiB RAM | TSC: 2.495GHz | AVX+ | FMA3
- SYS: Operating system: Windows, Major: 10, Minor: 0, Build: 19043, Service Pack: none, Compatibility mode: 0
- RSX: Found vulkan-compatible GPU: 'AMD Radeon(TM) Vega 3 Graphics' running on driver 2.0.173
- SYS: Firmware version: 4.88

https://user-images.githubusercontent.com/100016968/154793778-d76f0045-4d25-4daf-b5e6-c7f8aad328a8.mp4

Both using Vulkan but OpenGL doesn't seem to change anything (on Nvidia at least).

**Comment by JimScript** [comment] 2022-02-19 12:00
I think there are two separate issues in this issue, the foliage sorting and the outline shader. What kd-11 is talking about is the shader issue. What you have tested is the sorting issue. If you want an example of the shader problem in action, go to hoolifar island in QFB. If you don't have QFB, Planet Mukow's foliage has the same problem, so you can check it there.

**Comment by JimScript** [comment] 2022-02-28 05:25
Hey @Shadowsplace, can you check the foliage in the imperial fight festival with your AMD machine? It is different than the ones on cobalia and I was wondering if @kd-11 is right about this particular part of the issue is vendor related. And sorry I couldn't do it, I don't own any AMD gpus. Here is an example of the problem on Nvidia hardware:
![BCUS98127_screenshot_2022_02_27_14_49_44](https://user-images.githubusercontent.com/66685584/155928552-2bf437c9-84dd-48f8-9be9-7fa6df645ca4.png)
If your AMD machine still makes the foliage here an outline, then it isn't vendor related.

**Comment by Shadowsplace** [comment] 2022-03-06 00:56
Sorry about the delay. Same specs (RPCS3 v0.0.21-13333-aafd74f9 Alpha | HEAD build)

- Nvidia
![Nvidia Plant](https://user-images.githubusercontent.com/100016968/156904637-b84fd1cf-244c-48d6-8990-d91fb42b91af.JPG)

- AMD
![AMDplant](https://user-images.githubusercontent.com/100016968/156904686-1ed415b4-aa4e-45a6-ac53-f70709bed878.PNG)

It appears the issue isn't vendor related.

**Comment by JimScript** [comment] 2022-03-06 05:15
Thank you for testing this, Shadowsplace, with this we now know both issues are not vendor related. I still think that the sorting part is a spu problem, but I don't know what could cause this particular shader to render as an outline.

**Comment by JimScript** [comment] 2022-05-11 22:43
I was looking at an [old resistance video](https://www.youtube.com/watch?v=jrH-JrJIDZU) when I noticed that the amount of foliage missing is worse than Tools of Destruction's. Here is a screenshot of RPCS3 in roughly the same location as [0:28](https://youtu.be/jrH-JrJIDZU?t=28) in the Somerset(40p) map:
![BCUS98107_screenshot_2022_05_11_15_06_20](https://user-images.githubusercontent.com/66685584/167959223-469ba4fb-5829-44e9-8363-1024ee1978ba.png)

**Comment by homembarata** [comment] 2022-05-19 22:06
Wish I had seen this thread before...

It's not just grass, but small stuff like small rocks are also missing. Here's a later level in Resistance:
![rpcs3 exe Screenshot 2021 07 10 - 02 08 59 27](https://user-images.githubusercontent.com/13881636/169410702-b4866dec-70d2-4b60-8ad7-3d479709c659.png)

In the original hardware there are a bunch of small debris on the floor (not exactly the same screen but the same area):
![Resistance_ Fall Of Man _ PS3 _ Full Game Playthrough Walkthrough _ No Commentary 3-57-4 screenshot](https://user-images.githubusercontent.com/13881636/169410743-039f8794-7d9d-4609-9107-1c5eeee43053.png)

My guess is that this is an instanced mesh system, which is common for this kind of small objects and foliage. And the emulator is only rendering one instance at a time. Just throwing some ideas here.

**Comment by JimScript** [comment] 2022-05-19 22:22
It probably is that since I made a Renderdoc of this issue and didn't find any of the missing meshes anywhere in it. But it also seems to be different than the fade in/out as that works correctly with the one mesh that does render. Also certain multiplayer maps can run more than one at a time for some reason.

**Comment by isJuhn** [comment] 2022-05-19 23:36
I believe ratchet games culls lots of stuff in case of low fps before the rendering stage at all. I've checked a lot of ToD renderdocs and if it runs too slow a lot of stuff is not even in the renderdoc. But at the same time the foliage is never there no matter the fps so it might be some stage before the render stage that removes them, and not some rex culling.

**Comment by JimScript** [comment] 2022-05-25 22:26
I have thought a bit about the possibility of this being related to a performance cull, and now I think that this culling system might not be receiving a proper(or any) performance report. That would explain why there is generally only one rendered, because to the instanced mesh system the PS3 is getting absolutely slammed, so it renders the bare minimum amount of meshes it can(only one). That would also explain why Grimsby(40p) can render more meshes at once, because it is getting a lighter report. Now this is all guesswork, but it is the only thing that I can think of that would cause this.

**Comment by Darkhost1999** [comment] 2022-10-17 15:48
I have to host the video somewhere else because GitHub will say the video is corrupt or too big.
Oblivion (looks better upscaled and if I load all of the environment first.) Trees lose leaves as you approach them.
https://youtu.be/rBs_uqE2V1k
[RPCS3.log](https://github.com/RPCS3/rpcs3/files/9801890/RPCS3.log)

OpenGL Comparison
https://youtu.be/8nowDtWDMJY
[RPCS3.log](https://github.com/RPCS3/rpcs3/files/9802206/RPCS3.log)

I know this is a different game. Spooky. But the issues look the same.
I mean let's compare Oblivion only loses leaves not entire plants.
All 3 games lose foliage at similar distances to each other.
The other games plants are on the ground. Oblivion's leaves are off the ground.
If you want a separate issue ticket just lmk.

I can test on my Intel uhd 620 igpu laptop later for a comparison there? Would that be helpful or because igpus are not officially supported would it be meaningless?

**Comment by kd-11** [comment] 2022-10-17 18:18
This one never got triaged. I've added it to backlog.

**Comment by JimScript** [comment] 2022-10-17 20:14
> I have to host the video somewhere else because GitHub will say the video is corrupt or too big. Oblivion (looks better upscaled and if I load all of the environment first.) Trees lose leaves as you approach them. https://youtu.be/rBs_uqE2V1k [RPCS3.log](https://github.com/RPCS3/rpcs3/files/9801890/RPCS3.log)
> 
> OpenGL Comparison https://youtu.be/8nowDtWDMJY [RPCS3.log](https://github.com/RPCS3/rpcs3/files/9802206/RPCS3.log)
> 
> I know this is a different game. Spooky. But the issues look the same. I mean let's compare Oblivion only loses leaves not entire plants. All 3 games lose foliage at similar distances to each other. The other games plants are on the ground. Oblivion's leaves are off the ground. If you want a separate issue ticket just lmk.
> 
> I can test on my Intel uhd 620 igpu laptop later for a comparison there? Would that be helpful or because igpus are not officially supported would it be meaningless?

I'll admit, I don't see the similarity. In TOD & R:FOM they both can only show one or few pieces of foliage at a time with them popping around as you get closer or farther, this seems more gradual(except for the trees suddenly popping up in the background in the Vulkan example). I wouldn't even say it was the outlined plants part of this issue, as that remains consistent at any distance with any renderer. But maybe the underlining renderer could be used differently?

**Comment by Darkhost1999** [comment] 2022-10-17 20:33
> I'll admit, I don't see the similarity
You never see similarity to ANYTHING I say so IDK
OGL did same thing as vulkan tree pop in I just needed to load the water so there actually is no difference between renderers

**Comment by Darkhost1999** [comment] 2022-10-17 20:36
I definitely see as you described this
RPCS3: ![FoliageDemoRPCS3](https://user-images.githubusercontent.com/66685584/152706975-7b2fc785-2b09-4f08-b59a-d7f03f2c4fc3.gif)

**Comment by JimScript** [comment] 2022-10-17 20:51
> > I'll admit, I don't see the similarity
> 
> You never see similarity to ANYTHING I say so IDK OGL did same thing as vulkan tree pop in I just needed to load the water so there actually is no difference between renderers

I'm sorry about that. But issues with Oblivion were fixed with the PC uptime problem I posted, so maybe it is similar and would be fixed with this.

**Comment by JimScript** [comment] 2023-03-08 17:26
I think the reason why some of the ground plants look hollowed out and spindly is that that the alpha is limited to around 127 and anything past that is all zeroed out for that shader, making the bulk of it not render. This is the alpha of the QFB plant edited to demonstrate:
![QFBPlantBrokenAlpha](https://user-images.githubusercontent.com/66685584/223785447-96864cc8-fe14-4b90-ab2b-009a82d68876.png)

**Comment by JimScript** [comment] 2023-09-25 05:42
I've found something interesting about the hollowed out shader:
![BCUS98127_screenshot_2023_09_24_22_10_18](https://github.com/RPCS3/rpcs3/assets/66685584/235a0754-066a-4a9f-a707-3a8c6f630040)
It doesn't block shadows, even though it does on a real PS3. It makes sense since this is a transparent material, but what if it can block shadows on PS3 because it's filled with an opaque material, like it fades from transparent into opaqueness. And what if it's hollowed doing around a thousand draw calls because it's caught in a loop trying to get the opaque version but it's just getting the transparent version over and over again until the emulator gives up? I guess I'm making a lot of assumptions here.

**Comment by JimScript** [comment] 2023-10-25 21:04
Turns out it _does_ draw the opaque part first in another color pass, but it only does so on a _very_ slim threshold. That must have been the few pixels I saw being drawn first before, I could only really see it now when the LOD bias offset is set to 10 since the threshold is _so_ tight.
Opaque Shader Drawn:
![ToDPlantOpaque](https://github.com/RPCS3/rpcs3/assets/66685584/533ba2ad-4725-4b94-8548-b26b65fd3efb)

Translucent Shader and Shadow Drawn:
![ToDPlantTranslucent](https://github.com/RPCS3/rpcs3/assets/66685584/2e4e05ec-acf6-40ec-92e7-619e17af43bd)

Still don't know why both the opaque and translucent parts draw hundreds of times each frame though.

**Comment by JimScript** [comment] 2024-04-18 16:02
You know, with Resistance: Fall of Man showing multiple clusters rather than a single plant, could that in fact be a different issue? I mean this issue turned out to be different from the one that affected Resistance 2 and ACIT on NVIDIA, who's to say this isn't a different issue either? Still, this is only speculation, I won't make another issue until we know for sure.

**Comment by rogeriodomingos** [comment] 2024-04-18 17:12
You are right. Here is a screenshot with version 0.0.30-15956:
![Screenshot 2024-04-18 135822](https://github.com/RPCS3/rpcs3/assets/10940771/82c35c28-c945-4b1c-b579-7c2ec5a89352)

And version 0.0.30-16096:
![image](https://github.com/RPCS3/rpcs3/assets/10940771/9741fce1-1f08-4746-9a98-a4e41a3fadfb)
Same behavior as the latest version.

https://github.com/RPCS3/rpcs3/pull/15471 doesn't seem to have made any difference in this case. I'll try to narrow down the commit that made the improvement.

**Comment by rogeriodomingos** [comment] 2024-04-18 17:36
Found it. Version 0.0.30-15994 is what introduced the improvement, so that would be the following commits:
https://github.com/RPCS3/rpcs3/commit/0971636c07f42e36ccc6e7725611a26d7bd9a3f0
https://github.com/RPCS3/rpcs3/commit/9a9b5860df86f3ecceece5e81492e594e56443f9
https://github.com/RPCS3/rpcs3/commit/ca7de4bcb13e5a72d4bab6acb1d5caa9fea26fe0
https://github.com/RPCS3/rpcs3/commit/abe5013f1dfd0399cba2f863765a0833a044d0e1
https://github.com/RPCS3/rpcs3/commit/8eae8cb86c740317abe3b9e88e73d661d210d67b

Hopefully this information can help with further improvements.

**Comment by kd-11** [comment] 2024-04-18 20:42
This one is weird. I'll have to investigate assuming it's multiple issues. Hopefully it's not related to depth precision since that can only be correctly resolved with software rendering.

**Comment by kd-11** [comment] 2024-04-18 22:40
Ok, nothing too special here. It's what I expected. PS3 doesn't have dedicated instancing hardware, but it can do instancing through like a million different methods. We just didn't have a pattern match for the registers this game is using to implement it.
Fix incoming.

**Comment by kd-11** [comment] 2024-04-19 01:41
https://github.com/RPCS3/rpcs3/pull/15483 implements the feature, though in a very suboptimal way right now. A lot more work is needed to get this ready for merge.

**Closed** 2024-05-12 18:26 UTC
Labels: Bug, RSX
