### ISSUE TITLE
[Regression] XInput & DS4 Bug buttons ingame

### ISSUE THREAD

**Issue by MineSAT** [RPCS3/rpcs3#9160] opened 2020-10-28 19:36 UTC
Quick summary

When playing with either the PS4 or XBOX ONE controller, there is a problem in certain games that when pressing it, other actions are carried out that they should not. I have uploaded 2 videos to show what happens with 2 different versions of the emulator where this error happens, but this did not happen before.

Details

When playing with either the PS4 or XBOX ONE controller, there is a problem in certain games that when pressing it, other actions are carried out that they should not.

Please provide _exact_ build (or commit) information that introduced the regression you're reporting.:

v0.0.12-11088 and v0.0.12-11092

Logs.:

[RPCS3.log.gz](https://github.com/RPCS3/rpcs3/files/5454362/RPCS3.log.gz)

Attach screenshots of your problem.
11088 -> https://www.youtube.com/watch?v=H7RyCCztMw8&ab_channel=RatchetCinemaESP

11092 -> https://www.youtube.com/watch?v=-N1c0LChr54&ab_channel=RatchetCinemaESP

#### 6. Please provide your system configuration:
PC 1
* OS: W10 PRO x64
* CPU: AMD RYZEN 7 4700H
* RAM: 16GB DDR4 3200Mhz
* GPU: AMD RX 5500M 4GB GDDR6
* Driver version: RADEON 20.10.1 (Latest driver)

PC 2
* OS: W10 PRO x64
* CPU: AMD RYZEN THREADRIPPER 2990WX 32core
* RAM: 32GB DDR4 3200Mhz
* GPU: AMD RX 5700 XT 8GB GDDR6 (OC)
* Driver version: RADEON 20.10.1 (Latest driver)

**Comment by AniLeo** [comment] 2020-10-29 17:39
False/incorrect report

a) Two different versions of the emulator introduced the same issue? Obviously not possible
b) Impossible that v0.0.12-11088 introduced such an issue since it only changes CI.

Missing the actual version that introduced this issue.

**Comment by AniLeo** [comment] 2020-10-29 17:41
The last PR to touch input was #9135, you should check that one

**Comment by doesthisusername** [comment] 2020-10-29 18:53
FWIW, I've experienced something like this as well, for at least two months, probably three+. The PS2 R&C ports seem to be affected. On Linux (haven't tried Windows), using the DualShock 4 pad handler makes triangle and L3 also do the action for select/R3 (unsure which for which, as the buttons do the same ingame). Both select and R3 now do nothing when pressed. Evdev does not exhibit this issue, so that's what I've been using. I've also tried multiple DS4 controllers, all of which had this behaviour for me. Hope it helps a little.

**Comment by jeremybris** [comment] 2020-10-30 18:15
same with Fallout 3 and Fallout New Vegas. **Xinput "x" ----> causes ----> Xinput "select"**

it's #9135 for me. 

I experienced this in earlier versions too once, but then never again; it's probably some left over, code compilation from the current versions that causes that.

**Comment by MineSAT** [comment] 2020-10-30 21:05
The bug continue in v11119 on Ratchet Deadlocked and PS All Stars BR with XBOX ONE controller. 
In the case of PS All Stars BR, pressing X (Button A on xbox) selects the last option in the game menu and marks it as if the X had been pressed

**Comment by Braindead82** [comment] 2020-10-31 12:38
I would also like to confirm that something weird happened with xinput after build 0.0.12 -11091. I was trying to play ratchet and clank trilogy but when i try to load or start new game it goes back. The CROSS button now does the same as SELECT button. I tested that 11092 has this problem. 11091 works fine.

**Comment by MineSAT** [comment] 2020-11-01 11:33
In the current version of the emulator, in R&C Tools of Destruction the XInput works perfectly. 

It must be something that happens in certain games ... I Can Confirm 2: R&C Trilogy and PS All Stars BR

I also confirm that it is true that in compilation 11091 everything worked perfectly.

**Comment by narfel** [comment] 2020-11-01 17:32
And here I was thinking i'm going crazy. Can confirm R&C1 have the X and Start button bound together somehow. The launcher works fine. In R&C3 for some reason the menu works normal, you can select 'New Game' and go ingame. But as soon as you are ingame the Start/X button problem happens. You can switch to keyboard and get all 3 games to run. If you switch back to Xinput in the actual game you can in R&C1 see that if you hit X the map selection screen comes up and when you exit it the character finishes the jump animation. To add to the confusion, R&C3 the game can be taken past the 'New Game', create a save and start the game, but as soon as you are in control X just loads the menu.

Version: 2 0.0.12-11148-46d3066c Alpha
Rig: Ryzen 5/GTX 1660 Super/32 GB Ram

**Comment by duganman1997** [comment] 2020-11-06 07:04
Same issue here! Latest update, only on ratchet and clank games! Using Dualshock 4 my Triangle button also clicks R3, and on XBONE Controller my X button hits triangle!

**Comment by Aphelion42069** [comment] 2020-11-09 19:25
Can confirm that this issue was caused by #9135. Easily reproduceable using x-input in Fallout 3, Fallout New Vegas, or Ratchet Deadlocked.

The emulated controller's select button gets mapped to the A button on my Xbox 360 controller, regardless of what other button is assigned to A.

Logs are likely irrelevant for this issue, but here they are:
[RPCS3 - 9135.log](https://github.com/RPCS3/rpcs3/files/5512795/RPCS3.-.9135.log) - 0.0.12-11092-0a121e9d
[RPCS3 - 9146.log](https://github.com/RPCS3/rpcs3/files/5512797/RPCS3.-.9146.log) - 0.0.12-11091-15e8cba3

**Comment by RipleyTom** [comment] 2020-11-09 20:15
That PR literally only changed ds4 pad handler and only to add log messages, it's very unlikely to be the culprit.

**Comment by Aphelion42069** [comment] 2020-11-09 22:11
It seems a bit peculiar, but I'm not sure what else it could be. Input works just fine in 0.0.12-11091-15e8cba3 (#9146) and is broken in the next build, which is 0.0.12-11092-0a121e9d (#9135).

**Comment by jeremybris** [comment] 2020-11-09 23:21
I get this on earlier versions! But _only on the first time booting a game_, in earlier versions! _It's elusive_! This makes it very time consuming to find the regression, and I won't have time to find the regression. Someone else will have to find it...

**Comment by jeremybris** [comment] 2020-11-10 21:33
The regression if from #8663 , @RipleyTom, #9135 just made it more noticeable.

**Comment by RipleyTom** [comment] 2020-11-10 21:51
I've noticed in MineSat log that for some reason he's using psn simulated and status connected.
I'd try setting that to disconnected/disconnected first of all(if my PR is the culprit, which seems doubtful as it doesn't touch pads at all).

**Comment by jeremybris** [comment] 2020-11-10 22:27
I use the default settings of the emulator. 

[RPCS3 v0.0.11-10790 Working.log](https://github.com/RPCS3/rpcs3/files/5520552/RPCS3.v0.0.11-10790.Working.log)
vs.
[RPCS3 v0.0.11-10791 Not Working.log](https://github.com/RPCS3/rpcs3/files/5520553/RPCS3.v0.0.11-10791.Not.Working.log)

I don't think it is necessarily an input bug, because it only effects some games, and an input bug should effect all games.

**Comment by RipleyTom** [comment] 2020-11-10 23:13
I was able to reproduce with DS4 pad handler on linux, we'll fix this :).

**Comment by RipleyTom** [comment] 2020-11-11 03:22
https://github.com/RPCS3/rpcs3/pull/9242 should fix it.

**Closed** 2020-11-11 04:16 UTC
Labels: Input, Need Information
