### ISSUE TITLE
Ar Nosurge is not reacting on input during installation request

### ISSUE THREAD

**Issue by vsub** [RPCS3/rpcs3#4117] opened 2018-01-26 19:46 UTC
I am using
RPCS3 0.0.4-6350-4f0179471
And when I try to run the game,it displays a message that the game will be installed and I have to press X to start the progress.
Pressing any button on the gamepad or switching to keyboard(of course changing the controller type from the settings to keyboard and making sure I'm pressing the correct key)does nothing.

And I think this is the important part of the log

E {PPU[0x1000018] Thread (installGameDataThread) [0x000a748c]} cellSysutil: Ar nosurge is being installed to the hard disk drive. The HDD access indicator will flash during installation. Please do not turn off the power.

E {dialog input thread} RSX: Pad handler expected but none initialized!

E {dialog input thread} RSX: Dialog input loop exited with error code=-3

I was able to install the game by using some randomly choosen older build(v0.0.3-3-d3f13ab)that is still using dialogs rather than messages in the game window
[log.zip](https://github.com/RPCS3/rpcs3/files/1668997/log.zip)

**Comment by Megamouse** [comment] 2018-01-27 01:06
duplicate of #4011

**Closed** 2018-01-27 03:41 UTC
