### ISSUE TITLE
'Vulkan surface color format'

### ISSUE THREAD

**Issue by SakataGintokiYT** [RPCS3/rpcs3#1710] opened 2016-05-24 15:57 UTC
@raven02 
{rsx::thread} RSX: Surface color buffer: Unsupported surface color format (0xc)

Log : https://gist.github.com/SakataGintokiYT/65a7c42d19e3fd79a3e205feb21bd695

**Comment by raven02** [comment] 2016-05-24 16:23
will look into it .

**Comment by raven02** [comment] 2016-05-25 16:22
Duplicate of #1681

**Closed** 2016-05-26 06:09 UTC
