### ISSUE TITLE
Regression after #5453: Ratchet & Clank: A Crack in Time [BCES00511]

### ISSUE THREAD

**Issue by leskal** [RPCS3/rpcs3#5552] opened 2019-01-14 02:21 UTC
After #5453 game boots and stuck with black screen at constant fps
rpcs3-v0.0.5-7715-bc27f5f7_win64:
![screenshot_2](https://user-images.githubusercontent.com/11486824/51094221-b680f400-17b3-11e9-8d2f-b05dfd9411ec.png)
rpcs3-v0.0.5-7727-c5026f71_win64:
![screenshot_1](https://user-images.githubusercontent.com/11486824/51094226-c7ca0080-17b3-11e9-91af-89db26c74c50.png)

Verification of disc image:
![screenshot_1](https://user-images.githubusercontent.com/11486824/51094234-d44e5900-17b3-11e9-9dc3-2ac43e7f94a9.png)
Log:
[RPCS3.log.gz](https://github.com/RPCS3/rpcs3/files/2753877/RPCS3.log.gz)

**Comment by isJuhn** [comment] 2019-01-14 02:47
Can't reproduce on my 4690k, try disabling TSX and see if that makes any difference.

**Comment by leskal** [comment] 2019-01-14 02:52
> Can't reproduce on my 4690k, try disabling TSX and see if that makes any difference.

Doesn't change anything...
[RPCS3.log.gz](https://github.com/RPCS3/rpcs3/files/2753913/RPCS3.log.gz)

**Comment by stride21** [comment] 2019-01-14 03:41
Got ingame without any issues with a 6700k and a GTX 1070
![ratchet](https://user-images.githubusercontent.com/37915864/51095588-7d2c9200-177b-11e9-9a74-58534e41452a.JPG)
[RPCS3.log.gz](https://github.com/RPCS3/rpcs3/files/2753979/RPCS3.log.gz)

**Comment by leskal** [comment] 2019-01-14 03:45
But you test the BCUS98124. I face prob with BCES00511 as the title says

**Comment by stride21** [comment] 2019-01-14 05:06
Someone else posted they were having a black screen issue with Ratchet & Clank Future: A Crack in Time BCUS98124 four days ago on the [forum](https://forums.rpcs3.net/thread-189234.html) as well.

**Comment by Asinin3** [comment] 2019-01-14 08:21
Disc region generally shouldn't matter, it could be a race condition. But i see that you have write color buffers off, and strict rendering mode off. If you have strict off then this games graphics will go black when certain things happen e.g breaking boxes which is a normal issue. I'm pretty sure it needs write color buffers too. I remember having race condition issues and it wouldn't always go ingame so i used to use PPU Interpreter too. Just try strict + wcb and see if it helps, because it's working fine on psn version here.
![image](https://user-images.githubusercontent.com/15137035/51102065-53a05480-17d5-11e9-88c6-b198e8566403.png)

**Comment by leskal** [comment] 2019-01-14 14:50
@Asinin3 I did what you suggest but same result
[RPCS3.log.gz](https://github.com/RPCS3/rpcs3/files/2755618/RPCS3.log.gz)

**Comment by Hirato** [comment] 2019-01-14 16:17
PPU LLVM has never worked for me - I've only been able to get in game with the PPU interpreters.
The recent commits doesn't change that.

From what I can see, due to recent work:
1. Starts much more reliably
2. WRC causes it to freeze when going ingame
3. SRM no longer makes the screen super blurry, but it does make it super pixelated, and produces a weird interlacing effect when you'd get the black screen without SRM.
Additionally you now get some super bloom on the top right half (dunno what else you'd call it), which occasionally turns into coloured confetti for brief periods when panning the camera.

like so:
![screenshot_20190115_000940](https://user-images.githubusercontent.com/881518/51124724-f13d6780-1859-11e9-99c5-7d2d7b34cbaa.png)
![screenshot_20190115_001152](https://user-images.githubusercontent.com/881518/51124837-38c3f380-185a-11e9-93a2-c1f6dea75e67.png)

Beyond that, game works about as well (or poorly) as it has since last September.

**Comment by stride21** [comment] 2019-01-14 17:11
@leskal Did you try testing the game on a clean install of 0.0.5-7727?

**Comment by leskal** [comment] 2019-01-14 21:47
I think i found the proble.

First of all i have installed on rpcs3 both digital[NPEA00453] and the disc[BCES00511] versions. I have notice after clean installs of rpcs that when i launch first the digital version, then the disc version has the problem i mention above. Again in another clean install of rpcs3, if i launch first the disc version, then the digital version doesn't go ingame. My guess is that something conflicts the two version.

Something not related to the problem, with `Right click-> Remove-> Remove PPU Cache`, it tries to remove in the data folder and in the new cache folder

**Comment by kd-11** [comment] 2019-07-04 11:22
Is this still an issue? I'm certain the remove cache option has been fixed by now.

**Comment by Asinin3** [comment] 2019-10-18 12:50
I think this should be closed tbh the game has improved a lot since, there's a new regression with SPU LLVM but i already have that issue open.

**Closed** 2019-10-18 12:57 UTC
