### ISSUE TITLE
When I click on "Config" it crashes with this error on a new install.

### ISSUE THREAD

**Issue by D-elias** [RPCS3/rpcs3#15098] opened 2024-01-26 04:36 UTC
### Quick summary

On OSX 14.3, M2 Macbook Pro, the only build that works is Rcps3 0.0.28-15308. I click on config and pads on this version, then opened Rcps3 0.0.30-15914 and booted the game, changed the resolution in the older version and it works. After removing all of the Rcps3 system files with a clean install, the current builds only boot the game but clicking on config or pads crashes it.  Then when I changed the settings in 0.0.28-15308 and the current build stopped booting games. So I booted in 0.0.30-15914 and it boots in 0.0.28-15308 now.

### Details

Others have this same issue as discussed in the comments in this video.

https://youtu.be/926SGyTUHfc?si=1TVNHa3vFSmpgo0Q

I get a crash all the time and when I try to click Pads or Config it just crashes again. I can launch a game but I can't configure a controller. I'm on version 15916 on MacOS 14.2. Any ideas?

I'd recommend trying a different build, sometimes there can be bugs in the nightly

Same issue for me. I just tried the build he's using in this video and I can now access the pad and config settings but now games won't

I've got around it for now by installing the latest build to launch games, and saving the old build from this video in my documents folder purely to launch and configure settings. They both point to the same Library folders so the controller and config settings will carry across!

Segfault writing location 00007ff80eed0f34 at 000000000de23f6b.
Thread: Main Thread.
Title: "™ (emulation is stopped)
Build: "0.0.30-15949-4c36b803 Alpha | HEAD"
Date: "2024-01-1418:51:29"
HOW TO REPORT ERRORS:
https://github.com/RPCS3/rpcs3/wiki/How-to-ask-for-Support
Please, don't send incorrect reports. Thanks for understanding.

MacBook Pro
16-inch, 2023
Apple M2 Pro
32 GB
14.2.1 (23C71

https://imgur.com/a/O2EEQPY

### Attach a log file

https://www.mediafire.com/file/l1s1oy6ozyjhpx1/RPCS3.log/file

### System configuration

MacBook Pro
16-inch, 2023
Apple M2 Pro
32 GB
14.3

**Comment by RipleyTom** [comment] 2024-01-26 04:56
Duplicate of https://github.com/RPCS3/rpcs3/issues/14997

**Closed by RipleyTom** 2024-01-26 04:56 UTC
