### ISSUE TITLE
Big FPS slowdown on some games after adding TSX

### ISSUE THREAD

**Issue by Psycho-A** [RPCS3/rpcs3#4524] opened 2018-05-06 02:05 UTC
After adding TSX instructions support last month, FPS on some games was greatly regressed on non-TSX processors.

For example (builds 6630 vs current), 
Red Dead Redemption: 7-12 fps -> 1-2,5 fps;
WWE Smackdown vs. RAW 2009 -> 17-23 fps -> 0.6-2 fps.

My system config:
Core i5-760; GTX 750 Ti; 8 Gb RAM, Windows 7 Ultimate.

**Comment by TGEnigma** [comment] 2018-05-06 03:30
Your processor does not support TSX so TSX isn't relevant to the issue.

**Comment by spyropt** [comment] 2018-05-06 06:06
@tgenigma that's not he is saying, tsx optimizations in my case did not had much impact because my cpu is a x5675 6cores/12threads, but on a cpu with less cores there is a noticeable slowdown without avx (first Gen i5), even on my cpu there was a hit of about 10%

**Comment by 13xforever** [comment] 2018-05-06 07:34
What’s the point of opening a performamce regression on a cpu that is far below minimum system requirements?

**Comment by spyropt** [comment] 2018-05-06 07:41
Because there were games that were playable and now they aren't... And I you find the culprit probably can be beneficial for other cpus...
On my xeon  cpu x5675 in the first tsx commit there was a hit in fps almost 30% after testing and reporting in the end most games apart from p5 gained fps. Now with the latest changes to master its even faster...
So if you have regressions report them...

**Comment by AniLeo** [comment] 2018-05-06 11:36
FYI TSX support was added like a year ago

**Comment by qm3ster** [comment] 2018-05-07 13:29
@AniLeo not the part of TSX that slaughtered me :man_shrugging: That was added about a month ago.

**Comment by digitaldude555** [comment] 2019-06-17 17:52
Its been one year of no update.

**Comment by AniLeo** [comment] 2019-09-18 14:42
Closing since not only the CPU is well below recommended requirements, but lots of improvements have already been done to non-TSX paths.

**Closed by AniLeo** 2019-09-18 14:42 UTC
