### ISSUE TITLE
[BCUS98119] inFamous freeze each time at the same spot and "damaged" screen never leave

### ISSUE THREAD

**Issue by toto621-linux** [RPCS3/rpcs3#10759] opened 2021-08-24 20:57 UTC
Title: inFamous
Serial: BCUS98119
Version: 1.00
- The game freeze each time when entering tunnel during mission where you have to close 3 valves full of "goo" making you hallucinating. Can't play this game further, not a single freeze/crash before that point. 
RPCS3 log console view show this error :
`VM: Access violation writing location 0x10 (unmapped memory) [type=u32]`

- Second problem, when you're hit you screen become grey with blood splatters. you have 50% chance this effect never wear off, you have to save and reload the game to clean it. A PPU patch to disable this sh*t would be awesome.

## System summary
RPCS3 v0.0.17-12665-4e139ee0 Alpha
CPU: Intel(R) Core(TM) i9-9900KF CPU @ 3.60GHz | 16 Threads | 31.94 GiB RAM | TSC: 3.600GHz | AVX+ | FMA3
GPU: NVIDIA GeForce RTX 2070
RAM: 32Gb of DDR4
SSD: Samsung 860 Pro 1TB
OS: Windows 10, Build: 19042

Screenshot of the effect not leaving (I waited 10 min and try to heal with electricity, nothing work) :
![inFamous-01](https://user-images.githubusercontent.com/88256778/130688622-dfef3246-cb40-44e6-8cd4-adfb52758fdc.jpg)

Screenshot of the spot where it always freeze (it stay like this until you manually close RPCS3) :
![inFamous-02](https://user-images.githubusercontent.com/88256778/130688374-c4ba90e0-922a-404a-ad30-bdf4503950ac.jpg)

[RPCS3.log.gz](https://github.com/RPCS3/rpcs3/files/7042077/RPCS3.log.gz)

**Comment by Darkhost1999** [comment] 2021-09-14 11:52
I can not reproduce. The black sewage hallucinogen mission was fully capable of being completed.
The health indication fades away by recovering your health either through avoiding getting damaged or by absorbing electricity.
The only issues I've had with infamous is once you get to the 2nd region your enemies are now at complete random times fully capable of becoming invisible and because they do not exist, invincible.
They can attack you. You can not attack them. It's quite frustrating.
I got an AMD Ryzen 5 3600, GTX 1660S, 16 gigs of ram, Windows 11 beta channel.

**Comment by Megamouse** [comment] 2021-10-31 01:00
![image](https://user-images.githubusercontent.com/23019877/139562553-2c4ee8c7-c8e6-4f15-8190-b6b19376f5bc.png)

**Comment by Darkhost1999** [comment] 2022-01-24 18:52
@toto621-linux did you manage to find out the answer to your problem?
Can this issue be closed?

**Comment by MSuih** [comment] 2022-01-24 18:55
He hasn't given any update for the comments so I think it's safe to close this now.

**Closed by MSuih** 2022-01-24 18:55 UTC
