### ISSUE TITLE
(Linux only) MGS2 crashing after corridor battle - Metal Gear Solid HD Collection [BLUS30847]

### ISSUE THREAD

**Issue by ghost** [RPCS3/rpcs3#9465] opened 2020-12-18 15:31 UTC
Hello everyone, I'm facing a crash in MGS2 from the HD Collection that is happening with various emulator settings. After the corridor battle when Snake reaches the Marines speech the game freezes and eventually crashes right after the dialogue with Otacon is finished and the game is supposed to hand back control to the player.

![image](https://user-images.githubusercontent.com/865413/102630604-84106c00-412b-11eb-97db-af4eb51a3b1b.png)

The log reads this when it crashes:

```F {PPU[0x1000000] Thread (main_thread) [HLE:0x018f5184, LR:0x009af104]} SYS: 
Segfault reading location 0000000000000000 at 00007f5aaed5466b.
Emu Thread Name: 'PPU[0x1000000] main_thread '.
Thread id = 140014172231232.
```

I'm running an up-to-date Arch Linux on the following hardware:
```processor	: 0
vendor_id	: GenuineIntel
cpu family	: 6
model		: 158
model name	: Intel(R) Core(TM) i7-9750H CPU @ 2.60GHz
stepping	: 10
microcode	: 0xcc
cpu MHz		: 899.994
cache size	: 12288 KB
physical id	: 0
siblings	: 12
core id		: 0
cpu cores	: 6
apicid		: 0
initial apicid	: 0
fpu		: yes
fpu_exception	: yes
cpuid level	: 22
wp		: yes
flags		: fpu vme de pse tsc msr pae mce cx8 apic sep mtrr pge mca cmov pat pse36 clflush dts acpi mmx fxsr sse sse2 ss ht tm pbe syscall nx pdpe1gb rdtscp lm constant_tsc art arch_perfmon pebs bts rep_good nopl xtopology nonstop_tsc cpuid aperfmperf pni pclmulqdq dtes64 monitor ds_cpl vmx est tm2 ssse3 sdbg fma cx16 xtpr pdcm pcid sse4_1 sse4_2 x2apic movbe popcnt tsc_deadline_timer aes xsave avx f16c rdrand lahf_lm abm 3dnowprefetch cpuid_fault epb invpcid_single pti ssbd ibrs ibpb stibp tpr_shadow vnmi flexpriority ept vpid ept_ad fsgsbase tsc_adjust bmi1 avx2 smep bmi2 erms invpcid mpx rdseed adx smap clflushopt intel_pt xsaveopt xsavec xgetbv1 xsaves dtherm ida arat pln pts hwp hwp_notify hwp_act_window hwp_epp md_clear flush_l1d
vmx flags	: vnmi preemption_timer invvpid ept_x_only ept_ad ept_1gb flexpriority tsc_offset vtpr mtf vapic ept vpid unrestricted_guest ple pml ept_mode_based_exec
bugs		: cpu_meltdown spectre_v1 spectre_v2 spec_store_bypass l1tf mds swapgs itlb_multihit srbds
bogomips	: 5202.65
clflush size	: 64
cache_alignment	: 64
address sizes	: 39 bits physical, 48 bits virtual
power management:
```

```
Presentable Surfaces:
=====================
GPU id : 0 (GeForce RTX 2060):
	Surface types: count = 2
		VK_KHR_xcb_surface
		VK_KHR_xlib_surface
	Formats: count = 2
		SurfaceFormat[0]:
			format = FORMAT_B8G8R8A8_UNORM
			colorSpace = COLOR_SPACE_SRGB_NONLINEAR_KHR
		SurfaceFormat[1]:
			format = FORMAT_B8G8R8A8_SRGB
			colorSpace = COLOR_SPACE_SRGB_NONLINEAR_KHR
	Present Modes: count = 3
		PRESENT_MODE_FIFO_KHR
		PRESENT_MODE_FIFO_RELAXED_KHR
		PRESENT_MODE_IMMEDIATE_KHR
	VkSurfaceCapabilitiesKHR:
	-------------------------
		minImageCount       = 2
		maxImageCount       = 8
		currentExtent:
			width  = 256
			height = 256
		minImageExtent:
			width  = 256
			height = 256
		maxImageExtent:
			width  = 256
			height = 256
		maxImageArrayLayers = 1
		supportedTransforms: count = 1
			SURFACE_TRANSFORM_IDENTITY_BIT_KHR
		currentTransform    = SURFACE_TRANSFORM_IDENTITY_BIT_KHR
		supportedCompositeAlpha: count = 1
			COMPOSITE_ALPHA_OPAQUE_BIT_KHR
		supportedUsageFlags: count = 6
			IMAGE_USAGE_TRANSFER_SRC_BIT
			IMAGE_USAGE_TRANSFER_DST_BIT
			IMAGE_USAGE_SAMPLED_BIT
			IMAGE_USAGE_STORAGE_BIT
			IMAGE_USAGE_COLOR_ATTACHMENT_BIT
			IMAGE_USAGE_INPUT_ATTACHMENT_BIT
	VkSurfaceCapabilities2EXT:
	--------------------------
		supportedSurfaceCounters: count = 0
			None
	VkSurfaceProtectedCapabilitiesKHR:
	----------------------------------
		supportsProtected = false
```

RPCS3 Version: 0.0.13-11409-6b3f722f Alpha

I cannot confirm this happens with OpenGL given that I can't get to the title screen with that backend.

~I cannot confirm this happens in Windows various rendering glitches cause the game to be unplayable there.~ After disabling the antialias for the Vulkan backend I was able to play the game in Windows. This bug DOES NOT happen in Windows.

**Comment by Soapsuds** [comment] 2021-05-20 03:20
For what it's worth I recently played this game all the way through on Linux using Vulkan and did not experience any crashes.

**Comment by Megamouse** [comment] 2022-02-22 06:38
Closing due to missing log.
You may reopen this issue if you can still reproduce this with the latest version.

**Closed by Megamouse** 2022-02-22 06:38 UTC
