### ISSUE TITLE
RSX: Invalid RSX method [NPUB30932] [Vulkan]

### ISSUE THREAD

**Issue by vasiliyaltunin** [RPCS3/rpcs3#3847] opened 2017-12-04 20:55 UTC
RPCS3 v0.0.4-6207-970d2a06

 Alpha | HEAD
Intel(R) Core(TM) i5-7400 CPU @ 3.00GHz | 4 Threads | 7.97 GiB RAM | AVX+

Ni No Kuni: Wrath of the White Witch [NPUB30932]

Vulkan renderer
just in middle of battle 

```
S {rsx::thread} RSX: New program compiled successfully
E {rsx::thread} RSX: Invalid RSX method 0xbb80 (arg=0x18829)
(in file Emu\RSX\rsx_methods.cpp:45)
E {rsx::thread} HLE: Getting the real address failed. (addr=0x1f5f9db4)
E {rsx::thread} RSX: Invalid FIFO queue get/put registers found, get=0x1F5F9DB4, put=0x40A5BC
E {rsx::thread} HLE: Getting the real address failed. (addr=0x1f5f9db4)
E {rsx::thread} RSX: Invalid FIFO queue get/put registers found, get=0x1F5F9DB4, put=0x40A5BC
E {rsx::thread} HLE: Getting the real address failed. (addr=0x1f5f9db4)
E {rsx::thread} RSX: Invalid FIFO queue get/put registers found, get=0x1F5F9DB4, put=0x40A5BC
E {rsx::thread} HLE: Getting the real address failed. (addr=0x1f5f9db4)
E {rsx::thread} RSX: Invalid FIFO queue get/put registers found, get=0x1F5F9DB4, put=0x40A5BC
E {rsx::thread} RSX: Application has failed to recover, discarding FIFO queue
```

Opengl have around 10 fps. Vulkan more than 20 fps

OpenGL render crush with error when i just lying dead with "You were defeated..." screen

```
E {PPU[0x1000015] Thread (fios mediathread 6) [0x01e0dee4]} 'sys_fs_stat' failed with 0x80010006 : CELL_ENOENT, “/dev_hdd0/game/NPUB30932/USRDIR/data/sound/voice/en/70/7000370.sgh.zarc” [1]
E {PPU[0x1000015] Thread (fios mediathread 6) [0x01e0dee4]} 'sys_fs_stat' failed with 0x80010006 : CELL_ENOENT, “/dev_hdd0/game/NPUB30932/USRDIR/data/sound/voice/en/70/7000370.sgh.zarc” [2]
E {PPU[0x1000015] Thread (fios mediathread 6) [0x01e0e090]} 'sys_fs_open' failed with 0x80010006 : CELL_ENOENT, “/dev_hdd0/game/NPUB30932/USRDIR/data/sound/voice/en/70/7000370.sgh.zarc” [1]
E {PPU[0x1000015] Thread (fios mediathread 6) [0x01e0dee4]} 'sys_fs_stat' failed with 0x80010006 : CELL_ENOENT, “/dev_hdd0/game/NPUB30932/USRDIR/data/sound/bgm/bg1010.sgh.zarc” [1]
E {PPU[0x1000015] Thread (fios mediathread 6) [0x01e0dee4]} 'sys_fs_stat' failed with 0x80010006 : CELL_ENOENT, “/dev_hdd0/game/NPUB30932/USRDIR/data/sound/bgm/bg1010.sgh.zarc” [2]
E {PPU[0x1000015] Thread (fios mediathread 6) [0x01e0e090]} 'sys_fs_open' failed with 0x80010006 : CELL_ENOENT, “/dev_hdd0/game/NPUB30932/USRDIR/data/sound/bgm/bg1010.sgh.zarc” [1]
E {rsx::thread} RSX: Invalid framebuffer setup, w=0, h=0
E {rsx::thread} RSX: FIFO: RET found without corresponding CALL. Discarding queue

```

P.S. overlightning fixed with vulkan and opengl versions

![shot3](https://user-images.githubusercontent.com/417082/33575348-65c9de30-d990-11e7-948b-5c1fffc92ce7.png)
LOGS - https://yadi.sk/d/kdm_-Owb3Q6pkT 

051217- v0.0.4-6207-970d2a06-vulcan-log-1.7z
051217- v0.0.4-6207-970d2a06-opengl-log-1.7z

**Comment by kd-11** [comment] 2017-12-04 20:58
Duplicate of https://github.com/RPCS3/rpcs3/issues/2359

**Closed by kd-11** 2017-12-04 20:58 UTC
