### ISSUE TITLE
Persona 5 [NPEB02436]: Vulkan crash on low FPS

### ISSUE THREAD

**Issue by endervad** [RPCS3/rpcs3#6144] opened 2019-06-28 21:57 UTC
I've already raised a topic about this in #6091, but it seems like it's not related to that issue.

RPCS3 v0.0.6-8311-232a35b6 Alpha | HEAD | Firmware version: 4.84
Intel(R) Core(TM) i7-2860QM CPU @ 2.50GHz | 8 Threads | 15.98 GiB RAM | AVX
NVIDIA GeForce GTX 1050 Ti (430.86)

Errors:
```
·W 4:11:03.864784 {PPU[0x1000000] Thread (main_thread) [0x008f7594]} RSX: Cache miss at address 0xCA8EB800. This is gonna hurt...
·E 4:11:03.964916 {PPU[0x1000000] Thread (main_thread) [0x008f7594]} RSX: [vulkan] vk::wait_for_event has timed out!
·W 4:11:31.702850 {RSX [0x01962d4]} RSX: Cache miss at address 0xCA99D800. This is gonna hurt...
·E 4:11:31.903154 {RSX [0x01962d4]} RSX: [vulkan] vk::wait_for_event has timed out!
·F 4:11:32.191255 {RSX [0x0024a6c]} RSX: class std::runtime_error thrown: Assertion Failed! Vulkan API call failed with unrecoverable error: Device lost (Driver crashed with unspecified error or stopped responding and recovered) (VK_ERROR_DEVICE_LOST)
```

It often happens at some point if FPS is around 10 or lower. OpenGL doesn't have this issue, i.e. doesn't crash, even though it runs much slower.
Examples of those scenes:
1. Shujin Rooftop: Plant tomatoes. Seems like they have so many polygons that FPS falls from stable 30 to around 5. Crash triggers either some time after entering the scene or if moving to another location.
2. Shido's Palace - Treasure Room: I've just got a crash during a cutscene there. The scene had around 10 FPS or lower. The log has this crash.

Settings:
PPU/SPU: LLVM Recompiler
SPU threads: Auto
SPU block size: Safe
Additional settings: Enable thread scheduler, Enable SPU loop detection, SPU Cache
TSX is not supported
GPU:
Vulkan, 1280x720, 100%, AA - off, all additional settings are off

[RPCS3.log.gz](https://github.com/RPCS3/rpcs3/files/3340965/RPCS3.log.gz)

**Comment by kd-11** [comment] 2019-06-29 07:15
Duplicate of https://github.com/RPCS3/rpcs3/issues/6135

**Comment by endervad** [comment] 2019-06-29 13:23
Why? I have a different error and it's not caused by #6112. It's been there before #6112 too. I don't know for how long though. I've just finally figured how to trigger the crash.
And the emulator does not hang. After the crash I can close the game and the emulator just fine.

In any case I've tried your build in #6135 and it still crashes with the same
```
·F 0:07:33.370552 {RSX [0x0076ee0]} RSX: class std::runtime_error thrown: Assertion Failed! Vulkan API call failed with unrecoverable error: Device lost (Driver crashed with unspecified error or stopped responding and recovered) (VK_ERROR_DEVICE_LOST)
```
[RPCS3.log.gz](https://github.com/RPCS3/rpcs3/files/3341897/RPCS3.log.gz)

**Comment by Tenkuuu** [comment] 2019-07-09 15:16
I've had the same issue multiple times through multiple sessions now. Enabling or disabling TSX didn't change this (save for exactly once). I've encountered this bug constantly a few times like

1. The loading screen after I had Ann rank up to 7 on a specific day
2. A cutscene during the High School Festival when Goro Akechi lets the public know he is leaving
3. The reveal of the Madarame Palace when the camera pans to the top of the palace
4. Some random which I frankly can't remember the exact detail of

I've "by-passed" 
- The first by simply postponing this to another day
- The second by switching to OpenGL
- And the third by switching TSX to disabled, this was the one and only time it actually helped me by-pass the issue
- The random ones are usually fixed by a quick restart 

All the crashes I've experienced have the same fatal error

> ·F 0:18:38.073789 {RSX [0x0081af8]} RSX: class std::runtime_error thrown: Assertion Failed! Vulkan API call failed with unrecoverable error: Device lost (Driver crashed with unspecified error or stopped responding and recovered) (VK_ERROR_DEVICE_LOST)
(in file c:\projects\rpcs3\rpcs3\emu\rsx\vk\vkhelpers.h:1043)

My specs are:
Intel i5 6500
RX 580 8GB
8GB RAM
RPCS3 v0.0.6-8329-ad10eb39 Alpha | HEAD | Firmware version: 4.84
[RPCS3.log.gz](https://github.com/RPCS3/rpcs3/files/3373637/RPCS3.log.gz)

**Comment by endervad** [comment] 2019-07-09 15:26
I can confirm that I indeed had this crash during Ann confidant. However, I didn't try another day, I just switched to OpenGL and endured it. And I also experienced a few crashes at Madarame Palace's entrance if I stay there for too long.
By the way, since my CPU doesn't have TSX, we can safely assume that this issue has nothing to do with TSX.

**Comment by kd-11** [comment] 2020-02-08 10:33
Request to reopen if still an issue.

**Closed by kd-11** 2020-02-08 10:33 UTC
