### ISSUE TITLE
when launch rpcs3 one of cpu cores become idle

### ISSUE THREAD

**Issue by cloudslsw** [RPCS3/rpcs3#15066] opened 2024-01-20 04:45 UTC
### Quick summary

bitdefender doesnt detect any virus and running other software all my cpu cores are being used, but launch rpcs3 and playing one of my cpu cores is idle, usually CPU1 occasionally CPU2

image 1 is rpcs3,  image 2 is boot into windows

![屏幕截图 2024-01-20 091116](https://github.com/RPCS3/rpcs3/assets/11231847/bd9ca411-a91f-4f79-aef6-246739fadc70)
![屏幕截图 2024-01-20 090836](https://github.com/RPCS3/rpcs3/assets/11231847/9ca823be-1029-43f7-80f3-a27fec1a7e69)

### Attach a log file

[RPCS3.log.gz](https://github.com/RPCS3/rpcs3/files/13996722/RPCS3.log.gz)

**Comment by Megamouse** [comment] 2024-01-20 09:57
Duplicate of #14648

**Closed by Megamouse** 2024-01-20 09:57 UTC
