### ISSUE TITLE
rsx: Crash on d3d11.dll

### ISSUE THREAD

**Issue by Bel25m** [RPCS3/rpcs3#8176] opened 2020-05-09 01:42 UTC
hello I have a problem with the emulator lately, I have been playing person 5 as if nothing but today when alcutalizing the emulator I just got an error I tried to remove the update but it did not work, the error is that of this capture:
![imagen](https://user-images.githubusercontent.com/65053160/81460616-1b601a80-916c-11ea-85f0-dfca0d53fdb1.png).
log file: http://www.mediafire.com/file/38235o7sdyiu6wi/RPCS3.log/file

**Comment by AniLeo** [comment] 2020-05-09 01:44
d3d11.dll is not used by RPCS3, makes no sense
@kd-11

**Comment by Bel25m** [comment] 2020-05-09 01:47
So what can i do? and sorry for bad english

**Comment by Bel25m** [comment] 2020-05-09 06:12
So what can i do? sorry if i bother you

**Comment by AniLeo** [comment] 2020-05-09 06:15
Stop flooding, this is an issue tracker not a helpdesk

**Comment by Bel25m** [comment] 2020-05-09 07:51
oh sorry my fault

**Comment by kd-11** [comment] 2020-05-09 09:06
This is likely a sign of something outside rpcs3 hooked into the application somehow, maybe monitoring software or something like that. We do not use DirectX.

**Comment by jedinjapan** [comment] 2020-05-10 04:23
Disable any overlay software you have in use (Nvidia, Steam, etc) and any enhancement software like ReShade or SweetFX.

**Comment by AniLeo** [comment] 2020-05-13 01:19
I've seen this pop up a couple of times, but RPCS3 indeed does not use neither it ever used Direct3D 11, since it's a crash caused by an unknown 3rd party hook will be closing as it's not a crash on our side to fix

**Closed by AniLeo** 2020-05-13 01:19 UTC
Labels: Need Information
