### ISSUE TITLE
Demon's Souls slow loading screen + Suppress all logs

### ISSUE THREAD

**Issue by 2mg** [RPCS3/rpcs3#11244] opened 2021-12-08 02:43 UTC
Apparently not using "Suppress all logs" causes a very, very long 1st loading screen in this game. I found around that other users recommended it, don't know if it's a regression or CPU issue.

It's been happening I think since I started using RPCS3 and this game, I thought it hanged but ever so slightly the loading icons moved a bit, so I waited it out each time.

I can turn on logs and attach here if need be, just wanted to chime in.

RPCS3 Version: 0.0.19-13090-8abd3e8b Alpha
Win 7 x64 SP1
i7 4c/8t CPU non-TSX
Custom game config, but same happens with vanilla.

**Comment by illusion0001** [comment] 2021-12-08 06:43
Send logs, with and without suppression

**Comment by 2mg** [comment] 2021-12-08 12:49
[RPCS3 without log.zip](https://github.com/RPCS3/rpcs3/files/7676099/RPCS3.without.log.zip)
[RPCS3 with logging.zip](https://github.com/RPCS3/rpcs3/files/7676100/RPCS3.with.logging.zip)

**Comment by Megamouse** [comment] 2021-12-15 21:55
upload the tty.log please

**Comment by 2mg** [comment] 2021-12-16 14:15
[tty.zip](https://github.com/RPCS3/rpcs3/files/7727978/tty.zip)

For the record, I just tried disabling TTY, and it took the same long time. Didn't fiddle with log levels, but suppressing cut's loading times.

**Comment by Megamouse** [comment] 2021-12-16 20:57
I am not getting any tty output during load.
Your TTY seems to suggest some error with the data.
Maybe your dump is corrupt?
I'd try to dump the game again.
Or does it only happen when the game loads something specific?

**Comment by 2mg** [comment] 2021-12-17 15:04
> I am not getting any tty output during load. Your TTY seems to suggest some error with the data. Maybe your dump is corrupt? I'd try to dump the game again. Or does it only happen when the game loads something specific?

Only on 1st boot loading screen. I finished the game twice, no crashes or corruption or anything of the sort. Even if something is iffy, why does suppression help and is there an alternative to mitigate it within emu settings without resorting to full log suppression?

**Comment by mshpakov** [comment] 2021-12-19 05:48
Upgrade HD font mod, it only happens with the previous version of HD font mod.
https://www.nexusmods.com/demonssouls/mods/53

**Comment by 2mg** [comment] 2021-12-19 19:46
> Upgrade HD font mod, it only happens with the previous version of HD font mod. https://www.nexusmods.com/demonssouls/mods/53

1. I am using this mod, I know old HD font mod is slow.
2. This is happening on unmodded game anyway.

**Comment by Megamouse** [comment] 2022-04-21 20:20
I'll close this one. It's suspicious that there are mods applied. Even with a "unmodded" game we cannot confirm if this is true.
Also, I could not reproduce the TTY log spam at all.

**Closed by Megamouse** 2022-04-21 20:20 UTC
Labels: Need Information

**Comment by 2mg** [comment] 2022-04-22 02:30
Seems to be a dump issue, can't confirm other than say that I used a different dump and it was fast.

Though I am getting a hang (took too long) on booting the game on the very last few "Building SPU cache". This happens with both dumps. And it's not guaranteed, but frequent.

**Comment by 2mg** [comment] 2022-10-03 08:58
Small update:

Issue seems to randomly appear on vanilla game, had a playthru without it happening, then it happened on another playthru, same settings and all.

However, when I modded it, the mod called "Monk's Head Wrappings from Once Royal Mistress" seems to trigger the TTY spam immediately, so I'm posting this info here just for posterity.

Cache clearing might help in both cases, sometimes I need to set the entire game and emu from scratch...
