### ISSUE TITLE
Games freeze and crash after start 

### ISSUE THREAD

**Issue by TomSlayer997** [RPCS3/rpcs3#9249] opened 2020-11-11 17:36 UTC
i've playing for awhile, everything was pretty much normal and smooth, but recently the newer updates broke every game for me:
the games start normally, intro, menus ecc.. the game start, for like 10 seconds it goes nice then it freeze completely.

here is the log for ratchet and clank quest for booty, hope this will help programmers...i don't know sh*t about programming sadly :(

[RPCS3.log](https://github.com/RPCS3/rpcs3/files/5526298/RPCS3.log)

* OS: Windows 10
If you need anything else i'll try my best to send it

* CPU Intel I5 9700k
* GPU Nvidia RTX 2070 Super

**Comment by RainbowCookie32** [comment] 2020-11-11 17:44
Missing build that introduced the issue and a proper log. 

Please read [the issue template](https://github.com/RPCS3/rpcs3/blob/master/.github/ISSUE_TEMPLATE/1-regression-report.md) when opening an issue.

**Comment by TomSlayer997** [comment] 2020-11-11 19:33
Don't remember the exact build but it worked fine till yesterday i uploaded the log

**Comment by RainbowCookie32** [comment] 2020-11-11 19:42
Time to go and check what build did it then
https://rpcs3.net/compatibility?b

**Comment by RainbowCookie32** [comment] 2020-11-11 19:46
Check if 0.0.13-11212 works. If it does, then this issue it's a duplicate of #9238

**Comment by AphelionWasTaken** [comment] 2020-11-11 19:49
> Check if 0.0.13-11212 works. If it does, then this issue it's a duplicate of #9238

0.0.13-11212 should be the first broken build if it's a duplicate; 0.0.13-11205 should be the last working build.

**Comment by TomSlayer997** [comment] 2020-11-11 20:07
yup version 0.0.13-11205 seems to work fine

**Comment by RainbowCookie32** [comment] 2020-11-11 20:08
Duplicate of #9238 then, close.

**Comment by TomSlayer997** [comment] 2020-11-11 20:11
thanks guys : D

**Closed** 2020-11-11 20:12 UTC
