### ISSUE TITLE
[NPUB31848} Persona 5 Weird Glitchy Line during Gameplay

### ISSUE THREAD

**Issue by ExtremeCaliber** [RPCS3/rpcs3#5787] opened 2019-04-02 16:34 UTC
For some reason there's this wierd line going from the top left corner to the center. It's done this in older versions aswell.
![image](https://user-images.githubusercontent.com/41549730/55414794-d6fe5600-5539-11e9-9082-efa218ed39f7.png)
Here's a gif of the problem while the game is running
https://gyazo.com/974304bf0b8d3e48ed587537a58f389e

Settings:
PPU LLVM Recompiler
SPU LLVM Recompiler
Preferred SPU Threads: 3
Load libv2.sprx only
SPU Cache
And no additional settings under GPU

This happens mostly during gameplay or 3d scenes. During the main menu, it's not visible but as you start a new game, I can see it come a little bit and go. This problem seems to be exclusive since most other videos are seen with the game running perfectly fine. I have updated to the latest version of amd adrenaline which is 19.4.1

Specs:
AMD Athlon(tm) X4 870K Quad Core 3.9Ghz
MSI Radeon RX 480
8GB DDR3 Ram

**Comment by 13xforever** [comment] 2019-04-02 16:37
It is a known issue and is a hardware limitation https://github.com/RPCS3/rpcs3/wiki/Graphics-Driver-Issues

It's also a duplicate of #2976

**Closed** 2019-04-02 16:41 UTC
