### ISSUE TITLE
Format incompatibility detected  (Killzone 2, possibly same on others)

### ISSUE THREAD

**Issue by MrJordanL** [RPCS3/rpcs3#4543] opened 2018-05-11 10:10 UTC
Up until now, killzone 2 has never been able to get in-game, the campaign cannot in-game at all, but skimirish mode however, is now able to. So this issue i've found when going in-game in killzone 2's skimirish mode is brand new, and never before seen by any of the developers, i think this could explain some of the graphical issues in killzone 2 and 1, and possible 3, perhaps other games on the same engine/made by the creators. Please read the message in the speechmarks.

(Pasted from a dm)

"in the recent build killzone 2's skimirish mode is able to get in-game, i posted screenshots and stuff in the help channel
but.
I think might know why there;s texture/graphical bugs and such
in rpcs3 there isn't compatibility to read most of it's texture formats
E {rsx::thread} RSX: Format incompatibility detected, reporting failure to force data copy (VK_FORMAT=0x2C, GCM_FORMAT=0x9F)
E {rsx::thread} RSX: Depth texture bound to pipeline with unexpected format 0x94 x11
E {rsx::thread} RSX: Failed to find section for render target 0xC1214000 + 0x1C2000
E {rsx::thread} RSX: Format incompatibility detected, reporting failure to force data copy (VK_FORMAT=0x7C, GCM_FORMAT=0x94)
E {rsx::thread} RSX: Depth texture bound to pipeline with unexpected format 0x94 x367
E {rsx::thread} RSX: Failed to find section for render target 0xC1214000 + 0x1C2000
i had this kinda stuff in the log.
E {rsx::thread} RSX: Format incompatibility detected, reporting failure to force data copy (VK_FORMAT=0x7C, GCM_FORMAT=0x94)
that particular line could be of great use to the team
in fixing games that use the same format"

**Comment by AniLeo** [comment] 2018-05-18 20:10
Already answered on https://github.com/RPCS3/rpcs3/issues/4559#issuecomment-388840311

Closing as duplicate of #4559

**Closed by AniLeo** 2018-05-18 20:10 UTC
