### ISSUE TITLE
MGS4 higher resolution rendering graphical corruption on RDNA3

### ISSUE THREAD

**Issue by plsfixrito** [RPCS3/rpcs3#14803] opened 2023-11-08 10:59 UTC
### Quick summary

When using the following settings the skybox starts to flicker on MGS4 using AMD Vulkan driver.

settings that the issue occurs with:
GPU menu
- Renderer Vulkan
- Scaling 300% (any value beyond 200% will have the issue)

All other settings are default except those recommended on the WIKI.

### Details

The issue does appear when using AMD CPU+GPU and using Vulkan as renderer, but it is not present when using AMD CPU+GPU with OpenGL. Also the issue is not present when using a laptop with intel/nvidia hardware using the same settings.

### Attach a log file

[METAL GEAR SOLID 4 GUNS OF THE PATRIOTS [NPUB31633].log.gz](https://github.com/RPCS3/rpcs3/files/13295440/METAL.GEAR.SOLID.4.GUNS.OF.THE.PATRIOTS.NPUB31633.log.gz)

### Attach capture files for visual issues

![NPUB31633_screenshot_2023_11_08_13_28_09](https://github.com/RPCS3/rpcs3/assets/10469564/6be2b1bf-fbec-4350-a119-9b951a009cbe)

Both RSX file and Renderdoc are too large to upload to github even after compressing.

### System configuration

CPU AMD 7700X
GPU AMD 7900XTX

**Comment by AniLeo** [comment] 2023-11-18 21:51
rrc/rdc file can be uploaded elsewhere and linked here as a downloadable

**Comment by kd-11** [comment] 2023-11-20 16:48
I suspect it's Z-buffer emulation crap. AMD does not expose 24-bit depth buffers which PS3 relies on.
Test what happens with "high precision Z buffer" option with OpenGL and see if the problem re-appears.

**Comment by plsfixrito** [comment] 2023-11-25 18:01
> rrc/rdc file can be uploaded elsewhere and linked here as a downloadable

I uploaded rrc to mega
https://mega.nz/file/1kJDGbyA#VlbCC7Fj5VOIOdR0bnnAEtDjLe7s___DOGd67wlZX4k

**Comment by plsfixrito** [comment] 2023-11-25 18:03
> I suspect it's Z-buffer emulation crap. AMD does not expose 24-bit depth buffers which PS3 relies on. Test what happens with "high precision Z buffer" option with OpenGL and see if the problem re-appears.

I used the option with OpenGL and 300% upscale the issue didn't appear.
![NPUB31633_screenshot_2023_11_25_20_54_42](https://github.com/RPCS3/rpcs3/assets/10469564/fe41781d-3075-46bd-9aa0-25ef924a3599)

**Comment by kd-11** [comment] 2023-11-25 18:47
That means this is most likely the same issue as https://github.com/RPCS3/rpcs3/issues/14838 affecting RDNA3.

**Comment by grimmute** [comment] 2023-12-19 17:25
I have finished BLES00246 last week on 6900XT using the latest drivers using Vulkan + 300% scaling. I haven't encountered this issue. It might indeed be an issue specific to RDNA3.

**Comment by asp0909** [comment] 2024-02-05 20:56
I have the same problem! rx 7900 xtx! RDNA 3 specific problem... is there a solution expected?

**Comment by asp0909** [comment] 2024-02-19 00:55
![Captura de pantalla (14)](https://github.com/RPCS3/rpcs3/assets/29218473/5765cbb3-df7a-43c1-badd-dd0a211bfe0f)
7900 xtx  adrenaline latest beta drivers  16/2/2024

**Comment by AniLeo** [comment] 2024-03-03 13:39
Duplicate of #14838 where the main discussion took place.

---

Closing as fixed by AMD.

Added this to the documentation at https://github.com/RPCS3/rpcs3/wiki/Graphics-Driver-Issues for historical purposes.

**Closed by AniLeo** 2024-03-03 13:39 UTC
Labels: Need Information, Render: Vulkan, Driver: AMD Vulkan
