### ISSUE TITLE
Unreal Engine 3 games issues (common)

### ISSUE THREAD

**Issue by Psycho-A** [RPCS3/rpcs3#4025] opened 2018-01-03 16:17 UTC
I suggest to write here about all found bugs and issues on Unreal Engine 3 games since a lot of them seems require fixing for now.

For Silent Hill Downpour:
1. No dynamic shadows from player and objects.
2. Static world lighting computes incorrectly: most of areas look overbrighten and overbloomed.
3. Bad model lighting: some models looks completely white or too dark,
4. Intro cutscene's video freezes and doesn't exit after played, so the following game progress is impossible.

The same issues (except 4) noticed on Saw: The videogame.

**Comment by slashiee** [comment] 2018-01-03 22:38
Supersonic Acrobatic...whatever the fuck [NPUB30035] also has these issues (no problem 4)
![2018-01-03_14-38-18](https://user-images.githubusercontent.com/15317421/34543018-c60f26d2-f093-11e7-98f9-7aba1e7a731f.png)

**Comment by Psycho-A** [comment] 2018-01-04 18:18
To be more certain: this video (https://www.youtube.com/watch?v=WflsHHR-3fA) demonstrates that dynamic shadows are emulated in Downpour after all, but it reaches ONLY with AMD Radeon cards, and seems like that only for main characters, not world objects. For NVidia I never noticed *any* shadows myself as well as on the demo videos.

**Comment by Xcedf** [comment] 2018-01-08 00:29
Lolipop Chainsaw another example of this
i don't have shadows on my GTX 1070, but here's someone's video on AMD gpu which has it
https://www.youtube.com/watch?v=lDOvnQr8drI

**Comment by kd-11** [comment] 2018-03-21 12:50
The rsx part of the shared bugs should be fixed in https://github.com/RPCS3/rpcs3/pull/4312. The freezing videos/intros require LLE audio to get past which does not produce any sound, someone will have to fix HLE audio at some point for that.

**Comment by isshininu** [comment] 2018-03-21 15:35
Silent Hill Downpour now have proper lighting (Strict RM disabled, scale set to 125%, **gamma settings by default**).
![464](https://user-images.githubusercontent.com/6324523/37719637-dfe930ba-2d3e-11e8-9df5-3359253e70fd.png)

![462](https://user-images.githubusercontent.com/6324523/37719633-de623296-2d3e-11e8-9dfb-164db38aa1aa.png)

[RPCS3.log.gz](https://github.com/RPCS3/rpcs3/files/1833955/RPCS3.log.gz)

**Comment by Psycho-A** [comment] 2018-03-21 17:20
Wow, that's a breakthrough! I strongly need to test this right now ;)

Yes, shaders now bumped to v1.2

**Comment by slashiee** [comment] 2018-03-21 17:32
Supersonic Acrobatic Long-Name's lighting is fixed
![2018-03-21_10-31-22](https://user-images.githubusercontent.com/15317421/37726659-18d36284-2cf3-11e8-9329-0912ece2f802.png)

**Comment by Psycho-A** [comment] 2018-03-22 00:17
Well, SH: Downpour is mostly fixed, but bump-maps on characters and some itmes seems still to be rendered weird way (sharp dark to light gradients on one plain, some texture smoothing etc.), and dynamic shadows are glitchy if any resolution scaling different from 720p is chosen (they cuts and flicker).

**Comment by isshininu** [comment] 2018-03-22 09:31
Could you provide screenshots with these issues?

**Comment by kd-11** [comment] 2018-03-22 09:37
Don't report issues with resolution scaling with the other issues. Same thing with forced anisotropic filter overrides - they will always break some games as they are semi-hacks by design. The enhancements are a bonus and should be disabled if they break the game's logic.

**Comment by isshininu** [comment] 2018-03-22 11:57
Yeah, anisotropic filter must be set on "Automatic". Resolution scale should be set by default...
Thank god, SHD gameplay doesn't really affected by red noise - only menu.
But this problem is really very interesting

**Comment by Psycho-A** [comment] 2018-03-22 19:10
@kd-11, yes, I already figured out that shadows is the scaling issue. And also it cures by setting resolution threshold to 512x512 (as well as 'red' menu issue).

@isshininu, yes, I can. Here's that issue related to bump mapping (as I think), and not presented on the original console. It seems that some shadowing vectors reading incorrectly, or texture coordinates are wrong so we can see these white-dark areas.

![01](https://user-images.githubusercontent.com/1223276/37792798-b74180b0-2e04-11e8-9dd3-d84f27fcf100.jpg)
![02](https://user-images.githubusercontent.com/1223276/37792799-b7686446-2e04-11e8-9899-2f640bceb160.jpg)
![03](https://user-images.githubusercontent.com/1223276/37792800-b78b65ae-2e04-11e8-89d2-6251ee1022d4.jpg)
![04](https://user-images.githubusercontent.com/1223276/37792801-b7adca36-2e04-11e8-9a56-5b1da0c39dd7.jpg)
![05](https://user-images.githubusercontent.com/1223276/37792802-b7cef030-2e04-11e8-85b8-e3ee9431fd20.jpg)
![06](https://user-images.githubusercontent.com/1223276/37792803-b7f096e0-2e04-11e8-8001-0026aa0fe30d.jpg)
![07](https://user-images.githubusercontent.com/1223276/37792804-b8105ab6-2e04-11e8-9de0-aa1538179e8e.jpg)
![08](https://user-images.githubusercontent.com/1223276/37792805-b8313a4c-2e04-11e8-853d-23ce79114291.jpg)

**Comment by Xcedf** [comment] 2018-03-22 20:31
Saw II looks fixed like any other UE3 game except it still has wierd shadowmap issue
![22](https://user-images.githubusercontent.com/7060586/37796772-19a8ce10-2e29-11e8-84b5-2113d3d9d920.jpg)

**Comment by slashiee** [comment] 2018-03-24 05:37
Latest PR commits fixes lighting even more for SARPBC!
![2018-03-23_22-35-37](https://user-images.githubusercontent.com/15317421/37860820-9ad1a78e-2eea-11e8-8626-cdd9197ad598.png)

**Comment by kd-11** [comment] 2018-03-25 13:10
Most issues fixed with https://github.com/RPCS3/rpcs3/pull/4312. The normal vector issue is still present though

**Comment by Psycho-A** [comment] 2018-03-25 16:47
Bump mapping issues still present (not seen at the original console)...

**Comment by AcceptableSpare** [comment] 2018-05-30 02:43
Does anyone know what's wrong with the shading on the characters in killer is dead? It looks kinda correct, but I can't really explain what's wrong with it (lighting issue ?). Depth of field isn't working correctly either during cut scenes. It'll instead cover the entire screen with some distorted box.

**Comment by Ale100000** [comment] 2018-06-09 22:57
Asura's Wrath also have this problem with lighting/shadows
![1](https://user-images.githubusercontent.com/16784631/41196748-d363059a-6c1e-11e8-9805-3c6ebd8c6c53.png)
![2](https://user-images.githubusercontent.com/16784631/41196749-d3e2a4bc-6c1e-11e8-87aa-391dd9d33bc1.png)

**Comment by Parthorisian** [comment] 2018-07-23 17:20
![qw](https://user-images.githubusercontent.com/35437970/43092371-b0366a3a-8eb5-11e8-8866-b3a57084a362.png)
log [SilentHillDownpour_RPCS3.zip](https://github.com/RPCS3/rpcs3/files/2220365/SilentHillDownpour_RPCS3.zip)

**Comment by Psycho-A** [comment] 2019-03-22 09:40
The lighting/shadowing issues are still in their place...
(see https://github.com/RPCS3/rpcs3/issues/4025#issuecomment-396004614)

**Comment by kd-11** [comment] 2020-05-08 10:24
Any other common UE3 bugs left?

**Comment by GustavoVR11** [comment] 2020-05-28 13:03
As Psycho-A mentioned in his own post (https://github.com/RPCS3/rpcs3/issues/4641), the binoculars do not work on Silent Hill downpour:

![40379658-41d2f87e-5de6-11e8-93d1-6ebb48427a45](https://user-images.githubusercontent.com/66071632/83144876-421eca80-a0f4-11ea-9374-4995f4b91452.jpg)
![40379659-421080a4-5de6-11e8-9df5-e8d90051f3e1](https://user-images.githubusercontent.com/66071632/83144883-43e88e00-a0f4-11ea-8ff3-66f86b9428d4.jpg)

Here's the savegame for *BLUS30565*:
[SaveData.zip](https://github.com/RPCS3/rpcs3/files/4695670/SaveData.zip)

**Comment by ruthan** [comment] 2020-05-29 01:26
Have all UE3 games have also sound problems, or its only UT3 problem?
See https://github.com/RPCS3/rpcs3/issues/5134

**Comment by DefaltBR** [comment] 2020-06-02 13:33
> 
> 
> Any other common UE3 bugs left?

Some shadows/ligthing on objects still seems to get wrong coordinates (lightmap issue? shadowmap issue?) shadows sometimes are kind of facing the light source instead of going the opposite, gerenating extra bright/pitch black gradients on a few objects (much more visible if there's a dynamic light in action, like the flashlight in SH Downpour)... And also, some models shows wrong depth, like shown by Ale100000... (bump-mapping or tesselation issue? If so, that may be what's generating the shadow/lighting gradient issue?) I'm not a "graphic expert" by any means, i'm just reporting what i stiil see in UE3 games... (i'm using latest master build, no extra settings... Native res, native Aniso, Vulkan... Tried OpenGL and it's the same) "Extra info/Off topic": I tried SH Downpour on Xenia emu. Canary build and it doesn't have that tesselation/bump-mapping issue... Then i sniffed into the .cfgs to see if there was anything related to that, and i noticed they made a special fix for it that was only applied when using DX12 called "UE3 Tesselation Fix (DX12 Only)" or something like that, so maybe DirectX is required to fix this? Thank you, and sorry if i talked some non-sense, like i said, i'm no expert, just reporting the bugs that are still present up to date... 

> 
> 
> Asura's Wrath also have this problem with lighting/shadows
> ![1](https://user-images.githubusercontent.com/16784631/41196748-d363059a-6c1e-11e8-9805-3c6ebd8c6c53.png)
> ![2](https://user-images.githubusercontent.com/16784631/41196749-d3e2a4bc-6c1e-11e8-87aa-391dd9d33bc1.png)

**Comment by Emulator-Team-2** [comment] 2020-06-11 08:32
Tested with pr https://github.com/RPCS3/rpcs3/pull/8398.
Screenshots from (Asura's Wrath, Silent Hill: Downpour).
**Link:** https://github.com/RPCS3/rpcs3/pull/8398#issuecomment-642414947

**Comment by DefaltBR** [comment] 2020-06-11 13:54
Basically everything here is fixed by #8398 ! Only thing not fixed is issue number 1 from issue thread #4641 mentioned by @GustavoVR11 (binoculars in SH Downpour Devil's Pit Platform are showing black screen when looking through)

> 
> 
> As @Psycho-A mentioned in his own post (#4641), the binoculars do not work on Silent Hill downpour:
> 
> ![40379658-41d2f87e-5de6-11e8-93d1-6ebb48427a45](https://user-images.githubusercontent.com/66071632/83144876-421eca80-a0f4-11ea-9374-4995f4b91452.jpg)
> ![40379659-421080a4-5de6-11e8-9df5-e8d90051f3e1](https://user-images.githubusercontent.com/66071632/83144883-43e88e00-a0f4-11ea-8ff3-66f86b9428d4.jpg)
> 
> Here's the savegame for _BLUS30565_:
> [SaveData.zip](https://github.com/RPCS3/rpcs3/files/4695670/SaveData.zip)

And here it is in PR #8398:
![image](https://user-images.githubusercontent.com/65127365/84393251-c16ecc80-abd1-11ea-8be7-b1d6367a012b.png)

![image](https://user-images.githubusercontent.com/65127365/84393329-d51a3300-abd1-11ea-8a4a-0ee8d853d059.png)

**Closed** 2020-06-12 17:19 UTC
Labels: RSX
