### ISSUE TITLE
Regression: Starting games from Windows network share stopped working again

### ISSUE THREAD

**Issue by ruthan** [RPCS3/rpcs3#9647] opened 2021-01-24 12:10 UTC
## Quick summary
I cant say, exactly with which build, it was broken, but its more than month, i would say that 2 months ago, it worked fine.

 Tested with:
 RPCS3 Version: 0.0.14-11619-22584fb2 Alpha

Here are logs, for same game, once install on local disk, once on Windows network share path (UNC).
- locally it works fine.. i simullated same behavior with all other games and with 2 machines, in WIn7 and Win10.

[RPCS3-LoadingOkLocalDisk.zip](https://github.com/RPCS3/rpcs3/files/5862151/RPCS3-LoadingOkLocalDisk.zip)
[RPCS3-Network.zip](https://github.com/RPCS3/rpcs3/files/5862152/RPCS3-Network.zip)

**Comment by elad335** [comment] 2021-01-24 12:38
Its a duplicate of #9228 I think.

**Comment by AniLeo** [comment] 2021-01-24 12:49
Duplicate of #9228

**Closed by AniLeo** 2021-01-24 12:49 UTC
Labels: Meta: Duplicate

**Comment by SteveOfWarr** [comment] 2021-01-24 13:03
Issue goes away when reverting to RPCS3 Version: 0.0.14-11605-b96864c7 Alpha.
