### ISSUE TITLE
[BCES00008] [Regression] Warhawk Textures Missing In v0.0.6 Builds, But Present In v0.0.5. 

### ISSUE THREAD

**Issue by mmentc** [RPCS3/rpcs3#6443] opened 2019-08-28 20:46 UTC
PC Specs:

Processor Intel(R) Core(TM) i7-4790 CPU @ 3.60GHz
Video Card NVIDIA GeForce GTX 970
RAM 20 GB
Operating System Windows 10

**Working Build: rpcs3-v0.0.5-7772**
[rpcs3-v0.0.5-7772.log.gz](https://github.com/RPCS3/rpcs3/files/3552815/rpcs3-v0.0.5-7772.log.gz)

**Non-Working Build: rpcs3-v0.0.6-8612**
[rpcs3-v0.0.6-8612.log.gz](https://github.com/RPCS3/rpcs3/files/3552814/rpcs3-v0.0.6-8612.log.gz)

---

When using the older builds from v0.0.5, the textures are displayed wish some missing effects here and there. On the v0.0.6 builds, the textures aren't present at all. Using all of the default settings on RPCS3 except for changing OpenGL to Vulkan. 

This is an easily reproducible issue. In order to reproduce, start Warhawk with each of the versions listed above. I've tried nearly every combination of settings over the course of about 10 builds ranging from 0.0.5 and 0.0.6, and the issue remains.

---

**rpcs3-v0.0.5-7772**

![rpcs3-v0 0 5-7772](https://user-images.githubusercontent.com/25136478/63890778-82e88800-c998-11e9-8ffc-be1b7c6c1326.png)

**rpcs3-v0.0.6-8612**

![rpcs3-v0 0 6-8612](https://user-images.githubusercontent.com/25136478/63891185-7ca6db80-c999-11e9-8fcf-5dfc927b9af3.png)

---

The major issue with the non working build seems to be this:

`·E 0:02:40.022876 {RSX [0x0045f7c]} RSX: Could not gather all required slices for cubemap/3d generation`

**Comment by dio-gh** [comment] 2019-08-28 22:59
Could you upload RSX captures as well? You can take one if you enable the debugger window in `View -> Show Debugger` then click `RSX Capture`. They'll be saved to `/captures/`. You may want to compress them, as uncompressed they get pretty large.

**Comment by mmentc** [comment] 2019-08-29 02:09
> Could you upload RSX captures as well? You can take one if you enable the debugger window in `View -> Show Debugger` then click `RSX Capture`. They'll be saved to `/captures/`. You may want to compress them, as uncompressed they get pretty large.

Sure thing. 

**rpcs3-v0.0.6-8612**
https://drive.google.com/open?id=13neJHZiK8Ss5jPrZ3Y6xLwr97FcZFCtg

**rpcs3-v0.0.6-8612**
https://drive.google.com/open?id=1pz3o3TsVtzp1lKYHxUb3J5raeR40Xeao

**Comment by kd-11** [comment] 2019-08-30 14:56
I'd like to see a renderdoc capture of the game running under 0.0.5. rpcs3 0.0.5 did not support 3D textures, and unless we somehow got the dimensions wrong, the LUT is only 1x1x1 (which is suspicious) and its just black in color, which is doubly suspicious. This black LUT is the cause of the messed up visuals. The game renders fine but the diffuse contribution is "color corrected" to 0 which removes all the color in post.

**Comment by mmentc** [comment] 2019-08-30 22:13
> I'd like to see a renderdoc capture of the game running under 0.0.5. rpcs3 0.0.5 did not support 3D textures, and unless we somehow got the dimensions wrong, the LUT is only 1x1x1 (which is suspicious) and its just black in color, which is doubly suspicious. This black LUT is the cause of the messed up visuals. The game renders fine but the diffuse contribution is "color corrected" to 0 which removes all the color in post.

Thanks for the insight kd. I've never thought of that being a something that can cause issues with the render. I've attached the capture below, so maybe it can be of use. 

https://drive.google.com/open?id=12-MRiRg-qBBPJLGjjuBZ0bmyyGGKqY2j

**Comment by kd-11** [comment] 2019-08-31 09:30
Looks like nvidia drivers for maxwell and pascal have diverged for some time now, which is making it impossible to replay a maxwell capture on pascal. I'll see what I can do about it.
Maybe you can just attach the old 0.0.5 build and I can try and get it running locally.

**Comment by mmentc** [comment] 2019-09-01 01:03
> Looks like nvidia drivers for maxwell and pascal have diverged for some time now, which is making it impossible to replay a maxwell capture on pascal. I'll see what I can do about it.
> ~Maybe you can just attach the old 0.0.5 build and I can try and get it running locally.~
> EDIT: Actually, try capture with OpenGL (you need to enable the "Use legacy buffers" option).

Here's the new capture.

https://drive.google.com/open?id=1s2_sAHj6IjL2j_0gHgWDj9QZu7T6Q2pm

**Comment by kd-11** [comment] 2019-09-01 11:10
Thanks. Shows the problem perfectly. The texture dimensions are 16x16x16 not 1x1x1 as newer builds are detecting. I strongly suspect broken mipmaps for 3D textures.

**Comment by kd-11** [comment] 2019-09-01 14:24
Should be fixed by https://github.com/RPCS3/rpcs3/pull/6467.

**Closed** 2019-09-02 13:49 UTC
