### ISSUE TITLE
inverted controls on linux

### ISSUE THREAD

**Issue by Gamedev1909** [RPCS3/rpcs3#3825] opened 2017-12-02 00:37 UTC
Hi me again Friendly Time lord 
on linux we got a major issue with controllers 
everything is inverted left and right stick and even remapping fails up is always down and down is always up

**Comment by annadess** [comment] 2017-12-02 02:04
I had a similar issue, there should be an option saying scanning for noise, try to see if that fixes it, it did it for me

**Comment by Gamedev1909** [comment] 2017-12-02 02:24
doesnt work this is a real issue

**Comment by kirbyfan64** [comment] 2017-12-02 02:59
I know on the YAML config there's a config option for reversing the axes that I use, but I'm not sure how to configure it using the UI...

**Comment by Hirato** [comment] 2017-12-02 03:13
The default binds work perfectly for me and my controller - I'm just using a standard xbox360 controller coupled with the stock standard xpad kernel driver.
I'm also not seeing any issues with rebinding any controls; I swapped the vertical axis of both my sticks via the UI (it appeared within the last few days), and they're now inverted as they should be when going into a game.

You'll have to provide more information, such as your distro, controller, userspace driver (i.e. xboxdrv and it's settings) if applicable, etc. If there's to be any hope of either reproducing the issue, or tracking it down.
I'd also suggest checking to see if there's anything else plugged in that evdev might pick up as a controller - maybe check `/dev/input` to see if there are multiple js devices?

**Comment by hcorion** [comment] 2017-12-02 03:17
I also noticed this axis reversial with my Xbox 360 controller, but it's easy enough to change this through the GUI now.

**Comment by Gamedev1909** [comment] 2017-12-02 04:26
Arch linux evdev 360 controller and no other controllers

**Comment by sambow23** [comment] 2017-12-02 04:27
Having the same issue too, was working fine on older builds

**Comment by 7oxicshadow** [comment] 2017-12-02 17:04
Same issue with me on 360 controllers (using xboxdrv).

Note sure if it is by design but changes made to the controller mappings whilst the game is loaded will not take effect until the game is restarted. This caught me out a couple of times.

**Comment by Megamouse** [comment] 2017-12-02 22:58
https://github.com/RPCS3/rpcs3/pull/3817

**Comment by 7oxicshadow** [comment] 2017-12-03 13:16
Sorry to be the bringer of bad news but i have just tested v0.0.4-50-bfb3144 and it is no different (xboxdrv). Hopefully somebody else will be able to test soon to confirm my findings.

**Comment by Megamouse** [comment] 2017-12-03 13:22
That's because you haven't tried my branch.
You have tested with master.
You need to compile my branch yourself or let someone create an appimage for you.

**Comment by 7oxicshadow** [comment] 2017-12-03 13:25
sorry that was my bad, i checked the master and saw a number of commits with your name against them and assumed it was one of them.

I will try your branch in a bit.

**Comment by 7oxicshadow** [comment] 2017-12-03 16:40
@Megamouse I have built your "volley" branch and RPCS3 reports v00.04-6024-5838e27f.

The Y axis appears to be fixed but the X axis on both sticks still appears to be reversed?

**Comment by Megamouse** [comment] 2017-12-03 17:23
reversed how? by default?
or ingame AFTER you set your own controller configuration

**Comment by 7oxicshadow** [comment] 2017-12-03 17:28
I start RPCS3, configure my controller to bind the joystick controls (up, down, left, right) and then load Demons Souls. When in game, if I press right my character moves left and visa versa

**Comment by Megamouse** [comment] 2017-12-03 19:39
It should work now with my latest push.
At least I hope so

**Comment by Megamouse** [comment] 2017-12-03 19:39
and try rumble as well

**Comment by 7oxicshadow** [comment] 2017-12-03 21:58
I rebuilt your latest branch. v0.0.4-6206-be2d56c0 and confirm that the controls are now working as expected :)

I cannot test rumble as i have never got it working on my machine (think there is an xboxdrv parameter I am missing). If anyone has ever got it working let me know how. Thanks.

**Comment by Megamouse** [comment] 2017-12-03 22:01
yeah actually I got it working with ubuntu 17.40.
don't remember which evdev I have

**Comment by Megamouse** [comment] 2017-12-21 15:06
Please retest

**Comment by 7oxicshadow** [comment] 2017-12-24 16:38
I have just tested v0.0.4-6272-fc2ef552 and can confirm that the controls are working correctly for me. 
[ For anyone updating to the latest version, don't forget to re-configure your analog sticks :) ]

**Comment by AniLeo** [comment] 2018-01-13 19:11
This has been confirmed as fixed for a while, I'm therefore closing the issue.

**Closed by AniLeo** 2018-01-13 19:11 UTC
Labels: Input, OS: Linux
