### ISSUE TITLE
[Regression] Using Vulkan or OpenGL doesn't render anything.

### ISSUE THREAD

**Issue by emmanu888** [RPCS3/rpcs3#13689] opened 2023-04-17 20:58 UTC
### Quick summary

Rendering must have been broken for GPU's on the GTX 600 series after 0.0.23-14088 as going to even to 0.0.23-14089 is enough to break rendering on both Vulkan and OpenGL on GTX 600 series GPU's. I know these GPU's are old but GTX 700 series GPU do produce an output and both series 600 and series 700 cards operate on the same Kepler architecture.

### Details

Build v0.0.23-14088-698c3415 was the last build of RPCS3 that was able to render on Nvidia series 600 GPU's on both Vulkan and OpenGL. Any builds newer than the afformentioned build has broken rendering on Kepler architecture GPU's in the series 600 range of GPU's, however series 700 which also runs on the Kepler architecture renders out correctly with even the latest build of RPCS3 leading me to believe that something was broken in the rendering pipeline after build 0.0.23-14088 that leads series 600 GPU's to no longer render out anything once a game is running.

I've used After Burner Climax as the test game as its the game that runs as smoothly as possible on the emulator when it comes to doing tests.

### Build with regression

0.0.23-14089-e2870705

### Attach two log files

[RPCS3.log](https://github.com/RPCS3/rpcs3/files/11255663/RPCS3.log) 0.0.23-14088
[RPCS3.log](https://github.com/RPCS3/rpcs3/files/11255668/RPCS3.log) 0.0.23-14089

### System configuration

AMD Phenom II X6 1055T
NVIDIA GeForce GTX 680 on driver 474.30
16GB of RAM

**Comment by solarmystic** [comment] 2023-04-17 21:41
I doubt 14089 is the actual responsible commit for broken GPU rendering, it was broken for another reason.

This was subsequently fixed in 14090.

![image](https://user-images.githubusercontent.com/4345150/232616411-4bcdc6ee-7fef-41b3-ac7f-3462ebba8d9e.png)

Please continue testing 14090 and above until you hit the actual responsible commit that broke OpenGL/Vulkan rendering on your GPU.

**Comment by emmanu888** [comment] 2023-04-17 22:29
I don't want to sound aggressive but as soon as i use any other build that is not 0.0.23-14088, i get zero render output. The FPS counter suggest something is being rendered, i can hear sounds in game but all i get is a black screen unless i use 0.0.23-14088.

It cannot be Vulkan or OpenGL because if i try the latest version of DuckStation or Dolphin, they both render correctly. Only RPCS3 with anything newer than build 0.0.23-14088 stops giving me a render output.

I'm including two logs, different systems but both GPU's run the same Kepler architecture.
[RPCS3.log](https://github.com/RPCS3/rpcs3/files/11256320/RPCS3.log) Phenom II X6 1055T and GTX 680
[RPCS3 0.0.23-14090.log](https://github.com/RPCS3/rpcs3/files/11256324/RPCS3.0.0.23-14090.log) Core i7-6700 and GT 710

Both the GTX 680 and the GT 710 are Kepler based. The only thing different is the CPU. Would it be something CPU related that breaks rendering on anything above build 0.0.23-14088 on the Phenom 2 system but doesn't break anything on the Core i7-6700 system?

**Comment by RipleyTom** [comment] 2023-04-17 23:00
Yes, the PR you pointed at is about automating vector instructions using sse/avx/avx2/avx512. There may be a bug in it that has gone unnoticed because no one had a cpu ancient enough to not have at least avx.

**Comment by emmanu888** [comment] 2023-04-17 23:07
So i'm guessing giving logs for both systems, both running 14090 could be of some help?

Because yeah. Phenom II has nothing for AVX, i can't even run newer versions of PCSX2 on that CPU.
Would it be the lack of AVX that breaks rendering on anything past 14088? 
As to why 14090 produces no rendering output on the Phenom II but does produce a render output on the i7-6700? Despite the fact that both the GTX680 and the GT710 runs on the Kepler architecture?

**Comment by RipleyTom** [comment] 2023-04-17 23:39
It's common for ps3 games to use the SPU for some part of the image processing(usually AA), which makes heavy use of vector instructions in recompiled code(we also use said vector instructions to help with atomic operations). This can easily lead to corrupt video output.

I tried disabling the optimized paths to see if I could reproduce and I couldn't.

Also of note you have weird settings on the phenom log, multithreaded rsx and async texture streaming, also spu decode is set to asmjit and not spu llvm. Probably unrelated but I thought I'd point it out.

**Comment by emmanu888** [comment] 2023-04-17 23:56
On the Phenom if i enable spu llvm the emulator crashes, probably due to the missing AVX instructions.

And those settings i enabled once and just never really thought about disabling them, but even disabled i have no rendering output on the Phenom based system.

I'm including a log with multithreaded rsx and async texture streaming disabled, i disabled AA as well but still no rendering output.
[RPCS3.log](https://github.com/RPCS3/rpcs3/files/11256612/RPCS3.log)

And also a log with LLVM enabled, rarely does it work and won't crash the emulator but i guess i caught LLVM recompiler in a good mood to allow After Burner Climax to load up this time around.
[RPCS3.log](https://github.com/RPCS3/rpcs3/files/11256626/RPCS3.log)

**Comment by RipleyTom** [comment] 2023-04-18 02:17
After further testing I can confirm that if you disable avx, avx2, sse4.1 AND ssse3(I had initially forgotten that one) games don't render properly.

**Comment by emmanu888** [comment] 2023-04-18 04:21
All instruction sets that the Phenom II CPU doesn't have but newer CPU's has.

In other words my CPU's too old for any other builds of the emulator unless its specifically 0.0.23-14088.
And i'm gonna guess there's probably no way to fix that issue since it only affects CPU's that don't have newer instruction sets like AVX, AVX2, SSE4.1 and SSSE3.

**Comment by kd-11** [comment] 2023-04-18 08:53
My bet is on ssse3 emulation not working properly. We use pshufb to do byteswap on 16 bytes at a time on the index buffers.

**Comment by solarmystic** [comment] 2023-04-18 09:53
@emmanu888 Try https://github.com/RPCS3/rpcs3/pull/13691 and see whether that PR fixes it for you.

**Comment by emmanu888** [comment] 2023-04-18 11:36
@solarmystic How do i try the PR? I do not have a compiler installed on my PC at the moment so i can't compile the code with the potential fix. Sorry i only just woke up half an hour ago

**Comment by RipleyTom** [comment] 2023-04-18 11:40
I can confirm that it fixes it on my setup with every vector extension disabled.

**Comment by Darkhost1999** [comment] 2023-04-18 11:44
> How do I try the PR?

https://wiki.rpcs3.net/index.php?title=Help:Using_different_versions_of_RPCS3#How_to_download_builds_from_a_pull_request_on_GitHub?

**Comment by emmanu888** [comment] 2023-04-18 11:53
As @RipleyTom said, yep the new PR fixes the rendering issues caused by the instruction sets that the Phenom II is missing!

![new pr works!](https://user-images.githubusercontent.com/23643422/232768979-f2295601-f380-4ac2-bbd6-733bff940b9d.PNG)

**Comment by Nekotekina** [comment] 2023-04-18 13:48
@emmanu888 Should be fixed now. What happens if you use SPU LLVM?

**Comment by emmanu888** [comment] 2023-04-18 16:07
@Nekotekina Either the emulator crashes or the game will start but load times will be long and the game ends up crashing from the long load times

**Comment by Augusto7743** [comment] 2023-04-19 02:16
The problem not was related with video code, but an Phenom II issue.
Phenom II have similar performance comparing with AMD FX.
Thus can run several games that not not use extremely the Cell.

**Closed** 2023-04-19 02:58 UTC
