### ISSUE TITLE
UFC Undisputed 3 CPU blit Causes crash. But is needed for textures.

### ISSUE THREAD

**Issue by blowsmoke** [RPCS3/rpcs3#10906] opened 2021-09-21 23:57 UTC
So CPU blit is needed for textures on the characters to show properly, however it causes an issue where eventually the audio stops working then shortly after the game crashes. Turning off CPU blit and enduring the texture issues seems to prevent the crash.

This game is not available on PC nor are any other sports games. RPCS3 saves the day in that regard. But this game :<

The problem is that it seems like it should be a simple fix. Or at least an easy diagnosis.
[RPCS3.log.gz](https://github.com/RPCS3/rpcs3/files/7206878/RPCS3.log.gz)

**Comment by jokoputera** [comment] 2021-09-23 07:30
RSX Capture please, and last known build that worked well

**Comment by blowsmoke** [comment] 2021-09-23 10:37
If I knew the last build it worked on I'd be using that build, this game is the only one I have and the only one I can't play :<

So I don't know what an RSX capture is, but MAN after looking it up it's EXACTLY what I been looking for! I tried to ask the people in the RPCS3 discord "help" channel where I could find a log of the code one would need to diagnose an issue.... but they were super rude to me refusing to help telling me it would do me no good since I'm not a programmer even going as far as deleting my messages as I typed them asking for help. Finally, after saying "there is something wrong with you guys" I left. I later learned I had been banned.... 

*sigh* Why couldn't they just tell me about this... then I'd be able to easily provide you with what ur looking for now.

Instead I have to ask you what RSX capture is. I looked it up, but I'm not sure.... it's a download right? Can you give me a link so I'm know what I'm getting please. Or is it built into RPCS3?

BTW THANK YOU FOR YOUR HELP!

**Comment by MSuih** [comment] 2021-09-23 10:44
Captures can be taken with `Utilities > Create RSX capture`. You have to do it while the issue is visible on screen. Shortcut for it is ALT + C. The capture is saved to a folder in the emulator directory, you should compress it and add is as attachment to the first post.

**Comment by blowsmoke** [comment] 2021-09-23 10:48
Hmmm I guess the RSX capture is not what I thought it was.....

So... man IDK. Do I hit alt C while it's crashing? Maybe after the audio goes out but before it crashes? Or should I run the game without CPU blit and capture the texture/lighting issue THAT presents?

**Comment by blowsmoke** [comment] 2021-09-23 10:49
I mean It's a hard crash that shuts down RPCS3 altogether...

**Comment by MSuih** [comment] 2021-09-23 10:55
RSX Capture is for capturing visual issues, it tries to save the commands used for rendering the currently displayed frame so that it can be reproduced later and without requiring the game itself.

Diagnosing crashes is much harder, and usually requires an IDE so that you can build a debug version and attach a debugger to the process. I would not recommend trying it without any prior experience.

**Comment by blowsmoke** [comment] 2021-09-23 11:04
I have no prior experience but I'm willing to try and figure it out, or have a friend walk me through it.

I know WHAT causes the crash. I just need to know why. I've narrowed the culprit of the crash to CPU blit.

CPU blit is what fixes the texture issue in the game. without it you're looking at lightless shadowed figures (the characters in game)... not black.... just not lighted... or in shadow..... without write color buffer, they ARE black textures. You need both write color and CPUblit for the textures to work........ But unfortunately CPUblit causes a crash...

The audio cuts out first while the game goes on as if simply muted for about 20 seconds then inevitably crashes.

But yes the RSX debugger is what I came across when looking up RSX capture. I assumed you needed that for RSX capture. I was wrong. However the debugger itself is EXACTLY what I need. I just need to know how to use it or have someone who does walk me through it. I guess.....

**Comment by blowsmoke** [comment] 2021-09-23 11:08
"Diagnosing crashes is much harder, and usually requires an IDE so that you can build a debug version and attach a debugger to the process." << this statement right here helped answer the question I was asking in the discord help server. The answer they all refused to give me. You recommend I don't try it without prior experience. That's perfectly fine but you still gave me the answer! 

lol anyway, sry I'm kinda bitter about getting banned from a help channel for asking for help.

Thank you though, you've given me a new avenue to explore, even if it turns out to be beyond me. At least now I can explore it.

If anyone wants to help me explore it ;> haha

Again though thanks. I guess sending the RSX capture won't help then. I spent hours and hours trying to get this game to work within the last few days, right this second I'm taking a break though. ;D

**Comment by blowsmoke** [comment] 2021-09-23 11:09
Maybe someone passing by knows a build this game worked on in the past. That would be ideal.

**Comment by Asinin3** [comment] 2021-09-23 11:31
The best way to find that out would be either searching for the game on youtube and looking for a recent video with build number listed. Or going on compatibility forums. E.g these threads: https://forums.rpcs3.net/thread-183304.html https://forums.rpcs3.net/thread-182532.html

**Comment by Mookie19** [comment] 2021-09-23 16:36
I feel this is a duplicate of another post about UFC Undisputed 3's audio desyncing and freezing. There has never been a working build running with force CPU Blit.

be patient, the devs have made a tremendous amount of progress in the year I've been following this game closely. I'd say... Soon™

**Comment by blowsmoke** [comment] 2021-09-23 23:11
Thanks I hope so.

SO CLOSE!!!!

**Comment by ScottNash042** [comment] 2023-08-09 11:57
update or close ??

**Comment by Mookie19** [comment] 2023-08-10 05:24
I would close this.

 UFC Undisputed 3 (and 2010) doesn't require "Force CPU Blit" or "Write Color Buffers" anymore. Performance is worst now but that is an issue for another post.

**Closed** 2023-08-10 05:34 UTC

**Comment by DeceptionDeceives** [comment] 2024-08-10 00:25
Liar.
