### ISSUE TITLE
Wayland unable to boot 

### ISSUE THREAD

**Issue by LuxLucian** [RPCS3/rpcs3#9882] opened 2021-03-02 21:41 UTC
## Quick summary
RPCS3 does not run on Wayland. Switching to an X11 based desktop and running RPCS3 in that works just fine.

## Details
The tested games were Spyro DoTD and the basic cube and triangle renders.
Running a game in Wayland (Wayfire) does not work. Running it in OpenGL returns the following in terminal.
https://pastebin.com/qcv0t8qm
Running the game in Vulkan crashes EPCS3 and returns:
https://pastebin.com/nbLrqqzZ

#### 5. Please provide your system configuration:
* OS: ArchLinux
* CPU: Ryzen 3600
* GPU: Radeon 5700XT
* Driver version: amdgpu 19.10-2

[opengl-RPCS3.log](https://github.com/RPCS3/rpcs3/files/6071966/opengl-RPCS3.log)
[vulkan-RPCS3.log](https://github.com/RPCS3/rpcs3/files/6071967/vulkan-RPCS3.log)

**Comment by Kommynct** [comment] 2021-03-02 23:44
can confirm, works fine with QT_QPA_PLATFORM=xcb rpcs3

**Comment by LuxLucian** [comment] 2021-03-03 00:25
> can confirm, works fine with QT_QPA_PLATFORM=xcb rpcs3

This fixes the issue for me too. Thanks for the help.

**Comment by digitaldude555** [comment] 2021-03-03 13:16
close it. @LuxLucian

**Comment by Kommynct** [comment] 2021-03-03 19:32
Woah woah woah, my fix is a hacky workaround, it just forces use of xwayland, unless this issue was fixed with a commit that I missod

**Comment by MSuih** [comment] 2021-03-03 19:45
I agree, we should probably look into this a bit more.

**Comment by LuxLucian** [comment] 2021-03-03 20:26
Should I keep it open? Not sure what I should do atm.

**Comment by Kommynct** [comment] 2021-03-03 20:46
It's not fixed, leave it open.

**Comment by LuxLucian** [comment] 2021-03-03 22:35
Alright

**Comment by jenny-taila655** [comment] 2021-03-11 12:25
Can confirm this is an issue @here , @everyone I know that uses linux and RPCS3 has this problem.
Is there a known fix/workaround (besides not using wayland)?

**Comment by LuxLucian** [comment] 2021-03-14 01:07
> Can confirm this is an issue @here , @everyone I know that uses linux and RPCS3 has this problem.
> Is there a known fix/workaround (besides not using wayland)?

Running this line in the terminal from Kommynct should work.
QT_QPA_PLATFORM=xcb rpcs3

Launching rpcs3 with that command will run it in Xwayland, which is a good workaround for now. You can set up an alias or modify the .desktop to avoid having to type it every time.

**Comment by Kommynct** [comment] 2021-03-14 06:37
Slightly off topic but I do it with

QT_QPA_PLATFORM=xcb nohup rpcs3 & disown

If you want a way to do it in the terminal and still be able to close the terminal.

**Comment by jefferyrlc** [comment] 2021-03-18 10:50
[RPCS3.log](https://github.com/RPCS3/rpcs3/files/6163380/RPCS3.log)
 Terminal output
 /home/jeffery> rpcs3
Debugger: 0
Failed to set RLIMIT_MEMLOCK size to 2 GiB. Try to update your system configuration.
libpng warning: iCCP: known incorrect sRGB profile
libpng warning: iCCP: known incorrect sRGB profile
libpng warning: iCCP: known incorrect sRGB profile
libpng warning: iCCP: known incorrect sRGB profile
libpng warning: iCCP: known incorrect sRGB profile
libpng warning: iCCP: known incorrect sRGB profile
libpng warning: iCCP: known incorrect sRGB profile
libpng warning: iCCP: known incorrect sRGB profile
libpng warning: iCCP: known incorrect sRGB profile
libpng warning: iCCP: known incorrect sRGB profile
libpng warning: iCCP: known incorrect sRGB profile
libpng warning: iCCP: known incorrect sRGB profile
libpng warning: iCCP: known incorrect sRGB profile
libpng warning: iCCP: known incorrect sRGB profile
libpng warning: iCCP: known incorrect sRGB profile
libpng warning: iCCP: known incorrect sRGB profile
libpng warning: iCCP: known incorrect sRGB profile
libpng warning: iCCP: known incorrect sRGB profile
libpng warning: iCCP: known incorrect sRGB profile
libpng warning: iCCP: known incorrect sRGB profile
libpng warning: iCCP: known incorrect sRGB profile
libpng warning: iCCP: known incorrect sRGB profile
libpng warning: iCCP: known incorrect sRGB profile
libpng warning: iCCP: known incorrect sRGB profile
libpng warning: iCCP: known incorrect sRGB profile
libpng warning: iCCP: known incorrect sRGB profile
libpng warning: iCCP: known incorrect sRGB profile
libpng warning: iCCP: known incorrect sRGB profile
libpng warning: iCCP: known incorrect sRGB profile
libpng warning: iCCP: known incorrect sRGB profile
libpng warning: iCCP: known incorrect sRGB profile
libpng warning: iCCP: known incorrect sRGB profile
libpng warning: iCCP: known incorrect sRGB profile
libpng warning: iCCP: known incorrect sRGB profile
libpng warning: iCCP: known incorrect sRGB profile
libpng warning: iCCP: known incorrect sRGB profile
Icon theme "ubuntu-mono-dark" not found.
Icon theme "Mint-X" not found.
Icon theme "elementary" not found.
ioctl (GFEATURE): Input/output error
libpng warning: iCCP: known incorrect sRGB profile
libpng warning: iCCP: known incorrect sRGB profile
libpng warning: iCCP: known incorrect sRGB profile
libpng warning: iCCP: known incorrect sRGB profile
libpng warning: iCCP: known incorrect sRGB profile
libpng warning: iCCP: known incorrect sRGB profile
libpng warning: iCCP: known incorrect sRGB profile
libpng warning: iCCP: known incorrect sRGB profile
libpng warning: iCCP: known incorrect sRGB profile
libpng warning: iCCP: known incorrect sRGB profile
libpng warning: iCCP: known incorrect sRGB profile
libpng warning: iCCP: known incorrect sRGB profile
libpng warning: iCCP: known incorrect sRGB profile
libpng warning: iCCP: known incorrect sRGB profile
libpng warning: iCCP: known incorrect sRGB profile
libpng warning: iCCP: known incorrect sRGB profile
libpng warning: iCCP: known incorrect sRGB profile
libpng warning: iCCP: known incorrect sRGB profile
libpng warning: iCCP: known incorrect sRGB profile
libpng warning: iCCP: known incorrect sRGB profile
libpng warning: iCCP: known incorrect sRGB profile
libpng warning: iCCP: known incorrect sRGB profile
libpng warning: iCCP: known incorrect sRGB profile
libpng warning: iCCP: known incorrect sRGB profile
libpng warning: iCCP: known incorrect sRGB profile
libpng warning: iCCP: known incorrect sRGB profile
libpng warning: iCCP: known incorrect sRGB profile
libpng warning: iCCP: known incorrect sRGB profile
libpng warning: iCCP: known incorrect sRGB profile
libpng warning: iCCP: known incorrect sRGB profile
libpng warning: iCCP: known incorrect sRGB profile
libpng warning: iCCP: known incorrect sRGB profile
libpng warning: iCCP: known incorrect sRGB profile
libpng warning: iCCP: known incorrect sRGB profile
libpng warning: iCCP: known incorrect sRGB profile
libpng warning: iCCP: known incorrect sRGB profile
xdg_wm_base@28: error 3: xdg_surface must not have a buffer at creation
The Wayland connection experienced a fatal error: Protocol error

**Comment by bmwalters** [comment] 2021-03-26 04:10
Same issue but slightly different logs here. Running latest master 9f80a55

<details>

<summary>logs</summary>

```
$ QT_QPA_PLATFORM=wayland rpcs3
Debugger: 0
[ALSOFT] (EE) Failed to set real-time priority for thread: Operation not permitted (1)
libpng warning: iCCP: known incorrect sRGB profile
libpng warning: iCCP: known incorrect sRGB profile
libpng warning: iCCP: known incorrect sRGB profile
Thread '' terminated due to fatal error: Assertion Failed! Vulkan API call failed with unrecoverable error: Surface lost (VK_ERROR_SURFACE_LOST)
(in file /tmp/makepkg/rpcs3-git/src/rpcs3/rpcs3/Emu/RSX/VK/vkutils/instance.hpp:384, in function create_swapchain) (errno=32)
(in file /tmp/makepkg/rpcs3-git/src/rpcs3/rpcs3/Emu/RSX/VK/vkutils/shared.cpp:107, in function die_with_error) (errno=32)
RPCS3: Assertion Failed! Vulkan API call failed with unrecoverable error: Surface lost (VK_ERROR_SURFACE_LOST)
(in file /tmp/makepkg/rpcs3-git/src/rpcs3/rpcs3/Emu/RSX/VK/vkutils/instance.hpp:384, in function create_swapchain) (errno=32)
(in file /tmp/makepkg/rpcs3-git/src/rpcs3/rpcs3/Emu/RSX/VK/vkutils/shared.cpp:107, in function die_with_error) (errno=32)
Thread id = 139926548416384.
Found exec link: /usr/bin/rpcs3
Debugger: 0
Thread '' terminated due to fatal error: Segfault reading location 0000000000000000 at 00007fc057056225.
Thread: Main Thread.

RPCS3: Segfault reading location 0000000000000000 at 00007fc057056225.
Thread: Main Thread.
```

</details>

**Comment by escalade** [comment] 2021-03-30 15:43
Same issue with Sway (latest git), I believe it was broken some time after RPCS3 0.0.13.

**Comment by jroyvde** [comment] 2021-04-29 02:28
A recent commit seems to have fixed this! After updating my RPCS3 flatpak today I'm able to start games under Wayland.

My current version is 0.0.15-1-64a109d2 Alpha

**Comment by Kommynct** [comment] 2021-04-29 03:13
I still have the issue

rpcs3                                                                          (04-28 23:09)
Debugger: 0
Failed to set RLIMIT_MEMLOCK size to 2 GiB. Try to update your system configuration.
[ALSOFT] (EE) Failed to set real-time priority for thread: Operation not permitted (1)
libpng warning: iCCP: known incorrect sRGB profile
libpng warning: iCCP: known incorrect sRGB profile
libpng warning: iCCP: known incorrect sRGB profile
libpng warning: iCCP: known incorrect sRGB profile
xdg_wm_base@24: error 3: xdg_surface must not have a buffer at creation
The Wayland connection experienced a fatal error: Protocol error
┌[~][1]

**Comment by jroyvde** [comment] 2021-04-30 12:05
After another update to my RPCS3 flatpak installation, the problem has returned for me as well.

My version right now is 0.0.15-1-71d58e3a Alpha

**Comment by p01arst0rm** [comment] 2021-06-02 09:22
@jroyvde @Kommynct @escalade / any others can you please give PTRACE/STRACE dumps of the execution attempts under wayland? theres not really much information to go off with what you've provided so far.

can you also please provide:
GCC version
CMake version
Ninja version
LD version
LDD version
Wayland version & config
X11 version & config
Qt version

**Comment by Kommynct** [comment] 2021-06-03 21:25
gcc 11.1.0-1
cmake 3.20.3-1
ninja 1.10.2-1
LD and LDD don't appear in pacman for me
sway-git r6704.b9971472-1 -- happens with the default config
wlroots-git 0.13.0.r153.g9e58301d-1
xorg-xwayland 21.1.1-1
qt5-base 5.15.2+kde+r196-1

What would the command be to test ptrace? I can't seem to find the package on arch

here's an strace though:

[rpcs3-output.txt](https://github.com/RPCS3/rpcs3/files/6594438/rpcs3-output.txt)

**Comment by p01arst0rm** [comment] 2021-06-03 21:42
you can use gdb to generate a ptrace execution log ( helpful link: https://sourceware.org/gdb/current/onlinedocs/gdb/Process-Record-and-Replay.html)

could you also create a valgrind analysis log? would make it a lot easier to narrow down where/why its failing

**Comment by hcorion** [comment] 2021-06-03 21:49
The strace has a pretty simple explanation
```
write(2, "xdg_wm_base@24: error 3: xdg_sur"..., 72xdg_wm_base@24: error 3: xdg_surface must not have a buffer at creation
) = 72
write(2, "The Wayland connection experienc"..., 65The Wayland connection experienced a fatal error: Protocol error
) = 65
exit_group(1)                           = ?
+++ exited with 1 +++
```
apparently wlroots is more strict with protocol violations https://github.com/swaywm/sway/issues/1992#issuecomment-389516088. Not sure if this is caused by Qt code or our code though.

Other resources from a quick google 
https://github.com/glfw/glfw/issues/1268
https://github.com/kovidgoyal/kitty/issues/157#issuecomment-389516579

Seems like this error is caused by
> creating a xdg_surface with a wl_surface which already has a buffer attached, this is forbidden by the protocol.

**Comment by p01arst0rm** [comment] 2021-06-03 21:56
ah ok :) hadnt looked at it yet just wanted the other logs first

**Comment by escalade** [comment] 2021-08-09 11:01
@p01arst0rm

GCC: 11.2.0
wlroots: 88f65db
Sway: d0fe721
CMake: 3.19.3
ninja: 1.10.2
Qt: 5.15.2

Anything else I can do to help resolve this issue, please let me know. Big thanks to every RPCS3 developer for the time and effort spent on this amazing emulator, it's much appreciated.

**Comment by kd-11** [comment] 2021-08-21 17:55
This issue is fixed by https://github.com/RPCS3/rpcs3/pull/10739

**Closed** 2021-08-21 18:40 UTC
Labels: OS: Linux

**Comment by iMonZ** [comment] 2021-08-21 22:58
> This issue is fixed by #10739

I can confirm that this issue is fixed, except it created a new one.

X11:
![Screenshot from 2021-08-22 00-53-54](https://user-images.githubusercontent.com/11319871/130336791-a2dc26d4-f21f-4f5f-8964-45af54ac8901.png)

Wayland:
![Screenshot from 2021-08-22 00-54-38](https://user-images.githubusercontent.com/11319871/130336794-6fd279d2-a620-478d-835f-7d34d71574e8.png)

**Comment by kd-11** [comment] 2021-08-22 06:09
Works fine on kde for me though the main window (game list) sometimes is missing decorations at random. The wm session failing to draw window decorations is a thing with wayland, but this isnt something we can do much about on our side. Try a different DE or we can just wait for Qt to improve their eayland integration.

**Comment by jr1991-g** [comment] 2021-08-22 16:07
Seems fixed
![Captura de pantalla de 2021-08-22 13-05-08](https://user-images.githubusercontent.com/75588345/130362047-bea3e55f-ebb9-4aab-8a0d-68696c39014f.png)
