### ISSUE TITLE
[BCES00511] Ratchet and Clank: a crack in time frequent crashes on Torren IV

### ISSUE THREAD

**Issue by Radu13** [RPCS3/rpcs3#10765] opened 2021-08-25 17:18 UTC
I keep getting crashes on the planet Torren IV in 2 minutes or less, can't even reach the first checkpoint unfortunally!
It seems to be related to the glitched RSX stuff like some far away tornados in the background for example.
![image](https://user-images.githubusercontent.com/25487544/130832809-99c29d82-72f5-4f7b-8fc3-0ff1cf37d329.png)
![image](https://user-images.githubusercontent.com/25487544/130836527-1d00af85-9b4a-4dc3-9424-fbb05fffd9f1.png)

I consistently get one of those 2 log errors:
![image](https://user-images.githubusercontent.com/25487544/130833024-349f8b2d-98fa-4cc7-8462-b0a6ba4a3401.png)
![image](https://user-images.githubusercontent.com/25487544/130834825-fe3b3dd9-f011-4cae-8304-11b2ed7998f4.png)

My log file is attached as well, hopefully all this can help figure out what's wrong with this specific planet!
[RPCS3.log](https://github.com/RPCS3/rpcs3/files/7048704/RPCS3.log)

**Comment by dragonDScript** [comment] 2021-09-08 22:45
I can't reproduce. Already on Lumos! Please enable "read color buffers" and don't jump over those electrical barriers, as it can cause performance issues. Good luck!

**Comment by RainbowCookie32** [comment] 2021-10-22 00:22
Enable Read Color Buffers to fix that. Use [our Discord server](https://discord.me/RPCS3) for support instead of commenting on random issues next time please

**Comment by JimScript** [comment] 2021-11-27 17:43
Is this issue tracking the rsx glitching or the crashing?

**Comment by dragonDScript** [comment] 2021-11-27 17:49
> Is this issue tracking the rsx glitching or the crashing?

The title says crashes

**Comment by JimScript** [comment] 2021-11-27 18:40
Right, sorry, it is just there is a lot of RSX talk in this issue. I have made an issue to track the RSX glitching then. #11205

**Comment by nitroos-ai** [comment] 2021-11-27 20:13
Remove the "Write Depth Buffer", "Read Depth Buffer", "Accurate RSX reservation access", "Strict Rendering Mode", "SPU loop detection" and "Disable Vertex Cache".

Set PPU Decoder and SPU Decoder to LLVM and "Max SPURS Threads: 5".

Or just use my Config [config_BCES00511.zip](https://github.com/RPCS3/rpcs3/files/7612375/config_BCES00511.zip)

**Comment by Megamouse** [comment] 2021-12-15 21:38
closing, as there's some patch applied.
Patches are not officially supported and don't belong in any issues.

**Closed by Megamouse** 2021-12-15 21:38 UTC
Labels: Need Information, Potato
