### ISSUE TITLE
Uncharted 3 (specific) RSX error

### ISSUE THREAD

**Issue by Alessioc3l** [RPCS3/rpcs3#9501] opened 2020-12-26 03:20 UTC
## Quick summary:
Hello,
due to an weird issue i can't continue the uncharted 3 main story. If i go to this log (which i need to) and press triangle the game will just crash with this weird RSX error. I tried fixing it by going through the settings but nothing worked.
![RPCS3 uncharted](https://user-images.githubusercontent.com/69675939/103144879-37332380-4731-11eb-876d-559bfc5f070d.png)
![RSX_error](https://user-images.githubusercontent.com/69675939/103144884-4b772080-4731-11eb-945c-85d9686308ae.png)

#### RPCS3's log:
[RPCS3.zip](https://github.com/RPCS3/rpcs3/files/5742635/RPCS3.zip)

#### RSX capture:
[BCES01175_20201226041425_capture.zip](https://github.com/RPCS3/rpcs3/files/5742636/BCES01175_20201226041425_capture.zip)

**Comment by RainbowCookie32** [comment] 2020-12-26 04:04
Duplicate of #9474

**Closed** 2020-12-26 04:10 UTC
Labels: Meta: Duplicate
