### ISSUE TITLE
Same error in many Call of Duty games - Access Violation error

### ISSUE THREAD

**Issue by Josivan88** [RPCS3/rpcs3#5940] opened 2019-05-09 01:31 UTC
The same crash occurs in many call of duty games after 0.0.6-8085 from @elad335 
mainly on coop/split screen modes, fixing it will remain basically framerate issue to make Call of duty series playable.
COD World at war [BLUS30192]:
![Call of duty WaW](https://user-images.githubusercontent.com/36341425/57420687-0eb68880-71df-11e9-93c2-c0a5d382b39a.jpg)
COD Modern Warfare [BLES00148]:
![Call of duty MW](https://user-images.githubusercontent.com/36341425/57420859-d1062f80-71df-11e9-8fb8-b71df5049a2e.jpg)
RPCS3 Version:
0.0.6-8085
Game crash after a few seconds
Computer:
Core i7 4790
16Gb of RAM
Nvidia GTX 1070
With same error:
F {RSX [0x217b23c]} RSX: class std::runtime_error thrown: Unknown blend eq 0x0
(in file c:\projects\rpcs3\rpcs3\emu\rsx\gcm_enums.cpp:734)
World at war Log:
[RPCS3.log.gz](https://github.com/RPCS3/rpcs3/files/3159861/RPCS3.log.gz)
Modern warfare log:
[RPCS3.log.gz](https://github.com/RPCS3/rpcs3/files/3159887/RPCS3.log.gz)

**Comment by elad335** [comment] 2019-05-09 03:48
thats a duplicate of #3357.

**Closed** 2019-05-09 03:48 UTC
