### ISSUE TITLE
Emulator doesn't open after pull #8399

### ISSUE THREAD

**Issue by EddyHg80** [RPCS3/rpcs3#8560] opened 2020-07-06 21:44 UTC
Ok so I updated today after a while and the emulator didn't open after the process.

An older version worked for me so I found, after several version downloaded, that my problem started with rpcs3-v0.0.10-10479-1668900f, so after the pull #8399.

Since not a lot of people are talking about this I think it's a problem on my end, what should I do?

**Comment by Megamouse** [comment] 2020-07-06 21:46
Duplicate of #8409

**Closed by Megamouse** 2020-07-06 21:46 UTC
