### ISSUE TITLE
Fist of the North Star: Ken’s Rage 2 [BLES01801] .. RPCS3 LOG (reporting developer)

### ISSUE THREAD

**Issue by Augusto7743** [RPCS3/rpcs3#6913] opened 2019-10-29 06:48 UTC
Trying start that game in LOG status was displayed an message to report developer.
Here is the log.
Have a nice day.

**Comment by Augusto7743** [comment] 2019-10-29 07:21
Not is being possible upload the log file directly in github.
Below direct link in mega.
Thanks for read my post.
https://mega.nz/#!UFlCEIBK!iuQJRfCqoK4hFOt2A6msxC96WseFeC5qGvwxPc4adHU

**Comment by RainbowCookie32** [comment] 2019-10-29 16:48
If you mean the `SPU TODO: Special branch patchpoint hit.
Please report to the developer (0x03618).` then this issue is a duplicate of #6905.

Close the issue and comment on that one if that's the case

**Comment by Augusto7743** [comment] 2019-10-30 06:00
Thanks very much for your reply.
Have a nice day.

**Closed** 2019-10-30 06:00 UTC
