### ISSUE TITLE
Minecraft: PS3 Edition crashes while creating a world or when trying to play the tutorial world

### ISSUE THREAD

**Issue by Mario3264** [RPCS3/rpcs3#4583] opened 2018-05-15 03:19 UTC
These are the lines of code listed within the Log which I think pertain to this issue:

`U {PPU[0x1000018] Thread ((4J) Post processing) [0x00c64864]} HLE TODO: Unimplemented syscall syscall_988 -> CELL_OK`

`U {PPU[0x1000018] Thread ((4J) Post processing) [0x00c647d0]} HLE TODO: Unimplemented syscall syscall_988 -> CELL_OK`

`S sys_process: Process finished`

`E {PPU[0x1000000] Thread (main_thread) [0x002b7e44]} Stat: 'sys_fs_stat' failed with 0x80010006 : CELL_ENOENT, “/dev_hdd0/game/NPUB31419/USRDIR/Common/res/TitleUpdate/res/textures/items/clockMipMapLevel2.png” [x5]`

`E {PPU[0x1000000] Thread (main_thread) [0x002b7e44]} Stat: 'sys_fs_stat' failed with 0x80010006 : CELL_ENOENT, “/dev_hdd0/game/NPUB31419/USRDIR/Common/res/TitleUpdate/res/textures/items/compassMipMapLevel2.png” [x5]`

Details about my computer:
OS: Windows 10 Professional (Build 17134)
CPU: Intel Core i3-4160 at 3.60GHz
GPU: Intel HD Graphics 4400

Log: [RPCS3.log](https://github.com/RPCS3/rpcs3/files/2003346/RPCS3.log)

**Comment by hcorion** [comment] 2018-05-15 03:49
Duplicate of #3627

**Closed** 2018-05-15 04:18 UTC
