### ISSUE TITLE
 VK:IDOLM@STER OFA graphics issue

### ISSUE THREAD

**Issue by RainKikyou** [RPCS3/rpcs3#5890] opened 2019-04-28 06:12 UTC
Most people have this glitch problem .Strangely，I have a PC ’s graphics is correct，but another pc is wrong，too.
![123](https://user-images.githubusercontent.com/20301499/56859532-f9f81a80-69be-11e9-9b3d-7fa77431748c.png)
![124](https://user-images.githubusercontent.com/20301499/56859534-fc5a7480-69be-11e9-83e3-4d3b942b4cf1.png)

rdc
https://drive.google.com/open?id=1OddSWR3htR2jM2iQpcQza9iOSTLjJ42h

**Comment by rikimtasu** [comment] 2019-05-14 14:35
Same issue here with AMD graphic card.
RX 470 19.4.3

here the log attached.
[RPCS3.log](https://github.com/RPCS3/rpcs3/files/3178281/RPCS3.log)

**Comment by kd-11** [comment] 2019-05-14 14:43
Unrelated issue - the original is about border lines being visible; this one is about partial framebuffer inheritance. See https://github.com/RPCS3/rpcs3/pull/5937

**Comment by kd-11** [comment] 2019-08-19 22:41
@RainKikyou Which GPU was working and which one was not? Could have been a simple driver issue that has been fixed by now.

**Comment by zalghornain** [comment] 2020-04-13 11:48
currently on master
![image](https://user-images.githubusercontent.com/51984674/79114826-79d4eb80-7dae-11ea-8a2e-d477c8cd76fc.png)
with WDB  (WDB makes the game crash in openGL) 
![image](https://user-images.githubusercontent.com/51984674/79114932-c4566800-7dae-11ea-9ef5-93807e01f366.png)
the strange things (in my setup at least), with WDB on, if you alt+enter (go to fullscreen) while the white bar displayed, it will be gone for the rest of your play (doesnt matter if you go back windowed or playing fullscren after)
![image](https://user-images.githubusercontent.com/51984674/79115188-6413f600-7daf-11ea-9a61-2ab68eed73fe.png)

while the visual glitch displayed, the log spammed with
E {RSX [0x0131adc]} RSX: Transfer cropped in X, src_w=1024, offset_x=2, block_w=1024
E {RSX [0x0131b2c]} RSX: Transfer cropped in Y, src_h=1024, offset_y=2, block_h=1024

log :
[RPCS3.log.gz](https://github.com/RPCS3/rpcs3/files/4469247/RPCS3.log.gz)

**Comment by kd-11** [comment] 2020-04-13 20:00
Seems the game is using large wrap offsets. I never really figured out why developers were doing it, if I can figure out the real reason to use offsets like 1 or 2 when the intention is to actually ignore the offset then I can easily fix the bar issue. Or more importantly - is PS3 doing texel wrapping? This is possible and would just make everyone's life harder. You can also check if using CPU blit + WCB + WDB makes the bar go away.

**Comment by zalghornain** [comment] 2020-04-13 23:43
yep, CPU blit + WCB + WDB makes it gone, the log spam seems to disappear too.

**Comment by OmnomP** [comment] 2020-04-24 02:11
I did WCB + WDB and the issue is gone about the blurry bars but now, the dancing animations lag during close up and body angles and it drastically lowers the FPS from 60 yto 40, but on long cam, it goes back to normal

**Comment by kd-11** [comment] 2020-05-22 18:33
I need more information how to reproduce this bug. Keep in mind that I cannot understand any text in the game when giving instructions. Following steps that caused crashes before shows nothing, while I can see the transfer crop messages, they are happening when loading which is not alarming. Ingame seems fine:
![image](https://user-images.githubusercontent.com/15904127/82698597-bdefc180-9c73-11ea-948a-d7cefaeceaf2.png)

**Comment by zalghornain** [comment] 2020-05-23 03:22
if i remember right, i believe there's one time when using LLVM SPU crashes the game (i believe its not an issue anymore (?) audio still broken on that setting though)

that's weird, the bug and log spam appear just like that if i played stage mode here
first change enter button assignment to enter with circle (enter with cross makes the games bugged, sometimes x detected as confirmation but another time detected as cancel, but that's a different issue altogether)
to reproduce choose S4U! (the second one from the left), after that choose whatever card. now the stage setting will be displayed, in here, choose the second option from above to change unit (ユニット編集), after that press R1/L1 to reduce/increase unit (i forgot to said that the issue only appears for 3 man live or less), press X to back and then press rectangle to start the stage, there will be confirmation prompt that ask if you fine with this setting, choose the left one for yes (はい) 
when the stage played, press up arrow to change to close-up camera, left arrow to change to mid camera, right to auto camera and bottom to long camera (the glitch and log spam only appear at close and mid camera)
press start to exit stage, and choose the left one for yes

**Comment by kd-11** [comment] 2020-05-23 17:05
Should be fixed by https://github.com/RPCS3/rpcs3/pull/8281

**Comment by zalghornain** [comment] 2020-05-23 20:37
yep, confirmed fixed here

**Closed** 2020-05-24 08:31 UTC
Labels: Bug, Need Information, RSX
